


[core]
name: 创世纪钻井平台t2
displayText: Буровая платформа Генезисаt2
displayDescription: 【Уровень t2】【Здание】【Наземный юнит】\n-Тактическое назначение: ресурсное здание, без вооружения.\n-важнейшее и распространённое горнодобывающее здание，\n-вся армия Генезиса не может функционировать без ресурсов, которые оно обеспечивает。
class: CustomUnitMetadata
price: 2000
maxHp: 3000
generation_credits: 25
generation_delay: 40
techLevel: 1
buildSpeed: 8s
radius: 28
isBio: false
isBuilding: true
placeOnlyOnResPool: true
numBitsOnDeath: 10
tags: 地面,建筑,寄生免疫
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆破*4,largeExplosion
armour: 5
copyFrom: ROOT:/通用特效/单位防护.ini

[decal_地板]
image: ROOT:/创世纪军事集团/建筑特效/地.png
total_frames: 1
layer: shadow
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
imageScale: 0.8
alpha:1
[decal_影子]
image: SHADOW:矿.png
total_frames: 1
layer: shadow
yOffsetRelative:40
xOffsetRelative:3
onlyWhileAlive:true
isVisible:true
imageScale: 0.8
alpha:0.5
[decal_泵]
image: ROOT:/创世纪军事集团/建筑特效/钻头.png
total_frames: 4
frame: (self.customTimer * 14) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-2
yOffsetRelative:3.5
layer: onTop
onlyWhileAlive:true
imageScale: 0.8
[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:40
xOffsetRelative:-0.7
onlyWhileAlive:true
isVisible:if self.hp<self.maxHp * 0.36
teamColors: true
imageScale: 0.8
[action_炉增益]
autoTrigger:if self.globalTeamTags(includes='同步轨道加速器')
isVisible: false
addResources:40

[action_升级]
convertTo: 创世纪钻井平台t3
displayType: action
text: 升класс
buildSpeed: 20s
price: 2500

description:повышаетБуровая платформауровень，加固其结构强度иувеличивает产出。\n-升классиспользоватьсамый新的合金钻头，одновременно全面升класс钻井的材质，\n-повышаетБуровая платформа的血量，иувеличивает其收入。
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня
ai_isHighPriority: true
[graphics]
total_frames: 1
image: 矿.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/死了.png
image_back: ROOT:/通用特效/NO.png
imageScale: 0.8
image_shadow: NONE
image_offsetY: -40
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 30
maxAttackRange: 99999
shootDelay: 0


[turret_火焰]
x: -24
y: 45
projectile: 13
shoot_flame: CUSTOM:烟雾1
delay: 20
invisible: true
size: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[effect_烟雾1]
createWhenZoomedOut: false
stripIndex: effects
frameIndex: 0
life: 300
fadeOut: true
priority: verylow
attachedToUnit: false
color: #646464
fadeInTime: 15
scaleFrom: 0.65
scaleTo: 4

alpha: 1
drawUnderUnits: false
hSpeed: 0.6
xSpeedAbsolute: -0.2
hOffsetRandom: 0.15

yOffsetRelative: -2
dirOffsetRandom: 180
shadow: false
xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1
atmospheric: true

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
delayedStartTimerRandom:30


[ai]
buildPriority: 1
maxEachBase: 500
maxGlobal: 500


