


[core]
name: 操纵者
displayText: Манипулятор
price: 1100
maxHp: 2650
displayDescription:【Уровень t4】【Преодолевает утёсы】【Биологический юнит】【Наземный юнит】Тактическое назначение:высокийклассуниверсальный пехота，размер юнита:3\n-вооружение：▲链пушкаX1 по земле и воздуху кинетический уронипробивает укрытия \n-ввойнаконецсГенезистехнология развиваться，одинмодельистинныйправильныйзрелыймех изобретать выходит，\n-相比вдругиереальный验тип мех，Манипуляторещё болеепростойуниверсальный，одновременно体积меньше，\n-егооснащённый тяжёлыйштурмовая винтовкаможетещё болееэффективныйуничтожатьЗарево бронявойскавплоть доистребитель，\n-свойна развиваться，отМанипуляторидругиемех构становиться бронетанковая дивизияколичество，уже逐渐превышаеттрадиционныйтанк师，\n-Манипуляторидругиемехиспользоватьреальныйсила证明 новый兴 мехтехнологиядостаточно длявна поле боя独когдаодинповерхность。
techLevel: 1
fogOfWarSightRange: 18
buildSpeed: 8s
radius: 27
displayRadius: 27
armour: 6
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md,ROOT:/通用特效/扎针.md

isUnrepairableUnit:true
transportSlotsNeeded: 3
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,操纵者,步兵,驻扎要塞
energyMax: 4
energyRegen: 0

energyNeedsToRechargeToFull: true
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 操纵者
[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: Мина «Кошмар»1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3') 

#———科技—————
[action_轻型掩体]
text: лёгкое укрытие
isVisible: if self.globalTeamTags(includes='外骨骼')
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/轻型掩体.png
description: одиннаходитьсялёгкое укрытие，можетв качестверядомпехота140в радиусе биологический юнитобеспечиваетлёгкое прикрытие。\n-лёгкое прикрытиеможетв качествебиологический юнитснижает на50% 伤害，\n-но，укрытиене можетснижает начастьскорострельный，激свет，Огонь，Электричествоудар，втип，самоподрыв，ближний бой，衰解и т.д.другиеигнорироватьукрытие оружие。
[action_加掩体]
autoTrigger: if self.globalTeamTags(includes='外骨骼')and not self.tags(includes= '轻型掩体') and not self.hasParent
isVisible:false
temporarilyAddTags:轻型掩体

[hiddenAction_减掩体]
autoTrigger:if self.hasParent and self.tags(includes= '轻型掩体')
isVisible:false
temporarilyRemoveTags:轻型掩体




[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[action_tx1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[action_电磁炮2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道2.png
text: орбитальныйпусковая установка2
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器2')
[action_温压弹1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/温压弹.png
text: Объёмно-детонирующая бомба1
isActive: false
isVisible: if self.globalTeamTags(includes='温压弹1')

[action_冲击飞弹]
fireTurretXAtGround: 飞弹
text: Запустить ударную ракету
displayType: action
buildSpeed: 0s
pos: 0.1

#displayRemainingStockpile: true
#highPriorityQueue: true
price: 0
canPlayerCancel: false
addActionCooldownTime: 16s

onlyOneUnitAtATime: false
description: запускатьодна针противтяжёлыйназемный юнита такжездание 灌顶飞снаряд，\n-противцельв врагнаноситсамыйвысокий1500пунктвзрывной урон。


[action_换弹1]
#autoTrigger: if self.energy(empty=true) and self.queueSize < 0.5
#temporarilyAddTags: 换弹
isVisible: false
#alsoQueueAction: 换弹
#spawnEffects: CUSTOM:弹匣


[action_换弹]
isVisible: false
#buildSpeed: 0.46s
#alsoQueueAction: bx


[action_bx]
#displayType: action
#price: 0
#buildSpeed: 1s
isVisible: false
#whenBuilding_cannotMove: false
#highPriorityQueue: true
#whenBuilding_playAnimation: 换弹
#addEnergy: 40
temporarilyRemoveTags: 换弹
[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 410 | setFlag= 0)
[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5)
isVisible: false
alsoQueueAction: b
[action_b]
convertTo: 操纵者1
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed




[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 410 | setFlag= 0-1)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true




[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
imageScale: 0.85


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 310
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_飞弹]
x: 19
y: -4
canShoot: false
idleDir: 0
invisible: true

size: 1.1
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:烟雾4*8

projectile: 2
delay: 0

altProjectile: 炮弹w
altProjectileCondition: if self.globalTeamTags(includes='温压弹1')

[turret_1]
x: 0
y: 0
canShoot: false
#image:身体.png
invisible: true


[projectile_2]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.7

image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1


[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 1000
areaRadius: 70
life: 200
speed: 7

color: #FFFFFF73
targetSpeed: 12
drawSize: 2.5
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波

targetGround: true
areaRadiusFromEdge: true
trailEffect: true
lightSize: 1.5
lightColor: #FFFFFF73

[projectile_炮弹w]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.7
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80
ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定w
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1

[projectile_锁定w]
@copyFromSection: template_爆炸
areaDamage: 120
areaRadius: 70
life: 200
speed: 7
color: #FFFFFF73
targetSpeed: 12
drawSize: 2.5
explodeEffect: CUSTOM:烟雾wy*12
explodeEffectOnShield: CUSTOM:烟雾wy*12
targetGround: true
areaRadiusFromEdge: true
trailEffect: true
lightSize: 1.5
lightColor: #FFFFFF73
spawnProjectilesOnExplode: wy
[projectile_wy]
@copyFromSection: template_爆炸
areaDamage: 1400
areaRadius: 90
areaDamageNoFalloff: true
areaRadiusFromEdge: true
life: 0
invisible: true
delayedStartTimer: 1.5s
speed: 0
turnSpeed: 0.0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.3
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 2
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.6
mutator7_areaDamageMultiplier: 0.6
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=10
explodeEffect: CUSTOM:闪光wy2*2,CUSTOM:火光wy,CUSTOM:冲击波wy,CUSTOM:闪光wy1,CUSTOM:巨大冲击波wy,CUSTOM:闪光wy*1,CUSTOM:实验wy,CUSTOM:火星wy*4,CUSTOM:随机爆炸wy*4
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false

atmospheric: false


[effect_冲击波]
life: 110
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false

scaleFrom: 1.4
scaleTo: 2.8
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2

createWhenOverLiquid: false
createWhenOverLand: true


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.3

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10


[effect_烟雾4]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 100
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.3
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true

#————————温压弹
[effect_烟雾wy]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 200
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 4.5
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
xOffsetRelativeRandom:40
yOffsetRelativeRandom:40
delayedStartTimerRandom:10
atmospheric: true
[effect_火光wy]
priority: critical
image: ROOT:/通用特效/火光.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 5
scaleTo: 5
alwayStartDirAtZero: true
color: #FFFF5B18
alpha: 0.9
drawUnderUnits: false
atmospheric: false
[effect_冲击波wy]
stripIndex: shockwave
life: 80
scaleFrom: 1
scaleTo: 7
alpha: 1
[effect_闪光wy]
image: SHARED:light_50.png
life: 250
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 1.5
scaleTo: 1.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound: ROOT:/通用特效/火球发射.ogg
[effect_闪光wy1]
image: SHARED:light_50.png
life: 180
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
[effect_巨大冲击波wy]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 2.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
color: #FFFF5B18
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_实验wy]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.8
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[effect_闪光wy2]
image: SHARED:light_50.png
life: 280
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFF86
priority: critical
fadeInTime: 2
scaleFrom: 2.8
scaleTo: 2.8
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 150
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.8
scaleTo: 2.2
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:65
yOffsetRelativeRandom:65
[effect_随机爆炸wy]
life: 100
priority: high
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:55
yOffsetRelativeRandom:55
delayedStartTimerRandom:20
[arm_1]
x: -9
y: 0
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: -30

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_2]
x: 10
y: -8
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 35
image_end_shadow: SHADOW:胳膊.png


[arm_3]
x: -17
y: 17
image_end: 左手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 35
image_end_shadow: SHADOW:左手.png


[arm_4]
x: 20
y: 8
image_end: 右手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -45
image_end_shadow: SHADOW:右手.png


[arm_5]
x: 12
y: 17
image_end: 弹匣.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -53


[arm_6]
x: 12
y: 17
image_end: 枪.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.globalTeamTags(includes='轨道发射器2')
drawDirOffset: -53

[arm_7]
x: 12
y: 17
image_end: 电磁枪.png
image_end_teamColors: true
drawOverBody: true
hidden:if not self.globalTeamTags(includes='轨道发射器2')
drawDirOffset: -53
[arm_8]
#左肩
x: 0
y: 15
image_end: 头.png
image_end_teamColors: true

drawOverBody: true
#image_end_shadow:SHADOW:损坏.png


[arm_9]
#左肩
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true

drawOverBody: true
#image_end_shadow:SHADOW:损坏.png
hidden: if self.maxHp * 0.36 < self.hp


[arm_10]
#左肩
x: 0
y: 0
image_end: 身体.png
image_end_teamColors: true

hidden: if self.maxHp * 0.36 > self.hp
drawOverBody: true
image_end_shadow: SHADOW:身体.png


[leg_1]
x: -9
y: 4
attach_x: -1
attach_y: 0
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 17

holdDisMax: 35
hardLimit: 60


[leg_2]
x: 9
y: 4
attach_x: 1
attach_y: 0
copyFrom: 1

drawDirOffset: 10


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}

arm1_0.6s: {x:-1, y:5, dir:30}
arm2_0.6s: {x:-6, y:0, dir:10}
arm3_0.6s: {x:10, y:5, dir:10}
arm4_0.6s: {x:-3, y:-3, dir:15}
arm5_0.6s: {x:-6, y:-3, dir:53}
arm6_0.6s: {x:-6, y:-3, dir:53}
arm7_0.6s: {x:-6, y:-3, dir:53}
arm8_0.6s: {x:4, y:-1, dir:0}
arm9_0.6s: {x:0, y:0, dir:15}
arm10_0.6s: {x:0, y:0, dir:15}


[movement]
movementType: OVER_CLIFF
moveSpeed: 1.45
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

turnAcceleration: 0.08
targetHeight: 4
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0

slowDeathFall: true


