


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=118


[core]
name: SDD血星
displayText: SDD Кровавая Звезда
class: CustomUnitMetadata
displayDescription: -Кровавая Звездаэто тип мощный торпедабомбардировкамашина, они чтобы против военный корабльуничтожение урон, а мчатьсяимя, \n-Кровавая Звездаоснащёндвадверьимпульсный лазерЗапустить устройство,  и дваштмощьне младшийк ядроснаряд осадаторпеда, \n-Этот стандартторпедабомбардировкамашинакогда-то проходитьэто Аравелидская республикаполётматьредактироватьотряд основная силамашинавидсреди .\n-в антисопротивлениеАравелидтирания (период), Кровавая Звездабитьтонуть кораблькорабльне расчётего количество.\n-Этот может превосходстворазный, ценаобъединениесчитать бомбардировкамашиначертёжЗаревоместонаследие, \n-например сейчаспо-прежнемугордость на службек ЗаревооченьВВСпалубный самолётсоединениеотряд.\n-только по земле, торпедавзрыв, пулемётможет источник.\n-Тип проекта:Империя Нова основакаменьрасчётразрезданные
price: 4000,蓝晶=190
maxHp: 2500

techLevel: 1
buildSpeed: 23s
availableInDemo: true
radius: 44
displayRadius: 44
fogOfWarSightRange: 23
isBio: false
maxShield: 2500
shieldRegen: 0.07
softCollisionOnAll: 10
shieldRenderRadius: 50

energyMax: 6
copyFrom: ROOT:/通用特效/单位防护.ini
energyRegen: 0.0055
energyNeedsToRechargeToFull: true
armour: 18

tags: 飞机,低空,无人单位

[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_反物质2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/反物质2.png
text: Антиматериальное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='反物质2')
[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
movementEffect: CUSTOM:火

movementEffectRate: 1.4
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9

animation_moving_start: 2
animation_moving_end: 2
animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1

animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 400
shootDelay: 1
attackMovement: bomber
disablePassiveTargeting: false


[turret_1]
x: 27
y: 23
image: 枪.png
turnSpeed: 0
recoilOffset: -2

canShoot: false


[turret_2]
x: -27
y: 23
image: 枪.png
turnSpeed: 0
recoilOffset: -2

canShoot: false


[turret_3]
x: -3
y: -11
projectile: 1
delay: 10
invisible: true

shoot_light: #FF00B3FF
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
recoilOffset: -2
attachedTo: 1

limitingAngle: 15


[turret_4]
x: 3
y: -11
projectile: 1
delay: 10
shoot_light: #FF00B3FF

shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
attachedTo: 2
limitingAngle: 15
invisible: true


[turret_5]
x: 19
y: 4
image: 炮.png
turnSpeed: 0
invisible: if self.energy(LessThan=6)

canShoot: false


[turret_6]
x: -19
y: 4
image: 炮.png
turnSpeed: 0
canShoot: false

invisible: if self.energy(LessThan=3)


[turret_17]
x: 19
y: 4
projectile: 2
delay: 10
shoot_light: #FF00B3FF

shoot_sound: ROOT:/余辉军团/单位特效/鱼雷.ogg
shoot_sound_vol: 0.3
limitingAngle: 25
invisible: true
limitingRange: 320

energyUsage: 3
canAttackCondition: if self.flying
altProjectile: 炮弹2
altProjectileCondition: if self.globalTeamTags(includes='反物质2')

[turret_18]
x: -19
y: 4
projectile: 2
delay: 10
shoot_light: #FF00B3FF

shoot_sound: ROOT:/余辉军团/单位特效/鱼雷.ogg
shoot_sound_vol: 0.3
limitingAngle: 25
invisible: true
energyUsage: 3

limitingRange: 320
canAttackCondition: if self.flying
altProjectile: 炮弹2
altProjectileCondition: if self.globalTeamTags(includes='反物质2')

[projectile_1]
@copyFromSection: template_能源
directDamage: 20
life: 200
speed: 10
image: ROOT:/余辉军团/单位特效/星星.png

targetSpeed: 10
drawSize: 0.45
explodeEffect: CUSTOM:爆炸
explodeEffectOnShield: CUSTOM:爆炸
lightSize: 0.75

lightColor: #FF00B3FF


[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 2000
areaRadius: 70
life: 240
speed: 5

deflectionPower: -1
lightSize: 1.5
lightColor: #FF39FFFF
drawSize: 0.85
targetSpeed: 9

disableLeadTargeting: true
image: ROOT:/余辉军团/单位特效/鱼雷.png
explodeEffect: CUSTOM:大爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:大爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:弹坑
areaRadiusFromEdge: true

targetGround: true
targetGroundSpread: 70

[projectile_炮弹2]
@copyFromSection: template_能源
areaDamage: 3250
areaRadius: 90
life: 240
speed: 5

deflectionPower: -1
lightSize: 1.5
lightColor: #FF39FFFF
drawSize: 0.85
targetSpeed: 5

disableLeadTargeting: true
image: ROOT:/余辉军团/单位特效/鱼雷.png
areaRadiusFromEdge: true
targetGround: true
targetGroundSpread: 70

explodeEffect: CUSTOM:闪光h,CUSTOM:光球,CUSTOM:光球2,CUSTOM:云雾,CUSTOM:云雾2,CUSTOM:云雾1,CUSTOM:聚变x,CUSTOM:冲击波1,CUSTOM:弹坑1


[effect_光球]
life: 250
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1

image: ROOT:/余辉军团/单位特效/收缩1.png
ySpeedAbsolute: -0.7
yOffsetAbsolute: 35
fadeOut: true
alpha: 1

alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg


[effect_光球2]
life: 250
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.7

image: 光球.png
ySpeedAbsolute: -0.7
#drawUnderUnits:true
yOffsetAbsolute: 35
fadeOut: true

alpha: 1
fadeInTime: 1


[effect_云雾]
life: 260
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.45

image: 云雾.png
ySpeedAbsolute: -0.9
yOffsetAbsolute: 90
fadeOut: true
alpha: 1

fadeInTime: 1


[effect_云雾2]
life: 260
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.4

image: 云雾.png
ySpeedAbsolute: -0.8
yOffsetAbsolute: 90
fadeOut: true
alpha: 1

fadeInTime: 1


[effect_云雾1]
life: 260
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.5

image: 云雾.png
ySpeedAbsolute: -0.7
yOffsetAbsolute: 90
fadeOut: true
alpha: 1

fadeInTime: 1


[effect_闪光h]
priority: critical
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FFE56BFF
fadeInTime: 2
scaleFrom: 10
scaleTo: 10

drawUnderUnits: false
atmospheric: false


[effect_聚变x]
priority: critical
image: ROOT:/余辉军团/单位特效/光束1.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 3
scaleTo: 3
alpha: 0.4
drawUnderUnits: false
atmospheric: false

ySpeedAbsolute: -1
yOffsetAbsolute: 35




[effect_冲击波1]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波4.png
life: 200
fadeOut: true
attachedToUnit: false

scaleFrom: 2
scaleTo: 6
alpha: 1
drawUnderUnits: true
atmospheric: false

yOffsetAbsolute: 90


[effect_弹坑1]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 400
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 5
scaleTo: 5
createWhenOverLiquid: false
createWhenOverLand: true
yOffsetAbsolute: 35

[effect_爆炸]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.4
image: ROOT:/余辉军团/单位特效/碎裂.png
total_frames: 8

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -46


[effect_大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: .75

image: ROOT:/余辉军团/单位特效/巨大爆炸.png
total_frames: 15
animateFrameStart: 0
animateFrameEnd: 15
alpha: 1.5

animateFramePingPong: false
animateFrameSpeed: 0.2
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
alwayStartDirAtZero: true


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true


[effect_冲击波]
life: 130
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 2.1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

drawUnderUnits: true
animateFrameSpeed: 0.18
alwayStartDirAtZero: true


[arm_1]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true


[movement]
movementType: AIR
moveSpeed: 2.2
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.007
#landOnGround: onlyIdle

joinsGroupFormations: false
maxTurnSpeed: 2.2
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false

slowDeathFall: true
targetHeight: 70
startingHeightOffset: 1000


