


[core]
name: 太空浪人钻探机t1传送
class: CustomUnitMetadata
displayDescription: 基本的矿业设施，\n-供给太空浪人军队需要。\n-自我供能，无需供电。
price: 800
maxHp: 600

techLevel: 1
buildSpeed: 0s
isBio: false
placeOnlyOnResPool: true
isBuilding: true

numBitsOnDeath: 0
radius: 35
tags: 地面,建筑,寄生免疫
energyMax: 15
energyRegen: 0
selfBuildRate: 10
energyNeedsToRechargeToFull: true
generation_resources: energy= ${ core.energyMax / -3 / 8 }
# 40是传送时间
generation_active: true
generation_delay: 20


[action_取消]
text: 取消建造
addResources: credits= ${core.price}
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false

deleteSelf: true


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_转换]
convertTo: 太空浪人钻探机t1
autoTrigger: if self.energy(LessThan=1)
isVisible: false
spawnEffects: CUSTOM:闪光,CUSTOM:底色,CUSTOM:冲击波2


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.6


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.3
scaleTo: 0.45
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.65
scaleFrom: 0.65
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.65
scaleFrom: 0.65
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5

scaleTo: 0.8
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
scaleTo: 18

alpha: 0.9
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 15

drawUnderUnits: false
atmospheric: false


[effect_底色]
priority: critical
image: ROOT:/太空浪人/传送门/收缩2.png
life: 150
fadeOut: true
attachedToUnit: false

scaleFrom: 0.5
scaleTo: 0.8
alpha: 0.5
drawUnderUnits: false
atmospheric: true


[effect_冲击波2]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5

scaleTo: 1.6
alpha: 1
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.5
recommendedInEachBasePriorityIfUnmet: 0.85
recommendedInEachBaseNum: 2
noneInBaseExtraPriority: 0.8
maxGlobal: 9999


