


[core]
name: 粒子弩炮t1
displayText: Частицевый арбалет t1
class: CustomUnitMetadata
price: 2500
maxHp: 2100
footprint: 0,0,1,1

constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 13
techLevel: 1
buildSpeed: 0

radius: 25
buildingSelectionOffset: -8
isBuilding: true
copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.12
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
isBio: false
effectOnDeath: CUSTOM:烟雾2*2,CUSTOM:爆炸*1
tags: 地面,灰影建筑,建筑


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_升级]
convertTo: 粒子弩炮t2
displayType: action
text: Улучшить
price: 2000
buildSpeed: 8s

isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Требуется Узел уровня 3, либо это здание должно быть обесточено.
ai_isHighPriority: true
description: Частицевый арбалет 2 уровня получил больше и сильнее ускоряющих модулей,\n-не только увеличив дальность, но и эффективнее пронзая юнитов.


[graphics]
total_frames: 1
image: ROOT:/太空浪人/建筑特效/防御塔t1.png
image_wreak: ROOT:/太空浪人/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
imageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 150

turretSize: 23
turretTurnSpeed: 3
maxAttackRange: 380
aimOffsetSpread: -0.01


[turret_1]
x: 0
y: 18
canShoot: true
recoilOffset: -4
projectile: 1

image: 主炮.png
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*5,CUSTOM:光粒*8

delay: 240
size: 30
canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
warmup: 60
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png

idleDir: 0
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
idleSweepAngle: 100
idleSweepDelay: 210

idleSweepSpeed: 0.2


[projectile_1]
@copyFromSection: template_动能
directDamage: 1200
life: 240
speed: 10
image: ROOT:/太空浪人/单位特效/弯子弹.png

drawSize: 1.1
spawnProjectilesOnExplode: m2(yOffsetRelative= 10)
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:粒子*7,CUSTOM:穿透
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:粒子*7,CUSTOM:穿透
lightSize: 0.75

trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
lightColor: #FFFF1200


[projectile_m2]
@copyFromSection: template_动能
life: 1
deflectionPower: -1
explodeOnEndOfLife: true
speed: 0

turnSpeed: 0.0
areaDamage: 200
areaRadius: 50
areaRadiusFromEdge: true
targetGround: true

invisible: true
explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光1
spawnProjectilesOnCreate: m2(recursionLimit= 10, yOffsetRelative= 8)


[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.48
scaleTo: 0.7

image: ROOT:/太空浪人/单位特效/核弹.png
total_frames: 21
animateFrameStart: 0
animateFrameEnd: 21
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom: 0.1
scaleTo: 0.4

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2

ySpeedRelativeRandom: 2.2
#atmospheric: true


[effect_穿透]
priority: critical
image: ROOT:/太空浪人/单位特效/弯子弹.png
life: 100
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
alpha: 1
drawUnderUnits: false

ySpeedRelative: 3
atmospheric: false


[effect_闪光1]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_爆炸1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/双尾.png
life: 20
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.9
scaleTo: 0.9
alpha: 0.6

#drawUnderUnits:t


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2

yOffsetRelative: 0.3
ySpeedRelative: 0.5
atmospheric: true


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 1

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.5
ySpeedAbsoluteRandom: 1
ySpeedRelative: 1
#xOffsetRelative:-2

atmospheric: true


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 空塔楼t1传送
ai_upgradePriority: 0.07


