


[core]
name: 人肉炸弹
displayText: Живая бомба
displayDescription:【Уровень t2】【Биологический юнит】【Наземный юнит】  Тактическое назначение: 杀式пехота，\n-не может загружает，только по земле，вооружение：\n-▲炸снаряд背心X1 взрывной урон， 杀式входитьвойнаатака。\n-этот些бесстрашный者будет烈тип炸药绑полныйвсетело，\n-онис牺牲самв качествецена挽回не利 война局。
isUnrepairableUnit:true
price: 550

maxHp: 650
techLevel: 1
fogOfWarSightRange: 10
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 8s
radius: 8
transportSlotsNeeded: 200
isBio: true
hideScorchMark: true
effectOnDeath: CUSTOM:飘血*12,CUSTOM:飘血2*14
fireTurretXAtSelfOnDeath: 1
tags: 地面,步兵,射程x
softCollisionOnAll: 60
armour: 0
[action_外骨骼]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/外骨骼.png
text: Технология экзоскелета
isActive: false
isVisible: if self.globalTeamTags(includes='外骨骼')
[hiddenAction_外骨骼生效]
autoTrigger: if self.globalTeamTags(includes='外骨骼') and not self.tags(includes= '外骨骼保险')
setUnitStats: moveSpeed= ${movement.moveSpeed * 1.3},maxHp= ${core.maxHp*1.2},hp= ${core.maxHp*1.2}, maxTurnSpeed = ${movement.maxTurnSpeed* 1.65}
temporarilyAddTags:外骨骼保险

[action_自爆]
displayType: rally
text: самоподрыв
description: немедленнооригинал самоподрыв
addResources: hp=-9999
buildSpeed: 1
highPriorityQueue: true
displayRemainingStockpile: false
iconImage: ROOT:/通用特效/自爆.png

[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: ROOT:/创世纪军事集团/步兵特效/影子.png
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.7


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 1
turretTurnSpeed: 2.5
dieOnAttack: true
maxAttackRange: 18
isMelee: true
[projectile_0]
directDamage: 0
life: 50
instant: true
explodeEffect: NONE
[turret_0]
projectile: 0
x: 0
y: 0
invisible: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
canAttackCondition:if not self.hasParent
[turret_1]
x: 0
y: 0
invisible: true
shoot_sound: NONE
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFFEB88
projectile: 1
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
canAttackCondition:if not self.hasParent
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 800
areaRadius: 65
life: 666
speed: 8888
targetSpeed: 8888
instant: true
flameWeapon: true
deflectionPower: -1
areaRadiusFromEdge: true
explodeEffect: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠,CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠,CUSTOM:弹坑
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound:大爆炸.ogg


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority:veryhigh
attachedToUnit: true
scaleFrom: 0.4
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.22
alwayStartDirAtZero: true
alpha: 0.8


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 0.7
scaleTo: 0.7
createWhenOverLiquid: false
createWhenOverLand: true


[effect_飘血]
life: 300
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1
scaleTo: 1
drawUnderUnits: false
liveAfterAttachedDies: true
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.6
ySpeedRelativeRandom: 1.8
hSpeed: 1.5


[effect_飘血2]
life: 300
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: false
liveAfterAttachedDies: true
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 2.3
ySpeedRelativeRandom: 2.3
hSpeed: 2
dirSpeedRandom: 50
[arm_1]
#左后臂
x: -6
y: 1
image_end: 手.png
image_end_teamColors: true
drawDirOffset: 20
drawOverBody: false
image_end_shadow: SHADOW:手.png
[arm_2]
#右后臂
x: 6
y: 1
image_end: 手.png
image_end_teamColors: true
drawOverBody: false
drawDirOffset: -20
image_end_shadow: SHADOW:手.png
[arm_5]
#身体
x: 0
y: 0
image_end: 躯干.png
image_end_teamColors: true
#drawOverBody: true
image_end_shadow: SHADOW:躯干.png
[arm_7]
#脑袋
x: 0
y: -1
image_end: 头盔.png
image_end_teamColors: true
drawOverBody: true
[leg_1]
x: -2
y: 0
attach_x: -1
attach_y: -1
moveSpeed: 3.5
moveWarmUp: 0.3s
rotateSpeed: 9
heightSpeed: 1
resetAngle: 25
targetHeightRelative: false
image_leg: 腿.png
dust_effect: false
holdDisMin:1
holdDisMax: 4
hardLimit: 7
estimatingPositionMultiplier: 0.65
hidden: if self.hasParent() or self.isOverLiquid
[leg_2]
x: 2
y: 0
attach_x: 1
attach_y: -1
copyFrom: 1
[animation_move]
onActions: move
#blendIn: 0.05s
#blendOut: 0.05s
arm5_0.2s: {x:0, y:0, dir:-9}
arm1_0.2s: {x:0, y:0, dir:-9}
arm2_0.2s: {x:0, y:0, dir:-9}
arm5_0.4s: {x:0, y:0, dir:9}
arm1_0.4s: {x:0, y:0, dir:9}
arm2_0.4s: {x:0, y:0, dir:9}
arm5_0.5s: {x:0, y:0, dir:0}
arm1_0.5s: {x:0, y:0, dir:0}
arm2_0.5s: {x:0, y:0, dir:0}
[movement]
movementType: LAND
moveSpeed: 1.65
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0
maxTurnSpeed: 4.1
targetHeight: 2

turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: true


