


[core]
name: 大型离心机
class: CustomUnitMetadata
price: 0
maxHp: 25000
footprint: -9,-2,9,4
armour: 50
constructionFootprint: -9,-2,9,4
techLevel: 1
#copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 0s
displayDescription:一种处理钍原矿的大型离心机，现已废弃

radius: 100
isBio: false
isBuilding: true
effectOnDeath: largeExplosion*1
tags: 中立地面,不检测,建筑

stayNeutral: true
createOnAggressiveTeam: true
isUnrepairableUnit: true


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
#imageScale:0.7
image_back: ROOT:/通用特效/NO.png

image_shadow: 影子.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[arm_1]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_2]
x: 0
y: 0
image_end: 闪.png
image_end_teamColors: true
drawOverBody: true
lockMovement: true
hidden:if self.hp< self.maxHp * 0.36
[animation_1]
onActions: idle
blendIn: 1.4s
blendOut: 1.4s
arm2_0s: {alpha:0.0}
arm2_0.5s: {alpha:1}

arm2_0.9s: {alpha:0.1}

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
lowPriorityTargetForOtherUnits: true
notPassivelyTargetedByOtherUnits: true


