


[core]
name: 灰影病毒催化剂中介
displayText: Посредник катализатора вируса «Серая Тень»
class: CustomUnitMetadata
price: 0
maxHp: 5

techLevel: 1
buildSpeed: 5s
radius: 20
displayRadius: 20
numBitsOnDeath: 0

fogOfWarSightRange: 0
isBio: false
softCollisionOnAll: 100
isBuilding: true
energyMax: 1

explodeOnDeath: false
hideScorchMark: true
energyRegen: -1
dieOnZeroEnergy: true
canNotBeGivenOrdersByPlayer: true

disableAllUnitCollisions: true
isUnselectable: true
fireTurretXAtSelfOnDeath: 1
canNotBeDirectlyAttacked: true
showOnMinimapToEnemies: false
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true

[graphics]
total_frames: 1
image: ROOT:通用特效/NO.png
image_wreak: NONE
image_turret: NONE
showEnergyBar: false

image_shadow: NONE
imageScale: 0.5
dustEffect: false


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 10

turretTurnSpeed: 6
maxAttackRange: 35
shootDelay: 8
aimOffsetSpread: 0.25


[turret_1]
x: -7000
y: 7000
invisible: true
projectile: 1
turnSpeed: 15

turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true


[projectile_1]
areaDamage: 0
areaRadius: 0
areaHitAirAndLandAtSameTime: true
life: 24000
speed: 29

deflectionPower: -1
drawSize: 1.5
targetSpeed: 23
tags: 导弹2
#frame:1

image: 弹头.png
targetGround: true
lightSize: 1
trailEffectRate: 0.5
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1

lightColor: #FF00B3FF
spawnUnit: 狂暴灰影中介(alwayStartDirAtZero= true)
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0


[effect_尾巴]
priority: critical
image: ROOT:/通用特效/爆炸.png
life: 45
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 1
scaleTo: 5
alpha: 0.5
drawUnderUnits: false

atmospheric: true
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13
animateFrameSpeed: 0.3

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_尾巴1]
stripIndex: effects
frameIndex: 0
life: 75
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 5
scaleFrom: 1
scaleTo: 5
alpha: 0.6

drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[movement]
movementType: AIR
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
moveSlidingMode : true
moveIgnoringBody: true
targetHeight: 0
targetHeightDrift: 0


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


