


[core]
name: 狂暴灰影中介
displayText: Посредник яростной «Серой Тени»
class: CustomUnitMetadata
price: 0
maxHp: 5

techLevel: 1
buildSpeed: 5s
radius: 20
displayRadius: 20
numBitsOnDeath: 0

fogOfWarSightRange: 30
isBio: false
softCollisionOnAll: 100
isBuilding: true
energyMax: 1800

energyRegen: -1
showInEditor: false
dieOnZeroEnergy: true
explodeOnDeath: false
hideScorchMark: true

showOnMinimapToEnemies: false
canNotBeGivenOrdersByPlayer: true
disableAllUnitCollisions: true
isUnselectable: true
canNotBeDirectlyAttacked: true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_发射]
fireTurretXAtGround: 1
autoTrigger: if not self.energy(empty=true)
fireTurretXAtGround_withOffset: 0,0


[action_发射1]
fireTurretXAtGround: 1
autoTrigger: if not self.energy(empty=true)
fireTurretXAtGround_withOffset: 0,0


[action_发射2]
fireTurretXAtGround: 1
autoTrigger: if not self.energy(empty=true)
fireTurretXAtGround_withOffset: 0,0


[action_发射3]
fireTurretXAtGround: 1
autoTrigger: if not self.energy(empty=true)
fireTurretXAtGround_withOffset: 0,0


[action_发射4]
fireTurretXAtGround: 1
autoTrigger: if not self.energy(empty=true)
fireTurretXAtGround_withOffset: 0,0


[action_发射5]
fireTurretXAtGround: 1
autoTrigger: if not self.energy(empty=true)
fireTurretXAtGround_withOffset: 0,0


[graphics]
total_frames: 1
image: ROOT:通用特效/NO.png
image_wreak: NONE
image_turret: NONE
showEnergyBar: false

image_shadow: NONE
imageScale: 0.5
dustEffect: false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
turretSize: 100

turretTurnSpeed: 600
maxAttackRange: 9999
shootDelay: 2
aimOffsetSpread: 0.25


[turret_1]
x: 0
y: 0
canShoot: false
projectile: 1


[turret_2]
#area shock turret
x: 0
y: 0
invisible: true
canAttackFlyingUnits: true

canAttackLandUnits: true
canAttackUnderwaterUnits: false
limitingRange: 9999
projectile: 2
turnSpeed: 50

shoot_sound: NONE
shoot_flame: NONE
canShoot: true
size: 0


[turret_3]
#area shock turret
x: 0
y: 0
invisible: true
canAttackFlyingUnits: true

canAttackLandUnits: true
canAttackUnderwaterUnits: false
limitingRange: 9999
projectile: 3
turnSpeed: 50

shoot_sound: NONE
shoot_flame: NONE
canShoot: true
size: 0


[projectile_1]
areaDamage: 0
areaRadius: 0
life: 6661
frame: 1
drawSize: 0.1

speed: 10
deflectionPower: -1
targetSpeed: 10
explodeEffect: CUSTOM:纳米*2,CUSTOM:纳米1*2,CUSTOM:闪电*1,CUSTOM:烟雾x*2
targetGround: true

targetGroundSpread: 180


[projectile_2]
@copyFromSection: template_动能,template_战略武器
areaDamage: 8
armourIgnoreAmount: 90
areaRadius: 320
speed: 0.1

areaHitAirAndLandAtSameTime: true
life: 0
image: NO.png
instant: false
largeHitEffect: false

explodeOnEndOfLife: true
deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true

buildingDamageMultiplier: 0
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_3]
areaDamage: -18
areaRadius: 320
speed: 0.1
areaHitAirAndLandAtSameTime: true
life: 0

friendlyFire: only-ignoreEnemy
image: NO.png
instant: false
largeHitEffect: false
explodeOnEndOfLife: true

deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true


[effect_纳米]
spawnChance: 0.6
priority: critical
image: 纳米.png
frameIndex: 0
createWhenOverLiquid: false

life: 240
fadeOut: true
attachedToUnit: false
#color: #6D5448
fadeInTime: 5

scaleFrom: 1.7
scaleTo: 2.7
alpha: 1
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 17
yOffsetRelativeRandom: 17

xSpeedAbsoluteRandom: 0.1
ySpeedAbsoluteRandom: 0.1


[effect_纳米1]
image: 纳米1.png
spawnChance: 0.6
priority: critical
frameIndex: 0
createWhenOverLiquid: false

life: 240
fadeOut: true
attachedToUnit: false
#color: #6D5448
fadeInTime: 5

scaleFrom: 1.4
scaleTo: 2.4
alpha: 1
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 2
yOffsetRelativeRandom: 24

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_烟雾x]
stripIndex: effects
frameIndex: 0
life: 250
fadeOut: true
attachedToUnit: false

color: #FFFF1200
fadeInTime: 4
scaleFrom: 8
scaleTo: 10
alpha: 0.3

drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.1

hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.8
ySpeedRelativeRandom: 0.8
xSpeedAbsoluteRandom: 0.4
ySpeedAbsoluteRandom: 0.4


[effect_闪电]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.6

drawUnderUnits: true
scaleFrom: 4
scaleTo: 6
color: #FFFF1200


[movement]
movementType: AIR
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
moveSlidingMode : true
moveIgnoringBody: true
targetHeight: 0
targetHeightDrift: 0


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


