
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true




[core]
name: AI核心作战中枢t2
displayText: боевой центр ядра ИИt2
class: CustomUnitMetadata
price: 8000
maxHp: 5000
maxShield: 6000
shieldRenderRadius: 1
shieldRegen: 1
footprint: -6,-3,6,5
constructionFootprint: -6,-3,6,5
tags:余辉指挥中心t2,地面,建筑,无人单位,自动
techLevel: 1
displayDescription: 【Уровень t2】【Здание】【Беспилотный юнит】【Наземный юнит】\n-тактическое назначение: ключевое здание. вооружение:\n-▲Дрон-осаX2 по земле и воздуху взрывной урон, \n-Империя Новастандартное предсобранное полевое командный центр, используется для более удобного командования на поверхности планеты, \n-они могут управлять боевыми подразделениями уровня легиона, а также космическим флотвести боевые действия.\n-Этот командный центрсодержит один илиили несколько специализированных для командования высокоинтеллектуальное ядро ИИ II уровня, \n-а также несколько пусковых установок дронов для самозащиты, \n-Это здание - основа Империя Новапроявления мощи и завоевания звёздных систем.
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1),AI核心作战中枢t2残骸
effectOnDeath: CUSTOM:烟雾*6, CUSTOM:爆破*15
experimental: true
selfBuildRate: 1
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md

isBuilding: true
armour: 12
radius: 90
fogOfWarSightRange: 49

generation_delay: 40
generation_credits: 25
exit_x:0
exit_y: 60
exit_moveAwayAmount: 180
canBuild_11_name: setRally
canBuild_11_pos: 0.0001
maxTransportingUnits: 2
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]

[action_开启]
text: Включить автопроизводство
displayType: action
buildSpeed: 0s
pos: 0.01
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/修复.png
temporarilyAddTags:自动
#temporarilyRemoveTags:不自动
isVisible: if not self.tags(includes= '自动')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: Включить автопроизводствопалубный самолёт
ai_isHighPriority: false
[action_关闭]
text: Выключить автопроизводство
displayType: action
buildSpeed: 0s
pos: 0.011
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
temporarilyRemoveTags:自动
isVisible: if self.tags(includes= '自动')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: Отключить автопроизводство палубных юнитов, чтобы освободить место для других умений
iconImage: ROOT:/通用特效/修复1.png
ai_isHighPriority: true



[hiddenAction_drone]
autoTrigger: if memory.灰机 < 2 and self.tags(includes= '自动') and self.queueSize < 0.5
alsoQueueAction: SDD
highPriorityQueue: true
[hiddenAction_SDD]
buildSpeed: 10s
requireConditional: if memory.灰机 < 2
addUnitsIntoTransport: SDD黄蜂无人机
highPriorityQueue: true
[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1


[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)


[canBuild_T33]
name:爪巴
pos: 1
isVisible: false
isLocked: true
isLockedMessage:🐴

[action_升级]
convertTo: AI核心作战中枢t3
displayType: upgrade
text: быстрыйУлучшить
price: 15000
buildSpeed: 20s
highPriorityQueue: false
ai_isHighPriority: true
description: добавитьтвёрдыйбоевой центр ядра ИИи расширениенаполнитьбоймашинамашинабиблиотека, \n-под одинуровеньбоевой центр ядра ИИбудетимеет указыватьразмахбольшой  типделатьистребительмеханизм может сила, \n-дажедо имеет правонастройкаиспользует небофлот.
pos: 0.005
refundAllQueuedItems:true
addResources: ry=300
[action_升级x]
autoTrigger: if self.lastConverted > 210
isActive: false

text: честныйценаУлучшить:%{ 210 - self.lastConverted }s
# %{ 210 - self.lastConverted }# 用来显示廉价升级剩余时间。# 动态文本。可以加在text或者description里，可以在前面后面加文本。动态文本目前除了core 和resource_以外，其它地方基本能加
description: под одинуровенькомандный центрбудетполучить более многотехнология, \n-будетполучить Империя Новаосновная силавойска производствоправо, \n-дажедо имеет правонастройкаиспользует небофлот.
pos: 0.006
convertTo: AI核心作战中枢t3
refundAllQueuedItems:true
addResources: ry=300
displayType: infoOnlyNoBox
[action_造筑基虫]
displayType: action
price: 700
buildSpeed: 11s
isVisible: true
highPriorityQueue: true
produceUnits:筑基虫(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: 筑基虫
textAddUnitName:筑基虫
descriptionAddFromUnit: 筑基虫
descriptionAddUnitStats: 筑基虫
allowMultipleInQueue:true
pos:0.2
#ai_isHighPriority: true
isLocked: if numberOfUnitsInTeam(greaterThan=3, withTag='农民') and self.isControlledByAI()
[action_造开拓者]
displayType: action
price: 150
buildSpeed: 3.75s
isVisible: true
highPriorityQueue: true
produceUnits:HK开拓者(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: HK开拓者
textAddUnitName:HK开拓者
descriptionAddFromUnit: HK开拓者
descriptionAddUnitStats: HK开拓者
allowMultipleInQueue:true
pos:0.3
ai_isHighPriority: false


[action_造收割者]
displayType: action
price: 700
buildSpeed: 10s
isVisible: true
highPriorityQueue: true
produceUnits:HK收割者(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: HK收割者
textAddUnitName:HK收割者
descriptionAddFromUnit: HK收割者
descriptionAddUnitStats: HK收割者
allowMultipleInQueue:true
pos:0.4
ai_isHighPriority: false










[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
yOffsetRelative:8
xOffsetRelative:8
onlyWhileAlive:true
isVisible:true
alpha:0.6

[decal_光]
image: ROOT:/余辉军团/建筑特效/老家灯.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
alpha:0.6


[decal_遮盖]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true

[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true

[decal_转子]
image: ROOT:/余辉军团/建筑特效/老家动画.png
total_frames: 3
frame: (self.customTimer * 15) % 3
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:0
yOffsetAbsolute:-36
isVisible:true
onlyWhileAlive:true
layer: onTop


[decal_光头]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:0.5
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1

[graphics]
total_frames: 1
image: NO.png
image_back: ROOT:/余辉军团/建筑特效/老家地板.png
image_wreak:ROOT:/余辉军团/建筑特效/老家死亡.png
image_turret: NONE
#imageScale: 0.8
#turretImageScale: 0.75
showShotDelayBar:false

#image_offsetY: -50
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
maxAttackRange: 99999
turretTurnSpeed: 50
turretMultiTargeting: true

[turret_1]
x: -90
y: -22
projectile: 233
delay: 2.2s
canAttackMaxAngle: 181
canOnlyAttackUnitsWithoutTags:高空
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true
limitingRange: 900
unloadUpToXUnitsAndGiveAttackOrder: 1
[turret_2]
x: 90
y: -22
copyFrom: 1

[turret_3]
x: 0
y: 0
projectile: 233
delay: 99999s
warmup:99999s
canAttackMaxAngle: 181
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true




[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true




[arm_1]
x: 0
y: 0
image_end:ROOT:/余辉军团/建筑特效/老家钢门.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:0.3

[animation_开门]
blendIn: 0.1s
blendOut: 0.1s
arm1_0s: {x:0, y:0, dir:0}

arm1_2s: {x:0, y:33, dir:0}

arm1_99999s: {x:0, y:33, dir:0}



[attachment_drone1]
x: -90
y: -22
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false
idleDir:-90
addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: false
lockRotation: true
#height:1


[attachment_drone6]
@copyFromSection: attachment_drone1
x: 90
y: -22
idleDir:90


[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 60
yOffsetRelativeRandom: 100
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: 30
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
xOffsetRelativeRandom:70
yOffsetRelativeRandom:160
delayedStartTimerRandom:30
yOffsetRelative: 50
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[ai]
ai_upgradePriority: 1
buildPriority: 0.01



