


[core]
name: 攻城锥IFV
displayText: БМП Осадный конус
displayDescription:【Уровень t3】【Механический юнит】【Наземный юнит】【тяжёлое укрытие】Тактическое назначение:БМП，вместимость десанта：6\n-может загружать только биологические юнитыисам не может транспортироваться。\n-вооружение：▲миномётX1 только по земле взрывной урон \n-БМП Осадный конусявляетсяоснащённыйбольшойкалибртяжёлыйминомёт многоприменение车 ，\n-онможетв安вседистанциявиспользоватьминомётв качествепехота清理различные碉堡с工事，\n-одновременнооснащённый Дымовая гранатаприходить弥补车体защита недостаточно。\n-согласно统计，размещатьсявБМП Осадный конусв пехотаполе боя生存率можетповышает30%，\n-именно поэтому，Генезиспехота亲切 называтьегов качестве“守护神”。

price: 3000

maxHp: 4000
techLevel: 1
buildSpeed: 10s
radius: 23
isBio: false

copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,攻城锥,重型掩体
armour: 10
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 攻城锥
energyMax: 10
energyStartingPercentage: 0
energyRegen: 0.006
maxTransportingUnits: 6
transportUnitsRequireTag: 步兵,卧倒,机甲
transportUnitsKillOnDeath: true
transportUnitsKeepBuiltUnits: true

unitsSpawnedOnDeath: 损毁*1
canRepairBuildings: true
autoRepair: true
canRepairUnits: true
nanoRepairSpeed: 0.2

nanoRange: 150
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
canBuild_1_name: 重装部队
canBuild_1_pos: 1
canBuild_2_name: 狙击手
canBuild_2_pos: 2

canBuild_3_name: 迫击炮小队
canBuild_3_pos: 3
canBuild_4_name: 无畏战士
canBuild_4_pos: 4
canBuild_5_name: 蜂刺导弹小组

canBuild_5_pos: 5



[canBuild_9]
name: 跳跳虎
pos: 0.3
forceNano: true


[canBuild_10]
name: 高爆地雷
pos: 0.4
forceNano: true
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[hiddenAction_1]
price: 0
buildSpeed: 0s
isVisible: false
autoTrigger:if  self.numberOfAttachedUnits(withTag= '1格')*1 + self.numberOfAttachedUnits(withTag= '蜂刺')*2 + self.numberOfAttachedUnits(withTag= '反坦克炮') * 2+self.numberOfAttachedUnits(withTag= '机甲战士') * 2+self.numberOfAttachedUnits(withTag= '角斗士') * 3+self.numberOfAttachedUnits(withTag= '操纵者') * 2+self.numberOfAttachedUnits(withTag= '狩猎者') * 4> 6
forceUnloadTransportNow:true
forceUnloadTransportNow_onlyOnSlot:1
highPriorityQueue: true
#refundAllQueuedItems:true
displayType: action

[action_弹幕架1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕1.png
text: Реактивная установка1
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架1')


[action_恐怖地雷2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: Мина «Кошмар»2
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷2') and not self.globalTeamTags(includes='恐怖地雷3')
isAlsoViewableByAllies: true
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')



[action_重型掩体]
text: тяжёлое укрытие
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: одиннаходитьсятяжёлое укрытие，можетв качестверядом140в радиусе биологический юнитобеспечиваеттяжёлое прикрытие。\n-тяжёлое прикрытиеможетв качествебиологический юнитснижает на75% 伤害，\n-но，укрытиене можетснижает начастьскорострельный，激свет，Огонь，Электричествоудар，втип，самоподрыв，ближний бой，衰解и т.д.другиеигнорироватьукрытие оружие。



[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_1_烟幕弹]
fireTurretXAtGround: 烟幕弹
text: запускатьДымовая граната
displayType: action
buildSpeed: 0.1s
pos: 0.1

displayRemainingStockpile: true
highPriorityQueue: true
price: energy=10
canPlayerCancel: false
onlyOneUnitAtATime: true

description: кцельобласть投掷однаДымовая граната，Дымовая гранатаможетсерьёзный干扰вражеская армия 瞄准система。\n-Дымовая гранатабудет降низкийрядом160в радиусе вражескийназемный юнит дальностьа такжескорострельность，\n-противобладатьдальнийцелеуказаниеспособностьа такжеиметьУлучшенный модуль наведениянаука юнитнеэффективный。
iconImage: ROOT:/创世纪军事集团/单位特效/烟雾弹.png
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 

[graphics]
total_frames: 2
image: 攻城锥IFV.png
image_wreak: 攻城锥IFV死亡.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 3
dustEffect: true

turretImageScale: 0.8
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 13

turretTurnSpeed: 4
maxAttackRange: 310

turretMultiTargeting: true


[turret_烟幕弹]
x: 0
y: 0
canShoot: false
idleDir: 0
invisible: true

size: 1.1
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 2

delay: 0
canAttackCondition: if self.resource.xk < 1


[attachment_1]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: true


[attachment_2]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false

resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: true


[attachment_3]
x: 0
y: 0
alwaysAllowedToAttackParentsMainTarget: true
height: -1
isVisible: false

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_4]
x: 0
y: 0
isVisible: false
alwaysAllowedToAttackParentsMainTarget: true
height: -1

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_5]
x: 0
y: 0
alwaysAllowedToAttackParentsMainTarget: true
height: -1
isVisible: false

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_6]
x: 0
y: 0
isVisible: false
alwaysAllowedToAttackParentsMainTarget: true
height: -1

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[turret_1]
x: 0
y: 7
attachedTo: 0
slave: true
image: ROOT:/创世纪军事集团/单位特效/炮管.png

shoot_sound: ROOT:/创世纪军事集团/单位特效/迫击炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFFEB88
recoilOffset: -2
recoilOutTime: 2

limitingMinRange: 150
recoilReturnTime: 30
shoot_flame: CUSTOM:烟雾2*3,CUSTOM:枪口火焰
projectile: 1
delay: 240
aimOffsetSpread: 1
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='弹幕架1')

[turret_0]
x: 0
y: -7
canShoot: false
recoilOffset: -2
limitingMinRange: 150

image: ROOT:/创世纪军事集团/单位特效/炮塔2.png
canAttackCondition: if self.resource.xk < 1 


[turret_3]
x: 0
y: -30
idleDir: 180
warmup: 0
size: 8

canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true

image: 塔.png
[turret_4]
x: 0
y: 0
#炮塔损坏
canShoot: false
image: 炮塔损坏.png
invisible: if self.maxHp * 0.36 < self.hp
attachedTo: 0
slave: true

[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 300
areaRadius: 60
life: 6661
speed: 5

targetSpeed: 5
drawSize: 0.75
image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
explodeEffect: CUSTOM:爆炸,CUSTOM:弹坑,CUSTOM:烟雾,CUSTOM:闪光*1,CUSTOM:烟雾3*3,CUSTOM:水波*1,CUSTOM:水花*1
targetGround: true

trailEffect: true
initialUnguidedSpeedHeight: 1
areaRadiusFromEdge: true


[projectile_2]
life: 600
directDamage: 0
speed: 4
targetSpeed: 4
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png

drawSize: 0.6
targetGround: true
spawnUnit: 烟幕弹*1
trailEffect: true
deflectionPower: -1
[projectile_炮弹]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1

frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 炮弹1*3
[projectile_炮弹1]
@copyFromSection: template_爆炸
areaDamage: 250
areaRadius: 60
life: 6661
speed: 5
drawSize: 0.7
targetGroundSpread: 20
image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
explodeEffect: CUSTOM:爆炸,CUSTOM:弹坑,CUSTOM:烟雾,CUSTOM:闪光*1,CUSTOM:烟雾3*3,CUSTOM:水波*1,CUSTOM:水花*1
targetGround: true
trailEffect: true
initialUnguidedSpeedHeight: 2
areaRadiusFromEdge: true
speedSpread:0.5
[effect_烟雾]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true

life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5

scaleFrom: 0.15
scaleTo: 0.3
alpha: 1.25
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_烟雾2]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 80
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 1
scaleTo: 1.8
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 3
scaleTo: 3


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.3

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟雾3]
priority: critical
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true

attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 3

alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true

hSpeed: 0.2
hOffsetRandom: 0.15
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/迫击炮爆炸.ogg
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15

xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false


[effect_水花]
image: ROOT:/通用特效/水花.png
life: 160
fadeOut: true
attachedToUnit: false
color: #FFFFFF

fadeInTime: 4
scaleFrom: 0.05
scaleTo: 0.4
alpha: 0.6
drawUnderUnits: false

dirOffsetRandom: 0
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3

createWhenOverLiquid: true
createWhenOverLand: false


[effect_水波]
priority: critical
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.45
alpha: 1
drawUnderUnits: true
atmospheric: true

createWhenOverLiquid: true
createWhenOverLand: false


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5

drawUnderUnits: false
atmospheric: false


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1
scaleTo: 1
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0.6

maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false


[ai]
useAsBuilder: true


