
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 超坦克MK2
displayText: Супертанк MK2
class: CustomUnitMetadata
price: 10000,钍=200,bj= ${bjxq}
@global bjxq:15
reclaimPrice: bj= ${bjxq}
maxHp: 30000
displayDescription: 【Уровень t4】【Механический юнит】【Наземный юнит】【тяжёлое укрытие】【扫雷устройство】Тактическое назначение:продвинутый突удар танк，\n-размер юнита:8，вооружение：▲405ммлинкорглавныйпушкаX2 только по земле кинетический урон \n-▲противопехотный榴снарядпусковая установкаX4 только по земле взрывной урон пробивает укрытия противпехотаурон-бонус\n-投入поле боя база准 Супертанквреальныйвойнав，逐渐暴露выходить诸много问题:\n-例как высокий  тяжёлыйиневсекбашняпозволятьеговЛунана поле боя 模拟表现не佳。\n-тогдаармиястратегияИнститутна основебаза准 выполнять 针противтипразрабатывать，\n-в牺牲толстыйтяжёлый бронязенитная ракетаа такжеболее换самыйновый высокий扭矩башняЭлектричествомашинапосле，\n-Супертанк MK2 иметь может媲美средний танк скоростьа такжевсекбашня，\n-одновременномногоостаток 配тяжёлый используется для安установитьодин套复合扫雷установить置а такжепротивлёгкийюнитэффективный折叠ракетаснарядпусковой блок。\n-сСупертанк相比，этот видмалый 化изменять  преимуществоввболеехороший манёвренностьа также整备тип，\n-реальныйвойна证明，этот видменьше изменять  манёвренностьнестиприходить сражениеэффективностьповышаетявляетсяоригинал版нетможно比拟 ，\n-сэтот相比，бронятолстый度верх 牺牲简直не值один提。


techLevel: 1
buildSpeed: 45s
radius: 75
fogOfWarSightRange: 33
displayRadius: 75
isBio: false
transportSlotsNeeded: 8
softCollisionOnAll: 10
armour: 80
unitsSpawnedOnDeath: 损毁3*1
tags: 地面,扫雷,重型掩体,驻扎要塞
copyFrom: ROOT:/通用特效/单位防护.ini

[hiddenAction_掩体1取消]
autoTrigger:if self.hasParent and self.tags(includes= '重型掩体')
isVisible:false
temporarilyRemoveTags:重型掩体
[hiddenAction_掩体1生成]
autoTrigger:if not self.hasParent and not self.tags(includes= '重型掩体')
isVisible:false
temporarilyAddTags:重型掩体

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[action_重型掩体]
text: тяжёлое укрытие
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: одиннаходитьсятяжёлое укрытие，можетв качестверядом140в радиусе биологический юнитобеспечиваеттяжёлое прикрытие。\n-тяжёлое прикрытиеможетв качествебиологический юнитснижает на75% 伤害，\n-но，укрытиене можетснижает наскорострельный，激свет，Огонь，Электричествоудар，втип，самоподрыв，ближний бой，衰解и т.д.другиеигнорироватьукрытие оружие。


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_地震弹头]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/地震弹头.png
text: Сейсмическая боеголовка
isActive: false
isVisible: if self.globalTeamTags(includes='地震弹头')

[decal_履带]
image: 轻履带动画.png
total_frames: 4
frame: (self.customTimer * 22) % 4
# 8为图片帧数，17改速度，1/17s下一帧
layer: afterBody
isVisible:if self.isMoving
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_履带1]
image: 轻履带.png
total_frames: 1
layer: afterBody
isVisible:if not self.isMoving
onlyWhileAlive:true
[decal_灯光]
layer: afterBody
image: 轻底盘灯.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
[decal_损坏]
layer: afterBody
image: 轻底盘损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
alpha:0.8

[decal_损坏1]
layer: onTop
image: 轻炮塔损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
alpha:0.8
basePositionFromTurret: 4
[decal_炮塔影子]
image:轻炮塔影.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:4
onlyWhileAlive:true
basePositionFromTurret: 4
alpha:0.75
[decal_炮管影子]
image:炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_炮管影子1]
image:炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 2

[decal_导弹盖子]
layer: onTop
image: 导1.png
onlyWhileAlive: true
teamColors: true
isVisible:true
basePositionFromTurret: 4
yOffsetRelative:-5
xOffsetRelative:-38
[decal_导弹盖子1]
layer: onTop
image: 导1.png
onlyWhileAlive: true
teamColors: true
isVisible:true
basePositionFromTurret: 4
yOffsetRelative:-5
xOffsetRelative:38
[graphics]
total_frames: 1
image: 轻底盘.png
image_wreak: 轻死亡.png
image_turret: 轻炮塔.png
teamColorsOnTurret: true
image_shadow: 影.png
shadowOffsetX: 4
shadowOffsetY: 4
movementEffect: CUSTOM:烟1,CUSTOM:烟2
movementEffectRate: 20


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
disablePassiveTargeting: false

turretMultiTargeting: true
turretSize: 22
turretTurnSpeed: 1
maxAttackRange: 650
#—————模块化————

#——————炮塔




[turret_2]
x: -12
y: 88
#主炮
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/突击炮音效.ogg

shoot_sound_vol: 1
shoot_flame: CUSTOM:烟雾*8,CUSTOM:枪口火焰,CUSTOM:烟雾2*5
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -14

recoilOutTime: 10
recoilReturnTime: 27
delay: 180
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1
image: 炮管.png
attachedTo: 4
slave: true
size: 48
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='地震弹头')

[turret_3]
x: 12
y: 88
#主炮
copyFrom: 2
shoot_flame: CUSTOM:烟雾*8,CUSTOM:枪口火焰,CUSTOM:烟雾3*5
delay:150
warmup: 30


[turret_4]
x: 0
y: -23
#炮塔
turnSpeed: 1.3
turnSpeedAcceleration: 0.75
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: true
idleSweepAngle: 10
idleSweepDelay: 400
idleSweepSpeed: 0.1
canAttackCondition: if self.resource.xk < 1

[turret_5]
x: -38
y: -5
#炮塔
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1
attachedTo: 4
slave: true
image:导.png
[turret_6]
x: -40.5
y: 0.5
#导弹右
projectile: 2
attachedTo: 4
slave: true
image: 小弹头.png
shoot_sound: ROOT:/创世纪军事集团/单位特效/迫击炮音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*3
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -12
size:10
recoilOutTime: 0
recoilReturnTime: 60
delay:165
aimOffsetSpread: 1
canAttackFlyingUnits: false
[turret_7]
x: -35.5
y: 0.5
#主炮
copyFrom: 6
delay:150
warmup: 15

[turret_8]
x: 38
y: -5
#主炮
copyFrom: 5
[turret_9]
x: 40.5
y: 0.5
#主炮
copyFrom: 6
delay:165

[turret_10]
x: 35.5
y: 0.5
#主炮
copyFrom: 6
delay:150
warmup: 15

[projectile_1]
@copyFromSection: template_动能
#普通炮弹
areaDamage: 2450
areaRadius: 75
life: 5000

speed: 13
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
frame: 9

drawSize: 1
targetSpeed: 13
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑
disableLeadTargeting: true
targetGround: true
trailEffectRate: 0.4
trailEffect: CUSTOM:尾巴, CUSTOM:尾巴x
[projectile_炮弹]
#普通炮弹
areaDamage: 3150
areaRadius: 95
life: 5000
speed: 13
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
frame: 9
drawSize: 1
targetSpeed: 13
areaRadiusFromEdge: true
explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
explodeEffectOnShield:CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
trailEffectRate: 0.4
trailEffect: CUSTOM:尾巴, CUSTOM:尾巴x
disableLeadTargeting: true
targetGround: true
buildingDamageMultiplier: 1.5
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=6

[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 380
areaRadius: 60
life: 6661
speed: 3
targetSpeed: 8
drawSize: 0.95
image: 小弹头.png
explodeEffect:CUSTOM:钢珠,CUSTOM:爆炸f, CUSTOM:爆破f*3,CUSTOM:闪光f,CUSTOM:冲击波f
explodeEffectOnShield:CUSTOM:钢珠,CUSTOM:爆炸f, CUSTOM:爆破f*3,CUSTOM:闪光f,CUSTOM:冲击波f
targetGround: true
initialUnguidedSpeedHeight:1.2
areaRadiusFromEdge: true
disableLeadTargeting: true
trailEffectRate: 0.2
trailEffect: CUSTOM:尾巴z
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 4
speedSpread:1
#————————————导弹特效
[effect_尾巴z]
image: SHARED:light_50.png
life: 12
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFFFF73
fadeInTime: 2
scaleFrom: 0.15
scaleTo: 0.05
alpha: 1
drawUnderUnits: true
[effect_冲击波f]
stripIndex: shockwave
life: 33
scaleFrom: 0.4
scaleTo: 2.7
alpha: 1

[effect_爆破f]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:40
yOffsetRelativeRandom:40
delayedStartTimerRandom:10
[effect_爆炸f]
life: 120
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2.1
image: ROOT:/创世纪军事集团/单位特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alpha: 1.2

[effect_闪光f]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false

#主炮开火特效————————


[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.9

scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1

atmospheric: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 5
scaleTo: 5

#主炮爆炸特效———————————


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false

atmospheric: false


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false

scaleFrom: 2
scaleTo: 2.7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0

animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 2
scaleTo: 2
createWhenOverLiquid: false
createWhenOverLand: true


[effect_尾巴]
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFFFF73
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true









[effect_烟1]
life: 130
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.43
scaleTo: 0.43
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative	: 45
yOffsetRelative	: -70


[effect_烟2]
life: 130
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.43
scaleTo: 0.43
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative	: -45
yOffsetRelative	: -70


[effect_烟雾2]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 100
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.5
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true

xOffsetRelative	: -17
yOffsetRelative	: -114


[effect_烟雾3]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 100
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.5
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
xOffsetRelative	: 17

yOffsetRelative	: -114
atmospheric: true
[effect_尾巴x]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/光束3.png
life: 20
fadeOut: true
attachedToUnit: false
yOffsetRelative	: -10
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7

drawUnderUnits: false
#————————————炮弹爆炸
[effect_聚变nk]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 18
fadeOut: true
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
[effect_冲击波nk]
life: 45
priority: critical
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 2.3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true

[effect_冲击波nk1]
priority: low
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.2
alpha: 0.8
showInFog: true
drawUnderUnits: false
atmospheric: false
#——————@——————看NM，给👴爬


[effect_光球nk]
life: 90
priority: veryhigh
attachedToUnit: false
scaleFrom:0.75
scaleTo: 0.75
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
ySpeedAbsolute:0
fadeOut: true
alpha: 0.85
showInFog: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true
[effect_光球1nk]
life: 90
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/创世纪军事集团/单位特效/大光球.png

fadeOut: true
showInFog: true
alpha: 0.7
fadeInTime: 1
createWhenOffscreen: true

[effect_聚变nk1]
image: ROOT:/通用特效/火光.png
life: 100
fadeOut: true
attachedToUnit: false
alpha: 0.9
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 2
scaleTo: 8.5
color: #FFFFF44C
alwayStartDirAtZero: true
createWhenOffscreen: true
[effect_冲击波nk3]
priority: high
image: ROOT:/创世纪军事集团/单位特效/冲击波4.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.4
alpha: 0.8
drawUnderUnits: true
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:35
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.5
scaleTo:2.67
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180





[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.1
maxTurnSpeed: 1.35

turnAcceleration: 0.11
moveSlidingMode : false
moveIgnoringBody: false


