


[core]
name: 萤火轰炸机
displayText: Бомбардировщик «Светлячок»
class: CustomUnitMetadata
displayDescription: -Бомбардировщик «Светлячок» был создан Скитальцами в крайне тяжёлых условиях.\n-Его технология настолько проста, что над ней мог бы посмеяться даже Генезис, и атакует он самыми примитивными методами.\n-В последний момент эвакуации Скитальцев из галактики Сино флот был почти полностью потерян.\n-Перед лицом грозного королевского флота Империи бомбардировщик «Светлячок» стал одним из немногих противокорабельных вооружений.\n-Они сбрасывают на цели плотный поток неуправляемых плазменных бомб, единственная сила которых — инерция.\n-Из-за крайне низкой эффективности этого метода сегодня «Светлячки» обычно выполняют задачи бомбардировки наземных целей\n-и достигают значительных результатов.\n-Атакует только землю и подводные цели, энергетический урон.
price: 1750
maxHp: 3000

techLevel: 1
buildSpeed: 8s
availableInDemo: true
radius: 23
copyFrom: ROOT:/通用特效/单位防护.ini

selfRegenRate: 0.2
armour: 4
displayRadius: 24
isBio: false
softCollisionOnAll: 10

energyMax: 2
energyRegen: 0.004
energyNeedsToRechargeToFull: true
tags: 飞机,低空


[action_爆散1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: Детонационная боеголовка 1
isActive: false
isVisible: if self.globalTeamTags(includes='爆散1')


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.85
movementEffect: CUSTOM:火,CUSTOM:火1
movementEffectRate: 0.7


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
aimOffsetSpread: 1

turretSize: 0
turretTurnSpeed: 200
maxAttackRange: 150
shootDelay: 4
attackMovement: bomber


[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir: 0

canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shoot_sound: NONE
shoot_sound_vol: 0.3

projectile: 1
size: 0
turnSpeed: 2
energyUsage: 0.2
canAttackCondition: if self.flying

altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散1')


[turret_2]
#bomber
invisible: true
x: 0
y: 0
idleDir: 0

canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shoot_sound: NONE
shoot_sound_vol: 0.3

projectile: 1
size: 0
turnSpeed: 2
energyUsage: 0.2
canAttackCondition: if self.flying

altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散1')


[projectile_1]
@copyFromSection: template_能源
life: 250
speed: 2
targetSpeed: 3
areaDamage: 200

areaRadius: 60
drawSize: 0.7
explodeEffect: CUSTOM:爆炸,CUSTOM:弹坑,CUSTOM:烟雾*2
targetGround: true
areaRadiusFromEdge: true

image: 炸弹.png
areaHitUnderwaterAlways: true


[projectile_炮弹]
@copyFromSection: template_爆炸
life: 250
speed: 2
targetSpeed: 3
areaDamage: 275

areaRadius: 70
drawSize: 0.7
explodeEffect: CUSTOM:爆炸b,CUSTOM:弹坑,CUSTOM:闪电b*2
targetGround: true
areaRadiusFromEdge: true

image: 炸弹.png
areaHitUnderwaterAlways: true


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 0.7
scaleTo: 0.7
createWhenOverLiquid: false
createWhenOverLand: true


[effect_爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 1.5
scaleTo: 1.5

drawUnderUnits: false
atmospheric: false


[effect_烟雾]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false

color: #FFFF1200
fadeInTime: 4
scaleFrom: 1
scaleTo: 2.5
alpha: 1.33

drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2

hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: -5
yOffsetRelative	: -42


[effect_火1]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 5
yOffsetRelative	: -42

#——@———————————


[effect_爆炸b]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/太空浪人/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
#color:#FFFF1200


[effect_闪电b]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.9

#drawUnderUnits:false
scaleFrom: 1.5
scaleTo: 2
color: #FF68FF2E


[movement]
movementType: AIR
moveSpeed: 1.85
moveAccelerationSpeed: 0.04
moveDecelerationSpeed: 0.004
#landOnGround: onlyIdle

joinsGroupFormations: false
maxTurnSpeed: 1.5
turnAcceleration: 0.06
moveSlidingMode : false
moveIgnoringBody: false

targetHeight: 70
slowDeathFall: true


[ai]
disableUse: true


