


[core]
name: 空塔楼t2
class: CustomUnitMetadata
price: 2500
maxHp: 5000
footprint: 0,0,1,1

constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 13
techLevel: 1
buildSpeed: 0

showInEditor: false
radius: 25
buildingSelectionOffset: -8
copyFrom: ROOT:/通用特效/单位防护.ini
armour: 12

isBuilding: true
selfRegenRate: 0.12
tags: 地面,灰影建筑,建筑
isBio: false
effectOnDeath: CUSTOM:烟雾2*2,CUSTOM:爆炸*1


[action_停电]
#autoTrigger:displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: 缺少供能
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

displayType: infoOnly
isGuiBlinking: true


[action_中性粒子炮]
convertTo: 中性粒子炮t2
displayType: action
text: 部署中性粒子炮t2
description: 二级中性粒子炮采用了最新的粒子加速器，\n-能更加有效的击穿重型单位。
price: 1000
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: 你需要三级枢纽，或者该建筑已断电，且一次只能部署一种炮塔。
ai_isHighPriority: true


[action_瓦普驱动炮]
convertTo: 瓦普驱动炮t2
displayType: action
text: 部署瓦普驱动炮t2
description: 二级瓦普驱动炮升级了引力抛射系统，\n-使其能将更具威力聚变物质抛射出惊人的距离。
price: 2000
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: 你需要三级枢纽，或者该建筑已断电，且一次只能部署一种炮塔。
ai_isHighPriority: true


[action_重型多联炮]
convertTo: 重型多联炮t2
displayType: action
text: 部署重型多联炮t2
description: 二级重型多联炮加装了更多发射极，\n-能倾泻出巨量弹雨压制敌人。
price: 1000
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: 你需要三级枢纽，或者该建筑已断电，且一次只能部署一种炮塔。


[action_粒子弩炮]
convertTo: 粒子弩炮t2
displayType: action
text: 部署粒子弩炮t2
description: 二级粒子弩炮叠加了更多更强的加速模块，\n-不仅提升了射程，而且能更有效的洞穿单位
price: 2000
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: 你需要三级枢纽，或者该建筑已断电，且一次只能部署一种炮塔。
ai_isHighPriority: true


[graphics]
total_frames: 1
image: ROOT:/太空浪人/建筑特效/防御塔t2.png
image_wreak: ROOT:/太空浪人/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
imageScale: 0.9
image_back: ROOT:/通用特效/NO.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 200

turretSize: 12
turretTurnSpeed: 3
maxAttackRange: 340


[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 空塔楼t1传送
ai_upgradePriority: 0.07


