


[core]
name: 飞鱼级导弹艇
price: 0
maxHp: 7500
displayDescription:【阶级t4】【机械单位】【水上单位】【伴生单位】\n-战术定位:伴随式战舰，武器配置：\n-▲鱼雷发射管X2 只能攻击水面单位和潜航单位 爆炸伤害\n-▲战术飞弹发射舱X1 只能对地 爆炸伤害 战术武器\n-复仇女神利用内部舰载车间生产的小体积导弹艇，\n-装配了重型鱼雷管和战术导弹发射单元，能够为复仇女神扫清潜航障碍的同时，\n-发射战术导弹支援母体作战，但需要注意的是，飞鱼内部弹药有限，需要母体进行补给。
techLevel: 1
buildSpeed: 17s
radius: 55
displayRadius: 55
showInEditor: false
isBio: false
softCollisionOnAll: 7
armour: 15
fogOfWarSightRange: 23
unitsSpawnedOnDeath: 中型水上单位死亡*1

copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,海上,冲锋,歼敌,伴生单位
energyMax: 10000
energyRegen: -1
energyStartingPercentage:1
[hiddenAction_冇了]
autoTrigger: if self.energy<1
temporarilyAddTags:冇了
[hiddenAction_回家]
autoTrigger: if self.energy<1
addWaypoint_target_nearestUnit_tagged: 复仇女神
addWaypoint_type: move
addWaypoint_target_nearestUnit_team: own
clearAllWaypoints: true
[hiddenAction_紫砂]
autoTrigger: if self.energy<1 and self.hasUnitInTeam(withTag='复仇女神', withinRange=280) and self.resource.零件<200
deleteSelf: true
addResources: 零件=45
[hiddenAction_紫砂x]
autoTrigger: if self.energy<1 and self.hasUnitInTeam(withTag='复仇女神', withinRange=250) and self.resource.零件>=200
deleteSelf: true
[hiddenAction_紫砂1]
autoTrigger: if self.noUnitInTeam(withTag='复仇女神') and self.energy<1
addResources:  hp=-99999
[action_s1]
autoTrigger: if not self.isOverLiquid
isVisible: false
addResources: hp=-999999
[hiddenAction_图]
autoTrigger: if self.tags(includes= '歼敌') and self.energy>1
addWaypoint_target_nearestUnit_tagged: 海上
addWaypoint_type: attackmove
addWaypoint_target_nearestUnit_team: enemy
[action_bkm]
autoTrigger: if not self.tags(includes= '保险') 
isVisible: false
playAnimation: attack
temporarilyAddTags:保险
[decal_导弹仓1]
image: 导弹平影.png
total_frames: 1
layer: onTop
isVisible: if not self.tags(includes= '开始')
yOffsetRelative:12
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
[decal_导弹井1]
image: 导弹立影.png
total_frames: 1
layer: onTop
isVisible: if self.tags(includes= '准备发射')
yOffsetRelative:12
xOffsetRelative:2
alpha:0.65
onlyWhileAlive:true
[decal_导弹仓开启1]
image: 立起影.png
total_frames: 12
frame: select(self.tags(includes= '打开'), (self.customTimer * 12) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '打开')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:12
xOffsetRelative:2
alpha:0.65
[decal_导弹仓关闭1]
image: 落下影.png
total_frames: 12
frame: select(self.tags(includes= '反向'), (self.customTimer * 12) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '反向')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:12
xOffsetRelative:2
alpha:0.65




[decal_导弹仓]
image: 导弹平.png
total_frames: 1
layer: onTop
isVisible: if not self.tags(includes= '开始')
yOffsetRelative:10
xOffsetRelative:0
onlyWhileAlive:true

[decal_导弹仓开启]
image: 立起.png
total_frames: 12
frame: select(self.tags(includes= '打开'), (self.customTimer * 12) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '打开')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:10
xOffsetRelative:0



[decal_导弹井]
image: 导弹立.png
total_frames: 1
layer: onTop
isVisible: if self.tags(includes= '准备发射')
yOffsetRelative:10
xOffsetRelative:0
onlyWhileAlive:true

[decal_导弹仓关闭]
image: 落下.png
total_frames: 12
frame: select(self.tags(includes= '反向'), (self.customTimer * 12) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '反向')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:10
xOffsetRelative:0

[action_竖起]
text: 竖起战术导弹发射架
displayType: action
buildSpeed: 0s
pos: 0.3
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: 竖起.png
temporarilyAddTags:开始,打开
temporarilyRemoveTags:歼敌
isVisible: if not self.tags(includes= '开始')
whenBuilding_cannotMove: true
allowMultipleInQueue:false
description: 竖起飞鱼导弹艇的战术导弹发射架，\n-对地面敌人进行远距离打击。\n-竖起导弹架后，飞鱼导弹艇将停用鱼雷发射管，并停止移动，\n-启用战术导弹发射器对范围400-2000内的敌方地面单位进行攻击，\n-战术导弹将造成爆炸aoe伤害，发射将额外消耗能量，\n-同时将被判定为战术武器。
isLocked:if self.queueSize> 0 or self.tags(includes= '发射') or self.energy<1 or self.tags(includes= '冇了')
isLockedMessage: 其他动作进行中，请等待，或该舰已没有能量。
alsoQueueAction:nuke
resetCustomTimer: true
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
setUnitStats: moveSpeed=0,maxTurnSpeed=0
[action_nuke]
displayType: action
price: 0
buildSpeed: 1s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 打开
temporarilyAddTags:准备发射
[action_关闭竖起]
text: 关闭战术导弹发射架
displayType: action
buildSpeed: 0s
pos: 0.4
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: 关闭.png
temporarilyRemoveTags:准备发射
temporarilyAddTags:反向
isVisible: if self.tags(includes= '准备发射')
whenBuilding_cannotMove: true
allowMultipleInQueue:false
description: 收起战术导弹发射架，\n-以便使用其他技能。
isLocked:if self.queueSize> 0 or self.tags(includes= '发射') 
isLockedMessage: 其他动作进行中，请等待。
alsoQueueAction:nuke1
resetCustomTimer: true
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
autoTrigger: if self.energy<1 and not self.tags(includes= '冇了')
[action_nuke1]
displayType: action
price: 0
buildSpeed: 1s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 反向,开始
resetUnitStats:true
temporarilyAddTags:歼敌
[action_歼敌]
text: 自动模式
displayType: action
buildSpeed: 0s
pos: 0.5
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/开.png
temporarilyAddTags:歼敌
isVisible: if not self.tags(includes= '歼敌')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令飞鱼级导弹艇主动搜索并攻击敌方水面单位
isLocked:if self.queueSize> 0 or self.energy<1 or self.tags(includes= '准备发射')
isLockedMessage: 其他动作进行中，请等待，或能量已用尽

[action_歼敌1]
text: 手动模式
displayType: action
buildSpeed: 0s
pos: 0.5
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/关.png
temporarilyRemoveTags:歼敌
isVisible: if self.tags(includes= '歼敌')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令飞鱼级导弹艇改为手动控制模式
isLocked:if self.queueSize> 0 or self.energy<1 or self.tags(includes= '准备发射')
isLockedMessage: 其他动作进行中，请等待，或能量已用尽

[graphics]
total_frames: 1
image: 船.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: NONE
splastEffect: true
teamColorsOnTurret: true
movementEffect: CUSTOM:火
movementEffectRate: 12
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shootDelay: 75

maxAttackRange: 2000
turretMultiTargeting: true
[turret_1]
x: -30
y: 19
canShoot: true
invisible: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.7
shoot_flame:  CUSTOM:烟雾*4, CUSTOM:冲击
shoot_light: #FFEECCCC
canAttackFlyingUnits: false
size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackCondition: if self.resource.xk < 1
canAttackMaxAngle: 181
delay:120
limitingRange: 650
limitingMinRange: 150
canOnlyAttackUnitsWithoutTags:悬浮
[turret_2]
x: 30
y: 19
copyFrom: 1
delay:90
warmup:30
linkDelayWithTurret:1
[turret_3]
x: 0
y: 0
invisible: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾1*5,CUSTOM:冲击
shoot_light: #FFEECCCC
projectile: 2
size: 0
turnSpeed: 811
delay:480
limitingMinRange: 500
canAttackCondition: if self.tags(includes= '准备发射')
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 700
areaRadius: 40
areaHitUnderwaterAlways:true
life: 1000
speed: 2
targetSpeed: 4
image: 鱼雷1.png
largeHitEffect: true
deflectionPower: -1
drawSize: 0.75
explodeEffect: CUSTOM:烟雾tp*4,CUSTOM:水波tp,CUSTOM:冲击波dp
explodeEffectOnShield: CUSTOM:烟雾tp*4,CUSTOM:水波tp,CUSTOM:冲击波dp
turnSpeed: 2
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴tp
areaRadiusFromEdge: true
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 3500
life: 1000
areaRadius: 90
alwaysVisibleInFog: true
nukeWeapon: true
speed: 0
image:导弹1.png
targetSpeed: 12
drawSize:0.9
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸m,CUSTOM:气浪m,CUSTOM:冲击波m,CUSTOM:闪光m*2,CUSTOM:弹坑m
targetGroundSpread: 60
disableLeadTargeting: true
trailEffect: true
trailEffectRate: 0.8
areaRadiusFromEdge: true
targetGround: true
ballistic: true
ballistic_height: 260
ballistic_delaymove_height: 210
tags:战术武器
shouldRevealFog: true
deflectionPower: -1
[effect_冲击波dp]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
#——————————发射效果
[effect_烟雾1]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.9
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true
[effect_冲击]
stripIndex: shockwave
life: 45
scaleFrom: 0.3
scaleTo: 2
alpha: 0.8
fadeOut: true
fadeInTime: 2
[effect_烟雾tp]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 3
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
xOffsetRelativeRandom: 10
yOffsetRelativeRandom: 10
createWhenOverLiquid: true
createWhenOverLand: false
[effect_水波tp]
priority: low
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.45
alpha: 1
drawUnderUnits: true
atmospheric: true
createWhenOverLiquid: true
createWhenOverLand: false
[effect_火]
life: 100
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:2
scaleTo: 3
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -0.5
yOffsetRelative	: 0
drawUnderUnits: true
[effect_尾巴tp]
image: SHARED:light_50.png
life: 38
fadeOut: true
attachedToUnit: false
priority: high
color:#FF0092FF
fadeInTime: 2
scaleFrom: 0.2
scaleTo: 0.05
alpha: 0.8
drawUnderUnits: true
yOffsetRelative:-7
#战术飞弹————————
[effect_弹坑m]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true

[effect_气浪m]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 3
scaleTo: 7.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true

[effect_闪光m]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 7
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true

[effect_冲击波m]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_爆炸m]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.5
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[arm_1]
x: -16
y: -1
image_end: 左小.png
image_end_teamColors: true
drawOverBody: true
[arm_2]
x: -14
y: 17
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: true
[arm_3]
x: 16
y: -1
image_end: 右小.png
image_end_teamColors: true
drawOverBody: true
[arm_4]
x: 14
y: 17
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: true
[arm_5]
x: 0
y: -35
image_end: 尾.png
image_end_teamColors: true
drawOverBody: true
[arm_6]
x: 0
y: 0
image_end: 船.png
image_end_teamColors: true
drawOverBody: true
[arm_7]
x: 2
y: -14
image_end: 影子.png
image_end_teamColors: true
[animation_attack]
arm1_0s: {x:0, y:0,dir:0}
arm1_1s: {x:-40, y:0,dir:0}
arm1_99999s: {x:-40, y:0,dir:0}
arm2_0s: {x:0, y:0,dir:0}
arm2_1s: {x:-20, y:0,dir:0}
arm2_99999s: {x:-20, y:0,dir:0}
arm3_0s: {x:0, y:0,dir:0}
arm3_1s: {x:40, y:0,dir:0}
arm3_99999s: {x:40, y:0,dir:0}
arm4_0s: {x:0, y:0,dir:0}
arm4_1s: {x:20, y:0,dir:0}
arm4_99999s: {x:20, y:0,dir:0}
arm5_0s: {x:0, y:0,dir:0}
arm5_1s: {x:0, y:-40,dir:0}
arm5_99999s: {x:0, y:-40,dir:0}

[movement]
movementType: WATER
moveSpeed: 1.2
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
reverseSpeedPercentage: 0.1
maxTurnSpeed: 1
turnAcceleration: 0.05

