


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}
[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}

[core]
name: 余辉军械库
displayText: Заревоармиямеханизмбиблиотека
class: CustomUnitMetadata
price: 2600
maxHp: 5000
maxShield: 7000

shieldRegen: 0.05
isBuilding: true
techLevel: 1
buildSpeed: 0.0005
isBio: false

footprint: -4,-1,4,4
constructionFootprint: -4,-1,4,4
copyFrom: ROOT:/通用特效/单位防护.ini
numBitsOnDeath: 35
armour: 20

showInEditor: false
radius: 60
#displayRadius: 35
tags: 军械库,地面,建筑,无人单位
shieldDisplayOnlyDeflection: true

shieldRenderRadius: 68
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='军械库')
deleteSelf: true
showMessageToPlayer: Эксплойт? Размечтался, в наказание лишний юнит сожрёт сервер눈_눈
addResources: 威胁点数=-${core.price / 25}




[action_等离子场1研发]
price: energy=1,800
text: плазмаполе1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,防弹甲1,防爆甲1,红蓝1
iconImage: 红蓝.png
description: -от низкий плотныйстепеньраскалённыйгорячий плазмагруппастать  медленныйрывокполоса, может быстрыйплавитьразрушатьприходит набег снарядголова и снарядкусок, \n-этотможет уменьшениедвижениеможет  и взрывтипоружиестроить стать  15%урон.
showMessageToPlayer: плазмаполе1Исследование завершено
addResources: energy=1

ai_isHighPriority: true


[action_等离子场2研发]
price: energy=1,1800,蓝晶=600
text: плазмаполе2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红蓝1') and not self.globalTeamTags(includes='红蓝2')

addGlobalTeamTags: 红蓝2,防弹甲2,防爆甲2
removeGlobalTeamTags: 防弹甲1,防爆甲1
addResources: energy=1
iconImage: 红蓝.png
description: -плотныйстепень и тёплыйстепеньещё болееобжигающийгорячий газсостояниеплазмаоблакогруппастать  барьер, \n-может уменьшениедвижениеможет  и взрывтипоружиестроить стать  30% урон.

showMessageToPlayer: плазмаполе2Исследование завершено
ai_isHighPriority: true


[action_偏转场1研发]
price: energy=1,800
text: наклонповоротполе1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防爆甲1,红黄1
iconImage: 红黄.png
description: -от большой количествонаномашинаустройствочеловекгруппастать  облакотуманвидбарьер, может большой количествопотреблятьрассеиватьможет источник и взрывразорватьоружие мощь.\n-может уменьшениеможет источник и взрывтипоружиестроить стать  15%урон.
showMessageToPlayer: наклонповоротполе1Исследование завершено
addResources: energy=1

ai_isHighPriority: true


[action_偏转场2研发]
price: energy=1,1800,蓝晶=600
text: наклонповоротполе2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红黄1') and not self.globalTeamTags(includes='红黄2')

addGlobalTeamTags: 红黄2,光学护甲2,防爆甲2
removeGlobalTeamTags: 光学护甲1,防爆甲1
addResources: energy=1
iconImage: 红黄.png
description: -ещё болеесначалав наномашинаустройствочеловекможет самдвижениеделитьанализприходит набег каждыйвидвысокий может стрельбапучок и снарядкусоки главныйдвижениев  и , \n-может уменьшениеможет источник и взрывтипоружиестроить стать  30% урон.

showMessageToPlayer: наклонповоротполе2Исследование завершено
ai_isHighPriority: true


[action_斥力场1研发]
price: energy=1,800
text: оттолкнутьсилаполе1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防弹甲1,蓝黄1
iconImage: 蓝黄.png
description: -от супервоздушныймеждувнутриособыйобъекткачествопроизводствожизнь определятьк сильныйоттолкнутьсила, может лёгкий лёгкийпрепятствоватьзастрятьприходит набегснарядшарикто естьдо луч, \n-может уменьшениеможет источник и движениеможет типоружиестроить стать  15%урон.
showMessageToPlayer: оттолкнутьсилаполе1Исследование завершено
addResources: energy=1

ai_isHighPriority: true


[action_斥力场2研发]
price: energy=1,1800,蓝晶=600
text: оттолкнутьсилаполе2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='蓝黄1') and not self.globalTeamTags(includes='蓝黄2')

addGlobalTeamTags: 蓝黄2,光学护甲2,防弹甲2
removeGlobalTeamTags: 光学护甲1,防弹甲1
addResources: energy=1
iconImage: 蓝黄.png
description: -более сначалав оттолкнутьсилавыпуститьжизньустройство, его производствожизнь определятьк оттолкнутьсиладажедо может позволитьвысокий может светлиниянаклонповорот, \n-может уменьшениеможет источник и движениеможет типоружиестроить стать  30% урон.

showMessageToPlayer: оттолкнутьсилаполе2Исследование завершено
ai_isHighPriority: true


[action_消除所有护甲1]
price: energy=1,600
text: устранитьвсех стоятьполе
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲1') or self.globalTeamTags(includes='防爆甲1') or self.globalTeamTags(includes='光学护甲1')

removeGlobalTeamTags: 已有,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1
addResources: energy=1


[action_消除所有护甲2]
price: energy=1,600
text: устранитьвсех стоятьполе
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲2') or self.globalTeamTags(includes='防爆甲2') or self.globalTeamTags(includes='光学护甲2')

removeGlobalTeamTags: 已有,防弹甲2,防爆甲2,光学护甲2,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1,蓝黄2,红黄2,红蓝2
addResources: energy=1


[action_反物质1研发]
price: energy=1,1200
text: Антиматериальное оружие 1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='反物质')

addGlobalTeamTags: 反物质1,反物质
addResources: energy=1
description: -может будетмалоколичествоантиобъекткачествооколопучокк снарядголовав  технология, \n-получаетвлияние юнитбудетполучить урондобавитьстать , AOEдобавитьстать , уронбудетповоротдля энергетический урон.\n-имеет эффектюнит:Смертельный Дождь, Ураган, Ударная Волна, Призрак.
showMessageToPlayer: Антиматериальное оружие 1Исследование завершено
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/反物质1.png


[action_反物质2研发]
price: energy=1,2000,蓝晶=1050
text: Антиматериальное оружие 2
displayType: upgrade
buildSpeed: 60s
isVisible: if self.globalTeamTags(includes='反物质1') and not self.globalTeamTags(includes='反物质2')

addGlobalTeamTags: 反物质2
addResources: energy=1
description: -более сначалав околопучоктехнология, разрешаетснарядголоваоколопучоккрайнебольшой качествоколичество антиобъекткачество, \n-дажедо может используя сначалав супервоздушныйпузырьформастать антиобъекткачествопучокпрямоатака, \n-получаетвлияние юнитбудетбудетполучить урондобавитьстать , AOEдобавитьстать , поворотдля энергетический урон.\n-имеет эффектюнит:Аджирион, нулевой элемент, Кровавая Звезда, Колебательная волна, Охотник-убийца, Священное Копьё, переворот.
showMessageToPlayer: Антиматериальное оружие 2Исследование завершено
iconImage: ROOT:/余辉军团/单位特效/反物质2.png

ai_isHighPriority: true


[action_裂解炮1研发]
price: energy=1,900
text: Расщепляющая пушка 1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='裂解炮')

addGlobalTeamTags: 裂解炮1,裂解炮
addResources: energy=1
description: -расщеплениепушкаЗапустить тип особый частицамладшийпучок,  и цельстолкновениебить, когда будетпривлекатьвыпуститьпьесаяростный ядрорасщеплятьизменитьантидолжен .\n-получаетвлияние юнитбудетполучить урондобавитьстать , но толькоможет строить стать очкопоражение, уронбудетповоротдля кинетический урон.\n-имеет эффектюнит:Смертельный Дождь  Чистильщик, Ворон, Железный Всадник, Часовой, Священное Копьё.
showMessageToPlayer: Расщепляющая пушка 1Исследование завершено
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/裂解炮1.png


[action_裂解炮2研发]
price: energy=1,2000,蓝晶=1050
text: расщеплениепушка2
displayType: upgrade
buildSpeed: 40s
isVisible: if self.globalTeamTags(includes='裂解炮1') and not self.globalTeamTags(includes='裂解炮2')

addGlobalTeamTags: 裂解炮2
addResources: energy=1
description: -новый  типрасщеплениепушкадобычаиспользует более имеет эффект массовый ускоритель, может быстрыйЗапустить снарядшарик, \n- также может собратьколлекцияболее единицамощь очкопоместить типатака, \n-получаетвлияние юнитбудетбудетполучить урондобавитьстать , но толькоможет строить стать очкопоражение, поворотдля кинетический урон.\n-имеет эффектюнит:Тёмный Ангел, Адский Дракон, Ревун, Охотник-убийца, вздох, Ударная Волна.
showMessageToPlayer: расщеплениепушка2Исследование завершено
iconImage: ROOT:/余辉军团/单位特效/裂解炮2.png

ai_isHighPriority: true


[action_反应核科技1研发]
price: energy=1,2000
text: антидолжен ядротехнология1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='反应核')

addGlobalTeamTags: 曲线核1,反应核,护盾充能
addResources: energy=1
description: -антидолжен ядротехнологияданныебудетвключаетПозитронное ядро1 и кривойлинияядро1уровеньтехнология.\n-Империяпоздний периодкривойлинияядроИмператорвыпуститьясный , когда ждать, кривойлинияядропривлекатьвыпустить дрожьдвижениене младшийк Когда годсупервоздушныймежду выпуститьтекущий.\n-кривойлинияядроразрешаетопределённый боевойюнитвременно, когда прыгатьвходит червоточинаи истинныйв данный моментнамерениесправедливостьна реальныйтекущий"мгновенноперемещениедвижение".\n-, получаетвлияние юнитбудетполучить "Кривой прыжок"техникаможет .\n-имеет эффектюнит:Смертельный Дождь, Колебательная волна, Ревун, Призрак, Аджирион.\n-Позитронное ядроэто самыйэффективный антиобъекткачествокуча, может обеспечиватьдаватьбольшой количество щитможет количество.\n-Имея Позитронное ядро юнитможет в отделениебойпозади то естьдо в бойв быстрыйвозвратвосстановитьщит.\n-получаетвлияние юниткаждыйсекбудетквотаснаружи возвратвосстановить10очкощит.\n-имеет эффектюнит:3-й уровенькомандный центртехнологияводаплоскийможет производство (не содержитодинуровень и 2-й уровеньюнит), всех Имея щит Заревоюнит.(не включаетздание)
showMessageToPlayer: антидолжен ядротехнология1Исследование завершено
ai_isHighPriority: true

iconImage: 堆.png


[action_不稳定反应堆1研发]
price: energy=1,1500
text: Нестабильный реактор 1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='反应堆')

addGlobalTeamTags: 反应堆1,反应堆
addResources: energy=1
description: -Нестабильный реакторзапретиспользует мирвсе устройствои добавитьдобавитьне стабильный размахвыпуститьядротопливо.\n-Имея Нестабильный реактор юнитв смертьпозади может выпуститьодин уронсамыйбольшой для 3000очко может источниквзрыв.\n-и в комплектеэлектричествомагнитныйпаралич.\n-имеет эффектюнит:Чистильщик, предзнаменование, вздох, Железный Всадник, Ревун.
showMessageToPlayer: Нестабильный реактор 1Исследование завершено
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/反应堆1.png


[action_重子兵器1研发]
price: energy=1,1500
text: барионное оружие 1
displayType: upgrade
buildSpeed: 40s
isVisible: if not self.globalTeamTags(includes='重子1')

addGlobalTeamTags: 重子1
addResources: energy=1
description: -тяжёлый младшийоружиеэто чтобы крайневысокий плотныйстепень критическийобъекткачестводелатьдля уронисточник оружие, это имперская армияогоньбиблиотекав самыйединицамощь оружиесреди .\n-одинуровень тяжёлый младшийоружиеможет производствожизньодин атомуровень чёрная дыра, будетпотому чтодля быстрозолотоизлучениестрельбабыстрыйуничтожитьрассеиватьи привлекатьвыпуститьогромныйвзрыв.\n-получаетвлияние юниторужиеуронбудетизменитьстать двасегментвзрывной урон, и одновременноуронвоздушныйв  и наземные юниты на пути.\n-имеет эффектюнит: предзнаменование, Орион, вздох, аэростат, Скрытник, Ворон.
showMessageToPlayer: барионное оружие 1Исследование завершено
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/重子1.png


[action_重子兵器2研发]
price: energy=1,2500,蓝晶=1300,科技=-1
text: барионное оружие 2
displayType: upgrade
buildSpeed: 70s
isVisible: if self.globalTeamTags(includes='重子1') and not self.globalTeamTags(includes='重子2')

addGlobalTeamTags: 重子2
addResources: energy=1,科技=1
description: -2-й уровеньтяжёлый младшийоружиеможет пучоксвязыватьи производствожизнькачествоколичествоболее большой  критическийобъекткачество, \n-одновременнотакже частьрешениетяжёлый младшийоружиеогромныйнет чем недостатокочко, \n-получаетвлияние юнитбудетможет строить стать двасегментвзрывной урон, одновременноуронвоздушныйв  и наземные юниты на пути.\n-имеет эффектюнит:Белый Карлик, Аджирион, Адский Дракон, Призрак, Опустошитель, нулевой элемент.\n-Небесный Охотник предварительная технология
showMessageToPlayer: барионное оружие 2Исследование завершено
iconImage: ROOT:/余辉军团/单位特效/重子2.png

ai_isHighPriority: true
isLocked: if self.resource(type="科技",greaterThan=0)
isLockedMessage: уже имеет другие  объектв разработка


[action_立场科技研发]
price: energy=1,2000,科技1=-1,蓝晶=500
text: стоятьполетехнология
displayType: upgrade
buildSpeed: 50s
isVisible: if not self.globalTeamTags(includes='立场1')

addGlobalTeamTags: 撕裂立场,立场1,隐形立场
addResources: energy=1,科技1=1
description: -стоятьполетехнологияданныевключаетРазрыв силового полятехнология.\n-Разрыв силового поляможет в большой радиусвнутрипроизводствожизньтип крайнеего не стабильный стоятьполе, может из делитьмладшийструктурана полностьюуничтожитьвраги.\n-Разрыв силового полябудетнепрерывныйпротив имеет эффектрадиусвнутривсех врагипроизводствожизньнепрерывныйнейтральный урон, многоштРазрыв силового поляможет складыватьдобавить.\n-имеет эффектюнит:Скрытник, Опустошитель, Парящая крепость.
showMessageToPlayer: стоятьполетехнологияИсследование завершено
ai_isHighPriority: true

iconImage: 场.png
isLocked: if self.resource(type="科技1",greaterThan=0)
isLockedMessage: уже имеет другие  объектв разработка


[action_克莱因瓶1研发]
price: energy=1,2500,蓝晶=600
text: бутылка Клейна1
displayType: upgrade
buildSpeed: 50s
isVisible: if not self.globalTeamTags(includes='瓶')

addGlobalTeamTags: 克莱因瓶1,瓶
addResources: energy=1
description: -бутылка Клейнаэто тип кожажизнь щиттехнология, может жизньстать одинслойот сто миллионовдесять тысячштделитьмладшийуровеньчервоточинагруппастать  защитазащитаслой.\n-всех  и  контакт объекттеловсе будетбитьрассеиватьстать делитьмладшийи следоватьмашинателепортдо вселенная каждыйштуголпадение.\n-почти нетимеет любойсредствоможет битьпробитьэтотслойщит, кромене щитиз внутричастьчерепицаразблокировка.\n-открытьпозади юнитживойдвижениекороткий временно нет враги.\n-имеет эффектюнит:Опустошитель, нулевой элемент.
showMessageToPlayer: бутылка Клейна1Исследование завершено
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/克莱因瓶1.png


[graphics]
total_frames: 1
image: 主体.png
image_back: ROOT:/通用特效/NO.png
image_wreak: 死亡.png
image_turret: NONE

image_shield: 护盾.png
#imageScale:0.75


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[effect_烟雾]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.5

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[arm_1]
x: -10.5
y: 32
image_end: 块.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: -24.5
y: 32
image_end: 块.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_3]
x: -38.5
y: 32
image_end: 块.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_4]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_5]
x: -10
y: 72
image_end: 块1.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[animation_1]
onActions: idle
blendIn: 4s
blendOut: 5s
arm1_1s: {x:0, y:13}
arm2_2s: {x:0, y:13}

arm3_3s: {x:0, y:13}
arm5_4.5s: {x:-24, y:0}


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
ai_upgradePriority: 0.07
maxGlobal: 12


