


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}
[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}

[core]
name: 余辉军械库
class: CustomUnitMetadata
price: 2600
maxHp: 5000
maxShield: 7000

shieldRegen: 0.05
isBuilding: true
techLevel: 1
buildSpeed: 0.0005
isBio: false

footprint: -4,-1,4,4
constructionFootprint: -4,-1,4,4
copyFrom: ROOT:/通用特效/单位防护.ini
numBitsOnDeath: 35
armour: 20

showInEditor: false
radius: 60
#displayRadius: 35
tags: 军械库,地面,建筑,无人单位
shieldDisplayOnlyDeflection: true

shieldRenderRadius: 68
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='军械库')
deleteSelf: true
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈
addResources: 威胁点数=-${core.price / 25}




[action_等离子场1研发]
price: energy=1,800
text: 等离子场1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,防弹甲1,防爆甲1,红蓝1
iconImage: 红蓝.png
description: -由低密度炽热的等离子组成的缓冲带，可以快速熔毁来袭的弹头与弹片，\n-这能减少动能和爆炸类武器造成的15%伤害。
showMessageToPlayer: 等离子场1已经研发完成
addResources: energy=1

ai_isHighPriority: true


[action_等离子场2研发]
price: energy=1,1800,蓝晶=600
text: 等离子场2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红蓝1') and not self.globalTeamTags(includes='红蓝2')

addGlobalTeamTags: 红蓝2,防弹甲2,防爆甲2
removeGlobalTeamTags: 防弹甲1,防爆甲1
addResources: energy=1
iconImage: 红蓝.png
description: -密度和温度更加灼热的气态等离子云组成的屏障，\n-能减少动能和爆炸类武器造成的30%的伤害。

showMessageToPlayer: 等离子场2已经研发完成
ai_isHighPriority: true


[action_偏转场1研发]
price: energy=1,800
text: 偏转场1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防爆甲1,红黄1
iconImage: 红黄.png
description: -由大量纳米机器人组成的云雾状屏障，可以大量耗散能源和爆破武器的威力。\n-能减少能源和爆炸类武器造成的15%伤害。
showMessageToPlayer: 偏转场1已经研发完成
addResources: energy=1

ai_isHighPriority: true


[action_偏转场2研发]
price: energy=1,1800,蓝晶=600
text: 偏转场2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红黄1') and not self.globalTeamTags(includes='红黄2')

addGlobalTeamTags: 红黄2,光学护甲2,防爆甲2
removeGlobalTeamTags: 光学护甲1,防爆甲1
addResources: energy=1
iconImage: 红黄.png
description: -更加先进的纳米机器人能自动分析来袭的各种高能射束和弹片并主动中和，\n-能减少能源和爆炸类武器造成的30%的伤害。

showMessageToPlayer: 偏转场2已经研发完成
ai_isHighPriority: true


[action_斥力场1研发]
price: energy=1,800
text: 斥力场1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防弹甲1,蓝黄1
iconImage: 蓝黄.png
description: -由超空间内特殊物质产生的定向强斥力，可以轻易阻滞来袭弹丸乃至光束，\n-能减少能源和动能类武器造成的15%伤害。
showMessageToPlayer: 斥力场1已经研发完成
addResources: energy=1

ai_isHighPriority: true


[action_斥力场2研发]
price: energy=1,1800,蓝晶=600
text: 斥力场2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='蓝黄1') and not self.globalTeamTags(includes='蓝黄2')

addGlobalTeamTags: 蓝黄2,光学护甲2,防弹甲2
removeGlobalTeamTags: 光学护甲1,防弹甲1
addResources: energy=1
iconImage: 蓝黄.png
description: -更先进的斥力发生器，其产生的定向斥力甚至能让高能光线偏转，\n-能减少能源和动能类武器造成的30%的伤害。

showMessageToPlayer: 斥力场2已经研发完成
ai_isHighPriority: true


[action_消除所有护甲1]
price: energy=1,600
text: 消除所有立场
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲1') or self.globalTeamTags(includes='防爆甲1') or self.globalTeamTags(includes='光学护甲1')

removeGlobalTeamTags: 已有,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1
addResources: energy=1


[action_消除所有护甲2]
price: energy=1,600
text: 消除所有立场
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲2') or self.globalTeamTags(includes='防爆甲2') or self.globalTeamTags(includes='光学护甲2')

removeGlobalTeamTags: 已有,防弹甲2,防爆甲2,光学护甲2,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1,蓝黄2,红黄2,红蓝2
addResources: energy=1


[action_反物质1研发]
price: energy=1,1200
text: 反物质兵器1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='反物质')

addGlobalTeamTags: 反物质1,反物质
addResources: energy=1
description: -能将少量反物质约束于弹头中的科技，\n-受影响的单位将获得伤害加成，AOE加成，伤害将转化为能源伤害。\n-有效单位：死亡之雨，狂风，冲击波，亡魂。
showMessageToPlayer: 反物质兵器1已经研发完成
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/反物质1.png


[action_反物质2研发]
price: energy=1,2000,蓝晶=1050
text: 反物质兵器2
displayType: upgrade
buildSpeed: 60s
isVisible: if self.globalTeamTags(includes='反物质1') and not self.globalTeamTags(includes='反物质2')

addGlobalTeamTags: 反物质2
addResources: energy=1
description: -更先进的约束技术，允许弹头约束极大质量的反物质，\n-甚至可以利用先进的超空泡形成反物质束直接攻击，\n-受影响的单位将会获得伤害加成，AOE加成，转为能源伤害。\n-有效单位：阿吉里恩，零素，血星，震荡波，猎杀者，圣枪，颠覆者。
showMessageToPlayer: 反物质兵器2已经研发完成
iconImage: ROOT:/余辉军团/单位特效/反物质2.png

ai_isHighPriority: true


[action_裂解炮1研发]
price: energy=1,900
text: 裂解炮1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='裂解炮')

addGlobalTeamTags: 裂解炮1,裂解炮
addResources: energy=1
description: -裂解炮发射一种特殊的粒子束，与目标撞击时会引发剧烈的核裂变反应。\n-受影响的单位将获得伤害加成，但只能造成点杀伤，伤害将转化为动能伤害。\n-有效单位：死亡之雨  清道夫，渡鸦，铁骑，哨兵，圣枪。
showMessageToPlayer: 裂解炮1已经研发完成
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/裂解炮1.png


[action_裂解炮2研发]
price: energy=1,2000,蓝晶=1050
text: 裂解炮2
displayType: upgrade
buildSpeed: 40s
isVisible: if self.globalTeamTags(includes='裂解炮1') and not self.globalTeamTags(includes='裂解炮2')

addGlobalTeamTags: 裂解炮2
addResources: energy=1
description: -新型裂解炮采用更有效的质量加速器，可以快速发射弹丸，\n-又可以聚集更具威力的点放式攻击，\n-受影响的单位将会获得伤害加成，但只能造成点杀伤，转为动能伤害。\n-有效单位：暗天使，地狱之龙，咆哮者，猎杀者，叹息，冲击波。
showMessageToPlayer: 裂解炮2已经研发完成
iconImage: ROOT:/余辉军团/单位特效/裂解炮2.png

ai_isHighPriority: true


[action_反应核科技1研发]
price: energy=1,2000
text: 反应核科技1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='反应核')

addGlobalTeamTags: 曲线核1,反应核,护盾充能
addResources: energy=1
description: -反应核科技数据将包括正电子芯核1和曲线核1级科技。\n-帝国末期曲线核被皇帝发明的时候，曲线核引发的震动不亚于当年超空间的发现。\n-曲线核允许特定的作战单位暂时跳入虫洞并真正意义上实现了“瞬间移动”。\n-，受影响的单位将获得“曲线跳跃”技能。\n-有效单位：死亡之雨，震荡波，咆哮者，亡魂，阿吉里恩。\n-正电子芯核是最高效的反物质堆，可以供给大量的护盾能量。\n-拥有正电子芯核的单位可以在脱离战斗后乃至在战斗中快速回复护盾。\n-受影响的单位每秒将额外回复10点护盾。\n-有效单位：三级指挥中心科技水平能制造的（不包含一级和二级单位），所有拥有护盾的余辉单位。（不包括建筑）
showMessageToPlayer: 反应核科技1已经研发完成
ai_isHighPriority: true

iconImage: 堆.png


[action_不稳定反应堆1研发]
price: energy=1,1500
text: 不稳定反应堆1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='反应堆')

addGlobalTeamTags: 反应堆1,反应堆
addResources: energy=1
description: -不稳定反应堆禁用了安全装置并添加了不稳定的挥发性核燃料。\n-拥有不稳定反应堆的单位在死亡后可以释放一个伤害最大为3000点的能源爆炸。\n-并附带电磁瘫痪效果。\n-有效单位：清道夫，预兆，叹息，铁骑，咆哮者。
showMessageToPlayer: 不稳定反应堆1已经研发完成
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/反应堆1.png


[action_重子兵器1研发]
price: energy=1,1500
text: 重子兵器1
displayType: upgrade
buildSpeed: 40s
isVisible: if not self.globalTeamTags(includes='重子1')

addGlobalTeamTags: 重子1
addResources: energy=1
description: -重子兵器是以极高密度的临界物质作为伤害源的武器，是帝国军火库中最具威力的武器之一。\n-一级的重子兵器可以产生一个原子级的黑洞，会因为霍金辐射迅速消散并引发巨大爆炸。\n-受影响的单位武器伤害将变成两段爆炸伤害，并同时伤害空中和地面单位。\n-有效单位： 预兆，猎户座，叹息，气球，潜伏者，渡鸦。
showMessageToPlayer: 重子兵器1已经研发完成
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/重子1.png


[action_重子兵器2研发]
price: energy=1,2500,蓝晶=1300,科技=-1
text: 重子兵器2
displayType: upgrade
buildSpeed: 70s
isVisible: if self.globalTeamTags(includes='重子1') and not self.globalTeamTags(includes='重子2')

addGlobalTeamTags: 重子2
addResources: energy=1,科技=1
description: -二级重子兵器能束缚并产生质量更大的临界物质，\n-同时也部分解决了重子兵器巨大无比的缺点，\n-受影响的单位将可以造成两段爆炸伤害，同时伤害空中和地面单位。\n-有效单位：白矮星，阿吉里恩，地狱之龙，亡魂，浩劫，零素。\n-苍穹猎者的前置科技
showMessageToPlayer: 重子兵器2已经研发完成
iconImage: ROOT:/余辉军团/单位特效/重子2.png

ai_isHighPriority: true
isLocked: if self.resource(type="科技",greaterThan=0)
isLockedMessage: 已经有其他的设施在研发了


[action_立场科技研发]
price: energy=1,2000,科技1=-1,蓝晶=500
text: 立场科技
displayType: upgrade
buildSpeed: 50s
isVisible: if not self.globalTeamTags(includes='立场1')

addGlobalTeamTags: 撕裂立场,立场1,隐形立场
addResources: energy=1,科技1=1
description: -立场科技数据包括撕裂立场科技。\n-撕裂立场能在大范围内产生一种极其不稳定的立场，能从分子结构上彻底摧毁敌人。\n-撕裂立场将持续对有效范围内所有敌人产生持续中性伤害，多个撕裂立场效果可以叠加。\n-有效单位：潜伏者，浩劫，浮岛要塞。
showMessageToPlayer: 立场科技已经研发完成
ai_isHighPriority: true

iconImage: 场.png
isLocked: if self.resource(type="科技1",greaterThan=0)
isLockedMessage: 已经有其他的设施在研发了


[action_克莱因瓶1研发]
price: energy=1,2500,蓝晶=600
text: 克莱因瓶1
displayType: upgrade
buildSpeed: 50s
isVisible: if not self.globalTeamTags(includes='瓶')

addGlobalTeamTags: 克莱因瓶1,瓶
addResources: energy=1
description: -克莱因瓶是一种革命性的护盾技术，可以生成一层由亿万个分子级虫洞组成的保护层。\n-所有与之接触的物体都会被打散成分子并随机传送至宇宙的各个角落。\n-几乎没有任何手段可以击穿这层护盾，除非护盾从内部瓦解。\n-开启后单位活动短暂的无敌效果。\n-有效单位：浩劫，零素。
showMessageToPlayer: 克莱因瓶1已经研发完成
ai_isHighPriority: true

iconImage: ROOT:/余辉军团/单位特效/克莱因瓶1.png


[graphics]
total_frames: 1
image: 主体.png
image_back: ROOT:/通用特效/NO.png
image_wreak: 死亡.png
image_turret: NONE

image_shield: 护盾.png
#imageScale:0.75


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[effect_烟雾]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.5

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[arm_1]
x: -10.5
y: 32
image_end: 块.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: -24.5
y: 32
image_end: 块.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_3]
x: -38.5
y: 32
image_end: 块.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_4]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_5]
x: -10
y: 72
image_end: 块1.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[animation_1]
onActions: idle
blendIn: 4s
blendOut: 5s
arm1_1s: {x:0, y:13}
arm2_2s: {x:0, y:13}

arm3_3s: {x:0, y:13}
arm5_4.5s: {x:-24, y:0}


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
ai_upgradePriority: 0.07
maxGlobal: 12


