


[core]
name: 重型炮塔底座t1
displayText: Основание тяжёлой турели t1
class: CustomUnitMetadata
price: 3500
maxHp: 14000
footprint: -2,-2,1,1

constructionFootprint: -2,-2,1,1
buildingToFootprintOffsetX: -1
#buildingToFootprintOffsetY:13
techLevel: 1
buildSpeed: 0

radius: 25
#buildingSelectionOffset: -8
isBuilding: true
copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.12

isBio: false
effectOnDeath: CUSTOM:烟雾2*2,CUSTOM:爆炸*1
tags: 地面,灰影建筑,建筑
armour: 25


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[action_寂灭]
convertTo: 寂灭t1
displayType: action
text: Развернуть турель «Гибель» t1
description: Огромная револьверная зенитная пушка эпохи Альфрида, которая могла устанавливаться только на корабли класса линкор.\n-Её цель — быстро уничтожать атакующие самолёты различных типов.\n-Как тогда, так и сейчас, заградительный огонь «Гибели» разрушителен для любой авиации.\n-Сегодня это старое оружие используется как стационарные турели, охраняющие территорию Скитальцев.\n-Атакует только воздух, энергетический урон. Бонус урона по нелёгким сверхтяжёлым юнитам.
price: 4000

isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, либо это здание должно быть обесточено, и одновременно можно развернуть только одну турель
buildSpeed: 20s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='科斯塔3')


[action_灭世]
convertTo: 灭世t1
displayType: action
text: Развернуть турель «Истребитель миров» t1
description: 一种发射毁灭性光束洪流的重型主炮，\n-灭世的灵感源自于只配给诺瓦帝国超无畏舰救赎者级的重型武器，零点能光矛，\n-零点能光矛能汇聚令人难以置信的能量在瞬间贯穿任何规模的战舰乃至空间站，\n-可惜的是，随着帝国四分五裂，余辉和太空浪人各得到了他的一半蓝图，\n-因为缺乏最关键的射击模块，太空浪人只能在零点能光矛的结构上创造了灭世，\n-即便如此，灭世的依然可以轻松消灭绝大部分重型单位乃至战舰，\n-对地对空对高空，能源伤害，反掩体
price: 2500,awz=150

isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, либо это здание должно быть обесточено, и одновременно можно развернуть только одну турель
buildSpeed: 20s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='法雅德3')


[action_洪水]
convertTo: 洪水t1
displayType: action
text: Развернуть турель «Потоп» t1
description: Крупные противодесантные турели, широко распространённые на территории Буэнфендель в эпоху Воюющих государств Древних Людей.\n-Две 400-миллиметровые частицевые пушки с автоматическими заряжающими обрушивают на любые осмелившиеся высадиться наземные войска\n-огромный, но мощный заградительный огонь. Тогда ни один наземный юнит не мог противостоять снарядам «Потопа» в лоб.\n-По сей день «Потоп» используется как тяжёлое оборонительное укрепление против стальной лавины Зарева на земле.\n-Атакует только землю, кинетический урон. Бонус урона по сверхтяжёлым юнитам.
price: 1500,awz=90

isVisible: if self.globalTeamTags(includes='科斯塔2')
buildSpeed: 15s
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, либо это здание должно быть обесточено, и одновременно можно развернуть только одну турель


[graphics]
total_frames: 1
image: ROOT:/太空浪人/建筑特效/大底座t1.png
image_wreak: ROOT:/太空浪人/建筑特效/大底座t1死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
imageScale: 0.9

turretImageScale: 0.9


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shootDelay: 150

turretSize: 23
turretTurnSpeed: 3
maxAttackRange: 480
#aimOffsetSpread: -0.01


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 重型炮塔底座t1传送
ai_upgradePriority: 0.07
maxEachBase: 6
maxGlobal: 30


