


[core]
name: 轨道卫星炮1
displayText: Орбитальная спутниковая пушка1
displayDescription: 【Уровень t4】【Механический юнит】【Воздушный юнит】【Высотный юнит】【сопровождающий юнит】\n-Тактическое назначение:сопровождающий типпротиводиночный体浮游пушка，вооружение：\n-▲гигантскийРельсотронX1 только по земле кинетический урон \n-Немезида尾部несёт ПустонебоРельсотронплатформа，главный体использоватьдовоенный вселенная探测卫星модификация，\n-веговодиночный独загружает один малый 钍裂变堆保证энергия供给，\n-одновременноиспользоватьодин 伸缩Рельсотронв качествеглавныйоружие，указанныйоружиезапускать большой体积磁化сплав棒впройти черезЭлектромагнитсила 加速стяжёлыйсила 加становитьсяегопосле，\n-будетбудетстановитсянет坚не摧，加егоегоиспользоватьатака顶снаряд道，против抗боевой корабль эффект格внененеправильный，\n-нонуждаетсяВнимание является，верх帝его杖одиночный次несёт Боеприпасыесть限，Боеприпасыиспользоватьсветпосленужно回до本体补充。
price: 0
maxHp: 20000

techLevel: 1
buildSpeed: 0s
copyFrom: ROOT:/通用特效/单位防护.ini
availableInDemo: true
armour: 20
showInEditor: false
radius: 70
displayRadius: 70
softCollisionOnAll: 10
isBio: false
tags: 飞机,高空,卫星炮,伴生单位
canOnlyBeAttackedByUnitsWithTags:反高空
energyMax: 12
energyRegen: 0
energyNeedsToRechargeToFull: true
fogOfWarSightRange: 18
effectOnDeath:CUSTOM:碎片,CUSTOM:碎片1,CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大钢珠*2,CUSTOM:巨大闪光
effectOnDeathGroundCollision: CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大钢珠*2,CUSTOM:巨大闪光
[hiddenAction_紫砂1]
autoTrigger: if self.noUnitInTeam(withTag='复仇女神')
addResources:  hp=-99999
[action_高空]
text: высотныйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: находится вочень высокийвысокий度 истребительибоевой корабль。\n-вэтотвысокий度низ，толькоесть поверхностьиПустовспециальный против высотныхюнит，а такжевысотныйюнитможетатакадоуказанныйюнит，\n-одновременно，большинствовысотныйюнитможет互相атака，иможетатакаобычныйвоздушный юнит，\n-толькоестьспециальный высотныйюнитможетпо землеатака。
[action_歼敌]
text: автоматический模式
displayType: action
buildSpeed: 0s
pos: 0.5
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/开.png
temporarilyAddTags:歼敌
isVisible: if not self.tags(includes= '歼敌')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令Орбитальная спутниковая пушкаавтоматический寻敌ибой
isLocked:if self.queueSize> 0 or self.energy<0.58 or self.tags(includes= '往回走')
isLockedMessage: выполняется другое действие，пожалуйста, подождите，或энергияужеиспользовать尽，或卫星правильныйв 召回。

[action_歼敌1]
text: ручной模式
displayType: action
buildSpeed: 0s
pos: 0.5
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/关.png
temporarilyRemoveTags:歼敌
isVisible: if self.tags(includes= '歼敌')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令Орбитальная спутниковая пушкаизменятьв качестверучнойуправление模式
isLocked:if self.queueSize> 0 or self.energy<0.58 or self.tags(includes= '往回走')
isLockedMessage: выполняется другое действие，пожалуйста, подождите，或энергияужеиспользовать尽，或卫星правильныйв 召回。
[hiddenAction_图]
autoTrigger: if self.tags(includes= '歼敌') and self.energy>=0.58
addWaypoint_target_nearestUnit_tagged: 地面
addWaypoint_type: attackmove
addWaypoint_target_nearestUnit_team: enemy
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[decal_影子]
image: 轨影.png
total_frames: 1
layer: shadow
isVisible: if not self.hasParent and not self.tags(includes= '变形金刚')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
hOffset:-140
alpha:0.6
basePositionFromTurret: 2
[decal_影子1]
image: 轨2影.png
total_frames: 1
layer: shadow
isVisible: if not self.hasParent and not self.tags(includes= '变形金刚')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
hOffset:-140
alpha:0.6
basePositionFromTurret: 1
[decal_转子]
image: 动画1.png
total_frames: 2
frame: (self.customTimer * 18) % 2
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-0.5
yOffsetRelative:-38.5
isVisible:true
onlyWhileAlive:true
[decal_装填]
image: 装填动画.png
total_frames: 21
frame: select(self.tags(includes= '切枪'), (self.customTimer * 15) % 21, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:-5
xOffsetRelative:-0.5

[hiddenAction_反馈]
autoTriggerOnEvent: destroyed
removeGlobalTeamTags:wx回收
[hiddenAction_disconnect]
autoTrigger:if self.noUnitInTeam(withTag='出击指令wx') and not self.tags(includes= '往回走')
temporarilyAddTags:往回走
[hiddenAction_discssonnect1]
autoTrigger:if self.energy<0.58 and not self.tags(includes= '往回走')
temporarilyAddTags:往回走


[action_召回]
text:返回мать舰
displayType: action
buildSpeed: 0s
pos: 0.2
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/回家.png
allowMultipleInQueue:false
description: 命令Орбитальная спутниковая пушка立刻返回мать舰
isLocked:if self.tags(includes= '往回走')
isLockedMessage: правильныйв返回в
temporarilyAddTags:往回走
[hiddenAction_disconnect1]
autoTrigger:if self.tags(includes= '往回走') and self.hasUnitInTeam(withTag='复仇女神', withinRange=700) 
alsoQueueAction:变形
temporarilyAddTags:立刻回家,变形金刚

[action_变形]
convertTo: 轨道卫星炮
displayType: action
price: 0
buildSpeed: 2.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
allowMultipleInQueue:false
whenBuilding_playAnimation: 部署
temporarilyAddTags:可以回wx
temporarilyRemoveTags:变形金刚
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed
[action_往回走]
temporarilyRemoveTags:歼敌
buildSpeed: 0s
price:0
isVisible: false
canPlayerCancel: false
autoTrigger:if self.tags(includes= '往回走')
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged:复仇女神
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: move
addWaypoint_target_nearestUnit_maxRange:99999
addGlobalTeamTags:wx回收
[hiddenAction_装填]
addResources: 弹药=1
[hiddenAction_装]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
whenBuilding_cannotMove:false
allowMultipleInQueue:false
autoTrigger: if self.resource.弹药>0.5 and not self.tags(includes= '切枪')
alsoQueueAction: ax
[action_ax]
displayType: action
price: 0
buildSpeed: 0.8s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
alsoQueueAction: bx
resetCustomTimer: true
temporarilyAddTags: 切枪
[action_bx]
displayType: action
price: 0
buildSpeed: 1.3s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
addResources:弹药=-1
[graphics]
total_frames: 1
image: NO.png
image_wreak: 似主.png
image_turret: NONE

image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3,CUSTOM:火4


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 4
maxAttackRange:3000
shootDelay: 5
isFixedFiring: true
turretRotateWithBody: true

[turret_0]
x: 0
y: 0
invisible: true
canShoot: false
canAttackCondition:if self.energy>0.57
[turret_1]
x: 0
y: 72
projectile: 1
shoot_sound: ROOT:/通用特效/高斯炮.wav
shoot_sound_vol: 1.5
shoot_flame: CUSTOM:烟雾*8,CUSTOM:粒子*16,CUSTOM:闪光,CUSTOM:冲击波*3,CUSTOM:冲击波1
canShoot: true
recoilOffset: -55
recoilOutTime: 5
recoilReturnTime: 70
delay: 460
size:40
image: 轨2.png
attachedTo: 0
slave: true
limitingMinRange: 500
canAttackFlyingUnits: false
invisible:if self.tags(includes= '变形金刚')
canAttackCondition:if not self.tags(includes= '变形金刚') and self.resource.弹药<0.5
onShoot_triggerActions:装填
energyUsage:0.58
[turret_2]
x: 0
y: 70
projectile: 2
shoot_sound:NONE
canShoot: true
recoilOffset: -24
recoilOutTime: 10
recoilReturnTime: 40
delay: 460
size:22
image: 轨.png
attachedTo: 0
slave: true
limitingMinRange: 500
invisible:if self.tags(includes= '变形金刚')
canAttackCondition:if not self.tags(includes= '变形金刚')  and self.energy>0.57
[turret_3]
x: 0
y: 55
attachedTo: 0
projectile: 2
slave: true
delay: 35
shoot_flame: CUSTOM:电弧*3
canShoot: true
invisible: true
canAttackCondition:if not self.tags(includes= '变形金刚') and self.energy>0.57
[projectile_1]
@copyFromSection: template_动能
directDamage: 28500
life: 400
speed: 25
image: ROOT:/太空浪人/单位特效/星星1.png
targetSpeed: 33
drawSize: 0.7
explodeEffect: NONE
explodeEffectOnShield: NONE
lightSize: 0.75
trailEffectRate: 0.4
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1*2,CUSTOM:尾巴3
lightColor: #FFFF1200
spawnUnit: 小核爆(addResources=撞击:1)
[projectile_2]
directDamage: 0
life: -4
instant: true
drawSize: 0
frame: 33
color: #FF25E0AF
explodeEffect: none
#——————————开炮效果
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.5
scaleTo: 3.75
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true
[effect_闪光]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 9
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 3.5
alpha: 0.8
fadeOut: true
fadeInTime: 2
color: #FFFF1200
delayedStartTimerRandom:10
[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1
xSpeedRelativeRandom: 0.6
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2.7
#xOffsetRelative:-2
atmospheric: true

[effect_电弧]
image: ROOT:/通用特效/红电弧.png
life: 70
priority: critical
attachedToUnit: true
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.9
total_frames: 8
animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
dirOffset:150
delayedStartTimerRandom:15
xOffsetRelativeRandom:10
yOffsetRelativeRandom:45
dirOffsetRandom: 360
[effect_冲击波1]
life: 60
priority: critical
attachedToUnit: false
alpha: 0.8
fadeOut: true
fadeInTime: 2
scaleFrom: 0.8
scaleTo: 2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
#——————————
[effect_尾巴]
priority: critical
image: 冲击波.png
life: 30
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.8
alpha: 1
drawUnderUnits: true
atmospheric: false
[effect_尾巴1]
image: ROOT:/太空浪人/单位特效/光束.png
spawnChance: 1
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.95
scaleTo: 0.95
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: -0.5
ySpeedRelativeRandom: 1
xSpeedRelativeRandom: 1.5
atmospheric: true
[effect_尾巴3]
priority: veryhigh
image: SHARED:light_50.png
life: 60
fadeOut: true
attachedToUnit: false
color: #A6D80000
fadeInTime: 2
scaleFrom: 1.8
scaleTo: 0.2
alpha: 1
drawUnderUnits: true
[effect_火1]
life: 25
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.15
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -3
yOffsetRelative	: -117
drawUnderUnits: true
[effect_火2]
life: 22
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.033
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
ySpeedRelative: -1.5
yOffsetRelative	: -122
#drawUnderUnits: true
[effect_火3]
life: 22
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.15
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920

xSpeedRelative: -2
ySpeedRelative: -2.5
yOffsetRelative	: -80
xOffsetRelative	: -20
drawUnderUnits: true
[effect_火4]
life: 22
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.15
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920

xSpeedRelative: 2
ySpeedRelative: -2.5
yOffsetRelative	: -80
xOffsetRelative	: 20
drawUnderUnits: true
#————————————————似了
#-.....寄
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.5
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[effect_巨大钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
alpha: 0.8
scaleFrom: 3
scaleTo: 7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_碎片]
priority: critical
image: 似后.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
ySpeedRelative: -1.3
xSpeedRelativeRandom: 0.2
yOffsetRelative: -55
xOffsetRelative:0
hSpeed: 2
dirSpeed:0.7
dirSpeedRandom:1
[effect_碎片1]
priority: critical
image: 似左.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: -2
ySpeedRelativeRandom: 0.2
yOffsetRelative: -10
xOffsetRelative:-25
hSpeed: 2
dirSpeed:0.7
dirSpeedRandom:1
[arm_1]
x: 0
y: -50
image_end: 卫星.png
drawOverBody: true
image_end_shadow: SHADOW:卫星.png
image_end_teamColors: true
[arm_2]
x: 0
y: 40
image_end: 轨1.png
drawOverBody: false
image_end_shadow: SHADOW:轨1.png
image_end_teamColors: true
[arm_3]
x: 0
y: 72
image_end: 轨2.png
drawOverBody: true
image_end_shadow: SHADOW:轨2.png
image_end_teamColors: true
hidden:if not self.tags(includes= '变形金刚')
[arm_4]
x: 0
y: 70
image_end: 轨.png
drawOverBody: true
image_end_shadow: SHADOW:轨.png
image_end_teamColors: true
hidden:if not self.tags(includes= '变形金刚')
[arm_5]
x: 0
y: 54
image_end: 轨3.png
drawOverBody: true
image_end_shadow: SHADOW:轨3.png
image_end_teamColors: true
[arm_6]
x: 0
y: 20
image_end: 核.png
drawOverBody: true
image_end_shadow: SHADOW:核.png
image_end_teamColors: true
[arm_7]
x: -27
y: -37
image_end: 左边.png
drawOverBody: true
image_end_shadow: SHADOW:左边.png
image_end_teamColors: true
[arm_8]
x: 27
y: -37
image_end: 右边.png
drawOverBody: true
image_end_shadow: SHADOW:右边.png
image_end_teamColors: true
[arm_9]
x: -46
y: -70
image_end: 左后.png
drawOverBody: true
image_end_shadow: SHADOW:左后.png
image_end_teamColors: true
[arm_10]
x: 46
y: -70
image_end: 右后.png
drawOverBody: true
image_end_shadow: SHADOW:右后.png
image_end_teamColors: true
[arm_11]
x: 0
y: -40
image_end: 盖子.png
drawOverBody: true
image_end_teamColors: true
[arm_12]
x: 0
y: -50
image_end: 卫星遮盖.png
drawOverBody: true
image_end_shadow: SHADOW:卫星遮盖.png
image_end_teamColors: true
[animation_部署]

arm2_0s: {x:0, y:0,dir:0}
arm2_1.7s: {x:0, y:-90,dir:0}
arm2_2.5s: {x:0, y:-90,dir:0}

arm3_0s: {x:0, y:0,dir:0}
arm3_1.7s: {x:0, y:-94,dir:0}
arm3_2.5s: {x:0, y:-94,dir:0}

arm4_0s: {x:0, y:0,dir:0}
arm4_1.7s: {x:0, y:-115,dir:0}
arm4_2.5s: {x:0, y:-115,dir:0}

arm5_0s: {x:0, y:0,dir:0}
arm5_1.7s: {x:0, y:-104,dir:0}
arm5_2.5s: {x:0, y:-104,dir:0}

arm6_0s: {x:0, y:0,dir:0}
arm6_1.7s: {x:0, y:-60,dir:0}
arm6_2.5s: {x:0, y:-60,dir:0}

arm7_0s: {x:0, y:0,dir:0}
arm7_1.7s: {x:0, y:0,dir:0}
arm7_2.5s: {x:10, y:-36,dir:52}

arm8_0s: {x:0, y:0,dir:0}
arm8_1.7s: {x:0, y:0,dir:0}
arm8_2.5s: {x:-10, y:-36,dir:-52}

arm9_0s: {x:0, y:0,dir:0}
arm9_1.7s: {x:0, y:0,dir:0}
arm9_2.5s: {x:40, y:0,dir:0}

arm10_0s: {x:0, y:0,dir:0}
arm10_1.7s: {x:0, y:0,dir:0}
arm10_2.5s: {x:-40, y:0,dir:0}

arm11_0s: {x:0, y:0,dir:0}
arm11_1.7s: {x:0, y:41,dir:0}
arm11_2.5s: {x:0, y:41,dir:0}
[movement]
movementType: AIR
targetHeight: 140
targetHeightDrift: 2
moveSpeed: 0.8
moveAccelerationSpeed: 0.02

moveDecelerationSpeed: 0.06
maxTurnSpeed: 0.7
turnAcceleration: 0.03
slowDeathFall: true
moveSlidingMode :true

moveIgnoringBody: true
[resource_撞击]
displayName: Удар
displayNameShort: Удар
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_弹药]
displayName: Боеприпасы
displayNameShort: Боеприпасы
displayColor: #FF9D00FF
priority: 1
hidden: true
