


[core]
name: 休克打击炮塔t1
displayText: Шоковая башняt1
price: 1250
maxHp: 2100
footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 20
techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 10s
radius: 16
buildingSelectionOffset: -8
isBuilding: true
armour: 2
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1,largeExplosion*1
tags: 地面,建筑,防御建筑
displayDescription: 【Уровень t2】【Иммунитет к шоку】【Оборонительное здание】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение: парализующая атакующая башня。вооружение：\n-▲шоклиния圈X1 только по земле нейтральный урон пробивает укрытия усиленный урон по щитам\n-Экспериментальная вспомогательная оборонительная система Генезиса，\n-Способна выпускать ЭМИ-разряд, парализующий вражеские юниты，\n-Также высоковольтные волны легко убивают биологические юниты，\n-и могут вызывать необратимый разрушительный отказ у бронетехники противника。
[action_升级]
convertTo: 休克打击炮塔t2
displayType: action
text: Улучшение
price: 1000
buildSpeed: 10s

isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня
description: повышаетШоковая башня уровень，加固егоструктурасильный度иувеличивает伤害идальностьа такжескорострельность。\n-входитьодин步сменавышекласс супер导группавещь，\n-увеличивает充можетскорость одновременно，\n-такжевходитьодин步увеличиваетдальностьимощность。
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/t1影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:4
onlyWhileAlive:true
alpha:0.65
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/小支撑.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-30
xOffsetRelative:0.5
onlyWhileAlive:true
alpha:0.9

[decal_主体]
image: 电磁.png
total_frames: 1
isVisible:true
layer: afterBody
yOffsetRelative:33
xOffsetRelative:-0.5
onlyWhileAlive:true
alpha:1
[graphics]
total_frames: 1
image_back: ROOT:/通用特效/NO.png
image: ROOT:/创世纪军事集团/建筑特效/防御塔t1底座.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/防御塔t1死亡.png
image_turret: NONE

image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
image_offsetY: -4


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 12

turretTurnSpeed: 6
maxAttackRange: 270
shootDelay: 0
[turret_1]
x: 0
y: 55
invisible: true
size:0
shoot_sound: ROOT:/通用特效/shock.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:闪光1
shoot_light: #FF004AFF
projectile: beam0
delay:0
warmup:120
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
[turret_2]
x: 0
y: 55
projectile: 2
canShoot: true
shoot_flame: CUSTOM:汇聚*3
delay: 15
invisible: true
size:0


[projectile_beam0]
explodeEffect: CUSTOM:电电,CUSTOM:闪光
explodeEffectOnShield: CUSTOM:电电,CUSTOM:闪光
directDamage: 70
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 1
life: 3
instant: true
armourIgnoreAmount: 99999
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true
beamImage: ROOT:/通用特效/闪电1q.png
#beamImageOffsetRate: 2
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
shieldDamageMultiplier:20
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电2q.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0
[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电3q.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电4q.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电5q.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电6q.png
spawnProjectilesOnEndOfLife: beam6(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam6]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电7q.png
spawnProjectilesOnEndOfLife: beam7(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam7]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电8q.png
spawnProjectilesOnEndOfLife: NONE
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_2]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1



[effect_电电]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 1

drawUnderUnits: false
scaleFrom: 2
scaleTo: 2
[effect_闪光]
image: SHARED:light_50.png
life: 10
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
[effect_闪光1]
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1
attachedToUnit: true
color:  #FF004AFF
fadeInTime: 2
scaleFrom: 1
scaleTo: 1
drawUnderUnits: false
atmospheric: false

[effect_汇聚]
priority: low
image: ROOT:/通用特效/旋转光效.png
dirOffsetRandom: 360
dirSpeed: 1
dirSpeedRandom: 0.5
life: 45
scaleFrom: 0.45
scaleTo: 0
alpha: 0.9
drawUnderUnits: false
attachedToUnit: true
atmospheric: false




[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


