


[core]
name: 太空浪人暗物质筒仓t1
displayText: Хранилище тёмной материи Скитальцев t1
class: CustomUnitMetadata
price: 3000
maxHp: 30000
tags: 地面,灰影建筑,建筑,战略武器抗性

#selfRegenRate:0
techLevel: 1
buildSpeed: 3s
isBio: false
isBuilding: true

#numBitsOnDeath: 14
footprint: -3,0,3,3
constructionFootprint: -3,0,3,3
radius: 35
borrowResourcesWhileAlive: awz= -300, awz2= -300

#reclaimPrice: awz=-300
copyFrom: ROOT:/通用特效/单位防护.ini
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
armour: 30
energyMax: 1

energyRegen: 0
energyNeedsToRechargeToFull: true


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[action_t1]
autoTrigger: if self.noUnitInTeam(withTag='聚变堆', withinRange=400)
isVisible: false
addResources: hp=-150


[action_总产出]
isActive: false
text: Общая выработка: %{self.resource.awz2}
isVisible: true
displayType: infoOnlyNoBox


[action_负载]
isActive: false
text: Занято: %{self.resource.awz2 - self.resource.awz}
isVisible: true
displayType: infoOnlyNoBox


[action_可用暗物质]
isActive: false
text: Доступно: %{self.resource.awz}
isVisible: true
displayType: infoOnlyNoBox


[graphics]
total_frames: 1
image: 背景.png
image_wreak: 死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

shadowOffsetX: 3
shadowOffsetY: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 9999

turretSize: 0
turretTurnSpeed: 50


[turret_1]
x: 2
y: 32
canShoot: true
shoot_flame: CUSTOM:光粒*3
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 160
fadeOut: true
attachedToUnit: false

color: #FFFF1200
fadeInTime: 4
scaleFrom: 0.3
scaleTo: 0.6
alpha: 0.55

drawUnderUnits: false
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.17

ySpeedAbsoluteRandom: 0.17


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[arm_1]
x: -50
y: -26
image_end: 货.png
image_end_teamColors: true
drawOverBody: true

hidden: if self.hp(lessThan=5760)


[arm_2]
x: 2
y: 30
image_end_teamColors: false
image_end: 球.png
drawOverBody: true

hidden: if self.hp(lessThan=5760)


[arm_3]
x: 0
y: 0
image_end_teamColors: false
image_end: 身体.png
drawOverBody: true


[arm_4]
x: 0
y: 0
image_end_teamColors: false
image_end: 闪.png
drawOverBody: true

hidden: if self.hp(lessThan=5760)


[arm_5]
x: 0
y: 0
image_end_teamColors: false
image_end: 损坏.png
drawOverBody: true

hidden: if self.hp(greaterThan=5760)


[animation_1]
onActions: idle
arm2_0s: {x:0,y:0}
arm2_1s: {x:0,y:1}
arm2_2s: {x:0,y:2}
arm2_3s: {x:0,y:3}

arm2_4s: {x:0,y:5}
arm2_5s: {x:0,y:2}
arm2_6s: {x:0,y:0}
arm1_0s: {x:0,y:0}
arm1_2s: {x:0,y:30}

arm1_3s: {x:0,y:0}
arm4_0s: {alpha:0.0}
arm4_2s: {alpha:0.9}
arm4_3s: {alpha:0.1}


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 太空浪人暗物质筒仓t1传送
buildPriority: 0.05
ai_upgradePriority: 0.07
maxEachBase: 6
maxGlobal: 30


