


[core]
name: 爆炸僵尸
displayText: 爆炸僵尸
displayDescription: -爆炸僵尸经过太空浪人的负重与耐力改造，\n-并且在体内体外都植入了各种爆炸物以及钢珠。\n-这些僵尸唯一的命运就是点燃炸弹与敌人同归于尽。\n-只能对地。爆炸伤害，反掩体，生物单位。
class: CustomUnitMetadata
price: 750

maxHp: 1500
techLevel: 1
buildSpeed: 7s
radius: 14
isBio: true
transportSlotsNeeded: 200
hideScorchMark: true
effectOnDeath: CUSTOM:飘血*12,CUSTOM:飘血2*14
fireTurretXAtSelfOnDeath: 1
tags: 地面,寄生免疫,射程x,步兵
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 10
isUnrepairableUnit:true
[action_自爆]
displayType: rally
text: 自爆
description: 立即原地自爆
addResources: hp=-9999
buildSpeed: 1

highPriorityQueue: true
displayRemainingStockpile: false


[graphics]
total_frames: 5
image: 爆炸僵尸.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 0
animation_moving_end: 4
animation_moving_speed: 5

#imageScale:0.93


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 1

turretTurnSpeed: 2.5
dieOnAttack: true
maxAttackRange: 18
isMelee: true


[projectile_0]
directDamage: 0
life: 50
instant: true
explodeEffect: NONE


[turret_0]
projectile: 0
x: 0
y: 0
invisible: true
canAttackFlyingUnits: false

canAttackLandUnits: true
canAttackUnderwaterUnits: false


[turret_1]
x: 0
y: 0
invisible: true
shoot_sound: NONE
shoot_sound_vol: 0.5

shoot_flame: small
shoot_light: #FFFFEB88
projectile: 1
canAttackFlyingUnits: false
canAttackLandUnits: false

canAttackUnderwaterUnits: false


[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 1300
areaRadius: 80
life: 666
speed: 8888

targetSpeed: 8888
instant: true
flameWeapon: true
deflectionPower: -1
areaRadiusFromEdge: true

explodeEffect: CUSTOM:大爆炸,CUSTOM:弹坑*1,CUSTOM:闪光*1,CUSTOM:气浪*1
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 1
scaleTo: 1
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 0.7
createWhenZoomedOut: false
xSpeedRelativeRandom: 2
ySpeedRelativeRandom: 2

hSpeed: 1.5


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.7
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 2.5
ySpeedRelativeRandom: 2.5

hSpeed: 1.5
dirSpeedRandom: 50


[effect_大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.7

image: ROOT:/创世纪军事集团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/单位特效/大爆炸.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_气浪]
life: 90
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false

scaleFrom: 1.5
scaleTo: 3.5
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1.4

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 4

drawUnderUnits: false
atmospheric: false


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1.7
scaleTo: 1.7
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: LAND
moveSpeed: 1.4
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: true


