


[core]
name: 强固混凝土围墙
class: CustomUnitMetadata
price: 430
maxHp: 6000
energyMax: 10
energyStartingPercentage: 1
copyFrom: ROOT:/通用特效/单位防护.ini
energyRegen: 0.008
techLevel: 1
buildSpeed: 3s
isBio: false
isBuilding: true
tags: 地面,重型掩体,建筑,防御建筑
numBitsOnDeath: 10
armour: 35
radius: 10
fogOfWarSightRange: 10
displayDescription:【阶级t4】【防御类建筑】【建筑单位】【地面单位】\n-战术定位：障碍物，只能对地，爆炸伤害。无法在水面上建造，\n-围墙的意义在于为步兵等单位提供掩体，\n-或者作为障碍物大量部署，迫使敌人清除围墙，阻碍敌人的前进。
[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免部分速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。
[decal_损坏]
image: 围墙.png
total_frames: 1
layer: onTop
yOffsetRelative:14
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
teamColors: true
[decal_损坏1]
image: 围墙1.png
total_frames: 1
layer: onTop
yOffsetRelative:14
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.isEnergyFull()
teamColors: true
[hiddenAction_DPS]
buildSpeed: 0s
fireTurretXAtGround: 2
whenBuilding_cannotMove: true
fireTurretXAtGround_withOffset: 0,0
[graphics]
total_frames: 1
image: 钢筋混凝土围墙.png
image_wreak: 钢筋混凝土围墙死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.75


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
maxAttackRange: 55
turretTurnSpeed: 50
[turret_1]
x: 0
y: 0
invisible: true
delay: 0s
projectile: 1
turnSpeed: 100
turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true
size: 0
onShoot_triggerActions: DPS
energyUsage:10
canOnlyAttackUnitsWithoutTags:建筑,海上

[turret_2]
x: 0
y: 0
invisible: true
delay: 0s
projectile: 2
turnSpeed: 100
turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: false
size: 0
[projectile_1]
life: 0
speed: 0
directDamage: 0
drawSize: 0
areaDamage:0
areaRadius: 0
frame: 1
explodeEffect:NONE
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 3000
areaRadius: 80
life: 666
speed: 0

targetSpeed: 0
instant: true
flameWeapon: true
deflectionPower: -1
areaRadiusFromEdge: true

explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波
buildingDamageMultiplier: 0
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false

atmospheric: false


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false

scaleFrom: 2
scaleTo: 2.7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0

animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


