


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}


[core]
name: SDD渡鸦
displayText: SDD Ворон
class: CustomUnitMetadata
displayDescription: -Воронэто широкоРазвернутьк Империя Новастраназемля в  промышленностьмеханическийчеловек, \n-они хранениев  намерениесправедливостьтогдаэто висетьдвижениетоваробъект и делитьрезатьметалли т.п.другие минералы, \n-в усилениебурениелазер передаватьвыходит функциякоэффициентпозади , Этот вещьможет изменитьстать тип мощныйоружие.\n-самыйконец, производствоколичествооставшийся Воронимеет оченьбольшой одинчастьЗаревопереоборудованныйстать атакамашина, \n-хотя основаштпротив тяжёлыйюнитммнет угроза, но против платитьсозиданиеэпохаэра разорватьмедьгнилойжелезоещё это с избыткомимеет остаток.\n-по земле и воздухуэнергетический урон, лазерпротив укрытий.может транспортюнит.\n-Тип проекта:базовая база данных
price: 1500
maxHp: 700

techLevel: 1
buildSpeed: 16s
availableInDemo: true
radius: 28
displayRadius: 28

isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 10
maxShield: 300
shieldRegen: 0.07
armour: 1
tags: 飞机,低空,无人单位
maxTransportingUnits: 1
[hiddenAction_地上]
autoTrigger: if not self.tags(includes= '地面') and not self.flying
isVisible: false
temporarilyAddTags:地面
temporarilyRemoveTags:飞机
[hiddenAction_天上]
autoTrigger: if self.tags(includes= '地面') and self.flying
isVisible: false
temporarilyAddTags:飞机
temporarilyRemoveTags:地面
[action_裂解炮1]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/裂解1.png
text: Расщепляющая пушка 1
isActive: false
isVisible: if self.globalTeamTags(includes='裂解炮1')


[action_重子1]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重1.png
text: барионное оружие 1
isActive: false
isVisible: if self.globalTeamTags(includes='重子1')


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 0.9

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 2
animation_moving_end: 2

animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3
movementEffect: CUSTOM:火

movementEffectRate: 1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 220
isFixedFiring: true


[turret_1]
x: 0
y: 15
projectile: 1
delay: 0.9
attachedTo: 2

canAttackCondition: if self.flying and not self.globalTeamTags(includes='裂解炮1')
slave: true
[turret_炮台1]
x: 0
y: 15
projectile: 炮弹1
delay: 30
attachedTo: 2

canAttackCondition: if self.flying and self.globalTeamTags(includes='裂解炮1')
slave: true
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.35

[turret_3]
x: -25
y: 0
canShoot: true
delay: 60
projectile: 2

slave: true
attachedTo: 2
canAttackCondition: if self.flying
shoot_sound: ROOT:/余辉军团/单位特效/大炮音效.ogg
shoot_sound_vol: 0.45

shoot_flame: CUSTOM:气浪*2
shoot_light: #FFccCCEE
canAttackFlyingUnits: false
altProjectile: 炮弹2
altProjectileCondition: if self.globalTeamTags(includes='重子1')

[turret_4]
x: 25
y: 0
copyFrom: 3


[turret_2]
x: 0
y: 0
canShoot: false
canAttackCondition: if self.flying


[projectile_1]
@copyFromSection: template_能源
directDamage: 2
life: -4
instantReuseLast: true
beamImage: SHARED:beam3.png

beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true

color: #FF00B3FF
lightColor: #FF004AFF
lightSize: 0.1
explodeEffect: CUSTOM:闪光
explodeEffectOnShield: CUSTOM:闪光

armourIgnoreAmount: 30
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_能源
directDamage: 60
life: 100
speed: 7
image: ROOT:/余辉军团/单位特效/星星.png

drawSize: 0.55
lightSize: 1.5
lightColor: #FF00B3FF
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光

trailEffect: CUSTOM:尾巴
trailEffectRate: 1

[projectile_炮弹1]
@copyFromSection: template_动能
directDamage: 65
life: 5
instantReuseLast: true
beamImage: SHARED:beam3.png

beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true

color: #FFFFFF3D
lightColor: #FFFFFF3D
lightSize: 0.1
targetGroundSpread: 200
explodeEffect: CUSTOM:爆炸a,CUSTOM:闪光b

explodeEffectOnShield: CUSTOM:爆炸a,CUSTOM:闪光b
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_炮弹2]
@copyFromSection: template_爆炸
areaDamage: 270
areaRadius: 45
life: 300
lightSize: 1

largeHitEffect: true
speed: 6.5
trailEffect: CUSTOM:尾
areaHitAirAndLandAtSameTime: true
drawSize: 0.5

image: ROOT:/余辉军团/单位特效/星星2.png
deflectionPower: -1
explodeEffectOnShield: CUSTOM:底色a,CUSTOM:闪光d,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:聚变
explodeEffect: CUSTOM:底色a,CUSTOM:闪光d,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:聚变
trailEffectRate: 0.5

areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[effect_尾]
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
#priority:low

color:#FF00B3FF
fadeInTime: 2
scaleFrom: 0.7
scaleTo: 0.2
alpha: 1

drawUnderUnits: true


[effect_闪光b]
priority: low
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFFFF3D
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[effect_爆炸a]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg

alpha: 1.2


[effect_底色a]
priority: critical
image: ROOT:/余辉军团/单位特效/黑洞1.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.25
scaleTo: 0.25
alpha: 1.3
drawUnderUnits: false
atmospheric: false


[effect_闪光d]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: true

atmospheric: false


[effect_粒子a]
life: 45
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 0.1
scaleTo: 2
alpha: 1

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
drawUnderUnits: true


[effect_冲击波a]
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.7
scaleTo: 0.7
alpha: 0.6
drawUnderUnits: true
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg



[effect_爆炸]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_闪光]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.25

scaleTo: 0.25
image: ROOT:/余辉军团/单位特效/光束.png
dirOffsetRandom: 180


[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -35


[effect_气浪]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70

fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8

ySpeedRelative: 1.5
atmospheric: true


[attachment_1]
x: 0
y: 5
canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
addTransportedUnits: 1

rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: false
setDrawLayerOnBottom: true

alwaysAllowedToAttackParentsMainTarget: true
lockLegMovement: true


[movement]
movementType: AIR
moveSpeed: 1.7
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02
maxTurnSpeed: 2.1

turnAcceleration: 1
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: true
targetHeight: 70

landOnGround: onlyIdle
startingHeightOffset: 1000


