[hiddenAction_寄生b]
addResources: bj= ${bjxq}


[core]
name: 天盾防御系统
displayText: Система обороны «Небесный щит»
displayDescription: 【Уровень t4】【Оборонительное здание】【Здание】【Дальнее целеуказание】【Защита от тактического оружия】【Наземный юнит】【Надводный юнит】\n-(при развёртывании на воде)Тактическое назначение：大 тактическое оружиеоборонасооружение вооружение：\n-▲тактикаракета垂 单元X4 только по земле взрывной урон тактическое оружие\n-▲长距离целеуказаниетактикаракета垂 单元X4 толькоможет攻击地面被锁定的юнит взрывной урон тактическое оружие\n-▲торпедапусковая трубаX8 доступно только при постройке на воде только по надводным и подводным юнитам взрывной урон\n-Система обороны «Небесный щит»是Генезис为了оборонаЗарево的далеко程ракетаудар，аразрабатывать的新一代оборона系统，\n-这вид占地面积и不大的зданиеможетразвёртывать在绝大部分环境当中，包括海面，\n-Система обороны «Небесный щит»главным образомфункция是перехватывать那些威胁较大的тактическое оружие，одновременноещёспособензапускатьракета进行反击。\n在война后期，几乎每一个база都有развёртыватьСистема обороны «Небесный щит»，\n-а这些由продвинутыйнаука打造的здание，также将完美способенперехватывать的任务。
price: 12000,钍=200,bj= ${bjxq}
@global bjxq: 15
reclaimPrice: bj= ${bjxq}
maxHp: 55000
fogOfWarSightRange: 82
footprint: -6,-4,6,5
constructionFootprint: -6,-4,6,5
techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 91s
radius: 80
armour: 55
isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆破*12,largeExplosion
unitsSpawnedOnDeath:建筑损毁*1
tags: 地面,建筑,防御建筑
energyMax: 21
energyRegen: 0.0135
energyNeedsToRechargeToFull: true
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上

[action_长距离]
text: 长距离целеуказание
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.15
iconImage: ROOT:/通用特效/长距离.png
description: 在иметьпортативный弹道ракетанаука时，该юнит有способность射击极далеко距离上的被锁定юнит。\n-允许Система обороны «Небесный щит»在攻击 наземный юнит 中的 被锁定 вражескийюнит时，\n-将тактикаракетадальностьповышает至2200


[action_没有]
text: 未启用тактикаракета系统
isVisible: if not self.globalTeamTags(includes='弹道导弹技术2')
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 3
iconImage: ROOT:/通用特效/关.png
description: 在иметьпортативный弹道ракетанаука时，该юнит有способностьзапускатьтактикаракета攻击далеко程地面враг。\n-ракетатолькоможет攻击非юнит-здание，造成взрывной урон，одновременно将被判定为тактическое оружие。

[action_有]
text: 已启用тактикаракета系统
isVisible: if self.globalTeamTags(includes='弹道导弹技术2')
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 3
iconImage: ROOT:/通用特效/开.png
description: 该юнит有способностьзапускатьтактикаракета攻击далеко程地面враг。\n-ракетатолькоможет攻击非юнит-здание，造成взрывной урон，одновременно将被判定为тактическое оружие。
[decal_地板]
image: 地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-33
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
isVisible:if not self.isOverLiquid
[decal_影子]
image: 主主影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:4
xOffsetRelative:7
onlyWhileAlive:true
imageScale: 1.05
alpha:0.65
[decal_支柱]
image: 支持.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-57
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.65
[decal_左门]
image:左门.png
total_frames: 1
layer: onTop
isVisible:if not self.isOverLiquid
yOffsetRelative:-76
xOffsetRelative:-74
onlyWhileAlive:true
[decal_右门]
image:右门.png
total_frames: 1
layer: onTop
isVisible:if not self.isOverLiquid
yOffsetRelative:-76
xOffsetRelative:74
onlyWhileAlive:true


[decal_遮盖]
image:主主遮盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
[decal_盖]
image:盖.png
total_frames: 1
layer: onTop
isVisible:if not self.isAttacking()
yOffsetRelative:35
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true


#————————————灯光
[decal_灯光]
image:光.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_雷达]
image:雷.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:62
xOffsetRelative:95
onlyWhileAlive:true
teamColors: true
dirOffset:45
[decal_损坏]
image:损坏.png
total_frames: 1
layer: onTop
isVisible:if self.hp<self.maxHp * 0.36 
yOffsetRelative:0
xOffsetRelative:0
teamColors: true
onlyWhileAlive:true
#——————————————————柱子
[decal_柱子1]
image:柱子.png
total_frames: 1
layer: onTop
isVisible:if self.energy>18
yOffsetRelative:100
xOffsetRelative:-18.5
onlyWhileAlive:true
teamColors: true
[decal_柱子2]
image:柱子.png
total_frames: 1
layer: onTop
isVisible:if self.energy>15
yOffsetRelative:100
xOffsetRelative:-6.5
onlyWhileAlive:true
teamColors: true
[decal_柱子3]
image:柱子.png
total_frames: 1
layer: onTop
isVisible:if self.energy>12
yOffsetRelative:100
xOffsetRelative:5.5
onlyWhileAlive:true
teamColors: true
[decal_柱子4]
image:柱子.png
total_frames: 1
layer: onTop
isVisible:if self.energy>9
yOffsetRelative:100
xOffsetRelative:17.5
onlyWhileAlive:true
teamColors: true
[decal_柱子5]
image:柱子.png
total_frames: 1
layer: onTop
isVisible:if self.energy>6
yOffsetRelative:93
xOffsetRelative:-12.5
onlyWhileAlive:true
teamColors: true
[decal_柱子6]
image:柱子.png
total_frames: 1
layer: onTop
isVisible:if self.energy>4
yOffsetRelative:93
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
[decal_柱子7]
image:柱子.png
total_frames: 1
layer: onTop
isVisible:if self.energy>2
yOffsetRelative:93
xOffsetRelative:11.5
onlyWhileAlive:true
teamColors: true

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image_back: ROOT:/通用特效/NO.png
image: 主主.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
turretSize: 12

turretTurnSpeed: 6
shootDelay: 0
maxAttackRange: 2200
turretMultiTargeting: true
[turret_1]
x: 0
y: 35
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 1
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:60
interceptProjectiles_withTags:战术武器
interceptProjectiles_andUnderDistance: 2000
interceptProjectiles_andOverHeight: -10
energyUsage: 0.5
size:0
invisible: true
shoot_flame: CUSTOM:烟雾x*5, CUSTOM:冲击波1
onShoot_playAnimation: 舱盖

[turret_1x]
x: 0
y: 35
copyFrom: 1
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 2000
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2000
#战术防御天上



[turret_2]
x: -64
y: -62
#导弹右
projectile: 2
image: 鱼雷.png
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾x*3
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -10
size:20
recoilOutTime: 0
recoilReturnTime: 200
delay:240
canAttackNotTouchingWaterUnits: false
canAttackFlyingUnits:false
canAttackUnderwaterUnits: true
canAttackCondition: if self.resource.xk < 1 and self.isOverLiquid
turnSpeed: 0
canAttackMaxAngle: 181
idleDir: 135
limitingMinRange: 350
limitingRange: 1000
canOnlyAttackUnitsWithoutTags:悬浮
[turret_3]
x: -57
y: -69
copyFrom: 2
warmup: 30
delay:210

[turret_4]
x: 64
y: -62
copyFrom: 2
idleDir: 45
[turret_5]
x: 57
y: -69
copyFrom: 2
warmup: 30
delay:210
idleDir: 45

[turret_6]
x: 64
y: 52
copyFrom: 2
idleDir: -45
[turret_7]
x: 57
y: 59
copyFrom: 2
warmup: 30
delay:210
idleDir: -45

[turret_8]
x: -64
y: 52
copyFrom: 2
idleDir: 225
[turret_9]
x: -57
y: 59
copyFrom: 2
warmup: 30
delay:210
idleDir: 225


[turret_10]
x: -19
y: 60
invisible: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾x*4,CUSTOM:冲击波1
shoot_light: #FFEECCCC
projectile: 3
size: 0
turnSpeed: 811
delay:480
limitingMinRange: 500
limitingRange: 1200
canOnlyAttackUnitsWithoutTags:建筑
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹道导弹技术2')
energyUsage: 1.5
[turret_11]
x: 19
y: 60
copyFrom: 10
delay:420
warmup:60
[turret_12]
x: -19
y: 30
copyFrom: 10
delay:360
warmup:120
[turret_13]
x: 19
y: 30
copyFrom: 10
delay:300
warmup:180


[turret_14]
x: -19
y: 60
invisible: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾x*4,CUSTOM:冲击波1
shoot_light: #FFEECCCC
projectile: 3
size: 0
turnSpeed: 811
delay:480
limitingMinRange: 1200
canOnlyAttackUnitsWithoutTags:建筑
canOnlyAttackUnitsWithTags:被锁定
energyUsage: 1.5
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹道导弹技术2')
[turret_15]
x: 19
y: 60
copyFrom: 14
delay:420
warmup:60
[turret_16]
x: -19
y: 30
copyFrom: 14
delay:360
warmup:120
[turret_17]
x: 19
y: 30
copyFrom: 14
delay:300
warmup:180

[projectile_1]
areaDamage: 0
areaRadius: 0
life: 120
speed: 40
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 1
largeHitEffect: true
deflectionPower: -1
trailEffectRate: 0
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光

[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
life: 38
speed: 4
targetGround: false
deflectionPower: -1
areaRadiusFromEdge: true
targetSpeed: 4
image: 鱼雷.png
explodeEffect: CUSTOM:烟雾x*2,CUSTOM:水波
explodeEffectOnShield: CUSTOM:烟雾x*2,CUSTOM:水波
initialUnguidedSpeedHeight: 4
trueGravity: 0.2
lightSize: 0.75
trailEffectRate: 2
trailEffect:true
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
turnSpeed: 0
[projectile_锁定]
targetGround: false
@copyFromSection: template_爆炸
areaDamage: 1000
areaRadius: 70
areaRadiusFromEdge: true
life: 460
speed: 0.5
targetSpeed: 9
image: 鱼雷1.png
lightSize: 3
lightColor: #FFFFFF
trailEffect: CUSTOM:尾巴
trailEffectRate: 0.4
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:冲击波y,CUSTOM:闪光y,CUSTOM:水波y,CUSTOM:水雾y*4,CUSTOM:水波1
explodeEffectOnShield: CUSTOM:冲击波y,CUSTOM:闪光y,CUSTOM:水波y,CUSTOM:水雾y*4,CUSTOM:水波1
turnSpeed: 2
areaHitUnderwaterAlways:true



[projectile_3]
life: 80
speed: 2
targetSpeed: -1
largeHitEffect: true
drawSize: 0.95
image: 战术导弹.png
directDamage: 0
ballistic: true
ballistic_height: 260
ballistic_delaymove_height: 210
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:冲击波t,CUSTOM:烟雾x*4,CUSTOM:闪光mx,CUSTOM:音效
trailEffect: true
trailEffectRate: 1.2
deflectionPower: -1
[projectile_锁定1]
@copyFromSection: template_爆炸
areaDamage: 4500
life: 1000
areaRadius: 100
alwaysVisibleInFog: true
nukeWeapon: true
speed: 0
image:导弹头.png
targetSpeed: 12
drawSize:0.95
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸m,CUSTOM:气浪m,CUSTOM:冲击波m,CUSTOM:闪光m*2,CUSTOM:弹坑m
targetGroundSpread: 60
disableLeadTargeting: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate: 1.2
areaRadiusFromEdge: true
targetGround: true
ballistic: true
ballistic_height: 260
deflectionPower: -1
ballistic_delaymove_height: 210
tags:战术武器
shouldRevealFog: true
#————————，，，，，，，反导开火
[effect_冲击波1]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1
[effect_烟雾x]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 2.3
scaleTo: 2.7
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.33
xSpeedRelativeRandom: 0.33
atmospheric: true
#————————，，，，，，，反导爆炸
[effect_闪光]
image: SHARED:light_50.png
life: 18
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.9
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸1.ogg
alpha: 1.2
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
#——————————————————————鱼雷
[effect_尾巴]
image: SHARED:light_50.png
life: 38
fadeOut: true
attachedToUnit: false
priority: high
color:#FF0092FF
fadeInTime: 2
scaleFrom: 0.4
scaleTo: 0.2
alpha: 0.8
drawUnderUnits: true
yOffsetRelative:-10
[effect_水波]
priority: low
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.7
alpha:0.7
drawUnderUnits: true
atmospheric: true
createWhenOverLiquid: true
createWhenOverLand: false
[effect_闪光y]
image: SHARED:light_50.png
life: 15
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 7
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_冲击波y]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
createWhenOverLiquid: true
createWhenOverLand: false
drawUnderUnits: true
[effect_水波y]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 4
scaleTo: 6
image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
[effect_水雾y]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 3.5
scaleTo: 5
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.27
ySpeedRelativeRandom: 0.27
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
createWhenOverLiquid: true
createWhenOverLand: false
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
[effect_水波1]
image: SHARED:ripple.png
life: 90
lifeRandom: 20
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1.5
scaleTo: 5
alpha: 0.7
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5
delayedStartTimer: 5


#————————导弹发射

[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:nuke_launch
[effect_闪光mx]
image: SHARED:light_50.png
life:30
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FFFF5B18
fadeInTime: 2
scaleFrom: 5.5
scaleTo: 5.5
drawUnderUnits: false
atmospheric: false
[effect_导弹碎片]
#priority: low
image: 导弹碎片.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 50

[effect_冲击波t]
stripIndex: shockwave
life: 33
scaleFrom: 0.6
scaleTo: 3.5
alpha: 0.9
fadeOut: true
attachedToUnit: false
fadeInTime: 2
#战术飞弹————————
[effect_弹坑m]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true

[effect_气浪m]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 3
scaleTo: 7.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true

[effect_闪光m]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true

[effect_冲击波m]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_爆炸m]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.5
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.8
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2

[arm_1]
x: -6
y: 35
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

[arm_2]
x: 6
y: 35
image_end: 右.png
image_end_teamColors: true
drawOverBody: true
[animation_舱盖]
arm1_0.4s: {x:-20, y:0}
arm2_0.4s: {x:20, y:0}
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0
turnAcceleration: 0

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:65
yOffsetRelativeRandom:65
delayedStartTimerRandom:30
[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


