


[core]
name: 选择阵营t3
displayText: Выбор фракции (t3)
class: CustomUnitMetadata
price: 0
maxHp: 999999
radius: 100
techLevel: 1
buildSpeed: 0.0005
isBio: false
isBuilding: true
nanoRange: 400
nanoBuildSpeed: 1.1
canRepairBuildings: true
canRepairUnits: true
canReclaimResources: true
isPickableStartingUnit: true

#————————————————————选择器
[action_总产出]
isActive: false
text: Осталось времени: %{30-self.timeAlive}
isVisible: true
displayType: infoOnlyNoBox
description:Если фракция не будет выбрана за оставшееся время, по умолчанию будет выбран Альянс Генезис.
[action_创]
isVisible: if not self.tags(includes= '创世纪')
isActive: true
iconImage: G.png
price: 0
text: Альянс Генезис
buildSpeed: 0s
pos: 0.1
highPriorityQueue: true
ai_isHighPriority: false

temporarilyAddTags:创世纪
temporarilyRemoveTags:余晖,浪人
playSoundToPlayer:创.wav
[action_选了创]
pos: 0.1
displayType: infoOnly
isGuiBlinking: true
iconImage:G.png
text:Выбрано
isActive: false
isVisible:if self.tags(includes= '创世纪')
description: Чтобы противостоять Имперскому Зареву, всё человечество объединилось в Альянс Генезис.\n-Несмотря на ограниченную мощь, Альянс по-прежнему остаётся главной силой в борьбе с Заревом и с трудом удерживает порядок в человеческом обществе.\n-Однако сражение за сражением доказывают: недооценивать боевой потенциал Генезиса — глупость и предубеждение.\n-Генезис — фракция, опирающаяся прежде всего на кинетическое и взрывное оружие.\n-Она прекрасно умеет использовать масштабную экономику, быстро превращая разные ресурсы в производство и боевую мощь, чтобы сокрушать противника.\n-Также располагает множеством тактических юнитов и тяжёлыми бомбардировщиками.\n-Боеспособность юнитов напрямую зависит от навыков игрока — при неумелом использовании их потенциал крайне низок.\n-При этом Генезис очень силён в обороне.\n-Сложность освоения: высокая.


[action_余]
isVisible: if not self.tags(includes= '余晖')
isActive: true
iconImage: A.png
price: 0
text: Имперское Зарево
buildSpeed: 0s
pos: 0.2
highPriorityQueue: true
ai_isHighPriority: false

temporarilyAddTags:余晖
temporarilyRemoveTags:创世纪,浪人
playSoundToPlayer:余.wav
[action_选了余]
pos: 0.2
displayType: infoOnly
isGuiBlinking: true
iconImage:A.png
text:Выбрано
isActive: false
isVisible:if self.tags(includes= '余晖')
description: Имперское Зарево — автоматизированная армия, созданная Империей Нова. Цель ИИ Зарева — устранить все угрозы на территории Империи\n-и обеспечить её безопасность и стабильность. Всех людей на Земле он считает чужаками, посягнувшими на имперские владения,\n-и потому отправляет войска защищать «свои» территории, ведя войну сразу на двух фронтах.\n-Войска Зарева опираются прежде всего на энергетическое и взрывное оружие и, как правило, располагают самыми мощными боевыми юнитами своей эпохи.\n-Это даёт Имперскому Зареву огромное преимущество в открытом бою и позволяет реализовать высокую боевую мощь без сложного микроконтроля и тактики.\n-Кроме того, Зарево возводит здания при помощи десанта с орбиты, что значительно экономит время.\n-Фракция почти не нуждается в тонком управлении: благодаря высоким характеристикам Зарево практически не уступает в прямом столкновении.\n-Сложность освоения: низкая.


[action_浪]
isVisible: if not self.tags(includes= '浪人')
isActive: true
iconImage: R.png
price: 0
text: Космические Скитальцы
buildSpeed: 0s
pos: 0.3
highPriorityQueue: true
ai_isHighPriority: false

temporarilyAddTags:浪人
temporarilyRemoveTags:创世纪,余晖
playSoundToPlayer:浪.wav
[action_选了浪]
pos: 0.3
displayType: infoOnly
isGuiBlinking: true
iconImage:R.png
text:Выбрано
isActive: false
isVisible:if self.tags(includes= '浪人')
description:Космические Скитальцы изначально называются «Объединённый Орден Эвенора», но «Скитальцы» — их повсеместно распространённое прозвище.\n-Они представляют собой последних известных потомков Древних Людей. Покинув родину, превратившуюся в адскую пустошь,\n-их корабль-ковчег («Семя») рухнул на Землю, и теперь они вместе с человечеством сражаются против общего врага — Имперского Зарева.\n-Скитальцы — фракция кинетического и энергетического оружия.\n-Большинство их машин обладают самовосстановлением и высокой боевой мощью.\n-Биологические юниты быстро производятся в подавляющих количествах, а способность к ассимиляции позволяет рвать оборону врага,\n-создавая возможности и прикрытие для машин — стиль игры строится на быстрых компактных штурмах.\n-У Скитальцев есть уникальная механика телепортации, позволяющая мгновенно перебрасывать большие силы\n-или проводить разнообразные диверсионные удары для решающего перевеса.\n-Сложность освоения: средняя.
#——————————————确定
[action_确定]
isVisible:if not self.tags(includes= '完成选择')
isActive: if not self.tags(includes= '完成选择')
iconImage: 对勾.png
price: 0
text: Подтвердить
buildSpeed: 0s
pos: 0.4
highPriorityQueue: true
ai_isHighPriority: false
temporarilyAddTags:完成选择
isLocked: if not self.tags(includes= '创世纪') and not self.tags(includes= '余晖') and not self.tags(includes= '浪人')
isLockedMessage: Сначала выберите фракцию

[action_注意]
iconImage: 感叹号.png
text: Внимание
isActive: false
isVisible: true
displayType: infoOnly
pos: 9999
isGuiBlinking: true
description:Внимание: бой начнётся со штаб-квартиры t3.
#——————————————转换
[hiddenAction_g1]
autoTrigger: if self.tags(includes= '创世纪') and self.tags(includes= '完成选择')
convertTo: 创世纪指挥中心t3
addResources: bj=300
addGlobalTeamTags: 我是创世纪
[hiddenAction_a1]
autoTrigger: if self.tags(includes= '余晖') and self.tags(includes= '完成选择')
convertTo: AI核心作战中枢t3
addResources: ry=300
addGlobalTeamTags: 我是余晖
[hiddenAction_r1]
autoTrigger: if self.tags(includes= '浪人') and self.tags(includes= '完成选择')
convertTo: 太空浪人枢纽t3
addGlobalTeamTags: 我是浪人
[decal_1]
image: 在1.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人') or self.tags(includes= '余晖') or self.tags(includes= '创世纪')

yOffsetRelative:110
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own

[decal_2]
image: 余1.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人') or self.tags(includes= '余晖') or self.tags(includes= '创世纪')

yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own
[decal_3]
image: 浪1.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人') or self.tags(includes= '余晖') or self.tags(includes= '创世纪')

yOffsetRelative:-110
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own
[decal_4]
image: 主.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.115
onlyTeam:own
color:#FF00FF00
teamColors: true
[decal_5]
image: 主要.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.1
onlyTeam:own
[decal_6]
image: 在.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '创世纪') 
yOffsetRelative:110
xOffsetRelative:0
onlyWhileAlive:true
onlyTeam:own
imageScale:0.25
[decal_7]
image: 余.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '余晖') 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own
[decal_8]
image: 浪.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人')
yOffsetRelative:-110
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own

[decal_9]
image: 蜂窝.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:1.5
alpha:0.7

[decal_10]
image: T3开.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
yOffsetRelative:100
xOffsetRelative:-108
onlyWhileAlive:true
imageScale:0.1
onlyTeam:own
[hiddenAction_1]
autoTrigger: if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
spawnEffects: CUSTOM:闪光,CUSTOM:冲击波

#——————————————ai
[action_upgrade_1]
isVisible: if self.isControlledByAI()
isActive: if self.isControlledByAI()
convertTo: 创世纪指挥中心t3
displayType: upgrade
iconImage: G.png
addResources: bj=300
price: 0
text: Выбрать Альянс Генезис
buildSpeed: 0s
highPriorityQueue: true
ai_isHighPriority: true
addGlobalTeamTags: 我是创世纪


[action_upgrade_2]
isVisible: if self.isControlledByAI()
isActive: if self.isControlledByAI()
convertTo:AI核心作战中枢t3
addResources: ry=300
iconImage: A.png
displayType: upgrade
addGlobalTeamTags: 我是余晖
price: 0
text: Выбрать Зарево
buildSpeed: 0s
highPriorityQueue: true
ai_isHighPriority: true



[action_upgrade_3]
isVisible: if self.isControlledByAI()
isActive: if self.isControlledByAI()
convertTo: 太空浪人枢纽t3
iconImage: R.png
displayType: upgrade
addGlobalTeamTags: 我是浪人
price: 0
text: Выбрать Космических Скитальцев
buildSpeed: 0s
highPriorityQueue: true
ai_isHighPriority: true



[action_t1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
convertTo: 创世纪指挥中心t3
addGlobalTeamTags: 我是创世纪
addResources: bj=300
[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
shadowOffsetX: 3

shadowOffsetY: 3
imageScale: 0.7


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 95

turretSize: 0
turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1
[effect_冲击波]
image: 主.png
life: 75
fadeOut: true
attachedToUnit: false
scaleFrom: 0.11

scaleTo: 0.15
alpha: 0.8
drawUnderUnits: true
atmospheric:false
priority: critical
color:#FF00FF00
[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 110
fadeOut: true
scaleTo: 15
scaleFrom: 12
alpha: 0.7
attachedToUnit: false
color:#FF00FF00
fadeInTime: 2
drawUnderUnits: true
atmospheric: false
[ai]
useAsBuilder: true


