


[core]
name: 选择阵营（无t4）
class: CustomUnitMetadata
price: 0
maxHp: 999999
radius: 100
techLevel: 1
buildSpeed: 0.0005
isBio: false
isBuilding: true
nanoRange: 400
nanoBuildSpeed: 1.1
canRepairBuildings: true
canRepairUnits: true
canReclaimResources: true
isPickableStartingUnit: true

[hiddenAction_禁止t4]
autoTrigger: if not self.globalTeamTags(includes='禁止t4')
addGlobalTeamTags: 禁止t4

#————————————————————选择器
[action_总产出]
isActive: false
text: 剩余时间：%{30-self.timeAlive}
isVisible: true
displayType: infoOnlyNoBox
description:如果超过剩余时间仍未选择阵营，将默认选择创世纪联盟
[action_创]
isVisible: if not self.tags(includes= '创世纪') 
isActive: true
iconImage: G.png
price: 0
text: 创世纪联盟
buildSpeed: 0s
pos: 0.1
highPriorityQueue: true
ai_isHighPriority: false

temporarilyAddTags:创世纪
temporarilyRemoveTags:余晖,浪人
playSoundToPlayer:创.wav
[action_选了创]
pos: 0.1
displayType: infoOnly
isGuiBlinking: true
iconImage:G.png
text:已选择
isActive: false
isVisible:if self.tags(includes= '创世纪') 
description: 为了对抗帝国余晖，全世界人类组成了创世纪联盟。\n-虽然实力不济，但创世纪联盟依旧是对抗余晖的主力，并艰难的维持着人类社会的秩序，\n-但是一次又一次的战斗证明，低估创世纪的战斗潜力是愚蠢且富有偏见的。\n-创世纪是一个以动能和爆炸类武器为主的阵营，\n-非常擅长利用大规模的经济体系，将各种资源快速转化为生产力和战斗力摧垮对手。\n-同时拥有许多战术单位，以及大型轰炸机等。\n-玩家的操作水平直接决定了单位的战斗力，如果使用不当则下限很低。\n-同时创世纪还十分擅长防御作战。\n-上手难度较难。


[action_余]
isVisible: if not self.tags(includes= '余晖') 
isActive: true
iconImage: A.png
price: 0
text: 帝国余晖
buildSpeed: 0s
pos: 0.2
highPriorityQueue: true
ai_isHighPriority: false

temporarilyAddTags:余晖
temporarilyRemoveTags:创世纪,浪人
playSoundToPlayer:余.wav
[action_选了余]
pos: 0.2
displayType: infoOnly
isGuiBlinking: true
iconImage:A.png
text:已选择
isActive: false
isVisible:if self.tags(includes= '余晖') 
description: 帝国余晖是诺瓦帝国创造的自动化作战部队，余晖AI的目标是清除帝国境内所有危险因素，\n-保证帝国的安全与稳定，同时又将地球上所有人类认定为侵占帝国领土的外星敌人，\n-从而派遣军队以保卫领土为目标与两方展开战争。\n-帝国余晖阵营的兵力主要使用能源类武器与爆炸武器，并且往往拥有同时期最为强大的作战单位，\n-这让帝国余晖在正面战场拥有极高的优势，并无需太多操作和战术即可发挥出强大的战斗力。\n-同时，帝国余晖使用空投建造建筑物，这极大的节省了时间。\n-帝国余辉阵营不需要过多操作，强大的属性使得帝国余晖几乎不会在正面战斗中落得下风，\n-操作难度较为简单。


[action_浪]
isVisible: if not self.tags(includes= '浪人') 
isActive: true
iconImage: R.png
price: 0
text: 太空浪人
buildSpeed: 0s
pos: 0.3
highPriorityQueue: true
ai_isHighPriority: false

temporarilyAddTags:浪人
temporarilyRemoveTags:创世纪,余晖
playSoundToPlayer:浪.wav
[action_选了浪]
pos: 0.3
displayType: infoOnly
isGuiBlinking: true
iconImage:R.png
text:已选择
isActive: false
isVisible:if self.tags(includes= '浪人') 
description:太空浪人原名艾文诺拉联合秩序，而"太空浪人"则是其一个及其普遍的外号。\n-太空浪人代表目前已知的古人类最后的幸存者，在逃离成为炼狱的家乡后，\n-他们乘坐的火种舰坠落在地球上，目前正与人类协同对抗他们共同的敌人帝国余晖。\n-太空浪人是一个以动能和能源武器为主的阵营。\n-太空浪人的大部分机械单位都具有自我修复能力，以及强大的战斗力，\n-而生物单位的优势则在于快速生产并以压倒性的数量，再加上强大的同化能力可以快速撕开敌人防线，\n-并为机械单位创造机会和提供掩护，利用小规模无缝进攻快速击溃敌人。\n-太空浪人拥有独特的传送机制，这种强大的能力能快速建造大量部队，\n-或进行各种偷袭战术以取得决定性的优势。\n-上手难度中
#——————————————确定
[action_确定]
isVisible:if not self.tags(includes= '完成选择')
isActive: if not self.tags(includes= '完成选择')
iconImage: 对勾.png
price: 0
text: 确定
buildSpeed: 0s
pos: 0.4
highPriorityQueue: true
ai_isHighPriority: false
temporarilyAddTags:完成选择
isLocked: if not self.tags(includes= '创世纪') and not self.tags(includes= '余晖') and not self.tags(includes= '浪人')
isLockedMessage: 请先选择阵营
[action_注意]
iconImage: 感叹号.png
text: 注意
isActive: false
isVisible: true
displayType: infoOnly
pos: 9999
isGuiBlinking: true
description:注意，这场战斗将被禁止使用t4单位
#——————————————转换
[hiddenAction_g1]
autoTrigger: if self.tags(includes= '创世纪') and self.tags(includes= '完成选择')
convertTo: 创世纪指挥中心t1
addGlobalTeamTags: 我是创世纪
[hiddenAction_a1]
autoTrigger: if self.tags(includes= '余晖') and self.tags(includes= '完成选择')
convertTo: 请选择空降地点
showMessageToPlayer:请选择AI核心作战中枢t1空降地点。
addGlobalTeamTags: 我是余晖
[hiddenAction_r1]
autoTrigger: if self.tags(includes= '浪人') and self.tags(includes= '完成选择')
convertTo: 正在传送
addGlobalTeamTags: 我是浪人
[decal_1]
image: 在1.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人') or self.tags(includes= '余晖') or self.tags(includes= '创世纪')

yOffsetRelative:110
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own

[decal_2]
image: 余1.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人') or self.tags(includes= '余晖') or self.tags(includes= '创世纪')

yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own
[decal_3]
image: 浪1.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人') or self.tags(includes= '余晖') or self.tags(includes= '创世纪')

yOffsetRelative:-110
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own
[decal_4]
image: 主.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.115
onlyTeam:own
color:#FF00FF00
teamColors: true
[decal_5]
image: 主要.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.1
onlyTeam:own
[decal_6]
image: 在.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '创世纪') 
yOffsetRelative:110
xOffsetRelative:0
onlyWhileAlive:true
onlyTeam:own
imageScale:0.25
[decal_7]
image: 余.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '余晖') 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own
[decal_8]
image: 浪.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '浪人')
yOffsetRelative:-110
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.25
onlyTeam:own

[decal_9]
image: 蜂窝.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:1.5
alpha:0.7

[decal_10]
image: 无t4.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
yOffsetRelative:100
xOffsetRelative:-108
onlyWhileAlive:true
imageScale:0.1
onlyTeam:own
[hiddenAction_1]
autoTrigger: if not self.tags(includes= '余晖') and not self.tags(includes= '浪人') and not self.tags(includes= '创世纪') 
spawnEffects: CUSTOM:闪光,CUSTOM:冲击波

#——————————————ai
[action_upgrade_1]
isVisible: if self.isControlledByAI()
isActive: if self.isControlledByAI()
convertTo: 创世纪指挥中心t1
displayType: upgrade
iconImage: G.png

price: 0
text: 选择创世纪阵营
buildSpeed: 0s
highPriorityQueue: true
ai_isHighPriority: true
addGlobalTeamTags: 我是创世纪


[action_upgrade_2]
isVisible: if self.isControlledByAI()
isActive: if self.isControlledByAI()
convertTo: 请选择空降地点
iconImage: A.png
displayType: upgrade
addGlobalTeamTags: 我是余晖
price: 0
text: 选择余辉阵营
buildSpeed: 0s
highPriorityQueue: true
ai_isHighPriority: true



[action_upgrade_3]
isVisible: if self.isControlledByAI()
isActive: if self.isControlledByAI()
convertTo: 正在传送
iconImage: R.png
displayType: upgrade
addGlobalTeamTags: 我是浪人
price: 0
text: 选择太空浪人阵营
buildSpeed: 0s
highPriorityQueue: true
ai_isHighPriority: true



[action_t1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
convertTo: 创世纪指挥中心t1
addGlobalTeamTags: 我是创世纪

[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
shadowOffsetX: 3

shadowOffsetY: 3
imageScale: 0.7


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 95

turretSize: 0
turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1
[effect_冲击波]
image: 主.png
life: 75
fadeOut: true
attachedToUnit: false
scaleFrom: 0.11

scaleTo: 0.15
alpha: 0.8
drawUnderUnits: true
atmospheric:false
priority: critical
color:#FF00FF00
[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 110
fadeOut: true
scaleTo: 15
scaleFrom: 12
alpha: 0.7
attachedToUnit: false
color:#FF00FF00
fadeInTime: 2
drawUnderUnits: true
atmospheric: false
[ai]
useAsBuilder: true


