


[core]
name: 迫击炮t4
displayText: миномётt4
displayDescription: 【Уровень t4】【Оборонительное здание】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение: противомассовая башня。вооружение：\n-▲миномётX1 только по земле，взрывной урон\n-▲противокорабельный臼炮x1 толькоможет攻击надводный юнит 对极端重 юнит，和наземный юнитэффект差  \n-Стандартный автоматически заряжающийся миномёт Генезиса\n-Эта башня эффективна против скоплений вражеской брони，\n-и массовых атак малых юнитов。
price: 8000
maxHp: 20000

footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 20
techLevel: 1
fogOfWarSightRange: 50
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 10s
radius: 16
buildingSelectionOffset: -8
armour:35

isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1,largeExplosion*1
tags: 地面,建筑,防御建筑
energyMax: 4
energyRegen: 0
energyNeedsToRechargeToFull: true
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_炮塔影子]
image: 影子.png
total_frames: 1
layer: afterBody
isVisible:if not self.tags(includes= '反舰')
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 1
imageScale:0.9
[decal_炮管影子]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:if not self.tags(includes= '反舰')
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 2
imageScale:0.9

[decal_炮塔影子1]
image: 影子.png
total_frames: 1
layer: afterBody
isVisible:if self.tags(includes= '反舰')
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 3
imageScale:0.9
[decal_炮管影子1]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:if self.tags(includes= '反舰')
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 4
imageScale:0.9
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/t4影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
alpha:0.65
[action_反舰模式]
text: противокорабельный模式
displayType: action
buildSpeed: 0s
pos: 0.1
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: X.png
temporarilyAddTags:反舰
isVisible: if not self.tags(includes= '反舰')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 为миномёт换装大口径臼炮弹药进行曲射противокорабельный，\n-这вид重 弹头не толькодальность极далекои且можетпо воде面корабль造成毁灭性удар。\n-切换模式后，миномёт将дальностьповышает至1400，改用单 无导炮弹，итолькоможет攻击надводный юнит，\n-даже если该оружиеможет通过溅射的方式伤害до非надводный юнит，но其伤害очень之低。\n-对极端重 юнитэффект差。
isLocked:if self.queueSize> 0  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: 换装弹药中，пожалуйста, подождите
setResourcesWithLogic: energy=0
resetCustomTimer: true
[action_普通模式]
text: обычный模式
displayType: action
buildSpeed: 0s
pos: 0.2
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: X1.png
temporarilyRemoveTags:反舰
isVisible: if self.tags(includes= '反舰')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 为миномёт换装经典的小口径миномёт弹，\n-миномёт塔射出的弹幕对于绝大部分бронетехника都весьмасмертельный。\n-切换模式后，миномёт将может回复攻击всеназемный юнит的функция，\n-нодальность将缩减至650。
isLocked:if self.queueSize> 0  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: 换装弹药中，пожалуйста, подождите
setResourcesWithLogic: energy=0
resetCustomTimer: true
[hiddenAction_装填]
autoTrigger: if self.isEnergyEmpty() and not self.tags(includes= '切枪') and not self.tags(includes= '反舰')
temporarilyAddTags:切枪
alsoQueueAction: bx
resetCustomTimer: true
[hiddenAction_装填1]
autoTrigger: if self.isEnergyEmpty() and not self.tags(includes= '切枪') and self.tags(includes= '反舰')
temporarilyAddTags:切枪
alsoQueueAction: cx
resetCustomTimer: true
[action_bx]
displayType: action
price: 0
buildSpeed: 3.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
addResources:energy=4
[action_cx]
displayType: action
price: 0
buildSpeed: 1s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
addResources:energy=4
[decal_覆盖]
image: 盖子.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if not self.tags(includes= '反舰')
yOffsetRelative:-3
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret:1
imageScale:0.9
[decal_覆盖1]
image: 盖子.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.tags(includes= '反舰')
yOffsetRelative:-3
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret:3
imageScale:0.9

[decal_装填]
image: 填弹器1.png
total_frames: 49
frame: select(self.tags(includes= '切枪'), (self.customTimer * 14) % 49, 0)
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 1
layer:onTop
isVisible:if self.tags(includes= '切枪') and not self.tags(includes= '反舰')
onlyWhileAlive:true
yOffsetRelative:-14
xOffsetRelative:-0.5
imageScale:0.9
[decal_装填1]
image: 大填弹器.png
total_frames: 13
frame: select(self.tags(includes= '切枪'), (self.customTimer * 13) % 13, 0)
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 3
layer:onTop
isVisible:if self.tags(includes= '切枪') and self.tags(includes= '反舰')
onlyWhileAlive:true
yOffsetRelative:-14
xOffsetRelative:-0.5
imageScale:0.9

[decal_壳]
image: 壳.png
total_frames: 1
layer: onTop
teamColors: true
yOffsetRelative:-14
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret:1
imageScale:0.9
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '反舰')

[decal_壳1]
image: 壳.png
total_frames: 1
layer: onTop
teamColors: true
yOffsetRelative:-14
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret:3
imageScale:0.9
isVisible:if not self.tags(includes= '切枪') and self.tags(includes= '反舰')


[decal_灯光]
image: ROOT:/创世纪军事集团/建筑特效/led.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:true
yOffsetRelative:-3
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.85
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/大支撑.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-30
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.9
alpha:0.9
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image: ROOT:/创世纪军事集团/建筑特效/防御塔t4底座.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_offsetY: 1

image_back: ROOT:/通用特效/NO.png
#AUTO
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9
turretImageScale: 0.9
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 12
turretMultiTargeting: true
turretTurnSpeed: 6
maxAttackRange: 1150
shootDelay: 0
[turret_1]
x: 0
y: 34
canShoot: false
idleSweepAngle: 100
idleSweepDelay: 210
idleSweepSpeed: 0.2
recoilOffset: -1
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '反舰')
invisible: if self.tags(includes= '反舰')
limitingRange:650
image:底.png
[turret_2]
x: 0
y: 20
shoot_sound: ROOT:/创世纪军事集团/单位特效/迫击炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFFEB88
shoot_flame: CUSTOM:烟雾1*4,LARGE
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '反舰')
invisible: if self.tags(includes= '反舰')
image: 管子.png
attachedTo: 1
recoilOffset: -4
recoilOutTime: 2
limitingRange:650
recoilReturnTime: 10
slave: true
delay:15
energyUsage:1
[turret_3]
x: 0
y: 34
canShoot: false
idleSweepAngle: 100
idleSweepDelay: 210
idleSweepSpeed: 0.2
recoilOffset: -1
canAttackCondition: if self.resource.xk < 1 and  self.tags(includes= '反舰')
invisible: if not self.tags(includes= '反舰')
image:底.png
canOnlyAttackUnitsWithTags:海上
[turret_4]
x: 0
y: 20
projectile: 2
attachedTo: 3
slave: true
image: 管子.png
shoot_flame: CUSTOM:烟雾1*8,CUSTOM:冲击波t,CUSTOM:闪光t
shoot_sound: ROOT:/创世纪军事集团/单位特效/巨炮发射.wav
shoot_sound_vol: 0.5
canAttackCondition: if self.resource.xk < 1 and self.tags(includes= '反舰')
invisible: if not self.tags(includes= '反舰')
size:11
delay:120
warmup:160
energyUsage:4
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
limitingMinRange:50
canOnlyAttackUnitsWithTags:海上
recoilOffset: -8
recoilOutTime: 8
recoilReturnTime: 70
[projectile_1]
@copyFromSection: template_爆炸
life: 6661
speed: 5
targetSpeed: 6
drawSize: 0.75
image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
areaDamage: 1350
areaRadius: 80
targetGround: true
initialUnguidedSpeedHeight: 1.5
areaRadiusFromEdge: true
gravity: 0.4
targetGroundSpread: 35
lightColor: #FFFFFF73
explodeEffect: CUSTOM:冲击波hx,CUSTOM:爆炸hx,CUSTOM:闪光hx,CUSTOM:弹坑,CUSTOM:黑雾
explodeEffectOnShield: CUSTOM:冲击波hx,CUSTOM:爆炸hx,CUSTOM:闪光hx,CUSTOM:弹坑,CUSTOM:黑雾
disableLeadTargeting: true
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
life: 800
speed: 6.5
deflectionPower: -1
areaRadiusFromEdge: true
targetSpeed: 6.5
image: ROOT:/创世纪军事集团/单位特效/光球.png
drawSize: 0.75
explodeEffect: NONE
initialUnguidedSpeedHeight: 3.5
trueGravity: 0.02
lightSize: 0.75
trailEffectRate: 0.5
trailEffect: CUSTOM:尾尾1
lightColor: #FFFFFF73
targetGround:true
disableLeadTargeting: true
targetGroundSpread: 40
spawnProjectilesOnExplode: 4x
[projectile_4x]
@copyFromSection: template_爆炸
areaDamage: 700
areaRadius: 100
life: 0
speed: 1
deflectionPower: -1
areaRadiusFromEdge: true
targetSpeed: 9999
frame:1
drawSize: 0
explodeEffect: CUSTOM:爆炸p,CUSTOM:气浪p,CUSTOM:冲击波p,CUSTOM:闪光p*2,CUSTOM:弹坑p
lightSize: 0
targetGround:true
explodeOnEndOfLife: true
mutator7_ifUnitWithTags: 海上
mutator7_directDamageMultiplier: 8
mutator7_areaDamageMultiplier: 8
mutator70_ifUnitWithTags: 极端重型
mutator70_directDamageMultiplier: 0.5
mutator70_areaDamageMultiplier: 0.5
#——————————————————开炮
[effect_冲击波t]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 2.6
alpha: 0.8
fadeOut: true
fadeInTime: 2
[effect_闪光t]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false
atmospheric: false
[effect_烟雾1]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 60
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: 0.3
ySpeedRelativeRandom: 0.35
xSpeedRelativeRandom: 0.2
yOffsetRelative: 0
atmospheric: true
[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.3
scaleTo: 0.1
alpha: 1
drawUnderUnits: true
#——————————————————爆炸
[effect_爆炸hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.44
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
alwayStartDirAtZero: true
[effect_闪光hx]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 1.3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life:150
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 1.2
scaleTo: 1.2
createWhenOverLiquid: false
createWhenOverLand: true
[effect_黑雾]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true
life: 200
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.35
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 10
yOffsetRelativeRandom: 10
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
#臼炮特效————
[effect_弹坑p]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.2
scaleTo: 2.2
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true
[effect_气浪p]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 6.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true
[effect_闪光p]
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波p]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_爆炸p]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 4.2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true
[effect_尾尾1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0

turnAcceleration: 0


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


