
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=300

[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true

[core]
name: 苍穹猎者1
displayText: Небесный Охотник1
showInEditor: false
maxHp: 6000
price: 6000,蓝晶=550
maxShield: 6000
shieldRegen: 0.07
shieldRenderRadius: 1
displayDescription: 【Уровень t4】【Преодолевает утёсы】【Беспилотный юнит】【Наземный юнит】тактическое назначение:ПВО/антибиологический мех, размер юнита:6.\n-вооружение:▲дробовик «Драконье дыхание»X1 только по земле взрывной урон против укрытийи накладывает горение на врагов.\n-▲тяжёлый пулемётX1 только по земле энергетический урон против укрытий \n-▲лазерная установка ближнего бояX2 только по воздуху энергетический урон \n-▲сингулярностьторпеда(взрывной урон), ЭМП-торпеда(нейтральный урон), плазменная торпеда(энергетический урон)только по высотным\n-На начальном этапе высадки десанта , часто терпит большие потери от воздушных ударов со всех сторон.\n-Для решения этой проблемы,, имперский флот заказал Имперский Университет Гранддейлразработать тяжёлый десантируемый ПВО-юнит.\n-Небесный Охотниквыделяется среди прочих вариантов, многофункциональный, не только быстро уничтожает приближающихся вражеских истребителей плечевым лучевым оружием,, \n-но и может обеспечивать базовую оборону земли плазменным дробовиком «Драконье дыхание» в руках, \n-Ключевое снаряжение - спинная торпедная пусковая система, чередующая три типа боеприпасов, \n-Плотный огневой щит способен сбить на больших дистанциях любой вражескийвоенный корабльили большой снаряд.
techLevel: 1
transportSlotsNeeded: 6
buildSpeed: 23s
radius: 52
displayRadius: 52
fogOfWarSightRange: ${int(attack.maxAttackRange/17.5)}
armour: 25
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:中余晖单位死亡冲击波,CUSTOM:中余晖单位死亡爆炸,CUSTOM:中余晖单位死亡钢珠,CUSTOM:中余晖单位死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:6)
tags: 地面,无人单位,反高空,苍穹猎者
[hiddenAction_创1造]
autoTrigger: if attachment(slot= '2') == nullUnit
attachments_onlyOnSlots: 2
attachments_addNewUnits:通用挂载附属1
[attachment_2]
x: 0
y: 0
onCreateSpawnUnitOf: 通用挂载附属1
lockRotation: true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
onConvertKeepExistingUnitInSameSlot:true
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
#——！————————————变形
[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 560 | setFlag= 0)
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 560 | setFlag= 0)
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false
onConvertKeepExistingUnitInSameSlot:true
[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", greaterThan= 0.5)
isVisible: false
alsoQueueAction: b
[action_b]
convertTo: 苍穹猎者
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed
#——！————————————贴画
#——！———————影子
[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:9
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_6
[decal_枪]
image: SHADOW:霰弹枪1.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_1
[decal_左手影]
image: SHADOW:左手.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_3
[decal_右手影]
image: SHADOW:右手.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_2
[decal_装填]
image:装弹.png
total_frames: 8
frame: select(self.tags(includes= '切枪'), (self.customTimer * 14) % 8, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:11
xOffsetRelative:-4
basePositionFromLegEnd: arm_1
[decal_左手]
image: 左手.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_3
[decal_右手]
image: 右手.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_2
[decal_左手1]
image: 小胳膊.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_4
[decal_右手1]
image: 小胳膊.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_5
[decal_主体]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_6
[decal_主体1]
image: 损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_6
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[decal_炮塔]
image: 加特林动画.png
total_frames: 3
frame: (self.customTimer * 30) % 3
basePositionFromTurret: 1
isVisible:if self.isAttacking()
onlyWhileAlive:true
layer: onTop
yOffsetRelative:60.5
xOffsetRelative:-17.5
[decal_射线]
image:射线.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:58
xOffsetRelative:-16
onlyWhileAlive:true
basePositionFromLegEnd: arm_1
[decal_机体灯]
image:灯光.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_6
#——！————————————装弹

[hiddenAction_装填]
addResources: 弹药=1
[hiddenAction_装]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
whenBuilding_cannotMove:false
allowMultipleInQueue:false
autoTrigger: if self.resource.弹药>0.5 and not self.tags(includes= '切枪')
alsoQueueAction: ax
[action_ax]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
alsoQueueAction: bx
resetCustomTimer: true
temporarilyAddTags: 切枪
[action_bx]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
addResources:弹药=-1
[graphics]
image: NO.png
image_wreak: 死.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 460
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: true

turretMultiTargeting: false
[turret_1]
x: 0
y: 0
canShoot: false
invisible: true
[turret_2]
x: -18
y: 58
attachedTo: 1
slave: true
image: NO.png
shoot_flame: CUSTOM:枪口火焰
shoot_sound: ROOT:/余辉军团/单位特效/机炮.wav
shoot_sound_vol: 0.12
recoilOffset: -6
recoilOutTime: 2
shoot_light: #FF00B3FF
recoilReturnTime: 10
projectile: 1
size: 18
delay:5
canAttackCondition: if self.resource.xk < 1
invisible:true
canAttackFlyingUnits: false
[turret_3]
x: 18
y: 85
#导弹右
projectile: 2
attachedTo: 1
slave: true
shoot_sound: ROOT:/余辉军团/单位特效/迫击炮.wav
shoot_sound_vol: 0.4
shoot_flame: CUSTOM:弹壳,CUSTOM:烟雾x*4,CUSTOM:火星*1,CUSTOM:闪光www
shoot_light:  #FF00B3FF
canShoot: true
size:32
delay:120
canAttackCondition: if self.resource.xk < 1 and self.resource.弹药<0.5
invisible:true
onShoot_triggerActions:装填
canAttackFlyingUnits: false
onShoot_playAnimation: attack
[turret_234]
x: 0
y: 0
projectile: 233
warmup: 1s

delay: 0.9s
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
invisible: true
attachedTo: 1
slave: true
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[projectile_1]
@copyFromSection: template_能源
directDamage: 70
life: 240
speed: 14
targetSpeed: 14
deflectionPower: -1
image:ROOT:/余辉军团/单位特效/粒子2.png
explodeEffect: CUSTOM:火花
drawSize: 0.45
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[projectile_2]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
targetGroundSpread: 70
spawnProjectilesOnEndOfLife: 3*3(recursionLimit= 17)
[projectile_3]
areaDamage: 600
areaRadius: 65
life: 600
speed: 12
drawSize: 1
largeHitEffect: true
lightSize: 2
lightColor: #FF00B3FF
image:ROOT:/余辉军团/单位特效/小闪光.png
trailEffectRate: 0.7
trailEffect:CUSTOM:尾巴
areaRadiusFromEdge: true
disableLeadTargeting: true
targetGround: true
areaDamageNoFalloff: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=3
explodeEffect: CUSTOM:闪光wy2*2,CUSTOM:火光wy,CUSTOM:冲击波wy,CUSTOM:闪光wy1,CUSTOM:巨大冲击波wy,CUSTOM:闪光wy,CUSTOM:实验wy,CUSTOM:火星wy*2

targetGroundSpread: 70
speedSpread:1.6
#——————————机关枪
[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/余辉军团/单位特效/枪口火焰.png
total_frames: 3
scaleFrom: 2
scaleTo: 4
animateFrameStart: 0
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
[effect_火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 0.34
image: ROOT:/余辉军团/单位特效/大火花.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2
#——————————主炮开火
[effect_弹壳]
image: 弹壳.png
spawnChance: 1
life: 130
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelative: 1
ySpeedRelative: 0
xSpeedRelativeRandom: -0.05
ySpeedRelativeRandom: 0.2
yOffsetRelative: -45
xOffsetRelative: 10
hSpeed: 2
dirSpeedRandom: 30
[effect_闪光www]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FF00B3FF
scaleFrom: 4
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_烟雾x]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom:1.3
scaleTo: 2.4
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.6
atmospheric: true
[effect_火星]
priority:low
spawnChance: 1
image: ROOT:/余辉军团/单位特效/火星.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.4
scaleTo: 1.9
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelative: 1
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2
atmospheric: true
[effect_尾巴]
priority: low
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
life: 17
fadeOut: true
attachedToUnit: false
fadeInTime: 2
scaleFrom: 0.4
scaleTo: 0.7
alpha: 0.75
drawUnderUnits: false
atmospheric: false
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13
animateFrameSpeed: 0.3
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -5
#————————温压弹
[effect_火光wy]
priority: critical
image: ROOT:/通用特效/火光y.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 4
scaleTo: 4
alwayStartDirAtZero: true
color: #FF00B3FF
alpha: 0.9
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/通用特效/巨炮爆炸.wav
[effect_冲击波wy]
stripIndex: shockwave
life: 80
scaleFrom: 1
scaleTo: 6
alpha: 1
color:#FFFFFFFF
[effect_闪光wy]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFFFF
scaleFrom: 7.5
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true

[effect_闪光wy1]
image: SHARED:light_50.png
life: 80
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo:5
drawUnderUnits: false
atmospheric: false
[effect_巨大冲击波wy]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 1.9
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
color: #FF00B3FF
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_实验wy]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.2
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[effect_闪光wy2]
image: SHARED:light_50.png
life: 75
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FF00B3FF
priority: critical
fadeInTime: 2
scaleFrom: 2.2
scaleTo: 2.2
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/余辉军团/单位特效/火星.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.8
scaleTo: 2.2
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:65
yOffsetRelativeRandom:65
[arm_1]
x: 18
y: 68
image_end: 霰弹枪1.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -5
[arm_2]
x: 40
y: 25
image_end: 右手.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -30

[arm_3]
x: -35
y: 44
image_end: 左手.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_4]
x: -25
y: 16
image_end: 小胳膊.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -40
[arm_5]
x: 34
y: 2
image_end: 小胳膊.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 35
[arm_6]
#左肩
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true

drawOverBody: true




[leg_1]
x: -46
y: 48
attach_x: -17
attach_y: 21
moveSpeed: 2

rotateSpeed: 6
heightSpeed: 0.5
resetAngle: 22
image_leg:大腿.png
image_foot: 脚.png

holdDisMin: 14
holdDisMax: 26
endDirOffset: -45
hardLimit: 40
hidden: if self.hasParent()


[leg_2]
x: 46
y: 48
attach_x: 17
attach_y: 21
copyFrom: 1

endDirOffset: 45
hidden: if self.hasParent()


[leg_3]
x: -46
y: -18
attach_x: -17
hidden: if self.hasParent()
attach_y: -3

copyFrom: 1
endDirOffset: -135


[leg_4]
x: 46
y: -18
attach_x: 17
attach_y: -3
copyFrom: 1

endDirOffset: 135
hidden: if self.hasParent()


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}


arm1_0.6s: {x:-8, y:-2, dir:-55}
arm2_0.6s: {x:0, y:11, dir:-20}
arm3_0.6s: {x:0, y:7, dir:20}
arm4_0.6s: {x:-4, y:10, dir:0}
arm5_0.6s: {x:0, y:14, dir:0}


[animation_attack]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm1_0.1s: {x:0, y:-20, dir:0}
arm2_0.1s: {x:0, y:-8, dir:-5}
arm3_0.1s: {x:0, y:-8, dir:5}
arm4_0.1s: {x:0, y:-8, dir:0}
arm5_0.1s: {x:0, y:-8, dir:0}

[resource_弹药]
displayName: Боеприпасы
displayNameShort: Боеприпасы
displayColor: #FF9D00FF
priority: 1
hidden: true
[movement]
movementType: OVER_CLIFF
moveSpeed: 0.7
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 0.75

turnAcceleration: 0.08
targetHeight: 3
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0.4

slowDeathFall: true


