

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=300

[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true
[core]
name: 苍穹猎者
price: 6000,蓝晶=550
maxHp: 6000
maxShield: 6000
shieldRegen: 0.07
shieldRenderRadius: 1
displayDescription: 【阶级t4】【可翻越悬崖】【无人单位】【地面单位】战术定位:防空/反生物机甲，单位体积：6。\n-武器配置：▲龙息霰弹枪X1 只能对地 爆炸伤害 反掩体并对敌人施加燃烧效果。\n-▲重机枪X1 只能对地 能源伤害 反掩体 \n-▲点防御激光炮X2 只能对空 能源伤害 \n-▲奇点鱼雷（爆炸伤害），EMP鱼雷（中性伤害），等离子鱼雷（能源伤害）只能对高空\n-当空降部队降落初期，往往因从四面八方而来的空袭而遭受巨大损失。\n-为解决这一问题，帝国皇家舰队要求格兰戴尔帝国大学研发一款重型可空降的防空单位。\n-苍穹猎者则在各种方案中脱颖而出，功能多样，不仅能利用肩部的光束武器快速摧毁来袭敌机，\n-手中的等离子龙息散弹枪也能提供最基本的对地防御，\n-而其最核心的装备是其背后能够交替发射三种类型弹药的鱼雷发射系统，\n-发射出的密集火力网足以在极远的距离上击坠任何敌方战舰或是大型射弹。
techLevel: 1
transportSlotsNeeded: 6
buildSpeed: 23s
radius: 52
displayRadius: 52
fogOfWarSightRange: ${int(attack.maxAttackRange/17.5)}
armour: 25
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:中余晖单位死亡冲击波,CUSTOM:中余晖单位死亡爆炸,CUSTOM:中余晖单位死亡钢珠,CUSTOM:中余晖单位死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:6)
tags: 地面,无人单位,反高空,苍穹猎者
[hiddenAction_创1造]
autoTrigger: if attachment(slot= '2') == nullUnit
attachments_onlyOnSlots: 2
attachments_addNewUnits:通用挂载附属1
[attachment_2]
x: 0
y: 0
onCreateSpawnUnitOf: 通用挂载附属1
lockRotation: true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
onConvertKeepExistingUnitInSameSlot:true
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
#——！————————————贴画
#——！———————影子
[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:9
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_6
[decal_枪]
image: SHADOW:霰弹枪1.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_1
[decal_左手影]
image: SHADOW:左手.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_3
[decal_右手影]
image: SHADOW:右手.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_2
[decal_左手]
image: 左手.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_3
[decal_右手]
image: 右手.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_2
[decal_左手1]
image: 小胳膊.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_4
[decal_右手1]
image: 小胳膊.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_5
[decal_主体]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_6
[decal_主体1]
image: 损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_6
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[decal_炮塔]
image: 加特林动画.png
total_frames: 3
frame: (self.customTimer * 30) % 3
isVisible:false
onlyWhileAlive:true
layer: onTop
yOffsetRelative:60.5
xOffsetRelative:-17.5
[decal_射线]
image:射线.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:58
xOffsetRelative:-16
onlyWhileAlive:true
basePositionFromLegEnd: arm_1
[decal_机体灯]
image:灯光.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_6


#——！————————————变形
[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 560 | setFlag= 0)
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 560 | setFlag= 0)
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: false
onConvertKeepExistingUnitInSameSlot:true
alwaysAllowedToAttackParentsMainTarget: false
[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5)
isVisible: false
alsoQueueAction: b
stopLastAnimation: true
[action_b]
convertTo: 苍穹猎者1
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed
#——！————————————变形
[graphics]
image: NO.png
image_wreak: 死.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14
turretMultiTargeting: false
turretTurnSpeed: 2
maxAttackRange: 900
shootDelay: 100
turretRotateWithBody: true

[turret_233]
x: 0
y: 0
projectile: 233
warmup: 1s

delay: 0.9s
limitingRange: 460
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true
[turret_234]
x: 0
y: 0
projectile: 233
warmup: 1s

delay: 0.9s
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
invisible: true
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[arm_1]
x: 10
y: 66
image_end: 霰弹枪1.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -60
[arm_2]
x: 40
y: 36
image_end: 右手.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -50

[arm_3]
x: -35
y: 51
image_end: 左手.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 40
[arm_4]
x: -29
y: 26
image_end: 小胳膊.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -40
[arm_5]
x: 34
y: 16
image_end: 小胳膊.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 35
[arm_6]
#左肩
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true

drawOverBody: true




[leg_1]
x: -46
y: 48
attach_x: -17
attach_y: 21
moveSpeed: 2

rotateSpeed: 6
heightSpeed: 0.5
resetAngle: 22
image_leg:大腿.png
image_foot: 脚.png

holdDisMin: 14
holdDisMax: 26
endDirOffset: -45
hardLimit: 40
hidden: if self.hasParent()


[leg_2]
x: 46
y: 48
attach_x: 17
attach_y: 21
copyFrom: 1

endDirOffset: 45
hidden: if self.hasParent()


[leg_3]
x: -46
y: -18
attach_x: -17
hidden: if self.hasParent()
attach_y: -3

copyFrom: 1
endDirOffset: -135


[leg_4]
x: 46
y: -18
attach_x: 17
attach_y: -3
copyFrom: 1

endDirOffset: 135
hidden: if self.hasParent()



[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}


arm1_0.6s: {x:8, y:2, dir:55}
arm2_0.6s: {x:0, y:-11, dir:20}
arm3_0.6s: {x:0, y:-7, dir:-20}
arm4_0.6s: {x:4, y:-10, dir:0}
arm5_0.6s: {x:0, y:-14, dir:0}


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.7
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 0.75

turnAcceleration: 0.08
targetHeight: 3
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0.4

slowDeathFall: true


