[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[action_拆除哇袄]
addResources: 威胁点数=-1000
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=1000,ry= ${ryxq}
[core]
selfRegenRate: 2
name: 建造璇星之梯
displayText: строительствоЛестница Звезды
class: CustomUnitMetadata
price: 15000,蓝晶=3000,ry= ${ryxq}
@global ryxq:20
reclaimPrice: ry= ${ryxq}
maxHp: 60000
footprint: -9,-7,9,6
constructionFootprint: -9,-7,9,6
showInEditor: false
techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:通用实验*2,CUSTOM:通用闪光nk,CUSTOM:通用聚变nk,CUSTOM:通用云雾2nk*2,CUSTOM:通用云雾1nk*2,CUSTOM:通用云雾nk*2,CUSTOM:通用冲击波nk,CUSTOM:通用冲击波nk1,CUSTOM:通用冲击波nk2,CUSTOM:通用冲击波nk3,CUSTOM:通用聚变nk1,CUSTOM:通用光球1nk,CUSTOM:通用光球nk,CUSTOM:震动
unitsSpawnedOnDeath: 建筑损毁*2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
radius: 130
softCollisionOnAll: 60
exit_x:0
exit_y: 70
exit_moveAwayAmount: 240
fogOfWarSightRange: 55
isBio: false
isBuilding: true
energyMax: 200
energyRegen: 0.056
energyStartingPercentage: 0
displayDescription: 【Уровень t4】【Сверхтяжёлый юнит】【Здание】【Наземный юнит】【Беспилотный юнит】\n-тактическое назначение: завод суперюнитов, без вооружения.\n-не может строиться на воде.Лестница Звездыэто Империя Новаи всей Древние Людивершина строительной материаловедческой науки, \n-Эта пронзающая небо громадина - Империя Новаодин из основных средств проекции военной силы в звёздной системе, \n-Опираясь на звёздные нановолокнаэти исключительно прочные нанокабели, его наземная станция способна перебрасывать целые легионы, \n-наружуилиили внутрь, перевозя сухопутные войска.а за облаками, связанными серебряными нитями, \n-Лестница Звездыорбитальная станция может оснащаться разнообразным вооружением, а также множеством снабжениепроизводственных линий.\n-Эти исполинские башни - символ развитости имперских планет, \n-одновременнои предвестие смены власти на враждебных мирах.
tags: 地面,建筑,无人单位,极端重型
selfBuildRate: 99999
buildSpeed: 0s
[hiddenAction_升级]
convertTo: 璇星之梯
autoTrigger:if self.energy==200
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
addResources: energy=1000

[hiddenAction_特效]
autoTrigger:true
isVisible: false
spawnEffects: CUSTOM:闪光*5,CUSTOM:光粒*3,CUSTOM:光粒1*3
[decal_影子]
image: SHADOW:影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:8
xOffsetRelative:25
onlyWhileAlive:true

alpha:min(0.6,((0.6/100)*(self.resource.energy)))


[decal_主体]
image: 建造1.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy>100
onlyWhileAlive:true
layer: onTop
teamColors: true
[decal_初始化]
image: 建造.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy<100
onlyWhileAlive:true
layer: onTop
alpha:(self.resource.energy)/100

[decal_初始化1]
image: 建造.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy>99.5
onlyWhileAlive:true
layer: onTop
alpha:1-(((self.resource.energy)-100)/100)

[decal_预览]
image: 图标.png
total_frames: 1
layer: onTop
isVisible: true
yOffsetRelative:160
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.9
onlyInPreview:true


[graphics]
total_frames: 1
image: NO.png
image_wreak:死亡.png
image_back: NO.png
#drawLayer: experimentals
#icon_build:图标.png
[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 0







[effect_震动]
createWhenOffscreen:true
drawType: displacement
image:震动.png
life:40
fadeOut: false
fadeInTime:50
attachedToUnit: true
scaleFrom:20
scaleTo:20
alpha:0.035
drawUnderUnits:false
alwayStartDirAtZero: true
total_frames: 2
animateFrameStart: 0
animateFrameEnd:1
animateFrameSpeed: 0.3
animateFrameLooping:true
showInFog: true
priority: critical


[effect_闪光]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: false
color: #FF5BFF23
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
xOffsetRelative:0
yOffsetRelative:150
xOffsetRelativeRandom:120
yOffsetRelativeRandom:200
alpha:0.8
delayedStartTimerRandom:50

[effect_光粒]
color: #FF5BFF23
priority: veryhigh
spawnChance: 1
image: ROOT:/余辉军团/建筑特效/粒.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 0.7
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.6
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.7
xSpeedRelativeRandom: 0.7
atmospheric: true
xOffsetRelative:0
yOffsetRelative:150
xOffsetRelativeRandom:120
yOffsetRelativeRandom:200
alpha:0.4
delayedStartTimerRandom:50

[effect_光粒1]
color: #FF5BFF23
priority: high
spawnChance: 1
image: ROOT:/余辉军团/建筑特效/粒.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 0.4
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.6
dirOffsetRandom: 360
ySpeedRelativeRandom: 1.4
xSpeedRelativeRandom: 1.4
atmospheric: true
xOffsetRelative:0
yOffsetRelative:150
xOffsetRelativeRandom:120
yOffsetRelativeRandom:200
alpha:0.4
delayedStartTimerRandom:50
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0


[ai]
buildPriority: 10
maxEachBase: 1
maxGlobal: 2
noneInBaseExtraPriority:100

