


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=450


[core]
name: SDSF恐惧级驱逐舰
displayText: SDSFэсминец класса «Ужас»
displayDescription: -эсминец класса «Ужас»это Аравелидская республикарасцвет (период)его космосфлот главныйпотокэсминец, \n-опираясь наего крайнеего сначалав антиобъекткачествокуча и многофункцияможет установкарасчёт,  и может выдающийся оружие, \n-использоватьего стать для Аравелидвоенный корабльустановкарасчёт пик делать, нетимеет любоймодель эсминецнужночемстрахуровеньещё болеемощный и прочныйдовольно.\n-тольконе , Когда носительимеет истинныйвоздушныйнулевая точкаможет реактор Империя Новафлотчтобы уничтожатьистощениегнилой силаоткрытьновый , когда эрабольшой дверь, когда , \n-разрешатьмногоэсминец класса «Ужас» корабльдлинный опираясь наего превосходный скоростьстепеньбыстрыйотделениеАравелиди добавитьвходит Империя Нова.\n-послеэтиубратьзахватить эсминец класса «Ужас», Империя Новадля его делает большой количествотекущийэрапереоборудованный, \n-например тот жеФеникснирванатяжёлый жизнь эсминец класса «Ужас», текущийв по-прежнемуможет эффективный уничтожитькаждыйвидвраги.\n-по земле и воздуху, ракетаторпедавзрыв, другие может источник.
class: CustomUnitMetadata
maxShield: 10000
shieldRegen: 0.1

price: 9000,蓝晶=800
maxHp: 8000
shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 40s

availableInDemo: true
radius: 75
shieldRenderRadius: 54

displayRadius: 75
isBio: false
transportSlotsNeeded: 20
effectOnDeathGroundCollision: CUSTOM:爆炸x*1
tags: 飞机,低空,恐惧,无人单位
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 恐惧
softCollisionOnAll: 20
armour: 25
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 26
[action_b]
displayType: action
price: 0
buildSpeed: 5s
isVisible: true
whenBuilding_cannotMove: false
text:подъёмвысокий высокий степень
description: подъёмвысокий эсминец класса «Ужас» высокий степень, использоватьего стать для высотный юнит.\n-увеличениедобавитьдальность, высокий воздушныйсостояниепод может атакаобычныйвоздушныйв юнит и высотный юнит
iconImage: ROOT:/通用特效/高空.png
allowMultipleInQueue:false
convertTo: SDSF恐惧级驱逐舰1
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or (not self.globalTeamTags(includes='禁卫军1') and self.noUnitInTeam(withTag= '余辉指挥中心t4'))
isLockedMessage: Требуется репликация вооружений гвардии 1 илибоевой центр ядра ИИ \nилиюнитполучаетк электричествомагнитныйподавление
[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=550, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=550, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
image_shield: 护盾.png
turretImageScale: 0.8

movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3
movementEffectRate: 1.5
animation_moving_start: 2
animation_moving_end: 2
animation_moving_speed: 8

animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 440
shootDelay: 0


[turret_1]
x: -25
y: 0.5
canShoot: true
image: 炮.png
delay: 25

limitingAngle: 40
idleDir: -90
shoot_sound: ROOT:/余辉军团/单位特效/大炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:气浪*1,CUSTOM:粒子*1

shoot_light: #FFccCCEE
projectile: 1
recoilOffset: -1


[turret_2]
x: -25
y: 24.5
canShoot: true
image: 炮.png
delay: 25

limitingAngle: 40
idleDir: -90
shoot_sound: ROOT:/余辉军团/单位特效/大炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:气浪*1,CUSTOM:粒子*1

shoot_light: #FFccCCEE
projectile: 1
recoilOffset: -1


[turret_3]
x: 25
y: 0.5
canShoot: true
image: 炮.png
delay: 25

limitingAngle: 40
idleDir: 90
shoot_sound: ROOT:/余辉军团/单位特效/大炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:气浪*1,CUSTOM:粒子*1

shoot_light: #FFccCCEE
projectile: 1
recoilOffset: -1


[turret_4]
x: 25
y: 24.5
canShoot: true
image: 炮.png
delay: 25

limitingAngle: 40
idleDir: 90
shoot_sound: ROOT:/余辉军团/单位特效/大炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:气浪*1,CUSTOM:粒子*1

shoot_light: #FFccCCEE
projectile: 1
recoilOffset: -1


[turret_5]
x: 18
y: -34.5
canShoot: true
size: 15
image: 导弹.png

delay: 10
limitingAngle: 40
idleDir: 90
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3

shoot_light: #FFEECCCC
shoot_flame: CUSTOM:烟雾
projectile: 2
canAttackLandUnits: false
recoilOffset: -1


[turret_6]
x: -18
y: -34.5
canShoot: true
size: 15
image: 导弹.png

delay: 10
limitingAngle: 40
idleDir: -90
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3

shoot_light: #FFEECCCC
shoot_flame: CUSTOM:烟雾
projectile: 2
canAttackLandUnits: false
recoilOffset: -1


[turret_8]
x: 0
y: 4
image: 鱼雷.png
attachedTo: 7
slave: true

shoot_sound: ROOT:/余辉军团/单位特效/鱼雷.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*3
shoot_light: #FFccCCEE
projectile: 3

limitingAngle: 30
delay: 120
recoilOffset: -5
recoilOutTime: 4
size: 10

recoilReturnTime: 160


[turret_7]
x: 0
y: 50
canShoot: false
image: 雷.png
delay: 180

limitingAngle: 30
recoilOffset: -1


[turret_12]
x: 0
y: 9
image: 管.png
attachedTo: 9
slave: true

shoot_sound: ROOT:/余辉军团/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_flame: NONE
shoot_light: #FFccCCEE
projectile: 4

limitingAngle: 70
delay: 5
canAttackLandUnits: false
recoilOffset: -1
size: 4


[turret_9]
x: -45
y: 74
canShoot: false
image: 枪.png
idleDir: -45

delay: 180
limitingAngle: 65
canAttackLandUnits: false


[turret_10]
x: 0
y: 9
image: 管.png
attachedTo: 11
slave: true

shoot_sound: ROOT:/余辉军团/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_flame: NONE
shoot_light: #FFccCCEE
projectile: 4

limitingAngle: 70
delay: 5
canAttackLandUnits: false
recoilOffset: -1
size: 4


[turret_11]
x: 45
y: 74
canShoot: false
image: 枪.png
idleDir: 45

delay: 180
limitingAngle: 65
canAttackLandUnits: false


[projectile_1]
@copyFromSection: template_能源
directDamage: 175
life: 100
speed: 7
image: ROOT:/余辉军团/单位特效/星星.png

drawSize: 0.55
lightSize: 1.5
lightColor: #FF00B3FF
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光*2,CUSTOM:爆炸1
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光*2,CUSTOM:爆炸1

trailEffect: CUSTOM:尾巴
trailEffectRate: 2


[projectile_2]
@copyFromSection: template_爆炸
life: 420
speed: 3.5
targetSpeed: 7
largeHitEffect: true

drawSize: 0.8
trailEffect: true
lightSize: 1.5
lightColor: #FF00B3FF
directDamage: 70

image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:波雷爆炸,CUSTOM:闪光
#摆动幅
wobbleFrequency: 100
#摆动频率

turnSpeed: 20
#应该是转弯速度
#调太小可能打不中
#你看NM呢눈_눈
#눈      눈

#     —
wobbleAmplitude: 3


[projectile_3]
@copyFromSection: template_能源
areaDamage: 2500
areaRadius: 80
life: 240
speed: 4.5

lightSize: 1.5
lightColor: #FF39FFFF
#spawnUnit:脉冲*1
drawSize: 0.8
targetSpeed: 4.5

image: ROOT:/余辉军团/单位特效/鱼雷.png
explodeEffect: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变
explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变
areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
targetGround_includeTargetHeight:true

[projectile_4]
@copyFromSection: template_能源
directDamage: 20
life: 70
image: ROOT:/余辉军团/单位特效/双枪.png
drawSize: 0.5

speed: 9
targetSpeed: 9
explodeEffect: CUSTOM:火花


[effect_波雷爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.8
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg

alpha: 2


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 25
fadeOut: true
scaleFrom: 0.2

scaleTo: 0.8
alpha: 2
drawUnderUnits: false
atmospheric: false
attachedToUnit: true


[effect_粒子]
life: 50
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 0.1
scaleTo: 1.5
alpha: 1

dirOffsetRandom: 180
attachedToUnit: true


[effect_火2]
life: 45
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 26
yOffsetRelative	: -82


[effect_火1]
life: 45
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: -26
yOffsetRelative	: -82


[effect_火3]
life: 55
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 10

scaleTo: 3
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -99


[effect_爆炸x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/余辉军团/单位特效/爆炸25.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_爆炸]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.7
image: ROOT:/余辉军团/单位特效/碎裂.png
total_frames: 8

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_爆炸1]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[effect_烟雾]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.25
scaleTo: 1.25
alpha: 0.65
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_底色]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩.png
life: 130
fadeOut: true
attachedToUnit: false

scaleFrom: 0.65
scaleTo: 0.65
alpha: 1.3
drawUnderUnits: false
atmospheric: true

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.65
scaleTo: 0.65
alpha: 0.4
drawUnderUnits: false
atmospheric: true


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 6
scaleTo: 6

drawUnderUnits: false
atmospheric: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1.3
scaleTo: 0.4
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.05
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[arm_1]
x: -36
y: 0.5
image_end: 左盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: -36
y: 24.5
image_end: 左盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 36
y: 0.5
image_end: 右盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 36
y: 24.5
image_end: 右盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_6]
x: -25
y: -34.5
image_end: 左盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_7]
x: 25
y: -34.5
image_end: 右盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_8]
x: 0
y: 56.5
image_end: 前盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_9]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:30, y:0}
arm1_950s: {x:30, y:0}
arm3_1s: {x:30, y:0}

arm3_950s: {x:30, y:0}
arm4_1s: {x:-30, y:0}
arm4_950s: {x:-30, y:0}
arm5_1s: {x:-30, y:0}
arm5_950s: {x:-30, y:0}

arm6_1s: {x:30, y:0}
arm6_950s: {x:30, y:0}
arm7_1s: {x:-30, y:0}
arm7_950s: {x:-30, y:0}
arm8_1s: {x:0, y:-25}

arm8_950s: {x:0, y:-25}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}
arm4_1s: {x:0, y:0}

arm5_1s: {x:0, y:0}
arm6_1s: {x:0, y:0}
arm7_1s: {x:0, y:0}
arm8_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 1.4
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 1.2
turnAcceleration: 0.05
targetHeightDrift: 0.3

slowDeathFall: true
targetHeight: 70


[ai]
buildPriority: 0.9


