


[core]
name: 幻想级巡洋舰
displayText: Крейсер класса «Фантазия»
price: 3000
maxHp: 6000
displayDescription: 【Уровень t3】【Механический юнит】【Надводный юнит】\n-Тактическое назначение: ПВО/противолодочный боевой корабль，вооружение：\n-▲пушка «Вулкан»X2 по земле и воздуху кинетический урон пробивает укрытия противвоздушный юнитурон-бонус\n-▲зенитная ракетаX2 только по воздуху взрывной урон \n-▲Противолодочный самолётX1 толькоможетатакаподводный юнит взрывной урон\n-по земле，по воздуху，противолодочный。пушка «Вулкан»кинетический уронипробивает укрытия，остальноевзрывной урон。противвоздушный юнитурон-бонус。\n-Крейсер класса «Фантазия»являетсяГенезисВМС небо捍卫者，\n-они统одинотдовоенный 落послевоенный корабльмодифицироватьаприходить，усиливает защитаПустосистемапосле，\n-тогдастановиться 令многоЗаревонизковысотныйюнит，望а生畏 存в。\n-幻想классспособениспользоватьсобственныймощныйзащитаПустоогневая мощь，быстрыйперехватывать或уничтожатьбольшинствоПустовцель，\n-его额вненесёт противолодочный истребитель，такжеможетнаходиться理深海в 威胁。
techLevel: 1
buildSpeed: 15s
radius: 66
displayRadius: 66
isBio: false
softCollisionOnAll: 7
fogOfWarSightRange: 23
unitsSpawnedOnDeath: 中型水上单位死亡*1
armour: 8
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 航母2,地面,海上
energyNeedsToRechargeToFull: true

maxTransportingUnits: 1
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 反潜机
transportUnitsHealBy: 0.5

transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
borrowResourcesWhileAlive: wrj2=-1
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[action_电磁炮2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道2.png
text: орбитальныйпусковая установка2
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器2')


[hiddenAction_1b]
autoTrigger: if self.resource(type='wrj2', greaterThan=0) and not self.transportingCount(greaterThan=0) and self.ammo(lessThan=0.5)
alsoQueueAction: drone
addResources: ammo= 1


[hiddenAction_drone]
price: 0
buildSpeed: 6s
isActive: true
onlyOneUnitAtATime: true
# isLocked: if not self.resource(type='wrj1', greaterThan=0) or self.transportingCount(greaterThan=7)

addResources: ammo= -1
alsoTriggerAction: SDD


[hiddenAction_SDD]
text: строитьдрон
requireConditional: if self.resource(type='wrj2', greaterThan=0)
addUnitsIntoTransport: 反潜机


[hiddenAction_bqk]
autoTrigger: if self.numberOfAttachedUnits(lessThan=1)
temporarilyAddTags: 航母2


[hiddenAction_bqm]
autoTrigger: if self.transportingCount(greaterThan=0)
temporarilyRemoveTags: 航母2
[attachment_1]
x: 0
y: -92
isUnselectable: true
canBeAttackedAndDamaged: false
addTransportedUnits: true

setDrawLayerOnBottom: false
canAttack: false
isVisible: true
idleDir: 180
lockRotation: true

height: 1

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[decal_水下]
image: 水下.png
total_frames: 1
layer: beforeBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.8
alpha:0.6

[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
imageScale:0.8
alpha:0.8
[decal_炮塔影子1]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
imageScale: 0.8
[decal_炮塔]
image: 枪管.png
total_frames: 2
frame: (self.customTimer * 20) % 2
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 1
isVisible:if self.isAttacking()
onlyWhileAlive:true
layer: onTop
imageScale:0.8
yOffsetRelative:20
xOffsetRelative:-0.5
[decal_炮塔影子]
image: SHADOW:${turret_3.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 3
alpha:0.65
imageScale: 0.8
[decal_炮塔1]
image: 枪管.png
total_frames: 2
frame: (self.customTimer * 20) % 2
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 3
isVisible:if self.isAttacking()
onlyWhileAlive:true
layer: onTop
imageScale:0.8
yOffsetRelative:20
xOffsetRelative:-0.5

[decal_炮塔影]
image: SHADOW:${turret_5.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 5
alpha:0.65
imageScale: 0.8
[decal_炮塔影1]
image: SHADOW:${turret_7.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 7
alpha:0.65
imageScale: 0.8
[decal_灯光12]
layer: afterBody
image: led.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
imageScale:0.8
[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: AUTO

shadowOffsetX: 3
shadowOffsetY: 3
splastEffect: true
showTransportBar: false
teamColorsOnTurret: true
imageScale: 0.8
turretImageScale: 0.8
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 12
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 75

maxAttackRange: 420
turretMultiTargeting: true
turretSize: 20
[turret_1]
x:0
y: 68
canShoot: false
canAttackCondition: if self.resource.xk<1
image:加特林.png
turnSpeed: 3
turnSpeedAcceleration: 0.6
limitingAngle: 90
aimOffsetSpread: -0.01
[turret_2]
x: 0
y: 1
attachedTo: 1
slave: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/机炮.ogg
shoot_sound_vol: 0.3
shoot_flame: large
shoot_light: #FFccCCEE
projectile: 1
delay:3
size:31
canAttackCondition: if self.resource.xk < 1
altProjectile: 3
altProjectileCondition: if self.globalTeamTags(includes='轨道发射器2')
[turret_3]
x: 0
y:25
image:加特林.png
copyFrom: 1
[turret_4]
x: 0
y:1
copyFrom: 2
attachedTo: 3
slave: true

[turret_5]
x: 17
y: 3
canShoot: false
canAttackCondition: if self.resource.xk<1
image:导弹.png
turnSpeed: 3
turnSpeedAcceleration: 0.6
limitingAngle: 70
canAttackLandUnits: false
idleDir:35
[turret_6]
invisible: true
x:0
y: 5
projectile: 2
size: 0
turnSpeed: 0
shoot_sound: ROOT:/通用特效/连射.wav
shoot_sound_vol: 0.4
attachedTo: 5
slave: true
delay: 100
shoot_flame: CUSTOM:烟雾*2
canAttackCondition: if self.resource.xk<1
canAttackLandUnits: false

[turret_7]
x: -17
y:3
image:导弹.png
copyFrom: 5
idleDir:-35
[turret_8]
x: 0
y:5
copyFrom: 6
attachedTo: 7
slave: true

[projectile_1]
@copyFromSection: template_动能
directDamage: 10
life: 240
armourIgnoreAmount: 10
speed: 19
deflectionPower: -1
image:ROOT:/创世纪军事集团/单位特效/大子弹.png
explodeEffect: CUSTOM:火花
drawSize: 0.54
turnSpeed: 0.5
mutator1_ifUnitWithTags: 飞机
mutator1_directDamageMultiplier: 4
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 350
areaRadius: 45
life: 250
speed: 2
targetSpeed: 13
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 0.75
trailEffect: true
lightSize: 0.75
trailEffectRate: 2.5
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光
[projectile_3]
@copyFromSection: template_动能
directDamage: 15
lightColor: #FFFF1200
lightSize: 1.2
life: 240
armourIgnoreAmount: 10
shieldDamageMultiplier: 1.2
speed: 19
deflectionPower: -1
image:大子弹.png
explodeEffect: CUSTOM:火花
drawSize: 0.54
turnSpeed: 0.5
mutator1_ifUnitWithTags: 飞机
mutator1_directDamageMultiplier: 4
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

#——————————子弹

[effect_火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.4
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.6
ySpeedRelative: 1
atmospheric: true
#——————————子弹
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.4
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2

[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
createWhenOverLand: false
life: 90
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.4
scaleTo: 5
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -15
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1


[effect_火]
life: 100
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1
scaleTo: 3.4
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1.5
yOffsetRelative	: 20
drawUnderUnits: true
[arm_1]
x: 0
y: -62
image_end: ROOT:/创世纪军事集团/单位特效/雷达.png
drawOverBody: true
spinRate: 4
[movement]
movementType: WATER
moveSpeed: 1.2
moveAccelerationSpeed: 0.04
moveDecelerationSpeed: 0.04
maxTurnSpeed: 1.7

turnAcceleration: 0.04


