


[core]
name: AG热射线炮塔t1
displayText: AGТурель тепловых лучейt1
class: CustomUnitMetadata
price: 1500
maxHp: 1100
maxShield: 1000

shieldRegen: 0.07
footprint: 0,0,1,1
effectOnDeath: CUSTOM:烟雾2*2,CUSTOM:爆炸*1
constructionFootprint: 0,0,1,1
copyFrom: ROOT:/通用特效/单位防护.ini

buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 13
tags: 地面,建筑,无人单位
techLevel: 1
buildSpeed: 0.0008
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
#availableInDemo: true
radius: 25
#displayRadius: 25
buildingSelectionOffset: -8
isBuilding: true
armour: 5
isBio: false


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_升级]
convertTo: AG热射线炮塔t2
displayType: action
text: AGТурель тепловых лучейt2
price: 1200
buildSpeed: 10s

isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t2')
isLockedMessage: Требуется боевой центр ядра ИИ 2-го уровня
ai_isHighPriority: true
description: 2-й уровеньТурель тепловых лучейможет собиратьещё более灼горячий высокий может лазер, \n-его тёплыйстепеньможет достичьна 万степень, достаточночтобы 熔абсолютныйбольшой частьматериал.


[graphics]
total_frames: 1
image: ROOT:/余辉军团/建筑特效/一级座.png
image_wreak: ROOT:/余辉军团/建筑特效/座死亡.png
image_turret: 热射线炮塔.png
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
imageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 26.5

turretTurnSpeed: 6
maxAttackRange: 290
aimOffsetSpread: -0.01


[turret_1]
x: 0
y: 20
projectile: 1
delay: 0.9
idleSweepAngle: 100

idleSweepDelay: 210
idleSweepSpeed: 0.2
canAttackCondition: if self.resource.xk < 1


[projectile_1]
@copyFromSection: template_能源
directDamage: 4
life: -4
instantReuseLast: true
beamImage: SHARED:beam3.png

beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true

color: #FF00B3FF
lightColor: #FF004AFF
lightSize: 0.1
explodeEffect: CUSTOM:闪光,CUSTOM:烟雾
explodeEffectOnShield: CUSTOM:闪光,CUSTOM:烟雾
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_烟雾]
priority: low
spawnChance: 1
stripIndex: effects
frameIndex: 0
life: 100

fadeOut: true
attachedToUnit: false
fadeInTime: 0.8
scaleTo: 1
scaleFrom: 0.5

alpha: 0.5
hSpeed: 1
drawUnderUnits: false
atmospheric: false
xSpeedAbsoluteRandom: 0.3


[effect_闪光]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.25

scaleTo: 0.25
image: ROOT:/余辉军团/单位特效/光束.png
dirOffsetRandom: 180


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[ai]
buildPriority: 0.3
ai_upgradePriority: 1
maxEachBase: 30
maxGlobal: 50
upgradedFrom: 空AG炮塔空投

