[core]
name: 净化者机甲
displayText: Мех «Очиститель»
price: 3700
maxHp: 7500
displayDescription: 【Уровень t4】【Механический юнит】【Наземный юнит】【Амфибия】【Защита от тактического оружия】Тактическое назначение: ПВО/反生物重 мех\n-размер юнита:7，вооружение：▲重 Зенитное орудиеX1 по земле и воздуху взрывной урон пробивает укрытия усиленный урон по биологическим юнитам \n-▲зенитная ракетазапускать仓X1 только по воздуху взрывной урон ▲тяжёлый пулемётX1 по земле и воздуху кинетический урон пробивает укрытия\n-▲Дрон «Очиститель»пусковой отсекX1 только по воздуху взрывной урон\n-Очиститель是一видфункциямощный，适用性广且灵活манёвр的防空оружие，\n-这видмех是Генезис陆军中самый为мощныйманёвренность地по воздуху平 。\n-Очистительоснащение了弹炮一体зенитное орудие а также自杀дрон阵列，\n-позволяетон对付大масштаб轻 目标或者单个重 目标都是好手。\n-самый令人惊喜的是，这вид平 независимо от在надводныйещё是陆上都можетнормальныйиспользовать。\n-相较于其он笨重又огромный的地по воздухуоружие，\n-Очистительсамый大的преимущество在于можнобыстрыйразвёртыватьи避免与部队脱节。\n-единственный的美中不足是Очиститель无法威胁до高度过高的враг。
techLevel: 1
buildSpeed: 16s
radius: 55
displayRadius: 55
energyMax: 10
energyRegen: 0.05

armour: 10
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/扎针1.md
transportSlotsNeeded: 7
unitsSpawnedOnDeath: 损毁3*1
tags:地面
fogOfWarSightRange: 28
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=700) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack
[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=700)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false
[decal_主体损坏a]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
#imageScale:0.9
isVisible: if self.hp < self.maxHp * 0.36
[decal_灯光]
layer: afterBody
image: 闪光.png
onlyWhileAlive: true
teamColors: true
#imageScale:0.9
isVisible:if self.maxHp * 0.36 < self.hp
#yOffsetRelative:-4
[decal_炮塔3]
image: 炮塔损坏.png
#layer:beforeUI
isVisible: if self.hp < self.maxHp * 0.36
onlyWhileAlive:true
basePositionFromTurret: 2
#——————————————————————————科技

[action_聚变弹头2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变2.png
text: Термоядерная боеголовка2
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头2')

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[decal_副炮影子]
image: 副炮影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 0
[decal_主炮影子]
image: 主炮影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 2
[decal_炮影子]
image: 炮影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
[graphics]
image: 主要.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 7
shadowOffsetY: 7
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits:true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14
turretTurnSpeed: 1
maxAttackRange: 650
shootDelay: 100
turretMultiTargeting: true
[turret_0]
x: 0
y: 43
canShoot: false
image: 副炮.png
#limitingAngle: 100
limitingRange: 245
turnSpeed: 3.5
turnSpeedAcceleration: 1


[turret_1]
x: -11
y: 13.5
#主炮
shoot_sound: ROOT:/创世纪军事集团/单位特效/坦克音效.ogg
shoot_sound_vol: 0.5
shoot_flame:large,CUSTOM:烟雾*5,CUSTOM:弹壳
shoot_light: #FFEECCCC
recoilOffset: -6
recoilOutTime: 5
recoilReturnTime: 10
delay: 60
image: 炮.png
attachedTo: 2
canShoot: true
slave: true
canAttackLandUnits:true
limitingRange: 470
size: 46
canAttackCondition: if self.resource.xk < 1
projectile: 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头2')
[turret_2]
x: 0
y: -36
#炮塔
turnSpeed: 2.8
turnSpeedAcceleration: 0.6
canShoot: false
idleSweepAngle: 20
idleSweepDelay: 260
idleSweepSpeed: 0.4
image: 主炮.png
limitingRange: 470
canAttackLandUnits:true
canAttackCondition: if self.resource.xk < 1
[turret_3]
x: 10.5
y: 17
#导弹右
projectile: 2
attachedTo: 2
slave: true
image: 导弹.png
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*3
shoot_light: #FFEECCCC
limitingRange: 470
canShoot: true
canAttackCondition: if self.resource.xk < 1
recoilOffset: -10
size:3
recoilOutTime: 4
recoilReturnTime: 60
delay:150
warmup:30
canAttackLandUnits:false
[turret_4]
x: 17.5
y: 17
#主炮
copyFrom: 3
delay:160
warmup:20
[turret_5]
x: 0
y: 0
canShoot: false
image: 主炮遮盖.png
attachedTo: 2
slave: true
[turret_6]
x: 17.5
y: 11
#主炮
copyFrom: 3
delay:170
warmup:10

[turret_7]
x: 10.5
y: 11
#主炮
copyFrom: 3
[turret_8]
x: 0
y: 0
canShoot: false
image: 主炮遮盖1.png
attachedTo: 2
slave: true
[turret_9]
x: 0
y: 0
attachedTo: 0
slave: true
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/机枪.ogg
shoot_sound_vol: 0.35
shoot_flame: small
shoot_light: #FFFFEB88
projectile: 3
delay: 3
canAttackCondition: if self.resource.xk < 1
limitingRange: 245
size:21
[turret_10]
x: 0
y: 8
invisible: true
shoot_sound: NONE
shoot_flame: NONE
projectile: 4
size: 0
turnSpeed: 811
turnSpeedAcceleration: 10
delay:1
energyUsage:10
canAttackLandUnits:false
canOnlyAttackUnitsWithoutTags:浮空雷
[turret_13]
x: 0
y: 8
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾at*7
shoot_light: #FFEECCCC
projectile: 6
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay: 30
interceptProjectiles_withTags: 战术武器
interceptProjectiles_andUnderDistance: 2000
interceptProjectiles_andOverHeight: -100
energyUsage: 10
invisible: true
onShoot_playAnimation: 发飞机

[turret_13x]
x: 0
y: 8
copyFrom: 13
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 2000
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2000
#战术防御天上



[projectile_6]
areaDamage: 0
areaRadius: 0
life: 666
speed: 15
targetSpeed: 15
trailEffect:true
image: 紫砂.png
drawSize: 0.9
largeHitEffect: true
deflectionPower: -1
trailEffectRate: 0.4
lightSize: 0
[projectile_1]
@copyFromSection: template_爆炸
#主炮子弹
areaDamage: 150
areaRadius: 75
life: 60
speed: 99
targetSpeed: 99
drawSize: 0
lightSize: 0
frame: 8
explodeEffect: CUSTOM:爆炸, CUSTOM:爆破*3,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:爆破*3,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
areaRadiusFromEdge: true
instant: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
mutator3_ifUnitWithTags:飞机
mutator3_areaDamageMultiplier: 4
mutator2_ifUnitWithTags:步兵
mutator2_areaDamageMultiplier: 10
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[projectile_2]
@copyFromSection: template_爆炸
#主炮子弹
directDamage: 550
life: 250
speed: 5
targetSpeed: 14
image: ROOT:/创世纪军事集团/单位特效/小导弹.png
drawSize: 0.8
trailEffect: true
deflectionPower: -1
lightSize: 0.75
lightColor: #FFFFFF73
autoTargetingOnDeadTarget: true
explodeEffect: CUSTOM:钢珠1,CUSTOM:爆炸1, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:钢珠1,CUSTOM:爆炸1,CUSTOM:闪光
[projectile_3]
@copyFromSection: template_动能
directDamage: 30
life: 80
speed: 14
deflectionPower: -1
trailEffect: false
frame: 5
explodeEffect: CUSTOM:火花
mutator1_ifUnitWithTags: 飞机
mutator1_directDamageMultiplier: 3
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[projectile_4]
directDamage: 0
life: 2
speed: 0.01
drawSize: 0
explodeOnEndOfLife: true
spawnUnit: 净化者无人机(offsetHeight=4)
deflectionPower: -1
explodeEffect: NONE
[projectile_炮弹]
@copyFromSection: template_能源
#主炮子弹
areaDamage: 180
areaRadius: 80
life: 60
speed: 99
targetSpeed: 99
drawSize: 0
lightSize: 0
frame: 8
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:冲击波
areaRadiusFromEdge: true
instant: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
mutator3_ifUnitWithTags:飞机
mutator3_areaDamageMultiplier: 4
mutator2_ifUnitWithTags:步兵
mutator2_areaDamageMultiplier: 10
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[arm_1]
x: 0
y: 0
image_end: 底.png
image_end_teamColors: true
#drawOverBody: true

[arm_2]
x: 0
y: 8
image_end: 紫砂.png
image_end_teamColors: true
hidden:if self.energy<7
[arm_3]
x: 0
y: -4
image_end: 下门.png
image_end_teamColors: true
[arm_4]
x: 0
y: 17
image_end: 上门.png
image_end_teamColors: true
#drawOverBody: true
[animation_attack]
blendIn: 1s
blendOut: 2s
arm3_1s: {x:0, y:-20}
arm3_950s: {x:0, y:-20}
arm4_1s: {x:0, y:20}
arm4_950s: {x:0, y:20}
[animation_attack1]
blendIn: 1s
blendOut: 2s
arm3_1s: {x:0, y:0}
arm4_1s: {x:0, y:0}
[animation_发飞机]
arm3_0.3s: {x:0, y:-20}
arm4_0.3s: {x:0, y:20}
[effect_烟雾at]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1.5
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_爆炸]
life: 120
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2.1
image: ROOT:/创世纪军事集团/单位特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
alpha: 1.2
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:30
yOffsetRelativeRandom:30
delayedStartTimerRandom:10
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.5
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_弹壳]
image: 弹壳.png
spawnChance: 1
life: 130
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: 0.1
ySpeedRelative: -0.6
xSpeedRelativeRandom: -0.05
ySpeedRelativeRandom: -0.2
yOffsetRelative: -90
xOffsetRelative: 0
hSpeed: 2
dirSpeedRandom: 10

[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.6
ySpeedRelative: 1
atmospheric: true

[effect_爆炸1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.3
scaleTo: 1.7
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alpha: 1.2
[effect_钢珠1]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.3
scaleTo: 1.8
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 1.3
scaleTo: 1.9
image: ROOT:/创世纪军事集团/单位特效/火花.png
alpha: 1.2
total_frames: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFramePingPong: false
animateFrameSpeed: 0.3
#——————————————————科技主炮
[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.4
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1.1
alpha: 0.8
drawUnderUnits: false
atmospheric: false

[leg_1]
x: -40
y: 63
attach_x: -15
attach_y: 8
moveSpeed: 1.7
rotateSpeed: 9
heightSpeed: 0.55
resetAngle: 25
image_leg: 腿.png
image_foot: 脚.png
image_foot_shadow: SHADOW:脚.png
hardLimit: 30
holdDisMin: 8
holdDisMax: 15
drawDirOffset: -10
[leg_2]
x: 40
y: 63
attach_x: 15
attach_y: 8
copyFrom: 1
drawDirOffset: 10
[leg_3]
x: -55
y: -30
attach_x: -20
attach_y: -5
copyFrom: 1
drawDirOffset: 0
[leg_4]
x: 55
y: -30
attach_x: 20
attach_y: 5
copyFrom: 1
drawDirOffset: 0


[movement]
movementType: OVER_CLIFF_WATER
moveSpeed: 0.85
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 1

turnAcceleration: 0.09
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4
slowDeathFall: true


