


[core]
name: 海蜂武装直升机
displayText: Боевой вертолёт «Морская оса»
class: CustomUnitMetadata
displayDescription: -阿巴阿巴阿巴阿巴阿巴阿巴
price: 0
maxHp: 4300
techLevel: 1
buildSpeed: 0s
fogOfWarSightRange: 28
armour: 8
radius: 29
displayRadius: 29
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 10
energyMax: 60
showInEditor: false
energyRegen: 0
energyNeedsToRechargeToFull: true
tags: 飞机,低空,直升机hf,寄生免疫,伴生单位
effectOnDeath:CUSTOM:碎片,CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
effectOnDeathGroundCollision:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
canNotBeGivenOrdersByPlayer: true
energyStartingPercentage: 1
logIfCreditResourceUsed: true
[action_聚变弹头2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变2.png
text: Термоядерная боеголовка2
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头2')

[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'


[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'


[hiddenAction_return1]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( self.isEnergyRecharging or distanceBetweenSquared(self, customTarget1) > 1400 * 1400 )
# distanceBetweenSquared 返回两个单位之间的平方距离。 比 distanceBetween 快一点，因为少了开方这一步。1100² 判断灰机离母体有多远，超过1100回家
clearActiveWaypoint: true
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own

addWaypoint_type: loadInto


[hiddenAction_disconnect]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( not self.hasActiveWaypoint(type= 'attack') or activeWaypointTarget.height < 0)
disconnectFromParent: true
clearActiveWaypoint: true
addWaypoint_type: attack
addWaypoint_prepend: true

addWaypoint_target_fromReference: customTarget1.attacking
addWaypoint_triggerActionIfMatched: 补丁
addWaypoint_triggerActionIfFailed: return1


[hiddenAction_补丁]
requireConditional: if not self.hasParent and not self.hasActiveWaypoint(type= 'attackMove')
addWaypoint_type: attackMove
addWaypoint_target_fromReference: thisActionTarget




[hiddenAction_energy]
autoTriggerOnEvent: enteredTransport
addEnergy: 60





[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
# 这条在鹰爪和雪崩里忘改成这样了，原本是打算航母凉后灰机用完能量才自杀，不过有bug忘了改回来
addResources: hp= -999999

[action_akm]
autoTrigger: if self.hasParent and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack
temporarilyAddTags:锤子
[action_bkm]
autoTrigger: if not self.hasParent and self.hasFlag(id=1)
stopLastAnimation: true
isVisible: false
addResources: unsetFlag=1
playAnimation: attack1
alsoQueueAction: bx
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[action_bx]
price: 0
buildSpeed: 1s
temporarilyRemoveTags:锤子
isVisible: false
[graphics]
total_frames: 1
image: 机体1.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 0.75
image_shadow: NONE

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 300
isFixedFiring: true


[turret_0]
x: 0
y: 0
invisible: true
canShoot: false

[turret_1]
x: 11.5
y: 15
invisible: true
shoot_sound: ROOT:/创世纪军事集团/建筑特效/机枪塔音效.ogg
shoot_sound_vol: 0.1
shoot_light: #FFFFEB88
shoot_flame: CUSTOM:枪口火焰
projectile: 1
attachedTo: 0
slave: true
delay: 6
#limitingRange:300
[turret_2]
x: -11.5
y:15
copyFrom: 1
[turret_3]
invisible: true
attachedTo: 0
slave: true
x: 15
y: -6
projectile: 2
shoot_sound: missile_fire
shoot_sound_vol: 0.3
shoot_light: #FFFFEB88
shoot_flame: CUSTOM:烟雾*3
canAttackCondition: if self.flying and not self.globalTeamTags(includes='聚变弹头2')
delay:15
energyUsage:0.5
#limitingRange:300
[turret_4]
x:-15
y:-6
copyFrom: 3
delay:23
warmup:7
[turret_5]
invisible: true
attachedTo: 0
slave: true
x: 15
y: -6
projectile: 炮弹
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 0.6
shoot_light: #FFFFEB88
shoot_flame:NONE
canAttackCondition: if self.flying and self.globalTeamTags(includes='聚变弹头2')
delay:120
energyUsage:2.5
[turret_6]
x:15
y:-6
copyFrom: 5
delay:90
warmup:30
[projectile_炮弹]
@copyFromSection: template_能源
life: 36
speed: 0
targetSpeed: 0
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
areaDamage: 1200
areaRadius: 45
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:炮弹1
drawUnderUnits:true
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波d
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波d
buildingDamageMultiplier: 1.2
[projectile_炮弹1]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
areaDamage: 1200
areaRadius: 45
deflectionPower: -1
areaRadiusFromEdge: true
trailEffectRate: 0.8
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波d
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波d
buildingDamageMultiplier: 1.2
[projectile_1]
@copyFromSection: template_动能
directDamage: 16
life: 60
speed: 4
targetSpeed: 7.5
deflectionPower: -1
drawSize: 0.75
color: #FFFFFF73
frame: 8
explodeEffect: CUSTOM:火花
mutator32_ifUnitWithTags: 轻型掩护
mutator32_directDamageMultiplier: 1
mutator32_areaDamageMultiplier: 1
mutator33_ifUnitWithTags: 重型掩护
mutator33_directDamageMultiplier: 1
mutator33_areaDamageMultiplier: 1
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 200
areaRadius: 30
life: 250
speed: 5
frame: 4
drawSize: 0.8
trailEffect: true
lightSize: 0.75
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光
areaRadiusFromEdge: true
initialUnguidedSpeedHeight: 3
trueGravity: 0.1
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.4
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2
yOffsetRelative: 0.6
ySpeedRelative: 0.7
atmospheric: true
[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
scaleFrom: 2
scaleTo: 2
animateFrameStart: 0
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.6
image: ROOT:/通用特效/火花.png
alpha: 1.2
total_frames: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 0.6
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.2
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alpha: 1.2
[effect_碎片]
priority: critical
image: 尸块.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: 2
ySpeedRelative: 1
yOffsetRelative: -12
xOffsetRelative: 4
xSpeedRelativeRandom: 0.8
ySpeedRelativeRandom: 0.5
hSpeed: 2
dirSpeed:1.5
dirSpeedRandom:1
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/巨大爆炸.ogg
createWhenOffscreen: true
#——————————聚变

[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.4
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1.1
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_实验jb]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:10
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.5
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[effect_冲击波d]
life: 100
priority:veryhigh
attachedToUnit: true
scaleFrom: 0.4
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.22
alwayStartDirAtZero: true
alpha: 0.8
[arm_1]
x: 0
y: -41
image_end: 尾翼1.png
drawOverBody: true
image_end_shadow: SHADOW:尾翼1.png
[arm_2]
x: 0
y: 0
image_end: 机体1.png
drawOverBody: true
image_end_shadow: SHADOW:机体1.png
image_end_teamColors: true
[arm_3]
x: -12
y: -4
image_end: 左轮1.png
drawOverBody: true
image_end_shadow: SHADOW:左轮1.png
image_end_teamColors: true
[arm_4]
x: 12
y: -4
image_end: 右轮1.png
drawOverBody: true
image_end_shadow: SHADOW:右轮1.png
image_end_teamColors: true
[arm_5]
x: -12
y: -4
image_end: 左扇叶.png
drawOverBody: true
image_end_shadow: SHADOW:左扇叶.png
hidden:if not self.tags(includes= '锤子')
[arm_6]
x: 12
y: -4
image_end: 右扇叶.png
drawOverBody: true
image_end_shadow: SHADOW:右扇叶.png
hidden:if not self.tags(includes= '锤子')
[arm_7]
x: 20
y: -3
image_end: 风扇.png
drawOverBody: true
spinRate: 25
hidden:if self.tags(includes= '锤子')
[arm_8]
x: -20
y: -3
image_end: 风扇.png
drawOverBody: true
spinRate: -25
hidden:if self.tags(includes= '锤子')
[arm_9]
x: 0
y: -3
image_end:中1.png
drawOverBody: true
[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_0s: {x:0, y:0,dir:0}
arm1_1s: {x:0, y:21,dir:0}
arm1_9990s: {x:0, y:21,dir:0}
arm3_0s: {x:0, y:0,dir:0}
arm3_1s: {x:-2, y:0,dir:-90}
arm3_9990s: {x:-2, y:0,dir:-90}
arm4_0s: {x:0, y:0,dir:0}
arm4_1s: {x:2, y:0,dir:90}
arm4_9990s: {x:2, y:0,dir:90}
arm5_0s: {x:0, y:0,dir:0}
arm5_1s: {x:-2, y:0,dir:-90}
arm5_9990s: {x:-2, y:0,dir:-90}
arm6_0s: {x:0, y:0,dir:0}
arm6_1s: {x:2, y:0,dir:90}
arm6_9990s: {x:2, y:0,dir:90}
[animation_attack1]
arm1_0s: {x:0, y:21,dir:0}
arm1_1s: {x:0, y:0,dir:0}
arm3_0s: {x:-2, y:0,dir:-90}
arm3_1s: {x:0, y:0,dir:0}
arm4_0s: {x:2, y:0,dir:90}
arm4_1s: {x:0, y:0,dir:0}
arm5_0s: {x:-2, y:0,dir:-90}
arm5_1s: {x:0, y:0,dir:0}
arm6_0s: {x:2, y:0,dir:90}
arm6_1s: {x:0, y:0,dir:0}
[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02
maxTurnSpeed: 2.5
startingHeightOffset: 1000
turnAcceleration: 1
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: false
targetHeight: 70


