


[core]
name: 护板层1
strictLevel: 1
price: 0
radius: 0
maxHp: 1

class: CustomUnitMetadata
showInEditor: false
canNotBeDirectlyAttacked: true
disableDeathOnZeroHp: true
isUnrepairableUnit: true

isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
[hiddenAction_开始]
autoTrigger:if parent.tags(includes= '突进') and not self.tags(includes= '阻挡')
temporarilyAddTags:阻挡
stopLastAnimation: true
alsoQueueAction: b

[action_b]
convertTo: 护板层
displayType: action
price: 0
buildSpeed: 4s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
temporarilyRemoveTags:阻挡

[graphics]
image:NO.png
#isVisible: false
showQueueBar:false
showTransportBar:false
#imageScale: 0.9


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 0
[arm_1]
x: 0
y: 25
image_end: 护板1.png
image_end_teamColors: true
drawOverBody: true
[arm_2]
x: 0
y: 25
image_end: 护板1.png
image_end_teamColors: true
drawOverBody: true
[arm_3]
x: 0
y: 25
image_end: 护板1.png
image_end_teamColors: true
drawOverBody: true
[arm_4]
x: 0
y: 25
image_end: 护板1.png
image_end_teamColors: true
drawOverBody: true
[arm_5]
x: 0
y: 26
image_end: 护板.png
image_end_teamColors: true
drawOverBody: true
[arm_6]
x: 0
y: 35
image_end: 护板2.png
image_end_teamColors: true
drawOverBody: true
[arm_7]
x: 0
y: 35
image_end: 护板2.png
image_end_teamColors: true
drawOverBody: true
[arm_8]
x: 0
y: 35
image_end: 护板2.png
image_end_teamColors: true
drawOverBody: true
[arm_9]
x: 0
y: 35
image_end: 护板2.png
image_end_teamColors: true
drawOverBody: true
[arm_10]
x: 0
y: 31
image_end: 特殊护板.png
image_end_teamColors: true
drawOverBody: true
[arm_11]
x: 0
y: -30
image_end: 护板3.png
image_end_teamColors: true
#drawOverBody: true
[arm_12]
x: 0
y: -30
image_end: 护板3.png
image_end_teamColors: true
#drawOverBody: true

[arm_13]
x: 0
y: -30
image_end: 护板3.png
image_end_teamColors: true
#drawOverBody: true
[arm_14]
x: 0
y: -30
image_end: 护板3.png
image_end_teamColors: true
#drawOverBody: true

[animation_部署]
#————————————左右护板
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm1_1s: {x:0, y:13, dir:0}
arm2_1s: {x:0, y:13, dir:0}
arm3_1s: {x:0, y:13, dir:0}
arm4_1s: {x:0, y:13, dir:0}

arm1_2s: {x:0, y:23, dir:0}
arm2_2s: {x:0, y:23, dir:0}
arm3_2s: {x:0, y:23, dir:0}
arm4_2s: {x:0, y:13, dir:0}

arm1_3s: {x:0, y:23, dir:0}
arm2_3s: {x:0, y:33, dir:0}
arm3_3s: {x:0, y:23, dir:0}
arm4_3s: {x:0, y:13, dir:0}

arm1_4s: {x:0, y:43, dir:0}
arm2_4s: {x:0, y:33, dir:0}
arm3_4s: {x:0, y:23, dir:0}
arm4_4s: {x:0, y:13, dir:0}

arm1_5s: {x:0, y:43, dir:0}
arm2_5s: {x:0, y:33, dir:0}
arm3_5s: {x:0, y:23, dir:0}
arm4_5s: {x:0, y:13, dir:0}
#————————————中央护板
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}

arm6_1s: {x:0, y:14, dir:0}
arm7_1s: {x:0, y:14, dir:0}
arm8_1s: {x:0, y:14, dir:0}
arm9_1s: {x:0, y:14, dir:0}

arm6_2s: {x:0, y:28, dir:0}
arm7_2s: {x:0, y:28, dir:0}
arm8_2s: {x:0, y:28, dir:0}
arm9_2s: {x:0, y:14, dir:0}

arm6_3s: {x:0, y:42, dir:0}
arm7_3s: {x:0, y:42, dir:0}
arm8_3s: {x:0, y:28, dir:0}
arm9_3s: {x:0, y:14, dir:0}

arm6_4s: {x:0, y:56, dir:0}
arm7_4s: {x:0, y:42, dir:0}
arm8_4s: {x:0, y:28, dir:0}
arm9_4s: {x:0, y:14, dir:0}

arm6_5s: {x:0, y:56, dir:0}
arm7_5s: {x:0, y:42, dir:0}
arm8_5s: {x:0, y:28, dir:0}
arm9_5s: {x:0, y:14, dir:0}
#————————————后侧护板
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}

arm11_1s: {x:0, y:-26, dir:0}
arm12_1s: {x:0, y:-26, dir:0}
arm13_1s: {x:0, y:-26, dir:0}
arm14_1s: {x:0, y:-26, dir:0}

arm11_2s: {x:0, y:-36, dir:0}
arm12_2s: {x:0, y:-36, dir:0}
arm13_2s: {x:0, y:-36, dir:0}
arm14_2s: {x:0, y:-26, dir:0}

arm11_3s: {x:0, y:-46, dir:0}
arm12_3s: {x:0, y:-46, dir:0}
arm13_3s: {x:0, y:-36, dir:0}
arm14_3s: {x:0, y:-26, dir:0}

arm11_4s: {x:0, y:-56, dir:0}
arm12_4s: {x:0, y:-46, dir:0}
arm13_4s: {x:0, y:-36, dir:0}
arm14_4s: {x:0, y:-26, dir:0}

arm11_5s: {x:0, y:-56, dir:0}
arm12_5s: {x:0, y:-46, dir:0}
arm13_5s: {x:0, y:-36, dir:0}
arm14_5s: {x:0, y:-26, dir:0}


[movement]
movementType: AIR
maxTurnSpeed: 999
