


[core]
name: 核心
displayText: Ядро
strictLevel: 1
price: 0
radius: 0
maxHp: 1

class: CustomUnitMetadata
showInEditor: false
canNotBeDirectlyAttacked: true
disableDeathOnZeroHp: true
isUnrepairableUnit: true

isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
[hiddenAction_开始1]
autoTrigger:if parent.tags(includes= '齿轮') and not self.tags(includes= '阻挡')
temporarilyAddTags:阻挡
stopLastAnimation: true
playAnimation: 艹
[hiddenAction_开始2]
autoTrigger:if parent.tags(includes= '齿轮') and parent.tags(includes= '黑寡妇主炮')  and not self.tags(includes= '执行一次')
temporarilyAddTags:执行一次
stopLastAnimation: true
alsoQueueAction: bx

[action_bx]
displayType: action
price: 0
buildSpeed: 10s
isVisible: false
temporarilyRemoveTags:阻挡,执行一次
[decal_灯光]
image: 灯光1.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[graphics]
image:NO.png
#isVisible: false
showQueueBar:false
showTransportBar:false
#imageScale: 0.4


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 0

[arm_1]
x: 0
y: 11
image_end:垫子.png
image_end_teamColors: true
#drawOverBody: true
[arm_2]
x: 0
y: 11
image_end:外环.png
image_end_teamColors: true
#drawOverBody: true
spinRate: -2
[arm_3]
x: 0
y: 11
image_end:木亥.png
image_end_teamColors: true
#drawOverBody: true
spinRate: 4
[arm_4]
x: 0
y: 11
image_end:小盖子.png
image_end_teamColors: true
#drawOverBody: true
[arm_5]
x: 0
y: 0
image_end:总部.png
image_end_teamColors: true
[arm_6]
x: 0
y: -34
image_end: 雷达.png
drawOverBody: true
spinRate: 4
[animation_艹]
arm4_0s: {x:0, y:0, dir:0}
arm4_2s: {x:0, y:-25, dir:0}
arm4_99999s: {x:0, y:-25, dir:0}


[movement]
movementType: AIR
maxTurnSpeed: 999
