


[core]
name: 践踏x
displayText: Топот x
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: 눈_눈,隐藏
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
[action_触发]
buildSpeed: 0s
price:0
canPlayerCancel: false
isVisible: false
temporarilyAddTags: 布雷
playAnimation: 麻烦
alsoQueueAction: 生
autoTrigger:if self.resource.生儿子>0.5
addResources:生儿子=-1

[action_生]
displayType: action
price: 0
buildSpeed: 5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove:true
allowMultipleInQueue:false
spawnUnits:寡妇1(spawnSource= self.getOffsetRelative(x= 0, y= 150,dirOffset=180))
temporarilyRemoveTags: 布雷
[hiddenAction_开始]
autoTrigger:if parent.tags(includes= '突进') and not self.tags(includes= '阻挡')
temporarilyAddTags:阻挡
stopLastAnimation: true
alsoQueueAction: b
playAnimation: 似了

[action_b]
displayType: action
price: 0
buildSpeed: 4s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags:隐藏
temporarilyAddTags:离谱
[hiddenAction_开始1]
autoTrigger:if parent.tags(includes= '不突进') and self.tags(includes= '阻挡')
temporarilyRemoveTags:阻挡,离谱
playAnimation: 似了1
stopLastAnimation: true

alsoQueueAction: b1
[action_b1]
displayType: action
price: 0
buildSpeed: 3s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyAddTags:隐藏
stopLastAnimation: true

[graphics]
total_frames: 8
image: NO.png
showQueueBar: false
showTransportBar: false
# lock_body_rotation_with_main_turret: true

# lock_leg_rotation_with_main_turret: true
animation_attack_start: 0
animation_attack_end: 7
animation_attack_speed: 3.5
animation_idle_start: 0

animation_idle_end: 7
animation_idle_speed: 3.5
showEnergyBar: false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 99999

# 这个炮塔最好主体的最大范围多200
#disablePassiveTargeting: true
isFixedFiring: false
turretSize: 24
turretTurnSpeed: 200

shootDelay: 0.9
aimOffsetSpread: 0


[turret_1]
x: 0
y: 0
delay: 1
projectile: 1
turnSpeedAcceleration: 5000
size: 6
invisible: true

[projectile_1]
areaDamage: 300
areaRadius: 220
armourIgnoreAmount: 100
speed: 0.1
life: 1
image: NO.png
instant: false
largeHitEffect: false
explodeOnEndOfLife: true
deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

#————————
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.9
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative:0
atmospheric: true
[arm_1]
x: 0
y: -40
image_end: 龙门架.png
drawOverBody: true
image_end_teamColors:true
image_end_shadow: SHADOW:龙门架.png
drawDirOffset: 180
[arm_2]
x: 0
y: -40
image_end: 龙门架1.png
drawOverBody: true
image_end_teamColors:true
image_end_shadow: SHADOW:龙门架1.png
drawDirOffset: 180
hidden:if not self.tags(includes= '布雷')

[arm_3]
x: 0
y: 0
image_end: 压路机.png
drawOverBody: false
image_end_teamColors:true
image_end_shadow: SHADOW:压路机.png

[arm_4]
x: 0
y: 155
image_end: 压路机.png
drawOverBody: false
image_end_teamColors:true
image_end_shadow: SHADOW:压路机.png
hidden:if self.tags(includes= '隐藏')
[decal_炮塔]
image: 压路机动画.png
total_frames: 6
frame: (self.customTimer * 34) % 6
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '离谱')
onlyWhileAlive:true
layer: afterBody
yOffsetRelative:155
xOffsetRelative:0
[animation_麻烦]
arm1_0s: {x:0, y:0}
arm1_5s: {x:0, y:-100}
arm2_0s: {x:0, y:0}
arm2_5s: {x:0, y:-100}
[animation_似了]
arm3_0s: {x:0, y:0}
arm3_2s: {x:0, y:155}
arm3_99999s: {x:0, y:155}
[animation_似了1]
arm4_0s: {x:0, y:0}
arm4_3s: {x:0, y:-155}



[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 180
targetHeight: 4
targetHeightDrift: 0

turnAcceleration: 233
moveIgnoringBody: true


