


[core]
name: 黑寡妇之耀附属物1
displayText: «Сияние Чёрной Вдовы» вспомогательное1
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
energyMax: 4

energyRegen: 0.033
energyNeedsToRechargeToFull: true
tags:反高空
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 2000 | setFlag= 1)
# 对地对空
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false


[decal_左导弹井]
image: 左.png
total_frames: 1
layer: beforeBody
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
yOffsetRelative:-64.5
xOffsetRelative:-49.5
onlyWhileAlive:true

[decal_右导弹井]
image: 右.png
total_frames: 1
layer: beforeBody
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
yOffsetRelative:-64.5
xOffsetRelative:49.5
onlyWhileAlive:true

[decal_左开启]
image: 左导弹开启.png
total_frames: 6
frame: select(self.tags(includes= '切枪'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer: beforeBody
yOffsetRelative:-64.5
xOffsetRelative:-49.5
[decal_右开启]
image: 右导弹开启.png
total_frames: 6
frame: select(self.tags(includes= '切枪'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer: beforeBody
yOffsetRelative:-64.5
xOffsetRelative:49.5

[decal_左关闭]
image: 左导弹关闭.png
total_frames: 6
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: beforeBody
yOffsetRelative:-64.5
xOffsetRelative:-49.5
[decal_右关闭]
image: 右导弹关闭.png
total_frames: 6
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: beforeBody
yOffsetRelative:-64.5
xOffsetRelative:49.5

[hiddenAction_akm]
autoTrigger: if not self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") == null
addResources: setFlag=1
alsoQueueAction:zx
temporarilyAddTags: 切枪
temporarilyRemoveTags:关闭
resetCustomTimer: true
[hiddenAction_bkm]
autoTrigger: if self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") != null
stopLastAnimation: true
addResources: unsetFlag=1
alsoQueueAction:zxx
temporarilyAddTags: 切枪x,关闭
resetCustomTimer: true
[action_zx]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪
[action_zxx]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪x
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
#turretImageScale: 0.9

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 1800
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0
turretMultiTargeting: true
[turret_1]
x: -57
y: -79
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/通用特效/新导弹发射.wav
shoot_sound_vol: 1.2
shoot_flame: CUSTOM:烟雾*6,CUSTOM:冲击波
shoot_light: #FFEECCCC
projectile: 3
size: 0
turnSpeed: 811
delay: 700
canOnlyAttackUnitsWithTags:高空
limitingMinRange: 450
canAttackCondition: if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
#动能
[turret_2]
x: -45
y: -73
invisible: true
canAttackFlyingUnits:true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/通用特效/新导弹发射.wav
shoot_sound_vol: 1.2
shoot_flame: CUSTOM:烟雾*6,CUSTOM:冲击波
shoot_light: #FFEECCCC
projectile: 1
size: 0
turnSpeed: 811
delay: 650
warmup:50
canOnlyAttackUnitsWithTags:高空
limitingMinRange: 450
canAttackCondition: if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
#高爆

[turret_3]
x: -57
y: -67
copyFrom: 1
delay: 600
warmup:100
#动能
[turret_4]
x: -45
y: -61
copyFrom: 2
delay: 550
warmup:150
#高爆
[turret_5]
x: -57
y: -55
copyFrom: 1
delay: 500
warmup:200
#动能

[turret_6]
x: 57
y: -79
copyFrom: 2
delay: 450
warmup:250
#爆炸
[turret_7]
x: 45
y: -73
copyFrom: 1
delay: 400
warmup:300
#动能
[turret_8]
x: 57
y: -67
copyFrom: 2
delay: 350
warmup:350
#爆炸
[turret_9]
x: 45
y: -61
copyFrom: 1
delay: 300
warmup:400
#动能
[turret_10]
x: 57
y: -55
copyFrom: 2
delay: 250
warmup:450
#爆炸
[projectile_1]
life: 45
speed: 3
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: he.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
spawnProjectilesOnEndOfLife: 2
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:冲击波zz,CUSTOM:红闪光
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 5000
areaRadius: 80
life: 200
speed: 7
image: he1.png
targetSpeed: 12
drawSize:0.9
explodeEffect: CUSTOM:冲击波1,CUSTOM:爆炸1, CUSTOM:爆炸,CUSTOM:闪光
explodeEffectOnShield: CUSTOM:冲击波1,CUSTOM:爆炸1, CUSTOM:爆炸,CUSTOM:闪光
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
trailEffectRate: 0.8
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
shieldDamageMultiplier: 0.3
[projectile_3]
life: 45
speed: 3
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: k.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
spawnProjectilesOnEndOfLife: 4
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:冲击波zz,CUSTOM:红闪光
[projectile_4]
@copyFromSection: template_动能
areaDamage: 0
areaRadius: 0
life: 40
speed: 7
image: k1.png
targetSpeed: 12
drawSize:0.9
explodeEffect: CUSTOM:音效
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
trailEffectRate: 0.8
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
spawnProjectilesOnEndOfLife: 5
explodeOnEndOfLife: true
[projectile_5]
@copyFromSection: template_动能
directDamage: 2000
life: 200
speed: 12
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
drawSize: 0.7
explodeEffect: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*7,CUSTOM:冲击波gd,CUSTOM:穿透
explodeEffectOnShield: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*7,CUSTOM:冲击波gd,CUSTOM:穿透
lightSize: 1
trailEffectRate: 0.28
trailEffect: CUSTOM:尾巴gd
lightColor: #FFFF1200
armourIgnoreAmount: 999
shieldDamageMultiplier: 4
#——————————导弹发射
[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1
[effect_冲击波zz]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1
attachedToUnit: false
[effect_导弹碎片]
#priority: high
image: 导弹壳.png
spawnChance: 1
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 25
[effect_红闪光]
image: SHARED:light_50.png
life:40
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FFFF5B18
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
#——————————————————炸
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.37
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/重型爆炸.wav
alwayStartDirAtZero: true
[effect_爆炸1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/12.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.21
alwayStartDirAtZero: true
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 1.6
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
#——————————————轨道炮
#——————————————————————科技
[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.87
scaleTo: 0.87
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_冲击波gd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 1.35
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_爆炸1gd]
image: ROOT:/创世纪军事集团/单位特效/轨道炮炸裂.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 3
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.55
alwayStartDirAtZero: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:30
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.2
scaleTo:1.5
alpha: 0.8
fadeInTime: 4
drawUnderUnits:false
[effect_碎星gd]
spawnChance: 1
createWhenZoomedOut: false
life: 35
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom:0.175
scaleTo:0.175
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 5
ySpeedRelativeRandom: 5
[effect_穿透]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
life: 35
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.1
alpha: 1
drawUnderUnits: false
ySpeedRelative: 8
atmospheric: true
[effect_闪光gd]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 8
scaleTo: 1
drawUnderUnits: true
atmospheric: false
#——++......
[effect_尾巴gd]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 15
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.4
scaleTo: 0.5
alpha: 0.7
drawUnderUnits: false
[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


