


[core]
name: 轻坦克
copyFrom: ROOT:/通用特效/单位防护.ini
price: 650
maxHp: 1400
displayDescription: 【阶级t2】【机械单位】【地面单位】【轻型掩体】战术定位:泛用型坦克，\n-单位体积:2，武器配置：▲45毫米炮X1 只能对地 动能伤害\n-不要轻视这种用步兵战车改造的轻坦克，\n-他们虽然只配备45毫米炮威力略显不足，\n-但他们依然能像拍苍蝇一样摧毁轻型装甲车辆，\n-同时其绝佳的越野能力也能让人眼前一亮。
techLevel: 1
buildSpeed: 7.5s
radius: 19
transportSlotsNeeded:2
displayRadius: 19
isBio: false
softCollisionOnAll: 6
unitsSpawnedOnDeath: 损毁*1
armour: 5

tags: 地面,轻型掩体,驻扎要塞
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
[action_轻型掩体]
text: 轻型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/轻型掩体.png
description: 一处轻型掩体，能为附近140范围内的生物单位提供轻型掩护。\n-轻型掩护能为生物单位减免50%的伤害，\n-但是，掩体无法减免部分速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。
[action_聚变弹头1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变1.png
text: 聚变弹头1
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头1')


[action_恐怖地雷2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖2.png
text: 恐怖地雷2
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷2') and not self.globalTeamTags(includes='恐怖地雷3')
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')


[decal_损坏]
layer: afterBody
image: 损耗.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36
alpha:0.7
[decal_炮塔影子1]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:1
xOffsetRelative:1
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
[decal_损耗1]
image: 炮塔损耗.png
total_frames: 1
isVisible:if self.hp<self.maxHp * 0.36
layer: onTop
teamColors: true
onlyWhileAlive:true

basePositionFromTurret: 1
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[hiddenAction_掩体1取消]
autoTrigger:if self.hasParent and self.tags(includes= '轻型掩体')
isVisible:false
temporarilyRemoveTags:轻型掩体
[hiddenAction_掩体1生成]
autoTrigger:if not self.hasParent and not self.tags(includes= '轻型掩体')
isVisible:false
temporarilyAddTags:轻型掩体



[graphics]
total_frames: 3
image: 轻坦克底盘.png
image_wreak: 轻坦克死亡.png
image_turret: 轻坦克炮塔.png
#imageScale:5.8

#turretImageScale:0.8
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 0

animation_moving_end: 2
animation_moving_speed: 1
dustEffect: true
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 33

turretTurnSpeed: 4
maxAttackRange: 260
shootDelay: 75


[turret_1]
#
x: 0
y: -2
projectile: 1
turnSpeedAcceleration: 1.0

shoot_sound: large_gun_fire1
shoot_sound_vol: 0.5
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true

recoilOffset: -2
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头1')
image:轻坦克炮塔.png
canAttackFlyingUnits: false
[projectile_1]
@copyFromSection: template_动能
directDamage: 125
life: 600
speed: 8.5
color: #FFFFFF73

drawSize: 1.5
largeHitEffect: true
lightSize: 1
lightColor: #FFFFFF73
[projectile_炮弹]
@copyFromSection: template_能源
areaDamage: 160
areaRadius: 45
life: 600
speed: 8.5

drawSize: 0.7
image: ROOT:/创世纪军事集团/单位特效/核弹.png
explodeEffect: CUSTOM:底色,CUSTOM:闪光,CUSTOM:冲击波
buildingDamageMultiplier: 1.2
deflectionPower: -1

areaRadiusFromEdge: true

[effect_底色]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.25
scaleTo: 0.25
alpha: 1.3
drawUnderUnits: false


alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 0.1

drawUnderUnits: false
atmospheric: false


[effect_冲击波]
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 20
fadeOut: true
attachedToUnit: false

scaleFrom: 0.05
scaleTo: 0.5
alpha: 0.8
drawUnderUnits: false
atmospheric: true



[movement]
movementType: LAND
moveSpeed: 0.9
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 3.5

turnAcceleration: 0.25
moveSlidingMode : false
moveIgnoringBody: false


