


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=700

[action_拆除哇袄]
addResources: 威胁点数=-700
[core]
name: 余辉重力场要塞炮
strictLevel: 0
displayDescription: 少有的由马尔科姆 莱恩皇帝亲自设计的毁灭性武器，\n-毫无疑问，重力场要塞炮是余辉军火库中最具威力的兵器，没有之一。\n-重力场要塞炮以经过重子凝缩后的临界状态蓝晶作为武器，\n-这种物质一旦脱离束缚就可以将空间中的零点能无节制的释放并引发链式反应，\n-在释放巨大能量引发零点能震爆的同时，空间也将被彻底颠覆。\n-模拟黑洞，反物质兵器，哪怕是最恐怖的自然灾害在零点能震爆的面前，都显得如同烛火一般温顺。\n-在诺瓦帝国时期，人们观看过重力场要塞炮的实验后，有许多人便坚定不移的相信马尔科姆莱恩殿下就是神明。
price: 15500,蓝晶=1050
radius: 70

extraBuildRangeWhenBuildingThis: 200
maxHp: 14500
energyMax: 1
energyRegen: 0
energyNeedsToRechargeToFull: true

energyStartingPercentage: 0
class: CustomUnitMetadata
effectOnDeath: CUSTOM:死亡, CUSTOM:爆炸s*1
copyFrom: ROOT:/通用特效/单位防护.ini

tags: 要塞炮,地面,建筑
isBuilding: true
#footprint used for collisions with units (left, up, right, down)
footprint: -2,-2,2,2
#used for placement, and placement of other buildings

constructionFootprint: -8,-4,8,6
armour: 12
buildSpeed: 145s


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='要塞炮')
deleteSelf: true
addResources: 威胁点数=-700
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[action_0_补充能量]
price: 蓝晶=3100,35000
text: 相控电磁阀充能
buildSpeed: 95s
pos: 0.2
isActive: if self.energyIncludingQueued(lessThan= 0.5)

addResources: energy= 1
description: -激活相控电磁阀，对蓝晶进行重子凝缩使其转化为临界物质，\n-同时将其约束于发射口准备击发，\n-相控电磁阀充能的巨大能量波动无法隐藏，充能完毕将警告所有玩家，请注意。
iconImage: 充能.png
showMessageToAllPlayers: 监测到超高密度临界物质！
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_攻击]
highPriorityQueue: true
price: energy= 1
buildSpeed: 0s
fireTurretXAtGround: 0
text: 真空零点能震爆

isVisible: if numberOfUnitsInAggressiveTeam(withTag= "要塞炮目标", lessThan= 0.5)
addResources: ammo= 1
alsoTriggerAction: 增加标签
description: -发射终极武器，制造一场规模空前的浩劫摧毁敌人。
iconImage: 狙.png

showMessageToAllPlayers: 发射检测：警告，监测到巨大能量波动！
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[hiddenAction_增加标签]
autoTrigger: if not self.isAmmoEmpty() and not self.tags(includes='要塞炮攻击')
temporarilyAddTags: 要塞炮攻击


[hiddenAction_正常]
resourceAmount: ammo
resourceAmount_setValue: 0
temporarilyRemoveTags: 要塞炮攻击


[graphics]
image: 底盘.png
image_wreak: 死亡.png
# image_turret:炮台.png
#turretImageScale:0.9
#scaleImagesTo: 20

#scaleTurretImagesTo: 20
image_back: 背景.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1

teamColorsOnTurret: true
imageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
# turretMultiTargeting: true

canOnlyAttackUnitsWithTags: 要塞炮目标
maxAttackRange: 99999
turretSize: 200


[turret_0]
x: 0
y: 0
projectile: 0
limitingMinRange: 800
canShoot: false

invisible: true


[turret_10]
x: 0
y: 0
projectile: 13
attachedTo: 1
canShoot: true

slave: true
shoot_flame: CUSTOM:冲击波z,CUSTOM:粒子z*2,CUSTOM:闪光z
delay: 50
invisible: true


[turret_1]
#
x: 0
y: 57
projectile: 1
turnSpeed: 1

idleSpin: 0.1
canShoot: true
canAttackCondition: if self.tags(includes='要塞炮攻击')
shoot_sound: 大主炮音效.ogg
shoot_sound_vol: 0.6

warmup: 7.5s
# energyUsage: 0
onShoot_triggerActions: 正常
#warmupStartEffect:CUSTOM:气浪,CUSTOM:粒子*3,CUSTOM:旋转*1
chargeEffectImage: 闪光.png

shoot_flame: CUSTOM:烟雾x*10,CUSTOM:粒子1*20,CUSTOM:闪光y,CUSTOM:聚变,CUSTOM:冲击波,CUSTOM:气浪,CUSTOM:粒子*3
image: 炮台.png
recoilOffset: -20
recoilOutTime: 13
recoilReturnTime: 30


[projectile_0]
# 生成中介
life: 1
speed: 0
deflectionPower: -1
directDamage: 0

invisible: true
instant: true
spawnUnit: 要塞炮中介1
explodeEffect:NONE

[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[projectile_1]
# 伤害
areaDamage: 0
areaRadius: 0
#areaHitAirAndLandAtSameTime:true
life: 24000

speed: 17
deflectionPower: -1
drawSize: 1.8
targetSpeed: 17
#frame:1

image: ROOT:/余辉军团/单位特效/子弹1.png
#explodeEffect:CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:弹坑,CUSTOM:爆炸
#targetGround:true
lightSize: 0.75
trailEffectRate: 0.5

trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1
lightColor: #FF00B3FF
mutator1_ifUnitWithTags: 要塞炮目标
mutator1_addResourcesDirectHit: ammo= 10
spawnUnit: 要塞炮炮弹1*1

explodeEffect: CUSTOM:闪光x


[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/粗子弹3.png
life: 30
fadeOut: true
attachedToUnit: false

#color:#FFFFFF3D
fadeInTime: 0.1
scaleFrom: 0.6
scaleTo: 0.6
alpha: 0.6

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_尾巴1]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 30
fadeOut: true
attachedToUnit: false

fadeInTime: 0.1
scaleFrom: 0.2
scaleTo: 1.3
alpha: 0.8
drawUnderUnits: false


[arm_1]
#左肩
x: 0
y: 0
image_end: 闪烁.png
image_end_teamColors: true

drawOverBody: false


[animation_idle]
onActions : idle
arm1_0s: {alpha:0.0}
# arm1_0.1s:{alpha:0.1}
# arm1_0.2s:{alpha:0.2}
# arm1_0.3s:{alpha:0.3}

# arm1_0.4s:{alpha:0.4}
# arm1_0.5s:{alpha:0.5}
# arm1_0.6s:{alpha:0.6}
# arm1_0.7s:{alpha:0.7}
arm1_0.8s: {alpha:0.8}

# arm1_0.9s:{alpha:0.7}
# arm1_1s:{alpha:0.6}
# arm1_1.1s:{alpha:0.5}
# arm1_1.2s:{alpha:0.4}
# arm1_1.3s:{alpha:0.3}

# arm1_1.4s:{alpha:0.2}
arm1_1.5s: {alpha:0.1}


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 55
fadeOut: true
#dirOffsetRandom:100

dirSpeed: -2
dirSpeedRandom: 1.5
scaleFrom: 5
scaleTo: 0.1
alpha: 2

drawUnderUnits: false
atmospheric: false
attachedToUnit: true
#xOffsetRelative	:-10


[effect_粒子]
priority: critical
image: 光粒.png
dirOffsetRandom: 200
dirSpeed: -2
dirSpeedRandom: 1.5

life: 100
scaleFrom: 0.1
scaleTo: 3
alpha: 1
drawUnderUnits: false

attachedToUnit: true
atmospheric: false
#xOffsetRelative	:-10


[effect_烟雾x]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 100
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 2
scaleTo: 5
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 3
xSpeedRelativeRandom: 1.5

yOffsetRelative: 3
ySpeedRelative: 2.5
atmospheric: true


[effect_粒子1]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 1
scaleTo: 1

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 2

xSpeedRelativeRandom: 0.6
yOffsetRelative: 1.6
ySpeedAbsoluteRandom: 3
ySpeedRelative: 3
#xOffsetRelative:-2

#xOffsetRelative	:-10
atmospheric: true


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 1
scaleTo: 1

drawUnderUnits: true
atmospheric: false
alsoPlaySound: 蓄力.ogg


[effect_旋转]
life: 700
priority: critical
attachedToUnit: true
scaleFrom: 0
scaleTo: 0.7

image: 闪光.png
fadeOut: true
alpha: 2
fadeInTime: 10
dirOffsetRandom: 200

dirSpeed: -2
dirSpeedRandom: 1.5
drawUnderUnits: false
#xOffsetRelative	:-10


[effect_闪光y]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 8
scaleTo: 8

drawUnderUnits: true
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 3.3
scaleTo: 3.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.7
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_死亡]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3.3

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
createWhenOverLiquid: true
createWhenOverLand: true
drawUnderUnits: true


[effect_爆炸s]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2.5

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_冲击波z]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.2
scaleTo: 0
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_粒子z]
priority: critical
image: 光粒.png
dirOffsetRandom: 200
dirSpeed: -2
dirSpeedRandom: 1.5

life: 100
scaleFrom: 1.7
scaleTo: 0
alpha: 0.8
drawUnderUnits: false

attachedToUnit: true
atmospheric: false
#xOffsetRelative	:-10


[effect_闪光z]
priority: critical
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 0

turnAcceleration: 0.25
moveSlidingMode : false
moveIgnoringBody: false


