


[core]
name: 要塞炮中介1
displayText: Посредник крепостной пушки 1
strictLevel: 1
price: 0
radius: 10
maxHp: -1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: 要塞炮目标
canNotBeDamaged: true

canOnlyBeAttackedByUnitsWithTags: 要塞炮
isUnrepairableUnit: true
isUnselectable: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
hideScorchMark: true
explodeOnDeath: false
disableDeathOnZeroHp: true
isBuilding: true
# stayNeutral: true
# createNeutral: true
createOnAggressiveTeam: true

# 创建为敌对中立


[action_爆炸]
autoTrigger: if self.timeAlive(laterThanSeconds=35)
deleteSelf: true


[graphics]
image: SHARED:blank.png
# isVisible: false
disableLowHpFire: true
disableLowHpSmoke: true

[attack]
canAttack: false
# maxAttackRange: 3


[hiddenAction_删除]
autoTrigger: if self.ammo(greaterThan= 9.5)
deleteSelf: true


[movement]
movementType: AIR
moveSpeed: 0
moveAccelerationSpeed: 0
maxTurnSpeed: 0
targetHeight: 0

targetHeightDrift: 0


