


[core]
name: 丧钟鱼雷舱
displayText: Торпедный отсек «Похоронный звон»
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
tags:反高空

[hiddenAction_目标定位生效]
autoTrigger: if self.globalTeamTags(includes='目标定位2')
setUnitStats: maxAttackRange= ${attack.maxAttackRange*1.35}

[graphics]
total_frames: 1
image: 导弹托.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 900
isFixedFiring: true
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0


[turret_1]
x: 0
y: 0
canShoot: false
invisible: true


[turret_2]
x: 6
y: 8
projectile: 1
attachedTo: 1
slave: true
image: 导弹头1.png
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾*5
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -10
recoilOutTime: 4
recoilReturnTime: 180
#limitingMinRange: 400
canOnlyAttackUnitsWithTags:高空
delay:360
canAttackCondition: if not self.globalTeamTags(includes='轨道4')
invisible:if self.globalTeamTags(includes='轨道4')
[turret_3]
copyFrom: 2
warmup: 15
x: 0
y: 8
delay:345
[turret_4]
copyFrom: 2
warmup: 30
delay:330
x: -6
y: 8

[turret_5]
copyFrom: 2
x: 6
y: 8
delay:300
canAttackCondition: if self.globalTeamTags(includes='轨道4')
invisible:if not self.globalTeamTags(includes='轨道4')
projectile: 炮弹
image:罐1.png
[turret_6]
copyFrom: 2
warmup: 15
x: 0
y: 8
delay:345
canAttackCondition: if self.globalTeamTags(includes='轨道4')
invisible:if not self.globalTeamTags(includes='轨道4')
image:罐1.png
projectile: 炮弹
linkDelayWithTurret:5
[turret_7]
copyFrom: 2
warmup: 30
delay:330
x: -6
y: 8
canAttackCondition: if self.globalTeamTags(includes='轨道4')
invisible:if not self.globalTeamTags(includes='轨道4')
projectile: 炮弹
image:罐1.png
linkDelayWithTurret:6
[projectile_1]
@copyFromSection: template_爆炸
#普通炮弹
areaDamage: 2500
areaRadius: 90
life: 5000
speed: 8
color: #FFFFFF73
trailEffect: true
lightSize: 1.5
image:导弹头.png
lightColor: #FFFFFF73
drawSize: 0.9
targetSpeed: 15
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波
targetGroundHeightOffset:140
targetGround:true
disableLeadTargeting: true
trailEffectRate: 1.5
targetGroundSpread: 40
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_炮弹]
@copyFromSection: template_动能
life: 25
speed: 8
targetSpeed: 15
targetSpeedAcceleration: 0.1
image: 罐.png
drawSize: 1
spawnProjectilesOnEndOfLife:炮弹1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片
trailEffectRate: 1
areaDamage: 0
areaRadiusFromEdge: true
areaHitAirAndLandAtSameTime: false
alwaysVisibleInFog: true
areaRadius: 0
deflectionPower: -1
shouldRevealFog: true
lightColor: #FFEEEE00
lightSize: 1
trailEffect:true
[projectile_炮弹1]
@copyFromSection: template_动能
directDamage: 3000
life: 200
speed: 15
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
drawSize: 0.7
explodeEffect: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*7,CUSTOM:冲击波gd,CUSTOM:穿透
explodeEffectOnShield: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*7,CUSTOM:冲击波gd,CUSTOM:穿透
lightSize: 1
trailEffectRate: 0.2
trailEffect: CUSTOM:尾巴gd
lightColor: #FFFF1200
armourIgnoreAmount: 999
shieldDamageMultiplier: 1.2
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.6
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
#————————
[effect_导弹碎片]
#priority: low
image: 弹壳.png
spawnChance: 1
life: 60
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.2
ySpeedRelative: -0.5
ySpeedRelativeRandom: 0.2
hSpeed: 2
dirSpeedRandom: 35
#——————————————————————科技
[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.87
scaleTo: 0.87
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_冲击波gd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 1.35
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_爆炸1gd]
image: ROOT:/创世纪军事集团/单位特效/轨道炮炸裂.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 3
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.55
alwayStartDirAtZero: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:30
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.2
scaleTo:1.5
alpha: 0.8
fadeInTime: 4
drawUnderUnits:false
[effect_碎星gd]
spawnChance: 1
createWhenZoomedOut: false
life: 35
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom:0.175
scaleTo:0.175
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 5
ySpeedRelativeRandom: 5
[effect_穿透]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
life: 35
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.1
alpha: 1
drawUnderUnits: false
ySpeedRelative: 8
atmospheric: true
[effect_闪光gd]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 8
scaleTo: 1
drawUnderUnits: true
atmospheric: false
#——++......
[effect_尾巴gd]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 15
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.4
scaleTo: 0.5
alpha: 0.7
drawUnderUnits: false

[arm_1]
x: 0
y: 0
image_end: 导弹炮塔.png
drawOverBody: true

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 1.6
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


