


[core]
name: 死眼和雷神1
displayText: 落点
class: CustomUnitMetadata
price: 0
maxHp: 10
armour: 999989
techLevel: 2
radius: 0
displayRadius: 0
armourMinDamageToKeep: 0
showInEditor:false
hideScorchMark: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
isUnselectable: true
isBio: false
canNotBeGivenOrdersByPlayer: true
showOnMinimap:false
energyMax: 1
energyRegen: -1
fogOfWarSightRange: 40
explodeOnDeath: false
isBuilding: true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_添加]
autoTrigger: if self.isEnergyEmpty() and not self.tags(includes= '1号') and self.resource.1>0.5
temporarilyAddTags:1号
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 0,0

[hiddenAction_添加1]
autoTrigger: if self.isEnergyEmpty() and not self.tags(includes= '2号') and self.resource.2>0.5
temporarilyAddTags:2号
fireTurretXAtGround: 2
fireTurretXAtGround_withOffset: 0,0

[hiddenAction_麻]
autoTrigger: if self.isEnergyEmpty()and (self.resource.1>0.5 or self.resource.2>0.5) and self.timeAlive(laterThanSeconds=8)
deleteSelf: true

[hiddenAction_干扰弹]
autoTrigger: if self.resource.3>0.5
fireTurretXAtGround: 干扰弹
fireTurretXAtGround_withOffset: 0,0
deleteSelf: true
[graphics]
total_frames: 1
image:ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 1
icon_zoomed_out_neverShow:true
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 150

aimOffsetSpread: 0
shootDelay: 1
turretMultiTargeting: true

[turret_1]
#死眼
x:0
y: 3000
invisible: true
projectile: 1
turnSpeed: 15

turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true
[turret_2]
#雷神
x:0
y: 0
height:3000
invisible: true
projectile: 3
turnSpeed: 15

turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true
[turret_干扰弹]
x: 0
y: 3000
copyFrom: 1
projectile: 2

[projectile_1]
@copyFromSection: template_动能,template_战略武器
areaDamage:70000
areaRadius: 100
drawSize: 0.9
life: 9999
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
image:ROOT:/创世纪军事集团/单位特效/弹头.png
speed: 19
explodeEffect: NONE
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 0.07
trailEffect: CUSTOM:烟雾*3,CUSTOM:火焰,CUSTOM:闪光nk
tags:天上战略
spawnUnit: 小核爆(addResources=撞击:1,spawnSource= self.getOffsetRelative(x= 0, y= 0,dirOffset=180))
spawnProjectilesOnExplode:wy
explodeOnEndOfLife: true
areaHitUnderwaterAlways:true
largeHitEffect: true
[projectile_wy]
@copyFromSection: template_爆炸,template_战略武器
areaDamage: 28000
areaRadius: 300
areaRadiusFromEdge: true
life: 0
invisible: true
delayedStartTimer: 4s
speed: 0
turnSpeed: 0.0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
explodeEffect: CUSTOM:超级冲击波*2,CUSTOM:实验*2,CUSTOM:震动,CUSTOM:闪光hh
explodeEffectOnShield: CUSTOM:超级冲击波*2,CUSTOM:实验*2,CUSTOM:震动,CUSTOM:闪光hh

spawnUnit: 导弹2爆炸(addResources=1:1,spawnSource= self.getOffsetRelative(x= 0, y= 0,dirOffset=180))
areaHitUnderwaterAlways:true

largeHitEffect: true

[projectile_2]
@copyFromSection: template_动能,template_战略武器
areaDamage:1000
areaRadius: 60
drawSize: 0.7
life: 9999
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
image:ROOT:/创世纪军事集团/单位特效/弹头.png
speed: 19
explodeEffect: CUSTOM:闪光dn,CUSTOM:烟雾dn1*8,CUSTOM:烟雾dn*8,CUSTOM:冲击波dn1,CUSTOM:冲击波dn2
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 0.07
trailEffect: CUSTOM:烟雾*2,CUSTOM:火焰
tags:天上战略
explodeOnEndOfLife: true
largeHitEffect: true
[projectile_3]
areaDamage:1000
areaRadius: 700
drawSize: 0.9
life: 9999
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
image:ROOT:/创世纪军事集团/单位特效/弹头.png
speed: 19
explodeEffect: CUSTOM:超级冲击波emp*2,CUSTOM:实验emp*2,CUSTOM:震动emp,CUSTOM:粒子emp*50,CUSTOM:电磁emp1*25
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 0.07
trailEffect: CUSTOM:烟雾*3,CUSTOM:火焰,CUSTOM:闪光nk
tags:天上战略
explodeOnEndOfLife: true
areaDamageNoFalloff: true
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: xk= 10
shieldDamageMultiplier: 9999
spawnProjectilesOnExplode:4,5
spawnUnit: 导弹2爆炸(addResources=2:1,spawnSource= self.getOffsetRelative(x= 0, y= 0,dirOffset=180)),电磁立场(spawnSource= self.getOffsetRelative(x= 0, y= 0,dirOffset=180))
areaHitAirAndLandAtSameTime: true
largeHitEffect: true
[projectile_4]
areaDamage: 15000
delayedStartTimer: 0.4s
areaRadius: 300
areaRadiusFromEdge: true
life: 0
invisible: true
speed: 0
turnSpeed: 0.0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
explodeEffect: NONE
explodeEffectOnShield: NONE
mutator121_ifUnitWithoutTags: 无人单位
mutator121_directDamageMultiplier: 0
mutator121_areaDamageMultiplier: 0
largeHitEffect: true
[projectile_5]
areaDamage: 9999999
areaRadius: 300
areaRadiusFromEdge: true
life: 0
invisible: true
speed: 0
turnSpeed: 0.0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
explodeEffect: NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true
mutator121_ifUnitWithoutTags: 步兵
mutator121_directDamageMultiplier: 0
mutator121_areaDamageMultiplier: 0
largeHitEffect: true
[effect_烟雾]
dirOffsetRandom: 180
stripIndex: effects
frameIndex: 0
life: 100
fadeOut: true
priority: critical
attachedToUnit: false
fadeInTime: 0.8
scaleTo: 3
scaleFrom: 2.5
alpha: 3
hSpeed: 1.5
drawUnderUnits: false
atmospheric: false
spawnChance: 1
hOffsetRandom: 0.9
xSpeedRelativeRandom: 2.5


[effect_火焰]
priority: critical
image: ROOT:/余辉军团/建筑特效/火光.png
life: 15
spawnChance: 0.4
fadeOut: true
attachedToUnit: true
fadeInTime: 0.8
scaleTo: 1
scaleFrom: 0.5
alpha: 0.5
hSpeed: 0.5
drawUnderUnits: false
atmospheric: false
xSpeedAbsoluteRandom: 0.8
alwayStartDirAtZero: true
xOffsetRelativeRandom:5
yOffsetRelativeRandom:3
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 20
spawnChance: 0.3
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 4
scaleTo: 0
drawUnderUnits: false
atmospheric: false
xOffsetRelativeRandom:8
yOffsetRelativeRandom:8



[effect_超级冲击波]
priority: critical
image: 超级.png
life: 110
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 4
drawUnderUnits: false

atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:100
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:7
priority: critical
scaleTo:13
alpha: 1
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180
[effect_震动]
createWhenOffscreen:true
drawType: displacement
priority: critical
image:震动.png
life:120
fadeOut: false
fadeInTime:50
attachedToUnit: true
scaleFrom:40
scaleTo:40
alpha:0.035
drawUnderUnits:false
createWhenZoomedOut: true
alwayStartDirAtZero: true
total_frames: 2
animateFrameStart: 0
animateFrameEnd:1
animateFrameSpeed: 0.3
animateFrameLooping:true
[effect_闪光hh]
priority: high
image: SHARED:light_50.png
life: 45
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 17
scaleTo: 1
drawUnderUnits: true
atmospheric: false
showInFog: true
#————————————————小爆炸
[effect_冲击波dn1]
life: 100
priority: high
attachedToUnit: false
scaleFrom: 1
scaleTo: 3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true
alpha:0.8
createWhenOffscreen: true
[effect_冲击波dn2]
stripIndex: shockwave
life: 60
scaleFrom: 1
scaleTo: 10
alpha: 0.8
fadeOut: true
fadeInTime: 2
createWhenOffscreen: true
[effect_闪光dn]
image: SHARED:light_50.png
life: 15
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 8
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_烟雾dn]
color: #FF917C44
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenOffscreen: true
life: 300
fadeOut: true
attachedToUnit: false
fadeInTime: 1
scaleFrom: 7
scaleTo: 10
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.4
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
atmospheric: true
xOffsetRelativeRandom:30
yOffsetRelativeRandom:30
createWhenOverLiquid: false
createWhenOverLand: true
[effect_烟雾dn1]
color: #FFFFFFFF
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenOffscreen: true
life: 300
fadeOut: true
attachedToUnit: false
fadeInTime: 1
scaleFrom: 7
scaleTo: 10
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.4
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
atmospheric: true
xOffsetRelativeRandom:30
yOffsetRelativeRandom:30
createWhenOverLiquid: true
createWhenOverLand: false
#——————————————emp
[effect_粒子emp]
spawnChance: 1
createWhenZoomedOut: true
life: 100
fadeOut: true
attachedToUnit: false
#color: #FFFFFF
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom: 0.85
scaleTo: 0.85
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 17
ySpeedRelativeRandom: 17
xOffsetRelativeRandom:50
yOffsetRelativeRandom:50

[effect_电磁emp1]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: ROOT:/通用特效/电弧.png
total_frames: 8
animateFrameStart:1
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 0.85
drawUnderUnits: false
scaleFrom: 3
scaleTo:3
xOffsetRelativeRandom:700
yOffsetRelativeRandom:700
delayedStartTimerRandom:70
createWhenZoomedOut: true
createWhenOffscreen: true
[effect_超级冲击波emp]
priority: critical
image: 超级1.png
life: 110
fadeOut: true
attachedToUnit: false
scaleFrom: 1.8
scaleTo: 1.8
alpha: 4
drawUnderUnits: false
createWhenZoomedOut: true
createWhenOffscreen: true
atmospheric: false
showInFog: true
alsoPlaySound: ROOT:/余辉军团/单位特效/瓶1.ogg
[effect_实验emp]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:100
fadeOut: true
attachedToUnit: true
scaleFrom:6
priority: critical
scaleTo:10
alpha: 1
drawUnderUnits:false
createWhenZoomedOut: true
createWhenOffscreen: true
dirOffsetRandom:180
[effect_震动emp]
createWhenOffscreen:true
drawType: displacement
priority: critical
image:震动.png
life:120
fadeOut: false
fadeInTime:50
attachedToUnit: true
scaleFrom:50
scaleTo:50
alpha:0.035
drawUnderUnits:false
createWhenZoomedOut: true
alwayStartDirAtZero: true
total_frames: 2
animateFrameStart: 0
animateFrameEnd:1
animateFrameSpeed: 0.3
animateFrameLooping:true
[movement]
movementType: AIR
moveSpeed: 1
maxTurnSpeed: 1
targetHeight: -1
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true

[resource_1]
displayName: 1
displayNameShort: 1
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_2]
displayName: 2
displayNameShort: 2
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_3]
displayName: 3
displayNameShort: 3
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_撞击]
displayName: 撞击
displayNameShort: 撞击
displayColor: #FF9D00FF
priority: 1
hidden: true
