


[core]
name: 小型空投仓空投
class: CustomUnitMetadata
price: 0
maxHp: 999999
techLevel: 1

buildSpeed: 0s
isBio: false
isBuilding: true
footprint: -1,0,1,2
constructionFootprint: -1,0,1,2

fogOfWarSightRange: 5
tags: 空降仓x
radius: 25
canOnlyBeAttackedByUnitsWithTags: 导弹防御,卫星防御,无人机库

[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_t1]
autoTrigger: if self.timeAlive(laterThanSeconds=2.6)
isVisible: false
spawnEffects: CUSTOM:碎片,CUSTOM:碎片1,CUSTOM:碎片2,CUSTOM:碎片3*2,CUSTOM:碎片4,CUSTOM:碎片5,CUSTOM:烟雾3*8,CUSTOM:冲击波zx
spawnUnits: SDAF预兆*1,SDAF冲击波*1
deleteSelf: true


[graphics]
total_frames: 1
image: 空投.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
#imageScale:0.9


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
turretSize: 0

turretTurnSpeed: 50
maxAttackRange: 9999


[turret_烟雾]
x: -20
y: -40
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 5

invisible: true
size: 1


[turret_烟雾2]
x: 20
y: -40
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 5

invisible: true
size: 1


[turret_火焰]
x: 0
y: -30
projectile: 13
shoot_flame: CUSTOM:火焰
delay: 10

invisible: true
size: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[effect_烟雾]
dirOffsetRandom: 180
stripIndex: effects
frameIndex: 0
life: 100
fadeOut: true

priority: critical
attachedToUnit: false
fadeInTime: 0.8
scaleTo: 3
scaleFrom: 2.5

alpha: 3
hSpeed: 1.5
drawUnderUnits: false
atmospheric: false
spawnChance: 1

hOffsetRandom: 0.9
xSpeedRelativeRandom: 2.5


[effect_火焰]
priority: critical
image: ROOT:/余辉军团/建筑特效/火光.png
life: 20
fadeOut: true
attachedToUnit: true

fadeInTime: 0.8
scaleTo: 1
scaleFrom: 0.5
alpha: 1
hSpeed: 0.5

drawUnderUnits: false
atmospheric: false
spawnChance: 1
xSpeedAbsoluteRandom: 0.8
alwayStartDirAtZero: true


[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
life: 240
fadeOut: true
attachedToUnit: false

color: #6D5448
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 0.6
alpha: 1

drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180

xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_冲击波]
stripIndex: shockwave
life: 70
scaleFrom: 0.3
scaleTo: 3
color: #FFF0AFA5

alpha: 1


[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1
startingHeightOffset: 2000
targetHeightDrift: 0


[ai]
buildPriority: 0.2
ai_upgradePriority: 1
maxEachBase: 30
maxGlobal: 200


[effect_碎片]
priority: critical
image: 碎片.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: -5
ySpeedRelativeRandom: -0.35
yOffsetRelative: 30
xOffsetRelative: -7
hSpeed: 3

dirSpeedRandom: 70


[effect_碎片1]
priority: critical
image: 碎片1.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 4
ySpeedRelativeRandom: 0.35
yOffsetRelative: 30
xOffsetRelative: 7
hSpeed: 3

dirSpeedRandom: 70


[effect_碎片2]
priority: critical
image: 顶.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: -0.5
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 3
yOffsetRelative: 30
xOffsetRelative: 0

hSpeed: 4
dirSpeedRandom: 30


[effect_碎片3]
priority: critical
image: 碎片2.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.2
yOffsetRelative: 10
xOffsetRelative: 0
hSpeed: 5
dirSpeedRandom: 60


[effect_碎片4]
priority: critical
image: 门.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1
yOffsetRelative: -45
xOffsetRelative: 0
hSpeed: 2
dirSpeedRandom: 25


[effect_碎片5]
priority: critical
image: 底.png
life: 360
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 2
drawUnderUnits: true
atmospheric: false


[effect_烟雾3]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 200
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 5
scaleTo: 7
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.3
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_冲击波zx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.2

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


