


[core]
name: 标旗空降兵
displayText: Десантник со штандартом
class: CustomUnitMetadata
displayDescription: 【Уровень t4】【Биологический юнит】【Наземный юнит】Тактическое назначение: универсальная пехота，размер юнита:1\n-▲12.7мм步枪X1 по земле и воздуху кинетический урон пробивает укрытия \n-▲нетпосле坐силапушкаx1 по земле и воздуху кинетический урон\n-тот些вна войнетело受тяжёлый伤，почтипотерять抢救价值 Генезиссолдат，\n-в运气влиния，телоотносительнов качествеполныйхороший в случае，онибудет ЧВК «Корпус»нести走，\n-ичерезмодификация手术植入усиливает义体，черезпередовойнаукатяжёлый获новый生。\n-пройти черезмодификацияпосле Десантник со штандартом，будетбудетв药物 рольнизстановитсяне惧疼痛инет所畏惧，\n-ониобычнобудет командование官когдастановитьсяодин разтип消耗品，тело усиливаетустановитьоснащение，отнебоа降至врагпослеквадратный，\n-或者徒步去执行тот些девять死один生 задача，сила争в关键момент逆转局势。

reclaimPrice:0
isUnrepairableUnit:true
price: 300
maxHp: 950
mass: 700
techLevel: 1
buildSpeed: 3s
radius: 9
softCollisionOnAll: 0
isBio: true
explodeOnDeath: false
hideScorchMark: true
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
tags: 步兵,地面,标旗空降兵,驻扎要塞,1格
fogOfWarSightRange: 15
energyMax: 4
energyRegen: 0.035
energyNeedsToRechargeToFull: true
armour: 4
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md,ROOT:/通用特效/扎针.md
[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
#高达—————————
[action_举枪]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan= 0,withInRange=370, incompleteBuildings= true) and not self.tags(includes= '举枪')
isVisible:false
temporarilyAddTags:举枪
playAnimation:部署
[action_收枪]
autoTrigger: if numberOfUnitsInEnemyTeam(lessThan= 1,withInRange=370, incompleteBuildings= true) and self.tags(includes= '举枪')
isVisible:false
stopLastAnimation: true

alsoQueueAction: b
[action_b]
displayType: action
price: 0
playAnimation: 部署1
buildSpeed: 0.51s
isVisible: false
temporarilyRemoveTags:举枪
highPriorityQueue: true
whenBuilding_cannotMove: false
[action_tx1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
#————————科技
[action_聚变弹头2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变2.png
text: Термоядерная боеголовка2
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头2')

[graphics]
total_frames: 13
image: 腿.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
imageScale: 0.8
animation_moving_start: 0
animation_moving_end: 12
animation_moving_speed: 1


[attack]
canAttack: true
canAttackFlyingUnits:true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 18
turretTurnSpeed: 3
maxAttackRange: 270
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_1]
#绑定
x: 0
y: 0
canShoot: false


[turret_2]
#主炮
x: 5
y: 4
invisible: true
attachedTo: 1
slave: true
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.7
projectile: 1
delay: 3
shoot_flame: CUSTOM:枪口火焰,CUSTOM:弹壳
energyUsage:0.5
size:19
canAttackCondition:if (self.tags(includes= '举枪') or self.hasParent) and not self.tags(includes= '冲锋')
[turret_3]
#主炮
x: -5
y: 0
invisible: true
attachedTo: 1
slave: true
shoot_sound:突击炮音效.ogg
shoot_sound_vol: 0.45
projectile: 2
delay: 120
shoot_flame: CUSTOM:枪口火焰
canAttackFlyingUnits:true
size:10
canAttackCondition:if self.tags(includes= '举枪') or self.hasParent
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头2')
[turret_4]
#主炮
x: 5
y: 4
invisible: true
attachedTo: 1
slave: true
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.7
projectile: 1
delay: 3
shoot_flame: CUSTOM:枪口火焰,CUSTOM:弹壳
size:19
canAttackCondition:if (self.tags(includes= '举枪') or self.hasParent) and self.tags(includes= '冲锋')
[projectile_1]
@copyFromSection: template_动能
directDamage: 22
life: 420
speed: 10
targetSpeed: 10
deflectionPower: -1
frame:8
drawSize: 0.45
largeHitEffect: false
explodeEffect: CUSTOM:火花
explodeEffectOnShield: CUSTOM:火花
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[projectile_2]
@copyFromSection: template_动能
directDamage: 325
life: 320
lightColor: #FFFFEB88
lightSize: 1
largeHitEffect: true
drawSize: 0.65
speed: 7
frame: 8
deflectionPower: -1
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光
[projectile_炮弹]
@copyFromSection: template_能源
areaDamage: 425
areaRadius: 40
life: 320
lightColor: #FFFFEB88
lightSize: 1
largeHitEffect: true
drawSize: 0.65
speed: 7
frame: 8
deflectionPower: -1
explodeEffect: CUSTOM:底色jb,CUSTOM:闪光jb,CUSTOM:冲击波jb
buildingDamageMultiplier: 1.2
explodeEffectOnShield:CUSTOM:底色jb,CUSTOM:闪光jb,CUSTOM:冲击波jb
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

#死亡特效———————


[effect_飘血]
life: 150
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: true
liveAfterAttachedDies: true
physics: true

physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.7
ySpeedRelativeRandom: 0.6
hSpeed: 1


[effect_飘血2]
life: 150
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

scaleFrom: 0.5
scaleTo: 0.5
drawUnderUnits: true
liveAfterAttachedDies: true
physics: true

physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1
ySpeedRelativeRandom: 1
hSpeed: 1

dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 150
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 3
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡.ogg,ROOT:/创世纪军事集团/步兵特效/死亡3.ogg,ROOT:/创世纪军事集团/步兵特效/死亡4.ogg,ROOT:/创世纪军事集团/步兵特效/死亡5.ogg

[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0
scaleFrom: 1.3
scaleTo: 1.3
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
[effect_火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.18
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2


[effect_弹壳]
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 120
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.3
scaleTo: 0.3
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 0.6
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.25
yOffsetRelative: -10
xOffsetRelative: 5

hSpeed: 2
dirSpeedRandom: 50

[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 2
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.65
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.26
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alpha: 1.2
#————————聚变
[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 55
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.2
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
[effect_闪光jb]
image: SHARED:light_50.png
life: 10
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 3
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 0.45
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[arm_1]
#左后臂
x: -6
y: -1
image_end: 手.png
image_end_teamColors: true

drawDirOffset: -20
drawOverBody: false
image_end_shadow: SHADOW:手.png


[arm_2]
#右后臂
x: 5
y: -2
image_end: 手.png
image_end_teamColors: true

drawOverBody: false
drawDirOffset: 45
image_end_shadow: SHADOW:手.png


[arm_3]
#右前臂
x: 9
y: 2
image_end: 手.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -45
image_end_shadow: SHADOW:手.png




[arm_4]
x: -7
y: 5
image_end: 手.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: 45
image_end_shadow: SHADOW:手.png

[arm_5]
#身体
x: 0
y: 0
image_end: 身体.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:身体.png

[arm_6]
#枪
x: 4
y: 5
image_end: 枪.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -63


[arm_7]
#脑袋
x: 0
y: 0
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[arm_8]
#脑袋
x: -5
y: 0
image_end: 炮.png
image_end_teamColors: true

drawOverBody: true


[leg_1]
x: -2
y: 0
attach_x: -1
attach_y: -1
moveSpeed: 2.8
#hardLimit: 
moveWarmUp: 0.1s
hidden: if self.hasParent()
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25
targetHeightRelative: false
image_leg: 腿.png
dust_effect: false
holdDisMin: 1
holdDisMax: 6
estimatingPositionMultiplier: 0.8


[leg_2]
x: 2
y: 0
attach_x: 1
attach_y: -1
copyFrom: 1

hidden: if self.hasParent()

[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm1_0.2s: {x:4, y:3, dir:20}
arm2_0.2s: {x:1, y:-1, dir:0}
arm3_0.2s: {x:-1, y:-1, dir:10}

arm4_0.2s: {x:7, y:3, dir:10}
arm5_0.2s: {x:0, y:0, dir:18}
arm6_0.2s: {x:1, y:1, dir:63}

arm1_9999s: {x:4, y:3, dir:20}
arm2_9999s: {x:1, y:-1, dir:0}
arm3_9999s: {x:-1, y:-1, dir:10}

arm4_9999s: {x:7, y:3, dir:10}
arm5_9999s: {x:0, y:0, dir:18}
arm6_9999s: {x:1, y:1, dir:63}
[animation_部署1]
arm1_0.4s: {x:0, y:0}
arm2_0.4s: {x:0, y:0}
arm3_0.4s: {x:0, y:0}
arm4_0.4s: {x:0, y:0}
arm5_0.4s: {x:0, y:0}
arm6_0.4s: {x:0, y:0}


[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 3
targetHeight: 2
turnAcceleration: 0.25
moveSlidingMode: false
reverseSpeedPercentage: 0
moveIgnoringBody: false


