


[core]
name: HK爬行者部署
displayText: HK ПолзунРазвернуть
class: CustomUnitMetadata
price: 550
maxHp: 140
displayDescription: -HK Ползун — это дальняя мина, разработанная Заревом, \n-Они умело размещают засады у дорог и узловых точек,, \n-используя свои ракеты, чтобы преподнести врагибольшой сюрприз.\n-только по земле, Нужно развернуться для атаки, взрывной урон.
techLevel: 1
buildSpeed: 0.035
radius: 12
showOnMinimapToEnemies: false
canOnlyBeAttackedByUnitsWithTags:主动扫雷
displayRadius: 12
isBio: false
tags: 地雷
transportSlotsNeeded: 99999

fogOfWarSightRange: 13
softCollisionOnAll: 1
showInEditor: false
energyMax: 1
energyRegen: 0.001

energyNeedsToRechargeToFull: true
canNotBeDamaged:true

[hiddenAction_打断]
autoTrigger:if self.hasParent
disconnectFromParent: true



[action_显示]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=300) and not self.tags(includes= '显示')
isVisible:false
temporarilyAddTags:显示
[action_显示1]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',lessThan=1,withInRange=300) and self.tags(includes= '显示')
isVisible:false
temporarilyRemoveTags:显示

[decal_光圈]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈a]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈b]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈c]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈1]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈2]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈3]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_地雷]
layer: afterBody
image: HK爬行者.png
onlyWhileAlive: true
isVisible:true
onlyTeam:own
teamColors: true
[decal_地雷1]
layer: afterBody
image: HK爬行者.png
onlyWhileAlive: true
isVisible:if self.tags(includes= '显示')
onlyTeam:enemy
teamColors: true
[action_起身]
convertTo: HK爬行者
displayType: action
price: 0
text: Встать
buildSpeed: 0.1s

whenBuilding_cannotMove: true


[action_t1]
autoTrigger: if self.isOverLiquid
isVisible: false
addResources: hp=-999999


[action_扫雷]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=50)  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)  or self.hasFlag(id=1)
deleteSelf: true
isVisible: false
[action_起身1]
convertTo: HK爬行者
displayType: action
price: 0
isVisible: false
autoTrigger: if not self.energy(full=true)

whenBuilding_cannotMove: true


[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE


image_shadow: NONE
dustEffect: false


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
canOnlyAttackUnitsWithoutTags: 扫雷,悬浮

turretSize: 10
turretTurnSpeed: 6
maxAttackRange: 215
shootDelay: 1


[turret_siloTop]
x: 0
y: 0
idleDir: 0
invisible: true
shoot_sound: nuke_launch

shoot_sound_vol: 0.27
shoot_light: #FFEECCCC
projectile: 1
size: 1
turnSpeed: 40

warmup: 80
energyUsage: 1


[projectile_1]
@copyFromSection: template_爆炸
life: 999
speed: 3
targetSpeed: 4
targetSpeedAcceleration: 4

largeHitEffect: true
ballistic: true
ballistic_height: 60
drawSize: 0.8
image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:爆炸,CUSTOM:气浪,CUSTOM:闪光,CUSTOM:烟雾3*3,CUSTOM:水波*1,CUSTOM:水花*1,CUSTOM:弹坑*1
targetGround: true
areaDamage: 800
alwaysVisibleInFog: true
deflectionPower: -1
areaRadius: 85
areaRadiusFromEdge: true
shouldRevealFog: true
lightColor: #FF4DD3F7
lightSize: 2.5

trailEffect: CUSTOM:projectileTrail
trailEffectRate: 4
mutator32_ifUnitWithTags: 悬浮
mutator32_directDamageMultiplier: 0
mutator32_areaDamageMultiplier: 0

[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6

drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2

image: ROOT:/余辉军团/单位特效/爆炸.png
total_frames: 13
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.2
alsoPlaySound: ROOT:/余辉军团/单位特效/激光炮音效.ogg
alwayStartDirAtZero: true


[effect_气浪]
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.5
alpha: 1
drawUnderUnits: false
atmospheric: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 2
drawUnderUnits: false

atmospheric: false


[effect_烟雾3]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true

attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 1.5
scaleTo: 3.5

alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true

hSpeed: 0.2
hOffsetRandom: 0.15
alsoPlaySound: ROOT:/余辉军团/单位特效/激光炮音效.ogg
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15

xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false


[effect_水花]
image: ROOT:/通用特效/水花.png
life: 160
fadeOut: true
attachedToUnit: false
color: #FFFFFF

fadeInTime: 4
scaleFrom: 0.05
scaleTo: 0.25
alpha: 0.6
drawUnderUnits: false

dirOffsetRandom: 0
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3

createWhenOverLiquid: true
createWhenOverLand: false


[effect_水波]
priority: critical
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.35
alpha: 1
drawUnderUnits: true
atmospheric: true

createWhenOverLiquid: true
createWhenOverLand: false


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1.4
scaleTo: 1.4


[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
targetHeight: -8
targetHeightDrift: 0
moveSlidingMode : true
moveIgnoringBody: true


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


