
[core]
name: 创世纪兵营t3
displayText: Казарма Генезисаt3
class: CustomUnitMetadata
price: 2050
maxHp: 4500
footprint: -3,-1,3,3
unitsSpawnedOnDeath:建筑损毁*1
constructionFootprint: -3,-1,3,3
techLevel: 1
armour: 10
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 35
isBio: false
buildSpeed: 7s
isBuilding: true
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆破*4,largeExplosion
exit_x: 0
exit_y: 20
nanoFactorySpeed:1
tags: 地面,建筑,兵营
displayDescription: 【Уровень t3】【Здание】【Наземный юнит】\n-Тактическое назначение: завод пехоты, без вооружения.\n-не может строиться на воде。Базовое здание подготовки пехоты Генезиса，\n-От рядовой пехоты до тяжёлых экзоскелетных бойцов Генезиса，вплоть до БМП，\n-развёртываются в таких типичных зданиях，и затем отправляются на поле боя。
canBuild_31_name: setRally
canBuild_31_pos: 0.1
[action_煅炉增益]
autoTrigger:if self.globalTeamTags(includes='纳米煅炉') and not self.tags(includes= '煅炉保险')
isActive: false
isVisible: false
temporarilyAddTags:煅炉保险
setUnitStats: nanoFactorySpeed=1.3
[canBuild_T1]
name: 苦工机器人,侦察兵,民兵,海军陆战队,机枪手,火箭炮兵,火焰喷射手,悍马
pos: 1
isVisible: if self.hasFlag(id=1)
[canBuild_T2]
name: 重装部队,迫击炮小队,狙击手,游侠机器人,人肉炸弹,瓦尔基里,反坦克炮小队,狼獾IFV,战马IFV
pos: 1
isVisible: if self.hasFlag(id=2)
[canBuild_T3]
name: 无畏战士,休克打击步兵,蜂刺导弹小组,特种部队,攻城锥IFV
pos: 1
isVisible: if self.hasFlag(id=3)
[canBuild_T33]
name: 火龙卷,机甲战士,角斗士
pos: 1
isVisible: if self.hasFlag(id=3)
isLocked: if not self.globalTeamTags(includes='材料技术1')
isLockedMessage: Требуется материаловедение 1
[action_T1]
pos: 0.1
buildSpeed: 0s
addResources: setFlag=0,setFlag=1
text: 显示t1юнит
isVisible: if not self.hasFlag(id=1) and not self.hasFlag(id=0)
[action_T1_back]
pos: 0.1
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=1
isVisible: if self.hasFlag(id=1)
text: 不显示t1юнит
[action_T2]
pos: 0.2
buildSpeed: 0s
addResources: setFlag=0,setFlag=2
text: 显示t2юнит
isVisible: if not self.hasFlag(id=2) and not self.hasFlag(id=0)
[action_T2_back]
pos: 0.2
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=2
isVisible: if self.hasFlag(id=2)
text: 不显示t2юнит
ai_isHighPriority: true
[action_T3]
pos: 0.3
buildSpeed: 0s
addResources: setFlag=0,setFlag=3
text: 显示t3юнит
isVisible: if not self.hasFlag(id=3) and not self.hasFlag(id=0)
highPriorityQueue: true
ai_isHighPriority: true
[action_T3_back]
pos: 0.3
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=3
isVisible: if self.hasFlag(id=3)
text: 不显示t3юнит
#——————————————
[action_MK1]
displayType: action
text: модульныйпроизводствоБесстрашный боец
price:800
pos: 1.1
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术')
produceUnits:无畏战士*2
buildSpeed: 5s
playAnimation: 开门

[action_MK2]
displayType: action
text: модульныйпроизводствоШок-пехотинец
price:1200
pos: 1.2
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术')
produceUnits:休克打击步兵*2
buildSpeed: 5s
playAnimation: 开门

[action_MK3]
displayType: action
text: модульныйпроизводствоРасчёт ракет «Жало»
price:2000
pos: 1.3
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术')
produceUnits:蜂刺导弹小组*2
buildSpeed: 12s
playAnimation: 开门

[action_MK4]
displayType: action
text: модульныйпроизводствоБоевой мех
price:1800
pos: 1.3
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术') and self.globalTeamTags(includes='材料技术1')
produceUnits:机甲战士*2
buildSpeed: 8s
playAnimation: 开门

[action_MK5]
displayType: action
text: модульныйпроизводствоОгненный смерч
price:1100
pos: 1.4
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术') and self.globalTeamTags(includes='材料技术1')
produceUnits:火龙卷*2
buildSpeed: 3s
playAnimation: 开门
[action_升级]
convertTo: 创世纪兵营t4
displayType: action
text: 升класс
price: 1500
buildSpeed: 15s
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
ai_isHighPriority: true
description:повышаетКазармауровень，самый大化其здание结构，и使其можетпроизводство阶классT4的пехотаюнит，\n-усиливаетКазармаимеет встроенныйпроизводство线与容量至самый高阶段，\n-这将使КазармаспособенразвёртыватьГенезис几乎всепехотаа также相关оборудование。
pos: 0.05

[graphics]
total_frames: 1
image: NO.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/死亡.png
image_back: 背景.png
image_shadow: 影.png

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0
[arm_1]
x: 29
y: -21
image_end: ROOT:/创世纪军事集团/建筑特效/右.png
image_end_teamColors: true
drawUnderAllUnits: true
[arm_2]
x: -29
y: -21
image_end: ROOT:/创世纪军事集团/建筑特效/左.png
image_end_teamColors: true
drawUnderAllUnits: true
[arm_3]
x: 0
y: 0
image_end: ROOT:/创世纪军事集团/建筑特效/遮盖.png
image_end_teamColors: true
drawUnderAllUnits: true
[arm_4]
x: 0
y: -21
image_end: ROOT:/创世纪军事集团/建筑特效/中.png
image_end_teamColors: true
[arm_5]
x: 0
y: 5
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_6]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_7]
x: 0
y: 2
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_8]
x: -10
y: 32
image_end: 箱子.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[animation_1]
onActions: queuedUnits
onActionsQueuedUnitPlayAt: 0.6
arm1_0s: {x:0, y:0}
arm1_0.6s: {x:0, y:-24}
arm1_900s: {x:0, y:-24}
arm2_0s: {x:0, y:0}
arm2_0.6s: {x:0, y:-24}
arm2_900s: {x:0, y:-24}
arm4_0s: {x:0, y:0}
arm4_0.6s: {x:0, y:25}
arm4_900s: {x:0, y:25}

[animation_开门]
arm1_0s: {x:0, y:0}
arm1_0.5s: {x:0, y:-24}
arm1_1s: {x:0, y:-24}
arm2_0s: {x:0, y:0}
arm2_0.5s: {x:0, y:-24}
arm2_1s: {x:0, y:-24}
arm4_0s: {x:0, y:0}
arm4_0.5s: {x:0, y:25}
arm4_1s: {x:0, y:25}
[animation_2]
onActions: idle
blendIn: 0.2s
blendOut: 0.2s
arm8_0s: {x:0, y:0}
arm8_1.3s: {x:19, y:0}
arm8_1.7s: {x:19, y:0}
arm8_2.3s: {x:0, y:0}
arm8_2.6s: {x:0, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
delayedStartTimerRandom:30

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 创世纪兵营t1
ai_upgradePriority: 0.07
buildPriority: 0.08
maxEachBase: 3
maxGlobal: 9

