


[core]
name: 雷烬天使战斗机
class: CustomUnitMetadata
displayDescription: -😡
price: 1
maxHp: 16500
techLevel: 1
buildSpeed: 0s
availableInDemo: true
showInEditor: false
fogOfWarSightRange: 28
armour: 35
radius: 35
displayRadius: 35
canOnlyBeAttackedByUnitsWithTags:反高空
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 35
energyMax: 60
energyRegen: 0
energyNeedsToRechargeToFull: true
tags: 飞机,高空,雷烬天使,寄生免疫,反高空,轨道炮,伴生单位
canNotBeGivenOrdersByPlayer: true
energyStartingPercentage: 1
logIfCreditResourceUsed: true
effectOnDeath:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
effectOnDeathGroundCollision:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
[hiddenAction_有轨道]
autoTrigger: if self.globalTeamTags(includes='lg轨道炮') and self.hasParent 
temporarilyAddTags: 轨道炮
temporarilyRemoveTags:火箭,幻象
[hiddenAction_有火箭]
autoTrigger: if self.globalTeamTags(includes='lg火箭') and self.hasParent 
temporarilyAddTags: 火箭
temporarilyRemoveTags:幻象,轨道炮
[hiddenAction_有幻象]
autoTrigger: if self.globalTeamTags(includes='lg幻象') and self.hasParent 
temporarilyAddTags: 幻象
temporarilyRemoveTags:轨道炮,火箭
[action_高空]
text: 高空单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的战机和战舰。\n-在此高度下，只有地面和空中特殊的反高空单位，以及高空单位才能攻击到该单位，\n-同时，大部分高空单位可以互相攻击，并可以攻击普通空中单位，\n-只有特殊的高空单位才能对地攻击。

[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'


[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'


[hiddenAction_return1]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( self.isEnergyRecharging or distanceBetweenSquared(self, customTarget1) > 3500* 3500 )
# distanceBetweenSquared 返回两个单位之间的平方距离。 比 distanceBetween 快一点，因为少了开方这一步。1100² 判断灰机离母体有多远，超过1100回家
clearActiveWaypoint: true
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own

addWaypoint_type: loadInto


[hiddenAction_disconnect]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( not self.hasActiveWaypoint(type= 'attack') or activeWaypointTarget.height < 10)
disconnectFromParent: true
clearActiveWaypoint: true
addWaypoint_type: attack
addWaypoint_prepend: true

addWaypoint_target_fromReference: customTarget1.attacking
#addWaypoint_triggerActionIfMatched: 补丁
addWaypoint_triggerActionIfFailed: return1





[hiddenAction_energy]
autoTriggerOnEvent: enteredTransport
addEnergy: 60





[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
# 这条在鹰爪和雪崩里忘改成这样了，原本是打算航母凉后灰机用完能量才自杀，不过有bug忘了改回来
addResources: hp= -999999



[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[graphics]
total_frames: 1
image: 机体.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 0.8
image_shadow: AUTO
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2
[attack]
canAttack:true
canAttackFlyingUnits: if self.isInMap
canAttackLandUnits: false

canAttackUnderwaterUnits: false
turretSize: 20
maxAttackRange: 1250
attackMovement: bomber
[turret_1]
x: 19
y: 2
canShoot: true
invisible:true
shoot_sound: ROOT:/通用特效/中轨道炮.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾*2

limitingAngle: 15
delay: 40
size:10
projectile: 1
canAttackLandUnits:false
energyUsage:1
canAttackCondition: if self.tags(includes= '轨道炮')
limitingRange: 650

[turret_2]
x: -19
y: 2
copyFrom: 1
linkDelayWithTurret:1
delay:35
warmup:5
[turret_3]
x: 21
y: 2
canShoot: true
invisible:true
shoot_sound: ROOT:/通用特效/连射.wav
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾*2
limitingAngle: 15
delay: 10
size:3
projectile: 2
canAttackLandUnits:false
canOnlyAttackUnitsWithTags:高空
energyUsage:0.5
canAttackCondition: if self.tags(includes= '火箭')
limitingRange: 650
[turret_4]
x: -21
y: 2
copyFrom: 3
[turret_5]
x: 21
y: 2
canShoot: true
invisible:true
shoot_sound: ROOT:/通用特效/连射.wav
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾*2
limitingAngle: 15
delay: 10
size:3
projectile: 3
canAttackLandUnits:false
canOnlyAttackUnitsWithoutTags:高空
energyUsage:0.5
canAttackCondition: if self.tags(includes= '火箭')
limitingRange: 650
[turret_6]
x: -21
y: 2
copyFrom: 5
[turret_7]
x: -21
y: -2
canShoot: true
projectile: 4
canOnlyAttackUnitsWithTags:高空
shoot_sound: ROOT:/通用特效/新导弹发射.wav
shoot_sound_vol: 0.8
shoot_flame: CUSTOM:烟雾*5
shoot_light: #FFEECCCC
size: 3
delay: 200
invisible:true
energyUsage:30
canAttackCondition: if self.tags(includes= '幻象')
[turret_8]
x: 21
y: 2
copyFrom: 7
delay: 170
warmup:30
[turret_9]
x: -21
y: -2
canShoot: true
projectile: 5
canOnlyAttackUnitsWithoutTags:高空
shoot_sound: ROOT:/通用特效/新导弹发射.wav
shoot_sound_vol: 0.8
shoot_flame: CUSTOM:烟雾*5
shoot_light: #FFEECCCC
size: 3
delay: 200
invisible:true
energyUsage:30
canAttackCondition: if self.tags(includes= '幻象')
[turret_10]
x: 21
y: 2
copyFrom: 9
delay: 170
warmup:30
[projectile_1]
@copyFromSection: template_动能
directDamage: 445
life: 200
speed: 9
image: ROOT:/太空浪人/单位特效/光.png
targetSpeed: 9
drawSize: 0.45
explodeEffect: CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:光子gd*4,CUSTOM:冲击波gd,CUSTOM:爆炸2gd,CUSTOM:穿透gd
explodeEffectOnShield: CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:光子gd*4,CUSTOM:冲击波gd,CUSTOM:爆炸2gd,CUSTOM:穿透gd
lightSize: 0.75
trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
lightColor: #FFFF1200
armourIgnoreAmount: 10
shieldDamageMultiplier: 1.2
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 1.5
mutator7_areaDamageMultiplier: 1.5
[projectile_2]
@copyFromSection: template_爆炸
speedSpread:1
areaDamage: 450
areaRadius: 55
life: 180
targetGroundSpread: 45
speed: 9
frame:8
drawSize: 0.85
deflectionPower: -1
explodeEffect: CUSTOM:爆炸hj, CUSTOM:闪光hj, CUSTOM:冲击波hj
targetGroundHeightOffset:140
targetGround:true
#speedSpread:1
areaRadiusFromEdge: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
disableLeadTargeting: true
trailEffectRate: 0.3
trailEffect: CUSTOM:火3
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
mutator7_ifUnitWithoutTags: 极端重型
mutator7_directDamageMultiplier: 1.5
mutator7_areaDamageMultiplier: 1.5
[projectile_3]
@copyFromSection:projectile_2
targetGroundHeightOffset:70
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_4]
@copyFromSection: template_爆炸
areaDamage: 1350
areaRadiusFromEdge: true
areaRadius: 90
deflectionPower: -1
life: 600
speed: 12
image: 大导弹1.png
targetSpeed: 14
drawSize:0.8
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
explodeEffectOnShield: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
trailEffect:true
trailEffectRate: 0.65
turnSpeed: 3
spawnUnit: 幻象导弹中介(offsetHeight=140,offsetDir=0)
[projectile_5]
@copyFromSection: template_爆炸
areaDamage: 1350
areaRadiusFromEdge: true
areaRadius: 90
deflectionPower: -1
life: 600
speed: 12
image: 大导弹1.png
targetSpeed: 14
drawSize:0.8
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
explodeEffectOnShield: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
trailEffect:true
trailEffectRate: 0.65
turnSpeed: 3
spawnUnit: 幻象导弹中介(offsetHeight=70,offsetDir=0,addResources=空:1)
#————————尾焰
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: -5
ySpeedRelative: -2
yOffsetRelative	: -34
drawUnderUnits: false
[effect_火2]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 5
ySpeedRelative: -2
yOffsetRelative	: -34
drawUnderUnits: false
[effect_火3]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.9
color: #FFFFA920
ySpeedRelative: -2.5
yOffsetRelative	: 0
drawUnderUnits: false

[arm_1]
x: 0
y: 0
image_end: 机体.png
drawOverBody: true
image_end_teamColors: true

[arm_2]
x: 19
y: -2
image_end: 轨道炮.png
image_end_teamColors: true
hidden:if not self.tags(includes= '轨道炮')
[arm_3]
x: -19
y: -2
image_end: 轨道炮.png
image_end_teamColors: true
hidden:if not self.tags(includes= '轨道炮')
[arm_4]
x: 0
y: -4
image_end: 火箭弹.png
image_end_teamColors: true
hidden:if not self.tags(includes= '火箭')
#———————————————轨道炮
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
[effect_爆炸2gd]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9
color: #FFFF1200
[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 15
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.25
scaleTo: 0.25
alpha: 0.7
drawUnderUnits: false
[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.43
scaleTo: 0.43
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_闪光gd]
priority:low
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3
drawUnderUnits: true
atmospheric: false
[effect_光子gd]
spawnChance: 0.8
createWhenZoomedOut: false
life: 50
priority: low
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7
ySpeedRelativeRandom: 3.7
[effect_冲击波gd]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.65
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_穿透gd]
image: ROOT:/创世纪军事集团/单位特效/子弹.png
life: 30
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.22
scaleTo: 0.02
alpha: 1
drawUnderUnits: false
ySpeedRelative: 8.5
atmospheric: false
#————————
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/巨大爆炸.ogg
createWhenOffscreen: true
#————————————火箭炮
[effect_闪光hj]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false

atmospheric: false


[effect_爆炸hj]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.4
scaleTo: 1.4

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
[effect_冲击波hj]
stripIndex: shockwave
life: 20
scaleFrom: 0.3
scaleTo: 3
alpha: 1
#——————————————幻象导弹
#——————————————————炸
[effect_爆炸hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.44
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/重型爆炸.wav
alwayStartDirAtZero: true
[effect_爆炸hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/12.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.21
alwayStartDirAtZero: true
[effect_闪光hx]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 8
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.85
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[movement]
movementType: AIR
moveSpeed: 5.5
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.01
#landOnGround: onlyIdle

targetHeight: 140
targetHeightDrift: 2
maxTurnSpeed: 2.5
turnAcceleration: 0.2
startingHeightOffset: 1000
moveSlidingMode : true
moveIgnoringBody: false
slowDeathFall: true

[resource_空]
displayName: 空
displayNameShort: 空
displayColor: #FF9D00FF
priority: 1
hidden: true

