
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=500
[core]
name:艾斯兰佩萨1
displayText: Эсланпеса 1
price: 7800,蓝晶=660
maxHp: 5000
maxShield: 10000
shieldRenderRadius: 0
shieldRegen: 0.1
showInEditor:false
displayDescription: 【Уровень t4】【Иммунитет к шоку】【Беспилотный юнит】【Механический юнит】【Наземный юнит】【Преодолевает утёсы】\n-тактическое назначение: универсальный антиединичный мех, размер юнита:10, вооружение:\n-▲плазменная винтовка точного боя энергетический урон только по земле только в режиме меха.\n-▲ракета «воздух-воздух»X6 взрывной урон только по воздуху только в режиме истребителя.\n-▲излучатель плазменного потока энергетический урон только по воздуху только в режиме истребителя.\n-Эсланпесаэто от Малкольм Рейнблизкийсамдля Империяморская пехотабитьстроить  войнамашинаустройство, это Империя Новасухопутные войскав  абсолютныйпротив  основная сила, \n-может сказать, Эсланпеса выходит текущийэто против планетарный штурмтактический большой перетасовать, \n-Этот основноймеховможет в боймашина и мехов междупреобразованиеформа, \n-поэтомуможет прямоиз полётматьна выходит выпустить, внезапновходит вражескийпланетавыполняет боевой.\n-Эсланпесаможет в чистыйкромевражескийвоздушныйв цельпослебыстрыйизменитьформападение , \n-использоватьиспользует рукав  лучстрелокшагоружиеснаряднет пустойвыпустить уничтожитьвраги.\n-ммнет вопрос, Эсланпесатогдаэто Империяморская пехотав самыйострый меч, \n-онв один разразвойнав для Империяуничтожитьнет количество враги.
techLevel: 1
fogOfWarSightRange: ${int(attack.maxAttackRange/17.5)}
buildSpeed: 17s
radius: 85
displayRadius: 85
armour: 30
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:中余晖单位死亡冲击波,CUSTOM:中余晖单位死亡爆炸,CUSTOM:中余晖单位死亡钢珠,CUSTOM:中余晖单位死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:6)
transportSlotsNeeded: 10
tags: 地面,无人单位
energyMax: 80
energyRegen: 0.38
energyNeedsToRechargeToFull: true
#————————————————影子
[decal_影子]
image: SHADOW:左手1.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_1
[decal_影子1]
image: SHADOW:右手1.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_2

[decal_影子2]
image: SHADOW:枪.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_3

[decal_主体影子]
image: SHADOW:主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_11
[decal_前盖影子]
image: SHADOW:前盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:3
xOffsetRelative:3
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_13

[decal_左翼影子]
image: SHADOW:左翼.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_5
[decal_右翼影子]
image: SHADOW:右翼.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_6
#————————————————全覆盖
[decal_枪led]
image: LED1.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_3
[decal_左前覆盖]
image: 左前.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_7
teamColors: true
[decal_右前覆盖]
image: 右前.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_8
teamColors: true
[decal_左引擎覆盖]
image: 左引擎.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_9
teamColors: true
[decal_右引擎覆盖]
image: 右引擎.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_10
teamColors: true
[decal_主体覆盖]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_11
teamColors: true
[decal_主体led]
image: LED.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_11
[decal_脑袋影子]
image: SHADOW:脑袋.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.6
basePositionFromLegEnd: arm_12
[decal_脑袋覆盖]
image: 脑袋.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_12
teamColors: true
[decal_脑袋LED]
image: LED2.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_12
alpha:0.8
[decal_前盖覆盖]
image: 前盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_13
teamColors: true
[decal_后盖覆盖]
image: 后盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_14
teamColors: true
[decal_左覆盖]
image: 左.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_15
teamColors: true
[decal_右覆盖]
image: 右.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_16
teamColors: true
[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:12
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1.2
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 750 | setFlag= 0-1)
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999

[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", greaterThan= 0.5) and self.queueSize< 0.5 
isVisible: false
alsoQueueAction: b

[action_b]
convertTo: 艾斯兰佩萨
displayType: action
price: 0
buildSpeed: 0.42s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed
temporarilyRemoveTags:变形1

[action_起飞]
displayType: action
price: 0
buildSpeed: 0s
isVisible: if not self.tags(includes= '变形1')
text: изменить типстать истребитель
iconImage: 飞机.png
isLocked: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.queueSize> 0.5
alsoQueueAction: 延时
highPriorityQueue: true
description: изменить типстать истребительсостояние, изменить типпозади , Эсланпесабудетповоротдля обычныйвоздушныйв юнит, \n-в истребительсостояниепод может по воздухув юнитвыполняетатака.
whenBuilding_cannotMove: true
temporarilyAddTags:变形1
stopLastAnimation: true
[hiddenAction_延时]
buildSpeed: 1s
alsoQueueAction: b
highPriorityQueue: false
stopLastAnimation: true
temporarilyAddTags:该变形了
[graphics]
image: NO.png
image_wreak: 主体死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
#imageScale: 0.85
showEnergyBar:false
showQueueBar: false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 650
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: true
aimOffsetSpread: -0.01
turretMultiTargeting: false
[turret_1]
x: 27
y: 72
invisible: true
size:70
canShoot: true
shoot_sound: ROOT:/余辉军团/单位特效/大开火.wav
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:小闪光,CUSTOM:冲击波,CUSTOM:烟雾*5,CUSTOM:光子*8
projectile:1
delay:80
canAttackFlyingUnits: false
attachedTo: 3
slave: true
onShoot_playAnimation: attack
canAttackCondition: if not self.tags(includes= '变形1')
limitingMinRange: 150
[turret_2]
x: 44
y: 120
attachedTo: 3
projectile: 2
slave: true
delay: 1
canShoot: true
invisible: true
canAttackCondition: if not self.tags(includes= '变形1')
limitingMinRange: 150
[turret_3]
x: 0
y: 0
canShoot: false
limitingMinRange: 150
invisible: true
[projectile_1]
@copyFromSection: template_能源
directDamage: 2850
life: 200
speed: 14
image: ROOT:/余辉军团/单位特效/电磁炮.png
drawSize: 0.75
explodeEffect: CUSTOM:大闪光,CUSTOM:聚变,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:炸了,CUSTOM:蓝色光*10
explodeEffectOnShield:CUSTOM:大闪光,CUSTOM:聚变,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:炸了,CUSTOM:蓝色光*10
lightSize: 2
trailEffectRate: 0.25
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1,CUSTOM:尾巴2
lightColor: #FF00B3FF
[projectile_2]
directDamage: 0
life: -4
instant: true
frame: 33
beamImage: 光.png

beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
color: #FF00B3FF
explodeEffect: none
[arm_1]
x: 54
y: 46
image_end: 左手1.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 55
moveSpeed:13
[arm_2]
x: -14
y: 35
image_end: 右手1.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -30
moveSpeed:13
[arm_3]
x: 31
y: 72
image_end: 枪.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -4
moveSpeed:13
[arm_4]
x: 0
y: 0
image_end: 尾巴.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20

[arm_5]
x: 0
y: 0
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_6]
x: 0
y: 0
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20

[arm_7]
x: 0
y: 0
image_end: 左前.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_8]
x: 0
y: 0
image_end: 右前.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset:20
[arm_9]
x: 0
y: 0
image_end: 左引擎.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_10]
x: 0
y: 0
image_end: 右引擎.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_11]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_12]
x: 0
y: 0
image_end: 脑袋.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
[arm_13]
x: 0
y: 0
image_end: 前盖.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_14]
x: 0
y: 0
image_end: 后盖.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 20
[arm_15]
x: 0
y: 0
image_end: 左.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:13
drawDirOffset: 20
[arm_16]
x: 0
y: 0
image_end: 右.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:13
drawDirOffset:20


[animation_部署]
KeyframeTimeScale:0.7
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}
arm15_0s: {x:0, y:0, dir:0}
arm16_0s: {x:0, y:0, dir:0}

arm1_0.6s: {x:-43, y:2, dir:-25}
arm2_0.6s: {x:4, y:-2, dir:0}
arm3_0.6s: {x:-31, y:-10, dir:-66}
arm4_0.6s: {x:0, y:0, dir:-20}
arm5_0.6s: {x:2, y:15, dir:-30}
arm6_0.6s: {x:-2, y:15, dir:-10}
arm7_0.6s: {x:0, y:-12, dir:-10}
arm8_0.6s: {x:0, y:-12, dir:-30}
arm9_0.6s: {x:0, y:0, dir:-20}
arm10_0.6s: {x:0, y:0, dir:-20}
arm11_0.6s: {x:0, y:0, dir:-20}
arm12_0.6s: {x:0, y:0, dir:0}
arm13_0.6s: {x:0, y:0, dir:-20}
arm14_0.6s: {x:0, y:0, dir:-20}
arm15_0.6s: {x:-8, y:-30, dir:10}
arm16_0.6s: {x:8, y:-30, dir:-50}


[leg_1]
x: -26
y: 14
attach_x: -1
attach_y: -1
moveSpeed: 3

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png
hidden:if self.height(greaterThan=5)
image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 25

holdDisMax: 50



[leg_2]
x: 26
y: 14
attach_x: 1
attach_y: -1
copyFrom: 1

drawDirOffset: 10
[animation_attack]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm1_0.1s: {x:0, y:-10, dir:0}
arm2_0.1s: {x:0, y:-10, dir:0}
arm3_0.1s: {x:0, y:-15, dir:0}

#——————————————开火特效
[effect_小闪光]
priority:low
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_冲击波]
stripIndex: shockwave
life: 45
scaleFrom: 0.2
scaleTo: 3.5
alpha: 1
color: #FF00B3FF
[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 60
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.7
scaleTo: 0.7
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 1
ySpeedRelative: 2
ySpeedRelativeRandom: 0.5
[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1
scaleTo: 2.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.65
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true

#——————————尾巴
[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/光束3.png
life: 24
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
drawUnderUnits: false
[effect_尾巴1]
image: ROOT:/余辉军团/单位特效/冲击.png
spawnChance: 1
createWhenZoomedOut: false
life: 17
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.08
scaleTo: 0.37
alpha: 0.8
drawUnderUnits: false
yOffsetRelative: 18
liveAfterAttachedDies: false
atmospheric: false
[effect_尾巴2]
priority: veryhigh
image: SHARED:light_50.png
life: 25
fadeOut: true
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.6
scaleTo: 0.6
alpha: 1
drawUnderUnits: true

#——————————————命中特效
[effect_炸了]
life:70
frame_width:296
frame_height:300
priority: critical
image: ROOT:/余辉军团/单位特效/暴暴.png
dirOffsetRandom:360
fadeInTime:0
fadeOut: false
attachedToUnit:false
scaleFrom:0.8
scaleTo:1.2
total_frames:16
animateFrameStart:0
animateFrameEnd:15
animateFramePingPong: false
animateFrameSpeed:0.3
alpha:2
createWhenOffscreen: true
alsoPlaySound: ROOT:/通用特效/巨大爆炸.ogg
[effect_大闪光]
image: SHARED:light_50.png
life:40
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 2
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true

[effect_冲击波nk]
priority: high
image: ROOT:/余辉军团/单位特效/超级冲击波1.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 1.2
alpha: 1.2
drawUnderUnits: true
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_冲击波nk1]
life: 75
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.4
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true

[effect_蓝色光]
spawnChance: 0.8
priority: verylow
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: false
fadeInTime: 20
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.6
scaleTo: 0.6
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 4
ySpeedRelativeRandom: 4
atmospheric: true
[movement]
movementType: OVER_CLIFF
moveSpeed: 0.9
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 1.5

turnAcceleration: 0.08
targetHeight: 2
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0
slowDeathFall: true





