

[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=500
[core]
name:艾斯兰佩萨
displayText: Эсланпеса
price: 7800,蓝晶=660
maxHp: 5000
maxShield: 10000
shieldRenderRadius: 0
shieldRegen: 0.1
displayDescription: 【Уровень t4】【Иммунитет к шоку】【Беспилотный юнит】【Механический юнит】【Наземный юнит】【Преодолевает утёсы】\n-тактическое назначение: универсальный антиединичный мех, размер юнита:10, вооружение:\n-▲плазменная винтовка точного боя энергетический урон только по земле только в режиме меха.\n-▲ракета «воздух-воздух»X6 взрывной урон только по воздуху только в режиме истребителя.\n-▲излучатель плазменного потока энергетический урон только по воздуху только в режиме истребителя.\n-Эсланпесаэто от Малкольм Рейнблизкийсамдля Империяморская пехотабитьстроить  войнамашинаустройство, это Империя Новасухопутные войскав  абсолютныйпротив  основная сила, \n-может сказать, Эсланпеса выходит текущийэто против планетарный штурмтактический большой 洗牌, \n-Этот основноймеховможет в боймашина и мехов междупреобразованиеформа, \n-поэтомуможет прямоиз полётматьна выходит выпустить, внезапновходит вражескийпланетавыполняет боевой.\n-Эсланпесаможет в чистыйкромевражескийвоздушныйв цельпослебыстрыйизменитьформападение , \n-использоватьиспользует рукав  лучстрелокшагоружиеснаряднет 虚выпустить уничтожитьвраги.\n-ммнет вопрос, Эсланпесатогдаэто Империяморская пехотав самый锋利 宝剑, \n-онв один разразвойнав для Империяуничтожитьнет количество враги.
techLevel: 1
fogOfWarSightRange: ${int(attack.maxAttackRange/17.5)}
buildSpeed: 17s
radius: 85
displayRadius: 85
armour: 30
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:中余晖单位死亡冲击波,CUSTOM:中余晖单位死亡爆炸,CUSTOM:中余晖单位死亡钢珠,CUSTOM:中余晖单位死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:6)
transportSlotsNeeded: 10
tags: 地面,无人单位
energyMax: 80
energyRegen: 0.38
energyNeedsToRechargeToFull: true
#————————————————影子
[decal_影子]
image: SHADOW:左手1.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_1
[decal_影子1]
image: SHADOW:右手1.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_2

[decal_影子2]
image: SHADOW:枪.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_3

[decal_主体影子]
image: SHADOW:主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_11
[decal_前盖影子]
image: SHADOW:前盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:3
xOffsetRelative:3
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_13

[decal_左翼影子]
image: SHADOW:左翼.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_5
[decal_右翼影子]
image: SHADOW:右翼.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_6
#————————————————全覆盖
[decal_枪led]
image: LED1.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_3
[decal_左前覆盖]
image: 左前.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_7
teamColors: true
[decal_右前覆盖]
image: 右前.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_8
teamColors: true
[decal_左引擎覆盖]
image: 左引擎.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_9
teamColors: true
[decal_右引擎覆盖]
image: 右引擎.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_10
teamColors: true
[decal_主体覆盖]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_11
teamColors: true
[decal_主体led]
image: LED.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_11
[decal_脑袋影子]
image: SHADOW:脑袋.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.6
basePositionFromLegEnd: arm_12
[decal_脑袋覆盖]
image: 脑袋.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_12
teamColors: true

[decal_脑袋LED]
image: LED2.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_12
alpha:0.8
[decal_前盖覆盖]
image: 前盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_13
teamColors: true
[decal_后盖覆盖]
image: 后盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_14
teamColors: true
[decal_左覆盖]
image: 左.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_15
teamColors: true
[decal_右覆盖]
image: 右.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_16
teamColors: true
[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:12
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1.2
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 750 | setFlag= 0-1)
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true

[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[hiddenAction_等会]
autoTrigger: if self.tags(includes= '等会') and not self.tags(includes= '保险丝')
alsoQueueAction: 等
temporarilyAddTags:保险丝
[action_等]
price: 0
buildSpeed: 1.2s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags:等会,保险丝

[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5) and not self.tags(includes= '等会') and not self.tags(includes= '该变形了') and not self.tags(includes= '变形1')
isVisible: false
alsoQueueAction: b
stopLastAnimation: true



[action_b]
convertTo: 艾斯兰佩萨1
displayType: action
price: 0
buildSpeed: 0.42s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed


[action_起飞]
autoTrigger: if self.tags(includes= '该变形了') and not self.tags(includes= '变形1')
displayType: action
price: 0
buildSpeed: 0s
isVisible: if not self.tags(includes= '变形1')
iconImage: 飞机.png
text: изменить типстать истребитель
isLocked: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.tags(includes= '等会') or self.queueSize> 0.5
alsoQueueAction: bx1
highPriorityQueue: true
description: изменить типстать истребительсостояние, изменить типпозади , Эсланпесабудетповоротдля обычныйвоздушныйв юнит, \n-в истребительсостояниепод может по воздухув юнитвыполняетатака.
whenBuilding_cannotMove: true
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
temporarilyAddTags:变形1
[action_bx1]
convertTo: 艾斯兰佩萨2
displayType: action
price: 0
buildSpeed: 4s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 变型
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
temporarilyRemoveTags:变形1,地面,该变形了
temporarilyAddTags:飞机,低空


[graphics]
image: NO.png
image_wreak: 主体死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
#imageScale: 0.85
showEnergyBar:false
showQueueBar: false
[attack]
canAttack:true
canAttackFlyingUnits: false
canAttackLandUnits: if not self.tags(includes= '等会')
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 650
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: true

turretMultiTargeting: false
[turret_233]
x: 0
y: 0
projectile: 233
delay: 1s
canAttackMaxAngle: 181
warmup:1.5s
invisible: true
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[arm_1]
x: 13
y: 48
image_end: 左手1.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 30
moveSpeed:13
[arm_2]
x: -10
y: 33
image_end: 右手1.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -30
moveSpeed:13
[arm_3]
x: 0
y: 62
image_end: 枪.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -70
moveSpeed:13
[arm_4]
x: 0
y: 0
image_end: 尾巴.png
image_end_teamColors: true
drawOverBody: true
#drawDirOffset: 145
[arm_5]
x: 2
y: 15
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -10
[arm_6]
x: -2
y: 15
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 10
[arm_7]
x: 0
y: -12
image_end: 左前.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:13
drawDirOffset: 10
[arm_8]
x: 0
y: -12
image_end: 右前.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:13
drawDirOffset: -10
[arm_9]
x: 0
y: 0
image_end: 左引擎.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
[arm_10]
x: 0
y: 0
image_end: 右引擎.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
[arm_11]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
[arm_12]
x: 0
y: 0
image_end: 脑袋.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
[arm_13]
x: 0
y: 0
image_end: 前盖.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
[arm_14]
x: 0
y: 0
image_end: 后盖.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
[arm_15]
x: -8
y: -30
image_end: 左.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:13
drawDirOffset: 30
[arm_16]
x: 8
y: -30
image_end: 右.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:13
drawDirOffset: -30
[leg_1]
x: -26
y: 14
attach_x: -1
attach_y: -1
moveSpeed: 3

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png
hidden:if self.height(greaterThan=5)
image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 25

holdDisMax: 50



[leg_2]
x: 26
y: 14
attach_x: 1
attach_y: -1
copyFrom: 1

drawDirOffset: 10

[animation_部署]
KeyframeTimeScale:0.7
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}
arm15_0s: {x:0, y:0, dir:0}
arm16_0s: {x:0, y:0, dir:0}

arm1_0.6s: {x:47, y:-2, dir:25}
arm2_0.6s: {x:-4, y:2, dir:0}
arm3_0.6s: {x:31, y:10, dir:66}
arm4_0.6s: {x:0, y:0, dir:20}
arm5_0.6s: {x:-2, y:-15, dir:30}
arm6_0.6s: {x:2, y:-15, dir:10}
arm7_0.6s: {x:0, y:12, dir:10}
arm8_0.6s: {x:0, y:12, dir:30}
arm9_0.6s: {x:0, y:0, dir:20}
arm10_0.6s: {x:0, y:0, dir:20}
arm11_0.6s: {x:0, y:0, dir:20}
arm12_0.6s: {x:0, y:0, dir:0}
arm13_0.6s: {x:0, y:0, dir:20}
arm14_0.6s: {x:0, y:0, dir:20}
arm15_0.6s: {x:8, y:30, dir:-10}
arm16_0.6s: {x:-8, y:30, dir:50}

[animation_变型]

arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}
arm15_0s: {x:0, y:0, dir:0}
arm16_0s: {x:0, y:0, dir:0}

arm1_0.6s: {x:0, y:0, dir:0}
arm2_0.6s: {x:0, y:0, dir:0}
arm3_0.6s: {x:0, y:0, dir:0}
arm4_0.6s: {x:0, y:0, dir:0}
arm5_0.6s: {x:-2, y:-15, dir:10}
arm6_0.6s: {x:2, y:-15, dir:-10}
arm7_0.6s: {x:0, y:12, dir:-10}
arm8_0.6s: {x:0, y:12, dir:10}
arm9_0.6s: {x:0, y:0, dir:0}
arm10_0.6s: {x:0, y:0, dir:0}
arm11_0.6s: {x:0, y:0, dir:0}
arm12_0.6s: {x:0, y:0, dir:0}
arm13_0.6s: {x:0, y:-25, dir:0}
arm14_0.6s: {x:0, y:24, dir:0}
arm15_0.6s: {x:8, y:30, dir:-30}
arm16_0.6s: {x:-8, y:30, dir:30}

arm1_1.2s: {x:10, y:0, dir:10}
arm2_1.2s: {x:-13, y:15, dir:-10}
arm3_1.2s: {x:0, y:0, dir:70}
arm4_1.2s: {x:0, y:0, dir:0}
arm5_1.2s: {x:-2, y:-15, dir:10}
arm6_1.2s: {x:2, y:-15, dir:-10}
arm7_1.2s: {x:0, y:12, dir:-10}
arm8_1.2s: {x:0, y:12, dir:10}
arm9_1.2s: {x:0, y:0, dir:0}
arm10_1.2s: {x:0, y:0, dir:0}
arm11_1.2s: {x:0, y:0, dir:0}
arm12_1.2s: {x:0, y:0, dir:0}
arm13_1.2s: {x:0, y:-25, dir:0}
arm14_1.2s: {x:0, y:24, dir:0}
arm15_1.2s: {x:8, y:30, dir:-30}
arm16_1.2s: {x:-8, y:30, dir:30}

arm1_1.8s: {x:15, y:-20, dir:10}
arm2_1.8s: {x:-18, y:-5, dir:-10}
arm3_1.8s: {x:0, y:-32, dir:70}
arm4_1.8s: {x:0, y:-42, dir:0}
arm5_1.8s: {x:-2, y:-15, dir:10}
arm6_1.8s: {x:2, y:-15, dir:-10}
arm7_1.8s: {x:0, y:12, dir:-10}
arm8_1.8s: {x:0, y:12, dir:10}
arm9_1.8s: {x:-4, y:-20, dir:0}
arm10_1.8s: {x:4, y:-20, dir:0}
arm11_1.8s: {x:0, y:0, dir:0}
arm12_1.8s: {x:0, y:0, dir:0}
arm13_1.8s: {x:0, y:-25, dir:0}
arm14_1.8s: {x:0, y:24, dir:0}
arm15_1.8s: {x:8, y:30, dir:-30}
arm16_1.8s: {x:-8, y:30, dir:30}

arm1_2.6s: {x:15, y:-20, dir:10}
arm2_2.6s: {x:-18, y:-5, dir:-10}
arm3_2.6s: {x:0, y:-32, dir:70}
arm4_2.6s: {x:0, y:-42, dir:0}
arm5_2.6s: {x:18, y:20, dir:10}
arm6_2.6s: {x:-18, y:20, dir:-10}
arm7_2.6s: {x:40, y:12, dir:-10}
arm8_2.6s: {x:-40, y:12, dir:10}
arm9_2.6s: {x:-4, y:-20, dir:0}
arm10_2.6s: {x:4, y:-20, dir:0}
arm11_2.6s: {x:0, y:0, dir:0}
arm12_2.6s: {x:0, y:0, dir:0}
arm13_2.6s: {x:0, y:-25, dir:0}
arm14_2.6s: {x:0, y:24, dir:0}
arm15_2.6s: {x:50, y:30, dir:-30}
arm16_2.6s: {x:-50, y:30, dir:30}

arm1_3.2s: {x:15, y:-20, dir:10}
arm2_3.2s: {x:-18, y:-5, dir:-10}
arm3_3.2s: {x:0, y:-32, dir:70}
arm4_3.2s: {x:0, y:-42, dir:0}
arm5_3.2s: {x:18, y:20, dir:10}
arm6_3.2s: {x:-18, y:20, dir:-10}
arm7_3.2s: {x:40, y:12, dir:-10}
arm8_3.2s: {x:-40, y:12, dir:10}
arm9_3.2s: {x:-4, y:-20, dir:0}
arm10_3.2s: {x:4, y:-20, dir:0}
arm11_3.2s: {x:0, y:0, dir:0}
arm12_3.2s: {x:0, y:0, dir:0}
arm13_3.2s: {x:0, y:-25, dir:0}
arm14_3.2s: {x:0, y:24, dir:0}
arm15_3.2s: {x:50, y:90, dir:-30}
arm16_3.2s: {x:-50, y:90, dir:30}

arm1_4s: {x:15, y:-20, dir:10}
arm2_4s: {x:-18, y:-5, dir:-10}
arm3_4s: {x:0, y:-32, dir:70}
arm4_4s: {x:0, y:-42, dir:0}
arm5_4s: {x:18, y:20, dir:10}
arm6_4s: {x:-18, y:20, dir:-10}
arm7_4s: {x:40, y:127, dir:-10}
arm8_4s: {x:-40, y:127, dir:10}
arm9_4s: {x:-4, y:-20, dir:0}
arm10_4s: {x:4, y:-20, dir:0}
arm11_4s: {x:0, y:0, dir:0}
arm12_4s: {x:0, y:0, dir:0}
arm13_4s: {x:0, y:-25, dir:0}
arm14_4s: {x:0, y:24, dir:0}
arm15_4s: {x:50, y:90, dir:-30}
arm16_4s: {x:-50, y:90, dir:30}

[movement]
movementType: OVER_CLIFF
moveSpeed: 0.9
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 1.5

turnAcceleration: 0.08
targetHeight: 2
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0
slowDeathFall: true


