
[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}
[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}


[core]
name: AI核心作战中枢t3
class: CustomUnitMetadata
price: 18000
maxHp: 15000
maxShield: 15000
shieldRenderRadius: 1
shieldRegen: 1
footprint: -6,-3,6,5
constructionFootprint: -6,-3,6,5
tags: 余辉指挥中心t3,余辉指挥中心t2,地面,建筑,反高空,无人单位,自动
techLevel: 1
displayDescription: 【阶级t3】【建筑单位】【无人单位】【地面单位】【战术武器防御】\n-战术定位：核心建筑物。武器配置：\n-▲黄蜂无人机X4 对地对空 爆炸伤害，\n-▲防空气球发射单元X2 对空对高空 能源伤害。\n-诺瓦帝国标准预封装战地指挥中枢，用于在星球地表更便捷的指挥，\n-他们可以指挥军团规模的作战单元，以及太空舰队进行作战。\n-这种指挥中枢内含一个或者数个专用于指挥作战的高智能II级AI核心，\n-以及数个无人机发射单元用于自我防卫，\n-这种建筑是发挥诺瓦帝国强大军事实力和征服星域作战的基础。
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1),AI核心作战中枢t3残骸
effectOnDeath: CUSTOM:烟雾*6, CUSTOM:爆破*15
experimental: true
selfBuildRate: 1
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md

isBuilding: true
armour: 30
radius: 90
fogOfWarSightRange: 49
energyMax: 12
energyRegen: 0.0015
energyNeedsToRechargeToFull: false
generation_delay: 40
generation_credits: 50
exit_x:0
exit_y: 60
exit_moveAwayAmount: 180
canBuild_11_name: setRally
canBuild_11_pos: 0.0001
maxTransportingUnits: 4
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]

[action_ai无限补给]
autoTrigger: if self.isControlledByAI() and not self.tags(includes= '保险啊啊')
isVisible: false
temporarilyAddTags:保险啊啊
addResources: ry=9999
[action_开启]
text: 开启自动生产
displayType: action
buildSpeed: 0s
pos: 0.01
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/修复.png
temporarilyAddTags:自动
#temporarilyRemoveTags:不自动
isVisible: if not self.tags(includes= '自动')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 开启自动生产舰载机
ai_isHighPriority: false
[action_关闭]
text: 关闭自动生产
displayType: action
buildSpeed: 0s
pos: 0.011
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
temporarilyRemoveTags:自动
isVisible: if self.tags(includes= '自动')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 取消自动生产舰载机，为使用其他技能腾出空间
iconImage: ROOT:/通用特效/修复1.png
ai_isHighPriority: true

[hiddenAction_drone]
autoTrigger: if memory.灰机 < 4 and self.tags(includes= '自动') and self.queueSize < 0.5
alsoQueueAction: SDD
highPriorityQueue: true
[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 4
addUnitsIntoTransport: SDD黄蜂无人机
highPriorityQueue: true



[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1


[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)


[canBuild_T33]
name:爪巴
pos: 1
isVisible: false
isLocked: true
isLockedMessage:🐴




[action_升级]
convertTo: AI核心作战中枢t4
displayType: upgrade
text: 普通升级
price: 12500,蓝晶=2500
buildSpeed: 215s
ai_isHighPriority: true
description: 最大化AI核心作战中枢等级，加强防御能力，扩容战斗机库并获得战术武器防御能力，\n-使己方进入t4阶段，这将完全取得帝国所有单位的控制能力，\n-进入t4阶段后，我们能建造各种机械怪兽，奇观巨构，并且能部署强大的帝国舰队。
pos: 0.005
isLocked: if (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and self.globalTeamTags(includes='皇家舰队2')) or self.globalTeamTags(includes='禁止t4')
addResources: ry=225
isLockedMessage:你需要泽塔诺亚蓝图数据库2，乌托米尔原子刻蚀技术2，皇家舰队作战学说2的其中两个
isVisible:if not self.globalTeamTags(includes='禁止t4') 
highPriorityQueue: false
refundAllQueuedItems:true

[action_升级1]
convertTo: AI核心作战中枢t4
displayType: upgrade
text: 高科技升级
price: 0
buildSpeed: 60s
ai_isHighPriority: true
description: 最大化AI核心作战中枢等级，加强防御能力，扩容战斗机库并获得战术武器防御能力，\n-使己方进入t4阶段，这将完全取得帝国所有单位的控制能力，\n-进入t4阶段后，我们能建造各种机械怪兽，奇观巨构，并且能部署强大的帝国舰队。
pos: 0.006
isLocked: if not self.globalTeamTags(includes='禁卫军1') or self.globalTeamTags(includes='禁止t4')
isLockedMessage:你需要帝国禁卫军军备复现1
isVisible:if not self.globalTeamTags(includes='禁止t4') 
highPriorityQueue: false
refundAllQueuedItems:true
addResources: ry=225



[action_雷达]
text: 雷达扫描
allowMultipleInQueue: false
description: -命令太空舰队对地面进行扫描，\n-将对目标区域获取5.5秒的有效视野。
iconImage: ROOT:/通用特效/雷达.png
price: energy=6
fireTurretXAtGround: 雷达
highPriorityQueue: true
isVisible: true
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
pos:0.1
buildSpeed: 0s
ai_isHighPriority: false
[action_造筑基虫]
displayType: action
price: 700
buildSpeed: 11s
isVisible: true
highPriorityQueue: true
produceUnits:筑基虫(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: 筑基虫
textAddUnitName:筑基虫
descriptionAddFromUnit: 筑基虫
descriptionAddUnitStats: 筑基虫
allowMultipleInQueue:true
pos:0.2
ai_isHighPriority: true
isLocked: if numberOfUnitsInTeam(greaterThan=10, withTag='农民') and self.isControlledByAI()
[action_造开拓者]
displayType: action
price: 150
buildSpeed: 3.75s
isVisible: true
highPriorityQueue: true
produceUnits:HK开拓者(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: HK开拓者
textAddUnitName:HK开拓者
descriptionAddFromUnit: HK开拓者
descriptionAddUnitStats: HK开拓者
allowMultipleInQueue:true
pos:0.3
ai_isHighPriority: false


[action_造收割者]
displayType: action
price: 700
buildSpeed: 10s
isVisible: true
highPriorityQueue: true
produceUnits:HK收割者(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: HK收割者
textAddUnitName:HK收割者
descriptionAddFromUnit: HK收割者
descriptionAddUnitStats: HK收割者
allowMultipleInQueue:true
pos:0.4
ai_isHighPriority: false



[action_造死亡之雨]
displayType: action

price: 1300
buildSpeed: 16.5s
isVisible: true
highPriorityQueue: true
produceUnits:HK死亡之雨(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: HK死亡之雨
textAddUnitName:HK死亡之雨
descriptionAddFromUnit: HK死亡之雨
descriptionAddUnitStats: HK死亡之雨
allowMultipleInQueue:true
pos:0.5
ai_isHighPriority: false







[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
yOffsetRelative:8
xOffsetRelative:8
onlyWhileAlive:true
isVisible:true
alpha:0.6

[decal_光]
image: ROOT:/余辉军团/建筑特效/老家灯.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
alpha:0.6


[decal_遮盖]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true

[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true

[decal_转子]
image: ROOT:/余辉军团/建筑特效/老家动画.png
total_frames: 3
frame: (self.customTimer * 15) % 3
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:0
yOffsetAbsolute:-36
isVisible:true
onlyWhileAlive:true
layer: onTop


[decal_光头]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:0.5
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1

[graphics]
total_frames: 1
image: NO.png
image_back: ROOT:/余辉军团/建筑特效/老家地板.png
image_wreak:ROOT:/余辉军团/建筑特效/老家死亡.png
image_turret: NONE
#imageScale: 0.8
#turretImageScale: 0.75
showShotDelayBar:false

#image_offsetY: -50
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
maxAttackRange: 99999
turretTurnSpeed: 50
turretMultiTargeting: true
[turret_雷达]
x: 0
y: 0
projectile: 雷达
#limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true
shoot_sound: ROOT:/通用特效/扫描.ogg
shoot_sound_vol: 1
[turret_1]
x: -90
y: -22
projectile: 233
delay: 2.2s
canAttackMaxAngle: 181
canOnlyAttackUnitsWithoutTags:高空
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true
limitingRange: 900
unloadUpToXUnitsAndGiveAttackOrder: 1
[turret_2]
x: 90
y: -22
copyFrom: 1

[turret_3]
x: 0
y: 0
projectile: 233
delay: 99999s
warmup:99999s
canAttackMaxAngle: 181
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true

[turret_4]
x: -100
y: -22
invisible: true
shoot_sound: NONE
shoot_flame: NONE
projectile: 1
size: 0
turnSpeed: 811
turnSpeedAcceleration: 10
delay: 400
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
limitingRange: 900

[turret_5]
x: 100
y: -22
copyFrom: 4
delay:350
warmup:50


[turret_6]
x: 0
y: 0
canShoot: true
shoot_sound: ROOT:/余辉军团/单位特效/瓶1.ogg
shoot_sound_vol: 0.3

shoot_flame: NONE
projectile: 2
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay: 10
interceptProjectiles_withTags: 战术武器
interceptProjectiles_andUnderDistance: 1000
interceptProjectiles_andOverHeight: -100
invisible: true
energyUsage: 2


[turret_6x]
x: 0
y: 0
copyFrom: 6
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 1000
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:1000
#战术防御天上



[projectile_1]
directDamage: 0
life: 2
speed: 0.01
drawSize: 0
color: #1E1E96

explodeOnEndOfLife: true
spawnUnit: 气球
deflectionPower: -1
explodeEffect: NONE
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true

[projectile_雷达]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 雷达(offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none

[projectile_2]
areaDamage: 0
areaRadius: 0
life: 666
speed: 30
targetSpeed: 30

trailEffect: false
frame:1
drawSize: 0
largeHitEffect: true
deflectionPower: -1

explodeEffect:CUSTOM:战术防御瓶1,CUSTOM:战术防御波,CUSTOM:战术防御光子*8,CUSTOM:战术防御闪光d
[arm_1]
x: 0
y: 0
image_end:ROOT:/余辉军团/建筑特效/老家钢门.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:0.3

[animation_开门]
blendIn: 0.1s
blendOut: 0.1s
arm1_0s: {x:0, y:0, dir:0}

arm1_2s: {x:0, y:33, dir:0}

arm1_99999s: {x:0, y:33, dir:0}



[attachment_drone1]
x: -90
y: -22
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false
idleDir:-90
addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: false
lockRotation: true
#height:1
[attachment_drone2]
@copyFromSection: attachment_drone1
x: -90
y: -22


[attachment_drone6]
@copyFromSection: attachment_drone1
x: 90
y: -22
idleDir:90
[attachment_drone7]
@copyFromSection: attachment_drone1
x: 90
y: -22
idleDir:90


[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 60
yOffsetRelativeRandom: 100
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: 30
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
xOffsetRelativeRandom:70
yOffsetRelativeRandom:160
delayedStartTimerRandom:30
yOffsetRelative: 50
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[ai]
ai_upgradePriority: 1
buildPriority: 0.01



