


[core]
name: 高射炮t4
displayText: Зенитное орудиеt4
displayDescription: 【Уровень t4】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение: ПВО炮塔。вооружение：\n-▲小 РельсотронX4 по воздуху对высотный кинетический урон \n-多联装中口径老式Зенитное орудие，способен持续不断的запускать破片огневая сеть封锁天空，\n-该вооружениеспособенэффективный对вражеский空军实施удар和огневая мощь覆盖。
price: 6200,钍=113
maxHp: 20000
footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 20
techLevel: 1
fogOfWarSightRange: 41
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 10s
radius: 16
buildingSelectionOffset: -8
armour:35

isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1,largeExplosion*1
tags: 地面,建筑,防御建筑,反高空
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_炮塔影子]
image: 影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 6
imageScale:0.9
[decal_炮管影子]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 1
imageScale:0.9
[decal_炮管影子1]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 2
imageScale:0.9
[decal_炮管影子2]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 4
imageScale:0.9
[decal_炮管影子3]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 5
imageScale:0.9
[decal_炮塔]
image: 链.png
total_frames: 2
frame: (self.customTimer * 10) % 2
basePositionFromTurret: 6
isVisible:if self.isAttacking()
onlyWhileAlive:true
layer: onTop
yOffsetRelative:-3.5
xOffsetRelative:-0.5
imageScale:0.9
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/t4影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
alpha:0.65
[decal_灯光]
image: ROOT:/创世纪军事集团/建筑特效/led.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:true
yOffsetRelative:-3
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.85
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/大支撑.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-30
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.9
alpha:0.9
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image: ROOT:/创世纪军事集团/建筑特效/防御塔t4底座.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_offsetY: 1

image_back: ROOT:/通用特效/NO.png
#AUTO
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9
turretImageScale: 0.9
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 12

turretTurnSpeed: 6
maxAttackRange: 805
shootDelay: 0
[turret_1]
x: 9.5
y: 11
attachedTo: 6
slave: true
shoot_flame: CUSTOM:烟雾1*2,CUSTOM:弹壳
shoot_light: #FFEECCCC
shoot_sound: ROOT:/通用特效/中轨道炮.ogg
shoot_sound_vol: 0.55
image: 轨道管.png
recoilOffset: -12
delay: 40
size:16
projectile: 1
canAttackCondition: if self.resource.xk < 1
[turret_2]
x:-9.5
y:11
copyFrom: 1
linkDelayWithTurret:5
warmup:15
delay:25
[turret_3]
x:0
y:0
canShoot: false
image:轨道.png
attachedTo: 6
slave: true
[turret_4]
x:-5
y:8
copyFrom: 1
linkDelayWithTurret:4
warmup:10
delay:30

[turret_5]
x:5
y:8
copyFrom: 1
linkDelayWithTurret:1
warmup:5
delay:35
[turret_6]
x: 0
y: 34
canShoot: false
idleSweepAngle: 100
idleSweepDelay: 210

idleSweepSpeed: 0.2
canAttackCondition: if self.resource.xk < 1
recoilOffset: -1
image:轨道1.png
[turret_7]
x: 0
y: 5
attachedTo: 6
projectile: 2
slave: true
delay: 1
canShoot: true
invisible: true
aimOffsetSpread: -0.01
[projectile_1]
@copyFromSection: template_动能
directDamage: 380
life: 400
speed: 15
image: ROOT:/太空浪人/单位特效/星星1.png
targetSpeed:18
drawSize: 0.43
lightSize: 0.8
trailEffectRate: 0.5
trailEffect: CUSTOM:尾,CUSTOM:尾1
lightColor: #FFFF1200
explodeEffect: CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:光子gd*14,CUSTOM:冲击波gd,CUSTOM:爆炸2gd
explodeEffectOnShield:CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:光子gd*14,CUSTOM:冲击波gd,CUSTOM:爆炸2gd
armourIgnoreAmount: 10
shieldDamageMultiplier: 1.2
[projectile_2]
directDamage: 0
life: -4
instant: true
frame: 33
beamImage: 光.png

beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
color: #FFFF1200
explodeEffect: none
#———————————————科技
[effect_爆炸2gd]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 1.9
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9
color: #FFFF1200
[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.6
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_闪光gd]
priority:low
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 4
scaleTo: 0.1
drawUnderUnits: true
atmospheric: false
[effect_光子gd]
spawnChance: 0.8
createWhenZoomedOut: false
life: 50
priority: low
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 4.3
ySpeedRelativeRandom: 4.3
[effect_冲击波gd]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
atmospheric: false
#——————————
[effect_尾]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.05
scaleTo: 0.2
alpha: 0.8
drawUnderUnits: true
atmospheric: false
spawnChance: 0.8
[effect_尾1]
priority: veryhigh
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
color: #A6D80000
fadeInTime: 2
scaleFrom: 0.8
scaleTo: 0.1
alpha: 0.7
drawUnderUnits: true
#——————————
[effect_弹壳]
priority: high
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.7
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 0
ySpeedRelative: -1.5
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -40
hSpeed: 2
dirSpeedRandom: 15

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true

[effect_烟雾1]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.6
ySpeedRelative: 1
atmospheric: true
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0

turnAcceleration: 0


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


