


[core]
name: 自行高炮
displayText: Самоходное зенитное орудие
price: 1600
maxHp: 2500
displayDescription: 【Уровень t3】【Механический юнит】【Наземный юнит】Тактическое назначение: ПВО-машина，размер юнита:3，\n-вооружение：▲Зенитное орудиеX2 только по воздуху。взрывной урон противсопровождающий юнитурон-бонус。\n-перед лицомЗаревоистребителькрайнетолстыйреальный 护盾спередовой合становитьсяброня，\n-Генезисобнаруживатьтрадиционныйракета早ужене можетэффективныйудар落Заревоистребитель，\n-тогда，одинбольшой批老式 Самоходное зенитное орудиевмодификацияпослетогда снова次启использовать。\n-Самоходное зенитное орудиеявляется поверхностьверхсамыйсмертельный низковысотный杀手，\n-егооснащённый двойной联установитьЗенитное орудиеможетбыстрый撕碎любой胆敢соединятьблизко ВВС，\n-смотретьприходитьнеботакжебольше не安все 。
transportSlotsNeeded:3
techLevel: 1
buildSpeed: 8s
radius: 26
displayRadius: 26
isBio: false
armour: 3
unitsSpawnedOnDeath: 损毁2*1
softCollisionOnAll: 4
tags: 地面,驻扎要塞
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 19
[action_电磁炮1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道2.png
text: орбитальныйпусковая установка2
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器2')


[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: Мина «Кошмар»1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3') 


[action_t1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999



[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
imageScale:1
[decal_炮塔影子]
image: SHADOW:${turret_3.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:1.5
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret: 3
alpha:0.65
[decal_炮塔影子1]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:1.5
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
[decal_炮塔影子2]
image: SHADOW:${turret_2.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:1.5
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret: 2
alpha:0.65
[decal_炮塔损坏]
image: 炮塔损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_机枪]
image: 雷达.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 5
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 3
image: 自行高炮底盘.png
image_wreak: 自行高炮死亡.png
image_turret: 自行高炮炮塔.png
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 0
animation_moving_end: 2

animation_moving_speed: 4
dustEffect: true
imageScale: 1
turretImageScale: 1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
disablePassiveTargeting: false

turretMultiTargeting: true
turretSize: 20
turretTurnSpeed: 2.8
maxAttackRange: 320


[turret_1]
x: 13
y: 19
attachedTo: 3
slave: true
shoot_flame: large,CUSTOM:弹壳右
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.5
image: 自行高炮炮管.png
recoilOffset: -5
delay: 20
projectile: 1
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='轨道发射器2')
canAttackLandUnits: false
[turret_2]
x: -13
y: 19
linkDelayWithTurret: 1
copyFrom: 1
image: 自行高炮炮管.png
warmup:6
shoot_flame: large,CUSTOM:弹壳左

[turret_3]
x: 0
y: -8
canShoot: false
canAttackCondition: if self.resource.xk < 1
idleSweepAngle: 20
idleSweepDelay: 230
idleSweepSpeed: 0.2
image:自行高炮炮塔.png
canAttackLandUnits: false
[turret_5]
x: 0
y: -14
canShoot: false
image: 雷达.png
attachedTo: 3
projectile: 2
slave: true
idleSpin: 2
limitingRange: 1
canAttackLandUnits: false
canAttackCondition: if self.resource.xk < 1
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 130
areaRadius: 50
color: #FFFFFF73
largeHitEffect: true
lightSize: 1
frame: 8
lightColor: #FFFFFF73
deflectionPower: -1
life: 550
speed: 12
explodeEffect: CUSTOM:爆炸2,CUSTOM:烟雾2*4,CUSTOM:闪光
drawSize: 0.7
areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
mutator997_ifUnitWithTags: 伴生单位
mutator997_directDamageMultiplier: 2
[projectile_炮弹]
@copyFromSection: template_动能
directDamage: 200
life: 650
speed: 10
image: ROOT:/创世纪军事集团/单位特效/星星.png
drawSize: 0.35
lightSize: 1.5
lightColor: #FFFF1200
explodeEffect: CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:光子gd*4,CUSTOM:冲击波gd,CUSTOM:爆炸2gd
explodeEffectOnShield: CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:光子gd*4,CUSTOM:冲击波gd,CUSTOM:爆炸2gd
deflectionPower: -1
shieldDamageMultiplier: 1.2
armourIgnoreAmount: 15
trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
mutator997_ifUnitWithTags: 伴生单位
mutator997_directDamageMultiplier: 2
[projectile_2]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

[effect_尾巴]
image: SHARED:light_50.png
life: 20
fadeOut: true
attachedToUnit: false
#priority:low

color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.38
scaleTo: 0.1
alpha: 1

drawUnderUnits: true


#———————————————科技
[effect_爆炸2gd]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9
color: #FFFF1200

[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.43
scaleTo: 0.43
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_闪光gd]
priority:low
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3
drawUnderUnits: true
atmospheric: false
[effect_光子gd]
spawnChance: 0.8
createWhenZoomedOut: false
life: 50
priority: low
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7
ySpeedRelativeRandom: 3.7
[effect_冲击波gd]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.65
alpha: 0.8
drawUnderUnits: false
atmospheric: false

[effect_弹壳左]
priority: high
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: -1.2
xSpeedRelativeRandom: -0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -37
xOffsetRelative: -3

hSpeed: 3
dirSpeedRandom: 50
[effect_弹壳右]
priority: high
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 1.2
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -37
xOffsetRelative: 3

hSpeed: 3
dirSpeedRandom: 50

[effect_烟雾2]
#priority:high
frameIndex: 0
stripIndex: smoke_black
spawnChance: 1
createWhenZoomedOut: false

life: 140
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 1

scaleFrom: 1
scaleTo: 1.8
alpha: 1.3
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3
scaleTo: 0.1

drawUnderUnits: false
atmospheric: false


[effect_爆炸2]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg

alpha: 1.2





[movement]
movementType: LAND
moveSpeed: 1.2
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.12
maxTurnSpeed: 1.6

turnAcceleration: 0.7
moveSlidingMode : false
moveIgnoringBody: false


