


[core]
name: 雪崩
displayDescription: 
class: CustomUnitMetadata
price: 2
maxHp: 3000

energyMax: 4.1
energyRegen: 0
energyNeedsToRechargeToFull: true
tags: 战机lrx,飞机,寄生免疫,低空,伴生单位
buildSpeed: 4s
showInEditor: false
techLevel: 2
radius: 18
displayRadius: 18
isBio: false
softCollisionOnAll: 100
armour: 5
numBitsOnDeath: 5
canNotBeGivenOrdersByPlayer: true


[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'


[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'


[hiddenAction_return]
autoTrigger: if not self.hasActiveWaypoint(type= 'loadInto') and not self.hasParent
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto


[hiddenAction_return1]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( self.energy < 0.5 or attacking.hp <= 0 or distanceBetweenSquared(self, customTarget1) > 1210000 )
# distanceBetweenSquared 返回两个单位之间的平方距离。 比 distanceBetween 快一点，因为少了开方这一步。1100² 判断灰机离母体有多远，超过1100回家
clearActiveWaypoint: true
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own

addWaypoint_type: loadInto


[hiddenAction_disconnect]
requireConditional: if self.hasParent and self.isEnergyFull and not self.hasActiveWaypoint(type= 'attack')
# autoTrigger: if self.hasParent and self.isEnergyFull and customTarget1.isAttacking
disconnectFromParent: true
addWaypoint_target_fromReference: attacking
addWaypoint_type: attack

addWaypoint_triggerActionIfMatched: return


[hiddenAction_energy]
autoTrigger: if self.hasParent and not self.isEnergyFull
addEnergy: 5


[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
addResources: hp= -999999
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999

[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.8


[attack]
canAttack: true
canAttackFlyingUnits: if self.resource.awz>-1 and self.isInMap
canAttackLandUnits: if self.resource.awz>-1 and self.isInMap
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 4
maxAttackRange: 1030
# 900+130 阿玛洛克MKII 有个槽位在130
attackMovement: bomber
# isMelee:true

# meleeEngangementDistance:1600


[turret_2]
x: 0
y: 0
invisible: true
limitingRange: 350
canAttackCondition: if not self.hasParent()

shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
projectile: 1

energyUsage: 0.5
delay: 120


[projectile_1]
@copyFromSection: template_能源
areaDamage: 650
areaRadius: 50
life: 200
speed: 6

image: ROOT:/太空浪人/单位特效/星星1.png
targetSpeed: 6
drawSize: 0.60
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*9,CUSTOM:冲击波,CUSTOM:爆炸2
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*9,CUSTOM:冲击波,CUSTOM:爆炸2

areaRadiusFromEdge: true
lightSize: 0.75
lightColor: #FFFF1200


[turret_233]
x: 0
y: 0
# limitingRange: 580
projectile: 233
warmup: 1s

delay: 0.9s
canAttackMaxAngle: 181
canAttackCondition: if self.energy(full= true) and self.hasParent()
canAttackFlyingUnits: true
canAttackLandUnits: true

canAttackUnderwaterUnits: false
invisible: true
onShoot_triggerActions: disconnect


[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true


[effect_爆炸2]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.8
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9

#alsoPlaySound:  ROOT:/余辉军团/单位特效/波雷爆炸.ogg
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 0.5

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7

ySpeedRelativeRandom: 3.7
#atmospheric: true


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.65
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.48
scaleTo: 0.48
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[movement]
movementType: AIR
reverseSpeedPercentage: 0
moveSpeed: 2.8
moveAccelerationSpeed: 2.5
moveDecelerationSpeed: 0

targetHeightDrift: 0.3
targetHeight: 70
maxTurnSpeed: 4
turnAcceleration: 0.05
moveSlidingMode: false

moveIgnoringBody: false
moveSlidingDir: 0
slowDeathFall: true


