


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=250


[core]
name: SDSF凤凰级护卫舰1
displayText: SDSF Корвет класса «Феникс»1
showInEditor: false
class: CustomUnitMetadata
displayDescription: -корвет класса «Феникс»это Империяфлотв самыйбыстрый военный корабль, \n-его опираясь напревосходный толкатьвустройство и сначалав реакторстать для Империяфлотв  "срочносначалалезвие".\n-делатьдля Империя НоваоченьВВСв  стандарткорвет, нет теориялюбоймасштаблюбойделатьиспользует  флотвсе будетсмотретьк Феникс телотень, \n-даже если такобычный, дажедо имеет несколькослабыймалый , использовать корвет класса «Феникс»частополучаетк враги лёгкий видеть, \n-тольконе , тене берёт Феникскорветпоместитьв глазвнутри  врагибольшой частьвсе смерть.\n-только по воздуху, главное орудиеможет источник, взрыв ракеты.\n-Тип проекта:ИмперияЗаревооченьВВС.
price: 3950,蓝晶=375
maxHp: 3500

techLevel: 2
buildSpeed: 20s
canOnlyBeAttackedByUnitsWithTags:反高空
fogOfWarSightRange: 33
maxShield: 5500
shieldRegen: 0.07
armour: 18
radius: 53

shieldRenderRadius: 45
shieldDisplayOnlyDeflection: true
displayRadius: 53
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 凤凰
softCollisionOnAll: 10
tags: 飞机,高空,反高空,凤凰,无人单位
energyMax: 4
energyRegen: 0.027
energyNeedsToRechargeToFull: true
[action_b]
displayType: action
price: 0
buildSpeed: 5s
isVisible: true
whenBuilding_cannotMove: false
text:спускнизкий высокий степень
description: спускнизкий корвет класса «Феникс» высокий степень, использоватьего стать для обычныйвоздушныйв юнит.\n-восстановлениедальность и против обычныйвоздушныйв юнит может сила, но потеряидти атакавысотный юнит может сила.
iconImage: ROOT:/通用特效/低空.png
allowMultipleInQueue:false
convertTo: SDSF凤凰级护卫舰
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_高空]
text: высотный юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: место к крайневысокий высокий степень истребитель и военный корабль.\n-в этовысокий степеньпод , толькоимеет   и воздушныйв особый антивысотный юнит,  и высотный юниттолько тогдаможет атакак этотюнит, \n-одновременно, большой частьвысотный юнитможет взаимноатака, и может атакаобычныйвоздушныйв юнит, \n-толькоимеет особый высотный юниттолько тогдаможет по землеатака.

[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=775, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=775, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[graphics]
total_frames: 3
image_shield: 护盾.png
image: 身体.png
image_wreak: 死亡.png
image_turret: NONE

#imageScale:0.9
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 2

animation_moving_end: 2
animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3

movementEffect: CUSTOM:火,CUSTOM:火1
movementEffectRate: 0.8
lock_body_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 13

turretTurnSpeed: 1.5
maxAttackRange: 675
isFixedFiring: true


[turret_1]
x: 0
y: 0
invisible: true
canShoot: false
canOnlyAttackUnitsWithTags:高空

[turret_2]
x: 0
y: 20
canShoot: true
image: 主炮.png
delay: 7

#limitingAngle:40
#idleDir:-90
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾a*2,CUSTOM:粒子*3

shoot_light: #FFccCCEE
projectile: 1
#delay:25
#recoilOffset: -1
attachedTo: 1

slave: true
energyUsage: 1
canOnlyAttackUnitsWithTags:高空

[turret_3]
x: 30
y: 73
canShoot: true
image: 导弹.png
projectile: 2

shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC
#canAttackFlyingUnits: false

size: 0
slave: true
attachedTo: 1
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 150
turnSpeed: 0
delay: 150
canOnlyAttackUnitsWithTags:高空

[turret_4]
x: 35
y: 73
canShoot: true
image: 导弹.png
projectile: 2

shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC
#canAttackFlyingUnits: false

size: 0
slave: true
attachedTo: 1
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 150
turnSpeed: 0
delay: 150
warmup: 10
canOnlyAttackUnitsWithTags:高空

[turret_5]
x: -30
y: 73
canShoot: true
image: 导弹.png
projectile: 2

shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC
#canAttackFlyingUnits: false

size: 0
slave: true
attachedTo: 1
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 150
turnSpeed: 0
delay: 150
canOnlyAttackUnitsWithTags:高空

[turret_6]
x: -35
y: 73
canShoot: true
image: 导弹.png
projectile: 2

shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC
#canAttackFlyingUnits: false

size: 0
slave: true
attachedTo: 1
recoilOffset: -30
recoilOutTime: 4
canOnlyAttackUnitsWithTags:高空
recoilReturnTime: 150
turnSpeed: 0
delay: 150
warmup: 10


[projectile_1]
@copyFromSection: template_能源
directDamage: 280
life: 200
speed: 10
image: ROOT:/余辉军团/单位特效/子弹.png

targetSpeed: 10
drawSize: 0.73
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光*1,CUSTOM:聚变
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光*1,CUSTOM:聚变
#areaRadiusFromEdge:true

lightSize: 0.75
trailEffectRate: 1.5
trailEffect: CUSTOM:尾巴
lightColor: #FF00B3FF


[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 150
areaRadius: 50
life: 350
speed: 5

deflectionPower: -1
lightSize: 1.5
lightColor: #FF39FFFF
drawSize: 0.9
targetSpeed: 8

trailEffect: true
image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:大爆炸,CUSTOM:闪光,CUSTOM:聚变x
explodeEffectOnShield: CUSTOM:大爆炸,CUSTOM:闪光,CUSTOM:聚变x
areaRadiusFromEdge: true

autoTargetingOnDeadTarget: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[effect_聚变x]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.1
scaleTo: 1.1
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_大爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2

scaleTo: 1.2
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.35
image: ROOT:/余辉军团/单位特效/自制.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩.png
life: 50
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 0.3
alpha: 1
drawUnderUnits: false
atmospheric: false


[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/光束22.png
life: 30
fadeOut: true
attachedToUnit: false

color: #63e6e8
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_烟雾a]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8

ySpeedRelative: 1.5
atmospheric: true


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedRelative: 2
#xOffsetRelative:-2
atmospheric: true


[effect_火1]
life: 55
fadeInTime: 4
fadeOut: true
attachedToUnit: false
scaleFrom: 5

scaleTo: 1.5
image: ROOT:/通用特效/蓝火.png
alpha: 0.7
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: -5
yOffsetRelative	: -70


[effect_火]
life: 55
fadeInTime: 4
fadeOut: true
attachedToUnit: false
scaleFrom: 5

scaleTo: 1.5
image: ROOT:/通用特效/蓝火.png
alpha: 0.7
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 5
yOffsetRelative	: -70


[arm_1]
x: 0
y: 34
image_end: 门.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:-60}
arm1_950s: {x:0, y:-60}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 2.25
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02
maxTurnSpeed: 3.8

turnAcceleration: 0.4
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: false
targetHeight: 140

startingHeightOffset: 1000


