
[hiddenAction_寄生b]
addResources: bj= ${bjxq}
produceUnits:清理标签
[action_拆除哇袄]
spawnUnits:清理标签
removeGlobalTeamTags:有和平了
[core]
name: 创世纪导弹基地t22
displayText: Ракетная база Генезисаt22
displayDescription:【Уровень t4】【Здание】【Наземный юнит】\n-Тактическое назначение：дорогабазадальнийстратегическое оружие/тактическое оружиезапускатьплатформа。\n-не может строиться на воде。\n-черездовоенный 固定式снаряд道ракетазапускать井модификация 固定式ракетазапускатьплатформа，\n-этот видпройти черезсовременныйУлучшение запускатьбазаспособензапускатьразные类  Боеприпасы，\n-одновременно容量такжеполучить огромныйУлучшение，можетвзапускать井в储存в качествечислонемало 待 снаряд，\n-в качествеГенезис综合соотношение цена/качествосамыйвысокий многоприменениеснаряд道ударсила，\n-этот видРакетная базазапускать разныетяжёлыйракетавбойв важныйтипявляетсялюбойманёврзапускатьплатформавсене можетвместопоколение 。
class: CustomUnitMetadata
price: 15000,钍=300,bj= ${bjxq}
@global bjxq: 30
reclaimPrice: bj= ${bjxq}
maxHp: 60000
showInEditor:false
effectOnDeath: CUSTOM:烟雾s*4, CUSTOM:爆破*8,largeExplosion
unitsSpawnedOnDeath:建筑损毁,清理标签
footprint: -6,-1,6,6
constructionFootprint: -6,-1,6,6
techLevel: 1
buildSpeed: 60s
radius: 100
displayRadius: 100
isBuilding: true
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
armour: 30

energyMax: 6
energyRegen: 0
energyNeedsToRechargeToFull: false
energyStartingPercentage: 0
tags: 导弹基地,地面,建筑
isLockedIfGameModeNoNuke: true


[action_和平守卫者]
fireTurretXAtGround: 1
text: запускатьХранитель мира
price: 0
displayType: action
buildSpeed: 0s
pos: 10
description: -запускатьпосле，будетгенерировать3находитьсяракетаточка приземления标记，иможно 行ручной修правильныйракетаточка приземления，\n-триракетабудетминута别взапускатьпосле 12секунда/20секунда/28секунда命в指定 три цель，\n-ибудетпротивцельпунктв качестве圆心，радиус750и менее вражеский поверхность，Пустов，высотныйюнит，\n-наноситсамыйвысокий100000пунктэнергетический урон，\n-иибудетмгновенно斩杀дистанциявзрыв心150в радиусе любойназемный юнит，не包括находится внет敌состояние юнитиподводныйюнит。
displayRemainingStockpile:false
highPriorityQueue: true
onlyOneUnitAtATime: true
iconImage: 狙.png
showMessageToAllPlayers: 发射检测：警告，检测到一枚和平守卫者已升空！
temporarilyAddTags:已发射,齿轮
isLocked: if self.tags(includes= '已发射')
isVisible: if not self.tags(includes= '已发射')
alsoQueueAction:动画
playSoundGlobally:ROOT:/通用特效/警告.wav

[action_动画]
convertTo: 创世纪导弹基地t2
displayType: action
price: 0
buildSpeed: 20s
isVisible: false
highPriorityQueue: false
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
temporarilyRemoveTags:已发射,齿轮
removeGlobalTeamTags:有和平了
[decal_损坏]
image:上层损坏.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9

[decal_灯]
image: led.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:if self.maxHp * 0.36< self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale: 0.9
alpha:0.8
[decal_灯1]
image: led1.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:if self.maxHp * 0.36< self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale: 0.9
alpha:0.8

[decal_雷达2]
image: SHADOW:ROOT:/创世纪军事集团/建筑特效/雷达.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:66
xOffsetRelative:37
onlyWhileAlive:true
dirOffset:-45
imageScale: 0.8
alpha:0.65
[decal_雷达]
image: ROOT:/创世纪军事集团/建筑特效/雷达.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:if self.maxHp * 0.36< self.hp
yOffsetRelative:64
xOffsetRelative:34
onlyWhileAlive:true
dirOffset:-45
imageScale: 0.8

[decal_雷达1]
image: ROOT:/创世纪军事集团/建筑特效/雷达损坏.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:64
xOffsetRelative:34
onlyWhileAlive:true
dirOffset:-45
imageScale: 0.8
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[decal_地板]
image: 地板.png
total_frames: 1
layer: shadow
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
imageScale: 0.9
alpha:1
[decal_影子]
image: SHADOW:a.png
layer: shadow
xOffsetAbsolute: 5
yOffsetAbsolute: -1
alpha: 0.5
onlyWhileAlive: true
imageScale: 0.9
isVisible: true
[graphics]
total_frames: 1
image:a.png
image_back: ROOT:/通用特效/NO.png
image_wreak:maf.png
image_turret: NONE
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 1

turretTurnSpeed: 15
maxAttackRange: 99999
shootDelay: 0


[turret_1]
canShoot: false
x: 27
y: -34
idleDir: 0
invisible: true
shoot_sound: nuke_launch
shoot_sound_vol: 0.6
shoot_light: #FFEECCCC
projectile: 1
shoot_flame: CUSTOM:水雾y*10,CUSTOM:冲击波,CUSTOM:闪光
size: 46
turnSpeed: 40
limitingMinRange: 500
[projectile_1]
directDamage: 0
life: 180
speed: 0.1
targetSpeed: 4
targetSpeedAcceleration: 0.02
ballistic: true
ballistic_delaymove_height: 1500
ballistic_height: 1600
image: 导弹.png
drawSize: 0.9
targetGround: true
alwaysVisibleInFog: true
areaRadius: 0
deflectionPower: -1
shouldRevealFog: true
nukeWeapon: true
trailEffect: CUSTOM:火箭,CUSTOM:火,CUSTOM:火1,CUSTOM:火2,CUSTOM:闪光1
trailEffectRate: 0.8
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:导弹碎片1,CUSTOM:导弹碎片2,CUSTOM:冲击波,CUSTOM:闪光
spawnProjectilesOnEndOfLife:2
[projectile_2]
@copyFromSection:projectile_1
image: 导弹6.png
spawnProjectilesOnEndOfLife: 3,4,5

explodeEffect: NONE
life: 240
trailEffect: CUSTOM:火箭,CUSTOM:火,CUSTOM:闪光1
trailEffectRate: 0.8
[projectile_3]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true
instant: true
spawnUnit: 和平守卫者(addResources=1:1,offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none
targetGroundSpread: 500
targetGround: true
[projectile_4]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true
instant: true
spawnUnit: 和平守卫者(addResources=2:1,offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none
targetGroundSpread: 500
targetGround: true
[projectile_5]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true
instant: true
spawnUnit: 和平守卫者(addResources=3:1,offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none
targetGroundSpread: 500
targetGround: true
[arm_1]
x: -6.5
y: -34
image_end: ROOT:/创世纪军事集团/建筑特效/导弹上左.png
image_end_teamColors: true
drawOverBody: true

[arm_2]
x: 56
y: -34
image_end: ROOT:/创世纪军事集团/建筑特效/导弹上右.png
image_end_teamColors: true
drawOverBody: true


[arm_3]
x: 26
y: -14
image_end: ROOT:/创世纪军事集团/建筑特效/导弹上.png
image_end_teamColors: true
drawOverBody: true

[arm_4]
x: 26
y: -55
image_end: ROOT:/创世纪军事集团/建筑特效/导弹下.png
image_end_teamColors: true
drawOverBody: true

[arm_5]
x: 30
y: 21
image_end:1.png
image_end_teamColors: true
drawOverBody: true
[arm_6]
x: 52
y: 21
image_end:2.png
image_end_teamColors: true
drawOverBody: true
[arm_7]
x: 78
y: 19
image_end:3.png
image_end_teamColors: true
drawOverBody: true
[arm_8]
x: 113
y: -15
image_end:吊车影子.png
image_end_teamColors: true
drawOverBody: true


[arm_9]
x: 0
y: 0
image_end:上层2遮盖.png
image_end_teamColors: true
drawOverBody: true
[arm_10]
x: 0
y: 0
image_end: 上层2遮盖损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_11]
x: 26
y: 41
image_end:导弹1.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.tags(includes= '已发射')
[arm_12]
x: 26
y: -20
image_end:导弹2.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.tags(includes= '已发射')
[arm_13]
x: 30
y: 3
image_end:1.png
image_end_teamColors: true
drawOverBody: true
[arm_14]
x: 52
y: 3
image_end:2.png
image_end_teamColors: true
drawOverBody: true
[arm_15]
x: 78
y: 1
image_end:3.png
image_end_teamColors: true
drawOverBody: true
[arm_16]
x: 108
y: -20
image_end:吊车.png
image_end_teamColors: true
drawOverBody: true
[arm_17]
x: 108
y: -20
image_end:吊车损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_18]
x: 0
y: 0
image_end:吐了1.png
image_end_teamColors: true
drawOverBody: true
[arm_19]
x: 0
y: 0
image_end: 吐了.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_20]
x: 109.5
y: -93
image_end:扇区.png
image_end_teamColors: false
drawOverBody: true
spinRate:4
hidden:if not self.tags(includes= '齿轮')
[animation_部署]
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}
arm15_0s: {x:0, y:0, dir:0}
arm16_0s: {x:0, y:0, dir:0}
arm17_0s: {x:0, y:0, dir:0}

arm1_2s: {x:22, y:0, dir:0}
arm2_2s: {x:-22, y:0, dir:0}
arm3_2s: {x:0, y:0, dir:0}
arm4_2s: {x:0, y:0, dir:0}
arm5_2s: {x:0, y:0, dir:0}
arm6_2s: {x:0, y:0, dir:0}
arm7_2s: {x:0, y:0, dir:0}
arm8_2s: {x:0, y:0, dir:0}
arm9_2s: {x:0, y:0, dir:0}
arm10_2s: {x:0, y:0, dir:0}
arm11_2s: {x:0, y:-126, dir:0}
arm12_2s: {x:0, y:-65, dir:0}
arm13_2s: {x:0, y:0, dir:0}
arm14_2s: {x:0, y:0, dir:0}
arm15_2s: {x:0, y:0, dir:0}
arm16_2s: {x:0, y:0, dir:0}
arm17_2s: {x:0, y:0, dir:0}

arm1_4s: {x:22, y:0, dir:0}
arm2_4s: {x:-22, y:0, dir:0}
arm3_4s: {x:0, y:-15, dir:0}
arm4_4s: {x:0, y:15, dir:0}
arm5_4s: {x:0, y:0, dir:0}
arm6_4s: {x:0, y:0, dir:0}
arm7_4s: {x:0, y:0, dir:0}
arm8_4s: {x:0, y:0, dir:0}
arm9_4s: {x:0, y:0, dir:0}
arm10_4s: {x:0, y:0, dir:0}
arm11_4s: {x:0, y:-126, dir:0}
arm12_4s: {x:0, y:-65, dir:0}
arm13_4s: {x:0, y:0, dir:0}
arm14_4s: {x:0, y:0, dir:0}
arm15_4s: {x:0, y:0, dir:0}
arm16_4s: {x:0, y:0, dir:0}
arm17_4s: {x:0, y:0, dir:0}

arm1_10s: {x:22, y:0, dir:0}
arm2_10s: {x:-22, y:0, dir:0}
arm3_10s: {x:0, y:-15, dir:0}
arm4_10s: {x:0, y:15, dir:0}
arm5_10s: {x:53, y:0, dir:0}
arm6_10s: {x:38, y:0, dir:0}
arm7_10s: {x:20, y:0, dir:0}
arm8_10s: {x:0, y:0, dir:0}
arm9_10s: {x:0, y:0, dir:0}
arm10_10s: {x:0, y:0, dir:0}
arm11_10s: {x:0, y:-126, dir:0}
arm12_10s: {x:0, y:-65, dir:0}
arm13_10s: {x:53, y:0, dir:0}
arm14_10s: {x:38, y:0, dir:0}
arm15_10s: {x:20, y:0, dir:0}
arm16_10s: {x:0, y:0, dir:0}
arm17_10s: {x:0, y:0, dir:0}

arm1_20s: {x:22, y:0, dir:0}
arm2_20s: {x:-22, y:0, dir:0}
arm3_20s: {x:0, y:-15, dir:0}
arm4_20s: {x:0, y:15, dir:0}
arm5_20s: {x:53, y:60, dir:0}
arm6_20s: {x:38, y:60, dir:0}
arm7_20s: {x:20, y:60, dir:0}
arm8_20s: {x:0, y:60, dir:0}
arm9_20s: {x:0, y:0, dir:0}
arm10_20s: {x:0, y:0, dir:0}
arm11_20s: {x:0, y:-126, dir:0}
arm12_20s: {x:0, y:-65, dir:0}
arm13_20s: {x:53, y:60, dir:0}
arm14_20s: {x:38, y:60, dir:0}
arm15_20s: {x:20, y:60, dir:0}
arm16_20s: {x:0, y:60, dir:0}
arm17_20s: {x:0, y:60, dir:0}

#——————————发射火光
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: false
yOffsetRelative:-23
[effect_闪光]
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 12
scaleTo: 0
drawUnderUnits: false
atmospheric: false
yOffsetRelative:-23
[effect_水雾y]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 3.5
scaleTo: 5
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.35
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
xOffsetRelativeRandom:5
yOffsetRelativeRandom:5
yOffsetRelative:-23
#——————————尾部火焰
[effect_火]
life: 20
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.2
image: SHARED:light_50.png
alpha: 1
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -4
yOffsetRelative	: -63
drawUnderUnits: false
[effect_火1]
priority:low
life: 13
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.2
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: -10
ySpeedRelative: -3
xSpeedRelative: -1
yOffsetRelative	: -60
drawUnderUnits: false
[effect_火2]
priority:low
life: 13
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.2
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 10
ySpeedRelative: -3
xSpeedRelative: 1
yOffsetRelative	: -60
drawUnderUnits: false
[effect_闪光1]
image: SHARED:light_50.png
spawnChance: 0.25
life: 30
fadeOut: true
alpha: 0.7
attachedToUnit: false
color:  #FFFFA920
fadeInTime: 2
scaleFrom: 2
scaleTo: 0
drawUnderUnits: false
atmospheric: false
yOffsetRelative:-60

[effect_火箭]
stripIndex: effects
spawnChance: 0.8
frameIndex: 0
life: 80
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 2
scaleTo: 4
alpha: 0.7
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: false
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative:-60
ySpeedRelative: -1

#——————————导弹碎片
[effect_导弹碎片]
image: 左边.png
priority: critical
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
xSpeedRelative: -2
hSpeed: 2
dirSpeedRandom: 2
yOffsetRelative:-60
[effect_导弹碎片1]
image: 右边.png
priority: critical
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
xSpeedRelative: 2
hSpeed: 2
dirSpeedRandom: 2
yOffsetRelative:-60

[effect_导弹碎片2]
image: 中间.png
priority: critical
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.25
hSpeed: 2
dirSpeedRandom: 3
yOffsetRelative:-60
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1
[effect_烟雾s]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 30
yOffsetRelativeRandom: 30
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:45
yOffsetRelativeRandom:55
delayedStartTimerRandom:30
[resource_1]
displayName: 1
displayNameShort: 1
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_2]
displayName: 2
displayNameShort: 2
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_3]
displayName: 3
displayNameShort: 3
displayColor: #FF9D00FF
priority: 1
hidden: true
[ai]
disableUse: true


