


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=74


[core]
name: SDD暗天使
displayText: SDDТёмный Ангел
class: CustomUnitMetadata
displayDescription: -приказчеловекжизньстрах Тёмный Ангелрождениек Империя Нова и Аравелидвойна позади период, \n-нет теорияиз истинныйвоздушныйнулевая точкаможет реактормалый  типещё это другойтип машинателоприходит смотреть, Тёмный Ангелвсе это один разбольшой отвага пробоватьтест.\n-Этот крайнеего смертоносный по землеатакамашинаимеет достаточнодостаточно может источникштподдерживатьодин мощный наклонповоротполеприходит реальныйтекущийскрытыйформа, \n-они может лёгкий лёгкийвнезапноразорватьКогда , когда то естьдо текущийв мирна любойсамыйплотный радарсеть, и в чёрныйтёмныйв максимумситуацияубратьрезатьвраги, \n-Этот ужасный по землеатакамашинапотому чтодля крайнеего превосходстворазный, а сначалавхарактеристикиЗаревоместорасположение, \n-но может жалеть это , строительствонет теориябольшой  типещё это малый  тип истинныйвоздушныйнулевая точкаможет реакторвсе это одинкистьогромный открытьшт.\n-только по земле, энергетический урон, пулемётпротив укрытийможет скрытыйформа.\n-Тип проекта:Империя Нова следующее поколениерасчётразрезданные
price: 2400,蓝晶=120
maxHp: 1500

techLevel: 1
buildSpeed: 16s
availableInDemo: true
fogOfWarSightRange: 19
maxShield: 1500

shieldRegen: 0.07
armour: 10
radius: 37
displayRadius: 37
isBio: false

copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 10
energyMax: 15
energyRegen: 0.007
energyNeedsToRechargeToFull: true
tags: 飞机,低空,无人单位
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_裂解炮2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/裂解2.png
text: расщеплениепушка2
isActive: false
isVisible: if self.globalTeamTags(includes='裂解炮2')
[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox
price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png



[graphics]
total_frames: 3
image: SDD暗天使.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 0.9

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 2
animation_moving_end: 2

animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3
movementEffect: CUSTOM:火

movementEffectRate: 0.8


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 10

turretTurnSpeed: 1.5
maxAttackRange: 315
isFixedFiring: true


[turret_1]
x: 0
y: 0
invisible: true
canShoot: false


[turret_2]
x: -25
y: 16
attachedTo: 1
slave: true
projectile: 1

delay: 5
shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/激光音效.ogg
shoot_sound_vol: 0.35

image: 枪.png
recoilOffset: -1
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='裂解炮2')

[turret_3]
x: 25
y: 16
copyFrom: 2

[turret_4]
x: -35
y: 32
attachedTo: 1
slave: true
projectile: 2

delay: 30
shoot_light: #FF00B3FF
shoot_sound: ROOT:/余辉军团/单位特效/大炮音效.ogg
shoot_sound_vol: 0.9
image: 炮.png

recoilOffset: -3
recoilOutTime: 4
recoilReturnTime: 10
shoot_flame: CUSTOM:气浪*1,CUSTOM:粒子*1
altProjectile: 炮弹2
altProjectileCondition: if self.globalTeamTags(includes='裂解炮2')


[turret_5]
x: 35
y: 32
copyFrom: 4


[projectile_1]
@copyFromSection: template_能源
directDamage: 15
life: 100
speed: 7
color: #FF00B3FF

targetSpeed: 7
deflectionPower: -1
frame: 8
explodeEffect: CUSTOM:火花
drawSize: 0.9

lightSize: 0.6
lightColor: #FF00B3FF
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_能源
areaDamage: 80
areaRadius: 40
life: 200
speed: 10

image: ROOT:/余辉军团/单位特效/星星.png
targetSpeed: 10
drawSize: 0.45
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光

mutator3_ifUnitWithTags: 卧倒
mutator3_directDamageMultiplier: 1
targetGround: true
areaRadiusFromEdge: true
lightSize: 0.75

lightColor: #FF00B3FF
trailEffect: CUSTOM:尾巴
trailEffectRate: 2
[projectile_炮弹1]
@copyFromSection: template_动能
directDamage: 25
life: 5
instantReuseLast: true
beamImage: SHARED:beam3.png

beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true

color: #FFFFFF3D
lightColor: #FFFFFF3D
lightSize: 0.1
explodeEffect: CUSTOM:爆炸a,CUSTOM:闪光b
explodeEffectOnShield: CUSTOM:爆炸a,CUSTOM:闪光b
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_炮弹2]
@copyFromSection: template_动能
directDamage: 110
life: 200
speed: 8
image: ROOT:/余辉军团/单位特效/星星3.png

targetSpeed: 10
drawSize: 0.6
explodeEffect: CUSTOM:爆炸c, CUSTOM:闪光b
explodeEffectOnShield: CUSTOM:爆炸c, CUSTOM:闪光b
lightSize: 0.75

lightColor: #FFFFFF3D
trailEffect: CUSTOM:尾巴x
trailEffectRate: 0.8


[effect_爆炸c]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.8
image: ROOT:/余辉军团/单位特效/自制1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg


[effect_尾巴x]
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
#priority:low

color: #FFFFFF3D
fadeInTime: 2
scaleFrom: 0.8
scaleTo: 0.8
alpha: 1

drawUnderUnits: true


[effect_闪光b]
priority: critical
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFFFF3D
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[effect_爆炸a]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg

alpha: 1.2




[effect_尾巴]
image: ROOT:/余辉军团/单位特效/蓄能.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime: 1

scaleFrom: 1
scaleTo: 0.7
alpha: 0.8
drawUnderUnits: false
yOffsetRelative	: -5


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 25
fadeOut: true
scaleFrom: 0.2

scaleTo: 0.8
alpha: 2
drawUnderUnits: false
atmospheric: false
attachedToUnit: true


[effect_粒子]
life: 50
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 0.1
scaleTo: 1.5
alpha: 1

dirOffsetRandom: 180
attachedToUnit: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1

scaleTo: 1.7
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -40


[arm_1]
x: 0
y: 0
image_end: 遮盖.png
drawOverBody: true
image_end_teamColors: true


[movement]
movementType: AIR
moveSpeed: 2.8
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02
maxTurnSpeed: 2.5

turnAcceleration: 1
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: true
targetHeight: 70

startingHeightOffset: 1000


