


[core]
name: 机枪塔t3
displayText: Пулемётная башняt3
price: 2900
maxHp: 8000
footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
buildingToFootprintOffsetX: 20
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
buildingToFootprintOffsetY: 20
armour: 20
copyFrom: ROOT:/通用特效/单位防护.ini
techLevel: 1
buildSpeed: 0.0008
radius: 16
buildingSelectionOffset: -8
tags: 地面,建筑,防御建筑
isBuilding: true
isBio: false
displayDescription: 【Уровень t3】【Оборонительное здание】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение: противопехотная пулемётная башня。вооружение：\n-▲20毫米пулемётX1 по земле и воздуху кинетический урон пробивает укрытия по воздуху中，伴生，биологический юнит伤害加成 \n-Оборонительная башня с 20-мм пулемётом，Такая автоматическая башня эффективно противостоит малым юнитам и лёгкой бронетехнике，\n-но бессильна против тяжёлой брони。
[action_升级]
convertTo: 机枪塔t4
displayType: action
text: 升класс
price: 1250
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
description: самый大化Пулемётная башняуровень，加固其结构强度иувеличивает伤害а такжедальность，и使其может攻击высотный伴生юнит，\n-将弹药进一步升класс为самый高класс的贫铀穿甲弹，\n-这将赋予Пулемётная башня对轻бронированная цель和воздушный юнит毁灭性的压制способность。

[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上

[decal_炮塔影子]
image: 影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 1
[decal_炮管影子]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 2
[decal_炮管影子1]
image: 管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 3
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/t3影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.65
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/小支撑.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-30
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.9
[decal_覆盖]
image: 三级机枪塔底座.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret:1
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: ROOT:/创世纪军事集团/建筑特效/防御塔t3底座.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/防御塔t1死亡.png
image_turret: 三级机枪塔底座.png
image_offsetY: -6

image_back: ROOT:/通用特效/NO.png
#AUTO
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 16

turretTurnSpeed: 6
maxAttackRange: 350


[turret_1]
x: 0
y: 30
canShoot: false
#idleSpin:0.8
canAttackCondition: if self.resource.xk < 1

idleSweepAngle: 100
idleSweepDelay: 210
idleSweepSpeed: 0.2
#idleSweepAddRandomAngle:90


[turret_2]
x: 6
y: 16
attachedTo: 1
slave: true
shoot_flame: small,CUSTOM:弹壳右

shoot_sound: ROOT:/创世纪军事集团/建筑特效/机枪塔音效.ogg
shoot_sound_vol: 0.1
image: 三级机枪塔枪管.png
recoilOffset: -4
delay: 10

projectile: 1
canAttackCondition: if self.resource.xk < 1


[turret_3]
x: -6
y: 16
copyFrom: 2
shoot_flame: small,CUSTOM:弹壳左


[projectile_1]
@copyFromSection: template_动能
directDamage: 20
life: 240
speed: 10
targetSpeed: 10

deflectionPower: -1
frame: 5
mutator1_ifUnitWithTags: 飞机
mutator1_directDamageMultiplier: 3
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator996_ifUnitWithTags: 步兵
mutator996_directDamageMultiplier: 2
mutator997_ifUnitWithTags: 伴生单位
mutator997_directDamageMultiplier: 3

[projectile_2]
directDamage: 0
life: 0
speed: 0
targetSpeed: 0


[effect_弹壳左]
priority: high
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: -1.2
xSpeedRelativeRandom: -0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -33
xOffsetRelative: -5

hSpeed: 3
dirSpeedRandom: 50


[effect_弹壳右]
priority: high
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 1.2
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -33
xOffsetRelative: 5

hSpeed: 3
dirSpeedRandom: 50


[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/单位特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.22
noneInBaseExtraPriority: 0.17
maxEachBase: 3


