


[hiddenAction_瞄准坐标]
autoTriggerOnEvent: created
addWaypoint_type: attack
addWaypoint_target_nearestUnit_tagged: 飞机目标
addWaypoint_target_nearestUnit_team: enemy
addWaypoint_target_nearestUnit_maxRange: 9

addWaypoint_triggerActionIfFailed: 补偿1
addWaypoint_triggerActionIfMatched: a1


[hiddenAction_a1]
setUnitMemory: nextTarget = activeWaypointTarget


[hiddenAction_a2]
autoTrigger: if self.timeAlive > 5 and attacking == nullUnit and self.isEnergyFull()
addWaypoint_type: attack
addWaypoint_target_fromReference: memory.nextTarget


[hiddenAction_补偿1]
autoTrigger: if self.timeAlive > 360 and self.isEnergyFull() or self.timeAlive > 2 and not memory.nextTarget.isInMap
# 原本的改成这个
addResources: 4200,蓝晶=450
isVisible: false
deleteSelf: true

showMessageToPlayer: 淦！竟然出现了意外BUG，作为补偿影袭轰炸机的资源费用已退回。


[core]
name: 影袭轰炸机
class: CustomUnitMetadata
displayDescription: -血星是一种强大的鱼雷轰炸机，他们以对战舰毁灭性的伤害而驰名，\n-血星配备两门脉冲激光发射器，以及两枚威力不亚于核弹的攻城鱼雷，\n-这种标准鱼雷轰炸机曾经是亚尔佛里德共和国航母编队的主力机种之一。\n-在反抗亚尔佛里德暴政时期，被血星击沉的舰船不计其数。\n-这种性能优异，价格合算的轰炸机蓝图被余辉所继承，\n-如今依然骄傲的服役于余辉太空军舰载机连队。\n-只能对地，鱼雷爆炸，机枪能源。\n-设计类型：诺瓦帝国 基石计划数据
price: 0
@memory nextTarget: unit

maxHp: 1000
techLevel: 1
buildSpeed: 23s
availableInDemo: true
radius: 44

displayRadius: 44
showInEditor: false
isBio: false
softCollisionOnAll: 10
shieldRenderRadius: 50

energyMax: 1
canNotBeDamaged: true
isUnrepairableUnit: true
isUnselectable: true
canNotBeDirectlyAttacked: true

ignoreInUnitCapCalculation: true
#copyFrom:ROOT:/通用特效/单位防护.ini,ROOT:/余辉军团/SDD科技/血星科技.ini
energyRegen: 0
#energyNeedsToRechargeToFull: true
#armour:18

tags: 飞机,灰机

[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true

[action_返回]
autoTrigger: if self.energy(empty=true)
isVisible: false
addWaypoint_type: move
addWaypoint_target_nearestUnit_tagged: 轨道系统
addWaypoint_target_nearestUnit_team: own
addWaypoint_target_nearestUnit_maxRange:99999
clearAllWaypoints: true


[action_跳跃]
autoTrigger: if self.energy(empty=true) and self.hasUnitInTeam(withTag='轨道系统', withinRange=400)
isVisible: false
deleteSelf: true
spawnEffects: CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:飞机


[action_返回1]
autoTrigger: if self.energy(empty=true) and self.noUnitInTeam(withTag='轨道系统')
isVisible: false
deleteSelf: true
spawnEffects: CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:飞机


[graphics]
total_frames: 1
image: 主体.png
image_wreak: NONE
image_turret: NONE
movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3

movementEffectRate: 0.6
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.9

lock_body_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 850
shootDelay: 1
#attackMovement: bomber
disablePassiveTargeting: true

isFixedFiring: true


[turret_18]
x: 0
y: 25
projectile: 删除坐标
delay: 10
shoot_light: #FF00B3FF

shoot_sound: ROOT:/余辉军团/单位特效/鱼雷.ogg
shoot_sound_vol: 0.3
#limitingAngle: 25
invisible: true
energyUsage: 1

canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
# canAttackCondition:


[projectile_2]
@copyFromSection: template_能源,template_战略武器
areaDamage: 12000
areaRadius: 200
life: 5000
speed: 5

deflectionPower: -1
lightSize: 1.5
lightColor: #FF39FFFF
nukeWeapon: true
drawSize: 0.85

targetSpeed: 5
#disableLeadTargeting:true
image: 导弹.png
shouldRevealFog: true
alwaysVisibleInFog: true

tags: 导弹2
targetGround: true
explodeEffect: CUSTOM:闪光h,CUSTOM:光球,CUSTOM:光球2,CUSTOM:云雾,CUSTOM:云雾2,CUSTOM:云雾1,CUSTOM:聚变x,CUSTOM:冲击波a,CUSTOM:弹坑1,CUSTOM:冲击波b
areaRadiusFromEdge: true
trailEffect: CUSTOM:projectileTrail

#spawnProjectilesOnExplode: 删除坐标
# 爆炸时生成炮弹，如果只发一个导弹的话，改成下面这条更好。
# 因为炮弹即使瞄准的单位没了还是会打到那个单位的位置，然后即使炮弹被拦截了坐标也会清掉。
#spawnProjectilesOnCreate: 删除坐标
# 在创建时刷抛射体


[projectile_删除坐标]
# 用来删除中介的
life: 0
speed: 0
deflectionPower: -1
directDamage: 0

invisible: true
instant: true
explodeEffect: none
explodeEffectOnShield: none
mutator1_ifUnitWithTags: 飞机目标

mutator1_addResourcesDirectHit: ammo= 10
spawnProjectilesOnCreate: 2


[effect_火2]
life: 30
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.15
xOffsetRelative	: 26
yOffsetRelative	: -52


[effect_火1]
life: 30
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.15
xOffsetRelative	: -26
yOffsetRelative	: -52


[effect_火3]
life: 30
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 5

scaleTo: 2
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.15
xOffsetRelative	: 0
yOffsetRelative	: -69


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 2.4
scaleTo: 2.4
alpha: 0.6
drawUnderUnits: false
atmospheric: false

showInFog: true


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4

drawUnderUnits: true
atmospheric: false
showInFog: true


[effect_冲击波1]
life: 130
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.5
alpha: 0.8
showInFog: true
drawUnderUnits: false

atmospheric: true
#——————@——————看NM，给👴爬


[effect_光球]
life: 350
priority: critical
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 1.35

image: ROOT:/余辉军团/单位特效/收缩1.png
ySpeedAbsolute: -0.7
#yOffsetAbsolute:35
fadeOut: true
alpha: 1

showInFog: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg


[effect_光球2]
life: 350
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 1

image: 光球.png
ySpeedAbsolute: -0.7
#drawUnderUnits:true
#yOffsetAbsolute:35
fadeOut: true

showInFog: true
alpha: 1
fadeInTime: 1


[effect_云雾]
life: 360
priority: critical
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 0.65

image: 云雾.png
ySpeedAbsolute: -0.9
#yOffsetAbsolute:90
fadeOut: true
alpha: 1

showInFog: true
fadeInTime: 1


[effect_云雾2]
life: 360
priority: critical
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 0.55

image: 云雾.png
ySpeedAbsolute: -0.8
showInFog: true
#yOffsetAbsolute:90
fadeOut: true

alpha: 1
fadeInTime: 1


[effect_云雾1]
life: 360
priority: critical
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.65

image: 云雾.png
ySpeedAbsolute: -0.7
#yOffsetAbsolute:90
fadeOut: true
alpha: 1

showInFog: true
fadeInTime: 1


[effect_闪光h]
priority: critical
image: SHARED:light_50.png
life: 300
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FFE56BFF
fadeInTime: 2
scaleFrom: 15
scaleTo: 15

showInFog: true
drawUnderUnits: false
atmospheric: false


[effect_聚变x]
priority: critical
image: ROOT:/余辉军团/单位特效/光束1.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 4
scaleTo: 4
alpha: 0.4
drawUnderUnits: false
atmospheric: false

ySpeedAbsolute: -1
showInFog: true
#yOffsetAbsolute:35


[effect_冲击波a]
life: 300
priority: critical
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 0.75

image: 云雾.png
ySpeedAbsolute: -0.7
#yOffsetAbsolute:90
fadeOut: true
alpha: 1

showInFog: true
fadeInTime: 1


[effect_冲击波b]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波4.png
life: 200
fadeOut: true
attachedToUnit: false

scaleFrom: 3
scaleTo: 7
alpha: 1
drawUnderUnits: true
atmospheric: false

#yOffsetAbsolute:90
showInFog: true


[effect_弹坑1]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 400
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 7
scaleTo: 7
createWhenOverLiquid: false
createWhenOverLand: true
#yOffsetAbsolute:35


[effect_飞机]
priority: critical
image: 主体.png
spawnChance: 1
createWhenZoomedOut: false
life: 120

fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1

scaleTo: 1
showInFog: true
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
#dirOffsetRandom:180
#ySpeedRelativeRandom: 0.1
#xSpeedRelativeRandom: 0.6
yOffsetRelative: 0

ySpeedRelative: 12
atmospheric: false


[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.6

drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[movement]
movementType: AIR
moveSpeed: 3.5
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.007
landOnGround: onlyIdle

joinsGroupFormations: false
maxTurnSpeed: 0.8
turnAcceleration: 0.03
moveSlidingMode : false
moveIgnoringBody: false

slowDeathFall: true
targetHeight: 120
startingHeightOffset: 1000


