


[core]
name: 反坦克路障
displayText: Противотанковый барьер
class: CustomUnitMetadata
price: 0
maxHp: 18000
footprint: -1,-1,1,1
constructionFootprint: -3,-3,3,3
techLevel: 1
buildSpeed: 0s

radius: 25
isBio: false
isBuilding: true
effectOnDeath: largeExplosion*1
tags: 中立地面,不检测,建筑
autoTriggerCooldownTime_allowDangerousHighCPU:true
autoTriggerCooldownTime:0.5s

stayNeutral: true
createOnAggressiveTeam: true
isUnrepairableUnit: true
[decal_影子]
image: 石头块影子.png
total_frames: 1
layer: shadow
isVisible: true
yOffsetRelative:-1.5
xOffsetRelative:4
onlyWhileAlive:true
alpha:0.6
imageScale:1
[graphics]
total_frames: 1
image: 石头块.png
image_wreak: 死亡.png
image_back: ROOT:/通用特效/NO.png

image_shadow: NONE


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
maxAttackRange:0


[turret_惩罚]
x: 0
y: 0
projectile: 罚
turnSpeedAcceleration: 20
canShoot: true
turnSpeed: 20
invisible:true

[projectile_罚]
life: 1
speed: 0
areaDamage: 1000
areaRadius: 30
invisible:true
deflectionPower: -1
shieldDefectionMultiplier:0
shieldDamageMultiplier: 0
buildingDamageMultiplier: 0
explodeOnEndOfLife:true
tags: 
explodeEffect:NONE
areaDamageNoFalloff:true
#shouldRevealFog:true
mutator8_ifUnitWithTags:重型工程车
mutator8_directDamageMultiplier: 999
mutator8_areaDamageMultiplier: 999
[action_包]
autoTrigger: true
isVisible: false
fireTurretXAtGround:惩罚
fireTurretXAtGround_withOffset: 0,0
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[ai]
lowPriorityTargetForOtherUnits: true
notPassivelyTargetedByOtherUnits: true






