[core]
name: 飓风导弹
displayText: 飓风导弹
displayDescription: -别玩沙盒了。
price: 0
maxHp: 15000
techLevel: 1
softCollisionOnAll: 20
buildSpeed: 0.0007
radius: 22
fogOfWarSightRange: 12
numBitsOnDeath:0
explodeOnDeath: false
canNotBeGivenOrdersByPlayer: true
showInEditor:false
isBio: false
armour: 50
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 30
energyStartingPercentage: 1
energyRegen: 0
dieOnZeroEnergy: true
effectOnDeath: CUSTOM:碎片
tags:反高空,高空,飞机
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_太麻烦了]
autoTrigger:if self.energy<1
deleteSelf:true

[hiddenAction_装填]
temporarilyAddTags: 扣钱
[hiddenAction_散热]
autoTrigger: if self.tags(includes= '扣钱')
addResources:energy=-1
[decal_遮盖]
image:导弹体.png
total_frames: 1
teamColors: true
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.82
[decal_遮盖1]
image:弹壳.png
total_frames: 1
teamColors: true
layer: onTop
isVisible:true
yOffsetRelative:45
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.82
[action_近距离锁定]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='被锁定',greaterThan= 0)
addWaypoint_target_nearestUnit_tagged:被锁定
addWaypoint_type: attack
addWaypoint_target_nearestUnit_team: enemy
clearAllWaypoints: true
isVisible:false
[action_近距离锁定1]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='被锁定',lessThan=1)
addWaypoint_target_nearestUnit_tagged:地面,飞机
addWaypoint_type: attack
addWaypoint_target_nearestUnit_team: enemy
clearAllWaypoints: true
isVisible:false
[hiddenAction_盘旋1]
requireConditional: if self.hasActiveWaypoint(type= 'attackMove') or self.hasActiveWaypoint(type= 'attack')
autoTrigger: ${section.requireConditional}
autoTriggerOnEvent: newWaypointGivenByPlayer
addWaypoint_type: move
addWaypoint_target_fromReference: activeWaypointTarget.getOffsetRelative(x= 0, y= -700, dirOffset= directionBetween(self, activeWaypointTarget) - activeWaypointTarget.dir + 30 )

alsoTriggerAction: 盘旋2
alsoTriggerOrQueueActionWithTarget: ${section.addWaypoint_target_fromReference}.getOffsetRelative(dirOffset= 120 )


[hiddenAction_盘旋2]
clearActiveWaypoint: true
alsoTriggerAction: 盘旋3
alsoTriggerActionRepeat: 60


[hiddenAction_盘旋3]
addWaypoint_type: move
addWaypoint_target_fromReference: thisActionTarget.getOffsetRelative(x= 0, y= 700, dirOffset= -60 )


#——————————————
[graphics]
total_frames: 1
image: 导弹体.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
splastEffect: true
imageScale: 0.82
turretImageScale: 0.82
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: false
turretSize: 1
turretTurnSpeed: 999
maxAttackRange: 1500
isMelee: true
meleeEngangementDistance: 99999
#attackMovement: bomber
turretMultiTargeting: true
[turret_1]
x: 0
y: -17
invisible:true
canShoot: true
projectile: 1
shoot_sound: missile_fire
shoot_sound_vol: 0.8
shoot_flame: CUSTOM:烟1雾*3
size: 5
canAttackMaxAngle: 181
idleDir: 90
turnSpeed: 999
#limitingAngle: 30
delay: 20
canOnlyAttackUnitsWithTags:被锁定
onShoot_triggerActions:装填
[turret_2]
x: 0
y: -17
copyFrom: 1
idleDir: -90
[turret_3]
x: 0
y: 0
copyFrom: 1
idleDir: -90
[turret_4]
x: 0
y: 0
copyFrom: 1
idleDir: 90
[turret_5]
x: 0
y: 43
canShoot: false
turnSpeed: 999
size:0
turnSpeedAcceleration: 999
image:雷达.png
limitingAngle: 120
[turret_6]
x: 0
y: 50
projectile: 2
delay: 0.5
canShoot: true
aimOffsetSpread: -0.01
turnSpeed: 999
size:0
turnSpeedAcceleration: 999
invisible: true
limitingAngle: 120
canOnlyAttackUnitsWithTags:被锁定

#——<(……□@#？）(……-h——……>
[turret_7]
x: 0
y: -17
invisible:true
canShoot: true
projectile: 1
shoot_sound: missile_fire
shoot_sound_vol: 0.8
shoot_flame: CUSTOM:烟1雾*3
size: 5
canAttackMaxAngle: 181
idleDir: 90
turnSpeed: 999
#limitingAngle: 30
delay: 20
canOnlyAttackUnitsWithoutTags:被锁定
onShoot_triggerActions:装填
canAttackCondition:if numberOfUnitsInEnemyTeam(withTag='被锁定',lessThan=1)
[turret_8]
x: 0
y: -17
copyFrom: 7
idleDir: -90
[turret_9]
x: 0
y: 0
copyFrom: 7
idleDir: -90
[turret_10]
x: 0
y: 0
copyFrom: 7
idleDir: 90
[projectile_1]
@copyFromSection: template_爆炸
directDamage: 400
life: 20
speed: 9
deflectionPower:-1
lightSize: 1.5
lightColor: #FFFFFF73
drawSize: 0.9
targetSpeed: 10
turnSpeed: 0
trailEffect: true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:钢珠
autoTargetingOnDeadTarget: true
spawnProjectilesOnEndOfLife: 锁定
areaRadiusFromEdge: true
#buildingDamageMultiplier: 0.5
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.5
mutator7_areaDamageMultiplier: 0.5
[projectile_2]
directDamage: 0
life: -4
instant: true
frame: 33
beamImage: 光.png
instantReuseLast:true
beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
color: #FFFF1200
explodeEffect: none
[projectile_锁定]
@copyFromSection:projectile_1
life: 99999
targetSpeed: 9
turnSpeed: 4.5
wobbleAmplitude: 4
wobbleFrequency: 100
speed: 9
autoTargetingOnDeadTarget: true
spawnProjectilesOnEndOfLife: NONE
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false
atmospheric: false
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.7
scaleTo: 1.7
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸1.ogg
alwayStartDirAtZero: true

[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.55
scaleTo: 0.2
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -46
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.18
scaleTo: 0.03
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
ySpeedRelative: -0.1
yOffsetRelative	: -46
#drawUnderUnits: true
[effect_烟1雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2
yOffsetRelative: 0.4
ySpeedRelative: 1
atmospheric: true
[effect_碎片]
#priority: high
image: 导弹体.png
spawnChance: 1
life: 200
fadeOut: true
attachedToUnit: false
scaleFrom: 0.82
scaleTo: 0.82
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.35
ySpeedRelativeRandom: 0.35
ySpeedRelative: 1.5
hSpeed: 1.5
dirSpeedRandom: 1

[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0
maxTurnSpeed: 1.4
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false
targetHeight: 140

