


[core]
name: HK石像鬼
displayDescription: 石像鬼的诞生最早能追溯到古人类统一以前，\n-在面对如同潮水一般涌来的敌人时，\n-诺瓦帝国急需一种能够在中远距离压制大量敌人的单位，\n-于是，石像鬼便由此应运而生。\n-千万年之后，余辉重新将他从仓库中找到，\n-并将其搭载的热脉冲炮稍加改进后送回战场，\n-使其从新成为战场上最致命的轻型单位杀手。\n-只能对地。能源伤害，且对建筑效率低
class: CustomUnitMetadata
copyFrom:ROOT:/通用特效/单位防护.ini
price: 2500

maxHp: 150
techLevel: 1
buildSpeed: 22s
radius: 23
isBio: false
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
softCollisionOnAll: 6
tags: 地面,无人单位
energyMax: 80
energyRegen: 0
energyNeedsToRechargeToFull: true
energyStartingPercentage: 0
maxShield: 350
shieldRegen: 0.07
unitsSpawnedOnDeath: 损毁*1
[hiddenAction_DPS]
addResources=energy=1.15
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[decal_炮塔1]
image: HK石像鬼损坏.png
basePositionFromTurret: 1
layer:onTop
isVisible:if self.hp<self.maxHp * 0.36 
onlyWhileAlive:true
#imageScale:0.85
teamColors:true
[graphics]
total_frames: 1
image: HK石像鬼头.png
image_wreak: HK石像鬼死亡.png
image_turret: NONE
image_shadow: NONE

shadowOffsetX: 2
shadowOffsetY: 2
lock_body_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 32

turretTurnSpeed: 4
maxAttackRange: 305
aimOffsetSpread: -0.01
turretRotateWithBody: false
shootDelay: 1


[turret_1]
x: 0
y: 0
idleDir: 0
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
canShoot: false


[turret_2]
x: 0
y: 0
attachedTo: 1
projectile: 1
invisible: true

turnSpeed: 2.9
turnSpeedAcceleration: 0.3
shoot_sound: NONE
shoot_sound_vol: 0.5
shoot_flame: NONE

canShoot: true

shoot_light: #FF4DD3F7
canAttackCondition: if self.resource.xk < 1
#energyUsage:-0.01
onShoot_triggerActions: DPS
[turret_3]
x: 0
y: 0
attachedTo: 1
projectile: 2
turnSpeed: 2.9

turnSpeedAcceleration: 0.3
shoot_sound: ROOT:/通用特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 180
canShoot: true

invisible: true
canAttackCondition: if self.resource.xk < 1
[turret_4]
x: 0
y: 0
attachedTo: 1
projectile: 3
invisible: true
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
shoot_sound: NONE
shoot_sound_vol: 0.5
canShoot: true
shoot_light: #FF4DD3F7
canAttackCondition: if self.resource.xk < 1
energyUsage:2.3

[projectile_1]
@copyFromSection: template_能源
directDamage: 4
life: -4
instant: true
frame: 33
beamImage: 光.png
beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
color: #FF4DD3F7
explodeEffect: none

[projectile_2]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1
[projectile_3]
@copyFromSection: template_能源
areaDamage: 48
areaRadius: 50
life: -4
instantReuseLast: true
instant: true
laserEffect: true
color: #FF4DD3F7
lightColor: #FF4DD3F7
lightSize: 0.5
explodeEffect: CUSTOM:闪光,CUSTOM:闪光2
areaRadiusFromEdge: true
buildingDamageMultiplier: 0.3

[effect_闪光]
life: 5
spawnChance: 1
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.4
image: ROOT:/余辉军团/单位特效/光束.png
dirOffsetRandom: 180
[effect_闪光2]
image: SHARED:light_50.png
life: 10
fadeOut: true
alpha: 0.3
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false

atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/激光.ogg

[leg_1]
x: -17
y: 0
attach_x: -10
attach_y: 0
moveSpeed: 2.1

rotateSpeed: 7
heightSpeed: 0.8
resetAngle: 25
image_leg: leg.png
image_foot: foot_med.png

hidden: if self.hasParent()
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 21
holdDisMax: 36


[leg_2]
x: 17
y: 0
attach_x: 10
attach_y: 0
copyFrom: 1

[movement]
moveSpeed: 0.6
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 3.5
turnAcceleration: 0.5
moveSlidingMode : false
moveIgnoringBody: false
movementType: OVER_CLIFF
reverseSpeedPercentage: 0

