


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=550


[core]
name: SDSF类星体级航空母舰
displayText: SDSF Авианосец класса «Квазар»
displayDescription: -типзвездателоуровеньударавианосец прототип, это младшийЭльфвнутри добродетельИмперия тип планетабоевойогневая мощьподдержкакорабль.\n-в Война Государств эпохи Древних Людей (период), опираясь насвирепый огневая мощь и мощный машинадвижение, \n-этот типвоенный кораблькогда-то даватьвосстаниеармиястроить стать не малый  проблема, \n-в Империя Новастроитьстоятьпозади , типзвездателоуровеньпотому чтодля превосходный установкарасчёт, а Императортяжёлый новый переоборудованныйи рядоснащатьИмперия Новафлот.\n-новыйновый  типзвездателоуровеньударполётматьэто не сложитьне застёжка воздушныйв зломагия, \n-но от к переоборудованныйоснованизна пределне высокий , типзвездателонет методв космосбоевойв проявлениеделатьиспользует .\n-но его оружиепо-прежнемув планетаатакаподдержкабоевойв оченьэффективный, \n-не теориякак , типзвездателоточнореальныйэто эффективный, а смертоносный оружие.\n-по земле и воздуху, взрыв ракеты, другие может источник, истребительвзрыв.
class: CustomUnitMetadata
maxShield: 10000
shieldRegen: 0.1

price: 9000, 蓝晶= 1000
maxHp: 7000
shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 55s

availableInDemo: true
radius: 83
shieldRenderRadius: 54
displayRadius: 83
isBio: false

transportSlotsNeeded: 20
effectOnDeathGroundCollision: CUSTOM:爆炸x*1
softCollisionOnAll: 20

armour: 20
fogOfWarSightRange: 37
tags: 飞机,低空,无人单位
copyFrom: ROOT:/通用特效/单位防护.ini
maxTransportingUnits: 10

transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=540, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=540, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[turret_233]
x: 0
y: 160
projectile: 233
delay: 2.2s
canAttackMaxAngle: 181

canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true


[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true


[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 10
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 10
addUnitsIntoTransport: SDD黄蜂无人机


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1


[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)
[graphics]
total_frames: 3
image: 身体.png
image_wreak: 死亡.png
#image_turret:NONE
showTransportBar: false

teamColorsOnTurret: true
image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
image_shield: 护盾.png

turretImageScale: 0.8
movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3
movementEffectRate: 1.5
animation_moving_start: 2
animation_moving_end: 2

animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 900
shootDelay: 0


[turret_2]
x: 3
y: 11
projectile: 1
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3

shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾1*3
canShoot: true
limitingRange: 440
recoilOffset: -6

recoilOutTime: 7
recoilReturnTime: 35
delay: 120
limitingMinRange: 220
image: 炮管.png

attachedTo: 1
slave: true


[turret_3]
x: -3
y: 11
projectile: 1
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3

shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾1*3
canShoot: true
recoilOffset: -6
recoilOutTime: 7

recoilReturnTime: 35
delay: 120
limitingRange: 440
limitingMinRange: 220
image: 炮管.png

attachedTo: 1
slave: true
warmup: 12


[turret_4]
x: 0
y: 11
projectile: 1
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3

shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾1*3
canShoot: true
recoilOffset: -6
recoilOutTime: 7

recoilReturnTime: 35
delay: 120
limitingRange: 440
limitingMinRange: 220
image: 炮管.png

warmup: 6
attachedTo: 1
slave: true


[turret_1]
x: 16
y: -70
canShoot: false
limitingAngle: 50
idleDir: 90

limitingMinRange: 220
limitingRange: 440
image: 炮台.png


[turret_6]
x: 3
y: 11
projectile: 1
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3

shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾1*3
canShoot: true
recoilOffset: -6
recoilOutTime: 7

recoilReturnTime: 35
delay: 120
limitingMinRange: 220
limitingRange: 440
image: 炮管.png

attachedTo: 5
slave: true


[turret_7]
x: -3
y: 11
projectile: 1
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3

shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾1*3
canShoot: true
recoilOffset: -6
recoilOutTime: 7

recoilReturnTime: 35
delay: 120
limitingRange: 440
limitingMinRange: 220
image: 炮管.png

attachedTo: 5
slave: true
warmup: 12


[turret_8]
x: 0
y: 11
projectile: 1
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3

shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾1*3
canShoot: true
recoilOffset: -6
recoilOutTime: 7

recoilReturnTime: 35
limitingRange: 440
delay: 120
limitingMinRange: 220
image: 炮管.png

warmup: 6
attachedTo: 5
slave: true


[turret_5]
x: -16
y: -70
canShoot: false
limitingAngle: 50
idleDir: -90

limitingMinRange: 220
limitingRange: 440
image: 炮台.png


[turret_9]
x: -25
y: 53
canShoot: true
image: 导弹.png
projectile: 2

shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾1*2
shoot_light: #FFEECCCC
canAttackLandUnits: false

limitingRange: 440
size: 0
canAttackMaxAngle: 181
limitingMinRange: 180
idleDir: -90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
delay: 100


[turret_10]
x: -25
y: 57
limitingRange: 440
canShoot: true
image: 导弹.png

projectile: 2
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾1*2
shoot_light: #FFEECCCC

limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: -90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
warmup: 10

delay: 100


[turret_11]
x: 25
y: 53
canShoot: true
image: 导弹.png
limitingRange: 440

projectile: 2
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾1*2
shoot_light: #FFEECCCC

canAttackLandUnits: false
size: 0
limitingMinRange: 180
canAttackMaxAngle: 181
idleDir: 90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
delay: 100


[turret_12]
x: 25
y: 57
canShoot: true
image: 导弹.png
limitingMinRange: 180

projectile: 2
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾1*2
shoot_light: #FFEECCCC

canAttackLandUnits: false
limitingRange: 440
size: 0
canAttackMaxAngle: 181
idleDir: 90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
warmup: 10

delay: 100


[turret_13]
x: -14
y: 22
#invisible: true
projectile: 3
delay: 2

shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/小激光.ogg
shoot_sound_vol: 0.7
limitingAngle: 50

size: 10
canAttackLandUnits: false
idleDir: -90
image: 枪.png
limitingRange: 440


[turret_14]
x: 14
y: 22
#invisible: true
projectile: 3
delay: 2

shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/小激光.ogg
shoot_sound_vol: 0.7
limitingAngle: 50

size: 10
canAttackLandUnits: false
idleDir: 90
image: 枪.png
limitingRange: 440


[projectile_1]
@copyFromSection: template_能源
areaDamage: 150
areaRadius: 50
life: 100
speed: 9

image: ROOT:/余辉军团/单位特效/星星.png
drawSize: 0.55
lightSize: 1.5
lightColor: #FF00B3FF
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:大爆炸

explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:大爆炸
trailEffect: CUSTOM:尾巴
trailEffectRate: 0.7
areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0


[projectile_2]
@copyFromSection: template_爆炸
directDamage: 100
life: 350
speed: 5
#deflectionPower:-1

lightSize: 1.5
lightColor: #FF39FFFF
drawSize: 0.7
targetSpeed: 8
turnSpeed: 4

trailEffect: true
image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:爆炸1,CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸1,CUSTOM:闪光
autoTargetingOnDeadTarget: true


[projectile_3]
@copyFromSection: template_能源
directDamage: 15
life: 100
speed: 8
targetSpeed: 9

image: ROOT:/余辉军团/单位特效/长炮弹.png
deflectionPower: -1
drawSize: 0.55
lightSize: 0.6
lightColor: #FF00B3FF

explodeEffect: CUSTOM:爆炸2
explodeEffectOnShield: CUSTOM:爆炸2
#shieldDamageMultiplier:2


[effect_爆炸2]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/碎裂.png
total_frames: 8

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_大爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1

scaleTo: 1
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸1]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[effect_爆炸]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.35
image: ROOT:/余辉军团/单位特效/自制.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2


[effect_火2]
life: 45
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.6
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 9
yOffsetRelative	: -123


[effect_火1]
life: 45
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.6
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: -9
yOffsetRelative	: -123


[effect_火3]
life: 55
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.7
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 0
yOffsetRelative	: -123


[effect_烟雾1]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8

ySpeedRelative: 1.5
atmospheric: true


[effect_爆炸x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/余辉军团/单位特效/爆炸25.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[attachment_drone1]
x: -30
y: -40
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1


[attachment_drone2]
x: 30
y: -40
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1


[attachment_drone3]
x: 0
y: 140
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1


[attachment_drone4]
x: 0
y: 90
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1


[attachment_drone5]
x: 0
y: 80
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1


[attachment_drone6]
x: 0
y: 70
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1

[attachment_drone7]
x: -30
y: -50
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1
[attachment_drone8]
x: 30
y: -50
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1
[attachment_drone9]
x: -30
y: -60
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1
[attachment_drone10]
x: 30
y: -60
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false

addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: true
lockRotation: true
#height:1

[arm_1]
x: 31
y: -70
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: -31
y: -70
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: -26
y: 22.3
image_end: 左盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 26
y: 22.3
image_end: 右盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:-45, y:0}
arm1_950s: {x:-45, y:0}
arm2_1s: {x:45, y:0}

arm2_950s: {x:45, y:0}
arm3_1s: {x:40, y:0}
arm3_950s: {x:40, y:0}
arm4_1s: {x:-40, y:0}
arm4_950s: {x:-40, y:0}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}

arm4_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 1
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 1.3
turnAcceleration: 0.05
targetHeightDrift: 0.3

slowDeathFall: true
targetHeight: 70


[ai]
buildPriority: 0.9


