


[core]
name: 火焰1
class: CustomUnitMetadata
price: 100
maxHp: 1200
armour: 30000

canOnlyBeAttackedByUnitsWithTags:消防
energyMax: 2000
energyRegen: -1
dieOnZeroEnergy: true
techLevel: 1
canNotBeDamaged: true
buildSpeed: 0

showOnMinimap:false
isUnselectable: true
numBitsOnDeath: 0
showInEditor: false
hideScorchMark: true
explodeOnDeath: false
radius: 0
isBio: false
isBuilding: true
softCollisionOnAll: 0
fogOfWarSightRange: 5

tags:危险物品
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_扫雷]
autoTrigger: if self.hasFlag(id=1)
deleteSelf: true
[action_t1]
autoTrigger: if self.isOverLiquid
isVisible: false
addResources: hp=-9999999

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
spawnEffects: CUSTOM:弹坑
[graphics]
total_frames: 1
image: 弹坑.png
image_wreak: NONE
image_turret: NO.png
image_shadow: NONE

shadowOffsetX: 1
shadowOffsetY: 1
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 40
maxAttackRange: 9999
shootDelay: 1
aimOffsetSpread: -0.01

[turret_烟雾]
x: 0
y: 0
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 15

invisible: true


[turret_烟雾2]
x: 0
y: 18
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 15

invisible: true


[turret_烟雾3]
x: 16
y: 8
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 15

invisible: true
size: 1


[turret_火焰]
x: 0
y: 0
projectile: 13
shoot_flame: CUSTOM:火焰
delay: 4

invisible: true
size: 1


[turret_火焰2]
x: 0
y: 18
projectile: 13
shoot_flame: CUSTOM:火焰, CUSTOM:闪光wy
delay: 5

invisible: true
size: 1


[turret_火焰3]
x: 16
y: 8
projectile: 13
shoot_flame: CUSTOM:火焰
delay: 3

invisible: true
size: 1


[turret_shock]
#area shock turret
x: 0
y: 0
invisible: true
canAttackFlyingUnits: true

canAttackLandUnits: true
canAttackUnderwaterUnits: false
limitingRange: 4000000
projectile: 1
turnSpeed: 5.0

shoot_sound: NONE
shoot_sound_vol: 0.9
shoot_flame: NONE
canShoot: true
size: 0

delay: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[projectile_1]
areaDamage: 50
areaRadius: 80
speed: 11
life: 1
instant: false

largeHitEffect: false
explodeOnEndOfLife: true
deflectionPower: -1
buildingDamageMultiplier: 1.5
explodeEffect: NONE

explodeEffectOnShield: NONE
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_烟雾]
stripIndex: smoke_black
life: 100
fadeOut: true
attachedToUnit: true
fadeInTime: 0.8

scaleTo: 3
scaleFrom: 2
alpha: 0.8
hSpeed: 1
drawUnderUnits: false

atmospheric: false
spawnChance: 1
xSpeedAbsoluteRandom: 0.3
alsoPlaySound: ROOT:/通用特效/燃烧.ogg
[effect_闪光wy]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FFFFFF86
priority: critical
fadeInTime: 2
scaleFrom: 2
scaleTo: 0.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
[effect_火焰]
stripIndex: projectiles
life: 30
frameIndex: 3
fadeOut: true
attachedToUnit: true

fadeInTime: 0.8
scaleTo: 4
scaleFrom: 2
alpha: 0.8
hSpeed: 1

drawUnderUnits: false
atmospheric: false
spawnChance: 1
xSpeedAbsoluteRandom: 0.5

[effect_弹坑]
image: 弹坑.png
spawnChance: 1
life: 600
attachedToUnit: false
drawUnderUnits: true
alwayStartDirAtZero: true
scaleFrom: 1
scaleTo: 1
createWhenOverLiquid: false
createWhenOverLand: true
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.1
maxTurnSpeed: 0

turnAcceleration: 0.1
moveSlidingMode : false
moveIgnoringBody: false


