


[core]
name: big通用炮塔
displayText: bigпроходиспользует турель
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags: 激光炮塔
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true


[hiddenAction_akm]
autoTrigger: if not self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") == null
addResources: setFlag=1
playAnimationIfNotPlaying: attack
[hiddenAction_bkm]
autoTrigger: if self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") != null

alsoQueueAction: bx1

[hiddenAction_bx1]
buildSpeed:0s
addResources:unsetFlag=1
stopLastAnimation:true
playAnimation: attack1
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 1100 | setFlag= 0)
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false
hidden: true
[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 1100| setFlag= 0)
[decal_中影子]
image: SHADOW:中.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:4
xOffsetRelative:5
onlyWhileAlive:true
imageScale: 1
alpha:0.7
basePositionFromLegEnd: arm_1
[decal_左影子]
image: SHADOW:左.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:4
xOffsetRelative:5
onlyWhileAlive:true
imageScale: 1
alpha:0.7
basePositionFromLegEnd: arm_2
[decal_右影子]
image: SHADOW:右.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:4
xOffsetRelative:5
onlyWhileAlive:true
imageScale: 1
alpha:0.7
basePositionFromLegEnd: arm_3
[decal_左边影子]
image: SHADOW:左边.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:4
xOffsetRelative:5
onlyWhileAlive:true
imageScale: 1
alpha:0.7
basePositionFromLegEnd: arm_4
[decal_右边影子]
image: SHADOW:右边.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:4
xOffsetRelative:5
onlyWhileAlive:true
imageScale: 1
alpha:0.7
basePositionFromLegEnd: arm_5
[decal_炮台影子]
image: SHADOW:炮台.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:4
xOffsetRelative:5
onlyWhileAlive:true
imageScale: 1
alpha:0.7
basePositionFromLegEnd: arm_6


#——————————贴画覆盖






[decal_左覆盖]
image: 左.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 1
basePositionFromLegEnd: arm_2
[decal_左损坏]
image: 左损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if parent.hp < parent.maxHp * 0.36
alpha:1
basePositionFromLegEnd: arm_2
[decal_左led]
image:左led.png
total_frames: 1
layer: onTop
isVisible:if parent.maxHp * 0.36 < parent.hp
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_2



[decal_右覆盖]
image: 右.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 1
basePositionFromLegEnd: arm_3
[decal_右损坏]
image: 右损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if parent.hp < parent.maxHp * 0.36
alpha:1
basePositionFromLegEnd: arm_3
[decal_右led]
image:右led.png
total_frames: 1
layer: onTop
isVisible:if parent.maxHp * 0.36 < parent.hp
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_3



[decal_左边覆盖]
image: 左边.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 1
basePositionFromLegEnd: arm_4
[decal_左边损坏]
image: 左边损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if parent.hp < parent.maxHp * 0.36
alpha:1
basePositionFromLegEnd: arm_4
[decal_左边led]
image:左边led.png
total_frames: 1
layer: onTop
isVisible:if parent.maxHp * 0.36 < parent.hp
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_4






[decal_右边覆盖]
image: 右边.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 1
basePositionFromLegEnd: arm_5
[decal_右边损坏]
image: 右边损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if parent.hp < parent.maxHp * 0.36
alpha:1
basePositionFromLegEnd: arm_5
[decal_右边led]
image:右边led.png
total_frames: 1
layer: onTop
isVisible:if parent.maxHp * 0.36 < parent.hp
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_5




[decal_炮台覆盖]
image: 炮台.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 1
basePositionFromLegEnd: arm_6
[decal_炮台损坏]
image: 炮台损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if parent.hp < parent.maxHp * 0.36
alpha:1
basePositionFromLegEnd: arm_6
[decal_炮台led]
image:炮台led.png
total_frames: 1
layer: onTop
isVisible:if parent.maxHp * 0.36 < parent.hp
yOffsetRelative:-12.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromLegEnd: arm_6
alpha:0.9
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
isVisible:if not parent.hasParent
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 853

disablePassiveTargeting: true
isFixedFiring: true
turretSize: 24
turretTurnSpeed: 2

shootDelay: 0.9
aimOffsetSpread: 0
[turret_1]
x: 0
y: 43
projectile: 233
canShoot: true
shoot_sound: ROOT:/通用特效/巨大激光.ogg
shoot_sound_vol: 0.5
delay: 180
warmup:120
invisible: true
warmupStartEffect:CUSTOM:音效
size:20
attachedTo: 4
limitingMinRange: 200
slave: true
canAttackFlyingUnits: false
canAttackCondition: if parent.resource.xk < 1 and self.hasFlag(id= 1) and not parent.hasParent
[turret_2]
x: 0
y: 24
projectile: 1
shoot_sound: ROOT:/通用特效/巨大激光.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾*9,CUSTOM:闪光fs,CUSTOM:冲击波fs1,CUSTOM:闪光fs1,CUSTOM:实验,CUSTOM:聚变nk,CUSTOM:光子*12
shoot_light: #FF00B3FF
canShoot: true
recoilOffset: -5
recoilOutTime: 3
recoilReturnTime: 100
delay: 180
warmup:120
canAttackCondition: if parent.resource.xk < 1 and self.hasFlag(id= 1) and not parent.hasParent
size:23
attachedTo: 4
slave: true
canAttackFlyingUnits: false
aimOffsetSpread:0
invisible:true
limitingMinRange: 200
chargeEffectImage: ROOT:/余辉军团/单位特效/小闪光.png
[turret_3]
x: 0
y: 24
projectile: 233
canShoot: true
shoot_flame: CUSTOM:汇聚*4,CUSTOM:冲击波1
delay: 10
invisible: true
size:23
limitingMinRange: 200
attachedTo: 4
slave: true
canAttackFlyingUnits: false
canAttackCondition: if parent.resource.xk < 1 and self.hasFlag(id= 1) and not parent.hasParent
[turret_4]
x: 0
y: 0
canShoot: false
canAttackFlyingUnits: false
invisible:true
canAttackCondition: if parent.resource.xk < 1 and self.hasFlag(id= 1) and not parent.hasParent
limitingMinRange: 200


[projectile_1]
areaDamage: 0
areaRadius: 0
spawnUnit: 闪电球(offsetHeight=0,offsetDir=0)
life: 0
speed: 0
#deflectionPower:-1
lightSize: 0
drawSize: 0
targetSpeed: 0
turnSpeed: 0
frame:1
explodeOnEndOfLife:true
explodeEffect:NONE


[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[arm_1]
x: 0
y: 36
image_end:中.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:20
drawDirOffset: 0
[arm_2]
x: -15
y: 36
image_end:左.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:20
drawDirOffset: 0
[arm_3]
x: 15
y: 36
image_end:右.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:20
drawDirOffset: 0
[arm_4]
x: -30
y: 8
image_end:左边.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:20
drawDirOffset: 0
[arm_5]
x: 30
y: 8
image_end:右边.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:20
drawDirOffset: 0
[arm_6]
x: 0
y: 0
image_end:炮台.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:20
drawDirOffset: 0




[animation_attack]
blendIn: 0.005s
blendOut: 0.005s
#onActions: attack

arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}



arm1_1s: {x:0, y:10, dir:0}
arm2_1s: {x:-5, y:15, dir:0}
arm3_1s: {x:5, y:15, dir:0}
arm4_1s: {x:-7, y:-4, dir:-60}
arm5_1s: {x:7, y:-4, dir:60}

arm1_99999s: {x:0, y:10, dir:0}
arm2_99999s: {x:-5, y:15, dir:0}
arm3_99999s: {x:5, y:15, dir:0}
arm4_99999s: {x:-7, y:-4, dir:-60}
arm5_99999s: {x:7, y:-4, dir:60}

[animation_attack1]

#onActions: attack
arm1_0s: {x:0, y:10, dir:0}
arm2_0s: {x:-5, y:15, dir:0}
arm3_0s: {x:5, y:15, dir:0}
arm4_0s: {x:-7, y:-4, dir:-60}
arm5_0s: {x:7, y:-4, dir:60}

arm1_0.1s: {x:0, y:10, dir:0}
arm2_0.1s: {x:-5, y:15, dir:0}
arm3_0.1s: {x:5, y:15, dir:0}
arm4_0.1s: {x:-7, y:-4, dir:-60}
arm5_0.1s: {x:7, y:-4, dir:60}


arm1_1s: {x:0, y:0, dir:0}
arm2_1s: {x:0, y:0, dir:0}
arm3_1s: {x:0, y:0, dir:0}
arm4_1s: {x:0, y:0, dir:0}
arm5_1s: {x:0, y:0, dir:0}

#————————————蓄力效果
[effect_汇聚]
priority: low
image: ROOT:/通用特效/旋转光效.png
dirOffsetRandom: 360
dirSpeed: 1
dirSpeedRandom: 0.5
life: 60
scaleFrom: 0.5
scaleTo: 0
alpha: 0.9
drawUnderUnits: false
attachedToUnit: true
atmospheric: false
delayedStartTimerRandom:30
[effect_冲击波1]
stripIndex: shockwave
life: 33
scaleFrom: 2
scaleTo: 0.1
alpha: 0.7
color: #FF00B3FF
#————————————主炮开火
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.6
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true
[effect_闪光fs]
image: SHARED:light_50.png
life: 45
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 7
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:ROOT:/余辉军团/单位特效/蓄力.ogg
priority: critical

[effect_冲击波fs1]
color: #FF00B3FF
life: 50
priority: critical
attachedToUnit: false
alpha: 0.8
fadeOut: true
fadeInTime: 2
scaleFrom: 0.6
scaleTo: 0.9
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: false


[effect_闪光fs1]
image: SHARED:light_50.png
life: 70
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 3
drawUnderUnits: false
atmospheric: false
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.6
scaleTo:1.2
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180
[effect_聚变nk]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 18
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 2
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 62
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.6
scaleTo: 0.6
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 1
ySpeedRelative: 2
ySpeedRelativeRandom: 0.5
priority: low

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 1
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


