
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=300
[core]
name: 罪堕之眼
displayText: Око Падшего
class: CustomUnitMetadata
displayDescription: 【Уровень t4】【Механический юнит】【Наземный юнит】【Парящий юнит】【Беспилотный юнит】\n-【Защита от тактического оружия】【Амфибия】тактическое назначение: тяжёлая осадная артиллерия, размер юнита:12, \n-вооружение:▲осадная плазменная пушка только по земле энергетический урон усиленный урон по зданиям и сверхтяжёлым юнитам \n-▲тройная плазменная пушкаX2 только по земле энергетический урон \n-▲лазерная установка ближнего бояX2 по земле и воздуху энергетический урон. \n-конструкторское бюро Утомирдолжен имперский флот требование, иглапротив трудночтобы атакаодолеть крепость, а битьстроить  тяжёлыйпушкасолдат.\n-Этот машинадвижениепушкасолдатплатформа оригиналразумоченьпростойодиночный, один тяжёлыйантигравитационное шасси, \n-снаружи добавитьодиндверьплазмаантикорабльпушка, тогдаструктурастать звёздная системавнутрисамыйдля смертоносный осадапушкасолдатюнит.\n-Око Падшегооснащатьрезерв главное орудие, от военный корабль антикорабльплазменная пушкамодифицированный, а приходит , не толькодальностьпревосходный, \n-мощьболее это может превзойтиорбитальный флот прямоартобстрел, \n-в нетимеет орбитальный флотпушкаогоньприкрытие, когда , от Око Падшегогруппастать  пушкасолдатвойска, \n-будетбудетзаменаЕго Величество Император священныйфлотпротив любойосквернятьспускпод уничтожение железодождь.
price: 7000,蓝晶=330
maxHp: 5000
maxShield: 5000
shieldRenderRadius: 0
shieldRegen: 0.1
fogOfWarSightRange: ${int(attack.maxAttackRange/17.5)}
techLevel: 1
buildSpeed: 17s
radius: 80
displayRadius: 80
tags: 地面,无人单位,罪堕之眼
transportSlotsNeeded: 12
isBio: false
softCollisionOnAll: 17
armour: 40
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:中余晖单位死亡冲击波,CUSTOM:中余晖单位死亡爆炸,CUSTOM:中余晖单位死亡钢珠,CUSTOM:中余晖单位死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:6)
energyMax: 10
energyRegen: 0.005
energyNeedsToRechargeToFull: true
[hiddenAction_创造]
autoTrigger: if attachment(slot= '1') == nullUnit
attachments_onlyOnSlots: 1
attachments_addNewUnits:big通用炮塔
[attachment_1]
x: 0
y: -5
isUnselectable:true
onCreateSpawnUnitOf: big通用炮塔
lockRotation: false
resetRotationWhenNotAttacking:true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: false
#setDrawLayerOnTop:true
idleDir:0

[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:6
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.5
[decal_主体损坏]
image: 主体损坏.png
total_frames: 1
layer: afterBody
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[decal_机体灯]
image:主体led.png
total_frames: 1
layer: afterBody
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.8
[decal_小炮影子]
image: SHADOW:小炮.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:3
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 4
imageScale: 0.8
alpha:0.5
[decal_小炮影子1]
image: SHADOW:小炮.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:3
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 8
imageScale: 0.8
alpha:0.5
[decal_pd影子]
image: SHADOW:雷达.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:3
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 9
imageScale: 1
alpha:0.5
[decal_pd影子1]
image: SHADOW:雷达.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:3
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 11
imageScale: 1
alpha:0.5
[decal_pd]
image: 雷达.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 9
imageScale: 1
[decal_pd1]
image: 雷达.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 11
imageScale: 1

[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: beforeUI
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:6
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1.2


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: NONE
teamColorsOnTurret: true
turretImageScale: 0.8
movementEffect: CUSTOM:地面,CUSTOM:水波x,CUSTOM:火
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 30
turretMultiTargeting: true
maxAttackRange: 850
[turret_1]
x: -5.5
y: 25
attachedTo: 4
slave: true
shoot_light: #FF00B3FF
image: 炮管.png
shoot_flame: CUSTOM:烟雾*2
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.2
recoilOffset: -6
recoilOutTime: 5
recoilReturnTime: 25
projectile: 1
size: 12
canAttackFlyingUnits: false
delay:120
limitingRange: 600
turnSpeed: 1.2
canAttackCondition: if self.resource.xk < 1
turnSpeedAcceleration: 0.07
[turret_2]
x: 0
y: 25
copyFrom: 1
delay:110
warmup:10

[turret_3]
x: 5.5
y: 25
copyFrom: 1
delay:100
warmup:20
[turret_4]
x: -37
y: 54
canShoot: false
recoilOffset: -1
image: 小炮.png
recoilOutTime: 7
recoilReturnTime: 12
canAttackFlyingUnits: false
limitingRange: 600
canAttackCondition: if self.resource.xk < 1
limitingAngle: 100
idleDir:-35
[turret_5]
x: -5.5
y: 25
copyFrom: 1
delay:120
attachedTo: 8
slave: true
[turret_6]
x: 0
y: 25
copyFrom: 1
delay:110
warmup:10
attachedTo: 8
slave: true
[turret_7]
x: 5.5
y: 25
copyFrom: 1
delay:100
warmup:20
attachedTo: 8
slave: true
[turret_8]
x: 37
y: 54
copyFrom: 4
limitingAngle: 70
idleDir:35


[turret_9]
x: -39
y: -62
canShoot: false
image: NO.png
idleDir:-135
canAttackCondition: if self.resource.xk < 1
turnSpeed: 3
turnSpeedAcceleration: 4
limitingRange: 600
limitingAngle: 100
canOnlyAttackUnitsWithoutTags:高空
[turret_10]
x: 0
y: 5
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FF00B3FF
shoot_flame: NONE
invisible: true
delay: 50
projectile: beam01
size: 7
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup:10
canAttackCondition: if self.resource.xk < 1
attachedTo: 9
slave: true
canOnlyAttackUnitsWithoutTags:高空
limitingRange: 600
[turret_11]
x: 39
y: -62
copyFrom: 9
idleDir:135
[turret_12]
x: 0
y: 5
copyFrom: 10
attachedTo: 11
slave: true
[turret_13]
x: 0
y: 0
projectile: 233
delay: 0.1s
invisible: true
canAttackCondition: if self.resource.xk < 1
canAttackFlyingUnits: false
[turret_14]
x: 0
y: 0
canShoot: true
shoot_sound: ROOT:/余辉军团/单位特效/瓶1.ogg
shoot_sound_vol: 0.3

shoot_flame: NONE
projectile: 2
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay: 10
interceptProjectiles_withTags: 战术武器
interceptProjectiles_andUnderDistance: 1000
interceptProjectiles_andOverHeight: -100
invisible: true
energyUsage: 1.5


[turret_14x]
x: 0
y: 0
copyFrom: 14
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 1000
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:1000
#战术防御天上


[turret_15]
x: 0
y: -5
canAttack: false
invisible: if self.numberOfAttachedUnits(greaterThan= 0)
image:炮.png
# 让建造界面显示时有炮塔



[projectile_1]
@copyFromSection: template_能源
directDamage: 300
life: 200
speed: 11
image: ROOT:/余辉军团/单位特效/子弹.png
targetSpeed: 11
drawSize: 0.67
explodeEffect: CUSTOM:爆炸s, CUSTOM:闪光s,CUSTOM:冲击波s
explodeEffectOnShield: CUSTOM:爆炸s, CUSTOM:闪光s,CUSTOM:冲击波s
lightSize: 0.75
trailEffectRate: 0.85
trailEffect: CUSTOM:尾巴s
lightColor: #FF00B3FF

[projectile_beam01]
@copyFromSection: template_能源
explodeEffect: CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
explodeEffectOnShield: CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
directDamage: 350
life: 3
instant: true
moveWithParent: true
beamImage: ROOT:/通用特效/6.png
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
delayedStartTimer:0
[projectile_beam0]
@copyFromSection: template_能源
explodeEffect: CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
explodeEffectOnShield: CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
directDamage: 400
life: 3
instant: true
moveWithParent: true
beamImage: ROOT:/通用特效/6.png
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
delayedStartTimer:0
[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/5.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/4.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/3.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/2.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/1.png
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE
spawnProjectilesOnEndOfLife: NONE
[projectile_2]
areaDamage: 0
areaRadius: 0
life: 666
speed: 30
targetSpeed: 30

trailEffect: false
image: NO.png
drawSize: 0
largeHitEffect: true
deflectionPower: -1

explodeEffect:CUSTOM:战术防御瓶1,CUSTOM:战术防御波,CUSTOM:战术防御光子*8,CUSTOM:战术防御闪光d

[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
#——#——————三管炮开火
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.2
scaleTo: 1.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.5
ySpeedRelative: 1
atmospheric: true
#——#——————三管炮爆炸
[effect_爆炸s]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2

scaleTo: 1.2
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg

[effect_闪光s]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 0
drawUnderUnits: false
atmospheric: false

[effect_冲击波s]
priority: high
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 28
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_尾巴s]
priority: low
image: ROOT:/余辉军团/单位特效/光束2.png
life: 15
fadeOut: true
attachedToUnit: false

color: #63e6e8
fadeInTime: 0.1
scaleFrom: 0.25
scaleTo: 0.25
alpha: 0.7
drawUnderUnits: false
yOffsetRelative	: -2
atmospheric: true



[effect_地面]
createWhenZoomedOut: false
frameIndex: 0
stripIndex: effects
life: 70
fadeOut: true

attachedToUnit: false
#color: #FFFF1200
fadeInTime: 3
scaleFrom: 7
scaleTo: 10

alpha: 0.4
drawUnderUnits: true
ySpeedRelative: -1
atmospheric: true
createWhenOverLiquid: false
createWhenOverLand: true
[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
life: 130
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo:7.8
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -40
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
createWhenOverLiquid: true
createWhenOverLand: false
[effect_火]
life: 140
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:2
scaleTo: 3.7
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -0.5
yOffsetRelative	: -10
drawUnderUnits: true
createWhenOverLiquid: true
createWhenOverLand: false
[movement]
movementType: HOVER
moveSpeed: 0.8
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.3
maxTurnSpeed: 0.6

turnAcceleration: 0.2
targetHeight: 1
targetHeightDrift: 1
moveSlidingMode : false
moveIgnoringBody: true


