


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=210


[core]
name: SDAF阿吉里恩
displayText: SDAFАджирион
price: 6200,蓝晶=500
maxHp: 2000
maxShield: 6000
shieldRegen: 0.07

displayDescription: -еслинужносказатьИмперия Нова на истинныйв данный момент в потокопора, тогдане Аджирион莫属, \n-в проходитьопытТролльустановкарасчётна  потеряпоражениепозади , Империя Нованаука家всегозавязать错误, \n-конецк будетАджирионбитьстроить закончитьстать , Аджирионэто Империя Новамеховтехнология 集большой стать .\n-этиогромный, а гибкий основноймеховможет лёгкий , а лёгкий举 уничтожитьколичестворазк самсвой основнойтанк.\n-сильный, 威猛, может опираться, нет прочныйне уничтожать, этотэто каждыйодин Пилоты Аджирион машинамастервсе будетдаватьон 评цена.\n-только по земле, главное орудиеможет источник, взрыв ракеты\n-Тип проекта:Империя Нова раз, когда эрарасчётразрезданные
techLevel: 1
buildSpeed: 30s
radius: 52
displayRadius: 52
fogOfWarSightRange: 21
armour: 15
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 3
unitsSpawnedOnDeath: 损毁3*1
tags: 地面,无人单位

energyMax: 5
energyRegen: 0.06
energyNeedsToRechargeToFull: true


[action_1_曲线跳跃]
fireTurretXAtGround: 曲线
text: Кривой прыжок
isVisible: if self.globalTeamTags(includes='曲线核1')
iconImage: ROOT:/余辉军团/单位特效/曲线核1.png
displayType: action

buildSpeed: 0s
pos: 0.1
isLocked: if self.resource.xk > 0
price: 0
#displayRemainingStockpile: true

highPriorityQueue: true
canPlayerCancel: false
onlyOneUnitAtATime: false
description: Активирует кривое ядро, совершая короткий мгновенный прыжок,\n-юнит мгновенно перемещается в указанную точку.
addActionCooldownTime: 12s

isActive: if self.queueSize(lessThan=0.5)


[action_反物质兵器2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/反物质2.png
text: Антиматериальное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='反物质2')


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
addResources: shield=10
text: Позитронное ядро
price: 0
displayType: infoOnlyNoBox

isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_重子兵器2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重子2.png
text: барионное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='重子2')


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 500 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true


[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 500 | setFlag= 0)


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5)
isVisible: false
alsoQueueAction: b



[action_b]
convertTo: SDAF阿吉里恩1
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false

highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 385
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_2]
x: 24
y: 56
attachedTo: 1
invisible: true
projectile: 1

shoot_sound: NONE
canShoot: true
size: 36
delay: 8
energyUsage: 0

slave: true


[turret_曲线]
x: 0
y: 0
canShoot: false
idleDir: 0
invisible: true

size: 1.1
turnSpeed: 40
shoot_sound: NONE
shoot_sound_vol: 0.6
projectile: 炮弹3

limitingRange: 300


[turret_1]
x: 0
y: 0
canShoot: false
#image:身体.png
invisible: true


[projectile_1]
@copyFromSection: template_能源
directDamage: 150
life: 0
speed: 7
image: ROOT:/余辉军团/单位特效/星星.png

drawSize: 0.55
lightSize: 1.5
lightColor: #FF00B3FF
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光*2,CUSTOM:爆炸1
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光*2,CUSTOM:爆炸1

trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1
trailEffectRate: 2


[projectile_炮弹3]
life: 600
directDamage: 0
speed: 70
targetSpeed: 70
drawSize: 0

frame: 1
targetGroundSpread: 8
targetGround: true
deflectionPower: -1
explodeEffect: CUSTOM:闪光c,CUSTOM:冲击波c

teleportSource: true


[effect_爆炸]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.7
image: ROOT:/余辉军团/单位特效/碎裂.png
total_frames: 8

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_爆炸1]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.8
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg

alpha: 2


[effect_尾巴1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[effect_烟雾]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 1
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
atmospheric: true


[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/光束2.png
life: 30
fadeOut: true
attachedToUnit: false

color: #63e6e8
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[arm_1]
#左肩
x: 0
y: 0
image_end: 身体1.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:身体1.png


[arm_6]
#左肩
x: 0
y: -5
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[arm_2]
x: -24
y: -8
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: -10

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_3]
x: 23
y: 37
image_end: 枪.png
image_end_shadow: SHADOW:枪.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -60


[arm_5]
x: -28
y: 30
image_end: 手1.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 30
image_end_shadow: SHADOW:手1.png


[arm_7]
x: 40
y: 31
image_end: 手.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: -60
image_end_shadow: SHADOW:手.png


[arm_4]
x: 20
y: 0
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 35
image_end_shadow: SHADOW:胳膊.png


[arm_8]
x: -24
y: -3
image_end: 导弹.png
image_end_teamColors: true
drawOverBody: true

#drawDirOffset:


[leg_1]
x: -14
y: -1.5
attach_x: -1
attach_y: -1
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: SDAF巨魔腿.png

image_foot: SDAF巨魔脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 14
y: -1.5
attach_x: 1
attach_y: -1
copyFrom: 1

drawDirOffset: 10


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm1_0.6s: {x:0, y:0, dir:15}
arm2_0.6s: {x:3, y:8, dir:20}
arm3_0.6s: {x:-8, y:0, dir:60}

arm4_0.6s: {x:-12, y:0, dir:75}
arm5_0.6s: {x:17, y:10, dir:20}
arm7_0.6s: {x:-5, y:-35, dir:35}


[effect_冲击波c]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3

scaleTo: 0.8
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_闪光c]
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1
attachedToUnit: false

color: #FF39FFFF
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false

atmospheric: false


[movement]
movementType: OVER_CLIFF
moveSpeed: 1.1
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

turnAcceleration: 0.08
targetHeight: 2
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0.4

slowDeathFall: true


