


[core]
name: 太空浪人纳米蜂巢
class: CustomUnitMetadata
price: 2500
maxHp: 10000
selfRegenRate: 0.2

footprint: -4,-1,4,5
constructionFootprint: -4,-1,4,5
techLevel: 1
energyMax: 1
energyRegen: 0

energyStartingPercentage: 1
buildSpeed: 10s
#displayDescription:太空浪人将从战场上收集来的尸体储存于此，\n-并将他们改造成傀儡为自己而战。
radius: 60
isBio: false

copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
exit_x: 0
exit_y: -1

tags: 地面,蜂巢,灰影建筑,建筑
armour: 10


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: 缺少供能
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_断电a]
autoTrigger: if not self.hasFlag(id= 30) and self.queueSize > 0 and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
resetCustomTimer: true
addResources: setFlag= 30


[hiddenAction_断电b]
autoTrigger: if self.hasFlag(id= 30) and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30
refundAllQueuedItems: true


[hiddenAction_来电a]
autoTrigger: if self.hasFlag(id= 30) and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30





[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='蜂巢')
deleteSelf: true
#addResources:威胁点数=-${core.price / 25}
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈


[action_黏性拟态合金护甲1研发]
price: energy=1,800
text: 黏性拟态合金护甲1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,防弹甲1,防爆甲1,红蓝1
iconImage: 红蓝.png
description: -极具弹性与柔韧性的黏性拟态合金打造的防护层，\n-能减少动能和爆炸类武器造成的15%伤害。
showMessageToPlayer: 黏性拟态合金护甲1已经研发完成
addResources: energy=1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_黏性拟态合金护甲2研发]
price: energy=1,1800,hy=1000
text: 黏性拟态合金护甲2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红蓝1') and not self.globalTeamTags(includes='红蓝2')

addGlobalTeamTags: 红蓝2,防弹甲2,防爆甲2
removeGlobalTeamTags: 防弹甲1,防爆甲1
addResources: energy=1
iconImage: 红蓝.png
description: -升级的黏性拟态合金能更有效的中和弹头与弹片对结构的损坏，\n-能减少动能和爆炸类武器造成的30%的伤害。

showMessageToPlayer: 黏性拟态合金护甲2已经研发完成
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_镜面拟态合金护甲1研发]
price: energy=1,800
text: 镜面拟态合金护甲1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防爆甲1,红黄1
iconImage: 红黄.png
description: -镜面拟态合金着重强化了耐热性并可以形成非常光滑坚固的表面，\n-能减少能源和爆炸类武器造成的15%伤害。
showMessageToPlayer: 镜面拟态合金护甲1已经研发完成
addResources: energy=1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_镜面拟态合金护甲2研发]
price: energy=1,1800,hy=1000
text: 镜面拟态合金护甲2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红黄1') and not self.globalTeamTags(includes='红黄2')

addGlobalTeamTags: 红黄2,光学护甲2,防爆甲2
removeGlobalTeamTags: 光学护甲1,防爆甲1
addResources: energy=1
iconImage: 红黄.png
description: -升级版的拟态合金能在极端温度下保持活性并能形成几乎完美的光滑平面，\n-能减少能源和爆炸类武器造成的30%的伤害。

showMessageToPlayer: 镜面拟态合金护甲2已经研发完成
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_刚性拟态合金护甲1研发]
price: energy=1,800
text: 刚性拟态合金护甲1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防弹甲1,蓝黄1
iconImage: 蓝黄.png
description: -刚性拟态合金能在瞬间模拟钛，钽，铪等高强度金属元素的原子构成，\n-能减少能源和动能类武器造成的15%伤害。
showMessageToPlayer: 刚性拟态合金护甲1已经研发完成
addResources: energy=1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_刚性拟态合金护甲2研发]
price: energy=1,1800,hy=1000
text: 刚性拟态合金护甲2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='蓝黄1') and not self.globalTeamTags(includes='蓝黄2')

addGlobalTeamTags: 蓝黄2,光学护甲2,防弹甲2
removeGlobalTeamTags: 光学护甲1,防弹甲1
addResources: energy=1
iconImage: 蓝黄.png
description: -升级版刚性拟态合金能在瞬间模拟出余辉超合金护甲的原子排列顺序，\n-能减少能源和动能类武器造成的30%的伤害。

showMessageToPlayer: 刚性拟态合金护甲2已经研发完成
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_消除所有护甲1]
price: energy=1,600
text: 消除所有护甲
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲1') or self.globalTeamTags(includes='防爆甲1') or self.globalTeamTags(includes='光学护甲1')

removeGlobalTeamTags: 已有,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1
addResources: energy=1
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_消除所有护甲2]
price: energy=1,600
text: 消除所有护甲
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲2') or self.globalTeamTags(includes='防爆甲2') or self.globalTeamTags(includes='光学护甲2')

removeGlobalTeamTags: 已有,防弹甲2,防爆甲2,光学护甲2,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1,蓝黄2,红黄2,红蓝2
addResources: energy=1
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_灰影1]
text: 灰影病毒进化1
buildSpeed: 30s
price: hy=600,energy=1
description: -强化灰影病毒繁殖能力和精密程度，\n-升级过后的灰影病毒能更有效的为太空浪人机械类单位提供辅助，\n-这将解锁冥蜂，解锁太空浪人聚变堆变种
isVisible: if not self.globalTeamTags(includes='灰影1')

addGlobalTeamTags: 灰影1
addResources: energy=1
iconImage: 灰影.png
showMessageToPlayer: 灰影病毒已经变得更强大了
pos: 1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_灰影2]
text: 灰影病毒进化2
buildSpeed: 40s
price: hy=1500,energy=1
description: -灰影病毒内存组建和工程组件的全面升级，\n-内置革命性的微型生物计算机能保存无数种生物的基因数据，\n-以及各种古人类战争机器的设计蓝图，\n-这将使得灰影病毒能构造更强大的傀儡，或维护更复杂的机械。\n-这将解锁魔像，解锁赛格门塔护甲1
isVisible: if self.globalTeamTags(includes='灰影1') and not self.globalTeamTags(includes='灰影2')

addGlobalTeamTags: 灰影2
addResources: energy=1
iconImage: 灰影.png
ai_isHighPriority: true
showMessageToPlayer: 灰影病毒已经变得更强大了

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_灰影3]
text: 灰影病毒进化3
buildSpeed: 50s
price: hy=2400,energy=1
description: -灰影病毒繁殖能力与协调性的革命性升级，\n-庞大的数量再加上生物计算机组网使得灰影病毒能用脆弱的人体构造出更巨大的生化怪物，\n-最可怕的是，灰影病毒已经进化出了能寄生于帝国机械中的能力。\n-这将解锁基因血巢，解锁灰影寄生虫1
isVisible: if self.globalTeamTags(includes='灰影2') and not self.globalTeamTags(includes='灰影3')

addGlobalTeamTags: 灰影3
addResources: energy=1
iconImage: 灰影.png
ai_isHighPriority: true
showMessageToPlayer: 灰影病毒已经变得更强大了

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_没赛格门塔护甲1]
text: 未拥有赛格门塔护甲
#alsoTriggerOrQueueActionConditional:true
isVisible: if not self.globalTeamTags(includes='灰影2')
description: -赛格门塔护甲是一层由灰影病毒维护的装甲，\n-强大的灰影病毒将战斗中散落的稀土和金属元素捕获，\n-并在单位的身上组成了一道强悍的合金附加甲壳，\n-浪人所有t3机械类作战单位将在战斗中回复血量。\n-升级二级灰影病毒即可解锁该科技。
#text:已拥有 赛格门塔护甲1

iconImage: 赛格门塔护甲.png
displayType: infoOnlyNoBox
isActive: false


[action_有赛格门塔护甲1]
autoTrigger: if self.globalTeamTags(includes='灰影2')
#text: TRIGGER
alsoTriggerOrQueueActionConditional: true
isVisible: if self.globalTeamTags(includes='灰影2')
description: -赛格门塔护甲是一层由灰影病毒维护的装甲，\n-强大的灰影病毒将战斗中散落的稀土和金属元素捕获，\n-并在单位的身上组成了一道强悍的合金附加甲壳，\n-浪人所有t3机械类作战单位，除胡蜂无人机，萤火轰炸机，漂泊者之外将在战斗中回复血量。

text: 已拥有 赛格门塔护甲1
iconImage: 赛格门塔护甲.png
displayType: infoOnlyNoBox
addGlobalTeamTags: 赛格门塔1
isActive: false


[action_没灰影寄生虫1]
text: 未拥有灰影寄生虫
#alsoTriggerOrQueueActionConditional:true
isVisible: if not self.globalTeamTags(includes='灰影3')
description: -灰影寄生虫是一种强大的纳米病毒，\n-他可以寄生在血肉之躯或者钢筋铁骨之上，\n-并静待单位死亡后将其遗骸重新打造成强有力的怪兽，\n-并为太空浪人而战。\n-对全体生物单位有效，升级灰影寄生虫后的单位，\n-会在攻击敌方单位时追加寄生效果，被寄生的单位无论因为何种原因死亡，\n-都将化为一定数量的感染单位为你而战，伤害类型转为爆炸。\n-无法寄生浪人T3生物单位。\n-升级三级灰影病毒即可解锁该科技。
#text:已拥有 赛格门塔护甲1

iconImage: 灰影寄生虫.png
displayType: infoOnlyNoBox
isActive: false


[action_有灰影寄生虫1]
autoTrigger: if self.globalTeamTags(includes='灰影3')
#text: TRIGGER
alsoTriggerOrQueueActionConditional: true
isVisible: if self.globalTeamTags(includes='灰影3')
description: -灰影寄生虫是一种强大的纳米病毒，\n-他可以寄生在血肉之躯或者钢筋铁骨之上，\n-并静待单位死亡后将其遗骸重新打造成强有力的怪兽，\n-并为太空浪人而战。\n-对全体生物单位有效，升级灰影寄生虫后的单位，\n-会在攻击敌方单位时追加寄生效果，被寄生的单位无论因为何种原因死亡，\n-都将化为一定数量的感染单位为你而战，伤害类型转为爆炸。\n-无法寄生浪人T3生物单位。如果宿主被秒杀则无法触发寄生效果。\n-升级三级灰影病毒即可解锁该科技。

text: 已拥有 灰影寄生虫1
iconImage: 灰影寄生虫.png
displayType: infoOnlyNoBox
addGlobalTeamTags: 寄生虫1
isActive: false


[action_灰影机械1]
text: 灰影病毒集结1
description: 命令负责维护建筑的灰影病毒开始繁殖，\n-这将产出500单位的灰影病毒机械。\n-当健全建筑总数达到6时将升级产能。
buildSpeed: 15s
price: 1200
isVisible: if numberOfUnitsInTeam(greaterThan=0, withTag='灰影建筑') and not numberOfUnitsInTeam(greaterThan=5, withTag='灰影建筑')

#highPriorityQueue: true
addResources: hy=900
ai_isHighPriority: true
iconImage: 灰影生产.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

isLockedMessage: 没有供能


[action_灰影机械2]
text: 灰影病毒集结2
description: 命令负责维护建筑的灰影病毒开始繁殖，\n-这将产出800单位的灰影病毒机械。\n-当健全建筑总数达到13时将升级产能。
buildSpeed: 15s
price: 1500
isVisible: if numberOfUnitsInTeam(greaterThan=5, withTag='灰影建筑') and not numberOfUnitsInTeam(greaterThan=12, withTag='灰影建筑')

#highPriorityQueue: true
addResources: hy=1200
ai_isHighPriority: true
iconImage: 灰影生产.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

isLockedMessage: 没有供能


[action_灰影机械3]
text: 灰影病毒集结3
description: 命令负责维护建筑的灰影病毒开始繁殖，\n-这将产出1200单位的灰影病毒机械。\n-产能已达最大值
buildSpeed: 10s
price: 1800
isVisible: if numberOfUnitsInTeam(greaterThan=12, withTag='灰影建筑')

#highPriorityQueue: true
addResources: hy=1500
ai_isHighPriority: true
iconImage: 灰影生产.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

isLockedMessage: 没有供能


[graphics]
total_frames: 7
image: 主体.png
image_back: SHARED:blank.png
image_wreak: 死亡.png
animation_idle_start: 0

animation_idle_end: 6
animation_idle_speed: 8
#imageScale:0.7


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


