


[core]
name: 太空浪人纳米蜂巢
displayText: Наноулей Скитальцев
class: CustomUnitMetadata
price: 2500
maxHp: 10000
selfRegenRate: 0.2

footprint: -4,-1,4,5
constructionFootprint: -4,-1,4,5
techLevel: 1
energyMax: 1
energyRegen: 0

energyStartingPercentage: 1
buildSpeed: 10s
#displayDescription:太空浪人将从战场上收集来的尸体储存于此，\n-并将他们改造成傀儡为自己而战。
radius: 60
isBio: false

copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
exit_x: 0
exit_y: -1

tags: 地面,蜂巢,灰影建筑,建筑
armour: 10


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_断电a]
autoTrigger: if not self.hasFlag(id= 30) and self.queueSize > 0 and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
resetCustomTimer: true
addResources: setFlag= 30


[hiddenAction_断电b]
autoTrigger: if self.hasFlag(id= 30) and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30
refundAllQueuedItems: true


[hiddenAction_来电a]
autoTrigger: if self.hasFlag(id= 30) and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30





[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='蜂巢')
deleteSelf: true
#addResources:威胁点数=-${core.price / 25}
showMessageToPlayer: Эксплойт? Размечтался! В наказание лишних юнитов поглотил мой сервер 눈_눈


[action_黏性拟态合金护甲1研发]
price: energy=1,800
text: Вязкая мимикрирующая броня 1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,防弹甲1,防爆甲1,红蓝1
iconImage: 红蓝.png
description: -Защитный слой из крайне упругого и гибкого вязкого мимикрирующего сплава,\n-снижает урон от кинетического и взрывного оружия на 15%.
showMessageToPlayer: Вязкая мимикрирующая броня 1 — исследование завершено
addResources: energy=1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_黏性拟态合金护甲2研发]
price: energy=1,1800,hy=1000
text: Вязкая мимикрирующая броня 2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红蓝1') and not self.globalTeamTags(includes='红蓝2')

addGlobalTeamTags: 红蓝2,防弹甲2,防爆甲2
removeGlobalTeamTags: 防弹甲1,防爆甲1
addResources: energy=1
iconImage: 红蓝.png
description: -Улучшенный вязкий мимикрирующий сплав эффективнее нейтрализует повреждения конструкции от боеголовок и осколков,\n-снижает урон от кинетического и взрывного оружия на 30%.

showMessageToPlayer: Вязкая мимикрирующая броня 2 — исследование завершено
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_镜面拟态合金护甲1研发]
price: energy=1,800
text: Зеркальная мимикрирующая броня 1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防爆甲1,红黄1
iconImage: 红黄.png
description: -Зеркальный мимикрирующий сплав акцентирует усиленную термостойкость и может формировать очень гладкую и прочную поверхность,\n-снижает урон от энергетического и взрывного оружия на 15%.
showMessageToPlayer: Зеркальная мимикрирующая броня 1 — исследование завершено
addResources: energy=1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_镜面拟态合金护甲2研发]
price: energy=1,1800,hy=1000
text: Зеркальная мимикрирующая броня 2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='红黄1') and not self.globalTeamTags(includes='红黄2')

addGlobalTeamTags: 红黄2,光学护甲2,防爆甲2
removeGlobalTeamTags: 光学护甲1,防爆甲1
addResources: energy=1
iconImage: 红黄.png
description: -Улучшенный мимикрирующий сплав сохраняет активность при экстремальных температурах и может формировать почти идеально гладкую поверхность,\n-снижает урон от энергетического и взрывного оружия на 30%.

showMessageToPlayer: Зеркальная мимикрирующая броня 2 — исследование завершено
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_刚性拟态合金护甲1研发]
price: energy=1,800
text: Жёсткая мимикрирующая броня 1
displayType: upgrade
buildSpeed: 20s
isVisible: if not self.globalTeamTags(includes='已有')

addGlobalTeamTags: 已有,光学护甲1,防弹甲1,蓝黄1
iconImage: 蓝黄.png
description: -Жёсткий мимикрирующий сплав способен мгновенно имитировать атомное строение титана, тантала, гафния и других высокопрочных металлов,\n-снижает урон от энергетического и кинетического оружия на 15%.
showMessageToPlayer: Жёсткая мимикрирующая броня 1 — исследование завершено
addResources: energy=1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_刚性拟态合金护甲2研发]
price: energy=1,1800,hy=1000
text: Жёсткая мимикрирующая броня 2
displayType: upgrade
buildSpeed: 30s
isVisible: if self.globalTeamTags(includes='蓝黄1') and not self.globalTeamTags(includes='蓝黄2')

addGlobalTeamTags: 蓝黄2,光学护甲2,防弹甲2
removeGlobalTeamTags: 光学护甲1,防弹甲1
addResources: energy=1
iconImage: 蓝黄.png
description: -Улучшенный жёсткий мимикрирующий сплав может мгновенно имитировать атомную структуру суперсплавной брони Зарева,\n-снижает урон от энергетического и кинетического оружия на 30%.

showMessageToPlayer: Жёсткая мимикрирующая броня 2 — исследование завершено
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_消除所有护甲1]
price: energy=1,600
text: Снять всю броню
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲1') or self.globalTeamTags(includes='防爆甲1') or self.globalTeamTags(includes='光学护甲1')

removeGlobalTeamTags: 已有,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1
addResources: energy=1
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_消除所有护甲2]
price: energy=1,600
text: Снять всю броню
displayType: upgrade
buildSpeed: 1s
isVisible: if self.globalTeamTags(includes='防弹甲2') or self.globalTeamTags(includes='防爆甲2') or self.globalTeamTags(includes='光学护甲2')

removeGlobalTeamTags: 已有,防弹甲2,防爆甲2,光学护甲2,防弹甲1,防爆甲1,光学护甲1,蓝黄1,红黄1,红蓝1,蓝黄2,红黄2,红蓝2
addResources: energy=1
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_灰影1]
text: Эволюция вируса «Серая Тень» 1
buildSpeed: 30s
price: hy=600,energy=1
description: -Усиление способности вируса «Серая Тень» к размножению и его точности.\n-После улучшения вирус «Серая Тень» эффективнее поддерживает механические юниты Скитальцев.\n-Это разблокирует «Тёмную Пчелу» и варианты термоядерного реактора Скитальцев.
isVisible: if not self.globalTeamTags(includes='灰影1')

addGlobalTeamTags: 灰影1
addResources: energy=1
iconImage: 灰影.png
showMessageToPlayer: Вирус «Серая Тень» стал ещё сильнее
pos: 1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_灰影2]
text: Эволюция вируса «Серая Тень» 2
buildSpeed: 40s
price: hy=1500,energy=1
description: -Комплексное обновление памяти и инженерных компонентов вируса «Серая Тень».\n-Встроенный революционный микро-биокомпьютер может хранить генетические данные множества живых организмов,\n-а также чертежи различных боевых машин Древних Людей.\n-Это позволит вирусу «Серая Тень» создавать более мощных марионеток и обслуживать более сложные механизмы.\n-Это разблокирует Голема и броню «Сегмента» 1.
isVisible: if self.globalTeamTags(includes='灰影1') and not self.globalTeamTags(includes='灰影2')

addGlobalTeamTags: 灰影2
addResources: energy=1
iconImage: 灰影.png
ai_isHighPriority: true
showMessageToPlayer: Вирус «Серая Тень» стал ещё сильнее

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_灰影3]
text: Эволюция вируса «Серая Тень» 3
buildSpeed: 50s
price: hy=2400,energy=1
description: -Революционное улучшение размножения и координации вируса «Серая Тень».\n-Огромное количество в сочетании с сетью биокомпьютеров позволяет вирусу «Серая Тень» создавать из хрупких человеческих тел ещё более огромных биологических чудовищ.\n-Самое страшное — вирус «Серая Тень» уже приобрёл способность паразитировать на имперских механизмах.\n-Это разблокирует Генетический кровяной улей и паразита «Серая Тень» 1.
isVisible: if self.globalTeamTags(includes='灰影2') and not self.globalTeamTags(includes='灰影3')

addGlobalTeamTags: 灰影3
addResources: energy=1
iconImage: 灰影.png
ai_isHighPriority: true
showMessageToPlayer: Вирус «Серая Тень» стал ещё сильнее

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_没赛格门塔护甲1]
text: Нет брони «Сегмента»
#alsoTriggerOrQueueActionConditional:true
isVisible: if not self.globalTeamTags(includes='灰影2')
description: -Броня «Сегмента» — это слой брони, поддерживаемый вирусом «Серая Тень».\n-Мощный вирус «Серая Тень» захватывает рассеянные в бою редкоземельные и металлические элементы\n-и формирует на юните прочную дополнительную сплавную оболочку.\n-Все боевые механические юниты Скитальцев t3 будут восстанавливать здоровье в бою.\n-Улучшение вируса «Серая Тень» 2 уровня разблокирует эту технологию.
#text:已拥有 赛格门塔护甲1

iconImage: 赛格门塔护甲.png
displayType: infoOnlyNoBox
isActive: false


[action_有赛格门塔护甲1]
autoTrigger: if self.globalTeamTags(includes='灰影2')
#text: TRIGGER
alsoTriggerOrQueueActionConditional: true
isVisible: if self.globalTeamTags(includes='灰影2')
description: -Броня «Сегмента» — это слой брони, поддерживаемый вирусом «Серая Тень».\n-Мощный вирус «Серая Тень» захватывает рассеянные в бою редкоземельные и металлические элементы\n-и формирует на юните прочную дополнительную сплавную оболочку.\n-Все боевые механические юниты Скитальцев t3, кроме дрона «Шершень», бомбардировщика «Светлячок» и «Странника», будут восстанавливать здоровье в бою.

text: Получено: броня «Сегмента» 1
iconImage: 赛格门塔护甲.png
displayType: infoOnlyNoBox
addGlobalTeamTags: 赛格门塔1
isActive: false


[action_没灰影寄生虫1]
text: Нет паразита «Серая Тень»
#alsoTriggerOrQueueActionConditional:true
isVisible: if not self.globalTeamTags(includes='灰影3')
description: -Паразит «Серая Тень» — мощный нановирус,\n-он может паразитировать как в плоти, так и в стальных конструкциях,\n-терпеливо ожидая смерти юнита, чтобы перестроить его останки в могучего монстра\n-и сражаться за Скитальцев.\n-Действует на всех биологических юнитов; юниты, получившие улучшение паразита «Серая Тень»,\n-при атаке вражеских юнитов добавляют эффект паразитирования. Заражённые юниты, погибнув по любой причине,\n-превратятся в определённое количество заражённых юнитов, сражающихся за вас. Тип урона меняется на взрывной.\n-Не может заражать биологических юнитов Скитальцев T3.\n-Улучшение вируса «Серая Тень» 3 уровня разблокирует эту технологию.
#text:已拥有 赛格门塔护甲1

iconImage: 灰影寄生虫.png
displayType: infoOnlyNoBox
isActive: false


[action_有灰影寄生虫1]
autoTrigger: if self.globalTeamTags(includes='灰影3')
#text: TRIGGER
alsoTriggerOrQueueActionConditional: true
isVisible: if self.globalTeamTags(includes='灰影3')
description: -Паразит «Серая Тень» — мощный нановирус,\n-он может паразитировать как в плоти, так и в стальных конструкциях,\n-терпеливо ожидая смерти юнита, чтобы перестроить его останки в могучего монстра\n-и сражаться за Скитальцев.\n-Действует на всех биологических юнитов; юниты, получившие улучшение паразита «Серая Тень»,\n-при атаке вражеских юнитов добавляют эффект паразитирования. Заражённые юниты, погибнув по любой причине,\n-превратятся в определённое количество заражённых юнитов, сражающихся за вас. Тип урона меняется на взрывной.\n-Не может заражать биологических юнитов Скитальцев T3. Если носитель убит мгновенно, эффект паразитирования не сработает.\n-Улучшение вируса «Серая Тень» 3 уровня разблокирует эту технологию.

text: Получено: паразит «Серая Тень» 1
iconImage: 灰影寄生虫.png
displayType: infoOnlyNoBox
addGlobalTeamTags: 寄生虫1
isActive: false


[action_灰影机械1]
text: Сбор вируса «Серая Тень» 1
description: Прикажите вирусу «Серая Тень», обслуживающему здания, начать размножение.\n-Это даст 500 единиц нанотеха «Серая Тень».\n-При общем количестве исправных зданий 6 производительность будет улучшена.
buildSpeed: 15s
price: 1200
isVisible: if numberOfUnitsInTeam(greaterThan=0, withTag='灰影建筑') and not numberOfUnitsInTeam(greaterThan=5, withTag='灰影建筑')

#highPriorityQueue: true
addResources: hy=900
ai_isHighPriority: true
iconImage: 灰影生产.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

isLockedMessage: Нет питания


[action_灰影机械2]
text: Сбор вируса «Серая Тень» 2
description: Прикажите вирусу «Серая Тень», обслуживающему здания, начать размножение.\n-Это даст 800 единиц нанотеха «Серая Тень».\n-При общем количестве исправных зданий 13 производительность будет улучшена.
buildSpeed: 15s
price: 1500
isVisible: if numberOfUnitsInTeam(greaterThan=5, withTag='灰影建筑') and not numberOfUnitsInTeam(greaterThan=12, withTag='灰影建筑')

#highPriorityQueue: true
addResources: hy=1200
ai_isHighPriority: true
iconImage: 灰影生产.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

isLockedMessage: Нет питания


[action_灰影机械3]
text: Сбор вируса «Серая Тень» 3
description: Прикажите вирусу «Серая Тень», обслуживающему здания, начать размножение.\n-Это даст 1200 единиц нанотеха «Серая Тень».\n-Производительность достигла максимума.
buildSpeed: 10s
price: 1800
isVisible: if numberOfUnitsInTeam(greaterThan=12, withTag='灰影建筑')

#highPriorityQueue: true
addResources: hy=1500
ai_isHighPriority: true
iconImage: 灰影生产.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

isLockedMessage: Нет питания


[graphics]
total_frames: 7
image: 主体.png
image_back: SHARED:blank.png
image_wreak: 死亡.png
animation_idle_start: 0

animation_idle_end: 6
animation_idle_speed: 8
#imageScale:0.7


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


