


[core]
name: 超战机导弹
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
tags:反高空


[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 1250
isFixedFiring: true
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0


[turret_1]
x: 0
y: 0
canShoot: false
invisible: true
[turret_2]
invisible: true
x: 55
y: -8
idleDir: 0
projectile: 1
size: 1.1
turnSpeed: 0
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹发射音效.ogg
shoot_sound_vol: 0.5
delay: 120
canAttackMaxAngle: 181
canOnlyAttackUnitsWithTags:被锁定
limitingMinRange: 750
canAttackCondition: if parent.tags(includes= '锁人') and parent.queueSize<1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
[turret_3]
x: -55
y: -8
copyFrom: 2
warmup:30
delay: 90
[projectile_1]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.85
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
directDamage: 900
explodeEffect: CUSTOM:冲击波d,CUSTOM:爆炸d, CUSTOM:闪光d,CUSTOM:钢珠d
explodeEffectOnShield: CUSTOM:冲击波d,CUSTOM:爆炸d, CUSTOM:闪光d,CUSTOM:钢珠d
deflectionPower: -1
autoTargetingOnDeadTarget: true
trailEffectRate: 1.5
turnSpeed: 3.5
[projectile_炮弹]
@copyFromSection: template_能源
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.85
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
deflectionPower: -1
autoTargetingOnDeadTarget: true
trailEffectRate: 1.5
turnSpeed: 3.5
directDamage: 1450
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb
areaRadiusFromEdge: true
[effect_闪光d]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
[effect_爆炸d]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.3
scaleTo: 2.2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
[effect_钢珠d]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_冲击波d]
life: 100
priority:veryhigh
attachedToUnit: true
scaleFrom: 0.4
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.22
alwayStartDirAtZero: true
alpha: 0.8
#——————————聚变

[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 1.2
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6.8
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 28
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1.3
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_实验jb]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:18
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:2
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 0
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


