


[core]
name: 军团级重型运输机
displayText: Тяжёлый транспортный самолёт класса «Легион»
displayDescription: 【Уровень t4】【Механический юнит】【Воздушный юнит】【Сверхтяжёлый юнит】Тактическое назначение:тяжёлыйвооружениетранспортный самолёт，\n-вместимость десанта：24，не может транспортироваться，пассажиры внутри не могут стрелять наружу вооружение：\n-▲зенитное орудиеX6 только по воздуху взрывной урон ▲гаубицаX2 только по земле взрывной урон\n-▲тяжёлый пулемётX2 по земле и воздуху кинетический урон пробивает укрытия ▲Дрон «Колибри»X6 по земле и воздуху кинетический урон пробивает укрытия\n-в качестве 安все投送большое количествовойскааисследовать тяжёлыйтранспортный самолёт，\n-в качествеГенезисмаксимальный транспортный самолёт，легионклассможетнесётбольшое количествовойска，даже еслиявляетсястратегияклассоснащениетакженев话низ，\n-легионклассне толькоиметь堪называтьужасающий 容量，он вооружениетакжене容малый觑，\n-легионкласс挂везти многомодель огоньпушкаа такжеодинвся группадронудар序列можетлёгкийлёгкий撕碎доприходитьперехватывать враг，\n-легион вооружениедажеможетделатьдосначала清Пусто登陆пункт，сновапозволяетвойска登陆。\n-этотпозволяетлегионстановиться Генезис现存сильнейший транспортный самолёт，неестьегоодин。
price: 9200
maxHp: 10500
techLevel: 1
selfRegenRate: 0.7
buildSpeed: 35s
copyFrom: ROOT:/通用特效/单位防护.ini
availableInDemo: true
armour: 125
radius: 80
displayRadius: 80
softCollisionOnAll: 40
fogOfWarSightRange: 25
isBio: false
tags: 飞机,极端重型,低空
maxTransportingUnits: 24
transportUnitsUnloadDelayBetweenEachUnit:12
effectOnDeath:CUSTOM:碎片,CUSTOM:碎片1,CUSTOM:碎片2,CUSTOM:碎片3,CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大钢珠*2,CUSTOM:巨大闪光,CUSTOM:碎片4*3
effectOnDeathGroundCollision: CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大钢珠*2,CUSTOM:巨大闪光
[hiddenAction_地上]
autoTrigger: if not self.tags(includes= '地面') and not self.flying
isVisible: false
temporarilyAddTags:地面
temporarilyRemoveTags:飞机
[hiddenAction_天上]
autoTrigger: if self.tags(includes= '地面') and self.flying
isVisible: false
temporarilyAddTags:飞机
temporarilyRemoveTags:地面
[action_弹幕架2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕2.png
text: Реактивная установка2
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架2')

[action_akm]
autoTrigger: if not self.isFlying() and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack
[action_bkm]
autoTrigger: if self.isFlying()  and self.hasFlag(id=1)
stopLastAnimation: true
isVisible: false
addResources: unsetFlag=1
playAnimation: attack1
[action_重]
text: крайне端тяжёлыйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积преувеличивать юнит独есть характеристика，\n-иметькрайне端тяжёлыйюнит标签 юнитбудетиметькакнизпринадлежатьтип，\n-иметь 愈способность，исобственный护甲ненизкийв100пункт，\n-не может шок，но受допротивтяжёлый甲юнит伤害бафф。
[hiddenAction_创造hmmkA1]
autoTrigger: if attachment(slot= 'hmmkA1') == null
attachments_addNewUnits: 军团航母模块
attachments_onlyOnSlots: hmmkA1




[decal_转子]
image: 右引擎.png
total_frames: 4
frame: (self.customTimer * 20) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:19.5
yOffsetRelative:-40.5
isVisible:if self.maxHp * 0.36 < self.hp
layer: afterBody
[decal_转子1]
image: 左引擎.png
total_frames: 4
frame: (self.customTimer * 20) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-19.5
yOffsetRelative:-40.5
isVisible:if self.maxHp * 0.36 < self.hp
[decal_主体损坏a]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
#imageScale:0.9
isVisible: if self.hp < self.maxHp * 0.36
[decal_灯光]
layer: afterBody
image: 灯光.png
onlyWhileAlive: true
teamColors: true
#imageScale:0.9
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:-4


[attachment_hmmkA1]
x: 0
y: 0
onCreateSpawnUnitOf:军团航母模块
setDrawLayerOnBottom:true
lockRotation: true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: false
[attachment_1]
x: 0
y: 0
canAttack:false
addTransportedUnits: true
hidden: true
setDrawLayerOnBottom:true
[attachment_2]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_3]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_4]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_5]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_6]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_7]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_8]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_9]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_10]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_11]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_12]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_13]
@copyFromSection: attachment_1
x: 0
y: 0


[attachment_14]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_15]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_16]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_17]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_18]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_19]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_20]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_21]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_22]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_23]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_24]
@copyFromSection: attachment_1
x: 0
y: 0


[graphics]
total_frames: 1
image: 主.png
image_wreak: 死亡.png
image_turret: NONE
#imageScale: 0.9
image_shadow:影子.png
turretImageScale: 0.95
movementEffect: CUSTOM:火1,CUSTOM:火2
movementEffectRate: 0.5
teamColorsOnTurret: true
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 4
maxAttackRange: 450
shootDelay: 5
turretMultiTargeting: true
[turret_1]
x: -35
y: 35
canShoot: false
canAttackCondition: if self.resource.xk < 1
image: 主炮.png
idleDir:-15
limitingAngle: 70
limitingMinRange: 100
turnSpeed: 2
turnSpeedAcceleration: 0.2
canAttackLandUnits:false
[turret_2]
x: 5.5
y: 14
projectile: 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='弹幕架2')
shoot_sound: large_gun_fire2
shoot_sound_vol: 0.75
shoot_flame:large
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -6
recoilOutTime: 4
recoilReturnTime: 13
delay: 30
size:22
image: 炮管1.png
canAttackLandUnits:false
attachedTo: 1
slave: true
limitingAngle: 70
aimOffsetSpread: 1.7
limitingMinRange: 100
[turret_3]
x: 0
y: 14
copyFrom: 2
warmup: 5
[turret_4]
x: -5.5
y: 14
copyFrom: 2
warmup: 10
[turret_5]
x: 0
y: 0
canShoot: false
turnSpeed: 1.8
turnSpeedAcceleration: 1.0
image: 主炮1.png
attachedTo: 1
slave: true
limitingAngle: 70
limitingMinRange: 100
limitingRange:450
[turret_6]
x: 35
y: 35
copyFrom: 1
idleDir:15
[turret_7]
x: 5.5
y: 14
copyFrom: 2
attachedTo: 6
[turret_8]
x: 0
y: 14
copyFrom: 2
attachedTo: 6
delay:25
[turret_9]
x: -5.5
y: 14
copyFrom: 2
attachedTo: 6
delay:20
[turret_10]
x: 0
y: 0
copyFrom: 5
attachedTo: 6
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 100
areaRadius: 55
life: 60
speed: 11
color: #FFFFFF73
drawSize: 0.8
largeHitEffect: true
lightSize: 1
frame: 8
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
targetGroundHeightOffset:70
targetGround:true
disableLeadTargeting: true
[projectile_炮弹]
@copyFromSection: template_爆炸
life: 0
speed: 0
drawSize: 0
directDamage: 1
frame:1
spawnProjectilesOnEndOfLife: 锁定*3
targetGroundSpread: 55
[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 70
areaRadius: 50
life: 60
speed: 11
color: #FFFFFF73
drawSize: 0.8
largeHitEffect: true
lightSize: 0.8
frame: 3
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸s,CUSTOM:闪光s,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸s,CUSTOM:闪光s,CUSTOM:冲击波
targetGroundHeightOffset:70
targetGround:true
disableLeadTargeting: true
targetGroundSpread: 55
armourIgnoreAmount: 35
speedSpread:2
[effect_冲击波]
stripIndex: shockwave
life: 23
scaleFrom: 0.5
scaleTo: 2
alpha: 1
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3
scaleTo: 3
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.1
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.26
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alpha: 1.2
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.1
scaleTo: 1.6
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
#-.....寄
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.5
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[effect_巨大钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
alpha: 0.8
scaleFrom: 3
scaleTo: 7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3

#————————碎片
[effect_碎片]
priority: critical
image: 碎片.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: -5
ySpeedRelativeRandom: -2
yOffsetRelative: 31
xOffsetRelative: -30
hSpeed: 1.8
dirSpeed:1
dirSpeedRandom:2
[effect_碎片1]
priority: critical
image: 碎片1.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: 4.5
ySpeedRelativeRandom: -1.2
yOffsetRelative: -37
xOffsetRelative:-17.5
hSpeed: 2
dirSpeed:1.5
dirSpeedRandom:1
[effect_碎片2]
priority: critical
image: 碎片2.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 0.35
yOffsetRelative: -70
hSpeed: 3
dirSpeed:1
dirSpeedRandom:2.5
[effect_碎片3]
priority: critical
image: 碎片3.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: -0.5
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 3
yOffsetRelative: 0
xOffsetRelative: 0
hSpeed: 4
dirSpeed:4
dirSpeedRandom:2
[effect_碎片4]
priority: critical
image: 碎片4.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
yOffsetRelative: 0
xOffsetRelative: 0
hSpeed: 4
dirSpeed:4
dirSpeedRandom:2
[effect_火1]
life: 17
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #BBBBFFEE
xOffsetRelative	: 17.5
ySpeedRelative: -2
yOffsetRelative	: -45
drawUnderUnits: true
[effect_火2]
life: 17
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #BBBBFFEE
xOffsetRelative	: -17.5
ySpeedRelative: -2
yOffsetRelative	: -45
drawUnderUnits: true
[effect_爆炸s]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.95
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.26
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alpha: 1.2
[effect_闪光s]
image: SHARED:light_50.png
life: 17
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[arm_1]
x: 0
y: -16.5
image_end: 底子.png

[arm_2]
x: 0
y: -18.5
image_end: 球.png
spinRate:2 

[arm_3]
x: 0
y: -18.5
image_end: 外圆.png
spinRate:-0.6

[arm_4]
x: 0
y: -18.5
image_end: 外圆光.png
spinRate:-0.6

[arm_5]
x: 0
y: -2.5
image_end: 上盖.png

[arm_6]
x: 0
y: -32.5
image_end: 下盖.png
[arm_11]
x: 0
y: 15
image_end: 扇叶.png
drawOverBody: true
spinRate: 30
[animation_attack]
blendIn: 1s
blendOut: 2s
arm5_0s: {x:0, y:0,dir:0}
arm5_2s: {x:0, y:-12,dir:0}
arm5_9950s: {x:0, y:-12,dir:0}
arm6_0s: {x:0, y:0,dir:0}
arm6_2s: {x:0, y:10,dir:0}
arm6_9950s: {x:0, y:10,dir:0}
[animation_attack1]
arm5_0s: {x:0, y:0,dir:0}
arm5_1s: {x:0, y:12,dir:0}
arm6_0s: {x:0, y:0,dir:0}
arm6_1s: {x:0, y:-10,dir:0}
[movement]
movementType: AIR
targetHeight: 70
targetHeightDrift: 2
moveSpeed: 1.2
moveAccelerationSpeed: 0.03
startingHeightOffset: 1000
moveDecelerationSpeed: 0.03
maxTurnSpeed: 1
turnAcceleration: 1
slowDeathFall: true
moveSlidingMode : true
moveIgnoringBody:true
moveSlidingDir: 120


