


[core]
name: 光轮级护卫舰
displayText: Фрегат класса «Световой нимб»
displayDescription: -В отличие от универсального имперского фрегата класса «Феникс», фрегат класса «Световой нимб» поставлялся только Королевской гвардии,\n-его передовая боевая эффективность поражает воображение — даже в боях, где разница в классах не имеет значения,\n-фрегат «Световой нимб» не уступает противнику. Такой мощный корабль давно был желанной добычей для семьи Фаяд.\n-Однако строгий, даже жёсткий запрет Империи Нова на оружие вынуждал семью Фаяд тайно копировать его в подполье.\n-После раскола Империи чертежи «Светового нимба» были утрачены вместе с Таутени,\n-а единственные оставшиеся «Световые нимбы» в руках Зарева были полностью уничтожены в боях. Если сегодня вы хотите вновь увидеть былую мощь «Светового нимба»,\n-многочисленные журналы уничтожения врагов в копиях «Светового нимба» Скитальцев расскажут вам о его прошлой храбрости.\n-Атакует землю и воздух, энергетический урон. Лазеры пробивают укрытия.
class: CustomUnitMetadata
price: 6000
maxHp: 8500

shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 25s
availableInDemo: true
radius: 56


displayRadius: 56
isBio: false
transportSlotsNeeded: 20
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 光轮
#effectOnDeathGroundCollision:CUSTOM:爆炸x*1
tags: 飞机,低空,光轮
softCollisionOnAll: 20
armour: 20
copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.15
fogOfWarSightRange: 26
[action_bz]
displayType: action
price: 0
buildSpeed: 5s
isVisible: true
whenBuilding_cannotMove: false
text:Подняться выше
description: Увеличить высоту фрегата класса «Световой нимб», превращая его в высотный юнит.\n-Увеличивает дальность стрельбы, в высотном состоянии может атаковать воздушные и высотные юниты.
iconImage: ROOT:/通用特效/高空.png
allowMultipleInQueue:false
convertTo: 光轮级护卫舰1
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_a]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=540, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_b]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=540, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
turretImageScale: 0.8
movementEffect: CUSTOM:火,CUSTOM:火1,CUSTOM:火2

movementEffectRate: 1
animation_moving_start: 2
animation_moving_end: 2
animation_moving_speed: 8
animation_idle_start: 0

animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 440
shootDelay: 0


[turret_1]
x: 0
y: 95
image: 主炮.png
#canShoot: false
limitingAngle: 80

projectile: 1
delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200

shoot_flame: CUSTOM:球
aimOffsetSpread: -0.01
limitingMinRange: 170
size: 12


[turret_3]
x: 0
y: 11
canShoot: true
#recoilOffset:-2
idleDir: 90
turnSpeed: 0
projectile: 2
image: 副炮.png
shoot_sound: ROOT:/太空浪人/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.7
shoot_light: #FFFF1200
canAttackMaxAngle: 181
shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*3
delay: 25
#limitingAngle: 50
size: 10
canAttackLandUnits: false


[turret_4]
x: 0
y: 11
canShoot: true
#recoilOffset:-2
idleDir: -90
turnSpeed: 0
projectile: 2
image: 副炮.png
shoot_sound: ROOT:/太空浪人/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.7
shoot_light: #FFFF1200
canAttackMaxAngle: 181
shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*3
delay: 25
#limitingAngle: 50
size: 10
canAttackLandUnits: false


[projectile_1]
@copyFromSection: template_能源
directDamage: 13
instantReuseLast: true
life: 10
instant: true
armourIgnoreAmount: 30
laserEffect: true
explodeEffect: CUSTOM:闪光1
explodeEffectOnShield: CUSTOM:闪光1
lightSize: 0.75
beamImage: ROOT:/太空浪人/单位特效/光束3.png

#color:#FFFF1200
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_能源
directDamage: 160
life: 200
speed: 9
image: ROOT:/太空浪人/单位特效/光.png
turnSpeed: 3.5
targetSpeed: 9
drawSize: 0.60
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:爆炸2
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:爆炸2
lightSize: 0.75

trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
lightColor: #FFFF1200


[effect_闪光1]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.55

scaleTo: 0.55
image: ROOT:/太空浪人/单位特效/光束1.png
dirOffsetRandom: 180


[effect_球]
life: 5
spawnChance: 0.9
#priority:critical
attachedToUnit: true
scaleFrom: 0.7

scaleTo: 0.7
# image: 光球.png
image: ROOT:/太空浪人/单位特效/光束.png
alpha: 0.7


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_爆炸2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.38
scaleTo: 0.38
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 20
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false


[effect_火]
life: 28
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: -16
yOffsetRelative	: -85


[effect_火1]
life: 28
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 16
yOffsetRelative	: -85


[effect_火2]
life: 28
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -93


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
#color: #FFFF1200
fadeOut: true
attachedToUnit: true
#color:#FFE56BFF

#color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9

drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedRelative: 1
atmospheric: true


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: true

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[arm_1]
x: -13
y: 10.5
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: 13
y: 10.5
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: 0
y: 101
image_end: 前.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 0
y: 0
image_end: 损坏1.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(lessThan=2125)


[arm_6]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(lessThan=4675)


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:14, y:0}
arm1_950s: {x:14, y:0}
arm2_1s: {x:-14, y:0}

arm2_950s: {x:-14, y:0}
arm3_1s: {x:0, y:-20}
arm3_950s: {x:0, y:-20}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 2
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 2.6
turnAcceleration: 0.05
targetHeightDrift: 0.3

slowDeathFall: false
targetHeight: 70


[ai]
buildPriority: 0.9


