


[core]
name: 光轮级护卫舰1
displayText: 光轮级护卫舰
showInEditor: false
displayDescription: -不同于帝国泛用型凤凰级护卫舰，光轮级护卫舰只配发给皇家禁卫军，\n-其先进的作战效能令人叹为观止，哪怕是无视舰船规模的越级交战，\n-光轮级护卫舰依旧能在战斗中丝毫不落下风，如此强悍的战舰让法雅德家族垂涎已久。\n-但诺瓦帝国严格甚至严苛的军火禁令，使得法雅德家族只能在暗中进行仿制。\n-帝国分裂后，光轮护卫舰的图纸随着淘特尼一同灰飞烟灭，\n-而余辉手中仅存的光轮也在交战中全部损毁，如今如若想再次目睹光轮当年的强悍，\n-太空浪人仿制的光轮护卫舰那数量巨大的歼敌日志会告诉你他当年的勇猛。\n-对地对空，能源伤害。激光反掩体。
class: CustomUnitMetadata
price: 6000
maxHp: 8500
canOnlyBeAttackedByUnitsWithTags:反高空
shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 25s
availableInDemo: true
radius: 56
selfRegenRate: 0.15

displayRadius: 56
isBio: false
transportSlotsNeeded: 20
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 光轮
#effectOnDeathGroundCollision:CUSTOM:爆炸x*1
tags: 飞机,高空,光轮,反高空
softCollisionOnAll: 20
armour: 20
copyFrom: ROOT:/通用特效/单位防护.ini

fogOfWarSightRange: 32
[action_bz]
displayType: action
price: 0
buildSpeed: 5s
isVisible: true
whenBuilding_cannotMove: false
text:降低高度
description: 降低光轮级护卫舰的高度，使其成为常规空中单位。\n-恢复射程和对地面单位的能力，但失去了攻击高空单位的能力。
iconImage: ROOT:/通用特效/低空.png
allowMultipleInQueue:false
convertTo: 光轮级护卫舰
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_高空]
text: 高空单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的战机和战舰。\n-在此高度下，只有地面和空中特殊的反高空单位，以及高空单位才能攻击到该单位，\n-同时，大部分高空单位可以互相攻击，并可以攻击普通空中单位，\n-只有特殊的高空单位才能对地攻击。


[action_a]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=785, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_b]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=785, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
turretImageScale: 0.8
movementEffect: CUSTOM:火,CUSTOM:火1,CUSTOM:火2

movementEffectRate: 1
animation_moving_start: 2
animation_moving_end: 2
animation_moving_speed: 8
animation_idle_start: 0

animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 685
shootDelay: 0


[turret_1]
x: 0
y: 95
image: 主炮.png
#canShoot: false
limitingAngle: 80

projectile: 1
delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200

shoot_flame: CUSTOM:球
aimOffsetSpread: -0.01
limitingMinRange: 170
size: 12


[turret_3]
x: 0
y: 11
canShoot: true
#recoilOffset:-2
idleDir: 90
turnSpeed: 0
projectile: 2
image: 副炮.png
shoot_sound: ROOT:/太空浪人/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.7
shoot_light: #FFFF1200
canAttackMaxAngle: 181
shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*3
delay: 25
#limitingAngle: 50
size: 10
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空

[turret_4]
x: 0
y: 11
canShoot: true
#recoilOffset:-2
idleDir: -90
turnSpeed: 0
projectile: 2
image: 副炮.png
shoot_sound: ROOT:/太空浪人/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.7
shoot_light: #FFFF1200
canAttackMaxAngle: 181
shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*3
delay: 25
#limitingAngle: 50
size: 10
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空

[projectile_1]
@copyFromSection: template_能源
directDamage: 13
instantReuseLast: true
life: 10
instant: true
armourIgnoreAmount: 30
laserEffect: true
explodeEffect: CUSTOM:闪光1
explodeEffectOnShield: CUSTOM:闪光1
lightSize: 0.75
beamImage: ROOT:/太空浪人/单位特效/光束3.png

#color:#FFFF1200
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_能源
directDamage: 160
life: 200
speed: 9
image: ROOT:/太空浪人/单位特效/光.png
turnSpeed: 3.5
targetSpeed: 9
drawSize: 0.60
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:爆炸2
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:爆炸2
lightSize: 0.75

trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
lightColor: #FFFF1200


[effect_闪光1]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.55

scaleTo: 0.55
image: ROOT:/太空浪人/单位特效/光束1.png
dirOffsetRandom: 180


[effect_球]
life: 5
spawnChance: 0.9
#priority:critical
attachedToUnit: true
scaleFrom: 0.7

scaleTo: 0.7
# image: 光球.png
image: ROOT:/太空浪人/单位特效/光束.png
alpha: 0.7


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_爆炸2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.38
scaleTo: 0.38
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 20
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false


[effect_火]
life: 28
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: -16
yOffsetRelative	: -85


[effect_火1]
life: 28
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 16
yOffsetRelative	: -85


[effect_火2]
life: 28
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -93


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
#color: #FFFF1200
fadeOut: true
attachedToUnit: true
#color:#FFE56BFF

#color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9

drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedRelative: 1
atmospheric: true


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: true

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[arm_1]
x: -13
y: 10.5
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: 13
y: 10.5
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: 0
y: 101
image_end: 前.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 0
y: 0
image_end: 损坏1.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(lessThan=2125)


[arm_6]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(lessThan=4675)


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:14, y:0}
arm1_950s: {x:14, y:0}
arm2_1s: {x:-14, y:0}

arm2_950s: {x:-14, y:0}
arm3_1s: {x:0, y:-20}
arm3_950s: {x:0, y:-20}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 2
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 2.6
turnAcceleration: 0.05
targetHeightDrift: 0.3

slowDeathFall: false
targetHeight: 140


[ai]
buildPriority: 0.9


