


[core]
name: 模拟黑洞1
displayText: Симуляция чёрной дыры 1
class: CustomUnitMetadata
price: 0
maxHp: 5000000

techLevel: 1
buildSpeed: 5s
radius: 20
displayRadius: 20
numBitsOnDeath: 0

fogOfWarSightRange: 5
isBio: false
# createOnAggressiveTeam:true
canNotBeDirectlyAttacked: true
stayNeutral: true

tags: 引力点
softCollisionOnAll: 100
isBuilding: true
energyMax: 1
#dieOnZeroEnergy:true

canNotBeGivenOrdersByPlayer: true
disableAllUnitCollisions: true
isUnselectable: true
#canOnlyBeAttackedByUnitsWithTags:电击点

[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_转换]
autoTrigger: if self.timeAlive(laterThanSeconds=10)
deleteSelf: true


[action_发射]
fireTurretXAtGround: x
autoTrigger: true
fireTurretXAtGround_withOffset: 0,0
#addResources=energy=-1
# [action_发射1]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1
# [action_发射2]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1
# [action_发射3]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1
# [action_发射4]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1
# [action_发射5]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1
# [action_发射6]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1
# [action_发射7]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1
# [action_发射8]

# fireTurretXAtGround: x
# autoTrigger:true
# fireTurretXAtGround_withOffset: 0,0
# #addResources=energy=-1


[graphics]
image: SHARED:blank.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
#imageScale:0.5

dustEffect: false
drawLayer: air
icon_zoomed_out_neverShow: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 9999

turretSize: 0
turretTurnSpeed: 50


[turret_x]
x: 0
y: 0
canShoot: false
#warmup:600
projectile: a0

turnSpeedAcceleration: 999
delay: 15


[turret_z]
x: 0
y: 0
canShoot: true
#warmup:600
projectile: 4

turnSpeedAcceleration: 999
delay: 50
shoot_flame: CUSTOM:粒子效果*3


[projectile_4]
areaDamage: 0
areaRadius: 0
life: 0
frame: 1
drawSize: 0

speed: 0


[projectile_a0]
deflectionPower: -1
life: 0
speed: 0
turnSpeed: 0.0
directDamage: 0

invisible: true
explodeEffect: none
explodeEffectOnShield: none
spawnProjectilesOnCreate: a1*9(offsetRandomXY= 750)


[projectile_a1]
directDamage: 0
life: 90
image: 黑洞1.png
drawSize: 0.8
speed: 14

targetSpeed: 24
targetSpeedAcceleration: 0.5
explodeEffect: NONE
# spawnUnit:光点x*1


[turret_1]
x: 0
y: 0
canShoot: true
#warmup:600
projectile: 1

delay: 60000
turnSpeedAcceleration: 999


[turret_2]
#area shock turret
x: 0
y: 0
invisible: true
canAttackFlyingUnits: true

canAttackLandUnits: true
canAttackUnderwaterUnits: false
limitingRange: 9999
projectile: 2
turnSpeed: 50

shoot_sound: NONE
shoot_flame: NONE
canShoot: true
size: 0
#canAttackCondition:if self.globalTeamTags(includes='撕裂立场')

delay: 2


[projectile_1]
life: 1
areaDamage: 0
areaRadius: 0
targetGround: true
image: SHARED:blank.png

explodeOnEndOfLife: true
drawSize: 1
deflectionPower: -1
areaRadiusFromEdge: true
explodeEffect: CUSTOM:闪光*3,CUSTOM:漩涡4*3,CUSTOM:漩涡2,CUSTOM:漩涡,CUSTOM:核


[projectile_2]
@copyFromSection: template_战略武器
areaDamage: 120
armourIgnoreAmount: 900
areaRadius: 650
speed: 0.1
areaHitAirAndLandAtSameTime: true

life: 0
image: SHARED:blank.png
instant: false
largeHitEffect: false
explodeOnEndOfLife: true

deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true
pushForce: 0

pushVelocity: -2.1
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_主体]
priority: critical
image: 黑洞.png
life: 120
attachedToUnit: false
#color: #000000

alpha: 6666
scaleFrom: 0
scaleTo: 1.7
#hOffset: 75
alsoEmitEffectsOnDeath: CUSTOM:主体1


[effect_主体1]
priority: critical
image: 黑洞.png
life: 480
attachedToUnit: true
#color: #000000

alpha: 6666
scaleFrom: 1.7
scaleTo: 1.7
alsoEmitEffectsOnDeath: CUSTOM:主体1x


[effect_主体1x]
priority: critical
image: 黑洞.png
life: 35
attachedToUnit: false
#color: #000000

alpha: 6666
scaleFrom: 1.7
scaleTo: 0
#hOffset: 75


[effect_核]
priority: critical
image: 合体.png
life: 120
attachedToUnit: false
#color: #000000

alpha: 6666
scaleFrom: 0
alwayStartDirAtZero: true
scaleTo: 0.85
#hOffset: 75

alsoEmitEffectsOnDeath: CUSTOM:核1
createWhenOffscreen: true


[effect_核1]
priority: critical
image: 合体.png
life: 480
attachedToUnit: true
#color: #000000

alpha: 6666
scaleFrom: 0.85
scaleTo: 0.85
alwayStartDirAtZero: true
alsoEmitEffectsOnDeath: CUSTOM:核1x

createWhenOffscreen: true


[effect_核1x]
priority: critical
image: 合体.png
life: 35
attachedToUnit: true
#color: #000000

alpha: 6666
scaleFrom: 0.85
scaleTo: 0
alwayStartDirAtZero: true
createWhenOffscreen: true


[effect_漩涡]
priority: critical
image: 底色1.png
life: 120
dirOffsetRandom: 200
dirSpeed: -2

dirSpeedRandom: 1.5
attachedToUnit: false
#color: #000000
alpha: 6666
scaleFrom: 0

scaleTo: 1.85
createWhenOffscreen: true
#hOffset: 75
alsoEmitEffectsOnDeath: CUSTOM:漩涡1


[effect_漩涡1]
priority: critical
image: 底色1.png
dirOffsetRandom: 200
dirSpeed: -2
dirSpeedRandom: 1.5

life: 480
attachedToUnit: true
createWhenOffscreen: true
#color: #000000
alpha: 6666

scaleFrom: 1.85
scaleTo: 1.85
fadeOut: true


[effect_漩涡2]
priority: critical
image: 漩涡.png
life: 120
dirOffsetRandom: 200
dirSpeed: -2

dirSpeedRandom: 1.5
attachedToUnit: false
createWhenOffscreen: true
#color: #000000
alpha: 6666

scaleFrom: 0
scaleTo: 7.5
#hOffset: 75
alsoEmitEffectsOnDeath: CUSTOM:漩涡3
drawUnderUnits: true


[effect_漩涡3]
priority: critical
image: 漩涡.png
dirOffsetRandom: 200
dirSpeed: -2
dirSpeedRandom: 1.5

life: 480
createWhenOffscreen: true
attachedToUnit: true
#color: #000000
alpha: 6666

scaleFrom: 7.5
scaleTo: 7.5
fadeOut: true
drawUnderUnits: true


[effect_漩涡4]
priority: critical
image: 漩涡1.png
life: 120
dirOffsetRandom: 200
dirSpeed: -4

dirSpeedRandom: 1.5
attachedToUnit: false
createWhenOffscreen: true
#color: #000000
alpha: 6666

scaleFrom: 0
scaleTo: 11
#hOffset: 75
alsoEmitEffectsOnDeath: CUSTOM:漩涡5


[effect_漩涡5]
priority: critical
image: 漩涡1.png
dirOffsetRandom: 200
dirSpeed: -4
dirSpeedRandom: 1.5

life: 480
attachedToUnit: true
createWhenOffscreen: true
#color: #000000
alpha: 6666

scaleFrom: 11
scaleTo: 11
fadeOut: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 650
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF140000
createWhenOffscreen: true
#fadeInTime:2
scaleFrom: 55

scaleTo: 55
drawUnderUnits: true
atmospheric: false


[effect_粒子效果]
priority: critical
image: 粒子.png
dirOffsetRandom: 360
dirSpeed: -3
dirSpeedRandom: 1.5

life: 55
fadeOut: true
attachedToUnit: false
scaleFrom: 4
scaleTo: 1

alpha: 1
drawUnderUnits: false
atmospheric: false


[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
moveSlidingMode : false
moveIgnoringBody: true


