


[core]
name: 模拟黑洞
displayText: 模拟黑洞
class: CustomUnitMetadata
price: 0
maxHp: 5000000

techLevel: 1
buildSpeed: 5s
radius: 20
displayRadius: 20
numBitsOnDeath: 0

fogOfWarSightRange: 5
isBio: false
# createOnAggressiveTeam:true
stayNeutral: true
tags: 模拟黑洞

softCollisionOnAll: 100
isBuilding: true
energyMax: 400
dieOnZeroEnergy: true
canNotBeGivenOrdersByPlayer: true

disableAllUnitCollisions: true
isUnselectable: true
# canOnlyBeAttackedByUnitsWithTags:电击点
canNotBeDirectlyAttacked: true

[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_转换]
autoTrigger: if self.timeAlive(laterThanSeconds=7.5)
text: TRIGGER
buildSpeed: 0s
price: 0
spawnUnits: 模拟黑洞1

#alsoTriggerOrQueueActionConditional:true
isVisible: false
deleteSelf: true
spawnEffects: CUSTOM:光点*80
playSoundAtUnit: 黑洞.ogg


[action_发射]
fireTurretXAtGround: x
autoTrigger: if self.timeAlive > 0.5 and self.timeAlive < 7.5
fireTurretXAtGround_withOffset: 0, 0


[graphics]
total_frames: 5
image: 电球.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE

#imageScale:0.5
dustEffect: false
drawLayer: air
animation_idle_start: 0
animation_idle_end: 4

animation_idle_speed: 8
icon_zoomed_out_neverShow: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 9999

turretSize: 0
turretTurnSpeed: 50


[turret_3]
x: 2
y: 0
canShoot: true
shoot_flame: CUSTOM:光环*2,CUSTOM:漩涡*3
projectile: 13

delay: 4000


[turret_1]
x: 2
y: 0
canShoot: true
shoot_flame: CUSTOM:光粒*3,CUSTOM:光粒1*14,CUSTOM:闪光
projectile: 13

delay: 40


[turret_2]
#area shock turret
x: 0
y: 0
invisible: true
canAttackFlyingUnits: true

canAttackLandUnits: true
canAttackUnderwaterUnits: false
limitingRange: 9999
projectile: 2
turnSpeed: 50

shoot_sound: NONE
shoot_flame: NONE
canShoot: true
size: 0
#canAttackCondition:if self.globalTeamTags(includes='撕裂立场')

delay: 2


[projectile_2]
@copyFromSection: template_战略武器
areaDamage: 25
areaRadius: 325
speed: 0.1
areaHitAirAndLandAtSameTime: true
life: 0

image: SHARED:blank.png
instant: false
largeHitEffect: false
explodeOnEndOfLife: true
deflectionPower: -1

explodeEffect: NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[turret_x]
x: 0
y: 0
canShoot: false
projectile: a0


[projectile_a0]
deflectionPower: -1
life: 0
speed: 0
turnSpeed: 0.0
directDamage: 0

invisible: true
explodeEffect: none
explodeEffectOnShield: none
spawnProjectilesOnCreate: a1*5(offsetRandomXY= 450)


[projectile_a1]
deflectionPower: -1
life: 0
speed: 0
turnSpeed: 0.0
directDamage: 0

invisible: true
explodeEffect: none
explodeEffectOnShield: none
spawnProjectilesOnCreate: a2*3, a3


[projectile_a2]
deflectionPower: -1
lightingEffect: true
directDamage: 0
life: 20
instant: true

trailEffect: true
speedSpread: 1
lightSize: 0
explodeEffect: NONE


[projectile_a3]
@copyFromSection: template_能源,template_战略武器
areaDamage: 4000
areaRadius: 70
explodeOnEndOfLife: true
life: 1

areaRadiusFromEdge: true
speed: 0
targetSpeed: 0.0
flameWeapon: true
deflectionPower: -1

explodeEffect: CUSTOM:爆炸,CUSTOM:冲击波,CUSTOM:闪光1,CUSTOM:爆炸1,CUSTOM:电流*2


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200


[effect_爆炸1]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.1

scaleTo: 1.1
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/余辉军团/单位特效/瓶1.ogg
color: #FFFF1200


[effect_冲击波]
#priority:critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.85
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_闪光1]
priority: low
image: SHARED:light_50.png
life: 1
fadeOut: true
alpha: 0.5

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 7
scaleTo: 7

drawUnderUnits: true
atmospheric: false


[effect_电流]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.8

drawUnderUnits: true
scaleFrom: 4
scaleTo: 5.5
color: #FFFF1200


[effect_光粒]
#spawnChance: 0.6
#priority:critical
image: 纳米.png
frameIndex: 0
createWhenOverLiquid: false

life: 140
fadeOut: true
attachedToUnit: false
#color: #6D5448
fadeInTime: 5

scaleFrom: 1.7
scaleTo: 2.7
alpha: 1
drawUnderUnits: false
hSpeed: 4

hOffsetRandom: 1
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 17
yOffsetRelativeRandom: 17

xSpeedAbsoluteRandom: 0.1
ySpeedAbsoluteRandom: 0.1


[effect_光粒1]
spawnChance: 1
createWhenZoomedOut: false
life: 180
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/方块.png
scaleFrom: 1
scaleTo: 1.8

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xOffsetRelativeRandom: 2

yOffsetRelativeRandom: 2
xSpeedAbsoluteRandom: 2
ySpeedAbsoluteRandom: 2
#atmospheric: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 220
fadeOut: true
alpha: 0.8

attachedToUnit: false
color: #FF140000
fadeInTime: 2
scaleFrom: 25
scaleTo: 25

drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true


[effect_光环]
priority: critical
image: 环.png
life: 600
fadeOut: false
attachedToUnit: false

scaleFrom: 14
scaleTo: 0
alpha: 1
drawUnderUnits: true
atmospheric: false

alwayStartDirAtZero: true
#color:#FFFF1200
createWhenOffscreen: true


[effect_漩涡]
life: 600
priority: critical
attachedToUnit: false
scaleFrom: 9
scaleTo: 0

image: 漩涡1.png
fadeOut: false
alpha: 1
#fadeInTime: 1
createWhenOffscreen: true

dirOffsetRandom: 200
dirSpeed: -2
dirSpeedRandom: 1.5
drawUnderUnits: true


[arm_1]
x: -4
y: 5
image_end: 底色1.png
spinRate: -8
drawOverBody: false

drawUnderAllUnits: true


[arm_2]
x: -4
y: 5
image_end: 黑洞1.png
drawOverBody: true


[arm_3]
x: -4
y: 5
image_end: 环.png
drawOverBody: true


[effect_光点]
spawnChance: 1
createWhenZoomedOut: false
life: 65
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 3
scaleTo: 3

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 15

ySpeedRelativeRandom: 15
#atmospheric: true


[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
moveSlidingMode : false
moveIgnoringBody: true


