


[core]
name: 日耀无人机
displayText: 日耀无人机
displayDescription: -😅
class: CustomUnitMetadata
price: 0
maxHp: 2000
techLevel: 1
canNotBeGivenOrdersByPlayer: true
buildSpeed: 0
radius: 16
displayRadius: 16

fireTurretXAtSelfOnDeath: 1
#showOnMinimapToEnemies: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 90
isBio: false
energyMax: 3000
energyRegen: -1
dieOnZeroEnergy: true
tags: 地面,寄生免疫,射程x,伴生单位,无人单位
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[decal_履带]
image: 履带.png
total_frames: 4
frame: (self.customTimer * 22) % 4
# 8为图片帧数，17改速度，1/17s下一帧
layer: onTop
isVisible:if self.isMoving
yOffsetRelative:10
xOffsetRelative:-0.5
onlyWhileAlive:true
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[action_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
addResources: hp=-999999
[hiddenAction_zz1]
autoTrigger:if not self.isInMap()
addResources: hp= -999999
[graphics]
total_frames: 1
image: 钢蛋.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
splastEffect: true
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 10
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false

dieOnAttack: true
turretSize: 1
turretTurnSpeed: 250
maxAttackRange: 15
isMelee: true

meleeEngangementDistance: 99999


[projectile_0]
directDamage: 0
life: 50
instant: true
explodeEffect: NONE


[turret_0]
projectile: 0
x: 0
y: 0
invisible: true


[turret_1]
x: 0
y: 0
invisible: true
shoot_sound: NONE
shoot_flame: NONE

projectile: 1
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false


[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 6500
areaRadius: 100
life: 666
speed: 8888
targetSpeed: 8888
instant: true
flameWeapon: true
deflectionPower: -1
areaRadiusFromEdge: true

explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
explodeEffectOnShield:CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk

mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
#————————————炮弹爆炸
[effect_聚变nk]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 18
fadeOut: true
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
[effect_冲击波nk]
life: 45
priority: critical
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 2.3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true

[effect_冲击波nk1]
priority: low
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.2
alpha: 0.8
showInFog: true
drawUnderUnits: false
atmospheric: false

[effect_光球nk]
life: 90
priority: veryhigh
attachedToUnit: false
scaleFrom:0.75
scaleTo: 0.75
image: ROOT:/余辉军团/单位特效/收缩.png
ySpeedAbsolute:0
fadeOut: true
alpha: 0.85
showInFog: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true
[effect_光球1nk]
life: 90
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/创世纪军事集团/单位特效/光球z.png

fadeOut: true
showInFog: true
alpha: 0.7
fadeInTime: 1
createWhenOffscreen: true

[effect_聚变nk1]
image: ROOT:/通用特效/火光y.png
life: 100
fadeOut: true
attachedToUnit: false
alpha: 0.9
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 2
scaleTo: 8.5
color: #FF00B3FF
alwayStartDirAtZero: true
createWhenOffscreen: true
[effect_冲击波nk3]
priority: high
image: ROOT:/余辉军团/单位特效/超级冲击波1.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 1.8
alpha: 0.8
drawUnderUnits: true
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:35
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.5
scaleTo:2.67
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180
[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
createWhenOverLand: false
life: 90
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1
scaleTo: 3.2
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -20
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
[effect_火]
life: 70
fadeInTime: 1
createWhenOverLand: false
fadeOut: true
attachedToUnit: false
scaleFrom:1
scaleTo: 1.8
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1
yOffsetRelative	: 20
drawUnderUnits: true
[movement]
movementType: HOVER
moveSpeed: 1.8
moveAccelerationSpeed: 0.2
moveDecelerationSpeed: 0.4
maxTurnSpeed: 2
moveSlidingMode : false
moveIgnoringBody: true
turnAcceleration: 0.1


