

[hiddenAction_寄生b]
addResources: bj= ${bjxq}
[core]
name: 要塞t3
displayText: 要塞t1
displayDescription:【阶级t3】【防御类建筑】【建筑单位】【地面单位】【极端重型单位】\n-战术定位：超级单位掩体，允许驻扎机械单位，载员数量：16，\n-提升内部单位射程至550，战略武器抗性。\n-创世纪为了能在平坦地形上遏制余晖装甲集群冲锋所建立的，坚固而巨大的永驻工事。\n-要塞采用强固混凝土混合装甲钢框架浇注进行建造，其铜墙铁壁般的防御能力能抵御余晖绝大多数炮火直射，\n-以往毁灭性的攻击在要塞坚固的防护下都显得宛如瘙痒般无力。\n-要塞内部巨大的空间，更是允许大量的步兵乃至装甲力量驻扎在其内部，\n-甚至还能额外支持数个炮组和远程重炮提供额外火力支援。
class: CustomUnitMetadata
price: 18000,钍=200,bj= ${bjxq}
@global bjxq: 20
reclaimPrice: bj= ${bjxq}
maxHp: 30000
constructionFootprint:-7,-6,7,6
footprint: -7,-6,7,6
techLevel: 1
buildSpeed: 120s
fogOfWarSightRange: 30
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
numBitsOnDeath: 12
unitsSpawnedOnDeath:建筑损毁*2
effectOnDeath: CUSTOM:烟雾*5, CUSTOM:爆破*12,largeExplosion*2
radius: 100
displayRadius: 100
softCollisionOnAll: 12
energyStartingPercentage: 0
energyMax: 12
energyRegen: 0.003
exit_x: 0
exit_y: -1
tags: 地面,建筑,防御建筑,要塞t3,极端重型,jabzhdja,战略武器抗性,本来就有啊
armour: 100
transportUnitsRequireTag:驻扎要塞,步兵,卧倒,机甲
maxTransportingUnits: 16
selfRegenRate: 0.8
[hiddenAction_创造]
autoTrigger: if attachment(slot= '0') == nullUnit
attachments_onlyOnSlots: 0
attachments_addNewUnits:阵地
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[hiddenAction_内衬]
autoTrigger: if not self.tags(includes= 'jabzhdja') and self.hp> self.maxHp * 0.5
temporarilyAddTags: jabzhdja

[hiddenAction_内衬没了]
autoTrigger: if self.tags(includes= 'jabzhdja') and self.hp< self.maxHp * 0.5
temporarilyRemoveTags: jabzhdja
[decal_地板]
image: ROOT:/创世纪军事集团/建筑特效/要塞地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-28
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
imageScale: 0.9
alpha:1




[decal_shadow]
image: 要塞影子.png
layer: shadow
xOffsetAbsolute: 9
yOffsetAbsolute: -10
alpha: 0.5
onlyWhileAlive: true
imageScale: 0.9
isVisible: true


[decal_损坏]
image:小损坏2.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:10.5
xOffsetRelative:0
onlyWhileAlive:true
imageScale: 0.9
alpha:1
[action_1_烟幕弹]
fireTurretXAtGround: 烟幕弹
text: 发射烟幕弹
displayType: action
buildSpeed: 1s
pos: 1
iconImage: ROOT:/创世纪军事集团/单位特效/烟雾弹.png
displayRemainingStockpile: true
highPriorityQueue: true
price: energy=3
canPlayerCancel: false
onlyOneUnitAtATime: true
whenBuilding_playAnimation: 1
description: 向目标区域投掷一枚烟幕弹，烟幕弹能严重干扰敌军的瞄准系统。\n-烟雾弹将降低附近160范围内的敌方地面单位的射程以及射速，\n-对具有长距离索敌能力以及拥有先进目标定位核心科技的单位无效。
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_没有]
text: 未启用自动炮阵地
isVisible: if self.transportingCount < 4
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 3
iconImage: ROOT:/通用特效/关.png
description: 当要塞内部驻扎单位数量大于等于4个时，\n-要塞将开启自动炮组进行攻击，\n-自动炮组射程为500，对地对空，造成动能点杀伤，对伴生单位伤害加成。
[action_有]
text: 已启用自动炮阵地
isVisible: if self.transportingCount > 3
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 4
iconImage: ROOT:/通用特效/开.png
description: 已启用自动炮阵地，\n-要塞已开启自动炮组进行攻击，\n-自动炮组射程为500，对地对空，造成动能点杀伤，对伴生单位伤害加成。


[action_没有1]
text: 未启用280毫米炮阵地
isVisible: if self.transportingCount < 8
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 5
iconImage: ROOT:/通用特效/关.png
description: 当要塞内部驻扎单位数量大于等于8个时，\n-要塞将开启280毫米炮进行攻击，\n-280毫米炮射程为650，只能对地，造成爆炸溅射伤害。
[action_有1]
text: 已启用280毫米炮阵地
isVisible: if self.transportingCount > 7
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 6
iconImage: ROOT:/通用特效/开.png
description: 已启用280毫米炮阵地，\n-要塞已开启280毫米炮进行攻击，\n-280毫米炮射程为650，只能对地，造成爆炸溅射伤害。



[action_重]
text: 极端重型单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 9
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积夸张的单位独有的特性，\n-拥有极端重型单位标签的单位将拥有如下属性，\n-拥有自愈能力，且自身护甲不低于100点，\n-难以被休克，但是受到反重甲单位伤害增益。

[action_结构]
text: 强化结构
isVisible:if self.hp> self.maxHp * 0.5
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 10
iconImage: ROOT:/通用特效/强化结构.png
isLockedMessage: 该单位的结构构造经过特殊的强化和加固，\n-能免疫一切负面效果。但仅在自身生命值大于50%时起效。
[action_查看]
text: 查看能驻扎的单位类型
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0
iconImage: ROOT:/通用特效/坦克.png
isLockedMessage: 所有能驻扎在步战车/观察哨/地堡内的步兵，\n-IAV轮式突击炮，轻坦克，加特林卡车，反坦克导弹车，袋熊战车，游侠机器人，\n-自行高炮，主战坦克，自行榴弹炮，巨兽坦克，\n-休克打击坦克，征服者，浮游坦克，超坦克，挑战者坦克，暴雨火箭炮，超坦克mk2。
[action_升级]
convertTo: 要塞t4
displayType: action
text: 升级
price: 20000,钍=400
buildSpeed: 40s
pos: 0
isLocked: if not self.globalTeamTags(includes='材料技术3') or not self.globalTeamTags(includes='强固建筑')
isLockedMessage: 需要材料技术3和强固建筑
ai_isHighPriority: true
description:最大化要塞等级，加固其结构强度，提升内部载员数量至24，\n-并将内部单位射程提升至1200，添加无人机机库，升级280毫米炮组。\n-将要塞的防御能力升级至几乎无懈可击的强度，\n-并在要塞内部部署大量重型火力，\n-使其真正成为战场上的一道叹息之壁。
[graphics]
total_frames: 1
image: 小要塞.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/要塞死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

shadowOffsetX: 3
shadowOffsetY: 3
imageScale: 0.9
image_offsetY: -10
drawLayer: ground

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 50
maxAttackRange: 500
meleeEngangementDistance: 50
isMelee: true

[turret_烟幕弹]
x: 0
y: -25
canShoot: false
invisible: true
size: 1.1
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 1
delay: 0
shoot_flame: CUSTOM:烟雾1*7
shoot_light: #FFEECCCC

[projectile_1]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.9

image: ROOT:/创世纪军事集团/建筑特效/弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 2
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1

[projectile_2]
life: 600
directDamage: 0
speed: 6
targetSpeed: 9
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png
initialUnguidedSpeedHeight: 2.5
gravity: 0.4
drawSize: 0.9
targetGround: true
spawnUnit: 烟幕弹*1
trailEffect: true
deflectionPower: -1
trailEffectRate: 1


#————————————
[effect_烟雾1]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120

fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1

scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
atmospheric: true


[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10
[attachment_0]
x: 0
y: 0
isUnselectable:true
onCreateSpawnUnitOf:阵地
lockRotation: false
resetRotationWhenNotAttacking:true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
setDrawLayerOnTop:true
onConvertKeepExistingUnitInSameSlot:true
[attachment_1]
x:0
y: 0
isVisible: false
height: 40
canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true
prioritizeParentsMainTarget:true
alwaysAllowedToAttackParentsMainTarget: false
onConvertKeepExistingUnitInSameSlot:true
[attachment_2]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_3]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_4]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_5]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_6]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_7]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_8]
x: 0
y:0
@copyFromSection: attachment_1

[attachment_9]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_10]
x: 0
y:0
@copyFromSection: attachment_1

[attachment_11]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_12]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_13]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_14]
x: 0
y:0
@copyFromSection: attachment_1


[attachment_15]
x: 0
y:0
@copyFromSection: attachment_1

[attachment_16]
x: 0
y:0
@copyFromSection: attachment_1



[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 360
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.4
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 50
yOffsetRelativeRandom: 70
xSpeedAbsoluteRandom: 0.35
ySpeedAbsoluteRandom: 0.35
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.8
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:100
yOffsetRelativeRandom:100
delayedStartTimerRandom:40
[arm_1]
x: -5
y: -30
image_end:ROOT:/创世纪军事集团/建筑特效/要塞左.png
image_end_teamColors: true
drawOverBody: true
[arm_2]
x: 5
y: -30
image_end:ROOT:/创世纪军事集团/建筑特效/要塞右.png
image_end_teamColors: true
drawOverBody: true
[animation_1]

arm1_0s: {x:0, y:0}
arm2_0s: {x:0, y:0}
arm1_1s: {x:-15, y:0}
arm2_1s: {x:15, y:0}
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


