
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 聚变鱼雷炮塔t2
displayDescription: 【阶级t4】【防御类建筑】【建筑单位】【地面单位】【水上单位】（当部署在水上时）\n-战术定位：重型防空鱼雷炮塔 武器配置：\n-▲聚变鱼雷发射管X1 对空对高空 能源伤害\n-创世纪通过月球芯片中提取的蓝图制造出的固定反舰系统，\n-其发射的制导核弹头鱼雷能够有效打击余晖战机乃至战舰，\n-几乎任何已知的空中单位都无法抵御聚变弹头的攻击。
price: 6400,钍=235,bj= ${bjxq}
@global bjxq: 12
reclaimPrice: bj= ${bjxq}
maxHp: 30000

footprint: -2,-2,2,2
constructionFootprint: -2,-2,2,2
fogOfWarSightRange: 37
techLevel: 1

copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 20s
radius: 40
armour: 40

isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆破*4,largeExplosion
tags: 地面,建筑,防御建筑,反高空
energyMax: 1
energyRegen: 0
energyNeedsToRechargeToFull: true
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[action_升级]
convertTo: 聚变鱼雷炮塔t3
displayType: action
text: 升级
price: 2500,钍=200
buildSpeed: 15s
isLocked: if not  self.globalTeamTags(includes='地震弹头')
isLockedMessage: 你需要地震弹头
description: 最大化聚变鱼雷炮塔等级，加固其结构强度，提升伤害以及射程，额外增加一组发射管。\n-换装额外的鱼雷发射管和扩展装弹器，\n-将对空军毁伤提升到极致，\n-这样的鱼雷能有效威胁到已知的任何种类的空中战舰。
highPriorityQueue: false
temporarilyRemoveTags:↯
setResourcesWithLogic: xk=0
#——————————————装填动画
[decal_炮塔影子]
image: 本体影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:4
xOffsetRelative:4
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
imageScale: 0.84
[decal_遮盖1]
image:底.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:30
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 1
imageScale: 0.84
[decal_装填]
image:ROOT:/创世纪军事集团/建筑特效/1.png
total_frames: 9
frame: select(self.tags(includes= '切枪'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1
[decal_装填z]
image:ROOT:/创世纪军事集团/建筑特效/2.png
total_frames: 9
frame: select(self.tags(includes= '切枪1'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪1')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1
[decal_装填z1]
image:ROOT:/创世纪军事集团/建筑特效/3.png
total_frames: 9
frame: select(self.tags(includes= '切枪2'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪2')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1
[decal_装填z2]
image:ROOT:/创世纪军事集团/建筑特效/4.png
total_frames: 9
frame: select(self.tags(includes= '切枪3'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪3')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1

[decal_装填z3]
image:ROOT:/创世纪军事集团/建筑特效/5.png
total_frames: 12
frame: select(self.tags(includes= '切枪4'), (self.customTimer * 14) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪4')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1

[decal_装填z4]
image:ROOT:/创世纪军事集团/建筑特效/6.png
total_frames: 9
frame: select(self.tags(includes= '切枪5'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪5')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1

[decal_装填z5]
image:ROOT:/创世纪军事集团/建筑特效/7.png
total_frames: 9
frame: select(self.tags(includes= '切枪6'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪6')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1

[decal_装填z6]
image:ROOT:/创世纪军事集团/建筑特效/8.png
total_frames: 9
frame: select(self.tags(includes= '切枪7'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪7')
onlyWhileAlive:true
yOffsetRelative:-34
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1

[decal_装填z7]
image:ROOT:/创世纪军事集团/建筑特效/装填.png
total_frames: 9
frame: select(self.tags(includes= '切枪8'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:afterBody
isVisible:if self.tags(includes= '切枪8')
onlyWhileAlive:true
yOffsetRelative:32
xOffsetRelative:0
imageScale: 0.84
basePositionFromTurret: 1
[decal_影子1]
image: ROOT:/创世纪军事集团/建筑特效/地板.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:2
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
imageScale: 0.84
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/座1影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:13
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.65
imageScale: 0.84
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/支持.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-41
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.65
imageScale: 0.84


[decal_右弹头]
image: ROOT:/创世纪军事集团/建筑特效/导弹.png
total_frames: 1
layer: afterBody
yOffsetRelative:29
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 1
imageScale: 0.84
teamColors: true
isVisible:if self.energy>0.5
[decal_遮盖]
image:本体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 1
imageScale: 0.84
teamColors: true

[decal_雷达]
image:雷达.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 4
imageScale: 0.84
teamColors: true

#——————————装弹逻辑
[hiddenAction_装]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
whenBuilding_cannotMove:false
allowMultipleInQueue:false
autoTrigger: if self.energy<0.2 and not self.tags(includes= '切枪') and not self.tags(includes= '结束')
temporarilyAddTags: 结束
alsoQueueAction: ax
highPriorityQueue: true
[action_ax]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
alsoQueueAction: bx
resetCustomTimer: true
temporarilyAddTags: 切枪
[action_bx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
temporarilyAddTags: 切枪1
alsoQueueAction: cx
resetCustomTimer: true
[action_cx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
alsoQueueAction: dx
resetCustomTimer: true
temporarilyRemoveTags: 切枪1
temporarilyAddTags: 切枪2
[action_dx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪2
temporarilyAddTags: 切枪3
alsoQueueAction: ex
resetCustomTimer: true
[action_ex]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪3
temporarilyAddTags: 切枪4
alsoQueueAction: fx
[action_fx]
displayType: action
price: 0
buildSpeed: 0.75s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪4
temporarilyAddTags: 切枪5
alsoQueueAction: gx
[action_gx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪5
temporarilyAddTags: 切枪6
alsoQueueAction: hx
[action_hx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪6
temporarilyAddTags: 切枪7
alsoQueueAction: ix
[action_ix]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪7
temporarilyAddTags: 切枪8
alsoQueueAction: jx
[action_jx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪8,结束
addResources:energy=1

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image_back: ROOT:/通用特效/NO.png
image: ROOT:/创世纪军事集团/建筑特效/座1.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/中座死亡.png
image_turret: NONE
turretImageScale: 0.84
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.84
image_offsetY: -11
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 12

turretTurnSpeed: 6
maxAttackRange: 900
shootDelay: 0

[turret_1]
x: 0
y: 33
canShoot: false
image: 本体.png
idleDir:90
turnSpeed: 1.5
turnSpeedAcceleration: 0.15
canAttackCondition: if self.resource.xk < 1
limitingMinRange: 275
[turret_2]
x: 0
y: 28
#导弹右
projectile: 1
attachedTo: 1
slave: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾x*6,CUSTOM:冲击波
shoot_light: #FFEECCCC
canShoot: true
size:0
delay:240
canAttackCondition: if self.resource.xk < 1 and self.energy>0.8
energyUsage:1
invisible:true
canOnlyAttackUnitsWithoutTags:高空
limitingMinRange: 275
[turret_3]
x: 0
y: 28
#导弹右
projectile: 2
attachedTo: 1
slave: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾x*6,CUSTOM:冲击波
shoot_light: #FFEECCCC
canShoot: true
size:0
delay:240
canAttackCondition: if self.resource.xk < 1 and self.energy>0.8
energyUsage:1
invisible:true
canOnlyAttackUnitsWithTags:高空
limitingMinRange: 275
[turret_4]
x: -35
y: -7
canShoot: false
image: 雷达.png
attachedTo: 1
idleSpin: 4
[projectile_1]
life: 45
speed: 3.5
targetSpeed: 0
largeHitEffect: true
drawSize: 0.84
image: ROOT:/创世纪军事集团/建筑特效/导弹.png
trailEffect: true
trailEffectRate: 1.3
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:冲击波,CUSTOM:闪光mx
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_锁定]
@copyFromSection: template_能源
areaDamage: 10500
shouldRevealFog: true
areaRadius: 75
life: 600
speed: 1
targetSpeed: 13
image: ROOT:/创世纪军事集团/建筑特效/导弹头.png
lightColor: #FFFFFF73
areaRadiusFromEdge: true
drawSize: 0.84
lightSize: 0.9
trailEffectRate: 0.25
trailEffect: CUSTOM:尾巴1,CUSTOM:星
explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
explodeEffectOnShield:CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_2]
life: 45
speed: 3.5
targetSpeed: 0
largeHitEffect: true
drawSize: 0.84
image: ROOT:/创世纪军事集团/建筑特效/导弹.png
trailEffect: true
trailEffectRate: 1.3
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:冲击波,CUSTOM:闪光mx
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_锁定1]
@copyFromSection: template_能源
areaDamage: 10500
shouldRevealFog: true
areaRadius: 75
life: 600
speed: 1
targetSpeed: 13
image: ROOT:/创世纪军事集团/建筑特效/导弹头.png
lightColor: #FFFFFF73
areaRadiusFromEdge: true
drawSize: 0.84
lightSize: 0.9
trailEffectRate: 0.25
trailEffect: CUSTOM:尾巴1,CUSTOM:星
explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
explodeEffectOnShield:CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
#——————————发射特效
[effect_闪光mx]
image: SHARED:light_50.png
life:30
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FFFF5B18
fadeInTime: 2
scaleFrom: 5.5
scaleTo: 5.5
drawUnderUnits: false
atmospheric: false
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 3
alpha: 0.8
fadeOut: true
fadeInTime: 2
attachedToUnit: false
[effect_烟雾x]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 2
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.6
atmospheric: true
[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/建筑特效/弹壳.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.84
scaleTo: 0.84
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
ySpeedRelative: -1
hSpeed: 2
dirSpeedRandom: 10
alsoPlaySound:nuke_launch
#——————————————尾巴
[effect_星]
image:ROOT:/创世纪军事集团/单位特效/星星1.png
life: 5
fadeOut: true
spawnChance: 0.55
alpha: 0.8
attachedToUnit:true
#color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 0.4
scaleTo: 0.4
drawUnderUnits: false
atmospheric: false
yOffsetRelative: -10
xOffsetRelativeRandom:5
yOffsetRelativeRandom:5
[effect_尾巴1]
stripIndex: effects
frameIndex: 0
life: 80
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 2.1
alpha: 0.7
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative	: -14
#——————————聚变
[effect_聚变nk]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 18
fadeOut: true
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
[effect_冲击波nk]
life: 45
priority: critical
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 2.3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true

[effect_冲击波nk1]
priority: low
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.2
alpha: 0.8
showInFog: true
drawUnderUnits: false
atmospheric: false
#——————@——————看NM，给👴爬


[effect_光球nk]
life: 90
priority: veryhigh
attachedToUnit: false
scaleFrom:0.75
scaleTo: 0.75
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
ySpeedAbsolute:0
fadeOut: true
alpha: 0.85
showInFog: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true
[effect_光球1nk]
life: 90
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/创世纪军事集团/单位特效/大光球.png

fadeOut: true
showInFog: true
alpha: 0.7
fadeInTime: 1
createWhenOffscreen: true

[effect_聚变nk1]
image: ROOT:/通用特效/火光.png
life: 100
fadeOut: true
attachedToUnit: false
alpha: 0.9
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 2
scaleTo: 8.5
color: #FFFFF44C
alwayStartDirAtZero: true
createWhenOffscreen: true
[effect_冲击波nk3]
priority: high
image: ROOT:/创世纪军事集团/单位特效/冲击波4.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.4
alpha: 0.8
drawUnderUnits: true
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:35
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
scaleFrom:0.5
scaleTo:2.67
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
delayedStartTimerRandom:30
[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


