


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=310


[core]
name: SDN零素
displayText: SDN Нулевой элемент
class: CustomUnitMetadata
price: 9500,蓝晶=550
maxHp: 8000
displayDescription: -в Древние Людиязыкв , "нулевой элемент"это одиночныйслово"морекорользвезда" транслитерация.\n-Империя Новапоздний период большой смешанныйбойв , Заревооченьбыстрыйтогдазахватить поле бояна абсолютныйпротив  главныйдвижениеправо, \n-в тотштзвездакорабльещё ещё незакончитьвсе общий и  годэра, еслихочет закончитьвсе захватодинместо пригодный для жизни мореокеанпланета, \n-РазвернутьВМФэто должен не может мало одиншаг, к это , нулевой элементуровеньтогдав Зарево установкарасчётпод должен движение, а жизнь.\n-Этот прямоот списанзвездакорабльпереоборудованный, а приходит  ВМФ, нет теорияиз тело типещё это огневая мощьна все можно назватьэто превышатьуровеньподобный хранениев .\n-в Парящая крепостьпроизводствоможет не достаточно ситуацияпод , нулевой элементстать функцияпомощьЗаревобитьотступлениеодин раз также один раз удар.\n-, а текущийв , нулевой элементделатьдля иглапротив созиданиеэпохаэрабойв  ВМФосновная сила, распространенык  шармореокеан каждыйштуголпадение.\n-по земле и воздуху, взрыв ракеты, другие может источник.\n-Тип проекта:ИмперияЗарево Валгалларасчётразрезданные

techLevel: 1
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 60
buildSpeed: 22s

radius: 85
displayRadius: 85
armour: 25
fogOfWarSightRange: 29
isBio: false

softCollisionOnAll: 4
energyMax: 7.3
energyRegen: 0.004
maxShield: 10000
tags: 地面,海上,无人单位

copyFrom: ROOT:/通用特效/单位防护.ini
shieldRegen: 0.07
effectOnDeath: CUSTOM:爆炸5*1,CUSTOM:冲击波2,CUSTOM:水波1
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_反物质2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/反物质2.png
text: Антиматериальное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='反物质2')


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
displayType: infoOnlyNoBox
text: Позитронное ядро

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_重子兵器2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重子2.png
text: барионное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='重子2')
[action_1_瓶]
text: открытьбутылка Клейна
displayType: action
buildSpeed: 0s
pos: 0.1
#displayRemainingStockpile: true

highPriorityQueue: true
price: 0
canPlayerCancel: false
#displayRemainingStockpile: true
#onlyOneUnitAtATime: true

description: открытьбутылка Клейна, \n-ввходит нет врагисостояние.
isVisible: if self.globalTeamTags(includes='克莱因瓶1')
convertTo: SDN零素1
addActionCooldownTime: 65s
playSoundAtUnit: ROOT:/余辉军团/单位特效/瓶.ogg

iconImage: ROOT:/余辉军团/单位特效/克莱因瓶1.png
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
temporarilyAddTags: 本来就有啊



[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=700, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=700, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 5

shadowOffsetY: 5
image_shield: 护盾.png
splastEffect: true
turretImageScale: 0.8


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 180

maxAttackRange: 630
turretMultiTargeting: true
turretTurnSpeed: 2


[turret_1]
x: 40
y: -34
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/大主炮音效.ogg
recoilOffset: -3

warmupStartEffect: CUSTOM:气浪,CUSTOM:粒子*2
recoilOutTime: 5
recoilReturnTime: 30
projectile: 1
idleDir: 35

limitingAngle: 100
warmup: 40
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
delay: 200
canAttackFlyingUnits: false

image: 主炮1.png
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='重子2')

[turret_2]
x: -40
y: -34
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/大主炮音效.ogg
recoilOffset: -3

warmupStartEffect: CUSTOM:气浪,CUSTOM:粒子*2
recoilOutTime: 5
recoilReturnTime: 30
projectile: 1
idleDir: -35

limitingAngle: 100
warmup: 40
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
delay: 200
canAttackFlyingUnits: false

image: 主炮1.png
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='重子2')

[turret_3]
x: 0
y: 71
shoot_flame: NONE
shoot_light: #FF00B3FF
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg

shoot_sound_vol: 0.3
#shoot_flame: CUSTOM:气浪*1
image: 主炮2.png
recoilOffset: -1
limitingAngle: 70

delay: 20
canAttackFlyingUnits: false
projectile: 2
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹2
altProjectileCondition: if self.globalTeamTags(includes='反物质2')


[turret_5]
x: -4
y: 7
attachedTo: 7
slave: true
image: 弹头.png

projectile: 3
size: 10
recoilOffset: -10
recoilOutTime: 1
recoilReturnTime: 60

shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾x
delay: 60
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹3
altProjectileCondition: if self.globalTeamTags(includes='反物质2')


[turret_6]
x: 4
y: 7
attachedTo: 7
slave: true
image: 弹头.png

projectile: 3
size: 10
recoilOffset: -10
recoilOutTime: 1
recoilReturnTime: 60

shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾x
delay: 60
warmup: 5

canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹3
altProjectileCondition: if self.globalTeamTags(includes='反物质2')



[turret_7]
x: 17
y: 46
image: 火箭.png
canShoot: false
limitingAngle: 45

idleDir: 90
#canAttackFlyingUnits:false
canAttackCondition: if self.resource.xk < 1 


[turret_8]
x: -4
y: 7
attachedTo: 10
slave: true
image: 弹头.png

projectile: 3
size: 10
recoilOffset: -10
recoilOutTime: 1
recoilReturnTime: 60

shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾x
delay: 60
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹3
altProjectileCondition: if self.globalTeamTags(includes='反物质2')



[turret_9]
x: 4
y: 7
attachedTo: 10
slave: true
image: 弹头.png

projectile: 3
size: 10
recoilOffset: -10
recoilOutTime: 1
recoilReturnTime: 60

shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾x
delay: 60
warmup: 5

canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹3
altProjectileCondition: if self.globalTeamTags(includes='反物质2')


[turret_10]
x: -17
y: 46
image: 火箭.png
canShoot: false
limitingAngle: 45

idleDir: -90
#canAttackFlyingUnits:false
canAttackCondition: if self.resource.xk < 1 


[turret_11]
x: 0
y: 0
invisible: if self.globalTeamTags(includes='反物质2')
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3

shoot_flame: CUSTOM:烟雾x*2
shoot_light: #FFEECCCC
projectile: 4
size: 0
turnSpeed: 811

turnSpeedAcceleration: 10
delay: 30
canAttackLandUnits: false
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹4
altProjectileCondition: if self.globalTeamTags(includes='反物质2')


[projectile_1]
@copyFromSection: template_能源
areaDamage: 300
areaRadius: 65
spawnUnit: 脉冲小*1
life: 300

lightSize: 1
largeHitEffect: true
speed: 8
targetGround: true
trailEffect: CUSTOM:尾巴

drawSize: 1
explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波
explodeEffect: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波
image: ROOT:/余辉军团/单位特效/子弹.png
deflectionPower: -1

trailEffectRate: 2
areaRadiusFromEdge: true


[projectile_2]
@copyFromSection: template_能源
areaDamage: 300
areaRadius: 55
life: 300
lightSize: 1

explodeEffect: CUSTOM:爆炸x, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸x, CUSTOM:闪光
speed: 8
#trailEffect:CUSTOM:尾巴1
drawSize: 0.7

image: ROOT:/余辉军团/单位特效/中子弹.png
deflectionPower: -1
trailEffectRate: 4
areaRadiusFromEdge: true
targetGroundSpread: 50

targetGround: true


[projectile_3]
@copyFromSection: template_爆炸
directDamage: 60
life: 160
lightSize: 1
largeHitEffect: true

speed: 7
image: ROOT:/余辉军团/单位特效/导弹.png
drawSize: 0.8
explodeEffect: CUSTOM:大爆炸,CUSTOM:闪光*1


[projectile_4]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 11
largeHitEffect: true

drawSize: 0.85
image: ROOT:/余辉军团/单位特效/导弹.png
trailEffect: true
directDamage: 200
ballistic: true

ballistic_height: 70
ballistic_delaymove_height: 50
explodeEffect: CUSTOM:爆炸x, CUSTOM:闪光
lightSize: 0.75
lightColor: #FF00B3FF


[projectile_炮弹1]
@copyFromSection: template_爆炸
areaDamage: 1200
areaRadius: 70
life: 200
spawnUnit: 小脉冲*1

speed: 8
image: ROOT:/余辉军团/单位特效/子弹1.png
targetSpeed: 8
drawSize: 1
explodeEffectOnShield: CUSTOM:底色a,CUSTOM:闪光a,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:漩涡

explodeEffect: CUSTOM:底色a,CUSTOM:闪光a,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:漩涡
targetGround: true
areaRadiusFromEdge: true
lightSize: 0.75
trailEffectRate: 1.5

trailEffect: CUSTOM:尾巴3
lightColor: #FF00B3FF
targetGroundSpread: 35
deflectionPower: -1


[projectile_炮弹2]
@copyFromSection: template_能源
areaDamage: 450
areaRadius: 55
life: 300
lightSize: 1

largeHitEffect: true
speed: 8
areaRadiusFromEdge: true
drawSize: 0.8
explodeEffectOnShield: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:底色c

explodeEffect: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:底色c
image: ROOT:/余辉军团/单位特效/中子弹1.png


[projectile_炮弹3]
@copyFromSection: template_能源
areaDamage: 80
areaRadius: 30
life: 160
lightSize: 1

largeHitEffect: true
speed: 7
image: ROOT:/余辉军团/单位特效/导弹.png
drawSize: 0.8
explodeEffect: CUSTOM:大爆炸zz,CUSTOM:闪光v*1

areaRadiusFromEdge: true


[projectile_炮弹4]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 11
largeHitEffect: true

drawSize: 0.85
image: ROOT:/余辉军团/单位特效/导弹.png
trailEffect: true
areaDamage: 280
areaRadius: 40

ballistic: true
ballistic_height: 70
ballistic_delaymove_height: 50
explodeEffect: CUSTOM:大爆炸zz,CUSTOM:闪光v*1
lightSize: 0.75

lightColor: #FF00B3FF
areaRadiusFromEdge: true




[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[effect_爆炸x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.3

image: ROOT:/余辉军团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg
alwayStartDirAtZero: true


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_底色]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.8
scaleTo: 0
alpha: 1.3
drawUnderUnits: false
atmospheric: false


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 9
scaleTo: 9

drawUnderUnits: true
atmospheric: false


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 5
scaleTo: 0.1
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_爆炸5]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.2

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/爆炸.ogg
alwayStartDirAtZero: true


[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/光束2.png
life: 20
fadeOut: true
attachedToUnit: false

color: #63e6e8
fadeInTime: 0.1
scaleFrom: 0.35
scaleTo: 0.35
alpha: 0.7

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 55
fadeOut: true
attachedToUnit: false

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
scaleFrom: 2
scaleTo: 0.1

alpha: 2
drawUnderUnits: false
atmospheric: false


[effect_粒子]
life: 60
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 2
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_大爆炸]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_烟雾x]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.25
scaleTo: 1.25
alpha: 0.65
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true

[effect_底色a]
priority: critical
image: ROOT:/余辉军团/单位特效/黑洞1.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.4
scaleTo: 0
alpha: 1.3
drawUnderUnits: false
atmospheric: false


[effect_漩涡]
priority: critical
image: ROOT:/余辉军团/单位特效/漩涡.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.8
scaleTo: 0
alpha: 0.8
drawUnderUnits: false
atmospheric: false

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_闪光a]
priority: critical
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_粒子a]
life: 60
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 2.8
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
drawUnderUnits: true


[effect_冲击波a]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 3
scaleTo: 0.1
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_尾巴3]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/粗子弹3.png
life: 30
fadeOut: true
attachedToUnit: false

#color:#FFFFFF3D
fadeInTime: 0.1
scaleFrom: 0.17
scaleTo: 0.17
alpha: 0.6

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true
#color:#FFFFFF3D


[effect_底色c]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩1.png
life: 35
fadeOut: true
attachedToUnit: false

scaleFrom: 0.33
scaleTo: 0.33
alpha: 1
drawUnderUnits: false
atmospheric: false


[effect_闪光b]
priority: critical
image: SHARED:light_50.png
life: 150
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFE56BFF
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_爆炸b]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1.1
scaleTo: 1.55
image: ROOT:/余辉军团/单位特效/自制2.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_闪光v]
priority: critical
image: SHARED:light_50.png
life: 150
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFE56BFF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4

drawUnderUnits: false
atmospheric: false


[effect_大爆炸zz]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 1.8

image: ROOT:/余辉军团/单位特效/小爆炸动态1.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
[arm_1]
x: -23
y: 46
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: 23
y: 46
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: 0
y: 77
image_end: 前.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 0
y: -1
image_end: 盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:30, y:0}
arm1_950s: {x:30, y:0}
arm2_1s: {x:-30, y:0}

arm2_950s: {x:-30, y:0}
arm3_1s: {x:0, y:-40}
arm3_950s: {x:0, y:-40}
arm4_1s: {x:0, y:-50}
arm4_950s: {x:0, y:-50}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}

arm4_1s: {x:0, y:0}


[movement]
movementType: WATER
moveSpeed: 0.8
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06
maxTurnSpeed: 0.9

turnAcceleration: 0.05


