

[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[core]
name: 重力吸纳仓t1
displayText: Гравитационный экстрактор t1
displayDescription: 【Уровень t1】【Беспилотный юнит】【Здание】【Наземный юнит】\n-тактическое назначение: ресурсное здание.\n-стандартное добывающее сооружение Империи, использует гравитационные технологии вместе с лазерным буром, \n-и эффективно добывает руду расплавленной мантии, и плавит её в слитки, \n-обеспечивая автоматизированной армии Империи бесконечный поток ресурсов.
effectOnDeath: CUSTOM:烟雾*3, CUSTOM:爆破*5
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1)
class: CustomUnitMetadata
price: 900

maxHp: 800
maxShield: 800
shieldRenderRadius: 1
shieldRegen: 0.3
generation_credits: 16
generation_delay: 40
techLevel: 1
buildSpeed: 8s
radius: 28
isBio: false
isBuilding: true
placeOnlyOnResPool: true
numBitsOnDeath: 10
tags: 地面,建筑,无人单位,寄生免疫
armour: 2
copyFrom: ROOT:/通用特效/单位防护.ini
[action_升级]
convertTo: 重力吸纳仓t2
displayType: action
text: Улучшить
buildSpeed: 20s
price: 1200
description: подъёмвысокий гравитациявсасыватьприниматьустройство эффективность, \n-увеличениедобавитьрудапроизводствовыходит .
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t2')
isLockedMessage: Требуется боевой центр ядра ИИ 2-го уровня
ai_isHighPriority: true
[decal_地板]
image: ROOT:/余辉军团/建筑特效/矿地板.png
total_frames: 1
layer: shadow
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
imageScale: 0.8
alpha:1
[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
yOffsetRelative:3
xOffsetRelative:3
onlyWhileAlive:true
isVisible:true
imageScale: 0.8
alpha:0.5
[decal_泵]
image: ROOT:/余辉军团/建筑特效/动画.png
total_frames: 5
frame: (self.customTimer * 30) % 5
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-0.5
yOffsetRelative:25
onlyWhileAlive:true
layer: onTop
imageScale: 0.8
[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.hp<self.maxHp * 0.36
teamColors: true
imageScale: 0.8
[decal_光头]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8
imageScale: 0.8
[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03
yOffsetRelative:0
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 0.8
[graphics]
total_frames: 1
image: 主体.png
image_wreak: ROOT:/余辉军团/建筑特效/矿死亡.png
image_back: ROOT:/通用特效/NO.png
imageScale: 0.8
image_shadow: NONE

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 30
maxAttackRange: 99999
shootDelay: 0


[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 20
yOffsetRelativeRandom: 30
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:20
yOffsetRelativeRandom:45
delayedStartTimerRandom:30

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1



[ai]
buildPriority: 1
maxEachBase: 12
maxGlobal: 18
ai_upgradePriority: 1
upgradedFrom: 重力吸纳仓空投
