


[core]
name: 太空浪人重组培养箱t3
class: CustomUnitMetadata
price: 2800
maxHp: 7000
selfRegenRate: 0.2

footprint: -2,-1,2,3
constructionFootprint: -2,-1,2,3
techLevel: 1
buildSpeed: 10s
displayDescription: 太空浪人将从战场上收集来的尸体储存于此，\n-并将他们改造成傀儡为自己而战。

radius: 25
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1

exit_x: 0
exit_y: -1
tags: 地面,培养箱,灰影建筑,建筑
armour: 9
canBuild_21_name: setRally

canBuild_21_pos: 0.1


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: 缺少供能
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_断电a]
autoTrigger: if self.queueSize > 0 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
refundAllQueuedItems: true


[action_T1]
pos: 0.1
buildSpeed: 0s
addResources: setFlag=0,setFlag=1
text: 显示t1单位
isVisible: if not self.hasFlag(id=1) and not self.hasFlag(id=0)


[action_T1_back]
pos: 0.1
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=1
isVisible: if self.hasFlag(id=1)
text: 不显示t1单位


[action_T2]
pos: 0.2
buildSpeed: 0s
addResources: setFlag=0,setFlag=2
text: 显示t2单位
isVisible: if not self.hasFlag(id=2) and not self.hasFlag(id=0)


[action_T2_back]
pos: 0.2
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=2
isVisible: if self.hasFlag(id=2)
text: 不显示t2单位


[action_T3]
pos: 0.3
buildSpeed: 0s
addResources: setFlag=0,setFlag=3
text: 显示t3单位
isVisible: if not self.hasFlag(id=3) and not self.hasFlag(id=0)

highPriorityQueue: true
ai_isHighPriority: true


[action_T3_back]
pos: 0.3
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=3
isVisible: if self.hasFlag(id=3)
text: 不显示t3单位


[canBuild_T1]
name: 突变体,撕裂者,穿刺者,毒液,石头人,
pos: 1
isVisible: if self.hasFlag(id=1)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[canBuild_T2]
name: 重型改造僵尸,巨人,电鬼,焚魂者,爆炸僵尸
pos: 1
isVisible: if self.hasFlag(id=2)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[canBuild_T3]
name: 毒蝎,狼牙,狂战士,
pos: 1
isVisible: if self.hasFlag(id=3)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[canBuild_T21]
name: 冥蜂
pos: 1
isVisible: if self.globalTeamTags(includes='灰影1') and self.hasFlag(id=3)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[canBuild_T22]
name: 魔像
pos: 1
isVisible: if self.globalTeamTags(includes='灰影2') and self.hasFlag(id=3)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[canBuild_T23]
name: 基因血巢
pos: 1
isVisible: if self.globalTeamTags(includes='灰影3') and self.hasFlag(id=3)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能





[graphics]
total_frames: 1
image: 主体.png
image_back: 背景.png
image_wreak: ROOT:/太空浪人/太空浪人建筑/t1建筑/太空浪人重组培养箱t1/重组培养箱t1死亡.png
#imageScale:0.7


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: 0
y: -34
image_end: ROOT:/太空浪人/太空浪人建筑/t1建筑/太空浪人重组培养箱t1/门.png
image_end_teamColors: true


[animation_1]
onActions: queuedUnits
blendIn: 1s
blendOut: 2s
onActionsQueuedUnitPlayAt: 0.7
arm1_0: {x:0, y:30}


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[ai]
upgradedFrom: 太空浪人重组培养箱t1传送
ai_upgradePriority: 0.07
maxGlobal: 12


