


[core]
name: 瓦尔基里
displayText: 瓦尔基里
class: CustomUnitMetadata
displayDescription: 【阶级t2】【步兵单位】【空中单位】战术定位:骚扰型飞行步兵，\n-无法被运输。\n-武器配置：▲重机枪X2 对地对空 动能伤害，反掩体 \n-瓦尔基里是一种灵活机动的飞行步兵单位，\n-这些犹如蜂群般的坏小子们可以让敌人鸡犬不宁。
price: 560
maxHp: 60
mass: 45
techLevel: 1
fogOfWarSightRange: 10
isUnrepairableUnit:true
buildSpeed: 8s
radius: 13
softCollisionOnAll: 5
isBio: true
copyFrom: ROOT:/通用特效/单位防护.ini
explodeOnDeath: false
hideScorchMark: true
armour: 0
tags: 步兵,飞机,低空
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:爆炸
[action_外骨骼]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/外骨骼.png
text: 外骨骼技术
isActive: false
isVisible: if self.globalTeamTags(includes='外骨骼')
[hiddenAction_外骨骼生效]
autoTrigger: if self.globalTeamTags(includes='外骨骼') and not self.tags(includes= '外骨骼保险')
setUnitStats: moveSpeed= ${movement.moveSpeed * 1.3},maxHp= ${core.maxHp*1.2},hp= ${core.maxHp*1.2}, maxTurnSpeed = ${movement.maxTurnSpeed* 1.65}
temporarilyAddTags:外骨骼保险

[graphics]
total_frames: 4
image: NO.png
image_wreak:NONE
image_turret: NONE
image_shadow: 影子.png
imageScale: 0.75
turretImageScale: 0.75
movementEffect: CUSTOM:projectileTrail
movementEffectRate: 5
#lock_body_rotation_with_main_turret: true
teamColorsOnTurret: true
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretRotateWithBody: true
maxAttackRange: 150
aimOffsetSpread: -0.01

[turret_1]
x: 8
y: 5
image: 机枪左.png
attachedTo: 3
idleDir: 10
projectile: 1
turnSpeed: 3.0
limitingAngle: 30
turnSpeedAcceleration: 0.5
shoot_sound: ROOT:/创世纪军事集团/步兵特效/重机枪射击.ogg
shoot_sound_vol: 0.06
shoot_flame: CUSTOM:枪口火焰
shoot_light: #FFEECCCC
canShoot: true
size: 16
recoilOffset: -1
delay:3
[turret_2]
x: -8
y: 5
copyFrom: 1
idleDir: -10
image: 机枪右.png
[turret_3]
x: 0
y: 0
image: 躯干.png
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
canShoot: false
[turret_4]
x: 0
y: 2
image: 头盔.png
canShoot: false
attachedTo: 3
slave:true

[projectile_1]
@copyFromSection: template_动能
directDamage: 3
life: 666
speed: 6
targetSpeed: 6
deflectionPower: -1
drawSize: 0.85
explodeEffect: NONE
color: #FFFFFF73
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1
scaleTo: 1
drawUnderUnits: true
liveAfterAttachedDies: true
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.8
ySpeedRelativeRandom: 1.9

hSpeed: 1


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.65
scaleTo: 0.65
drawUnderUnits: true
liveAfterAttachedDies: true
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.8
ySpeedRelativeRandom: 1.9
hSpeed: 1
dirSpeedRandom: 50


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg


[effect_枪口火焰]
life: 20
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false


[effect_projectileTrail]
createWhenZoomedOut: false
frameIndex: 0
stripIndex: effects
life: 50
fadeOut: true
attachedToUnit: false
color: #63e6e8
fadeInTime: 3
scaleFrom: 1
scaleTo: 0.6
alpha: 0.65
drawUnderUnits: true
ySpeedRelative: -0.4
atmospheric: true

[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.015
moveDecelerationSpeed: 0.015
maxTurnSpeed: 5.0

turnAcceleration: 0.5
moveSlidingMode : true
moveIgnoringBody: true
reverseSpeedPercentage: 0
slowDeathFall: false


