


[core]
name: 剑鱼级护卫舰
class: CustomUnitMetadata
price: 3500
maxHp: 4500
displayDescription: -古人类战国时期阿瓦瑞里安王国的标准海军护卫舰，\n-作为一个爱好和平的国家，他们的军用设备并不先进，\n-剑鱼级护卫舰运用简单的技术，能最低限度的保护国家的海洋。\n-在诺瓦帝国统一古人类后，阿瓦瑞里安王国被迫上缴了所有军事装备，\n-其中就包括了大批剑鱼级护卫舰，在与余辉作战最危及的关头，\n-剑鱼被从仓库中取出并作为海洋上的最后一道防线与余辉作战，\n-直至今日，太空浪人依然在生产性价比极高的剑鱼级护卫舰，\n-他们构成了太空浪人海军的前锋力量。对地对空对高空，动能伤害，主炮反掩体。

techLevel: 1
buildSpeed: 20s
availableInDemo: true
radius: 46
displayRadius: 46

isBio: false
softCollisionOnAll: 7
selfRegenRate: 0.2
armour: 15
fogOfWarSightRange: 24

copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,海上,反高空
#showActionsWithMixedSelectionIfOtherUnitsHaveTag:	剑鱼
energyMax: 10
energyRegen: 0.0025

energyNeedsToRechargeToFull: true
effectOnDeath: CUSTOM:爆炸5*1,CUSTOM:冲击波2,CUSTOM:水波1
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36


[action_衰解科技TS1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/衰解.png
text: 相衰解炮2
isActive: false
isVisible: if self.globalTeamTags(includes='衰解2')


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: 赛格门塔护甲1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_1_气球]
text: 释放水雷
displayType: action
buildSpeed: 0.5s
pos: 0.1
displayRemainingStockpile: true

highPriorityQueue: true
price: energy=5
canPlayerCancel: false
spawnUnits: 水雷*1
onlyOneUnitAtATime: true

description: 部署一种自动搜索水上敌人的水雷，\n-他只能被反潜单位拦截，并能对海面以及水下敌人造成最高1500点能源伤害。\n-释放后，他将自动寻找范围为2500以内的敌人，\n-直至被摧毁或者能源耗尽。
isLocked: if self.resource.xk > 0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 身体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
splastEffect: true
teamColorsOnTurret: true
turretImageScale: 0.85


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 75

maxAttackRange: 440
turretMultiTargeting: true


[turret_1]
x: 0
y: 48
image: 主炮.png
canShoot: false
limitingAngle: 100

canAttackCondition: if self.resource.xk < 1
limitingRange: 300
canAttackFlyingUnits: false


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-100
projectile: 13
delay: 120

size: 0
limitingRange: 300


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_2]
x: 0
y: 10
canShoot: true
#recoilOffset:-2
projectile: 1

invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.35
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*3

delay: 10
limitingAngle: 100
attachedTo: 1
slave: true
limitingRange: 290

canAttackFlyingUnits: false
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='衰解2')
size: 12


[turret_3]
x: -15
y: -10
image: 副炮.png
canShoot: false
canAttackCondition: if self.resource.xk < 1

canAttackLandUnits: false
idleDir: -45


[turret_4]
x: -3.5
y: 7
canShoot: true
#recoilOffset:-2
projectile: 2

invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/副炮.ogg
shoot_sound_vol: 1
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2

canAttackLandUnits: false
delay: 10
warmup: 5
attachedTo: 3
slave: true

chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
size: 12
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='衰解2')


[turret_5]
x: 3.5
y: 7
canShoot: true
#recoilOffset:-2
projectile: 2

invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/副炮.ogg
shoot_sound_vol: 1
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2

canAttackLandUnits: false
delay: 15
warmup: 5
attachedTo: 3
slave: true

chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
size: 12
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='衰解2')


[turret_6]
x: 15
y: -10
image: 副炮.png
canShoot: false
canAttackCondition: if self.resource.xk < 1

canAttackLandUnits: false
idleDir: 45


[turret_7]
x: -3.5
y: 7
canShoot: true
#recoilOffset:-2
projectile: 2

invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/副炮.ogg
shoot_sound_vol: 1
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2

canAttackLandUnits: false
delay: 10
warmup: 5
attachedTo: 6
slave: true

chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
size: 12
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='衰解2')


[turret_8]
x: 3.5
y: 7
canShoot: true
#recoilOffset:-2
projectile: 2

invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/副炮.ogg
shoot_sound_vol: 1
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2

canAttackLandUnits: false
delay: 15
warmup: 5
attachedTo: 6
slave: true

chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
size: 12
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='衰解2')


[projectile_1]
@copyFromSection: template_动能
directDamage: 60
life: 180
speed: 12
targetSpeed: 12

trailEffect: false
image: ROOT:/创世纪军事集团/单位特效/子弹.png
drawSize: 0.52
largeHitEffect: true
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:穿透

explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:穿透
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_炮弹]
@copyFromSection: template_能源
directDamage: 57
life: 180
speed: 12
targetSpeed: 12

trailEffect: false
image: ROOT:/太空浪人/单位特效/中子弹1.png
drawSize: 0.65
largeHitEffect: true
explodeEffect: CUSTOM:爆炸s,CUSTOM:闪光s

explodeEffectOnShield: CUSTOM:爆炸s, CUSTOM:闪光s
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: sz=4
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_动能
directDamage: 90
life: 200
speed: 10

image: ROOT:/太空浪人/单位特效/光束.png
targetSpeed: 10
drawSize: 0.88
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光

#targetGround:true
lightSize: 0.75
trailEffectRate: 0.9
trailEffect: CUSTOM:尾巴

lightColor: #FFFF1200


[projectile_炮弹1]
@copyFromSection: template_能源
directDamage: 80
life: 200
areaDamageNoFalloff: true

speed: 10
image: ROOT:/太空浪人/单位特效/光束7.png
targetSpeed: 10
drawSize: 0.88
explodeEffect: CUSTOM:爆炸s1, CUSTOM:闪光s

explodeEffectOnShield: CUSTOM:爆炸s1, CUSTOM:闪光s
#targetGround:true
lightSize: 0.75
trailEffectRate: 0.9

trailEffect: CUSTOM:尾巴s
lightColor: #FF2C56FF
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: sz=4


[effect_穿透]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/子弹.png
life: 70
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.28
scaleTo: 0.1
alpha: 1
drawUnderUnits: false

ySpeedRelative: 4
atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.4

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2

yOffsetRelative: 0.3
ySpeedRelative: 0.5
atmospheric: true


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.3
yOffsetRelative: 0.4
ySpeedAbsoluteRandom: 1
ySpeedRelative: 1
#xOffsetRelative:-2

atmospheric: true


[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_爆炸5]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.2

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/爆炸.ogg
alwayStartDirAtZero: true


[arm_1]
#左肩
x: -27
y: -17
image_end: 左.png
image_end_teamColors: true

drawOverBody: false
#moveSpeed: 6
drawDirOffset: 90


[arm_2]
#左肩
x: 27
y: -17
image_end: 右.png
image_end_teamColors: true

drawOverBody: false
#moveSpeed: 6
drawDirOffset: -90


[effect_尾巴]
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.37
scaleTo: 0.37
alpha: 1

drawUnderUnits: true


[animation_move]
onActions: move
blendIn: 0.5s
blendOut: 0.5s
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}

arm1_0.5s: {x:0, y:0, dir:-90}
arm2_0.5s: {x:0, y:0, dir:90}
arm1_250s: {x:0, y:0, dir:0}
arm2_250s: {x:0, y:0, dir:0}
#————————————————————————


[effect_爆炸s]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.4

image: ROOT:/太空浪人/单位特效/小爆炸动态1.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true


[effect_闪光s]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF2C56FF
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[effect_尾巴s]
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
priority: low

color: #FF2C56FF
fadeInTime: 2
scaleFrom: 0.37
scaleTo: 0.37
alpha: 1

drawUnderUnits: true


[effect_爆炸s1]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.45
image: ROOT:/太空浪人/单位特效/衰解1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: WATER
moveSpeed: 1.43
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06
maxTurnSpeed: 2.3

turnAcceleration: 0.05
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


