


[core]
name: 钢筋混凝土围墙
displayText: Железобетонная стена
class: CustomUnitMetadata
price: 180
maxHp: 3000
copyFrom: ROOT:/通用特效/单位防护.ini

techLevel: 1
buildSpeed: 3s
isBio: false
isBuilding: true
tags: 地面,重型掩体,建筑,防御建筑
fogOfWarSightRange: 1
numBitsOnDeath: 10
armour: 20
radius: 10
displayDescription:【Уровень t3】【Оборонительное здание】【Здание】【Наземный юнит】\n-Тактическое назначение：障碍物，без вооружения。无法在надводный上строить，\n-Стена的意义在于为пехота等юнитобеспечиваетукрытие，\n-或者в качестве障碍物большое количестворазвёртывать，迫使враг清除Стена，阻碍враг的前进。

[action_升级]
convertTo: 强固混凝土围墙
displayType: action
text: 升класс
buildSpeed: 10s
price: 250

isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
description: повышаетСтенауровень，加固其结构强度，и追加视野和进炸броня，造成взрывной урон。\n-在一体浇筑Железобетонная стена的основа上использовать防爆钢板和摄像头，进一步усиливает感知способность和оборонахарактеристики，\n-можетдовольноэффективный抵挡直射огневая мощь弹片冲击和其онполе боя危险，\n-одновременно其外置的爆破динамическая броня在抵御вражеский攻击的одновременно，ещёможетэффективный伤害试图绕开Стена的враг。
[action_重型掩体]
text: тяжёлое укрытие
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处тяжёлое укрытие，может为рядом140范围内的биологический юнитобеспечиваеттяжёлое прикрытие。\n-тяжёлое прикрытиеможет为биологический юнит减免75%的伤害，\n-но，укрытие无法减免部分скорострельный，激光，Огонь，电击，中性，самоподрыв，ближний бой，衰解等其он无视укрытие的оружие。

[graphics]
total_frames: 1
image: 钢筋混凝土围墙.png
image_wreak: 钢筋混凝土围墙死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.75


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


