


[core]
name: 钢筋混凝土围墙
class: CustomUnitMetadata
price: 180
maxHp: 3000
copyFrom: ROOT:/通用特效/单位防护.ini

techLevel: 1
buildSpeed: 3s
isBio: false
isBuilding: true
tags: 地面,重型掩体,建筑,防御建筑
fogOfWarSightRange: 1
numBitsOnDeath: 10
armour: 20
radius: 10
displayDescription:【阶级t3】【防御类建筑】【建筑单位】【地面单位】\n-战术定位：障碍物，无武装。无法在水面上建造，\n-围墙的意义在于为步兵等单位提供掩体，\n-或者作为障碍物大量部署，迫使敌人清除围墙，阻碍敌人的前进。

[action_升级]
convertTo: 强固混凝土围墙
displayType: action
text: 升级
buildSpeed: 10s
price: 250

isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心
description: 提升围墙等级，加固其结构强度，并追加视野和进炸装甲，造成爆炸伤害。\n-在一体浇筑钢筋混凝土围墙的基础上使用防爆钢板和摄像头，进一步强化感知能力和防御性能，\n-能相当有效的抵挡直射火力弹片冲击和其他战场危险，\n-同时其外置的爆破反应装甲在抵御敌方攻击的同时，还能有效伤害试图绕开围墙的敌人。
[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免部分速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。

[graphics]
total_frames: 1
image: 钢筋混凝土围墙.png
image_wreak: 钢筋混凝土围墙死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.75


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


