


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=650


[core]
name: SDAF龙魇
displayText: SDAF Драконий кошмар
tags: 地面,无人单位
copyFrom: SDAF龙魇2.ini, ROOT:/通用特效/单位防护.ini
showInEditor: true
fogOfWarSightRange: 26
armour: 70
[action_x]
@copyFrom_skipThisSection: true
displayType: action
price: 0
buildSpeed: 2.3s
isLocked: if self.queueSize > 0.5 or self.isAttacking() or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

text: близкийбоймодель тип
description: вытягиватьвыходит одинберёт от тяжёлый магнитныйсилапучоксвязывать супервысокий тёплыйэлектричествопастанаручный клинок, \n-против ближняя дистанцияврагистроить стать уничтожение нейтральный урон.\n-но использоватьиспользует плазманаручный клинокбудетбудетзапретиспользует всех дальнийоружие.\n-переключениеоружиемеханизмили  и врагипередаватьогонь, когда будетзапретиспользует переключениеблизкийбойфункцияможет .
iconImage: 刀.png
canPlayerCancel: false
whenBuilding_triggerAction: 亮

whenBuilding_playAnimation: 部署1
#playSoundAtUnit: 部署.ogg
#spawnEffects:CUSTOM:聚变ab,CUSTOM:闪光ab,CUSTOM:粒子ab*15
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 26, 47

convertTo: SDAF龙魇2
addResources: unsetFlag= 0


[hiddenAction_亮]
@copyFrom_skipThisSection: true
resetCustomTimer: true
addResources: setFlag= 0


[hiddenAction_a]
autoTrigger: if self.attachment(withTag= "ANM_cat") == nullUnit and self.queueSize < 0.5
alsoQueueAction: b


[hiddenAction_b]
buildSpeed: 0.65s
convertTo: SDAF龙魇1
whenBuilding_playAnimation: 部署


[hiddenAction_DPS]
@copyFrom_skipThisSection: true


[hiddenAction_DPS1]
@copyFrom_skipThisSection: true


[graphics]
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttackLandUnits: true
maxAttackRange: 510
# turretSize: 14
turretTurnSpeed: 2
# shootDelay: 100

turretRotateWithBody: true
turretMultiTargeting: true
isMelee: false
isFixedFiring: false
showRangeUIGuide: true


[turret_1]
projectile: 11
turnSpeed: 2


[turret_2]
@copyFrom_skipThisSection: true
x: 24
y: 100
size: 36
invisible: true

projectile: 2
attachedTo: 1
slave: true
limitingMinRange: 200
canShoot: true

warmup: 100
delay: 300


[projectile_1]
@copyFrom_skipThisSection: true


[projectile_11]
life: 99
speed: 100
directDamage: 0
drawSize: 0
frame: 1

targetGround: true
explodeEffect: CUSTOM:聚变ab,CUSTOM:闪光ab,CUSTOM:粒子ab*15


[arm_1]
drawDirOffset: -30


[arm_2]
x: 24
y: -6
drawDirOffset: 50


[arm_3]
x: 60
y: 27
drawDirOffset: -60


[arm_4]
x: 60
y: 27
drawDirOffset: -60
hidden: if not self.hasFlag(id= 0) or self.customTimer(withinSeconds= 0.9)


[arm_6]
x: -45
y: 30
drawDirOffset: 34


[arm_8]
# x: 23
y: 42
drawDirOffset: -60


[leg_1]
holdDisMin: 28
holdDisMax: 42


[animation_attack]
@copyFrom_skipThisSection: true


[animation_部署]
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}

arm1_0.65s: {x:-6, y:19, dir:40}
arm2_0.65s: {x:-20, y:1, dir:25}
arm3_0.65s: {x:-15, y:-12, dir:35}
arm6_0.65s: {x:25, y:27, dir:21}
arm8_0.65s: {x:0, y:3, dir:60}


[animation_部署1]
@copyFrom_skipThisSection: true
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}

arm8_0s: {x:0, y:0, dir:0}
arm1_0.65s: {x:-6, y:19, dir:40}
arm2_0.65s: {x:-20, y:1, dir:25}
arm3_0.65s: {x:-15, y:-12, dir:35}
arm6_0.65s: {x:25, y:27, dir:21}

arm8_0.65s: {x:0, y:3, dir:60}
arm1_1.4s: {x:-6, y:26, dir:40}
arm2_1.4s: {x:-19, y:-16, dir:-5}
arm3_1.4s: {x:-20, y:-7, dir:45}
arm6_1.4s: {x:25, y:27, dir:66}

arm8_1.4s: {x:0, y:-42, dir:60}
arm8_1.9s: {x:0, y:-67, dir:60}
arm1_2.3s: {x:0, y:0, dir:-15}
arm2_2.3s: {x:-19, y:-16, dir:-5}
arm3_2.3s: {x:-20, y:-7, dir:45}

arm6_2.3s: {x:-10, y:-3, dir:11}
arm8_2.3s: {x:0, y:-67, dir:60}
arm4_0s: {x:-20, y:-7, dir:45, alpha:0.0}
arm4_1.6s: {x:-20, y:-7, dir:45, alpha:0.0}
arm4_1.61s: {x:-20, y:-7, dir:45, alpha:0.1}

arm4_2.2s: {x:-20, y:-7, dir:45, alpha:1.0}
arm4_2.3s: {x:-20, y:-7, dir:45, alpha:1.0}


[effect_聚变ab]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 100
fadeOut: true
attachedToUnit: true

scaleFrom: 1.5
scaleTo: 1.5
alpha: 0.4
drawUnderUnits: false
atmospheric: false

#ySpeedAbsolute:-1


[effect_闪光ab]
#priority:critical
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 1

attachedToUnit: true
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 7
scaleTo: 7

drawUnderUnits: false
atmospheric: false


[effect_粒子ab]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom: 0.1
scaleTo: 0.4

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7

ySpeedRelativeRandom: 3.7


[effect_sparks]
@copyFrom_skipThisSection: true


[effect_刀光]
@copyFrom_skipThisSection: true


[effect_闪光h]
@copyFrom_skipThisSection: true


[effect_聚变]
@copyFrom_skipThisSection: true


[effect_粒子1]
@copyFrom_skipThisSection: true


[movement]
moveSpeed: 1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0.4
maxTurnSpeed: 1.8

turnAcceleration: 0.05
moveIgnoringBody: false
slowDeathFall: true


