


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=650


[core]
name: SDAF龙魇1
displayText: SDAFДраконий кошмар1
tags: 地面,无人单位
copyFrom: SDAF龙魇2.ini, ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 26
armour: 70
[hiddenAction_a]
autoTrigger: if self.attachment(withTag= "ANM_cat") != nullUnit and self.queueSize < 0.5
alsoQueueAction: b


[hiddenAction_b]
convertTo: SDAF龙魇
displayType: action
buildSpeed: 0.65s
whenBuilding_playAnimation: 部署


[action_x]
@copyFrom_skipThisSection: true
displayType: action
price: 0
buildSpeed: 3.5s
isLocked: if self.queueSize > 0.5 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

text: близкийбоймодель тип
description: вытягиватьвыходит одинберёт от тяжёлый магнитныйсилапучоксвязывать супервысокий тёплыйэлектричествопастанаручный клинок, \n-против ближняя дистанцияврагистроить стать уничтожение нейтральный урон.\n-но использоватьиспользует плазманаручный клинокбудетбудетзапретиспользует всех дальнийоружие.\n-переключениеоружиемеханизмили  и врагипередаватьогонь, когда будетзапретиспользует переключениеблизкийбойфункцияможет .против укрытий.
iconImage: 刀.png
canPlayerCancel: false
whenBuilding_triggerAction: 亮

whenBuilding_playAnimation: 部署1
#playSoundAtUnit: 部署.ogg
#spawnEffects:CUSTOM:聚变ab,CUSTOM:闪光ab,CUSTOM:粒子ab*15
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 26, 47

convertTo: SDAF龙魇2
addResources: unsetFlag= 0


[hiddenAction_亮]
@copyFrom_skipThisSection: true
resetCustomTimer: true
addResources: setFlag= 0
setUnitStats: maxTurnSpeed= 0


[hiddenAction_DPS]
@copyFrom_skipThisSection: true


[hiddenAction_DPS1]
@copyFrom_skipThisSection: true


[graphics]
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttackLandUnits: if not self.queueSize(greaterThan= 0.5)
maxAttackRange: 510
# turretSize: 14
turretTurnSpeed: 2
# shootDelay: 100

turretRotateWithBody: true
turretMultiTargeting: true
isMelee: false
isFixedFiring: false
showRangeUIGuide: true


[turret_1]
projectile: 11
turnSpeed: 2


[turret_2]
@copyFrom_skipThisSection: true
x: 24
y: 100
size: 36
invisible: true

projectile: 1
attachedTo: 1
slave: true
#energyUsage:1
limitingMinRange: 200

canShoot: true
warmupStartEffect: CUSTOM:气浪,CUSTOM:粒子*2
warmup: 100
delay: 300
shoot_sound: ROOT:/余辉军团/单位特效/大主炮音效.ogg

shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾*8
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
shoot_light: #FF00B3FF
onShoot_playAnimation: attack


[turret_3]
x: 44
y: -27
size: 36
invisible: true
projectile: 3

attachedTo: 1
slave: true
energyUsage: 0.5
#limitingMinRange:200
canShoot: true

#warmupStartEffect:CUSTOM:气浪,CUSTOM:粒子*2
#warmup:100
delay: 7
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3

#shoot_light:#FFEECCCC
shoot_flame: CUSTOM:烟雾*2
#chargeEffectImage:ROOT:/余辉军团/单位特效/蓄能.png
shoot_light: #FF00B3FF


[turret_5]
x: -44
y: -27
size: 36
invisible: true
projectile: 3

attachedTo: 1
slave: true
energyUsage: 0.5
#limitingMinRange:200
canShoot: true

#warmupStartEffect:CUSTOM:气浪,CUSTOM:粒子*2
#warmup:100
delay: 7
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3

#shoot_light:#FFEECCCC
shoot_flame: CUSTOM:烟雾*2
#chargeEffectImage:ROOT:/余辉军团/单位特效/蓄能.png
shoot_light: #FF00B3FF


[projectile_1]
@copyFromSection: template_能源
@copyFrom_skipThisSection: true
areaDamage: 4700
areaRadius: 100

life: 300
# lightSize:1
largeHitEffect: true
speed: 10
color: #FFE56BFF

lightColor: #FFE56BFF
lightSize: 0.4
targetGround: true
trailEffect: CUSTOM:尾巴3,CUSTOM:尾巴1
drawSize: 1

image: ROOT:/余辉军团/单位特效/子弹3.png
deflectionPower: -1
trailEffectRate: 2
areaRadiusFromEdge: true
explodeEffect: CUSTOM:闪光h,CUSTOM:光球,CUSTOM:光球2,CUSTOM:云雾,CUSTOM:云雾2,CUSTOM:云雾1,CUSTOM:聚变x,CUSTOM:冲击波1,CUSTOM:弹坑1


[projectile_11]
life: 99
speed: 100
directDamage: 0
drawSize: 0
frame: 1

targetGround: true
explodeEffect: CUSTOM:聚变ab,CUSTOM:闪光ab,CUSTOM:粒子ab*15


[projectile_3]
@copyFromSection: template_爆炸
life: 420
speed: 5
areaDamage: 150
areaRadius: 40

targetSpeed: 9
# largeHitEffect: true
targetGround: true
drawSize: 0.8
lightSize: 1

lightColor: #FF00B3FF
trailEffect: true
largeHitEffect: true
image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:波雷爆炸,CUSTOM:闪光
armourIgnoreAmount:10
targetGroundSpread: 40
areaRadiusFromEdge: true


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波4.png
life: 55
fadeOut: true
attachedToUnit: true

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
scaleFrom: 2
scaleTo: 0.1

alpha: 2
drawUnderUnits: false
atmospheric: false


[effect_粒子]
life: 60
image: ROOT:/余辉军团/单位特效/光粒1.png
scaleFrom: 0.7
attachedToUnit: true
scaleTo: 0.1

alpha: 1
dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_烟雾]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 75

fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF
fadeInTime: 10

scaleFrom: 1.2
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8

ySpeedRelative: 1.5
atmospheric: true


[effect_尾巴3]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/粗子弹2.png
life: 30
fadeOut: true
attachedToUnit: false

#color:#FFFFFF3D
fadeInTime: 0.1
scaleFrom: 0.17
scaleTo: 0.17
alpha: 0.6

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_尾巴1]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波1.png
life: 30
fadeOut: true
attachedToUnit: false

fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.7
alpha: 0.8
drawUnderUnits: false

yOffsetRelative	: -5


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 5
fadeOut: true
alpha: 0.8

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_闪光1]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.1

scaleTo: 0.1
image: ROOT:/余辉军团/单位特效/光束.png
dirOffsetRandom: 180
#—————————————炸裂


[effect_光球]
life: 250
priority: critical
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.8

image: ROOT:/余辉军团/单位特效/收缩1.png
ySpeedAbsolute: -0.7
#yOffsetAbsolute:35
fadeOut: true
alpha: 1

alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg


[effect_光球2]
life: 250
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.58

image: 光球.png
ySpeedAbsolute: -0.7
#drawUnderUnits:true
#yOffsetAbsolute:35
fadeOut: true

alpha: 1
fadeInTime: 1


[effect_云雾]
life: 260
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.4

image: 云雾.png
ySpeedAbsolute: -0.9
#yOffsetAbsolute:90
fadeOut: true
alpha: 1

fadeInTime: 1


[effect_云雾2]
life: 260
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.35

image: 云雾.png
ySpeedAbsolute: -0.8
#yOffsetAbsolute:90
fadeOut: true
alpha: 1

fadeInTime: 1


[effect_云雾1]
life: 260
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.4

image: 云雾.png
ySpeedAbsolute: -0.7
#yOffsetAbsolute:90
fadeOut: true
alpha: 1

fadeInTime: 1


[effect_闪光h]
priority: critical
# image: SHARED:light_50.png
life: 100
# fadeOut: true
alpha: 2

# attachedToUnit: false
color: #FFE56BFF
# fadeInTime:2
scaleFrom: 8
scaleTo: 8

drawUnderUnits: false
atmospheric: false


[effect_聚变x]
priority: critical
image: ROOT:/余辉军团/单位特效/光束1.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 2.5
scaleTo: 2.5
alpha: 0.4
drawUnderUnits: false
atmospheric: false

ySpeedAbsolute: -1
#yOffsetAbsolute:35


[effect_冲击波]
life: 200
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.5

image: 云雾.png
ySpeedAbsolute: -0.7
#yOffsetAbsolute:90
fadeOut: true
alpha: 1

fadeInTime: 1


[effect_冲击波1]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波4.png
life: 200
fadeOut: true
attachedToUnit: false

scaleFrom: 2
scaleTo: 5
alpha: 1
drawUnderUnits: true
atmospheric: false

#yOffsetAbsolute:90


[effect_弹坑1]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 400
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 4
scaleTo: 4
createWhenOverLiquid: false
createWhenOverLand: true
#yOffsetAbsolute:35


[effect_波雷爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.7

scaleTo: 1.4
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[arm_1]
x: -30
y: 5
drawDirOffset: 10


[arm_2]
x: 4
y: -5
drawDirOffset: 75


[arm_3]
x: 45
y: 15
drawDirOffset: -25


[arm_4]
hidden: if not self.hasFlag(id= 0) or self.customTimer(withinSeconds= 0.5)


[arm_6]
x: -20
y: 57
drawDirOffset: 55


[arm_8]
x: 23
y: 45
drawDirOffset: 0


[animation_attack]
@copyFrom_skipThisSection: true
#onActions: attack
blendIn: 0.1s
blendOut: 0.1s
arm8_0.16s: {x:0, y:-19, dir:0}

arm3_0.16s: {x:0, y:-15, dir:10}
arm6_0.16s: {x:0, y:-10, dir:3}
arm1_0.16s: {x:0, y:-8, dir:0}


[animation_部署]
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}

arm1_0.65s: {x:6, y:-19, dir:-40}
arm2_0.65s: {x:20, y:-1, dir:-25}
arm3_0.65s: {x:15, y:12, dir:-35}
arm6_0.65s: {x:-25, y:-27, dir:-21}
arm8_0.65s: {x:0, y:-3, dir:-60}

#============


[animation_部署1]
@copyFrom_skipThisSection: true
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}

arm8_0s: {x:0, y:0, dir:0}
arm1_2s: {x:0, y:0, dir:0}
arm2_2s: {x:0, y:0, dir:0}
arm3_2s: {x:0, y:0, dir:0}
arm6_2s: {x:0, y:0, dir:0}

arm8_2s: {x:0, y:0, dir:0}
arm1_2.6s: {x:0, y:7, dir:0}
arm2_2.6s: {x:1, y:-17, dir:-30}
arm3_2.6s: {x:-5, y:5, dir:10}
arm6_2.6s: {x:0, y:0, dir:45}

arm8_2.6s: {x:0, y:-42, dir:0}
arm8_3.2s: {x:0, y:-70, dir:0}
arm1_3.4s: {x:6, y:-19, dir:-55}
arm2_3.4s: {x:1, y:-17, dir:-30}
arm3_3.4s: {x:-5, y:5, dir:10}

arm6_3.4s: {x:-35, y:-30, dir:-10}
arm1_3.5s: {x:6, y:-19, dir:-55}
arm2_3.5s: {x:1, y:-17, dir:-30}
arm3_3.5s: {x:-5, y:5, dir:10}
arm6_3.5s: {x:-35, y:-30, dir:-10}

arm8_3.5s: {x:0, y:-70, dir:0}
arm4_0s: {alpha:0.0}
arm4_2.8s: {alpha:0.0}
arm4_2.81s: {alpha:0.1}
arm4_3.4s: {alpha:1.0}

arm4_3.5s: {alpha:1.0}


[leg_1]
holdDisMin: 28
holdDisMax: 42


[effect_聚变ab]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 100
fadeOut: true
attachedToUnit: true

scaleFrom: 1.5
scaleTo: 1.5
alpha: 0.4
drawUnderUnits: false
atmospheric: false

#ySpeedAbsolute:-1


[effect_闪光ab]
#priority:critical
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 1

attachedToUnit: true
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 7
scaleTo: 7

drawUnderUnits: false
atmospheric: false


[effect_粒子ab]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom: 0.1
scaleTo: 0.4

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7

ySpeedRelativeRandom: 3.7


[effect_sparks]
@copyFrom_skipThisSection: true


[effect_刀光]
@copyFrom_skipThisSection: true


[effect_聚变]
@copyFrom_skipThisSection: true


[effect_粒子1]
@copyFrom_skipThisSection: true


[movement]
moveSpeed: 0.7
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0.4
maxTurnSpeed: 2

turnAcceleration: 0.05
moveIgnoringBody: false
slowDeathFall: true


