


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=650


[core]
name: SDAF龙魇2
displayText: SDAF Драконий кошмар2
strictLevel: 1
price: 13000, 蓝晶= 1000
radius: 65
# displayRadius: 65
fogOfWarSightRange: 26
maxHp: 14000
maxShield: 16000
shieldRegen: 0.1
energyMax: 5
energyRegen: 0.06

energyNeedsToRechargeToFull: true
armour: 90
tags: 地面,刀,射程x,无人单位
buildSpeed: 60s
class: CustomUnitMetadata

techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini
displayDescription: -Драконий кошмарэто от Империя НоваИмператор женамладший, Шила методмладшийдобродетельустановкарасчёти производство модель тяжёлыймехов, \n-то естьиспользоватьгодэрадолгодалёкий, Драконий кошмарпо-прежнемуэто Империямехов в  выдающийся, \n-его машинатело каждыйодин нольчастьштвсе это Империя Новавысокий конецтехнология кристалл, \n-одновременно, оснащёнимеет Драконий кошмармеховэто Империямашинамастер самыйвысокий честь, \n-Драконий кошмарэто Империя Новагвардия в  гордость, если может имеет удачаввходит Император дворец, \n-тогдаможет смотретьк дворец длинный рядом с галереейвесь вместе расстановканет количествоДраконий кошмармеховзащитасолдат.\n-только по земле, главное орудиеможет источник, взрыв ракеты, клинокв \n-Тип проекта:Империя Нова высокий технологияданные2-й уровень.
#感谢血族大佬的援助

showInEditor: false
transportSlotsNeeded: 4
unitsSpawnedOnDeath: 损毁3*1



[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[hiddenAction_DPS]
alsoQueueAction: DPS1


[hiddenAction_DPS1]
buildSpeed: 0.6s
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 0, 135
#size: 1
#attachedTo:1

#slave:true


[action_x]
displayType: action
price: 0
buildSpeed: 1.2s
isLocked: if self.queueSize > 0.5 or self.isAttacking() or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
text: снайпербитьмодель тип

description: закрытьплазманаручный клиноки тяжёлый новый использоватьиспользует антипротонное копьё, \n-антипротонное копьёможет в мирвсе дистанциядаватьврагистроить стать уничтожениеэнергетический урон.\n-но использоватьиспользует антипротонное копьёбудетзапретиспользует плазманаручный клинок.\n- и врагипередаватьогонь, когда будетзапретиспользует переключениеантипротонное копьёфункцияможет .
iconImage: 狙.png
canPlayerCancel: false
whenBuilding_triggerAction: 亮
whenBuilding_playAnimation: 部署1

convertTo: SDAF龙魇1


[hiddenAction_亮]
#playSoundAtUnit: 部署.ogg
resetCustomTimer: true
temporarilyRemoveTags: 刀


[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 680 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 680 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true


[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 680 | setFlag= 0)


[graphics]
image: SHARED:blank.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
drawLayer: ground2


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.tags(includes='刀')
canAttackUnderwaterUnits: false
maxAttackRange: 85

# turretSize: 35
# turretTurnSpeed: 10
isMelee: true
isFixedFiring: true
showRangeUIGuide: false


[turret_1]
x: 0
y: 0
idleDir: 0
# size: 14
invisible: true

projectile: 1
turnSpeed: 4
canShoot: false
#shouldResetTurret: false


[turret_2]
x: 0
y: 0
invisible: true
delay: 150
#warmup:30

projectile: 2
turnSpeed: 4
attachedTo: 1
slave: true
#shoot_sound:ROOT:/通用特效/光剑1.ogg

shoot_flame: NONE
onShoot_playAnimation: attack
canShoot: true
#canAttackCondition:if self.resource.xk < 1
onShoot_triggerActions: DPS


[projectile_2]
deflectionPower: -1
directDamage: 0
life: 0
invisible: true
explodeEffect: NONE

explodeEffectOnShield: NONE


[projectile_1]
life: 200
areaDamage: 3000
areaRadius: 135
instant: true
speed: 10

targetSpeed: 10
explodeEffect: CUSTOM:刀光*1,CUSTOM:聚变*1,CUSTOM:闪光h*1,CUSTOM:粒子1*15
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[arm_1]
x: -24
y: -14
image_end: 胳膊.png
image_end_shadow: SHADOW:胳膊.png
image_end_teamColors: true

drawDirOffset: -45


[arm_2]
x: 5
y: -22
image_end: 胳膊.png
image_end_shadow: SHADOW:胳膊.png
image_end_teamColors: true

drawDirOffset: 45


[arm_3]
x: 40
y: 20
image_end: 右手.png
image_end_shadow: SHADOW:右手.png
image_end_teamColors: true

drawDirOffset: -15
hidden: if self.tags(includes='刀')


[arm_4]
x: 40
y: 20
image_end: 刀片.png
image_end_teamColors: true
drawDirOffset: -15

hidden: if self.tags(includes='刀') or self.customTimer(laterThanSeconds= 0.9)


[arm_5]
x: 40
y: 20
image_end: 腕刀.png
image_end_teamColors: true
drawDirOffset: -15

hidden: if not self.tags(includes='刀')


[arm_6]
x: -55
y: 27
image_end: 左手.png
image_end_shadow: SHADOW:左手.png
image_end_teamColors: true

drawDirOffset: 45


[arm_7]
x: 0
y: 0
image_end: 身子.png
image_end_shadow: SHADOW:身子.png
image_end_teamColors: true

drawOverBody: true
#drawDirOffset: 50


[arm_8]
x: 23
y: -25
image_end: 枪.png
image_end_shadow: SHADOW:枪.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: 0
hidden: if self.tags(includes='刀')


[arm_9]
x: 0
y: 0
image_end: 枪2.png
image_end_shadow: SHADOW:枪2.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: 0
hidden: if not self.tags(includes='刀')


[arm_10]
x: 0
y: -5
image_end: 头.png
image_end_teamColors: true
drawOverBody: true


[leg_1]
x: -18
y: 8
attach_x: -1
attach_y: -1
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: SDAF巨魔腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 18

holdDisMax: 30
hardLimit: 60


[leg_2]
x: 18
y: 8
attach_x: 1
attach_y: -1
copyFrom: 1

drawDirOffset: 10


[animation_attack]
#onActions: attack
blendIn: 0.05s
blendOut: 0.05s
#KeyframeTimeScale: 0.15
# arm3_0s: {x:0, y:0, dir:0}

arm10_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm1_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}

arm2_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm5_0.3s: {x:-10, y:12, dir:-75}
# arm2_0.3s: {x:0, y:0, dir:0}
arm6_0.3s: {x:-8, y:-12, dir:10}

arm1_0.3s: {x:0, y:-9, dir:-5}
arm7_0.3s: {dir:-30}
arm9_0.3s: {dir:-30}
arm5_0.5s: {x:-10, y:12, dir:-75}
# arm2_0.5s: {x:0, y:0, dir:0}

arm6_0.5s: {x:-8, y:-12, dir:10}
arm1_0.5s: {x:0, y:-9, dir:-5}
arm7_0.5s: {dir:-30}
arm9_0.5s: {dir:-30}
arm5_0.6s: {x:0, y:0, dir:15}

# arm2_0.6s: {x:0, y:0, dir:0}
arm6_0.6s: {x:0, y:0, dir:0}
arm1_0.6s: {x:0, y:0, dir:0}
arm9_0.6s: {dir:0}
arm7_0.6s: {dir:0}

arm5_0.65s: {x:0, y:0, dir:105}
arm9_0.7s: {dir:15}
arm7_0.7s: {dir:15}
arm5_1.0s: {x:0, y:0, dir:0}
arm2_1.0s: {x:0, y:0, dir:0}

arm6_1.0s: {x:0, y:0, dir:0}
arm1_1.0s: {x:0, y:0, dir:0}
arm9_1.0s: {dir:0}
arm7_1.0s: {dir:0}
#============


[animation_部署1]
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}

arm8_0.6s: {x:0, y:70, dir:0}
arm1_1.2s: {x:-6, y:19, dir:55}
arm2_1.2s: {x:-1, y:17, dir:30}
arm3_1.2s: {x:5, y:-5, dir:-10}
arm6_1.2s: {x:35, y:30, dir:10}

arm8_1.2s: {x:0, y:70, dir:0}
arm4_0s: {x:0, y:0, dir:0, alpha:1.0}
arm4_0.1s: {alpha:1.0}
arm4_0.7s: {alpha:0.1}
arm4_0.71s: {alpha:0.0}

arm4_1.2s: {x:5, y:-5, dir:-10, alpha:0.0}


[effect_sparks]
attachedToUnit: false
life: 60
scaleFrom: 0.3
scaleTo: 0.3
physics: true

xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.7

#==========================｛🌿｝


[effect_刀光]
priority: critical
image: 刀光.png
spawnChance: 1
createWhenZoomedOut: false
life: 40

fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1

scaleTo: 2.8
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

#dirOffsetRandom:180
#ySpeedRelativeRandom: 0.1
#xSpeedRelativeRandom: 0.6
yOffsetRelative: 0
ySpeedRelative: 1.6

atmospheric: false
alsoPlaySound: ROOT:/通用特效/光剑1.ogg


[effect_闪光h]
#priority:critical
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.4
drawUnderUnits: false
atmospheric: false

#ySpeedAbsolute:-1
#yOffsetAbsolute:35


[effect_粒子1]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom: 0.1
scaleTo: 0.4

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 4

ySpeedRelative: 5
ySpeedRelativeRandom: 2
#atmospheric: true


[movement]
movementType: OVER_CLIFF
moveSpeed: 1.9
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1
maxTurnSpeed: 2.4

turnAcceleration: 0.1
targetHeight: 2
moveSlidingMode: false
moveIgnoringBody: true


