


[core]
name: 检测中介4
displayText: обнаружениев посредник4
strictLevel: 1
price: 0
radius: 10
maxHp: 999

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
buildSpeed: 5s
canNotBeDirectlyAttacked: true

# isUnrepairableUnit: true
# isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
ignoreInUnitCapCalculation: true


[graphics]
image: NO.png
isVisible: false


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 600


[turret_1]
x: 0
y: 0
projectile: 1
delay: 0.9s
canAttackMaxAngle: 181

invisible: true
onShoot_triggerActions: 1


[projectile_1]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true


[hiddenAction_1]
temporarilyRemoveTags: ANM_cat
resetCustomTimer: true


[hiddenAction_2]
autoTrigger: if self.customTimer(laterThanSeconds= 1.0)
temporarilyAddTags: ANM_cat


[hiddenAction_3]
autoTrigger: if not self.hasParent()
deleteSelf: true


[movement]
movementType: LAND


