


[core]
name: 和平守卫者3
displayText: 和平守卫者落点
class: CustomUnitMetadata
price: 0
maxHp: 10
armour: 999989
techLevel: 2
radius: 0
displayRadius: 0
armourMinDamageToKeep: 0
showInEditor:false
hideScorchMark: true
disableAllUnitCollisions: true
isBio: false
canNotBeDirectlyAttacked: true
isUnselectable: true
fireTurretXAtSelfOnDeath: 1
explodeOnDeath: false
energyMax: 12
energyRegen: -0.016
energyStartingPercentage: 1
dieOnZeroEnergy: true
fogOfWarSightRange: 40
showOnMinimap:false
isBuilding: true
autoTriggerCooldownTime:0.01s
autoTriggerCooldownTime_allowDangerousHighCPU:true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_散热]
autoTrigger:true
addResources:太麻烦=0.4,太麻烦1=-0.04,太麻烦2=0.01


[hiddenAction_损坏]
autoTrigger: if self.isEnergyFull()
deleteSelf: true
[decal_闪光]
image:50.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: 90
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/12
[decal_闪光1]
image:50.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: 90
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/12
[decal_闪光2]
image:50.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: 90
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/12

[decal_闪光3]
image:52.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: 40
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/7
[decal_闪光4]
image:52.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: 40
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/7
[decal_闪光44]
image:52.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: 40
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/7
[decal_冲击波]
image:ROOT:/创世纪军事集团/单位特效/超级冲击波.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: (self.resource.太麻烦)*1.5
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:((self.energy)-5)/12
[decal_冲击波1]
image:ROOT:/创世纪军事集团/单位特效/超级冲击波.png
total_frames: 1
layer: shadow
isVisible:true
imageScale: (self.resource.太麻烦)*0.7
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:((self.energy)-5)/12
[decal_爆闪]
image:大闪光.png
total_frames: 1
layer: shadow
isVisible:true
imageScale:29
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.resource.太麻烦1)*1
[decal_爆闪1]
image:51.png
total_frames: 1
layer: shadow
isVisible:true
imageScale:125
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.resource.太麻烦1)/2.2
[decal_爆闪2]
image:51.png
total_frames: 1
layer: shadow
isVisible:true
imageScale:125
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.resource.太麻烦1)/1.9
[decal_爆闪3]
image:51.png
total_frames: 1
layer: shadow
isVisible:true
imageScale:125
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.resource.太麻烦1)/1.9




[decal_云雾a]
image:云雾1.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:1+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*30
onlyWhileAlive:true
alpha:(self.energy)/3
[decal_云雾b]
image:云雾1.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:1+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*30
onlyWhileAlive:true
alpha:(self.energy)/3

[decal_烟柱dc]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.25+(self.resource.太麻烦)/280
#480/x=1.5
yOffsetRelative:-18
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/3
[decal_烟柱dc1]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.25+(self.resource.太麻烦)/280
#480/x=1.5
yOffsetRelative:-18
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/3
[decal_火球ct]
image:光球1.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.5+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)
onlyWhileAlive:true
alpha:(self.energy)/5
[decal_火球a]
image:光球1.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:1.2+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*30
onlyWhileAlive:true
alpha:(self.energy)/7
[decal_火球ab]
image:光球1.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.5+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*30
onlyWhileAlive:true
alpha:(self.energy)/7

[decal_烟柱ax]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.35+(self.resource.太麻烦)/280
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)
onlyWhileAlive:true
alpha:(self.energy)/5
[decal_烟柱bx]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.35+(self.resource.太麻烦)/280
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)
onlyWhileAlive:true
alpha:(self.energy)/5


[decal_烟柱a]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.2+(self.resource.太麻烦)/280
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*3
onlyWhileAlive:true
alpha:(self.energy)/5
[decal_烟柱b]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.2+(self.resource.太麻烦)/280
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*3
onlyWhileAlive:true
alpha:(self.energy)/5

[decal_烟柱]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.2+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:20
xOffsetRelative: 0
yOffsetAbsolute:(self.resource.太麻烦1)*6
onlyWhileAlive:true
alpha:(self.energy)/5
[decal_烟柱1]
image:烟柱.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:0.2+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:20
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*6
onlyWhileAlive:true
alpha:(self.energy)/5


[decal_火球y]
image:长火光.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:(self.resource.太麻烦)/265
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*30
onlyWhileAlive:true
alpha:(self.energy)/12

[decal_火球]
image:光球.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:1+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*30
onlyWhileAlive:true
alpha:(self.energy)/4
[decal_火球1]
image:光球.png
total_frames: 1
layer: beforeUI
isVisible:true
imageScale:1+(self.resource.太麻烦)/240
#480/x=1.5
yOffsetRelative:0
xOffsetRelative:0
yOffsetAbsolute:(self.resource.太麻烦1)*30
onlyWhileAlive:true
alpha:(self.energy)/5

[graphics]
total_frames: 1
image:ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 1
icon_zoomed_out_neverShow:true
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 150

aimOffsetSpread: 0
shootDelay: 1
turretMultiTargeting: true


[resource_太麻烦]
displayName: 太麻烦
displayNameShort: 太麻烦
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_太麻烦1]
displayName: 太麻烦1
displayNameShort: 太麻烦1
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_太麻烦2]
displayName: 太麻烦2
displayNameShort: 太麻烦2
displayColor: #FF9D00FF
priority: 1
hidden: true
[movement]
movementType: AIR
moveSpeed: 1
maxTurnSpeed: 1
targetHeight: -1
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true


