


[core]
name: 和平守卫者
displayText: 和平守卫者落点
class: CustomUnitMetadata
price: 0
maxHp: 10
armour: 999989
techLevel: 2
radius: 100
displayRadius: 100
armourMinDamageToKeep: 0
showInEditor:false
hideScorchMark: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
isBio: false
energyMax: 18
tags:反高空
energyRegen: -0.01
fogOfWarSightRange: 40
explodeOnDeath: false
energyStartingPercentage: 0
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_不能这么干]
autoTrigger:if self.hasActiveWaypoint(type='patrol') or self.hasActiveWaypoint(type='guard')
clearAllWaypoints: true
showMessageToPlayer:导弹不能执行巡逻或者保护单位的命令。
[hiddenAction_添加]
autoTrigger: if self.resource.1>0.5 and self.isEnergyEmpty() and not self.tags(includes= '1号')
addResources: energy=6
temporarilyAddTags:1号
[hiddenAction_添加1]
autoTrigger: if self.resource.2>0.5 and self.isEnergyEmpty() and not self.tags(includes= '2号')
addResources: energy=12
temporarilyAddTags:2号
[hiddenAction_添加2]
autoTrigger: if self.resource.3>0.5 and self.isEnergyEmpty() and not self.tags(includes= '3号')
addResources: energy=18
temporarilyAddTags:3号

[hiddenAction_损坏]
spawnUnits:和平守卫者1(spawnSource= self.getOffsetRelative(x= 0, y= 0,dirOffset=0))
autoTrigger: if self.isEnergyEmpty() and (self.tags(includes= '1号') or self.tags(includes= '2号') or self.tags(includes= '3号'))
deleteSelf: true
[decal_2]
image: ROOT:/通用特效/外圈.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.1>0.5
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:(self.energy)/6
[decal_4]
image: ROOT:/通用特效/外圈1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.1>0.5 and self.tags(includes= '1号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/6
alwaysStartDirAtZero:true
imageScale:(self.energy)/6
[decal_1]
image: 目标.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.1>0.5 and self.tags(includes= '1号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
[decal_3]
image: 目标1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.1>0.5 and self.tags(includes= '1号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/6
alwaysStartDirAtZero:true
[decal_9]
image: ROOT:/通用特效/准星1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.1>0.5 and self.tags(includes= '1号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:1.6
[decal_10]
image: ROOT:/通用特效/准星.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.1>0.5 and self.tags(includes= '1号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/6
imageScale:1.6
alwaysStartDirAtZero:true
[decal_主体]
image: 中心.png
total_frames: 1
layer: beforeUI
isVisible:if self.resource.1>0.5 and self.tags(includes= '1号')
onlyWhileAlive:true
alpha:0.6
imageScale:0.5
alwaysStartDirAtZero:true
#————————————————————————
[decal_2x]
image: ROOT:/通用特效/外圈1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.2>0.5 and self.tags(includes= '2号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:(self.energy)/12
[decal_4x]
image: ROOT:/通用特效/外圈1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.2>0.5 and self.tags(includes= '2号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/12
alwaysStartDirAtZero:true
imageScale:(self.energy)/12
[decal_1x]
image: 目标.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.2>0.5 and self.tags(includes= '2号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
[decal_3x]
image: 目标1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.2>0.5 and self.tags(includes= '2号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/12
alwaysStartDirAtZero:true
[decal_9x]
image: ROOT:/通用特效/准星1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.2>0.5 and self.tags(includes= '2号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:1.6
[decal_10x]
image: ROOT:/通用特效/准星.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.2>0.5 and self.tags(includes= '2号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/12
imageScale:1.6
alwaysStartDirAtZero:true
[decal_主体x]
image: 中心.png
total_frames: 1
layer: beforeUI
isVisible:if self.resource.2>0.5 and self.tags(includes= '2号')
onlyWhileAlive:true
alpha:0.6
imageScale:0.5
alwaysStartDirAtZero:true
#————————————————————————
[decal_2xa]
image: ROOT:/通用特效/外圈.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.3>0.5 and self.tags(includes= '3号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:(self.energy)/18
[decal_4xa]
image: ROOT:/通用特效/外圈1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.3>0.5 and self.tags(includes= '3号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/18
alwaysStartDirAtZero:true
imageScale:(self.energy)/18
[decal_1xa]
image: 目标.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.3>0.5 and self.tags(includes= '3号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
[decal_3xa]
image: 目标1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.3>0.5 and self.tags(includes= '3号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/18
alwaysStartDirAtZero:true
[decal_9xa]
image: ROOT:/通用特效/准星1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.3>0.5 and self.tags(includes= '3号')
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:1.6
[decal_10xa]
image: ROOT:/通用特效/准星.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:if self.resource.3>0.5 and self.tags(includes= '3号')
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/18
imageScale:1.6
alwaysStartDirAtZero:true
[decal_主体xa]
image: 中心.png
total_frames: 1
layer: beforeUI
isVisible:if self.resource.3>0.5 and self.tags(includes= '3号')
onlyWhileAlive:true
alpha:0.6
imageScale:0.5
alwaysStartDirAtZero:true
[graphics]
total_frames: 1
image:ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 1
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
isVisibleToEnemies:false
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 1

aimOffsetSpread: 0
shootDelay: 1
turretMultiTargeting: true
[turret_1]
x: 0
y: 0
invisible: true
delay: 1
projectile: 1

turnSpeed: 100
turnSpeedAcceleration: 1000
shoot_sound: NONE
shoot_flame:  NONE
canShoot: true
size: 0
[projectile_1]
life: 0
areaDamageNoFalloff: true
areaDamage: 0
areaRadius: 0
instant: true
speed: 10
targetSpeed: 10
explodeEffect: NONE
areaRadiusFromEdge: true
explodeEffectOnShield:NONE
[movement]
movementType: AIR
moveSpeed: 1
maxTurnSpeed: 1
targetHeight: -1
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true

[resource_1]
displayName: 1
displayNameShort: 1
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_2]
displayName: 2
displayNameShort: 2
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_3]
displayName: 3
displayNameShort: 3
displayColor: #FF9D00FF
priority: 1
hidden: true
