


[core]
name: 和平冲击波
price: 0
radius: 0
maxHp: -1
class: CustomUnitMetadata

# showInEditor: false
canNotBeDirectlyAttacked: true
isUnrepairableUnit: true
isUnselectable: true
disableAllUnitCollisions: true
showInEditor:false
isBuilding: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
explodeOnDeath: false
hideScorchMark: true
showOnMinimap:false
# autoTriggerCooldownTime: 0.01s
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 999, 999
deleteSelf: true


[graphics]
image: SHARED:blank.png
# isVisible: false
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: false
maxAttackRange: 700


[turret_1]
x: 0
y: 0
canShoot: false
projectile: a2
# 650爆炸范围


[template_1]
@global life1= 15
deflectionPower: -1
speed: 0
turnSpeed: 0.0
directDamage: 0

invisible: true
explodeEffect: none
explodeEffectOnShield: none


[projectile_a2]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b2(recursionLimit= 999, offsetDir= 0), b2(recursionLimit= 999, offsetDir= 60), b2(recursionLimit= 999, offsetDir= 120), b2(recursionLimit= 999, offsetDir= 180), b2(recursionLimit= 999, offsetDir= 240), b2(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a3(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a3]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b3(recursionLimit= 999, offsetDir= 0), b3(recursionLimit= 999, offsetDir= 60), b3(recursionLimit= 999, offsetDir= 120), b3(recursionLimit= 999, offsetDir= 180), b3(recursionLimit= 999, offsetDir= 240), b3(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a4(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a4]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b4(recursionLimit= 999, offsetDir= 0), b4(recursionLimit= 999, offsetDir= 60), b4(recursionLimit= 999, offsetDir= 120), b4(recursionLimit= 999, offsetDir= 180), b4(recursionLimit= 999, offsetDir= 240), b4(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a5(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a5]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b5(recursionLimit= 999, offsetDir= 0), b5(recursionLimit= 999, offsetDir= 60), b5(recursionLimit= 999, offsetDir= 120), b5(recursionLimit= 999, offsetDir= 180), b5(recursionLimit= 999, offsetDir= 240), b5(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a6(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a6]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b6(recursionLimit= 999, offsetDir= 0), b6(recursionLimit= 999, offsetDir= 60), b6(recursionLimit= 999, offsetDir= 120), b6(recursionLimit= 999, offsetDir= 180), b6(recursionLimit= 999, offsetDir= 240), b6(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a7(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a7]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b7(recursionLimit= 999, offsetDir= 0), b7(recursionLimit= 999, offsetDir= 60), b7(recursionLimit= 999, offsetDir= 120), b7(recursionLimit= 999, offsetDir= 180), b7(recursionLimit= 999, offsetDir= 240), b7(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a8(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a8]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b8(recursionLimit= 999, offsetDir= 0), b8(recursionLimit= 999, offsetDir= 60), b8(recursionLimit= 999, offsetDir= 120), b8(recursionLimit= 999, offsetDir= 180), b8(recursionLimit= 999, offsetDir= 240), b8(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a9(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a9]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b9(recursionLimit= 999, offsetDir= 0), b9(recursionLimit= 999, offsetDir= 60), b9(recursionLimit= 999, offsetDir= 120), b9(recursionLimit= 999, offsetDir= 180), b9(recursionLimit= 999, offsetDir= 240), b9(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a10(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a10]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b10(recursionLimit= 999, offsetDir= 0), b10(recursionLimit= 999, offsetDir= 60), b10(recursionLimit= 999, offsetDir= 120), b10(recursionLimit= 999, offsetDir= 180), b10(recursionLimit= 999, offsetDir= 240), b10(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a11(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a11]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b11(recursionLimit= 999, offsetDir= 0), b11(recursionLimit= 999, offsetDir= 60), b11(recursionLimit= 999, offsetDir= 120), b11(recursionLimit= 999, offsetDir= 180), b11(recursionLimit= 999, offsetDir= 240), b11(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a12(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a12]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b12(recursionLimit= 999, offsetDir= 0), b12(recursionLimit= 999, offsetDir= 60), b12(recursionLimit= 999, offsetDir= 120), b12(recursionLimit= 999, offsetDir= 180), b12(recursionLimit= 999, offsetDir= 240), b12(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a13(recursionLimit= 999, offsetRandomDir= 360)


[projectile_a13]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b13(recursionLimit= 999, offsetDir= 0), b13(recursionLimit= 999, offsetDir= 60), b13(recursionLimit= 999, offsetDir= 120), b13(recursionLimit= 999, offsetDir= 180), b13(recursionLimit= 999, offsetDir= 240), b13(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a14(recursionLimit= 999, offsetRandomDir= 360)

[projectile_a14]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b14(recursionLimit= 999, offsetDir= 0), b14(recursionLimit= 999, offsetDir= 60), b14(recursionLimit= 999, offsetDir= 120), b14(recursionLimit= 999, offsetDir= 180), b14(recursionLimit= 999, offsetDir= 240), b14(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a15(recursionLimit= 999, offsetRandomDir= 360)

[projectile_a15]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b15(recursionLimit= 999, offsetDir= 0), b15(recursionLimit= 999, offsetDir= 60), b15(recursionLimit= 999, offsetDir= 120), b15(recursionLimit= 999, offsetDir= 180), b15(recursionLimit= 999, offsetDir= 240), b15(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a16(recursionLimit= 999, offsetRandomDir= 360)

[projectile_a16]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b16(recursionLimit= 999, offsetDir= 0), b16(recursionLimit= 999, offsetDir= 60), b16(recursionLimit= 999, offsetDir= 120), b16(recursionLimit= 999, offsetDir= 180), b16(recursionLimit= 999, offsetDir= 240), b16(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a17(recursionLimit= 999, offsetRandomDir= 360)

[projectile_a17]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b17(recursionLimit= 999, offsetDir= 0), b17(recursionLimit= 999, offsetDir= 60), b17(recursionLimit= 999, offsetDir= 120), b17(recursionLimit= 999, offsetDir= 180), b17(recursionLimit= 999, offsetDir= 240), b17(recursionLimit= 999, offsetDir= 300)
spawnProjectilesOnEndOfLife: a18(recursionLimit= 999, offsetRandomDir= 360)

[projectile_a18]
@copyFromSection: template_1
life: ${life1}
spawnProjectilesOnCreate: b18(recursionLimit= 999, offsetDir= 0), b18(recursionLimit= 999, offsetDir= 60), b18(recursionLimit= 999, offsetDir= 120), b18(recursionLimit= 999, offsetDir= 180), b18(recursionLimit= 999, offsetDir= 240), b18(recursionLimit= 999, offsetDir= 300)
#spawnProjectilesOnEndOfLife: a16(recursionLimit= 999, offsetRandomDir= 360)
[projectile_b2]
@copyFromSection: template_1
@define num1= 2
life: 0
spawnProjectilesOnCreate: b2(recursionLimit= ${num1}, offsetDir= ${360 / 6 / num1} )
spawnProjectilesOnEndOfLife: a(recursionLimit= 999, xOffsetRelative= ${num1 * 50} )


[projectile_b3]
@copyFromSection: projectile_b2
@define num1= 3
spawnProjectilesOnCreate: b3(recursionLimit= ${num1 + 1}, offsetDir= ${360 / 6 / num1} )


[projectile_b4]
@copyFromSection: projectile_b2
@define num1= 4
spawnProjectilesOnCreate: b4(recursionLimit= ${num1 + 2}, offsetDir= ${360 / 6 / num1} )


[projectile_b5]
@copyFromSection: projectile_b2
@define num1= 5
spawnProjectilesOnCreate: b5(recursionLimit= ${num1 + 3}, offsetDir= ${360 / 6 / num1} )


[projectile_b6]
@copyFromSection: projectile_b2
@define num1= 6
spawnProjectilesOnCreate: b6(recursionLimit= ${num1 + 4}, offsetDir= ${360 / 6 / num1} )


[projectile_b7]
@copyFromSection: projectile_b2
@define num1= 7
spawnProjectilesOnCreate: b7(recursionLimit= ${num1 + 5}, offsetDir= ${360 / 6 / num1} )


[projectile_b8]
@copyFromSection: projectile_b2
@define num1= 8
spawnProjectilesOnCreate: b8(recursionLimit= ${num1 + 6}, offsetDir= ${360 / 6 / num1} )


[projectile_b9]
@copyFromSection: projectile_b2
@define num1= 9
spawnProjectilesOnCreate: b9(recursionLimit= ${num1 + 7}, offsetDir= ${360 / 6 / num1} )


[projectile_b10]
@copyFromSection: projectile_b2
@define num1= 10
spawnProjectilesOnCreate: b10(recursionLimit= ${num1 + 8}, offsetDir= ${360 / 6 / num1} )


[projectile_b11]
@copyFromSection: projectile_b2
@define num1= 11
spawnProjectilesOnCreate: b11(recursionLimit= ${num1 + 9}, offsetDir= ${360 / 6 / num1} )


[projectile_b12]
@copyFromSection: projectile_b2
@define num1= 12
spawnProjectilesOnCreate: b12(recursionLimit= ${num1 + 10}, offsetDir= ${360 / 6 / num1} )


[projectile_b13]
@copyFromSection: projectile_b2
@define num1= 13
spawnProjectilesOnCreate: b13(recursionLimit= ${num1 + 11}, offsetDir= ${360 / 6 / num1} )

[projectile_b14]
@copyFromSection: projectile_b2
@define num1= 14
spawnProjectilesOnCreate: b14(recursionLimit= ${num1 + 12}, offsetDir= ${360 / 6 / num1} )

[projectile_b15]
@copyFromSection: projectile_b2
@define num1= 15
spawnProjectilesOnCreate: b15(recursionLimit= ${num1 + 13}, offsetDir= ${360 / 6 / num1} )

[projectile_b16]
@copyFromSection: projectile_b2
@define num1= 16
spawnProjectilesOnCreate: b16(recursionLimit= ${num1 + 14}, offsetDir= ${360 / 6 / num1} )

[projectile_b17]
@copyFromSection: projectile_b2
@define num1= 17
spawnProjectilesOnCreate: b17(recursionLimit= ${num1 + 15}, offsetDir= ${360 / 6 / num1} )

[projectile_b18]
@copyFromSection: projectile_b2
@define num1= 18
spawnProjectilesOnCreate: b18(recursionLimit= ${num1 + 16}, offsetDir= ${360 / 6 / num1} )
[projectile_a]
@copyFromSection: template_1,template_能源,template_战略武器
life: 0
explodeOnEndOfLife: true
areaDamage: 800
largeHitEffect: true
areaRadius: 80
areaRadiusFromEdge: true
# invisible: false
spawnUnit:贴画炮弹1(addResources=energy:14)

nukeWeapon: false
areaHitAirAndLandAtSameTime: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_波雷爆炸]
life: 120
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3
image: ROOT:/创世纪军事集团/单位特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.28
alwayStartDirAtZero: true

alpha: 1.2


[movement]
movementType: AIR
moveSpeed: 0
moveAccelerationSpeed: 0
maxTurnSpeed: 0
targetHeight: 0

targetHeightDrift: 0


