

[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}

[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}
[core]
name: 超级计算机核心
displayDescription: 【阶级t3】【建筑单位】【地面单位】【水上单位】（当部署在水上时）【无人单位】\n-战术定位：科技研发设施，无武装。\n-水陆两栖，只能拥有一个。超级计算机核心是一种快速部署大型量子计算单元，\n-这种军用超级计算机负责储存和处理余辉军队的各级进阶武装的数据，\n-军备蓝图下载到位后，计算核心将会将解压完成的数据包上传至指挥网络的各级生产节点，\n-以便生产帝国各种强大的战争兵器
class: CustomUnitMetadata
price: 2200
maxHp: 7000
fogOfWarSightRange: 25
maxShield: 7000
shieldRegen: 0.09
techLevel: 1
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 1
buildSpeed: 20s
footprint: -6,-2,6,4
constructionFootprint: -6,-2,6,4
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 75
showInEditor: false
isBio: false
isBuilding: true
tags: 计算机,地面,建筑,无人单位
#numBitsOnDeath: 13
softCollisionOnAll: 3
armour: 10
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*10
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1)
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='计算机')
deleteSelf: true
addResources: 威胁点数=-${core.price / 25}
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈

[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上



[action_泽塔诺亚1]
text: 泽塔诺亚蓝图数据库1
buildSpeed: 20s
price: 1200,energy=1
description: -泽塔诺亚联合公司负责向帝国提供各种中低端武器，泽塔诺亚基础蓝图数据库\n-中的武器装备虽然较为老旧，但其久经考验，能保证实用并且有效。\n-这将解锁潜伏者和离子脉冲炮台t1，\n-热射线炮塔t3，等离子炮塔t3。
isVisible: if not self.globalTeamTags(includes='泽塔诺亚1')
addGlobalTeamTags: 泽塔诺亚1
addResources: energy=1
iconImage: 泽塔诺亚1.png
showMessageToPlayer: 泽塔诺亚蓝图数据库1级已下载
pos: 1
ai_isHighPriority: true


[action_泽塔诺亚2]
text: 泽塔诺亚蓝图数据库2
buildSpeed: 45s
price: 1500,energy=1,蓝晶=400
description: -泽塔诺亚公司的进阶蓝图包含了一些帝国初期使用的军备图纸，\n-以及战国时期其他派系经典战争机器的制造方法，这些可靠的旧式装备至今仍极具威力。\n-这将解锁震荡波，咆哮者，离子脉冲炮台t2以及亡魂。\n-凤凰级护卫舰，浮岛要塞的前置科技。
isVisible: if self.globalTeamTags(includes='泽塔诺亚1') and not self.globalTeamTags(includes='泽塔诺亚2')
addGlobalTeamTags: 泽塔诺亚2
addResources: energy=1
iconImage: 泽塔诺亚2.png
ai_isHighPriority: true
showMessageToPlayer: 泽塔诺亚蓝图数据库2级已下载
pos: 1.1

[action_泽塔诺亚3]
text: 泽塔诺亚蓝图数据库3
buildSpeed: 90s
price: 4500,energy=1,蓝晶=1500
description: -泽塔诺亚公司的高阶蓝图包含了大量帝国现役常规兵器的图纸，\n-这些极其有效且先进的作战兵器，被执法兵团和边防军广泛配备。\n-这将解锁圣裁战锤。同时是苍穹猎者的前置科技
isVisible: if self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='泽塔诺亚3')
addGlobalTeamTags: 泽塔诺亚3
addResources: energy=1
iconImage: 泽塔诺亚3.png
ai_isHighPriority: true
showMessageToPlayer: 泽塔诺亚蓝图数据库3级已下载
pos: 1.2
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: 你需要四级AI核心作战中枢
[action_泽塔诺亚最大化]
displayType: infoOnlyNoBox
iconImage: 泽塔诺亚3.png
text:泽塔诺亚数据\n已完全下载
isActive: false
isVisible: if self.globalTeamTags(includes='泽塔诺亚3')
pos: 10

[action_乌托米尔1]
text: 乌托米尔原子刻蚀技术1
buildSpeed: 40s
price: 2000,蓝晶=600,energy=1
description: -乌托米尔造船厂的原子刻蚀技术，是帝国重型军械制造的根基。\n-有了他我们将能自由的排列原子，并制造军械库中最强大的战争机器，\n-这将解锁地狱之龙和诱导激光t1。浮岛要塞的前置科技。
isVisible: if not self.globalTeamTags(includes='乌托米尔1')
addGlobalTeamTags: 乌托米尔1
addResources: energy=1
iconImage: 乌托米尔1.png
showMessageToPlayer: 乌托米尔原子刻蚀技术1级已下载
pos: 1.3
ai_isHighPriority: true


[action_乌托米尔2]
text: 乌托米尔原子刻蚀技术2
buildSpeed: 85s
price: 3500,蓝晶=1000,energy=1
description: -优化乌托米尔原子刻蚀技术的算法，以一种更为精确高效的算法打印重型设备，\n-有了新型原子刻蚀技术的支持，我们能制造更为巨大且夸张的军械。\n-这将解锁零素，浩劫，以及诱导激光t2。\n-恐惧级驱逐舰的前置科技。
isVisible: if self.globalTeamTags(includes='乌托米尔1') and not self.globalTeamTags(includes='乌托米尔2')
addGlobalTeamTags: 乌托米尔2
addResources: energy=1
iconImage: 乌托米尔2.png
showMessageToPlayer: 乌托米尔原子刻蚀技术2级已下载
pos: 1.4
ai_isHighPriority: true


[action_乌托米尔3]
text: 乌托米尔原子刻蚀技术3
buildSpeed: 90s
price: 5000,蓝晶=1500,energy=1
description: -最高阶的原子刻蚀技术精度甚至能在原子内部雕刻电路，\n-如果能拥有这项技术的支持，我们将能规模化生产帝国的各种机械巨兽。\n-这将解锁灾变祭司，\n-冥府渡人，焚天惩戒者的前置科技
isVisible: if self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='乌托米尔3')
addGlobalTeamTags: 乌托米尔3
addResources: energy=1
iconImage: 乌托米尔3.png
showMessageToPlayer: 乌托米尔原子刻蚀技术3级已下载
pos: 1.5
ai_isHighPriority: true
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: 你需要四级AI核心作战中枢
[action_乌托米尔最大化]
displayType: infoOnlyNoBox
iconImage: 乌托米尔3.png
text:乌托米尔数据\n已完全下载
isActive: false
isVisible: if self.globalTeamTags(includes='乌托米尔3')
pos: 11



[action_皇家舰队1]
text: 皇家舰队作战学说1
buildSpeed: 35s
price: 1600,蓝晶=500,energy=1
description: -应对小型战役的皇家舰队作战学说，包含了皇家舰队小型设备的生产工艺，\n-这些小型设备虽然只应用在小规模冲突中，但依然十分强悍，\n-这将解锁暗天使，血星和反质子标枪1。
isVisible: if not self.globalTeamTags(includes='皇家舰队1')
addGlobalTeamTags: 皇家舰队1
addResources: energy=1
iconImage: 皇家舰队1.png
showMessageToPlayer: 皇家舰队作战学说1级已下载
pos: 1.6
ai_isHighPriority: true


[action_皇家舰队2]
text: 皇家舰队作战学说2
buildSpeed: 70s
price: 2500,蓝晶=700,energy=1
description: -帝国早期皇家舰队的作战数据以及设备蓝图，\n-这些武器足以应对高烈度战斗并歼灭最为强大的敌人。\n-这将解锁白矮星，阿吉里恩，以及反质子标枪2。\n-浮岛要塞，凤凰级护卫舰，恐惧级驱逐舰，圣裁审判官的前置科技
isVisible: if self.globalTeamTags(includes='皇家舰队1') and not self.globalTeamTags(includes='皇家舰队2')
addGlobalTeamTags: 皇家舰队2
addResources: energy=1
iconImage:皇家舰队2.png
showMessageToPlayer: 皇家舰队作战学说2级已下载
pos: 1.7
ai_isHighPriority: true

[action_皇家舰队3]
text: 皇家舰队作战学说3
buildSpeed: 120s
price: 5000,蓝晶=2100,energy=1
description: -下载全套皇家舰队作战数据，以及其主力军备的生产图纸，\n-这些武器是帝国军队中的中流砥柱，其威力足以让整片星区为之颤抖。\n-这将解锁艾斯兰佩萨，\n-冥府渡人，奥克塔罗斯的前置科技
isVisible: if self.globalTeamTags(includes='皇家舰队2') and not self.globalTeamTags(includes='皇家舰队3')

addGlobalTeamTags: 皇家舰队3
addResources: energy=1
iconImage:皇家舰队3.png
showMessageToPlayer: 皇家舰队作战学说3级已下载
pos: 1.8
ai_isHighPriority: true
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: 你需要四级AI核心作战中枢


[action_皇家舰队最大化]
displayType: infoOnlyNoBox
iconImage: 皇家舰队3.png
text:皇家舰队数据\n已完全下载
isActive: false
isVisible: if self.globalTeamTags(includes='皇家舰队3')
pos: 12


[action_禁卫军1]
text: 禁卫军团军备复现1
buildSpeed: 195s
price: 15000,蓝晶=3600,energy=1
description: -复现早期帝国禁卫军的作战记录和装备数据，\n-即便是帝国禁卫军中的老旧装备，其威力也是难以想象的。\n-这将解锁类星体级行星突袭舰，灾厄级巡洋舰，龙魇，重力场要塞炮。
isVisible: if not self.globalTeamTags(includes='禁卫军1')
addGlobalTeamTags: 禁卫军1
addResources: energy=1
iconImage: 禁卫军1.png
showMessageToPlayer: 禁卫军团军备复现1级已下载
pos: 1.9
ai_isHighPriority: true
isLocked: if (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and self.globalTeamTags(includes='皇家舰队2'))
isLockedMessage:你需要泽塔诺亚蓝图数据库2，乌托米尔原子刻蚀技术2，皇家舰队作战学说2的其中两个

[action_禁卫军2]
text: 禁卫军团军备复现2
buildSpeed: 100s
price: 6000,蓝晶=2100,energy=1
description: -对禁卫军团中小型军备的复现，即便仅是中小型设备，\n-其威力也足以令最为强大的敌人灰飞烟灭。\n-拥有前置科技的情况下，这将解锁\n-独眼巨人，奥克塔罗斯的前置科技
isVisible: if self.globalTeamTags(includes='禁卫军1') and not self.globalTeamTags(includes='禁卫军2')

addGlobalTeamTags: 禁卫军2
addResources: energy=1
iconImage: 禁卫军2.png
showMessageToPlayer: 禁卫军团军备复现2级已下载
pos: 2
ai_isHighPriority: true
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: 你需要四级AI核心作战中枢


[action_禁卫军3]
text: 禁卫军团军备复现3
buildSpeed: 120s
price: 8000,蓝晶=2500,energy=1
description: -对禁卫军团主力级装备的复现，也是对机械之神最得意技术的复现，\n-就连恒星的光芒在这些军备的威力面前也显得黯然失色。\n-圣域守护神，圣裁审判官的前置科技
isVisible: if self.globalTeamTags(includes='禁卫军2') and not self.globalTeamTags(includes='禁卫军3')

addGlobalTeamTags: 禁卫军3
addResources: energy=1
iconImage: 禁卫军3.png
showMessageToPlayer: 禁卫军团军备复现3级已下载
pos: 2.1
ai_isHighPriority: true



[action_禁卫军最大化]
displayType: infoOnlyNoBox
iconImage: 禁卫军3.png
text:禁卫军军备数据\n已完全下载
isActive: false
isVisible: if self.globalTeamTags(includes='禁卫军3')
pos: 13


[action_行星突袭作战理论]
text: 行星突袭作战理论
buildSpeed: 40s
price: 4000,蓝晶=500,energy=1
description: -下载帝国皇家舰队先进的行星突袭作战的理论，以及相关设备图纸，\n-这些数据有助于我们发起远程打击，并防御敌方的战术/战略级武器，\n-解锁余辉行星防御系统t1，余辉轨道通讯系统。
isVisible: if not self.globalTeamTags(includes='行星突袭')
addGlobalTeamTags: 行星突袭
addResources: energy=1
iconImage: 行星突袭.png
showMessageToPlayer: 行星突袭作战理论已下载
pos: 2.2
ai_isHighPriority: true
isLocked: if (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and self.globalTeamTags(includes='皇家舰队2'))
isLockedMessage:你需要泽塔诺亚蓝图数据库2，乌托米尔原子刻蚀技术2，皇家舰队作战学说2的其中两个
[action_行星突袭最大化]
displayType: infoOnlyNoBox
iconImage: 行星突袭.png
text:行星突袭作战理论\n已完全下载
isActive: false
isVisible: if self.globalTeamTags(includes='行星突袭')
pos: 14



[decal_支撑]
image: 水下.png
total_frames: 1
layer: shadow
yOffsetRelative:0.5
xOffsetRelative:0.4
onlyWhileAlive:true
isVisible:if self.isOverLiquid
#alpha:0.4

[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.6
[decal_灯条]
image: 10.png
total_frames: 10
frame: (self.customTimer * 12) % 10
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-58
yOffsetAbsolute:49
isVisible:true
onlyWhileAlive:true
layer: onTop

[decal_主体损坏]
image: 损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true

[decal_光线]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:0.5
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1

[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_back: 地板.png
image_shadow: NONE


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 30
maxAttackRange: 0
shootDelay: 0








[arm_1]
x: 21.5
y: -14
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: 21.5
y: -25
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_3]
x: 21.5
y: -36
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_4]
x: 53.5
y: -14
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[arm_5]
x: 53.5
y: -25
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[arm_6]
x: 53.5
y: -36
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_7]
x: 85.5
y: -25
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_8]
x: 85.5
y: -36
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[animation_1]
KeyframeTimeScale:0.5
onActions: idle
blendIn: 0.5s
blendOut: 0.5s

arm1_0s: {x:0,y:0,alpha:0}
arm2_0s: {x:0,y:0,alpha:0}
arm3_0s: {x:0,y:0,alpha:0}
arm4_0s: {x:0,y:0,alpha:0}
arm5_0s: {x:0,y:0,alpha:0}
arm6_0s: {x:0,y:0,alpha:0}
arm7_0s: {x:0,y:0,alpha:0}
arm8_0s: {x:0,y:0,alpha:0}


arm1_1s: {x:0,y:0,alpha:1}
arm2_1s: {x:0,y:0,alpha:0}
arm3_1s: {x:0,y:0,alpha:0}
arm4_1s: {x:0,y:0,alpha:0}
arm5_1s: {x:0,y:0,alpha:0}
arm6_1s: {x:0,y:0,alpha:0}
arm7_1s: {x:0,y:0,alpha:0}
arm8_1s: {x:0,y:0,alpha:0}


arm1_2s: {x:0,y:0,alpha:0}
arm2_2s: {x:0,y:0,alpha:1}
arm3_2s: {x:0,y:0,alpha:0}
arm4_2s: {x:0,y:0,alpha:0}
arm5_2s: {x:0,y:0,alpha:0}
arm6_2s: {x:0,y:0,alpha:0}
arm7_2s: {x:0,y:0,alpha:0}
arm8_2s: {x:0,y:0,alpha:0}


arm1_3s: {x:0,y:0,alpha:0}
arm2_3s: {x:0,y:0,alpha:0}
arm3_3s: {x:0,y:0,alpha:1}
arm4_3s: {x:0,y:0,alpha:0}
arm5_3s: {x:0,y:0,alpha:0}
arm6_3s: {x:0,y:0,alpha:0}
arm7_3s: {x:0,y:0,alpha:0}
arm8_3s: {x:0,y:0,alpha:0}



arm1_4s: {x:0,y:0,alpha:0}
arm2_4s: {x:0,y:0,alpha:0}
arm3_4s: {x:0,y:0,alpha:0}
arm4_4s: {x:0,y:0,alpha:1}
arm5_4s: {x:0,y:0,alpha:0}
arm6_4s: {x:0,y:0,alpha:0}
arm7_4s: {x:0,y:0,alpha:0}
arm8_4s: {x:0,y:0,alpha:0}


arm1_5s: {x:0,y:0,alpha:0}
arm2_5s: {x:0,y:0,alpha:0}
arm3_5s: {x:0,y:0,alpha:0}
arm4_5s: {x:0,y:0,alpha:0}
arm5_5s: {x:0,y:0,alpha:1}
arm6_5s: {x:0,y:0,alpha:0}
arm7_5s: {x:0,y:0,alpha:0}
arm8_5s: {x:0,y:0,alpha:0}


arm1_6s: {x:0,y:0,alpha:0}
arm2_6s: {x:0,y:0,alpha:0}
arm3_6s: {x:0,y:0,alpha:0}
arm4_6s: {x:0,y:0,alpha:0}
arm5_6s: {x:0,y:0,alpha:0}
arm6_6s: {x:0,y:0,alpha:1}
arm7_6s: {x:0,y:0,alpha:0}
arm8_6s: {x:0,y:0,alpha:0}


arm1_7s: {x:0,y:0,alpha:0}
arm2_7s: {x:0,y:0,alpha:0}
arm3_7s: {x:0,y:0,alpha:0}
arm4_7s: {x:0,y:0,alpha:0}
arm5_7s: {x:0,y:0,alpha:0}
arm6_7s: {x:0,y:0,alpha:0}
arm7_7s: {x:0,y:0,alpha:1}
arm8_7s: {x:0,y:0,alpha:0}


arm1_8s: {x:0,y:0,alpha:0}
arm2_8s: {x:0,y:0,alpha:0}
arm3_8s: {x:0,y:0,alpha:0}
arm4_8s: {x:0,y:0,alpha:0}
arm5_8s: {x:0,y:0,alpha:0}
arm6_8s: {x:0,y:0,alpha:0}
arm7_8s: {x:0,y:0,alpha:0}
arm8_8s: {x:0,y:0,alpha:1}



arm1_9s: {x:0,y:0,alpha:0}
arm2_9s: {x:0,y:0,alpha:0}
arm3_9s: {x:0,y:0,alpha:0}
arm4_9s: {x:0,y:0,alpha:0}
arm5_9s: {x:0,y:0,alpha:0}
arm6_9s: {x:0,y:0,alpha:0}
arm7_9s: {x:0,y:0,alpha:0}
arm8_9s: {x:0,y:0,alpha:0}


[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 90
yOffsetRelativeRandom: 50
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:100
yOffsetRelativeRandom:70
delayedStartTimerRandom:30

[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
noneInBaseExtraPriority: 0.2
maxEachBase: 4
maxGlobal: 20


