

[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}

[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}
[core]
name: 超级计算机核心
displayText: ядро суперкомпьютера
displayDescription: 【Уровень t3】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)【Беспилотный юнит】\n-тактическое назначение: научная лаборатория, без вооружения.\n-амфибия, можно иметь только один.ядро суперкомпьютераэто тип быстрыйРазвернутьбольшой  типколичествомладшийвычислениеблок, \n-Этот армияиспользует суперкомпьютеротвечать за储хранение и место 理Заревоармияотряд каждыйуровеньвуровеньвооружение данные, \n-армиярезервчертёжпод носительк местопозади , вычислениеядробудетбудетбудетразблокировка压закончитьстать  данныеупаковкана 传до указыватьразмахсеть каждыйуровеньпроизводствоузелочко, \n-чтобы тогдапроизводствоИмпериякаждыйвидмощный войнаоружие
class: CustomUnitMetadata
price: 2200
maxHp: 7000
fogOfWarSightRange: 25
maxShield: 7000
shieldRegen: 0.09
techLevel: 1
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 1
buildSpeed: 20s
footprint: -6,-2,6,4
constructionFootprint: -6,-2,6,4
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 75
showInEditor: false
isBio: false
isBuilding: true
tags: 计算机,地面,建筑,无人单位
#numBitsOnDeath: 13
softCollisionOnAll: 3
armour: 10
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*10
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1)
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='计算机')
deleteSelf: true
addResources: 威胁点数=-${core.price / 25}
showMessageToPlayer: Эксплойт? Размечтался, в наказание лишний юнит сожрёт сервер눈_눈

[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上



[action_泽塔诺亚1]
text: база чертежей Зетаноя 1
buildSpeed: 20s
price: 1200,energy=1
description: -компания Зетанояотвечать зак Империяпредоставлятькаждыйвидв низкий конецоружие, Зетаноябазовыйчертёжбаза данных\n-в  оружиеоснащатьрезервхотя сравнительнодля старыйстарый , но его долгопроходить考验, может гарантироватьреальныйиспользует иимеет эффект.\n-эторазблокирует Скрытник и Ионная импульсная турельt1, \n-Турель тепловых лучейt3, Плазменная турельt3.
isVisible: if not self.globalTeamTags(includes='泽塔诺亚1')
addGlobalTeamTags: 泽塔诺亚1
addResources: energy=1
iconImage: 泽塔诺亚1.png
showMessageToPlayer: база чертежей Зетаноя 1уровеньуже под носитель
pos: 1
ai_isHighPriority: true


[action_泽塔诺亚2]
text: база чертежей Зетаноя 2
buildSpeed: 45s
price: 1500,energy=1,蓝晶=400
description: -компания Зетаноя вуровеньчертёжсодержитнекоторыеИмперияранний периодиспользоватьиспользует  армиярезервчертёж, \n- и период Войны Государствдругие отправлятьсерияпроходитьклассикавойнамашинаустройство производствометод, этиможет опираться старый  типоснащатьрезервдо сейчасвсё ещёкрайнеединицамощь.\n-эторазблокирует Колебательная волна, Ревун, Ионная импульсная турельt2 и Призрак.\n-корвет класса «Феникс», Парящая крепость предварительная технология.
isVisible: if self.globalTeamTags(includes='泽塔诺亚1') and not self.globalTeamTags(includes='泽塔诺亚2')
addGlobalTeamTags: 泽塔诺亚2
addResources: energy=1
iconImage: 泽塔诺亚2.png
ai_isHighPriority: true
showMessageToPlayer: база чертежей Зетаноя 2уровеньуже под носитель
pos: 1.1

[action_泽塔诺亚3]
text: база чертежей Зетаноя 3
buildSpeed: 90s
price: 4500,energy=1,蓝晶=1500
description: -компания Зетаноя высокий уровеньчертёжсодержитбольшой количествоИмпериядействующий обычныйоружие чертёж, \n-этикрайнеего имеет эффект и сначалав боевойоружие, правоохранительный корпус и пограничные войскаширокооснащён.\n-эторазблокирует Священный Молот.одновременноэто Небесный Охотник предварительная технология
isVisible: if self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='泽塔诺亚3')
addGlobalTeamTags: 泽塔诺亚3
addResources: energy=1
iconImage: 泽塔诺亚3.png
ai_isHighPriority: true
showMessageToPlayer: база чертежей Зетаноя 3уровеньуже под носитель
pos: 1.2
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: Требуется боевой центр ядра ИИ 4-го уровня
[action_泽塔诺亚最大化]
displayType: infoOnlyNoBox
iconImage: 泽塔诺亚3.png
text:Зетанояданные\nуже закончитьвсе под носитель
isActive: false
isVisible: if self.globalTeamTags(includes='泽塔诺亚3')
pos: 10

[action_乌托米尔1]
text: атомная литография Утомир 1
buildSpeed: 40s
price: 2000,蓝晶=600,energy=1
description: -верфь Утомир атомлитографиятехнология, это Империятяжёлыйармиямеханизмпроизводство штоснова.\n-имеет онмыбудетможет самот  расстановкаатом, и производствоармиямеханизмбиблиотекав самыймощный войнамашинаустройство, \n-эторазблокирует Адский Дракон и Управляемый лазерt1.Парящая крепость предварительная технология.
isVisible: if not self.globalTeamTags(includes='乌托米尔1')
addGlobalTeamTags: 乌托米尔1
addResources: energy=1
iconImage: 乌托米尔1.png
showMessageToPlayer: атомная литография Утомир 1уровеньуже под носитель
pos: 1.3
ai_isHighPriority: true


[action_乌托米尔2]
text: атомная литография Утомир 2
buildSpeed: 85s
price: 3500,蓝晶=1000,energy=1
description: -превосходствоУтомиратомлитографиятехнология считатьметод, чтобы тип более для точныйэффективный считатьметодпечатьтяжёлыйустановкарезерв, \n-имеет новый  типатомлитографиятехнология штдержать, мыможет производствоболее для огромный и огромный армиямеханизм.\n-эторазблокирует нулевой элемент, Опустошитель,  и Управляемый лазерt2.\n-эсминец класса «Ужас» предварительная технология.
isVisible: if self.globalTeamTags(includes='乌托米尔1') and not self.globalTeamTags(includes='乌托米尔2')
addGlobalTeamTags: 乌托米尔2
addResources: energy=1
iconImage: 乌托米尔2.png
showMessageToPlayer: атомная литография Утомир 2уровеньуже под носитель
pos: 1.4
ai_isHighPriority: true


[action_乌托米尔3]
text: атомная литография Утомир 3
buildSpeed: 90s
price: 5000,蓝晶=1500,energy=1
description: -самыйвысокий уровень атомлитографиятехнологияточныйстепеньдажедо может в атомвнутричастьскульптураэлектричествопуть, \n-если может Имея этотпункттехнология штдержать, мыбудетможет масштабпроизводствоИмперия каждыйвидмеханическийогромныйзверь.\n-эторазблокирует Жрец Катастрофы, \n-Перевозчик Аида, Каратель Небес предварительная технология
isVisible: if self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='乌托米尔3')
addGlobalTeamTags: 乌托米尔3
addResources: energy=1
iconImage: 乌托米尔3.png
showMessageToPlayer: атомная литография Утомир 3уровеньуже под носитель
pos: 1.5
ai_isHighPriority: true
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: Требуется боевой центр ядра ИИ 4-го уровня
[action_乌托米尔最大化]
displayType: infoOnlyNoBox
iconImage: 乌托米尔3.png
text:Утомирданные\nуже закончитьвсе под носитель
isActive: false
isVisible: if self.globalTeamTags(includes='乌托米尔3')
pos: 11



[action_皇家舰队1]
text: доктрина имперского флота 1
buildSpeed: 35s
price: 1600,蓝晶=500,energy=1
description: -должен против малый  типбойслужить имперский флотбоевой学сказать, содержитимперский флотмалый  типустановкарезерв производство工艺, \n-этималый  типустановкарезервхотя толькодолжен использует в малый масштабрывоквнезапнов , но по-прежнемуоченьсильный, \n-эторазблокирует Тёмный Ангел, Кровавая Звезда и антипротонное копьё1.
isVisible: if not self.globalTeamTags(includes='皇家舰队1')
addGlobalTeamTags: 皇家舰队1
addResources: energy=1
iconImage: 皇家舰队1.png
showMessageToPlayer: доктрина имперского флота 1уровеньуже под носитель
pos: 1.6
ai_isHighPriority: true


[action_皇家舰队2]
text: доктрина имперского флота 2
buildSpeed: 70s
price: 2500,蓝晶=700,energy=1
description: -Империяранний периодимперский флот боевойданные и установкарезервчертёж, \n-этиоружиедостаточночтобы должен против высокий 烈степеньбойи уничтожитьсамыйдля мощный враги.\n-эторазблокирует Белый Карлик, Аджирион,  и антипротонное копьё2.\n-Парящая крепость, корвет класса «Феникс», эсминец класса «Ужас», Священный Инквизитор предварительная технология
isVisible: if self.globalTeamTags(includes='皇家舰队1') and not self.globalTeamTags(includes='皇家舰队2')
addGlobalTeamTags: 皇家舰队2
addResources: energy=1
iconImage:皇家舰队2.png
showMessageToPlayer: доктрина имперского флота 2уровеньуже под носитель
pos: 1.7
ai_isHighPriority: true

[action_皇家舰队3]
text: доктрина имперского флота 3
buildSpeed: 120s
price: 5000,蓝晶=2100,energy=1
description: -под носительвсе штимперский флотбоевойданные,  и его основная силаармиярезерв производствочертёж, \n-этиоружиеэто имперская армияотрядв  в потокопора, его мощьдостаточночтобы позволитьвесь кусокзвездазонадля  颤抖.\n-эторазблокирует Эсланпеса, \n-Перевозчик Аида, Октарос предварительная технология
isVisible: if self.globalTeamTags(includes='皇家舰队2') and not self.globalTeamTags(includes='皇家舰队3')

addGlobalTeamTags: 皇家舰队3
addResources: energy=1
iconImage:皇家舰队3.png
showMessageToPlayer: доктрина имперского флота 3уровеньуже под носитель
pos: 1.8
ai_isHighPriority: true
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: Требуется боевой центр ядра ИИ 4-го уровня


[action_皇家舰队最大化]
displayType: infoOnlyNoBox
iconImage: 皇家舰队3.png
text:имперский флотданные\nуже закончитьвсе под носитель
isActive: false
isVisible: if self.globalTeamTags(includes='皇家舰队3')
pos: 12


[action_禁卫军1]
text: репликация вооружений гвардии 1
buildSpeed: 195s
price: 15000,蓝晶=3600,energy=1
description: -восстановитьтекущийранний периодИмпериягвардия боевой记录 и оснащатьрезервданные, \n-даже если это Империягвардияв  старыйстарый оснащатьрезерв, его мощьтакже это трудночтобы 想образ .\n-эторазблокирует типзвездателоуровеньпланетарный штурмкорабль, крейсер класса «Бедствие», Драконий кошмар, гравитацияполенужнозаглушкапушка.
isVisible: if not self.globalTeamTags(includes='禁卫军1')
addGlobalTeamTags: 禁卫军1
addResources: energy=1
iconImage: 禁卫军1.png
showMessageToPlayer: репликация вооружений гвардии 1уровеньуже под носитель
pos: 1.9
ai_isHighPriority: true
isLocked: if (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and self.globalTeamTags(includes='皇家舰队2'))
isLockedMessage:Требуется база чертежей Зетаноя 2, атомная литография Утомир 2, доктрина имперского флота 2 его в двашт

[action_禁卫军2]
text: репликация вооружений гвардии 2
buildSpeed: 100s
price: 6000,蓝晶=2100,energy=1
description: -против гвардейский легионв малый  типармиярезерв восстановитьтекущий, даже если толькоэто в малый  типустановкарезерв, \n-его мощьтакже достаточночтобы приказсамыйдля мощный враги灰飞烟灭.\n-Имея предварительная технология ситуацияпод , эторазблокирует \n-Циклоп, Октарос предварительная технология
isVisible: if self.globalTeamTags(includes='禁卫军1') and not self.globalTeamTags(includes='禁卫军2')

addGlobalTeamTags: 禁卫军2
addResources: energy=1
iconImage: 禁卫军2.png
showMessageToPlayer: репликация вооружений гвардии 2уровеньуже под носитель
pos: 2
ai_isHighPriority: true
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: Требуется боевой центр ядра ИИ 4-го уровня


[action_禁卫军3]
text: репликация вооружений гвардии 3
buildSpeed: 120s
price: 8000,蓝晶=2500,energy=1
description: -против гвардейский легионосновная силауровеньоснащатьрезерв восстановитьтекущий, также это против Механический Богсамый намерениетехнология восстановитьтекущий, \n-тогдасоединение恒звезда свет芒в этиармиярезерв мощьперед также 显 黯такпотеря色.\n-Хранитель Святилища, Священный Инквизитор предварительная технология
isVisible: if self.globalTeamTags(includes='禁卫军2') and not self.globalTeamTags(includes='禁卫军3')

addGlobalTeamTags: 禁卫军3
addResources: energy=1
iconImage: 禁卫军3.png
showMessageToPlayer: репликация вооружений гвардии 3уровеньуже под носитель
pos: 2.1
ai_isHighPriority: true



[action_禁卫军最大化]
displayType: infoOnlyNoBox
iconImage: 禁卫军3.png
text:гвардияармиярезервданные\nуже закончитьвсе под носитель
isActive: false
isVisible: if self.globalTeamTags(includes='禁卫军3')
pos: 13


[action_行星突袭作战理论]
text: планетарный штурмбоевойтеория
buildSpeed: 40s
price: 4000,蓝晶=500,energy=1
description: -под носительИмперияимперский флотсначалав планетарный штурмбоевой теория,  и взаимныйзакрытьустановкарезервчертёж, \n-этиданныеимеет помощьк мывыпуститьподнятьсядальнийудар, и оборонавражеский тактический/стратегическийуровеньоружие, \n-разблокирует Заревопланетарная защитная системаt1, Заревоорбитапроходинформациясистема.
isVisible: if not self.globalTeamTags(includes='行星突袭')
addGlobalTeamTags: 行星突袭
addResources: energy=1
iconImage: 行星突袭.png
showMessageToPlayer: планетарный штурмбоевойтеорияуже под носитель
pos: 2.2
ai_isHighPriority: true
isLocked: if (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and self.globalTeamTags(includes='乌托米尔2') and not self.globalTeamTags(includes='皇家舰队2')) or (not self.globalTeamTags(includes='泽塔诺亚2') and not self.globalTeamTags(includes='乌托米尔2') and self.globalTeamTags(includes='皇家舰队2'))
isLockedMessage:Требуется база чертежей Зетаноя 2, атомная литография Утомир 2, доктрина имперского флота 2 его в двашт
[action_行星突袭最大化]
displayType: infoOnlyNoBox
iconImage: 行星突袭.png
text:планетарный штурмбоевойтеория\nуже закончитьвсе под носитель
isActive: false
isVisible: if self.globalTeamTags(includes='行星突袭')
pos: 14



[decal_支撑]
image: 水下.png
total_frames: 1
layer: shadow
yOffsetRelative:0.5
xOffsetRelative:0.4
onlyWhileAlive:true
isVisible:if self.isOverLiquid
#alpha:0.4

[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.6
[decal_灯条]
image: 10.png
total_frames: 10
frame: (self.customTimer * 12) % 10
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-58
yOffsetAbsolute:49
isVisible:true
onlyWhileAlive:true
layer: onTop

[decal_主体损坏]
image: 损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true

[decal_光线]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:0.5
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1

[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_back: 地板.png
image_shadow: NONE


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 30
maxAttackRange: 0
shootDelay: 0








[arm_1]
x: 21.5
y: -14
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: 21.5
y: -25
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_3]
x: 21.5
y: -36
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_4]
x: 53.5
y: -14
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[arm_5]
x: 53.5
y: -25
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[arm_6]
x: 53.5
y: -36
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_7]
x: 85.5
y: -25
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true

[arm_8]
x: 85.5
y: -36
image_end:闪1.png
image_end_teamColors: true
drawOverBody: true


[animation_1]
KeyframeTimeScale:0.5
onActions: idle
blendIn: 0.5s
blendOut: 0.5s

arm1_0s: {x:0,y:0,alpha:0}
arm2_0s: {x:0,y:0,alpha:0}
arm3_0s: {x:0,y:0,alpha:0}
arm4_0s: {x:0,y:0,alpha:0}
arm5_0s: {x:0,y:0,alpha:0}
arm6_0s: {x:0,y:0,alpha:0}
arm7_0s: {x:0,y:0,alpha:0}
arm8_0s: {x:0,y:0,alpha:0}


arm1_1s: {x:0,y:0,alpha:1}
arm2_1s: {x:0,y:0,alpha:0}
arm3_1s: {x:0,y:0,alpha:0}
arm4_1s: {x:0,y:0,alpha:0}
arm5_1s: {x:0,y:0,alpha:0}
arm6_1s: {x:0,y:0,alpha:0}
arm7_1s: {x:0,y:0,alpha:0}
arm8_1s: {x:0,y:0,alpha:0}


arm1_2s: {x:0,y:0,alpha:0}
arm2_2s: {x:0,y:0,alpha:1}
arm3_2s: {x:0,y:0,alpha:0}
arm4_2s: {x:0,y:0,alpha:0}
arm5_2s: {x:0,y:0,alpha:0}
arm6_2s: {x:0,y:0,alpha:0}
arm7_2s: {x:0,y:0,alpha:0}
arm8_2s: {x:0,y:0,alpha:0}


arm1_3s: {x:0,y:0,alpha:0}
arm2_3s: {x:0,y:0,alpha:0}
arm3_3s: {x:0,y:0,alpha:1}
arm4_3s: {x:0,y:0,alpha:0}
arm5_3s: {x:0,y:0,alpha:0}
arm6_3s: {x:0,y:0,alpha:0}
arm7_3s: {x:0,y:0,alpha:0}
arm8_3s: {x:0,y:0,alpha:0}



arm1_4s: {x:0,y:0,alpha:0}
arm2_4s: {x:0,y:0,alpha:0}
arm3_4s: {x:0,y:0,alpha:0}
arm4_4s: {x:0,y:0,alpha:1}
arm5_4s: {x:0,y:0,alpha:0}
arm6_4s: {x:0,y:0,alpha:0}
arm7_4s: {x:0,y:0,alpha:0}
arm8_4s: {x:0,y:0,alpha:0}


arm1_5s: {x:0,y:0,alpha:0}
arm2_5s: {x:0,y:0,alpha:0}
arm3_5s: {x:0,y:0,alpha:0}
arm4_5s: {x:0,y:0,alpha:0}
arm5_5s: {x:0,y:0,alpha:1}
arm6_5s: {x:0,y:0,alpha:0}
arm7_5s: {x:0,y:0,alpha:0}
arm8_5s: {x:0,y:0,alpha:0}


arm1_6s: {x:0,y:0,alpha:0}
arm2_6s: {x:0,y:0,alpha:0}
arm3_6s: {x:0,y:0,alpha:0}
arm4_6s: {x:0,y:0,alpha:0}
arm5_6s: {x:0,y:0,alpha:0}
arm6_6s: {x:0,y:0,alpha:1}
arm7_6s: {x:0,y:0,alpha:0}
arm8_6s: {x:0,y:0,alpha:0}


arm1_7s: {x:0,y:0,alpha:0}
arm2_7s: {x:0,y:0,alpha:0}
arm3_7s: {x:0,y:0,alpha:0}
arm4_7s: {x:0,y:0,alpha:0}
arm5_7s: {x:0,y:0,alpha:0}
arm6_7s: {x:0,y:0,alpha:0}
arm7_7s: {x:0,y:0,alpha:1}
arm8_7s: {x:0,y:0,alpha:0}


arm1_8s: {x:0,y:0,alpha:0}
arm2_8s: {x:0,y:0,alpha:0}
arm3_8s: {x:0,y:0,alpha:0}
arm4_8s: {x:0,y:0,alpha:0}
arm5_8s: {x:0,y:0,alpha:0}
arm6_8s: {x:0,y:0,alpha:0}
arm7_8s: {x:0,y:0,alpha:0}
arm8_8s: {x:0,y:0,alpha:1}



arm1_9s: {x:0,y:0,alpha:0}
arm2_9s: {x:0,y:0,alpha:0}
arm3_9s: {x:0,y:0,alpha:0}
arm4_9s: {x:0,y:0,alpha:0}
arm5_9s: {x:0,y:0,alpha:0}
arm6_9s: {x:0,y:0,alpha:0}
arm7_9s: {x:0,y:0,alpha:0}
arm8_9s: {x:0,y:0,alpha:0}


[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 90
yOffsetRelativeRandom: 50
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:100
yOffsetRelativeRandom:70
delayedStartTimerRandom:30

[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
noneInBaseExtraPriority: 0.2
maxEachBase: 4
maxGlobal: 20


