


[core]
name: 焚魂者
displayText: 焚魂者
class: CustomUnitMetadata
displayDescription: 太空浪人基于创世纪报废油料的基础上，\n-生产出了一种新的燃烧剂，\n-这种特殊的燃烧剂可以快速熔化装甲以及建筑，\n-于是，名为焚魂者的单位便应运而生。\n-只能对地，中性伤害。反掩体，生物单位。
price: 900

maxHp: 900
mass: 1800
techLevel: 1
buildSpeed: 11s
softCollisionOnAll: 0

radius: 13
isBio: true
explodeOnDeath: false
hideScorchMark: true
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
tags: 步兵,地面,寄生免疫
armour: 4
copyFrom: ROOT:/通用特效/单位防护.ini
isUnrepairableUnit:true

[action_布雷2]
displayType: action
text: 布置僵尸诡雷
description: 消耗部分资源，使焚魂者埋下僵尸诡雷。\n-僵尸诡雷内塞满基因突变物。\n-并期待着敌人踏过他时发出的惨叫。
buildSpeed: 5s
price: 600

spawnUnits: 僵尸诡雷t1*1
canPlayerCancel: true


[graphics]
total_frames: 6
image: 焚魂者.png
image_wreak: 焚魂者死亡.png
image_turret: NONE
image_shadow: ROOT:/创世纪军事集团/步兵特效/影子.png

shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 1
animation_moving_end: 5
animation_moving_speed: 5

animation_attack_start: 0
animation_attack_end: 0
animation_attack_speed: 20
#imageScale:0.9


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 18

turretTurnSpeed: 40
maxAttackRange: 230
isFixedFiring: true
shootDelay: 3


[turret_1]
x: 0
y: 0
canShoot: false


[turret_3]
x: 10
y: 4
projectile: 1
shoot_sound: 火焰.ogg
shoot_sound_vol: 0.2

shoot_flame: CUSTOM:smoke
canShoot: true
invisible: true
attachedTo: 1
slave: true


[projectile_1]
life: 5000
speed: 5.5
areaDamage: 20
areaRadius: 50
targetSpeed: 5.5

image: 爆炸2.png
drawSize: 0.6
flameWeapon: true
targetGroundSpread: 25
areaRadiusFromEdge: true

targetGround: true
lightSize: 1
lightColor: #FF45FFB4
deflectionPower: -1
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
explodeEffect: CUSTOM:爆炸


[effect_smoke]
#priority:high
frameIndex: 0
stripIndex: smoke_black
spawnChance: 0.3
createWhenZoomedOut: false

life: 90
fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #FFFFFF

fadeInTime: 2
scaleFrom: 0.3
scaleTo: 1
alpha: 5
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.2
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.4
ySpeedRelativeRandom: 0.4

atmospheric: true


[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.7
ySpeedRelativeRandom: 0.6

hSpeed: 1


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.5
scaleTo: 0.5
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1
ySpeedRelativeRandom: 1

hSpeed: 1
dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 600
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 3
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡2.ogg


[effect_爆炸]
priority: critical
image: ROOT:/太空浪人/单位特效/波雷爆炸1.png
life: 70
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.6
scaleTo: 0.7
alpha: 1
drawUnderUnits: false

ySpeedRelative: 2
atmospheric: true
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13

animateFrameSpeed: 0.2


[movement]
movementType: LAND
moveSpeed: 1.25
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 5

turnAcceleration: 0.5
moveSlidingMode: false
moveIgnoringBody: false


