


[core]
name: 反潜机
class: CustomUnitMetadata
price: 2
maxHp: 1200
energyMax: 4.85

energyRegen: 0
#energyNeedsToRechargeToFull: true
tags: 反潜机,飞机,低空,伴生单位
buildSpeed: 4s
techLevel: 2
showInEditor: false
radius: 10
displayRadius: 10
isBio: false
softCollisionOnAll: 100
numBitsOnDeath: 3

canNotBeGivenOrdersByPlayer: true
copyFrom: ROOT:/通用特效/单位防护.ini
borrowResourcesWhileAlive: wrj2=1
logIfCreditResourceUsed: true

[hiddenAction_return]
autoTrigger: if self.hasUnitInTeam(withTag='航母2') and not self.hasActiveWaypoint(type='loadInto') and not self.hasParent()
addWaypoint_target_nearestUnit_tagged: 航母2
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto


[hiddenAction_return1]
# 没能量时返航
autoTrigger: if self.energy<0.9  and not self.hasParent() and not self.hasActiveWaypoint(type='loadInto')
clearActiveWaypoint: true
# addWaypoint_prepend: true
addWaypoint_target_nearestUnit_tagged: 航母2

addWaypoint_target_nearestUnit_team: own
addWaypoint_maxTime: 10s
addWaypoint_type: loadInto


[hiddenAction_disconnect]
autoTrigger: if self.hasParent() and not self.hasActiveWaypoint(type='attackmove') and self.energy(full=true) and numberOfUnitsInEnemyTeam(withTag='潜艇',greaterThan=0, withinRange=800) and self.isInMap()
disconnectFromParent: true
# clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: 潜艇
addWaypoint_triggerActionIfMatched: return

addWaypoint_type: attackmove
addWaypoint_target_nearestUnit_team: enemy
addWaypoint_target_nearestUnit_maxRange: 800


[hiddenAction_energy]
autoTrigger: if not self.energy(full= true) and self.hasParent()
addEnergy: 4


[action_t1]
autoTrigger: if not self.hasParent() and self.resource(type= 'wrj2', lessThan= 0)
isVisible: false
addResources: hp=-999999
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[action_弹幕架1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕1.png
text: 弹幕架1
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架1')

[graphics]
total_frames: 1
image: 反潜机.png
image_wreak: 反潜机死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: true
turretSize: 20

turretTurnSpeed: 4
maxAttackRange: 200
attackMovement: bomber
isMelee: true
meleeEngangementDistance: 600


[turret_1]
x: 0
y: 0
canShoot: true
invisible: true
delay: 30

projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFEECCCC

canAttackFlyingUnits: false
size: 15
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false

energyUsage: 2
canAttackCondition: if self.flying and not self.globalTeamTags(includes='弹幕架1')
[turret_炮台]
x: -5
y: 0
canShoot: true
invisible: true
delay: 5

projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFEECCCC

canAttackFlyingUnits: false
size: 15
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false

energyUsage: 1
canAttackCondition: if self.flying and self.globalTeamTags(includes='弹幕架1')
[turret_炮台1]
x: 5
y: 0
#导弹左
copyFrom: 炮台
[projectile_1]
@copyFromSection: template_爆炸
life: 35
speed: 0
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: ROOT:/通用特效/鱼雷.png
areaDamage: 0
areaRadius: 0
explodeEffect: CUSTOM:烟雾1*2,CUSTOM:水波
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:2
explodeOnEndOfLife:true
drawUnderUnits:true
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 600
areaRadius: 40
drawSize: 0.9
life: 460
lightColor: #FFFF1200
lightSize: 0
speed: 4
deflectionPower: -1
targetSpeed: 7
image: ROOT:/通用特效/鱼雷.png
trailEffect: true

areaRadiusFromEdge: true
largeHitEffect: true
explodeEffect: CUSTOM:冲击波2,CUSTOM:闪光,CUSTOM:水波1
explodeEffectOnShield: CUSTOM:冲击波2,CUSTOM:闪光,CUSTOM:水波1


[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 0

drawUnderUnits: false
atmospheric: false


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
createWhenOverLiquid: true
createWhenOverLand: false
drawUnderUnits: true


[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg

[effect_烟雾1]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 1
scaleTo: 2.5
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false
[effect_水波]
priority: low
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.35
alpha: 1
drawUnderUnits: true
atmospheric: true
createWhenOverLiquid: true
createWhenOverLand: false
[movement]
movementType: AIR
targetHeight: 40
targetHeightDrift: 2
moveSpeed: 2.3
moveAccelerationSpeed: 1

moveDecelerationSpeed: 0.001
maxTurnSpeed: 2
turnAcceleration: 0.04
moveSlidingMode: true
moveIgnoringBody: false

slowDeathFall: true


