

[hiddenAction_寄生b]
addResources: bj= ${bjxq}
[core]
name: 要塞t4
displayText: Крепостьt4
displayDescription:【Уровень t4】【Оборонительное здание】【Здание】【Наземный юнит】【Сверхтяжёлый юнит】\n-Тактическое назначение：суперюнитукрытие，позволятьразмещатьсямеханический юнит，\n-вместимость десанта：24。иметьстратегическое оружие抗тип。повышаетвнутреннийразмещатьсяюнитдальность至1200。\n-Генезисв качестве можетвплоский坦 формаверх遏制остаток晖бронегруппа冲锋所建立 ，прочныйаогромный永驻工事。\n-Крепость采использоватьсильный固混凝土混合бронясталь框 浇注выполнятьстроить，его铜墙железо壁般 оборонаспособностьможетпротивостоятьостаток晖абсолютныйбольшинствопушкаогонь直射，\n-ск毁灭тип атакавКрепостьпрочный защита护низвсе显 宛как瘙痒般нетсила。\n-КрепостьвнутреннийогромныйПусто间，болееявляетсяпозволятьбольшое количество пехотавплоть добронясиларазмещатьсявеговнутренний，\n-дажеещёможет额внеподдерживаетчисло пушкагруппаидальнийтяжёлыйпушкаобеспечивает额внеогневая мощьподдержка。
class: CustomUnitMetadata
price: 38000,钍=600,bj= ${bjxq}
@global bjxq: 20
reclaimPrice: bj= ${bjxq}

maxHp: 125000
constructionFootprint:-7,-6,7,6
footprint: -7,-6,7,6
techLevel: 1
buildSpeed: 120s
isBio: false
fogOfWarSightRange: 47
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
numBitsOnDeath: 12
unitsSpawnedOnDeath:建筑损毁*2
effectOnDeath: CUSTOM:烟雾*5, CUSTOM:爆破*12,largeExplosion*2
radius: 100
displayRadius: 100
softCollisionOnAll: 12
energyStartingPercentage: 0
energyMax: 16
energyRegen: 0.004
exit_x: 0
exit_y: -1
tags: 地面,建筑,防御建筑,要塞t4,极端重型,jabzhdja,战略武器抗性,本来就有啊
armour: 250
transportUnitsRequireTag:驻扎要塞,步兵,卧倒,机甲
maxTransportingUnits: 24
selfRegenRate: 1.5
[hiddenAction_创造]
autoTrigger: if attachment(slot= '0') == nullUnit
attachments_onlyOnSlots: 0
attachments_addNewUnits:阵地
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[hiddenAction_内衬]
autoTrigger: if not self.tags(includes= 'jabzhdja') and self.hp> self.maxHp * 0.5
temporarilyAddTags: jabzhdja

[hiddenAction_内衬没了]
autoTrigger: if self.tags(includes= 'jabzhdja') and self.hp< self.maxHp * 0.5
temporarilyRemoveTags: jabzhdja
[decal_地板]
image: ROOT:/创世纪军事集团/建筑特效/要塞地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-28
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
imageScale: 0.9
alpha:1




[decal_shadow]
image: 要塞影子.png
layer: shadow
xOffsetAbsolute: 12
yOffsetAbsolute: -9
alpha: 0.5
onlyWhileAlive: true
imageScale: 0.9
isVisible: true


[decal_损坏]
image:损坏2.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:10.5
xOffsetRelative:0
onlyWhileAlive:true
imageScale: 0.9
alpha:0.5
[action_1_烟幕弹]
fireTurretXAtGround: 烟幕弹
text: запускатьДымовая граната
displayType: action
buildSpeed: 1s
pos: 1
iconImage: ROOT:/创世纪军事集团/单位特效/烟雾弹.png
displayRemainingStockpile: true
highPriorityQueue: true
price: energy=3
canPlayerCancel: false
onlyOneUnitAtATime: true
whenBuilding_playAnimation: 1
description: кцельобласть投掷однаДымовая граната，Дымовая гранатаможетсерьёзный干扰вражеская армия 瞄准система。\n-Дымовая гранатабудет降низкийрядом160в радиусе вражескийназемный юнит дальностьа такжескорострельность，\n-противобладатьдальнийцелеуказаниеспособностьа такжеиметьУлучшенный модуль наведениянаука юнитнеэффективный。
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_索敌]
displayType: action
pos: 2
fireTurretXAtGround: 信标
displayRemainingStockpile: true
text:развёртыватьМаяк целеуказания
price: energy=6
buildSpeed: 1s
isLocked: if self.queueSize > 0.5  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: другиедействиявыполнятьв，пожалуйста, подождите
description: 命令КрепостьзапускатьоднаМаяк целеуказания，\n-Маяк целеуказаниябудетв качествеегорядомвсевражеский юнит施加захватэффект，\n-одновременноещёможетобеспечиваетсчитать野и扰乱相позицияэффект，\n-Маяк целеуказаниябудет считатьв качествеминаюнит。
iconImage: 索敌信标.png
isVisible: true
whenBuilding_playAnimation: 1
allowMultipleInQueue:true

[action_没有]
text: не启использоватьавтопушкаПозиция
isVisible: if self.transportingCount < 4
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 3
iconImage: ROOT:/通用特效/关.png
description: когдаКрепостьвнутреннийразмещатьсяюнитколичествобольшойви т.д.в4 ，\n-Крепостьбудетвключитьавтопушкагруппавыполнятьатака，\n-автопушкагруппадальностьв качестве500，по земле и воздуху，наносит动можетпункт杀伤，противсопровождающий юнитурон-бонус。
[action_有]
text: уже启использоватьавтопушкаПозиция
isVisible: if self.transportingCount > 3
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 4
iconImage: ROOT:/通用特效/开.png
description: уже启использоватьавтопушкаПозиция，\n-Крепостьуже включеноавтопушкагруппавыполнятьатака，\n-автопушкагруппадальностьв качестве500，по земле и воздуху，наносит动можетпункт杀伤，противсопровождающий юнитурон-бонус。


[action_没有1]
text: не启использовать280мм пушкаПозиция
isVisible: if self.transportingCount < 8
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 5
iconImage: ROOT:/通用特效/关.png
description: когдаКрепостьвнутреннийразмещатьсяюнитколичествобольшойви т.д.в8 ，\n-Крепостьбудетвключить280мм пушкавыполнятьатака，\n-280мм пушкадальностьв качестве850，только по земле，наноситвзрыв溅射伤害。
[action_有1]
text: уже启использовать280мм пушкаПозиция
isVisible: if self.transportingCount > 7
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 6
iconImage: ROOT:/通用特效/开.png
description: уже启использовать280мм пушкаПозиция，\n-Крепостьуже включено280мм пушкавыполнятьатака，\n-280мм пушкадальностьв качестве850，только по земле，наноситвзрыв溅射伤害。


[action_没有2]
text: не启использоватьдронАнгар
isVisible: if self.transportingCount < 12
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 7
iconImage: ROOT:/通用特效/关.png
description: когдаКрепостьвнутреннийразмещатьсяюнитколичествобольшойви т.д.в12 ，\n-Крепостьбудетвключитьдрон库выполнятьатака，\n-Крепостьбудетпротиврадиус985в вражеский поверхностьивоздушный юнитв качествецель，释放Вендиго 杀式дрон，наноситвзрыв溅射伤害。
[action_有2]
text: уже启использоватьдронАнгар
isVisible: if self.transportingCount > 11
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 8
iconImage: ROOT:/通用特效/开.png
description: уже启использоватьдронАнгар，\n-Крепостьуже включенодрон库выполнятьатака，\n-Крепостьбудетпротиврадиус985в вражеский поверхностьивоздушный юнитв качествецель，释放Вендиго 杀式дрон，наноситвзрыв溅射伤害。

[action_重]
text: крайне端тяжёлыйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 9
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积преувеличивать юнит独есть характеристика，\n-иметькрайне端тяжёлыйюнит标签 юнитбудетиметькакнизпринадлежатьтип，\n-иметь 愈способность，исобственный护甲ненизкийв100пункт，\n-трудно шок，но受допротивтяжёлый甲юнит伤害бафф。

[action_结构]
text: усиливаетструктура
isVisible:if self.hp> self.maxHp * 0.5
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 10
iconImage: ROOT:/通用特效/强化结构.png
isLockedMessage: указанныйюнит структура构создаватьпройти черезспециальный усиливаети加固，\n-можетосвобождать疫всё负поверхностьэффект。нотольковсобственный生命值большойв50%время起效。

[action_查看]
text: 查смотретьможетразмещаться юнит类 
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos:0
iconImage: ROOT:/通用特效/坦克.png
isLockedMessage: всеможетразмещатьсяв步бронемашина/Наблюдательный пост/Бункерв пехота，\n-IAV Колёсная штурмовая пушка，Лёгкий танк，Гатлинг-грузовик，Машина с противотанковой ракетой，Бронемашина «Вомбат»，Робот «Странник»，\n-Самоходное зенитное орудие，Основной боевой танк，Самоходная гаубица，Танк «Колосс»，\n-Шок-танк，Завоеватель，Парящий танк，Супертанк，Танк «Челленджер»，РСЗО «Ливень»，Супертанкmk2。

[graphics]
total_frames: 1
image: 要塞1.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/要塞死亡.png
image_turret: NONE
#image_back: ROOT:/通用特效/NO.png

shadowOffsetX: 3
shadowOffsetY: 3
imageScale: 0.9
image_offsetY: -10
drawLayer: ground

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 50
maxAttackRange: 1100
meleeEngangementDistance: 100
isMelee: true

[turret_烟幕弹]
x: 0
y: -25
canShoot: false
invisible: true
size: 1.1
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 1
delay: 0
shoot_flame: CUSTOM:烟雾1*7
shoot_light: #FFEECCCC
[turret_信标]
x:0
y:-25
copyFrom: 烟幕弹
projectile: 3
#limitingRange: 1000
[projectile_1]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.9

image: ROOT:/创世纪军事集团/建筑特效/弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 2
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1

[projectile_2]
life: 600
directDamage: 0
speed: 6
targetSpeed: 9
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png
initialUnguidedSpeedHeight: 2.5
gravity: 0.4
drawSize: 0.9
targetGround: true
spawnUnit: 烟幕弹*1
trailEffect: true
deflectionPower: -1
trailEffectRate: 1

[projectile_3]
life: 99999
speed: 1
targetSpeed: 9
targetSpeedAcceleration: 0.1
largeHitEffect: true
ballistic: true
ballistic_delaymove_height: 130
ballistic_height: 170
image: 导弹x.png
drawSize: 0.9
areaRadiusFromEdge: true
explodeEffect: CUSTOM:烟雾1x*7,CUSTOM:冲击波1
targetGround: true
areaDamage: 0
alwaysVisibleInFog: true
areaRadius: 0
deflectionPower: -1
shouldRevealFog: true
lightColor: #FFEEEE00
lightSize: 1
trailEffect: true
spawnUnit: 索敌信标*1
#————————————
[effect_烟雾1]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120

fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1

scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
atmospheric: true
[effect_烟雾1x]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1.5
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波1]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1

[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10
[attachment_0]
x: 0
y: 0
isUnselectable:true
onCreateSpawnUnitOf:阵地
lockRotation: false
resetRotationWhenNotAttacking:true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
setDrawLayerOnTop:true
canBeAttackedAndDamaged: false
onConvertKeepExistingUnitInSameSlot:true
[attachment_1]
x:0
y: 0
isVisible: false
height: 40
canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true
prioritizeParentsMainTarget:true
alwaysAllowedToAttackParentsMainTarget: false
onConvertKeepExistingUnitInSameSlot:true
[attachment_2]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_3]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_4]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_5]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_6]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_7]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_8]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_9]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_10]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_11]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_12]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_13]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_14]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_15]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_16]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_17]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_18]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_19]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_20]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_21]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_22]
x: 0
y: 0
@copyFromSection: attachment_1

[attachment_23]
x: 0
y: 0
@copyFromSection: attachment_1


[attachment_24]
x: 0
y: 0
@copyFromSection: attachment_1
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 360
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.4
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 50
yOffsetRelativeRandom: 70
xSpeedAbsoluteRandom: 0.35
ySpeedAbsoluteRandom: 0.35
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.8
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:100
yOffsetRelativeRandom:100
delayedStartTimerRandom:40
[arm_1]
x: -5
y: -30
image_end:ROOT:/创世纪军事集团/建筑特效/要塞左.png
image_end_teamColors: true
drawOverBody: true
[arm_2]
x: 5
y: -30
image_end:ROOT:/创世纪军事集团/建筑特效/要塞右.png
image_end_teamColors: true
drawOverBody: true
[animation_1]

arm1_0s: {x:0, y:0}
arm2_0s: {x:0, y:0}
arm1_1s: {x:-15, y:0}
arm2_1s: {x:15, y:0}
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


