


[core]
name: 余辉蓝晶萃取房t1空投
displayDescription: 蓝晶是只存在于超空间的细小微粒，任何零点能的提取都依赖于蓝晶。\n-所有的余辉高新科技都依赖于蓝晶，甚至可以说，\n-整个诺瓦帝国都是基于蓝晶和真空零点能而存在的。
class: CustomUnitMetadata
price: 3500,ry= ${ryxq}
@global ryxq:55
reclaimPrice: ry= ${ryxq}

maxHp: 10000

techLevel: 1
buildSpeed: 0.1s
isBio: false
isBuilding: true
selfBuildRate: 0.01

footprint: -3,-1,3,4
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 52
constructionFootprint: -3,-1,3,4
numBitsOnDeath: 35

fogOfWarSightRange: 5
radius: 35
armour: 25
maxShield: 8000
shieldRegen: 0.09

canNotBeDirectlyAttacked: true
tags: 蓝晶


[action_t1]
autoTrigger: if self.timeAlive(laterThanSeconds=2.6)
isVisible: false
convertTo: 余辉蓝晶萃取房t1
spawnEffects: CUSTOM:冲击波*1




[graphics]
total_frames: 1
image: 空投.png
image_wreak: NONE
image_turret: NONE
shadowOffsetX: 3

shadowOffsetY: 3
#imageScale:
drawLayer: air
image_shield: 护盾.png


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
turretSize: 0

turretTurnSpeed: 50
maxAttackRange: 9999


[turret_烟雾]
x: -40
y: -90
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 5

invisible: true
size: 1


[turret_烟雾2]
x: 40
y: -90
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 5

invisible: true
size: 1


[turret_火焰]
x: 0
y: -95
projectile: 13
shoot_flame: CUSTOM:火焰
delay: 10

invisible: true
size: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[effect_烟雾]
dirOffsetRandom: 180
stripIndex: effects
frameIndex: 0
life: 100
fadeOut: true

priority: critical
attachedToUnit: false
fadeInTime: 0.8
scaleTo: 6
scaleFrom: 5

alpha: 3
hSpeed: 1.5
drawUnderUnits: false
atmospheric: false
spawnChance: 1

hOffsetRandom: 0.9
xSpeedRelativeRandom: 3


[effect_火焰]
priority: critical
image: ROOT:/余辉军团/建筑特效/火光.png
life: 20
fadeOut: true
attachedToUnit: true

fadeInTime: 0.8
scaleTo: 2
scaleFrom: 0.5
alpha: 1
hSpeed: 0.5

drawUnderUnits: false
atmospheric: false
spawnChance: 1
xSpeedAbsoluteRandom: 0.8
alwayStartDirAtZero: true


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
createWhenOverLiquid: true
createWhenOverLand: true
drawUnderUnits: true


[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1
startingHeightOffset: 2000
targetHeightDrift: 0


[ai]
buildPriority: 0.23
maxEachBase: 10
maxGlobal: 25
noneGlobalExtraPriority:0.8






