
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 火箭弹幕炮塔t2
displayText: Ракетная башняt2
displayDescription: 【Уровень t4】【Оборонительное здание】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение：重 далеко程反群体ракетная установка，вооружение：\n-▲火箭弹пусковой отсекX2 только по земле взрывной урон 对极端重 юнитэффект差 爆炸后生成爆裂物 \n-充分运用Реактивная установка技术，имеет встроенныйбольшое количество火箭弹的中 оборона炮 ，\n-способен凭借着恐怖的огневая мощь爆 迅速摧垮враг的наступление，\n-одновременноещёможетиспользовать极далеко的удар范围压制вражеский炮兵和далеко程огневая мощь。\n-нонуждаетсяВнимание的是，其爆 完后，обладать较长的перезаряжает时间。
price: 6250,钍=190,bj= ${bjxq}
@global bjxq: 12
reclaimPrice: bj= ${bjxq}
maxHp: 30000

footprint: -2,-2,2,2
constructionFootprint: -2,-2,2,2
fogOfWarSightRange: 40
techLevel: 1

copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 20s
radius: 40
armour: 40

isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆破*4,largeExplosion
tags: 地面,建筑,防御建筑
[action_升级]
convertTo: 火箭弹幕炮塔t3
displayType: action
text: 升класс
price: 2500,钍=175
buildSpeed: 15s
isLocked: if not self.globalTeamTags(includes='导弹托1')
isLockedMessage: Требуется пусковая платформа
description: самый大化Ракетная башняуровень，加固其结构强度，连 количество，伤害а такжедальность。\n-и额外увеличивает两组толькоможет攻击надводный юнит的противокорабельныйракета，взрывной урон。\n-进一步увеличивает火箭弹的количество的одновременно追加一组双联装противокорабельныйракета单元，\n-这将позволяетРакетная башняспособен在压制вражеский的одновременно，эффективный对海面上的重 боевой корабль实施удар。

[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_影子1]
image: ROOT:/创世纪军事集团/建筑特效/地板.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:2
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
imageScale: 0.84
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/座1影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:13
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.65
imageScale: 0.84
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/支持.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-41
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.65
imageScale: 0.84
[decal_遮盖]
image:导弹盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:-10.5
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret: 1
imageScale: 0.8
teamColors: true
[decal_炮塔影子]
image: 导弹影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:1.5
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
imageScale: 0.8
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image_back: ROOT:/通用特效/NO.png
image: ROOT:/创世纪军事集团/建筑特效/座1.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/中座死亡.png
image_turret: NONE
turretImageScale: 0.8
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.84
image_offsetY: -11
[attack]
canAttack:true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 12
turretMultiTargeting:true
turretTurnSpeed: 6
maxAttackRange: 925
shootDelay: 0

[turret_1]
x: 0
y: 33
#武器底座
canShoot: false
image: 导弹底.png
delay: 0
turnSpeed: 1.5
turnSpeedAcceleration: 0.15
limitingMinRange: 350
canAttackCondition: if self.resource.xk < 1
idleDir:90
[turret_2]
x: 25.5
y: 2
#导弹右
projectile: 1
attachedTo: 1
slave: true
image: ROOT:/创世纪军事集团/建筑特效/导弹x.png
shoot_sound: ROOT:/通用特效/新导弹发射.wav
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:烟雾x*4,CUSTOM:冲击波
shoot_light: #FFEECCCC
canShoot: true
canAttackCondition: if self.resource.xk < 1 
recoilOffset: -20
recoilOutTime: 2
recoilReturnTime: 280
limitingMinRange: 350
delay:280
warmup:60
size:25
idleDir: 90
shouldResetTurret: false
[turret_3]
x:17.5
y:2
copyFrom: 2
delay:295
warmup:45

[turret_4]
x:9.5
y:2
copyFrom: 2
delay:310
warmup:30
[turret_5]
x:21.5
y:-1
copyFrom: 2
delay:325
warmup:15
[turret_6]
x:12.5
y:-1
copyFrom: 2
delay:340
warmup:0



[turret_7]
x:-25.5
y:2
copyFrom: 2
delay:280
warmup:60
[turret_8]
x:-17.5
y:2
copyFrom: 2
delay:295
warmup:45
[turret_9]
x:-9.5
y:2
copyFrom: 2
delay:310
warmup:30
[turret_10]
x:-21.5
y:-1
copyFrom: 2
delay:325
warmup:15

[turret_11]
x:-12.5
y:-1
copyFrom: 2
delay:340
warmup:0

[projectile_1]
life: 45
speed: 3
targetSpeed: 7
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/建筑特效/导.png
trailEffect: true
trailEffectRate: 1.3
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定,锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:冲击波
initialUnguidedSpeedHeight: 2.8
trueGravity: 0.02
disableLeadTargeting: true
targetGround: true
targetGroundSpread: 75
speedSpread: 0.8
[projectile_锁定]
@copyFromSection: template_爆炸
#主炮子弹
areaDamage: 600
areaRadius: 90
life: 350
speed: 7
targetSpeed: 13
image: ROOT:/创世纪军事集团/建筑特效/导导弹头.png
drawSize: 0.8
trailEffect: true
trailEffectRate: 1.3
lightSize: 0.75
lightColor: #FFFFFF73
targetGround: true
initialUnguidedSpeedHeight: 2.5
trueGravity: 0.02
disableLeadTargeting: true
areaRadiusFromEdge: true
explodeEffect: CUSTOM:冲击波hx,CUSTOM:爆炸hx,CUSTOM:闪光hx,CUSTOM:弹坑,CUSTOM:钢珠hx,CUSTOM:黑雾
explodeEffectOnShield: CUSTOM:冲击波hx,CUSTOM:爆炸hx,CUSTOM:闪光hx,CUSTOM:弹坑,CUSTOM:钢珠hx,CUSTOM:黑雾
targetGroundSpread: 65
speedSpread: 1.25
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.5
mutator7_areaDamageMultiplier: 0.5
[projectile_锁定1]
@copyFromSection:projectile_锁定
speedSpread: 1.25
speed: 7
targetSpeed: 9
areaDamage: 0
areaRadius: 0
image: 核.png
drawSize: 0.8
explodeEffect: CUSTOM:冲击波,CUSTOM:黑雾
explodeEffectOnShield: CUSTOM:冲击波,CUSTOM:黑雾
spawnUnit: 蹦蹦炸弹*1


#——————————导弹发射
[effect_烟雾x]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 1.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.5
atmospheric: true
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.6
scaleTo: 1.7
alpha: 1
[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/建筑特效/导弹壳.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
ySpeedRelative: -1.5
hSpeed: 2
dirSpeedRandom: 10
#——————————
#——————————————————爆炸
[effect_钢珠hx]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.5
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_爆炸hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.44
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
alwayStartDirAtZero: true
[effect_闪光hx]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 1.3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life:150
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 1.2
scaleTo: 1.2
createWhenOverLiquid: false
createWhenOverLand: true
[effect_黑雾]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true
life: 165
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.2
scaleTo: 0.3
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 10
yOffsetRelativeRandom: 10
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15

[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
delayedStartTimerRandom:30
[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


