


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}
[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}

[core]
name: 余辉纳米维修站t2
displayText: Заревонаноремонтстоятьt2
class: CustomUnitMetadata
price: 3000
maxHp: 3000
footprint: -1,-1,1,1

constructionFootprint: -1,-1,1,1
techLevel: 1
buildSpeed: 20s
radius: 25
maxShield: 3000

shieldRegen: 0.05
copyFrom: ROOT:/通用特效/单位防护.ini
buildingSelectionOffset: -8
isBuilding: true
isBio: false

tags: 地面,无人单位,建筑
canRepairBuildings: true
canRepairUnits: true
nanoRepairSpeed: 1
nanoRange: 300

nanoBuildSpeed: 1.5
autoRepair: true
#showInEditor:false


[graphics]
total_frames: 1
image: 身体.png
image_wreak: 死亡.png
image_turret: NO.png
image_back: ROOT:/通用特效/NO.png

image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 12

turretTurnSpeed: 6
maxAttackRange: 245


[turret_3]
x: 0
y: 19
warmup: 0
size: 8
canShoot: false

canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true


[arm_1]
x: 0
y: 26
image_end: 光粒.png
drawOverBody: true
spinRate: 3


[arm_2]
x: 0
y: 26
image_end: 光粒.png
drawOverBody: true
spinRate: 1


[arm_3]
x: 0
y: 26
image_end: 光粒.png
drawOverBody: true
spinRate: -2


[arm_4]
x: 0
y: 26
image_end: 光粒.png
drawOverBody: true
spinRate: -1


[arm_5]
x: 0
y: 26
image_end: 蓄能.png
drawOverBody: true
spinRate: -1


[arm_6]
x: 0
y: 26
image_end: 冲击波3.png
drawOverBody: true
spinRate: -1


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.22
noneInBaseExtraPriority: 0.17
maxEachBase: 3
useAsBuilder: true


