


[core]
name: 空塔楼t1
displayText: Пустая башня t1
class: CustomUnitMetadata
price: 500
maxHp: 2100
footprint: 0,0,1,1

constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 13
techLevel: 1
buildSpeed: 0

showInEditor: false
radius: 25
buildingSelectionOffset: -8
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true

selfRegenRate: 0.12
tags: 地面,灰影建筑,建筑
isBio: false
effectOnDeath: CUSTOM:烟雾2*2,CUSTOM:爆炸*1


[action_停电]
#autoTrigger:displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)

displayType: infoOnly
isGuiBlinking: true


[action_中性粒子炮]
convertTo: 中性粒子炮t1
displayType: action
text: Развернуть пушку нейтральных частиц
description: Пушка нейтральных частиц — зрелое частицевое оружие.\n-Частицевый луч пушки нейтральных частиц не рассеивается с расстоянием.\n-Это оружие прошло закалку огнём ещё во вторую великую эпоху мореплавания Древних Людей.\n-Смертоносное, точное, практичное, быстрое —\n-мы называем его классикой.\n-Атакует землю и воздух, кинетический урон.
price: 1500
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t2') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 2, либо это здание должно быть обесточено, и одновременно можно развернуть только одну турель.
ai_isHighPriority: true


[action_瓦普驱动炮]
convertTo: 瓦普驱动炮t1
displayType: action
text: Развернуть варп-пушку
description: Концепция варп-пушки очень брутальна и прямолинейна.\n-Она использует устройство ближнего прыжка, чтобы напрямую телепортировать термоядерное вещество из ближайшего реактора.\n-Это вещество с температурой в сотни миллионов градусов забрасывается во врага, вызывая мощный взрыв.\n-Атакует только землю, энергетический урон.
price: 2200
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t2') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 2, либо это здание должно быть обесточено, и одновременно можно развернуть только одну турель.
ai_isHighPriority: true


[action_重型多联炮]
convertTo: 重型多联炮t1
displayType: action
text: Развернуть тяжёлую многоствольную пушку
description: До изобретения плазменного оружия частицевые многоствольные пушки уже были распространены по всему миру Древних Людей.\n-В отличие от обычной пушки нейтральных частиц, они полагаются на несколько эмиттеров, стреляющих по очереди, чтобы быстро создавать огневое подавление.\n-Будь то воздушные или наземные юниты, многоствольная пушка может нанести быстрый и смертельный удар.\n-Атакует землю и воздух, кинетический урон. Пробивает укрытия.
price: 1800
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, либо это здание должно быть обесточено, и одновременно можно развернуть только одну турель.
[action_粒子弩炮]
convertTo: 粒子弩炮t1
displayType: action
text: Развернуть частицевый арбалет
description: Тяжёлое частицевое оружие для осады, широко устанавливалось на крупные корабли в эпоху Воюющих государств Древних Людей.\n-Оно разгоняет частицевые лучи до невообразимой скорости, пронзая всех врагов на пути.\n-Атакует только землю. Кинетический урон.
price: 2000
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.noUnitInTeam(withTag= '聚变堆', withinRange= 400) or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, либо это здание должно быть обесточено, и одновременно можно развернуть только одну турель.
ai_isHighPriority: true


[graphics]
total_frames: 1
image: ROOT:/太空浪人/建筑特效/防御塔t1.png
image_wreak: ROOT:/太空浪人/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
imageScale: 0.9
image_back: ROOT:/通用特效/NO.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 200

turretSize: 12
turretTurnSpeed: 3
maxAttackRange: 340


[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 空塔楼t1传送
ai_upgradePriority: 0.07


