
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}

[core]
name: 涤罪者1
displayText: Очиститель 1
showInEditor: false
price: 3000
maxHp: 4000
maxShield: 1000
shieldRenderRadius: 1
shieldRegen: 0.05
displayDescription:【Уровень t4】【Преодолевает утёсы】【Механический юнит】【Беспилотный юнит】【Наземный юнит】тактическое назначение:общийиспользует  типмехов, размер юнита:3, \n-вооружение:▲плазменная наручная пушкаX1 только по земле только по наземным целяммеханическийюнит энергетический урон \n-▲плазменный огнемётX1 только по наземным целямзданиеобъект и жизньобъектюнит  нейтральный урон против укрытий \n-▲тяжёлый пулемётX4 по земле и воздуху энергетический урон против укрытий против спутникжизнь, воздушныйв юнитурондобавитьстать  \n-Очистительэто поздний период Войны Государств эпохи Древних Людей, AIдля эффективныйдолжен против остатоккрутой переулокбойразработка тяжёлый оснащатьнет человекмехов, \n- и другие десантвойска юнитпо сравнению, Очистительтяжёлый сильныйнастройкаколичествопроизводство, \n-чтобы жертвареакторфункциякоэффициентвынужденныйоснащатьоснащёнреальныйтелощитдля эраценаменятьприходит крайнеего ужасный производствоколичество, \n-его головачастьраспространеныбольшой количествоснаружи размещениеразведкаигла, особенноего это против малый  типюниткрайнеего чувствительный, \n-Очистительможет в мгновение мгновеннобудетодин малый отряд тяжёлый оснащатьморская пехотав пепел, \n- также илиэто использует плазменная наручная пушкабудетвражескиймашинабитьштпротив пробить.
techLevel: 1
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
buildSpeed: 10s
radius: 42
displayRadius: 42
armour: 10
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
transportSlotsNeeded: 3
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
tags: 地面,无人单位,迎敌,涤罪者
energyMax: 5
energyRegen: 0.06
energyNeedsToRechargeToFull: true
effectOnDeath:CUSTOM:小型余晖死亡冲击波,CUSTOM:小型余晖死亡爆炸,CUSTOM:小型余晖死亡钢珠,CUSTOM:小型余晖死亡闪光
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 480 | setFlag= 0-1)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
[attachment_2]
x: -26
y: -42.5
onCreateSpawnUnitOf: 通用挂载附属
lockRotation: true
prioritizeParentsMainTarget: true
rotateWithParent:false
alwaysAllowedToAttackParentsMainTarget: true

[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 480 | setFlag= 0-1)
[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", greaterThan= 0.5)
isVisible: false
alsoQueueAction: b
temporarilyRemoveTags:迎敌
[action_b]
convertTo: 涤罪者
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed


[decal_灯光]
layer: onTop
image: 灯光.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
basePositionFromLegEnd: arm_8
alpha:0.8
[decal_主体损坏a]
layer: onTop
image: 损坏.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_8
isVisible: if self.hp < self.maxHp * 0.36
alpha:0.8
[decal_护盾损坏]
layer: onTop
image: 盾损坏.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_9
isVisible: if self.hp < self.maxHp * 0.36
alpha:0.8
[decal_机枪]
image: 机关枪2.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '迎敌')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_10
imageScale: 0.85
[decal_机枪1]
image: 机关枪3.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '迎敌')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_11
imageScale: 0.85
[decal_机枪2]
image: 机关枪1.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '迎敌')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_12
imageScale: 0.85

[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true

#imageScale: 0.8
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14
isFixedFiring: true
turretTurnSpeed: 2
maxAttackRange: 370
shootDelay: 100
turretRotateWithBody: true
turretMultiTargeting: false

[turret_1]
x: 34
y: 15
invisible: true
size:40
canShoot: true
shoot_sound: ROOT:/余辉军团/单位特效/等离子.wav
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:光子*7,CUSTOM:冲击波1,CUSTOM:闪光1
shoot_light: #FF00B3FF
projectile:1
delay:80
warmup:40
warmupStartEffect: CUSTOM:冲击波,CUSTOM:汇聚*8
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
canAttackFlyingUnits: false
attachedTo: 3
slave: true
onShoot_playAnimation: attack
canOnlyAttackUnitsWithoutTags:步兵,建筑
canAttackCondition: if self.resource.xk < 1
[turret_2]
x: 34
y: 15
invisible: true
size:40
attachedTo: 3
slave: true
canShoot: true
projectile: 2
shoot_sound: ROOT:通用特效/火球发射.ogg
shoot_sound_vol: 0.2
shoot_flame: CUSTOM:小火焰*1,CUSTOM:黑色烟雾*1,CUSTOM:闪光小
canAttackFlyingUnits: false
delay: 1
canAttackCondition: if self.resource.xk < 1
aimOffsetSpread: 1
energyUsage:0.15
canOnlyAttackUnitsWithTags:步兵,建筑
[turret_xx]
x: 34
y: 15
copyFrom: 2
shoot_sound: ROOT:通用特效/火球发射.ogg
shoot_sound_vol: 0
shoot_flame: NONE

[turret_3]
x: 0
y: 0
canShoot: false
invisible: true
[projectile_1]
@copyFromSection: template_能源
directDamage: 1000
life: 200
speed: 9
image: ROOT:/余辉军团/单位特效/中子弹.png
targetSpeed: 9
drawSize: 0.77
explodeEffect: CUSTOM:冲击波zp, CUSTOM:爆炸zp,CUSTOM:爆炸zp1,CUSTOM:闪光zp
explodeEffectOnShield: CUSTOM:冲击波zp, CUSTOM:爆炸zp,CUSTOM:爆炸zp1,CUSTOM:闪光zp
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1

[projectile_2]
life: 1
speed: 8
areaDamage: 65
areaRadius: 55
targetSpeed: 8
speedSpread:3
image: ROOT:/余辉军团/单位特效/大火焰.png
drawSize: 0.1
targetGroundSpread: 25
areaRadiusFromEdge: true
spawnProjectilesOnEndOfLife: 3(recursionLimit= 17)
explodeOnEndOfLife: false
targetGround: true
lightSize: 1.5
deflectionPower: -1
lightColor: #FF00B3FF
explodeEffect: CUSTOM:火焰爆炸
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator2_ifUnitWithTags: 步兵
mutator2_directDamageMultiplier: 2
mutator2_areaDamageMultiplier: 2
buildingDamageMultiplier: 2
[projectile_3]
@copyFromSection: projectile_2
life: 5
drawSize: 0.2
#0.4
spawnProjectilesOnEndOfLife: 4(recursionLimit= 17)
[projectile_4]
@copyFromSection: projectile_2
drawSize: 0.3
life: 8
#0.4
spawnProjectilesOnEndOfLife: 5(recursionLimit= 17)
[projectile_5]
@copyFromSection: projectile_2
drawSize: 0.35
life: 8
spawnProjectilesOnEndOfLife: 6(recursionLimit= 17)
[projectile_6]
@copyFromSection: projectile_2
drawSize: 0.4
life: 80

#————————主炮开火
[effect_汇聚]
priority: low
image: ROOT:/通用特效/旋转光效.png
dirOffsetRandom: 360
dirSpeed: 1
dirSpeedRandom: 0.5
life: 45
scaleFrom: 0.45
scaleTo: 0
alpha: 0.9
drawUnderUnits: false
attachedToUnit: true
atmospheric: false
delayedStartTimerRandom:20
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 1.4
scaleTo: 0.1
alpha: 0.8
color: #FF00B3FF

[effect_冲击波1]
stripIndex: shockwave
life: 33
scaleFrom: 0.2
scaleTo: 1.4
alpha: 0.8
color: #FF00B3FF
[effect_闪光1]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 30
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 0.2
ySpeedRelative: 1
ySpeedRelativeRandom: 0.5
priority: low
#————————主炮尾巴
[effect_尾巴]
priority: low
image: ROOT:/余辉军团/单位特效/光束3.png
life: 24
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
drawUnderUnits: false
yOffsetRelative: 5
[effect_尾巴1]
image: ROOT:/余辉军团/单位特效/蓄能.png
spawnChance: 1
priority: verylow
createWhenZoomedOut: false
life: 25
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 0.7
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: -0.4
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 1.2
atmospheric: true
#————————主炮爆炸

[effect_爆炸zp]
life: 70
dirOffsetRandom: 180
priority: veryhigh

fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.7
image: ROOT:/余辉军团/单位特效/爆.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.9

[effect_爆炸zp1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8
image: ROOT:/余辉军团/单位特效/炸裂.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.28
alpha:0.8
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
[effect_闪光zp]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波zp]
stripIndex: shockwave
life: 20
scaleFrom: 0.4
scaleTo: 1.8
alpha: 0.9
color: #FF00B3FF
#————————火焰喷射器开火
[effect_闪光小]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 0
drawUnderUnits: false
spawnChance: 0.5
atmospheric: false
[effect_黑色烟雾]
priority:verylow
frameIndex: 0
stripIndex: smoke_black
spawnChance: 0.8
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #FFFFFF
fadeInTime: 2
scaleFrom: 1
scaleTo: 1.5
alpha: 0.5
drawUnderUnits: false
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.5
ySpeedRelative: 1.2
ySpeedRelativeRandom: 0.3
atmospheric: true
[effect_小火焰]
priority:high
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 2
alpha: 0.5
drawUnderUnits: false
dirOffsetRandom: 180
xSpeedRelativeRandom: 1
ySpeedRelative:3
ySpeedRelativeRandom: 0.3
atmospheric: true
scaleFrom: 0.5
scaleTo: 1.2
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_火焰爆炸]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/boom.png
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.3
alpha: 0.7
drawUnderUnits: false
ySpeedRelative: 2
atmospheric: true
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFrameSpeed: 0.3
[arm_1]
x: 22
y: -9
image_end: 右.png
image_end_teamColors: true
drawDirOffset: -15

drawOverBody: true
image_end_shadow: SHADOW:右.png
[arm_2]
x: 34
y: 10
image_end: 右手.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
image_end_shadow: SHADOW:右手.png

[arm_3]
x: 34
y: 15
#（-8）
image_end: 腕炮炮管.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true

[arm_4]
x: 34
y: 10
image_end: 腕炮1.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
[arm_5]
x: -12
y: 38
image_end: 左手.png
image_end_teamColors: true
drawDirOffset: 70

drawOverBody: true
image_end_shadow: SHADOW:左手.png

[arm_6]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawDirOffset:22
drawOverBody: true
image_end_shadow: SHADOW:主体.png



[arm_7]
x: 7
y: -28
image_end: 机械臂.png
image_end_teamColors: true
drawDirOffset: -113
drawOverBody: true
image_end_shadow: SHADOW:机械臂.png


[arm_8]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawDirOffset:22
drawOverBody: true
image_end_shadow: SHADOW:遮盖.png
[arm_9]
x: -12
y: 38
image_end: 盾.png
image_end_teamColors: true
drawDirOffset: 70

drawOverBody: true
image_end_shadow: SHADOW:盾.png
[arm_10]
x: -26
y: -42
image_end: NO.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
#image_end_shadow: SHADOW:机关枪.png
[arm_11]
x: -26
y: -42
image_end:NO.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
#image_end_shadow: SHADOW:机关枪3.png
[arm_12]
x: -26
y: -43
image_end: NO.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
#image_end_shadow: SHADOW:机关枪1.png
[leg_1]
x: -16
y: 15
attach_x: -4
attach_y: 3
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚丫.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 16
y: 15
attach_x: 4
attach_y: 3
copyFrom: 1

drawDirOffset: 10
[animation_attack]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm2_0.1s: {x:0, y:-15, dir:-5}
arm3_0.1s: {x:0, y:-15, dir:-5}

arm4_0.1s: {x:0, y:-15, dir:-5}
arm6_0.1s: {x:0, y:0, dir:3}
arm8_0.1s: {x:0, y:0, dir:3}
[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}

arm1_0.12s: {x:0, y:0, dir:0}
arm2_0.12s: {x:0, y:0, dir:0}
arm3_0.12s: {x:0, y:-5, dir:0}
arm4_0.12s: {x:0, y:0, dir:0}
arm5_0.12s: {x:0, y:0, dir:0}
arm6_0.12s: {x:0, y:0, dir:0}
arm7_0.12s: {x:0, y:0, dir:0}
arm8_0.12s: {x:0, y:0, dir:0}
arm9_0.12s: {x:0, y:0, dir:0}
arm10_0.12s: {x:0, y:0, dir:0}
arm11_0.12s: {x:0, y:0, dir:0}
arm12_0.12s: {x:0, y:0, dir:0}


arm1_0.6s: {x:3, y:6, dir:-10}
arm2_0.6s: {x:3, y:4, dir:-40}
arm3_0.6s: {x:3, y:-1, dir:-40}
arm4_0.6s: {x:3, y:4, dir:-40}
arm5_0.6s: {x:-22, y:-18, dir:-60}
arm6_0.6s: {x:0, y:0, dir:-22}
arm7_0.6s: {x:13, y:0, dir:23}
arm8_0.6s: {x:0, y:0, dir:-22}
arm9_0.6s: {x:-22, y:-18, dir:-60}
arm10_0.6s: {x:11, y:11, dir:90}
arm11_0.6s: {x:11, y:17, dir:90}
arm12_0.6s: {x:11, y:15, dir:90}
[movement]
movementType: OVER_CLIFF
moveSpeed: 1.1
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 1.1

turnAcceleration: 0.04
targetHeight: 3
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0

slowDeathFall: true


