


[core]
name: 通用挂载附属
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true
energyMax: 4
energyRegen: 0.01
energyNeedsToRechargeToFull: true
isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true


#————————涤罪者
[decal_机枪1]
image:枪管.png
total_frames: 1
layer: onTop
isVisible:if parent.tags(includes= '迎敌') and parent.tags(includes= '涤罪者')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 1
imageScale: 0.85
[decal_机枪2]
image:枪管.png
total_frames: 1
layer: onTop
isVisible:if parent.tags(includes= '迎敌') and parent.tags(includes= '涤罪者')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 2
imageScale: 0.85
[decal_机枪3]
image:枪管.png
total_frames: 1
layer: onTop
isVisible:if parent.tags(includes= '迎敌') and parent.tags(includes= '涤罪者')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 3
imageScale: 0.85
[decal_机枪4]
image:枪管.png
total_frames: 1
layer: onTop
isVisible:if parent.tags(includes= '迎敌') and parent.tags(includes= '涤罪者')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 4
imageScale: 0.85
[decal_机枪]
image: 机关枪4.png
total_frames: 1
layer: onTop
isVisible:if parent.tags(includes= '迎敌') and parent.tags(includes= '涤罪者')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 5
imageScale: 0.85
[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: onTop
isVisible:if parent.shield>parent.maxShield*0.03 and not parent.tags(includes= '克莱因') and parent.tags(includes= '涤罪者')
yOffsetRelative:48
xOffsetRelative:27
alpha: max( 0, sin( parent.shield * 90 / parent.maxShield ) - ( 5 *  parent.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 0.7
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
#turretImageScale: 0.9
teamColorsOnTurret: true
[attack]
canAttack: true
canAttackFlyingUnits: if not parent.hasParent
canAttackLandUnits: if not parent.hasParent
canAttackUnderwaterUnits: false
maxAttackRange: 370
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0
turretMultiTargeting: true
#_______________余辉涤罪
[turret_1]
x: -9.5
y: 25.5
attachedTo: 5
slave: true
image: NO.png
shoot_flame: CUSTOM:枪口火焰
shoot_sound: ROOT:/余辉军团/单位特效/机炮.wav
shoot_sound_vol: 0.12
recoilOffset: -6
recoilOutTime: 2
shoot_light: #FF00B3FF
recoilReturnTime: 10
projectile: 1
size: 18
delay:20

canAttackCondition: if parent.resource.xk < 1 and parent.tags(includes= '涤罪者') and parent.tags(includes= '迎敌') and not parent.hasParent
invisible: if not parent.tags(includes= '迎敌') or not parent.tags(includes= '涤罪者')
[turret_2]
x: -5.5
y: 22
copyFrom: 1
delay:17
linkDelayWithTurret:1
warmup:3
[turret_3]
x: 5.5
y: 22
copyFrom: 1
delay:14
linkDelayWithTurret:2
warmup:6
[turret_4]
x: 9.5
y: 25.5
copyFrom: 1
delay:11
linkDelayWithTurret:3
warmup:9
[turret_5]
x: 0
y: 0
canShoot: false
recoilOffset: -1
image: NO.png
idleDir:0
canAttackCondition: if parent.resource.xk < 1 and parent.tags(includes= '涤罪者') and parent.tags(includes= '迎敌')
invisible: if not parent.tags(includes= '迎敌') or not parent.tags(includes= '涤罪者')
turnSpeed: 10
turnSpeedAcceleration: 4





[projectile_1]
@copyFromSection: template_能源
directDamage: 40
life: 240
speed: 14
targetSpeed: 14
deflectionPower: -1

image:ROOT:/余辉军团/单位特效/粒子2.png
explodeEffect: CUSTOM:火花
drawSize: 0.5
mutator997_ifUnitWithTags: 伴生单位
mutator997_directDamageMultiplier: 4
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator431_ifUnitWithTags: 飞机
mutator431_directDamageMultiplier: 2.5
mutator431_areaDamageMultiplier: 2.5



#_______________余辉涤罪开火特效
[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/余辉军团/单位特效/枪口火焰.png
total_frames: 3
scaleFrom: 2
scaleTo: 5
animateFrameStart: 0
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
[effect_火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 0.34
image: ROOT:/余辉军团/单位特效/大火花.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 1000
turnAcceleration: 1000
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


