

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}
[core]
name: 回声突击战车
displayText: Эхо-штурмовая бронемашина
displayDescription: 【Уровень t4】【Беспилотный юнит】【Механический юнит】【Наземный юнит】【Парящий юнит】【Амфибия】\n-тактическое назначение:парящая антитяжёлая боевая машина, размер юнита4, вооружение:\n-▲Колебательная пушка только по земле взрывной урон, усиленный урон по сверхтяжёлым юнитам и зданиям, \n-▲торпедатрубкаX4 толькоможет в водана использоватьиспользует  толькоможет атакавода и водапод юнит взрывной урон\n-▲плазмаминомётX2 только по земле взрывной урон\n-компания Зетаноядолжен имперский флотразработала для специальных десантных операций, амфибийное транспортное средство, заменяющее канонерку «Небесный Огонь», \n-Основное оружие - колебательная пушка, стреляющая конденсированной материей, Это летальное оружие от Утомирпосле пробития брони детонирует несколько раз, \n-Особенно эффективна против тяжёлых юнитов, Вооружённое до зубов «Эхо» также имеет торпедатрубка, плазмаминомёти другое вооружение для разных ситуаций.\n-А при сложном рельефе,, Империя другие сухопутные войскакогда другие наземные войска не могут развернуться,, \n-главным героем поля боя становится Эхо-штурмовая бронемашина.
transportSlotsNeeded: 4
price: 3000
maxHp: 4000
maxShield: 4000
shieldRenderRadius: 1
shieldRegen: 0.07
techLevel: 1
buildSpeed: 13s
availableInDemo: true
fogOfWarSightRange: ${int(attack.maxAttackRange/17.5)}
armour: 12
effectOnDeath:CUSTOM:小型余晖死亡冲击波,CUSTOM:小型余晖死亡爆炸,CUSTOM:小型余晖死亡钢珠,CUSTOM:小型余晖死亡闪光
radius: 48
displayRadius: 48
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
softCollisionOnAll: 10
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
tags: 地面,悬浮,无人单位
energyMax: 6
energyRegen: 0.023
energyNeedsToRechargeToFull: true
[decal_影子2]
image: SHADOW:回声主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:4
onlyWhileAlive:true
alpha:0.6
[decal_垫板]
image: 垫板.png
total_frames: 1
layer: beforeBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_导弹]
image: 左炮收.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪x') and self.tags(includes= '关闭')
yOffsetRelative:-41
xOffsetRelative:-25
onlyWhileAlive:true
[decal_导弹1]
image: 右炮收.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪x') and self.tags(includes= '关闭')
yOffsetRelative:-41
xOffsetRelative:25
onlyWhileAlive:true

[decal_导]
image: 左炮开.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
yOffsetRelative:-41
xOffsetRelative:-25
onlyWhileAlive:true
[decal_导1]
image: 右炮开.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
yOffsetRelative:-41
xOffsetRelative:25
onlyWhileAlive:true

[decal_左关闭]
image: 左炮关动.png
total_frames: 13
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 17) % 13, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:-41
xOffsetRelative:-25

[decal_右关闭]
image: 右炮关动.png
total_frames: 13
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 17) % 13, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:-41
xOffsetRelative:25

[decal_左开启]
image: 左炮开动.png
total_frames: 13
frame: select(self.tags(includes= '切枪'), (self.customTimer * 17) % 13, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:-41
xOffsetRelative:-25

[decal_右开启]
image: 右炮开动.png
total_frames: 13
frame: select(self.tags(includes= '切枪'), (self.customTimer * 17) % 13, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:-41
xOffsetRelative:25

[decal_本体]
image: 回声主体1.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
[decal_主体1]
image: 回声损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[decal_机体灯]
image:回声光.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.8
[decal_主炮]
image: 主炮.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 4
[decal_主炮光]
image: 主炮光.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 4
[decal_引擎盖]
image: 引擎盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:36
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
[decal_引擎盖损坏]
image: 盖损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:36
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[hiddenAction_akm]
autoTrigger: if not self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") == null
addResources: setFlag=1
alsoQueueAction:zx
temporarilyAddTags: 切枪
temporarilyRemoveTags:关闭
resetCustomTimer: true


[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:6
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 0.79
[hiddenAction_bkm]
autoTrigger: if self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") != null
stopLastAnimation: true
addResources: unsetFlag=1
alsoQueueAction:zxx
temporarilyAddTags: 切枪x,关闭
resetCustomTimer: true
[action_zx]
displayType: action
price: 0
buildSpeed: 0.61s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪

[action_zxx]
displayType: action
price: 0
buildSpeed: 0.61s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪x
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 540 | setFlag= 0)
# 对地对空
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image: 回声主体1.png
image_wreak: 死了.png
image_turret: NONE
image_shadow: NONE
showQueueBar: false
showTransportBar: false
showEnergyBar: false
teamColorsOnTurret: true
showShotDelayBar:false
movementEffectRate: 0.5
movementEffect: CUSTOM:火1,CUSTOM:火2

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
turretSize: 20
turretTurnSpeed: 1.5
maxAttackRange: 550
#425
isFixedFiring: true
[turret_1]
x: 0
y: 0
canShoot: false
canAttackCondition: if self.resource.xk < 1
invisible:true
[turret_2]
x: -25
y: -45
shoot_sound: ROOT:/余辉军团/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾*3
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '关闭')
invisible:true
attachedTo: 1
limitingRange:425
slave: true
delay:10
size:10
canAttackUnderwaterUnits: false
energyUsage:1
[turret_3]
x: 25
y: -45
copyFrom: 2
delay:7
warmup:3
linkDelayWithTurret:2
[turret_4]
x: 0
y: 47
#主炮
projectile: 2
shoot_sound: ROOT:/余辉军团/单位特效/迫击炮.wav
shoot_sound_vol: 0.4
shoot_flame: CUSTOM:烟雾*8,CUSTOM:小等离子冲击波,CUSTOM:小等离子闪光
shoot_light: #FF00B3FF
canAttackFlyingUnits: false
canAttackUnderwaterUnits: false
canShoot: true
recoilOffset: -9
recoilOutTime: 5
recoilReturnTime: 20
delay: 180
warmup:50
size: 35
canAttackCondition: if self.resource.xk < 1
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
image: 主炮.png
attachedTo: 1
slave: true
aimOffsetSpread: -0.01
warmupStartEffect: CUSTOM:汇聚冲击波,CUSTOM:汇聚*8
limitingRange:425
[turret_5]
x: -28.5
y: 35
canShoot: true
projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾*3
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
turnSpeed: 0
canAttackCondition: if self.resource.xk < 1 and self.overWater()
image:小鱼雷1.png
recoilOffset: -10
size:3
recoilOutTime: 4
recoilReturnTime: 60
delay:180
canOnlyAttackUnitsWithoutTags:悬浮
attachedTo: 1
slave: true
[turret_6]
x: -24
y: 38
copyFrom: 5
delay:170
warmup:10
linkDelayWithTurret:5
[turret_7]
x: 24
y: 38
copyFrom: 5
delay:160
warmup:20
linkDelayWithTurret:6
[turret_8]
x: 28.5
y: 35
copyFrom: 5
delay:150
warmup:30
linkDelayWithTurret:7
[projectile_1]
@copyFromSection: template_爆炸
life: 6661
speed: 4
targetSpeed: 6
drawSize: 1.1
image: ROOT:/余辉军团/单位特效/蓄能.png
areaDamage: 180
areaRadius: 55
targetGround: true
initialUnguidedSpeedHeight: 1
areaRadiusFromEdge: true
gravity: 0.4
targetGroundSpread: 35
lightColor: #FF00B3FF
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴
disableLeadTargeting: true
explodeEffectOnShield:CUSTOM:小等离子冲击波,CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光,CUSTOM:小等离子光子*5
explodeEffect: CUSTOM:小等离子冲击波,CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光,CUSTOM:小等离子光子*5

[projectile_2]
life: 0
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnExplode: m2(yOffsetRelative= 20)
explodeOnEndOfLife: true
explodeEffect:NONE
[projectile_m2]
@copyFromSection: template_爆炸
life: 1
deflectionPower: -1
explodeOnEndOfLife: true
speed: 0
turnSpeed: 0.0
areaDamage: 200
areaRadius: 50
areaRadiusFromEdge: true
targetGround: true
invisible: true
explodeEffect: CUSTOM:主炮闪光1,CUSTOM:爆炸b1,CUSTOM:主炮冲击波,CUSTOM:主炮闪光
spawnProjectilesOnCreate: m2(recursionLimit= 18, yOffsetRelative= 20)
delayedStartTimer: 0.05s
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2.5
mutator7_areaDamageMultiplier: 2.5
buildingDamageMultiplier: 2
[projectile_3]
@copyFromSection: template_爆炸
directDamage:450
life: 460
speed: 0.5
targetSpeed: 5
image: 小鱼雷.png
drawSize: 0.9
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:烟雾3*2,CUSTOM:水波*1,CUSTOM:水花*1,CUSTOM:鱼雷冲击波,CUSTOM:主炮闪光
explodeEffectOnShield: CUSTOM:烟雾3*2,CUSTOM:水波*1,CUSTOM:水花*1,CUSTOM:鱼雷冲击波,CUSTOM:主炮闪光
lightColor:#FF00B3FF
lightSize: 0
trailEffectRate: 0.8
trailEffect: CUSTOM:鱼雷尾巴
turnSpeed: 4
#——————————副炮发射
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 55
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.6
ySpeedRelative: 1
atmospheric: true
[effect_尾巴]
image: SHARED:light_50.png
life: 23
fadeOut: true
attachedToUnit: false
priority: verylow
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.26
scaleTo: 0.1
alpha: 1
drawUnderUnits: false
#——————————副炮发射
[effect_汇聚]
priority: low
image: ROOT:/通用特效/旋转光效.png
dirOffsetRandom: 360
dirSpeed: 1
dirSpeedRandom: 0.5
life: 45
scaleFrom: 0.45
scaleTo: 0
alpha: 0.9
drawUnderUnits: false
attachedToUnit: true
atmospheric: false
delayedStartTimerRandom:20
[effect_汇聚冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 1.6
scaleTo: 0.1
alpha: 0.8
color: #FF00B3FF
#——————————主炮爆炸

[effect_爆炸b1]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.8
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
[effect_主炮冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.5
scaleTo: 2.3
alpha: 0.8
color: #FF00B3FF
[effect_主炮闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_主炮闪光1]
image: SHARED:light_50.png
life: 110
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 0.2
drawUnderUnits: false
atmospheric: false
#——————————鱼雷发射
[effect_鱼雷尾巴]
image: SHARED:light_50.png
life: 38
fadeOut: true
attachedToUnit: false
priority: high
color:#FF0092FF
fadeInTime: 2
scaleFrom: 0.28
scaleTo: 0.15
alpha: 0.8
drawUnderUnits: true
yOffsetRelative:-10
#——————————鱼雷爆炸
[effect_鱼雷冲击波]
stripIndex: shockwave
life: 70
scaleFrom: 0.3
scaleTo: 2.8
color: #FFF0AFA5
attachedToUnit: false
alpha: 1
createWhenOverLiquid: true
createWhenOverLand: false
[effect_烟雾3]
priority: critical
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true

attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 1
scaleTo: 2.5

alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true

hSpeed: 0.2
hOffsetRandom: 0.15
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15

xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false


[effect_水花]
image: ROOT:/通用特效/水花.png
life: 160
fadeOut: true
attachedToUnit: false
color: #FFFFFF

fadeInTime: 4
scaleFrom: 0.05
scaleTo: 0.25
alpha: 0.6
drawUnderUnits: false

dirOffsetRandom: 0
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3

createWhenOverLiquid: true
createWhenOverLand: false


[effect_水波]
priority: critical
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.35
alpha: 1
drawUnderUnits: true
atmospheric: true

createWhenOverLiquid: true
createWhenOverLand: false
#——————————移动
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FF00B3FF
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -64
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
ySpeedRelative: -1
yOffsetRelative	: -64
#drawUnderUnits: true
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[movement]
movementType: HOVER
moveSpeed: 1.77
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.03
maxTurnSpeed: 1.5
turnAcceleration: 0.6
moveSlidingMode : true
moveIgnoringBody: true
targetHeight: 1
targetHeightDrift: 1
