[core]
name: 创世纪舰队港湾t3
class: CustomUnitMetadata
price: 12500
maxHp: 40000
armour: 60
footprint: -5,-5,5,9
constructionFootprint: -5,-5,5,9
displayDescription: 【阶级t4】【建筑单位】【水上单位】\n-战术定位：水面舰艇生产设施，无武装。\n-只能在水面上建造。利用标准建造系统快速部署的模块化海军生产设施，\n-内置一套自动化流水线，能够快速将封装好的模块打包建造成为战舰，\n-这种船厂几乎是创世纪港口最常见且不可或缺的设施。
unitsSpawnedOnDeath:建筑损毁*1
techLevel: 1
buildSpeed: 14s
#availableInDemo: true
tags:地面,海上,建筑
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 120
isBio: false
isBuilding: true
nanoFactorySpeed:1
effectOnDeath: CUSTOM:烟雾*6, CUSTOM:爆破*15
exit_x:0
exit_y: 95
exit_moveAwayAmount: 300
canBuild_31_name: setRally
canBuild_31_pos: 0.1
[action_煅炉增益]
autoTrigger:if self.globalTeamTags(includes='纳米煅炉') and not self.tags(includes= '煅炉保险')
isActive: false
isVisible: false
temporarilyAddTags:煅炉保险
setUnitStats: nanoFactorySpeed=1.3
[action_T2]
pos: 0.2
buildSpeed: 0s
addResources: setFlag=0,setFlag=2
text: 显示t1单位
isVisible: if not self.hasFlag(id=2) and not self.hasFlag(id=0)
[action_T2_back]
pos: 0.2
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=2
isVisible: if self.hasFlag(id=2)
text: 不显示t1单位
[action_T3]
pos: 0.3
buildSpeed: 0s
addResources: setFlag=0,setFlag=3
text: 显示t2单位
isVisible: if not self.hasFlag(id=3) and not self.hasFlag(id=0)
highPriorityQueue: true
[action_T3_back]
pos: 0.3
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=3
isVisible: if self.hasFlag(id=3)
text: 不显示t2单位
ai_isHighPriority: true
[action_T4]
pos: 0.3
buildSpeed: 0s
addResources: setFlag=0,setFlag=4
text: 显示t3单位
isVisible: if not self.hasFlag(id=4) and not self.hasFlag(id=0)
highPriorityQueue: true
ai_isHighPriority: true
[action_T4_back]
pos: 0.3
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=4
isVisible: if self.hasFlag(id=4)
text: 不显示t3单位
[canBuild_T2]
name: 长须鲸工程船,蛙人潜水器,炮艇,追击舰
pos: 0.4
isVisible: if self.hasFlag(id=2)
[canBuild_T3]
name: 长须鲸工程船,勇士级护卫舰,幻想级巡洋舰,两栖突击舰,长吻鳄级攻击潜艇
pos: 0.5
isVisible: if self.hasFlag(id=3)
[canBuild_T4]
name: 长须鲸工程船,重型工程车,净化者机甲,灰鲭鲨级重型驱逐舰,三叉戟级巡洋舰,阿特拉斯级运输船
pos: 0.6
isVisible: if self.hasFlag(id=4)
[canBuild_T33]
name: 核子巡洋舰
pos: 0.51
isVisible: if self.hasFlag(id=3)
isLocked: if not self.globalTeamTags(includes='裂变技术1')
isLockedMessage: 你需要裂变技术1
[canBuild_T34]
name: 黑珍珠级战列舰
pos: 0.52
isVisible: if self.hasFlag(id=3)
isLocked: if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: 你需要材料技术2
[canBuild_T35]
name: 双髻鲨级驱逐舰
pos: 0.53
isVisible: if self.hasFlag(id=3)
isLocked: if not self.globalTeamTags(includes='轨道发射器2') or not self.globalTeamTags(includes='材料技术2')
isLockedMessage: 你需要轨道发射器2和材料技术2

[canBuild_T41]
name:占星师级两栖攻击舰
pos: 0.61
isVisible: if self.hasFlag(id=4)
isLocked: if not self.globalTeamTags(includes='材料技术3') or not self.globalTeamTags(includes='弹道导弹技术2')
isLockedMessage: 你需要材料技术3和便携式弹道导弹技术

[canBuild_T42]
name:海狼级战列巡洋舰
pos: 0.62
isVisible: if self.hasFlag(id=4)
isLocked: if not self.globalTeamTags(includes='轨道发射器3') or not self.globalTeamTags(includes='超导技术1')
isLockedMessage: 你需要轨道发射器3和超导技术1

[canBuild_T43]
name:浮游坦克
pos: 0.63
isVisible: if self.hasFlag(id=4)
isLocked: if not self.globalTeamTags(includes='超导技术1')
isLockedMessage: 你需要超导技术1
[action_MK1]
displayType: action
text: 模块化生产双髻鲨级驱逐舰
price:5525,钍=52
pos: 1
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术') and self.globalTeamTags(includes='基础科学进步1')
isLocked: if not self.globalTeamTags(includes='轨道发射器2') or not self.globalTeamTags(includes='材料技术2')
isLockedMessage: 你需要轨道发射器2和材料技术2
produceUnits:双髻鲨级驱逐舰
buildSpeed: 22s

[action_MK2]
displayType: action
text: 模块化生产黑珍珠级战列舰
price:7800
pos: 1.1
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术') and self.globalTeamTags(includes='基础科学进步1')
isLocked: if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: 你需要材料技术2
produceUnits:黑珍珠级战列舰
buildSpeed: 30s
[graphics]
total_frames: 1
image: 底子.png
image_back: 底子.png
image_wreak:ROOT:/创世纪军事集团/建筑特效/死亡c.png
image_shadow: 影子.png
imageScale: 0.95

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 30
maxAttackRange: 9999
shootDelay: 0


[turret_1]
x: 10
y: 170
projectile: 13
shoot_flame: CUSTOM:烟雾2
delay: 20
invisible: true
size: 0
[turret_2]
x: 35
y: 170
copyFrom: 1

[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1
[effect_烟雾2]
createWhenZoomedOut: false
stripIndex: effects
frameIndex: 0
life: 300
fadeOut: true
attachedToUnit: false
color: #646464
fadeInTime: 15
scaleFrom: 0.65
scaleTo: 4
alpha: 0.45
drawUnderUnits: false
hSpeed: 0.6
xSpeedAbsolute: -0.2
hOffsetRandom: 0.15
yOffsetRelative: -2
atmospheric: true
dirOffsetRandom: 180
shadow: true
xOffsetRelativeRandom: 1

yOffsetRelativeRandom: 1
xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1
[arm_1]
x: 0
y: -130
image_end:阴影.png
image_end_teamColors: true
#drawOverBody: true
[arm_2]
x: -58
y: -29
image_end:ROOT:/创世纪军事集团/建筑特效/冲压机.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_3]
x: -58
y: -46
image_end:ROOT:/创世纪军事集团/建筑特效/冲压机.png
image_end_teamColors: true
hidden: if self.hp<self.maxHp * 0.36
drawOverBody: true
[arm_4]
x: -58
y: -63
image_end:ROOT:/创世纪军事集团/建筑特效/冲压机.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_5]
x: 0
y: 0
image_end:遮盖.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_6]
x: -67
y: 78
image_end:ROOT:/创世纪军事集团/建筑特效/起重机.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_7]
x: 73
y: 77
image_end:ROOT:/创世纪军事集团/建筑特效/扇叶.png
image_end_teamColors: true
#drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
spinRate:7
[arm_8]
x: 0
y: 0
image_end:ROOT:/创世纪军事集团/建筑特效/遮盖1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_9]
x: 3.5
y: -170
image_end:ROOT:/创世纪军事集团/建筑特效/水下.png
image_end_teamColors: true
#drawOverBody: true
[arm_10]
x: 3
y: 0
image_end:白光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_11]
x: 0
y: 0
image_end:紫光.png
#image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_12]
x: 0
y: 0
image_end:损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[animation_2]
onActions: idle
arm2_0s: {x:0, y:0}
arm3_0s: {x:0, y:0}
arm4_0s: {x:0, y:0}
arm6_0s: {x:0, y:0}

arm2_2s: {x:0, y:0}
arm3_2s: {x:0, y:0}
arm4_2s: {x:-15, y:0}

arm2_4s: {x:0, y:0}
arm3_4s: {x:-15, y:0}
arm4_4s: {x:-15, y:0}

arm2_6s: {x:-15, y:0}
arm3_6s: {x:-15, y:0}
arm6_6s: {x:52, y:0}
arm4_6s: {x:-15, y:0}

arm2_8s: {x:-15, y:0}
arm3_8s: {x:-15, y:0}
arm4_8s: {x:0, y:0}

arm2_10s: {x:-15, y:0}
arm3_10s: {x:0, y:0}
arm4_10s: {x:0, y:0}

arm2_12s: {x:0, y:0}
arm3_12s: {x:0, y:0}
arm4_12s: {x:0, y:0}
arm6_12s: {x:0, y:0}
arm11_0s: {alpha:0}
arm11_3s: {alpha:1}
arm11_6s: {alpha:0}
arm11_9s: {alpha:1}
arm11_12s: {alpha:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:55
yOffsetRelativeRandom:120
delayedStartTimerRandom:30
[movement]
movementType: WATER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.07
maxEachBase: 15
maxGlobal: 50


