[core]
name: 赫斯提亚锻炉
displayText: Кузница Гестии
selfRegenRate: 1
price: 12500,钍=175
maxHp: 100000
armour: 135
footprint: -8,-3,8,11
constructionFootprint: -8,-3,8,11
displayDescription:【Уровень t4】【Сверхтяжёлый юнит】【Здание】【Наземный юнит】\n-Тактическое назначение：суперюнитпроизводствосооружение，без вооружения。\n-не может строиться на воде。-随着наука的повышает，обычный的工厂已无法满足высокотехнологичныйюнит的производство需求，\n-于是Генезисразрабатывать团队производить出了一видоснащённый了большое количествогигантскийстроитьмашина构的супер工程--Кузница Гестии，\n-这видсупер工厂можетпроизводить重 火炮，дрон指挥单元，передовой复合броня等一系列Генезисброня巨兽所нуждается的东西，\n-在黑暗的纷争时代，这些怪物们может碾碎任何胆敢около阻挡они的враг。
tags: 地面,建筑,极端重型
unitsSpawnedOnDeath:建筑损毁*1
techLevel: 1
buildSpeed: 14s
#availableInDemo: true
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 110
isBio: false
isBuilding: true
effectOnDeath: CUSTOM:烟雾*8, CUSTOM:爆破*18,largeExplosion
exit_y: 180
exit_moveAwayAmount: 370
nanoFactorySpeed:1
canBuild_31_name: setRally
canBuild_31_pos: 0.1
canBuild_1_name:超坦克
canBuild_1_pos: 1

fogOfWarSightRange: 30
[canBuild_T40]
name:阿特拉斯级运输船
pos: 1
isVisible:true
isLocked: if self.isControlledByAI()
[action_煅炉增益]
autoTrigger:if self.globalTeamTags(includes='纳米煅炉') and not self.tags(includes= '煅炉保险')
isActive: false
isVisible: false
temporarilyAddTags:煅炉保险
setUnitStats: nanoFactorySpeed=1.3
[canBuild_T41]
name: 征服者
pos: 1
isVisible:true
isLocked: if not self.globalTeamTags(includes='材料技术4') or not self.globalTeamTags(includes='超导技术1')
isLockedMessage: Требуется улучшенное материаловедение和Сверхпроводимость1
[canBuild_T42]
name: 黑寡妇
pos: 1.1
isVisible:true
isLocked: if not self.globalTeamTags(includes='超导技术2') or not self.globalTeamTags(includes='裂变技术2') or not self.globalTeamTags(includes='材料技术3')
isLockedMessage: Требуется улучшенная сверхпроводимость，Технология деления2，а такжеМатериаловедение3
[canBuild_T43]
name: BFG核子巨炮
pos: 1.2
isVisible: true
isLocked: if not self.globalTeamTags(includes='同步轨道加速器') or numberOfUnitsInTeam(greaterThan=0, withTag='BFG')
isLockedMessage: тынуждается同步轨道加速устройство，或者已经иметьBFG
[canBuild_T44]
name: 黑寡妇之耀
pos: 1.3
isVisible: true
isLocked: if not self.globalTeamTags(includes='同步轨道加速器') or numberOfUnitsInTeam(greaterThan=0, withTag='黑寡妇之耀')
isLockedMessage: тынуждается同步轨道加速устройство，或者已经иметьСияние Чёрной Вдовы
[canBuild_T45]
name: 泰坦
pos: 1.4
isVisible: true
isLocked: if not self.globalTeamTags(includes='纳米煅炉') or numberOfUnitsInTeam(greaterThan=0, withTag='泰坦')
isLockedMessage: тынуждаетсямодульный纳米煅炉，或者已经иметьТитан。
[decal_转子]
image: 转子.png
total_frames: 14
frame: (self.customTimer * 30) % 14
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-129
yOffsetAbsolute:63
isVisible:if self.maxHp * 0.36 < self.hp


[decal_转子1]
image: 转子1.png
onlyWhileAlive:true
total_frames: 9
frame: (self.customTimer * 20) % 9
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-129
yOffsetAbsolute:47
isVisible:if self.maxHp * 0.36 < self.hp
[action_重]
text: 极端重 юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积夸张的юнит独有的характеристика，\n-иметь极端重 юнит标签的юнит将иметь如下属性，\n-иметь自愈способность，且自身护甲不低于100点，\n-无法被休克，но受до反重甲юнит伤害增益。

[graphics]
total_frames: 1
image: 夹层.png
image_back: 主体.png
image_wreak:死亡.png
image_shadow: 影子.png
#imageScale: 0.95

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 30
maxAttackRange: 9999
shootDelay: 0


[turret_火焰]
x: 140
y: 217
projectile: 13
shoot_flame: CUSTOM:烟雾2
delay: 20
invisible: true
size: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1
[effect_烟雾2]
createWhenZoomedOut: false
stripIndex: effects
frameIndex: 0
life: 300
fadeOut: true
attachedToUnit: false
color: #646464
fadeInTime: 15
scaleFrom: 0.65
scaleTo: 4
alpha: 0.7
drawUnderUnits: false
hSpeed: 0.6
xSpeedAbsolute: 0.2
hOffsetRandom: 0.15
yOffsetRelative: -2
atmospheric: true
dirOffsetRandom: 180
shadow: true
xOffsetRelativeRandom: 1

yOffsetRelativeRandom: 1
xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.3
scaleTo: 1.9
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:120
yOffsetRelativeRandom:200
delayedStartTimerRandom:30
[arm_1]
x: 0
y: -145
image_end:门.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_2]
x: 0
y: -145
image_end:门损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[arm_3]
x: 110
y: -80
image_end:货物1.png
image_end_teamColors: true
drawOverBody: true
[arm_4]
x: -76.5
y: 165
image_end:货物.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[arm_5]
x: -60.5
y: 165
image_end:货物.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[arm_6]
x: -44.5
y: 165
image_end:货物.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[arm_7]
x: 18
y: 154
image_end:吊车.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[arm_8]
x: 0
y: 0
image_end:遮盖.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_9]
x: 0
y: 0
image_end:损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[arm_10]
x: 108
y: 183.5
image_end:滑块.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[arm_11]
x: 74
y: 173.5
image_end:滑块.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_12]
x: 0
y: 0
image_end:灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[arm_13]
x: 0
y: 0
image_end:灯光1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 


[animation_1]
onActions: queuedUnits
blendIn: 1s
blendOut: 2s
onActionsQueuedUnitPlayAt: 0.8
arm1_0s: {x:0, y:185}
arm2_0s: {x:0, y:185}
[animation_2]
onActions: idle
#blendIn: 1s
#blendOut: 2s
#onActionsQueuedUnitPlayAt:0.7
#pingPong: true

arm3_0s: {x:0, y:0}
arm3_2s: {x:-36, y:40}
arm3_3s: {x:-36, y:0}
arm3_4s: {x:0, y:0}
arm3_5s: {x:-36, y:40}
arm3_6s: {x:-36, y:0}
arm3_7s: {x:0, y:0}

arm4_0s: {x:0, y:0}
arm5_0s: {x:0, y:0}
arm6_0s: {x:0, y:0}

arm4_2s: {x:0, y:12}
arm5_2s: {x:0, y:0}
arm6_2s: {x:0, y:0}

arm4_3s: {x:0, y:12}
arm5_3s: {x:0, y:12}
arm6_3s: {x:0, y:0}

arm4_4s: {x:0, y:12}
arm5_4s: {x:0, y:12}
arm6_4s: {x:0, y:12}

arm4_5s: {x:0, y:12}
arm5_5s: {x:0, y:12}
arm6_5s: {x:0, y:0}

arm4_6s: {x:0, y:12}
arm5_6s: {x:0, y:0}
arm6_6s: {x:0, y:0}

arm4_7s: {x:0, y:0}
arm5_7s: {x:0, y:0}
arm6_7s: {x:0, y:0}

arm7_0s: {x:0, y:0}
arm7_3.5s: {x:19, y:0}
arm7_7s: {x:0, y:0}

arm10_0s: {x:0, y:0}
arm10_3.5s: {x:-34, y:0}
arm10_7s: {x:0, y:0}

arm11_0s: {x:0, y:0}
arm11_3.5s: {x:34, y:0}
arm11_7s: {x:0, y:0}

arm12_0s: {alpha:0.0}
arm12_3.5s: {alpha:1}
arm12_7s: {alpha:0}

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[ai]
buildPriority: 0.16
ai_upgradePriority: 0.1
maxEachBase: 2
maxGlobal: 2
noneGlobalExtraPriority:0.5


