


[core]
name: air中介1
displayText: airв посредник1
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
# showInEditor: false
tags: 飞机目标
canNotBeDamaged: true
showInEditor: false
canOnlyBeAttackedByUnitsWithTags: 灰机
isUnrepairableUnit: true
isUnselectable: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true

disableDeathOnZeroHp: true
# stayNeutral: true
# createNeutral: true
createOnAggressiveTeam: true
# 创建为敌对中立

maxTransportingUnits: 1
transportUnitsRequireMovementType: AIR
transportUnitsRequireTag: 飞机目标
transportUnitsBlockOtherTransports: false


[hiddenAction_爆炸]
autoTrigger: if parent == nullUnit and not self.hasFlag(id = 0)
# 脱离母体，启动自杀
addResources: setFlag= 0
resetCustomTimer: true


[hiddenAction_爆炸1]
autoTrigger: if parent == nullUnit and self.hasFlag(id = 0) and self.customTimer > 90 or not self.isInMap


[attachment_位置1]
x: 0
y: 0
addTransportedUnits: true
canBeAttackedAndDamaged: true


[graphics]
image: SHARED:blank.png
isVisible: false


[attack]
canAttack: false
# maxAttackRange: 3


[hiddenAction_删除]
autoTrigger: if self.ammo(greaterThan= 9.5) or self.numberOfAttachedUnits(greaterThan= 0.5)
# 被灰机攻击了就自杀 或 自己是传送门。
attachments_unload: true
# 卸下附属。
deleteSelf: true


[movement]
movementType: AIR
moveSpeed: 0
moveAccelerationSpeed: 0
maxTurnSpeed: 0
targetHeight: 0

targetHeightDrift: 0


