

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=150,ry= ${ryxq}
[action_拆除哇袄]
addResources: 威胁点数=-150
[attachment_位置1]
x: 0
y: 0
addTransportedUnits: true
# canBeAttackedAndDamaged: true
# 解决轨道中心被打问题，应该没bug


[hiddenAction_创造]
autoTrigger: if self.numberOfAttachedUnits(withTag= "飞机目标", lessThan= 0.5)
addUnitsIntoTransport: air中介1
# 让灰机瞄准用的中介


[action_刷灰机]
text: 战术核打击
description: -呼叫一架影袭轰炸机从近地轨道进入大气层，\n-对指定目标发射一枚反物质导弹，进行战术打击。\n-战术打击将对范围200内的敌人最高造成12000点能源伤害。\n-由于影袭轰炸机配备长效克莱因瓶屏蔽所有索敌系统，因此无法被攻击。\n-但导弹依然可以被反导系统拦截。
onlyOneUnitAtATime: true
isActive: if self.numberOfAttachedUnits(withTag= "飞机目标", greaterThan= 0.5)
# 没中介时不能用

allowMultipleInQueue: false
# 允许多次点击此行为形成队列，false时则只能点一次，不能累加。
spawnUnits: 影袭轰炸机(offsetHeight= 2000)
# 在2000高度刷灰机
fireTurretXAtGround: 瞄准用

fireTurretXAtGround_withProjectile: 空
# 空炮弹
alsoTriggerAction: 瞄准坐标
# 将中介传送过去
iconImage: 轰炸.png

price: energy=3
highPriorityQueue: true
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[hiddenAction_瞄准坐标]
fireTurretXAtGround: 瞄准用


[turret_瞄准用]
x: 0
y: 0
projectile: 瞄准
limitingRange: 99999
limitingMinRange: 800

canAttack: false
invisible: true


[projectile_瞄准]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: air中介1(gridAlign= true, transportedUnitsToTransfer= 1)
# 传送中介，其实类似传送基站，只是要传送的单位和传送门是一个单位，然后在中介里自动把传送门关了。
# 主要另一个代码有bug，不能用瞬间命中，但不用瞬间命中打不了太远，只能这么写。
explodeEffect: none

explodeEffectOnShield: none


[projectile_空]
# 空炮弹
life: 0
speed: 0
deflectionPower: -1
directDamage: 0

invisible: true
explodeEffect: none
explodeEffectOnShield: none


[core]
name: 余辉轨道通讯系统
class: CustomUnitMetadata
price: 7500,ry= ${ryxq}
@global ryxq:30
reclaimPrice: ry= ${ryxq}
nanoRange: 99999
maxHp: 7000

tags: 地面,轨道系统,建筑,无人单位
techLevel: 1
buildSpeed: 3s
isBio: false
maxShield: 7000

shieldRegen: 0.05
isBuilding: true
numBitsOnDeath: 14
footprint: -4,1,4,5
showInEditor: false

maxTransportingUnits: 1
transportUnitsRequireTag: 飞机目标
transportUnitsAddUnloadOption: false
constructionFootprint: -4,1,4,5
radius: 70

copyFrom: ROOT:/通用特效/单位防护.ini
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
armour: 12
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 73

energyMax: 12
energyRegen: 0
energyNeedsToRechargeToFull: false
energyStartingPercentage: 0
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[action_0_补充能量]
price: 3000,蓝晶=300
text: 补充能量
buildSpeed: 27s
pos: 0.2
isActive: if self.energyIncludingQueued(lessThan=12)

addResources: energy=2
#allowMultipleInQueue: false
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)



[action_空投]
text: 小型空投仓
allowMultipleInQueue: false
description: -近地轨道舰队将发射一个小规模容量的空投仓支援地面，\n-该空投含有一个预兆和一个冲击波。
iconImage: 小空投.png
onlyOneUnitAtATime: true

price: energy=2.5
highPriorityQueue: true
fireTurretXAtGround: 小空投
fireTurretXAtGround_onlyOverPassableTileOf: BUILDING
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_空投1]
text: 中型空投仓
allowMultipleInQueue: false
description: -近地轨道舰队将发射一个中等规模容量的空投仓支援地面，\n-该空投根据是否持有泽塔诺亚蓝图数据库2，皇家舰队作战学说2，乌托米尔原子刻蚀技术2，\n-来产生SDAF咆哮者+SDAF预兆，SDAF阿吉里恩，SDAF浩劫，\n-并附带一台SDAF冲击波，若没有上述科技则产生SDAF预兆和SDAF冲击波各两台，\n-如果同时持有多个科技，则按照优先产生最强的单位，浩劫＞阿吉里恩＞咆哮者。
iconImage: 中空投.png
onlyOneUnitAtATime: true

price: energy=7.5
highPriorityQueue: true
fireTurretXAtGround: 中空投
fireTurretXAtGround_onlyOverPassableTileOf: BUILDING
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_雷达]
text: 雷达扫描
#guiBuildUnit: 小型空投仓空投
#alsoTriggerAction: 小型空投仓
allowMultipleInQueue: false
description: -命令近地轨道舰队对地面进行扫描，\n-将对目标区域获取5.5秒的有效视野。\n-如果离雷达中心足够进，则可以使对方隐形单位失效。

iconImage: 雷达.png
onlyOneUnitAtATime: true
price: energy=1
fireTurretXAtGround: 雷达
isVisible: true

highPriorityQueue: true
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[graphics]
total_frames: 7
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
image_back: SHARED:blank.png

shadowOffsetX: 3
shadowOffsetY: 3
image_shield: 护盾.png
showTransportBar: false


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 99999

turretSize: 0
turretTurnSpeed: 50


[turret_小空投]
x: 0
y: 0
projectile: 小空投
limitingRange: 99999
limitingMinRange: 300

canAttack: false
invisible: true


[turret_中空投]
x: 0
y: 0
projectile: 中空投
limitingRange: 99999
limitingMinRange: 300

canAttack: false
invisible: true


[turret_雷达]
x: 0
y: 0
projectile: 雷达
limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true
shoot_sound: ROOT:/通用特效/扫描.ogg
shoot_sound_vol: 1


[projectile_小空投]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 小型空投仓空投(gridAlign= true,offsetHeight= 2000)
# 传送中介，其实类似传送基站，只是要传送的单位和传送门是一个单位，然后在中介里自动把传送门关了。
# 主要另一个代码有bug，不能用瞬间命中，但不用瞬间命中打不了太远，只能这么写。
explodeEffect: none

explodeEffectOnShield: none


[projectile_中空投]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 中型空投仓空投(gridAlign= true,offsetHeight= 2000)
# 传送中介，其实类似传送基站，只是要传送的单位和传送门是一个单位，然后在中介里自动把传送门关了。
# 主要另一个代码有bug，不能用瞬间命中，但不用瞬间命中打不了太远，只能这么写。
explodeEffect: none

explodeEffectOnShield: none


[projectile_雷达]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 雷达
explodeEffect: none
explodeEffectOnShield: none


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true




[arm_2]
x: 0
y: 30
image_end_teamColors: false
image_end: 块.png
drawOverBody: true


[animation_1]
onActions: idle
blendIn: 10s
blendOut: 10s
arm2_0s: {x:0,y:0}
arm2_0.5s: {x:0,y:2}

arm2_4.0s: {x:0,y:10}
arm2_4.5s: {x:0,y:12}
arm2_5.0s: {x:0,y:10}
arm2_8.5s: {x:0,y:2}
arm2_9.5s: {x:0,y:0}

body_0s: {frame:0}
body_0.5s: {frame:6}
body_1.0s: {frame:0}
body_1.5s: {frame:6}
body_2.0s: {frame:0}

body_2.5s: {frame:6}
body_3.0s: {frame:0}
body_3.5s: {frame:6}
body_4.0s: {frame:0}
body_4.5s: {frame:6}

body_5.0s: {frame:0}
body_5.5s: {frame:6}
body_6.0s: {frame:0}
body_6.5s: {frame:6}
body_7.0s: {frame:0}

body_7.5s: {frame:6}
body_8.0s: {frame:0}
body_8.5s: {frame:6}
body_9.0s: {frame:0}
body_9.5s: {frame:6}

body_10.0s: {frame:0}

[ai]
buildPriority: 0.01
ai_upgradePriority: 0.07
maxEachBase: 1
maxGlobal: 2
upgradedFrom: 余辉轨道通讯系统空投
