
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 创世纪锻造厂
displayText: Кузница Генезиса
displayDescription: 【Уровень t3】【Здание】【Механический юнит】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение:специальный资源производствосооружение/资源转换сооружение，без вооружения。Кузница负责будетРуда тория打наносит裂变燃料棒，\n-одновременнотакжеможетгибкий будет钍выполнятьпродать弥补обычный资源 недостаточно。
class: CustomUnitMetadata
price: 2000,bj= ${bjxq}
@global bjxq: 30
reclaimPrice: bj= ${bjxq}
maxHp: 10000

techLevel: 1
buildSpeed: 20s
isBio: false
isBuilding: true
radius: 45
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 锻造厂,地面,建筑
armour: 15
footprint: -3,-1,3,3
constructionFootprint: -3,-1,3,3
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_地板]
image: 冶炼地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-25
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
[decal_影子]
image: SHADOW:冶炼.png
total_frames: 1
layer: shadow
yOffsetRelative:2
xOffsetRelative:4
onlyWhileAlive:true
isVisible:true
alpha:0.5
[decal_支撑]
image:水下.png
total_frames: 1
layer: shadow
yOffsetRelative:-66
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.isOverLiquid
alpha:1
[decal_遮盖]
image:冶炼遮盖.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
[decal_损坏]
image:损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
[decal_转子]
image: 动画.png
total_frames: 13
frame: (self.customTimer * 20) % 13
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:43.5
yOffsetRelative:-2.5
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp

[decal_柱猪]
image:储存.png
total_frames: 1
layer: onTop
teamColors: true
isVisible: if self.resource.钍>1000
yOffsetRelative:-15
xOffsetRelative:37
onlyWhileAlive:true

[decal_柱猪1]
image:储存.png
total_frames: 1
layer: onTop
teamColors: true
isVisible: if self.resource.钍>800
yOffsetRelative:-15
xOffsetRelative:48
onlyWhileAlive:true

[decal_柱猪2]
image:储存.png
total_frames: 1
layer: onTop
teamColors: true
isVisible: if self.resource.钍>150
yOffsetRelative:-15
xOffsetRelative:59
onlyWhileAlive:true

[decal_柱猪3]
image:储存.png
total_frames: 1
layer: onTop
teamColors: true
isVisible: if self.resource.钍>300
yOffsetRelative:-29
xOffsetRelative:37
onlyWhileAlive:true

[decal_柱猪4]
image:储存.png
total_frames: 1
layer: onTop
teamColors: true
isVisible: if self.resource.钍>600
yOffsetRelative:-29
xOffsetRelative:48
onlyWhileAlive:true

[decal_柱猪5]
image:储存.png
total_frames: 1
layer: onTop
teamColors: true
isVisible: if self.resource.钍>0
yOffsetRelative:-29
xOffsetRelative:59
onlyWhileAlive:true

[action_普通冶炼]
text: 钍 обычный冶炼
description: противРуда ториявыполнятьобычный规加工，\n-этотбудет产выходить60юнит 钍。
buildSpeed: 7s
price: 500,钍原石=500
isVisible: true
addResources: 钍=60
ai_isHighPriority: true
iconImage: 冶炼a.png
pos: 0.1
[action_精矿提纯]
text: 钍 точный矿提纯
description: противРуда ториявыполнять深加工，\n-этотбудет产выходить100юнит 钍。
buildSpeed: 15s
price: 600,钍原石=500
isLocked: if not self.globalTeamTags(includes='精炼技术1')
isLockedMessage: Требуется технология очистки 1
iconImage: 冶炼1.png
addResources: 钍=100
ai_isHighPriority: true
pos: 0.2
[action_精华萃取]
text: 钍 точный华萃取
description: противРуда ториявыполнятьточный细化冶炼，\n-с消耗большое количествовремяв качествецена产выходитьбольшое количество 钍。\n-этотбудет产выходить300юнит 钍
buildSpeed: 45s
price: 600,钍原石=500
isLocked: if not self.globalTeamTags(includes='精炼技术2')
isLockedMessage: Требуется технология очистки 2
iconImage: 冶炼3.png
addResources: 钍=300
ai_isHighPriority: true
pos: 0.3

[action_钍原石出售]
text: Руда торияпродать
description: 卖掉1000Руда тория，\n-этотбудетполучить1000资源。
buildSpeed: 6s
price: 钍原石=1000
isVisible: if not self.globalTeamTags(includes='精炼技术2')
pos: 0.4
addResources: 1000
iconImage: 卖矿.png

[action_钍原石出售1]
text: Руда торияпродать
description: 卖掉1000Руда тория，\n-этотбудетполучить2000资源。
buildSpeed: 2s
price: 钍原石=1000
isVisible: if self.globalTeamTags(includes='精炼技术2')
pos: 0.5
addResources: 2000
iconImage: 卖矿.png

[action_钍出售]
text: 钍продать
description: 卖掉100钍，\n-этотбудетполучить1750资源
buildSpeed: 4s
price: 钍=100
isVisible: if not self.globalTeamTags(includes='精炼技术2')
addResources: 1750
iconImage: 卖钍.png

[action_钍出售1]
text: 钍продать
description: 卖掉100钍，\n-этотбудетполучить3600资源
buildSpeed: 3s
price: 钍=100
isVisible: if self.globalTeamTags(includes='精炼技术2')
iconImage: 卖钍.png
addResources: 2400

[graphics]
total_frames: 1
image: 冶炼.png
image_wreak: 死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: NONE


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
turretTurnSpeed: 50

[arm_1]
x: 26.5
y: 15
image_end: 柱.png
image_end_teamColors: false
drawOverBody: true

[arm_2]
x: 37.5
y: 15
image_end: 柱.png
image_end_teamColors: false
drawOverBody: true

[arm_3]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: false
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[animation_idle]
onActions : idle
arm1_0s: {y:0}
arm2_0s: {y:0}
arm3_0s: {alpha:0}

arm1_0.3s: {y:-10}
arm2_0.3s: {y:0}
arm3_0.3s: {alpha:0.5}

arm1_0.6s: {y:0}
arm2_0.6s: {y:-10}
arm3_0.6s: {alpha:1}

arm1_0.9s: {y:-10}
arm2_0.9s: {y:0}
arm3_0.9s: {alpha:0.5}

arm1_1.2s: {y:0}
arm2_1.2s: {y:-10}
arm3_1.2s: {alpha:0}
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
noneGlobalExtraPriority: 0.2
maxEachBase: 4
maxGlobal: 20


