


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=900


[core]
name: SDSF灾厄级巡洋舰1
displayText: SDSFкрейсер класса «Бедствие»1
displayDescription: -крейсер класса «Бедствие»это Древние Людиисторияна номеродиншт (для судов)использоватьиспользует нулевая точкаможет реактор сначалавкрейсер, \n-в Аравелидпоздний период, Этот приказчеловекжизньстрах тяжёлыйкрейсерструктурастать Империя Нова основная силафлот.\n-крейсер класса «Бедствие»это имявспомогательныйего реальный гигантскийбольшой объект, сильныйсила реакториспользовать онможет оснащёнимеет масштабвоздушныйперед  оружие и защитаединица, \n-его оснащёнимеет плазмаосадапушкаможет производствоуничтожение Опустошительполностьюуничтожитьвраги.\n-то естьиспользоватьв Империя Новастроитьстранапозади , бедствиеуровеньболее сначалав аберодолетьлаффуровенькрейсервзятьэра, а отступлениепроживатьдвалиния.\n-но это одинподобный флотпо-прежнемупротив этотклинокоружиене входит  гигантскийбольшой объектпучокруканет стратегия, то естьиспользоватьэто сейчаснебо, бедствиеуровеньпо-прежнемуможет взрыввыпуститьвыходит удивлятьчеловек мощь.\n-по земле и воздуху, взрыв ракеты, другие может источник.
class: CustomUnitMetadata
maxShield: 16000

shieldRegen: 0.1
price: 15000, 蓝晶= 2100
maxHp: 15000
shieldDisplayOnlyDeflection: true
techLevel: 2

buildSpeed: 50s
availableInDemo: true
showInEditor: false
radius: 85
shieldRenderRadius: 70

displayRadius: 85
isBio: false
energyMax: 10
energyRegen: 0
#transportSlotsNeeded: 20

effectOnDeathGroundCollision: CUSTOM:爆炸x*1
tags: 飞机,高空,反高空,灾厄,无人单位
canOnlyBeAttackedByUnitsWithTags:反高空
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 灾厄

softCollisionOnAll: 20
armour: 70
fogOfWarSightRange: 33

copyFrom: ROOT:/通用特效/单位防护.ini

[action_高空]
text: высотный юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: место к крайневысокий высокий степень истребитель и военный корабль.\n-в этовысокий степеньпод , толькоимеет   и воздушныйв особый антивысотный юнит,  и высотный юниттолько тогдаможет атакак этотюнит, \n-одновременно, большой частьвысотный юнитможет взаимноатака, и может атакаобычныйвоздушныйв юнит, \n-толькоимеет особый высотный юниттолько тогдаможет по землеатака.
[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_x]
displayType: action
price: 0
buildSpeed: 1.5s
isVisible: true
#playSoundAtUnit: 部署.ogg

text: убратьглавное орудие
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署1
#isLocked: if self.isAttacking()
canPlayerCancel: false

addResources: unsetFlag= 1
description: главныйдвижениеубратьглавное орудие, использоватьиспользует вспомогательныйпушкавыполняетатака.
convertTo: SDSF灾厄级巡洋舰
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_b]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
autoTrigger: if self.energy(empty=true)

alsoQueueAction: a


[action_a]
convertTo: SDSF灾厄级巡洋舰
displayType: action
price: 0
buildSpeed: 1.5s
isVisible: false

addResources: unsetFlag= 1
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署1


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
#lock_body_rotation_with_main_turret:true

teamColorsOnTurret: true
image_shadow: AUTO
shadowOffsetX: 0
shadowOffsetY: 0
image_shield: 护盾.png

turretImageScale: 0.7
movementEffect: CUSTOM:火3
movementEffectRate: 1.5
lock_body_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: if not self.queueSize(greaterThan= 0.5)
canAttackLandUnits: if not self.queueSize(greaterThan= 0.5)
canAttackUnderwaterUnits: false
#disablePassiveTargeting:true

turretSize: 19
turretTurnSpeed: 0.85
#turretMultiTargeting: true
maxAttackRange: 800
shootDelay: 0

isFixedFiring: true


[turret_271]
x: 0
y: 0
invisible: true
canShoot: false


[turret_234]
x: 0
y: 48
canShoot: true
invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/大主炮音效.ogg

shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾a*8,CUSTOM:粒子1*13,CUSTOM:冲击波y
shoot_light: #FFccCCEE
projectile: 1
warmup: 30

chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
delay: 200
energyUsage: 10
attachedTo: 271
slave: true
canOnlyAttackUnitsWithTags:高空
warmupStartEffect: CUSTOM:粒子*3

[turret_256]
x: 0
y: 48
canShoot: true
invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/大主炮音效.ogg

shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾a*8,CUSTOM:粒子1*13,CUSTOM:冲击波y
shoot_light: #FFccCCEE
projectile: 2
warmup: 30

chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
delay: 200
energyUsage: 10
attachedTo: 271
slave: true
canOnlyAttackUnitsWithoutTags:高空
warmupStartEffect: CUSTOM:粒子*3

[turret_9]
x: -18
y: -115.5
#limitingRange:440
canShoot: false
image: 导弹.png

limitingAngle: 0
limitingMinRange: 180
canAttackLandUnits: false
attachedTo: 271
slave: true

size: 0
canAttackMaxAngle: 181
idleDir: -90
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 100
turnSpeed: 0
#warmup:10
delay: 100


[turret_10]
x: -18
y: -111.5
#limitingRange:440
canShoot: false
image: 导弹.png

limitingAngle: 0
limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181

attachedTo: 271
slave: true
idleDir: -90
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 100
turnSpeed: 0
warmup: 5
delay: 100


[turret_11]
x: -18
y: -107.5
#limitingRange:440
canShoot: false
image: 导弹.png

limitingAngle: 0
attachedTo: 271
slave: true
shoot_light: #FFEECCCC
limitingMinRange: 180

canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: -90
recoilOffset: -30

recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
warmup: 10
delay: 100


[turret_12]
x: 18
y: -115.5
#limitingRange:440
attachedTo: 271
slave: true

canShoot: false
image: 导弹.png
limitingAngle: 0
limitingMinRange: 180
canAttackLandUnits: false

size: 0
canAttackMaxAngle: 181
idleDir: 90
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 100
turnSpeed: 0
#warmup:10
delay: 100


[turret_13]
x: 18
y: -111.5
#limitingRange:440
attachedTo: 271
slave: true

canShoot: false
image: 导弹.png
limitingAngle: 0
limitingMinRange: 180
canAttackLandUnits: false

size: 0
canAttackMaxAngle: 181
idleDir: 90
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 100
turnSpeed: 0
warmup: 5
delay: 100


[turret_14]
x: 18
y: -107.5
#limitingRange:440
canShoot: false
attachedTo: 271

slave: true
image: 导弹.png
limitingAngle: 0
limitingMinRange: 180
canAttackLandUnits: false

size: 0
canAttackMaxAngle: 181
idleDir: 90
recoilOffset: -30
recoilOutTime: 4

recoilReturnTime: 100
turnSpeed: 0
warmup: 10
delay: 100


[projectile_1]
@copyFromSection: template_能源
areaDamage: 11000
areaRadius: 160
life: 300
lightSize: 1

largeHitEffect: true
speed: 7
#targetGround:true
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1
drawSize: 1

explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:电球,CUSTOM:粒子1*25
explodeEffect: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:电球,CUSTOM:粒子1*25
image: ROOT:/余辉军团/单位特效/星星.png
deflectionPower: -1
trailEffectRate: 2

areaRadiusFromEdge: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
buildingDamageMultiplier: 1.5


[projectile_2]
@copyFromSection: template_能源
areaDamage: 13000
areaRadius: 160
life: 300
lightSize: 1

largeHitEffect: true
speed: 7
#targetGround:true
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1
drawSize: 1

explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:电球,CUSTOM:粒子1*25
explodeEffect: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:电球,CUSTOM:粒子1*25
image: ROOT:/余辉军团/单位特效/星星.png
deflectionPower: -1
trailEffectRate: 2

areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
buildingDamageMultiplier: 1.5
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 1.5
mutator7_areaDamageMultiplier: 1.5
[effect_粒子]
life: 60
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 2
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_爆炸x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/余辉军团/单位特效/爆炸25.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_火3]
life: 55
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 1.5
image: ROOT:/通用特效/蓝火.png
alpha: 0.65
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 0
yOffsetRelative	: -150


[effect_烟雾a]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 55
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.5
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.5

ySpeedRelative: 1
atmospheric: true


[effect_粒子1]
spawnChance: 1
createWhenZoomedOut: false
life: 55
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom: 0.1
scaleTo: 0.38

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 4.3

ySpeedRelativeRandom: 4.3


[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 1
scaleTo: 1
alpha: 1

drawUnderUnits: true


[effect_尾巴1]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 30
fadeOut: true
attachedToUnit: false

fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.7
alpha: 0.8
drawUnderUnits: false

yOffsetRelative	: -5


[arm_1]
x: -42
y: 5
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:左翼.png


[arm_2]
x: 42
y: 5
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:右翼.png


[arm_3]
x: 37
y: 29.5
image_end: 右大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: -37
y: 29.5
image_end: 左大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: -37
y: 61.5
image_end: 左大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_6]
x: 37
y: 61.5
image_end: 右大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_7]
x: -28
y: -17
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_8]
x: 28
y: -17
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_9]
x: -39
y: 88
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_10]
x: 39
y: 88
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_11]
x: 0
y: 0
image_end: 前盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_12]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[effect_底色]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩.png
life: 140
fadeOut: true
attachedToUnit: false

scaleFrom: 1.2
scaleTo: 1.2
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 3.3
scaleTo: 3.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 8
scaleTo: 8

drawUnderUnits: true
atmospheric: false


[effect_电球]
priority: critical
attachedToUnit: false
scaleFrom: 1.1
scaleTo: 1.1
image: ROOT:/余辉军团/单位特效/电球1.png

total_frames: 5
animateFrameStart: 0
animateFrameEnd: 4
animateFramePingPong: true
animateFrameSpeed: 0.2

life: 300
alwayStartDirAtZero: true


[effect_冲击波1]
life: 130
priority: critical
attachedToUnit: false
scaleFrom: 1.1
scaleTo: 2.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.7
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_冲击波y]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 85
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 1.3
alpha: 1
drawUnderUnits: false
atmospheric: true


[animation_1]
onActions: idle
blendIn: 0.3s
blendOut: 0.3s
body_0s: {frame:0}
body_0.3s: {frame:2}


[animation_部署1]
arm1_1.5s: {x:-23, y:15}
arm2_1.5s: {x:23, y:15}
arm11_1.5s: {x:0, y:51}


[movement]
movementType: AIR
moveSpeed: 1
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.02
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 1.2
turnAcceleration: 0.08
targetHeightDrift: 0.3

slowDeathFall: true
targetHeight: 140


[ai]
buildPriority: 0.9


