


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=900


[core]
name: SDSF灾厄级巡洋舰
displayText: SDSFкрейсер класса «Бедствие»
displayDescription: -крейсер класса «Бедствие»это Древние Людиисторияна номеродин艘использоватьиспользует нулевая точкаможет реактор сначалавкрейсер, \n-в Аравелидпоздний период, Этот приказчеловекжизньстрах тяжёлыйкрейсерструктурастать Империя Нова основная силафлот.\n-крейсер класса «Бедствие»это имявспомогательныйего реальный гигантскийбольшой объект, сильный劲 реакториспользовать онможет оснащёнимеет масштабвоздушныйперед  оружие и защитаединица, \n-его оснащёнимеет плазмаосадапушкаможет производствоуничтожение Опустошительполностьюуничтожитьвраги.\n-то естьиспользоватьв Империя Новастроитьстранапозади , бедствиеуровеньболее сначалав 阿伯克拉佛уровенькрейсервзятьэра, а отступление居двалиния.\n-но это одинподобный флотпо-прежнемупротив этот刀оружиене входит  гигантскийбольшой объектпучокруканет 策, то естьиспользоватьэто сейчаснебо, бедствиеуровеньпо-прежнемуможет взрыввыпуститьвыходит удивлятьчеловек мощь.\n-по земле и воздуху, взрыв ракеты, другие может источник.
class: CustomUnitMetadata
maxShield: 16000
shieldRegen: 0.1

price: 15000, 蓝晶= 2100
maxHp: 15000
shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 80s

availableInDemo: true
radius: 85
shieldRenderRadius: 70


displayRadius: 85
isBio: false
#transportSlotsNeeded: 20
effectOnDeathGroundCollision: CUSTOM:爆炸x*1
tags: 飞机,高空,反高空,灾厄,无人单位
canOnlyBeAttackedByUnitsWithTags:反高空
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 灾厄
softCollisionOnAll: 20
armour: 70
fogOfWarSightRange: 33
energyMax: 10
energyRegen: 0.004

copyFrom: ROOT:/通用特效/单位防护.ini

[action_高空]
text: высотный юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: место к крайневысокий высокий степень истребитель и военный корабль.\n-в этовысокий степеньпод , толькоимеет   и воздушныйв особый антивысотный юнит,  и высотный юниттолько тогдаможет атакак этотюнит, \n-одновременно, большой частьвысотный юнитможет взаимноатака, и может атакаобычныйвоздушныйв юнит, \n-толькоимеет особый высотный юниттолько тогдаможет по землеатака.
[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=885, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=885, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[action_x]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: true
#playSoundAtUnit: 部署.ogg

text: развернутьглавное орудие
whenBuilding_cannotMove: true
#whenBuilding_playAnimation: 部署1
isLocked: if not self.energy(full=true) or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
canPlayerCancel: false

description: развернутьвоенный корабльв часть плазмаосадапушкабомбардировкавраги, \n-против врагистроить стать AOEэнергетический урон.\n-но использоватьиспользует осадапушкабудетзапретиспользует всех другие оружие.
whenBuilding_triggerAction: b
convertTo: SDSF灾厄级巡洋舰1


[hiddenAction_b]
stopLastAnimation: true
playAnimation: 部署1


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 0
shadowOffsetY: 0
image_shield: 护盾.png
turretImageScale: 0.7

movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3
movementEffectRate: 1.5


[attack]
canAttack: true
canAttackFlyingUnits: if not self.queueSize(greaterThan= 0.5)
canAttackLandUnits: if not self.queueSize(greaterThan= 0.5)
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 700
shootDelay: 0


[turret_1]
x: 27
y: 29.5
image: 炮.png
canShoot: false
recoilOffset: -1

limitingAngle: 50
idleDir: 90
#canAttackFlyingUnits:false


[turret_2]
x: 0
y: 0
attachedTo: 1
slave: true
#limitingRange:650

invisible: true
shoot_flame: CUSTOM:烟雾a*2
projectile: 1
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup: 160

size: 10
delay: 20


[turret_3]
x: -4
y: -7
attachedTo: 1
shoot_flame: CUSTOM:烟雾a*2
#limitingRange:650

slave: true
invisible: true
projectile: 1
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup: 175

size: 10
delay: 20


[turret_4]
x: 4
y: -7
#limitingRange:650
attachedTo: 1
shoot_flame: CUSTOM:烟雾a*2

slave: true
invisible: true
projectile: 1
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup: 190

size: 10
delay: 20


[turret_5]
x: -27
y: 29.5
image: 炮.png
canShoot: false
recoilOffset: -1

limitingAngle: 50
idleDir: -90
#canAttackFlyingUnits:false


[turret_6]
x: 0
y: 0
attachedTo: 5
slave: true
#limitingRange:650

invisible: true
shoot_flame: CUSTOM:烟雾a*2
projectile: 1
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup: 160

size: 10
delay: 20


[turret_7]
x: -4
y: -7
attachedTo: 5
shoot_flame: CUSTOM:烟雾a*2
#limitingRange:650

slave: true
invisible: true
projectile: 1
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup: 175

size: 10
delay: 20


[turret_8]
x: 4
y: -7
#limitingRange:650
attachedTo: 5
shoot_flame: CUSTOM:烟雾a*2

slave: true
invisible: true
projectile: 1
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup: 190

size: 10
delay: 20


[turret_9]
x: -18
y: -115.5
#limitingRange:440
canShoot: true
image: 导弹.png

projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC

limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: -90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
#warmup:10
canOnlyAttackUnitsWithTags:高空
delay: 100


[turret_10]
x: -18
y: -111.5
#limitingRange:440
canShoot: true
image: 导弹.png

projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC

limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: -90
canOnlyAttackUnitsWithTags:高空
recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
warmup: 5

delay: 100


[turret_11]
x: -18
y: -107.5
#limitingRange:440
canShoot: true
image: 导弹.png
canOnlyAttackUnitsWithTags:高空
projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC

limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: -90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
warmup: 10

delay: 100


[turret_12]
x: 18
y: -115.5
#limitingRange:440
canShoot: true
image: 导弹.png
canOnlyAttackUnitsWithTags:高空
projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC

limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: 90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
#warmup:10

delay: 100


[turret_13]
x: 18
y: -111.5
#limitingRange:440
canShoot: true
image: 导弹.png
canOnlyAttackUnitsWithTags:高空
projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC

limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: 90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
warmup: 5

delay: 100


[turret_14]
x: 18
y: -107.5
#limitingRange:440
canShoot: true
image: 导弹.png
canOnlyAttackUnitsWithTags:高空
projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFEECCCC

limitingMinRange: 180
canAttackLandUnits: false
size: 0
canAttackMaxAngle: 181
idleDir: 90

recoilOffset: -30
recoilOutTime: 4
recoilReturnTime: 100
turnSpeed: 0
warmup: 10

delay: 100


[turret_15]
x: 24
y: 61
canShoot: true
image: 主炮.png
limitingAngle: 50

idleDir: 90
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFccCCEE
canAttackLandUnits:false
projectile: 4
delay: 20
recoilOffset: -1
canOnlyAttackUnitsWithTags:高空

[turret_16]
x: -24
y: 61
canShoot: true
image: 主炮.png
limitingAngle: 50

idleDir: -90
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾a*2
shoot_light: #FFccCCEE
canAttackLandUnits:false
projectile: 4
delay: 20
recoilOffset: -1
canOnlyAttackUnitsWithTags:高空

[turret_17]
x: -20
y: -17
#invisible: true
projectile: 5
delay: 2

shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/小激光.ogg
shoot_sound_vol: 0.4
limitingAngle: 50
canOnlyAttackUnitsWithTags:高空
size: 10
canAttackLandUnits: false
idleDir: -90
image: 枪.png


[turret_18]
x: 20
y: -17
#invisible: true
projectile: 5
delay: 2

shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/小激光.ogg
shoot_sound_vol: 0.4
limitingAngle: 50
canOnlyAttackUnitsWithTags:高空
size: 10
canAttackLandUnits: false
idleDir: 90
image: 枪.png


[turret_19]
x: 30
y: 88
#invisible: true
projectile: 6
delay: 7

shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.5
limitingAngle: 50

size: 10
canAttackFlyingUnits: false
idleDir: 90
image: 炮1.png
limitingRange: 550

[turret_20]
x: -30
y: 88
#invisible: true
projectile: 6
delay: 7

shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.5
limitingAngle: 50
limitingRange: 550
size: 10
canAttackFlyingUnits: false
idleDir: -90
image: 炮1.png


[projectile_1]
@copyFromSection: template_能源
directDamage: 1000
life: 10
instantReuseLast: true
beamImage: SHARED:beam3.png
beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true

laserEffect: true
color: #FF00B3FF
lightColor: #FF004AFF
lightSize: 0.1
explodeEffect: CUSTOM:底色,CUSTOM:闪光,CUSTOM:冲击波x,CUSTOM:聚变,CUSTOM:粒子*4

explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光,CUSTOM:冲击波x,CUSTOM:聚变,CUSTOM:粒子*4


[projectile_2]
directDamage: 0
frame: 1
life: 10
instantReuseLast: true
beamImage: SHARED:beam3.png

beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true

color: #FF00B3FF
lightColor: #FF004AFF
lightSize: 0.1


[projectile_3]
@copyFromSection: template_爆炸
directDamage: 170
life: 350
speed: 5
#deflectionPower:-1

lightSize: 1.5
lightColor: #FF39FFFF
drawSize: 0.9
targetSpeed: 8
turnSpeed: 5.2

trailEffect: true
image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:爆炸1,CUSTOM:闪光1,CUSTOM:聚变1
explodeEffectOnShield: CUSTOM:爆炸1,CUSTOM:闪光1,CUSTOM:聚变1
autoTargetingOnDeadTarget: true


[projectile_4]
@copyFromSection: template_能源
areaDamage: 150
areaRadius: 50
life: 100
speed: 9

image: ROOT:/余辉军团/单位特效/星星.png
drawSize: 0.75
lightSize: 1.5
lightColor: #FF00B3FF
explodeEffect: CUSTOM:爆炸1,CUSTOM:闪光1,CUSTOM:爆炸

explodeEffectOnShield: CUSTOM:爆炸1,CUSTOM:闪光1,CUSTOM:爆炸
trailEffect: CUSTOM:尾巴
trailEffectRate: 0.7
areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_5]
@copyFromSection: template_能源
directDamage: 35
life: 100
speed: 8
targetSpeed: 9

image: ROOT:/余辉军团/单位特效/长炮弹.png
deflectionPower: -1
drawSize: 0.55
lightSize: 0.6
lightColor: #FF00B3FF

explodeEffect: CUSTOM:爆炸2
explodeEffectOnShield: CUSTOM:爆炸2


[projectile_6]
@copyFromSection: template_能源
areaDamage: 70
areaRadius: 40
life: 100
speed: 7

image: ROOT:/余辉军团/单位特效/蓄能.png
drawSize: 1
lightSize: 1.5
lightColor: #FF00B3FF
explodeEffect: CUSTOM:波雷爆炸

explodeEffectOnShield: CUSTOM:波雷爆炸
#trailEffect:CUSTOM:尾巴
trailEffectRate: 0.7
areaRadiusFromEdge: true
targetGroundSpread: 40

targetGround: true


[effect_爆炸2]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/碎裂.png
total_frames: 8

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[effect_爆炸]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.35
image: ROOT:/余辉军团/单位特效/自制.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4

drawUnderUnits: true
atmospheric: false


[effect_闪光1]
#priority:critical
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: true
atmospheric: false


[effect_冲击波x]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.05
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_爆炸1]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1

scaleTo: 1
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_底色]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩.png
life: 70
fadeOut: true
attachedToUnit: false

scaleFrom: 0.37
scaleTo: 0.37
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.4
drawUnderUnits: false
atmospheric: true


[effect_聚变1]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.4
drawUnderUnits: false
atmospheric: true


[effect_爆炸x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/余辉军团/单位特效/爆炸25.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_火2]
life: 55
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 37
yOffsetRelative	: -3


[effect_火1]
life: 55
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: -37
yOffsetRelative	: -3


[effect_火3]
life: 55
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 1.5
image: ROOT:/通用特效/蓝火.png
alpha: 0.65
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 0
yOffsetRelative	: -150


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 55
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom: 0.1
scaleTo: 0.38

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 4.3

ySpeedRelativeRandom: 4.3
#atmospheric: true


[effect_烟雾a]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 55
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.5
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.5

ySpeedRelative: 1
atmospheric: true


[effect_波雷爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 2.4
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg

alpha: 2


[arm_1]
x: -65
y: 20
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:左翼.png


[arm_2]
x: 65
y: 20
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:右翼.png


[arm_3]
x: 37
y: 29.5
image_end: 右大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: -37
y: 29.5
image_end: 左大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: -37
y: 61.5
image_end: 左大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_6]
x: 37
y: 61.5
image_end: 右大.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_7]
x: -28
y: -17
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_8]
x: 28
y: -17
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_9]
x: -39
y: 88
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_10]
x: 39
y: 88
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_11]
x: 0
y: 51
image_end: 前盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_12]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[animation_部署1]
arm1_0.5s: {x:23, y:-15}
arm2_0.5s: {x:-23, y:-15}
arm11_0.5s: {x:0, y:-51}


[animation_1]
onActions: idle
blendIn: 0.3s
blendOut: 0.3s
body_0s: {frame:0}
body_0.3s: {frame:2}


[animation_attack]
blendIn: 1s
blendOut: 2s
arm3_1s: {x:-50, y:0}
arm3_950s: {x:-50, y:0}
arm4_1s: {x:50, y:0}

arm4_950s: {x:50, y:0}
arm5_1s: {x:40, y:0}
arm5_950s: {x:40, y:0}
arm6_1s: {x:-40, y:0}
arm6_950s: {x:-40, y:0}

arm7_1s: {x:50, y:0}
arm7_950s: {x:50, y:0}
arm8_1s: {x:-50, y:0}
arm8_950s: {x:-50, y:0}
arm9_1s: {x:-40, y:0}

arm9_950s: {x:-40, y:0}
arm10_1s: {x:40, y:0}
arm10_950s: {x:40, y:0}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm3_1s: {x:0, y:0}
arm4_1s: {x:0, y:0}
arm5_1s: {x:0, y:0}

arm6_1s: {x:0, y:0}
arm7_1s: {x:0, y:0}
arm8_1s: {x:0, y:0}
arm9_1s: {x:0, y:0}
arm10_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 1
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.02
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 0.85
turnAcceleration: 0.03
targetHeightDrift: 0.3

slowDeathFall: true
targetHeight: 140


[ai]
buildPriority: 0.9


