


[core]
name: 尖兵
displayText: Передовой
price: 2000,钍=28
maxHp: 5500
displayDescription: 【Уровень t4】【Механический юнит】【Наземный юнит】【тяжёлое укрытие】【Преодолевает утёсы】【Дальнее целеуказание】\n-Тактическое назначение:далеко程防空/противотанковыймех，размер юнита:4 вооружение：▲155毫米Зенитное орудиеX1 по земле и воздуху对высотный \n-взрывной урон 对极端重 юнит伤害加成 ▲自动手枪x1 только по земле кинетический урон\n-在与余辉началосражение中，манёвренность和защитные характеристики都堪忧的牵引式火炮总是ещё没开火就被余辉精准清除。\n-在完全失去制空权的情况下，这些традиционныйа又老旧的оснащение早已无法在与余辉的сражение中проявитьроль，\n-为了不浪费这些资源，Генезистолько好将довоенный留存的большое количество牵引式火炮当做Гладиатор的零вещь，\n-或者直接当做固定炮 использовать，однако随着мех技术的 展，\n-一款为использовать这些资源а量身定做的мех，为这些退役的牵引式火炮带来了新的转машина。\n-Передовоймехоснащён155毫米重炮，можетодновременно消灭вражеский地面或者空中вплоть до超высотныйюнит，\n-经过实战检测，几乎没有врагможет在Передовоймех的炮击下逃脱。

techLevel: 1
fogOfWarSightRange: 29
buildSpeed: 16s
radius: 31
displayRadius: 31
armour: 4
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 4
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,反高空,尖兵,免疫烟雾,重型掩体
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 尖兵
energyMax: 4
energyRegen: 0

energyNeedsToRechargeToFull: true
@memory 计时1: float



[hiddenAction_掩体1取消]
autoTrigger:if self.hasParent and self.tags(includes= '重型掩体')
isVisible:false
temporarilyRemoveTags:重型掩体
[hiddenAction_掩体1生成]
autoTrigger:if not self.hasParent and not self.tags(includes= '重型掩体')
isVisible:false
temporarilyAddTags:重型掩体


#——————————盾
[action_护盾]
text: 重 护盾已启用
isVisible:if self.maxHp * 0.36 < self.hp
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 9
iconImage: 护盾.png
description: Передовой无法использоватьукрытие，ноПередовойоснащённый了一面重 护盾为самобеспечиваетприкрытие。\n-当自身生命值高于未加成前的36%时，Передовой将持有重 护盾，\n-持有重 护盾时Передовой视为在тяжёлое укрытие保护下。
[hiddenAction_生效]
autoTrigger:if not self.tags(includes= '重型掩护') and self.maxHp * 0.36 < self.hp
temporarilyAddTags:重型掩护
[hiddenAction_失效]
autoTrigger:if self.tags(includes= '重型掩护') and self.hp<self.maxHp * 0.36
temporarilyRemoveTags:重型掩护
[action_变形]
displayType: action
price: 3500,钍=80
buildSpeed: 0s
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
text: модифицировать为MK2
isLocked: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.isOverLiquid
isVisible:if not self.tags(includes= '模块化改造') and self.globalTeamTags(includes='模块化技术')
alsoQueueAction: 变形1
descriptionAddFromUnit: 尖兵MK2
descriptionAddUnitStats: 尖兵MK2
temporarilyAddTags:模块化改造
iconImage: ROOT:/创世纪军事集团/单位特效/模块生产.png
setUnitStats: maxTurnSpeed = 0
[action_变形1]
convertTo:尖兵MK2
displayType: action
price: 0
buildSpeed: 20s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
convertTo_keepCurrentTags:true
temporarilyRemoveTags:模块化改造,重型掩护,↯
refundAllQueuedItems:true
setResourcesWithLogic: xk=0
#————————————改造

[decal_改造]
image:  ROOT:/创世纪军事集团/单位特效/左围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:10
xOffsetRelative:-37
onlyWhileAlive:true
[decal_改造1]
image:  ROOT:/创世纪军事集团/单位特效/右围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:10
xOffsetRelative:37
onlyWhileAlive:true
[decal_支架]
image:  ROOT:/创世纪军事集团/单位特效/吊臂.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:30
xOffsetRelative:-15
onlyWhileAlive:true
dirOffset:65

#———科技—————
[action_重型掩体]
text: тяжёлое укрытие
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处тяжёлое укрытие，может为рядом140范围内的биологический юнитобеспечиваеттяжёлое прикрытие。\n-тяжёлое прикрытиеможет为биологический юнит减免75%的伤害，\n-но，укрытие无法减免скорострельный，激光，Огонь，电击，中性，самоподрыв，ближний бой，衰解等其он无视укрытие的оружие。




[hiddenAction_手动档]
autoTriggerOnEvent: newWaypointGivenByPlayer
setUnitMemory: 计时1 = self.timeAlive + 9999
# 检索延迟15s


[hiddenAction_检索]
autoTrigger: if self.timeAlive > memory.计时1
clearAllWaypoints: true
takeResources_searchOnly: true
takeResources_includeUnitsWithinRange: ${attack.maxAttackRange}
# 检索范围

takeResources_excludeUnitsWithoutTags: 飞机,地面
takeResources_includeUnitsWithinRange_team: enemy
takeResources_includeUnitsInTransport: false
takeResources_includeParent: false
takeResources_triggerActionForEach: 自动索敌

setUnitMemory: 计时1 = self.timeAlive + 0.5
# 检索延迟1.5s


[hiddenAction_自动索敌]
requireConditional: if not thisActionTarget.hasParent and not thisActionTarget.tags(includes= '不检测') and (thisActionTarget.tags(includes= '被锁定') or distanceBetweenSquared(self, thisActionTarget) < 535 * 535)
# 800为常规射程
addWaypoint_type: attack
addWaypoint_target_fromReference: thisActionTarget



[action_长距离]
text: 长距离целеуказание
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.15
iconImage: ROOT:/通用特效/长距离.png
description: 该юнит有способность射击极далеко距离上的被锁定юнит。\n-允许Передовой在использовать主炮攻击 воздушный юнит和высотныйюнит 中的 被锁定 вражескийюнит时，\n-将主炮的дальностьповышает至800



[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 400 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true





[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 410 | setFlag= 0)


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5) and not self.tags(includes= '模块化改造')
isVisible: false
alsoQueueAction: b


[action_b]
convertTo: 尖兵1
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false

highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[action_聚变弹头3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变3.png
text: Термоядерная боеголовка3
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头3')
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: Мина «Кошмар»1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3') 


[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
#imageScale:0.85


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 800
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: true

turretMultiTargeting: true


[turret_2]
x: 28
y: 33
attachedTo: 5
slave: true
shoot_flame: CUSTOM:烟雾*7,CUSTOM:枪口火焰,CUSTOM:弹壳

shoot_light: #FFEECCCC
shoot_sound: 炮击.ogg
shoot_sound_vol: 0.5
invisible: true
delay: 180
projectile: 1
size: 32
limitingMinRange: 170
canAttackFlyingUnits: false
limitingRange: 400
onShoot_playAnimation: attack1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
canAttackCondition:if not self.tags(includes= '模块化改造') and self.resource.xk < 1

[turret_3]
x: 28
y: 33
attachedTo: 5
slave: true
shoot_flame: CUSTOM:烟雾*7,CUSTOM:枪口火焰,CUSTOM:弹壳
shoot_light: #FFEECCCC
shoot_sound: 炮击.ogg
shoot_sound_vol: 0.5
invisible: true
delay: 180
projectile: 2
size: 32
limitingMinRange: 170
canAttackFlyingUnits: true
canAttackLandUnits: false
limitingRange: 535
onShoot_playAnimation: attack1
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
canAttackCondition:if not self.tags(includes= '模块化改造') and self.resource.xk < 1
[turret_6]
x: 28
y: -3
attachedTo: 5
projectile: 4
slave: true

delay: 1
canShoot: true
invisible: true
limitingMinRange: 170
canAttackFlyingUnits: true
canOnlyAttackUnitsWithTags:被锁定

canAttackLandUnits: false
aimOffsetSpread: -0.01
canAttackCondition:if not self.tags(includes= '模块化改造') and self.resource.xk < 1

[turret_5]
x: 0
y: 0
canShoot: false
#image:身体.png
invisible: true
canAttackCondition: if self.resource.xk < 1
[turret_7]
x: 28
y: 33
attachedTo: 5
canAttackCondition:if not self.tags(includes= '模块化改造') and self.resource.xk < 1
slave: true
shoot_flame: CUSTOM:烟雾*7,CUSTOM:枪口火焰,CUSTOM:弹壳
shoot_light: #FFEECCCC
shoot_sound: 炮击.ogg
shoot_sound_vol: 0.5
invisible: true
delay: 180
projectile: 2
size: 32
limitingMinRange: 400
canAttackLandUnits: false
onShoot_playAnimation: attack1
canOnlyAttackUnitsWithTags:被锁定
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 1200
areaRadius: 60
life: 250
frame: 9

lightColor: #FFFFFF73
drawSize: 0.9
speed: 9
targetSpeed: 14
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:钢珠

targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2
mutator7_areaDamageMultiplier: 2

[projectile_2]
@copyFromSection: template_爆炸
directDamage: 1200
life: 2500
frame: 9

lightColor: #FFFFFF73
drawSize: 0.01
speed: 90
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:钢珠,CUSTOM:黑烟*6,CUSTOM:黑烟1*7
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:钢珠,CUSTOM:黑烟*6,CUSTOM:黑烟1*7

areaRadiusFromEdge: true
instant: true

mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2
mutator7_areaDamageMultiplier: 2
[projectile_4]
directDamage: 0
life: -4
instant: true
frame: 33
beamImage: 光.png

beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
color: #FFFF1200
explodeEffect: none
[projectile_炮弹]
@copyFromSection: template_能源
areaDamage: 1800
areaRadius: 70
life: 250
frame: 9
lightColor: #FFFFFF73
drawSize: 0.9
speed: 9
targetSpeed: 14
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2
mutator7_areaDamageMultiplier: 2
buildingDamageMultiplier: 1.2
[projectile_炮弹1]
@copyFromSection: template_能源
directDamage: 1800
life: 2500
frame: 9
lightColor: #FFFFFF73
drawSize: 0.01
speed: 90
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb
areaRadiusFromEdge: true
instant: true
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2
mutator7_areaDamageMultiplier: 2
buildingDamageMultiplier: 1.2
[effect_枪口火焰]
life: 30
attachedToUnit: true
image: ROOT:/创世纪军事集团/单位特效/巨大火焰.png
total_frames: 7
animateFrameStart: 0

animateFrameEnd: 6
animateFrameSpeed: 0.3
fadeOut: false
scaleFrom: 0.1
scaleTo: 0.3


[effect_烟雾]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70

fadeOut: true
attachedToUnit: true
#color:#FFE56BFF
#color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.7
scaleTo: 1.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2
yOffsetRelative: 0.3

ySpeedRelative: 0.5
atmospheric: true


[effect_弹壳]
priority: high
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 1.5
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.25
yOffsetRelative: -74
xOffsetRelative: 2

hSpeed: 1.7
dirSpeedRandom: 50


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.6

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1.8
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 2
scaleTo: 2
createWhenOverLiquid: false
createWhenOverLand: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false

atmospheric: false


[effect_黑烟]
stripIndex: smoke_black
frameIndex: 0
life: 90
fadeOut: true
attachedToUnit: false

fadeInTime: 4
scaleFrom: 1
scaleTo: 2
alpha: 1
drawUnderUnits: false

atmospheric: true
dirOffsetRandom: 180
shadow: false
xSpeedRelativeRandom: 1
ySpeedRelativeRandom: 1

xSpeedAbsoluteRandom: 0.1
ySpeedAbsoluteRandom: 0.1


[effect_黑烟1]
stripIndex: smoke_black
frameIndex: 0
life: 90
fadeOut: true
attachedToUnit: false

fadeInTime: 4
scaleFrom: 1
scaleTo: 2
alpha: 1
drawUnderUnits: false

atmospheric: true
dirOffsetRandom: 180
shadow: false
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2

xSpeedAbsoluteRandom: 0.1
ySpeedAbsoluteRandom: 0.1
#——————————聚变

[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 1.2
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_实验jb]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.5
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[arm_1]
x: -10
y: 9
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: -30

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_2]
x: 14
y: 3
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 35
image_end_shadow: SHADOW:胳膊.png


[arm_3]
x: 24
y: 22
image_end: 右手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -45
image_end_shadow: SHADOW:右手.png


[arm_4]
x: -26
y: 26
image_end: 盾手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 45
image_end_shadow: SHADOW:盾手.png


[arm_5]
x: 16
y: 32
image_end: 枪.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -53


[arm_6]
x: 16
y: 32
image_end: 枪1.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -53


[arm_7]
#左肩
x: 28
y: 24
image_end: 主炮.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:主炮.png


[arm_8]
#左肩
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true

drawOverBody: true
#image_end_shadow:SHADOW:损坏.png
hidden: if self.maxHp * 0.36 < self.hp


[arm_9]
#左肩
x: 0
y: 0
image_end: 身体.png
image_end_teamColors: true

hidden: if self.maxHp * 0.36 > self.hp
drawOverBody: true
image_end_shadow: SHADOW:身体.png


[arm_10]
x: -26
y: 26
image_end: 盾.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 45
image_end_shadow: SHADOW:盾.png
hidden:if self.hp<self.maxHp * 0.36



[arm_11]
x: 0
y: -15
image_end: 雷达.png
image_end_teamColors: true
drawOverBody: true

image_end_shadow: SHADOW:雷达.png
spinRate: 4


[leg_1]
x: -14
y: 10
attach_x: -4
attach_y: 3
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 14
y: 10
attach_x: 4
attach_y: 3
copyFrom: 1

drawDirOffset: 10


[animation_attack1]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm7_0.1s: {x:0, y:-30, dir:0}
arm7_0.2s: {x:0, y:0, dir:0}


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm1_0.6s: {x:1, y:4, dir:3}
arm2_0.6s: {x:0, y:0, dir:0}

arm3_0.6s: {x:0, y:0, dir:25}
arm4_0.6s: {x:6, y:4, dir:35}
arm5_0.6s: {x:0, y:5, dir:53}
arm6_0.6s: {x:0, y:5, dir:53}
arm10_0.6s: {x:6, y:4, dir:35}


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.8
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

turnAcceleration: 1
targetHeight: 4
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0

slowDeathFall: true


