


[core]
name: 核弹标记
class: CustomUnitMetadata
price: 0
maxHp: 10
armour: 999989
tags:核弹标记
techLevel: 2
radius: 0
displayRadius: 0
armourMinDamageToKeep: 0
#showInEditor:false
isBuilding: true
hideScorchMark: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
isUnselectable: true
isBio: false

energyMax: 1
energyRegen: 0
dieOnZeroEnergy: true
fogOfWarSightRange: 40
explodeOnDeath: false
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[decal_主体1]
image: 外圈.png
total_frames: 1
layer: shadow
isVisible: true
onlyWhileAlive:true
alpha:0.4
[decal_主体]
image: 中心.png
total_frames: 1
layer: shadow
isVisible: true
onlyWhileAlive:true
alpha:0.4
imageScale:0.5
[decal_主体2]
image: 外圈.png
total_frames: 1
layer: shadow
isVisible: true
onlyWhileAlive:true
alpha:0.4
imageScale:1.8
[action_爆炸]
autoTrigger: if self.timeAlive(laterThanSeconds=40)
isVisible: false
addResources: energy=-1


[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 1.25

[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 450

aimOffsetSpread: 0
shootDelay: 1
turretMultiTargeting: true

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 0
targetHeight: -1
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true


