


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 太空浪人超立方t1
displayText: Гиперкуб Скитальцев t1
class: CustomUnitMetadata
price: 6500,awz= ${awzxq}
@global awzxq: 150
reclaimPrice: awz= ${awzxq}

maxHp: 14500
selfRegenRate: 0.2
footprint: -4,0,4,6
constructionFootprint: -4,0,4,6
techLevel: 1

energyMax: 12
energyRegen: 0
energyStartingPercentage: 0
buildSpeed: 10s
radius: 60

isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
exit_x: 0

exit_y: -1
tags: 地面,超立方,灰影建筑,建筑
energyNeedsToRechargeToFull: false
armour: 10
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=2, withTag='超立方')
deleteSelf: true
showMessageToPlayer: Эксплойт? Размечтался! В наказание лишних юнитов поглотил мой сервер 눈_눈


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: Недостаточно тёмной материи
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true





[hiddenAction_断电a]
autoTrigger: if not self.hasFlag(id= 30) and self.queueSize > 0 and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
resetCustomTimer: true
addResources: setFlag= 30


[hiddenAction_断电b]
autoTrigger: if self.hasFlag(id= 30) and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30
refundAllQueuedItems: true


[hiddenAction_来电a]
autoTrigger: if self.hasFlag(id= 30) and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30


[action_0_补充能量]
price: 2400,hy=650
text: Пополнить энергию
buildSpeed: 20s
pos: 0.2
isActive: if self.energyIncludingQueued(lessThan=12)

addResources: energy=2
#allowMultipleInQueue: false
isLocked: if self.noUnitInTeam(withTag='聚变堆', withinRange=400) or self.resource.awz<0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: Это здание потеряло питание либо недостаточно тёмной материи

[action_轨道空爆]
text: Орбитальный воздушный удар
allowMultipleInQueue: false
description: -指引附近的反舰轨道炮向目标地点投射炮击，\n-由刚化钴制成的炮弹将会被加速至亚光速，\n-随后在目标上方爆裂出大量碎片对密集的敌方单位造成毁灭性打击。\n-发射后，将向目标地点发射3枚子母弹，对敌方地面单位造成大量动能伤害，\n-轨道空爆打击将被视为战略武器，对 非 极端重型单位伤害加成且反掩体。
iconImage: 空爆.png
onlyOneUnitAtATime: true
price: energy=6
fireTurretXAtGround: 轨道空爆
isVisible: true
highPriorityQueue: true
isLocked: if self.noUnitInTeam(withTag='聚变堆', withinRange=400) or self.resource.awz<0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: Это здание потеряло питание либо недостаточно тёмной материи
buildSpeed: 0s


[action_轨道垃圾雨]
text: Вызвать орбитальный дождь мусора
allowMultipleInQueue: false
description: -Активирует генератор поля гиперкуба, начинает притягивать космический мусор с низкой околоземной орбиты\n-и направляет его в целевое место, поражая врагов мощными ударами.\n-С повышением уровня вируса «Серая Тень» мощь орбитального дождя мусора возрастает.\n-Кинетический урон, тактическое оружие.
iconImage: 轨道垃圾雨.png
onlyOneUnitAtATime: true
buildSpeed: 0s
price: energy=8
fireTurretXAtGround: 轨道垃圾雨
isVisible: true
highPriorityQueue: true
isLocked: if self.noUnitInTeam(withTag='聚变堆', withinRange=400) or self.resource.awz<0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

isLockedMessage: Это здание потеряло питание либо недостаточно тёмной материи


[action_灰影病毒催化剂]
text: Запустить катализатор вируса «Серая Тень»
allowMultipleInQueue: false
description: -引导一枚灰影病毒催化剂弹头，使目标附近的灰影病毒狂暴化，\n-处于狂暴状态的灰影病毒将会不顾一切的吞噬靠近的敌人，\n-又或者积少成多，用自己渺小的身躯以难以置信的速度修补己方单位的损伤。\n-对320范围内的敌人单位，造成持续穿甲动能伤害，对建筑物无效，\n-对320内的己方单位快速修复，包括建筑。\n-无法被拦截。反掩体
iconImage: 狂暴灰影.png
onlyOneUnitAtATime: true
buildSpeed: 0s
price: energy=2.5
fireTurretXAtGround: 狂暴灰影
isVisible: true
isLocked: if self.noUnitInTeam(withTag='聚变堆', withinRange=400) or self.resource.awz<0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: Это здание потеряло питание либо недостаточно тёмной материи

highPriorityQueue: true


[action_模拟黑洞]
text: Запустить симулированную чёрную дыру
allowMultipleInQueue: false
description: -Используя поразительную энергию, накопленную ранее гиперкубом из тёмной материи,\n-контролирует кривизну пространства в определённой области, искажая его\n-и создавая из ничего огромную гравитацию, сравнимую с маломассивной чёрной дырой, разрывающую всё вокруг.\n-Нейтральный урон. Пробивает укрытия.
iconImage: 狙.png
onlyOneUnitAtATime: true
buildSpeed: 0s
isVisible: if self.globalTeamTags(includes='帝国科技解析2')
price: energy=12,ammo=1
fireTurretXAtGround: 模拟黑洞
highPriorityQueue: true
showMessageToAllPlayers: 警告，侦测到巨大空间曲率波动。

isLocked: if self.resource.awz<1200 or self.noUnitInTeam(withTag='聚变堆', withinRange=400) or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: Недостаточно тёмной материи либо это здание потеряло питание


[action_模拟黑洞制造]
price: 10000
text: Создать симулированную чёрную дыру
description: -利用大量的暗物质汇聚惊人的能量于超立方中，\n-一但准备就绪，将可以发射太空浪人的终极武器，\n-模拟黑洞。汇聚暗物质引发的能量脉冲无法隐藏，\n-汇聚完毕将警告所有玩家，请注意。\n-汇聚能量时请时刻保持你的可用暗物质不低于1200，\n-制造完毕后，必须在超立方满能量，不缺少暗物质和供能的情况下才能释放模拟黑洞。
displayType: NONE
buildSpeed: 50s

isVisible: if self.globalTeamTags(includes='帝国科技解析2') and self.ammo(lessThan=1)
pos: 0.2
isActive: if self.ammoIncludingQueued(lessThan=1)
addResources: ammo=1
iconImage: 模拟黑洞.png

showMessageToAllPlayers: 检测到巨大能量脉冲
isLocked: if self.resource.awz<1200 or self.noUnitInTeam(withTag='聚变堆', withinRange=400) or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: Тёмной материи меньше 1200 либо это здание потеряло питание


[action_模拟黑洞完成]
iconImage: 模拟黑洞.png
text: Симуляция чёрной дыры готова
isActive: false
isVisible: if self.ammo(greaterThan=0)
displayType: infoOnly

isGuiBlinking: true


[graphics]
total_frames: 15
image: 主要体.png
image_wreak: 死亡.png
image_back: 背景.png
#imageScale:0.7

image_shadow: 影子.png


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 99999

turretSize: 0
turretTurnSpeed: 50


[turret_10]
x: 0
y: 170
canShoot: true
shoot_flame: CUSTOM:光粒*4
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 160
fadeOut: true
attachedToUnit: false

color: #FFFF1200
fadeInTime: 4
scaleFrom: 0.3
scaleTo: 0.6
alpha: 0.55

drawUnderUnits: false
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.17

ySpeedAbsoluteRandom: 0.17


[turret_轨道空爆]
x: 0
y: 0
projectile: 1
limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true


[turret_轨道垃圾雨]
x: 0
y: 0
projectile: 2
limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true


[turret_狂暴灰影]
x: 0
y: 0
projectile: 3
limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true


[turret_模拟黑洞]
x: 0
y: 0
projectile: 4
limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true


[projectile_1]
life: 0
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 1x,2x,3x
[projectile_1x]
areaDamage: 0
areaRadius: 0
life: 99999
frame: 1
drawSize: 0
speed: 30
explodeEffect: NONE
targetGround: true
areaRadiusFromEdge: true
spawnUnit: 轨道空爆中介
targetGroundSpread: 200
[projectile_2x]
@copyFromSection:projectile_1x
speed: 24
[projectile_3x]
@copyFromSection:projectile_1x
speed: 18
[projectile_2]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 太空垃圾雨中介
explodeEffect: none
explodeEffectOnShield: none


[projectile_3]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 灰影病毒催化剂中介
explodeEffect: none
explodeEffectOnShield: none


[projectile_4]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 模拟黑洞
explodeEffect: none
explodeEffectOnShield: none


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: 0
y: 0
image_end: 闪光.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: -12
y: -36
image_end: 货.png
image_end_teamColors: true
drawOverBody: false


[arm_3]
x: 12
y: 30
image_end: 货.png
image_end_teamColors: true
drawOverBody: false


[animation_1]
onActions: idle
blendIn: 1.4s
blendOut: 1.4s
arm1_0s: {alpha:0.0}
arm1_0.7s: {alpha:1}

arm1_1.4s: {alpha:0.1}
body_0s: {frame:0}
body_0.1s: {frame:1}
body_0.2s: {frame:2}
body_0.3s: {frame:3}

body_0.4s: {frame:4}
body_0.5s: {frame:5}
body_0.6s: {frame:6}
body_0.7s: {frame:7}
body_0.8s: {frame:8}

body_0.9s: {frame:9}
body_1s: {frame:10}
body_1.1s: {frame:11}
body_1.2s: {frame:12}
body_1.3s: {frame:13}

body_1.4s: {frame:14}
arm2_0s: {x:0,y:0}
arm2_1.4s: {x:0,y:76}
arm3_0s: {x:0,y:0}
arm3_1.4s: {x:0,y:-70}


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


