


[core]
name: 天照
class: CustomUnitMetadata
price: 1000
maxHp: 1400
displayDescription: -天照的历史甚至早于古人类战国时期，\n-这款主战坦克采用古老而实用的科技，\n-他们久经沙场，无数的战斗证明了他们存在至今的理由。\n-太空浪人在火种舰的数据库中发现了这位古老的战士，\n-在经过改造后，无论面对单个还是大量敌人，\n-他们都能像老练的战士一般轻易将他们撕碎。\n-只能对地。主炮动能伤害，散弹能源伤害
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
techLevel: 1
buildSpeed: 9s
radius: 20
displayRadius: 20
isBio: false
armour: 4
softCollisionOnAll: 6
selfRegenRate: 0.16
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,主炮
unitsSpawnedOnDeath: 损毁*1

[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_散弹]
displayType: action
price: 0
text: 散弹模式
buildSpeed: 2s
whenBuilding_cannotMove: false
temporarilyAddTags:散弹
temporarilyRemoveTags:主炮
isVisible: if not self.tags(includes= '散弹')
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_主炮]
displayType: action
price: 0
text: 点射模式
buildSpeed: 2s
whenBuilding_cannotMove: false
temporarilyAddTags:主炮
temporarilyRemoveTags:散弹
isVisible: if not self.tags(includes= '主炮')
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[graphics]
total_frames: 3
image: 天照底盘.png
image_wreak: 天照死亡.png
image_turret: 天照炮塔.png
#turretImageScale:0.9

image_shadow: AUTO
teamColorsOnTurret: true
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 0

animation_moving_end: 2
animation_moving_speed: 1
dustEffect: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 25

turretTurnSpeed: 4
maxAttackRange: 280
shootDelay: 90


[turret_1]
x: 0
y: 1
canShoot: false
canAttackCondition: if self.resource.xk < 1

[turret_0]
x: 0
y: 0
projectile: 1
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.3

shoot_flame: NONE
shoot_light: #FFEEEEEE
canShoot: true
attachedTo: 1
slave: true

invisible: true
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '散弹')
aimOffsetSpread: -0.01
[turret_2]
x: 0
y: 0
projectile: 2
shoot_sound: NONE
shoot_sound_vol: 0.3

shoot_flame: NONE
shoot_light: #FFEEEEEE
canShoot: true
attachedTo: 1
slave: true

invisible: true
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '散弹')
aimOffsetSpread: -0.01
[turret_3]
x: 0
y: 0
copyFrom: 2


[turret_4]
x: 0
y: 0
copyFrom: 2


[turret_5]
x: 0
y: 0
projectile: 3
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.3
shoot_flame: NONE
shoot_light: #FFEEEEEE
canShoot: true
attachedTo: 1
slave: true
delay:90
invisible: true
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '主炮')

[turret_6]
x: 0
y: 0
#炮塔损坏
canShoot: false
image: 炮塔损坏.png
invisible: if self.maxHp * 0.36 < self.hp
attachedTo: 1
slave: true

[projectile_1]
@copyFromSection: template_动能
directDamage: 200
life: 10
lightColor: #FFFF1200
lightSize: 1
largeHitEffect: true
instant: true
laserEffect: true
color: #FFFF1200
explodeEffect: CUSTOM:波雷爆炸*1


[projectile_2]
lightingEffect: true
directDamage: 0
life: 20
instant: true
trailEffect: true

speedSpread: 1
lightSize: 0
[projectile_3]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定*4

[projectile_锁定]
@copyFromSection: template_能源
areaDamage: 57
areaRadius: 35
life: 360
lightSize: 1

largeHitEffect: true
speed: 8
targetGroundSpread: 35
image: ROOT:/太空浪人/单位特效/光束.png
drawSize: 0.8
mutator2_ifUnitWithTags: 步兵
mutator2_directDamageMultiplier: 1.4
targetGround: true
explodeEffect: CUSTOM:波雷爆炸,CUSTOM:闪光
areaRadiusFromEdge: true





[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 1.5
scaleTo: 1.5

drawUnderUnits: false
atmospheric: false


[effect_波雷爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 2

color: #FFFF1200


[movement]
movementType: LAND
moveSpeed: 0.85
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 3.0

turnAcceleration: 0.25
moveSlidingMode : false
moveIgnoringBody: false


