


[core]
name: 漂泊者
class: CustomUnitMetadata
displayDescription: -以天火炮艇为基础改造的便携式虫洞载具，\n-漂泊者搭载了一个小型多向聚变堆和传送立场发生器，\n-漂泊者的存在极大的解决了固定式传送基站和聚变堆的局限性，\n-无数的传送基站和漂泊者组成了贯通全球的折越网络，\n-太空浪人的部队也正因如此能快速向全球任何一个角落发起出其不意的突袭，\n-漂泊者虽然没有任何自卫能力，但每一艘漂泊者的出现，\n-都意味着其身后必定有一支即将出现的太空浪人军团。\n-部署后可以供能，可以提供传送网络，不能攻击，水陆两栖，免疫地雷。
price: 4000
maxHp: 3000

techLevel: 1
buildSpeed: 15s
radius: 34
displayRadius: 34
tags: 地面,海上,悬浮

isBio: false
softCollisionOnAll: 6
armour: 7
copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.2

maxTransportingUnits: 4

[attachment_1]
x: 0
y: 0
canAttack:false
addTransportedUnits: true
hidden: true
setDrawLayerOnBottom:true
[attachment_2]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_3]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_4]
@copyFromSection: attachment_1
x: 0
y: 0


[action_x]
displayType: action
price: 0
buildSpeed: 3.0s
isVisible: if not self.isOverLiquid
#playSoundAtUnit: 部署.ogg

text: 展开
whenBuilding_cannotMove: true
convertTo: 漂泊者1
whenBuilding_playAnimation: 部署
canPlayerCancel: false

highPriorityQueue: true
description: 展开漂泊者的传送立场和聚变堆，\n-只能在地面上展开。
addResources: unsetFlag= 0
whenBuilding_triggerAction: 亮
isLocked: if self.resource.xk > 0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)


[hiddenAction_亮]
resetCustomTimer: true
addResources: setFlag= 0


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 2

shadowOffsetY: 2
teamColorsOnTurret: true
#turretImageScale:0.9
movementEffect: CUSTOM:projectileTrail


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shootDelay: 0

maxAttackRange: 0


[effect_projectileTrail]
createWhenZoomedOut: false
frameIndex: 0
stripIndex: effects
life: 50
fadeOut: true

attachedToUnit: false
color: #FFFF1200
fadeInTime: 3
scaleFrom: 3
scaleTo: 6

alpha: 0.4
drawUnderUnits: true
ySpeedRelative: -0.4
atmospheric: true


[arm_1]
x: 1
y: -40
image_end: 左.png
image_end_teamColors: true
drawDirOffset: 60

drawOverBody: false
image_end_shadow: SHADOW:左.png


[arm_2]
x: -1
y: -40
image_end: 右.png
image_end_teamColors: true
drawDirOffset: -60

drawOverBody: false
image_end_shadow: SHADOW:右.png


[arm_3]
x: 0
y: -41
image_end: 小球.png
image_end_teamColors: true
drawDirOffset: 180

drawOverBody: false
image_end_shadow: SHADOW:小球.png
hidden: if not self.hasFlag(id= 0) or self.customTimer(withinSeconds= 0.9)


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0, alpha:0.0}
arm1_3s: {x:0, y:0, dir:-60}

arm2_3s: {x:0, y:0, dir:60}
arm3_3s: {x:0, y:0, dir:0, alpha:1.0}


[movement]
movementType: HOVER
moveSpeed: 1
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.3
maxTurnSpeed: 1

turnAcceleration: 0.6
targetHeight: 3
targetHeightDrift: 1
moveSlidingMode : false
moveIgnoringBody: true


