[core]
name: 地狱火导弹平台1
class: CustomUnitMetadata
price: 6000,钍=70
maxHp: 11800
displayDescription: 【Уровень t4】【Механический юнит】【Наземный юнит】Тактическое назначение:тактическое оружиезапускатьплатформа，\n-размер юнита:10，вооружение：▲тактикаракетапусковая трубаX1 только по земле взрывной урон будет считатьв качестветактическое оружие \n-вЗаревовойнаначало，большинство 洲际снаряд道ракетатогда Зарево точныйударуничтожать，\n-а残存 снаряд道ракетазапускатьплатформа，впройти черезГенезисодин系列модификацияегопосле，\n-тогдастановиться Генезиссамыйв качествемощныйсупердальнийогневая мощь。пройти черезмодификацияпосле запускатьплатформаможетбыстрыйразворачиватьивцелеуказаниеатакапослебыстрый收起脱离，\n-егоиметь мощныйогневая мощьспособенвсупердалекодистанцияэффективный ударЗарево высокий价值 поверхностьцель，\n-одновременно，Платформа ракет «Адский огонь»болееявляетсяможетсогласнополе бояокружениенесётне同 специальныйснаряд头сражение。\n-независимо откак何，этоттогдаявляетсячеловечествосамыйв качествемощныйвооружение昔日荣свет 残存。
techLevel: 1
buildSpeed: 25s
radius: 58
mass: 4500000
displayRadius: 58
isBio: false
softCollisionOnAll: 6
transportSlotsNeeded: 800
fogOfWarSightRange: 28
tags: 地面,常规弹药
displayText: Платформа ракет «Адский огонь»1
showInEditor: false
copyFrom: ROOT:/通用特效/单位防护.ini
unitsSpawnedOnDeath: 损毁3*1
energyMax: 8
energyRegen: 0.0085
energyNeedsToRechargeToFull: true
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[action_弹道导弹托]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/导弹托.png
text: Пусковая платформа
isActive: false
isVisible: if self.globalTeamTags(includes='导弹托1')
pos: 1.1
[action_弹幕架3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕3.png
text: Реактивная установка3
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架3')
pos: 1.2
[hiddenAction_jb]
autoTrigger: if self.hasActiveWaypoint(type= 'move') or self.hasActiveWaypoint(type='patrol') or self.hasActiveWaypoint(type='guard') or self.hasActiveWaypoint(type='attackMove')
clearActiveWaypoint: true
[decal_导]
image: 导.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪') and self.energy(greaterThan=3)
yOffsetRelative:-52
xOffsetRelative:0.5

[decal_导弹影子]
image: 导弹影子1.png
total_frames: 1
layer: afterBody
#layer: onTop
isVisible:true
yOffsetRelative:-17
xOffsetRelative:4
[decal_炮塔动画影子]
image: 导弹动画影子1.png
total_frames: 15
frame: select(self.tags(includes= '切枪'), (self.customTimer * 15) % 15, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:-17
xOffsetRelative:4
[decal_炮塔1]
image: 导弹动画1.png
total_frames: 15
frame: select(self.tags(includes= '切枪'), (self.customTimer * 15) % 15, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:-14
xOffsetRelative:0
[decal_履带静止]
image: 履带.png
total_frames: 1
layer: shadow
isVisible:true
onlyWhileAlive:true
yOffsetRelative:0
xOffsetRelative:-0.5
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[action_b]
displayType: action
price: 0
buildSpeed: 0s
isVisible: true
whenBuilding_cannotMove: true
text: 收起ракетаплатформа
alsoQueueAction: bx
description: 收起固定установить置，иначало移动，迅速转移Позиция。\n-收起послеракетабудетне можетатака，номожет移动。
isLocked: if self.queueSize > 0.5 or self.resource.xk > 0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage:выполняется другое действие，пожалуйста, подождите。
iconImage: ROOT:/通用特效/收起主炮.png
resetCustomTimer: true
temporarilyAddTags: 切枪
playSoundAtUnit:ROOT:/通用特效/展开主炮.ogg
allowMultipleInQueue:false
playAnimation: 动画
pos: 0.1
[action_bx]
convertTo: 地狱火导弹平台
displayType: action
price: 0
buildSpeed: 0.95s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed
[action_装核弹]
text: Использовать стратегическую ядерную бомбу
displayType: action
buildSpeed: 2s
pos: 1
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/创世纪军事集团/单位特效/地震弹头.png
temporarilyAddTags:核弹
temporarilyRemoveTags:电磁脉冲,常规弹药
isVisible: if not self.tags(includes= '核弹')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令Платформа ракет «Адский огонь»Использовать стратегическую ядерную бомбуатакацель。\n-стратегияядерныйснарядбудетпротиврадиус200в враг，наноситсамыйвысокий18000пунктнейтральный урон，\n-одновременнобудет附нести燃烧эффект，противздание伤害+50%。\n-стратегияядерныйснарядне受Пусковая платформа加становитьсяэффект。\n-стратегияядерныйснарядбудет считатьв качествестратегическое оружие。
isLocked: if self.queueSize > 0.5 or not self.globalTeamTags(includes='地震弹头') or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: Требуется сейсмическая боеголовканаукаможетИспользовать тактическую ядерную бомбу，或выполняется другое действие，пожалуйста, подождите。
[action_装导弹]
text: использоватьтактика飞снаряд
displayType: action
buildSpeed: 2s
pos: 0.9
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/战术飞弹.png
temporarilyAddTags:常规弹药
temporarilyRemoveTags:电磁脉冲,核弹
isVisible: if not self.tags(includes= '常规弹药')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令Платформа ракет «Адский огонь»использоватьобычный规Боеприпасыатакацель。\n-обычный规Боеприпасы受Пусковая платформа加становитьсяэффект。\n-обычный规ракетабудет считатьв качестветактическое оружие。
isLocked: if self.queueSize > 0.5 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: выполняется другое действие，пожалуйста, подождите。
[action_装emp]
text: использоватьЭМИракета
displayType: action
buildSpeed: 2s
pos: 0.8
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/创世纪军事集团/单位特效/电磁1.png
temporarilyAddTags:电磁脉冲
temporarilyRemoveTags:核弹,常规弹药
isVisible: if not self.tags(includes= '电磁脉冲')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令Платформа ракет «Адский огонь»использоватьЭМИракетаатакацель。\n-ЭМИракетабудет瘫痪радиус300в некрайне端тяжёлыйюнит6секунда，\n-瘫痪крайне端тяжёлыйюнит3.5секунда，и彻底уничтожатьв радиусеназемный юнит 护盾，\n-ЭМИракетане受Пусковая платформа加становитьсяэффект。\n-ЭМИракетане перехватывать。
isLocked: if self.queueSize > 0.5 or not self.globalTeamTags(includes='电磁脉冲武器1') or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: Требуется ЭМИ-оружие1науканеобходима для использованияЭМИракета，或выполняется другое действие，пожалуйста, подождите。
[action_常规]
displayType: infoOnlyNoBox
iconImage: ROOT:/通用特效/战术飞弹.png
pos: 1
text:Боеприпасы类 :обычный规тактика飞снаряд
isActive: false
isVisible:if self.tags(includes= '常规弹药')
[action_核弹]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/地震弹头.png
pos: 1
text:Боеприпасы类 :тактикаядерныйснаряд
isActive: false
isVisible:if self.tags(includes= '核弹')
[action_电磁脉冲]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/电磁1.png
pos: 1
text:Боеприпасы类 :ЭМИракета
isActive: false
isVisible:if self.tags(includes= '电磁脉冲')



[hiddenAction_打断]
autoTrigger:if self.hasParent
disconnectFromParent: true
[graphics]
total_frames: 1
image: 底盘.png
image_wreak: 死亡.png
image_shadow: 影子.png
shadowOffsetX: 4
shadowOffsetY: 4
teamColorsOnTurret: true
dustEffect: true
showTransportBar: false
showEnergyBar: true
showShotDelayBar:false


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 2
maxAttackRange: 2850
shootDelay: 180
[turret_1]
x: 0
y: -52
idleDir: 0
invisible: true
shoot_sound: nuke_launch
shoot_sound_vol: 0.27
projectile: 1
size: 1
turnSpeed: 40
warmup:180
delay:180
shoot_flame: CUSTOM:烟雾*7, CUSTOM:冲击波
shoot_light: #FFEECCCC
limitingMinRange: 400
energyUsage:8
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='导弹托1') and self.tags(includes= '常规弹药')
altProjectile: 弹幕
altProjectileCondition: if self.globalTeamTags(includes='弹幕架3')

[turret_2]
x: 8
y: -52
copyFrom: 1
energyUsage:4
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='导弹托1') and self.tags(includes= '常规弹药')
projectile: 炮弹
altProjectile: 弹幕x
altProjectileCondition: if self.globalTeamTags(includes='弹幕架3')
[turret_3]
x: 8
y: -52
copyFrom: 1
energyUsage:4
linkDelayWithTurret:2
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='导弹托1') and self.tags(includes= '常规弹药')
projectile: 炮弹
warmup:220
delay:140
altProjectile: 弹幕x
altProjectileCondition: if self.globalTeamTags(includes='弹幕架3')

[turret_4]
x: 8
y: -52
copyFrom: 1
canAttackCondition: if self.resource.xk < 1 and self.tags(includes= '核弹')
projectile: 核弹
altProjectile: 核弹
altProjectileCondition: if self.globalTeamTags(includes='弹幕架3')
[turret_5]
x: 8
y: -52
copyFrom: 1
canAttackCondition: if self.resource.xk < 1 and self.tags(includes= '电磁脉冲')
projectile: 电磁脉冲
altProjectile: 电磁脉冲
altProjectileCondition: if self.globalTeamTags(includes='弹幕架3')
[projectile_1]
@copyFromSection: template_爆炸
life: 140
speed: 1
targetSpeed: 7
targetSpeedAcceleration: 0.1
#largeHitEffect: true
ballistic: true
ballistic_delaymove_height: 280
ballistic_height: 360
image: 导弹.png
drawSize: 1
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1
targetGround: true
areaDamage: 1
areaRadiusFromEdge: true
areaHitAirAndLandAtSameTime: false
alwaysVisibleInFog: true
areaRadius: 180
deflectionPower: -1
shouldRevealFog: true
lightColor: #FFEEEE00
lightSize: 1
trailEffect: CUSTOM:projectileTrail
disableLeadTargeting: true

[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 6800
shouldRevealFog: true
areaRadius: 160

life: 350
alwaysVisibleInFog: true
speed: 9
trailEffect: CUSTOM:projectileTrail
tags:战术武器
image: 弹头.png
targetSpeed: 9
#drawSize: 0.9
explodeEffect: CUSTOM:爆炸,CUSTOM:气浪,CUSTOM:冲击波2,CUSTOM:闪光*2,CUSTOM:弹坑*1
areaRadiusFromEdge: true
#trailEffect: true
#ballistic_delaymove_height: 280
#ballistic_height: 360
targetGround: true
ballistic: true
lightSize: 0.9
lightColor: #FFFFFF73
disableLeadTargeting: true
targetGroundSpread: 100
deflectionPower: -1
trailEffectRate: 0.6
[projectile_炮弹]
@copyFromSection:projectile_1
image: 小导弹.png
spawnProjectilesOnEndOfLife: 小锁定
explodeEffect: CUSTOM:导弹碎片*2
[projectile_小锁定]
@copyFromSection:projectile_锁定
areaDamage: 5000
areaRadius: 120
explodeEffect: CUSTOM:爆炸s,CUSTOM:气浪s,CUSTOM:冲击波2s,CUSTOM:闪光,CUSTOM:弹坑
#——————————————弹幕
[projectile_弹幕]
@copyFromSection:projectile_1
image: 导弹.png
spawnProjectilesOnEndOfLife: 弹幕锁定*4
[projectile_弹幕锁定]
@copyFromSection: template_爆炸
areaDamage: 3850
tags:战术武器
life: 1000
areaRadius: 100
speed: 3
image:核弹2.png
targetSpeed: 11
drawSize:0.95
lightSize: 0.9
lightColor: #FFFFFF73
targetGroundSpread: 150
disableLeadTargeting: true
speedSpread:3
trailEffect: true
trailEffectRate: 0.75
areaRadiusFromEdge: true
targetGround: true
deflectionPower: -1
shouldRevealFog: true
ballistic: true
ballistic_delaymove_height: 280
ballistic_height: 360
explodeEffect: CUSTOM:爆炸ss,CUSTOM:气浪ss,CUSTOM:冲击波2ss,CUSTOM:闪光ss,CUSTOM:弹坑ss
#——————————————弹幕x
[projectile_弹幕x]
@copyFromSection:projectile_1
image: 小导弹.png
spawnProjectilesOnEndOfLife: 弹幕锁定*3
explodeEffect: CUSTOM:导弹碎片*2
#——————————核弹
[projectile_核弹]
@copyFromSection:projectile_1
image: 和平守卫者.png
explodeEffect: CUSTOM:核弹碎片
spawnProjectilesOnEndOfLife: 核弹1
[projectile_核弹1]
@copyFromSection:projectile_锁定
areaDamage: 0
areaRadius: 0
spawnUnit:通用战略武器
image:和平弹头.png
explodeEffect:NONE
tags:导弹2
#——————————电磁脉冲
[projectile_电磁脉冲]
@copyFromSection:projectile_1
image: 电磁脉冲.png
explodeEffect: CUSTOM:电磁碎片
spawnProjectilesOnEndOfLife: 电磁脉冲1
[projectile_电磁脉冲1]
@copyFromSection:projectile_锁定
areaDamage: 0
areaRadius: 0
spawnUnit:通用战略武器(addResources=电磁:1)
image:脉冲导弹头.png
explodeEffect:NONE
tags:不能拦截捏
[arm_3]
x: -17
y: -56
#(-4)
image_end: 支架.png
image_end_teamColors: true
drawOverBody: false
drawDirOffset: 45
[arm_4]
x: 17
y: -56
image_end: 支架.png
image_end_teamColors: true
drawOverBody: false
drawDirOffset: -45
[arm_5]
x: 0
y: -14
image_end: 导管.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 0
hidden:if self.tags(includes= '切枪')

[effect_烟雾]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 135
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 2
scaleTo: 3.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.14
xSpeedRelativeRandom: 0.68
atmospheric: true
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: true
scaleFrom: 0.6
scaleTo: 1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.8
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true

[effect_气浪]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 3
scaleTo: 7.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true

[effect_闪光]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true

[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.5
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true


[effect_导弹碎片]
#priority: low
image:弹片.png
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 3.5
ySpeedRelativeRandom: 0.7
hSpeed: 2.5
dirSpeedRandom: 10


[effect_导弹碎片1]
#priority: low
image: 弹尾.png
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.37
hSpeed: 3
dirSpeedRandom: 18
#————————————————科技
[effect_气浪s]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true
[effect_冲击波2s]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 2.9
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_爆炸s]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3.9
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
#————————————弹幕
[effect_气浪ss]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 1.7
scaleTo: 4.7
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true
[effect_冲击波2ss]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.35
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_爆炸ss]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 3
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true

[effect_弹坑ss]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.9
life: 240
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2
scaleTo: 2
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true

[effect_闪光ss]
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
#————————————核弹
[effect_核弹碎片]
#priority: low
image: 导弹壳.png
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 1
hSpeed: 3
dirSpeedRandom: 18
[effect_电磁碎片]
#priority: low
image: 脉冲导弹壳.png
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 1
hSpeed: 3
dirSpeedRandom: 18
[animation_动画]
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm3_0.55s: {x:0, y:0, dir:-45}
arm4_0.55s: {x:0, y:0, dir:45}
arm3_0.95s: {x:0, y:22, dir:-45}
arm4_0.95s: {x:0, y:22, dir:45}
[resource_电磁]
displayName: Электромагнит
displayNameShort: Электромагнит
displayColor: #FF9D00FF
priority: 1
hidden: true
[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0

turnAcceleration: 0
moveSlidingMode : false
moveIgnoringBody: false


