


[core]
name: 狂战士
price: 2800
maxHp: 8000
mass: 30000
displayDescription: 狂战士机甲是对余辉与创世纪工业无情的嘲笑，\n-一个由灰影病毒用咆哮者残骸和其他垃圾组装起来的机甲，\n-战斗力竟然和那些由精密工厂制造出来的机甲战力不相上下。\n-即便如此，控制狂战士的灰影病毒没有精密到能修复余辉的核反应堆，\n-所以狂战士只能放弃能量武器，转而专门组装了一把威力强悍的霰弹枪。\n-无论如何，狂战士的存在对于余辉来说确实是一个可怕的事实，\n-哪怕是机械也难逃被灰影病毒掌握的命运。\n-只能对地，动能伤害，生物单位。

techLevel: 1
buildSpeed: 20s
radius: 37
displayRadius: 37
armour: 7
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 2
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,步兵,寄生免疫
energyMax: 2
isUnrepairableUnit:true
energyRegen: 0
energyNeedsToRechargeToFull: true
isBio: true


[action_灰影寄生虫科技提示1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/灰影寄生虫.png
text: 灰影寄生虫1
isActive: false
isVisible: if self.globalTeamTags(includes='寄生虫1')


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5)
isVisible: false
alsoQueueAction: b


[action_b]
convertTo: 狂战士1
displayType: action
price: 0
buildSpeed: 0.3s
isVisible: false

whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署


[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 390 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true


[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 350 | setFlag= 0)


[graphics]
image: 身体1.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 5

shadowOffsetY: 5
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 290
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[arm_1]
x: 9
y: -3
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 35
image_end_shadow: SHADOW:胳膊.png


[arm_2]
x: -15
y: 1
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: -10

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_3]
x: 29
y: 20
image_end: 手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -60
image_end_shadow: SHADOW:手.png


[arm_5]
x: 11
y: 32
image_end: 枪1.png
image_end_shadow: 枪1.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -60


[arm_7]
x: -18
y: 27
image_end: 手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 60
image_end_shadow: SHADOW:手.png


[arm_8]
x: 11
y: 32
image_end: 枪.png
image_end_shadow: SHADOW:枪.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -60


[arm_9]
#左肩
x: 0
y: 0
image_end: 身体1.png
image_end_teamColors: true

drawOverBody: true


[arm_10]
#左肩
x: 0
y: 0
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[leg_1]
x: -14
y: -1.5
attach_x: -1
attach_y: -1
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 胳膊.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 14
y: -1.5
attach_x: 1
attach_y: -1
copyFrom: 1

drawDirOffset: 10


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}

arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm1_0.3s: {x:0, y:8, dir:0}
arm2_0.3s: {x:0, y:8, dir:20}
arm3_0.3s: {x:0, y:-4, dir:15}

arm5_0.3s: {x:3, y:-3, dir:60}
arm7_0.3s: {x:10, y:6, dir:-10}
arm8_0.3s: {x:3, y:-3, dir:60}


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.8
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4
targetHeight: 3

slowDeathFall: true


