


[core]
name: 狂战士1
price: 2800
maxHp: 8000
displayText: Берсерк
mass: 30000

displayDescription: 狂战士机甲是对余辉与创世纪工业无情的嘲笑，\n-一个由灰影病毒用咆哮者残骸和其他垃圾组装起来的机甲，\n-战斗力竟然和那些由精密工厂制造出来的机甲战力不相上下。\n-即便如此，控制狂战士的灰影病毒没有精密到能修复余辉的核反应堆，\n-所以狂战士只能放弃能量武器，转而专门组装了一把威力强悍的霰弹枪。\n-无论如何，狂战士的存在对于余辉来说确实是一个可怕的事实，\n-哪怕是机械也难逃被灰影病毒掌握的命运。\n-只能对地，动能伤害，生物单位。
techLevel: 1
buildSpeed: 20s
radius: 37
displayRadius: 37

showInEditor: false
armour: 7
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 2
unitsSpawnedOnDeath: 损毁2*1
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
tags: 地面,步兵,寄生免疫
energyMax: 2
energyRegen: 0
energyNeedsToRechargeToFull: true
isBio: true

isUnrepairableUnit:true
[action_灰影寄生虫科技提示1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/灰影寄生虫.png
text: Паразит «Серая Тень» 1
isActive: false
isVisible: if self.globalTeamTags(includes='寄生虫1')


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", greaterThan= 0.5) and self.energy(full=true)
isVisible: false
alsoQueueAction: b


[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 390 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true


[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 350 | setFlag= 0)


[action_b]
convertTo: 狂战士
displayType: action
price: 0
buildSpeed: 0.3s
isVisible: false

whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署


[action_换弹1]
autoTrigger: if self.energy(empty=true) and self.queueSize < 0.5
isVisible: false
alsoQueueAction: 换弹


[action_换弹]
#autoTrigger: if self.energy(empty=true) and self.queueSize < 0.5
isVisible: false
buildSpeed: 0.46s
alsoQueueAction: bx


[action_bx]
displayType: action
price: 0
buildSpeed: 1s
isVisible: false
whenBuilding_cannotMove: false

whenBuilding_playAnimation: 换弹
addEnergy: 2


[graphics]
image: 身体1.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 5

shadowOffsetY: 5
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 290
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_1]
x: 0
y: 0
canShoot: false


[turret_2]
x: 17
y: 59
invisible: true
shoot_sound: 枪.ogg
shoot_sound_vol: 0.2

shoot_light: #FFFFEB88
shoot_flame: CUSTOM:枪口火焰,CUSTOM:气浪*3,CUSTOM:弹壳,CUSTOM:烟雾2*2
projectile: 1
delay: 1
energyUsage: 1

onShoot_playAnimation: attack
attachedTo: 1
slave: true
warmup: 40
altProjectile: 炮弹

altProjectileCondition: if self.globalTeamTags(includes='寄生虫1')


[turret_3]
x: 11
y: 59
invisible: true
shoot_sound: 枪.ogg
shoot_sound_vol: 0.2

shoot_light: #FFFFEB88
shoot_flame: CUSTOM:枪口火焰,CUSTOM:气浪*4,CUSTOM:弹壳,CUSTOM:烟雾2*2
projectile: 1
delay: 1
attachedTo: 1

slave: true
warmup: 40
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='寄生虫1')
energyUsage: 1


[projectile_1]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1

frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定*10


[projectile_锁定]
@copyFromSection: template_动能
targetGround: true
areaDamage: 280
areaRadius: 35
life: 120

targetGroundSpread: 40
speed: 8
color: #FFFFFF73
drawSize: 1.8
largeHitEffect: true

gravity: 1
deflectionPower: -1
mutator3_ifUnitWithTags: 卧倒
mutator3_areaDamageMultiplier: 2
speedSpread: 1


[projectile_炮弹]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1

frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定1*10


[projectile_锁定1]
@copyFromSection: template_爆炸
targetGround: true
areaDamage: 310
areaRadius: 35
life: 120

targetGroundSpread: 40
speed: 8
color: #FF68FF2E
drawSize: 1.8
explodeEffect: CUSTOM:爆炸j,CUSTOM:闪光j

largeHitEffect: true
gravity: 1
deflectionPower: -1
mutator3_ifUnitWithTags: 卧倒
mutator3_areaDamageMultiplier: 2
tags: 灰影寄生虫
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: JSC=0.001
speedSpread: 1


[arm_1]
x: 9
y: -3
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 35
image_end_shadow: SHADOW:胳膊.png


[arm_2]
x: -15
y: 9
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: 10

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_3]
x: 29
y: 16
image_end: 手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -45
image_end_shadow: SHADOW:手.png


[arm_5]
x: 14
y: 29
image_end: 枪1.png
image_end_shadow: 枪1.png
image_end_teamColors: true

drawOverBody: true
#drawDirOffset:


[arm_7]
x: -8
y: 33
image_end: 手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 50
image_end_shadow: SHADOW:手.png


[arm_8]
x: 14
y: 29
image_end: 枪.png
image_end_shadow: SHADOW:枪.png
image_end_teamColors: true

drawOverBody: true
#drawDirOffset: -60
hidden: if self.isEnergyEmpty() and self.customTimer > 30


[arm_9]
#左肩
x: 0
y: 0
image_end: 身体1.png
image_end_teamColors: true

drawOverBody: true


[arm_10]
#左肩
x: 0
y: 0
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[leg_1]
x: -14
y: -1.5
attach_x: -1
attach_y: -1
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 胳膊.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 14
y: -1.5
attach_x: 1
attach_y: -1
copyFrom: 1

drawDirOffset: 10


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 3
scaleTo: 3


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6

yOffsetRelative: 0.8
ySpeedRelative: 1.5
atmospheric: true


[effect_弹壳]
#priority: low
image: 蛋壳.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.7
alpha: 2

fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
xSpeedRelative: -1.2
xSpeedRelativeRandom: -0.3
ySpeedRelativeRandom: 0.8
yOffsetRelative: -35

xOffsetRelative: -2
hSpeed: 2
dirSpeedRandom: 50


[animation_attack]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm5_0.05s: {x:0, y:-10, dir:0}
arm8_0.05s: {x:0, y:-10, dir:3}

arm7_0.05s: {x:0, y:-7, dir:0}


[animation_换弹]
#onActions: attack
arm7_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm7_0.65s: {x:2, y:0, dir:85}
arm2_0.65s: {x:0, y:7, dir:5}

arm7_1s: {x:2, y:0, dir:30}
arm2_1s: {x:0, y:0, dir:0}


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}

arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm1_0.3s: {x:0, y:-8, dir:0}
arm2_0.3s: {x:0, y:-8, dir:-20}
arm3_0.3s: {x:0, y:4, dir:-15}

arm5_0.3s: {x:-3, y:3, dir:-60}
arm7_0.3s: {x:-10, y:-6, dir:10}
arm8_0.3s: {x:-3, y:3, dir:-60}


[effect_烟雾2]
#priority:critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.8
scaleTo: 2.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: -0.7
ySpeedRelativeRandom: 0.35
xSpeedRelativeRandom: 0.4

yOffsetRelative: -35
atmospheric: true


[effect_爆炸j]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.5
image: ROOT:/太空浪人/单位特效/毒液.png
total_frames: 10

color: #FF68FF2E
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.3

alsoPlaySound: ROOT:/太空浪人/单位特效/血.ogg
alpha: 2


[effect_闪光j]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.8
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

targetHeight: 3
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4

slowDeathFall: true


