


[core]
name: 寡妇中介
displayText: 信标
strictLevel: 1
price: 0
radius: 10
maxHp: 1
canNotBeDirectlyAttacked: true
techLevel: 1
showInEditor: false
tags: 寡妇中介
canNotBeDamaged: true
explodeOnDeath: false
hideScorchMark: true
isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
fogOfWarSightRange: 30
#disableDeathOnZeroHp: true
isBuilding: true


[action_麻了]
displayType: action
price: 0
buildSpeed: 0
whenBuilding_cannotMove:true
canPlayerCancel: false
isVisible: false
autoTrigger:if not self.tags(includes='伸腿')
temporarilyAddTags: 伸腿
playAnimation: 部
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='寡妇中介')
deleteSelf: true
[action_删除]
displayType: action
price: 0
buildSpeed: 0
canPlayerCancel: false
isVisible: true
text:删除信标
deleteSelf: true
[hiddenAction_zz1]
autoTrigger:if not self.isInMap()
deleteSelf: true
showMessageToPlayer:不能在无效的区域放置信标
[hiddenAction_zz2]
autoTrigger:if self.isOverLiquid() and not self.isOverwater()
deleteSelf: true
showMessageToPlayer:不能在无效的区域放置信标
[hiddenAction_zz3]
autoTrigger: if numberOfUnitsInTeam(lessThan=1, withTag='黑寡妇之耀')
deleteSelf: true
[graphics]
image: NO.png



[attack]
canAttack: false
[arm_1]
x: 0
y: 0
image_end: 目标.png
drawUnderAllUnits: true
[arm_2]
x: 0
y: 0
image_end: 目标.png
drawUnderAllUnits: true
[arm_3]
x: 0
y: 0
image_end: 目标1.png
drawUnderAllUnits: true
[animation_部]
arm2_0s: {x:0, y:0, dir:0}
arm2_0.7s: {x:0, y:0, dir:90}
arm2_99999s: {x:0, y:0, dir:90}

arm3_0s: {x:0, y:0, dir:0,alpha:0}
arm3_1.2s: {x:0, y:0, dir:0,alpha:1}
arm3_99999s: {x:0, y:0, dir:0}

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
maxTurnSpeed: 0
targetHeight: 0

targetHeightDrift: 0


