
[core]
name: 寡妇1
displayText: Вдова1
displayDescription: 【Уровень t4】【Механический юнит】【Наземный юнит】【Беспилотный юнит】【伴随式дрон】【伴生юнит】【Амфибия】【Защита от тактического оружия】【Защита от стратегического оружия】\n-Тактическое назначение:护卫машинаустройство人，не может транспортироваться。вооружение：▲粉碎者X1 только по земле нейтральный урон \n-▲防空垂 单元X6 только по высотным взрывной урон \n-▲火神炮X2 только по воздуху взрывной урон\n-Сияние Чёрной Вдовы的禁卫无人单元，虽说是无人单元，\n-но仰仗母体мощныйпроизводить力，оснащённый的огневая мощьтакже超越了大部分主战юнит，\n-одновременно，得益于Сияние Чёрной Вдовыболее大体 带来的более多может无线输出的电力，\n-Вдовадронможет直接在母体指挥下с蜂群тактика攻击враг，\n-номожет源输出依然仰仗母体，поэтому在母体被击毁后会陷入破坏性停машина。
price: 5000
showInEditor: false
maxHp: 25000
selfRegenRate: 1
armour: 70
techLevel: 1
buildSpeed: 1s
radius: 60
displayRadius: 60
fogOfWarSightRange: 33
isBio: false
softCollisionOnAll: 80
transportSlotsNeeded: 200
energyNeedsToRechargeToFull: true
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 60
energyRegen: 0
dieOnZeroEnergy: false
unitsSpawnedOnDeath: 损毁3*1
tags: 地面,寄生免疫,伴生单位,无人单位
canNotBeGivenOrdersByPlayer: true
[hiddenAction_zz1]
autoTrigger:if not self.isInMap
addResources: hp= -999999

[hiddenAction_zz2]
autoTrigger:if self.isOverLiquid() and not self.isOverwater()
isVisible: false
addResources: hp=-999999
[action_麻了]
displayType: action
price: 0
buildSpeed: 0
whenBuilding_cannotMove:true
canPlayerCancel: false
isVisible: false
alsoQueueAction: 虫丰
autoTrigger:if not self.tags(includes='伸腿')
temporarilyAddTags: 伸腿
[action_虫丰]
convertTo: 寡妇
displayType: action
whenBuilding_playAnimation: 部
price: 0
buildSpeed: 3s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 虫丰
convertTo_keepCurrentFields:maxHp
convertTo_keepCurrentTags:true
[attachment_1]
x: 0
y: 0
onCreateSpawnUnitOf: 寡妇附属物
lockRotation: false
prioritizeParentsMainTarget: true
resetRotationWhenNotAttacking: true
alwaysAllowedToAttackParentsMainTarget: false
setDrawLayerOnTop:true
idleDir:0


[decal_炮塔]
image: 粉碎机.png
total_frames: 4
frame: (self.customTimer * 28) % 4
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:true
onlyWhileAlive:true
layer: afterBody
yOffsetRelative:74
xOffsetRelative:0


[graphics]
total_frames: 1
image: 寡妇.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 7
shadowOffsetY: 7

[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 1
maxAttackRange: 28
shootDelay: 1
#turretRotateWithBody: true
isFixedFiring: true

isMelee: true
#turretMultiTargeting: true


[turret_1]
x: 0
y: 0
canShoot: false
#image:主体.png


[turret_2]
x: 0
y: 0
invisible: true
delay: 1
projectile: 1
canAttackFlyingUnits: false
turnSpeed: 100
turnSpeedAcceleration: 0.07
shoot_sound: ROOT:/创世纪军事集团/单位特效/电锯.ogg
shoot_flame: CUSTOM:火花*2,CUSTOM:火花1,CUSTOM:闪光
canShoot: true
size: 80
attachedTo: 1
slave: true



[projectile_1]
life: 5000
areaDamageNoFalloff: true
areaDamage: 70
areaRadius: 50
instant: true

speed: 10
targetSpeed: 10
explodeEffect: NONE
areaRadiusFromEdge: true
armourIgnoreAmount: 1000
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[projectile_2]
areaDamage: 0
areaRadius: 0
life: 120
speed: 18
targetSpeed: 22
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 0.8
largeHitEffect: true
deflectionPower: -1
trailEffectRate: 0.2

[arm_1]
x: 0
y: 0
image_end:寡妇1.png
image_end_teamColors:true
drawOverBody: true
[arm_2]
x: 0
y: -11
image_end:上.png
image_end_teamColors:true
drawOverBody: true
[arm_3]
x: 0
y: -19
image_end:下.png
image_end_teamColors:true
drawOverBody: true
[arm_4]
x: 0
y: 0
image_end:寡妇.png
image_end_teamColors:true
drawOverBody: true
[arm_5]
x: 0
y: 0
image_end:灯光.png
image_end_teamColors:true
drawOverBody: true

[arm_7]
x: 0
y: -45
image_end: 雷达.png
drawOverBody: true
spinRate: 4
[animation_舱盖]
arm2_1s: {x:0, y:9}
arm3_1s: {x:0, y:-9}
[effect_火花]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.35
physics: true

xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: 光束.png
alpha: 0.85
xOffsetRelativeRandom:40
yOffsetRelativeRandom:10

[effect_火花1]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.15
scaleTo: 0.33
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12

animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.85
xOffsetRelativeRandom:15
yOffsetRelativeRandom:5
physics: true
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 7
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false
#————————————
[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1.5
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1

[leg_1]
x: 0
y:0
attach_x: -4
attach_y: 10
moveSpeed: 2
rotateSpeed: 3
heightSpeed: 0.45
moveWarmUp: 4
resetAngle: 10
holdDisMin: 10
holdDisMax: 35
image_leg: 小腿.png
image_foot: 小脚.png
endDirOffset: -40
hardLimit: 25
favourOppositeSideNeighbours: true


[leg_2]
x: 0
y: 0
attach_x: 4
attach_y: 10
copyFrom: 1


[leg_3]
x: 0
y: 0
attach_x: -7
attach_y: -5
copyFrom: 1


[leg_4]
x: 0
y: 0
attach_x: 7
attach_y: -5
copyFrom: 1
[leg_5]
x: 0
y: 0
attach_x: -12
attach_y: 10
copyFrom: 1

endDirOffset: -90


[leg_6]
x: 0
y: 0
attach_x: 12
attach_y: 10
copyFrom: 1

endDirOffset: 90
[animation_部]
leg1_0s: {x:0, y:0, dir:0}
leg1_0.5s: {x:-55, y:65, dir:0}
leg1_3s: {x:-55, y:65, dir:0}

leg2_0s: {x:0, y:0, dir:0}
leg2_1s: {x:55, y:65, dir:0}
leg2_3s: {x:55, y:65, dir:0}

leg5_0s: {x:0, y:0, dir:0}
leg5_1.5s: {x:-69, y:10, dir:0}
leg5_3s: {x:-69, y:10, dir:0}

leg6_0s: {x:0, y:0, dir:0}
leg6_2s: {x:69, y:10, dir:0}
leg6_3s: {x:69, y:10, dir:0}

leg3_0s: {x:0, y:0, dir:0}
leg3_2.5s: {x:-55, y:-45, dir:0}
leg3_3s: {x:-55, y:-45, dir:0}

leg4_0s: {x:0, y:0, dir:0}
leg4_3s: {x:55, y:-45, dir:0}

[movement]
movementType: OVER_CLIFF_WATER
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0
moveSlidingMode: false
moveIgnoringBody: false


