





[core]
name: 黑曜石
displayDescription: -在诺瓦帝国时期，黑曜石本是高科技工厂里的重型工业机器人，\n-他们平时的任务就是搬运重物，以及其他重型作业。\n-在诺瓦帝国末期，当余辉攻陷维基兰特III星时，\n-绝望中的人们用工厂中的纳米材料，为黑曜石锻造了大量单分子巨斧，\n-他们将军事化控制软件覆盖了黑曜石机甲的原有系统，并改造了动力原件，\n-使其变成了一种军事化改造的民用机械人，这往往是古人类与余辉作战的最后手段。\n-他们驾驶着黑曜石埋伏在隐蔽的洞穴或者废墟中，等到余辉陷入自己的埋伏时，\n-在角落里静候的黑曜石便会一拥而上，用手中的单分子巨斧将余辉砍成废铁。\n-据统计，黑曜石挥舞巨斧产生的冲击力足以击碎绝大部分轻型护盾，\n-并如同砍瓜切菜一般将余辉的超合金护甲劈成两半，\n-只能对地。中性伤害。反掩体。
class: CustomUnitMetadata
price: 6000
maxHp: 11000
techLevel: 1
buildSpeed: 25s
radius: 37

isBio: false
transportSlotsNeeded: 3
#armour:10
copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.2

unitsSpawnedOnDeath: 损毁*1
tags: 地面,射程x

[action_1_亚空间]
text: 越入亚空间
displayType: action
buildSpeed: 0s
pos: 0.1
#displayRemainingStockpile: true

highPriorityQueue: true
price: 0
canPlayerCancel: false
isLocked: if self.resource.xk > 0 or self.resource.JB<3 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
#displayRemainingStockpile: true

#onlyOneUnitAtATime: true
description: 开启亚空间引擎，\n-进入亚空间潜行状态。
isVisible: if self.globalTeamTags(includes='亚空间1')
convertTo: 黑曜石1
playSoundAtUnit: ROOT:/余辉军团/单位特效/瓶.ogg

iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/亚空间.png


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: 赛格门塔护甲1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_JB]
autoTrigger: if self.resource.JB<3
isVisible: false
#addResources=JB=5
addResources: JB=0.1



[hiddenAction_DPS]
alsoQueueAction: DPS1
isLocked: if self.resource.awz<0


[hiddenAction_DPS1]
buildSpeed: 0.5s
fireTurretXAtGround: 伤害
whenBuilding_cannotMove: true
fireTurretXAtGround_withOffset: 0, 85
isLocked: if self.resource.awz<0

#size: 1
#attachedTo:1
#slave:true


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
imageScale: 1
teamColorsOnTurret: true
drawLayer: ground2


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 35

turretTurnSpeed: 1
maxAttackRange: 55
isFixedFiring: true
isMelee: true


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-150
projectile: 13
delay: 120

size: 0
#limitingRange:280


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_1]
invisible: true
x: 0
y: 0
size: 14
idleDir: 0

turnSpeed: 9.0
turnSpeedAcceleration: 0.08
canShoot: false
#shouldResetTurret: false


[turret_2]
x: 0
y: 0
invisible: true
delay: 1.1s
projectile: 2

turnSpeed: 100
turnSpeedAcceleration: 0.07
shoot_sound: NONE
onShoot_playAnimation: attack
canShoot: true

canAttackCondition: if self.resource.xk < 1
#warmup:20
size: 1
attachedTo: 1
onShoot_triggerActions: DPS

slave: true


[turret_伤害]
invisible: true
x: 0
attachedTo: 1
slave: true
y: 0

size: 0
turnSpeed: 4
turnSpeedAcceleration: 4
canShoot: false
projectile: 1


[arm_5]
x: 0
y: 15
image_end: 刀.png
#image_end_shadow:斧子.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: 30


[arm_9]
#左肩
x: 0
y: 0
image_end: 身子.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:身子.png


[arm_10]
#左肩
x: 0
y: 0
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[leg_1]
x: -9
y: 5
attach_x: -8
attach_y: -1
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 8
y: 5
attach_x: 8
attach_y: -1
copyFrom: 1

drawDirOffset: 10


[projectile_2]
directDamage: 0
life: 2
instant: true
explodeEffect: NONE


[projectile_1]
life: 5000
areaDamage: 1600
areaRadius: 70
instant: true
speed: 10

targetSpeed: 10
explodeEffect: CUSTOM:刀光*1,CUSTOM:聚变*1,CUSTOM:闪光h*1,CUSTOM:粒子1*13
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_刀光]
priority: critical
image: 刀光.png
spawnChance: 1
createWhenZoomedOut: false
life: 40

fadeOut: true
attachedToUnit: false
color: #FFFF1200
fadeInTime: 10
scaleFrom: 1

scaleTo: 1.8
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
#hSpeed: 0.01

#dirOffsetRandom:180
#ySpeedRelativeRandom: 0.1
#xSpeedRelativeRandom: 0.6
yOffsetRelative: 0
ySpeedRelative: 1

atmospheric: false
alsoPlaySound: ROOT:/通用特效/光剑1.ogg


[effect_闪光h]
#priority:critical
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.3
drawUnderUnits: false
atmospheric: false

#ySpeedAbsolute:-1
#yOffsetAbsolute:35


[effect_粒子1]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color:#FFFF1200
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom: 0.1
scaleTo: 0.28

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3

ySpeedRelative: 2
ySpeedRelativeRandom: 1
#atmospheric: true


[animation_move]
onActions: move
#blendIn: 0.05s
#blendOut: 0.05s
arm5_0.5s: {x:0, y:0, dir:-5}
arm5_1s: {x:0, y:0, dir:5}


[animation_attack]
#onActions: attac
blendIn: 0.05s
blendOut: 0.05s
arm5_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}

arm5_0.45s: {x:-5, y:6, dir:-50}
arm9_0.45s: {x:0, y:0, dir:-40}
arm5_0.65s: {x:12, y:-11, dir:65}
arm9_0.65s: {x:0, y:0, dir:60}
arm5_0.8s: {x:0, y:0, dir:0}

arm9_0.8s: {x:0, y:0, dir:0}


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: OVER_CLIFF
targetHeight: 3
moveSpeed: 1.9
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1

maxTurnSpeed: 2.5
turnAcceleration: 0.1
moveSlidingMode: false
moveIgnoringBody: true


