





[core]
name: 黑曜石1
displayText: «Обсидиан»
displayDescription: -Во времена Империи Нова «Обсидиан» был тяжёлым промышленным роботом на высокотехнологичных заводах,\n-их обычной задачей была перевозка тяжестей и другая тяжёлая работа.\n-В конце Империи Нова, когда Зарево захватило планету Викилант III,\n-в отчаянии люди выковали из заводских наноматериалов огромные мономолекулярные топоры для «Обсидианов».\n-Они переписали оригинальную систему меха «Обсидиан» военизированным управляющим ПО и переделали силовую установку,\n-превратив его в военизированный гражданский робот. Это часто было последним средством Древних Людей в борьбе с Заревом.\n-Они на «Обсидианах» устраивали засады в скрытых пещерах и руинах. Когда Зарево попадало в засаду,\n-«Обсидианы», тихо ждавшие в углу, разом нападали и мономолекулярными топорами рубили войска Зарева в металлолом.\n-По статистике, удар топора «Обсидиана» способен разбить большинство лёгких щитов\n-и разрубить суперсплавную броню Зарева пополам, как ножом по тыкве.\n-Атакует только землю. Нейтральный урон, пробивает укрытия.
class: CustomUnitMetadata
price: 6000

maxHp: 11000
techLevel: 1
buildSpeed: 20s

radius: 37
isBio: false
armour: 99999
armourMinDamageToKeep: 0
canNotBeDirectlyAttacked: true

transportSlotsNeeded: 9999
#armour:10
copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.2
unitsSpawnedOnDeath: 损毁*1

tags: 衰解免疫,寄生免疫,jabzhdja,射程x
showInEditor: false

[hiddenAction_打断]
autoTrigger:if self.hasParent
disconnectFromParent: true

[action_超空间已开启]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/亚空间.png
text: Подпространственная скрытность активна
isActive: false
isVisible: true


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: Броня «Сегмента» 1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_JBx]
autoTrigger: if self.resource.JB<0.5
isVisible: false
convertTo: 黑曜石


[action_JB]
autoTrigger: if self.resource.JB>0
isVisible: false
#addResources=JB=5
addResources: JB=-0.5


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: Недостаточно тёмной материи
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_DPS]
alsoQueueAction: DPS1
isLocked: if self.resource.awz<0


[hiddenAction_DPS1]
buildSpeed: 0.5s
fireTurretXAtGround: 伤害
whenBuilding_cannotMove: true
fireTurretXAtGround_withOffset: 0, 85
isLocked: if self.resource.awz<0

#size: 1
#attachedTo:1
#slave:true


[hiddenAction_↯ab]
autoTrigger: if self.resource.xk > 0 or self.tags(includes= '↯')
isActive: false
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= 0


[graphics]
total_frames: 1
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
imageScale: 1
teamColorsOnTurret: true
drawLayer: ground2

movementEffectRate: 1
movementEffect: CUSTOM:粒子y*2


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 35

turretTurnSpeed: 1
maxAttackRange: 55
isFixedFiring: true
#isMelee: true


[turret_1]
invisible: true
x: 0
y: 0
size: 14
idleDir: 0

turnSpeed: 9.0
turnSpeedAcceleration: 0.08
canShoot: false
#shouldResetTurret: false


[turret_2]
x: 0
y: 0
invisible: true
delay: 1.1s
projectile: 2

turnSpeed: 100
turnSpeedAcceleration: 0.07
shoot_sound: NONE
onShoot_playAnimation: attack
canShoot: true

canAttackCondition: if self.resource.xk < 1
#warmup:20
size: 1
attachedTo: 1
onShoot_triggerActions: DPS

slave: true


[turret_伤害]
invisible: true
x: 0
attachedTo: 1
slave: true
y: 0

size: 0
turnSpeed: 4
turnSpeedAcceleration: 4
canShoot: false
projectile: 1


[arm_5]
x: 0
y: 15
image_end: 刀1.png
#image_end_shadow:斧子.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: 30


[arm_9]
#左肩
x: 0
y: 0
image_end: 身子1.png
image_end_teamColors: true

drawOverBody: true
#image_end_shadow:SHADOW:身子.png


[arm_10]
#左肩
x: 0
y: 0
image_end: 头.png
image_end_teamColors: true

drawOverBody: true
hidden: true


[leg_1]
x: -9
y: 5
attach_x: -8
attach_y: -1
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿1.png

image_foot: 脚1.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 8
y: 5
attach_x: 8
attach_y: -1
copyFrom: 1

drawDirOffset: 10


[projectile_2]
directDamage: 0
life: 2
instant: true
explodeEffect: NONE


[projectile_1]
life: 5000
areaDamage: 1600
areaRadius: 70
instant: true
speed: 10

targetSpeed: 10
explodeEffect: CUSTOM:刀光*1,CUSTOM:聚变*1,CUSTOM:闪光h*1,CUSTOM:粒子1*13
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_刀光]
priority: critical
image: 刀光.png
spawnChance: 1
createWhenZoomedOut: false
life: 40

fadeOut: true
attachedToUnit: false
color: #FFFF1200
fadeInTime: 10
scaleFrom: 1

scaleTo: 1.8
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
#hSpeed: 0.01

#dirOffsetRandom:180
#ySpeedRelativeRandom: 0.1
#xSpeedRelativeRandom: 0.6
yOffsetRelative: 0
ySpeedRelative: 1

atmospheric: false
alsoPlaySound: ROOT:/通用特效/光剑1.ogg


[effect_闪光h]
#priority:critical
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.3
drawUnderUnits: false
atmospheric: false

#ySpeedAbsolute:-1
#yOffsetAbsolute:35


[effect_粒子1]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color:#FFFF1200
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom: 0.1
scaleTo: 0.28

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3

ySpeedRelative: 2
ySpeedRelativeRandom: 1
#atmospheric: true


[animation_move]
onActions: move
#blendIn: 0.05s
#blendOut: 0.05s
arm5_0.5s: {x:0, y:0, dir:-5}
arm5_1s: {x:0, y:0, dir:5}


[animation_attack]
#onActions: attac
blendIn: 0.05s
blendOut: 0.05s
arm5_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}

arm5_0.45s: {x:-5, y:6, dir:-50}
arm9_0.45s: {x:0, y:0, dir:-40}
arm5_0.65s: {x:12, y:-11, dir:65}
arm9_0.65s: {x:0, y:0, dir:60}
arm5_0.8s: {x:0, y:0, dir:0}

arm9_0.8s: {x:0, y:0, dir:0}


[effect_粒子y]
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/方块.png
scaleFrom: 0.7
scaleTo: 1.3

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 1

ySpeedRelativeRandom: 1.2
#atmospheric: true


[movement]
movementType: OVER_CLIFF
targetHeight: 3
moveSpeed: 1.9
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1

maxTurnSpeed: 2.5
turnAcceleration: 0.1
moveSlidingMode: false
moveIgnoringBody: true


