


[core]
name: 胡蜂无人机
displayText: Дрон «Шершень»
class: CustomUnitMetadata
displayDescription: -Дрон «Шершень» среди Скитальцев в шутку называют «торпедой с крыльями».\n-По сравнению с обычной торпедой, дрон «Шершень» имеет большую дальность и мощь,\n-его встроенная высококонцентрированная плазма способна пробить дыру даже в самой прочной броне.\n-При тактике внезапного нападения дрон «Шершень» всегда наносит врагу серьёзный урон.\n-Атакует землю и воздух, самоубийственная атака, энергетический урон.
price: 800
maxHp: 500

techLevel: 1
buildSpeed: 6s
availableInDemo: true
radius: 18
copyFrom: ROOT:/通用特效/单位防护.ini

explodeOnDeath: false
hideScorchMark: true
displayRadius: 14
isBio: false
selfRegenRate: 0.2
fogOfWarSightRange: 11
softCollisionOnAll: 10
tags: 飞机,低空
numBitsOnDeath: 0
energyMax: 1
energyRegen: 0


[action_爆散1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: Детонационная боеголовка 1
isActive: false
isVisible: if self.globalTeamTags(includes='爆散1')


[action_t1]
autoTrigger: if self.energy(empty=true)
isVisible: false
deleteSelf: true


[graphics]
total_frames: 1
image: 主体.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.8
movementEffect: CUSTOM:火
movementEffectRate: 0.7


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
#aimOffsetSpread:1

turretSize: 20
turretTurnSpeed: 1.5
isMelee: true
maxAttackRange: 160
shootDelay: 30

dieOnAttack: true
attackMovement: bomber


[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir: 0

canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shoot_sound: NONE
shoot_sound_vol: 0.3

projectile: 1
size: 1.1
turnSpeed: 2
energyUsage: 1
altProjectile: 炮弹

altProjectileCondition: if self.globalTeamTags(includes='爆散1')


[projectile_1]
@copyFromSection: template_能源
life: 250
speed: 5
targetSpeed: 10
areaDamage: 1800

areaRadius: 55
drawSize: 1
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:弹坑,CUSTOM:冲击波,CUSTOM:聚变
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:弹坑,CUSTOM:冲击波,CUSTOM:聚变
deflectionPower: -1

areaRadiusFromEdge: true
image: 主体.png
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_炮弹]
@copyFromSection: template_爆炸
life: 250
speed: 5
targetSpeed: 10
areaDamage: 2000

areaRadius: 55
drawSize: 1
explodeEffect: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:粒子b*12,CUSTOM:冲击波b,CUSTOM:聚变b,CUSTOM:溅射b
explodeEffectOnShield: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:粒子b*12,CUSTOM:冲击波b,CUSTOM:溅射b
deflectionPower: -1

areaRadiusFromEdge: true
image: 主体.png
spawnProjectilesOnExplode: m2(yOffsetRelative= 20)
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0


[projectile_m2]
@copyFromSection: template_爆炸
life: 1
deflectionPower: -1
explodeOnEndOfLife: true
speed: 0

turnSpeed: 0.0
areaDamage: 200
areaRadius: 40
areaRadiusFromEdge: true
targetGround: true

invisible: true
explodeEffect: CUSTOM:爆炸b1
spawnProjectilesOnCreate: m2(recursionLimit= 10, yOffsetRelative= 15)
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.38
scaleTo: 0.58

image: ROOT:/太空浪人/单位特效/核弹.png
total_frames: 21
animateFrameStart: 0
animateFrameEnd: 21
animateFramePingPong: false

animateFrameSpeed: 0.27
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
#color: #FFFF1200


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1.4
scaleTo: 1.4
createWhenOverLiquid: false
createWhenOverLand: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.6
scaleTo: 1.6
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 3.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -13

#——————————————————


[effect_爆炸b]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.38
scaleTo: 0.58

image: ROOT:/太空浪人/单位特效/核弹1.png
total_frames: 21
animateFrameStart: 0
animateFrameEnd: 21
animateFramePingPong: false

animateFrameSpeed: 0.27
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
#color: #FFFF1200


[effect_闪光b]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_粒子b]
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子.png
scaleFrom: 0.1
scaleTo: 0.3

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2.2

ySpeedRelativeRandom: 2.6
#atmospheric: true


[effect_冲击波b]
#priority:critical
image: ROOT:/太空浪人/单位特效/冲击波3.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_聚变b]
priority: critical
image: ROOT:/太空浪人/单位特效/火光1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.9
scaleTo: 0.9
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
#color:#FFFF120


[effect_溅射b]
life: 100
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.6
image: ROOT:/太空浪人/单位特效/爆散.png
total_frames: 9

animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.2
alpha: 1

atmospheric: false
#color:#FFFF1200


[effect_爆炸b1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/太空浪人/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
#color:#FFFF1200


[movement]
movementType: AIR
moveSpeed: 1.8
moveAccelerationSpeed: 0.04
moveDecelerationSpeed: 0.004
#landOnGround: onlyIdle

joinsGroupFormations: false
maxTurnSpeed: 1.8
turnAcceleration: 0.06
moveSlidingMode : false
moveIgnoringBody: false

targetHeight: 70
slowDeathFall: false


