


[core]
name: 镭射炮塔t4
displayText: Лазерная башняt4
class: CustomUnitMetadata
price: 8250,钍=178
maxHp: 20000

footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 20
techLevel: 1
fogOfWarSightRange: 34
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 10s
radius: 16
buildingSelectionOffset: -8
armour:35

isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1,largeExplosion*1
tags: 地面,建筑,防御建筑
energyMax: 120
energyRegen: 0
energyRegenWhenRecharging: 0.6
energyNeedsToRechargeToFull: true
displayDescription: 【Уровень t4】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение：противгруппабронябашня。вооружение：\n-▲扫射 лазерная пушкаX1 только по земле энергетический урон пробивает укрытия против护盾 крайне端тяжёлыйюнитслабый эффект\n-использоватьреальный验тип透镜технологиясреактор结合астановиться ，\n-直соединять喷射тепло熔毁свет束уничтожатьцель реальный验пушка ，\n-нонуждаетсяВнимание，этот видпушка два次射удармеждудолжен充может，\n-иитолькопротивброняэффективный。
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/t4影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
alpha:0.65
[decal_灯光]
image: ROOT:/创世纪军事集团/建筑特效/led.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:-3
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.85
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/大支撑.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-30
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.9
alpha:0.9
[hiddenAction_创造]
autoTrigger: if attachment(slot= '1') == nullUnit
attachments_onlyOnSlots: 1
attachments_addNewUnits:激光炮塔中介1
[attachment_1]
x: 0
y: 38
onCreateSpawnUnitOf: 激光炮塔中介1
# 激光炮塔
lockRotation: false
prioritizeParentsMainTarget: true
resetRotationWhenNotAttacking: true
alwaysAllowedToAttackParentsMainTarget: true
isUnselectable: true
idleDir: 90
[graphics]
total_frames: 1
image: ROOT:/创世纪军事集团/建筑特效/防御塔t4底座.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_offsetY: 1

image_back: ROOT:/通用特效/NO.png
#AUTO
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 6
maxAttackRange: 650
shootDelay: 0
aimOffsetSpread: -0.01
[turret_2]
x: 0
y: 38
canAttack: false
limitingMinRange: 25
invisible: if self.numberOfAttachedUnits(greaterThan= 0)
image:镭射炮.png
# 让建造界面显示时有炮塔


[turret_1]
x: 0
y: 0
attachedTo: 2
projectile: 1

invisible: true
slave: true
shoot_sound: NONE
shoot_sound_vol: 0.5
shoot_flame: NONE
canShoot: true
energyUsage: 1.3
shoot_light: #FFFF1200
canAttackCondition: if self.resource.xk < 1


[turret_3]
x: 0
y: 0
attachedTo: 2
projectile: 2
turnSpeed: 2

turnSpeedAcceleration: 1.0
shoot_sound: ROOT:/通用特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 180
canShoot: true

invisible: true
canAttackCondition: if self.resource.xk < 1 or not self.isEnergyRecharging


[projectile_1]
@copyFromSection: template_能源
directDamage: 20
life: -4
instant: true
frame: 33

explodeEffect: none
explodeEffectOnShield: NONE
beamImage: 光.png
beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
#FFFF1200
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.8
mutator7_areaDamageMultiplier: 0.8
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
shieldDamageMultiplier: 0.75
[projectile_2]
directDamage: 0
life: 0
frame: 33
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0

turnAcceleration: 0


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


