[core]
name: 创世纪指挥中心t4
displayText: Командный центр Генезисаt4
price: 30000
maxHp: 110000
footprint: -5,-2,5,4
constructionFootprint: -5,-2,5,4
tags: 创世纪指挥中心t3,创世纪指挥中心t2,地面,创世纪指挥中心t4,建筑,反高空
techLevel: 1
displayDescription: 【Уровень t4】【Здание】【Наземный юнит】\n-Тактическое назначение: ключевое здание.вооружение：\n-▲ракетный отсекX6 по земле и воздуху对 взрывной урон。\n-▲ВПУ зенитных ракетX1 только по высотным взрывной урон\n-Стандартный быстро развёртываемый передовой командный центр Генезиса。\n-Уровень командного центра напрямую определяет максимум всех аспектов армии，\n-одновременно，Командный центр также напрямую управляет действиями армии Генезиса，\n-Поэтому командный центр — наиболее ключевое и требующее защиты здание。
buildSpeed: 0.0005
experimental: true
unitsSpawnedOnDeath: 创世纪指挥中心t4残骸*1,建筑损毁*1
selfBuildRate: 1
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
armour: 70
radius: 90
fogOfWarSightRange: 38
energyMax: 12
energyRegen: 0.0015
energyNeedsToRechargeToFull: false
generation_delay: 40
generation_credits: 65
effectOnDeath: CUSTOM:烟雾*3, CUSTOM:爆破*5,largeExplosion*3
exit_x:-46
exit_y: 74

canBuild_11_name: setRally
canBuild_11_pos: 0.1
[canBuild_T33]
name:爪巴
pos: 1
isVisible: false
isLocked: true
isLockedMessage:🐴
[action_造苦工]
displayType: action
price: 500
buildSpeed: 11s
isVisible: true
highPriorityQueue: false
produceUnits:苦工机器人(spawnSource= self.getOffsetRelative(x= 46, y= 74,dirOffset=180))
whenBuilding_playAnimation: 部署
unitShownInUI: 苦工机器人
textAddUnitName: 苦工机器人
descriptionAddFromUnit: 苦工机器人
descriptionAddUnitStats: 苦工机器人
allowMultipleInQueue:true
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_ai无限补给]
autoTrigger: if self.isControlledByAI() and not self.tags(includes= '保险啊啊')
isVisible: false
temporarilyAddTags:保险啊啊
addResources: bj=9999
[action_雷达]
text: Радарное сканирование
allowMultipleInQueue: false
description: -Прикажите высотному разведчику просканировать землю，\n-Открывает обзор в целевой зоне на 5,5 секунд。
iconImage: ROOT:/通用特效/雷达.png
buildSpeed: 0s
price: energy=3
fireTurretXAtGround: 雷达
highPriorityQueue: true
isVisible: true
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_空投]
text: Пехотный десантный модуль
allowMultipleInQueue: false
description: -Прикажите транспортнику сбросить десантный модуль на поле боя，\n-Содержит отделение десантников со штандартом и Осадный конус MKII。
iconImage: 小空投.png
buildSpeed: 0s
price: energy=12
highPriorityQueue: true
fireTurretXAtGround: 小空投
fireTurretXAtGround_onlyOverPassableTileOf: BUILDING
isVisible: true
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_空...投1]
text: Десантный модуль с дронами
allowMultipleInQueue: false
description: -Прикажите транспортнику сбросить десантный модуль на поле боя，\n-Содержит три ремонтных дрона。
iconImage: 修复.png
buildSpeed: 0s
price: energy=8
highPriorityQueue: true
fireTurretXAtGround: 空投
fireTurretXAtGround_onlyOverPassableTileOf: BUILDING
isVisible: true
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)


[action_造标旗]
displayType: action
price: 600
buildSpeed: 5s
isVisible: true
highPriorityQueue: false
produceUnits:标旗空降兵(spawnSource= self.getOffsetRelative(x= 46, y= 74,dirOffset=180))
whenBuilding_playAnimation: 部署1
unitShownInUI: 标旗空降兵
textAddUnitName: 标旗空降兵
descriptionAddFromUnit: 标旗空降兵
descriptionAddUnitStats: 标旗空降兵
allowMultipleInQueue:true

[decal_地板]
image: ROOT:/创世纪军事集团/建筑特效/老家地.png
total_frames: 1
layer: shadow
yOffsetRelative:-25
xOffsetRelative:0.5
onlyWhileAlive:true
isVisible:true
imageScale: 0.79
[decal_影子]
image: SHADOW:老家.png
total_frames: 1
layer: shadow
yOffsetRelative:52
xOffsetRelative:14
onlyWhileAlive:true
isVisible:true
imageScale: 0.8
alpha:0.5

[decal_遮盖]
image:老家遮盖.png
total_frames: 1
layer: onTop
yOffsetRelative:50
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
imageScale: 0.8
teamColors: true
[decal_损坏]
image: 老家损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:50
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.hp<self.maxHp * 0.36
teamColors: true
imageScale: 0.8

[decal_雷达2]
image: SHADOW:ROOT:/创世纪军事集团/建筑特效/老家雷达.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:116
xOffsetRelative:57
onlyWhileAlive:true
dirOffset:45
imageScale: 0.8
alpha:0.5
[decal_雷达]
image: ROOT:/创世纪军事集团/建筑特效/老家雷达.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.maxHp * 0.36< self.hp
yOffsetRelative:114
xOffsetRelative:54
onlyWhileAlive:true
dirOffset:45
imageScale: 0.8

[decal_雷达1]
image: ROOT:/创世纪军事集团/建筑特效/老家雷达损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:114
xOffsetRelative:54
onlyWhileAlive:true
dirOffset:45
imageScale: 0.8

[decal_灯光]
image: 红灯.png
total_frames: 1
layer: onTop
yOffsetRelative:50
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
imageScale: 0.8

[decal_灯光1]
image: 白灯.png
total_frames: 1
layer: onTop
yOffsetRelative:50
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
imageScale: 0.8
alpha:0.8
[graphics]
total_frames: 1
image: 老家.png
image_back: ROOT:/通用特效/NO.png
image_wreak:ROOT:/通用特效/NO.png
image_turret: NONE
imageScale: 0.8
turretImageScale: 0.75
showShotDelayBar:false
image_offsetY: -50
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
maxAttackRange: 99999
turretTurnSpeed: 50
turretMultiTargeting: true
[turret_雷达]
x: 0
y: 0
projectile: 雷达
#limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true
shoot_sound: ROOT:/通用特效/扫描.ogg
shoot_sound_vol: 1
[turret_小空投]
x: 0
y: 0
projectile: 小空投
#limitingRange: 99999
#limitingMinRange: 300

canAttack: false
invisible: true
[turret_空投]
x: 0
y: 0
projectile: 空投
#limitingRange: 99999
#limitingMinRange: 300

canAttack: false
invisible: true




[turret_1]
x: -48
y: 0
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.15
shoot_flame: CUSTOM:烟雾x*3
shoot_light: #FFEECCCC
canShoot: true
size:7
delay:120
limitingRange: 600
image:导导.png
idleDir: 180
limitingAngle: 55
canOnlyAttackUnitsWithoutTags:高空
turnSpeed: 2.5
turnSpeedAcceleration: 0.2
[turret_2]
x: 50
y: 0
#主炮
copyFrom: 1


[turret_3]
x: 50
y: 60
#主炮
copyFrom: 1
idleDir: 360

[turret_4]
x: -48
y: 60
#主炮
copyFrom: 1
idleDir: 360

[turret_5]
x: -95
y: 18
#主炮
copyFrom: 1
idleDir: -90
delay:90
limitingAngle: 60

[turret_6]
x: 95
y: 18
#主炮
copyFrom: 1
idleDir: 90
delay:90
limitingAngle: 60

[turret_7]
x: -5
y: 20
canShoot: true
idleDir: 0
invisible: true
size: 0
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:烟雾1*4
projectile: 3
delay: 400
canAttackCondition: if self.resource.xk < 1
canAttackFlyingUnits: true
canAttackLandUnits:false
canOnlyAttackUnitsWithTags:高空
limitingRange: 700

[turret_8]
x: 5
y: 20
#主炮
copyFrom: 7
delay:380
warmup:20

[turret_9]
x: -5
y: 25
#主炮
copyFrom: 7
delay:360
warmup:40

[turret_10]
x: 5
y: 25
copyFrom: 7
delay:340
warmup:60
[turret_x]
x: 0
y: 0
projectile: x
shoot_sound: NONE
shoot_sound_vol: 0
shoot_flame: NONE
canShoot: true
size:0
delay:9999s
invisible: true
[projectile_1]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 2*3

[projectile_x]
life: 0
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
explodeEffect:NONE
[projectile_2]
@copyFromSection: template_爆炸
speedSpread:2
life: 420
speed: 3
targetSpeed: 9
directDamage: 300
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 0.8
trailEffect: true
lightSize: 0.75
trailEffectRate: 2.5
wobbleAmplitude: 2.5
wobbleFrequency: 150
turnSpeed: 30
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
[projectile_3]
@copyFromSection: template_爆炸
life: 600
speed: 8
targetSpeed: 13
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 700
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
explodeOnEndOfLife: true
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:钢珠
trailEffectRate: 0.8
[projectile_雷达]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 雷达(offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none
[projectile_小空投]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 单位空降仓(gridAlign= true,offsetHeight= 2000)
explodeEffect: none
explodeEffectOnShield: none
[projectile_空投]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 无人机空降仓(gridAlign= true,offsetHeight= 2000)
explodeEffect: none
explodeEffectOnShield: none
#——————————防空开火
[effect_烟雾1]
#priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1.2
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
atmospheric: true
#——————————主武器开火
[effect_烟雾x]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 60
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: 0.3
ySpeedRelativeRandom: 0.35
xSpeedRelativeRandom: 0.2
atmospheric: true
#————————主武器命中
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.6

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
alwayStartDirAtZero: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1.8
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_闪光]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 30
yOffsetRelativeRandom: 30
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:60
yOffsetRelativeRandom:55
delayedStartTimerRandom:30


[arm_1]
x: -46
y: -54
image_end: ROOT:/创世纪军事集团/建筑特效/钢门1.png
image_end_teamColors: true
drawOverBody: true
[arm_2]
x: 6.5
y: 48
image_end:ROOT:/创世纪军事集团/建筑特效/老家风扇.png
image_end_teamColors: true
spinRate:7
drawOverBody: true

[animation_部署]
arm1_0s: {x:0, y:0, dir:0}
arm1_9s: {x:0, y:0, dir:0}
arm1_11s: {x:0, y:30, dir:0}

[animation_部署1]
arm1_0s: {x:0, y:0, dir:0}
arm1_3s: {x:0, y:0, dir:0}
arm1_5s: {x:0, y:30, dir:0}
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
ai_upgradePriority: 1


