


[core]
name: 海啸级护卫舰
displayText: Корвет класса «Цунами»
price: 0
maxHp: 10500
displayDescription:【Уровень t4】【Механический юнит】【Надводный юнит】【сопровождающий юнит】\n-Тактическое назначение:сопровождающий типбоевой корабль，вооружение：\n-▲76ммавтопушкаX4 по земле и воздуху кинетический урон \n-Немезидапроизводить беспилотныйсторожевик，оснащённый два двойной联установить76ммавтопушка，\n-хотяправильныйповерхностьогневая мощь偏слабый，носпособенв качествеНемезида 眼睛использовать，\n-эффективный侦查внешний。одновременно，противостоятьотНемезидапосле部априходить 骚扰время，такжеестьодинвойнаегосила
techLevel: 1
buildSpeed: 17s
radius: 45
displayRadius: 45
showInEditor: false
isBio: false
softCollisionOnAll: 7
armour: 15
fogOfWarSightRange: 23
unitsSpawnedOnDeath: 中型水上单位死亡*1
canNotBeGivenOrdersByPlayer: true
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,海上,伴生单位
energyMax: 10000
energyRegen: -1
energyStartingPercentage:1
[hiddenAction_图]
autoTrigger: if self.energy>1
addWaypoint_target_nearestUnit_tagged: 海上
addWaypoint_type: attackmove
addWaypoint_target_nearestUnit_team: enemy
[hiddenAction_回家]
autoTrigger: if self.energy<1
addWaypoint_target_nearestUnit_tagged: 复仇女神
addWaypoint_type: move
addWaypoint_target_nearestUnit_team: own
clearAllWaypoints: true
[hiddenAction_紫砂]
autoTrigger: if self.energy<1 and self.hasUnitInTeam(withTag='复仇女神', withinRange=280) and self.resource.零件<200
deleteSelf: true
addResources: 零件=30
[hiddenAction_紫砂x]
autoTrigger: if self.energy<1 and self.hasUnitInTeam(withTag='复仇女神', withinRange=250) and self.resource.零件>=200
deleteSelf: true
[hiddenAction_紫砂1]
autoTrigger: if self.noUnitInTeam(withTag='复仇女神') and self.energy<1
addResources:  hp=-99999
[action_s1]
autoTrigger: if not self.isOverLiquid
isVisible: false
addResources: hp=-999999
[action_bkm]
autoTrigger: if not self.tags(includes= '保险') 
isVisible: false
playAnimation: attack
temporarilyAddTags:保险

[decal_炮影子]
image: 影.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:7
xOffsetRelative:1.8
onlyWhileAlive:true
basePositionFromTurret: 3
alpha:0.65
[decal_炮影子1]
image: 影.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:7
xOffsetRelative:1.8
onlyWhileAlive:true
basePositionFromTurret: 6
alpha:0.65
[graphics]
total_frames: 1
image: 船体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: 影子.png
splastEffect: true
teamColorsOnTurret: true
shadowOffsetX: 2.5
shadowOffsetY: 2.5
movementEffect: CUSTOM:火
movementEffectRate: 12
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shootDelay: 75
isMelee: true
meleeEngangementDistance: 99999
maxAttackRange: 600
turretMultiTargeting: true
[turret_1]
x: 3
y: 15
canAttackUnderwaterUnits:false
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/坦克音效.ogg
shoot_sound_vol: 0.5
shoot_flame: large,CUSTOM:烟雾*2
canShoot: true
recoilOffset: -8
recoilOutTime: 3
recoilReturnTime: 20
delay: 80
image: 管.png
attachedTo: 3
size:12
slave: true

[turret_2]
x: -3
y: 15
copyFrom: 1
linkDelayWithTurret:1
delay:70
warmup:10
[turret_3]
x: 0
y:42
canShoot: false
limitingAngle: 120
turnSpeed: 1.8
turnSpeedAcceleration: 0.1
image:炮.png
canAttackUnderwaterUnits:false
[turret_4]
x: 3
y: 15
copyFrom: 1
delay:80
attachedTo: 6
slave: true
[turret_5]
x: -3
y: 15
copyFrom: 1
linkDelayWithTurret:4
delay:70
warmup:10
attachedTo: 6
slave: true
[turret_6]
x: 0
y:-5
canShoot: false
limitingAngle: 120
turnSpeed: 1.8
turnSpeedAcceleration: 0.1
image:炮.png
canAttackUnderwaterUnits:false

[projectile_1]
@copyFromSection: template_动能
#主炮子弹
areaDamage: 400
areaRadius: 50
life: 600
speed: 9
largeHitEffect: true
lightSize: 1.5
frame: 9
lightColor: #FFFFFF73
drawSize: 0.85
trailEffectRate: 0.4
trailEffect: CUSTOM:尾巴
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
areaRadiusFromEdge: true
armourIgnoreAmount: 150

[arm_1]
x: 0
y: 53
image_end: 头.png
image_end_teamColors: true

[arm_2]
x: 0
y: -44
image_end: 尾翼.png
image_end_teamColors: true
[arm_3]
x: -11
y: -40
image_end: 左.png
image_end_teamColors: true
drawOverBody: true
[arm_4]
x: 11
y: -40
image_end: 右.png
image_end_teamColors: true
drawOverBody: true
[arm_5]
x: 0
y: -50
image_end: 船头.png
image_end_teamColors: true
drawOverBody: true
[arm_6]
x: 0
y: -54
image_end: ROOT:/创世纪军事集团/单位特效/雷达.png
drawOverBody: true
spinRate: 8
[animation_attack]
arm1_0s: {x:0, y:0,dir:0}
arm1_1s: {x:0, y:20,dir:0}
arm1_99999s: {x:0, y:20,dir:0}
arm2_0s: {x:0, y:0,dir:0}
arm2_1s: {x:0, y:-30,dir:0}
arm2_99999s: {x:0, y:-30,dir:0}
arm3_0s: {x:0, y:0,dir:0}
arm3_1s: {x:-20, y:0,dir:0}
arm3_99999s: {x:-20, y:0,dir:0}
arm4_0s: {x:0, y:0,dir:0}
arm4_1s: {x:20, y:0,dir:0}
arm4_99999s: {x:20, y:0,dir:0}
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.35
xSpeedRelativeRandom: 0.35
yOffsetRelative: 0.6
ySpeedRelative: 1
atmospheric: true
[effect_闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false

atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 1.5

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false

scaleFrom: 1.5
scaleTo: 2.4
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0

animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_尾巴]
image: SHARED:light_50.png
life: 21
fadeOut: true
attachedToUnit: false
priority: low
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.35
scaleTo: 0.02
alpha: 1
drawUnderUnits: false
[effect_火]
life: 100
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1
scaleTo: 2.6
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -0.5
yOffsetRelative	: 0
drawUnderUnits: true

[movement]
movementType: WATER
moveSpeed: 1.4
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.08
maxTurnSpeed: 3

turnAcceleration: 0.09
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


