


[core]
name: FAV
class: CustomUnitMetadata
price: 3300
maxHp: 7000
displayDescription: 【阶级t4】【机械单位】【地面单位】【重型掩体】战术定位:高速反生物/建筑战车，单位体积:4 \n-死亡后生成两台火龙卷。武器配置：▲火焰喷射器X5 只能对地 中性伤害 反掩体 对生物和建筑伤害加成。\n-火焰突击战车是一种以喷火器为主武器的快速突击车辆。\n-创世纪东欧阵线面临余辉与感染体的双重威胁，\n-FAV源自创世纪东欧战区一些军队对常规装甲车的奇妙改装，\n-他们拆除了装甲车上的主炮和多余的零件，并使用重型喷火器取而代之，\n-经过实战证明，这些军队用粗糙手段改装的装甲车对各种轻型敌人十分致命，\n-在经过创世纪科研部重新优化后，FAV便作为制式装备少量配发给一线部队，\n-经过特化装配的FAV甚至能对余辉造成相当巨大的威胁。




fogOfWarSightRange: 13
techLevel: 1
buildSpeed: 18s
radius: 35
displayRadius: 35
isBio: false
transportSlotsNeeded: 4
softCollisionOnAll: 10
armour: 14
unitsSpawnedOnDeath: 损毁2*1,火龙卷*2
tags: 地面,重型掩体
copyFrom: ROOT:/通用特效/单位防护.ini

[hiddenAction_掩体1取消]
autoTrigger:if self.hasParent and self.tags(includes= '重型掩体')
isVisible:false
temporarilyRemoveTags:重型掩体
[hiddenAction_掩体1生成]
autoTrigger:if not self.hasParent and not self.tags(includes= '重型掩体')
isVisible:false
temporarilyAddTags:重型掩体

[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免部分速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。

[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=320, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=320, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false

#———————科技————
[action_温压弹1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/温压弹.png
text: 空气燃料炸弹1
isActive: false
isVisible: if self.globalTeamTags(includes='温压弹1')
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: 恐怖地雷1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3')
isAlsoViewableByAllies: true
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')

#—————————休克


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[decal_右]
image: 轮子动画.png
total_frames: 2
frame: (self.customTimer * 22) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: afterBody
isVisible:if self.isMoving
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale:0.98
[decal_炮塔]
image: 炮塔.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if not self.globalTeamTags(includes='温压弹1')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: a

[decal_炮塔1]
image: 炮塔1.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.globalTeamTags(includes='温压弹1')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: c
[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: 炮塔.png
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 3
shadowOffsetY: 3
dustEffect: true
turretImageScale: 0.85


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
disablePassiveTargeting: false

turretMultiTargeting: true
turretSize: 0
turretTurnSpeed: 4
maxAttackRange: 260
#—————模块化————

#——————炮塔


[turret_1]
x: 5
y: 4
#炮塔
canShoot: false
idleDir: 90
limitingAngle: 50
invisible:if self.globalTeamTags(includes='温压弹1')
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='温压弹1')
[turret_2]
x: 0
y: 9
#主炮
attachedTo: 1
slave: true
projectile: 1
invisible: true
shoot_sound: ROOT:/通用特效/火焰.ogg
shoot_sound_vol: 0.1
shoot_flame: CUSTOM:烟雾
canShoot: true
delay: 1
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='温压弹1')


[turret_3]
x: -5
y: 4
copyFrom: 1
idleDir: -90
[turret_4]
x: 0
y: 9
attachedTo: 3
slave: true
copyFrom: 2


[turret_5]
x: 0
y: -29
idleDir: -90
copyFrom: 1


[turret_6]
x: 0
y: 9
#主炮
attachedTo: 5
slave: true
copyFrom: 2


[turret_7]
x: 0
y: -29
idleDir: 90
copyFrom: 1
[turret_8]
x: 0
y: 9
#主炮
attachedTo: 7
slave: true
copyFrom: 2

[turret_a]
x: 0
y: 30
idleDir: 0
copyFrom: 1
limitingAngle: 90
[turret_b]
x: 0
y: 9
#主炮
attachedTo: a
slave: true
copyFrom: 2

#————————————————科技主炮
[turret_9]
x: 5
y: 4
#炮塔
canShoot: false
idleDir: 90
limitingAngle: 50
image:炮塔1.png
invisible:if not self.globalTeamTags(includes='温压弹1')

[turret_10]
x: 0
y: 9
#主炮
attachedTo: 9
slave: true
projectile: 炮弹
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/迫击炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFFEB88
shoot_flame:LARGE
canShoot: true
delay: 160
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='温压弹1')

[turret_11]
x: -5
y: 4
copyFrom: 9
idleDir: -90
[turret_12]
x: 0
y: 9
attachedTo: 11
slave: true
copyFrom: 10

[turret_13]
x: 0
y: -29
idleDir: -90
copyFrom: 9
[turret_14]
x: 0
y: 9
#主炮
attachedTo: 13
slave: true
copyFrom: 10

[turret_15]
x: 0
y: -29
idleDir: 90
copyFrom: 9
[turret_16]
x: 0
y: 9
#主炮
attachedTo: 15
slave: true
copyFrom: 10

[turret_c]
x: 0
y: 30
idleDir: 0
copyFrom: 9
limitingAngle: 90
[turret_d]
x: 0
y: 9
#主炮
attachedTo: c
slave: true
copyFrom: 10

[projectile_1]
life: 5000
speed: 6
areaDamage: 25
areaRadius: 40
targetSpeed: 5

image: 爆炸.png
drawSize: 0.66
flameWeapon: true
targetGroundSpread: 10
targetGround: true

areaRadiusFromEdge: true
lightSize: 1
deflectionPower: -1
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸

mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator2_ifUnitWithTags: 步兵
mutator2_directDamageMultiplier: 4
mutator2_areaDamageMultiplier: 4
buildingDamageMultiplier: 2

[projectile_炮弹]
@copyFromSection: template_爆炸
areaDamage: 100
areaRadius: 50
life: 6661
speed: 2
targetSpeed: 3
drawSize: 0.7
image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
explodeEffect: NONE
targetGround: true
areaRadiusFromEdge: true
gravity: 0.4
trailEffectRate: 1.2
trailEffect: CUSTOM:尾巴
spawnProjectilesOnExplode: wy
[projectile_wy]
@copyFromSection: template_爆炸
areaDamage: 485
areaRadius: 55
areaDamageNoFalloff: true
areaRadiusFromEdge: true
life: 0
invisible: true
speed: 0
turnSpeed: 0.0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.8
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 4
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.6
mutator7_areaDamageMultiplier: 0.6
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=3
explodeEffect: CUSTOM:闪光wy2*2,CUSTOM:火光wy,CUSTOM:冲击波wy,CUSTOM:闪光wy,CUSTOM:实验wy,CUSTOM:火星wy*2

[effect_烟雾]
#priority:high
frameIndex: 0
stripIndex: smoke_black
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: true
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.4
scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2

yOffsetRelative: 0.2
ySpeedRelative: 0.41
atmospheric: true


[effect_爆炸]
priority: veryhigh
image: ROOT:/通用特效/爆炸.png
life: 55
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.55
scaleTo: 0.75
alpha: 1
drawUnderUnits: false

ySpeedRelative: 2
atmospheric: true
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13

animateFrameSpeed: 0.2
#——————————————————科技
[effect_烟雾wy]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 180
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 4
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
xOffsetRelativeRandom:27
yOffsetRelativeRandom:27
delayedStartTimerRandom:10
atmospheric: true
[effect_火光wy]
priority: critical
image: ROOT:/通用特效/火光.png
life: 75
fadeOut: true
attachedToUnit: false
scaleFrom: 3.2
scaleTo: 3.2
alwayStartDirAtZero: true
color: #FFFF5B18
alpha: 0.9
drawUnderUnits: false
atmospheric: false
[effect_冲击波wy]
stripIndex: shockwave
life: 30
scaleFrom: 1
scaleTo: 5
alpha: 1
[effect_闪光wy]
image: SHARED:light_50.png
life: 90
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 1
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound: ROOT:/通用特效/火球发射.ogg
[effect_实验wy]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.3
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[effect_闪光wy2]
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFF86
priority: critical
fadeInTime: 2
scaleFrom: 2.2
scaleTo: 2.2
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 80
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 1.5
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.3
scaleTo: 0.1
alpha: 1
drawUnderUnits: true
[arm_1]
x: -15.5
y: 4
image_end: 左.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: 15.5
y: 4
image_end: 右.png
image_end_teamColors: true
drawOverBody: true


[arm_3]
x: -10
y: -29
image_end: 左后.png
image_end_teamColors: true
drawOverBody: true


[arm_4]
x: 10
y: -29
image_end: 右后.png
image_end_teamColors: true
drawOverBody: true


[arm_5]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
hidden: if self.maxHp * 0.36 < self.hp

drawOverBody: true


[arm_6]
#左肩
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true

hidden: if self.maxHp * 0.36 > self.hp
drawOverBody: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:18, y:0}
arm1_950s: {x:18, y:0}
arm2_1s: {x:-18, y:0}

arm2_950s: {x:-18, y:0}
arm3_1s: {x:10, y:1}
arm3_950s: {x:10, y:1}
arm4_1s: {x:-10, y:0}
arm4_950s: {x:-10, y:0}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}

arm4_1s: {x:0, y:0}


[movement]
movementType: LAND
moveSpeed: 1.7
moveAccelerationSpeed: 0.3
moveDecelerationSpeed: 0.1
maxTurnSpeed: 2.8

turnAcceleration: 0.3
moveSlidingMode : false
moveIgnoringBody: false


