


[core]
name: 创世纪机库t1
displayText: Ангар Генезисаt1
price: 5000
maxHp: 10000
armour: 20
copyFrom: ROOT:/通用特效/单位防护.ini
footprint: -5,-3,5,5
constructionFootprint: -5,-3,5,5
displayDescription:【Уровень t3】【Здание】【Наземный юнит】\n-Тактическое назначение：воздушный юнитпроизводствосооружение，без вооружения。\n-не может строиться на воде。\n-一видГенезисфронтстандартныйразвёртыватьздание，используется чтобыбыстрый在фронтпроизводство和维护Генезис空军，\n-其может容纳большое количество技术персонал和地勤персонал，а также多条истребительпроизводство线，\n-这позволяетонможетбыстрыйпроизводствобольшинствоГенезисвоздушный юнит，\n-и用самыйпередовойоружиевооружениеони，одновременноонещё有一部高точность无线电系统，\n-一旦取得许можно便можно从后方呼叫болеемощныйюнитподдержкаполе боя。
techLevel: 1
buildSpeed: 16s
tags: 地面,机场,建筑
radius: 75
nanoFactorySpeed:1
displayRadius: 75
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*8,largeExplosion
isBio: false
isBuilding: true
unitsSpawnedOnDeath:建筑损毁
exit_moveAwayAmount: 180
canBuild_1_name: setRally
canBuild_1_pos: 0.1
[action_煅炉增益]
autoTrigger:if self.globalTeamTags(includes='纳米煅炉') and not self.tags(includes= '煅炉保险')
isActive: false
isVisible: false
temporarilyAddTags:煅炉保险
setUnitStats: nanoFactorySpeed=1.3
[canBuild_T1]
name: 收割者无人机,屠夫无人机,羽翼无人机,游骑兵战斗机,秃鹰运输机
pos: 1
isVisible: if self.hasFlag(id=1)

[action_T1]
pos: 0.1
buildSpeed: 0s
addResources: setFlag=0,setFlag=1
text: 显示t1юнит
isVisible: if not self.hasFlag(id=1) and not self.hasFlag(id=0)
ai_isHighPriority: true
[action_T1_back]
pos: 0.2
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=1
isVisible: if self.hasFlag(id=1)
text: 不显示t1юнит

[canBuild_T00]
name: 眼镜蛇直升机
pos: 1.05
isVisible: if self.hasFlag(id=1)
isLocked:if not self.globalTeamTags(includes='材料技术1')
isLockedMessage: Требуется материаловедение 1



[canBuild_T11]
name: 堡垒直升机
pos: 1.1
isVisible: if self.hasFlag(id=1)
isLocked:if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: Требуется материаловедение 2

[canBuild_T111]
name: 黑色守卫战斗机
pos: 1.31
isVisible: if self.hasFlag(id=1)
isLocked:if not self.globalTeamTags(includes='材料技术2') or not self.globalTeamTags(includes='裂变技术1')
isLockedMessage: Требуется технология деления 1和Материаловедение2


[canBuild_T12]
name: 血翼战斗机
pos: 1.2
isVisible: if self.hasFlag(id=1)
isLocked: if not self.globalTeamTags(includes='裂变技术1')
isLockedMessage: Требуется технология деления 1

[canBuild_T13]
name: 雷霆战机,憎恶级空中炮艇
pos: 1.3
isVisible: if self.hasFlag(id=1)
isLocked: if not self.globalTeamTags(includes='基础科学进步1')
isLockedMessage: Требуется фундаментальная наука1

[canBuild_T14]
name: 天灾重型攻击机
pos: 1.4
isVisible: if self.hasFlag(id=1)
isLocked: if not self.globalTeamTags(includes='基础科学进步1') or not self.globalTeamTags(includes='轨道发射器2')
isLockedMessage: Требуется фундаментальная наука1和轨道пусковая установка2


[action_MK1]
displayType: action
text: модульныйпроизводствоТяжёлый штурмовик «Бедствие»
price:5200,钍=175
pos: 2
isVisible: if self.hasFlag(id=1) and self.globalTeamTags(includes='模块化技术') and self.globalTeamTags(includes='基础科学进步1')
isLocked: if not self.globalTeamTags(includes='基础科学进步1') or not self.globalTeamTags(includes='轨道发射器2')
isLockedMessage: Требуется фундаментальная наука1和轨道пусковая установка2
produceUnits:天灾重型攻击机
buildSpeed: 30s

[action_MK2]
displayType: action
text: модульныйпроизводствоВоздушный канонёр класса «Мерзость»
price:5200,钍=117
pos: 2.1
isVisible: if self.hasFlag(id=1) and self.globalTeamTags(includes='模块化技术') and self.globalTeamTags(includes='基础科学进步1')
isLocked: if not self.globalTeamTags(includes='基础科学进步1')
isLockedMessage: Требуется фундаментальная наука1
produceUnits:憎恶级空中炮艇
buildSpeed: 30s

[action_升级]
convertTo: 创世纪机库t2
displayType: action
text: 升класс
price: 3500
buildSpeed: 25s
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
ai_isHighPriority: true
description: повышаетАнгаруровень，самый大化其здание结构，и使其можетпроизводство阶классT4的воздушный юнит。\n-升класс之后，Генезис空军的终极力量将被允许развёртывать，они将强有力的控制制空权。
pos: 0.05


[graphics]
total_frames: 1
image: 背景.png
image_wreak:ROOT:/创世纪军事集团/建筑特效/死亡2.png
image_back: 背景.png
#AUTO
image_shadow:ROOT:/创世纪军事集团/建筑特效/影子1.png
shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0



[arm_1]
x: 10
y: 69
image_end:ROOT:/创世纪军事集团/建筑特效/扇叶.png
image_end_teamColors: true
drawOverBody: true
spinRate:7
[arm_2]
x: 0
y: 0
image_end:主体.png
image_end_teamColors: true
drawOverBody: true

[arm_3]
x: 0
y: 0
image_end:损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_4]
x: 0
y: 0
image_end:灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_5]
x: 0
y: 0
image_end:灯光1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 


[animation_1]
onActions: idle
blendIn: 0.2s
blendOut: 0.2s


arm5_0s: {alpha:0.0}
arm5_0.8s: {alpha:1}
arm5_1.6s: {alpha:0}
arm5_2.4s: {alpha:1}
arm5_3.2s: {alpha:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 30
yOffsetRelativeRandom: 30
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:60
yOffsetRelativeRandom:70
delayedStartTimerRandom:30
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
maxEachBase: 5
maxGlobal: 50


