


[core]
name: 烟幕弹
class: CustomUnitMetadata
price: 100
maxHp: 1200
armour: 300000


techLevel: 1
fogOfWarSightRange: 0

buildSpeed: 0.01
#availableInDemo: true
isUnselectable: true
numBitsOnDeath: 0
disableAllUnitCollisions: true
tags:烟雾弹,危险物品
showInEditor: false
radius: 0
#displayRadius: 20
isBio: false
isBuilding: true
softCollisionOnAll: 0
canOnlyBeAttackedByUnitsWithTags:消防
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_扫雷]
autoTrigger: if self.hasFlag(id=1)
deleteSelf: true
[action_t1]
autoTrigger: if self.timeAlive(laterThanSeconds=20)
isVisible: false
addResources: hp=-999999
[hiddenAction_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
deleteSelf:true

[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE

shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 40
maxAttackRange: 9999
shootDelay: 1




[turret_烟雾]
x: 0
y: 0
projectile: 13
shoot_flame: CUSTOM:烟雾1
delay: 20

invisible: true


[turret_烟雾2]
x: 0
y: 10
projectile: 13
shoot_flame: CUSTOM:烟雾2*2
delay: 15

invisible: true


[turret_烟雾3]
x: 10
y: 8
projectile: 13
shoot_flame: CUSTOM:烟雾3*3
delay: 15
shoot_sound: ROOT:/通用特效/烟幕弹音效.ogg
shoot_sound_vol: 0.1
invisible: true
size: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1
explodeEffect:NONE
explodeEffectOnShield:NONE
[effect_烟雾1]
priority: critical
frameIndex: 0
stripIndex: effects
life:120
fadeOut: true
attachedToUnit: true

fadeInTime: 0.4
scaleTo: 6
scaleFrom: 3
alpha: 1.2
hSpeed: 0.2
drawUnderUnits: false
atmospheric: true
spawnChance: 1
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
xOffsetRelativeRandom:18
yOffsetRelativeRandom:18

[effect_烟雾2]
priority: critical
frameIndex: 0
stripIndex: effects
life: 100
fadeOut: true
attachedToUnit: true
fadeInTime: 0.2
scaleTo: 5
scaleFrom: 2
alpha: 0.5
hSpeed: 0.6
drawUnderUnits: false
atmospheric: true
spawnChance: 1
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
[effect_烟雾3]
priority: high
frameIndex: 0
stripIndex: effects
life: 140
fadeOut: true
attachedToUnit: true

fadeInTime: 0.6
scaleTo: 4
scaleFrom: 3
alpha: 1
hSpeed: 0.2
drawUnderUnits: false
atmospheric: false
spawnChance: 1
xSpeedAbsoluteRandom: 0.35
ySpeedAbsoluteRandom: 0.35
xOffsetRelativeRandom:45
yOffsetRelativeRandom:45
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.1
maxTurnSpeed: 0

turnAcceleration: 0.1
moveSlidingMode : false
moveIgnoringBody: false


