


[core]
name: 死神无人机
displayText: Дрон «Смерть»
class: CustomUnitMetadata
displayDescription: -🤡
price: 0
maxHp: 3350
showInEditor: true
techLevel: 1
buildSpeed: 0s
availableInDemo: true
radius: 20
copyFrom: ROOT:/通用特效/单位防护.ini
canNotBeGivenOrdersByPlayer: true
softCollisionOnAll: 30
explodeOnDeath: false
hideScorchMark: true
displayRadius: 20
isBio: false
fogOfWarSightRange: 11
tags: 飞机,高空,浮空雷,寄生免疫,死神,反高空,伴生单位,无人单位
canOnlyBeAttackedByUnitsWithTags:反高空
energyMax: 4000
energyRegen: -1
dieOnZeroEnergy: true
numBitsOnDeath:0
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_高空]
text: высотныйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: находится вочень высокийвысокий度 истребительибоевой корабль。\n-вэтотвысокий度низ，толькоесть поверхностьиПустовспециальный против высотныхюнит，а такжевысотныйюнитможетатакадоуказанныйюнит，\n-одновременно，большинствовысотныйюнитможет互相атака，иможетатакаобычныйвоздушный юнит，\n-толькоестьспециальный высотныйюнитможетпо землеатака。
[hiddenAction_zz1]
autoTrigger:if not self.isInMap
addResources: hp= -999999

[graphics]
total_frames: 1
image: 机体.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
#aimOffsetSpread:1

turretSize: 20
turretTurnSpeed: 1.5
isMelee: true
maxAttackRange: 280
shootDelay: 30

dieOnAttack: true
meleeEngangementDistance: 99999

[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir: 0
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shoot_sound: NONE
shoot_sound_vol: 0.3
projectile: 1
size: 1.1
turnSpeed: 999
energyUsage: 1
canOnlyAttackUnitsWithoutTags:高空,死神
[turret_2]
x: 0
y: 0
copyFrom: 1
canOnlyAttackUnitsWithTags:高空
canOnlyAttackUnitsWithoutTags:死神
projectile: 2
[projectile_1]
#低空
@copyFromSection: template_能源
life: 250
speed: 6
targetSpeed: 10
areaDamage: 8000
areaRadius: 85
drawSize: 1
explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
deflectionPower: -1
areaRadiusFromEdge: true
image: 机体.png
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
mutator9_ifUnitWithTags:死神
mutator9_directDamageMultiplier: 0
mutator9_areaDamageMultiplier: 0
buildingDamageMultiplier: 1.5
mutator1_ifUnitWithoutTags: jabzhdja,高空
mutator1_addResourcesAreaHit: 燃烧=15
targetGround_includeTargetHeight:true
[projectile_2]
@copyFromSection: template_能源
life: 250
speed: 6
targetSpeed: 10
areaDamage: 8000
areaRadius: 85
drawSize: 1
explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
deflectionPower: -1
areaRadiusFromEdge: true
image: 机体.png
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
mutator9_ifUnitWithTags:死神
mutator9_directDamageMultiplier: 0
mutator9_areaDamageMultiplier: 0
buildingDamageMultiplier: 1.5
targetGround_includeTargetHeight:true
mutator121_ifUnitWithoutTags: jabzhdja,低空
mutator121_addResourcesAreaHit: 燃烧=15

[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -28
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
#ySpeedRelative: -0.2
yOffsetRelative	: -31
#drawUnderUnits: true
#————————————炮弹爆炸
[effect_聚变nk]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 18
fadeOut: true
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
[effect_冲击波nk]
life: 45
priority: critical
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 2.3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true

[effect_冲击波nk1]
priority: low
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.2
alpha: 0.8
showInFog: true
drawUnderUnits: false
atmospheric: false
#——————@——————看NM，给👴爬


[effect_光球nk]
life: 90
priority: veryhigh
attachedToUnit: false
scaleFrom:0.75
scaleTo: 0.75
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
ySpeedAbsolute:0
fadeOut: true
alpha: 0.85
showInFog: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true
[effect_光球1nk]
life: 90
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/创世纪军事集团/单位特效/大光球.png

fadeOut: true
showInFog: true
alpha: 0.7
fadeInTime: 1
createWhenOffscreen: true

[effect_聚变nk1]
image: ROOT:/通用特效/火光.png
life: 100
fadeOut: true
attachedToUnit: false
alpha: 0.9
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 2
scaleTo: 8.5
color: #FFFFF44C
alwayStartDirAtZero: true
createWhenOffscreen: true
[effect_冲击波nk3]
priority: high
image: ROOT:/创世纪军事集团/单位特效/冲击波4.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.4
alpha: 0.8
drawUnderUnits: true
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:35
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.5
scaleTo:2.67
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180


[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.004
joinsGroupFormations: false
maxTurnSpeed: 2.2
turnAcceleration: 0.08
moveSlidingMode : false
moveIgnoringBody: false

targetHeight: 140
slowDeathFall: false


