


[core]
name: 雷霆战机
displayText: Истребитель «Громовержец»
displayDescription: 【Уровень t3】【Механический юнит】【Воздушный юнит】\n-Тактическое назначение:противозданныйбомбардировщик，вооружение：▲тяжёлыйпушка «Вулкан»X1 только по земле кинетический урон пробивает укрытия \n-▲воздушный炸снарядX2 только по земле взрывной урон усиленный урон по зданиям \n-этотмодель久через沙场 атакамашина早вверх世纪то разрабатыватьибольшое количество投入поле боя，\n-онииспользовать всеявляетсявесьмапростой，также或者являетсянесколькоблизко淘汰 технология，\n-ноэтотмодель结реальныйдолговечный 老爷машинаименно поэтому весьмане хватать资源 Генезистяжёлыйновыйиспользовать。\n-даже есливесьма老старый，ноИстребитель «Громовержец»ещёвна поле бояестьне俗 表现，\n-онинестиестьодин запускать贫铀穿甲снаряд пушка «Вулкан»ичисло все氮阴离сын盐炸снаряд，\n-может像开罐头одинаковыйбудеттяжёлыйбронетехника炸 четыреминутапять裂。
price: 4000
maxHp: 7500
techLevel: 2
buildSpeed: 23s
radius: 40
displayRadius: 40
isBio: false
softCollisionOnAll: 10
energyMax: 6
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/原地盘旋.ini
energyRegen: 0.0085

energyNeedsToRechargeToFull: true
armour: 24
effectOnDeathGroundCollision: CUSTOM:爆炸*1


tags: 飞机,低空
fogOfWarSightRange: 29


[action_温压弹1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/温压弹.png
text: Объёмно-детонирующая бомба1
isActive: false
isVisible: if self.globalTeamTags(includes='温压弹1')
[graphics]
total_frames: 1
image: 雷霆.png
image_wreak: 死亡.png
image_turret: NONE
movementEffect: CUSTOM:烟1,CUSTOM:烟2

movementEffectRate: 0.7
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.85
showQueueBar: false
showTransportBar: false
showEnergyBar: false
teamColorsOnTurret: true
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 550
shootDelay: 1
attackMovement: bomber
disablePassiveTargeting: false


[turret_1]
x: 0
y: 38
invisible: true
turnSpeed: 200
turnSpeedAcceleration: 11

projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/机炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFFEB88
shoot_flame: CUSTOM:枪口火焰

canShoot: true
delay: 5
limitingAngle: 15


[turret_2]
invisible: true
x: 0
y: 0
idleDir: 0
canAttackFlyingUnits: false

canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: NONE
shoot_sound_vol: 0.3
projectile: 2

size: 1.1
turnSpeed: 20
delay: 10
limitingRange: 100
energyUsage: 3
canAttackCondition:if not self.globalTeamTags(includes='温压弹1')
aimOffsetSpread: 1
[turret_3]
invisible: true
x: 0
y: 0
idleDir: 0
canAttackFlyingUnits: false

canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: NONE
shoot_sound_vol: 0.3
projectile: 3
aimOffsetSpread: 1
size: 1.1
turnSpeed: 20
delay: 10
limitingRange: 100
energyUsage: 6
canAttackCondition:if self.globalTeamTags(includes='温压弹1')
[projectile_1]
@copyFromSection: template_动能
directDamage: 75
life: 60
speed: 15
color: #FFFFFF73

drawSize: 0.85
deflectionPower: -1
largeHitEffect: true
lightSize: 1
frame: 8

lightColor: #FFFFFF73
explodeEffect: largeExplosion*1
armourIgnoreAmount: 80
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_爆炸
life: 250
speed: 1
targetSpeed: 2
areaDamage: 1500

areaRadius: 80
drawSize: 0.8
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光*1,CUSTOM:弹坑*1
targetGround: true
areaRadiusFromEdge: true

image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
buildingDamageMultiplier: 3
targetGround_includeTargetHeight:true
[projectile_3]
@copyFromSection: template_爆炸
life: 250
speed: 1
targetSpeed: 2
areaDamage: 100

areaRadius: 80
drawSize: 0.65
explodeEffect: CUSTOM:烟雾wy*12
explodeEffectOnShield: CUSTOM:烟雾wy*12
targetGround: true
areaRadiusFromEdge: true
image: 温压弹.png
spawnProjectilesOnExplode: wy
targetGround_includeTargetHeight:true
[projectile_wy]
@copyFromSection: template_爆炸
areaDamage: 3000
areaRadius: 90
areaDamageNoFalloff: true
areaRadiusFromEdge: true
life: 0
invisible: true
delayedStartTimer: 1.5s
speed: 0
turnSpeed: 0.0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 3
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 2
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.6
mutator7_areaDamageMultiplier: 0.6
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=10
explodeEffect: CUSTOM:闪光wy2*2,CUSTOM:火光wy,CUSTOM:冲击波wy,CUSTOM:闪光wy1,CUSTOM:巨大冲击波wy,CUSTOM:闪光wy*1,CUSTOM:实验wy,CUSTOM:火星wy*4,CUSTOM:随机爆炸wy*4
targetGround_includeTargetHeight:true
#————————温压弹
[effect_烟雾wy]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 200
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 4.5
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
xOffsetRelativeRandom:40
yOffsetRelativeRandom:40
delayedStartTimerRandom:10
atmospheric: true
[effect_火光wy]
priority: critical
image: ROOT:/通用特效/火光.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 5
scaleTo: 5
alwayStartDirAtZero: true
color: #FFFF5B18
alpha: 0.9
drawUnderUnits: false
atmospheric: false
[effect_冲击波wy]
stripIndex: shockwave
life: 80
scaleFrom: 1
scaleTo: 7
alpha: 1
[effect_闪光wy]
image: SHARED:light_50.png
life: 250
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 1.5
scaleTo: 1.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound: ROOT:/通用特效/火球发射.ogg
[effect_闪光wy1]
image: SHARED:light_50.png
life: 180
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
[effect_巨大冲击波wy]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 2.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
color: #FFFF5B18
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_实验wy]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.8
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[effect_闪光wy2]
image: SHARED:light_50.png
life: 280
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFF86
priority: critical
fadeInTime: 2
scaleFrom: 2.8
scaleTo: 2.8
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 150
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.8
scaleTo: 2.2
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:65
yOffsetRelativeRandom:65
[effect_随机爆炸wy]
life: 100
priority: high
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:55
yOffsetRelativeRandom:55
delayedStartTimerRandom:20

[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1.3
scaleTo: 1.3
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟1]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 1.5
scaleTo: 1.5
image: ROOT:/通用特效/烟.png
alpha: 0.5
total_frames: 4

animateFrameStart: 0
animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.1
xOffsetRelative	: 57

yOffsetRelative	: 3


[effect_烟2]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 1.5
scaleTo: 1.5
image: ROOT:/通用特效/烟.png
alpha: 0.5
total_frames: 4

animateFrameStart: 0
animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.1
xOffsetRelative	: -57

yOffsetRelative	: 3


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
scaleFrom: 3

scaleTo: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
[arm_1]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[movement]
movementType: AIR
moveSpeed: 2.4
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.007
#landOnGround: onlyIdle
startingHeightOffset: 1000
joinsGroupFormations: false
maxTurnSpeed: 1.8
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false

slowDeathFall: true
targetHeight: 70


