


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 冥卫机甲
displayText: Мех «Страж бездны»
price: 5500,awz= ${awzxq}
@global awzxq: 100
reclaimPrice: awz= ${awzxq}
maxHp: 4000
fogOfWarSightRange: 25
displayDescription: -«Страж бездны» — это передовой,\n-уникальный и крайне смертоносный основной боевой мех.\n-Этот мощный мех является доказательством того, что\n-новые технологии Скитальцев не отстают от имперских.\n-На больших расстояниях, даже сталкиваясь с различными железными монстрами Имперского Зарева,\n-«Страж бездны» способен одержать верх.\n-Этот мех, олицетворяющий передовые технологии Скитальцев,\n-из-за крайней сложности изготовления\n-редко встречается в армии Скитальцев,\n-управлять им имеют право только лучшие из лучших пилотов.\n-Несмотря на высокую стоимость, «Страж бездны» по-прежнему мощно\n-сбивает спесь с дерзких наземных войск Зарева.\n-Атакует только землю, кинетический урон.
techLevel: 1
buildSpeed: 24s
radius: 46
displayRadius: 46

armour: 7
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 3
unitsSpawnedOnDeath: 损毁3*1
tags: 地面

energyMax: 1
energyRegen: 0
energyNeedsToRechargeToFull: true
selfRegenRate: 0.2


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: Недостаточно тёмной материи
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: Броня «Сегмента» 1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_爆散2]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: Детонационная боеголовка 2
isActive: false
isVisible: if self.globalTeamTags(includes='爆散2')


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯') or self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 600 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true


[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 600 | setFlag= 0)


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5)
isVisible: false
alsoQueueAction: b


[action_b]
convertTo: 冥卫机甲1
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false

highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署


[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.resource.awz>-1
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 490
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_2]
x: 24
y: 56
attachedTo: 1
invisible: true
projectile: 1

shoot_sound: NONE
canShoot: true
size: 36
delay: 8
energyUsage: 0

slave: true


[turret_1]
x: 0
y: 0
canShoot: false
image: NO.png


[projectile_1]
life: 0
directDamage: 0
speed: 0
targetSpeed: 0
drawSize: 0

frame: 1
deflectionPower: -1


[arm_1]
x: -13
y: -5
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: -45

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_2]
x: 24
y: -5
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:胳膊.png
drawDirOffset: 35


[arm_3]
x: -28
y: 20
image_end: 左手.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 30
image_end_shadow: SHADOW:左手.png


[arm_4]
x: 37
y: 21
image_end: 右手.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:左手.png
drawDirOffset: -60


[arm_5]
#左肩
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:主体.png
drawDirOffset: 0


[arm_6]
x: 30
y: 28
image_end: 枪栓.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -65


[arm_7]
x: 30
y: 28
image_end: 枪.png
image_end_shadow: SHADOW:枪.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -65


[arm_8]
#左肩
x: 0
y: -3
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[leg_1]
x: -17
y: 9
attach_x: -7
attach_y: 7
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 左腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 17
y: 9
attach_x: 7
attach_y: 7
copyFrom: 1

image_leg: 右腿.png
drawDirOffset: 10


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm1_0.6s: {x:-1, y:14, dir:45}
arm2_0.6s: {x:-5, y:-4, dir:5}

arm3_0.6s: {x:18, y:22, dir:15}
arm4_0.6s: {x:-5, y:-6, dir:20}
arm5_0.6s: {x:0, y:0, dir:20}
arm6_0.6s: {x:-15, y:-10, dir:65}
arm7_0.6s: {x:-15, y:-10, dir:65}


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.81
moveAccelerationSpeed: 0.09
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

targetHeight: 4
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4

slowDeathFall: true


