


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 冥卫机甲1
displayText: Мех «Страж бездны»
price: 5500,awz= ${awzxq}
@global awzxq: 100
reclaimPrice: awz= ${awzxq}
fogOfWarSightRange: 25
maxHp: 4000
displayDescription: -冥卫是一种具备尖端技术，\n-有独特优势且极其致命的主战机甲，\n-这种强悍的机甲足以证明太空浪人的\n-新兴技术丝毫不落后于帝国科技，\n-在远距离上，哪怕是面对帝国余辉的各种钢铁怪兽，\n-冥卫机甲依旧能胜券在握。\n-这种代表太空浪人尖端技术的主战机甲，\n-因为极其困难的制造难度，\n-使得它很难在太空浪人的军队中发现其踪影，\n-只有最精锐的机师才有权驾驶冥卫机甲，\n-虽然造价高昂，但是冥卫机甲依旧强力的打\n-击了余辉地面部队嚣张的气焰。\n-只能对地，动能伤害。
techLevel: 1
buildSpeed: 24s
radius: 46

displayRadius: 46
armour: 7
showInEditor: false
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 3

unitsSpawnedOnDeath: 损毁3*1
tags: 地面
energyMax: 1
energyRegen: 0
energyNeedsToRechargeToFull: true

selfRegenRate: 0.2


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: Недостаточно тёмной материи
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[action_爆散2]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: Детонационная боеголовка 2
isActive: false
isVisible: if self.globalTeamTags(includes='爆散2')


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: Броня «Сегмента» 1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯') or self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 600 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true

[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 600 | setFlag= 0)


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", greaterThan= 0.5) and self.energy(full=true)
isVisible: false
alsoQueueAction: b


[action_b]
convertTo: 冥卫机甲
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false

highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署


[action_换弹1]
autoTrigger: if self.energy(empty=true) and self.queueSize < 0.5
isVisible: false
alsoQueueAction: 换弹


[action_换弹]
#autoTrigger: if self.energy(empty=true) and self.queueSize < 0.5
isVisible: false
buildSpeed: 0.46s
alsoQueueAction: bx
playSoundAtUnit: 拉栓.ogg


[action_bx]
displayType: action
price: 0
buildSpeed: 1s
isVisible: false
highPriorityQueue: true

whenBuilding_cannotMove: false
whenBuilding_playAnimation: 换弹
addEnergy: 1
spawnEffects: CUSTOM:弹壳


[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.resource.awz>-1
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 490
shootDelay: 100
turretRotateWithBody: true
#isFixedFiring: true

turretMultiTargeting: true


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-150
projectile: 13
delay: 120

attachedTo: 1
slave: true
size: 0
#limitingRange:280


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_2]
x: 15
y: 94
invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1

shoot_light: #FFFFEB88
shoot_flame: CUSTOM:气浪*6,CUSTOM:粒子*12
projectile: 2
delay: 250
energyUsage: 1

canAttackCondition: if self.resource.xk < 1
onShoot_playAnimation: attack
attachedTo: 1
slave: true
warmup: 40

chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
limitingMinRange: 220
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')


[turret_1]
x: 0
y: 0
canShoot: false
image: NO.png


[projectile_1]
life: 0
directDamage: 0
speed: 0
targetSpeed: 0
drawSize: 0

frame: 1
deflectionPower: -1


[projectile_2]
@copyFromSection: template_动能
directDamage: 3500
life: 200
speed: 9
image: ROOT:/太空浪人/单位特效/大炮弹.png

targetSpeed: 9
drawSize: 0.6
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*15,CUSTOM:冲击波,CUSTOM:爆炸2,CUSTOM:聚变,CUSTOM:冲击波2
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*15,CUSTOM:冲击波,CUSTOM:爆炸2,CUSTOM:聚变,CUSTOM:冲击波2
lightSize: 0.75

trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1
lightColor: #FFFF1200


[projectile_炮弹]
@copyFromSection: template_爆炸
life: 200
areaDamage: 4000
areaRadius: 65
speed: 9

image: ROOT:/太空浪人/单位特效/大炮弹1.png
targetSpeed: 9
drawSize: 0.6
explodeEffect: CUSTOM:爆炸b, CUSTOM:闪光b,CUSTOM:粒子b*15,CUSTOM:冲击波b,CUSTOM:溅射b,CUSTOM:聚变b,CUSTOM:冲击波2b
explodeEffectOnShield: CUSTOM:爆炸b, CUSTOM:闪光b,CUSTOM:粒子b*15,CUSTOM:冲击波b,CUSTOM:溅射b,CUSTOM:聚变b,CUSTOM:冲击波2b

lightSize: 0.75
trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴b,CUSTOM:尾巴b1
lightColor: #FF68FF2E
spawnProjectilesOnExplode: m2(yOffsetRelative= 20)


[projectile_m2]
@copyFromSection: template_爆炸
life: 1
deflectionPower: -1
explodeOnEndOfLife: true
speed: 0

turnSpeed: 0.0
areaDamage: 280
areaRadius: 50
areaRadiusFromEdge: true
targetGround: true

invisible: true
explodeEffect: CUSTOM:爆炸b1
spawnProjectilesOnCreate: m2(recursionLimit= 12, yOffsetRelative= 20)
#delayedStartTimer: 0.05s

[arm_1]
x: -14
y: 9
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: 0

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_2]
x: 19
y: -9
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:胳膊.png
drawDirOffset: 40


[arm_3]
x: -10
y: 42
image_end: 左手.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 45
image_end_shadow: SHADOW:左手.png


[arm_4]
x: 32
y: 15
image_end: 右手.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:左手.png
drawDirOffset: -40


[arm_5]
#左肩
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:主体.png
drawDirOffset: 20


[arm_6]
x: 15
y: 18
image_end: 枪栓.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 0


[arm_7]
x: 15
y: 18
image_end: 枪.png
image_end_shadow: SHADOW:枪.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: 0


[arm_8]
#左肩
x: 0
y: -3
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[leg_1]
x: -17
y: 9
attach_x: -7
attach_y: 7
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 左腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 17
y: 9
attach_x: 7
attach_y: 7
copyFrom: 1

image_leg: 右腿.png
drawDirOffset: 10


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm1_0.6s: {x:1, y:-14, dir:-45}
arm2_0.6s: {x:5, y:4, dir:-5}

arm3_0.6s: {x:-18, y:-22, dir:-15}
arm4_0.6s: {x:5, y:6, dir:-20}
arm5_0.6s: {x:0, y:0, dir:-20}
arm6_0.6s: {x:15, y:10, dir:-65}
arm7_0.6s: {x:15, y:10, dir:-65}


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6

yOffsetRelative: 0.8
ySpeedRelative: 1.5
atmospheric: true


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.7
scaleTo: 0.7

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2.3

ySpeedRelativeRandom: 2.3
#atmospheric: true


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_爆炸2]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5

scaleTo: 1.5
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.6
scaleTo: 1.6
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 30
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7

drawUnderUnits: false


[animation_attack]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm1_0.05s: {x:0, y:-3, dir:0}
arm7_0.05s: {x:0, y:-24, dir:0}

arm6_0.05s: {x:0, y:-24, dir:0}
arm3_0.05s: {x:0, y:-7, dir:3}
arm4_0.05s: {x:0, y:-7, dir:0}


[effect_尾巴1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[animation_换弹]
#onActions: attack
arm2_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm2_0.4s: {x:0, y:0, dir:0}

arm4_0.4s: {x:0, y:0, dir:30}
arm6_0.4s: {x:0, y:0, dir:0}
arm2_0.65s: {x:0, y:-6, dir:0}
arm4_0.65s: {x:0, y:-10, dir:30}
arm6_0.65s: {x:0, y:-15, dir:0}

arm2_0.8s: {x:0, y:0, dir:0}
arm4_0.8s: {x:0, y:0, dir:30}
arm6_0.8s: {x:0, y:0, dir:0}
arm2_1s: {x:0, y:0, dir:0}
arm4_1s: {x:0, y:0, dir:0}

arm6_1s: {x:0, y:0, dir:0}


[effect_弹壳]
priority: high
image: 弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.7
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 2.5
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: 40
xOffsetRelative: 20

hSpeed: 3.7
dirSpeedRandom: 50
#———————————————————————————————


[effect_爆炸b]
life: 100
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
image: ROOT:/太空浪人/单位特效/大爆炸.png
total_frames: 40

animateFrameStart: 0
animateFrameEnd: 39
animateFramePingPong: false
animateFrameSpeed: 0.8
alpha: 2

#color:#FFFF1200
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光b]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_粒子b]
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子.png
scaleFrom: 0.1
scaleTo: 0.3

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2.5

ySpeedRelativeRandom: 3
#atmospheric: true


[effect_冲击波b]
#priority:critical
image: ROOT:/太空浪人/单位特效/冲击波3.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 1.5
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_聚变b]
priority: critical
image: ROOT:/太空浪人/单位特效/火光1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
#color:#FFFF120


[effect_溅射b]
life: 100
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.55
scaleTo: 0.55
image: ROOT:/太空浪人/单位特效/爆散.png
total_frames: 9

animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.2
alpha: 1

atmospheric: false
#color:#FFFF1200


[effect_冲击波2b]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.3

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FF68FF2E


[effect_爆炸b1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2

image: ROOT:/太空浪人/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
#color:#FFFF1200


[effect_尾巴b1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF68FF2E
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[effect_尾巴b]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束5.png
life: 30
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7

drawUnderUnits: false


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.9
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.81
moveAccelerationSpeed: 0.09
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

targetHeight: 4
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4

slowDeathFall: true


