


[core]
name: 羽翼无人机
displayDescription: 【阶级t3】【机械单位】【无人单位】【空中单位】战术定位:反单体无人机，\n-武器配置：▲反坦克导弹X2 只能攻击地面机械单位 无法攻击建筑物 爆炸伤害 \n-在余辉还未侵略之前，无人机曾一度成为战场上的新星，\n-而羽翼无人机因在实战中摧毁坦克数量最多而畅销全球，\n-余辉入侵后，羽翼无人机庞大的库存被创世纪重新利用，\n-虽然他小而脆弱，但他依旧能对地面单位构成致命威胁。
price: 2700
maxHp: 600
techLevel: 1
buildSpeed: 12s
radius: 25
displayRadius: 25
armour: 1
isBio: false
softCollisionOnAll: 8
numBitsOnDeath: 8
energyMax: 8
tags: 飞机,低空,无人单位
fogOfWarSightRange: 21
energyRegen: 0.012
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/原地盘旋.ini
energyNeedsToRechargeToFull: true

[action_聚变弹头1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变1.png
text: 聚变弹头1
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头1')

[decal_导弹]
image: 中导弹.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.energy>6
yOffsetRelative:-13
xOffsetRelative:22
imageScale: 0.7
onlyWhileAlive:true


[decal_导弹1]
image: 中导弹.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.energy>2
yOffsetRelative:-13
xOffsetRelative:-22
imageScale: 0.8
onlyWhileAlive:true


[decal_遮盖1]
image: 羽翼.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
imageScale: 0.8
onlyWhileAlive:true
[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
yOffsetRelative:0
xOffsetRelative:-0.5
imageScale: 0.8
onlyWhileAlive:true
[graphics]
total_frames: 1
image: 羽翼.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.8
movementEffectRate: 0.5
movementEffect: CUSTOM:火1,CUSTOM:火2
turretImageScale: 0.7
showQueueBar: false
showTransportBar: false
showEnergyBar: false
teamColorsOnTurret: true
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 350
shootDelay: 15
attackMovement: bomber



[turret_1]
x: 22
y: -13
projectile: 1
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 0.6
shoot_flame: NONE
shoot_light: #FFEECCCC
canShoot: true
energyUsage: 4
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头1')
delay:120
warmup:10
image:中导弹.png
limitingAngle: 15
canOnlyAttackUnitsWithoutTags:步兵,建筑
[turret_2]
x: -22
y: -13
#导弹左
copyFrom: 1
warmup: 40
delay:90
invisible: true
[projectile_1]
@copyFromSection: template_爆炸
life: 39
speed: 0
targetSpeed: 0
largeHitEffect: true
image:中导弹.png
drawSize: 0.8
areaDamage: 0
areaRadius: 0
explodeEffect:CUSTOM:音效
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:2
explodeOnEndOfLife:true
drawUnderUnits:true
[projectile_2]
@copyFromSection: template_爆炸
#主炮子弹
areaDamage: 1350
areaRadius: 45
life: 350
speed: 3
targetSpeed: 8
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
drawSize: 0.8
trailEffect: CUSTOM:projectileTrail
lightSize: 0.75
lightColor: #FFFFFF73
areaRadiusFromEdge: true
buildingDamageMultiplier: 0.5
explodeEffect: CUSTOM:黑雾*2,CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:黑雾*2,CUSTOM:钢珠,CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑
autoTargetingOnDeadTarget: true
trailEffectRate: 0.8
targetGround_includeTargetHeight:true
[projectile_炮弹]
@copyFromSection: template_能源
life: 39
speed: 0
targetSpeed: 0
largeHitEffect: true
image:中导弹.png
drawSize: 0.8
areaDamage: 0
areaRadius: 0
explodeEffect:CUSTOM:音效
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:锁定
explodeOnEndOfLife:true
drawUnderUnits:true
[projectile_锁定]
@copyFromSection: template_能源
#主炮子弹
areaDamage: 2250
areaRadius: 55
life: 350
speed: 3
targetSpeed: 8
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
drawSize: 0.8
trailEffect: CUSTOM:projectileTrail
lightSize: 0.75
lightColor: #FFFFFF73
areaRadiusFromEdge: true
buildingDamageMultiplier: 0.5
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:冲击波
autoTargetingOnDeadTarget: true
trailEffectRate: 0.8
targetGround_includeTargetHeight:true
#——————————聚变

[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 1.2
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 30
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.8
scaleTo: 1
alpha: 0.6
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.1
ySpeedAbsoluteRandom: 0.1
[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -34
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0

yOffsetRelative	: -38
#drawUnderUnits: true
#主炮爆炸特效——————————


[effect_闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 0
drawUnderUnits: false

atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.7
scaleTo: 1.7

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false

scaleFrom: 1.8
scaleTo: 2.2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0

animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1.7
scaleTo: 1.7
createWhenOverLiquid: false
createWhenOverLand: true


[effect_黑雾]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true

life: 200
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5

scaleFrom: 0.17
scaleTo: 0.23
alpha: 1
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[movement]
movementType: AIR
moveSpeed: 2
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.002
#landOnGround: onlyIdle
startingHeightOffset: 1000
joinsGroupFormations: false
targetHeight: 70
targetHeightDrift: 2
maxTurnSpeed: 1.8
turnAcceleration: 0.06

moveSlidingMode : false
moveIgnoringBody: false
slowDeathFall: true


[ai]
disableUse: true


