


[core]
name: 加特林卡车
displayText: 加特林卡车
displayDescription: 【阶级t2】【机械单位】【地面单位】战术定位:反生物/防空战车，单位体积:2，\n-武器配置：▲GUA-11机枪X2 对地对空 动能伤害，反掩体对空中和生物单位伤害加成\n-加特林卡车是十分简单却有效的轻武装车辆，\n-他们非常善于用双联装GUA-11拆解敌方步兵和轻飞行器，\n-更是轻型空中单位的致命克星。
transportSlotsNeeded:2
price: 500
maxHp: 600
techLevel: 1
buildSpeed: 5s
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 16
isBio: false
softCollisionOnAll: 8
tags: 地面,驻扎要塞
unitsSpawnedOnDeath: 损毁*1
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
[action_电磁炮1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道1.png
text: 轨道发射器1
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器1')
[action_恐怖地雷2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖2.png
text: 恐怖地雷2
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷2') and not self.globalTeamTags(includes='恐怖地雷3')
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[decal_损坏]
layer: afterBody
image: 加特林卡车损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
imageScale:1
[decal_炮塔影子1]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:1
xOffsetRelative:1
onlyWhileAlive:true
alpha:0.55
imageScale:1.1
basePositionFromTurret: 1
[graphics]
total_frames: 2
image: 加特林卡车.png
image_wreak: 加特林卡车死亡.png
image_turret: 加特林卡车炮塔.png
image_shadow: AUTO
shadowOffsetX: 1.5
shadowOffsetY: 1.5
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 0.5

dustEffect: true
imageScale: 1.1
teamColorsOnTurret: true
turretImageScale: 1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 18
turretTurnSpeed: 5
maxAttackRange: 250
shootDelay: 4


[turret_1]
x: 0
y: -10
canShoot: false
idleSweepAngle: 20
idleSweepDelay: 230
idleSweepSpeed: 0.2
image:加特林卡车炮塔.png
[turret_2]
x: -4
y: 0
attachedTo: 1
slave: true
invisible: true

shoot_sound: ROOT:/创世纪军事集团/单位特效/重机枪音效.ogg
shoot_sound_vol: 0.2
shoot_flame: CUSTOM:枪口火焰,CUSTOM:弹壳
shoot_light: #FFFFEB88
projectile: 1
canAttackCondition: if self.resource.xk < 1
size:22
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='轨道发射器1')
[turret_3]
x: 4
y: 0
copyFrom: 2
shoot_flame: CUSTOM:枪口火焰,CUSTOM:弹壳1
[turret_4]
x: 0
y: 0
#炮塔损坏
canShoot: false
image: 加特林卡车炮塔损坏.png
invisible: if self.maxHp * 0.36 < self.hp
attachedTo: 1
slave: true
[projectile_1]
@copyFromSection: template_动能
directDamage: 4
life: 800
speed: 10
deflectionPower: -1
drawSize: 0.7
trailEffect: false
frame: 5
explodeEffect: CUSTOM:火花
mutator1_ifUnitWithTags: 飞机
mutator1_directDamageMultiplier: 3
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator3_ifUnitWithTags: 步兵
mutator3_directDamageMultiplier: 2
mutator3_areaDamageMultiplier: 2
[projectile_炮弹]
@copyFromSection: template_动能
directDamage: 7
life: 600
speed: 10
frame: 8
drawSize: 0.7
explodeEffect: CUSTOM:穿透,CUSTOM:大火花
deflectionPower: -1
armourIgnoreAmount: 10
mutator1_ifUnitWithTags: 飞机
mutator1_directDamageMultiplier: 3
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
shieldDamageMultiplier: 1.2
mutator3_ifUnitWithTags: 步兵
mutator3_directDamageMultiplier: 2
mutator3_areaDamageMultiplier: 2
[effect_穿透]
priority: high
frameIndex: 4
stripIndex: projectiles2
life: 15
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.7
alpha: 1
drawUnderUnits: false
ySpeedRelative: 2.6
atmospheric: false


[effect_大火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.25
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.6
image: ROOT:/创世纪军事集团/单位特效/火花.png
alpha: 1.2

total_frames: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFramePingPong: false
animateFrameSpeed: 0.3


[effect_弹壳]
priority: low
image: ROOT:/通用特效/弹壳.png
spawnChance: 0.75
life: 70
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.3
scaleTo: 0.3
alpha: 2

fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
xSpeedRelative: -1.2
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -20
xOffsetRelative: -5
hSpeed: 2
dirSpeedRandom: 50
[effect_弹壳1]
priority: low
image: ROOT:/通用特效/弹壳.png
spawnChance: 0.75
life:70
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.3
scaleTo: 0.3
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
xSpeedRelative: 1.2
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -20
xOffsetRelative: 5
hSpeed: 2
dirSpeedRandom: 50

[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 1
scaleTo: 2.3


[movement]
movementType: LAND
moveSpeed: 1.4
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0.6

maxTurnSpeed: 4.1
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false


