


[core]
@memory asd: number
name: 激光中介2
displayText: Лазерный посредник2
strictLevel: 1
price: 0
radius: 10

maxHp: 1
class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: 激光

createOnAggressiveTeam: true
canNotBeDamaged: true
canOnlyBeAttackedByUnitsWithTags: 激光炮塔
isUnrepairableUnit: true
isUnselectable: true

disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
# 零生命值时不死亡
isBuilding: true

autoTriggerCooldownTime_allowDangerousHighCPU: true
autoTriggerCooldownTime: 0.02s


[graphics]
image: SHARED:blank.png
isVisible: false


[attack]
canAttack: false


[turret_1]
# 传送用的
x: 0
y: 0
projectile: 1
canShoot: false


[projectile_1]
# 传送用的
life: 1
deflectionPower: -1
directDamage: 0
teleportSource: true

invisible: true
instant: true
explodeEffect: none
explodeEffectOnShield: none


[hiddenAction_1]
autoTrigger: if parent == nullUnit and self.queueSize<0.5
# 脱离母体，启动自杀
setUnitMemory: asd = 0
alsoQueueAction: 2


[hiddenAction_2]
# 自杀
buildSpeed: 6s
deleteSelf: true


[hiddenAction_3]
autoTrigger: if parent == nullUnit and self.ammo > memory.asd
fireTurretXAtGround: 1
fireTurretXAtGround_withTarget: self.getOffsetRelative( y= min( 0.02 * self.ammo, 1.2) )
setUnitMemory: asd = memory.asd + 1
# addResources: ammo= -1


[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 0
targetHeight: 0
targetHeightDrift: 0


