


[core]
name: 基因血巢
displayDescription: -比蒙巨兽原本是生活在奥博修斯星系科斯塔星球上，一种巨型草食动物，\n-这种动物生性温顺，但是并不代表其在面对威胁时没有战斗力，\n-其标志性的覆盖身体前端的骨版为其提供了绝佳的防护，再加上其力大无穷，\n-这简直是制造生物武器的绝佳基础，太空浪人将灰影病毒与比蒙巨兽的克隆体融合，\n-成功创造出了基因血巢这个恶心但是强大的怪物，只不过，\n-基因血巢依旧无法改变其温顺的本性，所以太空浪人着重强化了其生殖功能和其他腺体，\n-他可以从远处孵化大量僵尸并释放信息素指挥整个僵尸军团作战。\n-只能通过孵化小型僵尸攻击，中性伤害，生物单位。
class: CustomUnitMetadata
price: hy=3500
maxHp: 5000
fogOfWarSightRange: 27
mass: 9000
techLevel: 1
buildSpeed: 18s
radius: 47
transportSlotsNeeded: 99999
isUnrepairableUnit:true
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 18
energyRegen: 0.004
energyNeedsToRechargeToFull: true
tags: 地面,步兵,寄生免疫

effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
isBio: true
explodeOnDeath: false
hideScorchMark: true
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[action_1_EMP]
fireTurretXAtGround: 3
text: 喷卵
displayType: action
buildSpeed: 0s
pos: 0.1

highPriorityQueue: true
price: energy=6
fireTurretXAtGround_count: 15
canPlayerCancel: false
displayRemainingStockpile: true

onlyOneUnitAtATime: true
description: 将体内未成熟的幼体卵全部喷出，\n-这些未成熟的卵往往含有大量腐蚀性酸，\n-将对附近的敌人造成大量中性伤害并可能孵化出幼体。


[action_灰影寄生虫科技提示1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/灰影寄生虫.png
text: 灰影寄生虫1
isActive: false
isVisible: if self.globalTeamTags(includes='寄生虫1')


[action_2_EM]
fireTurretXAtGround: 4
text: 肿瘤喷射
displayType: action
buildSpeed: 0s
pos: 0.1

highPriorityQueue: true
price: energy=3
canPlayerCancel: false
displayRemainingStockpile: true
onlyOneUnitAtATime: true

description: 将一块特殊的肿瘤喷射到指定地点，\n-这块肿瘤将利用附近所有的物质瞬间生长成一坨肉山，\n-将阻碍敌人通过并吸引火力。\n-肿块破裂后会孵化一个幼体。


[graphics]
total_frames: 1
image: 身体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 4
shadowOffsetY: 4
#lock_body_rotation_with_main_turret:true
#lock_leg_rotation_with_main_turret:true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 1
maxAttackRange: 550
shootDelay: 100
#turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_1]
x: -7
y: 0
invisible: true
shoot_sound: NONE
shoot_flame: NONE

projectile: 1
size: 0
turnSpeed: 811
turnSpeedAcceleration: 10
delay: 400

#canAttackFlyingUnits: false


[turret_2]
x: 7
y: 0
invisible: true
shoot_sound: NONE
shoot_flame: NONE

projectile: 1
size: 0
turnSpeed: 811
turnSpeedAcceleration: 10
delay: 400

#canAttackFlyingUnits: false


[turret_3]
x: 0
y: -9
canShoot: false
projectile: 2


[turret_4]
x: 0
y: -9
canShoot: false
projectile: 3


[projectile_2]
areaDamage: 180
areaRadius: 70
life: 6661
image: 卵.png
drawSize: 0.9
deflectionPower: -1
speed: 4
targetSpeed: 7
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光
targetGround: true

initialUnguidedSpeedHeight: 3
gravity: 2
spawnUnit: 幼体(spawnChance=0.35)
targetGroundSpread: 100


[projectile_3]
areaDamage: 0
areaRadius: 25
life: 6661
image: 卵.png
drawSize: 0.9
deflectionPower: -1
speed: 4
targetSpeed: 7
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光
targetGround: true

initialUnguidedSpeedHeight: 3
gravity: 2
spawnUnit: 肿块
pushForce: 0
pushVelocity: 10


[projectile_1]
directDamage: 0
life: 2
speed: 0.01
drawSize: 0
color: #1E1E96

explodeOnEndOfLife: true
spawnUnit: 幼体*2
deflectionPower: -1
explodeEffect: NONE


[leg_1]
x: -30
y: 43
attach_x: -7
attach_y: 10
moveSpeed: 2

rotateSpeed: 6
heightSpeed: 0.5
resetAngle: 8
image_leg: 腿.png
image_foot: NO.png

holdDisMin: 5
holdDisMax: 15
endDirOffset: -20
hardLimit: 20


[leg_2]
x: 30
y: 43
attach_x: 7
attach_y: 10
copyFrom: 1

endDirOffset: 16


[leg_3]
x: -32
y: -38
attach_x: -7
attach_y: -3
copyFrom: 1

endDirOffset: 25


[leg_4]
x: 32
y: -38
attach_x: 7
attach_y: -3
copyFrom: 1

endDirOffset: -25


[leg_5]
x: -39
y: 12
attach_x: -7
attach_y: -3
copyFrom: 1

endDirOffset: -1


[leg_6]
x: 39
y: 12
attach_x: 7
attach_y: -3
copyFrom: 1

endDirOffset: 1


[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 1.3
scaleTo: 1.3
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.2
ySpeedRelativeRandom: 1.2

hSpeed: 1


[effect_爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.7
image: 爆炸.png
total_frames: 10

color: #FFFF1200
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.3

alsoPlaySound: 爆炸.ogg
alpha: 2


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 1
scaleTo: 1
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.8
ySpeedRelativeRandom: 1.8

hSpeed: 1
dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 600
fadeOut: true

attachedToUnit: false
scaleFrom: 3
scaleTo: 6
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡2.ogg


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[arm_1]
x: 0
y: 0
image_end: 背.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.energy(lessThan=12)


[arm_2]
x: 0
y: 0
image_end: 背1.png
image_end_teamColors: true
drawOverBody: true

hidden: if self.energy(lessThan=6)


[movement]
movementType: LAND
moveSpeed: 0.62
moveAccelerationSpeed: 0.5
moveDecelerationSpeed: 0.5
maxTurnSpeed: 0.95

turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false


