

[hiddenAction_寄生b]
addResources: bj= ${bjxq}
[core]
name: 创世纪炼油厂t1
displayText: Нефтеперерабатывающий завод Генезисаt1
displayDescription: 【Уровень t3】【Здание】【Механический юнит】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение:额внеобычный规资源производствосооружение，без вооружения。Генезис石油钻井负责产выходить宝贵 оригинал油维持войнамашинаустройство функционирование，\nв资源匮乏времяоригинал油такжеможетиспользуется для兑换другие资源。\n-ноэтот些危险 оригинал油однажды 引燃тобудет引 毁灭тип взрыв。\n-поэтомутолько建议будет石油钻井развёртыватьв安все послеквадратныйи避освобождать扎堆。

class: CustomUnitMetadata
price: 4000,bj= ${bjxq}
@global bjxq: 30
reclaimPrice: bj= ${bjxq}
maxHp: 13000

copyFrom: ROOT:/通用特效/单位防护.ini
techLevel: 1
buildSpeed: 40s
isBio: false
isBuilding: true
buildingToFootprintOffsetX:0
radius: 70
armour: 10
generation_credits: 15
generation_delay: 40
unitsSpawnedOnDeath:建筑损毁
fireTurretXAtSelfOnDeath: 1
tags: 炼油厂,地面,建筑
footprint: -6,-1,5,5
constructionFootprint: -6,-1,5,5
energyMax: 4
energyRegen: 0.015
energyNeedsToRechargeToFull: true
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[action_精炼2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/建筑特效/精炼技术2.png
text: Технология очистки2
isActive: false
isVisible: if self.globalTeamTags(includes='精炼技术2')
[decal_地板]
image: 油地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-50
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
[decal_影子]
image: SHADOW:油.png
total_frames: 1
layer: shadow
yOffsetRelative:3
xOffsetRelative:4
onlyWhileAlive:true
isVisible:true
alpha:0.5
[decal_支撑]
image: 水下.png
total_frames: 1
layer: shadow
yOffsetRelative:-117
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.isOverLiquid
[decal_泵]
image: 泵.png
total_frames: 20
frame: (self.customTimer * 14) % 20
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-82.5
yOffsetRelative:-55
layer: onTop
onlyWhileAlive:true
[action_炉增益]
autoTrigger:if self.globalTeamTags(includes='精炼技术2')
isVisible: false
addResources:10
[graphics]
total_frames: 1
image: 油.png
image_wreak: 油死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

shadowOffsetX: 3
shadowOffsetY: 3
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 30
maxAttackRange: 99999
shootDelay: 0


[turret_火焰]
x: 95
y: 7
projectile: 13
shoot_flame: CUSTOM:烟雾
delay: 15

invisible: true
size: 1

[turret_火焰1]
x: 95
y: 7
projectile: 13
shoot_flame: CUSTOM:烟雾x,CUSTOM:烟雾1
delay: 3
energyUsage:0.2
invisible: true
size: 1



[turret_1]
x: 0
y: 0
invisible: true
shoot_sound: ROOT:/通用特效/大爆炸1.ogg
shoot_sound_vol: 0.7

shoot_flame: NONE
shoot_light: #FFFFEB88
projectile: 1
canAttackFlyingUnits: false
canAttackLandUnits: false

canAttackUnderwaterUnits: false


[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 28000
areaRadius:250
life: 666
friendlyFire: true

speed: 8888
targetSpeed: 8888
instant: true
flameWeapon: true
deflectionPower: -1
areaDamageNoFalloff: true
explodeEffect: CUSTOM:大爆炸,CUSTOM:气浪,CUSTOM:闪光*2,CUSTOM:弹坑
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2

image: ROOT:/创世纪军事集团/单位特效/巨大爆炸.png
total_frames: 15
animateFrameStart: 0
animateFrameEnd: 15
animateFramePingPong: false

animateFrameSpeed: 0.27
alwayStartDirAtZero: true


[effect_气浪]
life: 90
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false

scaleFrom: 5
scaleTo: 7
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1.4

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 12
scaleTo: 1
drawUnderUnits: false
atmospheric: false


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 3.5
scaleTo: 3.5
createWhenOverLiquid: false
createWhenOverLand: true


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[effect_烟雾2]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/单位特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟雾]
createWhenZoomedOut: false
stripIndex: effects
frameIndex: 0
life: 300
fadeOut: true
priority: verylow
attachedToUnit: false
color: #646464
fadeInTime: 15
scaleFrom: 0.65
scaleTo: 4

alpha: 1
drawUnderUnits: false
hSpeed: 0.6
xSpeedAbsolute: -0.2
hOffsetRandom: 0.15

yOffsetRelative: -2
dirOffsetRandom: 180
shadow: false
xOffsetRelativeRandom: 1
yOffsetRelativeRandom: 1

xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1
atmospheric: true

[effect_烟雾x]
createWhenZoomedOut: false
stripIndex: effects
frameIndex: 0
life: 100
fadeOut: true
priority: low
attachedToUnit: false
color: #646464
fadeInTime: 15
scaleFrom: 0.8
scaleTo: 4.5

alpha: 2
drawUnderUnits: false
hSpeed: 0.8
xSpeedAbsolute: -0.2
hOffsetRandom: 0.3
dirOffsetRandom: 180
shadow: false
xOffsetRelativeRandom: 1
yOffsetRelativeRandom: 1
xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1
atmospheric: true

[effect_烟雾1]
createWhenZoomedOut: false
image: ROOT:/通用特效/爆炸.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
hSpeed: 1
xSpeedAbsolute: -0.2
hOffsetRandom: 0.15
dirOffsetRandom: 90
shadow: false
xOffsetRelativeRandom: 1
yOffsetRelativeRandom: 1
xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1
atmospheric: true
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13
animateFrameSpeed: 0.15
[arm_1]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_2]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[arm_5]
x: -82
y: -30
image_end: 棍子.png
image_end_teamColors: true
drawOverBody: true
[arm_6]
x: -17
y: 13
image_end: 杆子1.png
image_end_teamColors: true
drawOverBody: true
[arm_7]
x: -17
y: 12
image_end: 杆子.png
image_end_teamColors: true
drawOverBody: true
[arm_8]
x: -17
y: 11
image_end: 杆子.png
image_end_teamColors: true
drawOverBody: true
[arm_9]
x: -17
y: 10
image_end: 杆子.png
image_end_teamColors: true
drawOverBody: true
[arm_10]
x: -17
y: 9
image_end: 杆子.png
image_end_teamColors: true
drawOverBody: true
[arm_11]
x: -17
y: 8
image_end: 杆子.png
image_end_teamColors: true
drawOverBody: true
[arm_12]
x: -17
y: 7
image_end: 杆子1.png
image_end_teamColors: true
drawOverBody: true
[arm_13]
x: -17
y: 7
image_end: 杆损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_14]
x: -18.5
y: -26
image_end: 盖.png
image_end_teamColors: true
drawOverBody: true
[arm_15]
x: -18.5
y: -26
image_end: 盖损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[animation_1]
onActions: idle

arm6_0s: {x:0, y:0,dir:0}
arm7_0s: {x:0, y:0,dir:0}
arm8_0s: {x:0, y:0,dir:0}
arm9_0s: {x:0, y:0,dir:0}
arm10_0s: {x:0, y:0,dir:0}
arm11_0s: {x:0, y:0,dir:0}
arm12_0s: {x:0, y:0,dir:0}
arm13_0s: {x:0, y:0,dir:0}

arm6_0.6s: {x:0, y:0,dir:17}
arm7_0.6s: {x:0, y:0,dir:17}
arm8_0.6s: {x:0, y:0,dir:17}
arm9_0.6s: {x:0, y:0,dir:17}
arm10_0.6s: {x:0, y:0,dir:17}
arm11_0.6s: {x:0, y:0,dir:17}
arm12_0.6s: {x:0, y:0,dir:17}
arm13_0.6s: {x:0, y:0,dir:17}

arm6_1.2s: {x:0, y:0,dir:-17}
arm7_1.2s: {x:0, y:0,dir:-17}
arm8_1.2s: {x:0, y:0,dir:-17}
arm9_1.2s: {x:0, y:0,dir:-17}
arm10_1.2s: {x:0, y:0,dir:-17}
arm11_1.2s: {x:0, y:0,dir:-17}
arm12_1.2s: {x:0, y:0,dir:-17}
arm13_1.2s: {x:0, y:0,dir:-17}

arm6_1.5s: {x:0, y:0,dir:0}
arm7_1.5s: {x:0, y:0,dir:0}
arm8_1.5s: {x:0, y:0,dir:0}
arm9_1.5s: {x:0, y:0,dir:0}
arm10_1.5s: {x:0, y:0,dir:0}
arm11_1.5s: {x:0, y:0,dir:0}
arm12_1.5s: {x:0, y:0,dir:0}
arm13_1.5s: {x:0, y:0,dir:0}
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


