
[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true



[core]
name: AI核心作战中枢t1
class: CustomUnitMetadata
price: 3000
maxHp:2500
maxShield: 2500
shieldRenderRadius: 1
shieldRegen: 1
footprint: -6,-3,6,5
constructionFootprint: -6,-3,6,5
tags:余辉指挥中心t1,地面,建筑,无人单位
techLevel: 1
displayDescription: 【阶级t1】【建筑单位】【无人单位】【地面单位】\n-战术定位：核心建筑物。无武装。\n-诺瓦帝国标准预封装战地指挥中枢，用于在星球地表更便捷的指挥，\n-他们可以指挥军团规模的作战单元，以及太空舰队进行作战。\n-这种指挥中枢内含一个或者数个专用于指挥作战的高智能II级AI核心，\n-以及数个无人机发射单元用于自我防卫，\n-这种建筑是发挥诺瓦帝国强大军事实力和征服星域作战的基础。
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1),AI核心作战中枢t1残骸
effectOnDeath: CUSTOM:烟雾*6, CUSTOM:爆破*15
experimental: true
selfBuildRate: 1
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md

isBuilding: true
armour: 0
radius: 90
fogOfWarSightRange: 49

generation_delay: 40
generation_credits: 18
exit_x:0
exit_y: 60
exit_moveAwayAmount: 180
canBuild_11_name: setRally
canBuild_11_pos: 0.1

canBuild_2_isVisible: false
canBuild_2_name: AI核心作战中枢t1空投
canBuild_2_pos: 2
canBuild_2_isLocked:  if numberOfUnitsInTeam(withTag='初始化', greaterThan=0)


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='余辉指挥中心t1')
deleteSelf: true
showMessageToPlayer: 你只能有一坐AI核心作战中枢
[canBuild_T33]
name:爪巴
pos: 1
isVisible: false
isLocked: true
isLockedMessage:🐴
[action_升级]
convertTo: AI核心作战中枢t2
text: 升级
price: 5000
buildSpeed: 45s
ai_isHighPriority: true
highPriorityQueue: false
displayType: upgrade
description: 提升AI核心作战中枢等级，加强防御能力和武器，并使己方进入t2阶段。\n-升级AI核心作战中枢将使我们有能力建造并指挥机甲和船只，\n-并部署更多的其他设施。
pos:0.01
refundAllQueuedItems:true
[action_造筑基虫]
displayType: action
price: 700
buildSpeed: 11s
isVisible: true
highPriorityQueue: true
produceUnits:筑基虫(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: 筑基虫
textAddUnitName:筑基虫
descriptionAddFromUnit: 筑基虫
descriptionAddUnitStats: 筑基虫
allowMultipleInQueue:true
pos:0.2
ai_isHighPriority: true
isLocked: if numberOfUnitsInTeam(greaterThan=3, withTag='农民') and self.isControlledByAI()
[action_造开拓者]
displayType: action
price: 150
buildSpeed: 3.75s
isVisible: true
highPriorityQueue: true
produceUnits:HK开拓者(spawnSource= self.getOffsetRelative(x= 0, y= 1440,dirOffset=180))
whenBuilding_playAnimation: 开门
unitShownInUI: HK开拓者
textAddUnitName:HK开拓者
descriptionAddFromUnit: HK开拓者
descriptionAddUnitStats: HK开拓者
allowMultipleInQueue:true
pos:0.3
ai_isHighPriority: false














[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
yOffsetRelative:8
xOffsetRelative:8
onlyWhileAlive:true
isVisible:true
alpha:0.6

[decal_光]
image: ROOT:/余辉军团/建筑特效/老家灯.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
alpha:0.6


[decal_遮盖]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true

[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true

[decal_转子]
image: ROOT:/余辉军团/建筑特效/老家动画.png
total_frames: 3
frame: (self.customTimer * 15) % 3
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:0
yOffsetAbsolute:-36
isVisible:true
onlyWhileAlive:true
layer: onTop


[decal_光头]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:0.5
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1

[graphics]
total_frames: 1
image: NO.png
image_back: ROOT:/余辉军团/建筑特效/老家地板.png
image_wreak:ROOT:/余辉军团/建筑特效/老家死亡.png
image_turret: NONE
#imageScale: 0.8
#turretImageScale: 0.75
showShotDelayBar:false

#image_offsetY: -50
[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
maxAttackRange: 0
turretTurnSpeed: 50
turretMultiTargeting: true

[arm_1]
x: 0
y: 0
image_end:ROOT:/余辉军团/建筑特效/老家钢门.png
image_end_teamColors: true
drawOverBody: true
moveSpeed:0.3

[animation_开门]
blendIn: 0.1s
blendOut: 0.1s
arm1_0s: {x:0, y:0, dir:0}

arm1_2s: {x:0, y:33, dir:0}

arm1_999s: {x:0, y:33, dir:0}





[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 60
yOffsetRelativeRandom: 100
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: 30
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
xOffsetRelativeRandom:70
yOffsetRelativeRandom:160
delayedStartTimerRandom:30
yOffsetRelative: 50
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[ai]
ai_upgradePriority: 1
buildPriority: 0.01



