


[core]
name: 请选择空降地点
displayText: пожалуйставыбордесант очко
class: CustomUnitMetadata
price: 0
maxHp: 999999
footprint: 0,0,0,0
mass:99999999
constructionFootprint: 0,0,0,0
techLevel: 1
buildSpeed: 0.0005
isBio: false
isBuilding: true
canNotBeDamaged:true
radius: 90
nanoRange: 400
nanoBuildSpeed: 99
canRepairBuildings: true
disableAllUnitCollisions:true
canRepairUnits: true
explodeOnDeath: false
hideScorchMark: true
canReclaimResources: true
showInEditor: false
energyStartingPercentage: 1
energyMax: 12
energyRegen: -0.005

canBuild_2_isVisible: if numberOfUnitsInTeam(withTag='初始化', lessThan=1)
canBuild_2_name: AI核心作战中枢t1空投
canBuild_2_pos: 2
canBuild_2_isLocked:  if numberOfUnitsInTeam(withTag='初始化', greaterThan=0)


[decal_2]
image: ROOT:/通用特效/外圈.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:true
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:(self.energy)/12
[decal_4]
image: ROOT:/通用特效/外圈1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:true
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/12
alwaysStartDirAtZero:true
imageScale:(self.energy)/12
[decal_1]
image: 目标.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:true
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
[decal_3]
image: 目标1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:true
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/12
alwaysStartDirAtZero:true
[decal_9]
image: ROOT:/通用特效/准星1.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:true
layer: beforeUI
onlyWhileAlive:true
alwaysStartDirAtZero:true
imageScale:1.6
[decal_10]
image: ROOT:/通用特效/准星.png
total_frames: 1
xOffsetRelative:0
yOffsetRelative:0
isVisible:true
layer: beforeUI
onlyWhileAlive:true
alpha:(self.energy)/12
imageScale:1.6
alwaysStartDirAtZero:true
[decal_主体]
image: 核心.png
total_frames: 1
layer: beforeUI
isVisible:true
onlyWhileAlive:true
alpha:0.8
imageScale:0.38
alwaysStartDirAtZero:true



[action_t1]
autoTrigger: if self.isControlledByAI() and numberOfUnitsInTeam(withTag='初始化', lessThan=1) and numberOfUnitsInTeam(withTag='余辉指挥中心t1', lessThan=1)
isVisible: false
spawnUnits:AI核心作战中枢t1空投(gridAlign=true, skipIfOverlapping=false,offsetHeight=2000)


[action_t2]
autoTrigger: if numberOfUnitsInTeam(withTag='余辉指挥中心t1', greaterThan=0)
isVisible: false
deleteSelf: true

[action_t1tt]
autoTrigger:if self.isEnergyEmpty() and numberOfUnitsInTeam(withTag='初始化', lessThan=1) and numberOfUnitsInTeam(withTag='余辉指挥中心t1', lessThan=1)
isVisible: false
spawnUnits:AI核心作战中枢t1空投(gridAlign=true, skipIfOverlapping=false,offsetHeight=2000)
[graphics]
total_frames: 1
image: null.png
image_wreak: NONE
image_turret: NONE
#imageScale: 0.7
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 400

turretSize: 0
turretTurnSpeed: 50

[turret_233]
x: 0
y:0
projectile: 233
delay: 1000s
canAttackMaxAngle: 181
invisible: true
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0


[ai]
useAsBuilder: true


