


[core]
name: 维护者无人机
displayText: Дрон «Хранитель»
displayDescription: -哇袄！
price: -1
maxHp: 2500

techLevel: 1
buildSpeed: 15s
copyFrom: ROOT:/通用特效/单位防护.ini
availableInDemo: true
armour: 3

radius: 28
displayRadius: 28
softCollisionOnAll: 10
isBio: false
tags: 飞机,低空,维修飞机,寄生免疫,伴生单位
canNotBeGivenOrdersByPlayer: true
showInEditor: false
energyMax: 45
energyRegen: 0
energyNeedsToRechargeToFull: true
fogOfWarSightRange: 18
canRepairBuildings: true
autoRepair: false
canRepairUnits: true
nanoRepairSpeed: 2
nanoRange: 150
nanoBuildSpeed:0
[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'


[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'
[hiddenAction_return]
autoTrigger: if not self.hasActiveWaypoint(type='repair') and numberOfUnitsInTeam(withTag='需要维修',lessThan=1, withinRange=550) or distanceBetweenSquared(self, customTarget1) > 600 * 600
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto
clearActiveWaypoint: true
[hiddenAction_return1]
# 没能量时返航
autoTrigger: if self.energy==0 and not self.hasParent() and not self.hasActiveWaypoint(type='loadInto')
clearActiveWaypoint: true
# addWaypoint_prepend: true
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own
addWaypoint_maxTime: 10s
addWaypoint_type: loadInto





[hiddenAction_disconnect]
autoTrigger: if self.hasParent() and not self.hasActiveWaypoint(type='repair') and self.energy(full=true) and numberOfUnitsInTeam(withTag='需要维修',greaterThan=0, withinRange=550) and self.isInMap()
disconnectFromParent: true
clearActiveWaypoint: true
addWaypoint_target_nearestUnit_tagged: 需要维修
addWaypoint_type: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_target_nearestUnit_maxRange:550

[hiddenAction_补丁]
autoTrigger: if not self.hasParent() and not self.hasActiveWaypoint(type='repair') and self.energy>0 and numberOfUnitsInTeam(withTag='需要维修',greaterThan=0, withinRange=550) and self.isInMap() and not self.hasActiveWaypoint(type='loadInto')
addWaypoint_target_nearestUnit_tagged: 需要维修
addWaypoint_type: repair
addWaypoint_target_nearestUnit_team: own
addWaypoint_target_nearestUnit_maxRange:550
[hiddenAction_energy]
autoTrigger: if not self.energy(full= true) and self.hasParent()
addEnergy: 45
[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
# 这条在鹰爪和雪崩里忘改成这样了，原本是打算航母凉后灰机用完能量才自杀，不过有bug忘了改回来
addResources: hp= -999999
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[hiddenAction_zz]
autoTrigger:if not self.hasParent
addResources: energy=-1
[decal_维修吊臂]
image: 维修吊臂.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 0
[decal_机体]
image: 机体.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale: 0.85
teamColors: true
[graphics]
total_frames: 1
image: 机体.png
image_wreak: 死亡.png
image_turret: NONE
#imageScale: 
repairEffect: CUSTOM:尾巴, CUSTOM:尾巴1
repairEffectAtTarget:CUSTOM:闪光, CUSTOM:火花*4
repairEffectRate:10
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.85
turretImageScale: 0.85

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 4

maxAttackRange: 0
shootDelay: 5

[turret_0]
x: 0
y: 0
warmup: 0
size: 50
canShoot: false
isMainNanoTurret: true
image: NO.png
idleDir:180
[effect_尾巴1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low
ySpeedRelativeRandom: 0.5
ySpeedRelative: 1
color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1
drawUnderUnits: true
[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 100
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
#ySpeedRelativeRandom: 0.5
drawUnderUnits: false
ySpeedRelative: 2
yOffsetRelative	: 10
[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 2
drawUnderUnits:false
atmospheric: false
[effect_火花]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.35
physics: true
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: 光束.png
alpha: 0.85
drawUnderUnits:false
xOffsetRelativeRandom:25
yOffsetRelativeRandom:25
[arm_1]
x: 0
y: 0
image_end: 螺旋桨起飞.png
drawOverBody: true
spinRate: 30
hidden:if self.hasParent()
[arm_2]
x: 0
y: 0
image_end: 螺旋桨.png
drawOverBody: true
hidden:if not self.hasParent()
[movement]
movementType: AIR
targetHeight: 70
targetHeightDrift: 2
moveSpeed: 2.2
moveAccelerationSpeed: 0.03

moveDecelerationSpeed: 0.06
maxTurnSpeed: 4
turnAcceleration: 1
slowDeathFall: true
moveSlidingMode : true

moveIgnoringBody: true
moveSlidingDir: 120


