


[core]
name: 重型多联炮t2
class: CustomUnitMetadata
price: 3500
maxHp: 5000
footprint: 0,0,1,1

constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 13
techLevel: 1
buildSpeed: 0
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
radius: 25
buildingSelectionOffset: -8
isBuilding: true
copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.12

isBio: false
effectOnDeath: CUSTOM:烟雾2*2,CUSTOM:爆炸*1
tags: 地面,灰影建筑,建筑
armour: 12


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: 缺少供能
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: ROOT:/太空浪人/建筑特效/防御塔t2.png
image_wreak: ROOT:/太空浪人/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
imageScale: 0.9

turretImageScale: 0.8


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 150

turretSize: 23
turretTurnSpeed: 3
maxAttackRange: 400
#aimOffsetSpread: -0.01


[turret_3]
x: -8
y: 23
canShoot: true
recoilOffset: -4
projectile: 2

#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2

delay: 50
warmup: 0
attachedTo: 6
image: 炮管.png
slave: true

size: 12
canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)


[turret_4]
x: 8
y: 23
canShoot: true
recoilOffset: -4
projectile: 2

#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2

delay: 50
warmup: 5
attachedTo: 6
image: 炮管.png
slave: true

size: 12
canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)


[turret_5]
x: 3
y: 23
canShoot: true
recoilOffset: -4
projectile: 2

#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2

delay: 50
warmup: 10
attachedTo: 6
image: 炮管.png
slave: true

size: 12
canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)


[turret_7]
x: -3
y: 23
canShoot: true
recoilOffset: -4
projectile: 2

shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪,CUSTOM:光粒*2
delay: 50

warmup: 15
attachedTo: 6
image: 炮管.png
slave: true
size: 12

canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)


[turret_6]
x: 0
y: 22
image: 副炮.png
canShoot: false
canAttackCondition: if self.resource.xk < 1

turnSpeed: 4.5
idleSweepAngle: 100
idleSweepDelay: 210
idleSweepSpeed: 0.2


[projectile_2]
@copyFromSection: template_动能
areaDamage: 130
areaRadius: 50
life: 300
#lightSize:1

explodeEffect: CUSTOM:爆炸2, CUSTOM:闪光1
explodeEffectOnShield: CUSTOM:爆炸2, CUSTOM:闪光1
speed: 10
#trailEffect:CUSTOM:尾巴1
drawSize: 0.55

image: ROOT:/太空浪人/单位特效/星星1.png
#deflectionPower:-1
#trailEffectRate:4
areaRadiusFromEdge: true
#targetGroundSpread: 35

#targetGround: true
#lightColor:#FFFF1200
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_爆炸2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.5

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[effect_闪光1]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2

yOffsetRelative: 0.3
ySpeedRelative: 0.5
atmospheric: true


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 1

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.5
ySpeedAbsoluteRandom: 1
ySpeedRelative: 1
#xOffsetRelative:-2

atmospheric: true


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 空塔楼t1传送
ai_upgradePriority: 0.07


