


[core]
name: SDD黄蜂无人机
displayDescription: 
class: CustomUnitMetadata
price: 2
maxHp: 800

maxShield: 700
shieldRegen: 0.05
energyMax: 4
energyRegen: 0
energyNeedsToRechargeToFull: true
showInEditor: false
tags: 战机,飞机,寄生免疫,低空,伴生单位
buildSpeed: 4s
techLevel: 2
radius: 10
copyFrom: ROOT:/通用特效/单位防护.ini

displayRadius: 10
isBio: false
softCollisionOnAll: 100
canNotBeGivenOrdersByPlayer: true

[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'
[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'


[hiddenAction_return1]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( self.isEnergyRecharging or distanceBetweenSquared(self, customTarget1) > 1000 * 1000 )
# distanceBetweenSquared 返回两个单位之间的平方距离。 比 distanceBetween 快一点，因为少了开方这一步。1100² 判断灰机离母体有多远，超过1100回家
clearActiveWaypoint: true
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto


[hiddenAction_disconnect]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( not self.hasActiveWaypoint(type= 'attack') or activeWaypointTarget.height >10)
disconnectFromParent: true
clearActiveWaypoint: true
addWaypoint_type: attack
addWaypoint_prepend: true

addWaypoint_target_fromReference: customTarget1.attacking
addWaypoint_triggerActionIfMatched: 补丁
addWaypoint_triggerActionIfFailed: return1


[hiddenAction_补丁]
requireConditional: if not self.hasParent and not self.hasActiveWaypoint(type= 'attackMove')
addWaypoint_type: attackMove
addWaypoint_target_fromReference: thisActionTarget




[hiddenAction_energy]
autoTriggerOnEvent: enteredTransport
addResources:energy=61


[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
# 这条在鹰爪和雪崩里忘改成这样了，原本是打算航母凉后灰机用完能量才自杀，不过有bug忘了改回来
addResources: hp= -999999








[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999

[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: 正电子芯核
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[graphics]
total_frames: 3
image: 黄蜂.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.8
animation_moving_start: 2
animation_moving_end: 2

animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: if self.isInMap
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 4
maxAttackRange: 1040
# 900+140 类星体有个槽位在140那边
attackMovement: bomber
# isMelee:true

# meleeEngangementDistance:1600


[turret_2]
x: 0
y: 0
invisible: true
limitingRange: 280
canAttackCondition: if not self.hasParent()

shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FF004AFF
projectile: 1

energyUsage: 4
delay: 2


[turret_233]
x: 0
y: 0
# limitingRange: 580
projectile: 233
delay: 0.9s

canAttackMaxAngle: 181
canAttackCondition: if self.energy(full= true) and self.hasParent()
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false

invisible: true
onShoot_triggerActions: disconnect


[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true


[projectile_1]
@copyFromSection: template_爆炸
life: 180
speed: 6
targetSpeed: 8
largeHitEffect: true

lightSize: 1
lightColor: #FF00B3FF
drawSize: 0.7
image: ROOT:/余辉军团/单位特效/鱼雷.png
trailEffect: true

directDamage: 600
explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸1, CUSTOM:闪光
deflectionPower: 1


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_爆炸1]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1

scaleTo: 1.8
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[movement]
movementType: AIR
reverseSpeedPercentage: 0
moveSpeed: 3.5
moveAccelerationSpeed: 2.5
moveDecelerationSpeed: 0

targetHeightDrift: 0.3
targetHeight: 70
maxTurnSpeed: 90
turnAcceleration: 0.1
moveSlidingMode: false

moveIgnoringBody: false
moveSlidingDir: 0
slowDeathFall: true


