


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 帝王级战列舰
class: CustomUnitMetadata
price: 17000,awz= ${awzxq}
@global awzxq: 300
reclaimPrice: awz= ${awzxq}

maxHp: 30000
displayDescription: -帝王级战列舰是法雅德家族科研力量的结晶，无论从他庞大的身躯，\n-还是夸张的武器，还是摆满飞机的甲板来看，无一不显示着法雅德家族在星系中的地位与力量。\n-在帝王级战列舰研发的时候，当时希诺星系几乎没有任何一艘战舰要比帝王还要巨大宏伟。\n-而帝王级战列舰，更是作为了法雅德家族在诺瓦帝国开国之年送给皇帝的礼物，\n-只不过可惜的是，皇帝在对比浮岛要塞与帝王后，发现帝王级还是不敌浮岛要塞，\n-而帝王级战列舰也因此而停产，仅存的帝王级战列舰因为古人类统一后再无战事而荒废，\n-直到与余辉开战的时候，余辉和法雅德家族才领略到帝王级战列舰真正的威力，\n-在艾文诺拉星系防御战中，帝王级战列舰宛如战神一般在海面上以一当十，\n-帝王级战列舰恐怕是余辉最害怕，也最不愿意见到的水面舰艇了。\n-对地对空，动能伤害，导弹以及飞机能源伤害。
techLevel: 1
buildSpeed: 70s
availableInDemo: true

radius: 130
displayRadius: 130
isBio: false
softCollisionOnAll: 7
selfRegenRate: 0.8

armour: 100
fogOfWarSightRange: 40
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 航母lr,地面,海上,极端重型
maxTransportingUnits: 5

transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机lrx
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air

transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]
effectOnDeath: CUSTOM:爆炸5*1,CUSTOM:冲击波2,CUSTOM:水波1
[action_重]
text: 极端重型单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积夸张的单位独有的特性，\n-拥有极端重型单位标签的单位将拥有如下属性，\n-拥有自愈能力，且自身护甲不低于100点，\n-难以被休克，但是受到反重甲单位伤害增益。
[decal_主体损坏a]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: 缺少暗物质
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: 赛格门塔护甲1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')




[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 5
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 5
addUnitsIntoTransport: 雪崩


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1

[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)
[hiddenAction_↯a]
autoTrigger: if self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 身体2.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 5
shadowOffsetY: 5
splastEffect: true
teamColorsOnTurret: true
turretImageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: if self.resource.awz>-1
canAttackLandUnits: if self.resource.awz>-1
canAttackUnderwaterUnits: false
shootDelay: 75

maxAttackRange: 800
turretMultiTargeting: true


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-400
projectile: 13
delay: 120

size: 0
#limitingRange:2


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_1]
x: -9
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10
recoilReturnTime: 25
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg
shoot_sound_vol: 0.3

shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
#warmup:10
attachedTo: 5

image: 炮管.png
canAttackFlyingUnits: false
slave: true
size: 12


[turret_2]
x: -3.5
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10
recoilReturnTime: 25
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg
shoot_sound_vol: 0.3

shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
warmup: 5
canAttackFlyingUnits: false

attachedTo: 5
image: 炮管.png
slave: true
size: 12


[turret_3]
x: 9
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10

recoilReturnTime: 25
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg
shoot_sound_vol: 0.3

shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
warmup: 10
attachedTo: 5

canAttackFlyingUnits: false
image: 炮管.png
slave: true
size: 12


[turret_4]
x: 3.5
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10

recoilReturnTime: 25
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg
shoot_sound_vol: 0.3

shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
canAttackFlyingUnits: false
warmup: 15

attachedTo: 5
image: 炮管.png
slave: true
size: 12


[turret_5]
x: -52
y: 8
idleDir: -20
image: 主炮.png
canShoot: false

#idleDir:-45
turnSpeed: 1.2
canAttackFlyingUnits: false
limitingAngle: 70


[turret_6]
x: -9
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10

recoilReturnTime: 25
canAttackFlyingUnits: false
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg

shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
#warmup:10

attachedTo: 10
image: 炮管.png
slave: true
size: 12


[turret_7]
x: -3.5
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10
recoilReturnTime: 25
canAttackFlyingUnits: false
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg

shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
warmup: 5

attachedTo: 10
image: 炮管.png
slave: true
size: 12


[turret_8]
x: 9
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10

recoilReturnTime: 25
canAttackFlyingUnits: false
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg

shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
warmup: 10

attachedTo: 10
image: 炮管.png
slave: true
size: 12


[turret_9]
x: 3.5
y: 35
canShoot: true
recoilOffset: -7
recoilOutTime: 10

recoilReturnTime: 25
canAttackFlyingUnits: false
projectile: 1
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/主炮.ogg

shoot_sound_vol: 0.3
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*4,CUSTOM:光粒*6
delay: 240
warmup: 15

attachedTo: 10
image: 炮管.png
slave: true
size: 12


[turret_10]
x: 52
y: 8
idleDir: 20
image: 主炮.png
canShoot: false

#idleDir:-45
turnSpeed: 1.2
limitingAngle: 70
canAttackFlyingUnits: false


[turret_11]
x: 0
y: 15
canShoot: true
recoilOffset: -7
recoilOutTime: 10
recoilReturnTime: 25
projectile: 2
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/激光炮音效.ogg
shoot_sound_vol: 0.5

shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*6,CUSTOM:光粒*9
delay: 250
warmup: 30
attachedTo: 12

image: 枪管.png
slave: true
size: 19
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png


[turret_12]
x: -60
y: -91
idleDir: -20
image: 副炮.png
canShoot: false

#idleDir:-45
turnSpeed: 1.2
limitingAngle: 70
recoilOffset: -2
recoilOutTime: 5

recoilReturnTime: 10


[turret_13]
x: 0
y: 15
canShoot: true
recoilOffset: -7
recoilOutTime: 10
recoilReturnTime: 25
projectile: 2
#invisible: true
shoot_sound: ROOT:/太空浪人/单位特效/激光炮音效.ogg
shoot_sound_vol: 0.5

shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*6,CUSTOM:光粒*9
delay: 250
warmup: 30
attachedTo: 14

image: 枪管.png
slave: true
size: 19
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png


[turret_14]
x: 60
y: -91
idleDir: 20
image: 副炮.png
canShoot: false
#idleDir:-45
turnSpeed: 1.2
limitingAngle: 70
recoilOffset: -2
recoilOutTime: 5

recoilReturnTime: 10


[turret_15]
x: -22
y: -100
canShoot: true
#recoilOffset:-2
idleDir: -30

projectile: 3
image: 导弹.png
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.35
shoot_light: #FFFF1200

shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*3
delay: 100
limitingAngle: 130
size: 4


[turret_16]
x: 22
y: -100
canShoot: true
#recoilOffset:-2
idleDir: 30
projectile: 3
image: 导弹.png
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.35
shoot_light: #FFFF1200

shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*3
delay: 100
limitingAngle: 130
size: 4
[turret_233]
x: 0
y: 0
# limitingRange: 580
projectile: 233
delay: 2.2s

canAttackMaxAngle: 181
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true


[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true

[projectile_1]
@copyFromSection: template_动能
directDamage: 400
life: 200
speed: 9
image: ROOT:/太空浪人/单位特效/大炮弹.png

targetSpeed: 9
drawSize: 0.45
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*7,CUSTOM:冲击波,CUSTOM:爆炸2
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*7,CUSTOM:冲击波,CUSTOM:爆炸2
lightSize: 0.75

trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
lightColor: #FFFF1200


[projectile_2]
@copyFromSection: template_动能
directDamage: 700
life: 10
instant: true
laserEffect: true

explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光1,CUSTOM:聚变,CUSTOM:冲击波,CUSTOM:粒*7
explodeEffectOnShield: CUSTOM:爆炸1, CUSTOM:闪光1,CUSTOM:聚变,CUSTOM:冲击波,CUSTOM:粒*7
lightSize: 0.75
beamImage: ROOT:/太空浪人/单位特效/光束3.png
#color:#FFFF1200


[projectile_3]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1

frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定*3


[projectile_锁定]
@copyFromSection: template_能源
life: 420
speed: 3
targetSpeed: 9
largeHitEffect: true

drawSize: 1.25
trailEffect: true
directDamage: 80
image: ROOT:/太空浪人/单位特效/光束.png
explodeEffectOnShield: CUSTOM:爆炸3

explodeEffect: CUSTOM:爆炸3
wobbleAmplitude: 3
lightColor: #FFFF1200
#摆动幅
wobbleFrequency: 240

#摆动频率
turnSpeed: 30


[effect_爆炸1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.48
scaleTo: 0.7

image: ROOT:/太空浪人/单位特效/核弹.png
total_frames: 21
animateFrameStart: 0
animateFrameEnd: 21
animateFramePingPong: false

animateFrameSpeed: 0.27
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光1]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_粒]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom: 0.1
scaleTo: 0.4

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2

ySpeedRelativeRandom: 2.2
#atmospheric: true


[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_爆炸5]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.2

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/爆炸.ogg
alwayStartDirAtZero: true


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2

yOffsetRelative: 0.3
ySpeedRelative: 0.5
atmospheric: true


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 1

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.4
yOffsetRelative: 0.5
ySpeedAbsoluteRandom: 1
ySpeedRelative: 1
#xOffsetRelative:-2

atmospheric: true


[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.6
scaleTo: 0.6

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2.3

ySpeedRelativeRandom: 2.3
#atmospheric: true


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.7
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_爆炸2]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.3

scaleTo: 1.3
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 15
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7

drawUnderUnits: false


[effect_爆炸3]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[attachment_drone1]
x: 0
y: 0
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
idleDir: 45

height: 1


[attachment_drone2]
x: 0
y: 30
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
idleDir: 45

height: 1


[attachment_drone3]
x: 0
y: 60
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
height: 1

idleDir: 45


[attachment_drone4]
x: 0
y: 90
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
height: 1

idleDir: 45


[attachment_drone5]
x: 0
y: 120
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
height: 1

idleDir: 45




[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.4
scaleTo: 1.4
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 2.2
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.3

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: WATER
moveSpeed: 0.75
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06
maxTurnSpeed: 0.5

turnAcceleration: 0.1
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


