


[core]
name: 冥蜂
displayText: Тёмная Пчела
class: CustomUnitMetadata
displayDescription: -每当一场余辉与创世纪惨烈的空战之后，\n-灰影病毒就会将散落在地面上的飞机残骸组装成冥蜂战机，\n-随后，无数的冥蜂便会像苍蝇一样从那些机械残骸中复活，\n-他们那犹如洪水一般的数量可以轻易摧毁任何试图抵挡他们的敌人。\n-灰影病毒对飞行器的改造，更是证明了其纳米工艺上升到了一个新的高度。\n-对地对空，动能伤害且反掩体，生物单位。
price: hy=240
maxHp: 600

mass: 20000
techLevel: 1
buildSpeed: 3s
availableInDemo: true
fogOfWarSightRange: 17
isUnrepairableUnit:true
armour: 8
radius: 29
displayRadius: 29
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini

softCollisionOnAll: 17
energyMax: 6
energyRegen: 0.024
energyNeedsToRechargeToFull: true
tags: 飞机,步兵,寄生免疫,低空


[action_灰影寄生虫科技提示1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/灰影寄生虫.png
text: Паразит «Серая Тень» 1
isActive: false
isVisible: if self.globalTeamTags(includes='寄生虫1')


[graphics]
total_frames: 2
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 0.85

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 0
animation_moving_end: 1

animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 270
isFixedFiring: true


[turret_0]
x: 0
y: 0
invisible: true
canShoot: false


[turret_3]
x: 19
y: 17.5
invisible: true
shoot_sound: ROOT:/创世纪军事集团/建筑特效/机枪塔音效.ogg
shoot_sound_vol: 0.1

shoot_light: #FFFFEB88
shoot_flame: CUSTOM:枪口火焰
projectile: 1
attachedTo: 0
slave: true

delay: 30
#canAttackCondition:if not self.globalTeamTags(includes='轨道发射器2') and self.flying
warmup: 200
warmupCallDownRate: 0.6
warmupNoReset: true

warmupShootDelayTransfer: 25
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='寄生虫1')


[turret_4]
x: -19
y: 17.5
invisible: true
attachedTo: 0
slave: true

shoot_sound: ROOT:/创世纪军事集团/建筑特效/机枪塔音效.ogg
shoot_sound_vol: 0.1
shoot_light: #FFFFEB88
shoot_flame: CUSTOM:枪口火焰
projectile: 1

delay: 30
#canAttackCondition:if not self.globalTeamTags(includes='轨道发射器2') and self.flying
warmup: 200
warmupCallDownRate: 0.6
warmupNoReset: true

warmupShootDelayTransfer: 25
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='寄生虫1')


[projectile_1]
@copyFromSection: template_动能
directDamage: 16
life: 60
speed: 9
targetSpeed: 9

deflectionPower: -1
drawSize: 0.75
color: #FFFFFF73
frame: 8
explodeEffect: CUSTOM:火花
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_炮弹]
@copyFromSection: template_爆炸
directDamage: 19
life: 60
speed: 9
targetSpeed: 9
tags: 灰影寄生虫
deflectionPower: -1
drawSize: 0.75
color: #FF68FF2E
frame: 8
explodeEffect: CUSTOM:火花j
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: JSC=0.001
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
scaleFrom: 2

scaleTo: 2
animateFrameStart: 0
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false


[effect_火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.4
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12

animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2


[effect_火花j]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.3
image: ROOT:/太空浪人/单位特效/波雷爆炸1.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 2


[movement]
movementType: AIR
moveSpeed: 2.3
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02
maxTurnSpeed: 2.5

turnAcceleration: 1
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: true
targetHeight: 70


