
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 钍激光钻机t1
displayText: 钍激光钻机
displayDescription: 【阶级t3】【建筑单位】【机械单位】【地面单位】【水上单位】（当部署在水上时）\n-战术定位:特殊资源生产设施，无武装，钍激光钻机用于分离稀土矿石并提纯钍元素，\n-创世纪的高级科技都离不开钍和钍裂变堆。
class: CustomUnitMetadata
price: 3000,bj= ${bjxq}
@global bjxq: 50
reclaimPrice: bj= ${bjxq}
maxHp: 20000
unitsSpawnedOnDeath:建筑损毁
techLevel: 1
buildSpeed: 20s
footprint: -4,-1,4,5
copyFrom: ROOT:/通用特效/单位防护.ini
constructionFootprint: -4,-1,4,5
radius: 60
isBio: false
effectOnDeath: CUSTOM:烟雾1*4, CUSTOM:爆破*8,largeExplosion
isBuilding: true
tags: 激光钻机,地面,建筑
numBitsOnDeath: 13
softCollisionOnAll: 3
armour: 20
generation_delay: 40
generation_resources: 钍原石=12
[action_未超载]
text: 未超载
isVisible: if numberOfUnitsInTeam(lessThan=3, withTag='激光钻机')
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/开.png
isLockedMessage: 钍激光钻机需要高额的后勤维护，当钻机的数量超过2个时，\n-每个钍激光钻机将会产生每秒-35的资源惩罚。

[action_已超载]
text: 已超载
isVisible: if numberOfUnitsInTeam(greaterThan=2, withTag='激光钻机')
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/关.png
isLockedMessage: 你建造太多钍激光钻机了，\n-现在每个钍激光钻机将会产生每秒-35的资源惩罚。
[hiddenAction_扣钱]
autoTrigger: if numberOfUnitsInTeam(greaterThan=2, withTag='激光钻机')
addResources:-35
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[action_精炼2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/建筑特效/精炼技术2.png
text: 精炼技术2
isActive: false
isVisible: if self.globalTeamTags(includes='精炼技术2')
[action_炉增益]
autoTrigger:if self.globalTeamTags(includes='同步轨道加速器')
isVisible: false
addResources:钍=3
[action_炉增益1]
autoTrigger:if self.globalTeamTags(includes='精炼技术2')
isVisible: false
addResources:钍原石=6
[decal_地板]
image: 钍地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-36
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
[decal_影子]
image: SHADOW:钍.png
total_frames: 1
layer: shadow
yOffsetRelative:4
xOffsetRelative:5
onlyWhileAlive:true
isVisible:true
alpha:0.5
[decal_支撑]
image:水下.png
total_frames: 1
layer: shadow
yOffsetRelative:-106
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.isOverLiquid
alpha:1

[decal_转子]
image: 转子.png
total_frames: 2
frame: (self.customTimer * 15) % 2
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-1.5
yOffsetRelative:71
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
[decal_灯光]
image: 灯.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.85
[decal_损坏]
image:损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_激光]
image: 激光.png
total_frames: 5
frame: (self.customTimer * 15) % 5
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-1.5
yOffsetRelative:7
isVisible:true
onlyWhileAlive:true
layer: onTop
alpha:0.8
[graphics]
total_frames: 1
image: 钍.png
image_wreak: 死亡.png
image_back: ROOT:/通用特效/NO.png
image_shadow: NONE

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 30
maxAttackRange: 99999
shootDelay: 0


[turret_火焰]
x: 0
y: -10
projectile: 13
shoot_flame: CUSTOM:烟雾,CUSTOM:闪光
delay: 20

invisible: true
size: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[effect_烟雾]
createWhenZoomedOut: false
stripIndex: effects
frameIndex: 0
life: 300
fadeOut: true

attachedToUnit: false
color: #646464
fadeInTime: 15
scaleFrom: 0.65
scaleTo: 4

alpha: 0.7
drawUnderUnits: false
hSpeed: 0.6
xSpeedAbsolute: -0.2
hOffsetRandom: 0.15

yOffsetRelative: -2
atmospheric: true
dirOffsetRandom: 180
shadow: true
xOffsetRelativeRandom: 1

yOffsetRelativeRandom: 1
xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 0.7

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 0

drawUnderUnits: false
atmospheric: false


[effect_烟雾1]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 30
yOffsetRelativeRandom: 30
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:45
yOffsetRelativeRandom:55
delayedStartTimerRandom:30


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[arm_1]
x: 0
y: 0
image_end: 灯1.png
image_end_teamColors: false
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[animation_idle]
onActions : idle
arm1_0s: {alpha:0.0}
arm1_1.5s: {alpha:0.8}
arm1_3s: {alpha:0.1}
[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
noneGlobalExtraPriority: 0.2
maxEachBase: 4
maxGlobal: 20


