


[core]
name: 太空浪人多相聚变堆t2
class: CustomUnitMetadata
displayDescription:  用超合金板对聚变堆关键部位进行加固，使得其更难被摧毁。
price: 1500
maxHp: 4500

footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1
techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 3s

isBio: false
#showInEditor:false
isBuilding: true
selfRegenRate: 0.12
radius: 20

effectOnDeath: CUSTOM:冲击波, CUSTOM:爆炸,CUSTOM:闪光
tags: 聚变堆,d,地面,灰影建筑,建筑
armour: 10
buildingToFootprintOffsetY: -5


[action_升级为被感染的聚变堆]
convertTo: 被感染的聚变堆
displayType: action
text: 升级为被感染的聚变堆
price: hy=2400
buildSpeed: 18s

isVisible: if self.globalTeamTags(includes='灰影1')
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.queueSize(greaterThan= 0.5)
isLockedMessage: 你需要三级枢纽，且一次只能选择一种升级
ai_isHighPriority: true
description: 用灰影病毒覆盖多相聚变堆，使其在保持供能的同时，\n-还能向供能范围内的所有我方单位和建筑，提供35%的伤害加成，\n-以及每秒25点的生命值回复，不可叠加。


[action_升级为折越聚变堆]
convertTo: 折跃门聚变堆
displayType: action
text: 升级为折跃门聚变堆
price: 7500
buildSpeed: 25s

isVisible: if self.globalTeamTags(includes='灰影1')
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.queueSize(greaterThan= 0.5)
isLockedMessage: 你需要三级枢纽，且一次只能选择一种升级
ai_isHighPriority: true
description: 将允许附近生产机械单位的浪人工厂，开启折越模式，\n-将能直接把传送门部署于任何有传送立场的地方，并快速折越单位，\n-这将极大提升生产效率以及节约路程时间。
ai_isDisabled: true

[action_升级为堡垒聚变堆]
convertTo: 堡垒聚变堆
displayType: action
text: 升级为堡垒聚变堆
price: 4000
buildSpeed: 30s

isVisible: if self.globalTeamTags(includes='灰影1')
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.queueSize(greaterThan= 0.5)
isLockedMessage: 你需要三级枢纽，且一次只能选择一种升级
ai_isHighPriority: true
description: 堡垒聚变堆改用强固型超合金浇筑，拥有惊人的抗打击能力，\n-并且内置一套瓦普驱动炮系统，使其更难被摧毁。\n-对地对空，能源伤害。


[action_T1]
pos: 0
buildSpeed: 0s
addResources: setFlag=0,setFlag=1
isVisible: if not self.hasFlag(id=1) and not self.hasFlag(id=0)
text: 显示供能范围


[action_T1_back]
pos: 0
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=1
isVisible: if self.hasFlag(id=1)
text: 不显示供能范围


[graphics]
total_frames: 19
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

animation_idle_start: 0
animation_idle_end: 18
animation_idle_speed: 8
imageScale: 0.95
image_shadow: 影子.png


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 400

turretSize: 0
turretTurnSpeed: 50


[turret_光圈2]
x: 0
y: 0
canShoot: false
invisible: if self.isControlledByAI()or not self.hasFlag(id=1)
size: 1

image: ROOT:/太空浪人/建筑特效/光圈2.png


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_爆炸]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5

scaleTo: 1.5
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 7
scaleTo: 7

drawUnderUnits: true
atmospheric: false


[arm_1]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(greaterThan=1800)


[arm_2]
x: 0
y: 0
image_end: 底座.png
image_end_teamColors: true
drawUnderAllUnits: true

drawOverBody: false
lockMovement: true
hidden: if not self.isOverLiquid


[arm_3]
x: 0
y: 0
image_end: 覆盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(lessThan=1800)


[ai]
upgradedFrom: 太空浪人多相聚变堆t1传送
ai_upgradePriority: 0.07


