


[core]
name: 幽影猎狼炮塔
strictLevel: 1
price: 0
radius: 10
maxHp: 1
copyFrom:ROOT:/通用特效/爆炸素材库.md
class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags:反高空
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
[decal_炮塔影子]
image: SHADOW:炮塔.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:6
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
[decal_炮塔损坏]
image: 炮塔损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if parent.hp < parent.maxHp * 0.36
alpha:0.8
basePositionFromTurret: 1
[decal_炮塔led]
image: 炮塔led.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:if parent.maxHp * 0.36 < parent.hp
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
alpha:0.7
basePositionFromTurret: 1




[hiddenAction_坏了]
autoTrigger:if parent.hp < parent.maxHp * 0.36 and not self.tags(includes= '坏了')
temporarilyAddTags:坏了
[hiddenAction_好了]
autoTrigger:if parent.maxHp * 0.36 < parent.hp and self.tags(includes= '坏了')
temporarilyRemoveTags:坏了


[hiddenAction_创造]
autoTrigger: if attachment(slot= '1') == nullUnit
attachments_onlyOnSlots: 1
attachments_addNewUnits:幽影猎狼炮塔1

[hiddenAction_↯a]
autoTrigger: if parent.tags(includes= '↯') and not self.tags(includes= '电')
temporarilyAddTags: 电


[hiddenAction_↯b]
autoTrigger: if not parent.tags(includes= '↯') and self.tags(includes= '电')
temporarilyRemoveTags: 电


[hiddenAction_我日]
autoTrigger: if parent.hasParent and not self.tags(includes= '我日')
temporarilyAddTags: 我日


[hiddenAction_我日2]
autoTrigger: if not parent.hasParent and self.tags(includes= '我日')
temporarilyRemoveTags: 我日


[attachment_1]
x: 0
y: -24
isUnselectable:true
onCreateSpawnUnitOf: 幽影猎狼炮塔1
lockRotation: false
resetRotationWhenNotAttacking:true
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false
setDrawLayerOnTop:true
#idleDir:90
idleDir:0
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
teamColorsOnTurret: true
showEnergyBar: false
showShotDelayBar:false
isVisible:if not parent.hasParent
drawLayer: ground
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange:1200
isFixedFiring: true
turretSize: 24
turretTurnSpeed: 2
shootDelay: 0.9
aimOffsetSpread: 0
isMelee: true
[turret_1]
x: 0
y: 0
canShoot: false
image:炮塔.png
canAttackCondition: if not self.tags(includes= '电') and not parent.hasParent
#limitingMinRange: 200
canAttackFlyingUnits: true
canAttackLandUnits: true
canOnlyAttackUnitsWithTags:被锁定
[turret_2]
x: -25
y: 16
#主炮
projectile: beam0
shoot_sound: ROOT:/余辉军团/单位特效/等离子音效.ogg
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:小烟雾*5,CUSTOM:小等离子闪光,CUSTOM:小冲击波,CUSTOM:小球
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
shoot_light: #FFEECCCC
canOnlyAttackUnitsWithTags:被锁定
aimOffsetSpread: -0.01
invisible:true
warmup:40
warmupStartEffect: CUSTOM:冲击波11,CUSTOM:汇聚11*8
delay: 180
size: 20
canAttackCondition: if not self.tags(includes= '电') and not parent.hasParent
attachedTo: 1
slave: true
canAttackFlyingUnits: true
canAttackLandUnits: true
[turret_3]
x: 25
y: 16
copyFrom: 2
delay:140
warmup:80

[projectile_beam0]
@copyFromSection: template_能源
areaRadiusFromEdge: true
directDamage: 1850
life: 4
instant: true
moveWithParent: true
beamImage: ROOT:余辉军团/单位特效/1.png
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
delayedStartTimer:0
explodeEffect:CUSTOM:巨大冲击波,CUSTOM:爆炸1*3,CUSTOM:主炮爆炸,CUSTOM:巨大闪光
explodeEffectOnShield:CUSTOM:巨大冲击波,CUSTOM:爆炸1*3,CUSTOM:主炮爆炸,CUSTOM:巨大闪光
shieldDamageMultiplier:0.5


[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:余辉军团/单位特效/2.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
areaDamage: 0
areaRadius: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:余辉军团/单位特效/3.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
areaDamage: 0
areaRadius: 0
explodeEffect:NONE
explodeEffectOnShield:NONE


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:余辉军团/单位特效/4.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
areaDamage: 0
areaRadius: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:余辉军团/单位特效/5.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
areaDamage: 0
areaRadius: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:余辉军团/单位特效/6.png
spawnProjectilesOnEndOfLife: beam6(recursionLimit= 17)
directDamage: 0
areaDamage: 0
areaRadius: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam6]
@copyFromSection: projectile_beam0
beamImage: ROOT:余辉军团/单位特效/7.png
spawnProjectilesOnEndOfLife: beam7(recursionLimit= 17)
directDamage: 0
areaDamage: 0
areaRadius: 0
explodeEffect:NONE
explodeEffectOnShield:NONE


[projectile_beam7]
@copyFromSection: projectile_beam0
beamImage: ROOT:余辉军团/单位特效/8.png
directDamage: 0
areaDamage: 0
areaRadius: 0
explodeEffect:NONE
explodeEffectOnShield:NONE
spawnProjectilesOnEndOfLife: NONE
#————————————————————————幽影猎狼

#——————————————————主炮蓄力
[effect_汇聚11]
priority: low
image: ROOT:/通用特效/旋转光效.png
dirOffsetRandom: 360
dirSpeed: 1
dirSpeedRandom: 0.5
life: 45
scaleFrom: 0.8
scaleTo: 0
alpha: 0.9
drawUnderUnits: false
attachedToUnit: true
atmospheric: false
delayedStartTimerRandom:20
[effect_冲击波11]
stripIndex: shockwave
life: 33
scaleFrom: 1.9
scaleTo: 0.1
alpha: 0.8
color: #FF00B3FF
#————————————————激光炮开火
[effect_小球]
priority: high
image: ROOT:/余辉军团/单位特效/60.png
life: 70
fadeOut: true
attachedToUnit: true
scaleFrom: 0.9
scaleTo: 0.4
alpha: 1.3
drawUnderUnits: false
atmospheric: false
[effect_小烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.6
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true
[effect_小冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.1
scaleTo: 2
alpha: 0.7
color: #FF00B3FF
#——————————————————主炮爆炸
[effect_主炮爆炸]
life:70
frame_width:256
frame_height:256
priority: critical
image: ROOT:/余辉军团/单位特效/ab.png
dirOffsetRandom:360
fadeInTime:0
fadeOut: false
attachedToUnit:false
scaleFrom:0.5
scaleTo:0.8
total_frames:16
animateFrameStart:0
animateFrameEnd:15
animateFramePingPong: false
animateFrameSpeed:0.4
alpha:2
createWhenOffscreen: true
alsoPlaySound: ROOT:/余辉军团/单位特效/炸裂.wav
[effect_爆炸1]
life: 120
priority: veryhigh
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.5
image: ROOT:/余辉军团/单位特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
delayedStartTimerRandom:10
alpha: 1.2
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
color: #FF00B3FF
[effect_巨大闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 1
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


