
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}
[core]
name: 幽影猎狼
displayText: Призрачный Волк
displayDescription: -【Уровень t4】【Дальнее целеуказание】【Беспилотный юнит】【Механический юнит】【Наземный юнит】\n-тактическое назначение: скоростная ПВО-машина, размер юнита:8, \n-вооружение:▲кассетная самонаводящаяся ракетаX4 взрывной урон по земле и воздуху усиленный урон по воздушным и сопровождающим юнитам \n-▲импульсная лазерная пушкаX2 энергетический урон по земле, воздуху и высотным только по захваченным целям\n-Империя Новаодинлиниясухопутный легионв самыйобычновидеть сопровождениезащитавоздушныйблок, по сравнениюк старый  типзащитавоздушныйсистема, \n-приходит самкомпания Зетанояустановкарасчёт механическийдикийволкне толькоскоростьстепеньболее быстрый, функцияможет более много, итот жевидИмея антиконтрольвоенный корабль может сила, \n-его восстановитьобъединение типтурельоснащёндвижениеконтрольнаведение типимпульсная лазерная пушка и ракетаЗапустить шт (рам)двойнойтяжёлый вооружение, \n-может подходящийдолжен многовиддистанция, многовидвысокий степень против сопротивлениемиссия, \n-одновременно, внутрипрятатьв машинатело 3dпечатьсистематакже может производствомноговидтип тип скрытыйнет человекзащитазащитаблок, \n-быстрыйрасстилатьоткрытьполе бояи тянутьподнятьсязащитазащиталиния, Этот высокий машинадвижение, многофункцияможет , \n-тяжёлый огневая мощьплатформаможет имеет эффектзакончитьстать включаеттревожить, нужно защитавоздушный, дикийбойзащитавоздушный и поддерживатьдержатьбойлиния многовидмиссия, \n-это имперская армияотрядне может или недостаток одинчлен
price: 4500
maxHp: 4000
maxShield: 5000
shieldRenderRadius: 0
transportSlotsNeeded: 8
shieldRegen: 0.1
techLevel: 1
buildSpeed: 14s
radius: 65
displayRadius: 65
tags: 地面,无人单位,反高空
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
effectOnDeath:CUSTOM:小型余晖死亡冲击波,CUSTOM:小型余晖死亡爆炸,CUSTOM:小型余晖死亡钢珠,CUSTOM:小型余晖死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
isBio: false
softCollisionOnAll: 6
armour: 14
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
autoRepair: true
canRepairUnits: true
nanoRepairSpeed: 0.4
nanoRange: 150
energyMax: 4
energyRegen: 0.005
energyNeedsToRechargeToFull: true


[canBuild_1]
name: 亚空间撕裂者
pos: 0.01
forceNano: true

[canBuild_2]
name: 重力陷阱
pos: 0.02
forceNano: true

[decal_主体影子]
image: SHADOW:影子.png
total_frames: 1
layer: shadow
teamColors: false
isVisible:true
yOffsetRelative:5
xOffsetRelative:4
onlyWhileAlive:true
alpha:0.5

#————————————履带动画
[decal_履带]
image: 履带.png
total_frames: 4
frame: (self.customTimer * 32) % 4
# 8为图片帧数，17改速度，1/17s下一帧
layer: beforeBody
isVisible:if self.isMoving
yOffsetRelative:-3
xOffsetRelative:0
onlyWhileAlive:true
[decal_履带1]
image: 履带1.png
total_frames: 1
layer: beforeBody
isVisible:if not self.isMoving
onlyWhileAlive:true
yOffsetRelative:-3
xOffsetRelative:0
[decal_蛋蛋]
image: 蛋蛋.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 1
[decal_蛋蛋led]
image: 蛋蛋led.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 1
[decal_主体]
image: 主体1.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
[decal_主体损坏]
image: 主体损坏.png
total_frames: 1
layer: afterBody
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[decal_主体led]
image: 主体led.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
alpha:0.85
[decal_雷达影子]
image: SHADOW:雷.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:1
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromLegEnd: arm_1
alpha:0.65
[decal_打印机影子]
image: SHADOW:打印机.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:3
xOffsetRelative:1
onlyWhileAlive:true
basePositionFromTurret: 2
alpha:0.65
[decal_雷达]
image: 雷.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromLegEnd: arm_1




[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: beforeUI
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1.05


[action_长距离]
text: Дальнее целеуказание
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.15
iconImage: ROOT:/通用特效/长距离.png
description: этотюнитимеет может силастрельбакрайнедальнийна  захват прицеломюнит.\n-разрешаетПризрачный Волкв атака  , воздушныйв , высотный юнит в   захват прицелом вражескийюнит, когда , \n-использоватьиспользует 1200дальность импульсная лазерная пушкаатакавраги
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[hiddenAction_创造]
autoTrigger: if attachment(slot= '1') == nullUnit
attachments_onlyOnSlots: 1
attachments_addNewUnits:幽影猎狼炮塔
[attachment_1]
x: 0
y: -25
isUnselectable:true
onCreateSpawnUnitOf: 幽影猎狼炮塔
lockRotation: false
resetRotationWhenNotAttacking:true
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false
setDrawLayerOnTop:true
idleDir:0
#idleDir:90
[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: NONE

teamColorsOnTurret: true
#turretImageScale:0.9
showQueueBar: false
showTransportBar: false

showEnergyBar: false
showShotDelayBar:false
repairEffect: CUSTOM:尾巴, CUSTOM:光粒*2
repairEffectAtTarget:CUSTOM:闪光r, CUSTOM:火花*2
repairEffectRate:10
movementEffect: CUSTOM:烟1,CUSTOM:烟2
movementEffectRate: 13
drawLayer: ground
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 30
turretMultiTargeting: true
maxAttackRange: 500

[turret_1]
x: 0
y: 32
projectile: 233
canShoot: true
canAttackFlyingUnits: false
image:NO.png
delay:99999
limitingAngle: 45
shoot_flame: NONE
shoot_sound: NONE
shoot_sound_vol: 0
[turret_2]
x: -30
y: 21
idleDir: -45
warmup: 0
size: 8
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true
image:打印机.png

[turret_3]
x: 0
y: -25
canAttack: false
invisible: if self.numberOfAttachedUnits(greaterThan= 0)
image:炮.png
# 让建造界面显示时有炮塔

[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true



#————————————————维修效果

[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/光束3.png
life: 100
fadeOut: true
attachedToUnit: false
#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
#ySpeedRelativeRandom: 0.5
drawUnderUnits: false
ySpeedRelative: 2
yOffsetRelative	: 10
[effect_闪光r]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2
scaleTo: 2
drawUnderUnits:false
atmospheric: false
[effect_火花]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.35
physics: true
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.85
drawUnderUnits:false
xOffsetRelativeRandom:25
yOffsetRelativeRandom:25
[effect_光粒]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.2
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 1
ySpeedRelative: 3
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.85
drawUnderUnits:false
xOffsetRelativeRandom:10
#————————————履带印
[effect_烟1]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.37
scaleTo: 0.37
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative: 34
yOffsetRelative: -48


[effect_烟2]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.37
scaleTo: 0.37
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative: -34
yOffsetRelative: -48
[arm_1]
x: 28
y: 21
image_end:NO.png
drawOverBody: true
spinRate: 2
[movement]
movementType: LAND
moveSpeed: 1.75
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.3
maxTurnSpeed: 1.4
turnAcceleration: 0.6
moveSlidingMode : false
moveIgnoringBody: false


