


[core]
name: 幽影猎狼炮塔1
displayText: Турель Призрачного Волка1
strictLevel: 1
price: 0
radius: 10
maxHp: 1
copyFrom:ROOT:/通用特效/爆炸素材库.md
class: CustomUnitMetadata
techLevel: 1
showInEditor: false
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
[decal_炮塔影子]
image: SHADOW:导弹.png
total_frames: 1
layer: afterBody
teamColors: false
isVisible:true
yOffsetRelative:4
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
[decal_导弹]
image: 导弹.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible:true
alpha:1
basePositionFromTurret: 1
[decal_导弹损坏]
image: 导弹损坏.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible:if parent.tags(includes= '坏了')
alpha:1
basePositionFromTurret: 1
[decal_遮盖]
image: 遮盖.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret: 1
[decal_遮盖损坏]
image: 遮盖损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible:if parent.tags(includes= '坏了')
alpha:1
basePositionFromTurret: 1
[decal_导弹led]
image: 导弹led.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible:if not parent.tags(includes= '坏了')
alpha:1
basePositionFromTurret: 1

[decal_右射线]
image: 射线.png
total_frames: 1
layer: onTop
isVisible:if not parent.tags(includes= '坏了')
yOffsetRelative:40
xOffsetRelative:11
onlyWhileAlive:true
alpha:0.8
basePositionFromTurret: 1
[decal_左射线]
image: 射线.png
total_frames: 1
layer: onTop
isVisible:if not parent.tags(includes= '坏了')
yOffsetRelative:40
xOffsetRelative:-12
onlyWhileAlive:true
alpha:0.8
basePositionFromTurret: 1
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
teamColorsOnTurret: true
showEnergyBar: false
showShotDelayBar:false
isVisible:if not parent.tags(includes= '我日')
drawLayer: ground
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange:550
turretSize: 24
turretTurnSpeed: 3
shootDelay: 0.9

[turret_1]
x: 0
y: 0
canShoot: false
image:NO.png
canAttackCondition:if not parent.tags(includes= '电') and not parent.tags(includes= '我日')
limitingMinRange: 160
idleSweepAngle: 20
idleSweepDelay: 230
idleSweepSpeed: 0.2
[turret_2]
x: -21.5
y: -4
canShoot: true
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 0.6
shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾*3
canAttackCondition: if not parent.tags(includes= '电') and not parent.tags(includes= '我日')
image:导1.png
recoilOffset: -8
size:3
recoilOutTime: 4
recoilReturnTime: 140
delay:230
attachedTo: 1
slave:true
limitingMinRange: 160

[turret_3]
x: -13.5
y: -9
copyFrom: 2
delay:210
warmup:20
linkDelayWithTurret:2

[turret_4]
x: 13.5
y: -9
copyFrom: 2
delay:190
warmup:40
linkDelayWithTurret:3

[turret_5]
x: 21.5
y: -4
copyFrom: 2
delay:170
warmup:60
linkDelayWithTurret:4
[projectile_1]
@copyFromSection: template_爆炸
life: 27
speed: 3
targetSpeed: 3
largeHitEffect: true
drawSize: 0.9
image: 导.png
trailEffect: true
directDamage: 0
autoTargetingOnDeadTarget: true
autoTargetingOnDeadTargetRange:100
spawnProjectilesOnEndOfLife: 锁定*3
lightSize: 0.6
lightColor:  #FF00B3FF
explodeEffect: CUSTOM:导弹碎片
explodeOnEndOfLife: true
[projectile_锁定]
@copyFromSection: template_爆炸
life: 420
turnSpeed: 30
spawnProjectilesOnEndOfLife: NONE
speed: 3
targetSpeed: 7
largeHitEffect: true
drawSize: 0.7
lightSize: 0.6
lightColor:  #FF00B3FF
trailEffect: true
directDamage: 375
image: ROOT:/余辉军团/单位特效/中导弹.png
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield:CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波
wobbleAmplitude: 4
wobbleFrequency: 240
speedSpread:1.8
mutator1_ifUnitWithTags: 飞机
mutator1_directDamageMultiplier: 2
mutator997_ifUnitWithTags: 伴生单位
mutator997_directDamageMultiplier: 2
autoTargetingOnDeadTarget: true
autoTargetingOnDeadTargetRange:100
#————————导弹发射
[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.6
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true

[effect_导弹碎片]
#priority: low
image: 壳.png
spawnChance: 1
life: 90
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
ySpeedRelative: -1
hSpeed: 1
dirSpeedRandom: 5
#————————导弹爆炸
[effect_爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 1.4
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FF00B3FF
fadeInTime: 2
scaleFrom: 4
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_冲击波]
stripIndex: shockwave
life: 45
scaleFrom: 0.5
scaleTo: 3
alpha: 0.8
#color: #FF00B3FF
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 1
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


