[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}
[core]
name: 蜂甲先锋
displayDescription: 【阶级t4】【远程扫雷器】【机械单位】【地面单位】【无人单位】【可翻越悬崖】\n-战术定位:辅助型机器人 无法被运输 武器配置：\n-▲破障锯刃 X1 只能对地 中性伤害 \n-▲EMP线圈 X1 只能对地 中性伤害 对护盾伤害加成 造成休克效果 \n-▲震撼飞弹 X2 只能攻击和伤害地面建筑物 \n-▲消防装置 X1 自动清除附近的危险物体 \n-蜂甲先锋是帝国空降部队必不可少的辅助型机甲，\n-这些轻便且高效的机器工兵总是负责为后续的部队开拓道路。\n-与诺瓦帝国其他机械怪兽所不同的是，\n-蜂甲先锋既没有配备毁天灭地的武器，也没有配备铜墙铁壁般的护盾，\n-他最大的价值在于其先进且多功能的子系统，\n-无论前方的道路多么复杂且危险，蜂甲先锋总是能为你的部队开辟出一条通往胜利的道路。
class: CustomUnitMetadata
price: 3500
maxHp: 6000
maxShield: 5800
shieldRenderRadius: 1
shieldRegen: 0.07
armour: 40
techLevel: 1
radius: 50
displayRadius: 50
softCollisionOnAll: 30
fogOfWarSightRange: 33
isBio: false
transportSlotsNeeded: 9999
buildSpeed: 13s
copyFrom: ROOT:/通用特效/单位防护.ini
fireTurretXAtSelfOnDeath: 3
tags: 地面,无人单位

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)



[action_cf]
displayType: action
price: 0
buildSpeed: 0s
isVisible: if not self.tags(includes= '变形')
text: 远程模式
isLocked: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or  self.queueSize > 0.5 or self.resource.xk > 0
alsoQueueAction: bx1
description: 展开武器架和其他武装并收起破障剧刃，\n-对敌方进行远程打击。\n-远程模式下，蜂甲先锋将使用仅能攻击建筑的震撼导弹攻击敌方建筑物，\n-并仅对建筑造成爆炸无衰减伤害，对其他地面敌人使用emp线圈进行攻击，\n-造成中性伤害，对护盾伤害加成并附加休克效果。\n-同时在远程模式下蜂甲先锋获得远程扫雷能力，并能主动清除危险物（如烟雾弹，火坑等。）
iconImage: ROOT:/通用特效/展开主炮.png
temporarilyAddTags:变形
[hiddenAction_bx1]
isVisible: false
buildSpeed: 0.5s
whenBuilding_cannotMove: true
alsoQueueAction: bx2
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
[hiddenAction_bx2]
isVisible: false
buildSpeed: 1.5s
whenBuilding_cannotMove: true

highPriorityQueue: true
whenBuilding_playAnimation: 部署
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
temporarilyRemoveTags:变形
temporarilyAddTags:扫雷,主动扫雷,消防
convertTo: 蜂甲先锋1
[decal_主体影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:3
xOffsetRelative:-5
onlyWhileAlive:true
alpha:0.6
basePositionFromLegEnd: arm_5
[decal_影子]
image: SHADOW:左獠牙.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_4
[decal_影子1]
image: SHADOW:右獠牙.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_2

[decal_牙损坏]
layer: onTop
image: 左蛀牙.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_4
isVisible: if self.hp < self.maxHp * 0.36
[decal_牙损坏1]
layer: onTop
image: 右蛀牙.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_2
isVisible: if self.hp < self.maxHp * 0.36
[decal_遮盖]
image:主体遮盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_5

[decal_主体损坏a]
layer: onTop
image: 主体损坏.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_5
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0.5
xOffsetRelative:-0.5

[decal_灯光]
layer: onTop
image: 灯光.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
basePositionFromLegEnd: arm_5
yOffsetRelative:0
xOffsetRelative:0
[decal_武器遮盖]
image: 导弹.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_10
[decal_武器遮盖1]
image: 电枪.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_11


[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:7
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 0.75
[hiddenAction_DPS]
alsoQueueAction: DPS1

[hiddenAction_DPS1]
buildSpeed: 0.5s
fireTurretXAtGround: 伤害
whenBuilding_cannotMove: true
fireTurretXAtGround_withOffset: 0, 85
[graphics]
total_frames: 1
image: 空.png
image_wreak:死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 7
shadowOffsetY: 7
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 35

turretTurnSpeed: 1
maxAttackRange: 20
isFixedFiring: true
isMelee: true
[turret_1]
invisible: true
x: 0
y: 0
size: 14
idleDir: 0

turnSpeed: 9.0
turnSpeedAcceleration: 0.08
canShoot: false
[turret_2]
x: 0
y: 0
invisible: true
delay: 1.1s
projectile: 2
turnSpeed: 100
turnSpeedAcceleration: 0.07
onShoot_playAnimation: attack
canShoot: true
canAttackCondition: if self.resource.xk < 1
size: 1
attachedTo: 1
onShoot_triggerActions: DPS
slave: true
[turret_3]
x: 0
y: 0
invisible: true
shoot_sound: NONE
shoot_flame: NONE

projectile: 3
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
[turret_伤害]
invisible: true
x: 0
y: 0
size: 0
turnSpeed: 40
turnSpeedAcceleration: 40
canShoot: false
projectile: 1
attachedTo: 1
slave: true
shoot_sound: ROOT:/通用特效/光剑.ogg
shoot_sound_vol: 0.3
[projectile_1]
life: 5000
areaDamage: 1600
areaRadius: 70
instant: true
speed: 10
targetSpeed: 10
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
explodeEffectOnShield:CUSTOM:火花1*18,CUSTOM:火花*8,CUSTOM:闪光
explodeEffect:CUSTOM:火花1*18,CUSTOM:火花*8,CUSTOM:闪光
[projectile_2]
life: 0
speed: 0
directDamage: 0
drawSize: 0
[projectile_3]
@copyFromSection: template_爆炸
areaDamage: 12500
areaRadius: 125
life: 666
speed: 8888
targetSpeed: 8888
instant: true
flameWeapon: true
deflectionPower: -1
areaRadiusFromEdge: true
explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:光球1nk,CUSTOM:光球nk,CUSTOM:电球nk
explodeEffectOnShield:CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:光球1nk,CUSTOM:光球nk,CUSTOM:电球nk
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[arm_1]
x: 5
y:20
image_end: 杆子.png
image_end_teamColors: true
drawDirOffset: 70

drawOverBody: true
image_end_shadow: SHADOW:杆子.png
[arm_2]
x: 25
y: 30
image_end: 右獠牙.png
image_end_teamColors: true
drawDirOffset: 7

drawOverBody: true
image_end_shadow: SHADOW:右獠牙.png
[arm_3]
x: -5
y:20
image_end: 杆子.png
image_end_teamColors: true
drawDirOffset: -70

drawOverBody: true
image_end_shadow: SHADOW:杆子.png
[arm_4]
x: -25
y: 30
image_end: 左獠牙.png
image_end_teamColors: true
drawDirOffset: -7

drawOverBody: true
image_end_shadow: SHADOW:左獠牙.png
[arm_5]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawDirOffset: 0

drawOverBody: true
image_end_shadow: SHADOW:主体.png
[arm_6]
x: 0
y: 41
image_end: 球.png
image_end_teamColors: true
drawDirOffset: 0

drawOverBody: true
image_end_shadow: SHADOW:主体.png

[arm_7]
x: 0
y: 2
image_end: 壳.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
[arm_8]
x: 0
y: 7
image_end: 壳.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
[arm_9]
x: 0
y: 12
image_end: 壳.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
[arm_10]
x: -19
y: 0
image_end: 导弹.png
image_end_teamColors: true
drawDirOffset: -170
drawOverBody: true
[arm_11]
x: 19
y: 8
image_end: 电枪.png
image_end_teamColors: true
drawDirOffset: 170
drawOverBody: true
[arm_12]
x: 0
y: 0
image_end: 底盘.png
image_end_teamColors: true
drawOverBody: false
drawDirOffset: 0
[leg_1]
x: -30
y: 47
attach_x: -3
attach_y: 2
moveSpeed: 2
rotateSpeed: 3
heightSpeed: 0.45
moveWarmUp: 4
resetAngle: 8
holdDisMin: 5
holdDisMax: 15
image_leg: 腿.png
image_foot: NO.png
endDirOffset: -40
hardLimit: 15
favourOppositeSideNeighbours: true


[leg_2]
x: 30
y: 47
attach_x: 3
attach_y: 2
copyFrom: 1


[leg_3]
x: -30
y: -28
attach_x:-3
attach_y: 0
copyFrom: 1


[leg_4]
x: 30
y: -28
attach_x: 3
attach_y: 0
copyFrom: 1
[leg_5]
x: -40
y: 10
attach_x: -5
attach_y: 5
copyFrom: 1

endDirOffset: -90


[leg_6]
x: 40
y: 10
attach_x: 5
attach_y: 5
copyFrom: 1

endDirOffset: 90
[animation_attack]
#onActions: attac

arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}

arm1_0.45s: {x:8, y:-5, dir:0}
arm2_0.45s: {x:8, y:-5, dir:78}
arm3_0.45s: {x:-8, y:-5, dir:0}
arm4_0.45s: {x:-8, y:-5, dir:-78}
arm5_0.45s: {x:0, y:-5, dir:0}
arm6_0.45s: {x:0, y:-5, dir:0}
arm7_0.45s: {x:0, y:-5, dir:0}
arm8_0.45s: {x:0, y:-5, dir:0}
arm9_0.45s: {x:0, y:-5, dir:0}
arm10_0.45s: {x:0, y:-5, dir:0}
arm11_0.45s: {x:0, y:-5, dir:0}

arm1_0.6s: {x:5, y:52, dir:-35}
arm2_0.6s: {x:0, y:60, dir:-37}
arm3_0.6s: {x:-5, y:52, dir:35}
arm4_0.6s: {x:0, y:60, dir:37}
arm5_0.6s: {x:0, y:3, dir:0}
arm6_0.6s: {x:0, y:3, dir:0}
arm7_0.6s: {x:0, y:3, dir:0}
arm8_0.6s: {x:0, y:3, dir:0}
arm9_0.6s: {x:0, y:3, dir:0}
arm10_0.6s: {x:0, y:3, dir:0}
arm11_0.6s: {x:0, y:3, dir:0}

arm1_0.8s: {x:0, y:0, dir:0}
arm2_0.8s: {x:0, y:0, dir:0}
arm3_0.8s: {x:0, y:0, dir:0}
arm4_0.8s: {x:0, y:0, dir:0}
arm5_0.8s: {x:0, y:0, dir:0}
arm6_0.8s: {x:0, y:0, dir:0}
arm7_0.8s: {x:0, y:0, dir:0}
arm8_0.8s: {x:0, y:0, dir:0}
arm9_0.8s: {x:0, y:0, dir:0}
arm10_0.8s: {x:0, y:0, dir:0}
arm11_0.8s: {x:0, y:0, dir:0}

[animation_部署]
#onActions: attack

arm2_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}

arm2_1.5s: {x:-12, y:-30, dir:23}
arm4_1.5s: {x:12, y:-30, dir:-23}
arm7_1.5s: {x:0, y:20, dir:0}
arm8_1.5s: {x:0, y:15, dir:0}
arm9_1.5s: {x:0, y:10, dir:0}
arm10_1.5s: {x:-3, y:3, dir:160}
arm11_1.5s: {x:3, y:-4, dir:-160}
arm12_1.5s: {x:0, y:54, dir:0}

#————————锯齿
[effect_火花]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.35
physics: true
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.85
xOffsetRelativeRandom:40
yOffsetRelativeRandom:10
priority: low
delayedStartTimerRandom:10
[effect_火花1]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/大火花.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.85
xOffsetRelativeRandom:15
yOffsetRelativeRandom:5
physics: true
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
delayedStartTimerRandom:20

[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 6

drawUnderUnits: true
atmospheric: false

#————————紫砂
#————————————炮弹爆炸
[effect_电球nk]
priority: critical
attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
image: ROOT:/余辉军团/单位特效/电球1.png
total_frames: 5
animateFrameStart: 0
animateFrameEnd: 4
animateFramePingPong: true
animateFrameSpeed: 0.2
fadeOut: true
life: 300
drawUnderUnits: false
alwayStartDirAtZero: true
[effect_聚变nk]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 18
fadeOut: true
attachedToUnit: false
scaleFrom: 2.6
scaleTo: 2.6
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 8
scaleTo: 8
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
[effect_冲击波nk]
life: 45
priority: critical
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 2.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true

[effect_冲击波nk1]
priority: low
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 2.5
alpha: 0.8
showInFog: true
drawUnderUnits: false
atmospheric: false

[effect_光球nk]
life: 90
priority: veryhigh
attachedToUnit: false
scaleFrom:0.9
scaleTo: 0.9
image: ROOT:/余辉军团/单位特效/收缩.png
ySpeedAbsolute:0
fadeOut: true
alpha: 0.85
showInFog: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true
[effect_光球1nk]
life: 90
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.4
image: ROOT:/创世纪军事集团/单位特效/光球z.png

fadeOut: true
showInFog: true
alpha: 0.7
fadeInTime: 1
createWhenOffscreen: true


[effect_冲击波nk3]
priority: high
image: ROOT:/余辉军团/单位特效/超级冲击波1.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 2
alpha: 0.8
drawUnderUnits: true
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:35
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.7
scaleTo:2.9
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180
[movement]
movementType: OVER_CLIFF
moveSpeed: 1
moveAccelerationSpeed: 0.4
moveDecelerationSpeed: 0.4
maxTurnSpeed: 1
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: true


