[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}
[core]
name: 蜂甲先锋1
displayText:  蜂甲先锋
displayDescription: 【阶级t4】【远程扫雷器】【机械单位】【地面单位】【无人单位】【可翻越悬崖】\n-战术定位:辅助型机器人 单位体积：3 武器配置：\n-▲破障锯刃 X1 只能对地 中性伤害 \n-▲EMP线圈 X1 只能对地 中性伤害 对护盾伤害加成 造成休克效果 \n-▲震撼飞弹 X2 只能攻击和伤害地面建筑物 \n-▲消防装置 X1 自动清除附近的危险物体 \n-蜂甲先锋是帝国空降部队必不可少的辅助型机甲，\n-这些轻便且高效的机器工兵总是负责为后续的部队开拓道路。\n-与诺瓦帝国其他机械怪兽所不同的是，\n-蜂甲先锋既没有配备毁天灭地的武器，也没有配备铜墙铁壁般的护盾，\n-他最大的价值在于其先进且多功能的子系统，\n-无论前方的道路多么复杂且危险，蜂甲先锋总是能为你的部队开辟出一条通往胜利的道路。
class: CustomUnitMetadata
showInEditor: false
price: 3500
maxHp: 6000
maxShield: 5800
shieldRenderRadius: 1
shieldRegen: 0.07
armour: 5
techLevel: 1
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
radius: 50
displayRadius: 50
softCollisionOnAll: 30
fogOfWarSightRange: 33
isBio: false
transportSlotsNeeded: 3
buildSpeed: 13s
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,无人单位,扫雷,主动扫雷,消防
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_cf]
displayType: action
price: 0
buildSpeed: 0s
isVisible: if not self.tags(includes= '变形')
text: 冲锋模式
isLocked: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or  self.queueSize > 0.5 or self.resource.xk > 0
alsoQueueAction: bx1
description: 向后折叠武器架，关闭消防装置并展开机体前端破障剧刃，\n-同时展开护板遮盖机体关键部位，准备与敌人展开进战。\n-冲锋模式下蜂甲先锋将只能进行进战，并造成中性伤害，\n-提升移动速度，获得护甲加成，并在死亡时造成大量能源伤害。\n-注意，冲锋模式下扫雷装置和地雷屏蔽能力将禁用，并且本体将不能被运输。

iconImage: ROOT:/通用特效/加速.png
temporarilyAddTags:变形
[hiddenAction_bx1]
isVisible: false
buildSpeed: 0.5s
whenBuilding_cannotMove: true
alsoQueueAction: bx2
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
[hiddenAction_bx2]
isVisible: false
buildSpeed: 1.5s
whenBuilding_cannotMove: true

highPriorityQueue: true
whenBuilding_playAnimation: 部署
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
temporarilyRemoveTags:扫雷,主动扫雷,变形,消防
convertTo: 蜂甲先锋
[decal_主体影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:3
xOffsetRelative:-5
onlyWhileAlive:true
alpha:0.6
basePositionFromLegEnd: arm_5
[decal_影子]
image: SHADOW:左獠牙.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_4
[decal_影子1]
image: SHADOW:右獠牙.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_2

[decal_牙损坏]
layer: onTop
image: 左蛀牙.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_4
isVisible: if self.hp < self.maxHp * 0.36
[decal_牙损坏1]
layer: onTop
image: 右蛀牙.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_2
isVisible: if self.hp < self.maxHp * 0.36
[decal_遮盖球]
image:球.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 扫雷
[decal_遮盖]
image:主体遮盖.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_5

[decal_主体损坏a]
layer: onTop
image: 主体损坏.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_5
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0.5
xOffsetRelative:-0.5

[decal_灯光]
layer: onTop
image: 灯光.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
basePositionFromLegEnd: arm_5
yOffsetRelative:0
xOffsetRelative:0
[decal_武器遮盖]
image: 导弹.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '变形')
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_10
[decal_武器遮盖1]
image: 电枪.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '变形')
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromLegEnd: arm_11

[decal_武器遮盖x]
image: 电枪.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '变形')
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 1
[decal_武器遮盖z1]
image: 震撼弹.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '变形')
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 2
[decal_武器遮盖z2]
image: 震撼弹.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '变形')
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 3
[decal_武器遮盖z]
image: 导弹1.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '变形')
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 4
[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:7
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5*  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 0.75

[graphics]
total_frames: 1
image: 空.png
image_wreak:死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 7
shadowOffsetY: 7
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
turretSize: 35
turretMultiTargeting: true
turretTurnSpeed: 2
maxAttackRange: 410

[turret_扫雷]
x: 0
y: 41.5
projectile: 1
turnSpeedAcceleration: 2
shoot_sound: plasma_fire
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFEECCCC
canShoot: true
canAttackCondition: if self.resource.xk < 1 and not self.hasParent and not self.tags(includes= '变形')
delay:120
image:球.png
size:3
canOnlyAttackUnitsWithTags:地雷,危险物品
limitingAngle: 85
invisible:if self.tags(includes= '变形')
limitingRange: 350
[turret_1]
x: 22
y: 4
image:电枪.png
size:35
shoot_sound: ROOT:/通用特效/shock.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:闪光1,CUSTOM:冲击波1
shoot_light: #FF004AFF
projectile: beam0
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '变形')
canAttackUnderwaterUnits: false
delay: 120
idleDir:10
limitingAngle: 80
invisible:if self.tags(includes= '变形')
canOnlyAttackUnitsWithoutTags:危险物品
[turret_2]
x: 3
y: 0
#导弹右
projectile: 2
attachedTo: 4
slave: true
canAttackFlyingUnits: false
canAttackUnderwaterUnits: false
image: 震撼弹.png
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 0.4
shoot_flame: CUSTOM:烟雾*4
shoot_light: #FFEECCCC
canShoot: true
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '变形')
recoilOffset: -12
recoilOutTime: 0
recoilReturnTime: 120
delay:200
canOnlyAttackUnitsWithTags:建筑
canOnlyAttackUnitsWithoutTags:危险物品
size:15
invisible:if self.tags(includes= '变形')
[turret_3]
x: -3
y: 0
copyFrom: 2
delay:170
warmup:30
[turret_4]
x: -22
y: 3
idleDir:-10
limitingAngle: 80
canShoot: false
image: 导弹1.png
limitingMinRange: 150
canAttackCondition: if self.resource.xk < 1 and not self.tags(includes= '变形')
canAttackUnderwaterUnits: false
canOnlyAttackUnitsWithTags:建筑
canOnlyAttackUnitsWithoutTags:危险物品
invisible:if self.tags(includes= '变形')
[projectile_1]
directDamage: 10
life: 200
speed: 12
image: ROOT:/余辉军团/单位特效/冲击.png
targetSpeed: 12
drawSize: 0.25
explodeEffect: CUSTOM:冲击波1, CUSTOM:冲击波,CUSTOM:闪光,CUSTOM:光子*12
explodeEffectOnShield: CUSTOM:冲击波1, CUSTOM:冲击波,CUSTOM:闪光,CUSTOM:光子*12
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴
mutator969_ifUnitWithTags: 地雷
mutator969_addResourcesDirectHit:setFlag=1
mutator970_ifUnitWithTags: 危险物品
mutator970_addResourcesDirectHit:setFlag=1
[projectile_2]
@copyFromSection: template_爆炸
#主炮子弹
areaDamage: 10
areaRadius: 75
life: 350
speed: 3
targetSpeed: 7
image: 震撼弹.png
drawSize: 1
trailEffect: true
lightSize: 0.75
lightColor:  #FF00B3FF
targetGround: true
initialUnguidedSpeedHeight: 1.7
disableLeadTargeting: true
areaRadiusFromEdge: true
buildingDamageMultiplier: 300
explodeEffect: CUSTOM:气旋,CUSTOM:烟雾dn*8,CUSTOM:冲击波z1,CUSTOM:冲击波z, CUSTOM:白闪光,CUSTOM:碎星*13,CUSTOM:实验
explodeEffectOnShield: CUSTOM:气旋,CUSTOM:烟雾dn*8,CUSTOM:冲击波z1,CUSTOM:冲击波z, CUSTOM:白闪光,CUSTOM:碎星*13,CUSTOM:实验
trailEffectRate: 0.8
areaDamageNoFalloff: true
[projectile_beam0]
explodeEffect: CUSTOM:电,CUSTOM:闪光1,CUSTOM:冲击波1
directDamage: 70
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 1
life: 3
instant: true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true
beamImage: ROOT:/通用特效/闪电1q.png
#beamImageOffsetRate: 2
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
shieldDamageMultiplier:20
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_beam1]
explodeEffect:NONE
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电2q.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0
[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电3q.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam3]
explodeEffect:NONE
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电4q.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电5q.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam5]
explodeEffect:NONE
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电6q.png
spawnProjectilesOnEndOfLife: beam6(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam6]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电7q.png
spawnProjectilesOnEndOfLife: beam7(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam7]
explodeEffect:NONE
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电8q.png
spawnProjectilesOnEndOfLife: NONE
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0
#————————扫雷器尾巴
[effect_尾巴]
priority: low
image: ROOT:/余辉军团/单位特效/冲击.png
life: 45
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.28
alpha: 1
drawUnderUnits: false
atmospheric: false
#————————命中
[effect_闪光]
priority:low
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 1
attachedToUnit: true
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false
atmospheric: false
[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/超级冲击波1.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.3
alpha:1
drawUnderUnits: false
atmospheric: false
[effect_冲击波1]
stripIndex: shockwave
life: 35
scaleFrom: 1
scaleTo: 3
alpha: 0.9
color: #FF00B3FF
[effect_光子]
image: ROOT:/余辉军团/单位特效/蓄能.png
spawnChance: 1
priority: verylow
createWhenZoomedOut: false
life: 60
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.6
scaleTo: 0.6
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 2
xSpeedRelativeRandom: 2
atmospheric: true
#————————emp
[effect_闪光1]
priority:low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: true
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 0.1
drawUnderUnits: false
atmospheric: false
[effect_电]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 1

drawUnderUnits: false
scaleFrom: 2
scaleTo: 2
#————————导弹发射
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
#————————震撼弹
[effect_冲击波z]
priority: critical
image: ROOT:/余辉军团/单位特效/超级冲击波1.png
life: 50
fadeOut: true
attachedToUnit: false
scaleFrom: 0
scaleTo: 1
alpha:1
drawUnderUnits: false
atmospheric: false
[effect_冲击波z1]
life: 100
priority: high
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
color: #FF00B3FF
[effect_气旋]
image:ROOT:/余辉军团/单位特效/气旋.png
priority: critical
life: 90
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0
scaleTo: 3
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
dirSpeed: -2
alsoPlaySound:ROOT:/通用特效/音波.wav
dirSpeedRandom: 1.5
[effect_碎星]
spawnChance: 1
createWhenZoomedOut: false
priority: low
life: 60
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom:0.18
scaleTo:0.18
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 5
ySpeedRelativeRandom: 5
[effect_烟雾dn]
color: #BBBBFFEE
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenOffscreen: true
life: 250
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 4
scaleTo: 5
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.5
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:30
yOffsetRelativeRandom:30
createWhenOverLiquid: false
createWhenOverLand: true
[effect_白闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 10
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0
scaleTo:3
alpha: 1
fadeInTime: 4
drawUnderUnits:true
createWhenZoomedOut: false
dirOffsetRandom:180
dirSpeedRandom: 1.5
[arm_1]
x: 5
y:20
image_end: 杆子.png
image_end_teamColors: true
drawDirOffset: 70

drawOverBody: true
image_end_shadow: SHADOW:杆子.png
[arm_2]
x: 13
y: 0
image_end: 右獠牙.png
image_end_teamColors: true
drawDirOffset: 30

drawOverBody: true
image_end_shadow: SHADOW:右獠牙.png
[arm_3]
x: -5
y:20
image_end: 杆子.png
image_end_teamColors: true
drawDirOffset: -70

drawOverBody: true
image_end_shadow: SHADOW:杆子.png
[arm_4]
x: -13
y: 0
image_end: 左獠牙.png
image_end_teamColors: true
drawDirOffset: -30

drawOverBody: true
image_end_shadow: SHADOW:左獠牙.png
[arm_5]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawDirOffset: 0

drawOverBody: true
image_end_shadow: SHADOW:主体.png
[arm_6]
x: 0
y: 41
image_end: 球.png
image_end_teamColors: true
drawDirOffset: 0
hidden:if not self.tags(includes= '变形')
drawOverBody: true
image_end_shadow: SHADOW:主体.png

[arm_7]
x: 0
y: 22
image_end: 壳.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
[arm_8]
x: 0
y: 22
image_end: 壳.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
[arm_9]
x: 0
y: 22
image_end: 壳.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: true
[arm_10]
x: -22
y: 3
image_end: 导弹.png
image_end_teamColors: true
hidden:if not self.tags(includes= '变形')
drawOverBody: true
drawDirOffset: -10
[arm_11]
x: 22
y: 4
image_end: 电枪.png
image_end_teamColors: true
hidden:if not self.tags(includes= '变形')
drawOverBody: true
drawDirOffset: 10
[arm_12]
x: 0
y: 54
image_end: 底盘.png
image_end_teamColors: true
drawOverBody: false
drawDirOffset: 0
[leg_1]
x: -30
y: 47
attach_x: -3
attach_y: 2
moveSpeed: 2
rotateSpeed: 3
heightSpeed: 0.45
moveWarmUp: 4
resetAngle: 8
holdDisMin: 5
holdDisMax: 15
image_leg: 腿.png
image_foot: NO.png
endDirOffset: -40
hardLimit: 15
favourOppositeSideNeighbours: true


[leg_2]
x: 30
y: 47
attach_x: 3
attach_y: 2
copyFrom: 1


[leg_3]
x: -30
y: -28
attach_x:-3
attach_y: 0
copyFrom: 1


[leg_4]
x: 30
y: -28
attach_x: 3
attach_y: 0
copyFrom: 1
[leg_5]
x: -40
y: 10
attach_x: -5
attach_y: 5
copyFrom: 1

endDirOffset: -90


[leg_6]
x: 40
y: 10
attach_x: 5
attach_y: 5
copyFrom: 1

endDirOffset: 90
[animation_部署]
#onActions: attack

arm2_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}

arm2_1.5s: {x:12, y:30, dir:-23}
arm4_1.5s: {x:-12, y:30, dir:23}
arm7_1.5s: {x:0, y:-20, dir:0}
arm8_1.5s: {x:0, y:-15, dir:0}
arm9_1.5s: {x:0, y:-10, dir:0}
arm10_1.5s: {x:3, y:-3, dir:-160}
arm11_1.5s: {x:-3, y:4, dir:160}
arm12_1.5s: {x:0, y:-54, dir:0}

[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true

[movement]
movementType: OVER_CLIFF
moveSpeed: 0.75
moveAccelerationSpeed: 0.4
moveDecelerationSpeed: 0.4
maxTurnSpeed: 1
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: true


