


[core]
name: 观察哨t3
displayText: 观察哨t2
displayDescription:【阶级t3】【防御类建筑】【建筑单位】【地面单位】【轻型掩体】\n-战术定位：远程步兵掩体，载员数量：8，\n-只能装载生物单位，并将内部单位射程至430。\n-一种配备了烟雾弹发射器，固定式侦察雷达等设备的高级步兵掩体。\n-相比于普通的碉堡，观察哨真正的优势在于能大幅提升步兵单位的射程，\n-从而大幅度增强步兵单位的战斗力，虽说成本较高并且由于装载了太多设备导致载员量下降，\n-但这种高科技掩体的强大辅助效果，依然使其拥有了较大的使用量。
class: CustomUnitMetadata
price: 4000
maxHp: 8500
footprint:-3,-6,3,4
constructionFootprint: -3,-6,3,4
techLevel: 1
buildSpeed: 20s
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
numBitsOnDeath: 12
unitsSpawnedOnDeath:建筑损毁*1
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆破*4,largeExplosion
fogOfWarSightRange: 35
radius: 50
softCollisionOnAll: 12
energyStartingPercentage: 0
energyMax: 12
energyRegen: 0.003
exit_x: 0
exit_y: -1
tags: 地面,轻型掩体,建筑,防御建筑,观察哨t3
armour: 15
maxTransportingUnits: 8
transportUnitsRequireTag: 步兵,卧倒,支援,机甲
[hiddenAction_创造]
autoTrigger: if attachment(slot= '0') == nullUnit
attachments_onlyOnSlots: 0
attachments_addNewUnits:导弹阵地
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[action_1_烟幕弹]
fireTurretXAtGround: 烟幕弹
text: 发射烟幕弹
displayType: action
buildSpeed: 1s
pos: 0.1
iconImage: ROOT:/创世纪军事集团/单位特效/烟雾弹.png
displayRemainingStockpile: true
highPriorityQueue: true
price: energy=4
canPlayerCancel: false
onlyOneUnitAtATime: true
whenBuilding_playAnimation: 1
description: 向目标区域投掷一枚烟幕弹，烟幕弹能严重干扰敌军的瞄准系统。\n-烟雾弹将降低附近160范围内的敌方地面单位的射程以及射速，\n-对具有长距离索敌能力以及拥有先进目标定位核心科技的单位无效。
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_轻型掩体]
text: 轻型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/轻型掩体.png
description: 一处轻型掩体，能为附近，140范围内的生物单位提供轻型掩护。\n-轻型掩护能为生物单位减免50%的伤害，\n-但是，掩体无法减免速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。
[decal_地板]
image: ROOT:/创世纪军事集团/建筑特效/观察地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-45
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
imageScale: 0.9
alpha:1

[decal_烟雾弹]
image: 烟.png
total_frames: 1
layer: beforeBody
teamColors: true
isVisible:true
yOffsetRelative:10
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9
[decal_盖子]
image: 本体.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.maxHp * 0.36< self.hp
yOffsetRelative:10
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9
[decal_盖子1]
image: 本体损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:10
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9
[decal_shadow]
image: SHADOW:本体.png
layer: shadow
xOffsetAbsolute: 7
yOffsetAbsolute: -9
alpha: 0.5
onlyWhileAlive: true
imageScale: 0.9
isVisible: true

[decal_雷达2]
image: SHADOW:ROOT:/创世纪军事集团/建筑特效/雷达.png
total_frames: 1
layer: onTop

isVisible:true
yOffsetRelative:98
xOffsetRelative:12
onlyWhileAlive:true
dirOffset:45
imageScale: 0.8
alpha:0.65
[decal_雷达]
image: ROOT:/创世纪军事集团/建筑特效/雷达.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.maxHp * 0.36< self.hp
yOffsetRelative:102
xOffsetRelative:10
onlyWhileAlive:true
dirOffset:45
imageScale: 0.8

[decal_雷达1]
image: ROOT:/创世纪军事集团/建筑特效/雷达损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp< self.maxHp * 0.36
yOffsetRelative:102
xOffsetRelative:10
onlyWhileAlive:true
dirOffset:45
imageScale: 0.8
[action_升级]
convertTo: 观察哨t4
displayType: action
text: 升级
price: 2000
buildSpeed: 20s

isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心
ai_isHighPriority: true
description:最大化观察哨等级，加固其结构强度，提升内部载员数量至10，增加防空导弹炮组，并将内部单位射程提升至900。\n-全新升级版的观察哨不仅着重强化了雷达和观测系统用于提升射程，\n-并且添加了额外的四具双联装防空导弹炮塔用于封锁天空。
[graphics]
total_frames: 1
image: 本体.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/观察死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

shadowOffsetX: 3
shadowOffsetY: 3
imageScale: 0.9
image_offsetY: -10


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 50
maxAttackRange: 330
meleeEngangementDistance: 100
isMelee: true



[turret_烟幕弹]
x: 0
y: 58
canShoot: false
invisible: true
size: 1.1
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 1
delay: 0
shoot_flame: CUSTOM:烟雾1*7
shoot_light: #FFEECCCC
[projectile_1]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.9

image: ROOT:/创世纪军事集团/建筑特效/弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 2
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1

[projectile_2]
life: 600
directDamage: 0
speed: 6
targetSpeed: 9
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png
initialUnguidedSpeedHeight: 2.5
gravity: 0.4
drawSize: 0.9
targetGround: true
spawnUnit: 烟幕弹*1
trailEffect: true
deflectionPower: -1
trailEffectRate: 1
#————————————
[effect_烟雾1]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120

fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1

scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
atmospheric: true


[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10

[attachment_0]
x: 0
y: 0
isUnselectable:true
onCreateSpawnUnitOf:导弹阵地
lockRotation: false
resetRotationWhenNotAttacking:true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
setDrawLayerOnTop:true
onConvertKeepExistingUnitInSameSlot:true
[attachment_1]
x:0
y: 40
isVisible: false
height: -1
canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: true

[attachment_2]
x: 0
y: 40
@copyFromSection: attachment_1

[attachment_3]
x: 0
y: 40
@copyFromSection: attachment_1


[attachment_4]
x: 0
y: 40
@copyFromSection: attachment_1


[attachment_5]
x: 0
y: 40
@copyFromSection: attachment_1


[attachment_6]
x: 0
y: 40
@copyFromSection: attachment_1


[attachment_7]
x: 0
y: 40
@copyFromSection: attachment_1


[attachment_8]
x: 0
y: 40
@copyFromSection: attachment_1



[arm_1]
x: -3.5
y: 58
image_end:ROOT:/创世纪军事集团/建筑特效/观察左.png
image_end_teamColors: true
drawOverBody: true
[arm_2]
x: 3.5
y: 58
image_end:ROOT:/创世纪军事集团/建筑特效/观察右.png
image_end_teamColors: true
drawOverBody: true

[animation_1]

arm1_0s: {x:0, y:0}
arm2_0s: {x:0, y:0}
arm1_1s: {x:-15, y:0}
arm2_1s: {x:15, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
delayedStartTimerRandom:30

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


