[core]
name: 旋风导弹
displayText: Ракета «Вихрь»
displayDescription: -别玩沙盒 。
class: CustomUnitMetadata
price: 0
maxHp: 1
techLevel: 1
canNotBeGivenOrdersByPlayer: true
softCollisionOnAll: 20
buildSpeed: 0.0007
radius: 16
canNotBeDamaged: true
canNotBeDirectlyAttacked: true
fogOfWarSightRange: 8
numBitsOnDeath:0
explodeOnDeath: false
showInEditor:false
showOnMinimapToEnemies: false
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 3000
energyRegen: -1
dieOnZeroEnergy: true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_DPS]
addResources=JB=1
[hiddenAction_切换]
autoTrigger:if self.resource.JB>0
convertTo: 旋风导弹1
spawnEffects:CUSTOM:导弹碎片
[hiddenAction_答辩]
autoTrigger:if not self.isMoving()
addWaypoint_type: move
addWaypoint_position_relativeOffsetFromSelf:0,10
[graphics]
total_frames: 1
image: 导弹.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
splastEffect: true
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: false
turretSize: 1
turretTurnSpeed: 25
maxAttackRange: 1700
isMelee: true
meleeEngangementDistance: 99999
#attackMovement: bomber
[turret_1]
x: 0
y: -10
invisible:true
canShoot: true
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹音效.ogg
shoot_sound_vol: 0.3
shoot_flame:NONE
size: 0
canAttackMaxAngle: 181
idleDir: 180
turnSpeed: 0
delay: 3000
energyUsage:0
onShoot_triggerActions:DPS
aimOffsetSpread: 3.5
[turret_2]
x: 0
y: -10
copyFrom: 1
idleDir: 90
[turret_3]
x: 0
y: -10
copyFrom: 1
idleDir: -90
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
life: 30
speed: 3
deflectionPower:-1
lightSize: 1.5
lightColor: #FFFFFF73
drawSize: 0.85
targetSpeed: 6
turnSpeed: 0
trailEffect: true
image: ROOT:/创世纪军事集团/单位特效/小导弹.png
explodeEffect: NONE
spawnProjectilesOnEndOfLife: 锁定
areaRadiusFromEdge: true
[projectile_锁定]
@copyFromSection: template_爆炸
life: 4500
speed: 6
targetSpeed: 11
largeHitEffect: true
drawSize: 0.85
image: ROOT:/创世纪军事集团/单位特效/小导弹.png
areaDamage: 1500
deflectionPower: -1
areaRadiusFromEdge: true
areaRadius: 60
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:闪电,CUSTOM:粒子*10
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:闪电,CUSTOM:粒子*10
turnSpeed: 3
speedSpread:4
trailEffect: true
trailEffectRate: 0.75
targetGround: true
disableLeadTargeting: true
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: xk= 1
shieldDamageMultiplier: 20
targetGroundSpread: 85
armourIgnoreAmount: 99999
[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.65
scaleTo: 0.65
image:ROOT:/通用特效/电磁爆炸.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound:ROOT:/余辉军团/单位特效/瓶1.ogg
[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 40
fadeOut: true
attachedToUnit: false
#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.4
scaleTo: 0.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7
ySpeedRelativeRandom: 3.7
#atmospheric: true


[effect_闪电]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 1
drawUnderUnits: false
scaleFrom: 4
scaleTo: 4


[effect_闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -20
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
#ySpeedRelative: -0.2
yOffsetRelative	: -23
#drawUnderUnits: true

[effect_导弹碎片]
#priority: low
image: 导弹碎片1.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50

[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0
maxTurnSpeed: 1.4
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false

