[core]
name: 旋风导弹2
displayText: Ракета «Вихрь»2
displayDescription: -别玩沙盒了。
showInEditor: false
class: CustomUnitMetadata
price: 0
maxHp: 1
techLevel: 1
canNotBeGivenOrdersByPlayer: true
softCollisionOnAll: 20
buildSpeed: 0.0007
radius: 16
canNotBeDamaged: true
canNotBeDirectlyAttacked: true
fogOfWarSightRange: 8
numBitsOnDeath:0
explodeOnDeath: false
#showInEditor:false
showOnMinimapToEnemies: false
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 3000
energyRegen: -1
dieOnZeroEnergy: true

[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[graphics]
total_frames: 1
image: 导弹2.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
splastEffect: true
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: true
turretSize: 1
turretTurnSpeed: 25
maxAttackRange: 500
isMelee: true
meleeEngangementDistance: 99999

[turret_1]
x: 0
y: -10
invisible:true
canShoot: true
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
shoot_flame:NONE
size: 0
turnSpeed: 111
delay: 20
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 4000
shouldRevealFog: true
areaRadius: 80
nukeWeapon: false
life: 600
alwaysVisibleInFog: false
speed: 9
image: 导弹2.png
targetSpeed: 9
drawSize: 1
trailEffectRate: 1.2
explodeEffect: CUSTOM:巨大爆炸,CUSTOM:巨大冲击波,CUSTOM:巨大闪光,CUSTOM:气浪
areaRadiusFromEdge: true
targetGround: true
lightSize: 1.5
lightColor: #FFFFFF73
disableLeadTargeting: true
trailEffect: CUSTOM:projectileTrail1
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 3.3
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[effect_巨大钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
alpha: 0.8
scaleFrom: 2
scaleTo: 5
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_projectileTrail1]
stripIndex: effects
frameIndex: 0
life: 40
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 1.2
alpha: 0.7
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -22
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -10
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
#ySpeedRelative: -0.2
yOffsetRelative	: -10
[effect_气浪]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 3
scaleTo: 7.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true
[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0
maxTurnSpeed: 1.4
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false

