


[core]
name: 长须鲸工程船
displayText: Инженерное судно «Финвал»
price: 600
maxHp: 1000
displayDescription: 【Уровень t2】【Механический юнит】【Надводный юнит】【Инженерный юнит】\n-Тактическое назначение: водный строитель，вооружение：\n-▲ракетная установкаX1 только по земле взрывной урон\n-Инженерное судно «Финвал»на основедовоенный的驳корабльмодифицироватьа来，\n-ониглавным образом负责在надводный或акваториястроитьразличныесооружение，\n-такжеможет维修Генезис的различныекорабль。
fogOfWarSightRange: 17
techLevel: 1
buildSpeed: 10s
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 45
displayRadius: 45
unitsSpawnedOnDeath: 小型水上单位死亡*1
tags: 地面,海上
isBio: false
softCollisionOnAll: 5
canRepairBuildings: true
canRepairUnits : true
nanoRange: 220
nanoRepairSpeed: 0.4
energyMax: 12
energyRegen: 0.05
energyNeedsToRechargeToFull: true
[action_已落地]
autoTriggerOnEvent:created
isVisible:false
addResources:setFlag=1,setFlag=2,setFlag=3,setFlag=4
#——————————————————经济类建筑
[canBuild_啊1]
name: 苦工机器人
pos: 0.0001
forceNano: true
[action_T1]
pos: 0.001
buildSpeed: 0s
addResources: setFlag=1
text: Показать экономические здания
isVisible: if not self.hasFlag(id=1) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/经济.png
[action_T1_back]
pos: 0.002
buildSpeed: 0s
addResources: unsetFlag=1
isVisible: if self.hasFlag(id=1) and not self.isControlledByAI()
text: Скрыть экономические здания
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/经济.png
[canBuild_1]
name: 创世纪钻井平台t1
pos: 1
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()

[canBuild_2]
name: 创世纪钻井平台t2
pos: 2
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_3]
name: 创世纪钻井平台t3
pos: 3
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_3.5]
name: 创世纪钻井平台t4
pos: 3.5
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_4]
name: 钍激光钻机t1
pos: 4
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_5]
name: 创世纪锻造厂
pos: 5
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_6]
name: 创世纪炼油厂t1
pos: 6
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='精炼技术1')
isLockedMessage: Требуется технология очистки t1

#——————————————————生产类建筑

[action_T2]
pos: 0.003
buildSpeed: 0s
addResources: setFlag=2
text: Показать производственные здания
isVisible: if not self.hasFlag(id=2) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/生产.png
[action_T2_back]
pos: 0.004
buildSpeed: 0s
addResources: unsetFlag=2
isVisible: if self.hasFlag(id=2) and not self.isControlledByAI()
text: Скрыть производственные здания
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/生产.png

[canBuild_9]
name: 创世纪兵营t1
pos: 9
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()

[canBuild_10]
name: 创世纪兵营t2
pos: 10
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня



[canBuild_11]
name: 创世纪兵营t3
pos: 11
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_12]
name: 创世纪兵营t4
pos: 12
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина


[canBuild_13]
name: 创世纪战车工厂t1
pos: 13
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t2')
isLockedMessage: Требуется командный центр 2 уровня

[canBuild_14]
name: 创世纪战车工厂t2
pos: 14
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_15]
name: 创世纪战车工厂t3
pos: 15
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина


[canBuild_16]
name: 创世纪机库t1
pos: 16
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_17]
name: 创世纪机库t2
pos: 17
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_18]
name: 创世纪停机坪
pos: 18
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_19]
name: 创世纪舰队港湾t1
pos: 19
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t2')
isLockedMessage: Требуется командный центр 2 уровня

[canBuild_20]
name: 创世纪舰队港湾t2
pos: 20
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_21]
name: 创世纪舰队港湾t3
pos: 21
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_22]
name: 赫斯提亚锻炉
pos: 22
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина


#——————————————————军事建筑

[action_T3]
pos: 0.005
buildSpeed: 0s
addResources: setFlag=3
text: Показать военные/научные здания
isVisible: if not self.hasFlag(id=3) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/军事.png
[action_T3_back]
pos: 0.006
buildSpeed: 0s
addResources: unsetFlag=3
isVisible: if self.hasFlag(id=3) and not self.isControlledByAI()
text: Скрыть военные/научные здания
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/军事.png


[canBuild_24]
name: 创世纪科技中心
pos: 24
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3') or numberOfUnitsInTeam(withTag='科技中心',incompleteBuildings= true,greaterThan=0)
isLockedMessage: Требуется командный центр 3 уровня, и можно иметь только один.

[canBuild_25]
name: 创世纪工业商店
pos: 25
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3') or numberOfUnitsInTeam(withTag='工业商店',incompleteBuildings= true,greaterThan=0)
isLockedMessage: Требуется командный центр 3 уровня, и можно иметь только один.

[canBuild_26]
name: 多功能前哨站t1
pos: 26
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t2')
isLockedMessage: Требуется командный центр 2 уровня

[canBuild_27]
name: 多功能前哨站t2
pos: 27
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_28]
name: 多功能前哨站t3
pos: 28
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_29]
name: 创世纪导弹基地t1
pos: 29
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='弹道导弹技术1')
isLockedMessage: Требуется технология баллистических ракет 1

[canBuild_30]
name: 创世纪导弹基地t2
pos: 30
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_31]
name: 科普斯军事研究所
pos: 31
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

#——————————————————防御建筑

[action_T4]
pos: 0.007
buildSpeed: 0s
addResources: setFlag=4
text: Показать оборонительные здания
isVisible: if not self.hasFlag(id=4) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/防御.png
[action_T4_back]
pos: 0.008
buildSpeed: 0s
addResources: unsetFlag=4
isVisible: if self.hasFlag(id=4) and not self.isControlledByAI()
text: Скрыть оборонительные здания
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/防御.png


[canBuild_34]
name: 小型防御塔底座t1
pos: 34
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()

[canBuild_35]
name: 小型防御塔底座t2
pos: 35
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_36]
name: 小型防御塔底座t3
pos: 36
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_37]
name: 小型防御塔底座t4
pos: 37
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_38]
name: 砖墙
pos: 38
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()

[canBuild_39]
name: 混凝土围墙
pos: 39
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t2')
isLockedMessage: Требуется командный центр 2 уровня

[canBuild_40]
name: 钢筋混凝土围墙
pos: 40
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_41]
name: 强固混凝土围墙
pos: 41
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_42]
name: 中型防御塔底座t1
pos: 42
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_43]
name: 中型防御塔底座t2
pos: 43
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_44]
name: 中型防御塔底座t3
pos: 44
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_45]
name: 大型防御塔底座
pos: 45
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_46]
name: 地堡t2
pos: 46
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t2')
isLockedMessage: Требуется командный центр 2 уровня

[canBuild_47]
name: 地堡t3
pos: 47
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[canBuild_48]
name: 地堡t4
pos: 48
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_49]
name: 观察哨t2
pos: 49
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t2')
isLockedMessage: Требуется командный центр 2 уровня

[canBuild_50]
name: 观察哨t3
pos: 50
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[canBuild_51]
name: 观察哨t4
pos: 51
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_52]
name: 要塞t3
pos: 52
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: Требуется материаловедение 2



[canBuild_53]
name: 要塞t4
pos: 53
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_54]
name: 创世纪铁穹防空系统t1
pos: 54
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='弹道导弹技术1')
isLockedMessage: Требуется технология баллистических ракет 1

[canBuild_55]
name: 创世纪铁穹防空系统t2
pos: 55
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: true
isLockedMessage: Это здание может построить только Тяжёлая инженерная машина

[canBuild_56]
name:天盾防御系统
pos: 56
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')

[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36
[decal_炮塔影子1]
image: SHADOW:${turret_0.image}
total_frames: 1
layer: afterBody

isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 0
alpha:0.65
imageScale:1

[decal_炮塔影子]
image: SHADOW:${turret_2.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 2
alpha:0.65
imageScale:1
[graphics]
total_frames: 1
image: 船.png
image_wreak: 死亡.png
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
splastEffect: false
showEnergyBar: false
teamColorsOnTurret: true
showShotDelayBar:false
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 8
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shootDelay: 75

maxAttackRange: 280


[turret_0]
x: 0
y: 8
idleDir: 180
warmup: 30
turnSpeed: 4
image:支架.png
size: 25
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true
[turret_1]
x: 0
y: 0
projectile: 1
shoot_sound: missile_fire
shoot_sound_vol: 0.2
turnSpeed: 2
turnSpeedAcceleration: 0.1
shoot_light: #FFEEEE00
shoot_flame: CUSTOM:烟雾*2
canAttackFlyingUnits: false
canAttackLandUnits: true
energyUsage: 4
delay:10
size:10
invisible: true
attachedTo: 2
slave: true
[turret_2]
x: 0
y: 39
#炮塔
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1
turnSpeed: 2
turnSpeedAcceleration: 0.1

image:火箭炮.png
limitingAngle: 100
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 65
areaRadius: 30
life: 250
speed: 5
frame: 4
drawSize: 0.8
targetGround: true
trailEffect: false
lightSize: 0.75
lightColor: #FFFFFF73
largeHitEffect: true
areaRadiusFromEdge: true
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
createWhenOverLand: false
life: 90
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1
scaleTo: 4
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -20
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
[effect_火]
life: 70
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1
scaleTo: 2
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1
yOffsetRelative	: 0
drawUnderUnits: true
[movement]
movementType: WATER
moveSpeed: 1.0
moveAccelerationSpeed: 0.3
moveDecelerationSpeed: 0.3
maxTurnSpeed: 1.5

turnAcceleration: 0.2
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


[ai]
useAsBuilder: true

