


[core]
name: 太空浪人智脑节点
class: CustomUnitMetadata
price: 2500
maxHp: 10000
selfRegenRate: 0.2

footprint: -4,0,4,6
constructionFootprint: -4,0,4,6
techLevel: 1
energyMax: 1
energyRegen: 0

energyStartingPercentage: 1
buildSpeed: 10s
#displayDescription:太空浪人将从战场上收集来的尸体储存于此，\n-并将他们改造成傀儡为自己而战。
radius: 60
isBio: false

copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
exit_x: 0
exit_y: -1

tags: 地面,智脑,灰影建筑,建筑
armour: 10


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='智脑')
deleteSelf: true
#addResources:威胁点数=-${core.price / 25}
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈



[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: 缺少供能
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_断电a]
autoTrigger: if not self.hasFlag(id= 30) and self.queueSize > 0 and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
resetCustomTimer: true
addResources: setFlag= 30


[hiddenAction_断电b]
autoTrigger: if self.hasFlag(id= 30) and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30
refundAllQueuedItems: true


[hiddenAction_来电a]
autoTrigger: if self.hasFlag(id= 30) and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30


[action_科斯塔1]
text: 科斯塔家族科技1
buildSpeed: 30s
price: 1000,energy=1
description: -科斯塔工业集团的低端军火数据，\n-这些廉价而有效的技术能有效应对敌人，\n-这将解锁北极星机甲。\n-持有法雅德科技2和科斯塔科技2，可解锁帝国科技解析1。
isVisible: if not self.globalTeamTags(includes='科斯塔1')

addGlobalTeamTags: 科斯塔1
addResources: energy=1
iconImage: 科斯塔.png
showMessageToPlayer: 已共享 科斯塔家族一级技术。
pos: 1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_科斯塔2]
text: 科斯塔家族科技2
buildSpeed: 55s
price: 1600,energy=1,awz=100
description: -科斯塔中高端军火的数据，\n-这些科技都久经古人类战国时期战火的考验，\n-这将解锁狮鹫机甲，刚多林级巡洋舰，洪水炮塔。/n-持有法雅德科技2和科斯塔科技2，可解锁帝国科技解析1。
isVisible: if self.globalTeamTags(includes='科斯塔1') and not self.globalTeamTags(includes='科斯塔2')

addGlobalTeamTags: 科斯塔2
addResources: energy=1
iconImage: 科斯塔.png
ai_isHighPriority: true
showMessageToPlayer: 已共享 科斯塔家族二级技术

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_科斯塔3]
text: 科斯塔家族科技3
buildSpeed: 75s
price: 2200,energy=1,awz=200
description: -科斯塔高端限购级军火的数据，\n-因为忌惮运用这些科技所制造的战争兵器的力量，\n-科斯塔家族不会轻易将其卖给不信任的客户。\n-这将解锁黑火级巡洋舰，惩罚者，寂灭炮塔。
isVisible: if self.globalTeamTags(includes='科斯塔2') and not self.globalTeamTags(includes='科斯塔3')

addGlobalTeamTags: 科斯塔3
addResources: energy=1
iconImage: 科斯塔.png
ai_isHighPriority: true
showMessageToPlayer: 已共享 科斯塔家族三级技术

pos: 3
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_法雅德1]
text: 法雅德家族科技1
buildSpeed: 45s
price: 1400,energy=1,awz=60
description: -法雅德家族初级战争机械的设计数据，\n-这些科技在保证了质量的同时兼顾了效率，\n-这将解锁蝮蛇战机，黑曜石。\n-持有法雅德科技2和科斯塔科技2，可解锁帝国科技解析1。
isVisible: if not self.globalTeamTags(includes='法雅德1')

addGlobalTeamTags: 法雅德1
addResources: energy=1
iconImage: 法雅德.png
showMessageToPlayer: 已共享 法雅德家族一级技术。
pos: 1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_法雅德2]
text: 法雅德家族科技2
buildSpeed: 60s
price: 2000,energy=1,awz=140
description: -法雅德家族改良或意外发现的帝国科技，\n-先进的帝国科技再加上法雅德家族的智慧，\n-让这些兵器成为太空浪人军队中的关键力量。\n-这将解锁恶灵攻击机，冥卫机甲。/n-持有法雅德科技2和科斯塔科技2，可解锁帝国科技解析1。
isVisible: if self.globalTeamTags(includes='法雅德1') and not self.globalTeamTags(includes='法雅德2')

addGlobalTeamTags: 法雅德2
addResources: energy=1
iconImage: 法雅德.png
ai_isHighPriority: true
showMessageToPlayer: 已共享 法雅德家族二级技术

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_法雅德3]
text: 法雅德家族科技3
buildSpeed: 75s
price: 2600,energy=1,awz=210
description: -法雅德家族在古人类战国时期所持有的顶尖技术，\n-他们的力量在当时能让整个希诺星系为之颤抖，\n-即便放在今天也是一股令人恐惧的力量。\n-这将解锁帝王级战列舰，灭世炮塔。
isVisible: if self.globalTeamTags(includes='法雅德2') and not self.globalTeamTags(includes='法雅德3')

addGlobalTeamTags: 法雅德3
addResources: energy=1
iconImage: 法雅德.png
ai_isHighPriority: true
showMessageToPlayer: 已共享 法雅德家族三级技术

pos: 3
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_帝国科技解析1]
text: 帝国科技解析1
buildSpeed: 40s
price: 3000,energy=1,awz=150
description: -在拥有一定科技基础后，我们可以对帝国的常规科技进行复原，\n-这些常规科技能让我们造出更大更强的单位，\n-并熟练的运用立场技术。\n-这将解锁太空浪人超立方t1，太空浪人无人机库t1。
isVisible: if self.globalTeamTags(includes='法雅德2') and self.globalTeamTags(includes='科斯塔2') and not self.globalTeamTags(includes='帝国科技解析1')
addGlobalTeamTags: 帝国科技解析1
addResources: energy=1
iconImage: 帝国科技.png
ai_isHighPriority: true
showMessageToPlayer: 已复原 一级帝国科技

pos: 3
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[action_帝国科技解析2]
text: 帝国科技解析2
buildSpeed: 130s
price: 11000,energy=1,awz=300
description: -对皇帝曾经主导开发的一些初级技术进行还原，\n-虽然我们十分痛恨老皇帝，但这些技术却十分先进，\n-这些科技甚至对我们的终极武器起到关键作用。\n-这将解锁，光轮级护卫舰，仲裁者级航空母舰，耀斑级重型驱逐舰，安卡拉刚级巡洋舰。\n-以及阿玛洛克MKII和模拟黑洞的制造。
isVisible: if self.globalTeamTags(includes='帝国科技解析1') and not self.globalTeamTags(includes='帝国科技解析2')

addGlobalTeamTags: 帝国科技解析2
addResources: energy=1
iconImage: 帝国科技.png
ai_isHighPriority: true
showMessageToPlayer: 已复原 二级帝国科技


[action_爆散1研发]
price: energy=1,1300
text: 爆散弹头1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='爆散')

addGlobalTeamTags: 爆散1,爆散
addResources: energy=1
description: -由一股急剧压缩的不稳定物质制作的弹头，\n-弹体命中目标后会四分五裂或者贯穿敌人造成二次大范围伤害，\n-受影响的单位每次攻击都将造成二次面积伤害，伤害将转化为爆炸伤害。\n-有效单位：猎兵坦克 胡蜂无人机 萤火轰炸机
showMessageToPlayer: 爆散弹头1已经研发完成
ai_isHighPriority: true

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能
iconImage: 爆散.png


[action_爆散2研发]
price: energy=1,2300,awz=150
text: 爆散弹头2
displayType: upgrade
buildSpeed: 50s
isVisible: if self.globalTeamTags(includes='爆散1') and not self.globalTeamTags(includes='爆散2')

addGlobalTeamTags: 爆散2
addResources: energy=1
description: -新款的爆散弹头能容纳更多质量更大的凝聚态物质，\n-同时针对小型单位做了小型化处理，\n-受影响的单位每次攻击都将造成二次大面积伤害，伤害转化为爆炸伤害。\n-有效单位光翼战斗机，深渊级驱逐舰，冥卫机甲，路西法潜艇模式，黑火，惩罚者 刚多林级巡洋舰
showMessageToPlayer: 爆散弹头2已经研发完成
ai_isHighPriority: true

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能
iconImage: 爆散.png


[action_衰解1研发]
price: energy=1,1600
text: 相衰解炮1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='衰解')

addGlobalTeamTags: 衰解1,衰解
addResources: energy=1
description: -太空浪人利用暗物质原理制作的尖端武器，\n-利用熵的原理从原子层次对敌方目标进行彻底颠覆，\n-被攻击的单位每次都会获得减益资源，持有减益资源越多，\n-造成的减益也就越猛烈，\n-当敌方单位没有受到衰解武器攻击时，减益资源会持续减少，\n-伤害转变为能源，但减益造成的伤害为无法减免的直接伤害。\n-有效单位：招潮蟹机甲 天火炮艇
showMessageToPlayer: 相衰解炮1已经研发完成
ai_isHighPriority: true

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能
iconImage: 衰解.png


[action_衰解2研发]
price: energy=1,2500,awz=150
text: 相衰解炮2
displayType: upgrade
buildSpeed: 60s
isVisible: if self.globalTeamTags(includes='衰解1') and not self.globalTeamTags(includes='衰解2')

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能
addGlobalTeamTags: 衰解2
addResources: energy=1
description: -重型相衰解炮，更高效的暗物质发生器能显著提升衰解速度，\n-被攻击的单位每次都会获得减益资源，持有减益资源越多，\n-造成的减益也就越猛烈，\n-当敌方单位没有受到衰解武器攻击时，减益资源会持续减少，\n-伤害转变为能源，但减益造成的伤害为无法减免的直接伤害。\n-有效单位：恶灵 蝮蛇 北极星 狮鹫 黑火 剑鱼

showMessageToPlayer: 相衰解炮2已经研发完成
ai_isHighPriority: true
iconImage: 衰解.png


[action_亚空间幽灵1研发]
price: energy=1,2850
text: 亚空间幽灵1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='亚空间')

addGlobalTeamTags: 亚空间1,亚空间
addResources: energy=1
description: -利用小型亚空间引擎将单位折越到被古人类称为“亚空间”的镜像宇宙，\n-亚空间不仅与现所处的宇宙完全镜像相连，\n-而且在亚空间中时间流速和光速极限要元大于现宇宙，\n-从而实现单位的快速部署与移动。\n-指定单位将获得“越入亚空间”的技能，\n-技能冷却完毕后即可开启，单位将大幅度提升移动速度，\n-所有敌对单位无法攻击，\n-但开启过程中无法攻击任何单位，直到技能结束单位重现才可回复攻击能力。\n-有效单位：黑火级重型巡洋舰 黑曜石机甲 蝮蛇战斗机
showMessageToPlayer: 亚空间幽灵1已经研发完成
ai_isHighPriority: true

iconImage: 亚空间.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能


[graphics]
total_frames: 1
image: 遮盖2.png
image_back: 背景.png
image_wreak: 死亡.png
#imageScale:0.7


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: 0
y: -25
image_end: 脑子.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: 0
y: -21
image_end_teamColors: false
image_end: 玻璃.png
drawOverBody: true


[arm_3]
x: 0
y: 0
image_end_teamColors: false
image_end: 闪光.png
drawOverBody: true


[animation_idle]
onActions : idle
arm3_0s: {alpha:0.0}
arm3_0.8s: {alpha:1}
arm3_1.5s: {alpha:0.1}
arm1_0s: {x:0,y:0}

arm1_0.3s: {x:0,y:1}
arm1_0.6s: {x:0,y:1.5}
arm1_0.9s: {x:0,y:2}
arm1_1.2s: {x:0,y:2.5}
arm1_1.3s: {x:0,y:2}

arm1_1.5s: {x:0,y:1}


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


