


[core]
name: 太空浪人智脑节点
displayText: Узел разума Скитальцев
class: CustomUnitMetadata
price: 2500
maxHp: 10000
selfRegenRate: 0.2

footprint: -4,0,4,6
constructionFootprint: -4,0,4,6
techLevel: 1
energyMax: 1
energyRegen: 0

energyStartingPercentage: 1
buildSpeed: 10s
#displayDescription:太空浪人将从战场上收集来的尸体储存于此，\n-并将他们改造成傀儡为自己而战。
radius: 60
isBio: false

copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
exit_x: 0
exit_y: -1

tags: 地面,智脑,灰影建筑,建筑
armour: 10


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='智脑')
deleteSelf: true
#addResources:威胁点数=-${core.price / 25}
showMessageToPlayer: Эксплойт? Размечтался! В наказание лишних юнитов поглотил мой сервер 눈_눈



[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_断电a]
autoTrigger: if not self.hasFlag(id= 30) and self.queueSize > 0 and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
resetCustomTimer: true
addResources: setFlag= 30


[hiddenAction_断电b]
autoTrigger: if self.hasFlag(id= 30) and self.customTimer > 10 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30
refundAllQueuedItems: true


[hiddenAction_来电a]
autoTrigger: if self.hasFlag(id= 30) and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
addResources: unsetFlag= 30


[action_科斯塔1]
text: Технологии семьи Коста 1
buildSpeed: 30s
price: 1000,energy=1
description: -Данные дешёвого вооружения промышленной группы Коста.\n-Эти дешёвые и эффективные технологии помогают противостоять врагу.\n-Это разблокирует мех «Полярная звезда».\n-При наличии Технологий Фаяд 2 и Технологий Коста 2 можно разблокировать Анализ имперских технологий 1.
isVisible: if not self.globalTeamTags(includes='科斯塔1')

addGlobalTeamTags: 科斯塔1
addResources: energy=1
iconImage: 科斯塔.png
showMessageToPlayer: Получен общий доступ к Технологиям семьи Коста уровня 1.
pos: 1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_科斯塔2]
text: Технологии семьи Коста 2
buildSpeed: 55s
price: 1600,energy=1,awz=100
description: -Данные среднего и высокого класса вооружения Коста.\n-Эти технологии прошли испытания в горниле эпохи Воюющих государств Древних Людей.\n-Это разблокирует мех «Грифон», крейсер класса «Гондолин» и турель «Потоп»./n-При наличии Технологий Фаяд 2 и Технологий Коста 2 можно разблокировать Анализ имперских технологий 1.
isVisible: if self.globalTeamTags(includes='科斯塔1') and not self.globalTeamTags(includes='科斯塔2')

addGlobalTeamTags: 科斯塔2
addResources: energy=1
iconImage: 科斯塔.png
ai_isHighPriority: true
showMessageToPlayer: Получен общий доступ к Технологиям семьи Коста уровня 2

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_科斯塔3]
text: Технологии семьи Коста 3
buildSpeed: 75s
price: 2200,energy=1,awz=200
description: -Данные элитного ограниченного к продаже вооружения Коста.\n-Из-за опасений по поводу мощи оружия, созданного по этим технологиям,\n-семья Коста не продаёт их сомнительным клиентам.\n-Это разблокирует крейсер класса «Чёрный огонь», «Карателя» и турель «Гибель».
isVisible: if self.globalTeamTags(includes='科斯塔2') and not self.globalTeamTags(includes='科斯塔3')

addGlobalTeamTags: 科斯塔3
addResources: energy=1
iconImage: 科斯塔.png
ai_isHighPriority: true
showMessageToPlayer: Получен общий доступ к Технологиям семьи Коста уровня 3

pos: 3
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_法雅德1]
text: Технологии семьи Фаяд 1
buildSpeed: 45s
price: 1400,energy=1,awz=60
description: -Проектные данные начальных боевых машин семьи Фаяд.\n-Эти технологии сочетают качество и эффективность.\n-Это разблокирует истребитель «Гадюка» и «Обсидиан».\n-При наличии Технологий Фаяд 2 и Технологий Коста 2 можно разблокировать Анализ имперских технологий 1.
isVisible: if not self.globalTeamTags(includes='法雅德1')

addGlobalTeamTags: 法雅德1
addResources: energy=1
iconImage: 法雅德.png
showMessageToPlayer: Получен общий доступ к Технологиям семьи Фаяд уровня 1.
pos: 1

ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_法雅德2]
text: Технологии семьи Фаяд 2
buildSpeed: 60s
price: 2000,energy=1,awz=140
description: -Имперские технологии, улучшенные или случайно обнаруженные семьёй Фаяд.\n-Передовые имперские технологии в сочетании с мудростью семьи Фаяд\n-делают это вооружение ключевой силой в армии Скитальцев.\n-Это разблокирует штурмовик «Злой дух» и мех «Страж бездны»./n-При наличии Технологий Фаяд 2 и Технологий Коста 2 можно разблокировать Анализ имперских технологий 1.
isVisible: if self.globalTeamTags(includes='法雅德1') and not self.globalTeamTags(includes='法雅德2')

addGlobalTeamTags: 法雅德2
addResources: energy=1
iconImage: 法雅德.png
ai_isHighPriority: true
showMessageToPlayer: Получен общий доступ к Технологиям семьи Фаяд уровня 2

pos: 2
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_法雅德3]
text: Технологии семьи Фаяд 3
buildSpeed: 75s
price: 2600,energy=1,awz=210
description: -Высшие технологии семьи Фаяд эпохи Воюющих государств Древних Людей.\n-Их мощь в то время заставляла трепетать всю галактику Сино,\n-и сегодня это всё ещё страшная сила.\n-Это разблокирует линкор класса «Император» и турель «Истребитель миров».
isVisible: if self.globalTeamTags(includes='法雅德2') and not self.globalTeamTags(includes='法雅德3')

addGlobalTeamTags: 法雅德3
addResources: energy=1
iconImage: 法雅德.png
ai_isHighPriority: true
showMessageToPlayer: Получен общий доступ к Технологиям семьи Фаяд уровня 3

pos: 3
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_帝国科技解析1]
text: Анализ имперских технологий 1
buildSpeed: 40s
price: 3000,energy=1,awz=150
description: -Имея определённую технологическую базу, мы можем восстановить обычные имперские технологии.\n-Эти технологии позволяют создавать более крупные и сильные юниты,\n-а также мастерски использовать технологию полей.\n-Это разблокирует Гиперкуб Скитальцев t1 и Ангар дронов Скитальцев t1.
isVisible: if self.globalTeamTags(includes='法雅德2') and self.globalTeamTags(includes='科斯塔2') and not self.globalTeamTags(includes='帝国科技解析1')
addGlobalTeamTags: 帝国科技解析1
addResources: energy=1
iconImage: 帝国科技.png
ai_isHighPriority: true
showMessageToPlayer: Восстановлены Имперские технологии уровня 1

pos: 3
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[action_帝国科技解析2]
text: Анализ имперских технологий 2
buildSpeed: 130s
price: 11000,energy=1,awz=300
description: -Восстановление некоторых начальных технологий, разработанных под руководством императора.\n-Хотя мы ненавидим старого императора, эти технологии очень передовые,\n-они даже играют ключевую роль в нашем абсолютном оружии.\n-Это разблокирует фрегат класса «Световой нимб», корабль класса «Арбитр», тяжёлый эсминец класса «Вспышка», крейсер класса «Анкараган».\n-А также «Амарок MKII» и создание симулированной чёрной дыры.
isVisible: if self.globalTeamTags(includes='帝国科技解析1') and not self.globalTeamTags(includes='帝国科技解析2')

addGlobalTeamTags: 帝国科技解析2
addResources: energy=1
iconImage: 帝国科技.png
ai_isHighPriority: true
showMessageToPlayer: Восстановлены Имперские технологии уровня 2


[action_爆散1研发]
price: energy=1,1300
text: Детонационная боеголовка 1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='爆散')

addGlobalTeamTags: 爆散1,爆散
addResources: energy=1
description: -Боеголовка из резко сжатого нестабильного вещества.\n-После попадания в цель она разрывается на части или пробивает врага, нанося вторичный урон по большой площади.\n-Затронутые юниты при каждой атаке будут наносить вторичный урон по площади, урон преобразуется во взрывной.\n-Доступные юниты: танк «Егерь», дрон «Шершень», бомбардировщик «Светлячок».
showMessageToPlayer: Детонационная боеголовка 1 — исследование завершено
ai_isHighPriority: true

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания
iconImage: 爆散.png


[action_爆散2研发]
price: energy=1,2300,awz=150
text: Детонационная боеголовка 2
displayType: upgrade
buildSpeed: 50s
isVisible: if self.globalTeamTags(includes='爆散1') and not self.globalTeamTags(includes='爆散2')

addGlobalTeamTags: 爆散2
addResources: energy=1
description: -Новая детонационная боеголовка вмещает больше конденсированной материи большей массы,\n-одновременно подвергнутой миниатюризации для малых юнитов.\n-Затронутые юниты при каждой атаке будут наносить вторичный урон по большой площади, урон преобразуется во взрывной.\n-Доступные юниты: истребитель «Световое крыло», эсминец класса «Бездна», мех «Страж бездны», «Люцифер» в режиме подлодки, «Чёрный огонь», «Каратель», крейсер класса «Гондолин».
showMessageToPlayer: Детонационная боеголовка 2 — исследование завершено
ai_isHighPriority: true

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания
iconImage: 爆散.png


[action_衰解1研发]
price: energy=1,1600
text: Фазовая распадная пушка 1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='衰解')

addGlobalTeamTags: 衰解1,衰解
addResources: energy=1
description: -Передовое оружие Скитальцев, основанное на принципе тёмной материи,\n-использующее закон энтропии для полного разрушения целей противника на атомном уровне.\n-Атакованный юнит каждый раз получает дебафф-ресурсы, чем больше дебафф-ресурсов,\n-тем сильнее наносимый дебафф.\n-Когда вражеский юнит не подвергается атакам распадного оружия, дебафф-ресурсы постепенно уменьшаются.\n-Урон становится энергетическим, но дебафф наносит прямой неснижаемый урон.\n-Доступные юниты: мех «Краб-скрипач», канонерка «Небесный огонь».
showMessageToPlayer: Фазовая распадная пушка 1 — исследование завершено
ai_isHighPriority: true

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания
iconImage: 衰解.png


[action_衰解2研发]
price: energy=1,2500,awz=150
text: Фазовая распадная пушка 2
displayType: upgrade
buildSpeed: 60s
isVisible: if self.globalTeamTags(includes='衰解1') and not self.globalTeamTags(includes='衰解2')

isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания
addGlobalTeamTags: 衰解2
addResources: energy=1
description: -Тяжёлая фазовая распадная пушка. Более эффективный генератор тёмной материи значительно ускоряет распад.\n-Атакованный юнит каждый раз получает дебафф-ресурсы, чем больше дебафф-ресурсов,\n-тем сильнее наносимый дебафф.\n-Когда вражеский юнит не подвергается атакам распадного оружия, дебафф-ресурсы постепенно уменьшаются.\n-Урон становится энергетическим, но дебафф наносит прямой неснижаемый урон.\n-Доступные юниты: «Злой дух», «Гадюка», «Полярная звезда», «Грифон», «Чёрный огонь», «Меч-рыба».

showMessageToPlayer: Фазовая распадная пушка 2 — исследование завершено
ai_isHighPriority: true
iconImage: 衰解.png


[action_亚空间幽灵1研发]
price: energy=1,2850
text: Подпространственный призрак 1
displayType: upgrade
buildSpeed: 30s
isVisible: if not self.globalTeamTags(includes='亚空间')

addGlobalTeamTags: 亚空间1,亚空间
addResources: energy=1
description: -Маленькие подпространственные двигатели позволяют юнитам прыгать в зеркальную вселенную, которую Древние Люди называют «подпространство».\n-Подпространство не только полностью зеркально связано с текущей вселенной,\n-но и в нём скорость времени и предел скорости света на порядки выше, чем в нашей,\n-что обеспечивает быстрое развёртывание и перемещение юнитов.\n-Указанные юниты получат навык «Войти в подпространство»,\n-после перезарядки навыка можно его активировать, юнит значительно повышает скорость передвижения,\n-все враги не могут его атаковать,\n-но во время активации юнит не может атаковать никого, пока навык не закончится и юнит не вернётся.\n-Доступные юниты: тяжёлый крейсер класса «Чёрный огонь», мех «Обсидиан», истребитель «Гадюка».
showMessageToPlayer: Подпространственный призрак 1 — исследование завершено
ai_isHighPriority: true

iconImage: 亚空间.png
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[graphics]
total_frames: 1
image: 遮盖2.png
image_back: 背景.png
image_wreak: 死亡.png
#imageScale:0.7


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: 0
y: -25
image_end: 脑子.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: 0
y: -21
image_end_teamColors: false
image_end: 玻璃.png
drawOverBody: true


[arm_3]
x: 0
y: 0
image_end_teamColors: false
image_end: 闪光.png
drawOverBody: true


[animation_idle]
onActions : idle
arm3_0s: {alpha:0.0}
arm3_0.8s: {alpha:1}
arm3_1.5s: {alpha:0.1}
arm1_0s: {x:0,y:0}

arm1_0.3s: {x:0,y:1}
arm1_0.6s: {x:0,y:1.5}
arm1_0.9s: {x:0,y:2}
arm1_1.2s: {x:0,y:2.5}
arm1_1.3s: {x:0,y:2}

arm1_1.5s: {x:0,y:1}


[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


