


[core]
name: 核子巡洋舰
displayText: Ядерный крейсер
price: 4500,钍=45
maxHp: 8000
displayDescription: 【Уровень t3】【Механический юнит】【Надводный юнит】\n-死亡послесамоподрыв наноситвзрывной урон Тактическое назначение:высокий速противокорабельныйбоевой корабль，вооружение：\n-▲противокорабельныйракетаX10 только по земле взрывной урон\n-Ядерный крейсер 灵чувствоватьприходить вЛуна背поверхностьобнаруживать Древние Людикорабльпроектировать。\n-Ядерный крейсероснащёндваавиадвигательа такжеодин具ториевый солевой реактор，\n-этот些сильныймощный оборудованиепозволяетонстановитьсяГенезисВМСвскорость ходасамый быстрый 急авангард。\n-тольконужноуспехпозволяетцельвходитдоЯдерный крейсер дальностьв，\n-большое количествопротивокорабельныйракетапусковая установка倾泻выходить снаряд雨можетвмгновеннобудетвражескийкорабльопрокинуть，\n-этот видбыстрыйимощный毁灭者можетс闪Электричество般 скоростьликвидироватьнадводныйцель。
techLevel: 1
buildSpeed: 18s
radius: 70
displayRadius: 70
unitsSpawnedOnDeath: 中型水上单位死亡*1
isBio: false
softCollisionOnAll: 7
tags: 地面,海上
armour: 15
fogOfWarSightRange: 25
copyFrom: ROOT:/通用特效/单位防护.ini
fireTurretXAtSelfOnDeath:21
[action_聚变弹头2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变2.png
text: Термоядерная боеголовка2
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头2')

[decal_灯光12]
layer: afterBody
image: 闪光.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
imageScale:0.8

[decal_炮塔影子]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
[decal_炮塔影子1]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
basePositionFromTurret: 5
alpha:0.65
imageScale: 0.85
[decal_炮塔影子2]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
basePositionFromTurret: 9
alpha:0.65
imageScale: 0.85
[decal_炮塔影子3]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
basePositionFromTurret: 13
alpha:0.65
imageScale: 0.85
[decal_炮塔影子4]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
basePositionFromTurret: 17
alpha:0.65
imageScale: 0.85
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
imageScale:0.8
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
#image_turret: 炮塔.png
imageScale: 0.8

image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2
splastEffect: true
turretImageScale: 0.85
teamColorsOnTurret: true
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 12

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 75
maxAttackRange: 480
turretMultiTargeting: true

[turret_1]
x: 0
y: 75
canShoot: false
image: 炮塔.png
limitingAngle: 65
#idleDir:-90
turnSpeed: 3.5
turnSpeedAcceleration: 1
canAttackFlyingUnits:false
canAttackUnderwaterUnits: false
[turret_2]
x: 3.5
y: 6
#导弹右
projectile: 1
attachedTo: 1
slave: true
image: ROOT:/创世纪军事集团/单位特效/中导弹x.png
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*3
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -10
size:3
recoilOutTime: 4
recoilReturnTime: 60
delay:120
canAttackFlyingUnits:false
canAttackUnderwaterUnits: false
altProjectile: 2
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头2')
[turret_3]
x: -3.5
y: 6
copyFrom: 2
warmup: 10
delay:110
linkDelayWithTurret:2
[turret_4]
x: 0
y: 0
canShoot: false
image: 炮塔1.png
canAttackFlyingUnits:false
canAttackUnderwaterUnits: false
attachedTo: 1
slave: true
[turret_5]
x: 23
y: 38
copyFrom: 1
idleDir:10
#limitingAngle: 110
[turret_6]
x: 3.5
y: 6
copyFrom: 2
attachedTo: 5
slave: true
[turret_7]
x: -3.5
y: 6
copyFrom: 2
attachedTo: 5
slave: true
warmup: 10
delay:110
linkDelayWithTurret:6
[turret_8]
x: 0
y: 0
copyFrom: 4
attachedTo: 5
slave: true
[turret_9]
x: -23
y: 38
copyFrom: 1
idleDir:-10
#limitingAngle: 110
[turret_10]
x: 3.5
y: 6
copyFrom: 2
attachedTo: 9
slave: true
[turret_11]
x: -3.5
y: 6
copyFrom: 2
attachedTo: 9
slave: true
warmup: 10
delay:110
linkDelayWithTurret:10
[turret_12]
x: 0
y: 0
copyFrom: 4
attachedTo: 9
slave: true
[turret_13]
x: -26
y: -75
copyFrom: 1
idleDir:-90
limitingAngle: 55
[turret_14]
x: 3.5
y: 6
copyFrom: 2
attachedTo: 13
slave: true
[turret_15]
x: -3.5
y: 6
copyFrom: 2
attachedTo: 13
slave: true
warmup: 10
delay:110
linkDelayWithTurret:14
[turret_16]
x: 0
y: 0
copyFrom: 4
attachedTo: 13
slave: true
[turret_17]
x: 26
y: -75
copyFrom: 1
idleDir:90
limitingAngle: 55
[turret_18]
x: 3.5
y: 6
copyFrom: 2
attachedTo: 17
slave: true
[turret_19]
x: -3.5
y: 6
copyFrom: 2
attachedTo: 17
slave: true
warmup: 10
delay:110
linkDelayWithTurret:14
[turret_20]
x: 0
y: 0
copyFrom: 4
attachedTo: 17
slave: true
[turret_21]
x: 0
y: 0
invisible: true
shoot_sound: ROOT:/通用特效/大爆炸1.ogg
shoot_sound_vol: 0.7
shoot_flame: NONE
shoot_light: #FFFFEB88
projectile: 3
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
[projectile_1]
@copyFromSection: template_爆炸
directDamage: 340
life: 250
speed: 2
targetSpeed: 12
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
drawSize: 0.73
trailEffect: true
lightSize: 0.75
lightColor: #FFFFFF73
autoTargetingOnDeadTarget: true
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠


[projectile_2]
@copyFromSection: template_能源
areaDamage: 370
areaRadius: 65
life: 250
speed: 7
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
drawSize: 0.75
trailEffect: true
lightSize: 0.75
deflectionPower: -1
lightColor: #FFFFFF73
autoTargetingOnDeadTarget: true
explodeEffect: CUSTOM:底色,CUSTOM:闪光s,CUSTOM:冲击波jb
explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光s,CUSTOM:冲击波jb
buildingDamageMultiplier: 2
areaRadiusFromEdge: true

[projectile_3]
@copyFromSection: template_爆炸
areaDamage: 10000
areaRadius: 300
life: 666
speed: 8888
targetSpeed: 8888
instant: true
flameWeapon: true
deflectionPower: -1
explodeEffect: CUSTOM:火光,CUSTOM:闪光z,CUSTOM:冲击波x,CUSTOM:闪光1x,CUSTOM:闪光x,CUSTOM:闪光a,CUSTOM:气旋, CUSTOM:巨大冲击波x,CUSTOM:红闪光*2
explodeEffectOnShield:   CUSTOM:火光,CUSTOM:闪光z,CUSTOM:冲击波x,CUSTOM:闪光1x,CUSTOM:闪光x,CUSTOM:闪光a,CUSTOM:气旋, CUSTOM:巨大冲击波x,CUSTOM:红闪光*2,CUSTOM:火光
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[effect_闪光jb]
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 10
scaleTo: 15
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_气旋]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:35
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:1.7
scaleTo:3.4
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
alsoPlaySound:ROOT:/通用特效/巨大爆炸.ogg
#dirSpeedRandom: 1.5
[effect_红闪光]
image: SHARED:light_50.png
life: 300
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFF86
priority: critical
fadeInTime: 2
scaleFrom: 2.8
scaleTo: 2.8
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波x]
stripIndex: shockwave
life: 80
scaleFrom: 1
scaleTo: 10
alpha: 1

[effect_闪光1x]
priority: low
image: SHARED:light_50.png
life: 400
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false
atmospheric: false
[effect_巨大冲击波x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 3.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_闪光z]
image: SHARED:light_50.png
life: 600
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_闪光a]
image: SHARED:light_50.png
life:400
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF5B18
fadeInTime: 2
priority: critical
scaleFrom: 13
scaleTo: 13
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_火光]
priority: critical
image: ROOT:/通用特效/火光.png
life: 485
fadeOut: true
attachedToUnit: false
scaleFrom: 6
scaleTo: 6
alwayStartDirAtZero: true
color: #FFFF5B18
alpha: 0.9
drawUnderUnits: false
atmospheric: false
[effect_底色]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 60
fadeOut: true
attachedToUnit: false
scaleFrom: 0.45
scaleTo: 0.45
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_闪光x]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 0.8
alpha: 0.8
drawUnderUnits: false
atmospheric: true

[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.4
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
[effect_闪光s]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3
scaleTo: 3
drawUnderUnits: false
atmospheric: false
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
createWhenOverLand: false
life: 90
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.6
scaleTo: 6
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -40
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
[effect_火]
life: 100
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1
scaleTo: 3.7
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1.5
yOffsetRelative	: 10
drawUnderUnits: true
[arm_1]
x: 0
y: 0
image_end: 主体1.png
image_end_teamColors: true
drawUnderAllUnits: true
[arm_2]
x: 0
y: -48
image_end: ROOT:/创世纪军事集团/单位特效/雷达.png
drawOverBody: true
spinRate: 4

[movement]
movementType: WATER
moveSpeed: 1.15
moveAccelerationSpeed: 0.025
moveDecelerationSpeed: 0.025
maxTurnSpeed: 1
turnAcceleration: 0.4
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


