


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}


[core]
name: SDAF猎户座
displayDescription: -猎户座机甲是一款可以搭载多种导弹的移动火炮平台，\n-在古人类第二次大航海时期末期，搭载有核弹的猎户座是小国最实惠的威慑武器，\n-最重要的是，这款多足机甲不仅便宜耐用，而且制造工序极为简单，\n-因此，猎户座的图纸经过了亚尔佛里德共和国和诺瓦帝国，以及余辉的优化，并沿用至今，\n-但拥有庞大舰队的余辉早已不需要这种勉强够看的威慑武器，\n-现在，猎户座多在余辉陆军中扮演中远程重火力压制的角色。\n-对地对空，爆炸伤害，对建筑伤害加成，水陆两栖，无法攻击太近的敌人。\n-设计类型：帝国余辉基础数据库
class: CustomUnitMetadata
price: 3500
maxHp: 1500
fogOfWarSightRange: 22
techLevel: 1
buildSpeed: 18s
radius: 47
isBio: false
transportSlotsNeeded: 2

energyMax: 10
energyRegen: 0.03
energyNeedsToRechargeToFull: true
copyFrom: ROOT:/通用特效/单位防护.ini
unitsSpawnedOnDeath: 损毁2*1

maxShield: 1000
shieldRegen: 0.07
tags: 地面,无人单位

[action_重子兵器1]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重1.png
text: 重子兵器1
isActive: false
isVisible: if self.globalTeamTags(includes='重子1')


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
addResources: shield=10
text: 正电子芯核
price: 0
displayType: infoOnlyNoBox

isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png



[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=500) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=500)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 1
maxAttackRange: 430
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_1]
x: 0
y: 0
canShoot: false
#image:主体.png


[turret_2]
x: 0
y: -4
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3

shoot_flame: CUSTOM:烟雾*2
shoot_light: #FFEECCCC
projectile: 1
size: 0
turnSpeed: 811
turnSpeedAcceleration: 10
delay: 240
attachedTo: 1
slave: false
canAttackFlyingUnits: false
limitingMinRange: 170
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='重子1')


[turret_3]
x: 0
y: 3
copyFrom: 2
warmup:15
delay:225


[turret_4]
x: 0
y: 4
copyFrom: 2
warmup:30
delay:210


[turret_5]
x: 0
y: -4
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*2
shoot_light: #FFEECCCC
projectile: 2
size: 0
turnSpeed: 811
turnSpeedAcceleration: 10
delay: 160
attachedTo: 1
slave: false
limitingMinRange: 170
canAttackLandUnits: false
canAttackCondition: if self.resource.xk < 1


[turret_6]
x: 0
y: 3
copyFrom: 5
warmup:15
delay:145

[turret_7]
x: 0
y: 4
copyFrom: 5
warmup:30
delay:130


[projectile_1]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85

image: ROOT:/余辉军团/单位特效/鱼雷.png
trailEffect: true
directDamage: 110
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定*4
lightSize: 1
lightColor: #FF00B3FF


[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 110
areaRadius: 50
life: 200
speed: 7

image: ROOT:/余辉军团/单位特效/星星.png
targetSpeed: 14
drawSize: 0.45
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光

buildingDamageMultiplier: 1.5
targetGroundSpread: 65
targetGround: true
areaRadiusFromEdge: true
lightSize: 0.75

lightColor: #FF00B3FF


[projectile_2]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 11
largeHitEffect: true

drawSize: 0.85
image: ROOT:/余辉军团/单位特效/导弹.png
trailEffect: true
directDamage: 150
ballistic: true

ballistic_height: 80
ballistic_delaymove_height: 65
lightSize: 1
lightColor: #FF00B3FF
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光

[projectile_炮弹1]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85

image: ROOT:/余辉军团/单位特效/鱼雷.png
trailEffect: true
directDamage: 650
ballistic: true
deflectionPower: -1

ballistic_height: 80
ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定1
lightSize: 1
lightColor: #FF00B3FF


[projectile_锁定1]
@copyFromSection: template_爆炸
areaDamage: 650
areaRadius: 65
life: 200
speed: 7

areaHitAirAndLandAtSameTime: true
image: ROOT:/余辉军团/单位特效/星星2.png
targetSpeed: 14
drawSize: 0.55
explodeEffectOnShield: CUSTOM:底色a,CUSTOM:闪光d,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:聚变

explodeEffect: CUSTOM:底色a,CUSTOM:闪光d,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:聚变
deflectionPower: -1
targetGroundSpread: 65
targetGround: true
areaRadiusFromEdge: true

lightSize: 0.75
lightColor: #FF00B3FF


[effect_底色a]
priority: critical
image: ROOT:/余辉军团/单位特效/黑洞1.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.33
scaleTo: 0.33
alpha: 1.3
drawUnderUnits: false
atmospheric: false


[effect_闪光d]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: true
atmospheric: false


[effect_粒子a]
life: 30
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 0.1
scaleTo: 3
alpha: 1
dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
drawUnderUnits: true


[effect_冲击波a]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 3
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 0.6
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg



[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[arm_1]
x: 0
y: 0
image_end: 主体1.png
image_end_teamColors: true
#drawOverBody: true
lockMovement: true
#hidden: if self.hp<self.maxHp * 0.36
[arm_3]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
lockMovement: true
hidden: if self.maxHp * 0.36 < self.hp
drawOverBody: true
[arm_2]
x: 0
y: 3.3
image_end: 盖子.png
image_end_teamColors: true
#drawOverBody: true


[leg_1]
x: -17
y: 62
attach_x: -7
attach_y: 22
moveSpeed: 2

rotateSpeed: 6
heightSpeed: 0.5
resetAngle: 8
image_leg: 腿.png
image_foot: 脚1.png

holdDisMin: 5
holdDisMax: 15
endDirOffset: -20
hardLimit: 25


[leg_2]
x: 17
y: 62
attach_x: 7
attach_y: 22
copyFrom: 1

endDirOffset: 16


[leg_3]
x: -32
y: -38
attach_x: -7
attach_y: -3
copyFrom: 1

endDirOffset: -130


[leg_4]
x: 32
y: -38
attach_x: 7
attach_y: -3
copyFrom: 1

endDirOffset: 130


[leg_5]
x: -33
y: 31
attach_x: -7
attach_y: -3
copyFrom: 1

endDirOffset: -30


[leg_6]
x: 33
y: 31
attach_x: 7
attach_y: -3
copyFrom: 1

endDirOffset: 30


[effect_爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.7

scaleTo: 1.4
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_烟雾]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.25
scaleTo: 1.25
alpha: 0.65
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm2_1s: {x:0, y:-21}
arm2_490s: {x:0, y:-21}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm2_1s: {x:0, y:0}


[movement]
movementType: OVER_CLIFF_WATER
moveSpeed: 0.65
moveAccelerationSpeed: 0.5
moveDecelerationSpeed: 0.5
maxTurnSpeed: 1.1

turnAcceleration: 0.6
moveSlidingMode: false
moveIgnoringBody:true


