


[core]
name: 角斗士
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/扎针.md,ROOT:/通用特效/步兵掩体.md
price: 1700
maxHp: 2000
displayDescription:【阶级t3】【生物单位】【地面单位】战术定位:高级反装甲步兵，单位体积:3\n-▲155毫米榴弹炮X2 只能对地 动能伤害\n-角斗士诞生于资源极度匮乏，生产力近乎崩溃的绝境时期，\n-余辉的残骸，再加上创世纪仅有的设备拼凑成了这款机甲，\n-这种简单乃至简陋的作战机甲甚至只用人力都能组装。\n-其主武器由锯短的155MM牵引式火炮直接改造而来，\n-无数的战斗中，角斗士都以凶悍的火力摧毁了无数重型单位，\n-这证明他们即使凭借简陋的武器也能成为战场上的毁灭者。

techLevel: 1
buildSpeed: 13s
#availableInDemo: true
radius: 27
displayRadius: 27
isUnrepairableUnit:true
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,机甲,角斗士,步兵

transportSlotsNeeded: 3
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: 恐怖地雷1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
#———科技—————
[action_轻型掩体]
text: 轻型掩体
isVisible: if self.globalTeamTags(includes='外骨骼')
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/轻型掩体.png
description: 一处轻型掩体，能为附近步兵140范围内的生物单位提供轻型掩护。\n-轻型掩护能为生物单位减免50%的伤害，\n-但是，掩体无法减免部分速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。
[action_加掩体]
autoTrigger: if self.globalTeamTags(includes='外骨骼')and not self.tags(includes= '轻型掩体') and not self.hasParent
isVisible:false
temporarilyAddTags:轻型掩体

[hiddenAction_减掩体]
autoTrigger:if self.hasParent and self.tags(includes= '轻型掩体')
isVisible:false
temporarilyRemoveTags:轻型掩体

[hiddenAction_外骨骼生效麻烦1]
autoTrigger: if self.globalTeamTags(includes='外骨骼')
setUnitStats:armour= ${core.armour+10}

[action_外骨骼]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/外骨骼.png
text: 外骨骼技术
isActive: false
isVisible: if self.globalTeamTags(includes='外骨骼')
[hiddenAction_外骨骼生效]
autoTrigger: if self.globalTeamTags(includes='外骨骼') and not self.tags(includes= '外骨骼保险')
setUnitStats: moveSpeed= ${movement.moveSpeed * 1.3},maxHp= ${core.maxHp*1.2},hp= ${core.maxHp*1.2}, maxTurnSpeed = ${movement.maxTurnSpeed* 1.65}
temporarilyAddTags:外骨骼保险

[action_弹幕架2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕2.png
text: 弹幕架2
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架2')
[decal_损坏]
layer: onTop
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36
basePositionFromTurret: 1
[decal_损坏1]
layer: onTop
image: 炮损坏1.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36
basePositionFromTurret: 2
[decal_损坏2]
layer: onTop
image: 炮损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36
basePositionFromTurret: 3
[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[graphics]
image: NO.png
image_wreak: 角斗士死亡.png
image_turret: 角斗士.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
lock_body_rotation_with_main_turret: true
lock_shadow_rotation_with_main_turret: true
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretTurnSpeed: 1.8

maxAttackRange: 330
shootDelay: 180
turretRotateWithBody: true


[turret_1]
x: 0
y: 0
turnSpeed: 1.8
turnSpeedAcceleration: 0.1
canShoot: false
canAttackFlyingUnits: false



[turret_2]
x: 15
y: 0
image: 炮1.png
attachedTo: 1
barrelX: 5

idleDir: 10
warmup: 0
projectile: 1
turnSpeed: 3.0
limitingAngle: 30

turnSpeedAcceleration: 0.5
shoot_sound: 开炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾2*3,CUSTOM:枪口火焰,CUSTOM:弹壳
shoot_light: #FFEECCCC
delay:180
canShoot: true
size: 36
recoilOffset: -3

canAttackFlyingUnits: false
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='弹幕架2')

[turret_3]
x: -15
y: 0
shoot_flame: CUSTOM:烟雾2*3,CUSTOM:枪口火焰,CUSTOM:弹壳2
copyFrom: 2
idleDir: -10
barrelX: -5
delay:170
warmup:10
image: 炮.png
[projectile_1]
@copyFromSection: template_动能
areaDamage: 700
areaRadius: 30
life: 550
speed: 7.8

frame: 9
drawSize: 0.8
trailEffect: true
lightSize: 0.75
areaRadiusFromEdge: true

lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:弹坑
[projectile_炮弹]
life: 0
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 炮弹1*2

[projectile_炮弹1]
@copyFromSection: template_爆炸
areaDamage: 470
areaRadius: 35
life: 550
speed: 7.8
frame: 9
drawSize: 0.8
trailEffect: true
lightSize: 0.75
speedSpread:1
targetGround: true
lightColor: #FFFFFF73
targetGroundSpread: 38
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:弹坑

[projectile_3]
directDamage: 0
life: 0
speed: 0
targetSpeed: 0


[effect_弹壳]
priority: low
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2

fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
ySpeedRelative: -1
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -47

xOffsetRelative: -11
hSpeed: 2
dirSpeedRandom: 5


[effect_弹壳2]
priority: low
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2

fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
ySpeedRelative: -1
xSpeedRelativeRandom: -0.2
ySpeedRelativeRandom: 0.1
yOffsetRelative: -47
xOffsetRelative: 11
hSpeed: 2
dirSpeedRandom: 5


[effect_烟雾2]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.25
scaleTo: 1.25
alpha: 0.65
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.7
scaleTo: 1.7

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸1.ogg
alwayStartDirAtZero: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 3
scaleTo: 3


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 0.7
scaleTo: 0.7
createWhenOverLiquid: false
createWhenOverLand: true
[leg_1]
x: -8
y: 0
attach_x: -3
attach_y: 0
moveSpeed: 2.8

moveWarmUp: 0.1s
hidden: if self.hasParent()
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25

image_leg: ROOT:/创世纪军事集团/单位特效/腿.png
image_foot: ROOT:/创世纪军事集团/单位特效/脚.png
#draw_foot_on_top: true
dust_effect: false
holdDisMin: 5

holdDisMax: 20
estimatingPositionMultiplier: 0.8


[leg_2]
x: 8
y: 0
attach_x: 3
attach_y: 0
copyFrom: 1

hidden: if self.hasParent()


[movement]
movementType: LAND
moveSpeed: 0.7
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.07
reverseSpeedPercentage: 0.4
maxTurnSpeed: 2
turnAcceleration: 0.5
moveSlidingMode : false
moveIgnoringBody: false

