


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}


[core]
name: HK死亡之雨
copyFrom: ROOT:/通用特效/单位防护.ini
price: 1300
maxHp: 1000
maxShield: 1250
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
shieldRegen: 0.07
displayDescription: -这款机甲是古人类战国时期亚尔佛里德共和国的产物，\n-这些部署在矿区的自律防卫者是起义军最头疼的敌人之一。\n-起义胜利后，后来建立的诺瓦帝国收缴了大量亚尔佛里德的死亡之雨机甲。\n-这款机甲能够发射大量电浆导弹迅速覆盖敌人的地面与空中目标，\n-同时又配有相位炮和机枪分别对付地面装甲单位和步兵，\n-其优异的性能和极为可观的库存，使得这款机甲总是余辉进攻部队的首选。\n-对地对空。导弹爆炸且对空军伤害加成，主炮，机枪能源且反掩体。\n-设计类型：帝国余辉基础数据库
techLevel: 1
buildSpeed: 11s
#availableInDemo: true

radius: 28
armour: 4
displayRadius: 28
unitsSpawnedOnDeath: 损毁*1
tags: 地面,无人单位

#transportSlotsNeeded:2
energyMax: 8
energyRegen: 0.075
energyNeedsToRechargeToFull: true
[action_反物质1]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/反1.png
text: 反物质兵器1
isActive: false
isVisible: if self.globalTeamTags(includes='反物质1')


[action_裂解炮1]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/裂解1.png
text: 裂解炮1
isActive: false
isVisible: if self.globalTeamTags(includes='裂解炮1')


[action_1_曲线跳跃]
fireTurretXAtGround: 曲线
text: 曲线跳跃
isVisible: if self.globalTeamTags(includes='曲线核1')
iconImage: ROOT:/余辉军团/单位特效/曲线核1.png
displayType: action
buildSpeed: 0s
pos: 0.1
#displayRemainingStockpile: true
highPriorityQueue: true
canPlayerCancel: false
onlyOneUnitAtATime: false
description: 开启曲线核，进行一次短距离瞬间跳跃，\n-单位将瞬间移动至目标地点。
addActionCooldownTime: 20s
isLocked: if self.resource.xk > 0
[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: 正电子芯核
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png

[decal_炮塔1]
image: 损坏.png
basePositionFromTurret: 3
layer:onTop
isVisible:if self.hp<self.maxHp * 0.36 
onlyWhileAlive:true
#imageScale:0.85
teamColors:true

[action_t1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[turret_曲线]
x: 0
y: 0
canShoot: false
idleDir: 0
invisible: true

size: 1.1
turnSpeed: 40
shoot_sound: NONE
shoot_sound_vol: 0.6
projectile: 炮弹3

limitingRange: 300



[projectile_炮弹3]
life: 600
directDamage: 0
speed: 70
targetSpeed: 70
drawSize: 0

frame: 1
targetGroundSpread: 8
targetGround: true
deflectionPower: -1
explodeEffect: CUSTOM:闪光c,CUSTOM:冲击波a

teleportSource: true

[effect_闪光c]
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF39FFFF
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false
atmospheric: false
[effect_冲击波a]
image: ROOT:/余辉军团/单位特效/冲击波1.png
life: 20
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.8
alpha: 0.8
drawUnderUnits: false
atmospheric: false



[graphics]
image: ROOT:/通用特效/NO.png
image_wreak: 死亡.png
image_turret: 身体.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
showEnergyBar: false
lock_body_rotation_with_main_turret: true
lock_shadow_rotation_with_main_turret: true
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 1
maxAttackRange: 290
shootDelay: 6
turretRotateWithBody: true


[turret_1]
x: 17
y: 7
image: 炮.png
attachedTo: 3
idleDir: 10

warmup: 0
projectile: 2
turnSpeed: 3.0
limitingAngle: 30
turnSpeedAcceleration: 2

shoot_sound: ROOT:/余辉军团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.3
shoot_flame: NONE
shoot_light: #FFEECCCC
canShoot: true

size: 36
recoilOffset: -4
delay: 70
canAttackFlyingUnits: false
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹2
altProjectileCondition: if self.globalTeamTags(includes='裂解炮1')

[turret_2]
x: -17
y: 7
image: 枪.png
attachedTo: 3
idleDir: -10

warmup: 0
projectile: 3
turnSpeed: 3.0
limitingAngle: 30
turnSpeedAcceleration: 2

shoot_sound: ROOT:/余辉军团/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.2
shoot_light: #FF4DD3F7
canShoot: true
size: 33

recoilOffset: -1
delay: 4
canAttackFlyingUnits: false
canAttackCondition: if self.resource.xk < 1


[turret_3]
x: 0
y: 0
image: 身体.png
turnSpeed: 1.75
turnSpeedAcceleration: 0.1

canShoot: false
canAttackCondition: if self.resource.xk < 1


[turret_4]
x: 17
y: -8
attachedTo: 3
slave: true
projectile: 1

turnSpeed: 1
turnSpeedAcceleration: 0.1
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FFEECCCC

canShoot: true
size: 14
shoot_flame: CUSTOM:烟雾
energyUsage: 1
invisible: true

canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='反物质1')


[turret_5]
x: -17
y: -8
attachedTo: 3
slave: true
projectile: 1

turnSpeed: 1
turnSpeedAcceleration: 0.1
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FFEECCCC

canShoot: true
size: 14
shoot_flame: CUSTOM:烟雾
energyUsage: 1
invisible: true

canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='反物质1')
[turret_炮台1]
x: 17
y: -8
attachedTo: 3
slave: true
turnSpeed: 1

turnSpeedAcceleration: 0.1
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FFEECCCC
canShoot: true

size: 14
shoot_flame: CUSTOM:烟雾
energyUsage: 4
delay: 180
invisible: true

canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='反物质1')
projectile: 炮弹1


[turret_炮台2]
x: -17
y: -8
attachedTo: 3
slave: true
turnSpeed: 1

turnSpeedAcceleration: 0.1
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FFEECCCC
canShoot: true

size: 14
shoot_flame: CUSTOM:烟雾
energyUsage: 4
delay: 180
warmup: 20

invisible: true
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='反物质1')
projectile: 炮弹1

[projectile_1]
@copyFromSection: template_爆炸
life: 420
speed: 3
targetSpeed: 9
drawSize: 0.8
lightSize: 1
lightColor: #FF00B3FF
trailEffect: true
largeHitEffect: true
directDamage: 30
image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:波雷爆炸,CUSTOM:闪光
wobbleAmplitude: 5
#摆动幅
wobbleFrequency: 150

#摆动频率
turnSpeed: 20
#应该是转弯速度
#调太小可能打不中
#你看NM呢눈_눈

#눈      눈
#     —
mutator30_ifUnitWithTags: 飞机
mutator30_directDamageMultiplier: 2
mutator30_areaDamageMultiplier: 2

[projectile_2]
@copyFromSection: template_能源
areaDamage: 100
areaRadius: 35
life: 180
speed: 10
targetSpeed: 10
trailEffect: false
image: ROOT:/余辉军团/单位特效/炮弹.png
explodeEffect: CUSTOM:爆炸,CUSTOM:弹坑,CUSTOM:水波,CUSTOM:烟雾3*3,CUSTOM:闪光
drawSize: 0.55
lightSize: 1
lightColor: #FF00B3FF
areaRadiusFromEdge: true


[projectile_3]
@copyFromSection: template_能源
directDamage: 12
life: 710
image: HK收割者炮弹.png
drawSize: 0.5

speed: 9
targetSpeed: 9
explodeEffect: CUSTOM:火花
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[projectile_炮弹1]
@copyFromSection: template_能源
life: 420
speed: 5
targetSpeed: 8
largeHitEffect: true
drawSize: 0.8
trailEffect: true
areaDamage: 240
areaRadius: 55
image: ROOT:/余辉军团/单位特效/导弹.png
explodeEffect: CUSTOM:爆炸a,CUSTOM:电球,CUSTOM:闪光a,CUSTOM:聚变a,CUSTOM:冲击波aaa,CUSTOM:粒子a*10
explodeEffectOnShield: CUSTOM:爆炸a,CUSTOM:闪光a,CUSTOM:聚变a,CUSTOM:冲击波aaa,CUSTOM:粒子a*10,CUSTOM:电球
areaRadiusFromEdge: true
lightSize: 1
lightColor: #FF00B3FF
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
mutator30_ifUnitWithTags: 飞机
mutator30_directDamageMultiplier: 2
mutator30_areaDamageMultiplier: 2
[projectile_炮弹2]
@copyFromSection: template_动能
directDamage: 180
life: 300
lightSize: 1
largeHitEffect: true

speed: 8
trailEffect: CUSTOM:尾巴
drawSize: 0.7
explodeEffectOnShield: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:穿透
explodeEffect: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:穿透
image: ROOT:/余辉军团/单位特效/子弹2.png
trailEffectRate: 2


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2


[effect_波雷爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.8
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg

alpha: 2


[effect_烟雾]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.25
scaleTo: 1.25
alpha: 0.65
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #FF39FFFF
fadeInTime: 2
scaleFrom: 2
scaleTo: 2
drawUnderUnits: false

atmospheric: false


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1
scaleTo: 1
createWhenOverLiquid: false
createWhenOverLand: true


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.68

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟雾3]
priority: critical
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true

attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 1
scaleTo: 2.5

alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true

hSpeed: 0.2
hOffsetRandom: 0.15
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15

xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false


[effect_水波]
priority: critical
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.35
alpha: 1
drawUnderUnits: true
atmospheric: true

createWhenOverLiquid: true
createWhenOverLand: false
#——————————
[effect_粒子a]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false
#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子1.png
scaleFrom: 0.08
scaleTo: 0.27
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2
ySpeedRelativeRandom: 2
#atmospheric: true
[effect_聚变a]
priority: critical
image: ROOT:/余辉军团/单位特效/火光.png
life: 45
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 0.45
drawUnderUnits: false
atmospheric: false
alwayStartDirAtZero: true
[effect_闪光a]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFE56BFF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
[effect_电球]
priority: critical
attachedToUnit: false
scaleFrom: 0.68
scaleTo: 0.68
image: ROOT:/余辉军团/单位特效/电球.png
total_frames: 5
animateFrameStart: 0
animateFrameEnd: 4
animateFramePingPong: true
animateFrameSpeed: 0.2
life: 300
alwayStartDirAtZero: true
alpha: 0.4
[effect_爆炸a]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.28
scaleTo: 0.48
image: ROOT:/余辉军团/单位特效/核弹.png
total_frames: 21
animateFrameStart: 0
animateFrameEnd: 21
animateFramePingPong: false
animateFrameSpeed: 0.27
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_冲击波aaa]
image: ROOT:/余辉军团/单位特效/冲击波1.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.8
alpha: 0.8
drawUnderUnits: false
atmospheric: false
#——————
[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/粗子弹1.png
life: 18
fadeOut: true
attachedToUnit: false
#color:#FFFFFF3D
fadeInTime: 0.1
scaleFrom: 0.15
scaleTo: 0.15
alpha: 0.6
drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: false


[effect_闪光b]
priority: low
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFFFF3D
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false
atmospheric: false


[effect_爆炸b]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 1
image: ROOT:/余辉军团/单位特效/自制1.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_穿透]
priority: high
image: ROOT:/余辉军团/单位特效/子弹2.png
life: 35
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.6
scaleTo: 0.2
alpha: 1
drawUnderUnits: false
ySpeedRelative: 4.5
atmospheric: false




[leg_1]
x: -14
y: 7
attach_x: -5
attach_y: 4
moveSpeed: 2.8

moveWarmUp: 0.1s
hidden: if self.hasParent()
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25

image_leg: ROOT:/余辉军团/单位特效/腿.png
image_foot: ROOT:/余辉军团/单位特效/脚.png
#draw_foot_on_top: true
dust_effect: false
holdDisMin: 5

holdDisMax: 20
estimatingPositionMultiplier: 0.8


[leg_2]
x: 14
y: 7
attach_x: 5
attach_y: 4
copyFrom: 1

hidden: if self.hasParent()

[movement]
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.07
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage:0
movementType: LAND
moveSpeed: 1
maxTurnSpeed: 4
turnAcceleration: 0.5



