


[core]
name: 游侠机器人
displayDescription: 【阶级t2】【机械单位】【地面单位】【无人单位】【重型掩体】\n-【远程扫雷器】战术定位:步兵辅助型机器人，单位体积:2\n-武器配置：▲反坦克导弹发射器X2 只能对地，爆炸伤害。\n-一种结构简单，灵活机动的量产型战斗机器人。\n-那些运气不错的创世纪步兵班通常都会配有一部游侠机器人。\n-游侠机器人配有重型合金盾牌能有效保护周围的步兵，\n-同时用两门反坦克导弹发射器也能应付难缠的装甲目标。\n-当然他们的功能不仅只有这些，\n-在运输弹药，保护伤员，扫雷排障，哪怕是休闲娱乐方面，\n-游侠机器人都为创世纪步兵立下过汗马功劳，\n-在有些步兵班中，游侠机器人甚至被陆战队们当做兄弟。
copyFrom:ROOT:/通用特效/单位防护.ini
price: 750
maxHp: 1000
techLevel: 1
buildSpeed: 8s
radius: 17
isBio: false
softCollisionOnAll: 6
unitsSpawnedOnDeath: 损毁*1
tags: 地面,重型掩体,扫雷,主动扫雷,无人单位,驻扎要塞
transportSlotsNeeded: 2


[hiddenAction_掩体1取消]
autoTrigger:if self.hasParent and self.tags(includes= '重型掩体')
isVisible:false
temporarilyRemoveTags:重型掩体
[hiddenAction_掩体1生成]
autoTrigger:if not self.hasParent and not self.tags(includes= '重型掩体')
isVisible:false
temporarilyAddTags:重型掩体


[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image: 机体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true
image_shadow: NONE
shadowOffsetX: 2
shadowOffsetY: 2
lock_body_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
maxAttackRange: 280
#aimOffsetSpread: -0.01
turretRotateWithBody: false
shootDelay: 120
[turret_扫雷]
x: 8
y: 3
projectile: 3
turnSpeedAcceleration: 1.0
shoot_sound: plasma_fire
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFEECCCC
canShoot: true
canAttackCondition: if self.resource.xk < 1 and not self.hasParent
delay:75
slave: true
size:16
canOnlyAttackUnitsWithTags:地雷
attachedTo: 3
invisible: true

[turret_1]
x: -8
y: 8
attachedTo: 3
invisible: true
projectile: 1
shoot_sound: missile_fire
shoot_sound_vol: 0.55
shoot_light: #FFFFEB88
shoot_flame: CUSTOM:烟雾*3,large
canShoot: true
canAttackCondition: if self.resource.xk < 1
slave: true
size:14
canAttackUnderwaterUnits:false
delay:240
canAttackFlyingUnits: false
[turret_2]
x: -12
y: 8
copyFrom: 1
delay:210
warmup:30
[turret_3]
x: 0
y: 0
idleDir: 0
turnSpeed: 2.9
image: 机体.png
turnSpeedAcceleration: 0.3
canShoot: false
canAttackFlyingUnits: false
[turret_4]
x: 0
y: 0
#炮塔损坏
canShoot: false
image: 损坏.png
invisible: if self.maxHp * 0.36 < self.hp
attachedTo: 3
slave: true
canAttackFlyingUnits: false
[projectile_1]
@copyFromSection: template_爆炸
directDamage: 110
life: 6666
speed: 4
targetSpeed: 7
drawSize: 0.7
frame: 10
largeHitEffect: true
trailEffect:true
trailEffectRate: 1.1
[projectile_3]
directDamage: 999999
life: 10
instantReuseLast: true
beamImage: SHARED:beam3.png
beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true
color:  #FFFFFFFF
lightColor: #FFFFFFFF
lightSize: 0.1
largeHitEffect: true
mutator969_ifUnitWithTags: 地雷
mutator969_addResourcesDirectHit:setFlag=1
[effect_烟雾]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.1
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.3
yOffsetRelative: 0.4
ySpeedRelative: 0.3
atmospheric: true

[leg_1]
x: -8
y: 0
attach_x: -3
attach_y: 0
moveSpeed: 2.8
moveWarmUp: 0.1s
hidden: if self.hasParent()
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25
image_leg: ROOT:/创世纪军事集团/单位特效/腿.png
image_foot: ROOT:/创世纪军事集团/单位特效/脚.png
#draw_foot_on_top: true
dust_effect: false
holdDisMin: 5
holdDisMax: 20
estimatingPositionMultiplier: 0.8


[leg_2]
x: 8
y: 0
attach_x: 3
attach_y: 0
copyFrom: 1
hidden: if self.hasParent()

[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0
maxTurnSpeed: 3.5
turnAcceleration: 0.5
moveSlidingMode : false
moveIgnoringBody: false


