
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_2]
displayName: 2
displayNameShort: 2
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_3]
displayName: 3
displayNameShort: 3
displayColor: #FF9D00FF
priority: 1
hidden: true
[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}
[core]
name: 支援型载具站t3
displayText: поддержка типстанция машинt3
class: CustomUnitMetadata
price: 9600
maxHp: 15000
maxShield: 15000
shieldRenderRadius: 1
shieldRegen: 0.5
fogOfWarSightRange: 49
armour: 45
footprint: -4,-3,4,5
constructionFootprint: -4,-3,4,5
displayDescription:【Уровень t4】【Беспилотный юнит】【Здание】【Наземный юнит】\n-тактическое назначение: многофункциональный завод, \n-не может строиться на воде.вооружение:\n-▲Дрон-осаX6 по земле и воздуху взрывной урон.\n-Станция вспомогательной техники - это особое комплексное здание,, \n-основное применение - на полях боя низкой интенсивности, как опорный пункт фронта, \n-Не только производит базовые юниты на месте,, \n-но также имеет пусковую установку капсул и допускает расширение малого ангара, \n-Эти здания эффективно поддерживают передовые части,, являясь важной опорой имперских войск на фронте.
tags: 地面,无人单位,建筑,自动
energyMax: 4
energyRegen: 0.009
energyNeedsToRechargeToFull: true
energyStartingPercentage: 1
techLevel: 1
buildSpeed: 14s
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*10
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1)
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 78
isBio: false
isBuilding: true
nanoFactorySpeed:1
exit_x:0
exit_y: 60
exit_moveAwayAmount: 110
canBuild_31_name: setRally
canBuild_31_pos: 0.1
maxTransportingUnits: 6
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]

[hiddenAction_drone]
autoTrigger: if memory.灰机 < 6 and self.tags(includes= '自动') and self.queueSize < 0.5
alsoQueueAction: SDD
highPriorityQueue: false
[hiddenAction_SDD]
buildSpeed: 10s
requireConditional: if memory.灰机 < 6
addUnitsIntoTransport: SDD黄蜂无人机
highPriorityQueue: false


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1


[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)





[action_开启]
text: Включить автопроизводство
displayType: action
buildSpeed: 0s
pos: 0.1
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/修复.png
temporarilyAddTags:自动
#temporarilyRemoveTags:不自动
isVisible: if not self.tags(includes= '自动')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: Включить автопроизводствопалубный самолёт

[action_关闭]
text: Выключить автопроизводство
displayType: action
buildSpeed: 0s
pos: 0.11
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
temporarilyRemoveTags:自动
isVisible: if self.tags(includes= '自动')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: Отключить автопроизводство палубных юнитов, чтобы освободить место для других умений
iconImage: ROOT:/通用特效/修复1.png


[action_电池]
fireTurretXAtGround: 3
text: Запустить Щитовая батарея
price: energy=4,1500
displayType: action
buildSpeed: 0s
pos: 0.12
description: -Щитовая батареяСчитается тактическим оружием. После запуска, \n-в указанной точке появится одна Щитовая батарея, \n-восстанавливая щиты всех соседних союзныйсоюзных юнитов.
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
iconImage: ROOT:/余辉军团/单位特效/护盾电池.png




[action_电子战]
fireTurretXAtGround: 4
text: Запустить Капсула РЭБ
price: energy=4,2000,蓝晶=400
displayType: action
buildSpeed: 0s
pos: 0.12
description: -Капсула РЭБСчитается тактическим оружием. После запуска, \n-в указанной точке появится Башня электромагнитного подавления, \n-Башня электромагнитного подавленияВ момент приземления она обнулит в радиусе 415 , всех вражескийюнитов и зданий по энергии и боеприпасам, \n-одновременно все мины в этом радиусе будут уничтожены, \n-Все вражескиймеханические юниты в зоне помех не смогут переключаться или использовать умения, \n-и накладывает на все соседние вражескийвражеские юниты эффект захват прицелом.
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
iconImage: ROOT:/余辉军团/建筑特效/压制.png

[action_地雷]
fireTurretXAtGround: 5
text: Запустить Минный модуль
price: energy=4,6500
displayType: action
buildSpeed: 0s
pos: 0.12
description: -Минный модульСчитается тактическим оружием. После запуска, \n-Сбрасывает 12 шт. Магнитная мина.
displayRemainingStockpile: true
highPriorityQueue: true
onlyOneUnitAtATime: true
iconImage: ROOT:/余辉军团/建筑特效/地雷.png


[action_T2]
pos: 0.2
buildSpeed: 0s
addResources: setFlag=0,setFlag=2
text: Показать юниты T1
isVisible: if not self.hasFlag(id=2) and not self.hasFlag(id=0)
highPriorityQueue: true
[action_T2_back]
pos: 0.21
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=2
isVisible: if self.hasFlag(id=2)
text: Скрыть юниты T1
highPriorityQueue: true
[action_T3]
pos: 0.22
buildSpeed: 0s
addResources: setFlag=0,setFlag=3
text: Показать юниты T2
isVisible: if not self.hasFlag(id=3) and not self.hasFlag(id=0)
highPriorityQueue: true
[action_T3_back]
pos: 0.23
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=3
isVisible: if self.hasFlag(id=3)
text: Скрыть юниты T2
ai_isHighPriority: true
highPriorityQueue: true
[action_T4]
pos: 0.24
buildSpeed: 0s
addResources: setFlag=0,setFlag=4
text: Показать юниты T3
isVisible: if not self.hasFlag(id=4) and not self.hasFlag(id=0)
highPriorityQueue: true
ai_isHighPriority: true
[action_T4_back]
pos: 0.25
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=4
isVisible: if self.hasFlag(id=4)
text: Скрыть юниты T3
highPriorityQueue: true

[canBuild_T0]
name:筑基虫
pos: 0.5
isVisible: if self.hasFlag(id=2) or self.hasFlag(id=3) or self.hasFlag(id=4) or self.isControlledByAI()




[canBuild_T1]
name: SDAF灼光坦克,SDAF光矛,SDAF流星攻城炮,SDAF捍卫者,SDAF巨魔
pos: 1
isVisible: if self.hasFlag(id=2) or self.isControlledByAI


[canBuild_T2]
name: SDAF预兆,SDAF猎户座,SDAF冲击波
pos: 1.1
isVisible: if self.hasFlag(id=3) or self.isControlledByAI


[canBuild_T21]
name: SDAF咆哮者
pos: 1.2
isVisible: if self.hasFlag(id=3) or self.isControlledByAI
isLocked: if not self.globalTeamTags(includes='泽塔诺亚2')
isLockedMessage: Требуется база чертежей Зетаноя 2

[canBuild_T3]
name: 涤罪者,回声突击战车,蜂甲先锋
pos: 1.3
isVisible: if self.hasFlag(id=4) or self.isControlledByAI


[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
yOffsetRelative:6
xOffsetRelative:6
onlyWhileAlive:true
isVisible:true
alpha:0.6

[decal_光]
image: ROOT:/余辉军团/建筑特效/小重工光.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true

#isVisible: if self.maxHp * 0.36< self.hp
[decal_遮盖]
image: 主体.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
teamColors: true
[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true

[decal_光1]
image: ROOT:/余辉军团/建筑特效/小重工光1.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible: if self.maxHp * 0.36< self.hp
#alpha:0.6



[decal_转子]
image: ROOT:/余辉军团/建筑特效/小重工转子.png
total_frames: 3
frame: (self.customTimer * 15) % 3
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-0.5
yOffsetAbsolute:-31
isVisible:true
onlyWhileAlive:true
layer: onTop

[decal_光线]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp

alpha:0.8

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
#isVisible:if self.shield>self.maxShield*0.03
yOffsetRelative:0
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1



[graphics]
total_frames: 1
image: 主体.png
image_back: ROOT:/余辉军团/建筑特效/小重工地板.png
image_wreak:ROOT:/余辉军团/建筑特效/小重工死亡.png
image_shadow: NONE
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
maxAttackRange: 99999
turretTurnSpeed: 50
turretMultiTargeting: true

[turret_1]
x: -50
y: 20
projectile: 233
delay: 0s
canAttackMaxAngle: 181
canOnlyAttackUnitsWithoutTags:高空
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true
limitingRange: 900
unloadUpToXUnitsAndGiveAttackOrder: 1
warmup:1.5s
[turret_2]
x: 50
y: 20
copyFrom: 1

[turret_3]
canShoot: false
x: 0
y: 100
idleDir: 0
invisible: true
shoot_sound: nuke_launch
shoot_sound_vol: 0.6
shoot_light: #FFEECCCC
projectile: 1
shoot_flame: CUSTOM:水雾y*5,CUSTOM:冲击波,CUSTOM:闪光
size: 0
turnSpeed: 40
[turret_4]
x: 0
y: 100
copyFrom: 3
projectile: 3

[turret_5]
x: 0
y: 100
copyFrom: 3
projectile: 5
[turret_6]
x: 0
y: 0
projectile: 233
delay: 999s
canAttackMaxAngle: 181
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true
warmup:9999s



[projectile_1]
directDamage: 0
life: 220
speed: 0.1
targetSpeed: 8
targetSpeedAcceleration: 0.02
ballistic: true
ballistic_delaymove_height: 1500
ballistic_height: 1600
image: ROOT:/余辉军团/建筑特效/小重工仓.png
drawSize: 0.9
targetGround: true
alwaysVisibleInFog: true
areaRadius: 0
deflectionPower: -1
shouldRevealFog: true
nukeWeapon: true
trailEffect: CUSTOM:火1,CUSTOM:火2
trailEffectRate: 0.8
explodeOnEndOfLife: true
explodeEffect: NONE
tags:天上战术
spawnProjectilesOnEndOfLife: 2
[projectile_2]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true
instant: true
spawnUnit: 通用轨道轰炸(addResources=2:1,offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none


[projectile_3]
@copyFromSection:projectile_1
spawnProjectilesOnEndOfLife: 4
[projectile_4]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true
instant: true
spawnUnit: 通用轨道轰炸(addResources=3:1,offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none
[projectile_5]
@copyFromSection:projectile_1
spawnProjectilesOnEndOfLife: 6
[projectile_6]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true
instant: true
spawnUnit: 通用轨道轰炸(addResources=3:10,offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none

[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0

[arm_1]
x: 0
y: 81
image_end: ROOT:/余辉军团/建筑特效/小重工仓.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.energy<3.5


[attachment_drone1]
x: -50
y: 20
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false
idleDir:-90
addTransportedUnits: true
#setDrawLayerOnBottom:
canAttack: false
lockRotation: true
#height:1
[attachment_drone2]
@copyFromSection: attachment_drone1
x: -50
y: 20

[attachment_drone3]
@copyFromSection: attachment_drone1
x: -50
y: 20

[attachment_drone4]
@copyFromSection: attachment_drone1
x: 50
y: 20
idleDir:90
[attachment_drone5]
@copyFromSection: attachment_drone1
x: 50
y: 20
idleDir:90
[attachment_drone6]
@copyFromSection: attachment_drone1
x: 50
y: 20
idleDir:90

#——————————发射火光
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.9
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: false
yOffsetRelative:-23
[effect_闪光]
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 7
scaleTo: 0
drawUnderUnits: false
atmospheric: false
yOffsetRelative:-23
[effect_水雾y]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 3
scaleTo: 4
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.35
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
xOffsetRelativeRandom:5
yOffsetRelativeRandom:5
yOffsetRelative:-23
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 60
yOffsetRelativeRandom: 100
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:70
yOffsetRelativeRandom:120
delayedStartTimerRandom:30
#——————————起飞火光
[effect_火1]
life: 20
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.3
image: SHARED:light_50.png
alpha: 0.5
color: #FF00B3FF
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -27
drawUnderUnits: false
[effect_火2]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.18
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
ySpeedRelative: -0.7
yOffsetRelative	: -27
drawUnderUnits: false

[ai]
buildPriority: 0.08
ai_upgradePriority: 0.07
maxEachBase: 3
maxGlobal: 5
noneInBaseExtraPriority:0.15
upgradedFrom: 支援型载具站空投
