


[core]
name: 秃鹰运输机
class: CustomUnitMetadata
displayDescription:【阶级t3】【机械单位】【空中单位】\n-战术定位:大型运输直升机，载员数量：9，无武装。\n-在战争初期，创世纪为了快速大量投送兵力而改良的一款双旋翼运输直升机，\n-得益于先进的材料技术与强大的引擎提供的运载力，秃鹰能够运载数台主战坦克快速进入战场，\n-或是直接将一只标准步兵排增援快速送上前线，\n-唯一美中不足的是，为了最大化运载能力，秃鹰没有安排任何自卫火力，\n-因此，在运用中需要友军的密切保护。
price: 1550
maxHp: 3300
fogOfWarSightRange: 19
techLevel: 1
buildSpeed: 10s
availableInDemo: true
armour: 10
radius: 58
effectOnDeathGroundCollision: CUSTOM:炸炸
displayRadius: 58
softCollisionOnAll: 24
copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
maxTransportingUnits: 9
transportUnitsKillOnDeath: true
tags: 飞机,低空


[decal_损坏]
image: 死亡.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true

[hiddenAction_地上]
autoTrigger: if not self.tags(includes= '地面') and not self.flying
isVisible: false
temporarilyAddTags:地面
temporarilyRemoveTags:飞机
[hiddenAction_天上]
autoTrigger: if self.tags(includes= '地面') and self.flying
isVisible: false
temporarilyAddTags:飞机
temporarilyRemoveTags:地面

[attachment_1]
x: 0
y: 0
canAttack:false
addTransportedUnits: true
hidden: true
setDrawLayerOnBottom:true
[attachment_2]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_3]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_4]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_5]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_6]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_7]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_8]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_9]
@copyFromSection: attachment_1
x: 0
y: 0




[graphics]
total_frames: 1
image: 运输.png
image_wreak: 损坏.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 0

maxAttackRange: 0
shootDelay: 0




#————————————————炸炸
[effect_炸炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
[arm_1]
x: -79
y: 25
image_end: 螺旋桨.png
drawOverBody: true
spinRate: 60
[arm_2]
x: 79
y: 25
image_end: 螺旋桨.png
drawOverBody: true
spinRate: 60
[movement]
movementType: AIR
targetHeight: 70
targetHeightDrift: 2
moveSpeed: 1.2
moveAccelerationSpeed: 0.02
startingHeightOffset: 1000
moveDecelerationSpeed: 0.04
maxTurnSpeed: 1
turnAcceleration: 0.2
slowDeathFall: true
moveSlidingMode : false

moveIgnoringBody: true
moveSlidingDir: 120
landOnGround: onlyIdle


