


[core]
name: 无畏战士
displayText: Бесстрашный боец
class: CustomUnitMetadata
displayDescription: 【Уровень t3】【Биологический юнит】【Наземный юнит】Тактическое назначение: универсальная пехота，размер юнита:1\n-вооружение：▲榴弹пусковая установкаX1 только по земле，взрывной урон，\n-Бесстрашный боец将пехота所может达достигнутый防护扩展до了极限，\n-ониоснащённый了重 экзоскелет和防爆盾牌а также反танк榴弹пусковая установка，\n-消灭常规бронетехника不在话下。

price: 400
isUnrepairableUnit:true
maxHp: 700
mass: 700
techLevel: 1
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
buildSpeed: 5s
radius: 12
softCollisionOnAll: 0
isBio: true
explodeOnDeath: false

hideScorchMark: true
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
tags: 步兵,地面,驻扎要塞,1格
armour: 6
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md,ROOT:/通用特效/扎针.md

#———科技—————
[action_轻型掩体]
text: лёгкое укрытие
isVisible: if self.globalTeamTags(includes='外骨骼')
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/轻型掩体.png
description: 一处лёгкое укрытие，может为рядомпехота140范围内的биологический юнитобеспечиваетлёгкое прикрытие。\n-лёгкое прикрытиеможет为биологический юнит减免50%的伤害，\n-но，укрытие无法减免部分скорострельный，激光，Огонь，电击，中性，самоподрыв，ближний бой，衰解等其он无视укрытие的оружие。
[action_加掩体]
autoTrigger: if self.globalTeamTags(includes='外骨骼')and not self.tags(includes= '轻型掩体')
isVisible:false
temporarilyAddTags:轻型掩体
[hiddenAction_外骨骼生效1]
autoTrigger: if self.globalTeamTags(includes='外骨骼') and not self.tags(includes= '外骨骼保险1')
setUnitStats: moveSpeed= ${movement.moveSpeed * 1.3},maxHp= ${core.maxHp*1.2},hp= ${core.maxHp*1.2}, maxTurnSpeed = ${movement.maxTurnSpeed* 1.65}
temporarilyAddTags:外骨骼保险1
[action_弹幕架1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕1.png
text: Реактивная установка1
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架1')
#———展开————
[action_举枪]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan= 0,withInRange=365, incompleteBuildings= true) and not self.tags(includes= '举枪')
isVisible:false
temporarilyAddTags:举枪
playAnimation:部署
[action_收枪]
autoTrigger: if numberOfUnitsInEnemyTeam(lessThan= 1,withInRange=365, incompleteBuildings= true) and self.tags(includes= '举枪')
isVisible:false
stopLastAnimation: true

alsoQueueAction: b
[action_b]
displayType: action
price: 0
playAnimation: 部署1
buildSpeed: 0.51s
isVisible: false
temporarilyRemoveTags:举枪
highPriorityQueue: true
whenBuilding_cannotMove: false

[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999

[graphics]
image: NO.png
image_wreak: 无畏战士死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 2

shadowOffsetY: 2
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
imageScale: 0.85


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 18

turretTurnSpeed: 3
maxAttackRange: 275
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_1]
#绑定
x: 0
y: 0
canShoot: false
canAttackFlyingUnits: false

[turret_2]
#主炮
x: 6
y: 4
invisible: true
attachedTo: 1

slave: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/榴弹音效.ogg
shoot_sound_vol: 0.5
projectile: 1
delay: 40

shoot_flame: small,CUSTOM:弹壳
canAttackCondition:if self.tags(includes= '举枪') or self.hasParent
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='弹幕架1')
canAttackFlyingUnits: false

[projectile_炮弹]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 2*3


[projectile_1]
@copyFromSection: template_爆炸
#主武器炮弹
directDamage: 80
life: 420
speed: 2.5

targetSpeed: 6
deflectionPower: -1
image: ROOT:/创世纪军事集团/单位特效/榴弹.png
drawSize: 0.7
initialUnguidedSpeedHeight: 1

gravity: 0.4
largeHitEffect: true

[projectile_2]
@copyFromSection: template_爆炸
#主武器炮弹
directDamage: 50
life: 420
speed: 3.5
targetSpeed: 6
deflectionPower: -1
image: ROOT:/创世纪军事集团/单位特效/榴弹.png
drawSize: 0.7
initialUnguidedSpeedHeight: 1
speedSpread:1
gravity: 0.4
largeHitEffect: true
#死亡特效——————


[effect_飘血]
life: 150
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: true
liveAfterAttachedDies: true
physics: true

physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.7
ySpeedRelativeRandom: 0.6
hSpeed: 1


[effect_飘血2]
life: 150
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

scaleFrom: 0.5
scaleTo: 0.5
drawUnderUnits: true
liveAfterAttachedDies: true
physics: true

physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1
ySpeedRelativeRandom: 1
hSpeed: 1

dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 150
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 3
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡.ogg,ROOT:/创世纪军事集团/步兵特效/死亡3.ogg,ROOT:/创世纪军事集团/步兵特效/死亡4.ogg,ROOT:/创世纪军事集团/步兵特效/死亡5.ogg
#武器开火特效———————




[effect_弹壳]
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 120
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.4
scaleTo: 0.4
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 0.6
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.25
yOffsetRelative: -10
xOffsetRelative: 2

hSpeed: 2
dirSpeedRandom: 50

[arm_1]
#左后臂
x: -6
y: -1
image_end: 手.png
image_end_teamColors: true

drawDirOffset: -20
drawOverBody: false
image_end_shadow: SHADOW:手.png


[arm_2]
#右后臂
x: 5
y: -2
image_end: 手.png
image_end_teamColors: true

drawOverBody: false
drawDirOffset: 45
image_end_shadow: SHADOW:手.png


[arm_3]
#右前臂
x: 9
y: 2
image_end: 手.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -45
image_end_shadow: SHADOW:手.png


[arm_4]
#身体
x: 0
y: 0
image_end: 躯干.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:躯干.png


[arm_5]
#左手盾
x: -7
y: 6
image_end: 盾.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: 45
image_end_shadow: SHADOW:盾.png


[arm_6]
#枪
x: 6
y: 7
image_end: 枪.png
image_end_teamColors: true

drawOverBody: true
drawDirOffset: -53


[arm_7]
#脑袋
x: 0
y: 0
image_end: 头.png
image_end_teamColors: true

drawOverBody: true



[leg_1]
x: -3
y: 2
attach_x: -1
attach_y: -1
moveSpeed: 2.8
moveWarmUp: 0.5s
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25
targetHeightRelative: false
image_leg: 腿.png
dust_effect: false
holdDisMin: 1
holdDisMax: 6
hardLimit: 7
estimatingPositionMultiplier: 0.65
hidden: if self.hasParent() or self.isOverLiquid
[leg_2]
x: 3
y: 2
attach_x: 1
attach_y: -1
copyFrom: 1

[animation_部署1]
arm1_0.4s: {x:0, y:0}
arm2_0.4s: {x:0, y:0}
arm3_0.4s: {x:0, y:0}
arm4_0.4s: {x:0, y:0}
arm5_0.4s: {x:0, y:0}
arm6_0.4s: {x:0, y:0}
[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm1_0.2s: {x:2, y:3, dir:20}
arm2_0.2s: {x:0, y:-1, dir:0}
arm3_0.2s: {x:0, y:-1, dir:10}

arm4_0.2s: {x:0, y:0, dir:10}
arm5_0.2s: {x:5, y:1, dir:10}
arm6_0.2s: {x:0, y:-1, dir:53}

arm1_9999s: {x:2, y:3, dir:20}
arm2_9999s: {x:0, y:-1, dir:0}
arm3_9999s: {x:0, y:-1, dir:10}

arm4_9999s: {x:0, y:0, dir:10}
arm5_9999s: {x:5, y:1, dir:10}
arm6_9999s: {x:0, y:-1, dir:53}

[movement]
movementType: LAND
moveSpeed: 0.55
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 3

targetHeight: 2
reverseSpeedPercentage: 0
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false


