
[core]
name: 大力神无人机
displayText: Дрон «Геркулес»
displayDescription: -😱
price: 0
showInEditor: false
maxHp: 9000
techLevel: 1
buildSpeed: 0
radius: 35
displayRadius: 35
isBio: false
transportSlotsNeeded: 200
tags: 飞机,高空,伴生单位,无人单位
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 20
armour: 10
fogOfWarSightRange: 26
canOnlyBeAttackedByUnitsWithTags:反高空
effectOnDeath:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
effectOnDeathGroundCollision:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
#canNotBeGivenOrdersByPlayer: if self.energy<1
energyMax: 5
energyRegen: 0
energyStartingPercentage:1
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_zz1]
autoTrigger:if not self.isInMap
addResources: hp= -999999
[action_3b]
text: 释放空投
iconImage: ROOT:/通用特效/无人机.png
price: energy=5
canPlayerCancel: false
playSoundAtUnit: ROOT:/创世纪军事集团/单位特效/深水炸弹.ogg
displayType: action
description:немедленно原地释放空投进行десант
buildSpeed: 0s
displayRemainingStockpile: false
highPriorityQueue: true
fireTurretXAtGround_withOffset: 0,0
fireTurretXAtGround: 1
isLocked: if self.isOverLiquid
isLockedMessage:не может在这里释放空投。
[action_高空]
text: высотныйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的истребитель和боевой корабль。\n-在此高度下，только有地面和空中специальный的против высотныхюнит，а такжевысотныйюнит才может攻击до该юнит，\n-одновременно，大部分высотныйюнитможет互相攻击，иможет攻击обычныйвоздушный юнит，\n-только有специальный的высотныйюнит才можетпо земле攻击。
[action_bkm]
autoTrigger: if not self.tags(includes= '保险') 
isVisible: false
playAnimation: attack
temporarilyAddTags:保险
[hiddenAction_回家]
autoTrigger: if self.energy<1
addWaypoint_target_nearestUnit_tagged: 泰坦
addWaypoint_type: move
addWaypoint_target_nearestUnit_team: own
clearAllWaypoints: true
[hiddenAction_紫砂]
autoTrigger: if self.energy<1 and self.hasUnitInTeam(withTag='泰坦', withinRange=250) and self.resource.零件<200
deleteSelf: true
addResources: 零件=15
[hiddenAction_紫砂x]
autoTrigger: if self.energy<1 and self.hasUnitInTeam(withTag='泰坦', withinRange=250) and self.resource.零件>=200
deleteSelf: true
[hiddenAction_紫砂1]
autoTrigger: if self.noUnitInTeam(withTag='泰坦') and self.energy<1
addResources:  hp=-99999
[graphics]
total_frames: 1
image: NO.png
image_wreak: 死了.png
image_turret: NONE
teamColorsOnTurret: true
image_shadow: NONE
#turretImageScale: 0.85
movementEffect: CUSTOM:火1,CUSTOM:火2
movementEffectRate: 0.5
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:true
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 400
shootDelay: 0
[turret_1]
x: 0
y: -6
shoot_flame: NONE
shoot_sound: ROOT:/创世纪军事集团/单位特效/深水炸弹.ogg
shoot_sound_vol: 1.4
delay: 1
size:0
projectile: 1
energyUsage:5
canAttackCondition:if not self.isOverLiquid
canOnlyAttackUnitsWithoutTags:海上
[projectile_1]
life: 55
speed: 1
targetSpeed: 2
areaDamage: 0
explodeOnEndOfLife:true
spawnUnit: 狩猎者(offsetHeight=0,offsetDir=0)
areaRadius: 0
drawSize: 1
explodeEffect: CUSTOM:巨大冲击波,CUSTOM:左前,CUSTOM:右前
explodeEffectOnShield:CUSTOM:巨大冲击波,CUSTOM:左前,CUSTOM:右前
targetGround: true
areaRadiusFromEdge: true
image:空投.png
trueGravity: 0.1
disableLeadTargeting: true
[arm_1]
x: 0
y: -6
image_end: 空投.png
drawOverBody: true
image_end_shadow: SHADOW:空投.png
image_end_teamColors: true
hidden:if self.energy<1
[arm_2]
x: 0
y: 25
image_end: 尾翼1.png
drawOverBody: true
image_end_shadow: SHADOW:尾翼1.png
image_end_teamColors: true
[arm_3]
x: 15
y: 0
image_end: 左翼.png
drawOverBody: true
image_end_shadow: SHADOW:左翼.png
image_end_teamColors: true
[arm_4]
x: -15
y: 0
image_end: 右翼.png
drawOverBody: true
image_end_shadow: SHADOW:右翼.png
image_end_teamColors: true
[arm_5]
x: 0
y: 0
image_end: 机体1.png
drawOverBody: true
image_end_shadow: SHADOW:机体1.png
image_end_teamColors: true
[arm_6]
x: 0
y: 11
image_end: 风扇.png
drawOverBody: true
spinRate: 25
image_end_teamColors: true


[effect_右前]
priority: critical
image: 空投碎片1.png
spawnChance: 1
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: 0.3
ySpeedRelative: 1
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.2
yOffsetRelative: 5
xOffsetRelative: 0
hSpeed: 1.8
dirSpeed:2
dirSpeedRandom:1
dirOffset:360
[effect_左前]
priority: critical
image: 空投碎片.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: 0.3
ySpeedRelative: -1
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.2
yOffsetRelative: -5
xOffsetRelative: 0
hSpeed: 1.8
dirSpeed:2
dirSpeedRandom:1
dirOffset:360
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/巨大爆炸.ogg
createWhenOffscreen: true
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #BBBBFFEE
xOffsetRelative	: 32
ySpeedRelative: -4
yOffsetRelative	: -1.5
drawUnderUnits: false
[effect_火2]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #BBBBFFEE
xOffsetRelative	: -32
ySpeedRelative: -4
yOffsetRelative	: -1.5
drawUnderUnits: false
[animation_attack]

arm2_0s: {x:0, y:0,dir:0}
arm2_1s: {x:0, y:-25,dir:0}
arm2_99999s: {x:0, y:-25,dir:0}
arm3_0s: {x:0, y:0,dir:0}
arm3_1s: {x:-15, y:0,dir:0}
arm3_99999s: {x:-15, y:0,dir:0}
arm4_0s: {x:0, y:0,dir:0}
arm4_1s: {x:15, y:0,dir:0}
arm4_99999s: {x:15, y:0,dir:0}
[movement]
movementType: AIR
moveSpeed: 2.3
moveAccelerationSpeed: 0.09
moveDecelerationSpeed: 0.05
maxTurnSpeed: 3
turnAcceleration: 0.1
targetHeightDrift: 1

slowDeathFall: false
targetHeight: 140




