


[core]
name: 火龙卷
displayText: Огненный смерч
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md
price: 550
maxHp: 700
displayDescription: 【Уровень t3】【Биологический юнит】【Наземный юнит】Тактическое назначение:反生物пехота，размер юнита:1\n-▲огнемётX1 только по земле нейтральный урон пробивает укрытия \n-▲榴弹пусковая установкаX1 только по земле взрывной урон\n-为了防止反Генезис政府者а также僵尸的骚扰，\n-Генезиссполе боя上回收的Боевой мехобломки和废旧零вещь拼凑的半成品骨 为основа，\n-装配上轻 броня，огнемёт与自动榴弹пусковая установка后制成的简易мех，\n-в качествеотрядогневая мощь应用до清理感染区与镇压反政府вооружение的任务中，\n-在危急момент，онитакжеможет被используется для与余辉对抗。
techLevel: 1
buildSpeed: 5s
radius: 20
displayRadius: 20
tags: 地面,机甲,步兵
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
unitsSpawnedOnDeath: 损毁*1
isUnrepairableUnit:true
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3') 
[action_恐怖地雷2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖2.png
text: Мина «Кошмар»2
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷2') and not self.globalTeamTags(includes='恐怖地雷3')
[action_外骨骼]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/外骨骼.png
text: Технология экзоскелета
isActive: false
isVisible: if self.globalTeamTags(includes='外骨骼')
[hiddenAction_外骨骼生效]
autoTrigger: if self.globalTeamTags(includes='外骨骼') and not self.tags(includes= '外骨骼保险')
setUnitStats: moveSpeed= ${movement.moveSpeed * 1.3},maxHp= ${core.maxHp*1.2},hp= ${core.maxHp*1.2}, maxTurnSpeed = ${movement.maxTurnSpeed* 1.65}
temporarilyAddTags:外骨骼保险
[hiddenAction_外骨骼生效麻烦1]
autoTrigger: if self.globalTeamTags(includes='外骨骼')
setUnitStats:armour= ${core.armour+10}

[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999

[graphics]
image: NO.png
image_wreak: 火龙卷死亡.png
image_turret: 火龙卷身体.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
lock_body_rotation_with_main_turret: true
lock_shadow_rotation_with_main_turret: true
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 16

turretTurnSpeed: 3
maxAttackRange: 260
shootDelay: 2
aimOffsetSpread: -0.01
turretRotateWithBody: true


[turret_2]
x: 14
y: 3
image: 枪.png
attachedTo: 1
idleDir: 10

warmup: 0
turnSpeed: 3.0
turnSpeedAcceleration: 0.5
canShoot: true
projectile: 1

shoot_sound: ROOT:/通用特效/火焰.ogg
shoot_sound_vol: 0.1
shoot_flame: CUSTOM:烟雾
limitingAngle: 30
canAttackFlyingUnits: false
limitingRange: 250

[turret_3]
x: -14
y: 3
image: 炮.png
attachedTo: 1
idleDir: -10

warmup: 0
turnSpeed: 3.0
turnSpeedAcceleration: 0.5
canShoot: true
projectile: 2

delay: 60
canAttackFlyingUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/榴弹音效.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:枪口火焰

shoot_light: #FFEECCCC
size: 25
recoilOffset: -2.4
limitingAngle: 30


[turret_1]
x: 0
y: 0
image: 火龙卷身体.png
turnSpeed: 2.9
turnSpeedAcceleration: 0.3

canShoot: false


[projectile_1]
life: 5000
speed: 7
areaDamage: 20
areaRadius: 40
targetSpeed: 7

image: 爆炸.png
drawSize: 0.8
flameWeapon: true
targetGroundSpread: 25
targetGround: true

areaRadiusFromEdge: true
lightSize: 2
deflectionPower: -1
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_爆炸
directDamage: 80
life: 820
speed: 5
targetSpeed: 7

deflectionPower: -1
image: ROOT:/创世纪军事集团/单位特效/榴弹.png
drawSize: 0.8
initialUnguidedSpeedHeight: 1
largeHitEffect: true
explodeEffect: largeExplosion*1


[effect_烟雾]
#priority:high
frameIndex: 0
stripIndex: smoke_black
spawnChance: 0.3
createWhenZoomedOut: false

life: 90
fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #FFFFFF

fadeInTime: 2
scaleFrom: 0.3
scaleTo: 1
alpha: 5
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.2
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.4
ySpeedRelativeRandom: 0.4

atmospheric: true


[effect_爆炸]
priority: critical
image: ROOT:/通用特效/爆炸.png
life: 70
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.85
alpha: 1
drawUnderUnits: false

ySpeedRelative: 2
atmospheric: true
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13

animateFrameSpeed: 0.2


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 1.5
scaleTo: 1.5

[leg_1]
x: -8
y: 0
attach_x: -3
attach_y: 0
moveSpeed: 2.8

moveWarmUp: 0.1s
hidden: if self.hasParent()
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25

image_leg: ROOT:/创世纪军事集团/单位特效/腿.png
image_foot: ROOT:/创世纪军事集团/单位特效/脚.png
#draw_foot_on_top: true
dust_effect: false
holdDisMin: 5

holdDisMax: 20
estimatingPositionMultiplier: 0.8
[leg_2]
x: 8
y: 0
attach_x: 3
attach_y: 0
copyFrom: 1
hidden: if self.hasParent()

[movement]
moveSpeed: 1.2
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.07
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0
movementType: LAND
maxTurnSpeed: 7.0
turnAcceleration: 0.5

[ai]
useAsBuilder: true


