


[core]
name: 轻骑兵机甲1
displayText: 轻骑兵机甲
price: 2500
maxHp: 5500
displayDescription: -古人类战国时期，\n-每一个布恩芬德尔联盟官邸都会布置的警卫机甲，\n-轻骑兵配有一把电磁泵动式霰弹枪，\n-相比于当时其他花里胡哨的粒子和能量武器，\n-布恩芬德尔的老顽固们还是更相信这些传统的设计，\n-事实也证明了这确实是一个明智的选择。\n-太空浪人以几张火种舰船票为代价，\n-从布恩芬德尔的官僚手中收购了轻骑兵的蓝图，\n-这种工艺要求水平低，性能可靠，\n-威力强大的机甲被广泛用于二线作战。\n-只不过太空浪人实在无法忍受轻骑兵那抱残守缺的裂变能源，\n-只好将其改为了无内置反应堆的无线充电式作战单元，\n-至于为何不使用聚变堆，\n-是因为轻骑兵的内置硬件实在无法兼容这些先进的玩意。\n-只能对地，动能伤害，自动作战无法操作
techLevel: 1
fogOfWarSightRange: 18
buildSpeed: 5s
radius: 38
displayRadius: 38
armour: 20
showInEditor: false

copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 3
unitsSpawnedOnDeath: 损毁3*1
tags: 地面,轻骑兵,伴生单位
canNotBeGivenOrdersByPlayer: true

energyMax: 7
energyRegen: 0
energyNeedsToRechargeToFull: true
selfRegenRate: 0.2
borrowResourcesWhileAlive: zh=-12

[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[hiddenAction_强制脱离]
autoTrigger: if self.hasParent(withTag= '阿玛洛克')
disconnectFromParent: true


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[hiddenAction_1x]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=1000) and self.resource.xk < 1
addWaypoint_target_nearestUnit_tagged: 地面
addWaypoint_type: attack
addWaypoint_target_nearestUnit_team: enemy




[hiddenAction_21]
autoTrigger: if not self.hasUnitInTeam(withTag='阿玛洛克', withinRange=400) and self.resource.xk < 1
isVisible: false
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: 阿玛洛克
addWaypoint_target_nearestUnit_team: own

addWaypoint_maxTime: 1s
addWaypoint_type: move


[action_t1x]
autoTrigger: if self.noUnitInTeam(withTag='阿玛洛克', withinRange=400)
isVisible: false
addResources: zh=-1


[action_t1z]
autoTrigger: if self.resource(type= 'zh', lessThan= 0) and self.noUnitInTeam(withTag='阿玛洛克')
isVisible: false
addResources: hp=-99999


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", greaterThan= 0.5)
isVisible: false
alsoQueueAction: b


[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 500 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true

[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 400 | setFlag= 0)


[action_b]
convertTo: 轻骑兵机甲
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false

highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署


[action_换弹1]
autoTrigger: if self.energy(empty=true) and self.queueSize < 0.5
isVisible: false
alsoQueueAction: 换弹


[action_换弹]
#autoTrigger: if self.energy(empty=true) and self.queueSize < 0.5
isVisible: false
buildSpeed: 0.1s
alsoQueueAction: bx


[action_bx]
displayType: action
price: 0
buildSpeed: 4.2s
isVisible: false
highPriorityQueue: true

whenBuilding_cannotMove: false
whenBuilding_playAnimation: 换弹
addEnergy: 7


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯') or self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.resource.awz>-1
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 400
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_2]
x: 15
y: 94
invisible: true
shoot_sound: 枪.ogg
shoot_sound_vol: 1.4

shoot_light: #FFFFEB88
shoot_flame: CUSTOM:气浪*5,CUSTOM:粒子*8,CUSTOM:弹壳
projectile: 2
delay: 90
energyUsage: 1

canAttackCondition: if self.resource.xk < 1
onShoot_playAnimation: attack
attachedTo: 1
slave: true
limitingMinRange: 80


[turret_1]
x: 0
y: 0
canShoot: false
image: NO.png


[projectile_1]
life: 0
directDamage: 0
speed: 0
targetSpeed: 0
drawSize: 0

frame: 1
deflectionPower: -1


[projectile_2]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1

frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定*10


[projectile_锁定]
@copyFromSection: template_动能
targetGround: true
areaDamage: 250
areaRadius: 45
life: 120

targetGroundSpread: 30
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光
speed: 9
image: ROOT:/太空浪人/单位特效/中子弹.png
armourIgnoreAmount: 10
drawSize: 0.52
deflectionPower: -1
mutator3_ifUnitWithTags: 卧倒
mutator3_areaDamageMultiplier: 2
speedSpread: 1


[arm_1]
x: -13
y: 11
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: 0

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_2]
x: 10
y: -5
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:胳膊.png
drawDirOffset: 70


[arm_3]
x: -10
y: 40
image_end: 左手.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 45
image_end_shadow: SHADOW:左手.png


[arm_4]
x: 32
y: 6
image_end: 右手.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:左手.png
drawDirOffset: -25


[arm_5]
#左肩
x: 0
y: -4
image_end: 身体.png
image_end_teamColors: true

drawOverBody: true
image_end_shadow: SHADOW:身体.png
drawDirOffset: 15


[arm_6]
x: 16
y: 35
image_end: 枪1.png
image_end_teamColors: true
drawOverBody: true

#drawDirOffset: -65
hidden: if not self.isEnergyEmpty()


[arm_7]
x: 16
y: 35
image_end: 枪栓.png
image_end_teamColors: true
drawOverBody: true

#drawDirOffset: -65
hidden: if self.isEnergyEmpty()


[arm_8]
x: 16
y: 35
image_end: 枪.png
image_end_shadow: SHADOW:枪.png
image_end_teamColors: true

drawOverBody: true
hidden: if self.isEnergyEmpty()
drawDirOffset: 0


[arm_9]
#左肩
x: 0
y: -1
image_end: 头.png
image_end_teamColors: true

drawOverBody: true


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.4

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[leg_1]
x: -17
y: 9
attach_x: -7
attach_y: 7
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 17
y: 9
attach_x: 7
attach_y: 7
copyFrom: 1

image_leg: 腿.png
drawDirOffset: 10


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6

yOffsetRelative: 0.8
ySpeedRelative: 1.5
atmospheric: true


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[animation_attack]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm1_0.05s: {x:0, y:-3, dir:0}
arm7_0.05s: {x:0, y:-36, dir:0}

arm8_0.05s: {x:0, y:-12, dir:0}
arm3_0.05s: {x:0, y:-12, dir:3}
arm4_0.05s: {x:0, y:-12, dir:0}


[animation_换弹]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm1_0.3s: {x:-5, y:0, dir:5}

arm3_0.3s: {x:-5, y:7, dir:75}
arm6_0.3s: {x:0, y:0, dir:0}
arm1_0.6s: {x:-5, y:0, dir:0}
arm3_0.6s: {x:-5, y:0, dir:0}
arm6_0.6s: {x:0, y:0, dir:7}

arm1_0.9s: {x:-5, y:0, dir:5}
arm3_0.9s: {x:-5, y:7, dir:75}
arm6_0.9s: {x:0, y:0, dir:0}
arm1_1.2s: {x:-5, y:0, dir:0}
arm3_1.2s: {x:-5, y:0, dir:0}

arm6_1.2s: {x:0, y:0, dir:7}
arm1_1.5s: {x:-5, y:0, dir:5}
arm3_1.5s: {x:-5, y:7, dir:75}
arm6_1.5s: {x:0, y:0, dir:0}
arm1_1.8s: {x:-5, y:0, dir:0}

arm3_1.8s: {x:-5, y:0, dir:0}
arm6_1.8s: {x:0, y:0, dir:7}
arm1_2.1s: {x:-5, y:0, dir:5}
arm3_2.1s: {x:-5, y:7, dir:75}
arm6_2.1s: {x:0, y:0, dir:0}

arm1_2.4s: {x:-5, y:0, dir:0}
arm3_2.4s: {x:-5, y:0, dir:0}
arm6_2.4s: {x:0, y:0, dir:7}
arm1_2.7s: {x:-5, y:0, dir:5}
arm3_2.7s: {x:-5, y:7, dir:75}

arm6_2.7s: {x:0, y:0, dir:0}
arm1_3.0s: {x:-5, y:0, dir:0}
arm3_3.0s: {x:-5, y:0, dir:0}
arm6_3.0s: {x:0, y:0, dir:7}
arm1_3.3s: {x:-5, y:0, dir:5}

arm3_3.3s: {x:-5, y:7, dir:75}
arm6_3.3s: {x:0, y:0, dir:0}
arm1_3.6s: {x:-5, y:0, dir:0}
arm3_3.6s: {x:-5, y:0, dir:0}
arm6_3.6s: {x:0, y:0, dir:7}

arm1_3.9s: {x:-5, y:0, dir:5}
arm3_3.9s: {x:-5, y:7, dir:75}
arm6_3.9s: {x:0, y:0, dir:0}
arm1_4.2s: {x:-5, y:0, dir:0}
arm3_4.2s: {x:-5, y:0, dir:0}

arm6_4.2s: {x:0, y:0, dir:7}


[effect_弹壳]
priority: high
image: 弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.7
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 2.5
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -65
xOffsetRelative: 10

hSpeed: 3.7
dirSpeedRandom: 50


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm1_0.6s: {x:0, y:-16, dir:-45}

arm2_0.6s: {x:10, y:4, dir:-10}
arm3_0.6s: {x:-18, y:-20, dir:-15}
arm4_0.6s: {x:7, y:2, dir:-15}
arm5_0.6s: {x:0, y:0, dir:-15}
arm6_0.6s: {x:-5, y:0, dir:-65}

arm7_0.6s: {x:-5, y:0, dir:-65}
arm8_0.6s: {x:-5, y:0, dir:-65}


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.96
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2.5

targetHeight: 4
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4

slowDeathFall: true


