


[core]
name: 工蚁
displayText: Рабочий муравей
price: 800
maxHp: 12
displayDescription: -主要建造单位\n-无攻击能力
techLevel: 1

buildSpeed: 11s
#availableInDemo: true
radius: 15
displayRadius: 15
copyFrom: ROOT:/通用特效/单位防护.ini

canRepairBuildings: true
canRepairUnits: true
fogOfWarSightRange: 25
canReclaimResources: true
nanoRange: 235

nanoBuildSpeed: 1.1
tags: 农民,飞机,低空

canBuild_2_name: 太空浪人重组培养箱t1传送

canBuild_2_pos: 2
canBuild_2_isLocked: if numberOfUnitsInTeam(withTag='培养箱',withinRange=500,greaterThan=3) and self.isControlledByAI()
canBuild_3_name: 太空浪人钻探机t1传送
canBuild_3_pos: 3
canBuild_4_name: 太空浪人多相聚变堆t1传送

canBuild_4_pos: 1
canBuild_4_isLocked: if numberOfUnitsInTeam(withTag='d',withinRange=500,greaterThan=0) and self.isControlledByAI()
canBuild_5_name: 太空浪人机械工厂t1传送
canBuild_5_pos: 4
canBuild_5_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t2') or numberOfUnitsInTeam(withTag='浪人重工',withinRange=800,greaterThan=0) and self.isControlledByAI()

canBuild_5_isLockedMessage: 需要二级枢纽
canBuild_6_name: 太空浪人传送基站传送
canBuild_6_pos: 5
canBuild_6_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t2') or numberOfUnitsInTeam(withTag='核',withinRange=800,greaterThan=0) and self.isControlledByAI()
canBuild_6_isLockedMessage: 需要二级枢纽

canBuild_7_name: 空塔楼t1传送
canBuild_7_pos: 6
canBuild_7_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t2')
canBuild_7_isLockedMessage: 需要二级枢纽
canBuild_8_name: 太空浪人机库t1传送

canBuild_8_pos: 7
canBuild_8_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or numberOfUnitsInTeam(withTag='浪人机库',withinRange=800,greaterThan=0) and self.isControlledByAI()
canBuild_8_isLockedMessage: 需要三级枢纽
canBuild_9_name: 太空浪人船舰工厂t1传送
canBuild_9_pos: 4.5

canBuild_9_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t2')
canBuild_9_isLockedMessage: 需要二级枢纽
canBuild_10_name: 太空浪人暗物质筒仓t1传送
canBuild_10_pos: 8
canBuild_10_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3')

canBuild_10_isLockedMessage: 需要三级枢纽
canBuild_11_name: 太空浪人智脑节点传送
canBuild_11_pos: 9
canBuild_11_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or numberOfUnitsInTeam(withTag='智脑', greaterThan=0)
canBuild_11_isLockedMessage: 需要三级枢纽，只能拥有一个

canBuild_12_name: 太空浪人纳米蜂巢传送
canBuild_12_pos: 10
canBuild_12_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or numberOfUnitsInTeam(withTag='蜂巢', greaterThan=0)
canBuild_12_isLockedMessage: 需要三级枢纽，只能拥有一个
canBuild_13_name: 太空浪人超立方t1传送

canBuild_13_pos: 11
canBuild_13_isLocked: if not self.globalTeamTags(includes='帝国科技解析1') or numberOfUnitsInTeam(withTag='超立方', greaterThan=1)
canBuild_13_isLockedMessage: 需要帝国科技解析1，只能拥有两个
canBuild_14_name: 太空浪人无人机机库t1传送
canBuild_14_pos: 12

canBuild_14_isLocked: if not self.globalTeamTags(includes='帝国科技解析1') or numberOfUnitsInTeam(withTag='无人机库', greaterThan=3)
canBuild_14_isLockedMessage: 需要帝国科技解析1，只能拥有四个
canBuild_15_name: 重型炮塔底座t1传送
canBuild_15_pos: 13
canBuild_15_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3')

canBuild_15_isLockedMessage: 需要三级枢纽
canBuild_16_name: 空塔楼t2传送
canBuild_16_pos: 14
canBuild_16_isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3')
canBuild_16_isLockedMessage: 需要三级枢纽


[graphics]
image: 工蚁.png
image_wreak: 工蚁死亡.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1

movementEffect: CUSTOM:projectileTrail
imageScale: 1.3


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 3
maxAttackRange: 90
shootDelay: 15
turretRotateWithBody: false


[effect_projectileTrail]
createWhenZoomedOut: false
frameIndex: 0
stripIndex: effects
life: 50
fadeOut: true

attachedToUnit: false
color: #63e6e8
fadeInTime: 3
scaleFrom: 0.7
scaleTo: 1

alpha: 0.4
drawUnderUnits: true
ySpeedRelative: -0.4
atmospheric: true


[movement]
movementType: AIR
moveSpeed: 0.6
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.3
maxTurnSpeed: 2.3

turnAcceleration: 0.6
moveSlidingMode : false
moveIgnoringBody: false


[ai]
useAsBuilder: true
upgradedFrom: 工蚁传送
maxGlobal: 30


