
[core]
name: 机枪手
displayText: 机枪手
class: CustomUnitMetadata
displayDescription:【阶级t1】【生物单位】【地面单位】  战术定位:高级泛用型步兵，\n-单位体积:1，武器配置：▲MK46轻机枪X1 对地对空 动能伤害。\n-机枪手是步兵小队的火力支柱，\n-其配备的MK46MOD1机枪能像割草机一样射杀步兵，\n-他们甚至还拥有一定的反轻甲和防空能力。
price: 250
maxHp: 100
mass: 45
techLevel: 1
fogOfWarSightRange: 14
tags: 步兵,地面,驻扎要塞,1格
isUnrepairableUnit:true
buildSpeed: 3s
radius: 7
isBio: true
armour: 0
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md
explodeOnDeath: false
softCollisionOnAll: 17
hideScorchMark: true
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[action_举枪]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan= 0,withInRange=280, incompleteBuildings= true) and not self.tags(includes= '举枪')
isVisible:false
temporarilyAddTags:举枪
playAnimation:部署
[action_收枪]
autoTrigger: if numberOfUnitsInEnemyTeam(lessThan= 1,withInRange=280, incompleteBuildings= true) and self.tags(includes= '举枪')
isVisible:false
stopLastAnimation: true

alsoQueueAction: b
[action_b]
displayType: action
price: 0
playAnimation: 部署1
buildSpeed: 0.51s
isVisible: false
temporarilyRemoveTags:举枪
highPriorityQueue: true
whenBuilding_cannotMove: false

[graphics]
total_frames: 1
image: NO.png
image_wreak: 尸体.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
imageScale: 0.7


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretTurnSpeed: 40
maxAttackRange: 230
isFixedFiring: true
turretRotateWithBody: true


[turret_1]
x: 0
y: 0
canShoot: false
shouldResetTurret: false


[turret_2]
x: 2.8
y: 0
invisible: true
attachedTo: 1
slave: true

shoot_sound:机枪.ogg
shoot_sound_vol:0.1
shoot_flame: CUSTOM:枪口火焰
shoot_light: #FFFFEB88
size:20
delay: 4
canAttackCondition:if self.tags(includes= '举枪') or self.hasParent


[projectile_1]
@copyFromSection: template_动能
directDamage: 7
life: 666
speed: 9
targetSpeed: 9

deflectionPower: -1
frame: 5
drawSize: 0.6
explodeEffect: NONE


[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.7
ySpeedRelativeRandom: 0.6

hSpeed: 1


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.5
scaleTo: 0.5
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1
ySpeedRelativeRandom: 1

hSpeed: 1
dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 600
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 3
alpha: 1.2
fadeInTime: 3

liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10
animateFramePingPong: false

animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡.ogg,ROOT:/创世纪军事集团/步兵特效/死亡3.ogg,ROOT:/创世纪军事集团/步兵特效/死亡4.ogg,ROOT:/创世纪军事集团/步兵特效/死亡5.ogg


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
[arm_1]
#左后臂
x: -4
y: 1
image_end: 手.png
image_end_teamColors: true
drawDirOffset: -20
drawOverBody: false
image_end_shadow: SHADOW:手.png
[arm_2]
#右后臂
x: 5
y: 0
image_end: 手.png
image_end_teamColors: true
drawOverBody: false
drawDirOffset: 45
image_end_shadow: SHADOW:手.png
[arm_3]
#右前臂
x: 7
y: 3
image_end: 手.png
image_end_teamColors: true
#drawOverBody: true
drawDirOffset: -45
image_end_shadow: SHADOW:手.png
[arm_4]
x: -4
y: 5
image_end: 手.png
image_end_teamColors: true
#drawOverBody: true
drawDirOffset: 45
image_end_shadow: SHADOW:手.png
[arm_5]
#身体
x: 0
y: 0
image_end: 躯干.png
image_end_teamColors: true
#drawOverBody: true
image_end_shadow: SHADOW:躯干.png
[arm_6]
#枪
x: 2
y: 6
image_end: m4.png
image_end_teamColors: true
#drawOverBody: true
drawDirOffset: -63
[arm_7]
#脑袋
x: 0
y: 0
image_end: 头盔.png
image_end_teamColors: true
drawOverBody: true
[leg_1]
x: -2
y: 0
attach_x: -1
attach_y: -1
moveSpeed: 2.8
moveWarmUp: 0.5s
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25
targetHeightRelative: false
image_leg: 腿.png
dust_effect: false
holdDisMin: 1
holdDisMax: 6
hardLimit: 7
estimatingPositionMultiplier: 0.65
hidden: if self.hasParent() or self.isOverLiquid
[leg_2]
x: 2
y: 0
attach_x: 1
attach_y: -1
copyFrom: 1
[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm1_0.2s: {x:1, y:2, dir:20}
arm2_0.2s: {x:-2, y:-2, dir:0}
arm3_0.2s: {x:-2, y:-2, dir:10}
arm4_0.2s: {x:2, y:3, dir:10}
arm5_0.2s: {x:0, y:0, dir:18}
arm6_0.2s: {x:1, y:-2, dir:63}
arm1_9999s: {x:1, y:2, dir:20}
arm2_9999s: {x:-2, y:-2, dir:0}
arm3_9999s: {x:-2, y:-2, dir:10}
arm4_9999s: {x:2, y:3, dir:10}
arm5_9999s: {x:0, y:0, dir:18}
arm6_9999s: {x:1, y:-2, dir:63}
[animation_部署1]
arm1_0.4s: {x:0, y:0}
arm2_0.4s: {x:0, y:0}
arm3_0.4s: {x:0, y:0}
arm4_0.4s: {x:0, y:0}
arm5_0.4s: {x:0, y:0}
arm6_0.4s: {x:0, y:0}

[movement]
movementType: LAND
moveSpeed: 0.85
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2
reverseSpeedPercentage: 0
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: true
targetHeight: 2

[ai]
disableUse: true


