


[core]
name: 天灾侧炮模块
displayText: Боковой пушечный модуль «Бедствие»
strictLevel: 1
price: 0
radius: 0
maxHp: 1

class: CustomUnitMetadata
showInEditor: false
canNotBeDirectlyAttacked: true
disableDeathOnZeroHp: true
isUnrepairableUnit: true

isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
ignoreInUnitCapCalculation: true
[hiddenAction_消耗]
autoTrigger: if parent.tags(includes= '冲锋')
isVisible:false
setUnitStats: shootDelayMultiplier=0.5
[hiddenAction_消耗1]
autoTrigger: if not parent.tags(includes= '冲锋')
isVisible:false
setUnitStats: shootDelayMultiplier=1
[graphics]
image:NO.png
#isVisible: false
showQueueBar:false
#imageScale: 0.9
teamColorsOnTurret: true
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 1.5
maxAttackRange: 900
turretMultiTargeting: true
[turret_1]
x: -45
y: 25
canShoot: false
image: 主炮.png
idleDir:-30
limitingAngle: 100
turnSpeed: 2
turnSpeedAcceleration: 0.2
canAttackFlyingUnits: false
canAttackCondition: if not parent.tags(includes= '高空') and parent.tags(includes='天灾')
invisible:if not parent.tags(includes='天灾')
limitingRange: 500
[turret_2]
x: 5.5
y: 14
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.75
shoot_flame:large,CUSTOM:弹壳
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -6
recoilOutTime: 4
recoilReturnTime: 13
delay: 180
size:22
image: 炮管2.png
attachedTo: 1
slave: true
limitingAngle: 70
limitingMinRange: 100
canAttackFlyingUnits: false
limitingRange: 500
canAttackCondition: if not parent.tags(includes= '高空') and parent.tags(includes='天灾')
invisible:if not parent.tags(includes='天灾')
[turret_3]
x: 0
y: 14
copyFrom: 2
warmup: 10
delay:170
linkDelayWithTurret:2
[turret_4]
x: -5.5
y: 14
copyFrom: 2
warmup: 20
delay:160
linkDelayWithTurret:3

[turret_6]
x: 45
y: 25
copyFrom: 1
delay:60
warmup:60
idleDir:30
[turret_7]
x: 5.5
y: 14
copyFrom: 2
delay:180
attachedTo: 6
slave: true
[turret_8]
x: 0
y: 14
copyFrom: 2
delay:170
warmup:10
attachedTo: 6
slave: true
linkDelayWithTurret:7
[turret_9]
x: -5.5
y: 14
copyFrom: 2
delay:160
warmup:20
attachedTo: 6
slave: true
linkDelayWithTurret:8

#——————————————丧钟
[turret_10]
x: -45
y: 80
canShoot: false
image: 主炮.png
idleDir:-30
limitingAngle: 40
turnSpeed: 2
turnSpeedAcceleration: 0.2
canAttackFlyingUnits: false
canAttackCondition: if parent.tags(includes='丧钟')
invisible:if not parent.tags(includes='丧钟')
projectile: 2
[turret_11]
x: 5.5
y: 14
projectile:2
shoot_sound: ROOT:/创世纪军事集团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.75
shoot_flame:large,CUSTOM:弹壳
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -6
recoilOutTime: 4
recoilReturnTime: 13
delay: 180
size:22
image: 炮管2.png
attachedTo: 10
slave: true
limitingAngle: 70
#limitingMinRange: 100
canAttackFlyingUnits: false
canAttackCondition: if parent.tags(includes='丧钟')
invisible:if not parent.tags(includes='丧钟')
[turret_12]
x: 0
y: 14
copyFrom: 11
delay:170
warmup:10
attachedTo: 10
slave: true
linkDelayWithTurret:11
[turret_13]
x: -5.5
y: 14
copyFrom: 11
delay:160
warmup:20
attachedTo: 10
slave: true
linkDelayWithTurret:12

[turret_14]
x: 45
y: 80
copyFrom: 10
idleDir:30
[turret_15]
x: 0
y: 14
copyFrom: 11
delay:180
attachedTo: 14
slave: true
[turret_16]
x: 5.5
y: 14
copyFrom: 11
delay:170
warmup:10
attachedTo: 14
slave: true
linkDelayWithTurret:15
[turret_17]
x: -5.5
y: 14
copyFrom: 11
delay:160
warmup:20
attachedTo: 14
slave: true
linkDelayWithTurret:16
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 200
areaRadius: 65
life: 5000
speed: 7.5
color: #FFFFFF73
drawSize: 0.85
lightSize: 1.5
frame: 9
lightColor: #FFFFFF73
targetGroundSpread: 35
targetSpeed: 12
disableLeadTargeting: true
targetGround: true
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:钢珠
areaRadiusFromEdge: true
targetGround_includeTargetHeight:true
[projectile_2]
@copyFromSection: projectile_1
areaDamage: 350
areaRadius: 65
mutator7_ifUnitWithoutTags:极端重型
mutator7_directDamageMultiplier: 1.5
mutator7_areaDamageMultiplier: 1.5
targetGround_includeTargetHeight:true
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
alpha: 1
scaleFrom: 1.2
scaleTo: 3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
[effect_弹壳]
image: 弹壳.png
spawnChance: 1
life: 130
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5
drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: 0.1
ySpeedRelative: -0.2
xSpeedRelativeRandom: -0.05
ySpeedRelativeRandom: -0.2
yOffsetRelative: -30
xOffsetRelative: 0
hSpeed: 2
dirSpeedRandom: 10
[movement]
movementType: AIR
maxTurnSpeed: 999

