


[core]
name: 天灾重型攻击机1
displayText: 天灾重型攻击机
showInEditor: false
displayDescription: 【阶级t3】【机械单位】【空中单位】战术定位:重型泛用型攻击机，\n-武器配置：▲榴弹炮X6 只能对地 爆炸伤害 \n-▲火箭发射舱X4 只能对地 爆炸伤害 ▲轨道炮X2 只能对高空 动能伤害\n-▲空对空导弹X4 只能对高空 爆炸伤害\n-为了真正能有效击沉余辉进入大气内的战舰，\n-创世纪科学家们也曾尝试打造自己的，代号为“天灾”的空天战舰，\n-但由于科技能力的限制，“天灾”计划的指标与计划最终向现实妥协。\n-万般无奈下，创世纪科学家只好利用已经成熟的技术将其改造成重型直升机。\n-天灾重型攻击机专为参加与余辉的重型攻坚战而生，\n-其携带8枚反舰导弹和最先进的轨道炮科技，\n-同时拥有采用新型合金材料打造的强固机体结构。\n-天灾重型攻击机绝对是创世纪空军中最具威力，也是最恐怖的大型攻城单位之一。
price: 8000,钍=270
maxHp: 18000
techLevel: 2
buildSpeed: 42s
fogOfWarSightRange: 38
armour: 20
radius: 82
displayRadius: 82
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 天灾
isBio: false
canOnlyBeAttackedByUnitsWithTags:反高空
#effectOnDeathGroundCollision: CUSTOM:爆炸*1
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/扎针1.md
softCollisionOnAll: 10
tags: 飞机,高空,反高空,天灾
energyMax: 4
energyRegen: 0.016
energyNeedsToRechargeToFull: true
effectOnDeath:CUSTOM:碎片,CUSTOM:碎片1,CUSTOM:碎片2,CUSTOM:碎片3,CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大钢珠*2,CUSTOM:巨大闪光
effectOnDeathGroundCollision: CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大钢珠*2,CUSTOM:巨大闪光
[action_b]
displayType: action
price: 0
buildSpeed: 5s
isVisible: true
whenBuilding_cannotMove: false
text:降低高度
description: 降低天灾重型攻击机的高度，使其成为常规空中单位。\n-恢复对地能力和射程，但失去了攻击高空单位的能力。
iconImage: ROOT:/通用特效/低空.png
allowMultipleInQueue:false
convertTo: 天灾重型攻击机
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.tags(includes= '冲锋')
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
temporarilyAddTags:低空
temporarilyRemoveTags:高空,反高空
[action_高空]
text: 高空单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的战机和战舰。\n-在此高度下，只有地面和空中特殊的反高空单位，以及高空单位才能攻击到该单位，\n-同时，大部分高空单位可以互相攻击，并可以攻击普通空中单位，\n-只有特殊的高空单位才能对地攻击。
[attachment_hmmkA1]
x: 0
y: 0
onCreateSpawnUnitOf:天灾侧炮模块
resetRotationWhenNotAttacking: true
setDrawLayerOnBottom:true
[graphics]
total_frames: 1
image: 机体.png
image_wreak: 碎片1.png
image_turret: NONE
imageScale: 1

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
showEnergyBar: false
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 750
isFixedFiring: true


[turret_0]
x: 0
y: 0
invisible: true
canShoot: false
canOnlyAttackUnitsWithTags:高空

[turret_1]
x: 31
y: 151
projectile: 1
shoot_sound: ROOT:/通用特效/中轨道炮.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾*3
shoot_light: #FFFFEB88
canShoot: true
recoilOffset: -17
recoilOutTime: 5
recoilReturnTime: 30
delay: 60
size:17
image: 炮管1.png
canAttackLandUnits:false
limitingMinRange: 100
attachedTo: 0
slave: true
canOnlyAttackUnitsWithTags:高空
[turret_2]
x: 31
y: 149
projectile: 2
shoot_sound:NONE
canShoot: true
recoilOffset: -6
recoilOutTime: 10
recoilReturnTime: 25
delay: 60
size:17
image: 炮管.png
canAttackLandUnits:false
limitingMinRange: 50
attachedTo: 0
slave: true
canOnlyAttackUnitsWithTags:高空
[turret_3]
x: 31
y: 122
image:炮塔主体.png
attachedTo: 0
slave: true
canShoot:false
canAttackLandUnits:false
canOnlyAttackUnitsWithTags:高空
[turret_4]
x: -31
y: 151
copyFrom: 1
delay:50
warmup:10
#linkDelayWithTurret:1
[turret_5]
x: -31
y: 149
copyFrom: 2
delay:50
warmup:10
#linkDelayWithTurret:1
[turret_6]
x: -31
y: 122
copyFrom: 3
[turret_7]
invisible: true
x: -80
y: 82
projectile: 3
attachedTo: 0
slave: true
size: 0
turnSpeed: 0
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹发射音效.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾1*3
delay: 120
limitingMinRange: 300
energyUsage:1
canAttackLandUnits:false
canOnlyAttackUnitsWithTags:高空
[turret_8]
x: -70
y: 82
copyFrom: 7
delay:100
warmup:20
linkDelayWithTurret:7
[turret_9]
x: 70
y: 82
copyFrom: 7
delay:80
warmup:40
linkDelayWithTurret:8
[turret_10]
x: 80
y: 82
copyFrom: 7
delay:60
warmup:60
linkDelayWithTurret:9
[turret_11]
invisible: true
x: 55
y: 80
projectile: 5
size: 18
turnSpeed: 0
shoot_sound: ROOT:/通用特效/连射.wav
shoot_sound_vol: 0.4
attachedTo: 0
slave: true
delay: 30
shoot_flame: CUSTOM:烟雾*1
canAttackFlyingUnits: false
canShoot: false
canOnlyAttackUnitsWithTags:高空
[turret_12]
x: 41
y: 80
copyFrom: 11
delay:25
warmup:5
linkDelayWithTurret:11
[turret_13]
x: -55
y: 80
copyFrom: 11
delay:30
[turret_14]
x: -41
y: 80
copyFrom: 11
delay:25
warmup:5
linkDelayWithTurret:13
[projectile_1]
@copyFromSection: template_动能
directDamage: 580
life: 200
speed: 12
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
drawSize: 0.6
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:爆炸2,CUSTOM:冲击波2,CUSTOM:穿透
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:爆炸2,CUSTOM:冲击波2,CUSTOM:穿透
lightSize: 0.75
deflectionPower: -1
trailEffectRate: 0.25
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1
lightColor: #FFFF1200
[projectile_2]
directDamage: 0
life: 0
deflectionPower: -1
speed: 0
targetSpeed: 0
[projectile_3]
@copyFromSection:projectile_4
life: 10
turnSpeed: 0
spawnProjectilesOnEndOfLife: 4
drawUnderUnits:true
[projectile_4]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.95
image: 导弹.png
trailEffect: true
areaDamage: 850
areaRadius: 65
explodeEffect: CUSTOM:冲击波d,CUSTOM:爆炸d, CUSTOM:闪光d,CUSTOM:钢珠d
explodeEffectOnShield: CUSTOM:冲击波d,CUSTOM:爆炸d, CUSTOM:闪光d,CUSTOM:钢珠d
deflectionPower: -1
autoTargetingOnDeadTarget: true
autoTargetingOnDeadTargetRange:250
areaRadiusFromEdge: true
trailEffectRate: 1.5
turnSpeed: 3.5
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_5]
@copyFromSection: template_爆炸
targetGround: true
targetGroundSpread: 35
areaDamage: 150
areaRadius: 60
life: 250
speed: 2
targetSpeed: 13
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 0.85
trailEffect: true
lightSize: 0.75
trailEffectRate: 2.5
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸h,CUSTOM:冲击波h,CUSTOM:闪光h
explodeEffectOnShield:CUSTOM:爆炸h,CUSTOM:冲击波h,CUSTOM:闪光h
areaRadiusFromEdge: true
[effect_冲击波2]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:30
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1
alpha: 0.8
fadeInTime: 4
drawUnderUnits:false
[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: true
atmospheric: false
[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.58
scaleTo: 0.58
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.78
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_爆炸2]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
[effect_穿透]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
life: 40
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.5
scaleTo: 0.1
alpha: 1
drawUnderUnits: false
ySpeedRelative: 4
atmospheric: true
[effect_尾巴1]
priority: veryhigh
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.38
scaleTo: 0.38
alpha: 1
drawUnderUnits: true

[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 15
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.4
scaleTo: 0.4
alpha: 0.7
drawUnderUnits: false
ySpeedRelative: 0.3

[effect_烟雾1]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 60
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1
scaleTo: 1.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: -0.3
ySpeedRelativeRandom: 0.35
xSpeedRelativeRandom: 0.2
yOffsetRelative: -15
atmospheric: true
[effect_闪光d]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
[effect_爆炸d]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸a.ogg
[effect_钢珠d]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_冲击波d]
life: 100
priority:veryhigh
attachedToUnit: true
scaleFrom: 0.4
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.22
alwayStartDirAtZero: true
alpha: 0.8
[effect_冲击波h]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.8
alpha: 1
[effect_闪光h]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false
atmospheric: false
[effect_爆炸h]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 1
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.26
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alpha: 1.2

[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.5
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[effect_巨大钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
alpha: 0.8
scaleFrom: 3
scaleTo: 7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_巨大弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true
[effect_巨大气浪]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 3
scaleTo: 7.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true
[effect_碎片]
priority: critical
image: 碎片2.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1.5
createWhenZoomedOut: false
xSpeedRelative:-2
ySpeedRelativeRandom: -1
yOffsetRelative: 0
xOffsetRelative: -70
hSpeed: 1.5
dirSpeed:1
dirSpeedRandom:2
[effect_碎片1]
priority: critical
image: 碎片3.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelative:-0.1
ySpeedRelative:-1.35
ySpeedRelativeRandom: -1
yOffsetRelative: -70
xOffsetRelative:0
hSpeed: 1.2
dirSpeed:0.7
dirSpeedRandom:1
[effect_碎片2]
priority: critical
image: 碎片4.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 1.5
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1.6
createWhenZoomedOut: false
xSpeedRelative:-0.8
ySpeedRelative:-0.1
ySpeedRelativeRandom: -1
xOffsetRelative: -105
yOffsetRelative:3
hSpeed: 2.2
dirSpeed:2
dirSpeedRandom:3
[effect_碎片3]
priority: critical
image: 碎片4.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 1.5
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelative:0.8
ySpeedRelative:-0.1
ySpeedRelativeRandom: -1
xOffsetRelative: 105
yOffsetRelative:3
hSpeed: 1.2
dirSpeed:0.7
dirSpeedRandom:1
[arm_1]
x: -80
y: 84
image_end: 导弹.png
drawOverBody: true
hidden:if self.Energy<3.1 
[arm_2]
x: -69
y: 84
image_end: 导弹.png
drawOverBody: true
hidden:if self.Energy<2.1 
[arm_3]
x: 69
y: 84
image_end: 导弹.png
drawOverBody: true
hidden:if self.Energy<1.5
[arm_4]
x: 80
y: 84
image_end: 导弹.png
drawOverBody: true
hidden:if self.Energy<1.2
[arm_5]
x: 0
y: 0
image_end: 机体.png
drawOverBody: true
image_end_teamColors: true
hidden: if self.hp<self.maxHp * 0.36
[arm_6]
x: 0
y: 9.5
image_end: 灯光.png
drawOverBody: true
image_end_teamColors: true
hidden: if self.hp<self.maxHp * 0.36
[arm_7]
x: 0
y: 0
image_end: 损坏.png
drawOverBody: true
image_end_teamColors: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_8]
x: 105
y: 3
image_end: 扇叶.png
drawOverBody: true
spinRate: 50


[arm_9]
x: -105
y: 3
image_end: 扇叶.png
drawOverBody: true
spinRate: -50


[movement]
movementType: AIR
moveSpeed: 1.3
startingHeightOffset: 2000
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02

maxTurnSpeed: 1.2
turnAcceleration: 1
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: true

targetHeight: 140
fallingAccelerationDead: 0.01


