[core]
name: 创世纪战车工厂t3
displayText: Завод бронетехники Генезисаt3
price: 9000
maxHp: 33000
armour: 45
footprint: -3,-2,3,5
constructionFootprint: -3,-2,3,5
displayDescription:【Уровень t4】【Здание】【Наземный юнит】\n-Тактическое назначение: завод наземных механических юнитов, без вооружения.\n-не может строиться на воде。быстро развёртываемый фронтовой тяжёлый завод со встроенной производственной линией，\n-способен быстро производить юниты по стандартным шаблонам，\n-Эти типичные бронетанковые дивизии Генезиса，почти полностью производятся в таких базовых зданиях。
tags: 地面,战车工厂,建筑
unitsSpawnedOnDeath:建筑损毁*1
techLevel: 1
buildSpeed: 14s
#availableInDemo: true
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 50
isBio: false
isBuilding: true
nanoFactorySpeed:1
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*6,largeExplosion
exit_x:10
exit_y: 35
exit_moveAwayAmount: 110
canBuild_31_name: setRally
canBuild_31_pos: 0.1

[hiddenAction_ai自动造]
autoTrigger:if numberOfUnitsInTeam(lessThan=3, withTag='重型工程车') and self.isControlledByAI() and not self.tags(includes= '工程车保险')
alsoQueueAction:自动造
temporarilyAddTags:工程车保险
[action_自动造]
displayType: action
price: 0
buildSpeed: 10s
isVisible: false
highPriorityQueue: false
temporarilyRemoveTags:工程车保险
spawnUnits:重型工程车
[action_煅炉增益]
autoTrigger:if self.globalTeamTags(includes='纳米煅炉') and not self.tags(includes= '煅炉保险')
isActive: false
isVisible: false
temporarilyAddTags:煅炉保险
setUnitStats: nanoFactorySpeed=1.3
[canBuild_T2]
name: 苦工机器人,袋熊战车,火箭机车,加特林卡车,轻坦克,反坦克导弹车,IAV轮式突击炮
pos: 1
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
[canBuild_T3]
name: 苦工机器人,主战坦克,自行榴弹炮,自行高炮,自爆卡车,噩梦,两栖突击舰
pos: 1
isVisible: if self.hasFlag(id=3)  or self.isControlledByAI()
[canBuild_T4]
name: 苦工机器人,重型工程车,挑战者坦克,暴雨火箭炮,净化者机甲
pos: 1
isVisible: if self.hasFlag(id=4)
[canBuild_T33]
name: 镭射坦克
pos: 1
isVisible: if self.hasFlag(id=3)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='裂变技术1')
isLockedMessage: Требуется технология деления 1
[canBuild_T34]
name: 巨兽坦克
pos: 1
isVisible: if self.hasFlag(id=3)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: Требуется материаловедение 2
[canBuild_T35]
name: 暴君
pos: 1
isVisible: if self.hasFlag(id=3)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='轨道发射器2') or not self.globalTeamTags(includes='材料技术2')
isLockedMessage: тынуждаетсяорбитальныйпусковая установка2иМатериаловедение2

[canBuild_T36]
name: 地狱猎犬
pos: 1
isVisible: if self.hasFlag(id=3)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='基础科学进步1')
isLockedMessage: Требуется фундаментальная наука1

[canBuild_T41]
name: 贾弗林防空平台
pos: 1
isVisible: if self.hasFlag(id=4)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='轨道发射器3') or not self.globalTeamTags(includes='超导技术1')
isLockedMessage: тынуждаетсяорбитальныйпусковая установка3иСверхпроводимость1
[canBuild_T42]
name: 休克打击坦克
pos: 1
isVisible: if self.hasFlag(id=4)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='电磁脉冲武器1') or not self.globalTeamTags(includes='超导技术1') or not self.globalTeamTags(includes='材料技术3')
isLockedMessage: Требуется ЭМИ-оружие1，Сверхпроводимость1，а такжеМатериаловедение3
[canBuild_T43]
name: 浮游坦克
pos: 1
isVisible: if self.hasFlag(id=4)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='超导技术1')
isLockedMessage: Требуется сверхпроводимость 1
[canBuild_T44]
name: 地狱火导弹平台
pos: 1
isVisible: if self.hasFlag(id=4)  or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='材料技术3') or not self.globalTeamTags(includes='弹道导弹技术2')
isLockedMessage: Требуется материаловедение 3иТехнология портативных баллистических ракет

[action_T2]
pos: 0.2
buildSpeed: 0s
addResources: setFlag=0,setFlag=2
text: 显示t1юнит
isVisible: if not self.hasFlag(id=2) and not self.hasFlag(id=0)
[action_T2_back]
pos: 0.2
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=2
isVisible: if self.hasFlag(id=2)
text: не显示t1юнит
[action_T3]
pos: 0.3
buildSpeed: 0s
addResources: setFlag=0,setFlag=3
text: 显示t2юнит
isVisible: if not self.hasFlag(id=3) and not self.hasFlag(id=0)
highPriorityQueue: true
[action_T3_back]
pos: 0.3
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=3
isVisible: if self.hasFlag(id=3)
text: не显示t2юнит
ai_isHighPriority: true
[action_T4]
pos: 0.3
buildSpeed: 0s
addResources: setFlag=0,setFlag=4
text: 显示t3юнит
isVisible: if not self.hasFlag(id=4) and not self.hasFlag(id=0)
highPriorityQueue: true
ai_isHighPriority: true
[action_T4_back]
pos: 0.3
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=4
isVisible: if self.hasFlag(id=4)
text: не显示t3юнит
[action_T361]
displayType: action
text: модульныйпроизводствоАдский гончий
price:6500,钍=117
pos: 1
isVisible: if self.hasFlag(id=3) and self.globalTeamTags(includes='模块化技术') and self.globalTeamTags(includes='基础科学进步1')
isLocked: if not self.globalTeamTags(includes='基础科学进步1')
isLockedMessage:Требуется фундаментальная наука1
produceUnits:地狱猎犬
buildSpeed: 35s


playAnimation: 开门
[graphics]
total_frames: 1
image: 主体.png
image_back: 背景.png
image_wreak:ROOT:/创世纪军事集团/建筑特效/死亡1.png
image_shadow: 影子.png
imageScale: 0.95

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 30
maxAttackRange: 9999
shootDelay: 0


[turret_火焰]
x: -8
y: 80
projectile: 13
shoot_flame: CUSTOM:烟雾2
delay: 20
invisible: true
size: 1


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1
[effect_烟雾2]
createWhenZoomedOut: false
stripIndex: effects
frameIndex: 0
life: 300
fadeOut: true
attachedToUnit: false
color: #646464
fadeInTime: 15
scaleFrom: 0.65
scaleTo: 4
alpha: 0.45
drawUnderUnits: false
hSpeed: 0.6
xSpeedAbsolute: -0.2
hOffsetRandom: 0.15
yOffsetRelative: -2
atmospheric: true
dirOffsetRandom: 180
shadow: true
xOffsetRelativeRandom: 1

yOffsetRelativeRandom: 1
xSpeedAbsoluteRandom: 0.05
ySpeedAbsoluteRandom: 0.1

[arm_1]
x: 7
y: -59
image_end:ROOT:/创世纪军事集团/建筑特效/门.png
image_end_teamColors: true
drawOverBody: true

[arm_2]
x: -50
y: 23
image_end:ROOT:/创世纪军事集团/建筑特效/货物.png
image_end_teamColors: true
drawOverBody: true
[arm_3]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_6]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_7]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[animation_1]
onActions: queuedUnits
blendIn: 1s
blendOut: 2s
onActionsQueuedUnitPlayAt: 0.7
arm1_0: {x:0, y:30}
[animation_开门]
arm1_0s: {x:0, y:0}
arm1_0.5s: {x:0, y:90}
arm1_1s: {x:0, y:90}
[animation_2]
onActions: idle
blendIn: 1s
blendOut: 2s
#onActionsQueuedUnitPlayAt:0.7
#pingPong: true

arm2_0s: {x:0, y:0}
arm2_2s: {x:36, y:35}
arm2_3s: {x:36, y:0}
arm2_4s: {x:0, y:0}

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:55
delayedStartTimerRandom:30

[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.07
maxEachBase: 15
maxGlobal: 50
upgradedFrom: 创世纪战车工厂t1

