


[core]
name: 攻城锥IFV MKII
displayText: БМП Осадный конус MKII
displayDescription:【Уровень t3】【Механический юнит】【Наземный юнит】Тактическое назначение:БМП，вместимость десанта：8\n-может загружать только биологические юниты且сам не может транспортироваться。\n-вооружение：▲链炮X1 по земле и воздуху кинетический урон \n-▲ракетапусковая установкаX1 по земле и воздуху взрывной урон \n-Осадный конусБМП的MKII版本，从原版车 改造а来。\n-только保留了внутренний骨 结构，а其он部位全接受了全方面改造，\n-MKII版本为了уменьшаетдесант难度а做了减重处理，换装了轻 броня，\n-и移除了много不必要的оборудование，однако这些微小的代价，\n-换来的是额外的пехота容量和ещё более迅捷的манёвренность。

price: 3000
maxHp: 4000
techLevel: 1
buildSpeed: 10s
radius: 23
fogOfWarSightRange: 17
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,攻城锥
armour: 5
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 攻城锥
maxTransportingUnits: 8
transportUnitsRequireTag: 步兵,卧倒,机甲
transportUnitsKillOnDeath: true
transportUnitsKeepBuiltUnits: true
unitsSpawnedOnDeath: 损毁*1
[action_tx1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[decal_主体损坏a]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36





[graphics]
total_frames: 2
image: 主体.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 3
dustEffect: true
#turretImageScale: 0.8
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 13
turretTurnSpeed: 4
maxAttackRange: 295
turretMultiTargeting: true
[turret_1]
x: 0
y: 0
#地盘损坏
canShoot: false

[turret_2]
x: 0
y: 33
#主炮
projectile: 1
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.5
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -3.5
recoilOutTime: 4
recoilReturnTime: 19
delay: 35
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackCondition: if self.resource.xk<1
image: 炮管.png
attachedTo: 3
slave: true
size:11
[turret_3]
x: 0
y: -10
#炮塔
canShoot: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackCondition: if self.resource.xk<1
idleSweepAngle: 20
idleSweepDelay: 230
idleSweepSpeed: 0.2
image:炮塔.png
[turret_4]
x: 11
y: 4
projectile: 2
shoot_sound: missile_fire
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾*3
shoot_light: #FFEECCCC
canShoot: true
delay: 90
canAttackCondition: if self.resource.xk<1
attachedTo: 3
invisible: true
slave: true
size:0
[turret_5]
x: 0
y: 0
#炮塔损坏
canShoot: false
image: 炮塔损坏.png
invisible: if self.maxHp * 0.36 < self.hp
attachedTo: 3
slave: true
[projectile_1]
@copyFromSection: template_动能
directDamage: 60
life: 60
speed: 6.5
frame: 8
color: #FFFFFF73
drawSize: 0.8
largeHitEffect: true
lightSize: 1
lightColor: #FFFFFF73
gravity: 1
explodeEffect: CUSTOM:闪光,CUSTOM:爆炸
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 100
areaRadius: 35
life: 666
speed: 3
targetSpeed: 9
drawSize: 0.8
trailEffect: true
frame: 10
largeHitEffect: true
areaRadiusFromEdge: true
[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 2
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.8
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
dirOffsetRandom: 180
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2
ySpeedRelative: 0.3
atmospheric: true

[attachment_1]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: true


[attachment_2]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false

resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: true


[attachment_3]
x: 0
y: 0
alwaysAllowedToAttackParentsMainTarget: true
height: -1
isVisible: false

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: true
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_4]
x: 0
y: 0
isVisible: false
alwaysAllowedToAttackParentsMainTarget: true
height: -1

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: true
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_5]
x: 0
y: 0
alwaysAllowedToAttackParentsMainTarget: true
height: -1
isVisible: false

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: true
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_6]
x: 0
y: 0
isVisible: false
alwaysAllowedToAttackParentsMainTarget: true
height: -1

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: true
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true

[attachment_7]
x: 0
y: 0
alwaysAllowedToAttackParentsMainTarget: true
height: -1
isVisible: false

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: true
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_8]
x: 0
y: 0
isVisible: false
alwaysAllowedToAttackParentsMainTarget: true
height: -1

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: true
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true

[movement]
movementType: LAND
moveSpeed: 1.5
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0.6
maxTurnSpeed: 2.4
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false




