


[core]
name: 小型住宅
class: CustomUnitMetadata
price: 0
maxHp: 10000
footprint: -2,-1,2,2

constructionFootprint: -2,-1,2,2
techLevel: 1
#copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 0s
#displayDescription:兵营负责训练最基础步兵单位，\n-这些士兵往往组成创世纪的第一道防线。

radius: 25
isBio: false
isBuilding: true
effectOnDeath: largeExplosion*1
tags: 中立地面,不检测,建筑

stayNeutral: true
createOnAggressiveTeam: true
isUnrepairableUnit: true


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
#imageScale:0.7
image_back: ROOT:/通用特效/NO.png

image_shadow: 影子.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[arm_1]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(greaterThan=3600)


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
lowPriorityTargetForOtherUnits: true
notPassivelyTargetedByOtherUnits: true


