


[core]
name: 狼牙
displayText: Клык-Волка
copyFrom: ROOT:/通用特效/单位防护.ini
price: 800
maxHp: 1600
mass: 3000

displayDescription: -狼牙是太空浪人一种被升华到工业范式的强大生化怪物，\n-他们是一种技术低级，被粗糙的缝合加工出来的怪兽，\n-他们的身体和武器无一列外的来自于创世纪阵亡的士兵以及被摧毁的作战单位，\n-随着太空浪人在生物工程技术上的进步，狼牙的产量已经达到了规模空前的水平，\n-即便如此，狼牙配备自动迫击炮和火箭发射器使得其成为一个不融低估的危险对手，\n-即便这种变异体十分粗糙且身体结构畸形。\n-对地对空。爆炸伤害，生物单位。
techLevel: 1
buildSpeed: 7s
#availableInDemo: true
radius: 23
isUnrepairableUnit:true
displayRadius: 23
tags: 地面,步兵,寄生免疫
energyMax: 4
armour: 6
energyRegen: 0.017
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
energyNeedsToRechargeToFull: true
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
isBio: true
explodeOnDeath: false
hideScorchMark: true


[action_灰影寄生虫科技提示1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/灰影寄生虫.png
text: Паразит «Серая Тень» 1
isActive: false
isVisible: if self.globalTeamTags(includes='寄生虫1')


[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[graphics]
image: 主体.png
image_wreak: 死亡.png
image_turret: 主体.png
image_shadow: AUTO
shadowOffsetX: 3

shadowOffsetY: 3
lock_body_rotation_with_main_turret: true
lock_shadow_rotation_with_main_turret: true
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretTurnSpeed: 1.8

maxAttackRange: 280
shootDelay: 180
turretRotateWithBody: true


[turret_2]
x: 18
y: 6
image: 右.png
attachedTo: 1
#barrelX:5

idleDir: 10
warmup: 0
projectile: 1
turnSpeed: 3.0
limitingAngle: 30

turnSpeedAcceleration: 0.5
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*4
shoot_light: #FFEECCCC

canShoot: true
size: 29
recoilOffset: -3
delay: 100
altProjectile: 炮弹1

altProjectileCondition: if self.globalTeamTags(includes='寄生虫1')


[turret_3]
x: -18
y: 6
image: 左.png
attachedTo: 1
#barrelX:5

idleDir: -10
warmup: 0
projectile: 2
turnSpeed: 3.0
limitingAngle: 30

turnSpeedAcceleration: 0.5
shoot_sound: ROOT:/创世纪军事集团/单位特效/迫击炮音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*2,CUSTOM:枪口火焰*1
shoot_light: #FFEECCCC

canShoot: true
size: 29
recoilOffset: -1
canAttackFlyingUnits: false
delay: 10

energyUsage: 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='寄生虫1')


[turret_1]
x: 0
y: 0
turnSpeed: 1.8
turnSpeedAcceleration: 0.1
canShoot: false

image: 主体.png


[projectile_1]
@copyFromSection: template_爆炸
directDamage: 170
life: 250
speed: 6
image: ROOT:/创世纪军事集团/单位特效/导弹.png

drawSize: 0.6
trailEffect: true
lightSize: 0.75
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光


[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 80
areaRadius: 40
life: 6661
speed: 3.2

targetSpeed: 3.2
drawSize: 0.6
image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
explodeEffect: CUSTOM:爆炸1,CUSTOM:烟雾1,CUSTOM:闪光*1
targetGround: true

initialUnguidedSpeedHeight: 1
areaRadiusFromEdge: true
disableLeadTargeting: true
targetGroundSpread: 25


[projectile_炮弹]
@copyFromSection: template_爆炸
areaDamage: 110
areaRadius: 40
life: 6661
speed: 3.2

targetSpeed: 3.2
drawSize: 0.8
image: ROOT:/太空浪人/单位特效/卵.png
explodeEffect: CUSTOM:爆炸j,CUSTOM:闪光j
targetGround: true
tags: 灰影寄生虫
initialUnguidedSpeedHeight: 1
areaRadiusFromEdge: true
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: JSC=0.001
gravity: 0.4

disableLeadTargeting: true
targetGroundSpread: 25


[projectile_炮弹1]
@copyFromSection: template_爆炸
directDamage: 190
life: 250
speed: 6
image: ROOT:/创世纪军事集团/单位特效/导弹.png
tags: 灰影寄生虫
drawSize: 0.6
trailEffect: true
lightSize: 0.75
lightColor: #FF68FF2E
explodeEffect: CUSTOM:爆炸j1,CUSTOM:钢珠,CUSTOM:闪光j

mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: JSC=0.001


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.7
scaleTo: 1.7

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_烟雾]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6
xSpeedRelativeRandom: 0.6

yOffsetRelative: 0.8
ySpeedRelative: 1
atmospheric: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1.4

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[effect_钢珠]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.9
scaleTo: 0.9
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.8
ySpeedRelativeRandom: 0.8

hSpeed: 1


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.6
scaleTo: 0.6
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.2
ySpeedRelativeRandom: 1.2

hSpeed: 1
dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 600
fadeOut: true

attachedToUnit: false
scaleFrom: 2
scaleTo: 4.3
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡2.ogg


[effect_烟雾1]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true

life: 170
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5

scaleFrom: 0.1
scaleTo: 0.24
alpha: 1.25
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 1
scaleTo: 2.5


[effect_爆炸1]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.35
scaleTo: 1.2
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/迫击炮爆炸.ogg

alpha: 1.2
createWhenOverLiquid: false
createWhenOverLand: true


[leg_1]
x: -7
y: 0
attach_x: -1
attach_y: 0
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 20

holdDisMax: 35
hardLimit: 30


[leg_2]
x: 7
y: 0
attach_x: 1
attach_y: 0
copyFrom: 1

drawDirOffset: 10


[effect_爆炸j]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.6
image: ROOT:/太空浪人/单位特效/毒液.png
total_frames: 10

color: #FF68FF2E
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.3

alsoPlaySound: ROOT:/太空浪人/单位特效/血.ogg
alpha: 2


[effect_闪光j]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_爆炸j1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/太空浪人/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
#color:#FFFF1200
alsoPlaySound: ROOT:/太空浪人/单位特效/血.ogg


[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2.5

turnAcceleration: 0.2
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4


