


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=1200


[core]
name: SDN浮岛要塞核心
class: CustomUnitMetadata
displayDescription: -浮岛要塞是名副其实的钢铁巨兽，他是诺瓦帝国国力最强有力的象征之一。\n-古人类战国时期末期，为了守护刚刚从亚尔佛里德手中夺来的海洋霸权，\n-浮岛要塞被帝国的科研部设计出来，并大量部署于各个海洋星球。\n-规模空前的浮岛要塞携带大量毁灭性武器以及坚不可摧的防御设备，\n-他们可以在眨眼的瞬间摧毁整个海上舰队，哪怕是面对空天舰也有一战之力。\n-这种单位在创世纪看来是近乎无敌的存在，也是余辉海面上最大的单位之一。\n-令人庆幸的是，浮岛要塞在诺瓦帝国末期的混战中损失殆尽 ，\n-即使是余辉拥有的数量也十分有限，他们一般只出现在余辉核心设施附近。\n-对地对空对高空，导弹爆炸，其他能源，拥有舰载机。休克免疫\n-设计类型：诺瓦帝国 次世代计划数据，本体免疫地雷。
price: 25000,蓝晶=1800
maxShield: 500

shieldRegen: 0.07
maxHp: 700
techLevel: 1
buildSpeed: 60s
radius: 22

displayRadius: 22
tags: 地面,海上,悬浮
isBio: false
softCollisionOnAll: 6
copyFrom: ROOT:/通用特效/单位防护.ini

canRepairBuildings: true
canRepairUnits : true
nanoRange: 20
nanoRepairSpeed: 1
dieOnConstruct: true


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: 正电子芯核
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_3]
convertTo: 浮岛要塞中介
buildSpeed: 0s
isVisible: if self.isOverLiquid
text: 构建浮岛要塞


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 3

maxAttackRange: 10


[turret_1]
x: 0
y: 0
canShoot: false
# image:导弹.png
invisible: true

projectile: 1
idleDir: 90


[turret_2]
@copyFromSection: turret_1


[turret_3]
@copyFromSection: turret_1


[turret_4]
@copyFromSection: turret_1


[turret_5]
@copyFromSection: turret_1
idleDir: -90


[turret_6]
@copyFromSection: turret_5


[turret_7]
@copyFromSection: turret_5


[turret_8]
@copyFromSection: turret_5


[projectile_1]
# 空炮弹
life: 0
speed: 0
deflectionPower: -1
directDamage: 0

invisible: true
explodeEffect: none
explodeEffectOnShield: none


[movement]
movementType: HOVER
moveSpeed: 1.35
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.3
maxTurnSpeed: 1.8

turnAcceleration: 0.6
targetHeight: 3
targetHeightDrift: 2
moveSlidingMode : false
moveIgnoringBody: true


