


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=1200


[core]
name: 浮岛要塞中介
displayText: Парящая крепостьв посредник
class: CustomUnitMetadata
displayDescription: -Парящая крепостьэто имявспомогательныйего реальный стальогромныйзверь, онэто Империя Новастранасиласамыйсильныйимеет сила символсреди .\n-Война Государств эпохи Древних Людей (период)поздний период, для защитазащитатолько чтоиз Аравелидрукав захватитьприходит  мореокеантиранправо, \n-Парящая крепостьИмперия научно-исследовательскийчастьустановкарасчётвыходит приходит , и большой количествоРазвернутьк каждыйштмореокеанпланета.\n-масштабвоздушныйперед  Парящая крепостьпереноситьбольшой количествоуничтожениеоружие и прочныйне может уничтожать оборонаустановкарезерв, \n-они может в мгновение мгновенноуничтожитьвесь морена флот, даже еслиэто по воздухунебокорабльтакже имеет одинбой сила.\n-Этот юнитв созиданиеэпохаэрасмотретьприходит это близкийнет враги хранениев , также это Заревоморена самыйбольшой  юнитсреди .\n-приказчеловекк счастью это , Парящая крепостьв Империя Новапоздний период смешанныйбойв уронпотеряпочтимаксимум , \n-то естьиспользоватьэто ЗаревоИмея  количествотакже оченьимеет предел, они одинподобныйтольковыходит текущийв Заревоядрообъектрядом.\n-по земле и воздуху, взрыв ракеты, другие может источник, Имея палубный самолёт.шокиммунитет\n-Тип проекта:Империя Нова следующее поколениерасчётразрезданные
price: 25000,蓝晶=1800
maxShield: 16000

isBuilding: true
shieldRegen: 0.07
maxHp: 20000
techLevel: 1
buildSpeed: 45s

showInEditor: false
displayText: SDNпарящий岛нужнозаглушка
radius: 22
displayRadius: 22
tags: 地面,海上

isBio: false
softCollisionOnAll: 6
armour: 105
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 25

energyRegen: 0
energyNeedsToRechargeToFull: true
[action_重]
text: Сверхтяжёлый юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: Уникальное свойство огромных юнитов;\n-юниты с тегом «сверхтяжёлый» получают следующие свойства:\n-восстанавливают HP и имеют броню не менее 100,\n-трудно поддаётся шоку, но это получаетк определённыйюнит уронбафф.

[hiddenAction_1JZ]
addResources: energy=-1
autoTrigger: true


[action_3]
convertTo: SDN浮岛要塞
buildSpeed: 0s
isVisible: false
autoTrigger: if self.energy(empty=true)


[graphics]
total_frames: 1
image: 护盾.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 3

maxAttackRange: 10


[turret_1]
x: 0
y: 0
canShoot: false
# image:导弹.png
invisible: true

projectile: 1
idleDir: 90


[turret_2]
@copyFromSection: turret_1


[turret_3]
@copyFromSection: turret_1


[turret_4]
@copyFromSection: turret_1


[turret_5]
@copyFromSection: turret_1
idleDir: -90


[turret_6]
@copyFromSection: turret_5


[turret_7]
@copyFromSection: turret_5


[turret_8]
@copyFromSection: turret_5


[projectile_1]
# 空炮弹
life: 0
speed: 0
deflectionPower: -1
directDamage: 0

invisible: true
explodeEffect: none
explodeEffectOnShield: none


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0

turnAcceleration: 0


