


[core]
name: 蜂刺导弹小组卧倒
displayText: Расчёт ракет «Жало» (лежащий)
class: CustomUnitMetadata
displayDescription:【Уровень t3】【Биологический юнит】【Наземный юнит】Тактическое назначение:反单体пехота，размер юнита:2\n-вооружение：▲ракетазапускать仓X2 по земле и воздуху，взрывной урон。\n-Расчёт ракет «Жало»是броня的克星，\n-其оснащённый的新式重 ракетапусковая установкаможетодновременнозапускать两вид弹药，\n-можетиспользовать陶氏反танкракета和长钉зенитная ракета在安全距离内эффективный贯穿враг。
price: 1000
isUnrepairableUnit:true
maxHp: 450
mass: 450000
techLevel: 1
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
buildSpeed: 13s
armour: 5
softCollisionOnAll: 5
radius: 14
isBio: true
transportSlotsNeeded: 2
explodeOnDeath: false
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md
hideScorchMark: true
showInEditor: false
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
tags: 步兵,地面,蜂刺,驻扎要塞
energyMax: 2
energyRegen: 0
energyNeedsToRechargeToFull: true
[hiddenAction_不能动]
autoTrigger: true
setUnitStats: maxTurnSpeed =0
[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[action_聚变弹头1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变1.png
text: Термоядерная боеголовка1
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头1')
[decal_炮塔]
image: 导弹前.png
total_frames: 1
basePositionFromTurret: 1
layer:onTop
isVisible:if not self.tags(includes= '转管')
imageScale:0.68
onlyWhileAlive:true
teamColors:true
yOffsetRelative:11
[decal_炮塔1]
image: 弹壳.png
total_frames: 1
basePositionFromTurret: 1
layer:onTop
isVisible:if not self.tags(includes= '切枪')
imageScale:0.68
onlyWhileAlive:true
teamColors:true
yOffsetRelative:-7
[decal_炮塔2]
image: 人.png
total_frames: 1
basePositionFromTurret: 1
layer:onTop
isVisible:if not self.tags(includes= '切枪')
imageScale:0.68
onlyWhileAlive:true
teamColors:true
yOffsetRelative:-13

[decal_转管]
image: 管子旋转.png
total_frames: 7
frame: select(self.tags(includes= '转管'), (self.customTimer * 7) % 7, 0)
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 1
layer:onTop
isVisible:if self.tags(includes= '转管')
imageScale:0.68
onlyWhileAlive:true
teamColors:true
yOffsetRelative:11
[decal_炮塔3]
image: 主体动画1.png
total_frames: 16
frame: select(self.tags(includes= '切枪'), (self.customTimer * 16) % 16, 0)
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 1
layer:onTop
isVisible:if self.tags(includes= '切枪')
imageScale:0.68
onlyWhileAlive:true
teamColors:true
yOffsetRelative:-0.5
xOffsetRelative:-0.5
[action_bx]
displayType: action
price: 0
buildSpeed: 0
isVisible: false
autoTrigger: if self.isEnergyEmpty() and not self.tags(includes= '切枪') and not self.tags(includes= '转管')
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyAddTags: 切枪
alsoQueueAction: ax
resetCustomTimer: true
spawnEffects:CUSTOM:弹壳
[action_ax]
displayType: action
price: 0
buildSpeed: 1s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪
addResources:energy=2

[action_1]
price: 0
text: 收起ракетапусковая установка
buildSpeed: 1s
convertTo: 蜂刺导弹小组
displayType: action
iconImage: ROOT:/创世纪军事集团/单位特效/起立.png
description: 命令Расчёт ракет «Жало»收起оружиеи进行移动。\n-收起后将无法攻击，и失去护甲值增益，номожет移动。
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
[hiddenAction_离开地堡]
autoTrigger: if self.hasFlag(id=30) and not self.hasParent()
addResources: unsetFlag= 30,energy=-2
temporarilyRemoveTags: 切枪
convertTo: 蜂刺导弹小组
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
[hiddenAction_db]
temporarilyAddTags: 转管
[action_db1]
displayType: action
price: 0
buildSpeed: 0
isVisible: false
autoTrigger: if self.tags(includes= '转管')
highPriorityQueue: true
whenBuilding_cannotMove: true
alsoQueueAction: db2
resetCustomTimer: true

[action_db2]
displayType: action
price: 0
buildSpeed: 0.15s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 转管

[graphics]
total_frames: 1
image: 导弹支架.png
image_wreak: 死亡.png
image_turret: 火箭主体.png

imageScale: 0.68
turretImageScale: 0.68
teamColorsOnTurret: true
image_shadow: 影子.png

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8

turretTurnSpeed: 2
maxAttackRange: 350


[turret_1]
x: 0
y: 0
canShoot: false

[turret_2]
x: 0
y: 1
attachedTo: 1
slave: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
shoot_light: #FFFFEB88
shoot_flame: CUSTOM:烟雾2*3
projectile: 1
delay:1
#w#armup:30
invisible: true
canAttackCondition: if not self.tags(includes= '转管')
onShoot_triggerActions:db
energyUsage:1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头1')
[projectile_1]
@copyFromSection: template_爆炸
directDamage: 280
life: 6661
speed: 5
targetSpeed: 9
image: ROOT:/创世纪军事集团/单位特效/导弹.png
drawSize: 0.7
explodeEffect: CUSTOM:爆炸2,CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸2,CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:闪光
trailEffect: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_炮弹]
@copyFromSection: template_能源
areaDamage: 335
areaRadius: 65
life: 250
speed: 5
targetSpeed: 9
image: ROOT:/创世纪军事集团/单位特效/导弹.png
drawSize: 0.7
trailEffect: true
lightSize: 0.75
deflectionPower: -1
lightColor: #FFFFFF73
areaRadiusFromEdge: true
explodeEffect: CUSTOM:底色,CUSTOM:闪光2,CUSTOM:冲击波2
buildingDamageMultiplier: 1.2
explodeEffectOnShield:CUSTOM:底色,CUSTOM:闪光2,CUSTOM:冲击波2
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.7
ySpeedRelativeRandom: 0.6

hSpeed: 1


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.5
scaleTo: 0.5
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1
ySpeedRelativeRandom: 1

hSpeed: 1
dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 600
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 3
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡.ogg,ROOT:/创世纪军事集团/步兵特效/死亡3.ogg,ROOT:/创世纪军事集团/步兵特效/死亡4.ogg,ROOT:/创世纪军事集团/步兵特效/死亡5.ogg


[effect_冲击波]
stripIndex: shockwave
life: 70
scaleFrom: 0.3
scaleTo: 1.8
color: #FFF0AFA5

alpha: 1


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 0.7
scaleTo: 0.7
createWhenOverLiquid: false
createWhenOverLand: true


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸2]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg

alpha: 1.2


[effect_烟雾2]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.25

scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelative: -0.7
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.35
yOffsetRelative: -18
atmospheric: true
[effect_弹壳]
image: 弹壳.png
spawnChance: 1
life: 130
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.68
scaleTo: 0.68
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative: 0.1
ySpeedRelative: -0.6
xSpeedRelativeRandom: -0.05
ySpeedRelativeRandom: -0.2
yOffsetRelative: -10
hSpeed: 2
dirSpeedRandom: 10


[effect_底色]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.35
scaleTo: 0.35
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光2]
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2
scaleTo: 3
drawUnderUnits: false
atmospheric: false


[effect_冲击波2]
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 0.8
alpha: 0.8
drawUnderUnits: false
atmospheric: false



[movement]
movementType: LAND
moveSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0
moveSlidingMode: false

moveIgnoringBody: false


