


[core]
name: 镭射炮塔t1
price: 2750
maxHp: 2100
footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
copyFrom: ROOT:/通用特效/单位防护.ini
buildingToFootprintOffsetX: 20
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
buildingToFootprintOffsetY: 20
isBuilding: true
techLevel: 2
buildSpeed: 0.0025
buildingSelectionOffset: -8
armour: 2
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸2*1
radius: 19
displayRadius: 19
tags: 地面,建筑,防御建筑
energyMax: 80
energyRegen: 0.25
energyNeedsToRechargeToFull: true
isBio: false
softCollisionOnAll: 0
displayDescription: 【阶级t3】【建筑单位】【地面单位】【水上单位】（当部署在水上时）\n-战术定位：反群体装甲炮塔。武器配置：\n-▲激光炮X1 只能对地 能源伤害 反掩体 对护盾效果差\n-利用实验性透镜技术与反应堆结合而成的，\n-直接喷射热熔毁光束摧毁目标的实验炮台，\n-但需要注意，这种炮台两次射击之间必须充能，\n-并且仅对装甲有效。
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_炮塔影子]
image: 影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:1.5
xOffsetRelative:1.5
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 2
[decal_遮盖]
image: 炮塔.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.65
basePositionFromTurret: 2
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/小支撑.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-30
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.9
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/t1影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:4
onlyWhileAlive:true
alpha:0.65


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_升级]
convertTo: 镭射炮塔t2
displayType: action
text: 升级
price: 1500
buildSpeed: 10s

ai_isHighPriority: true
description: 提升镭射炮塔的等级，加固其结构强度并增加伤害和射程，\n-升级版本的镭射炮台强化了内置反应堆的充能速度，\n-可以更加迅速的向敌人喷射激光。


[graphics]
total_frames: 1
image: ROOT:/创世纪军事集团/建筑特效/防御塔t1底座.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/防御塔t1死亡.png
image_turret: 炮塔.png
image_back: ROOT:/通用特效/NO.png

#turretImageScale:0.9
image_shadow: NONE
dustEffect: true

image_offsetY: -4


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 12

turretTurnSpeed: 2.5
maxAttackRange: 360
shootDelay: 1
aimOffsetSpread: -0.01


[turret_1]
x: 0
y: 0
attachedTo: 2
projectile: 1
slave: true

invisible: true
turnSpeed: 2.5
turnSpeedAcceleration: 1.0
shoot_sound: NONE
shoot_sound_vol: 0.5

shoot_flame: NONE
canShoot: true
shoot_light: #FFFFBE67
canAttackCondition: if self.resource.xk < 1 and self.isEnergyRecharging


[turret_2]
x: 0
y: 21
canShoot: false
idleSweepAngle: 100
idleSweepDelay: 210

idleSweepSpeed: 0.2
canAttackCondition: if self.resource.xk < 1


[turret_3]
x: 0
y: 0
attachedTo: 2
projectile: 2
turnSpeed: 2.5

turnSpeedAcceleration: 1.0
shoot_sound: ROOT:/创世纪军事集团/建筑特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 180
canShoot: true

invisible: true
canAttackCondition: if self.resource.xk < 1


[turret_4]
x: 0
y: 0
attachedTo: 2
projectile: 3
slave: true

invisible: true
turnSpeed: 2.5
turnSpeedAcceleration: 1.0
shoot_sound: NONE
shoot_sound_vol: 0.5

canShoot: true
shoot_light: #FFFFBE67
canAttackCondition: if self.resource.xk < 1
shoot_flame: CUSTOM:光球
energyUsage: 2


[projectile_3]
@copyFromSection: template_能源
areaDamage: 90
areaRadius: 50
life: -4
instantReuseLast: true

instant: true
laserEffect: true
lightColor: #FFFFBE67
lightSize: 0.5
explodeEffect: CUSTOM:闪光

areaRadiusFromEdge: true
beamImage: ROOT:/创世纪军事集团/建筑特效/激光2.png
explodeEffectOnShield: CUSTOM:闪光
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
shieldDamageMultiplier: 0.75
[effect_闪光]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.7

scaleTo: 0.7
image: ROOT:/创世纪军事集团/建筑特效/光束.png
dirOffsetRandom: 180
alsoPlaySound: ROOT:/太空浪人/单位特效/激光.ogg


[projectile_1]
@copyFromSection: template_能源
directDamage: 10
life: -4
instant: true
frame: 33

explodeEffect: none
beamImage: ROOT:/创世纪军事集团/建筑特效/光.png
beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
color: #FFFFBE67
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
shieldDamageMultiplier: 0.75
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.42

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/单位特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_光球]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.4

scaleTo: 0.4
image: ROOT:/创世纪军事集团/单位特效/光球.png
alpha: 0.5


[projectile_2]
directDamage: 0
life: 0
frame: 33


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


