
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 创世纪铁穹防空系统t2
displayDescription: 【阶级t4】【长距离索敌】【防御类建筑】【建筑单位】【地面单位】【水上单位】（当部署在水上时）\n-战术定位:战略武器防御设施，\n-对于创世纪来讲，对付余晖的太空力量最实用的理论大概就是古人类的行星防御学说了。\n-以这套先进理论为基础的创世纪，很快就研发出了防御进攻两种方案：\n-后者是雷暴炮塔的雏形，而前者就是铁穹防空系统。\n-这台反导系统装备了包含拦截弹和重型防空导弹在内的多种弹药，\n-能够在执行区域拦截任务的同时进行高效率的防控工作。\n-铁穹的部署皆在为了限制余晖的航空航天力量，\n-对于创世纪而言，这座牢不可破的钢铁苍穹就是他们的天空守护神。
price: 18000,钍=300,bj= ${bjxq}
@global bjxq: 20
reclaimPrice: bj= ${bjxq}
maxHp: 70000
footprint: -7,-2,7,5
constructionFootprint: -7,-2,7,5
armour:85
techLevel: 1
buildSpeed: 45s
fogOfWarSightRange: 88
radius: 100
displayRadius: 100
copyFrom: ROOT:/通用特效/单位防护.ini
effectOnDeath: CUSTOM:烟雾s*4, CUSTOM:爆破*8,largeExplosion
unitsSpawnedOnDeath:建筑损毁
isBuilding: true
isBio: false
energyMax: 13
energyRegen: 0
energyNeedsToRechargeToFull: false
energyStartingPercentage: 0
tags: 导弹防御,地面,反高空,建筑
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_雷达1]
image: SHADOW:雷.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:86
xOffsetRelative:112
onlyWhileAlive:true
dirOffset:45
imageScale: 0.9
alpha:0.5
[decal_雷达]
image:雷.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:true
yOffsetRelative:88
xOffsetRelative:109
onlyWhileAlive:true
dirOffset:45
imageScale: 0.9
[decal_支撑]
image: ROOT:/创世纪军事集团/建筑特效/铁穹水下.png
total_frames: 1
layer: shadow
imageScale: 0.9
yOffsetRelative:-118
xOffsetRelative:0.5
onlyWhileAlive:true
isVisible:if self.isOverLiquid
alpha:0.45
[decal_地板]
image: ROOT:/创世纪军事集团/建筑特效/铁穹地板.png
total_frames: 1
layer: shadow
yOffsetRelative:-32
xOffsetRelative:0
onlyWhileAlive:true
isVisible:true
imageScale: 0.9
alpha:1
[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
yOffsetRelative:-5
xOffsetRelative:13
onlyWhileAlive:true
isVisible:true
imageScale: 0.9
alpha:0.5


[action_开盖]
autoTrigger:if self.energy>0.25 and not self.tags(includes= '开盖')
isVisible:false
temporarilyAddTags:开盖
playAnimation:部署
alsoQueueAction: 等着
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
buildSpeed: 0s
highPriorityQueue: true
[hiddenAction_等着]
isVisible: false
buildSpeed: 1.7s
temporarilyAddTags:开火
highPriorityQueue: true
[action_关盖]
autoTrigger:if self.energy<0.25 and self.tags(includes= '开盖')
isVisible:false
temporarilyRemoveTags:开盖,开火
stopLastAnimation: true
highPriorityQueue: true
playSoundAtUnit:  ROOT:/通用特效/部署.ogg
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[action_装弹]
price: 1500
text: 补充弹药
buildSpeed: 5s
isActive: if self.energyIncludingQueued(lessThan=13)
addResources: energy=1
pos: 0.1
displayRemainingStockpile: false
highPriorityQueue: false
canPlayerCancel: true
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/装填.png
isVisible:true
allowMultipleInQueue:true
description:为铁穹防空系统补充弹药。
isLocked:if self.isEnergyFull() or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: 弹药已满，或者补充弹药的队列已满

[action_开启导弹]
text: 开启防空导弹架
displayType: action
buildSpeed: 1s
pos: 0.4
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
iconImage: ROOT:/通用特效/开.png
temporarilyAddTags:能用导弹
isVisible: if not self.tags(includes= '能用导弹')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 开启防空导弹架，使铁穹防空系统能发射幻象导弹攻击空中和高空中的 非伴生 单位。\n-幻象巡航导弹将造成爆炸溅射伤害，并向爆点周围释放造成大量二次伤害的爆裂物。\n-同时幻象导弹拥有长距离索敌能力，但是每枚导弹将消耗0.25能量。
isLocked: if self.queueSize > 0.5
isLockedMessage: 其他动作进行中，请等待
[action_关闭导弹]
text: 停用防空导弹架
displayType: action
buildSpeed: 1s
pos: 0.4
displayRemainingStockpile: false
highPriorityQueue: true
price:0
canPlayerCancel: false
onlyOneUnitAtATime: false
temporarilyRemoveTags:能用导弹
isVisible: if self.tags(includes= '能用导弹')
whenBuilding_cannotMove: false
allowMultipleInQueue:false
description: 命令铁穹防空系统停用防空导弹发射架
iconImage: ROOT:/通用特效/关.png
isLocked: if self.queueSize > 0.5
isLockedMessage: 其他动作进行中，请等待
[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[action_长距离]
text: 长距离索敌
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 10
iconImage: ROOT:/通用特效/长距离.png
description: 该单位有能力射击极远距离上的被锁定单位。\n-允许铁穹防空系统在攻击 空中和高空单位 中的 被锁定 敌方单位时，\n-将射程提升至2200
[graphics]
total_frames: 1
image: 主体.png
image_wreak:ROOT:/创世纪军事集团/建筑特效/铁穹死.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9
image_offsetY: 5
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 1

turretTurnSpeed: 9999
turretMultiTargeting:true
maxAttackRange: 2200
shootDelay: 23

[turret_1]
x: -29
y: 15
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:冲击波,CUSTOM:烟雾*12
shoot_light: #FFEECCCC
projectile: 1
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay: 60
interceptProjectiles_withTags: 导弹2
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
#interceptProjectiles_andTargetingGroundUnderDistance:2200
energyUsage: 1
invisible: true
#战略防御常规
[turret_1x]
x: -29
y: 15
copyFrom: 1
interceptProjectiles_withTags: 天上战略
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战略防御天上

[turret_2]
x: -29
y: 15
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:冲击波,CUSTOM:烟雾*12
shoot_light: #FFEECCCC
projectile: 2
delay: 60
canOnlyAttackUnitsWithTags: 空降仓x
energyUsage: 1

[turret_3]
#普通对低空
x: -49
y: 20
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:冲击波1,CUSTOM:烟雾*6
shoot_light: #FFEECCCC
projectile: 3
size: 0
turnSpeed: 811
delay: 320
energyUsage: 0.5
canOnlyAttackUnitsWithoutTags:高空,伴生单位
limitingMinRange: 100
canAttackCondition: if self.resource.xk < 1 and self.tags(includes= '开火') and self.tags(includes= '能用导弹')
limitingRange:1200
[turret_4]
x: 1
y: 20
copyFrom: 3
delay:280
warmup:40

[turret_5]
#普通对高空
x: -49
y: 20
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:冲击波1,CUSTOM:烟雾*6
shoot_light: #FFEECCCC
projectile: 5
size: 0
turnSpeed: 811
delay: 320
energyUsage: 0.5
canOnlyAttackUnitsWithTags:高空
canOnlyAttackUnitsWithoutTags:伴生单位
limitingMinRange: 100
canAttackCondition: if self.resource.xk < 1 and self.tags(includes= '开火')  and self.tags(includes= '能用导弹')
limitingRange:1200
[turret_6]
x: 1
y: 20
copyFrom: 5
delay:280
warmup:40
[turret_7]
#长距离对低空
x: -49
y: 20
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:冲击波1,CUSTOM:烟雾*6
shoot_light: #FFEECCCC
projectile: 3
size: 0
turnSpeed: 811
delay: 320
energyUsage: 0.5
canOnlyAttackUnitsWithTags:被锁定
canOnlyAttackUnitsWithoutTags:高空,伴生单位
limitingMinRange: 1200
canAttackCondition: if self.resource.xk < 1 and self.tags(includes= '开火') and self.tags(includes= '能用导弹')
[turret_8]
x: 1
y: 20
copyFrom: 7
delay:280
warmup:40
[turret_9]
#长距离对高空
x: -49
y: 20
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:冲击波1,CUSTOM:烟雾*6
shoot_light: #FFEECCCC
projectile: 5
size: 0
turnSpeed: 811
delay: 320
energyUsage: 0.5
canOnlyAttackUnitsWithTags:被锁定
canOnlyAttackUnitsWithoutTags:低空,伴生单位
limitingMinRange: 1200
canAttackCondition: if self.resource.xk < 1 and self.tags(includes= '开火')  and self.tags(includes= '能用导弹')
[turret_10]
x: 1
y: 20
copyFrom: 9
delay:280
warmup:40
[projectile_1]
areaDamage: 0
areaRadius: 0
life: 120
speed: 65
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 1
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光
trailEffectRate: 0.01
targetSpeedAcceleration:999
targetSpeed:85
[projectile_2]
directDamage: 99999
life: 120
speed: 50
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 1
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光
trailEffectRate: 0.01
mutator3_ifUnitWithTags: 空降仓x
mutator3_directDamageMultiplier: 9999


[projectile_3]
life: 50
speed: 1
targetSpeed: 4
largeHitEffect: true
drawSize: 0.9
image: 大导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 75
ballistic_delaymove_height: 50
spawnProjectilesOnEndOfLife: 4
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片
autoTargetingOnDeadTarget: true
[projectile_4]
@copyFromSection: template_爆炸
areaDamage: 3000
areaRadiusFromEdge: true
areaRadius: 90
deflectionPower: -1
life: 600
speed: 12
image: 大导弹1.png
targetSpeed: 14
drawSize:0.9
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
explodeEffectOnShield: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
trailEffect:true
trailEffectRate: 0.65
turnSpeed: 3
spawnUnit: 幻象导弹中介(offsetHeight=70,offsetDir=0,addResources=唉:3)
autoTargetingOnDeadTarget: true
[projectile_5]
@copyFromSection:projectile_3
ballistic: true
ballistic_height: 145
ballistic_delaymove_height: 120
spawnProjectilesOnEndOfLife: 6
[projectile_6]
@copyFromSection: template_爆炸
areaDamage: 3000
areaRadiusFromEdge: true
areaRadius: 90
deflectionPower: -1
life: 600
speed: 12
image: 大导弹1.png
targetSpeed: 14
drawSize:0.9
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
explodeEffectOnShield: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
trailEffect:true
trailEffectRate: 0.65
turnSpeed: 3
spawnUnit: 幻象导弹中介(offsetHeight=70,offsetDir=0,addResources=唉:1.5)
autoTargetingOnDeadTarget: true

#——————————发射效果
[effect_烟雾]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 135
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 2
scaleTo: 3.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.45
atmospheric: true
[effect_冲击波1]
stripIndex: shockwave
life: 33
scaleFrom: 0.4
scaleTo: 1.6
alpha: 1
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: true
scaleFrom: 0.6
scaleTo: 1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: false
[effect_导弹碎片]
#priority: low
image: 大导弹壳.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
ySpeedRelative:-1
hSpeed: 2.5
dirSpeedRandom: 10
#——————————反导爆炸

[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 0.1
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.6
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸1.ogg
alpha: 1.2
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
#——————————幻象爆炸
[effect_爆炸hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.44
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/重型爆炸.wav
alwayStartDirAtZero: true
[effect_爆炸hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/12.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.21
alwayStartDirAtZero: true
[effect_闪光hx]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 8
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.85
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_烟雾s]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 30
yOffsetRelativeRandom: 30
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:45
yOffsetRelativeRandom:55
delayedStartTimerRandom:30
[arm_1]
x: 122
y: -10.5
image_end:ROOT:/创世纪军事集团/建筑特效/铁穹风扇.png
image_end_teamColors: true
spinRate:7
drawOverBody: true
[arm_2]
x: 0
y: -5
image_end:主体.png
drawOverBody: true
image_end_teamColors: true

[arm_3]
x: 0
y: -5
image_end: 主体损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_4]
x: 0
y: -5
image_end: led.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_5]
x: -54.5
y: 35
image_end:ROOT:/创世纪军事集团/建筑特效/左后后.png
drawOverBody: true
image_end_teamColors: true
[arm_6]
x: -4
y: 35
image_end:ROOT:/创世纪军事集团/建筑特效/右后后.png
drawOverBody: true
image_end_teamColors: true

[arm_7]
x: -49.5
y: 41
image_end:ROOT:/创世纪军事集团/建筑特效/左后.png
drawOverBody: true
image_end_teamColors: true
[arm_8]
x: -9.5
y: 41
image_end:ROOT:/创世纪军事集团/建筑特效/右后.png
drawOverBody: true
image_end_teamColors: true

[arm_9]
x: -54.5
y: 35
image_end:ROOT:/创世纪军事集团/建筑特效/左后后遮盖.png
drawOverBody: true
image_end_teamColors: true
[arm_10]
x: -4
y: 35
image_end:ROOT:/创世纪军事集团/建筑特效/右后后遮盖.png
drawOverBody: true
image_end_teamColors: true
[arm_11]
x: -29.5
y: 41
image_end:ROOT:/创世纪军事集团/建筑特效/锅盖.png
drawOverBody: true
image_end_teamColors: true

[arm_12]
x: -49.5
y: 25
image_end:ROOT:/创世纪军事集团/建筑特效/左前.png
drawOverBody: true
image_end_teamColors: true
[arm_13]
x: -9.5
y: 25
image_end:ROOT:/创世纪军事集团/建筑特效/右前.png
drawOverBody: true
image_end_teamColors: true


[arm_14]
x: -54.5
y: 8
image_end:ROOT:/创世纪军事集团/建筑特效/左前前.png
drawOverBody: true
image_end_teamColors: true
[arm_15]
x: -4
y: 8
image_end:ROOT:/创世纪军事集团/建筑特效/右前前.png
drawOverBody: true
image_end_teamColors: true


[animation_部署]
#onActions: attack
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}
arm15_0s: {x:0, y:0, dir:0}

arm5_0.3s: {x:0, y:0, dir:0}
arm6_0.3s: {x:0, y:0, dir:0}
arm7_0.3s: {x:0, y:0, dir:0}
arm8_0.3s: {x:0, y:0, dir:0}
arm9_0.3s: {x:0, y:0, dir:0}
arm10_0.3s: {x:0, y:0, dir:0}
arm11_0.3s: {x:-31, y:-41, dir:0}
arm12_0.3s: {x:0, y:0, dir:0}
arm13_0.3s: {x:0, y:0, dir:0}
arm14_0.3s: {x:0, y:0, dir:0}
arm15_0.3s: {x:0, y:0, dir:0}


arm5_1s: {x:0, y:0, dir:0}
arm6_1s: {x:0, y:0, dir:0}
arm7_1s: {x:-9, y:-9, dir:0}
arm8_1s: {x:9, y:-9, dir:0}
arm9_1s: {x:0, y:0, dir:0}
arm10_1s: {x:0, y:0, dir:0}
arm11_1s: {x:-31, y:-41, dir:0}
arm12_1s: {x:-9, y:-14, dir:0}
arm13_1s: {x:9, y:-14, dir:0}
arm14_1s: {x:0, y:0, dir:0}
arm15_1s: {x:0, y:0, dir:0}


arm5_1.3s: {x:0, y:5, dir:0}
arm6_1.3s: {x:0, y:5, dir:0}
arm7_1.3s: {x:-9, y:-5, dir:0}
arm8_1.3s: {x:9, y:-5, dir:0}
arm9_1.3s: {x:0, y:5, dir:0}
arm10_1.3s: {x:0, y:5, dir:0}
arm11_1.3s: {x:-31, y:-41, dir:0}
arm12_1.3s: {x:-9, y:-24, dir:0}
arm13_1.3s: {x:9, y:-24, dir:0}
arm14_1.3s: {x:0, y:-10, dir:0}
arm15_1.3s: {x:0, y:-10, dir:0}


arm5_1.6s: {x:-10, y:5, dir:0}
arm6_1.6s: {x:10, y:5, dir:0}
arm7_1.6s: {x:-19, y:-5, dir:0}
arm8_1.6s: {x:19, y:-5, dir:0}
arm9_1.6s: {x:-10, y:5, dir:0}
arm10_1.6s: {x:10, y:5, dir:0}
arm11_1.6s: {x:-31, y:-41, dir:0}
arm12_1.6s: {x:-19, y:-24, dir:0}
arm13_1.6s: {x:19, y:-24, dir:0}
arm14_1.6s: {x:-10, y:-10, dir:0}
arm15_1.6s: {x:10, y:-10, dir:0}

arm5_999999s: {x:-10, y:5, dir:0}
arm6_999999s: {x:10, y:5, dir:0}
arm7_999999s: {x:-19, y:-5, dir:0}
arm8_999999s: {x:19, y:-5, dir:0}
arm9_999999s: {x:-10, y:5, dir:0}
arm10_999999s: {x:10, y:5, dir:0}
arm11_999999s: {x:-31, y:-41, dir:0}
arm12_999999s: {x:-19, y:-24, dir:0}
arm13_999999s: {x:19, y:-24, dir:0}
arm14_999999s: {x:-10, y:-10, dir:0}
arm15_999999s: {x:10, y:-10, dir:0}

[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.07
maxEachBase: 1
maxGlobal: 4
[resource_唉]
displayName: 唉
displayNameShort: 唉
displayColor: #FF9D00FF
priority: 1
hidden: true
