


[core]
name: 追迹者无人机
displayText: Дрон «Преследователь»
class: CustomUnitMetadata
displayDescription: 【Уровень t4】【Механический юнит】【Воздушный юнит】【Беспилотный юнит】【сопровождающий типдрон】【сопровождающий юнит】【Высотный юнит】【Защита от тактического оружия】【Защита от стратегического оружия】\n-Тактическое назначение:侦查/против导 дрон，не может транспортироваться。。\n-без вооружения，высотныйюнит。защита от стратегического оружия，тактическое оружиеоборона。\n-BFGнесёт средний侦查дрон，используется для侦查敌情и引导пушкаудар。
price: 0
maxHp: 5500
techLevel: 1
buildSpeed: 16s
showInEditor: false
fogOfWarSightRange: 55

armour: 3
radius: 29
displayRadius: 29
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 10
canOnlyBeAttackedByUnitsWithTags:反高空
tags: 飞机,高空,追迹者,保险丝,伴生单位,无人单位
energyMax: 40
energyRegen: 0
energyNeedsToRechargeToFull: false

[action_保险丝]
autoTrigger: if self.hasParent and self.energy>0
isVisible: false
setResourcesWithLogic:energy=0

[hiddenAction_保险丝1]
autoTrigger: if self.hasParent and not self.tags(includes= '保险丝')
temporarilyAddTags: 保险丝
[action_补充能量]
autoTrigger: if not self.hasParent and self.energy<40 and self.tags(includes= '保险丝')
isVisible: false
addResources: energy=40
temporarilyRemoveTags: 保险丝
[hiddenAction_自杀]
autoTrigger:if numberOfUnitsInTeam(lessThan=1, withTag='BFG')
addResources: hp= -9999999
[hiddenAction_disconnect]
autoTrigger:if parent.tags(includes= '发射侦查')
disconnectFromParent: true
[hiddenAction_召回]
autoTrigger:if  numberOfUnitsInTeam(greaterThan=0, withTag='召回')
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged:家
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto
#addWaypoint_target_randomUnit_maxRange: 99999
addWaypoint_target_nearestUnit_maxRange:99999
[action_akm]
autoTrigger: if self.hasParent and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack
[action_bkm]
autoTrigger: if not self.hasParent and self.hasFlag(id=1)
stopLastAnimation: true
isVisible: false
addResources: unsetFlag=1
playAnimation: attack1
[action_高空]
text: высотныйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: находится вочень высокийвысокий度 истребительибоевой корабль。\n-вэтотвысокий度низ，толькоесть поверхностьиПустовспециальный против высотныхюнит，а такжевысотныйюнитможетатакадоуказанныйюнит，\n-одновременно，большинствовысотныйюнитможет互相атака，иможетатакаобычныйвоздушный юнит，\n-толькоестьспециальный высотныйюнитможетпо землеатака。
[action_雷达]
text: Радарное сканирование
allowMultipleInQueue: false
description: -Прикажите высотному разведчику просканировать землю，\n-Открывает обзор в целевой зоне на 5,5 секунд。\n-если离雷达центрдостаточновходить，томожетпозволятьпротивник隐формаюнитнедействителен。
iconImage: ROOT:/通用特效/雷达.png
onlyOneUnitAtATime: true
price: 0
fireTurretXAtGround: 雷达
highPriorityQueue: true
addActionCooldownTime: 20s
[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 1
image_shadow: NONE
movementEffect: CUSTOM:火1,CUSTOM:火2
movementEffectRate: 0.4
#drawLayer:air
[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 1.5
maxAttackRange: 99999
isFixedFiring: false
[turret_雷达]
x: 0
y: 0
projectile: 雷达
#limitingRange: 99999
#limitingMinRange:300
canAttack: false
invisible: true
shoot_sound: ROOT:/通用特效/扫描.ogg
shoot_sound_vol: 1
[projectile_雷达]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true
instant: true
spawnUnit: 雷达
explodeEffect: none
explodeEffectOnShield: none
[turret_26]
x: 5
y: 10
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 战术
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:10
interceptProjectiles_withTags:战术武器
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -10
energyUsage: 1
invisible: true
shoot_flame: CUSTOM:烟雾1*5, CUSTOM:冲击波1


[turret_26x]
x: 5
y: 10
copyFrom: 26
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战术防御天上






[turret_27]
x: 5
y: 10
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 战术
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:10
interceptProjectiles_withTags:导弹2
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -10
energyUsage: 5
invisible: true
shoot_flame: CUSTOM:烟雾1*5, CUSTOM:冲击波1

[turret_27x]
x: 5
y: 10
copyFrom: 27
interceptProjectiles_withTags: 天上战略
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战略防御天上




[projectile_战术]
areaDamage: 0
areaRadius: 0
life: 120
speed: 40
targetSpeed: 40
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 1
largeHitEffect: true
deflectionPower: -1
trailEffectRate: 0.8
[effect_烟雾1]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波1]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1
[arm_1]
x: 0
y: 28
image_end: 机头.png
image_end_teamColors: true
drawOverBody: true
image_end_shadow: SHADOW:机头.png
[arm_2]
x: 0
y: -30
image_end: 尾翼.png
image_end_teamColors: true
drawOverBody: true
image_end_shadow: SHADOW:尾翼.png
[arm_3]
x: -42
y: 3
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: true
image_end_shadow: SHADOW:左翼.png
[arm_4]
x: 42
y: 3
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: true
image_end_shadow: SHADOW:右翼.png

[arm_5]
x: 0
y: -19
image_end: 扇叶.png
drawOverBody: true
spinRate: 25
image_end_shadow: SHADOW:扇叶.png
[arm_6]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true
image_end_shadow: SHADOW:主体.png

[animation_attack]
arm1_0s: {x:0, y:0,dir:0}
arm2_0s: {x:0, y:0,dir:0}
arm3_0s: {x:0, y:0,dir:0}
arm4_0s: {x:0, y:0,dir:0}
arm5_0s: {x:0, y:0,dir:0}

arm1_1s: {x:0, y:-18,dir:0}
arm2_1s: {x:0, y:20,dir:0}
arm3_1s: {x:22, y:0,dir:0}
arm4_1s: {x:-22, y:0,dir:0}
arm5_1s: {x:0, y:20,dir:0}

arm1_99999s: {x:0, y:-18,dir:0}
arm2_99999s: {x:0, y:20,dir:0}
arm3_99999s: {x:22, y:0,dir:0}
arm4_99999s: {x:-22, y:0,dir:0}
arm5_99999s: {x:0, y:20,dir:0}

[animation_attack1]
arm1_0s: {x:0, y:0,dir:0}
arm2_0s: {x:0, y:0,dir:0}
arm3_0s: {x:0, y:0,dir:0}
arm4_0s: {x:0, y:0,dir:0}
arm5_0s: {x:0, y:0,dir:0}

[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.05
image: SHARED:light_50.png
alpha: 0.5
color: #BBBBFFEE
xOffsetRelative	: 25
ySpeedRelative: -2
yOffsetRelative	: -15
drawUnderUnits: false
[effect_火2]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.05
image: SHARED:light_50.png
alpha: 0.5
color: #BBBBFFEE
xOffsetRelative	: -25
ySpeedRelative: -2
yOffsetRelative	: -15
drawUnderUnits: false
[movement]
movementType: AIR
moveSpeed: 4
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.03
maxTurnSpeed: 3
#startingHeightOffset: 
turnAcceleration: 1
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: false
targetHeight: 140


