


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 耀斑级重型驱逐舰1
displayText: 耀斑级重型驱逐舰
displayDescription: -耀斑级重型驱逐舰的原型来自亚尔佛里德共和国的超级战舰，伯亚斯级无畏舰。\n-伯亚斯级无畏舰虽然在当时无人能敌，但其极低的产量和惊人的维护需求，\n-使得亚尔佛里德的科学家们不得不研发另一款战舰来充当主力舰。\n-在伯亚斯级的基础上改造后就诞生了耀斑级，或者不如说耀斑级就是伯亚斯级的缩比版。\n-耀斑级继承了伯亚斯的绝大部分优点，同时又拥有极高的可靠性而名声大噪。\n-之后又用自身强大的实力击败了一系列竞争对手，稳坐共和国主力舰的宝座。\n-帝国分裂后，伯亚斯家族的残党试图重新复活他们那早已荒废的王座——伯亚斯级来对抗余辉。\n-但受限于当时艰苦的条件，于是耀斑级得以重见天日，\n-耀斑级至今仍是太空浪人手中为数不多的具有远程狙击能力的战舰。\n-常规模式下只对空，能源伤害，主炮模式下动能伤害，对地对空。
class: CustomUnitMetadata
fogOfWarSightRange: 45
maxHp: 24000
price: 12000,awz= ${awzxq}
@global awzxq: 250
reclaimPrice: awz= ${awzxq}
shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 50s

availableInDemo: true
radius: 90
displayRadius: 90

isBio: false
selfRegenRate: 0.2
transportSlotsNeeded: 20
#effectOnDeathGroundCollision:CUSTOM:爆炸x*1
tags: 飞机,高空,耀斑,反高空
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 耀斑
canOnlyBeAttackedByUnitsWithTags:反高空

showInEditor: false
softCollisionOnAll: 20
armour: 25
copyFrom: ROOT:/通用特效/单位防护.ini


[action_无损]
text: 强化结构
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/无损.png
isLockedMessage: 该单位不会因为生命减少而变为战损状态
[action_高空]
text: 高空单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的战机和战舰。\n-在此高度下，只有地面和空中特殊的反高空单位，以及高空单位才能攻击到该单位，\n-同时，大部分高空单位可以互相攻击，并可以攻击普通空中单位，\n-只有特殊的高空单位才能对地攻击。


[action_xx]
displayType: action
price: 0
buildSpeed: 3s
isVisible: true
#playSoundAtUnit: 部署.ogg

text: 收起主炮
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署1
isLocked: if self.isAttacking() or self.resource.awz<0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
canPlayerCancel: false

addResources: unsetFlag= 1
description: 主动收起主炮，使用副炮进行攻击。\n-不能在攻击中收起主炮
convertTo: 耀斑级重型驱逐舰
iconImage: ROOT:/通用特效/收起主炮.png


[action_闪光]
autoTrigger: true
text: TRIGGER
buildSpeed: 0s
price: 0
isVisible: false

spawnEffects: CUSTOM:光粒子*3,CUSTOM:闪


[hiddenAction_↯a]
autoTrigger: if self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: 缺少暗物质
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[graphics]
total_frames: 3
image: 身子.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
turretImageScale: 0.8
animation_moving_start: 2

animation_moving_end: 2
animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3

movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3,CUSTOM:火4
movementEffectRate: 1.5


[attack]
canAttack: true
canAttackFlyingUnits: if self.queueSize < 0.5 and self.resource.awz>-1
canAttackLandUnits: if self.queueSize < 0.5 and self.resource.awz>-1
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 1.3
turretMultiTargeting: false
maxAttackRange: 1200
shootDelay: 0
isFixedFiring: true




[turret_5]
x: 0
y: 0
projectile: 13
limitingMinRange: 300
canShoot: false
turnSpeed: 0.75
turnSpeedAcceleration: 0.03
invisible: true


[turret_6]
x: 0
y: 140
projectile: 13
attachedTo: 5
canShoot: true
turnSpeed: 0.75
turnSpeedAcceleration: 0.03
slave: true
shoot_flame: CUSTOM:冲击波zz,CUSTOM:粒子*2,CUSTOM:闪光
delay: 60
invisible: true
limitingMinRange: 300

canAttackLandUnits: false


[turret_7]
x: 0
y: 140
projectile: 1
canShoot: true
shoot_sound: 大主炮音效.ogg
turnSpeed: 0.75
turnSpeedAcceleration: 0.03
shoot_sound_vol: 1.5
attachedTo: 5
warmup: 4s
limitingMinRange: 300
#warmupStartEffect:CUSTOM:气浪,CUSTOM:粒子*3,CUSTOM:旋转*1

chargeEffectImage: 闪光.png
shoot_flame: CUSTOM:烟雾x*7,CUSTOM:闪光x,CUSTOM:聚变,CUSTOM:冲击波
delay: 5s
canAttackLandUnits: false
slave: true


[turret_8]
x: 0
y: 140
projectile: 13
attachedTo: 5
canShoot: true
turnSpeed: 0.75
turnSpeedAcceleration: 0.03
slave: true
shoot_flame: CUSTOM:冲击波zz,CUSTOM:粒子*2,CUSTOM:闪光
delay: 60
invisible: true
limitingMinRange: 300

canAttackFlyingUnits: false
limitingRange: 800


[turret_11]
x: 0
y: 140
projectile: 2
canShoot: true
shoot_sound: 大主炮音效.ogg
turnSpeed: 0.75
turnSpeedAcceleration: 0.03
shoot_sound_vol: 1.5
attachedTo: 5
warmup: 4s
limitingMinRange: 300
#warmupStartEffect:CUSTOM:气浪,CUSTOM:粒子*3,CUSTOM:旋转*1

chargeEffectImage: 闪光.png
shoot_flame: CUSTOM:烟雾x*7,CUSTOM:闪光x,CUSTOM:聚变,CUSTOM:冲击波
delay: 5s
limitingRange: 800
canAttackFlyingUnits: false

slave: true


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[turret_9]
x: 55
y: -86
image: 主炮.png
canShoot: false
limitingAngle: 100

delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200
aimOffsetSpread: -0.01

turnSpeed: 0.75
turnSpeedAcceleration: 0.03
size: 12
idleDir: 45


[turret_10]
x: -55
y: -86
image: 主炮.png
canShoot: false
limitingAngle: 100

delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200
aimOffsetSpread: -0.01

turnSpeed: 0.75
turnSpeedAcceleration: 0.03
size: 12
idleDir: -45


[projectile_1]
@copyFromSection: template_动能
directDamage: 10000
life: 20
instant: true
laserEffect: true

explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光m,CUSTOM:冲击波m,CUSTOM:聚变m,CUSTOM:冲击波1m,CUSTOM:电球m,CUSTOM:粒子1*25
explodeEffect: CUSTOM:底色,CUSTOM:闪光m,CUSTOM:冲击波m,CUSTOM:聚变m,CUSTOM:冲击波1m,CUSTOM:电球m,CUSTOM:粒子1*25
lightSize: 0.75
beamImage: 激光.png
#color:#FFFF1200
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2
mutator7_areaDamageMultiplier: 2

[projectile_2]
@copyFromSection: template_动能
areaDamage: 6000
areaRadius: 150
life: 400
lightSize: 1

largeHitEffect: true
speed: 9
#targetGround:true
trailEffect: CUSTOM:尾巴
drawSize: 1

explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光m,CUSTOM:冲击波m,CUSTOM:聚变m,CUSTOM:冲击波1m,CUSTOM:电球m,CUSTOM:粒子1*25
explodeEffect: CUSTOM:底色,CUSTOM:闪光m,CUSTOM:冲击波m,CUSTOM:聚变m,CUSTOM:冲击波1m,CUSTOM:电球m,CUSTOM:粒子1*25
image: ROOT:/太空浪人/单位特效/星星1.png
deflectionPower: -1
trailEffectRate: 2

areaRadiusFromEdge: true
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2
mutator7_areaDamageMultiplier: 2

[arm_1]
x: 0
y: -33
image_end: 1左.png
image_end_teamColors: true
drawOverBody: false

lockMovement: true


[arm_2]
x: 0
y: -33
image_end: 1右.png
image_end_teamColors: true
drawOverBody: false

lockMovement: true


[arm_3]
x: 0
y: 101
image_end: 2.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 0
y: 140
image_end: 2.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 0
y: 20
image_end: 3.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:3.png


[arm_6]
x: 0
y: 20
image_end: 4.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:4.png


[arm_7]
x: 0
y: 20
image_end: 5.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:5.png


[arm_8]
x: 0
y: -35
image_end: 6.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_9]
x: 0
y: -10
image_end: 7.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_10]
x: 0
y: -60
image_end: 8.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_11]
x: -31
y: 25
image_end: 9左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_12]
x: 31
y: 25
image_end: 9右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_13]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_14]
x: -44
y: 70
image_end: 10左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:10左.png


[arm_15]
x: 44
y: 70
image_end: 10右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:10右.png


[animation_attack]
blendIn: 1s
blendOut: 2s
arm11_1s: {x:14, y:0}
arm11_950s: {x:14, y:0}
arm12_1s: {x:-14, y:0}

arm12_950s: {x:-14, y:0}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm11_1s: {x:0, y:0}
arm12_1s: {x:0, y:0}


[effect_火1]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 15
yOffsetRelative	: -138


[effect_火2]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: -15
yOffsetRelative	: -138


[effect_火3]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 34
yOffsetRelative	: -128


[effect_火4]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: -34
yOffsetRelative	: -128


[animation_部署1]
arm1_0s: {x:0, y:0}
arm2_0s: {x:0, y:0}
arm3_0s: {x:0, y:0}
arm4_0s: {x:0, y:0}
arm5_0s: {x:0, y:0}

arm6_0s: {x:0, y:0}
arm7_0s: {x:0, y:0}
arm9_0s: {x:0, y:0}
arm10_0s: {x:0, y:0}
arm14_0s: {x:0, y:0}

arm15_0s: {x:0, y:0}
arm3_1.5s: {x:0, y:0}
arm4_1.5s: {x:0, y:0}
arm5_1.5s: {x:0, y:132}
arm6_1.5s: {x:0, y:78}

arm7_1.5s: {x:0, y:39}
arm14_1.5s: {x:0, y:30}
arm15_1.5s: {x:0, y:30}
arm1_3s: {x:-38, y:0}
arm2_3s: {x:38, y:0}

arm3_3s: {x:0, y:-31}
arm4_3s: {x:0, y:-61}
arm9_3s: {x:0, y:-20}
arm10_3s: {x:0, y:20}
arm14_3s: {x:10, y:45}

arm15_3s: {x:-10, y:45}


[effect_光粒子]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 160
fadeOut: true
attachedToUnit: true

color: #FFFF1200
fadeInTime: 4
scaleFrom: 0.1
scaleTo: 0.5
alpha: 0.55

drawUnderUnits: false
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.17

ySpeedAbsoluteRandom: 0.17
yOffsetRelative	: -35


[effect_闪]
life: 40
#spawnChance: 0.9
priority: critical
attachedToUnit: true
scaleFrom: 1

scaleTo: 1
image: 闪.png
#dirOffsetRandom:180
yOffsetRelative	: -35
alpha: 0.8

fadeOut: true


[effect_冲击波zz]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 0.1
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_粒子]
priority: critical
image: 粒子.png
dirOffsetRandom: 200
dirSpeed: -2
dirSpeedRandom: 1.5

life: 100
scaleFrom: 0.7
scaleTo: 0
alpha: 0.8
drawUnderUnits: false

attachedToUnit: true
atmospheric: false
#xOffsetRelative	:-10


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_烟雾x]
#priority:critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 100
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 2
scaleTo: 5
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 2
xSpeedRelativeRandom: 1

#yOffsetRelative: 2
ySpeedRelative: 1
atmospheric: true


[effect_粒子1]
spawnChance: 1
createWhenZoomedOut: false
life: 80
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom: 0.2
scaleTo: 0.55

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 4.5

ySpeedRelativeRandom: 5
#atmospheric: true


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 9
scaleTo: 9

drawUnderUnits: true
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 2.3
scaleTo: 2.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 1.4
alpha: 0.8
drawUnderUnits: false
#_____________________________


[effect_底色]
priority: critical
image: ROOT:/太空浪人/单位特效/收缩2.png
life: 140
fadeOut: true
attachedToUnit: false

scaleFrom: 1.2
scaleTo: 1.2
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_聚变m]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 3.3
scaleTo: 3.3
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_闪光m]
#priority:critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 8
scaleTo: 8

drawUnderUnits: true
atmospheric: false


[effect_电球m]
priority: critical
attachedToUnit: false
scaleFrom: 1.1
scaleTo: 1.1
image: ROOT:/太空浪人/单位特效/电球.png

total_frames: 5
animateFrameStart: 0
animateFrameEnd: 4
animateFramePingPong: true
animateFrameSpeed: 0.2

life: 300
alwayStartDirAtZero: true


[effect_冲击波1m]
life: 130
priority: critical
attachedToUnit: false
scaleFrom: 1.1
scaleTo: 2.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
color: #FFFF1200
drawUnderUnits: true


[effect_冲击波m]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.7
alpha: 0.8
drawUnderUnits: false
atmospheric: true

#_____________________


[effect_尾巴]
#priority:critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false

fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.7
alpha: 0.8
drawUnderUnits: false

yOffsetRelative	: -5


[effect_爆炸mm]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.5

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[movement]
movementType: AIR
moveSpeed: 0.8
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0
maxTurnSpeed: 0.75
turnAcceleration: 0.01
targetHeightDrift: 0.3

slowDeathFall: false
targetHeight: 140


[ai]
buildPriority: 0.9


