


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 耀斑级重型驱逐舰
displayDescription: -耀斑级重型驱逐舰的原型来自亚尔佛里德共和国的超级战舰，伯亚斯级无畏舰。\n-伯亚斯级无畏舰虽然在当时无人能敌，但其极低的产量和惊人的维护需求，\n-使得亚尔佛里德的科学家们不得不研发另一款战舰来充当主力舰。\n-在伯亚斯级的基础上改造后就诞生了耀斑级，或者不如说耀斑级就是伯亚斯级的缩比版。\n-耀斑级继承了伯亚斯的绝大部分优点，同时又拥有极高的可靠性而名声大噪。\n-之后又用自身强大的实力击败了一系列竞争对手，稳坐共和国主力舰的宝座。\n-帝国分裂后，伯亚斯家族的残党试图重新复活他们那早已荒废的王座——伯亚斯级来对抗余辉。\n-但受限于当时艰苦的条件，于是耀斑级得以重见天日，\n-耀斑级至今仍是太空浪人手中为数不多的具有远程狙击能力的战舰。\n-常规模式下只对空，能源伤害，主炮模式下动能伤害，对地对空对高空。
class: CustomUnitMetadata
maxHp: 24000
price: 12000,awz= ${awzxq}
canOnlyBeAttackedByUnitsWithTags:反高空
@global awzxq: 250
reclaimPrice: awz= ${awzxq}
shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 50s

availableInDemo: true
radius: 90

displayRadius: 90

isBio: false
selfRegenRate: 0.2
transportSlotsNeeded: 20
#effectOnDeathGroundCollision:CUSTOM:爆炸x*1
tags: 飞机,高空,耀斑,反高空
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 耀斑
softCollisionOnAll: 20
armour: 25
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 34


[hiddenAction_↯a]
autoTrigger: if self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: 缺少暗物质
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true
[action_高空]
text: 高空单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的战机和战舰。\n-在此高度下，只有地面和空中特殊的反高空单位，以及高空单位才能攻击到该单位，\n-同时，大部分高空单位可以互相攻击，并可以攻击普通空中单位，\n-只有特殊的高空单位才能对地攻击。


[action_无损]
text: 强化结构
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/无损.png
isLockedMessage: 该单位不会因为生命减少而变为战损状态


[action_a]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=750, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_b]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=750, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[action_xx]
displayType: action
price: 0
buildSpeed: 3s
isVisible: true
#playSoundAtUnit: 部署.ogg

text: 展开主炮
whenBuilding_cannotMove: true
#whenBuilding_playAnimation: 部署1
canPlayerCancel: false
description: 展开战舰中部的巨型粒子脉冲光束轰炸敌人，\n-对地面敌人造成每次6000点动能AOE伤害，对空和高空则是每次10000点动能点伤害。\n-对极端重型单位伤害加成，\n-但使用主炮会禁用所有其他武器。不能在交战中展开主炮。

isLocked: if self.isAttacking() or self.resource.awz<0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
whenBuilding_triggerAction: bb
convertTo: 耀斑级重型驱逐舰1
iconImage: ROOT:/通用特效/展开主炮.png


[hiddenAction_bb]
stopLastAnimation: true
playAnimation: 部署1


[graphics]
total_frames: 3
image: 身子.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
turretImageScale: 0.8
animation_moving_start: 2

animation_moving_end: 2
animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3

movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3,CUSTOM:火4
movementEffectRate: 1.5


[attack]
canAttack: true
canAttackFlyingUnits: if self.queueSize < 0.5 and self.resource.awz>-1
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 750
shootDelay: 0


[turret_1]
invisible: true
x: -38
y: -43
idleDir: -90
projectile: 1

size: 0
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 65

canAttackMaxAngle: 181
limitingMinRange: 200
canOnlyAttackUnitsWithTags:高空

[turret_2]
invisible: true
x: -38
y: -23
idleDir: -90
projectile: 1

size: 0
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 65

warmup: 5
canAttackMaxAngle: 181
limitingMinRange: 200
canOnlyAttackUnitsWithTags:高空

[turret_3]
invisible: true
x: 38
y: -43
idleDir: 90
projectile: 1

size: 0
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 65

warmup: 10
canAttackMaxAngle: 181
limitingMinRange: 200
canOnlyAttackUnitsWithTags:高空

[turret_4]
invisible: true
x: 38
y: -23
idleDir: 90
projectile: 1

size: 0
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 65

warmup: 15
canAttackMaxAngle: 181
limitingMinRange: 200
canOnlyAttackUnitsWithTags:高空

[turret_5]
x: 19
y: 25
image: 副炮.png
canShoot: false
limitingAngle: 50

idleDir: 90
canOnlyAttackUnitsWithTags:高空

[turret_6]
x: 0
y: 10
canShoot: true
#recoilOffset:-2
projectile: 2

invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.35
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*2

delay: 18
attachedTo: 5
slave: true
size: 12
canOnlyAttackUnitsWithTags:高空

[turret_7]
x: -19
y: 25
image: 副炮.png
canShoot: false
limitingAngle: 50

idleDir: -90
canOnlyAttackUnitsWithTags:高空

[turret_8]
x: 0
y: 10
canShoot: true
#recoilOffset:-2
projectile: 2

invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.35
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*2,CUSTOM:光粒*2

delay: 18
attachedTo: 7
slave: true
size: 12
canOnlyAttackUnitsWithTags:高空

[turret_9]
x: 55
y: -86
image: 主炮.png
#canShoot: false
limitingAngle: 100

projectile: 3
delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200

shoot_flame: CUSTOM:球
aimOffsetSpread: -0.01
size: 12
idleDir: 45


[turret_10]
x: -55
y: -86
image: 主炮.png
#canShoot: false
limitingAngle: 100

projectile: 3
delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200

shoot_flame: CUSTOM:球
aimOffsetSpread: -0.01
size: 12
idleDir: -45


[projectile_2]
@copyFromSection: template_能源
directDamage: 100
life: 180
speed: 12
targetSpeed: 12

trailEffect: false
image: ROOT:/太空浪人/单位特效/中子弹.png
drawSize: 0.65
largeHitEffect: true
explodeEffect: CUSTOM:爆炸1,CUSTOM:爆炸,CUSTOM:闪光

explodeEffectOnShield: CUSTOM:爆炸1, CUSTOM:爆炸,CUSTOM:闪光


[projectile_1]
@copyFromSection: template_能源
life: 350
speed: 5
targetSpeed: 9
largeHitEffect: true

drawSize: 0.5
image: ROOT:/太空浪人/单位特效/光.png
trailEffect: CUSTOM:尾巴
areaDamage: 380
deflectionPower: -1

areaRadiusFromEdge: true
areaRadius: 45
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:溅射
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:溅射
autoTargetingOnDeadTarget: true

#spawnProjectilesOnEndOfLife:锁定
turnSpeed: 4
trailEffectRate: 0.01
lightColor: #FFFF1200
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_3]
@copyFromSection: template_能源
directDamage: 28
instantReuseLast: true
life: 10
instant: true

laserEffect: true
explodeEffect: CUSTOM:闪光1
explodeEffectOnShield: CUSTOM:闪光1
lightSize: 0.75
#beamImage:ROOT:/太空浪人/单位特效/光束3.png

color: #FFFF1200
beamImage: SHARED:beam3.png


[effect_闪光1]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.55

scaleTo: 0.55
image: ROOT:/太空浪人/单位特效/光束1.png
dirOffsetRandom: 180


[effect_溅射]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.8
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9

#alsoPlaySound:  ROOT:/余辉军团/单位特效/波雷爆炸.ogg
color: #FFFF1200


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.48
scaleTo: 0.48
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
atmospheric: false


[effect_爆炸1]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.1
image: ROOT:/太空浪人/单位特效/自制2.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[arm_1]
x: -38
y: -33
image_end: 1左.png
image_end_teamColors: true
drawOverBody: false

lockMovement: true


[arm_2]
x: 38
y: -33
image_end: 1右.png
image_end_teamColors: true
drawOverBody: false

lockMovement: true


[arm_3]
x: 0
y: 70
image_end: 2.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 0
y: 79
image_end: 2.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 0
y: 152
image_end: 3.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:3.png


[arm_6]
x: 0
y: 98
image_end: 4.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:4.png


[arm_7]
x: 0
y: 59
image_end: 5.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:5.png


[arm_8]
x: 0
y: -35
image_end: 6.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_9]
x: 0
y: -30
image_end: 7.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_10]
x: 0
y: -40
image_end: 8.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_11]
x: -31
y: 25
image_end: 9左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_12]
x: 31
y: 25
image_end: 9右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_13]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_14]
x: -34
y: 115
image_end: 10左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:10左.png


[arm_15]
x: 34
y: 115
image_end: 10右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
image_end_shadow: SHADOW:10右.png


[animation_attack]
blendIn: 1s
blendOut: 2s
arm11_1s: {x:14, y:0}
arm11_950s: {x:14, y:0}
arm12_1s: {x:-14, y:0}

arm12_950s: {x:-14, y:0}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm11_1s: {x:0, y:0}
arm12_1s: {x:0, y:0}


[effect_火1]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 15
yOffsetRelative	: -138


[effect_火2]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: -15
yOffsetRelative	: -138


[effect_火3]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: 34
yOffsetRelative	: -128


[effect_火4]
life: 60
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.2
xOffsetRelative	: -34
yOffsetRelative	: -128


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 11
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2

yOffsetRelative: 0.3
ySpeedRelative: 0.5
atmospheric: true


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.3
yOffsetRelative: 0.4
ySpeedAbsoluteRandom: 1
ySpeedRelative: 1
#xOffsetRelative:-2

atmospheric: true


[effect_球]
life: 5
spawnChance: 0.9
#priority:critical
attachedToUnit: true
scaleFrom: 0.7

scaleTo: 0.7
# image: 光球.png
image: ROOT:/太空浪人/单位特效/光束.png
alpha: 0.7


[animation_部署1]
arm1_0s: {x:0, y:0}
arm2_0s: {x:0, y:0}
arm3_0s: {x:0, y:0}
arm4_0s: {x:0, y:0}
arm5_0s: {x:0, y:0}

arm6_0s: {x:0, y:0}
arm7_0s: {x:0, y:0}
arm9_0s: {x:0, y:0}
arm10_0s: {x:0, y:0}
arm14_0s: {x:0, y:0}

arm15_0s: {x:0, y:0}
arm3_1.5s: {x:0, y:0}
arm4_1.5s: {x:0, y:0}
arm5_1.5s: {x:0, y:-132}
arm6_1.5s: {x:0, y:-78}

arm7_1.5s: {x:0, y:-39}
arm14_1.5s: {x:0, y:-30}
arm15_1.5s: {x:0, y:-30}
arm1_3s: {x:38, y:0}
arm2_3s: {x:-38, y:0}

arm3_3s: {x:0, y:31}
arm4_3s: {x:0, y:61}
arm9_3s: {x:0, y:20}
arm10_3s: {x:0, y:-20}
arm14_3s: {x:-10, y:-45}

arm15_3s: {x:10, y:-45}


[movement]
movementType: AIR
moveSpeed: 0.8
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 1.3
turnAcceleration: 0.02
targetHeightDrift: 0.3

slowDeathFall: false
targetHeight: 140


[ai]
buildPriority: 0.9


