


[core]
name: 机枪阵地
displayText: Пулемётная позиция
strictLevel: 1
price: 0
radius: 10
maxHp: 1
class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: 机枪阵地
canNotBeDirectlyAttacked: true
isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
[decal_盖子]
image: 盖子.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if parent.maxHp * 0.36< parent.hp and parent.tags(includes= '地堡t4')
yOffsetRelative:19.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9
[decal_盖子1]
image: 盖子损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if parent.hp< parent.maxHp * 0.36 and parent.tags(includes= '地堡t4')
yOffsetRelative:19.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9

[decal_盖子2]
image: 盖子1.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if parent.maxHp * 0.36< parent.hp and parent.tags(includes= '地堡t3')
yOffsetRelative:19.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9
[decal_盖子3]
image: 盖子损坏1.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if parent.hp< parent.maxHp * 0.36 and parent.tags(includes= '地堡t3')
yOffsetRelative:19.5
xOffsetRelative:-0.5
onlyWhileAlive:true
imageScale: 0.9
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
teamColorsOnTurret: true
imageScale: 0.9
turretImageScale: 0.9
image_shadow: AUTO
shadowOffsetX: 4.5
shadowOffsetY: 4.5
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 430
turretSize: 24
turretTurnSpeed: 2
turretMultiTargeting: true

[turret_1]
x: 3.5
y: 13
attachedTo: 3
slave: true
shoot_flame: small
shoot_sound: ROOT:/创世纪军事集团/建筑特效/机枪塔音效.ogg
shoot_sound_vol: 0.1
image: 枪管.png
recoilOffset: -2
delay: 10
size:5
projectile: 1
canAttackCondition:if parent.transportingCount + self.numberOfAttachedUnits(withTag= '蜂刺')*1 + parent.numberOfAttachedUnits(withTag= '反坦克炮') * 1+parent.numberOfAttachedUnits(withTag= '机甲战士') * 2+parent.numberOfAttachedUnits(withTag= '角斗士') * 3+parent.numberOfAttachedUnits(withTag= '操纵者') * 2+parent.numberOfAttachedUnits(withTag= '狩猎者') * 4> 3 and parent.tags(includes= '地堡t4')
invisible:if not parent.tags(includes= '地堡t4')
[turret_2]
x: -3.5
y: 13
copyFrom: 1
shoot_flame: small
delay:7

warmup:3
[turret_3]
x: 0
y: -4
canShoot: false
canAttackCondition:if parent.transportingCount + self.numberOfAttachedUnits(withTag= '蜂刺')*1 + parent.numberOfAttachedUnits(withTag= '反坦克炮') * 1+parent.numberOfAttachedUnits(withTag= '机甲战士') * 2+parent.numberOfAttachedUnits(withTag= '角斗士') * 3+parent.numberOfAttachedUnits(withTag= '操纵者') * 2+parent.numberOfAttachedUnits(withTag= '狩猎者') * 4> 3 and parent.tags(includes= '地堡t4')
idleDir:180
image:机枪.png
limitingAngle: 70
invisible:if not parent.tags(includes= '地堡t4')

#——————————————————————
[turret_4]
x: 3.5
y: 13
copyFrom: 1
shoot_flame: small
attachedTo: 6
slave: true
[turret_5]
x: -3.5
y: 13
copyFrom: 1
shoot_flame: small
delay:7
linkDelayWithTurret:4
warmup:3
attachedTo: 6
slave: true
[turret_6]
x: 20
y: 16
copyFrom: 3
idleDir:90
limitingAngle: 50

#——————————————————————
[turret_7]
x: 3.5
y: 13
copyFrom: 1
shoot_flame: small
attachedTo: 9
slave: true
[turret_8]
x: -3.5
y: 13
copyFrom: 1
shoot_flame: small
delay:7
linkDelayWithTurret:7
warmup:3
attachedTo: 9
slave: true
[turret_9]
x: -20
y: 16
copyFrom: 3
idleDir:-90
limitingAngle: 50
#——————————————————————
[turret_10]
x: 3.5
y: 13
copyFrom: 1
shoot_flame: small
attachedTo: 122
slave: true
[turret_11]
x: -3.5
y: 13
copyFrom: 1
shoot_flame: small
delay:7
linkDelayWithTurret:10
warmup:3
attachedTo: 122
slave: true
[turret_122]
x: 0
y: 32
copyFrom: 3
idleDir:360
limitingAngle: 70




#——————————————————————t3塔
[turret_12]
x: 0
y: 13
attachedTo: 13
slave: true
shoot_flame: small
shoot_sound: ROOT:/创世纪军事集团/建筑特效/机枪塔音效.ogg
shoot_sound_vol: 0.1
image: 枪管.png
recoilOffset: -2
delay: 10
size:5
projectile: 1
canAttackCondition:if parent.transportingCount + self.numberOfAttachedUnits(withTag= '蜂刺')*1 + parent.numberOfAttachedUnits(withTag= '反坦克炮') * 1+parent.numberOfAttachedUnits(withTag= '机甲战士') * 2+parent.numberOfAttachedUnits(withTag= '角斗士') * 3+parent.numberOfAttachedUnits(withTag= '操纵者') * 2+parent.numberOfAttachedUnits(withTag= '狩猎者') * 4> 3 and parent.tags(includes= '地堡t3')
invisible:if not parent.tags(includes= '地堡t3')
limitingRange: 350
[turret_13]
x: 0
y: -4
canShoot: false
canAttackCondition:if parent.transportingCount + self.numberOfAttachedUnits(withTag= '蜂刺')*1 + parent.numberOfAttachedUnits(withTag= '反坦克炮') * 1+parent.numberOfAttachedUnits(withTag= '机甲战士') * 2+parent.numberOfAttachedUnits(withTag= '角斗士') * 3+parent.numberOfAttachedUnits(withTag= '操纵者') * 2+parent.numberOfAttachedUnits(withTag= '狩猎者') * 4> 3 and parent.tags(includes= '地堡t3')
idleDir:180
image:机枪1.png
limitingAngle: 70
invisible:if not parent.tags(includes= '地堡t3')
limitingRange: 350
[turret_14]
x: 0
y: 13
copyFrom: 12
shoot_flame: small
attachedTo: 15
slave: true
[turret_15]
x: 20
y: 16
copyFrom: 13
idleDir:90
limitingAngle: 50

[turret_16]
x: 0
y: 13
copyFrom: 12
shoot_flame: small
attachedTo: 17
slave: true
[turret_17]
x: -20
y: 16
copyFrom: 13
idleDir:-90
limitingAngle: 50
[turret_18]
x: 0
y: 13
copyFrom: 12
shoot_flame: small
attachedTo: 19
slave: true
[turret_19]
x: 0
y: 32
copyFrom: 13
idleDir:360
limitingAngle: 70
[projectile_1]
@copyFromSection: template_动能
directDamage: 65
life: 240
speed: 10
targetSpeed: 10
deflectionPower: -1
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
frame: 8
color: #FFFFFF73
drawSize: 0.7
explodeEffect: CUSTOM:大火花
[effect_大火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.25
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12

animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2
[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
moveSlidingMode : false
moveIgnoringBody: false
