


[core]
name: 太空浪人船舰工厂t2
displayText: Корабельный завод Скитальцев t2
class: CustomUnitMetadata
price: 8500
maxHp: 14000
armour: 12

isBuilding: true
techLevel: 1
buildSpeed: 0.0005
isBio: false
footprint: -5,-2,5,7

constructionFootprint: -5,-2,5,7
numBitsOnDeath: 35
radius: 75
copyFrom: ROOT:/通用特效/单位防护.ini
canRepairBuildings: false

canRepairUnits: false
canReclaimResources: false
nanoRange: 3500000
nanoBuildSpeed: 1
#showInEditor:false

selfRegenRate: 0.12
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
tags: 地面,海上,灰影建筑,建筑
exit_y: 0
exit_moveAwayAmount: 180

canBuild_11_name: setRally
canBuild_11_pos: 0.1


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: Нет питания
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_断电a]
autoTrigger: if self.queueSize > 0 and self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
refundAllQueuedItems: true


[action_T1]
pos: 0.1
buildSpeed: 0s
addResources: setFlag=0,setFlag=1
text: Показать юниты t1
isVisible: if not self.hasFlag(id=1) and not self.hasFlag(id=0) and not numberOfUnitsInTeam(withTag='折跃门聚变堆', greaterThan=0,withinRange=400)


[action_T1_back]
pos: 0.1
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=1
isVisible: if self.hasFlag(id=1)and not numberOfUnitsInTeam(withTag='折跃门聚变堆', greaterThan=0,withinRange=400)
text: Скрыть юниты t1


[action_T2]
pos: 0.2
buildSpeed: 0s
addResources: setFlag=0,setFlag=2
text: Показать юниты t2
highPriorityQueue: true

ai_isHighPriority: true
isVisible: if not self.hasFlag(id=2) and not self.hasFlag(id=0) and not numberOfUnitsInTeam(withTag='折跃门聚变堆', greaterThan=0,withinRange=400)


[action_T2_back]
pos: 0.2
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=2
isVisible: if self.hasFlag(id=2) and not numberOfUnitsInTeam(withTag='折跃门聚变堆', greaterThan=0,withinRange=400)
text: Скрыть юниты t2


[canBuild_1]
name: 小型海军传送门
pos: 1
forceNano: true
isVisible: if numberOfUnitsInTeam(withTag='折跃门聚变堆', greaterThan=0,withinRange=400)


[canBuild_2]
name: 中型海军传送门
pos: 1
forceNano: true
isVisible: if numberOfUnitsInTeam(withTag='折跃门聚变堆', greaterThan=0,withinRange=400)


[canBuild_T1]
name: 死亡骑士,海蝎截击舰,卫士无人机,工蚁
pos: 1
isVisible: if numberOfUnitsInTeam(withTag='折跃门聚变堆', lessThan=1,withinRange=400) and self.hasFlag(id=1)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[canBuild_T2]
name: 剑鱼级护卫舰,深渊级驱逐舰,路西法,漂泊者
pos: 1
isVisible: if numberOfUnitsInTeam(withTag='折跃门聚变堆', lessThan=1,withinRange=400) and self.hasFlag(id=2)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[canBuild_T11]
name: 刚多林级巡洋舰
pos: 2
isVisible: if numberOfUnitsInTeam(withTag='折跃门聚变堆', lessThan=1,withinRange=400) and self.globalTeamTags(includes='科斯塔2') and self.hasFlag(id=2)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[canBuild_T12]
name: 黑火级重型巡洋舰
pos: 3
isVisible: if numberOfUnitsInTeam(withTag='折跃门聚变堆', lessThan=1,withinRange=400) and self.globalTeamTags(includes='科斯塔3') and self.hasFlag(id=2)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания


[canBuild_T13]
name: 帝王级战列舰
pos: 4
isVisible: if numberOfUnitsInTeam(withTag='折跃门聚变堆', lessThan=1,withinRange=400) and self.globalTeamTags(includes='法雅德3') and self.hasFlag(id=2)
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: Нет питания



[graphics]
total_frames: 1
image: 主体.png
image_back: 背景.png
image_wreak: 死亡.png
image_turret: NONE

#imageScale:0.75


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[effect_烟雾]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
life: 240
fadeOut: true
attachedToUnit: false

color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1

drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180

xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.5

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true


[arm_1]
x: -10
y: -12
image_end: 货.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: false


[animation_2]
onActions: idle
blendIn: 0.3s
blendOut: 0.2s
arm1_0s: {x:0, y:0}
arm1_2s: {x:70, y:0}

arm1_4s: {x:70, y:-25}
arm1_6s: {x:-40, y:-25}
arm1_8s: {x:-40, y:0}


[movement]
movementType: WATER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 太空浪人船舰工厂t1传送
ai_upgradePriority: 0.07
maxEachBase: 10
maxGlobal: 50


