


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=150


[core]
name: 白矮星中介
displayText: Белый Карликв посредник
class: CustomUnitMetadata
price: 4500,蓝晶=150
maxHp: 2500
displayDescription: -Белый Карликэто Империя Новасамыйдля огромный, также это  на самыйединицауничтожение тогданести типтяжёлый пушкамашина, \n-в нитьммне уменьшениемощь ситуацияпод , онпрямомонтажноситель幽冥уровеньбойрядкрейсер плазмаосадапушка, \n-поэтому, Белый Карликспециальныйдля уничтожитьвсе вспомогательныйвооружение тяжёлыйкрепость, а рождение, \n-ммне огромный сказать, Белый Карлик все силаодинбитьдажедо может будетбольшой  разрывать, \n- на , даже еслиэто небов также малоимеет может противостоятьБелый Карликпрямойстрельбавсе тело, а отступление юнит.\n-но это делатьдля Имея уничтожениеатакасила эрацена, Белый Карликзащитазащитасиланесколькоблизкийк ноль, \n-одновременнопотому чтодля главное орудиеантиделатьиспользует сила и может количествоспросбольшой , Белый КарликРазвернутьпушкашт (рам)позади только тогдаможет открытьогонь, а  и стрельбаскоростькрайнемедленный.\n-только по земле, Развернутьпозади только тогдаможет атака, энергетический урон

techLevel: 1
buildSpeed: 20s
radius: 52
showInEditor: false
displayRadius: 52
mass: 9999999 
isBio: false
softCollisionOnAll: 6
maxShield: 2500
shieldRegen: 0.07
tags: 地面,无人单位
fogOfWarSightRange:29
transportSlotsNeeded: 99
copyFrom: ROOT:/通用特效/单位防护.ini
unitsSpawnedOnDeath: 损毁3*1


[action_重子兵器2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重子2.png
text: барионное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='重子2')


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
addResources: shield=10
text: Позитронное ядро
price: 0
displayType: infoOnlyNoBox

isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_b]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
autoTrigger: true

alsoQueueAction: a


[action_a]
convertTo: SDAF白矮星展开
displayType: action
price: 0
buildSpeed: 2s
isVisible: false

highPriorityQueue: true
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: 主炮.png
#imageScale:0.8

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
teamColorsOnTurret: true
dustEffect: true


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 2
maxAttackRange: 540
shootDelay: 180


[turret_2]
x: 0
y: -6
shoot_flame: large
shoot_sound: NONE
recoilOffset: -5

recoilOutTime: 5
recoilReturnTime: 30
projectile: 2


[projectile_2]
directDamage: 0
life: 0
frame: 50
speed: 7.8
targetSpeed: 0

areaRadius: 0


[arm_1]
x: -23.4
y: 23.5
image_foot: 左前.png
image_end_teamColors: true
lockMovement: true

image_end_shadow: SHADOW:左前.png


[arm_2]
x: 23.4
y: 23.5
image_foot: 右前.png
image_end_teamColors: true
lockMovement: true

image_end_shadow: 右前.png


[arm_3]
x: -21
y: -30
image_end_teamColors: true
image_foot: 左后.png
image_end_shadow: 左后.png

lockMovement: true


[arm_4]
x: 21
y: -30
image_foot: 右后.png
image_end_teamColors: true
lockMovement: true

image_end_shadow: 右后.png


[arm_5]
x: 0
y: -5
image_foot: 左.png
lockMovement: true
drawUnderAllUnits: true


[arm_6]
x: 0
y: -5
image_foot: 右.png
lockMovement: true
drawUnderAllUnits: true


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm1_2s: {x:0, y:0, dir:-35}
arm2_2s: {x:0, y:0, dir:35}
arm3_2s: {x:0, y:0, dir:35}

arm4_2s: {x:0, y:0, dir:-35}
arm5_2s: {x:-30, y:0, dir:0}
arm6_2s: {x:30, y:0, dir:0}


[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 0

turnAcceleration: 0.25
moveSlidingMode : false
moveIgnoringBody: false


