


[core]
name: 脉冲
displayText: импульс
class: CustomUnitMetadata
price: 0
maxHp: 10
armour: 999989

techLevel: 2
radius: 0
displayRadius: 0
armourMinDamageToKeep: 0
showInEditor: false

hideScorchMark: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
isUnselectable: true
isBio: false

energyMax: 1
energyRegen: 0
dieOnZeroEnergy: true
explodeOnDeath: false


[action_爆炸]
autoTrigger: if self.timeAlive(laterThanSeconds=1)
isVisible: false
addResources: energy=-1
fireTurretXAtGround: 爆炸
fireTurretXAtGround_withOffset: 0,0


[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 200

aimOffsetSpread: 0
shootDelay: 1


[turret_爆炸]
x: 0
y: 0
canShoot: false
warmup: 600
projectile: 1

turnSpeedAcceleration: 999


[projectile_1]
@copyFromSection: template_能源
life: 999
instant: true
areaDamage: 2500
areaRadius: 80

targetGround: true
image: NO.png
drawSize: 1
deflectionPower: -1
areaRadiusFromEdge: true

explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:弹坑,CUSTOM:电球
explodeEffect: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:弹坑,CUSTOM:电球


[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/光束2.png
life: 20
fadeOut: true
attachedToUnit: false

color: #63e6e8
fadeInTime: 0.1
scaleFrom: 0.35
scaleTo: 0.35
alpha: 0.7

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_尾巴1]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 30
fadeOut: true
attachedToUnit: false

fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.7
alpha: 0.8
drawUnderUnits: false

yOffsetRelative	: -5


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 55
fadeOut: true
attachedToUnit: false

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
scaleFrom: 2
scaleTo: 0.1

alpha: 2
drawUnderUnits: false
atmospheric: false


[effect_粒子]
life: 60
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 2
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_烟雾]
frameIndex: 0
stripIndex: effects
spawnChance: 0.3
createWhenZoomedOut: false
life: 90

fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #FFFFFF
fadeInTime: 2

scaleFrom: 0.3
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.4
ySpeedRelativeRandom: 0.4
atmospheric: true


[effect_底色]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩.png
life: 140
fadeOut: true
attachedToUnit: false

scaleFrom: 0.9
scaleTo: 0.9
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 3
scaleTo: 3
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 6
scaleTo: 6

drawUnderUnits: true
atmospheric: false


[effect_电球]
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
image: ROOT:/余辉军团/单位特效/电球1.png

total_frames: 5
animateFrameStart: 0
animateFrameEnd: 4
animateFramePingPong: true
animateFrameSpeed: 0.2

life: 300
alwayStartDirAtZero: true


[effect_冲击波1]
life: 130
priority: critical
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 2.1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 60
fadeOut: true
attachedToUnit: false
drawType: displacement
scaleFrom: 0.1
scaleTo: 1.3
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 2
scaleTo: 2
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 0
targetHeight: -6
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true


