


[core]
name: 小型海军传送门
class: CustomUnitMetadata
displayDescription: -小型传送门可以传送剑鱼级护卫舰，刚多林级巡洋舰，深渊级驱逐舰，\n-路西法以及漂泊者，每个传送门仅能传送一个单位。\n-被传送的任何单位将在四秒之内到达战场。\n-每个传送门仅能维持30秒，请尽快决定要传送的单位，\n-否则传送门将在未传送任何单位的情况下关闭。且只能在传送场内产生传送门。
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=30
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: -2,-1,2,2
constructionFootprint: -2,-1,2,2


[action_取消]
text: 取消建造
addResources: hp=-999999,cs=30
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_剑鱼级护卫舰]
convertTo: 剑鱼级护卫舰
displayType: action
text: 传送剑鱼级护卫舰
description: -古人类战国时期阿瓦瑞里安王国的标准海军护卫舰，\n-作为一个爱好和平的国家，他们的军用设备并不先进，\n-剑鱼级护卫舰运用简单的技术，能最低限度的保护国家的海洋。\n-在诺瓦帝国统一古人类后，阿瓦瑞里安王国被迫上缴了所有军事装备，\n-其中就包括了大批剑鱼级护卫舰，在与余辉作战最危及的关头，\n-剑鱼被从仓库中取出并作为海洋上的最后一道防线与余辉作战，\n-直至今日，太空浪人依然在生产性价比极高的剑鱼级护卫舰，\n-他们构成了太空浪人海军的前锋力量。对地对空，动能伤害
price: 3500
buildSpeed: 4s
ai_isHighPriority: true
isVisible: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用


[action_刚多林级巡洋舰]
convertTo: 刚多林级巡洋舰
displayType: action
text: 传送刚多林级巡洋舰
description: -科斯塔工业集团在古人类战国时期推出的一款不伦不类的产品，\n-刚多林级巡洋舰配有十分新颖的水路两栖技术，以及舰载机甲板，\n-其售卖的对像就是那些同时想追求扩充海洋和地面力量的国家，科斯塔本想这种设计可以大赚一笔，\n-在大规模生产后，却发现其市场非常惨淡，只有少数国家愿意少数购买，\n-大量积压的刚多林在诺瓦帝国统一古人类后被皇帝收缴，之后便被遗忘在仓库中。\n-之后在与余辉战斗的危及时刻，大量的刚多林被意外发现，\n-他们在被简单改造后就被投入了与余辉的战斗中，并在各种战役中爆发出了不小的威力，\n-这款生不逢时的巡洋舰至今已然成为太空浪人的主力海军之一。对地对空，主炮动能，副炮飞机能源，水陆两栖
price: 6000,awz=120

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='科斯塔2')
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用


[action_漂泊者]
convertTo: 漂泊者
displayType: action
text: 传送漂泊者
description: -以天火炮艇为基础改造的便携式虫洞载具，\n-漂泊者搭载了一个小型多向聚变堆和传送立场发生器，\n-漂泊者的存在极大的解决了固定式传送基站和聚变堆的局限性，\n-无数的传送基站和漂泊者组成了贯通全球的折越网络，\n-太空浪人的部队也正因如此能快速向全球任何一个角落发起出其不意的突袭，\n-漂泊者虽然没有任何自卫能力，但每一艘漂泊者的出现，\n-都意味着其身后必定有一只即将出现的太空浪人军团。\n-部署后可以供能，可以提供传送网络，不能攻击。
price: 4000

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用


[action_深渊级驱逐舰]
spawnUnits: 深渊级驱逐舰(alwayStartDirAtZero= true)
displayType: action
text: 传送
addResources: hp=-999999
unitShownInUI: 深渊级驱逐舰

# 使用此单位作为动作图标。
textAddUnitName: 深渊级驱逐舰
# 从指定单位添加名称。
descriptionAddFromUnit: 深渊级驱逐舰
# 从指定单位添加单位描述。

price: 4500
descriptionAddUnitStats: 深渊级驱逐舰
# 从指定单位添加详细信息描述，比如攻击力，攻击范围。
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用


[action_路西法]
convertTo: 路西法水下
displayType: action
text: 传送路西法
description: -古人类战国时期，路西法是科斯塔工业集团推出的一款多用途攻击机，\n-其设计是基于那些没有额外经费支出给海军发展的落后国家。\n-路西法在作为一款强力的攻击机的同时，还配有新颖的变形系统，\n-使其可以变形潜入水下作战，在一定程度上可以当做海军使用，\n-在当时，路西法是星系间最抢手的军火之一，几乎所有反对亚尔佛里德的国家都拥有路西法。\n-直至今日，路西法依旧在太空浪人的军队中服役，并为打击余辉做出了卓越贡献。\n-只能对地，空中能源伤害，水下模式动能伤害
price: 3800

buildSpeed: 4s
setBodyRotation: 0
ai_isHighPriority: true


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

#drawLayer:top
animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.8


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.2
scaleTo: 0.6
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.8
scaleFrom: 0.8
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.7
scaleFrom: 0.7
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2

scaleTo: 0.9
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: WATER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


