


[core]
name: 小型海军传送门
displayText: Малый морской портал
class: CustomUnitMetadata
displayDescription: -Малый портал может телепортировать фрегат класса «Меч-рыба», крейсер класса «Гондолин», эсминец класса «Бездна»,\n-«Люцифер» и «Странник». Каждый портал может телепортировать только одного юнита.\n-Любой телепортируемый юнит прибудет на поле боя в течение четырёх секунд.\n-Каждый портал поддерживается только 30 секунд, поспешите решить, кого телепортировать,\n-иначе портал закроется, не телепортировав никого. Порталы можно создавать только в поле телепортации.
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=30
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: -2,-1,2,2
constructionFootprint: -2,-1,2,2


[action_取消]
text: Отменить постройку
addResources: hp=-999999,cs=30
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_剑鱼级护卫舰]
convertTo: 剑鱼级护卫舰
displayType: action
text: Телепортировать фрегат класса «Меч-рыба»
description: -Стандартный военно-морской фрегат Королевства Аваририан эпохи Воюющих государств Древних Людей.\n-Будучи миролюбивой страной, их военное оборудование не отличалось передовыми технологиями,\n-фрегат класса «Меч-рыба» использует простые технологии, обеспечивая минимальную защиту морских вод страны.\n-После объединения Древних Людей Империей Нова Королевство Аваририан было вынуждено сдать всё военное оборудование,\n-включая множество фрегатов класса «Меч-рыба». В критический момент войны с Заревом\n-«Меч-рыбы» были извлечены со складов и стали последней морской линией обороны против Зарева.\n-По сей день Скитальцы продолжают производить чрезвычайно эффективный по соотношению цены и качества фрегат класса «Меч-рыба»,\n-они составляют авангард флота Скитальцев. Атакует землю и воздух, кинетический урон.
price: 3500
buildSpeed: 4s
ai_isHighPriority: true
isVisible: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_刚多林级巡洋舰]
convertTo: 刚多林级巡洋舰
displayType: action
text: Телепортировать крейсер класса «Гондолин»
description: -Странный продукт промышленной группы Коста эпохи Воюющих государств Древних Людей.\n-Крейсер класса «Гондолин» оснащён весьма новаторской амфибийной технологией и палубой для мехов.\n-Он продавался странам, которые хотели одновременно развивать морские и наземные силы. Коста рассчитывала хорошо заработать на такой конструкции,\n-но после массового производства выяснилось, что рынок очень слаб — лишь немногие страны покупали небольшие партии.\n-Огромные запасы «Гондолина» после объединения Древних Людей Империей Нова были конфискованы императором и забыты на складах.\n-Затем в критический момент войны с Заревом большое количество «Гондолинов» было случайно обнаружено.\n-После небольшой переделки их бросили в бой против Зарева, и в различных сражениях они проявили немалую мощь.\n-Этот появившийся не в своё время крейсер ныне стал одной из основных сил флота Скитальцев. Атакует землю и воздух, главное орудие — кинетический, вторичные/самолёты — энергетический. Амфибия.
price: 6000,awz=120

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='科斯塔2')
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_漂泊者]
convertTo: 漂泊者
displayType: action
text: Телепортировать «Странник»
description: -Портативный кротонорный носитель, переоборудованный на базе канонерки «Небесный огонь».\n-«Странник» оснащён компактным многонаправленным термоядерным реактором и генератором поля телепортации.\n-Существование «Странника» значительно решает ограничения стационарных телепорт-станций и реакторов.\n-Бесчисленные телепорт-станции и «Странники» образуют глобальную сеть прыжков,\n-благодаря чему войска Скитальцев могут быстро наносить внезапные удары в любую точку мира.\n-Хотя «Странник» не имеет средств самообороны, появление каждого «Странника»\n-означает, что за ним непременно идёт армия Скитальцев.\n-После развёртывания может обеспечивать питание и сеть телепорта. Не может атаковать.
price: 4000

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_深渊级驱逐舰]
spawnUnits: 深渊级驱逐舰(alwayStartDirAtZero= true)
displayType: action
text: Телепорт
addResources: hp=-999999
unitShownInUI: 深渊级驱逐舰

# 使用此单位作为动作图标。
textAddUnitName: 深渊级驱逐舰
# 从指定单位添加名称。
descriptionAddFromUnit: 深渊级驱逐舰
# 从指定单位添加单位描述。

price: 4500
descriptionAddUnitStats: 深渊级驱逐舰
# 从指定单位添加详细信息描述，比如攻击力，攻击范围。
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_路西法]
convertTo: 路西法水下
displayType: action
text: Телепортировать «Люцифер»
description: -В эпоху Воюющих государств Древних Людей «Люцифер» был многоцелевым штурмовиком, выпускавшимся промышленной группой Коста.\n-Его конструкция была разработана для отсталых стран без дополнительного бюджета на развитие флота.\n-«Люцифер» — это мощный штурмовик, оснащённый новаторской системой трансформации,\n-которая позволяет ему погружаться под воду для боя, до некоторой степени заменяя флот.\n-В то время «Люцифер» был одним из самых популярных вооружений в галактике; почти все страны, противостоявшие Альфриду, имели «Люциферов».\n-По сей день «Люцифер» служит в армии Скитальцев и внёс выдающийся вклад в борьбу с Заревом.\n-Атакует только землю, в воздухе — энергетический урон, в подводном режиме — кинетический урон.
price: 3800

buildSpeed: 4s
setBodyRotation: 0
ai_isHighPriority: true


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

#drawLayer:top
animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.8


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.2
scaleTo: 0.6
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.8
scaleFrom: 0.8
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.7
scaleFrom: 0.7
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2

scaleTo: 0.9
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: WATER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


