


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 灭世t1
class: CustomUnitMetadata
price: 6000,awz= ${awzxq}
@global awzxq: 150
maxHp: 14000

reclaimPrice: awz= ${awzxq}
footprint: -2,-2,1,1
constructionFootprint: -2,-2,1,1
buildingToFootprintOffsetX: -1
#buildingToFootprintOffsetY:13
fogOfWarSightRange: 30
techLevel: 1
buildSpeed: 0
radius: 25
#buildingSelectionOffset: -8
isBuilding: true

copyFrom: ROOT:/通用特效/单位防护.ini
selfRegenRate: 0.12
isBio: false
effectOnDeath: CUSTOM:烟雾2*2,CUSTOM:爆炸*1
tags: 地面,灰影建筑,反高空,建筑

energyMax: 80
energyRegen: 0.35
energyNeedsToRechargeToFull: true
armour: 25
[action_近距离锁定]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='飞机',greaterThan= 0,withInRange=480) or numberOfUnitsInEnemyTeam(withTag='地面',greaterThan= 0,withInRange=480)
addWaypoint_target_nearestUnit_tagged:飞机,地面
addWaypoint_type: attack
addWaypoint_target_nearestUnit_team: enemy
clearAllWaypoints: true
isVisible:false
[action_近距离锁定x]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='高空',greaterThan= 0,withInRange=650) and numberOfUnitsInEnemyTeam(withTag='飞机',lessThan= 1,withInRange=480) and numberOfUnitsInEnemyTeam(withTag='地面',lessThan= 1,withInRange=480)
addWaypoint_target_nearestUnit_tagged:高空
addWaypoint_type: attack
addWaypoint_target_nearestUnit_team: enemy
clearAllWaypoints: true
isVisible:false

[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: 缺少供能
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: 缺少暗物质
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[graphics]
total_frames: 1
image: ROOT:/太空浪人/建筑特效/大底座t1.png
image_wreak: ROOT:/太空浪人/建筑特效/大底座t1死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
imageScale: 0.9

turretImageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 150

turretSize: 23
turretTurnSpeed: 1
maxAttackRange: 650
#aimOffsetSpread: -0.01
aimOffsetSpread: -0.01
[turret_1]
x: 0
y: 30
canShoot: false
image: 炮塔.png
idleSweepAngle: 100
idleSweepDelay: 210
idleSweepSpeed: 0.2
canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400) and self.resource.awz>-1
[turret_2]
x: 0
y: 0
canShoot: true
projectile: 1
#invisible: true

shoot_sound_vol: 2
shoot_sound: ROOT:/太空浪人/单位特效/长矛.ogg
shoot_flame: CUSTOM:烟雾*1,CUSTOM:光球*1,CUSTOM:粒子*1
shoot_light: #FFFF1200
delay: 1

canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400) and self.resource.awz>-1
#warmup:45
image: 炮塔.png
size: 28
energyUsage: 5
attachedTo: 1
slave: true
canOnlyAttackUnitsWithoutTags:高空
limitingRange: 500
[turret_3]
x: 0
y: 0
canShoot: true
projectile: 1
#invisible: true

shoot_sound_vol: 2
shoot_sound: ROOT:/太空浪人/单位特效/长矛.ogg
shoot_flame: CUSTOM:烟雾*1,CUSTOM:光球*1,CUSTOM:粒子*1
shoot_light: #FFFF1200
delay: 1

canAttackCondition: if self.resource.xk < 1 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400) and self.resource.awz>-1
#warmup:45
image: 炮塔.png
size: 28
energyUsage: 5
attachedTo: 1
slave: true
canOnlyAttackUnitsWithTags:高空
[effect_烟雾2]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[projectile_1]
@copyFromSection: template_能源
directDamage: 400
instantReuseLast: true
life: 10
instant: true

laserEffect: true
explodeEffect: CUSTOM:爆炸x, CUSTOM:闪光,CUSTOM:聚变,CUSTOM:光粒*2
explodeEffectOnShield: CUSTOM:爆炸x, CUSTOM:闪光,CUSTOM:聚变,CUSTOM:光粒*2
lightSize: 0.75
beamImage: 激光.png

#color:#FFFF1200
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟雾]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6

yOffsetRelative: 0.8
ySpeedRelative: 1.5
atmospheric: true


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[effect_光球]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.4

scaleTo: 0.4
# image: 光球.png
color: #FFFF1200
image: ROOT:/创世纪军事集团/单位特效/光球.png


[effect_爆炸x]
priority: critical
image: 光球.png
life: 10
fadeOut: true
attachedToUnit: false

scaleFrom: 0.25
scaleTo: 0.25
alpha: 1.3
drawUnderUnits: false
atmospheric: false

#alsoPlaySound:ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_聚变]
#priority:critical
image: 闪光.png
life: 10
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_光粒]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom: 0.1
scaleTo: 0.4

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.5

ySpeedRelativeRandom: 4
#atmospheric: true


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
upgradedFrom: 空塔楼t1传送
ai_upgradePriority: 0.07


