



[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
@global awzxq: 300
name: 阿玛洛克MKII
displayText: «Амарок MKII»
price: 12000,awz= ${awzxq}
maxHp: 30000
reclaimPrice: awz= ${awzxq}

displayDescription: -阿玛洛克是诺瓦帝国地面霸权最强有力的证明，这种战斗要塞曾经在地面上几乎无人能挡，\n-浮岛要塞和阿玛洛克分别作为帝国海洋和陆地最强大的捍卫者守护帝国直至今日，\n-他们强悍的战斗力同时也令各大家族所垂涎三尺，帝国分裂后，\n-帝国各地的阿玛洛克被法雅德家族抢占，并被改造成MKII型当做移动要塞部署于各大星系，\n-在余辉一轮又一轮的攻势下，阿玛洛克始终作为太空浪人地面上不败王牌而屹立不倒，\n-这种移动要塞至今仍是令余辉最忌惮的超级单位之一。\n-只能对地，动能伤害，导弹能源伤害，舰载机能源伤害，休克免疫。
techLevel: 1
buildSpeed: 34s
radius: 100
displayRadius: 100
armour: 105
fogOfWarSightRange: 32
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded: 100
selfRegenRate: 1
unitsSpawnedOnDeath: 损毁3*1
tags: 地面,阿玛洛克,极端重型
maxTransportingUnits: 3

transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机lrx
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: AIR

transportUnitsKeepBuiltUnits: false
@memory 灰机: number
@memory 灰机list: unit[]
[action_重]
text: Сверхтяжёлый юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0
iconImage: ROOT:/通用特效/重.png
isLockedMessage: Уникальная особенность юнитов огромного размера.\n-Юниты с тегом «Сверхтяжёлый юнит» обладают следующими свойствами:\n-имеют способность к самовосстановлению, броня не ниже 100,\n-плохо поддаются шоку, но получают повышенный урон от противотанковых юнитов.

[canBuild_T2]
name: 猎兵坦克,招潮蟹机甲,天火炮艇,轻骑兵机甲
pos: 1
isLocked: if self.resource.awz<0
isLockedMessage: Недостаточно тёмной материи

[canBuild_T21]
name: 北极星机甲
pos: 2
isVisible: true

isLocked: if not self.globalTeamTags(includes='科斯塔1') or self.resource.awz<0
isLockedMessage: Требуются Технологии семьи Коста 1, либо недостаточно тёмной материи


[action_a]
convertTo: 阿玛洛克MKII部署
displayType: action
text: Развернуть завод
price: 0
buildSpeed: 6s

highPriorityQueue: true
isVisible: true
isLocked: if self.resource.awz<0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署

description: Развернуть встроенный завод и сложить гигантские механические ноги.\n-Позволяет производить базовые наземные юниты Скитальцев t3 и мех «Лёгкий улан»,\n-но в режиме завода юнит не может двигаться. Нельзя развернуть во время производства истребителей.





[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 3
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 3
addUnitsIntoTransport: 雪崩


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1

[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)

[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: Недостаточно тёмной материи
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[hiddenAction_↯a]
autoTrigger: if self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

#——————————————————————————
[decal_大炮遮盖]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 2

[decal_大炮遮盖1]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 3

[decal_大炮遮盖2]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 4

[decal_大炮遮盖3]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 5

[decal_大炮遮]
image: 主炮.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 1


[decal_大炮遮盖4]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 6

[decal_大炮遮盖5]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 7

[decal_大炮遮盖6]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 8

[decal_大炮遮盖7]
image: 炮管.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 9

[decal_大炮遮1]
image: 主炮.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 10
[graphics]
image: 身体2.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 11

shadowOffsetY: 11
teamColorsOnTurret: true
#image_back:   背景.png


[attack]
canAttack: true
canAttackFlyingUnits: if self.resource.awz>-1
canAttackLandUnits: if self.resource.awz>-1
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 1
maxAttackRange: 900
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_233]
x: 0
y: 0
# limitingRange: 580
projectile: 233
delay: 2.2s

canAttackMaxAngle: 181
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
invisible: true


[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true


[turret_2]
x: -10
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
warmup: 0
image: 炮管.png
attachedTo: 1

canAttackFlyingUnits: false
slave: true


[turret_3]
x: 10
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
#warmup:6
image: 炮管.png
attachedTo: 1

canAttackFlyingUnits: false
slave: true


[turret_4]
x: -4
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
#warmup:12
image: 炮管.png
attachedTo: 1

canAttackFlyingUnits: false
slave: true


[turret_5]
x: 4
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
#warmup:18
image: 炮管.png
attachedTo: 1

canAttackFlyingUnits: false
slave: true


[turret_1]
x: 58
y: 23
canShoot: false
limitingAngle: 105
canAttackFlyingUnits: false

idleDir: 90
limitingRange: 525
image: 主炮.png


[turret_6]
x: -10
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
warmup: 0
image: 炮管.png
attachedTo: 10

canAttackFlyingUnits: false
slave: true


[turret_7]
x: 10
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
#warmup:6
image: 炮管.png
attachedTo: 10

canAttackFlyingUnits: false
slave: true


[turret_8]
x: -4
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
#warmup:12
image: 炮管.png
attachedTo: 10

canAttackFlyingUnits: false
slave: true


[turret_9]
x: 4
y: 33
projectile: 1
turnSpeed: 1.8
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
limitingRange: 525

shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
canShoot: true
recoilOffset: -6
recoilOutTime: 7
recoilReturnTime: 35

size: 9
delay: 140
#warmup:18
image: 炮管.png
attachedTo: 10

canAttackFlyingUnits: false
slave: true


[turret_10]
x: -58
y: 23
canShoot: false
limitingAngle: 105
canAttackFlyingUnits: false

idleDir: -90
image: 主炮.png
limitingRange: 525


[turret_11]
x: -59
y: -49
canShoot: true
recoilOffset: -4
projectile: 2

idleDir: -45
image: 副炮.png
#invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.45

shoot_light: #FFFF1200
shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*4
delay: 240
limitingAngle: 100
size: 30

warmup: 60
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
turnSpeed: 1.2
limitingRange: 525
canAttackFlyingUnits: false


[turret_12]
x: 59
y: -49
idleDir: 45
canShoot: true
recoilOffset: -4

projectile: 2
#idleDir:45
image: 副炮.png
#invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg

shoot_sound_vol: 0.45
shoot_light: #FFFF1200
shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*4
delay: 240
limitingAngle: 100

size: 30
warmup: 60
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
turnSpeed: 1.2
canAttackFlyingUnits: false

limitingRange: 525


[projectile_1]
@copyFromSection: template_动能
areaDamage: 350
areaRadius: 65
targetGroundSpread: 35
life: 200

speed: 9
image: ROOT:/太空浪人/单位特效/光.png
targetSpeed: 9
drawSize: 0.60
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*3,CUSTOM:冲击波,CUSTOM:爆炸2

explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:光子*3,CUSTOM:冲击波,CUSTOM:爆炸2
targetGround: true
areaRadiusFromEdge: true
lightSize: 0.75
lightColor: #FFFF1200


[projectile_2]
@copyFromSection: template_动能
directDamage: 1200
life: 240
speed: 10
image: ROOT:/太空浪人/单位特效/弯子弹.png

drawSize: 1.1
#spawnProjectilesOnExplode: m2(yOffsetRelative= 20)
explodeEffect: CUSTOM:爆炸w, CUSTOM:闪光w,CUSTOM:冲击波w,CUSTOM:聚变
explodeEffectOnShield: CUSTOM:爆炸w, CUSTOM:闪光w,CUSTOM:冲击波w,CUSTOM:聚变
lightSize: 0.75

trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
lightColor: #FFFF1200


[projectile_3]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1

frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定*3


[projectile_锁定]
@copyFromSection: template_能源
life: 420
speed: 3
targetSpeed: 9
largeHitEffect: true

drawSize: 1.25
trailEffect: false
lightSize: 0.75
lightColor: #FFFF1200
directDamage: 80

image: ROOT:/太空浪人/单位特效/光束.png
explodeEffectOnShield: CUSTOM:爆炸11,CUSTOM:闪光
armourIgnoreAmount: 20
explodeEffect: CUSTOM:爆炸11,CUSTOM:闪光
wobbleAmplitude: 3

#摆动幅
wobbleFrequency: 240
#摆动频率
turnSpeed: 30
trailEffectRate: 0.02


[leg_1]
x: -75
y: 110
attach_x: -35
attach_y: 50
moveSpeed: 1.1

rotateSpeed: 9
heightSpeed: 0.4
resetAngle: 25
#drawOverBody: true
image_leg: 腿.png

image_foot: 脚.png
image_foot_shadow: SHADOW:脚.png
hardLimit: 40
holdDisMin: 8
holdDisMax: 15

drawDirOffset: 180


[leg_2]
x: 75
y: 110
attach_x: 35
attach_y: 50
copyFrom: 1

drawDirOffset: 0


[leg_3]
x: -75
y: -100
attach_x: -35
attach_y: -40
copyFrom: 1

drawDirOffset: 180


[leg_4]
x: 75
y: -100
attach_x: 35
attach_y: -40
copyFrom: 1

drawDirOffset: 0


[leg_5]
x: -90
y: 10
attach_x: -45
attach_y: 10
copyFrom: 1

drawDirOffset: 180


[leg_6]
x: 90
y: 10
attach_x: 45
attach_y: 10
copyFrom: 1

drawDirOffset: 0


[effect_烟雾1]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
#color: #FFFF1200
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF

#color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9

drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedRelative: 1
atmospheric: true


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.48
scaleTo: 0.48
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.5
scaleTo: 0.5

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7

ySpeedRelativeRandom: 3.7
#atmospheric: true


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.65
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_爆炸2]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.8
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9

#alsoPlaySound:  ROOT:/余辉军团/单位特效/波雷爆炸.ogg
color: #FFFF1200


[effect_爆炸w]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.65

image: ROOT:/太空浪人/单位特效/核弹.png
total_frames: 21
animateFrameStart: 0
animateFrameEnd: 21
animateFramePingPong: false

animateFrameSpeed: 0.27
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光w]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 1.7
scaleTo: 1.7
alpha: 0.8
drawUnderUnits: true
atmospheric: false


[effect_冲击波w]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/双尾.png
life: 20
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.9
scaleTo: 0.9
alpha: 0.6

#drawUnderUnits:t


[effect_爆炸11]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[arm_1]
x: -25
y: 100
image_end: 左架子.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_2]
x: 25
y: 100
image_end: 右架子.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_3]
x: 0
y: 0
image_end: 架子.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_4]
x: 0
y: 70
image_end: 架子.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_5]
x: -39
y: 95
image_end: 左.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_6]
x: 39
y: 95
image_end: 右.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_7]
x: 0
y: -83.5
image_end: 环.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true
spinRate: 1


[arm_8]
x: 0
y: -65
image_end: 头.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_9]
x: -50
y: -50
image_end: 左平台.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: false


[arm_10]
x: 50
y: -50
image_end: 右平台.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: false


[arm_11]
x: -50
y: 20
image_end: 左平台.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: false


[arm_12]
x: 50
y: 20
image_end: 右平台.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: false


[arm_13]
x: 0
y: 0
image_end: 背景.png
image_end_teamColors: true
drawUnderAllUnits: true

drawOverBody: false


[animation_2]
onActions: idle
blendIn: 3s
blendOut: 4s
arm3_0s: {x:0, y:0}
arm3_4s: {x:0, y:-20}

arm3_8s: {x:0, y:0}


[animation_部署]
#onActions: attack
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}

arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm5_2s: {x:0, y:15, dir:0}
arm6_2s: {x:0, y:15, dir:0}

arm5_6s: {x:-45, y:15, dir:0}
arm6_6s: {x:45, y:15, dir:0}
arm8_6s: {x:0, y:55, dir:0}
arm9_6s: {x:-40, y:0, dir:0}
arm10_6s: {x:40, y:0, dir:0}

arm11_6s: {x:-40, y:0, dir:0}
arm12_6s: {x:40, y:0, dir:0}
leg1_0s: {x:0, y:0 }
leg2_0s: {x:0, y:0 }
leg3_0s: {x:0, y:0 }

leg4_0s: {x:0, y:0 }
leg5_0s: {x:0, y:0 }
leg6_0s: {x:0, y:0 }
leg1_6s: {x:65, y:-30 }
leg2_6s: {x:-65, y:-30 }

leg3_6s: {x:65, y:0 }
leg4_6s: {x:-65, y:0 }
leg5_6s: {x:80, y:0 }
leg6_6s: {x:-80, y:0 }


[attachment_drone1]
x: 63
y: -95
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: false
idleDir: 135

resetRotationWhenNotAttacking: true
height: 1


[attachment_drone2]
x: -63
y: -95
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: false
idleDir: -135

resetRotationWhenNotAttacking: true
height: 1


[attachment_drone3]
x: 0
y: -130
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: false
idleDir: 180

resetRotationWhenNotAttacking: true
height: 1


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.8
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 0.55

turnAcceleration: 0.01
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0.4
slowDeathFall: true


