


[core]
name: 战马IFV
displayText: БМП «Боевой конь»
class: CustomUnitMetadata
price: 1100
maxHp: 1275
displayDescription:【Уровень t2】【Механический юнит】【Наземный юнит】【лёгкое укрытие】Тактическое назначение:БМП，\n-вместимость десанта：4может загружать только биологические юниты且сам не может транспортироваться。\n-вооружение：▲тяжёлый пулемётX1 только по земле кинетический урон \n-ракетапусковая установкаX2 только по земле взрывной урон \n-БМП «Боевой конь»是一座移动式пехота堡垒，\n-оноснащённый了Дымовая граната和双连装ракетапусковая установка，\n-再加上он那厚实的броняабсолютный是пехота称职的保护伞。
techLevel: 1
buildSpeed: 11s
radius: 24
displayRadius: 24
isBio: false
softCollisionOnAll: 6
copyFrom: ROOT:/通用特效/单位防护.ini
armour: 3
tags: 地面,轻型掩体
maxTransportingUnits: 4
transportUnitsRequireTag: 步兵,机甲
transportUnitsKillOnDeath: true
energyMax: 10
energyRegen: 0.006
energyStartingPercentage: 0
nanoFactorySpeed: 0.5
transportUnitsKeepBuiltUnits: true
unitsSpawnedOnDeath: 损毁*1
fogOfWarSightRange: 15

canBuild_3_name: 海军陆战队
canBuild_3_pos: 3

canBuild_4_name: 机枪手
canBuild_4_pos: 4
canBuild_5_name: 火箭炮兵
canBuild_5_pos: 5
canBuild_6_name: 火焰喷射手

canBuild_6_pos: 6
canBuild_7_name: 重装部队
canBuild_7_pos: 7
canBuild_8_name: 迫击炮小队
canBuild_8_pos: 8

canBuild_9_name: 狙击手
canBuild_9_pos: 9
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[hiddenAction_1]
price: 0
buildSpeed: 0s
isVisible: false
autoTrigger:if  self.numberOfAttachedUnits(withTag= '1格')*1 + self.numberOfAttachedUnits(withTag= '蜂刺')*2 + self.numberOfAttachedUnits(withTag= '反坦克炮') * 2+self.numberOfAttachedUnits(withTag= '机甲战士') * 2+self.numberOfAttachedUnits(withTag= '角斗士') * 3+self.numberOfAttachedUnits(withTag= '操纵者') * 2+self.numberOfAttachedUnits(withTag= '狩猎者') * 4> 4
forceUnloadTransportNow:true
forceUnloadTransportNow_onlyOnSlot:1
highPriorityQueue: true
#refundAllQueuedItems:true
displayType: action
[action_轻型掩体]
text: лёгкое укрытие
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/轻型掩体.png
description: 一处лёгкое укрытие，может为рядом140范围内的биологический юнитобеспечиваетлёгкое прикрытие。\n-лёгкое прикрытиеможет为биологический юнит减免50%的伤害，\n-но，укрытие无法减免部分скорострельный，激光，Огонь，电击，中性，самоподрыв，ближний бой，衰解等其он无视укрытие的оружие。
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
[action_1_烟幕弹]
fireTurretXAtGround: 烟幕弹
text: запускатьДымовая граната
displayType: action
buildSpeed: 0.1s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
price: energy=10
canPlayerCancel: false
onlyOneUnitAtATime: true
description: 向目标区域投掷一枚Дымовая граната，Дымовая гранатаможетсерьёзный干扰敌军的瞄准系统。\n-Дымовая граната将降低рядом160范围内的вражескийназемный юнит的дальностьа также射速，\n-对обладать长距离целеуказаниеспособностьа такжеиметьУлучшенный модуль наведениянаука的юнитнеэффективный。
iconImage: ROOT:/创世纪军事集团/单位特效/烟雾弹.png
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_恐怖地雷2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: Мина «Кошмар»2
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷2') and not self.globalTeamTags(includes='恐怖地雷3')
isAlsoViewableByAllies: true
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 2
image: 战马IFV底盘.png
image_wreak: 战马IFV死亡.png
image_turret:炮塔.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
dustEffect: true
turretImageScale: 0.9
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 2
maxAttackRange: 255
shootDelay: 180
turretMultiTargeting: true


[turret_烟幕弹]
x: 0
y: 0
canShoot: false
idleDir: 0
invisible: true
size: 1.1
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 4
delay: 0
canAttackCondition: if self.resource.xk < 1
limitingRange: 235
[turret_0]
x: 0
y: -20
canShoot: false
recoilOffset: -2
idleSweepAngle: 20
idleSweepDelay: 230
idleSweepSpeed: 0.2
[turret_1]
x: 6
y: 4
projectile: 1
attachedTo: 0
slave: true
image:导弹头.png
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹音效.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾2*3
shoot_light: #FFEECCCC
canShoot: true
canAttackCondition: if self.resource.xk < 1
delay:180
recoilOffset: -10
recoilOutTime: 4
recoilReturnTime: 140
size:7
[turret_4]
x: -6
y: 4
#导弹左
copyFrom: 1
warmup: 15
delay:165
[turret_5]
x: 0
y: 0
canShoot: false
image: 炮塔遮盖.png
attachedTo: 0
slave: true
invisible:if self.hp < self.maxHp * 0.36
[turret_6]
x: 0
y: 0
canShoot: false
image: 炮塔损坏.png
attachedTo: 0
slave: true
invisible: if self.maxHp * 0.36 < self.hp
delay: 0


[turret_7]
x: 4
y: 10
image: ROOT:/创世纪军事集团/单位特效/机枪.png
shoot_sound: ROOT:/创世纪军事集团/步兵特效/重机枪射击.ogg
shoot_sound_vol: 0.2
shoot_flame: CUSTOM:枪口火焰
shoot_light: #FFccCCEE
projectile: 3
delay: 5
size: 13
canAttackCondition: if self.resource.xk < 1


[attachment_1]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: true


[attachment_2]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false

resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: true


[attachment_3]
x: 0
y: 0
alwaysAllowedToAttackParentsMainTarget: true
height: -1
isVisible: false

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[attachment_4]
x: 0
y: 0
isVisible: false
alwaysAllowedToAttackParentsMainTarget: true
height: -1

canBeAttackedAndDamaged: false
keepAliveWhenParentDies: false
setDrawLayerOnTop: false
addTransportedUnits: 1
rotateWithParent: true

lockRotation: false
resetRotationWhenNotAttacking: true
canAttack: true
setDrawLayerOnBottom: true


[projectile_3]
@copyFromSection: template_动能
directDamage: 4
life: 180
speed: 10
targetSpeed: 10
trailEffect: false
frame: 5
drawSize: 0.8
explodeEffect: CUSTOM:火花


[projectile_1]
@copyFromSection: template_爆炸
directDamage: 40
life: 250
speed: 6.5
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 0.85
trailEffect: true
lightSize: 0.75
lightColor: #FFFFFF73
largeHitEffect: true
explodeEffect: CUSTOM:爆炸
explodeEffectOnShield:CUSTOM:爆炸

[projectile_4]
life: 600
directDamage: 0
speed: 4
targetSpeed: 4
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png

drawSize: 0.8
targetGround: true
spawnUnit: 烟幕弹*1
trailEffect: true
deflectionPower: -1

[effect_烟雾2]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.25
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: -0.7
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.35

yOffsetRelative: -15
atmospheric: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.6
image: ROOT:/通用特效/火花.png
alpha: 1.2

total_frames: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFramePingPong: false
animateFrameSpeed: 0.3


[effect_爆炸]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[movement]
movementType: LAND
moveSpeed: 0.9
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.07
maxTurnSpeed: 2
turnAcceleration: 0.3
moveSlidingMode : false
moveIgnoringBody: false


