[hiddenAction_寄生b]
addResources: bj= ${bjxq}


[core]
name: 建造超战舰
displayText: Постройка суперкорабля
displayDescription: 【Уровень t4】【Механический юнит】【Надводный юнит】【Иммунитет к шоку】【Сверхтяжёлый юнит】\n-Тактическое назначение:продвинутыйтяжёлыйуниверсальный боевой корабль，вооружение：\n-▲РельсотронX2 только по земле кинетический урон ▲большойкалибрракетная установкаX2 только по земле взрывной урон \n-▲автопушкаX4 по земле и воздуху кинетический урон усиленный урон по щитам \n-▲большойкалибр臼пушкаX2 только по земле взрывной урон\n-▲ВПУ зенитных ракетX2 по земле и воздуху взрывной урон против сверхтяжёлых юнитурон-бонус\n-вовсе непреувеличивать говорить，Суперкорабльабсолютныйявляетсячеловечествосоздаватькорабль史верходин не может逾越 высокий峰。\n-его采использоватьдо卫 двойной体корабльпроектировать，позволятьегоможетв保持высокийскорость хода одновременно，\n-несётчисло ядерныйсынреакторисего相соединять большой оружие，\n-ядерныйЭлектричествопривод Рельсотрондостаточно дляпробитьчеловечество认знатьв большинствоброня，\n-кромеэтот ужасающий Рельсотрони более，ещёиметь独立 защитаПустоогневая сетьа такжеспособенудар垮любойнадводныйбоевой корабль противокорабельныйоружиегруппа。\n-этотпозволяетонпочтиможетодиночный舰разгромитьостаток晖 малый 海Пусто立体удар。\n-若Генезисистинныйестьспособенизменятьвойна局 надводныйбоевой корабль，тоттолькоможетявляетсяколичествотолькоестьоднако20  Суперкорабль，\n-Зарево 花哨玩具们указанныйхорошийхороший考虑考虑сам находиться境 。
techLevel: 1
price: 8000,钍=255,bj= ${bjxq}
@global bjxq:25
reclaimPrice: bj= ${bjxq}
maxHp: 72000
footprint: -4,-9,4,9
constructionFootprint: -4,-9,4,9
armour: 195
buildSpeed: 155s
softCollisionOnAll: 70
radius: 140
transportSlotsNeeded: 30
fogOfWarSightRange: 55
copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
tags: 地面,海上,极端重型,反高空
selfRegenRate: 1
energyMax: 7
energyRegen: 0.025
energyNeedsToRechargeToFull: true
unitsSpawnedOnDeath: 大型水上单位死亡*1
showInEditor: false
isBuilding: true
[action_t答辩]
autoTrigger: if self.timeAlive(laterThanSeconds=0.1)
isVisible: false
convertTo: 超战舰
convertTo_keepCurrentFields:maxHp
convertTo_keepCurrentTags:true
[attachment_1]
x: 0
y:0
onCreateSpawnUnitOf:超火箭炮
setDrawLayerOnBottom:false
lockRotation: false
prioritizeParentsMainTarget: true
resetRotationWhenNotAttacking: true
alwaysAllowedToAttackParentsMainTarget: true

[action_重]
text: крайне端тяжёлыйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积преувеличивать юнит独есть характеристика，\n-иметькрайне端тяжёлыйюнит标签 юнитбудетиметькакнизпринадлежатьтип，\n-иметь 愈способность，исобственный护甲ненизкийв100пункт，\n-не может шок，но受допротивтяжёлый甲юнит伤害бафф。
[decal_灯光]
layer: afterBody
image: 白光.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
[decal_灯光1]
layer: afterBody
image: 红光.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:-8
xOffsetRelative:0
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
[decal_转子]
image: 引擎.png
total_frames: 6
frame: (self.customTimer * 20) % 6
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:0
yOffsetRelative:-185
isVisible:if self.maxHp * 0.36 < self.hp
layer: afterBody
[graphics]
total_frames: 1
image: 船体.png
image_wreak: 死亡.png
showTransportBar: false
image_shadow: AUTO
shadowOffsetX: 5
shadowOffsetY: 5
teamColorsOnTurret: true
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 12
turretImageScale: 0.9
[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 17
turretTurnSpeed: 3
maxAttackRange: 1050
shootDelay: 120
turretMultiTargeting: true
[turret_0]
x: 0
y: 85
canShoot: false
image: 底座.png
limitingAngle: 140
limitingMinRange: 350
turnSpeed: 1
turnSpeedAcceleration: 0.1
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
[turret_1]
x: -8
y: 23
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.35
shoot_flame: CUSTOM:烟雾*5
shoot_light: #FFFFEB88
canShoot: true
recoilOffset: -17
recoilOutTime: 5
recoilReturnTime: 30
delay: 180
size:12
canAttackFlyingUnits:false
image: 内管.png
attachedTo: 0
slave: true
limitingMinRange: 350
canAttackUnderwaterUnits:false
[turret_2]
x: -8
y: 23
projectile: 2
shoot_sound:NONE
canShoot: true
recoilOffset: -6
recoilOutTime: 10
recoilReturnTime: 25
delay: 180
size:22
image: 左管.png
attachedTo: 0
slave: true
limitingMinRange: 350
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
[turret_3]
x: 8
y: 23
copyFrom: 1
linkDelayWithTurret:1
delay:150
warmup:30
[turret_4]
x: 8
y: 23
copyFrom: 2
linkDelayWithTurret:2
delay:150
warmup:30
[turret_5]
x: -20
y: -4
projectile: 2
turnSpeed: 0
shoot_sound:NONE
canShoot: true
recoilOffset: -8
recoilOutTime: 5
recoilReturnTime: 60
delay: 180
size:22
image: 柱.png
attachedTo: 0
limitingMinRange: 350
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
canAttackMaxAngle: 181
idleDir:225
[turret_6]
x: 20
y: -4
copyFrom: 5
idleDir:-225
[turret_7]
x: -20
y: -11
projectile: 2
turnSpeed: 0
shoot_sound:NONE
canShoot: true
recoilOffset: -8
recoilOutTime: 5
recoilReturnTime: 60
delay: 150
warmup:30
size:22
image: 小柱.png
attachedTo: 0
limitingMinRange: 350
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
canAttackMaxAngle: 181
linkDelayWithTurret:2
idleDir:225
[turret_8]
x: 20
y: -11
copyFrom: 7
idleDir:-225
[turret_9]
x:0
y:-14
canShoot: false
image: 轨道炮遮盖.png
attachedTo: 0
slave: true
[turret_10]
x: 5
y: 21
projectile: 3
attachedTo: 12
slave: true
image: 炮管.png
shoot_flame: large
shoot_sound: ROOT:/创世纪军事集团/单位特效/坦克音效.ogg
shoot_sound_vol: 0.3
canShoot: true
recoilOffset: -8
size:11
recoilOutTime: 2
recoilReturnTime:10
aimOffsetSpread: 0.1
delay:25
canOnlyAttackUnitsWithoutTags:高空

[turret_11]
x:-5
y:21
copyFrom: 10
attachedTo: 12
slave: true
delay:15
linkDelayWithTurret:10
warmup:10
[turret_12]
x: -70
y: -85
canShoot: false
image: 自动炮.png
limitingAngle: 85
turnSpeed: 4
turnSpeedAcceleration: 1
canAttackLandUnits: true
canAttackUnderwaterUnits: false
canAttackFlyingUnits:true
canOnlyAttackUnitsWithoutTags:高空
idleDir:-35
[turret_13]
x:-5
y:21
copyFrom: 10
attachedTo: 15
slave: true
delay:25
[turret_14]
x:5
y:21
copyFrom: 10
attachedTo: 15
slave: true
delay:15
linkDelayWithTurret:13
warmup:10
[turret_15]
x:70
y:-85
copyFrom: 12
idleDir:35
[turret_16]
x: -40
y: -160
canShoot: false
image: 炮座.png
#limitingAngle: 85
turnSpeed: 0.8
turnSpeedAcceleration: 0.05
canAttackLandUnits: true
canAttackUnderwaterUnits: false
canAttackFlyingUnits:false
idleDir:-90
limitingMinRange:680
[turret_17]
x: 0
y: 23
projectile: 4
attachedTo: 16
slave: true
image: 大炮.png
shoot_flame: CUSTOM:烟雾*8,CUSTOM:冲击波t,CUSTOM:闪光t
shoot_sound: ROOT:/创世纪军事集团/单位特效/巨炮发射.wav
shoot_sound_vol: 0.5
canShoot: true
recoilOffset: -10
size:11
recoilOutTime: 2
recoilReturnTime:70
aimOffsetSpread: 0.1
delay:450
canAttackFlyingUnits:false
canAttackUnderwaterUnits:false
limitingMinRange:680
[turret_18]
x: 0
y: 0
canShoot: false
image: 遮盖.png
#limitingAngle: 85
canAttackLandUnits: true
canAttackUnderwaterUnits: false
canAttackFlyingUnits:false
attachedTo: 16
slave: true
limitingMinRange:680
[turret_19]
x:40
y:-160
copyFrom: 16
idleDir:90
[turret_20]
x:0
y:23
copyFrom: 17
attachedTo: 19
slave: true
delay:330
warmup:120
[turret_21]
x:0
y:0
copyFrom: 18
attachedTo: 19
slave: true
[turret_22]
x: -32
y: 22
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾1*5, CUSTOM:冲击波t
shoot_light: #FFEECCCC
projectile: 5
size: 0
turnSpeed: 811
delay: 240
#canOnlyAttackUnitsWithTags:高空
limitingMinRange: 450
[turret_23]
x:-32
y:36
copyFrom: 22
delay: 210
warmup:30
linkDelayWithTurret:22
[turret_24]
x:32
y:22
copyFrom: 22
delay:180
warmup:60
linkDelayWithTurret:23
[turret_25]
x:32
y:36
copyFrom: 22
delay: 150
warmup:90
linkDelayWithTurret:24
[projectile_1]
@copyFromSection: template_动能
directDamage: 2000
life: 200
speed: 16
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
drawSize: 0.74
explodeEffect: CUSTOM:底色, CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:碎星*9,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波2,CUSTOM:实验,CUSTOM:穿透
explodeEffectOnShield: CUSTOM:底色, CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:碎星*15,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波2,CUSTOM:实验,CUSTOM:穿透
lightSize: 1
trailEffectRate: 0.25
trailEffect: CUSTOM:尾巴3,CUSTOM:尾巴1,CUSTOM:尾巴2
lightColor: #FFFF1200
[projectile_2]
directDamage: 0
life: -4
instant: true
drawSize: 0
frame: 33
color: #FF25E0AF
explodeEffect: none
[projectile_3]
@copyFromSection: template_动能
#主炮子弹
directDamage: 180
shieldDamageMultiplier: 3.5
life: 120
speed: 11
color: #BBBBFFEE
drawSize: 1
largeHitEffect: true
lightSize: 1
frame: 8
lightColor:#BBBBFFEE
explodeEffect: CUSTOM:闪光t,CUSTOM:冲击波t,CUSTOM:钢珠t*2,CUSTOM:穿透t
explodeEffectOnShield:CUSTOM:闪光t,CUSTOM:冲击波t,CUSTOM:钢珠t*2,CUSTOM:穿透t
trailEffectRate: 0.2
trailEffect: CUSTOM:尾尾
[projectile_4]
@copyFromSection: template_爆炸
areaDamage: 4500
areaRadius: 100
life: 800
speed: 1
deflectionPower: -1
areaRadiusFromEdge: true
targetSpeed: 6.5
image: ROOT:/创世纪军事集团/单位特效/光球.png
drawSize: 0.75
explodeEffect: CUSTOM:爆炸p,CUSTOM:气浪p,CUSTOM:冲击波p,CUSTOM:闪光p*2,CUSTOM:弹坑p
initialUnguidedSpeedHeight: 3.5
trueGravity: 0.009
lightSize: 0.75
trailEffectRate: 0.5
trailEffect: CUSTOM:尾尾1
lightColor: #FFFFFF73
targetGround:true
disableLeadTargeting: true
targetGroundSpread: 40
[projectile_5]
life: 45
speed: 3
targetSpeed: 0
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:导弹碎片1


[projectile_锁定1]
@copyFromSection: template_爆炸
directDamage: 1300
life: 200
speed: 7
image: ROOT:/创世纪军事集团/单位特效/新大导弹1.png
targetSpeed: 12
drawSize:0.8
explodeEffect: CUSTOM:冲击波a,CUSTOM:爆炸a, CUSTOM:闪光a,CUSTOM:钢珠a
explodeEffectOnShield: CUSTOM:冲击波a,CUSTOM:爆炸a, CUSTOM:闪光a,CUSTOM:钢珠a
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
trailEffectRate: 1.2
#轨道炮特效————————
[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
#color:#FFFF1200
[effect_闪光]
#priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: true
atmospheric: false
[effect_底色]
priority: critical
image: ROOT:/太空浪人/单位特效/收缩2.png
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.6
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1.6
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:30
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.2
scaleTo:1.5
alpha: 0.8
fadeInTime: 4
drawUnderUnits:false
[effect_碎星]
spawnChance: 1
createWhenZoomedOut: false
life: 60
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom:0.3
scaleTo:0.3
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 5
ySpeedRelativeRandom: 5
[effect_穿透]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
life: 55
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.6
scaleTo: 0.9
alpha: 1
drawUnderUnits: false
ySpeedRelative: 5
atmospheric: true
[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 60
fadeOut: true
attachedToUnit: false
scaleFrom: 2.4
scaleTo: 2.4
alpha: 0.6
drawUnderUnits: true
atmospheric: false
[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.6
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true

#轨道炮尾巴————
[effect_尾巴2]
priority: veryhigh
image: SHARED:light_50.png
life: 25
fadeOut: true
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1
drawUnderUnits: true
[effect_尾巴3]
priority: high
image: ROOT:/创世纪军事集团/单位特效/冲击波.png
life: 30
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.01
scaleTo: 0.45
alpha: 0.8
drawUnderUnits: true
atmospheric: false

[effect_尾巴1]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
drawUnderUnits: false
#突击炮特效————————
[effect_爆炸t]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/撞击.ogg
alwayStartDirAtZero: true
[effect_钢珠t]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.1
alpha: 0.8
scaleTo: 1.7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_冲击波t]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 2.6
alpha: 0.8
fadeOut: true
fadeInTime: 2
[effect_闪光t]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false
atmospheric: false
[effect_穿透t]
priority: high
frameIndex: 4
stripIndex: projectiles2
life: 45
fadeOut: true
attachedToUnit: false
color: #BBBBFFEE
scaleFrom: 1.8
scaleTo: 0.8
alpha: 1
drawUnderUnits: false
ySpeedRelative: 8
atmospheric: false
[effect_尾尾]
image: SHARED:light_50.png
life: 20
fadeOut: true
attachedToUnit: false
priority: low
color:#FFFFFFFF
fadeInTime: 2
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.8
#臼炮特效————
[effect_弹坑p]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.2
scaleTo: 2.2
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true
[effect_气浪p]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 6.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true
[effect_闪光p]
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波p]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_爆炸p]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 4.2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
createWhenOffscreen: true
[effect_尾尾1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1
#导弹特效————————
[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/大导弹碎片1.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/大导弹碎片.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10

[effect_闪光a]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false


[effect_爆炸a]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.3
scaleTo: 2.2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_钢珠a]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波a]
life: 100
priority:veryhigh
attachedToUnit: true
scaleFrom: 0.4
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.22
alwayStartDirAtZero: true
alpha: 0.8
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
createWhenOverLand: false
life: 130
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 3
scaleTo:9
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -70
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
[effect_火]
life: 140
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1.2
scaleTo: 4.5
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1.5
yOffsetRelative	: -40
drawUnderUnits: true
[effect_烟雾1]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[arm_1]
x: 0
y: 0
image_end: 背景.png
image_end_teamColors: true
drawUnderAllUnits: true
[arm_2]
x: 0
y: 0
image_end: 船体1.png
image_end_teamColors: true
drawUnderAllUnits: true
[arm_3]
x: 0
y: -128.5
image_end: 核心.png
image_end_teamColors: true
drawUnderAllUnits: true
spinRate:-0.6
#drawOverBody: true
[arm_4]
x: 0
y: -93
image_end: 雷达.png
drawOverBody: true
spinRate: 4
[arm_5]
x: 0
y: -40
image_end: ROOT:/创世纪军事集团/单位特效/雷达.png
drawOverBody: true
spinRate: 8
[arm_6]
x: 0
y: 0
image_end: 导弹盖.png
image_end_teamColors: true
drawUnderAllUnits: true
hidden:if self.isAttacking()
[movement]
movementType: WATER
moveSpeed: 0.52
moveAccelerationSpeed: 0.022
moveDecelerationSpeed: 0.013
maxTurnSpeed: 0.4
turnAcceleration: 0.01


