


[core]
name: 超火箭炮
displayText: Супер-РСЗО
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true

[decal_炮塔影子]
image: 火箭炮影.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:4.5
xOffsetRelative:3.5
onlyWhileAlive:true
basePositionFromTurret:1
imageScale:0.85
alpha:0.75
[decal_炮塔影子1]
image: 火箭炮影.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:4.5
xOffsetRelative:3.5
onlyWhileAlive:true
basePositionFromTurret:10
imageScale:0.85
alpha:0.75
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
turretImageScale: 0.85
teamColorsOnTurret: true
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:true
canAttackUnderwaterUnits: false
maxAttackRange: 1150
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0


[turret_1]
x: -38
y: 145
canShoot: false
image:火箭炮.png
limitingAngle: 110
idleDir:-35
canAttackFlyingUnits: false
[turret_2]
x: 9
y: 8
projectile: 1
attachedTo: 1
slave: true
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾*2
shoot_light: #FFEECCCC
canShoot: true
limitingMinRange: 100
delay:360
canAttackFlyingUnits: false
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
[turret_3]
x: 9
y: 8
copyFrom: 2
linkDelayWithTurret:2
delay:350
warmup:10
[turret_4]
x: 9
y: 8
copyFrom: 2
linkDelayWithTurret:3
delay:340
warmup:20
[turret_5]
x: 9
y: 8
copyFrom:2
linkDelayWithTurret:4
delay:330
warmup:30
[turret_6]
x: -9
y: 8
copyFrom: 2
linkDelayWithTurret:5
delay:320
warmup:40
[turret_7]
x: -9
y: 8
copyFrom: 2
linkDelayWithTurret:6
delay:310
warmup:50
[turret_8]
x: -9
y: 8
copyFrom:2
linkDelayWithTurret:7
delay:300
warmup:60
[turret_9]
x: -9
y: 8
copyFrom:2
linkDelayWithTurret:8
delay:290
warmup:70
[turret_10]
x: 38
y: 145
canShoot: false
image:火箭炮.png
limitingAngle: 110
idleDir:35
canAttackFlyingUnits: false


[turret_11]
x: 9
y: 8
projectile: 1
attachedTo: 10
slave: true
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾*2
shoot_light: #FFEECCCC
canShoot: true
canAttackFlyingUnits: false

altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
limitingMinRange: 100
delay:360
[turret_12]
x: 9
y: 8
copyFrom: 11
linkDelayWithTurret:11
delay:350
warmup:10
[turret_13]
x: 9
y: 8
copyFrom: 11
linkDelayWithTurret:12
delay:340
warmup:20
[turret_14]
x: 9
y: 8
copyFrom:11
linkDelayWithTurret:13
delay:330
warmup:30
[turret_15]
x: -9
y: 8
copyFrom: 11
linkDelayWithTurret:14
delay:320
warmup:40
[turret_16]
x: -9
y: 8
copyFrom: 11
linkDelayWithTurret:15
delay:310
warmup:50
[turret_17]
x: -9
y: 8
copyFrom:11
linkDelayWithTurret:16
delay:300
warmup:60
[turret_18]
x: -9
y: 8
copyFrom:11
linkDelayWithTurret:17
delay:290
warmup:70
[projectile_1]
@copyFromSection: template_爆炸
#普通炮弹
areaDamage:  500
areaRadius: 50
life: 180
speed: 2
color: #FFFFFF73
trailEffect: true
lightSize: 1.5
image:ROOT:/创世纪军事集团/单位特效/中导弹.png
lightColor: #FFFFFF73
drawSize: 0.75
targetSpeed: 11
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波
targetGround:true
disableLeadTargeting: true
trailEffectRate: 1.5
targetGroundSpread: 40
[projectile_炮弹]
@copyFromSection: template_能源
#普通炮弹
areaDamage: 775
areaRadius: 70
life: 180
speed: 2
color: #FFFFFF73
trailEffect: true
lightSize: 1.5
image:ROOT:/创世纪军事集团/单位特效/中导弹.png
lightColor: #FFFFFF73
drawSize: 0.75
targetSpeed: 11
areaRadiusFromEdge: true
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
targetGround:true
disableLeadTargeting: true
trailEffectRate: 1.5
targetGroundSpread: 40
buildingDamageMultiplier: 1.2
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.9
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 2.1
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1.05
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
#——————————聚变

[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 1.2
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 8
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 1.3
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_实验jb]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:10
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.6
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
spawnChance: 0.35
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 1.6
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


