


[core]
name: 雷暴本体
strictLevel: 1
price: 0
radius: 10
maxHp: 1
class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: 雷暴本体,反高空,免疫烟雾
canNotBeDirectlyAttacked: true
isUnrepairableUnit: true
disableAllUnitCollisions: true
selfRegenRate: 2
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
energyMax: 16
energyStartingPercentage: 1
energyRegen: 0
[attachment_1]
x: 0
y: 0
isUnselectable:true
onCreateSpawnUnitOf:雷暴本体2
lockRotation: true
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false
setDrawLayerOnTop:true
idleDir:0
#————————————装填
[hiddenAction_装]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
whenBuilding_cannotMove:false
allowMultipleInQueue:false
autoTrigger: if self.energy<0.5 and not self.tags(includes= '切枪')
alsoQueueAction: ax
temporarilyAddTags: 切枪
playSoundAtUnit:  ROOT:/通用特效/部署.ogg

[action_ax]
displayType: action
price: 0
whenBuilding_playAnimation: 部署
buildSpeed: 7s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
addResources:energy=16
[decal_遮盖]
image:遮.png
total_frames: 1
teamColors: true
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret: 1
imageScale: 0.82
[graphics]
total_frames: 1
image: 导导导导1.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
teamColorsOnTurret: true
imageScale: 0.82
turretImageScale: 0.82
image_shadow: AUTO
shadowOffsetX: 4.5
shadowOffsetY: 4.5
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 2000
turretSize: 24
turretTurnSpeed: 3
isFixedFiring: true
aimOffsetSpread: -0.01
turretMultiTargeting: true
[turret_1]
x: 0
y: 0
#武器底座
canShoot: false
delay: 0
limitingMinRange: 650
canOnlyAttackUnitsWithoutTags:伴生单位
shouldResetTurret: false
[turret_2]
x: 65.5
y: -18
#导弹右
projectile: 1
attachedTo: 1
size:17
slave: true
image: 导弹头.png
shoot_sound: nuke_launch
shoot_sound_vol: 0.33
shoot_flame: CUSTOM:冲击波,CUSTOM:烟雾*10,CUSTOM:闪光
canShoot: true
limitingMinRange: 650
canAttackCondition: if self.energy==16
invisible: if self.energy<16
energyUsage:1
delay:180
canOnlyAttackUnitsWithoutTags:伴生单位
warmup:140
[turret_3]
x: 45.5
y: -18
copyFrom: 2
canAttackCondition: if self.energy==15
invisible: if self.energy<15




[turret_4]
x: 55.5
y: -4
copyFrom: 2
canAttackCondition: if self.energy==14
invisible: if self.energy<14




[turret_5]
x: 65.5
y: 10
copyFrom: 2
canAttackCondition: if self.energy==13
invisible: if self.energy<13
[turret_6]
x: 45.5
y: 10
copyFrom: 2
canAttackCondition: if self.energy==12
invisible: if self.energy<12




[turret_7]
x: 55.5
y: 24
copyFrom: 2
canAttackCondition: if self.energy==11
invisible: if self.energy<11




[turret_8]
x: 65.5
y: 38
copyFrom: 2
canAttackCondition: if self.energy==10
invisible: if self.energy<10
[turret_9]
x: 45.5
y: 38
copyFrom: 2
canAttackCondition: if self.energy==9
invisible: if self.energy<9

#————————————————对面
[turret_10]
x: -65.5
y: -18
copyFrom: 2
canAttackCondition: if self.energy==8
invisible: if self.energy<8
[turret_11]
x: -45.5
y: -18
copyFrom: 2
canAttackCondition: if self.energy==7
invisible: if self.energy<7



[turret_12]
x: -55.5
y: -4
copyFrom: 2
canAttackCondition: if self.energy==6
invisible: if self.energy<6




[turret_13]
x: -65.5
y: 10
copyFrom: 2
canAttackCondition: if self.energy==5
invisible: if self.energy<5
[turret_14]
x: -45.5
y: 10
copyFrom: 2
canAttackCondition: if self.energy==4
invisible: if self.energy<4




[turret_15]
x: -55.5
y: 24
copyFrom: 2
canAttackCondition: if self.energy==3
invisible: if self.energy<3




[turret_16]
x: -65.5
y: 38
copyFrom: 2
canAttackCondition: if self.energy==2
invisible: if self.energy<2
[turret_17]
x: -45.5
y: 38
copyFrom: 2
canAttackCondition: if self.energy==1
invisible: if self.energy<1
[projectile_1]
@copyFromSection: template_能源
life: 140
speed: 0
targetSpeed: 9
targetSpeedAcceleration: 0.05
image: 导弹.png
drawSize: 0.9
spawnProjectilesOnEndOfLife: 2
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:橙色闪光,CUSTOM:橙色光点*16,CUSTOM:橙色冲击波,CUSTOM:火光,CUSTOM:白光*2
areaDamage: 1
areaRadiusFromEdge: true
areaHitAirAndLandAtSameTime: false
alwaysVisibleInFog: true
areaRadius: 180
deflectionPower: -1
shouldRevealFog: true
lightColor: #FFEEEE00
lightSize: 0
trailEffect: CUSTOM:projectileTrail
trailEffectRate: 0.8
autoTargetingOnDeadTarget: true
turnSpeed: 0
[projectile_2]
@copyFromSection: template_能源
areaDamage:8000
areaRadius: 145
deflectionPower: -1
life: 6000
speed: 20
image:大闪光.png
drawSize: 0.8
largeHitEffect: true
lightSize: 8
lightColor: #FFFFEF00
trailEffectRate: 0.25
trailEffect: CUSTOM:尾巴1,CUSTOM:尾巴,CUSTOM:尾巴2
explodeEffect: CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
explodeEffectOnShield:CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk
areaRadiusFromEdge: true
autoTargetingOnDeadTarget: true
mutator7_ifUnitWithTags: 飞机
mutator7_directDamageMultiplier: 2.5
mutator7_areaDamageMultiplier: 2.5
#————————————小导弹开火
[effect_冲击波]
life: 100
priority: low
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1.2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: false
[effect_闪光]
priority:verylow
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life:90
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.35
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.2
ySpeedRelative: 0.5
atmospheric: true
#————————————小导弹尾巴
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 80
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 2.1
alpha: 0.7
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -14
[effect_导弹碎片]
#priority: high
image: 导弹1.png
spawnChance: 1
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
ySpeedRelative: -2.7
hSpeed: 1.5
dirSpeedRandom: 25
#————————————小导弹击发
[effect_橙色闪光]
image: SHARED:light_50.png
life:30
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE

fadeInTime: 2
scaleFrom: 9
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_橙色冲击波]
life: 100
priority: low
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: false
color:#FFFF5B18
alpha:0.8
[effect_橙色光点]
spawnChance: 1
createWhenZoomedOut: false
life: 80
fadeOut: true
attachedToUnit: false
fadeInTime: 10
image: 光束.png
scaleFrom: 0.8
scaleTo: 0.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 1.8
ySpeedRelativeRandom: 4
ySpeedRelative: 7
#atmospheric: true

[effect_火光]
priority: critical
image: ROOT:/通用特效/火光.png
life: 80
fadeOut: true
attachedToUnit: false
alpha: 0.9
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 1
scaleTo: 5
color: #FFFFF44C
alsoPlaySound: ROOT:/通用特效/波雷.wav
[effect_白光]
priority:verylow
image: SHARED:light_50.png
life: 170
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FFFF5B18
fadeInTime: 2
scaleFrom: 3
scaleTo: 3
drawUnderUnits: false
atmospheric: false
#————————————射流尾巴
[effect_尾巴]
life: 37
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative: 0
yOffsetRelative: -5
ySpeedRelative:-1
[effect_尾巴1]
life: 70
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 1
color: #FFFFC100
xOffsetRelative: 0
yOffsetRelative: -5
ySpeedRelative:-1
[effect_尾巴2]
image: 光束.png
spawnChance: 1
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 0.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: -0.35
ySpeedRelativeRandom: 1
xSpeedRelativeRandom: 2
atmospheric: true
xOffsetRelativeRandom: 10
#————————————炮弹爆炸
[effect_聚变nk]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 2.6
scaleTo: 2.6
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 180
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 11
scaleTo: 11
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
[effect_冲击波nk]
life: 70
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 3.1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true

[effect_冲击波nk1]
priority: low
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 3
alpha: 0.8
showInFog: true
drawUnderUnits: false
atmospheric: false
#——————@——————看NM，给👴爬


[effect_光球nk]
life: 120
priority: veryhigh
attachedToUnit: false
scaleFrom:1.1
scaleTo: 1.1
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
ySpeedAbsolute:0
fadeOut: true
alpha: 0.85
showInFog: true
alsoPlaySound: ROOT:/通用特效/巨炮爆炸x.wav
createWhenOffscreen: true
[effect_光球1nk]
life: 135
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
image: 光球.png
fadeOut: true
showInFog: true
alpha: 0.7
fadeInTime: 1
createWhenOffscreen: true

[effect_聚变nk1]
image: ROOT:/通用特效/火光.png
life: 120
fadeOut: true
attachedToUnit: false
alpha: 0.9
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 3
scaleTo: 10
color: #FFFFF44C
alwayStartDirAtZero: true
createWhenOffscreen: true
[effect_冲击波nk3]
priority: high
image: ROOT:/创世纪军事集团/单位特效/冲击波4.png
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 3
alpha: 0.8
drawUnderUnits: true
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:60
fadeOut: true
attachedToUnit:false
createWhenOffscreen: true
scaleFrom:1.5
scaleTo:4.5
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180



[arm_1]
x: 55.5
y: -65
image_end: 导弹盒.png
image_end_teamColors: true
drawOverBody:true
[arm_2]
x: 55.5
y: -35
image_end: 导弹架.png
image_end_teamColors: true
drawOverBody:true
[arm_3]
x: 55.5
y: -65
image_end: 导弹盒1.png
image_end_teamColors: true
drawOverBody:true

[arm_4]
x: -55.5
y: -65
image_end: 导弹盒.png
image_end_teamColors: true
drawOverBody:true
[arm_5]
x: -55.5
y: -35
image_end: 导弹架.png
image_end_teamColors: true
drawOverBody:true
[arm_6]
x: -55.5
y: -65
image_end: 导弹盒1.png
image_end_teamColors: true
drawOverBody:true
[animation_部署]
#——————————装弹器动画
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}

arm1_1.5s: {x:0, y:-20, dir:0}
arm2_1.5s: {x:0, y:0, dir:0}
arm3_1.5s: {x:0, y:-20, dir:0}
arm4_1.5s: {x:0, y:-20, dir:0}
arm5_1.5s: {x:0, y:0, dir:0}
arm6_1.5s: {x:0, y:-20, dir:0}

arm1_3s: {x:0, y:-20, dir:0}
arm2_3s: {x:0, y:-50, dir:0}
arm3_3s: {x:0, y:-20, dir:0}
arm4_3s: {x:0, y:-20, dir:0}
arm5_3s: {x:0, y:-50, dir:0}
arm6_3s: {x:0, y:-20, dir:0}

arm1_3.5s: {x:0, y:-20, dir:0}
arm2_3.5s: {x:0, y:-50, dir:0}
arm3_3.5s: {x:0, y:-20, dir:0}
arm4_3.5s: {x:0, y:-20, dir:0}
arm5_3.5s: {x:0, y:-50, dir:0}
arm6_3.5s: {x:0, y:-20, dir:0}

arm1_5s: {x:0, y:17, dir:0}
arm2_5s: {x:0, y:-20, dir:0}
arm3_5s: {x:0, y:17, dir:0}
arm4_5s: {x:0, y:17, dir:0}
arm5_5s: {x:0, y:-20, dir:0}
arm6_5s: {x:0, y:17, dir:0}

arm1_6s: {x:0, y:17, dir:0}
arm2_6s: {x:0, y:-20, dir:0}
arm3_6s: {x:0, y:17, dir:0}
arm4_6s: {x:0, y:17, dir:0}
arm5_6s: {x:0, y:-20, dir:0}
arm6_6s: {x:0, y:17, dir:0}

arm1_7s: {x:0, y:0, dir:0}
arm2_7s: {x:0, y:0, dir:0}
arm3_7s: {x:0, y:0, dir:0}
arm4_7s: {x:0, y:0, dir:0}
arm5_7s: {x:0, y:0, dir:0}
arm6_7s: {x:0, y:0, dir:0}
[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 1
turnAcceleration: 0.04
moveSlidingMode : false
moveIgnoringBody: false