


[core]
name: 挑战者坦克
price: 3400
maxHp: 11000
displayDescription: 【阶级t4】【机械单位】【地面单位】【重型掩体】战术定位:泛用型反单体坦克，\n-单位体积:6，武器配置：▲280毫米炮X1 只能对地 动能伤害\n-创世纪科研部认为，必须用庞然大物来打败庞然大物，\n-为此，创世纪新一代主战坦克集合了各种各样的夸张设计，\n-挑战者坦克配有280毫米重炮以及高于常规坦克两倍厚度的合金装甲，\n-并使用钍基熔盐裂变堆供能，赋予了其搭载最新轨道发射器的能力，\n-以及完美无瑕的机动性，无论面对余辉的庞然大物还是机甲集群 ，\n-挑战者坦克都能以绝对的火力优势挽回败局。
fogOfWarSightRange: 21
techLevel: 1
buildSpeed: 11s
radius: 49
displayRadius: 49
isBio: false
transportSlotsNeeded:6
softCollisionOnAll: 10
armour: 50
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,重型掩体,驻扎要塞
copyFrom: ROOT:/通用特效/单位防护.ini

[hiddenAction_掩体1取消]
autoTrigger:if self.hasParent and self.tags(includes= '重型掩体')
isVisible:false
temporarilyRemoveTags:重型掩体
[hiddenAction_掩体1生成]
autoTrigger:if not self.hasParent and not self.tags(includes= '重型掩体')
isVisible:false
temporarilyAddTags:重型掩体




[action_tx1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[decal_主体损坏a]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
#———————科技————
#—————————休克
[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

#——————————————科技
[action_电磁炮3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道3.png
text: 轨道发射器3
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器3')
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: 恐怖地雷1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[action_先进目标定位核心1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位1.png
text: 先进目标定位核心1
isActive: false
isVisible: if self.globalTeamTags(includes='目标定位1')
[hiddenAction_目标定位生效]
autoTrigger: if self.globalTeamTags(includes='目标定位1')
setUnitStats: maxAttackRange= ${attack.maxAttackRange*1.35},fogOfWarSightRange= ${core.fogOfWarSightRange*1.35}
temporarilyAddTags:免疫烟雾
[decal_炮塔影子]
image: 炮塔影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_炮管影子]
image: 炮管影子.png
total_frames: 1
layer: afterBody
isVisible:if not self.globalTeamTags(includes='轨道发射器3')
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 2
[decal_炮管影子1]
image: 炮管影子1.png
total_frames: 1
layer: afterBody
isVisible:if self.globalTeamTags(includes='轨道发射器3')
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 2
[decal_加速器]
image: 轨道1.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.maxHp * 0.36< self.hp and self.globalTeamTags(includes='轨道发射器3')
yOffsetRelative:39
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_加速器损坏]
image: 轨道损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 and self.globalTeamTags(includes='轨道发射器3')
yOffsetRelative:39
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_加速器影子]
image: 特殊.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:if self.globalTeamTags(includes='轨道发射器3')
yOffsetRelative:39
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_炮塔损坏]
image: 炮塔损坏.png
total_frames: 1
layer: onTop
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 3
[graphics]
total_frames: 3
image: 底盘.png
image_wreak: 死亡.png
image_turret: 炮塔.png
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 3
shadowOffsetY: 3
animation_moving_start: 0
animation_moving_end: 2

animation_moving_speed: 1
movementEffect: CUSTOM:烟1,CUSTOM:烟2
movementEffectRate: 20


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
disablePassiveTargeting: false

turretMultiTargeting: true
turretSize: 22
turretTurnSpeed: 1.7
maxAttackRange: 430
#—————模块化————

#——————炮塔

[turret_1]
x: 0
y: 80
#主炮
projectile: 炮弹
turnSpeed: 1.4

turnSpeedAcceleration: 0.04
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:烟雾*10
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -9
recoilOutTime: 5
recoilReturnTime: 20
delay: 180
invisible:if not self.globalTeamTags(includes='轨道发射器3')
size: 27
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='轨道发射器3')
image: 轨道炮管.png
attachedTo: 3
slave: true
canAttackFlyingUnits: false
[turret_2]
x: 0
y: 80
#主炮
projectile: 1
turnSpeed: 1.4

turnSpeedAcceleration: 0.04
shoot_sound: ROOT:/创世纪军事集团/单位特效/突击炮音效.ogg
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:烟雾*8,CUSTOM:枪口火焰
shoot_light: #FFEECCCC
canAttackFlyingUnits: false
canShoot: true
recoilOffset: -9
recoilOutTime: 5
recoilReturnTime: 20
delay: 180
invisible:if self.globalTeamTags(includes='轨道发射器3')
size: 27
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='轨道发射器3')
image: 炮管.png
attachedTo: 3
slave: true



[turret_3]
x: 0
y: -15
#炮塔
canShoot: false
canAttackFlyingUnits: false

canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1
idleSweepAngle: 20
idleSweepDelay: 230
idleSweepSpeed: 0.2




[turret_5]
x: 13
y: 6
attachedTo: 3
projectile: 2
slave: true
delay: 1
canShoot: true
invisible: true
aimOffsetSpread: -0.01
canAttackFlyingUnits: false
canAttackCondition: if self.resource.xk < 1 and not self.hasParent
[projectile_1]
@copyFromSection: template_动能
#主炮子弹
directDamage: 2000
life: 260
speed: 10

color: #FFFFFF73
largeHitEffect: true
lightSize: 1.5
frame: 9
lightColor: #FFFFFF73

drawSize: 0.8
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:钢珠
trailEffectRate: 0.85
trailEffect: CUSTOM:尾巴jb
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 2
mutator7_areaDamageMultiplier: 2

[projectile_炮弹]
@copyFromSection: template_动能
directDamage: 2750
life: 300
speed: 14
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
drawSize: 0.7
explodeEffect: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*15,CUSTOM:冲击波gd,CUSTOM:聚变gd,CUSTOM:实验,CUSTOM:穿透
explodeEffectOnShield: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*15,CUSTOM:冲击波gd,CUSTOM:聚变gd,CUSTOM:实验,CUSTOM:穿透
lightSize: 1
trailEffectRate: 0.28
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴2
lightColor: #FFFF1200
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 1.7
mutator7_areaDamageMultiplier: 1.7
armourIgnoreAmount: 10
shieldDamageMultiplier: 1.2
[projectile_2]
directDamage: 0
life: -4
instant: true
frame: 33
beamImage: 光.png

beamImageEnd: SHARED:beam1_end.png
beamImageStart: SHARED:beam1_start.png
color: #FFFF1200
explodeEffect: none
#————————主炮发射特效


[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1

scaleTo: 2.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.65
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1

atmospheric: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 5
scaleTo: 5


[effect_尾巴jb]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true
#——————————主炮命中特效


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.6

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸a.ogg
alwayStartDirAtZero: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1.8
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 2
scaleTo: 2
createWhenOverLiquid: false
createWhenOverLand: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4.5
scaleTo: 4.5
drawUnderUnits: false

atmospheric: false
#履带特效—————————


[effect_烟1]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative	: 24
yOffsetRelative	: -50


[effect_烟2]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative	: -24
yOffsetRelative	: -50

#————————-——轨道
[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_冲击波gd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.25
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_爆炸1gd]
image: ROOT:/创世纪军事集团/单位特效/轨道炮炸裂.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 3.5
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.55
alwayStartDirAtZero: true
[effect_聚变gd]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 1.9
scaleTo: 1.9
alpha: 0.6
drawUnderUnits: true
atmospheric: false
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:30
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.2
scaleTo:1.5
alpha: 0.8
fadeInTime: 4
drawUnderUnits:false
[effect_碎星gd]
spawnChance: 1
createWhenZoomedOut: false
life: 35
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom:0.2
scaleTo:0.2
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 5
ySpeedRelativeRandom: 5
[effect_穿透]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
life: 35
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.1
alpha: 1
drawUnderUnits: false
ySpeedRelative: 8
atmospheric: true
[effect_闪光gd]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: true
atmospheric: false
#——++......
[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
drawUnderUnits: false

[effect_尾巴2]
priority: veryhigh
image: SHARED:light_50.png
life: 25
fadeOut: true
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1
drawUnderUnits: true
[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.1
maxTurnSpeed: 1.2

turnAcceleration: 0.1
moveSlidingMode : false
moveIgnoringBody: false


