


[core]
@memory nextTarget: unit
@global time1: 49.5
name: 激光中介a1
strictLevel: 1
price: 0

radius: 10
maxHp: 1
class: CustomUnitMetadata
techLevel: 1
showInEditor: false

showOnMinimap: false
tags: 激光炮塔
canNotBeDirectlyAttacked: true
isUnrepairableUnit: true
disableAllUnitCollisions: true

ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
maxTransportingUnits: 1
transportUnitsRequireTag: 激光
transportUnitsAddUnloadOption: false

exitHeightIgnoreParent: true
autoTriggerCooldownTime_allowDangerousHighCPU: true
autoTriggerCooldownTime: 0.005s


[graphics]
image: SHARED:blank.png
isVisible: false


[hiddenAction_创造]
autoTrigger: if transporting == nullUnit
addUnitsIntoTransport: 激光中介a2(maxSpawnLimit= 1, spawnChance= 0.5), 激光中介a2(maxSpawnLimit= 1, addResources= setFlag: 1)
# 自动生成中立敌对


[hiddenAction_a]
requireConditional: if memory.nextTarget != transporting and transporting != nullUnit
autoTrigger: if memory.nextTarget != transporting and not self.hasFlag(id= 0)
setUnitMemory: nextTarget = transporting


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 500

# 这个炮塔最好主体的最大范围多200
disablePassiveTargeting: true
turretTurnSpeed: 9999
shootDelay: 2
aimOffsetSpread: 0


[turret_2]
x: 0
y: 0
canShoot: false
limitingMinRange: 35
# limitingRange: 415

# idleDir:0


[turret_1]
x: 0
y: 0
# barrelY: 5
attachedTo: 2
projectile: 1

# turnSpeed: 4
shoot_flame: CUSTOM:光球
shoot_sound: NONE
shoot_sound_vol: 0.5
canShoot: true

shoot_light: #80FFBE67
resourceUsage: hasFlag= 0-1, ammo= -1
limitingMinRange: 35
canAttackLandUnits: if self.ammo < ${time1}
canOnlyAttackUnitsWithTags: 激光


[projectile_142857]
directDamage: 0
life: 1
deflectionPower: -1
invisible: true
instant: true

# instantReuseLast: true
unloadUpToXUnitsFromSource: 1
explodeEffect: NONE
explodeEffectOnShield: NONE


[projectile_1]
# 激光位置
directDamage: 0
life: -4
instantReuseLast: true
instant: true

laserEffect: true
lightColor: #FFFFBE67
lightSize: 0.5
explodeEffect: CUSTOM:闪光
# spawnUnit:爆炸LS*1

# 伤害改下面的炮弹3
beamImage: ROOT:/太空浪人/单位特效/光束3.png
mutator1_ifUnitWithTags: 激光
mutator1_addResourcesDirectHit: ammo= 1
spawnProjectilesOnCreate: 3


[projectile_3]
@copyFromSection: template_能源
areaDamage: 60
areaRadius: 60
# speed: 11
life: 1

# instant: false
instant: true
# invisible: true
largeHitEffect: false
# armourIgnoreAmount:40

explodeOnEndOfLife: true
deflectionPower: -1
areaRadiusFromEdge: true
# explodeEffect:NONE
explodeEffect: CUSTOM:弹坑*1

explodeEffectOnShield: NONE
lightColor: #FFFFBE67
lightSize: 3


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 240
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 0.65
scaleTo: 0.65
createWhenOverLiquid: false
createWhenOverLand: true


[effect_闪光]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.7

scaleTo: 0.7
image: ROOT:/太空浪人/单位特效/光束1.png
dirOffsetRandom: 180
alsoPlaySound: ROOT:/太空浪人/单位特效/激光.ogg


[effect_光球]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.4

scaleTo: 0.4
image: ROOT:/创世纪军事集团/单位特效/光球.png
color: #FFFF1200
xOffsetRelative: 1.25


[hiddenAction_0]
autoTrigger: if not parent.hasFlag(id= 0) and self.hasFlag(id= 0)
addResources: unsetFlag= 0-2
setResourcesWithLogic: ammo= 0
clearAllWaypoints: true
alsoTriggerAction: a

alsoTriggerOrQueueActionConditional: if memory.nextTarget != transporting and transporting != nullUnit


[hiddenAction_1]
autoTrigger: if parent.hasFlag(id= 0) and not self.hasFlag(id= 0) and transporting != nullUnit
addResources: setFlag= 0
resetCustomTimer: true
alsoTriggerAction: 2


[hiddenAction_2]
fireTurretXAtGround: 2
fireTurretXAtGround_withProjectile: 142857
fireTurretXAtGround_withTarget: parent.attacking.getAsMarker
alsoTriggerAction: 3


[hiddenAction_3]
autoTrigger: if parent.hasFlag(id= 0) and self.hasFlag(id= 0) and self.hasFlag(id= 1) and not self.hasActiveWaypoint(type= 'attack')
addWaypoint_type: attack
addWaypoint_target_fromReference: memory.nextTarget
# addWaypoint_maxTime: 2s
addResources: setFlag= 1


[hiddenAction_4]
autoTrigger: if parent.hasFlag(id= 0) and self.hasFlag(id= 0) and self.hasFlag(id= 1) and not self.hasFlag(id= 2) and self.ammo > ${time1} or parent.hasFlag(id= 0) and self.hasFlag(id= 0) and self.hasFlag(id= 1) and not self.hasFlag(id= 2) and self.customTimer > 3.9
addResources: setFlag= 2


[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 4
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


