


[core]
name: 路西法
displayText: «Люцифер»
strictLevel: 1
displayDescription: -В эпоху Воюющих государств Древних Людей «Люцифер» был многоцелевым штурмовиком, выпускавшимся промышленной группой Коста.\n-Его конструкция была разработана для отсталых стран без дополнительного бюджета на развитие флота.\n-«Люцифер» — это мощный штурмовик, оснащённый новаторской системой трансформации,\n-которая позволяет ему погружаться под воду для боя, до некоторой степени заменяя флот.\n-В то время «Люцифер» был одним из самых популярных вооружений в галактике; почти все страны, противостоявшие Альфриду, имели «Люциферов».\n-По сей день «Люцифер» служит в армии Скитальцев и внёс выдающийся вклад в борьбу с Заревом.\n-Атакует только землю, в воздухе — энергетический урон, в подводном режиме — кинетический урон.
price: 2900
radius: 28

maxHp: 2650
buildSpeed: 15s
class: CustomUnitMetadata
techLevel: 1
displayRadius: 28

# showInEditor: false
tags: 飞机,寄生免疫,低空
softCollisionOnAll: 10
armour: 7
fogOfWarSightRange: 20

copyFrom: ROOT:/通用特效/单位防护.ini


[hiddenAction_创造]
autoTrigger: if attachment(slot= '1') == nullUnit
attachments_onlyOnSlots: 1
attachments_addNewUnits: 激光中介a1


[action_a]
convertTo: 路西法水下
displayType: action
price: 0
text: Режим подлодки
buildSpeed: 1s

clearAllWaypoints: true
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署
description: Сложить крылья и развернуть подводный двигатель, превращаясь из штурмовика в подлодку,\n-уничтожать подводных и надводных врагов специальными торпедами.
isVisible: if self.isOverwater()
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: Броня «Сегмента» 1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_爆散2]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: Детонационная боеголовка 2
isActive: false
isVisible: if self.globalTeamTags(includes='爆散2')


[attachment_1]
x: 0
y: 37
# 这里改镭射开火位置
onCreateSpawnUnitOf: 激光中介a1
# 激光炮塔

# lockRotation: false
prioritizeParentsMainTarget: true
resetRotationWhenNotAttacking: true
alwaysAllowedToAttackParentsMainTarget: true


[hiddenAction_trigger_Land1]
autoTrigger: if self.hasFlag(id= 0) and attachment.hasFlag(id= 2)
addResources: unsetFlag= 0


[graphics]
# isVisible: false
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE

imageScale: 0.8
image_shadow: SHADOW:影子.png
shadowOffsetX: 1
shadowOffsetY: 1
movementEffect: CUSTOM:火

movementEffectRate: 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 260

isFixedFiring: true


[turret_0]
x: 0
y: 0
invisible: true
canShoot: false


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-100
projectile: 13
delay: 120

attachedTo: 0
slave: true
size: 0
limitingRange: 280


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_2]
x: 0
y: 0
# canShoot: true
projectile: 1
attachedTo: 0

slave: true
delay: 6s
onShoot_freezeBodyMovementFor: 2.5s
limitingMinRange: 35
resourceUsage: setFlag= 0, hasMissingFlag= 0


[turret_1]
x: -16
y: 8
canShoot: false
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
attachedTo: 0
slave: true

canAttackFlyingUnits: false
size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true

canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1

recoilReturnTime: 105
delay: 120


[turret_9]
x: -20
y: 6
canShoot: false
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
canAttackFlyingUnits: false
attachedTo: 0

slave: true
size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true

canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1

recoilReturnTime: 105
delay: 120
warmup: 20


[turret_3]
x: -24
y: 4
canShoot: false
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

attachedTo: 0
slave: true
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200

canAttackFlyingUnits: false
warmup: 40
size: 15
turnSpeed: 0
canAttackLandUnits: true

canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6

recoilOutTime: 1
recoilReturnTime: 105
delay: 120


[turret_4]
x: 16
y: 8
attachedTo: 0
slave: true
canShoot: false

projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200

canAttackFlyingUnits: false
size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true

canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1

recoilReturnTime: 105
delay: 120


[turret_5]
x: 20
y: 6
canShoot: false
attachedTo: 0
slave: true

projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200

canAttackFlyingUnits: false
size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true

canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1

recoilReturnTime: 105
delay: 120
warmup: 20


[turret_6]
x: 24
y: 4
canShoot: false
attachedTo: 0
slave: true

projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200

canAttackFlyingUnits: false
warmup: 40
size: 15
turnSpeed: 0
canAttackLandUnits: true

canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6

recoilOutTime: 1
recoilReturnTime: 105
delay: 120


[projectile_1]
directDamage: 0
life: 1
deflectionPower: -1
invisible: true
explodeEffect: NONE

explodeEffectOnShield: NONE


[arm_1]
x: -40
y: 0
image_end: 左小.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_2]
x: 40
y: 0
image_end: 右小.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_3]
x: -21
y: -7
image_end: 引擎.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_4]
x: 21
y: -7
image_end: 引擎.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_5]
x: -10
y: -20
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_6]
x: 10
y: -20
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_7]
x: -30
y: -3
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_8]
x: 30
y: -3
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_9]
x: -20
y: 12
image_end: 左盖子.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_10]
x: 20
y: 12
image_end: 右盖子.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_11]
x: 0
y: 26
image_end: 头.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_12]
x: 0
y: 37
image_end: 炮.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_15]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -34


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}

arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm1_1s: {x:20, y:22, dir:90}
arm2_1s: {x:-20, y:22, dir:-90}

arm3_1s: {x:0, y:-10, dir:0}
arm4_1s: {x:0, y:-10, dir:0}
arm5_1s: {x:0, y:-3, dir:-90}
arm6_1s: {x:0, y:-3, dir:90}
arm7_1s: {x:-5, y:-8, dir:90}

arm8_1s: {x:5, y:-8, dir:-90}
arm9_1s: {x:0, y:-12, dir:0}
arm10_1s: {x:0, y:-12, dir:0}
arm11_1s: {x:0, y:11, dir:0}
arm12_1s: {x:0, y:-11, dir:0}


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: AIR
targetHeight: 70
targetHeightDrift: 2
moveSpeed: 1.8
moveAccelerationSpeed: 0.03

moveDecelerationSpeed: 0.06
maxTurnSpeed: 3.5
turnAcceleration: 1
slowDeathFall: true
moveSlidingMode : true

moveIgnoringBody: false
moveSlidingDir: 120


