


[core]
name: 路西法水下
displayText: 路西法
strictLevel: 1
displayDescription: -古人类战国时期，路西法是科斯塔工业集团推出的一款多用途攻击机，\n-其设计是基于那些没有额外经费支出给海军发展的落后国家。\n-路西法在作为一款强力的攻击机的同时，还配有新颖的变形系统，\n-使其可以变形潜入水下作战，在一定程度上可以当做海军使用，\n-在当时，路西法是星系间最抢手的军火之一，几乎所有反对亚尔佛里德的国家都拥有路西法。\n-直至今日，路西法依旧在太空浪人的军队中服役，并为打击余辉做出了卓越贡献。\n-只能对地，能源伤害，变形后只能反潜及攻击水面单位。
price: 2900
fogOfWarSightRange: 25
radius: 28
maxHp: 2650
buildSpeed: 15s
class: CustomUnitMetadata
techLevel: 1

displayRadius: 28
# showInEditor: false
tags: 潜艇,寄生免疫
softCollisionOnAll: 10
armour: 7
copyFrom: ROOT:/通用特效/单位防护.ini


[hiddenAction_创造]
autoTrigger: if attachment(slot= '1') == nullUnit
attachments_onlyOnSlots: 1
attachments_addNewUnits: 激光中介a1


[action_t1]
autoTrigger: if not self.isOverLiquid
isVisible: false
addResources: hp=-999999


[action_爆散2]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: 爆散弹头2
isActive: false
isVisible: if self.globalTeamTags(includes='爆散2')


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: 赛格门塔护甲1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_a]
isVisible: if self.lastConverted > 6
convertTo: 路西法
displayType: action
price: 0
text: 攻击机模式

buildSpeed: 1s
clearAllWaypoints: true
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署
description: 展开机翼并收起水下引擎，由潜艇变成攻击机，\n-使用毁灭性的死亡激光扫射地面敌人。
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[attachment_1]
x: 0
y: 37
# 这里改镭射开火位置
onCreateSpawnUnitOf: 激光中介a1
# 激光炮塔

# lockRotation: false
prioritizeParentsMainTarget: true
resetRotationWhenNotAttacking: true
alwaysAllowedToAttackParentsMainTarget: true


[hiddenAction_trigger_Land1]
autoTrigger: if self.hasFlag(id= 0) and attachment.hasFlag(id= 2)
addResources: unsetFlag= 0


[graphics]
# isVisible: false
total_frames: 1
image: 主体.png
image_wreak: 死亡1.png
image_turret: NONE

turretImageScale: 0.8
imageScale: 0.8
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false

maxAttackRange: 380
# isFixedFiring: true


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-100
projectile: 13
delay: 120

size: 0
#limitingRange:280


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_1]
x: -16
y: 8
canShoot: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
canAttackFlyingUnits: false
size: 15

turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181

image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1
recoilReturnTime: 105
delay: 120

altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')
canOnlyAttackUnitsWithoutTags:悬浮

[turret_2]
x: -20
y: 6
canShoot: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
canAttackFlyingUnits: false
size: 15

turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181

image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1
recoilReturnTime: 105
delay: 120

warmup: 20
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')
canOnlyAttackUnitsWithoutTags:悬浮

[turret_3]
x: -24
y: 4
canShoot: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
canAttackFlyingUnits: false
warmup: 40

size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false

canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1
recoilReturnTime: 105

delay: 120
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')
canOnlyAttackUnitsWithoutTags:悬浮

[turret_4]
x: 16
y: 8
canShoot: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
canAttackFlyingUnits: false
size: 15

turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181

image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1
recoilReturnTime: 105
delay: 120

altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')
canOnlyAttackUnitsWithoutTags:悬浮

[turret_5]
x: 20
y: 6
canShoot: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
canAttackFlyingUnits: false
size: 15

turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackMaxAngle: 181

image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1
recoilReturnTime: 105
delay: 120

warmup: 20
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')
canOnlyAttackUnitsWithoutTags:悬浮

[turret_6]
x: 24
y: 4
canShoot: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg

shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFFF1200
canAttackFlyingUnits: false
warmup: 40

size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false

canAttackMaxAngle: 181
image: 鱼雷.png
recoilOffset: -6
recoilOutTime: 1
recoilReturnTime: 105

delay: 120
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')
canOnlyAttackUnitsWithoutTags:悬浮

[projectile_1]
@copyFromSection: template_动能
areaDamage: 70
areaRadius: 30
areaRadiusFromEdge: true
life: 200

speed: 0.5
targetSpeed: 1
image: 鱼雷.png
trailEffect: false
lightColor: #FFFF1200

ballistic: true
drawSize: 0.88
deflectionPower: -1
ballistic_height: -8
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:水波1

explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:水波1
spawnProjectilesOnEndOfLife: 锁定
turnSpeed: 2


[projectile_锁定]
@copyFromSection: template_动能
areaDamage: 70
areaRadius: 30
life: 180
areaRadiusFromEdge: true

speed: 12
targetSpeed: 12
trailEffect: false
image: ROOT:/创世纪军事集团/单位特效/子弹.png
drawSize: 0.58

largeHitEffect: true
lightColor: #FFFF1200
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:水波1
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:水波1


[projectile_炮弹]
@copyFromSection: template_爆炸
areaDamage: 60
areaRadius: 30
areaRadiusFromEdge: true
life: 200

speed: 0.5
targetSpeed: 1
image: 鱼雷.png
trailEffect: false
lightColor: #FF68FF2E

ballistic: true
drawSize: 0.88
deflectionPower: -1
ballistic_height: -8
explodeEffect: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:水波1

explodeEffectOnShield: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:水波1
spawnProjectilesOnEndOfLife: m1
turnSpeed: 2
areaHitUnderwaterAlways: true
spawnProjectilesOnExplode: m2*2


[projectile_m1]
@copyFromSection: template_爆炸
areaDamage: 70
areaRadius: 30
life: 180
areaRadiusFromEdge: true

speed: 12
targetSpeed: 12
trailEffect: false
image: ROOT:/太空浪人/单位特效/光1.png
drawSize: 0.58

largeHitEffect: true
lightColor: #FF68FF2E
explodeEffect: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:水波1
explodeEffectOnShield: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:水波1
spawnProjectilesOnExplode: m2*2

areaHitUnderwaterAlways: true


[projectile_m2]
@copyFromSection: template_爆炸
areaDamage: 45
areaRadius: 45
life: 6661
image: ROOT:/太空浪人/单位特效/光束0.png

speed: 200
targetSpeed: 200
drawSize: 0
areaRadiusFromEdge: true
explodeEffect: CUSTOM:波雷爆炸b

targetGround: true
targetGroundSpread: 65
lightColor: #FF68FF2E
areaHitUnderwaterAlways: true


[arm_1]
x: -20
y: 22
image_end: 左小.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true
drawDirOffset: 90


[arm_2]
x: 20
y: 22
image_end: 右小.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true
drawDirOffset: -90


[arm_3]
x: -21
y: -17
image_end: 引擎.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true


[arm_4]
x: 21
y: -17
image_end: 引擎.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true


[arm_5]
x: -10
y: -23
image_end: 左.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true
drawDirOffset: -90


[arm_6]
x: 10
y: -23
image_end: 右.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true
drawDirOffset: 90


[arm_7]
x: -35
y: -11
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true
drawDirOffset: 90


[arm_8]
x: 35
y: -11
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: false

drawUnderAllUnits: false
lockMovement: true
drawDirOffset: -90


[arm_9]
x: -12
y: 0
image_end: 左盖子.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_10]
x: 12
y: 0
image_end: 右盖子.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_11]
x: 0
y: 37
image_end: 头.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_12]
x: 0
y: 26
image_end: 炮.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[arm_15]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true


[effect_爆炸]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1

scaleTo: 1
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}

arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm1_1s: {x:-20, y:-22, dir:-90}
arm2_1s: {x:20, y:-22, dir:90}

arm3_1s: {x:0, y:10, dir:0}
arm4_1s: {x:0, y:10, dir:0}
arm5_1s: {x:0, y:3, dir:90}
arm6_1s: {x:0, y:3, dir:-90}
arm7_1s: {x:5, y:8, dir:-90}

arm8_1s: {x:-5, y:8, dir:90}
arm9_1s: {x:0, y:12, dir:0}
arm10_1s: {x:0, y:12, dir:0}
arm11_1s: {x:0, y:-11, dir:0}
arm12_1s: {x:0, y:11, dir:0}

#———————————————————————


[effect_爆炸b]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.44
scaleTo: 0.44
image: ROOT:/太空浪人/单位特效/爆散.png
total_frames: 9

animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.5
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/太空浪人/单位特效/爆散.ogg


[effect_闪光b]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_波雷爆炸b]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.3
image: ROOT:/太空浪人/单位特效/波雷爆炸1.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 2


[effect_闪电b]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.6

drawUnderUnits: false
scaleFrom: 1.8
scaleTo: 2.3
color: #FF68FF2E


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: WATER
moveSpeed: 0.4
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.07
#moveSlidingMode :false

#moveIgnoringBody:false
#moveSlidingDir:  45
targetHeight: -8
targetHeightDrift: 0.3
maxTurnSpeed: 0.7

turnAcceleration: 0.1


