


[core]
name: 战斧和狮鹰1
displayText: Топор и Грифон1
class: CustomUnitMetadata
price: 0
maxHp: 10
armour: 999989
techLevel: 2
radius: 0
displayRadius: 0
armourMinDamageToKeep: 0
showInEditor:false
hideScorchMark: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
isUnselectable: true
isBio: false
canNotBeGivenOrdersByPlayer: true
showOnMinimap:false
energyMax: 1
energyRegen: -100
fogOfWarSightRange: 40
explodeOnDeath: false
isBuilding: true

[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_添1加]
autoTrigger: if self.isEnergyEmpty() and not self.tags(includes= '1号') and self.resource.1>0.5
temporarilyAddTags:1号
fireTurretXAtGround: 1
fireTurretXAtGround_withOffset: 0,0


[hiddenAction_添12加]
autoTrigger: if self.isEnergyEmpty() and not self.tags(includes= '2号') and self.resource.3>0.5
temporarilyAddTags:2号
fireTurretXAtGround: 3
fireTurretXAtGround_withOffset: 0,0
deleteSelf: true

[hiddenAction_添加]
autoTrigger: if self.resource.2>0.5
deleteSelf: true
fireTurretXAtGround: 2
fireTurretXAtGround_withOffset: 0,0

[hiddenAction_麻]
autoTrigger: if self.isEnergyEmpty()and (self.resource.1>0.5 or self.resource.2>0.5) and self.timeAlive(laterThanSeconds=8)
deleteSelf: true




[graphics]
total_frames: 1
image:ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 1
icon_zoomed_out_neverShow:true
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 150

aimOffsetSpread: 0
shootDelay: 1
turretMultiTargeting: true

[turret_1]
#战斧
x:0
y: 3000
invisible: true
projectile: 1
turnSpeed: 15

turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true


[turret_2]
#战斧
x:0
y: -3000
invisible: true
projectile: 2
turnSpeed: 15

turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true

[turret_3]
#战斧
x:0
y: 3000
invisible: true
projectile: 3
turnSpeed: 15

turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true

[projectile_1]
@copyFromSection: template_爆炸,template_战略武器
areaDamage:18000
areaRadius: 200
drawSize: 0.9
life: 9999
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
image:ROOT:/创世纪军事集团/单位特效/弹头.png
speed: 19
explodeEffect: CUSTOM:爆炸,CUSTOM:气浪,CUSTOM:冲击波2,CUSTOM:闪光z,CUSTOM:闪光x*2,CUSTOM:弹坑*1
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 0.07
trailEffect: CUSTOM:烟雾*3,CUSTOM:火焰,CUSTOM:闪光nk
tags:天上战略
explodeOnEndOfLife: true
largeHitEffect: true
[projectile_2]
@copyFromSection: template_爆炸
areaDamage:5000
areaRadius: 120
drawSize: 1
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
life: 9999
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
speed: 17
explodeEffect: CUSTOM:黑雾*2,CUSTOM:冲击波a1,CUSTOM:爆炸a1, CUSTOM:爆炸a,CUSTOM:闪光a,CUSTOM:弹坑a
explodeEffectOnShield:CUSTOM:黑雾*2,CUSTOM:冲击波a1,CUSTOM:爆炸a1, CUSTOM:爆炸a,CUSTOM:闪光a,CUSTOM:弹坑a
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 1.1
trailEffect: CUSTOM:烟雾xdd*3,CUSTOM:火焰xdd
tags:战术武器
explodeOnEndOfLife: true
speedSpread:4
largeHitEffect: true



[projectile_3]
@copyFromSection:template_战略武器
areaDamage:0
areaRadius: 0
drawSize: 0.9
life: 9999
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1.5
image:ROOT:/创世纪军事集团/单位特效/弹头.png
speed: 19
explodeEffect: CUSTOM:wyd*24
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 0.07
trailEffect: CUSTOM:烟雾*3,CUSTOM:火焰,CUSTOM:闪光nk
tags:天上战略
explodeOnEndOfLife: true
largeHitEffect: true
spawnProjectilesOnExplode: 4
[projectile_4]
@copyFromSection: template_爆炸
areaDamage: 6000
areaRadius: 300
explodeEffect: CUSTOM:超级冲击波*2,CUSTOM:实验*2,CUSTOM:闪,CUSTOM:冲击波h,CUSTOM:火星wy*10
areaDamageNoFalloff: true
areaRadiusFromEdge: true
life: 0
invisible: true
delayedStartTimer: 2.5s
speed: 0
turnSpeed: 0.0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.3
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 2
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.6
mutator7_areaDamageMultiplier: 0.6
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=30
spawnUnit:超大火坑
#——————————————😪(

#——————————温压弹
[effect_wyd]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 170
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 10
scaleTo: 15
alpha: 2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.31
xSpeedRelativeRandom: 0.31
xOffsetRelativeRandom:200
yOffsetRelativeRandom:200
delayedStartTimerRandom:15
atmospheric: true
#——————————————😪(
[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.7
scaleTo: 2.7
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true
createWhenZoomedOut: true
[effect_气浪]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 6
scaleTo: 10
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true
createWhenZoomedOut: true
[effect_闪光z]
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 18
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
createWhenZoomedOut: true
[effect_闪光x]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 8
scaleTo: 8
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
createWhenZoomedOut: true
[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
createWhenZoomedOut: true

[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 4.5
scaleTo: 7
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
createWhenZoomedOut: true
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: true
scaleFrom: 0.6
scaleTo: 1.8

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
createWhenZoomedOut: true

[effect_烟雾]
dirOffsetRandom: 180
stripIndex: effects
frameIndex: 0
life: 100
fadeOut: true
priority: critical
attachedToUnit: false
fadeInTime: 0.8
scaleTo: 3
scaleFrom: 2.5
alpha: 3
hSpeed: 1.5
drawUnderUnits: false
atmospheric: false
spawnChance: 1
hOffsetRandom: 0.9
xSpeedRelativeRandom: 2.5


[effect_火焰]
priority: critical
image: ROOT:/余辉军团/建筑特效/火光.png
life: 15
spawnChance: 0.4
fadeOut: true
attachedToUnit: true
fadeInTime: 0.8
scaleTo: 1
scaleFrom: 0.5
alpha: 0.5
hSpeed: 0.5
drawUnderUnits: false
atmospheric: false
xSpeedAbsoluteRandom: 0.8
alwayStartDirAtZero: true
xOffsetRelativeRandom:5
yOffsetRelativeRandom:3
[effect_闪光nk]
priority: low
image: SHARED:light_50.png
life: 20
spawnChance: 0.3
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 4
scaleTo: 0
drawUnderUnits: false
atmospheric: false
xOffsetRelativeRandom:8
yOffsetRelativeRandom:8

#——————————————😪(

[effect_烟雾xdd]
dirOffsetRandom: 180
stripIndex: effects
frameIndex: 0
life: 80
fadeOut: true
priority: low
attachedToUnit: false
fadeInTime: 0.8
scaleTo: 2.2
scaleFrom:1.8
alpha: 2
hSpeed: 1.5
drawUnderUnits: false
atmospheric: false
spawnChance: 1
hOffsetRandom: 0.9
xSpeedRelativeRandom: 1


[effect_火焰xdd]
priority: low
image: ROOT:/余辉军团/建筑特效/火光.png
life: 15
spawnChance: 0.4
fadeOut: true
attachedToUnit: true
fadeInTime: 0.8
scaleTo: 1
scaleFrom: 0.37
alpha: 0.37
hSpeed: 0.5
drawUnderUnits: false
atmospheric: false
xSpeedAbsoluteRandom: 0.6
alwayStartDirAtZero: true
xOffsetRelativeRandom:3
yOffsetRelativeRandom:1


[effect_弹坑a]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 360
attachedToUnit: false
drawUnderUnits: true
createWhenOffscreen: true
createWhenZoomedOut: true
scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true
[effect_爆炸a]
life: 100
createWhenOffscreen: true
createWhenZoomedOut: true
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.5
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/重型爆炸.wav
alwayStartDirAtZero: true
[effect_爆炸a1]
life: 100
createWhenOffscreen: true
createWhenZoomedOut: true
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 3
image: ROOT:/创世纪军事集团/单位特效/12.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.21
alwayStartDirAtZero: true
[effect_闪光a]
createWhenOffscreen: true
createWhenZoomedOut: true
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 8
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_冲击波a1]
life: 100
createWhenOffscreen: true
createWhenZoomedOut: true
priority: critical
attachedToUnit: false
scaleFrom: 0.55
scaleTo: 2.1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true

[effect_黑雾]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true

life: 260
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 2
scaleFrom: 0.3
scaleTo: 0.4
alpha: 1.5
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
#——————————————😪(


[effect_超级冲击波]
priority: critical
image: 超级.png
life: 110
fadeOut: true
attachedToUnit: false
scaleFrom: 1.4
scaleTo: 1.84
alpha: 4
drawUnderUnits: false
createWhenZoomedOut: true
createWhenOffscreen: true
atmospheric: false
showInFog: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/爆燃.wav
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:100
fadeOut: true
attachedToUnit: true
scaleFrom:6
priority: critical
scaleTo:10
alpha: 1
drawUnderUnits:false
createWhenZoomedOut: true
createWhenOffscreen: true
dirOffsetRandom:180
[effect_震动]
createWhenOffscreen:true
drawType: displacement
priority: critical
image:震动.png
life:120
fadeOut: false
fadeInTime:50
attachedToUnit: true
scaleFrom:50
scaleTo:50
alpha:0.035
drawUnderUnits:false
createWhenZoomedOut: true
alwayStartDirAtZero: true
total_frames: 2
animateFrameStart: 0
animateFrameEnd:1
animateFrameSpeed: 0.3
animateFrameLooping:true
[effect_闪]
priority: high
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 0.8
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 19
scaleTo: 1
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
[effect_冲击波h]
life: 40
priority: high
attachedToUnit: false
scaleFrom: 1
scaleTo: 6
image: ROOT:创世纪军事集团/单位特效/超级冲击波.png
alwayStartDirAtZero: true
drawUnderUnits: true
alpha:0.8
createWhenOffscreen: true
[movement]
movementType: AIR
moveSpeed: 1.8
maxTurnSpeed: 1
targetHeight: -1
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true
[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 220
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 5
scaleTo: 6
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.75
xSpeedRelativeRandom: 0.75
atmospheric: true
xOffsetRelativeRandom:280
yOffsetRelativeRandom:280
[resource_1]
displayName: 1
displayNameShort: 1
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_2]
displayName: 2
displayNameShort: 2
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_3]
displayName: 3
displayNameShort: 3
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_撞击]
displayName: 撞击
displayNameShort: 撞击
displayColor: #FF9D00FF
priority: 1
hidden: true
