


[core]
name: 狩猎者导弹
displayText: 狩猎者
price: 3300
maxHp: 5300
displayDescription: 【阶级t4】【可翻越悬崖】【生物单位】【地面单位】战术定位:先进泛用型步兵，单位体积:5\n-武器配置：▲自动突击炮X1 只能对地 动能伤害 \n-▲火箭发射仓x1 只能对地 爆炸伤害 对建筑物伤害加成\n-一种以地狱猎犬结构为基础，进行再设计的中型主战机甲。\n-创世纪每次将与余辉作战的前线装甲兵团撤回时，都会从中挑选最优秀的驾驶员，\n-让这些既老道又疯狂的战争精英来驾驶创世纪的主战机甲——狩猎者。\n-相比于坦克而言，主战机甲在复杂地形中要更加灵活有效，\n-创世纪每个集团军中，都会配备由狩猎者和其他机甲组成的机甲营，\n-他们专门负责猎杀余辉的各种主力机甲和地面上的庞然大物。
isUnrepairableUnit:true
techLevel: 1
buildSpeed: 24s
radius: 33
displayRadius: 33
armour: 20
fogOfWarSightRange:20
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md,ROOT:/通用特效/扎针.md
transportSlotsNeeded: 5
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,狩猎者,机甲,步兵,驻扎要塞
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 狩猎者
energyMax: 4

energyRegen: 0.035
energyNeedsToRechargeToFull: true
showInEditor: false
[action_man1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: 恐怖地雷1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3') 

#———科技—————
[action_重型掩体]
text: 重型掩体
isVisible: if self.globalTeamTags(includes='外骨骼')
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。
[action_加掩体]
autoTrigger: if self.globalTeamTags(includes='外骨骼')and not self.tags(includes= '重型掩体') and not self.hasParent
isVisible:false
temporarilyAddTags:重型掩体

[hiddenAction_减掩体]
autoTrigger:if self.hasParent and self.tags(includes= '重型掩体')
isVisible:false
temporarilyRemoveTags:重型掩体


[action_x]
displayType: action
price: 0
buildSpeed: 2.4s
isLocked: if self.queueSize > 0.5 or self.isAttacking() or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.tags(includes= '冲锋')
text: 切换为自动炮

description: 切换武器，使用四十五毫米突击炮，\n-对单个敌人持续进行动能伤害的点射。\n-切换枪械或与敌人交火时将禁用切换枪械功能。
highPriorityQueue: true
canPlayerCancel: false
whenBuilding_playAnimation: 部署1
convertTo: 狩猎者1
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed,armour
convertTo_keepCurrentTags:true
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 435 | setFlag= 0)
# onCreateSpawnUnitOf: 检测中介a(addResources= ammo: 600 | setFlag= 0-1)
# 对地对空

# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true

[action_电磁炮3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道3.png
text: 轨道发射器3
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器3')
[action_弹幕架2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕2.png
text: 弹幕架2
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架2')

[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 435 | setFlag= 0)


[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5)
isVisible: false
alsoQueueAction: b


[action_b]
convertTo: 狩猎者导弹1
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
convertTo_keepCurrentTags:true
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed,armour





[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7

shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
imageScale: 0.85


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 335
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: false

turretMultiTargeting: true


[turret_2]
x: 24
y: 56
attachedTo: 1
invisible: true
projectile: 1

shoot_sound: NONE
canShoot: true
size: 36
delay: 8
energyUsage: 0

slave: true
canAttackFlyingUnits: false

[turret_1]
x: 0
y: 0
canShoot: false
#image:身体.png
invisible: true
canAttackFlyingUnits: false

[arm_1]
x: 5
y: 30
image_end: 炮.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: -60


[arm_2]
x: 12
y: -18
image_end: 枪.png
image_end_teamColors: true
drawOverBody: false
hidden:if self.globalTeamTags(includes='轨道发射器3')
drawDirOffset: 45
[arm_3]
x: 12
y: -18
image_end: 电磁炮.png
image_end_teamColors: true
drawOverBody: false
hidden:if not self.globalTeamTags(includes='轨道发射器3')
drawDirOffset: 45

[arm_4]
x: -23
y: 20
image_end: 左手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 35
image_end_shadow: SHADOW:左手.png


[arm_5]
x: 25
y: 11
image_end: 右手.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: -55
image_end_shadow: SHADOW:右手.png


[arm_6]
x: -15
y: -3
image_end: 胳膊.png
image_end_teamColors: true
drawDirOffset: -30

drawOverBody: false
image_end_shadow: SHADOW:胳膊.png


[arm_7]
x: 15
y: -5
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 35
image_end_shadow: SHADOW:胳膊.png


[arm_8]
#左肩
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true

drawOverBody: true
#image_end_shadow:SHADOW:损坏.png
hidden: if self.hp(greaterThan=1800)


[arm_9]
#左肩
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true

hidden: if self.hp(lessThan=1800)
drawOverBody: true
image_end_shadow: SHADOW:主体.png


[leg_1]
x: -14
y: 4
attach_x: -1
attach_y: 0
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 14
y: 4
attach_x: 1
attach_y: 0
copyFrom: 1

drawDirOffset: 10


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}

arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm1_0.6s: {x:5, y:-3, dir:60}
arm4_0.6s: {x:15, y:10, dir:10}

arm5_0.6s: {x:0, y:-3, dir:10}
arm6_0.6s: {x:0, y:10, dir:40}
arm7_0.6s: {x:0, y:-6, dir:0}
arm8_0.6s: {x:0, y:0, dir:10}
arm9_0.6s: {x:0, y:0, dir:10}


[animation_部署1]
#onActions: attack
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm1_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}

arm2_0.6s: {x:-2, y:0, dir:-45}
arm3_0.6s: {x:-2, y:0, dir:-45}
arm1_0.6s: {x:5, y:-3, dir:60}
arm4_0.6s: {x:15, y:10, dir:10}
arm5_0.6s: {x:0, y:-3, dir:10}
arm6_0.6s: {x:0, y:10, dir:40}
arm7_0.6s: {x:0, y:-6, dir:0}
arm8_0.6s: {x:0, y:0, dir:10}
arm9_0.6s: {x:0, y:0, dir:10}

arm4_1.2s: {x:15, y:10, dir:50}
arm1_1.2s: {x:7, y:-48, dir:60}

arm2_1.8s: {x:-2, y:0, dir:-45}
arm3_1.8s: {x:-2, y:0, dir:-45}
arm4_1.8s: {x:15, y:10, dir:80}
arm1_1.8s: {x:7, y:-48, dir:60}

arm1_2.4s: {x:7, y:-48, dir:105}
arm2_2.4s: {x:-2, y:45, dir:-45}
arm3_2.4s: {x:-2, y:45, dir:-45}
arm4_2.4s: {x:15, y:10, dir:10}


[movement]
movementType: OVER_CLIFF
moveSpeed: 1
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 2

turnAcceleration: 0.08
targetHeight: 4
moveSlidingMode : false
moveIgnoringBody: false
reverseSpeedPercentage: 0

slowDeathFall: true


