


[core]
name: 复仇女神装饰导弹层
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
energyMax: 4
energyRegen: 0.033
energyNeedsToRechargeToFull: true
tags:反高空,航母hf,免疫烟雾
maxTransportingUnits: 6
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 直升机hf
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]
canRepairBuildings: true
autoRepair: true
canRepairUnits: true
nanoRepairSpeed: 4.5
nanoRange: 650
[decal_吊车]
image: 吊车影.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 12
alpha:0.65
imageScale:0.85
[decal_车]
image: 雷.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:-148
xOffsetRelative:-20
onlyWhileAlive:true
imageScale:0.9
[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 6
alsoQueueAction: SDD
[hiddenAction_SDD]
buildSpeed: 2s
requireConditional: if memory.灰机 < 6
addUnitsIntoTransport: 海蜂武装直升机
[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2
[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource

[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1

[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)

[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 2500 | setFlag= 0-1)
# 对地对空
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false
[attachment_drone1]
x: -50
y: 10
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false
addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
idleDir: -45
height: 1
[attachment_drone2]
@copyFromSection: attachment_drone1
x: -50
y: 10
[attachment_drone3]
@copyFromSection: attachment_drone1
x: -50
y: 10

[attachment_drone6]
@copyFromSection: attachment_drone1
x: 50
y: 10
idleDir: 45
[attachment_drone7]
@copyFromSection: attachment_drone1
x: 50
y: 10
idleDir: 45
[attachment_drone8]
@copyFromSection: attachment_drone1
x: 50
y: 10
idleDir: 45

[decal_左导弹井]
image: 左.png
total_frames: 1
layer: afterBody
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
yOffsetRelative:125.5
xOffsetRelative:-84
onlyWhileAlive:true

[decal_右导弹井]
image: 右.png
total_frames: 1
layer: afterBody
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
yOffsetRelative:125.5
xOffsetRelative:84
onlyWhileAlive:true
[decal_左开启]
image: 左导弹开启.png
total_frames: 6
frame: select(self.tags(includes= '切枪'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer: afterBody
yOffsetRelative:125.5
xOffsetRelative:-84
[decal_右开启]
image: 右导弹开启.png
total_frames: 6
frame: select(self.tags(includes= '切枪'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer: afterBody
yOffsetRelative:125.5
xOffsetRelative:84

[decal_左关闭]
image: 左导弹关闭.png
total_frames: 6
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: afterBody
yOffsetRelative:125.5
xOffsetRelative:-84
[decal_右关闭]
image: 右导弹关闭.png
total_frames: 6
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 12) % 6, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: afterBody
yOffsetRelative:125.5
xOffsetRelative:84

[hiddenAction_akm]
autoTrigger: if not self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") == null
addResources: setFlag=1
alsoQueueAction:zx
temporarilyAddTags: 切枪
temporarilyRemoveTags:关闭
resetCustomTimer: true
[hiddenAction_bkm]
autoTrigger: if self.hasFlag(id= 1) and self.attachment(withTag= "ANM_cat") != null
addResources: unsetFlag=1
alsoQueueAction:zxx
temporarilyAddTags: 切枪x,关闭
resetCustomTimer: true
[action_zx]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪
[action_zxx]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪x
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
#turretImageScale: 0.9
repairEffect: CUSTOM:尾, CUSTOM:尾1
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 2000
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0
turretMultiTargeting: true
[turret_1]
x: 84
y: 108
invisible: true
shoot_sound: ROOT:/通用特效/新导弹发射.wav
shoot_sound_vol: 1.2
#shoot_flame: CUSTOM:烟雾*6,CUSTOM:冲击波
shoot_light: #FFEECCCC
projectile: 1
size: 0
turnSpeed: 811
delay: 400
canOnlyAttackUnitsWithTags:极端重型
limitingMinRange: 450
canAttackCondition: if not self.tags(includes= '切枪') and not self.tags(includes= '关闭')
[turret_2]
x: 84
y:115
copyFrom: 1
warmup:20
delay:380
[turret_3]
x: 84
y:125
copyFrom: 1
warmup:40
delay:360
[turret_4]
x: 84
y:135
copyFrom: 1
warmup:60
delay:340
[turret_5]
x: 84
y:145
copyFrom: 1
warmup:80
delay:320
#——————
[turret_6]
x: -84
y:108
copyFrom: 1
delay:400
[turret_7]
x: -84
y:115
copyFrom: 1
warmup:20
delay:380
[turret_8]
x: -84
y:125
copyFrom: 1
warmup:40
delay:360
[turret_9]
x: -84
y:135
copyFrom: 1
warmup:60
delay:340
[turret_10]
x: -84
y:145
copyFrom: 1
warmup:80
delay:320
[turret_11]
x: 0
y: 59
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 反导
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:20
interceptProjectiles_withTags:战术武器
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -10
invisible: true
shoot_flame: CUSTOM:烟雾at*6,CUSTOM:冲击波at,CUSTOM:闪光at
onShoot_playAnimation: 舱盖
resourceUsage:复仇女神零件=5

[turret_11x]
x: 0
y: 59
copyFrom: 11
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战术防御天上



[turret_66]
x: 0
y: 59
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 反导
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:20
interceptProjectiles_withTags:导弹2
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -10
invisible: true
shoot_flame: CUSTOM:烟雾at*6,CUSTOM:冲击波at,CUSTOM:闪光at
onShoot_playAnimation: 舱盖
resourceUsage:复仇女神零件=20


[turret_66x]
x: 0
y: 59
copyFrom: 66
interceptProjectiles_withTags: 天上战略
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战略防御天上

[turret_233]
x: -50
y: -10
projectile: 233
delay: 1s
canAttackMaxAngle: 181
warmup:0.5s
invisible: true
canAttackFlyingUnits:false
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
unloadUpToXUnitsAndGiveAttackOrder: 1
limitingRange: 1550
[turret_234]
x: 50
y:10
copyFrom: 233
warmup:1s
delay:0.5s
[turret_12]
x: 17
y: -145
warmup: 0
size: 35
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true
image: 吊车.png
idleDir: 135
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[projectile_1]
life: 45
speed: 3.5
targetSpeed: -1
largeHitEffect: true
drawSize: 0.9
image: 导弹1.png
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 90
spawnProjectilesOnEndOfLife: 2
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片d,CUSTOM:冲击波dd,CUSTOM:烟雾d*4,CUSTOM:闪光d
trailEffect: true
trailEffectRate: 1.2
deflectionPower: -1
drawUnderUnits:false
autoTargetingOnDeadTarget: true
[projectile_2]
turnSpeed: 7
wobbleAmplitude: 2
wobbleFrequency: 100
directDamage: 2000
life: 1000
nukeWeapon: false
speed: 3
image:导弹.png
targetSpeed: 12
drawSize:0.9
lightSize: 0.9
lightColor: #FFFFFF73
trailEffect: true
trailEffectRate: 0.7
areaRadiusFromEdge: true
targetGround: false
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 90
drawUnderUnits:false
deflectionPower: -1
autoTargetingOnDeadTarget: true
explodeEffect: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
explodeEffectOnShield: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
speedSpread: 1.25
[projectile_反导]
areaDamage: 0
areaRadius: 0
life: 120
speed: 40
targetSpeed: 40
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 1
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:钢珠fd,CUSTOM:爆炸fd, CUSTOM:闪光at
explodeEffectOnShield: CUSTOM:钢珠fd,CUSTOM:爆炸fd, CUSTOM:闪光at
trailEffectRate: 0.8
#——————————反导
#——————————反导

[effect_闪光at]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false

[effect_烟雾at]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 2
scaleTo: 2.4
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波at]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 3
alpha: 1
[effect_爆炸fd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.6

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
alwayStartDirAtZero: true


[effect_钢珠fd]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1.8
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
#——————————导弹发射
[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1
attachedToUnit: false
#——————————导弹
[effect_冲击波dd]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
attachedToUnit: false
alpha: 1
[effect_烟雾d]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.6
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_导弹碎片d]
#priority: low
image: 导弹壳.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.85
scaleTo: 0.85
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 50

[effect_闪光d]
image: SHARED:light_50.png
life:30
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FFFF5B18
fadeInTime: 2
scaleFrom: 5.5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
#——————————————————炸
[effect_爆炸hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.44
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/重型爆炸.wav
alwayStartDirAtZero: true
[effect_爆炸hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/12.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.21
alwayStartDirAtZero: true
[effect_闪光hx]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 12
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
#——————————修复
[effect_尾1]
image: SHARED:light_50.png
life: 60
fadeOut: true
attachedToUnit: false
priority: low
ySpeedRelativeRandom: 0.5
ySpeedRelative: 1.5
color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true
[effect_尾]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 200
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
#ySpeedRelativeRandom: 0.5
drawUnderUnits: false
ySpeedRelative: 3
yOffsetRelative	: 10
[arm_1]
x: 0
y: 60
image_end: 井.png
image_end_teamColors: true
[arm_2]
x: 0
y: 67
image_end: 上.png
image_end_teamColors: true
[arm_3]
x: 0
y: 52
image_end: 下.png
image_end_teamColors: true
[arm_4]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true
[arm_5]
x: 0
y: -181
image_end: 核心.png
image_end_teamColors: true
#drawUnderAllUnits: true
spinRate:-0.9
drawOverBody: true
[arm_6]
x: 0
y: -181
image_end: 核心罩.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawOverBody: true
[arm_7]
x: -20
y: -150
image_end: ROOT:/创世纪军事集团/单位特效/雷达.png
drawOverBody: true
spinRate: 8
[arm_8]
x: 0
y: 5
image_end: 雷达.png
drawOverBody: true
spinRate: 4
[animation_舱盖]
arm2_0.5s: {x:0, y:20}
arm3_0.5s: {x:0, y:-25}
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


