


[core]
name: 晨曦之星机库
displayText: Ангар «Утренняя звезда»
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
showInEditor: false
canNotBeDirectlyAttacked: true
disableDeathOnZeroHp: true
isUnrepairableUnit: true

isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
ignoreInUnitCapCalculation: true
maxTransportingUnits: 4

transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 晨曦
transportUnitsHealBy: 4
transportUnitsRequireMovementType: air
tags:反高空,免疫烟雾
transportUnitsKeepBuiltUnits: true
@memory 灰机: number

[graphics]
image: NO.png
#isVisible: false
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attachment_drone1]
x: 0
y: 125
isVisible:true
addTransportedUnits: true
canAttack: false
setDrawLayerOnBottom:false
lockRotation:true
idleDir: 45
[attachment_drone2]
@copyFromSection: attachment_drone1
x:0
y: 165
[attachment_drone3]
@copyFromSection: attachment_drone1
x: 0
y: 205
[attachment_drone4]
@copyFromSection: attachment_drone1
x: 0
y: 245
[hiddenAction_0]
autoTrigger: if not self.hasParent
deleteSelf: true


[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 4
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 4
addUnitsIntoTransport: 晨曦之星轰炸机


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
setUnitMemory: 灰机 = memory.灰机 + 1


[hiddenAction_set1]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
setUnitMemory: 灰机 = memory.灰机 - 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 3500

[turret_233]
x: 0
y: 100
projectile: 233
delay: 0s
canAttackMaxAngle: 181
warmup:2.8s
invisible: true
canAttackFlyingUnits: if self.isInMap
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
unloadUpToXUnitsAndGiveAttackOrder: 1
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[arm_1]
x: 0
y: 123
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_2]
x: 0
y: 142
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_3]
x: 0
y: 161
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_4]
x: 0
y: 180
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_5]
x: 0
y: 199
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_6]
x: 0
y: 218
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_7]
x: 0
y: 237
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_8]
x: 0
y: 256
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true
[arm_9]
x: 0
y: 275
image_end: 甲板灯1.png
image_end_teamColors: true
drawOverBody: true

[animation_1]
onActions: idle
arm9_0s: {alpha:0}
arm9_0.1s: {alpha:1.2}
arm9_0.2s: {alpha:0}
arm9_1.8s: {alpha:0}

arm8_0s: {alpha:0}
arm8_0.3s: {alpha:1.2}
arm8_0.4s: {alpha:0}
arm8_1.8s: {alpha:0}

arm7_0s: {alpha:0}
arm7_0.5s: {alpha:1.2}
arm7_0.6s: {alpha:0}
arm7_1.8s: {alpha:0}

arm6_0s: {alpha:0}
arm6_0.7s: {alpha:1.2}
arm6_0.8s: {alpha:0}
arm6_1.8s: {alpha:0}

arm5_0s: {alpha:0}
arm5_0.9s: {alpha:1.2}
arm5_1s: {alpha:0}
arm5_1.8s: {alpha:0}

arm4_0s: {alpha:0}
arm4_1.1s: {alpha:1.2}
arm4_1.2s: {alpha:0}
arm4_1.8s: {alpha:0}

arm3_0s: {alpha:0}
arm3_1.3s: {alpha:1.2}
arm3_1.4s: {alpha:0}
arm3_1.8s: {alpha:0}

arm2_0s: {alpha:0}
arm2_1.5s: {alpha:1.2}
arm2_1.6s: {alpha:0}
arm2_1.8s: {alpha:0}

arm1_0s: {alpha:0}
arm1_1.7s: {alpha:1.2}
arm1_1.8s: {alpha:0}
[movement]
movementType: AIR
maxTurnSpeed: 9999
turnAcceleration: 9999
