


[core]
name: 雷烬天使机库
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
showInEditor: false
canNotBeDirectlyAttacked: true
disableDeathOnZeroHp: true
isUnrepairableUnit: true

isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
ignoreInUnitCapCalculation: true
maxTransportingUnits: 8

transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 雷烬天使
transportUnitsHealBy: 8
transportUnitsRequireMovementType: air
tags:反高空,免疫烟雾
transportUnitsKeepBuiltUnits: true
@memory 灰机: number

[graphics]
image: NO.png
#isVisible: false
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false

[attachment_drone1]
x: 75
y: -135
isVisible:false
addTransportedUnits: true
canAttack: false
setDrawLayerOnBottom:false
lockRotation:true
[attachment_drone2]
@copyFromSection: attachment_drone1
x: 75
y: -135
[attachment_drone0]
@copyFromSection: attachment_drone1
x: 75
y: -135

[attachment_drone3]
@copyFromSection: attachment_drone1
x: 75
y: -135





[attachment_drone4]
@copyFromSection: attachment_drone1
x: -75
y: -125
[attachment_drone5]
@copyFromSection: attachment_drone1
x: -75
y: -125
[attachment_drone7]
@copyFromSection: attachment_drone1
x: -75
y: -125
[attachment_drone8]
@copyFromSection: attachment_drone1
x: -75
y: -125
[hiddenAction_0]
autoTrigger: if not self.hasParent
deleteSelf: true


[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 8
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 8
addUnitsIntoTransport: 雷烬天使战斗机


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
setUnitMemory: 灰机 = memory.灰机 + 1


[hiddenAction_set1]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
setUnitMemory: 灰机 = memory.灰机 - 1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 3500


[turret_233]
x: 75
y: -135
projectile: 233
delay: 0s
canAttackMaxAngle: 181
warmup:3s
invisible: true
canAttackFlyingUnits: if self.isInMap
canAttackLandUnits: false
canAttackUnderwaterUnits: false
unloadUpToXUnitsAndGiveAttackOrder: 1
[turret_234]
x: -75
y:-135
copyFrom: 233
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true

[movement]
movementType: AIR
maxTurnSpeed: 9999
turnAcceleration: 9999

