


[core]
name: 太空浪人枢纽t3
class: CustomUnitMetadata
price: 18000
maxHp: 30000
tags: 太空浪人枢纽t3,太空浪人枢纽t2,地面,核,聚变堆,灰影建筑,建筑

selfRegenRate: 0.2
techLevel: 1
buildSpeed: 3s
isBio: false
isBuilding: true

numBitsOnDeath: 14
footprint: -3,0,3,5
constructionFootprint: -3,0,3,5
radius: 35
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 21
unitsSpawnedOnDeath: 太空浪人枢纽t3残骸*1
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
generation_delay: 40
generation_credits: 50
canRepairBuildings: false

canRepairUnits: false
canReclaimResources: false
nanoRange: 3500000
nanoBuildSpeed: 1
armour: 30
energyMax: 12
energyRegen: 0.0015
energyNeedsToRechargeToFull: false

[action_T1]
pos: 0
buildSpeed: 0s
addResources: setFlag=0,setFlag=1
isVisible: if not self.hasFlag(id=1) and not self.hasFlag(id=0)
text: 显示传送和供能范围


[action_T1_back]
pos: 0
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=1
isVisible: if self.hasFlag(id=1)
text: 不显示传送和供能范围


[canBuild_1]
name: 工蚁传送
pos: 1
forceNano: true
isLocked: if numberOfUnitsInTeam(withTag='农民',withinRange=800,greaterThan=7) and self.isControlledByAI()


[canBuild_2]
name: 星辰传送
pos: 1
forceNano: true

[action_雷达]
text: 雷达扫描
allowMultipleInQueue: false
description: -命令太空舰队对地面进行扫描，\n-将对目标区域获取5.5秒的有效视野。
iconImage: ROOT:/通用特效/雷达.png
price: energy=6
fireTurretXAtGround: 雷达
highPriorityQueue: true
isVisible: true
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
pos:0.1
buildSpeed: 0s
ai_isHighPriority: false
[graphics]
total_frames: 1
image: 底座.png
image_wreak: 死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

shadowOffsetX: 3
shadowOffsetY: 3





[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 999999

turretSize: 0
turretTurnSpeed: 50


[turret_光圈]
x: 0
y: 0
canShoot: false
invisible: if self.isControlledByAI()or not self.hasFlag(id=1)
size: 1

image: ROOT:/太空浪人/建筑特效/光圈.png


[turret_光圈2]
x: 0
y: 0
canShoot: false
invisible: if self.isControlledByAI()or not self.hasFlag(id=1)
size: 1

image: ROOT:/太空浪人/建筑特效/光圈2.png


[turret_nanoTurret]
x: 0
y: 0
turnSpeed: 40
size: 0
canShoot: false

isMainNanoTurret: true

[turret_雷达]
x: 0
y: 0
projectile: 雷达
#limitingRange: 99999
#limitingMinRange:300

canAttack: false
invisible: true
shoot_sound: ROOT:/通用特效/扫描.ogg
shoot_sound_vol: 1
[projectile_雷达]
life: 1
speed: 0
deflectionPower: -1
directDamage: 0
invisible: true

instant: true
spawnUnit: 雷达(offsetDir=180)
explodeEffect: none
explodeEffectOnShield: none
[effect_烟雾]
image: ROOT:/太空浪人/建筑特效/倒塌特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/太空浪人/建筑特效/倒塌特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[arm_1]
x: 0
y: -2
image_end: 闪烁.png
image_end_teamColors: true
drawOverBody: true


[arm_2]
x: 0
y: 44
image_end_teamColors: false
image_end: 球.png
drawOverBody: true


[arm_3]
x: 60
y: 45
image_end_teamColors: false
image_end: 小球.png
drawOverBody: true


[arm_4]
x: -53
y: 25
image_end_teamColors: false
image_end: 小球.png
drawOverBody: true


[arm_5]
x: 7
y: -5
image_end_teamColors: false
image_end: 小球.png
drawOverBody: true


[animation_1]
onActions: idle
arm2_0s: {x:0,y:0}
arm2_1s: {x:0,y:2}
arm2_2s: {x:0,y:5}
arm2_3s: {x:0,y:6}

arm2_4s: {x:0,y:10}
arm2_5s: {x:0,y:5}
arm2_6s: {x:0,y:0}
arm5_0s: {x:0,y:0}
arm5_1s: {x:0,y:1}

arm5_2s: {x:0,y:3}
arm5_3s: {x:0,y:5}
arm5_4s: {x:0,y:8}
arm5_5s: {x:0,y:5}
arm5_6s: {x:0,y:0}

arm3_0s: {x:0,y:0}
arm3_1s: {x:0,y:1}
arm3_2s: {x:0,y:3}
arm3_3s: {x:0,y:5}
arm3_4s: {x:0,y:8}

arm3_5s: {x:0,y:5}
arm3_6s: {x:0,y:0}
arm4_0s: {x:0,y:0}
arm4_1s: {x:0,y:1}
arm4_2s: {x:0,y:3}

arm4_3s: {x:0,y:5}
arm4_4s: {x:0,y:8}
arm4_5s: {x:0,y:5}
arm4_6s: {x:0,y:0}
arm1_0s: {alpha:0.0}

arm1_3s: {alpha:0.9}
arm1_6s: {alpha:0.1}


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsBuilder: true
buildPriority: 0.05
ai_upgradePriority: 0.07
maxEachBase: 100
maxGlobal: 500


