


[core]
name: 收割者无人机
displayText: Дрон «Жнец»
displayDescription: 【Уровень t3】【Механический юнит】【Воздушный юнит】【Беспилотный юнит】\n-Тактическое назначение:反生物дрон，вооружение：▲GAU-11машина炮X1 по земле и воздуху кинетический урон пробивает укрытия。\n-Дрон «Жнец»是Генезис专 используется чтобы对付反叛者的оружие，\n-这виддрон被大масштабоснащение于Генезис警卫团，\n-Дрон «Жнец»оснащение对персонал极为эффективныйGAU11машина炮，\n-может用凶猛的огневая мощь撕碎地面和空中的轻 бронетехника。\n-在紧张时期，这видоружиетакже被используется чтобы对付余辉。
price: 500
maxHp: 700
armour: 2
techLevel: 1
buildSpeed: 2s
radius: 14
copyFrom: ROOT:/通用特效/单位防护.ini

displayRadius: 14
isBio: false
tags: 飞机,低空,无人单位

[action_电磁炮1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道1.png
text: 轨道пусковая установка1
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器1')



[graphics]
total_frames: 2
image: 收割者无人机机身.png
image_wreak: 收割者无人机死亡.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 1
animation_moving_start: 0

animation_moving_end: 1
animation_moving_speed: 1
animation_attack_start: 0
animation_attack_end: 1
animation_attack_speed: 1

imageScale: 0.8


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
disablePassiveTargeting: false

turretMultiTargeting: true
turretSize: 23
turretTurnSpeed: 4
isFixedFiring: true
maxAttackRange: 225


[turret_2]
x: 0
y: 0
invisible: true
projectile: 2
delay: 5

canShoot: false


[turret_3]
x: 0
y: 0
attachedTo: 2
invisible: true
slave: true

turnSpeed: 2.9
turnSpeedAcceleration: 0.3
projectile: 2
shoot_sound: ROOT:/创世纪军事集团/步兵特效/重机枪射击.ogg
shoot_sound_vol: 0.2

shoot_flame: CUSTOM:枪口火焰,CUSTOM:弹壳
shoot_light: #FFFFEB88
canShoot: true
delay: 5
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='轨道发射器1')

[projectile_炮弹]
@copyFromSection: template_动能
directDamage: 20
life: 60
speed: 10
frame: 8

drawSize: 0.7
explodeEffect: CUSTOM:穿透,CUSTOM:大火花
deflectionPower: -1
armourIgnoreAmount: 10
mutator2_ifUnitWithTags: 步兵
mutator2_directDamageMultiplier: 2
shieldDamageMultiplier: 1.2
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1




[projectile_2]
@copyFromSection: template_动能
directDamage: 17
life: 60
speed: 9
targetSpeed: 9
armourIgnoreAmount: 2
deflectionPower: -1
frame: 8
drawSize: 0.75
color: #FFFFFF73
explodeEffect: CUSTOM:火花
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1



[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
scaleFrom: 2

scaleTo: 2
animateFrameStart: 0
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.6
image: ROOT:/通用特效/火花.png
alpha: 1.2

total_frames: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_穿透]
priority: high
frameIndex: 4
stripIndex: projectiles2
life: 25
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.7
alpha: 1

drawUnderUnits: false
ySpeedRelative: 2
atmospheric: true


[effect_大火花]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.25
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12

animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2

[effect_弹壳]
priority: low
image: ROOT:/通用特效/弹壳.png
spawnChance: 0.75
life: 130
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.3
scaleTo: 0.3
alpha: 2

fadeInTime: 5
drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
xSpeedRelative: -0.1
xSpeedRelativeRandom: 0.05
ySpeedRelativeRandom: 0.25
yOffsetRelative: -28
xOffsetRelative: 0
hSpeed: 2
dirSpeedRandom: 50


[movement]
movementType: AIR
moveSpeed: 1.1
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.2
maxTurnSpeed: 2.4
startingHeightOffset: 1000
turnAcceleration: 0.4
targetHeight: 70
targetHeightDrift: 2
moveSlidingMode : false
moveIgnoringBody: true

#targetHeightDrift:1


[ai]
disableUse: true


