


[core]
name: 创世纪科技中心
displayText: Научный центр Генезиса
displayDescription: 【Уровень t3】【Здание】【Наземный юнит】\n-Тактическое назначение：наукаразрабатыватьсооружение，без вооружения。\n-同одинвремяможно иметь только одно，не можетразвёртыватьвнадводный。\n-Генезиссамыйпередовой 科研персоналвэтот集结，\n-они может安静 минута析иисследоватьразличныеновый наука，\n-ив качествевойскаобеспечиваетразличные意想недостигнутыйбафф，\n-а такжеразрабатыватьсамыйпродвинутый，самый具毁灭тип оружие。
class: CustomUnitMetadata
price: 2500
maxHp: 10000

footprint: -4,-2,4,4
constructionFootprint: -4,-2,4,4
techLevel: 1
buildSpeed: 0.001
armour: 10

#availableInDemo: true
radius: 55
#displayRadius: 25
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini

isBuilding: true
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*6,largeExplosion
tags: 地面,科技中心,建筑
energyMax: 1
energyRegen: 0

energyStartingPercentage: 1


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='科技中心')
deleteSelf: true
showMessageToPlayer: 卡BUG？тыв想屁吃，делатьв качествештрафмногоостатокюнитя服务устройство吞 눈_눈



[action_精炼技术1]
text: Технология очистки1
buildSpeed: 45s
price: 2000,energy=1
description: -черезисследоватьпередовой冶炼технология，\n-можетболееэффективный будет钍сдругие共生元素минута离，\n-этотбудетразблокировать“точный矿提纯”冶炼选项，разблокироватьГенезис石油钻井。
isVisible: if not self.globalTeamTags(includes='精炼技术1')
addGlobalTeamTags: 精炼技术1
addResources: energy=1
iconImage: 精炼技术1.png
showMessageToPlayer: Технология очистки1ужеразрабатыватьзавершать
pos: 1
ai_isHighPriority: true
[action_精炼技术2]
text: Технология очистки2
buildSpeed: 235s
price: 4000,energy=1,钍=200
description: -исследоватьипревосходный化ещё болееэффективныйТехнология очистки，\n-будеточень большойусиливаетРуда тория минута离эффективностьиоригинал油 снова加工эффективность，\n-этотбудетразблокироватьКузница Генезиса 钍 точный华萃取，\n-увеличиваетКузницапродать钍иРуда тория скоростьицена，\n-Лазерная буровая на торииза секунду额вне产выходить6Руда тория。\n-Генезис石油钻井за секунду额вне产выходить10资源。
isVisible: if self.globalTeamTags(includes='精炼技术1') and not self.globalTeamTags(includes='精炼技术2')
addGlobalTeamTags: 精炼技术2
addResources: energy=1
iconImage: 精炼技术2.png
showMessageToPlayer: Технология очистки2ужеразрабатыватьзавершать
pos: 1
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
[action_精炼技术最大化]
displayType: infoOnlyNoBox
iconImage: 精炼技术2.png
text: Технология очисткиполностью улучшено
isActive: false
isVisible: if self.globalTeamTags(includes='精炼技术2')
[action_裂变技术1]
text: Технология деления 1
buildSpeed: 45s
price: 1200,energy=1,钍=200
description: -исследовать钍база熔盐裂变堆，\n-позволяетГенезистакжеспособен供应высокийможетэнергияоружиеипродвинутыйпроизводствосооружение，\n-этотбудетразблокироватьЯдерный крейсер，Лазерная башня1，2 уровня，Лазерный танка такжеИстребитель «Кровавое крыло»。\n-Истребитель «Чёрный страж» предварительная технология。
isVisible: if not self.globalTeamTags(includes='裂变技术1')
addGlobalTeamTags: 裂变技术1
addResources: energy=1
iconImage: 裂变技术1.png
showMessageToPlayer: Технология деления1ужеразрабатыватьзавершать
pos: 2
ai_isHighPriority: true
[action_裂变技术2]
text: Технология деления 2
buildSpeed: 135s
price: 14000,energy=1,钍=500
description: -钍база熔盐裂变堆微 化инеуправлятьТехнология деления，\n-позволяетспособенизготавливатьядерныйснаряд头и供应высокий耗можетюнит，\n-Чёрная Вдова，Воздушный канонёр класса «Серафим»，Система ПРО «Гроза»，Жезл рассеивания тьмы，死亡его眼ракета，\n-雷神его锤ракета，Хранитель мираракета предварительная технология
isVisible: if self.globalTeamTags(includes='裂变技术1') and not self.globalTeamTags(includes='裂变技术2')
addGlobalTeamTags: 裂变技术2
addResources: energy=1
iconImage: 裂变技术2.png
showMessageToPlayer: Технология деления2ужеразрабатыватьзавершать
pos: 3
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
[action_裂变技术最大化]
displayType: infoOnlyNoBox
iconImage: 裂变技术2.png
text: Технология деленияполностью улучшено
isActive: false
isVisible: if self.globalTeamTags(includes='裂变技术2')
[action_材料技术1]
text: Материаловедение 1
buildSpeed: 15s
price: 800,energy=1
description: -Материаловедение входить步，\n-способенэффективный提纯титан，тантал，гафний，иридийи т.д.высокийсильный度金принадлежать，\n-этотпозволяетмехдолжен 关键材料карбид тантала-гафнияможет量产，\n-этотбудетразблокироватьОгненный смерч，\n-Боевой мех，Гладиатор，Вертолёт «Кобра»。
isVisible: if not self.globalTeamTags(includes='材料技术1')
addGlobalTeamTags: 材料技术1
addResources: energy=1
iconImage: 材料技术1.png
showMessageToPlayer: Материаловедение1ужеразрабатыватьзавершать
pos: 3
ai_isHighPriority: true
[action_材料技术2]
text: Материаловедение 2
buildSpeed: 90s
price: 1500,energy=1,钍=200
description: -Материаловедениеболееверходин层楼，\n-позволяетспособенумелыйосвоитьграфени碳炔и т.д.высокотехнологичный材料，\n-этотбудетразблокироватьЛинкор класса «Чёрная Жемчужина»，Вертолёт-Крепость，Танк «Колосс»。разблокироватьТехнология баллистических ракет，разблокироватьКрепостьt1。\n-Истребитель «Чёрный страж»，Эсминец класса «Молот-Рыба»，Тиран， предварительная технология。
isVisible: if self.globalTeamTags(includes='材料技术1') and not self.globalTeamTags(includes='材料技术2')
addGlobalTeamTags: 材料技术2
addResources: energy=1
iconImage: 材料技术2.png
showMessageToPlayer: Материаловедение2ужеразрабатыватьзавершать
pos: 3
ai_isHighPriority: true
[action_材料技术3]
text: Материаловедение 3
buildSpeed: 115s
price: 5000,energy=1,钍=350
description: -будетисследоватьсамыйдо沿 材料学технология，\n-самыйновый нанонаукаможет批量производствоочень высокийсильный度 различные材料，\n-разблокироватьБМП «Хранитель»，указанныйнаукаодновременноявляетсяШок-танк，Чёрная Вдова，Суперистребитель，\n-Воздушный часовой класса «Галка»，Стратегический бомбардировщик класса «Заря»，Воздушный канонёр класса «Серафим»，Суперкорабль，Амфибийный штурмовой корабль класса «Астролог»，Крепостьt2 предварительная технология。
isVisible: if self.globalTeamTags(includes='材料技术2') and not self.globalTeamTags(includes='材料技术3')
addGlobalTeamTags: 材料技术3
addResources: energy=1
iconImage: 材料技术3.png
showMessageToPlayer: Материаловедение3ужеразрабатыватьзавершать
pos: 3
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
[action_材料技术最大化]
displayType: infoOnlyNoBox
iconImage: 材料技术3.png
text: Материаловедениеполностью улучшено
isActive: false
isVisible: if self.globalTeamTags(includes='材料技术3')
[action_弹道导弹技术1]
text: Технология баллистических ракет1
buildSpeed: 90s
price: 3000,energy=1,钍=300
description: -этотпозволяеттыможетстроитьГенезиссамый具威慑сила оружиеегоодин，\n-этот видтехнологияможетпозволяеттыиметьдальнийточныйудар способность，\n-а такжесильный效 против导способность，\n-дажеможетпозволятьтывыполнятьстратегияядерныйснарядудар，\n-разблокироватьРакетная база Генезисаt1，Система ПВО Генезиса «Железный купол»t1，\n-разблокироватьДлинноносый Кайманатакаподводная лодказапускатьснаряд道ракета функция。
isVisible: if not self.globalTeamTags(includes='弹道导弹技术1')
addGlobalTeamTags: 弹道导弹技术1
isLocked:if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: Требуется материаловедение 2
addResources: energy=1
iconImage: 弹道导弹技术1.png
showMessageToPlayer: Технология баллистических ракет1ужеразрабатыватьзавершать
pos: 4
[action_弹道导弹技术2]
text: Технология портативных баллистических ракет
buildSpeed: 125s
price: 6000,energy=1,钍=350
description: -передовойснаряд道ракетамалый 化технология，\n-этот видтехнологияможетпозволятьбудетдальнийатакаракета，а такжебольшой против导системаразвёртывать至运везти车，ядерныйподводная лодка，вплоть дотяжёлый бомбардировщикверх，\n- 狱егоогоньракетаплатформа，«Адская буря»，Амфибийный штурмовой корабль класса «Астролог»，Стратегическая ядерная подлодка класса «Поглощающая Сирена» предварительная технология。\n-разблокироватьЗаря，Бомбардировщик «Демон»несёткрылатая ракета способность，разблокироватьТяжёлая инженерная машина защита от стратегического оружияспособность。\n-разблокироватьРакетная база Генезисаt2，разблокироватьнебо盾ракетаоборонасистематактикаракетаспособность。
isVisible: if not self.globalTeamTags(includes='弹道导弹技术2')
addGlobalTeamTags: 弹道导弹技术2
addResources: energy=1
iconImage: 弹道导弹技术2.png
showMessageToPlayer: Технология портативных баллистических ракетужеразрабатыватьзавершать
pos: 4
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[action_基础科学进步1]
text: Фундаментальная наука1
buildSpeed: 150s
price: 13000,energy=1,钍=500
description: -фундаментальная наука всеповерхностьвходить步，обладать划эпоха意义 科研，\n-этотможетпозволяеттыиметьГенезиссамый凶悍 юнит，разблокироватьИстребитель «Громовержец»，Воздушный канонёр класса «Мерзость»，\n-Адский гончий。Бедствиекласстяжёлыйатакамашина，«Адская буря»，Стратегический бомбардировщик класса «Заря»，Тяжёлый штурмовик класса «Похоронный звон»，\n-Стратегическая ядерная подлодка класса «Поглощающая Сирена» предварительная технология。
isLocked: if not self.globalTeamTags(includes='材料技术2') or not self.globalTeamTags(includes='裂变技术1')
isLockedMessage: Требуется технология деления 1иМатериаловедение2
isVisible: if not self.globalTeamTags(includes='基础科学进步1')
addGlobalTeamTags: 基础科学进步1
addResources: energy=1
iconImage: 基础科学进步.png
showMessageToPlayer: фундаментальная наукаужедостичь突破типвходить展。
pos: 4
ai_isHighPriority: true

[action_超导技术1]
text: Сверхпроводимость 1
buildSpeed: 85s
price: 4000,energy=1,钍=250
description: -Сверхпроводимостьявляетсяиспользоватьпередовойтехнологияа такжеприменение浪человектехнология важныйсначала决условие，\n-этотбудетпозволяетГенезисармияможетнемного安установитьсупер导оригиналвещь。\n-этотбудетразблокироватьПередовой，Парящий танк，Лазерная башняt4。указанныйнаукаодновременноявляетсяШок-танк，Суперистребитель，\n-Воздушный часовой класса «Галка»，Воздушный канонёр класса «Серафим»，Линейный крейсер класса «Морской волк» предварительная технология。
isVisible: if not self.globalTeamTags(includes='超导技术1')
addGlobalTeamTags: 超导技术1
addResources: energy=1
iconImage: 超导技术1.png
showMessageToPlayer: Сверхпроводимость1ужеразрабатыватьзавершать
pos: 2
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[action_外骨骼技术]
text: Технология экзоскелета
buildSpeed: 55s
price: 8500,energy=1
description: в качествесоюзныйпехота及лёгкиймех，额вне附加 есть源экзоскелет及额вне护甲система，\n-способенбольшой幅повышаетэтот类юнит защитные характеристики及манёвренность，\n-одновременно 益вэкзоскелет额вне 承тяжёлыйспособность，позволяетпехотаможетнесётбольше бронясзащита护。\n-будетв качествеБесстрашный боец，Гладиатор，Манипулятор，附加лёгкое укрытиехарактеристика，\n-в качествеОхотник，увеличиваеттяжёлое укрытиехарактеристика，\n-одновременноувеличиваетвсепехотаоснова护甲10пункт，\n-всепехотамаксимальный生命值加20%，移动скорость加30%，转кскорость加65%，\n-移动скорость加становиться 额внезначениебудетнеиспользуется для计算衰解замедление，Нанокатализатор加速и т.д.другие计算。\n-в 衰解времянеобеспечивает移动скоростьбафф。移动скоростьбаффвсдругие移速бафф叠加время，будет取максимум。
isVisible: if not self.globalTeamTags(includes='外骨骼')
addGlobalTeamTags: 外骨骼
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/外骨骼.png
showMessageToPlayer: Технология экзоскелетаужеразрабатыватьзавершать
pos: 0.001
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[action_强固建筑]
text: Укреплённое здание
buildSpeed: 150s
price: 9000,energy=1,钍=350
description: в качествевсезданиеи工事обеспечивает 加固план，этотбудетвзданиевсе承тяжёлый住и墙壁в添加额вне 加固структура，\n-и安установитьбольшое количество защитавзрыв气密 а такжеавтоматический灭огоньустановить置и т.д.один系列новый鲜玩意，\n-с保证все关键сооружениеможетввражеская армиясамый猛烈 пушкаогоньв幸存。\n-Улучшениепосле，всездание血量+25%，основа护甲+25%，\n-башня，Стена，碉堡то血量+40%。 всезданиепротивстратегическое оружие抗тип+40%，\n-всезданиеза секунду恢复50пункт生命值，Крепостьt2 предварительная технология。\n-Улучшениеполный毕послебудет立刻ремонтвсе受损здание。
isVisible: if not self.globalTeamTags(includes='强固建筑')
addGlobalTeamTags: 强固建筑
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/建筑加固.png
showMessageToPlayer: Укреплённое зданиеужеразрабатыватьзавершать
pos: 0.0015
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[action_模块化技术]
text: Модульные технологии
buildSpeed: 75s
price: 5000,energy=1,钍=200
description: в качествеАльянс Генезис механический юнитобеспечивает модульныймодификация，а такжепротив工厂производствооборудование всеквадратныйпозицияпревосходный化。\n-Модульные технологии 普及можетпозволяетнекоторыеГенезисюнитвна поле боявыполнятьмодифицироватьстановитьсяне同модель 变вид，\n-самыйтрудный можно贵 является， 益вмодульныйнестиприходить мощныйзапчастиуниверсальныйтип，\n-некоторыеегододорогойитрудно直соединятьпроизводство юнит或зданиеможет节околобольше производитьстановиться本。\n-в качествеПередовой，Атластранспорткорабль，Супертанкобеспечиваетмодификацияплан（разблокироватьMK2）。\n-позволятьКазармаодин разтип训练два或много Бесстрашный боец，Шок-пехотинец，Расчёт ракет «Жало»，Боевой мех，Огненный смерч，\n-Десантник со штандартом，Манипулятор。виметьФундаментальная наука в случае，\n-Адский гончий，Бедствиекласстяжёлыйатакамашина，Воздушный канонёр класса «Мерзость»，Эсминец класса «Молот-Рыба»，Линкор класса «Чёрная Жемчужина» производитьстановиться本уменьшает35%。\n-модульныйпроизводство превосходный惠ценаюнит，а такжедвойной倍производство юнитбудетне будет受домодульныйнано煅炉 производствоскоростьбафф。\n-будетпозволятьТяжёлая инженерная машина直соединятьстроитьабсолютныйбольшинствополныйклассздание。
isVisible: if not self.globalTeamTags(includes='模块化技术')
addGlobalTeamTags: 模块化技术
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/模块生产.png
showMessageToPlayer: Модульные технологииужеразрабатыватьзавершать
pos: 0.0012
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[graphics]
total_frames: 1
image: 科技中心.png
image_wreak: 科技中心死亡.png
image_back: 科技中心背景.png
image_shadow: 影子.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: -9
y: -10
image_end: 电梯.png
image_end_teamColors: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_2]
x: 0
y: 0
image_end: 科技中心损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_3]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[animation_1]
onActions: idle
blendIn: 1s
blendOut: 2s
arm1_0s: {x:0, y:0}
arm1_4s: {x:0, y:35}
arm1_6s: {x:0, y:35}
arm1_10s: {x:0, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:55
delayedStartTimerRandom:30



[ai]
buildPriority: 0.07
ai_upgradePriority: 0.07
noneGlobalExtraPriority: 0.3
maxEachBase: 50
maxGlobal: 50


