


[core]
name: 创世纪科技中心
displayDescription: 【阶级t3】【建筑单位】【地面单位】\n-战术定位：科技研发设施，无武装。\n-同一时间只能拥有一座，无法部署在水上。\n-创世纪最尖端的科研人员在此集结，\n-他们的可以安静的分析并研究各种新型科技，\n-并为部队提供各种意想不到的增益，\n-以及研发最先进，最具毁灭性的武器。
class: CustomUnitMetadata
price: 2500
maxHp: 10000

footprint: -4,-2,4,4
constructionFootprint: -4,-2,4,4
techLevel: 1
buildSpeed: 0.001
armour: 10

#availableInDemo: true
radius: 55
#displayRadius: 25
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini

isBuilding: true
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*6,largeExplosion
tags: 地面,科技中心,建筑
energyMax: 1
energyRegen: 0

energyStartingPercentage: 1


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='科技中心')
deleteSelf: true
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈



[action_精炼技术1]
text: 精炼技术1
buildSpeed: 45s
price: 2000,energy=1
description: -通过研究先进的冶炼技术，\n-能更高效的将钍与其他共生元素分离，\n-这将解锁“精矿提纯”冶炼选项，解锁创世纪石油钻井。
isVisible: if not self.globalTeamTags(includes='精炼技术1')
addGlobalTeamTags: 精炼技术1
addResources: energy=1
iconImage: 精炼技术1.png
showMessageToPlayer: 精炼技术1已经研发完成
pos: 1
ai_isHighPriority: true
[action_精炼技术2]
text: 精炼技术2
buildSpeed: 235s
price: 4000,energy=1,钍=200
description: -研究并优化更加有效的精炼技术，\n-将极大增强钍原石的分离效率和原油的再加工效率，\n-这将解锁创世纪锻造厂的钍 精华萃取，\n-增加锻造厂出售钍和钍原石的速度和价格，\n-钍激光钻机每秒额外产出6钍原石。\n-创世纪石油钻井每秒额外产出10资源。
isVisible: if self.globalTeamTags(includes='精炼技术1') and not self.globalTeamTags(includes='精炼技术2')
addGlobalTeamTags: 精炼技术2
addResources: energy=1
iconImage: 精炼技术2.png
showMessageToPlayer: 精炼技术2已经研发完成
pos: 1
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心
[action_精炼技术最大化]
displayType: infoOnlyNoBox
iconImage: 精炼技术2.png
text: 精炼技术已全面升级
isActive: false
isVisible: if self.globalTeamTags(includes='精炼技术2')
[action_裂变技术1]
text: 裂变技术 1
buildSpeed: 45s
price: 1200,energy=1,钍=200
description: -研究钍基熔盐裂变堆，\n-使得创世纪也能够供应高能能源武器和先进生产设施，\n-这将解锁核子巡洋舰，镭射炮塔1，2级，镭射坦克以及血翼战斗机。\n-黑色守卫战斗机的前置科技。
isVisible: if not self.globalTeamTags(includes='裂变技术1')
addGlobalTeamTags: 裂变技术1
addResources: energy=1
iconImage: 裂变技术1.png
showMessageToPlayer: 裂变技术1已经研发完成
pos: 2
ai_isHighPriority: true
[action_裂变技术2]
text: 裂变技术 2
buildSpeed: 135s
price: 14000,energy=1,钍=500
description: -钍基熔盐裂变堆微型化和不可控裂变技术，\n-使得能够制作核弹头和供应高耗能单位，\n-黑寡妇，炽天使级空中炮艇，雷暴导弹防御系统，破暗雷杖，死亡之眼导弹，\n-雷神之锤导弹，和平守卫者导弹的前置科技
isVisible: if self.globalTeamTags(includes='裂变技术1') and not self.globalTeamTags(includes='裂变技术2')
addGlobalTeamTags: 裂变技术2
addResources: energy=1
iconImage: 裂变技术2.png
showMessageToPlayer: 裂变技术2已经研发完成
pos: 3
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心
[action_裂变技术最大化]
displayType: infoOnlyNoBox
iconImage: 裂变技术2.png
text: 裂变技术已全面升级
isActive: false
isVisible: if self.globalTeamTags(includes='裂变技术2')
[action_材料技术1]
text: 材料技术 1
buildSpeed: 15s
price: 800,energy=1
description: -材料技术的进步，\n-能够高效提纯钛，钽，铪，铱等高强度金属，\n-这使得机甲必须的关键材料碳化钽铪可以量产，\n-这将解锁火龙卷，\n-机甲战士，角斗士，眼镜蛇直升机。
isVisible: if not self.globalTeamTags(includes='材料技术1')
addGlobalTeamTags: 材料技术1
addResources: energy=1
iconImage: 材料技术1.png
showMessageToPlayer: 材料技术1已经研发完成
pos: 3
ai_isHighPriority: true
[action_材料技术2]
text: 材料技术 2
buildSpeed: 90s
price: 1500,energy=1,钍=200
description: -材料技术更上一层楼，\n-使得能够熟练掌握石墨烯和碳炔等高科技材料，\n-这将解锁黑珍珠级战列舰，堡垒直升机，巨兽坦克。解锁弹道导弹技术，解锁要塞t1。\n-黑色守卫战斗机，双髻鲨级驱逐舰，暴君，的前置科技。
isVisible: if self.globalTeamTags(includes='材料技术1') and not self.globalTeamTags(includes='材料技术2')
addGlobalTeamTags: 材料技术2
addResources: energy=1
iconImage: 材料技术2.png
showMessageToPlayer: 材料技术2已经研发完成
pos: 3
ai_isHighPriority: true
[action_材料技术3]
text: 材料技术 3
buildSpeed: 115s
price: 5000,energy=1,钍=350
description: -将研究最前沿的材料学技术，\n-最新的纳米科技能批量生产极高强度的各种材料，\n-解锁守护者IFV，该科技同时是休克打击坦克，黑寡妇，超战机，\n-寒鸦级空中哨兵，黎明曙光级战略轰炸机，炽天使级空中炮艇，超战舰，占星师级两栖攻击舰，要塞t2的前置科技。
isVisible: if self.globalTeamTags(includes='材料技术2') and not self.globalTeamTags(includes='材料技术3')
addGlobalTeamTags: 材料技术3
addResources: energy=1
iconImage: 材料技术3.png
showMessageToPlayer: 材料技术3已经研发完成
pos: 3
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心
[action_材料技术最大化]
displayType: infoOnlyNoBox
iconImage: 材料技术3.png
text: 材料技术已全面升级
isActive: false
isVisible: if self.globalTeamTags(includes='材料技术3')
[action_弹道导弹技术1]
text: 弹道导弹技术1
buildSpeed: 90s
price: 3000,energy=1,钍=300
description: -这使得你可以建造创世纪最具威慑力的武器之一，\n-这种技术可以让你拥有远程精确打击的能力，\n-以及强效的反导能力，\n-甚至可以允许你进行战略核弹打击，\n-解锁创世纪导弹基地t1，创世纪铁穹防空系统t1，\n-解锁长吻鳄攻击潜艇发射弹道导弹的功能。
isVisible: if not self.globalTeamTags(includes='弹道导弹技术1')
addGlobalTeamTags: 弹道导弹技术1
isLocked:if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: 需要材料技术2
addResources: energy=1
iconImage: 弹道导弹技术1.png
showMessageToPlayer: 弹道导弹技术1已经研发完成
pos: 4
[action_弹道导弹技术2]
text: 便携式弹道导弹技术
buildSpeed: 125s
price: 6000,energy=1,钍=350
description: -先进的弹道导弹小型化技术，\n-这种技术可以允许将长距离攻击导弹，以及大型反导系统部署至运载车，核潜艇，乃至大型轰炸机上，\n-地狱之火导弹平台，地狱风暴，占星师级两栖攻击舰，噬海女妖级战略核潜艇的前置科技。\n-解锁黎明曙光，恶鬼轰炸机携带巡航导弹的能力，解锁重型工程车的战略武器防御能力。\n-解锁创世纪导弹基地t2，解锁天盾导弹防御系统战术导弹能力。
isVisible: if not self.globalTeamTags(includes='弹道导弹技术2')
addGlobalTeamTags: 弹道导弹技术2
addResources: energy=1
iconImage: 弹道导弹技术2.png
showMessageToPlayer: 便携式弹道导弹技术已经研发完成
pos: 4
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心

[action_基础科学进步1]
text: 基础科学进步1
buildSpeed: 150s
price: 13000,energy=1,钍=500
description: -基础科学的全面进步，具有划时代意义的科研，\n-这可以让你拥有创世纪最凶悍的单位，解锁雷霆战机，憎恶级空中炮艇，\n-地狱猎犬。天灾级重型攻击机，地狱风暴，黎明曙光级战略轰炸机，丧钟级重型攻击机，\n-噬海女妖级战略核潜艇的前置科技。
isLocked: if not self.globalTeamTags(includes='材料技术2') or not self.globalTeamTags(includes='裂变技术1')
isLockedMessage: 需要裂变技术1和材料技术2
isVisible: if not self.globalTeamTags(includes='基础科学进步1')
addGlobalTeamTags: 基础科学进步1
addResources: energy=1
iconImage: 基础科学进步.png
showMessageToPlayer: 基础科学已经取得突破性进展。
pos: 4
ai_isHighPriority: true

[action_超导技术1]
text: 超导技术 1
buildSpeed: 85s
price: 4000,energy=1,钍=250
description: -超导技术是使用尖端技术以及应用浪人技术的重要先决条件，\n-这将使得创世纪军队能少量安装超导原件。\n-这将解锁尖兵，浮游坦克，镭射炮塔t4。该科技同时是休克打击坦克，超战机，\n-寒鸦级空中哨兵，炽天使级空中炮艇，海狼级战列巡洋舰的前置科技。
isVisible: if not self.globalTeamTags(includes='超导技术1')
addGlobalTeamTags: 超导技术1
addResources: energy=1
iconImage: 超导技术1.png
showMessageToPlayer: 超导技术1已经研发完成
pos: 2
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心

[action_外骨骼技术]
text: 外骨骼技术
buildSpeed: 55s
price: 8500,energy=1
description: 为我方步兵及轻型机甲，额外附加的有源外骨骼及额外护甲系统，\n-能够大幅提升此类单位的防护能力及机动性，\n-同时得益于外骨骼额外的承重能力，使得步兵可以携带更多的装甲与防护。\n-将为无畏战士，角斗士，操纵者，附加轻型掩体特性，\n-为狩猎者，增加重型掩体特性，\n-同时增加所有步兵基础护甲10点，\n-所有步兵最大生命值加20%，移动速度加30%，转向速度加65%，\n-移动速度加成的额外数值将不用于计算衰解减速，纳米催化剂加速等其他计算。\n-在被衰解时不提供移动速度增益。移动速度增益在与其他移速增益叠加时，将取最大值。
isVisible: if not self.globalTeamTags(includes='外骨骼')
addGlobalTeamTags: 外骨骼
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/外骨骼.png
showMessageToPlayer: 外骨骼技术已经研发完成
pos: 0.001
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: 你需要三级指挥中心

[action_强固建筑]
text: 强固建筑
buildSpeed: 150s
price: 9000,energy=1,钍=350
description: 为所有建筑物和工事提供的加固方案，这将在建筑物所有承重住和墙壁中添加额外的加固结构，\n-并安装大量的防爆气密门以及自动灭火装置等一系列新鲜玩意，\n-以保证所有关键设施能在敌军最猛烈的炮火中幸存。\n-升级后，所有建筑物血量+25%，基础护甲+25%，\n-炮塔，围墙，碉堡则血量+40%。 所有建筑对战略武器抗性+40%，\n-所有建筑物每秒恢复50点生命值，要塞t2的前置科技。\n-升级完毕后将立刻修复所有受损建筑物。
isVisible: if not self.globalTeamTags(includes='强固建筑')
addGlobalTeamTags: 强固建筑
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/建筑加固.png
showMessageToPlayer: 强固建筑已经研发完成
pos: 0.0015
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: 你需要三级指挥中心

[action_模块化技术]
text: 模块化技术
buildSpeed: 75s
price: 5000,energy=1,钍=200
description: 为创世纪联盟的机械单位提供的模块化改造，以及对工厂生产设备的全方位优化。\n-模块化技术的普及能让一些创世纪单位在战场上进行改装成不同型号的变种，\n-最难得可贵的是，得益于模块化带来的强大零件通用性，\n-一些之前昂贵且难以直接生产的单位或建筑可以节约更多的制造成本。\n-为尖兵，阿特拉斯运输船，超坦克提供改造方案（解锁MK2）。\n-允许兵营一次性训练两个或多个无畏战士，休克打击步兵，蜂刺导弹小组，机甲战士，火龙卷，\n-标旗空降兵，操纵者。在拥有基础科学进步的情况下，\n-地狱猎犬，天灾级重型攻击机，憎恶级空中炮艇，双髻鲨级驱逐舰，黑珍珠级战列舰的制造成本减少35%。\n-模块化生产的优惠价格单位，以及双倍生产的单位将不会受到模块化纳米煅炉的生产速度增益。\n-将允许重型工程车直接建造绝大多数满级建筑。
isVisible: if not self.globalTeamTags(includes='模块化技术')
addGlobalTeamTags: 模块化技术
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/模块生产.png
showMessageToPlayer: 模块化技术已经研发完成
pos: 0.0012
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: 你需要三级指挥中心

[graphics]
total_frames: 1
image: 科技中心.png
image_wreak: 科技中心死亡.png
image_back: 科技中心背景.png
image_shadow: 影子.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: -9
y: -10
image_end: 电梯.png
image_end_teamColors: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_2]
x: 0
y: 0
image_end: 科技中心损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_3]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[animation_1]
onActions: idle
blendIn: 1s
blendOut: 2s
arm1_0s: {x:0, y:0}
arm1_4s: {x:0, y:35}
arm1_6s: {x:0, y:35}
arm1_10s: {x:0, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:55
delayedStartTimerRandom:30



[ai]
buildPriority: 0.07
ai_upgradePriority: 0.07
noneGlobalExtraPriority: 0.3
maxEachBase: 50
maxGlobal: 50


