


[core]
name: 创世纪科技中心
displayText: Научный центр Генезиса
displayDescription: 【Уровень t3】【Здание】【Наземный юнит】\n-Тактическое назначение：наукаразрабатыватьсооружение，без вооружения。\n-同一时间можно иметь только одно，无法развёртывать在надводный。\n-Генезиссамый尖端的科研персонал在此集结，\n-они的может安静的分析и研究различные新 наука，\n-и为部队обеспечиваетразличные意想不достигнутый增益，\n-а такжеразрабатыватьсамыйпродвинутый，самый具毁灭性的оружие。
class: CustomUnitMetadata
price: 2500
maxHp: 10000

footprint: -4,-2,4,4
constructionFootprint: -4,-2,4,4
techLevel: 1
buildSpeed: 0.001
armour: 10

#availableInDemo: true
radius: 55
#displayRadius: 25
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini

isBuilding: true
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*6,largeExplosion
tags: 地面,科技中心,建筑
energyMax: 1
energyRegen: 0

energyStartingPercentage: 1


[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='科技中心')
deleteSelf: true
showMessageToPlayer: 卡BUG？ты在想屁吃，做为惩罚多余юнитя服务устройство吞了눈_눈



[action_精炼技术1]
text: Технология очистки1
buildSpeed: 45s
price: 2000,energy=1
description: -通过研究передовой冶炼技术，\n-можетболееэффективный的将钍与其он共生元素分离，\n-这将解锁“精矿提纯”冶炼选项，解锁Генезис石油钻井。
isVisible: if not self.globalTeamTags(includes='精炼技术1')
addGlobalTeamTags: 精炼技术1
addResources: energy=1
iconImage: 精炼技术1.png
showMessageToPlayer: Технология очистки1已经разрабатывать完成
pos: 1
ai_isHighPriority: true
[action_精炼技术2]
text: Технология очистки2
buildSpeed: 235s
price: 4000,energy=1,钍=200
description: -研究и优化ещё болееэффективныйТехнология очистки，\n-将极大усиливаетРуда тория的分离эффективность和原油的再加工эффективность，\n-这将解锁Кузница Генезиса的钍 精华萃取，\n-увеличиваетКузница出售钍和Руда тория的скорость和价格，\n-Лазерная буровая на тории每秒额外产出6Руда тория。\n-Генезис石油钻井每秒额外产出10资源。
isVisible: if self.globalTeamTags(includes='精炼技术1') and not self.globalTeamTags(includes='精炼技术2')
addGlobalTeamTags: 精炼技术2
addResources: energy=1
iconImage: 精炼技术2.png
showMessageToPlayer: Технология очистки2已经разрабатывать完成
pos: 1
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
[action_精炼技术最大化]
displayType: infoOnlyNoBox
iconImage: 精炼技术2.png
text: Технология очистки已全面升класс
isActive: false
isVisible: if self.globalTeamTags(includes='精炼技术2')
[action_裂变技术1]
text: Технология деления 1
buildSpeed: 45s
price: 1200,energy=1,钍=200
description: -研究钍基熔盐裂变堆，\n-позволяетГенезистакжеспособен供应高можетможет源оружие和продвинутыйпроизводствосооружение，\n-这将解锁Ядерный крейсер，Лазерная башня1，2класс，Лазерный танка такжеИстребитель «Кровавое крыло»。\n-Истребитель «Чёрный страж»的前置наука。
isVisible: if not self.globalTeamTags(includes='裂变技术1')
addGlobalTeamTags: 裂变技术1
addResources: energy=1
iconImage: 裂变技术1.png
showMessageToPlayer: Технология деления1已经разрабатывать完成
pos: 2
ai_isHighPriority: true
[action_裂变技术2]
text: Технология деления 2
buildSpeed: 135s
price: 14000,energy=1,钍=500
description: -钍基熔盐裂变堆微 化和не控Технология деления，\n-позволяетспособенизготавливать核弹头和供应高耗можетюнит，\n-Чёрная Вдова，Воздушный канонёр класса «Серафим»，Система ПРО «Гроза»，Жезл рассеивания тьмы，死亡之眼ракета，\n-雷神之锤ракета，Хранитель мираракета的前置наука
isVisible: if self.globalTeamTags(includes='裂变技术1') and not self.globalTeamTags(includes='裂变技术2')
addGlobalTeamTags: 裂变技术2
addResources: energy=1
iconImage: 裂变技术2.png
showMessageToPlayer: Технология деления2已经разрабатывать完成
pos: 3
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
[action_裂变技术最大化]
displayType: infoOnlyNoBox
iconImage: 裂变技术2.png
text: Технология деления已全面升класс
isActive: false
isVisible: if self.globalTeamTags(includes='裂变技术2')
[action_材料技术1]
text: Материаловедение 1
buildSpeed: 15s
price: 800,energy=1
description: -Материаловедение的进步，\n-способенэффективный提纯钛，钽，铪，铱等高强度金属，\n-这позволяетмехдолжен的关键材料碳化钽铪может量产，\n-这将解锁Огненный смерч，\n-Боевой мех，Гладиатор，Вертолёт «Кобра»。
isVisible: if not self.globalTeamTags(includes='材料技术1')
addGlobalTeamTags: 材料技术1
addResources: energy=1
iconImage: 材料技术1.png
showMessageToPlayer: Материаловедение1已经разрабатывать完成
pos: 3
ai_isHighPriority: true
[action_材料技术2]
text: Материаловедение 2
buildSpeed: 90s
price: 1500,energy=1,钍=200
description: -Материаловедениеболее上一层楼，\n-позволяетспособен熟练掌握石墨烯和碳炔等высокотехнологичный材料，\n-这将解锁Линкор класса «Чёрная Жемчужина»，Вертолёт-Крепость，Танк «Колосс»。解锁Технология баллистических ракет，解锁Крепостьt1。\n-Истребитель «Чёрный страж»，Эсминец класса «Молот-Рыба»，Тиран，的前置наука。
isVisible: if self.globalTeamTags(includes='材料技术1') and not self.globalTeamTags(includes='材料技术2')
addGlobalTeamTags: 材料技术2
addResources: energy=1
iconImage: 材料技术2.png
showMessageToPlayer: Материаловедение2已经разрабатывать完成
pos: 3
ai_isHighPriority: true
[action_材料技术3]
text: Материаловедение 3
buildSpeed: 115s
price: 5000,energy=1,钍=350
description: -将研究самый前沿的材料学技术，\n-самый新的纳米наукаможет批量производство极高强度的различные材料，\n-解锁БМП «Хранитель»，该наукаодновременно是Шок-танк，Чёрная Вдова，Суперистребитель，\n-Воздушный часовой класса «Галка»，Стратегический бомбардировщик класса «Заря»，Воздушный канонёр класса «Серафим»，Суперкорабль，Амфибийный штурмовой корабль класса «Астролог»，Крепостьt2的前置наука。
isVisible: if self.globalTeamTags(includes='材料技术2') and not self.globalTeamTags(includes='材料技术3')
addGlobalTeamTags: 材料技术3
addResources: energy=1
iconImage: 材料技术3.png
showMessageToPlayer: Материаловедение3已经разрабатывать完成
pos: 3
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
[action_材料技术最大化]
displayType: infoOnlyNoBox
iconImage: 材料技术3.png
text: Материаловедение已全面升класс
isActive: false
isVisible: if self.globalTeamTags(includes='材料技术3')
[action_弹道导弹技术1]
text: Технология баллистических ракет1
buildSpeed: 90s
price: 3000,energy=1,钍=300
description: -这позволяеттыможетстроитьГенезиссамый具威慑力的оружие之一，\n-这вид技术может让тыиметьдалеко程精确удар的способность，\n-а также强效的反导способность，\n-дажеможет允许ты进行стратегия核弹удар，\n-解锁Ракетная база Генезисаt1，Система ПВО Генезиса «Железный купол»t1，\n-解锁Длинноносый Кайман攻击подводная лодказапускать弹道ракета的функция。
isVisible: if not self.globalTeamTags(includes='弹道导弹技术1')
addGlobalTeamTags: 弹道导弹技术1
isLocked:if not self.globalTeamTags(includes='材料技术2')
isLockedMessage: Требуется материаловедение 2
addResources: energy=1
iconImage: 弹道导弹技术1.png
showMessageToPlayer: Технология баллистических ракет1已经разрабатывать完成
pos: 4
[action_弹道导弹技术2]
text: Технология портативных баллистических ракет
buildSpeed: 125s
price: 6000,energy=1,钍=350
description: -передовой弹道ракета小 化技术，\n-这вид技术может允许将长距离攻击ракета，а также大 反导系统развёртывать至运载车，核подводная лодка，вплоть дотяжёлый бомбардировщик上，\n-地狱之火ракета平 ，«Адская буря»，Амфибийный штурмовой корабль класса «Астролог»，Стратегическая ядерная подлодка класса «Поглощающая Сирена»的前置наука。\n-解锁Заря，Бомбардировщик «Демон»несёткрылатая ракета的способность，解锁Тяжёлая инженерная машина的защита от стратегического оружияспособность。\n-解锁Ракетная база Генезисаt2，解锁天盾ракетаоборона系统тактикаракетаспособность。
isVisible: if not self.globalTeamTags(includes='弹道导弹技术2')
addGlobalTeamTags: 弹道导弹技术2
addResources: energy=1
iconImage: 弹道导弹技术2.png
showMessageToPlayer: Технология портативных баллистических ракет已经разрабатывать完成
pos: 4
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[action_基础科学进步1]
text: Фундаментальная наука1
buildSpeed: 150s
price: 13000,energy=1,钍=500
description: -фундаментальная наука的全面进步，обладать划时代意义的科研，\n-这может让тыиметьГенезиссамый凶悍的юнит，解锁Истребитель «Громовержец»，Воздушный канонёр класса «Мерзость»，\n-Адский гончий。Бедствиекласс重 攻击машина，«Адская буря»，Стратегический бомбардировщик класса «Заря»，Тяжёлый штурмовик класса «Похоронный звон»，\n-Стратегическая ядерная подлодка класса «Поглощающая Сирена»的前置наука。
isLocked: if not self.globalTeamTags(includes='材料技术2') or not self.globalTeamTags(includes='裂变技术1')
isLockedMessage: Требуется технология деления 1和Материаловедение2
isVisible: if not self.globalTeamTags(includes='基础科学进步1')
addGlobalTeamTags: 基础科学进步1
addResources: energy=1
iconImage: 基础科学进步.png
showMessageToPlayer: фундаментальная наука已经取得突破性进展。
pos: 4
ai_isHighPriority: true

[action_超导技术1]
text: Сверхпроводимость 1
buildSpeed: 85s
price: 4000,energy=1,钍=250
description: -Сверхпроводимость是использовать尖端技术а также应用浪人技术的重要先决条вещь，\n-这将позволяетГенезисармияможетнемного安装超导原вещь。\n-这将解锁Передовой，Парящий танк，Лазерная башняt4。该наукаодновременно是Шок-танк，Суперистребитель，\n-Воздушный часовой класса «Галка»，Воздушный канонёр класса «Серафим»，Линейный крейсер класса «Морской волк»的前置наука。
isVisible: if not self.globalTeamTags(includes='超导技术1')
addGlobalTeamTags: 超导技术1
addResources: energy=1
iconImage: 超导技术1.png
showMessageToPlayer: Сверхпроводимость1已经разрабатывать完成
pos: 2
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня

[action_外骨骼技术]
text: Технология экзоскелета
buildSpeed: 55s
price: 8500,energy=1
description: 为союзныйпехота及轻 мех，额外附加的有源экзоскелет及额外护甲系统，\n-способен大幅повышает此类юнит的защитные характеристики及манёвренность，\n-одновременно得益于экзоскелет额外的承重способность，позволяетпехотаможетнесётболее多的броня与防护。\n-将为Бесстрашный боец，Гладиатор，Манипулятор，附加лёгкое укрытиехарактеристика，\n-为Охотник，увеличиваеттяжёлое укрытиехарактеристика，\n-одновременноувеличиваетвсепехотаоснова护甲10点，\n-всепехотасамый大生命值加20%，移动скорость加30%，转向скорость加65%，\n-移动скорость加成的额外数值将不используется для计算衰解减速，Нанокатализатор加速等其он计算。\n-在被衰解时不обеспечивает移动скорость增益。移动скорость增益在与其он移速增益叠加时，将取самый大值。
isVisible: if not self.globalTeamTags(includes='外骨骼')
addGlobalTeamTags: 外骨骼
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/外骨骼.png
showMessageToPlayer: Технология экзоскелета已经разрабатывать完成
pos: 0.001
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[action_强固建筑]
text: Укреплённое здание
buildSpeed: 150s
price: 9000,energy=1,钍=350
description: 为всездание和工事обеспечивает的加固方案，这将在зданиевсе承重住和墙壁中添加额外的加固结构，\n-и安装большое количество的防爆气密 а также自动灭火装置等一系列新鲜玩意，\n-с保证все关键сооружениеможет在敌军самый猛烈的炮火中幸存。\n-升класс后，всездание血量+25%，основа护甲+25%，\n-炮塔，Стена，碉堡则血量+40%。 всездание对стратегическое оружие抗性+40%，\n-всездание每秒恢复50点生命值，Крепостьt2的前置наука。\n-升класс完毕后将立刻ремонтвсе受损здание。
isVisible: if not self.globalTeamTags(includes='强固建筑')
addGlobalTeamTags: 强固建筑
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/建筑加固.png
showMessageToPlayer: Укреплённое здание已经разрабатывать完成
pos: 0.0015
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[action_模块化技术]
text: Модульные технологии
buildSpeed: 75s
price: 5000,energy=1,钍=200
description: 为Альянс Генезис的механический юнитобеспечивает的модульный改造，а также对工厂производствооборудование的全方位优化。\n-Модульные технологии的普及может让некоторыеГенезисюнит在поле боя上进行модифицировать成不同модель的变вид，\n-самый难得можно贵的是，得益于модульный带来的мощный零вещьуниверсальный性，\n-некоторые之前дорогой且难с直接производство的юнит或зданиеможет节околоболее多的производить成本。\n-为Передовой，Атлас运输корабль，Супертанкобеспечивает改造方案（解锁MK2）。\n-允许Казарма一次性训练两个或多个Бесстрашный боец，Шок-пехотинец，Расчёт ракет «Жало»，Боевой мех，Огненный смерч，\n-Десантник со штандартом，Манипулятор。在иметьФундаментальная наука的情况下，\n-Адский гончий，Бедствиекласс重 攻击машина，Воздушный канонёр класса «Мерзость»，Эсминец класса «Молот-Рыба»，Линкор класса «Чёрная Жемчужина»的производить成本уменьшает35%。\n-модульныйпроизводство的优惠价格юнит，а также双倍производство的юнит将不会受домодульный纳米煅炉的производствоскорость增益。\n-将允许Тяжёлая инженерная машина直接строить绝большинство满классздание。
isVisible: if not self.globalTeamTags(includes='模块化技术')
addGlobalTeamTags: 模块化技术
addResources: energy=1
iconImage: ROOT:/创世纪军事集团/单位特效/模块生产.png
showMessageToPlayer: Модульные технологии已经разрабатывать完成
pos: 0.0012
ai_isHighPriority: true
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня

[graphics]
total_frames: 1
image: 科技中心.png
image_wreak: 科技中心死亡.png
image_back: 科技中心背景.png
image_shadow: 影子.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[arm_1]
x: -9
y: -10
image_end: 电梯.png
image_end_teamColors: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_2]
x: 0
y: 0
image_end: 科技中心损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_3]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 

[animation_1]
onActions: idle
blendIn: 1s
blendOut: 2s
arm1_0s: {x:0, y:0}
arm1_4s: {x:0, y:35}
arm1_6s: {x:0, y:35}
arm1_10s: {x:0, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:55
delayedStartTimerRandom:30



[ai]
buildPriority: 0.07
ai_upgradePriority: 0.07
noneGlobalExtraPriority: 0.3
maxEachBase: 50
maxGlobal: 50


