
[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true

[core]
name:鹞鹰无人机
displayText: 鹞鹰无人机
displayDescription: -?
class: CustomUnitMetadata
price: 0
maxHp: 2500
techLevel: 1
canNotBeGivenOrdersByPlayer: true
softCollisionOnAll: 200
radius: 12
explodeOnDeath: false
fogOfWarSightRange: 10
showOnMinimapToEnemies: true
isBio: false
numBitsOnDeath:0
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 7000
energyRegen: -1
dieOnZeroEnergy: true
tags: 飞机,寄生免疫,伴生单位,无人单位
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_zz1]
autoTrigger:if not self.isInMap
addResources: hp= -999999

[action_ax]
autoTrigger: if self.timeAlive(laterThanSeconds=1)	and not self.tags(includes= '部署')
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
temporarilyAddTags: 部署
playAnimation: attack
[decal_喷火]
image: ROOT:/余辉军团/建筑特效/喷火.png
total_frames: 4
frame: (self.customTimer * 30) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:0
yOffsetRelative:-40
isVisible: if self.isMoving()
layer: afterBody
onlyWhileAlive:true
imageScale:0.58
[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE

shadowOffsetX: 1
shadowOffsetY: 1
splastEffect: false


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: true
turretSize: 1
turretTurnSpeed: 250
maxAttackRange: 150
isMelee: true
meleeEngangementDistance: 99999
[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir: 0
shoot_flame: CUSTOM:导弹碎片,CUSTOM:导弹碎片1
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
projectile: 1
size: 0
turnSpeed: 2
aimOffsetSpread: 0


[projectile_1]
@copyFromSection: template_爆炸
speed: 5
targetSpeed: 10
drawSize: 1
image:机体.png
deflectionPower: -1
trailEffectRate: 0.4
trailEffect:true
areaDamage: 6000
areaRadius: 150
nukeWeapon: false
life: 9999
areaDamageNoFalloff: true
explodeEffect: CUSTOM:闪光wyd,CUSTOM:火光wy,CUSTOM:冲击波wyd,CUSTOM:闪光wyd1,CUSTOM:闪光wyd2,CUSTOM:巨大冲击波wyd,CUSTOM:实验,CUSTOM:火星wy*6
explodeEffectOnShield:    CUSTOM:闪光wyd,CUSTOM:火光wy,CUSTOM:冲击波wyd,CUSTOM:闪光wyd1,CUSTOM:闪光wyd2,CUSTOM:巨大冲击波wyd,CUSTOM:实验,CUSTOM:火星wy*6
targetGround:true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.3
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 2
mutator2_directDamageMultiplier: 2
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=20
areaRadiusFromEdge: true
explodeOnEndOfLife:true
lightSize: 0
lightColor:  #FF00B3FF
spawnUnit:铝热剂(addResources=电磁:10)
#————温压弹

[effect_闪光wyd]
image: SHARED:light_50.png
life:240
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
priority: critical
scaleFrom: 13
scaleTo: 17
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true


[effect_火光wy]
priority: critical
image: ROOT:/通用特效/火光y.png
life: 120
fadeOut: true
attachedToUnit: false
scaleFrom: 8.5
scaleTo: 8.5
alwayStartDirAtZero: true
alpha: 0.9
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆燃.wav

[effect_冲击波wyd]
stripIndex: shockwave
life: 45
scaleFrom: 1
scaleTo: 14
alpha: 1


[effect_闪光wyd1]
priority: low
image: SHARED:light_50.png
life: 45
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime:0
scaleFrom: 15
scaleTo: 1
drawUnderUnits: false
atmospheric: false

[effect_闪光wyd2]
image: SHARED:light_50.png
life: 300
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true




[effect_巨大冲击波wyd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 3.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
color: #FF00B3FF



[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/余辉军团/单位特效/火星.png
createWhenZoomedOut: false
life: 130
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 3
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.75
xSpeedRelativeRandom: 0.75
atmospheric: true
xOffsetRelativeRandom:140
yOffsetRelativeRandom:140




[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:60
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:1.5
scaleTo:4.8
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180


[arm_1]
x: -2
y: 0
image_end: 杆子.png
drawOverBody: true
image_end_shadow: SHADOW:杆子.png

[arm_2]
x: 2
y: 0
image_end: 杆子.png
drawOverBody: true
image_end_shadow: SHADOW:杆子.png
[arm_3]
x: -6
y: -4.5
image_end: 左翼.png
drawOverBody: true
image_end_shadow: SHADOW:左翼.png

[arm_4]
x: 6
y: -4.5
image_end: 右翼.png
drawOverBody: true
image_end_shadow: SHADOW:右翼.png

[arm_5]
x: 0
y: 0
image_end: 机体.png
drawOverBody: true
image_end_shadow: SHADOW:机体.png


[animation_attack]

arm1_0s: {x:0, y:0,dir:0}
arm2_0s: {x:0, y:0,dir:0}
arm3_0s: {x:0, y:0,dir:0}
arm4_0s: {x:0, y:0,dir:0}

arm1_1s: {x:-8, y:-10,dir:-45}
arm2_1s: {x:8, y:-10,dir:45}
arm3_1s: {x:-9, y:2.5,dir:55}
arm4_1s: {x:9, y:2.5,dir:-55}



arm1_99999s: {x:-8, y:-10,dir:-45}
arm2_99999s: {x:8, y:-10,dir:45}
arm3_99999s: {x:-9, y:2.5,dir:55}
arm4_99999s: {x:9, y:2.5,dir:-55}


[effect_导弹碎片]
#priority: low
image: 左翼.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative:-1
xSpeedRelativeRandom: -1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 15
xOffsetRelative	: -4
yOffsetRelative: 2
[effect_导弹碎片1]
#priority: low
image: 右翼.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
xSpeedRelative:1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 15
xOffsetRelative	: 4
yOffsetRelative: 2

[movement]
movementType: AIR
moveSpeed: 2.8
moveAccelerationSpeed: 100
moveDecelerationSpeed: 0.008
targetHeight: 70
targetHeightDrift: 2
maxTurnSpeed: 1.8
turnAcceleration: 0.06
#startingHeightOffset: 1000
moveSlidingMode : false
moveIgnoringBody: false
slowDeathFall: false


