


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 安卡拉刚级巡洋舰1
displayText: 安卡拉刚级巡洋舰
showInEditor: false
displayDescription: -安卡拉刚级是古人类太空战舰的典范之作，他几乎见证了整个古人类太空战斗史。\n-安卡拉刚早在古人类第二次大航海中期就已经服役于布恩芬德尔共和国舰队中，并一直被各大势力沿用至今。\n-在那个护盾和粒子武器还未诞生的时代，安卡拉刚是太空中绝对力量的象征，\n-更是布恩芬德尔霸权狂傲的空中王座。虽然在今天安卡拉刚已经十分落后。\n-但由于技术十分简单粗暴，为了能抵御余辉的入侵，太空浪人重新为安卡拉刚加装了粒子武器，\n-并更换了更为先进的反应堆和重置了整个舰体电网，在太空浪人的改造下，安卡拉刚迎来了重生，\n-如今，安卡拉刚级依旧服役于太空浪人舰队中，并续写着布恩芬德尔当年的荣耀与力量。\n-对地对空，多联炮动能伤害，其他能源。激光反掩体。
maxHp: 42500
price: 16000,awz= ${awzxq}

@global awzxq:300
reclaimPrice: awz= ${awzxq}
shieldDisplayOnlyDeflection: true
techLevel: 2
buildSpeed: 70s
selfRegenRate: 0.2
availableInDemo: true
radius: 87
displayRadius: 87

isBio: false
transportSlotsNeeded: 20
#effectOnDeathGroundCollision:CUSTOM:爆炸x*1
tags: 飞机,高空,安卡,反高空
showActionsWithMixedSelectionIfOtherUnitsHaveTag: 安卡
canOnlyBeAttackedByUnitsWithTags:反高空
softCollisionOnAll: 20

armour: 90
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 35
[action_bz]
displayType: action
price: 0
buildSpeed: 5s
isVisible: true
whenBuilding_cannotMove: false
text:降低高度
description: 降低安卡拉刚级护卫舰的高度，使其成为常规空中单位。\n-恢复射程和对地面单位的能力，但失去了攻击高空单位的能力。
iconImage: ROOT:/通用特效/低空.png
allowMultipleInQueue:false
convertTo: 安卡拉刚级巡洋舰
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_高空]
text: 高空单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的战机和战舰。\n-在此高度下，只有地面和空中特殊的反高空单位，以及高空单位才能攻击到该单位，\n-同时，大部分高空单位可以互相攻击，并可以攻击普通空中单位，\n-只有特殊的高空单位才能对地攻击。


[hiddenAction_↯a]
autoTrigger: if self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: 缺少暗物质
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[action_a]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=885) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_b]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=885)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
#imageScale:18
turretImageScale: 0.8

movementEffect: CUSTOM:火,CUSTOM:火1,CUSTOM:火2
movementEffectRate: 1
animation_moving_start: 2
animation_moving_end: 2
animation_moving_speed: 8

animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: if self.resource.awz>-1
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 785
shootDelay: 0


[turret_1]
x: -25
y: -40
image: 主炮.png
canShoot: false
turnSpeed: 1.2

limitingAngle: 40
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空

[turret_2]
x: 5
y: 11
canShoot: true
recoilOffset: -3
projectile: 1

#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50
canOnlyAttackUnitsWithTags:高空
warmup: 0
attachedTo: 1
image: 炮管.png
slave: true
size: 5

canAttackLandUnits: false


[turret_3]
x: -5
y: 11
canShoot: true
recoilOffset: -3
projectile: 1
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 5
attachedTo: 1
image: 炮管.png
slave: true
size: 5

canAttackLandUnits: false


[turret_4]
x: 0
y: 13
canShoot: true
recoilOffset: -3
projectile: 1
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 10
attachedTo: 1
image: 炮管.png
slave: true
size: 12

canAttackLandUnits: false


[turret_5]
x: 25
y: -40
image: 主炮.png
canShoot: false
turnSpeed: 1.2
canOnlyAttackUnitsWithTags:高空
limitingAngle: 40
canAttackLandUnits: false


[turret_6]
x: 5
y: 11
canShoot: true
recoilOffset: -3
projectile: 1
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 0
attachedTo: 5
image: 炮管.png
slave: true
size: 5

canAttackLandUnits: false


[turret_7]
x: -5
y: 11
canShoot: true
recoilOffset: -3
projectile: 1

#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50
canOnlyAttackUnitsWithTags:高空
warmup: 5
attachedTo: 5
image: 炮管.png
slave: true
size: 5

canAttackLandUnits: false


[turret_8]
x: 0
y: 13
canShoot: true
recoilOffset: -3
projectile: 1

#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50
canOnlyAttackUnitsWithTags:高空
warmup: 10
attachedTo: 5
image: 炮管.png
slave: true
size: 12

canAttackLandUnits: false


[turret_9]
x: 43
y: -6
image: 主炮.png
canShoot: false
turnSpeed: 1.2
canOnlyAttackUnitsWithTags:高空
#canAttackLandUnits:false
limitingAngle: 50
idleDir: 35


[turret_10]
x: 5
y: 11
canShoot: true
recoilOffset: -3
projectile: 2
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 0
attachedTo: 9
image: 炮管.png
slave: true
size: 5

#canAttackLandUnits:false


[turret_11]
x: -5
y: 11
canShoot: true
recoilOffset: -3
projectile: 2

#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50
canOnlyAttackUnitsWithTags:高空
warmup: 5
attachedTo: 9
image: 炮管.png
slave: true
size: 5

#canAttackLandUnits:false


[turret_12]
x: 0
y: 13
canShoot: true
recoilOffset: -3
projectile: 2
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 10
attachedTo: 9
image: 炮管.png
slave: true
size: 12

#canAttackLandUnits:false


[turret_13]
x: -43
y: -6
image: 主炮.png
canShoot: false
turnSpeed: 1.2
canOnlyAttackUnitsWithTags:高空
#canAttackLandUnits:false
limitingAngle: 50
idleDir: -35


[turret_14]
x: 5
y: 11
canShoot: true
recoilOffset: -3
projectile: 2
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 0
attachedTo: 13
image: 炮管.png
slave: true
size: 5

#canAttackLandUnits:false


[turret_15]
x: -5
y: 11
canShoot: true
recoilOffset: -3
projectile: 2
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 5
attachedTo: 13
image: 炮管.png
slave: true
size: 5

#canAttackLandUnits:false


[turret_16]
x: 0
y: 13
canShoot: true
recoilOffset: -3
projectile: 2
canOnlyAttackUnitsWithTags:高空
#invisible: true
shoot_sound: ROOT:/余辉军团/单位特效/副炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
delay: 50

warmup: 10
attachedTo: 13
image: 炮管.png
slave: true
size: 12

#canAttackLandUnits:false
#—————————————————————


[turret_17]
invisible: true
x: -38
y: 16
idleDir: -90
projectile: 3
canOnlyAttackUnitsWithTags:高空
size: 0
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 130

canAttackMaxAngle: 181
limitingMinRange: 200
canAttackLandUnits: false


[turret_18]
invisible: true
x: -38
y: 24
idleDir: -90
projectile: 3
canOnlyAttackUnitsWithTags:高空
size: 0
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 130

warmup: 5
canAttackLandUnits: false
canAttackMaxAngle: 181
limitingMinRange: 200


[turret_19]
invisible: true
x: 38
y: 24
idleDir: 90
projectile: 3
canOnlyAttackUnitsWithTags:高空
size: 0
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 130

warmup: 10
canAttackLandUnits: false
canAttackMaxAngle: 181
limitingMinRange: 200


[turret_20]
invisible: true
x: 38
y: 16
idleDir: 90
projectile: 3
canOnlyAttackUnitsWithTags:高空
size: 0
canAttackLandUnits: false
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5

delay: 130
warmup: 15
canAttackMaxAngle: 181
limitingMinRange: 200
#—————————————


[turret_21]
x: 18
y: 91.5
image: 炮.png
#canShoot: false
limitingAngle: 80

projectile: 4
delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200

aimOffsetSpread: -0.01
size: 12
idleDir: 90


[turret_22]
x: -18
y: 91.5
image: 炮.png
#canShoot: false
limitingAngle: 80

projectile: 4
delay: 0.2
shoot_sound: ROOT:/太空浪人/单位特效/激光.ogg
shoot_sound_vol: 0.45
shoot_light: #FFFF1200

aimOffsetSpread: -0.01
size: 12
idleDir: -90


[turret_23]
x: 0
y: 120
limitingMinRange: 180
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/大主炮音效.ogg
canOnlyAttackUnitsWithTags:高空
recoilOffset: -5
warmupStartEffect: CUSTOM:气浪,CUSTOM:粒子*2
recoilOutTime: 5
recoilReturnTime: 30
projectile: 5

image: 炮1.png
warmup: 40
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
delay: 200
limitingAngle: 40

size: 18


[projectile_1]
@copyFromSection: template_动能
areaDamage: 190
areaRadius: 50
life: 300
#lightSize:1

explodeEffect: CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光
speed: 10
#trailEffect:CUSTOM:尾巴1
drawSize: 0.7

image: ROOT:/太空浪人/单位特效/中子弹.png
#deflectionPower:-1
#trailEffectRate:4
areaRadiusFromEdge: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_2]
@copyFromSection: template_动能
areaDamage: 190
areaRadius: 50
life: 200
speed: 10

image: ROOT:/太空浪人/单位特效/光束.png
targetSpeed: 10
drawSize: 0.88
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光

#targetGround:true
areaRadiusFromEdge: true
lightSize: 0.75
trailEffectRate: 0.9
trailEffect: CUSTOM:尾巴

lightColor: #FFFF1200
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_3]
@copyFromSection: template_能源
life: 350
speed: 5
targetSpeed: 9
largeHitEffect: true

drawSize: 0.5
image: ROOT:/太空浪人/单位特效/光.png
directDamage: 100
deflectionPower: -1
explodeEffect: CUSTOM:闪光,CUSTOM:溅射

explodeEffectOnShield: CUSTOM:闪光,CUSTOM:溅射
autoTargetingOnDeadTarget: true
#spawnProjectilesOnEndOfLife:锁定
turnSpeed: 4
trailEffectRate: 0.01

trailEffect: CUSTOM:尾巴1
lightColor: #FFFF1200


[projectile_4]
@copyFromSection: template_能源
directDamage: 21
instantReuseLast: true
life: 10
instant: true

laserEffect: true
explodeEffect: CUSTOM:闪光1
explodeEffectOnShield: CUSTOM:闪光1
lightSize: 0.75
#beamImage:ROOT:/太空浪人/单位特效/光束3.png

color: #FFFF1200
beamImage: SHARED:beam3.png
beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_5]
@copyFromSection: template_能源
areaDamage: 3750
areaRadius: 60
life: 300
lightSize: 1

largeHitEffect: true
speed: 7
#targetGround:true
trailEffect: CUSTOM:尾巴2
drawSize: 0.7

explodeEffectOnShield: CUSTOM:聚变,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:底色
explodeEffect: CUSTOM:聚变,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:底色
image: ROOT:/太空浪人/单位特效/星星1.png
deflectionPower: -1
trailEffectRate: 2

areaRadiusFromEdge: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[effect_闪光1]
life: 5
spawnChance: 0.9
priority: critical
attachedToUnit: false
scaleFrom: 0.45

scaleTo: 0.45
image: ROOT:/太空浪人/单位特效/光束1.png
dirOffsetRandom: 180


[effect_溅射]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.1
image: ROOT:/太空浪人/单位特效/自制2.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
animateFramePingPong: false
animateFrameSpeed: 0.3

alpha: 1.2


[effect_尾巴1]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 11
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false


[effect_尾巴]
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.37
scaleTo: 0.37
alpha: 1

drawUnderUnits: true


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.5

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
color: #FFFF1200


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_火]
life: 35
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.15
xOffsetRelative	: -46
yOffsetRelative	: -78


[effect_火1]
life: 35
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 7

scaleTo: 2
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.15
xOffsetRelative	: 46
yOffsetRelative	: -78


[effect_火2]
life: 40
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 12

scaleTo: 3
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.1
xOffsetRelative	: 0
yOffsetRelative	: -120


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 1.8
scaleTo: 1.8
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_底色]
priority: critical
image: ROOT:/太空浪人/单位特效/收缩2.png
life: 140
fadeOut: true
attachedToUnit: false

scaleFrom: 0.5
scaleTo: 0.5
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光x]
#priority:critical
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 6
scaleTo: 6

drawUnderUnits: true
atmospheric: false


[effect_尾巴2]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false

fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.5
alpha: 0.8
drawUnderUnits: false

#yOffsetRelative	:-5


[effect_冲击波]
#priority:critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.4
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_气浪]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
#color: #FFFF1200
fadeOut: true
attachedToUnit: true
#color:#FFE56BFF

#color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9

drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedRelative: 1
atmospheric: true


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: true

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[arm_1]
x: -24.5
y: -33
image_end: 左后.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: 24.5
y: -33
image_end: 右后.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: -24
y: 91.5
image_end: 左前.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 24
y: 91.5
image_end: 右前.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_5]
x: 0
y: 133.5
image_end: 头.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
#image_end_shadow:SHADOW:3.png


[arm_6]
x: 0
y: 0
image_end: 遮盖2.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_7]
x: 0
y: 0
image_end: 遮盖1.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(lessThan=8125)


[arm_8]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(lessThan=17875)


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:-20}
arm1_950s: {x:0, y:-20}
arm2_1s: {x:0, y:-20}

arm2_950s: {x:0, y:-20}
arm3_1s: {x:14, y:0}
arm3_950s: {x:14, y:0}
arm4_1s: {x:-14, y:0}
arm4_950s: {x:-14, y:0}

arm5_1s: {x:0, y:-25}
arm5_950s: {x:0, y:-25}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}

arm4_1s: {x:0, y:0}
arm5_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 0.8
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
maxTurnSpeed: 1
turnAcceleration: 0.05
targetHeightDrift: 0.3

slowDeathFall: false
targetHeight: 140


[ai]
buildPriority: 0.9


