


[core]
name: 通用战略武器
displayText: Универсальное стратегическое оружие
class: CustomUnitMetadata
price: 0
maxHp: 10
armour: 999989

techLevel: 2
radius: 0
displayRadius: 0
armourMinDamageToKeep: 0
#showInEditor: false

hideScorchMark: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
isUnselectable: true
isBio: false
showOnMinimap:false
energyMax: 1
energyRegen: 0
dieOnZeroEnergy: true
explodeOnDeath: false

[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[resource_电磁]
displayName: Электромагнит
displayNameShort: Электромагнит
displayColor: #FF9D00FF
priority: 1
hidden: true

[resource_小电磁]
displayName: Малый электромагнит
displayNameShort: Малый электромагнит
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_温压弹]
displayName: ОДБ
displayNameShort: ОДБ
displayColor: #FF9D00FF
priority: 1
hidden: true
[action_爆炸]
autoTrigger: if self.timeAlive(laterThanSeconds=0.1) and self.resource.电磁<0.5 and self.resource.小电磁<0.5 and self.resource.温压弹<0.5
isVisible: false
addResources: energy=-1
fireTurretXAtGround: 爆炸
fireTurretXAtGround_withOffset: 0,0
[action_爆炸1]
autoTrigger: if self.timeAlive(laterThanSeconds=0.1) and self.resource.小电磁>0.5
isVisible: false
addResources: energy=-1
fireTurretXAtGround: 爆炸1
fireTurretXAtGround_withOffset: 0,0
[action_爆炸2]
autoTrigger: if self.timeAlive(laterThanSeconds=2) and self.resource.温压弹>0.5
isVisible: false
addResources: energy=-1
fireTurretXAtGround: 爆炸2
fireTurretXAtGround_withOffset: 0,0
[action_爆炸3]
autoTrigger: if self.timeAlive(laterThanSeconds=0.1) and self.resource.电磁>0.5
isVisible: false
addResources: energy=-1
fireTurretXAtGround: 爆炸3
fireTurretXAtGround_withOffset: 0,0
[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 200

aimOffsetSpread: 0
shootDelay: 1


[turret_爆炸]
x: 0
y: 0
canShoot: false
warmup: 600
projectile: 1

turnSpeedAcceleration: 999
[turret_爆炸1]
x: 0
y: 0
canShoot: false
warmup: 600
projectile: 2
#5500
turnSpeedAcceleration: 999
[turret_爆炸2]
x: 0
y: 0
canShoot: false
warmup: 600
projectile: 3
#5500
turnSpeedAcceleration: 999
[turret_爆炸3]
x: 0
y: 0
canShoot: false
warmup: 600
projectile: 4
#5500
turnSpeedAcceleration: 999
[projectile_1]
@copyFromSection: template_能源,template_战略武器
life: 999
instant: true
areaDamage: 18000
areaRadius: 200

targetGround: true
image: NO.png
drawSize: 1
deflectionPower: -1
areaRadiusFromEdge: true

areaHitAirAndLandAtSameTime: false
explodeEffect:   CUSTOM:实验,CUSTOM:闪光nk,CUSTOM:聚变nk,CUSTOM:云雾2nk*2,CUSTOM:云雾1nk*2,CUSTOM:云雾nk*2,CUSTOM:冲击波nk,CUSTOM:冲击波nk1,CUSTOM:冲击波nk2,CUSTOM:冲击波nk3,CUSTOM:聚变nk1,CUSTOM:光球1nk,CUSTOM:光球nk,CUSTOM:高闪nk
buildingDamageMultiplier: 1.5
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=12
[projectile_2]
life: 999
instant: true
areaDamage: 100
areaRadius: 100
targetGround: true
image: NO.png
drawSize: 1
deflectionPower: -1
areaRadiusFromEdge: true
areaDamageNoFalloff: true
areaHitAirAndLandAtSameTime: false
shieldDamageMultiplier: 30
armourIgnoreAmount: 99999
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: xk= 3
explodeEffect: CUSTOM:电磁remp*8,CUSTOM:电磁remp1*6
targetGround_includeTargetHeight:true
[projectile_3]
@copyFromSection: template_爆炸
areaDamage: 5000
areaRadius: 150
nukeWeapon: false
deflectionPower: -1
life: 999
speed: 99
instant: true
drawSize:0
areaDamageNoFalloff: true
explodeEffect: CUSTOM:闪光wyd,CUSTOM:火光wy,CUSTOM:冲击波wyd,CUSTOM:闪光wyd1,CUSTOM:闪光wyd2,CUSTOM:巨大冲击波wyd,CUSTOM:红闪光,CUSTOM:实验,CUSTOM:火星wy*6
explodeEffectOnShield:    CUSTOM:闪光wyd,CUSTOM:火光wy,CUSTOM:冲击波wyd,CUSTOM:闪光wyd1,CUSTOM:闪光wyd2,CUSTOM:巨大冲击波wyd,CUSTOM:红闪光,CUSTOM:实验,CUSTOM:火星wy*6
targetGround:true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.3
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 2
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.6
mutator7_areaDamageMultiplier: 0.6
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=20
areaRadiusFromEdge: true
explodeOnEndOfLife:true

[projectile_4]
life: 999
instant: true
areaDamage: 1000
areaRadius: 300
targetGround: true
image: NO.png
drawSize: 1
deflectionPower: -1
areaRadiusFromEdge: true
areaDamageNoFalloff: true
areaHitAirAndLandAtSameTime: false
shieldDamageMultiplier: 99999
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: xk= 10
explodeEffect: CUSTOM:底色emp,CUSTOM:火光emp,CUSTOM:聚变emp,CUSTOM:闪光emp,CUSTOM:闪光emp1, CUSTOM:冲击波emp, CUSTOM:冲击波dn, CUSTOM:粒子emp*12,CUSTOM:电磁emp*10,CUSTOM:电磁emp1*7,CUSTOM:实验
targetGround_includeTargetHeight:true
[effect_聚变nk]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 3.2
scaleTo: 3.2
alpha: 0.6
drawUnderUnits: false
atmospheric: false
showInFog: true
createWhenOffscreen: true
[effect_闪光nk]
priority: high
image: SHARED:light_50.png
life: 300
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 14
scaleTo: 14
drawUnderUnits: true
atmospheric: false
showInFog: true
[effect_冲击波nk]
life: 100
priority: high
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 4
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_冲击波nk1]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 4
alpha: 0.8
showInFog: true
drawUnderUnits: false
atmospheric: true
createWhenOffscreen: true
#——————@——————看NM，给👴爬


[effect_光球nk]
life: 350
priority: critical
attachedToUnit: false
scaleFrom: 0.7
scaleTo: 1.4
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
ySpeedAbsolute: -0.5
fadeOut: true
alpha: 0.85
showInFog: true
alsoPlaySound: 巨炮爆炸.wav
createWhenOffscreen: true
delayedStartTimer:5
fadeInTime:5
[effect_光球1nk]
life: 350
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.68
image: 大光球.png
ySpeedAbsolute: -0.5
#drawUnderUnits:true
#yOffsetAbsolute:35
fadeOut: true
showInFog: true
alpha: 0.7
createWhenOffscreen: true
delayedStartTimer:5
fadeInTime:5
[effect_云雾nk]
life: 620
priority: veryhigh
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.45
image: 云雾.png
ySpeedAbsolute: -0.5
ySpeedAbsoluteRandom: -0.2
#yOffsetAbsolute:90
fadeOut: true
alpha: 1
showInFog: true
fadeInTime: 1
createWhenOffscreen: true
[effect_云雾1nk]
life: 660
priority: veryhigh
attachedToUnit: false
scaleFrom: 0.35
scaleTo: 0.2
ySpeedAbsoluteRandom: -0.15
image: 云雾.png
ySpeedAbsolute: -0.35
#yOffsetAbsolute:90
fadeOut: true
alpha: 1
showInFog: true
fadeInTime: 1
createWhenOffscreen: true

[effect_云雾2nk]
life: 630
priority: veryhigh
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.15
image: 云雾.png
ySpeedAbsolute: -0.2
showInFog: true
#yOffsetAbsolute:90
fadeOut: true
alpha: 1
fadeInTime: 1
ySpeedAbsoluteRandom: -0.1
createWhenOffscreen: true


[effect_聚变nk1]
image: ROOT:/通用特效/火光.png
life: 180
fadeOut: true
attachedToUnit: false
alpha: 0.9
drawUnderUnits: false
atmospheric: false
showInFog: true
#yOffsetAbsolute:35
scaleFrom: 3
scaleTo: 14
ySpeedAbsolute: -0.5
color: #FFFFF44C
alwayStartDirAtZero: true
createWhenOffscreen: true
[effect_冲击波nk2]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波3.png
life: 150
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.1
alpha: 0.7
drawUnderUnits: true
atmospheric: false
#yOffsetAbsolute:90
showInFog: true
createWhenOffscreen: true
[effect_冲击波nk3]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波4.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.2
alpha: 0.8
drawUnderUnits: true
atmospheric: false
#yOffsetAbsolute:90
showInFog: true
createWhenOffscreen: true
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:60
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:1.5
scaleTo:4.8
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
dirOffsetRandom:180
[effect_高闪nk]
priority: high
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 2
attachedToUnit: false
color:#FFFFF44C
#fadeInTime: 2
scaleFrom: 18
scaleTo: 2
drawUnderUnits: true
atmospheric: false
showInFog: true
#——————————————



#————————————————————————电磁脉冲
[effect_火光emp]
priority: critical
image: 火光.png
life: 200
fadeOut: true
attachedToUnit: false
scaleFrom: 4
scaleTo: 4
alwayStartDirAtZero: true
color: #FF00B3FF
alpha: 0.9
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_底色emp]
priority: critical
image: 光球z.png
life: 90
fadeOut: true
attachedToUnit: false
scaleFrom: 0.32
scaleTo: 0.32
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
createWhenOffscreen: true
[effect_聚变emp]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 2
alpha: 0.6
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
[effect_闪光emp]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 18
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_闪光emp1]
image: SHARED:light_50.png
life: 150
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
priority: critical
createWhenOffscreen: true
[effect_粒子emp]
spawnChance: 1
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: false
#color: #FFFFFF
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom: 0.3
scaleTo: 0.3
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 9
ySpeedRelativeRandom: 9
xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
[effect_电磁emp]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.45
drawUnderUnits: false
scaleFrom: 4
scaleTo: 4
xOffsetRelativeRandom:250
yOffsetRelativeRandom:250
createWhenOffscreen: true
delayedStartTimerRandom:20
[effect_电磁emp1]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: ROOT:/通用特效/电弧.png
total_frames: 8
animateFrameStart:1
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 0.85
drawUnderUnits: false
scaleFrom: 0.85
scaleTo:0.85
xOffsetRelativeRandom:120
yOffsetRelativeRandom:120
createWhenOffscreen: true
delayedStartTimerRandom:30
[effect_冲击波emp]
life: 60
priority: high
attachedToUnit: false
scaleFrom: 2
scaleTo: 6
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
color: #FF00B3FF
showInFog: true
drawUnderUnits: true
alpha:0.8
createWhenOffscreen: true
[effect_冲击波dn]
life: 70
priority: high
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_电磁remp]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.8
drawUnderUnits: false
scaleFrom: 2
scaleTo: 2
xOffsetRelativeRandom:60
yOffsetRelativeRandom:60
createWhenOffscreen: true
delayedStartTimerRandom:20
color: #FFFF1200
[effect_电磁remp1]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: ROOT:/通用特效/红电弧.png
total_frames: 8
animateFrameStart:1
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 0.85
drawUnderUnits: false
scaleFrom: 0.93
scaleTo:0.93
xOffsetRelativeRandom:60
yOffsetRelativeRandom:60
createWhenOffscreen: true
delayedStartTimerRandom:15
#————温压弹
[effect_红闪光]
image: SHARED:light_50.png
life: 300
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFF86
priority: critical
fadeInTime: 2
scaleFrom: 5.5
scaleTo: 3
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波wyd]
stripIndex: shockwave
life: 45
scaleFrom: 1
scaleTo: 14
alpha: 1
[effect_闪光wyd1]
priority: low
image: SHARED:light_50.png
life: 45
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF5B18
fadeInTime:0
scaleFrom: 15
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_巨大冲击波wyd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 3.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_闪光wyd2]
image: SHARED:light_50.png
life: 600
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_闪光wyd]
image: SHARED:light_50.png
life:240
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF5B18
fadeInTime: 2
priority: critical
scaleFrom: 13
scaleTo: 17
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_火光wy]
priority: critical
image: ROOT:/通用特效/火光.png
life: 120
fadeOut: true
attachedToUnit: false
scaleFrom: 8.5
scaleTo: 8.5
alwayStartDirAtZero: true
color: #FFFF5B18
alpha: 0.9
drawUnderUnits: false
atmospheric: false
alsoPlaySound: 爆燃.wav
[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 130
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 3
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.75
xSpeedRelativeRandom: 0.75
atmospheric: true
xOffsetRelativeRandom:140
yOffsetRelativeRandom:140
[effect_震动]
createWhenOffscreen:true
drawType: displacement

image:ROOT:/通用特效/震动.png
life:120
fadeOut: false
fadeInTime:50
attachedToUnit: true

scaleFrom:40
scaleTo:40
alpha:0.035
drawUnderUnits:false
alwayStartDirAtZero: true
total_frames: 2
animateFrameStart: 0
animateFrameEnd:1
animateFrameSpeed: 0.3
animateFrameLooping:true
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 0
targetHeight: -6
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true


