


[core]
name: 恐怖地雷
displayText: 恐怖地雷
class: CustomUnitMetadata
price: 0
maxHp: 5
canNotBeDamaged:true
techLevel: 1
buildSpeed: 0.035
#availableInDemo: true
radius: 20
displayRadius: 20
hideScorchMark: true
numBitsOnDeath: 15
tags: 地雷,不能回收
isBio: false
softCollisionOnAll: 100
energyMax: 5000

energyRegen: -1
dieOnZeroEnergy: true
fogOfWarSightRange: 5
selfBuildRate: 0.01
disableAllUnitCollisions: true
showOnMinimapToEnemies: false


isBuilding: true
canOnlyBeAttackedByUnitsWithTags:主动扫雷
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
deleteSelf:true
[action_拆除]
displayType: action
iconImage: ROOT:/通用特效/关.png
text: 拆除
description: 拆除地雷
buildSpeed: 0s
highPriorityQueue: true
displayRemainingStockpile: false
deleteSelf: true


[hiddenAction_扫雷]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=50)  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.hasFlag(id=1)
deleteSelf: true
[action_显示]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=300) and not self.tags(includes= '显示')
isVisible:false
temporarilyAddTags:显示
[action_显示1]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',lessThan=1,withInRange=300) and self.tags(includes= '显示')
isVisible:false
temporarilyRemoveTags:显示

[decal_光圈]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈1]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈2]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈3]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈a]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈b]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈c]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:true
hOffset:8
onlyTeam:own
[decal_地雷]
layer: afterBody
image:  ROOT:/创世纪军事集团/单位特效/榴弹.png
onlyWhileAlive: true
imageScale:0.8
isVisible:true
onlyTeam:own
[decal_地雷1]
layer: afterBody
image:  ROOT:/创世纪军事集团/单位特效/榴弹.png
onlyWhileAlive: true
imageScale:0.8
isVisible:if self.tags(includes= '显示')
onlyTeam:enemy

[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 1
dustEffect: false
showEnergyBar:false


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: true

canOnlyAttackUnitsWithoutTags: 扫雷,建筑
turretSize: 10
turretTurnSpeed: 6
maxAttackRange: 300
shootDelay: 1

#aimOffsetSpread: 0.25


[turret_1]
x: 0
y: 0
invisible: true
projectile: 1
turnSpeed: 15

turnSpeedAcceleration: 15
canShoot: true
warmup: 300
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3


[projectile_1]
@copyFromSection: template_爆炸
life: 999
areaDamage: 350
areaRadius: 50
speed: 3

targetSpeed: 7
largeHitEffect: true
ballistic: true
ballistic_height: 70
frame: 4

drawSize: 1
alwaysVisibleInFog: true
shouldRevealFog: true
lightColor: #FFEEEE00
lightSize: 2.5

trailEffect: true
areaRadiusFromEdge: true
targetGround: true
explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator32_ifUnitWithTags: 悬浮
mutator32_directDamageMultiplier: 0
mutator32_areaDamageMultiplier: 0
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.3

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/建筑特效/地雷音效.ogg
alwayStartDirAtZero: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
targetHeight: -8
targetHeightDrift: 0
moveSlidingMode : true
moveIgnoringBody: true


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


