


[core]
name: 恐怖地雷升级
displayText: 恐怖地雷
class: CustomUnitMetadata
price: 0
maxHp: 5

techLevel: 1
buildSpeed: 0.035
#availableInDemo: true
radius: 20
displayRadius: 20
hideScorchMark: true
numBitsOnDeath: 15
tags: 地雷,反高空,不能回收
isBio: false
softCollisionOnAll: 100
energyMax: 5000
showOnMinimapToEnemies: false
energyRegen: -1
dieOnZeroEnergy: true
fogOfWarSightRange: 5
selfBuildRate: 0.01
disableAllUnitCollisions: true
canNotBeDamaged:true
isBuilding: true
canOnlyBeAttackedByUnitsWithTags:主动扫雷
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
deleteSelf:true
[action_拆除]
displayType: action
iconImage: ROOT:/通用特效/关.png
text: 拆除
description: 拆除地雷
buildSpeed: 0s
highPriorityQueue: true
displayRemainingStockpile: false
deleteSelf: true
[decal_光圈a]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈b]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈c]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:true
hOffset:8
onlyTeam:own
[action_显示]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=300) and not self.tags(includes= '显示')
isVisible:false
temporarilyAddTags:显示
[action_显示1]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',lessThan=1,withInRange=300) and self.tags(includes= '显示')
isVisible:false
temporarilyRemoveTags:显示

[decal_光圈]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈1]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈2]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈3]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.15
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_地雷]
layer: afterBody
image:  雷.png
onlyWhileAlive: true
imageScale:0.8
isVisible:true
onlyTeam:own
[decal_地雷1]
layer: afterBody
image:  雷.png
onlyWhileAlive: true
imageScale:0.8
isVisible:if self.tags(includes= '显示')
onlyTeam:enemy



[hiddenAction_扫雷]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=50)  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.hasFlag(id=1)
deleteSelf: true


[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 1
dustEffect: false
showEnergyBar:false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: true
canOnlyAttackUnitsWithoutTags: 扫雷,建筑
turretSize: 10
turretTurnSpeed: 6
maxAttackRange: 425
shootDelay: 1

#aimOffsetSpread: 0.25
turretMultiTargeting: true

[turret_1]
x: 0
y: 0
invisible: true
projectile: 1
turnSpeed: 15

turnSpeedAcceleration: 15
canShoot: true
warmup: 150
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
canAttackFlyingUnits: false
[turret_2]
x: 0
y: 0
invisible: true
projectile: 2
turnSpeed: 15

turnSpeedAcceleration: 15
canShoot: true
warmup: 150
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
canAttackFlyingUnits: true
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空
[projectile_1]
@copyFromSection: template_爆炸
life: 999

areaDamage: 850
areaRadius: 50
speed: 3
targetSpeed: 14
largeHitEffect: true
ballistic: true
ballistic_height: 70
image:ROOT:/创世纪军事集团/单位特效/小导弹.png
drawSize: 0.8
alwaysVisibleInFog: true
shouldRevealFog: true
lightColor: #FFEEEE00
lightSize: 2.5
trailEffect: true
areaRadiusFromEdge: true
targetGround: true
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator32_ifUnitWithTags: 悬浮
mutator32_directDamageMultiplier: 0
mutator32_areaDamageMultiplier: 0
[projectile_2]
@copyFromSection: template_爆炸
life: 999

areaDamage: 850
areaRadius: 50
speed: 3
targetSpeed: 7
largeHitEffect: true
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 95
image:ROOT:/创世纪军事集团/单位特效/小导弹.png
drawSize: 0.8
alwaysVisibleInFog: true
shouldRevealFog: true
lightColor: #FFEEEE00
lightSize: 2.5
trailEffect: true
areaRadiusFromEdge: true
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸,CUSTOM:闪光,CUSTOM:冲击波
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.33
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
alwayStartDirAtZero: true
[effect_闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 1.1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_钢珠]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 2
scaleTo: 2.5
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
targetHeight: -8
targetHeightDrift: 0
moveSlidingMode : true
moveIgnoringBody: true


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


