


[core]
name: 光翼战斗机1
displayText: Истребитель «Световое крыло»
displayDescription: -«Световое крыло» был стандартным истребителем Альфрида и участвовал во всех войнах Альфрида.\n-Благодаря передовому оружию и новаторскому изменяемому крылу, до Империи Нова он был самым передовым истребителем.\n-Однако из-за поражения в боях с Империей Нова «Световое крыло» был массово уничтожен. После основания Империи\n-«Световое крыло» был побеждён новым истребителем «Охотник» и в итоге был забыт.\n-В последующих тяжёлых боях с Заревом семья Бояс воссоздала этот истребитель для Скитальцев.\n-По сей день он остаётся основным истребителем авиации Скитальцев, и стоит отметить, что истребитель «Кровавое крыло» Генезиса создан на его основе.\n-Атакует землю и воздух. В режиме ПВО — кинетический урон, в режиме атаки земли — энергетический.
class: CustomUnitMetadata
price: 2000

maxHp: 2000
armour: 5
techLevel: 1
buildSpeed: 11s
availableInDemo: true
fogOfWarSightRange: 22
radius: 32
selfRegenRate: 0.2
showInEditor: false
displayRadius: 32
isBio: false

copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 10
tags: 飞机,低空
transportSlotsNeeded: 1
energyMax: 4

energyRegen: 0.04
energyNeedsToRechargeToFull: true


[action_a]
convertTo: 光翼战斗机
displayType: action
price: 0
text: Режим истребителя
buildSpeed: 1s

clearAllWaypoints: true
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署
description: Сложить обратные стреловидные крылья и перейти на наводящий лазер, очень эффективный против воздушных юнитов.\n-Режим истребителя атакует только воздух, повышены дальность и скорость.
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: Броня «Сегмента» 1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_爆散2]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: Детонационная боеголовка 2
isActive: false
isVisible: if self.globalTeamTags(includes='爆散2')


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
animation_moving_start: 2

animation_moving_end: 2
animation_moving_speed: 8
image_shadow: NONE
animation_idle_start: 0
animation_idle_end: 1

animation_idle_speed: 3
shadowOffsetX: 0
shadowOffsetY: 0
imageScale: 0.85
movementEffect: CUSTOM:火,CUSTOM:火1,CUSTOM:火2

movementEffectRate: 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 1

turretTurnSpeed: 2.5
isFixedFiring: true
maxAttackRange: 260


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-120
projectile: 13
delay: 120

size: 0
#limitingRange:280
attachedTo: 0
slave: true

[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_0]
x: 0
y: 0
invisible: true
canShoot: false


[turret_1]
attachedTo: 0
slave: true
x: 20
y: 0
invisible: true

shoot_sound: ROOT:/太空浪人/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
projectile: 1
delay: 4

energyUsage: 0.5
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')


[turret_2]
attachedTo: 0
slave: true
x: -20
y: 0
invisible: true

shoot_sound: ROOT:/太空浪人/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFF1200
projectile: 1
delay: 4

energyUsage: 0.5
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')


[projectile_1]
@copyFromSection: template_能源
life: 350
speed: 8
targetSpeed: 8
largeHitEffect: true

drawSize: 0.8
image: ROOT:/太空浪人/单位特效/光束.png
directDamage: 38
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光

#autoTargetingOnDeadTarget: true
#spawnProjectilesOnEndOfLife:锁定
lightColor: #FFFF1200


[projectile_炮弹]
@copyFromSection: template_爆炸
life: 350
speed: 8
targetSpeed: 8
largeHitEffect: true

drawSize: 1
image: ROOT:/太空浪人/单位特效/光束0.png
areaDamage: 35
areaRadiusFromEdge: true
areaRadius: 35

explodeEffect: CUSTOM:爆炸b, CUSTOM:闪光b,CUSTOM:闪电b
explodeEffectOnShield: CUSTOM:爆炸b, CUSTOM:闪光b,CUSTOM:闪电b
#autoTargetingOnDeadTarget: true
#spawnProjectilesOnEndOfLife:锁定
color: #FF68FF2E

spawnProjectilesOnExplode: m2*2


[projectile_m2]
@copyFromSection: template_爆炸
areaDamage: 35
areaRadius: 35
life: 6661
image: ROOT:/太空浪人/单位特效/光束0.png

speed: 200
targetSpeed: 200
drawSize: 0
areaRadiusFromEdge: true
explodeEffect: CUSTOM:波雷爆炸b

targetGround: true
targetGroundSpread: 65
lightColor: #FF68FF2E


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: -15
yOffsetRelative	: -37


[effect_火1]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 15
yOffsetRelative	: -37


[effect_火2]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -37


[effect_爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.8
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[arm_1]
x: -18
y: -7
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true
image_end_shadow: SHADOW:左.png
drawDirOffset: -60


[arm_2]
x: 18
y: -7
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true
image_end_shadow: SHADOW:右.png
drawDirOffset: 60


[arm_3]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true
drawUnderAllUnits: false
lockMovement: true
image_end_shadow: SHADOW:遮盖.png

[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm1_1s: {x:-7, y:-17, dir:60}
arm2_1s: {x:7, y:-17, dir:-60}

#—————————————


[effect_闪光b]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_闪电b]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.6

drawUnderUnits: false
scaleFrom: 1.8
scaleTo: 2.3
color: #FF68FF2E


[effect_爆炸b]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/太空浪人/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
#color:#FFFF1200
alsoPlaySound: ROOT:/太空浪人/单位特效/爆散.ogg


[effect_波雷爆炸b]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.3
image: ROOT:/太空浪人/单位特效/波雷爆炸1.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 2

#alsoPlaySound:  ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02
joinsGroupFormations: false

maxTurnSpeed: 2.3
turnAcceleration: 1
moveSlidingMode : true
moveIgnoringBody: true
slowDeathFall: true

targetHeight: 70


[ai]
buildPriority: 0.085


