


[core]
name: 光翼战斗机
displayText: Истребитель «Световое крыло»
displayDescription: -光翼曾是亚尔佛里德标准战斗机，参与过所有亚尔佛里德的战争，\n-光翼战机凭借其先进的武器和新颖的可变翼，在诺瓦帝国之前是最先进的战机。\n-不过，因为和诺瓦帝国战斗的失利导致光翼战机被大量摧毁，帝国建国后，\n-光翼更是被全新的猎杀者战机击败，最终惨遭遗弃。\n-在之后与余辉艰苦卓绝的战斗中，伯亚斯家族为太空浪人再次复刻了这款战机。\n-至今仍是太空浪人空军中主力战机，值得一提的是，创世纪血翼战机是在他的基础上改造的。\n-对地对空。对空模式动能，对地模式能源
class: CustomUnitMetadata
price: 2000
maxHp: 2000

armour: 5
techLevel: 1
buildSpeed: 14s
availableInDemo: true
radius: 32
fogOfWarSightRange: 22
selfRegenRate: 0.2
displayRadius: 32
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 10

tags: 飞机,低空
transportSlotsNeeded: 1
energyMax: 4
energyRegen: 0.01
energyNeedsToRechargeToFull: true


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: Броня «Сегмента» 1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_a]
convertTo: 光翼战斗机1
displayType: action
price: 0
text: Режим штурмовика
buildSpeed: 1s

clearAllWaypoints: true
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署
description: Раскрыть крылья и перейти в режим обратной стреловидности, одновременно сменив наводящий лазер на плазменно-импульсную пушку.\n-Режим штурмовика атакует только землю, дальность и скорость снижены.
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_爆散2]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: Детонационная боеголовка 2
isActive: false
isVisible: if self.globalTeamTags(includes='爆散2')


[graphics]
total_frames: 3
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
animation_moving_start: 2

animation_moving_end: 2
animation_moving_speed: 8
image_shadow: NONE
animation_idle_start: 0
animation_idle_end: 1

animation_idle_speed: 3
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.85
movementEffect: CUSTOM:火,CUSTOM:火1,CUSTOM:火2

movementEffectRate: 1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 10000
maxAttackRange: 375


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-120
projectile: 13
delay: 120

size: 0


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_1]
invisible: true
x: 20
y: 0
idleDir: 0
projectile: 1

size: 1.1
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 60

canAttackMaxAngle: 181
limitingMinRange: 100
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')


[turret_2]
invisible: true
x: -20
y: 0
idleDir: 0
projectile: 1

size: 1.1
turnSpeed: 0
shoot_sound: ROOT:/太空浪人/单位特效/激光音效.ogg
shoot_sound_vol: 0.5
delay: 60

canAttackMaxAngle: 181
limitingMinRange: 100
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='爆散2')


[projectile_1]
@copyFromSection: template_动能
life: 350
speed: 5
targetSpeed: 9
largeHitEffect: true

drawSize: 0.6
image: ROOT:/太空浪人/单位特效/光.png
trailEffect: CUSTOM:尾巴
areaDamage: 175
deflectionPower: -1

areaRadiusFromEdge: true
areaRadius: 28
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:溅射
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:溅射
autoTargetingOnDeadTarget: true

#spawnProjectilesOnEndOfLife:锁定
turnSpeed: 5
trailEffectRate: 0.01
lightColor: #FFFF1200


[projectile_炮弹]
@copyFromSection: template_爆炸
life: 350
speed: 5
targetSpeed: 9
largeHitEffect: true

drawSize: 0.5
image: ROOT:/太空浪人/单位特效/大炮弹1.png
areaDamage: 135
deflectionPower: -1
areaRadiusFromEdge: true

areaRadius: 60
explodeEffect: CUSTOM:爆炸x, CUSTOM:闪光x,CUSTOM:溅射x,CUSTOM:粒子b*6
explodeEffectOnShield: CUSTOM:爆炸x, CUSTOM:闪光x,CUSTOM:溅射x,CUSTOM:粒子b*6
autoTargetingOnDeadTarget: true
#spawnProjectilesOnEndOfLife:锁定

turnSpeed: 5
trailEffectRate: 0.01
trailEffect: CUSTOM:尾巴x
#lightColor:#FFFF1200
spawnProjectilesOnExplode: m2(yOffsetRelative= 20)
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_m2]
@copyFromSection: template_爆炸
life: 1
deflectionPower: -1
explodeOnEndOfLife: true
speed: 0

turnSpeed: 0.0
areaDamage: 40
areaRadius: 40
areaRadiusFromEdge: true
#targetGround: true

invisible: true
explodeEffect: CUSTOM:爆炸b1
explodeEffectOnShield: CUSTOM:爆炸b1
spawnProjectilesOnCreate: m2(recursionLimit=6, yOffsetRelative= 20)
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[effect_爆炸x]
priority: critical
image: ROOT:/太空浪人/单位特效/收缩3.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.35
scaleTo: 0.35
alpha: 1.3
drawUnderUnits: false
atmospheric: false


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: -15
yOffsetRelative	: -37


[effect_火1]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 15
yOffsetRelative	: -37


[effect_火2]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/红火1.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -37


[effect_尾巴x]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束5.png
life: 18
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 18
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.3
alpha: 0.7

drawUnderUnits: false


[effect_溅射]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.8
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9

#alsoPlaySound:  ROOT:/余辉军团/单位特效/波雷爆炸.ogg
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: true
atmospheric: false


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.48
scaleTo: 0.48
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
atmospheric: false


[effect_溅射x]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.44
scaleTo: 0.44
image: ROOT:/太空浪人/单位特效/爆散.png
total_frames: 9

animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.5
alpha: 0.8

#color:#FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[arm_1]
x: -25
y: -24
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true
image_end_shadow: SHADOW:左.png


[arm_2]
x: 25
y: -24
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

drawUnderAllUnits: false
lockMovement: true
image_end_shadow: SHADOW:右.png


[arm_3]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true
image_end_shadow: SHADOW:遮盖.png
drawUnderAllUnits: false
lockMovement: true


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm1_1s: {x:7, y:17, dir:-60}
arm2_1s: {x:-7, y:17, dir:60}


[effect_爆炸b1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2

image: ROOT:/太空浪人/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
#color:#FFFF1200


[effect_粒子b]
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子.png
scaleFrom: 0.1
scaleTo: 0.3

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2

ySpeedRelativeRandom: 2.2
#atmospheric: true


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: AIR
moveSpeed: 3.2
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.02
joinsGroupFormations: false

maxTurnSpeed: 2.7
turnAcceleration: 0.06
moveSlidingMode : false
moveIgnoringBody: false
slowDeathFall: true

targetHeight: 70


[ai]
buildPriority: 0.085


