


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=100


[core]
name: SDD地狱之龙展开
displayText: SDD Адский Дракон (развёрнут)
maxShield: 2700
shieldRegen: 0.07
class: CustomUnitMetadata

price: 2500,蓝晶=250
maxHp: 1500
armour: 12
displayDescription: -Заревовсегоэто может будеттеИмперия Новатолькоостановкав бумагана  безумиеустановкарасчётизменитьдля реальный, \n-Империя Новасумеркигод , когда , закрытьк под одинэрабоймашина разработкарасчётразрезподъёмна расписание, \n-"то естьможет захватитьвзятьконтрольвоздушныйправо,  также имеет против корабльбомбардировкаможет сила."это этотбоймашинаустановкарасчёт указыватьзначок, \n-тольконе этотпунктисследованиетолько тогдатолько чтооткрытьначало, Империя Новатогдазападнявходит одинкусокбойогонь в .\n-после, Заревоодинокийстоятьзакончитьстать этотбоймашина открытьвыпуститьи большой масштабрядоснащатьвойска.\n-Когда темятежсмотретьк тоттолькохранениев к чертёжна  боймашина, чтобы наводнениевода силак самсвойрывокприходит , когда , \n-Адский Драконэтотштимя, также поэтому, а рождениеи мощьдрожьвосемьнаправление.\n-Адский Драконэто Заревотехнология сокровище, уничтожитьистребитель и военный корабльвсе не в словапод , \n-Адский Драконодновременнотакже это звездазонав самыйможет бояться "огромныйкорабльохотарука".\n-по земле и воздуху, энергетический урон, оружиеусиленный урон по щитам, может развернуть.
techLevel: 1

buildSpeed: 17s
availableInDemo: true
radius: 44
displayRadius: 44
showInEditor: false
mass: 9999999 
isBio: false
shieldRenderRadius: 50
softCollisionOnAll: 10
energyMax: 2.5
fogOfWarSightRange: 24
energyRegen: 0.02
energyNeedsToRechargeToFull: true
tags: 飞机,低空,无人单位
copyFrom: ROOT:/通用特效/单位防护.ini


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_裂解炮2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/裂解炮2.png
text: расщеплениепушка2
isActive: false
isVisible: if self.globalTeamTags(includes='裂解炮2')


[action_重子兵器2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重子2.png
text: барионное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='重子2')


[action_a]
convertTo: SDD地狱之龙
displayType: action
price: 0
text: контрольвоздушныймодель тип
buildSpeed: 1s

isVisible: true
whenBuilding_cannotMove: true
description: убратьглавное орудие, тяжёлый новый запускиспользует двойнойоснащатьрасстояниемладшийимпульс и позади толкатьвустройство.
whenBuilding_playAnimation: 部署
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)


[graphics]
total_frames: 3
image: 身体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.9
animation_moving_start: 0
animation_moving_end: 1

animation_moving_speed: 3
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 4
maxAttackRange: 420
isFixedFiring: true
turretRotateWithBody: true


[turret_1]
x: 0
y: -6
canShoot: false


[turret_2]
x: 0
y: 37
attachedTo: 1
slave: true
projectile: 1

delay: 120
shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/等离子音效.ogg
shoot_sound_vol: 0.7

warmup: 60
warmupStartEffect: CUSTOM:气浪,CUSTOM:粒子*2
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
canAttackCondition: if not self.globalTeamTags(includes='重子2')


[turret_3]
x: 0
y: 37
projectile: 2
shoot_sound: NONE
shoot_sound_vol: 0.3

shoot_flame: NONE
shoot_light: #FFEEEEEE
canShoot: true
delay: 120
warmup: 60

attachedTo: 1
slave: true
invisible: true
canAttackCondition: if not self.globalTeamTags(includes='重子2')


[turret_4]
x: 0
y: 37
projectile: 2
shoot_sound: NONE
shoot_sound_vol: 0.3

delay: 120
warmup: 60
shoot_flame: NONE
shoot_light: #FFEEEEEE
canShoot: true

attachedTo: 1
slave: true
invisible: true
canAttackCondition: if not self.globalTeamTags(includes='重子2')


[turret_炮台1]
x: 0
y: 37
attachedTo: 1
slave: true
projectile: 炮弹1

delay: 240
shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/等离子音效.ogg
shoot_sound_vol: 0.7

warmup: 60
warmupStartEffect: CUSTOM:气浪,CUSTOM:粒子*2
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
canAttackCondition: if self.globalTeamTags(includes='重子2')
canAttackFlyingUnits: false
[turret_炮台2]
x: 0
y: 37
copyFrom: 炮台1
canAttackLandUnits: false
projectile: 炮弹2
canAttackFlyingUnits: true
[projectile_1]
@copyFromSection: template_能源
directDamage: 1700
life: 20
instant: true
laserEffect: true

explodeEffect: CUSTOM:爆炸, CUSTOM:闪光*2,CUSTOM:聚变,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光*2,CUSTOM:聚变,CUSTOM:冲击波
areaRadiusFromEdge: true
lightSize: 0.75
trailEffectRate: 1.5

trailEffect: CUSTOM:尾巴1
color: #FF00B3FF


[projectile_2]
lightingEffect: true
directDamage: 0
life: 20
instant: true
trailEffect: true

speedSpread: 1
lightSize: 0


[projectile_炮弹1]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
spawnUnit: 迷你黑洞*1
life: 300

lightSize: 1
largeHitEffect: true
speed: 10
trailEffect: CUSTOM:尾巴
drawSize: 0.4

image: ROOT:/余辉军团/单位特效/黑洞.png
deflectionPower: -1
trailEffectRate: 0.5
[projectile_炮弹2]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
spawnUnit: 迷你黑洞空中(offsetHeight=70)
life: 300

lightSize: 1
largeHitEffect: true
speed: 10
trailEffect: CUSTOM:尾巴
drawSize: 0.4

image: ROOT:/余辉军团/单位特效/黑洞.png
deflectionPower: -1
trailEffectRate: 0.5

[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
#priority:low

color: #FF000000
fadeInTime: 2
scaleFrom: 1
scaleTo: 1
alpha: 1

drawUnderUnits: true


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 40
fadeOut: true
attachedToUnit: false

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
scaleFrom: 1.3
scaleTo: 0.1

alpha: 2
drawUnderUnits: false
atmospheric: false


[effect_粒子]
life: 40
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 1.3
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2

scaleTo: 2
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5

drawUnderUnits: false
atmospheric: false


[effect_尾巴1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.6
scaleTo: 1.6
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[arm_1]
x: -8
y: 58
image_end: 左.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:左.png
lockMovement: true
#drawUnderAllUnits:true


[arm_2]
x: 8
y: 58
image_end: 右.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:右.png
lockMovement: true
#drawUnderAllUnits:true


[arm_3]
x: -16
y: 52
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:左翼.png
lockMovement: true
#drawUnderAllUnits:true


[arm_4]
x: 16
y: 52
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:右翼.png
lockMovement: true
#drawUnderAllUnits:true


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm1_0.5s: {x:0, y:-13, dir:0}
arm2_0.5s: {x:0, y:-13, dir:0}
arm3_0.5s: {x:0, y:-7, dir:0}
arm4_0.5s: {x:0, y:-7, dir:0}
arm1_1s: {x:3, y:-13, dir:0}

arm2_1s: {x:-3, y:-13, dir:0}
arm3_1s: {x:5, y:-7, dir:0}
arm4_1s: {x:-5, y:-7, dir:0}


[movement]
movementType: AIR
moveSpeed: 0
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.17
maxTurnSpeed: 3.2

turnAcceleration: 0.15
targetHeight: 70
moveSlidingMode: true
moveIgnoringBody: true
moveSlidingDir: 181

startingHeightOffset: 2000
slowDeathFall: true
reverseSpeedPercentage: 0


[ai]
buildPriority: 0.085


