


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=100


[core]
name: SDD地狱之龙
displayText: SDDАдский Дракон
maxShield: 2500
shieldRegen: 0.07
class: CustomUnitMetadata
price: 2700,蓝晶=250

maxHp: 1500
armour: 12
displayDescription: -Заревовсегоэто может будеттеИмперия Новатолькоостановкав 纸на  безумиеустановкарасчётизменитьдля реальный, \n-Империя Нова暮год , когда , закрытьк под одинэрабоймашина разработкарасчётразрезподъёмна 日程, \n-"то естьможет захватитьвзятьконтрольвоздушныйправо,  также имеет против корабльбомбардировкаможет сила."это этотбоймашинаустановкарасчёт указывать标, \n-тольконе этотпунктисследованиетолько тогдатолько чтооткрытьначало, Империя Новатогдазападнявходит одинкусокбойогонь в .\n-после, Зарево独стоятьзакончитьстать этотбоймашина открытьвыпуститьи большой масштабрядоснащатьвойска.\n-Когда те叛乱смотретьк тоттолькохранениев к чертёжна  боймашина, чтобы наводнениевода силак самсвойрывокприходит , когда , \n-Адский Драконэтотштимя, также поэтому, а рождениеи 威дрожьвосемьнаправление.\n-Адский Драконэто Заревотехнология 瑰宝, уничтожитьистребитель и военный корабльвсе не в 话под , \n-Адский Драконодновременнотакже это звездазонав самыйможет бояться "огромныйкорабльохотарука".\n-по земле и воздуху, энергетический урон, оружиеусиленный урон по щитам, может развернуть.\n-Тип проекта:ИмперияЗарево 米добродетельдобавитьдобродетельрасчётразрезданные
techLevel: 1
buildSpeed: 17s

availableInDemo: true
radius: 44
displayRadius: 44
isBio: false
shieldRenderRadius: 50
fogOfWarSightRange: 22
softCollisionOnAll: 10
energyMax: 2.5
energyRegen: 0.02
energyNeedsToRechargeToFull: true

tags: 飞机,低空,无人单位
copyFrom: ROOT:/通用特效/单位防护.ini


[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_裂解炮2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/裂解炮2.png
text: расщеплениепушка2
isActive: false
isVisible: if self.globalTeamTags(includes='裂解炮2')


[action_重子兵器2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重子2.png
text: барионное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='重子2')


[action_a]
convertTo: SDD地狱之龙展开
displayType: action
price: 0
text: развернутьглавное орудие
buildSpeed: 1s

#isVisible:if not self.isOverLiquid
clearAllWaypoints: true
whenBuilding_cannotMove: true
whenBuilding_playAnimation: 部署
description: развернутьвнутриразмещение протонное копьёантиброняогоньпушка, \n-но это для стабильныйснарядпуть и даватьглавное орудиеобеспечиватьможет , \n-позади толкатьвустройство и защитавоздушныйоружиебудетзапретиспользует .\n-огоньпушкакаждыйразатакапротив одиночныйштврагистроить стать 1500очкоэнергетический урон, \n-по земле и воздуху.
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[graphics]
total_frames: 3
image: 身体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 1
shadowOffsetY: 1
#imageScale:0.9
animation_moving_start: 2
animation_moving_end: 2

animation_moving_speed: 8
animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3
movementEffect: CUSTOM:火

movementEffectRate: 0.8


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 4
maxAttackRange: 370
isFixedFiring: true
turretRotateWithBody: true


[turret_1]
x: 0
y: -6
canShoot: false


[turret_2]
x: -30
y: 5
attachedTo: 1
slave: true
projectile: 1

delay: 2
shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/小激光.ogg
shoot_sound_vol: 0.7

energyUsage: 0.07
canAttackCondition: if not self.globalTeamTags(includes='裂解炮2')


[turret_3]
x: 30
y: 5
attachedTo: 1
slave: true
projectile: 1

delay: 2
shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/小激光.ogg
shoot_sound_vol: 0.7

energyUsage: 0.07
canAttackCondition: if not self.globalTeamTags(includes='裂解炮2')


[turret_炮台1]
x: -30
y: 5
attachedTo: 1
slave: true
projectile: 炮弹1

delay: 10
shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.7

energyUsage: 0.415
canAttackCondition: if self.globalTeamTags(includes='裂解炮2')


[turret_炮台2]
x: 30
y: 5
attachedTo: 1
slave: true
projectile: 炮弹1

delay: 10
shoot_light: #FF00B3FF
shoot_flame: NONE
shoot_sound: ROOT:/余辉军团/单位特效/主炮音效.ogg
shoot_sound_vol: 0.7

energyUsage: 0.415
canAttackCondition: if self.globalTeamTags(includes='裂解炮2')


[projectile_1]
@copyFromSection: template_能源
directDamage: 30
life: 100
speed: 8
targetSpeed: 9

image: ROOT:/余辉军团/单位特效/长炮弹.png
deflectionPower: -1
drawSize: 0.55
lightSize: 0.6
lightColor: #FF00B3FF

explodeEffect: CUSTOM:爆炸
explodeEffectOnShield: CUSTOM:爆炸
shieldDamageMultiplier: 2


[projectile_炮弹1]
@copyFromSection: template_动能
directDamage: 300
life: -1
lightSize: 1
largeHitEffect: true

speed: 8
trailEffect: CUSTOM:尾巴
drawSize: 0.8
explodeEffectOnShield: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:穿透,CUSTOM:爆炸c
explodeEffect: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:穿透,CUSTOM:爆炸c

image: ROOT:/余辉军团/单位特效/子弹2.png
trailEffectRate: 2
spawnProjectilesOnEndOfLife: 炮弹2


[projectile_炮弹2]
@copyFromSection: template_动能, projectile_炮弹1
directDamage: 270
life: 300
# 坑蒙拐骗ing


[arm_1]
x: -5
y: 45
image_end: 左.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:左.png
lockMovement: true
#drawUnderAllUnits:true


[arm_2]
x: 5
y: 45
image_end: 右.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:右.png
lockMovement: true
#drawUnderAllUnits:true


[arm_3]
x: -11
y: 45
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:左翼.png
lockMovement: true
#drawUnderAllUnits:true


[arm_4]
x: 11
y: 45
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: false

image_end_shadow: SHADOW:右翼.png
lockMovement: true
#drawUnderAllUnits:true


[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/粗子弹1.png
life: 30
fadeOut: true
attachedToUnit: false

#color:#FFFFFF3D
fadeInTime: 0.1
scaleFrom: 0.17
scaleTo: 0.17
alpha: 0.6

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_爆炸]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.4
image: ROOT:/余辉军团/单位特效/碎裂.png
total_frames: 8

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_火]
life: 18
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4.5

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -62


[effect_闪光b]
priority: critical
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFFFF3D
fadeInTime: 2
scaleFrom: 2
scaleTo: 2

drawUnderUnits: false
atmospheric: false


[effect_爆炸b]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.8
image: ROOT:/余辉军团/单位特效/自制1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg


[effect_爆炸c]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 1.8

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_穿透]
priority: high
image: ROOT:/余辉军团/单位特效/子弹2.png
life: 35
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.6
scaleTo: 0.6
alpha: 1
drawUnderUnits: false

ySpeedRelative: 4.5
atmospheric: true


[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm1_0.5s: {x:0, y:13, dir:0}
arm2_0.5s: {x:0, y:13, dir:0}
arm3_0.5s: {x:0, y:7, dir:0}
arm4_0.5s: {x:0, y:7, dir:0}
arm1_1s: {x:-3, y:13, dir:0}

arm2_1s: {x:3, y:13, dir:0}
arm3_1s: {x:-5, y:7, dir:0}
arm4_1s: {x:5, y:7, dir:0}


[movement]
movementType: AIR
moveSpeed: 2.35
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.17
maxTurnSpeed: 3.2

turnAcceleration: 0.15
targetHeight: 70
moveSlidingMode: true
moveIgnoringBody: true
moveSlidingDir: 181

startingHeightOffset: 2000
slowDeathFall: true
reverseSpeedPercentage: 0


[ai]
buildPriority: 0.085


