


[core]
name: 幼蛛
displayDescription: 【阶级t4】【机械单位】【地面单位】【无人单位】【伴随式无人机】【伴生单位】\n-战术定位:护卫机器人，无法被运输。武器配置：▲机关炮X1 只能对地 动能伤害\n-▲反坦克导弹发射仓X1 只能对地 爆炸伤害 ▲防空火箭1 对空对高空 爆炸伤害 \n-▲防空导弹垂发单元X1 对空对高空 爆炸伤害\n-幼蛛是专门为大型作战单位配有的重装无人作战单元。\n-幼蛛配有强悍的武器阵列，能为黑寡妇肃清绝大部分威胁，\n-并与母体相互掩护达到最佳战斗效能。\n-不过幼蛛没有内置燃油或反应堆，只能通过无线充电原理，\n-从附近的无人作战指挥单位身上获得能量，\n-离母体太远会造成破坏性停机，请注意。
price: 1500
maxHp: 7000
fogOfWarSightRange: 23
techLevel: 1
buildSpeed: 7s
radius: 28
armour: 8
isBio: false

softCollisionOnAll: 28
canNotBeGivenOrdersByPlayer: true
tags: 地面,镇压者,寄生免疫,反高空,伴生单位
unitsSpawnedOnDeath: 损毁2*1
copyFrom: ROOT:/通用特效/单位防护.ini

energyMax: 30
energyRegen: 0
dieOnZeroEnergy: false
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_s1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999
[action_先进目标定位核心1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位1.png
text: 先进目标定位核心1
isActive: false
isVisible: if self.globalTeamTags(includes='目标定位1')
[hiddenAction_目标定位生效]
autoTrigger: if self.globalTeamTags(includes='目标定位1')
setUnitStats: maxAttackRange= ${attack.maxAttackRange*1.35},fogOfWarSightRange= ${core.fogOfWarSightRange*1.35}
[action_聚变弹头3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变3.png
text: 聚变弹头3
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头3')
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: 恐怖地雷1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1')

[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=685) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=685)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[hiddenAction_1]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=780) and self.resource.xk < 1
addWaypoint_target_nearestUnit_tagged: 地面,飞机
addWaypoint_type: attackmove
addWaypoint_target_nearestUnit_team: enemy




[hiddenAction_21]
autoTrigger: if not self.hasUnitInTeam(withTag='暴君', withinRange=300) and self.resource.xk < 1
isVisible: false
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: 暴君
addWaypoint_target_nearestUnit_team: own
addWaypoint_maxTime: 1s
addWaypoint_type: move


[action_t1]
autoTrigger: if self.noUnitInTeam(withTag='暴君', withinRange=450)
isVisible: false
addResources: energy=-0.5


[action_t1xx]
autoTrigger: if self.hasUnitInTeam(withTag='暴君', withinRange=450)
isVisible: false
addResources: energy=5

[hiddenAction_321]
autoTrigger: if not self.hasUnitInTeam(withTag='暴君', withinRange=450) and self.energy<10
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: 暴君
addWaypoint_target_nearestUnit_team: own
addWaypoint_maxTime: 1s
addWaypoint_type: move
[action_tz1]
autoTrigger: if self.noUnitInTeam(withTag='暴君', withinRange=450) and self.energy<1
isVisible: false
addResources: hp=-400
[graphics]
total_frames: 1
image: NO.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 44

turretTurnSpeed: 4
maxAttackRange: 900
turretRotateWithBody: true
shootDelay: 100
turretMultiTargeting: true


[turret_1]
x: 0
y: 0
idleDir: 0
turnSpeed: 2.9
turnSpeedAcceleration: 0.3

canShoot: false


[turret_2]
x: -24
y: 27
attachedTo: 1
image: 主炮.png
projectile: 1

turnSpeed: 2.9
turnSpeedAcceleration: 0.3
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾*3,CUSTOM:枪口火焰,CUSTOM:弹壳左

shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -5
recoilOutTime: 2
recoilReturnTime: 15

canAttackFlyingUnits: false
slave: true
size: 45
delay: 20
limitingRange: 585

[turret_3]
x: 30
y: 14
projectile: 3
attachedTo: 1
slave: true

invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:烟雾1*4
shoot_light: #FFEECCCC
canShoot: true
canAttackFlyingUnits: false
size: 0
delay: 120
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
limitingRange: 585
[turret_4]
x: 0
y: -6.5
invisible: true
canAttackLandUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg

shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾1*4
shoot_light: #FFEECCCC
projectile: 2
attachedTo: 1

size: 0
turnSpeed: 811
warmup: 40
delay: 40
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')

[turret_5]
x: -18
y: 5
projectile: 4
attachedTo: 1
slave: true

size: 0
shoot_sound: missile_fire
shoot_sound_vol: 0.3
shoot_light: #FFEEEE00
shoot_flame: NONE

delay: 30
canAttackLandUnits: false
limitingRange: 585

[projectile_1]
@copyFromSection: template_动能
#主炮子弹
directDamage: 225
life: 60
speed: 7.5

color: #FFFFFF73
drawSize: 0.8
largeHitEffect: true
lightSize: 0.8
frame: 8

lightColor: #FFFFFF73


[projectile_2]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85

image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 100

ballistic_delaymove_height: 80
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1


[projectile_锁定]
@copyFromSection: template_爆炸
directDamage: 1500
life: 200
speed: 5
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
targetSpeed: 9
drawSize: 0.85

areaRadiusFromEdge: true
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波

[projectile_3]
@copyFromSection: template_爆炸
directDamage: 600
life: 250
speed: 7
image: ROOT:/创世纪军事集团/单位特效/导弹.png

drawSize: 0.8
trailEffect: true
lightSize: 0.75
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波

explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波
[projectile_炮弹]
@copyFromSection: template_能源
directDamage: 900
life: 250
speed: 7
image: ROOT:/创世纪军事集团/单位特效/导弹.png
drawSize: 0.8
trailEffect: true
lightSize: 0.75
lightColor: #FFFFFF73
explodeEffect: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波x
explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波x
[projectile_炮弹1]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85

image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 100

ballistic_delaymove_height: 80
spawnProjectilesOnEndOfLife: 锁定x
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1


[projectile_锁定x]
@copyFromSection: template_能源
directDamage: 2550
life: 200
speed: 5
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
targetSpeed: 9
drawSize: 0.85
areaRadiusFromEdge: true
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波x
explodeEffectOnShield: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波x

[projectile_4]
@copyFromSection: template_爆炸
directDamage: 120
life: 666
speed: 2
targetSpeed: 6
#drawSize:	0.8
frame: 4
trailEffect: true
largeHitEffect: true
wobbleAmplitude: 3
wobbleFrequency: 60
turnSpeed: 30


[leg_1]
x: -26
y: 30
attach_x: -3
attach_y: 7
moveSpeed: 2

rotateSpeed: 6
heightSpeed: 0.4
resetAngle: 22
image_leg: 腿.png
image_foot: 脚.png

holdDisMin: 6
holdDisMax: 18
endDirOffset: -45
hardLimit: 30
hidden: if self.hasParent()


[leg_2]
x: 26
y: 30
attach_x: 3
attach_y: 7
copyFrom: 1

endDirOffset: 45
hidden: if self.hasParent()


[leg_3]
x: -26
y: -22
attach_x: -3
hidden: if self.hasParent()
attach_y: 1

copyFrom: 1
endDirOffset: -135


[leg_4]
x: 26
y: -22
attach_x: 3
attach_y: 1
copyFrom: 1

endDirOffset: 135
hidden: if self.hasParent()


[arm_1]
x: 0
y: -6.5
image_end: 井.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: 0
y: -6.5
image_end: 盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: 0
y: 0
image_end: 身体.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm2_1s: {x:0, y:25}
arm2_950s: {x:0, y:25}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm2_1s: {x:0, y:0}


[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.5

scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3

atmospheric: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 3
scaleTo: 3


[effect_弹壳左]
priority: high
image: ROOT:/通用特效/弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.7
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
ySpeedRelative: -1.5
xSpeedRelative: 0.1
ySpeedRelativeRandom: 0.2
yOffsetRelative: -83
xOffsetRelative: -3

hSpeed: 3.7
dirSpeedRandom: 50


[effect_烟雾1]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 100
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.3
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true


[effect_冲击波]
life: 110
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false

scaleFrom: 1.2
scaleTo: 2.4
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2

createWhenOverLiquid: false
createWhenOverLand: true


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.8
scaleTo: 2

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false

atmospheric: false
#——————————！
[effect_底色]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.4
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_闪光x]
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 1
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_冲击波x]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 33
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[movement]
movementType: OVER_CLIFF
moveSpeed: 1.2
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1
maxTurnSpeed: 1.2

turnAcceleration: 0.8
moveSlidingMode: false
moveIgnoringBody: false


