


[core]
name: 超大火坑
displayText: 超大火坑
class: CustomUnitMetadata
price: -100
maxHp: 10
armour: 999989
techLevel: 2
radius: 0
showInEditor:false
displayRadius: 0
armourMinDamageToKeep: 0
hideScorchMark: true
disableAllUnitCollisions: true
isBio: false
canNotBeDirectlyAttacked: true
isUnselectable: true
energyMax: 24
#energyRegen: 0
energyRegen: -0.018
energyStartingPercentage: 1
dieOnZeroEnergy: true
fogOfWarSightRange: 25
explodeOnDeath: false
isBuilding: true
autoTriggerCooldownTime:0.04s
autoTriggerCooldownTime_allowDangerousHighCPU:true
showOnMinimap:false
#每秒触发25次
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_s1]
autoTrigger: if self.isOverLiquid and self.energy<0.1
isVisible: false
deleteSelf: true

[action_s2]
autoTrigger: if self.resource.1>0.5 and self.energy<0.1
isVisible: false
deleteSelf: true


[hiddenAction_火]
autoTrigger: if self.resource.1>0.5
spawnEffects: CUSTOM:闪光s,CUSTOM:上火1水s*2,CUSTOM:上火1s*2,CUSTOM:烟雾s
fireTurretXAtGround: 炎
fireTurretXAtGround_withOffset: 0,0



[hiddenAction_火焰区]
autoTrigger: if self.energy>16 and self.resource.1<0.5
spawnEffects: CUSTOM:闪光,CUSTOM:上火1水*2,CUSTOM:上火1*3,CUSTOM:烟雾
fireTurretXAtGround: 火
fireTurretXAtGround_withOffset: 0,0

[hiddenAction_火焰区1]
autoTrigger: if self.energy>4 and  self.energy<16 and self.resource.1<0.5
spawnEffects: CUSTOM:闪光,CUSTOM:上火1水*2,CUSTOM:上火1*2,CUSTOM:烟雾
fireTurretXAtGround: 火
fireTurretXAtGround_withOffset: 0,0

[hiddenAction_火焰区21]
autoTrigger: if self.energy<4 and self.resource.1<0.5
spawnEffects: CUSTOM:闪光,CUSTOM:上火1水,CUSTOM:烟雾
fireTurretXAtGround: 火
fireTurretXAtGround_withOffset: 0,0
[decal_弹坑]
image:坑.png
total_frames: 1
layer: shadow
isVisible:if not self.isOverLiquid and self.resource.1<0.5
imageScale: 3
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_弹坑1]
image:坑.png
total_frames: 1
layer: shadow
isVisible:if not self.isOverLiquid and self.resource.1<0.5
imageScale: 3
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_闪光3]
image:52.png
total_frames: 1
layer: shadow
isVisible:if self.resource.1<0.5
imageScale: 22
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/24
[decal_闪光4]
image:52.png
total_frames: 1
layer: shadow
isVisible:if self.resource.1<0.5
imageScale: 22
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/24

#——————————————
[decal_弹坑s]
image:坑.png
total_frames: 1
layer: shadow
isVisible:if not self.isOverLiquid and self.resource.1>0.5
imageScale: 1.3
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_闪光s]
image:52.png
total_frames: 1
layer: shadow
isVisible:if self.resource.1>0.5
imageScale: 9
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:(self.energy)/24
[graphics]
total_frames: 1
image:ROOT:/通用特效/NO.png
image_wreak: 坑.png
image_turret: NONE
image_shadow: NONE
imageScale: 3
icon_zoomed_out_neverShow:true
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 150

aimOffsetSpread: 0
shootDelay: 1
turretMultiTargeting: true
[turret_火]
#死眼
x:0
y:0
invisible: true
projectile: 1
turnSpeed: 15
turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true
[turret_炎]
x: 0
y: 0
copyFrom: 火
projectile: 2
[projectile_1]
@copyFromSection: template_战略武器
areaDamage: 16
areaRadius: 300
areaRadiusFromEdge: true
life: 1
invisible: true
speed: 0
targetGround: true
drawSize: 0
lightSize: 0
explodeOnEndOfLife:true
explodeEffect:NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true
armourIgnoreAmount: 1000
mutator7_ifUnitWithTags: 建筑
mutator7_directDamageMultiplier:10
mutator7_areaDamageMultiplier: 10
mutator74_ifUnitWithTags: 步兵
mutator74_directDamageMultiplier:10
mutator74_areaDamageMultiplier: 10


[projectile_2]
@copyFromSection: template_战略武器
areaDamageNoFalloff: true
areaDamage:76
areaRadius: 80
speed: 0
life: 1
instant: true
largeHitEffect: false
explodeOnEndOfLife: true
deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
#——————————————
[effect_闪光s]
priority: low
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 0.8
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
xOffsetRelativeRandom:70
yOffsetRelativeRandom:70
alsoPlaySound: ROOT:/通用特效/燃烧.ogg
[effect_上火1水s]
life: 100
priority: critical
stripIndex: effects
frameIndex: 0
fadeInTime: 4
scaleFrom:3
scaleTo: 6
atmospheric: true
dirOffsetRandom: 180
shadow: true
alpha: 1.33
liveAfterAttachedDies: true
createWhenZoomedOut: true
fadeOut: true
attachedToUnit: true
drawUnderUnits: false
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
xOffsetRelativeRandom:70
yOffsetRelativeRandom:70
delayedStartTimerRandom:30
createWhenOverLiquid: true
createWhenOverLand: false
[effect_上火1s]
life: 100
atmospheric: true
priority: veryhigh
scaleFrom: 0.15
scaleTo: 0.55
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
liveAfterAttachedDies: true
createWhenZoomedOut: true
fadeInTime: 1
fadeOut: true
attachedToUnit: true
alpha: 0.6
hSpeed: 0.46
hOffsetRandom: 0.1
drawUnderUnits: false
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xOffsetRelativeRandom:55
yOffsetRelativeRandom:55
delayedStartTimerRandom:30
[effect_烟雾s]
priority: low
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true
life: 120
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
createWhenZoomedOut: true
scaleFrom: 0.2
scaleTo: 0.4
alpha: 0.8
drawUnderUnits: false
hSpeed: 0.77
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom:60
yOffsetRelativeRandom:60
delayedStartTimerRandom:30
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
#——————————————

[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 0.8
attachedToUnit: false
color:#FFFFF44C
fadeInTime: 2
scaleFrom: 11
scaleTo: 1
drawUnderUnits: true
atmospheric: false
createWhenOffscreen: true
showInFog: true
xOffsetRelativeRandom:200
yOffsetRelativeRandom:200
alsoPlaySound: ROOT:/通用特效/燃烧.ogg

[effect_烟雾]
priority: low
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true
life: 200
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
createWhenZoomedOut: true
scaleFrom: 0.3
scaleTo: 0.6
alpha: 0.8
drawUnderUnits: false
hSpeed: 0.77
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom:200
yOffsetRelativeRandom:200
delayedStartTimerRandom:30
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_上火1]
life: 100
atmospheric: true
priority: veryhigh
scaleFrom: 0.4
scaleTo: 0.85
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
liveAfterAttachedDies: true
createWhenZoomedOut: true
fadeInTime: 1
fadeOut: true
attachedToUnit: true
alpha: 0.6
hSpeed: 0.46
hOffsetRandom: 0.1
drawUnderUnits: false
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xOffsetRelativeRandom:200
yOffsetRelativeRandom:200
delayedStartTimerRandom:30
[effect_上火1水]
life: 100
priority: critical
stripIndex: effects
frameIndex: 0
fadeInTime: 4
scaleFrom:6
scaleTo: 10
atmospheric: true
dirOffsetRandom: 180
shadow: true
alpha: 1.33
liveAfterAttachedDies: true
createWhenZoomedOut: true
fadeOut: true
attachedToUnit: true
drawUnderUnits: false
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xOffsetRelativeRandom:220
yOffsetRelativeRandom:220
delayedStartTimerRandom:30
createWhenOverLiquid: true
createWhenOverLand: false
[resource_1]
displayName: 1
displayNameShort: 1
displayColor: #FF9D00FF
priority: 1
hidden: true
[movement]
movementType: AIR
moveSpeed: 1
maxTurnSpeed: 1
targetHeight: -1
targetHeightDrift: 0

moveSlidingMode: true
moveIgnoringBody: true


