


[core]
name: 轨道空爆中介
displayText: 轨道空爆中介
price: -9999
maxHp: 5
techLevel: 1
buildSpeed: 0s
radius: 0
displayRadius: 0
numBitsOnDeath: 0
fogOfWarSightRange: 0
isBio: false
softCollisionOnAll: 100
isBuilding: true
energyMax: 1
explodeOnDeath: false
hideScorchMark: true
energyRegen: -1
dieOnZeroEnergy: true
canNotBeGivenOrdersByPlayer: true
disableAllUnitCollisions: true
canNotBeDamaged: true
isUnselectable: true
showInEditor: true
fireTurretXAtSelfOnDeath: 1
canNotBeDirectlyAttacked: true
showOnMinimapToEnemies: false
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true

[graphics]
total_frames: 1
image: ROOT:通用特效/NO.png
image_wreak: NONE
image_turret: NONE
showEnergyBar: false

image_shadow: NONE
imageScale: 0.5
dustEffect: false


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 10

turretTurnSpeed: 6
maxAttackRange: 35
shootDelay: 8
aimOffsetSpread: 0.25


[turret_1]
x: -7000
y: 7000
invisible: true
projectile: 1
turnSpeed: 15
turnSpeedAcceleration: 100
shoot_sound: NONE
canShoot: true


[projectile_1]
@copyFromSection: template_动能
areaDamage: 0
areaRadius: 0
areaHitAirAndLandAtSameTime: true
life: 390
speed: 23
deflectionPower: -1
drawSize: 1.5
targetSpeed: 23
tags:天上战略
image: 铁棍.png
explodeEffect: CUSTOM:导弹碎片,CUSTOM:导弹碎片1,CUSTOM:导弹碎片2,CUSTOM:冲击波,CUSTOM:烟雾*7
areaRadiusFromEdge: true
targetGround: true
lightSize: 1
trailEffectRate: 0.85
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1
lightColor: #FF00B3FF
#spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
spawnProjectilesOnEndOfLife: 2*3
speedSpread: 5
nukeWeapon: true
[projectile_2]
@copyFromSection: template_动能,template_战略武器
areaDamage: 4000
areaRadius: 165
life: 250
image: ROOT:/太空浪人/单位特效/光.png
drawSize: 1
speed: 35
explodeEffect: CUSTOM:烟雾dn*4,CUSTOM:烟雾dn2*3,CUSTOM:烟雾dn1,CUSTOM:光粒dn*2,CUSTOM:光粒dn1*3,CUSTOM:闪光dn,CUSTOM:冲击波dn1,CUSTOM:闪光dn1
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 0.1
trailEffect: CUSTOM:尾巴x
targetGroundSpread: 200
speedSpread: 4
mutator7_ifUnitWithoutTags:极端重型
mutator7_directDamageMultiplier: 1.5
mutator7_areaDamageMultiplier: 1.5
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
[effect_尾巴x]
priority: critical
image: ROOT:/太空浪人/单位特效/光束3.png
life: 15
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.85
scaleTo: 0.85
alpha: 0.85
drawUnderUnits: false
[effect_尾巴]
priority: critical
image: ROOT:/通用特效/爆炸.png
life: 65
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.2
scaleTo: 6
alpha: 0.5
drawUnderUnits: false
atmospheric: true
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13
animateFrameSpeed: 0.3
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: 145

[effect_尾巴1]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false
yOffsetRelative: 20
color: #FFFFFF
fadeInTime: 5
scaleFrom: 3
scaleTo: 8
alpha: 0.6
drawUnderUnits: true
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


#——————————————————导弹碎片
[effect_导弹碎片]
priority: veryhigh
image: 铁棍1.png
spawnChance: 1
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 1.5
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
ySpeedRelative: -10
hSpeed:1
dirSpeedRandom: 10
yOffsetRelative: -10

[effect_导弹碎片1]
priority: high
image: 碎片.png
spawnChance: 1
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 1.5
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
xSpeedRelative: 3
ySpeedRelative: 7
yOffsetRelative: 10
hSpeed: 2.5
dirSpeedRandom: 10

[effect_导弹碎片2]
priority: high
image: 碎片1.png
spawnChance: 1
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 1.5
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
xSpeedRelative: -3
ySpeedRelative: 7
yOffsetRelative: 10
hSpeed: 2.5
dirSpeedRandom: 10


[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 7
alpha: 1
fadeOut: true
alsoPlaySound: ROOT:/通用特效/巨大爆炸.wav:1.5
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 5
scaleTo: 7
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 2.5
xSpeedRelativeRandom: 0.8
yOffsetRelative: 0.6
ySpeedRelative: 5
atmospheric: true


#——————————————————爆

#——————————————————————

[effect_烟雾dn2]
color: #FFFFFFFF
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenOffscreen: true
life: 350
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 8
scaleTo: 10
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.8
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6
xSpeedRelativeRandom: 0.6
atmospheric: true
xOffsetRelativeRandom:40
yOffsetRelativeRandom:40
createWhenOverLiquid: true
createWhenOverLand: false


[effect_冲击波dn1]
life: 80
priority: high
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
showInFog: true
drawUnderUnits: true
alpha:0.8
createWhenOffscreen: true

[effect_闪光dn]
image: SHARED:light_50.png
life: 15
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 18
scaleTo: 18
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_闪光dn1]
image: SHARED:light_50.png
life: 90
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
priority: critical
createWhenOffscreen: true
alsoPlaySound:ROOT:/通用特效/音波.wav

[effect_烟雾dn]
color: #FF917C44
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenOffscreen: true
life: 220
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 9
scaleTo: 11
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.8
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6
xSpeedRelativeRandom: 0.6
atmospheric: true
xOffsetRelativeRandom:40
yOffsetRelativeRandom:40
createWhenOverLiquid: false
createWhenOverLand: true
[effect_烟雾dn1]
priority: veryhigh
color: #FF535656
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenOffscreen: true
life: 220
fadeOut: true
attachedToUnit: false
fadeInTime: 17
scaleFrom: 13
scaleTo: 8
alpha: 2
drawUnderUnits: true
liveAfterAttachedDies: false
hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.8
atmospheric: true
xOffsetRelativeRandom:50
yOffsetRelativeRandom:50
createWhenOverLiquid: false
createWhenOverLand: true
[effect_光粒dn]
color: #FF917C44
priority: veryhigh
spawnChance: 1
image: ROOT:/余辉军团/建筑特效/粒.png
createWhenZoomedOut: false
life: 300
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 0.8
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.6
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.7
xSpeedRelativeRandom: 0.7
atmospheric: true
xOffsetRelativeRandom:50
yOffsetRelativeRandom:50
createWhenOverLiquid: false
createWhenOverLand: true

[effect_光粒dn1]
color: #FFFFFFFF
priority: veryhigh
spawnChance: 1
image: ROOT:/余辉军团/建筑特效/粒.png
createWhenZoomedOut: false
life: 380
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 0.8
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.6
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.7
xSpeedRelativeRandom: 0.7
atmospheric: true
xOffsetRelativeRandom:50
yOffsetRelativeRandom:50
createWhenOverLiquid: true
createWhenOverLand: false


[movement]
movementType: AIR
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0
turnAcceleration: 0.75
moveSlidingMode : true
moveIgnoringBody: true
targetHeight: 0
targetHeightDrift: 0




