


[core]
name: 玄鸟轰炸机
displayText: Бомбардировщик «Чёрная Птица»
class: CustomUnitMetadata
showInEditor: false
displayDescription: -😭👊
price: 0
maxHp: 6800
techLevel: 1
buildSpeed: 0s
availableInDemo: true
fogOfWarSightRange: 28
armour: 8
radius: 29
displayRadius: 29
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 90
energyMax: 60
energyRegen: 0
energyNeedsToRechargeToFull: true
tags: 飞机,高空,玄鸟,寄生免疫,伴生单位
effectOnDeath:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
effectOnDeathGroundCollision:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
canNotBeGivenOrdersByPlayer: true
energyStartingPercentage: 1
logIfCreditResourceUsed: true
canOnlyBeAttackedByUnitsWithTags:反高空
[hiddenAction_有炸弹]
autoTrigger: if parent.tags(includes= '用炸弹') and self.hasParent 
temporarilyAddTags: 炸弹
temporarilyRemoveTags:导弹,祸根
[hiddenAction_有祸根]
autoTrigger: if parent.tags(includes= '用地雷') and self.hasParent 
temporarilyAddTags: 祸根
temporarilyRemoveTags:炸弹,导弹
[hiddenAction_有导弹]
autoTrigger: if parent.tags(includes= '用导弹') and self.hasParent 
temporarilyAddTags: 导弹
temporarilyRemoveTags:祸根,炸弹
[action_高空]
text: высотныйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的истребитель和боевой корабль。\n-在此高度下，только有地面和空中специальный的против высотныхюнит，а такжевысотныйюнит才может攻击до该юнит，\n-одновременно，大部分высотныйюнитможет互相攻击，иможет攻击обычныйвоздушный юнит，\n-только有специальный的высотныйюнит才можетпо земле攻击。
[decal_影子]
image: 影子.png
total_frames: 1
layer: shadow
isVisible: if not self.hasParent
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
hOffset:-140
alpha:0.6
imageScale:0.75
[decal_影子1]
image: 影子x.png
total_frames: 1
layer: shadow
isVisible: if self.hasParent
yOffsetRelative:-1
xOffsetRelative:-1.5
onlyWhileAlive:true
alpha:0.6
imageScale:0.75
[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'
[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'


[hiddenAction_return1]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( self.isEnergyRecharging or distanceBetweenSquared(self, customTarget1) > 3500 * 3500 )
# distanceBetweenSquared 返回两个单位之间的平方距离。 比 distanceBetween 快一点，因为少了开方这一步。1100² 判断灰机离母体有多远，超过1100回家
clearActiveWaypoint: true
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto


[hiddenAction_disconnect]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( not self.hasActiveWaypoint(type= 'attack') or activeWaypointTarget.height < 0)
disconnectFromParent: true
clearActiveWaypoint: true
addWaypoint_type: attack
addWaypoint_prepend: true

addWaypoint_target_fromReference: customTarget1.attacking
addWaypoint_triggerActionIfMatched: 补丁
addWaypoint_triggerActionIfFailed: return1


[hiddenAction_补丁]
requireConditional: if not self.hasParent and not self.hasActiveWaypoint(type= 'attackMove')
addWaypoint_type: attackMove
addWaypoint_target_fromReference: thisActionTarget




[hiddenAction_energy]
autoTriggerOnEvent: enteredTransport
addResources:energy=61


[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
# 这条在鹰爪和雪崩里忘改成这样了，原本是打算航母凉后灰机用完能量才自杀，不过有bug忘了改回来
addResources: hp= -999999

[action_akm]
autoTrigger: if self.hasParent and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
stopLastAnimation: true
[action_bkm]
autoTrigger: if not self.hasParent and self.hasFlag(id=1)
isVisible: false
addResources: unsetFlag=1
playAnimation: attack
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[graphics]
total_frames: 1
image: NO.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 0.75
image_shadow: NONE
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 850
attackMovement: bomber
[turret_1]
x: 0
y: -9
invisible: true
turnSpeed: 200
turnSpeedAcceleration: 11
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/丢炸弹.ogg
shoot_sound_vol: 0.8
canShoot: true
delay: 5
canAttackFlyingUnits: false
energyUsage:5
limitingRange:250
canAttackCondition: if self.tags(includes= '炸弹')
[turret_2]
x: -15
y: 0
invisible: true
turnSpeed: 200
turnSpeedAcceleration: 11
projectile: 2
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 0.8
canShoot: true
delay: 120
canAttackFlyingUnits: false
energyUsage:30
limitingRange:475
canAttackCondition: if self.tags(includes= '祸根')
[turret_3]
x: 15
y: 0
copyFrom: 2
warmup:20
delay:100
[turret_4]
x: -15
y: 0
idleDir: 0
canShoot: true
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 1
canAttackFlyingUnits: false
projectile: 4
size: 1
delay:120
energyUsage:30
limitingMinRange: 300
canAttackCondition:if self.tags(includes= '导弹')
limitingAngle: 15
[turret_5]
x: 15
y: 0
copyFrom: 4
warmup:20
delay:100
[projectile_1]
@copyFromSection: template_爆炸
life: 55
speed: 0
targetSpeed: 0
areaDamage: 1500
explodeOnEndOfLife:true
areaRadius: 80
drawSize: 0.8
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波, CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波, CUSTOM:弹坑
targetGround: true
areaRadiusFromEdge: true
image:铁炸弹.png
trueGravity: 0.1
#drawUnderUnits:true
disableLeadTargeting: true
targetGround_includeTargetHeight:true
[projectile_2]
@copyFromSection: template_爆炸
life: 35
speed:3
targetSpeed: 6
directDamage: 0
targetGround: true
explodeOnEndOfLife:true
drawSize: 0.8
image:祸根.png
trailEffectRate: 0.6
trailEffect: CUSTOM:projectileTrail,CUSTOM:星
initialUnguidedSpeedHeight: 2
#trueGravity: 0.05
spawnProjectilesOnEndOfLife:3*8
explodeEffect: CUSTOM:导弹碎片, CUSTOM:导弹碎片1*2
targetGroundSpread: 80

[projectile_3]
@copyFromSection: template_爆炸
life: 420
turnSpeed: 30
spawnProjectilesOnEndOfLife: NONE
speed: 4
targetSpeed: 6
largeHitEffect: true
drawSize: 0.75
lightSize: 0.6
color: #FFFFFF73
areaDamage: 100
areaRadius: 40
image: 核.png
explodeEffect: CUSTOM:黑冲击波
trailEffect: true
trailEffectRate: 1.75
targetGround: true
targetGroundSpread: 100
disableLeadTargeting: true
speedSpread:2
initialUnguidedSpeedHeight: 1.5
areaRadiusFromEdge: true
spawnUnit: 蹦蹦炸弹*1
gravity: 0.4
targetGround_includeTargetHeight:true
[projectile_4]
@copyFromSection: template_爆炸
life: 55
speed: 0
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: 巡航1.png
areaDamage: 0
areaRadius: 0
explodeEffect:CUSTOM:音效
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:5
explodeOnEndOfLife:true
drawUnderUnits:true

[projectile_5]
@copyFromSection: template_爆炸
directDamage: 6000
deflectionPower: -1
life: 600
speed: 9
image: 巡航.png
targetSpeed: 11
drawSize: 0.9
lightSize: 1.5
trailEffect: CUSTOM:pprojectileTrail
trailEffectRate: 0.7
lightColor: #FFFFFF73
explodeEffect: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
explodeEffectOnShield: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
#——————————

[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸1.ogg
alpha: 1.2
[effect_冲击波]
life: 110
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 1.6
scaleTo: 3
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 0.8
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.5
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 1
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1.3
scaleTo: 1.3
createWhenOverLiquid: false
createWhenOverLand: true
#————————尾焰
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: -7
ySpeedRelative: -2
yOffsetRelative	: -30
drawUnderUnits: true
[effect_火2]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 7
ySpeedRelative: -2
yOffsetRelative	: -30
drawUnderUnits: true
[arm_1]
x: 15
y: -4
image_end: 左1.png
drawOverBody: true
image_end_teamColors: true
[arm_2]
x: -15
y: -4
image_end: 右1.png
drawOverBody: true
image_end_teamColors: true
[arm_3]
x: 5
y: -4
image_end: 左.png
drawOverBody: true

image_end_teamColors: true
[arm_4]
x: -5
y: -4
image_end: 右.png
drawOverBody: true

image_end_teamColors: true
[arm_5]
x: 0
y: 0
image_end: 主体.png
drawOverBody: true
image_end_teamColors: true

[arm_6]
x: 0
y: -15
image_end: 机头.png
drawOverBody: true
image_end_teamColors: true
[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_0s: {x:0, y:0,dir:0}
arm1_1s: {x:-15, y:4,dir:0}
arm1_99999s: {x:-15, y:4,dir:0}

arm2_0s: {x:0, y:0,dir:0}
arm2_1s: {x:15, y:4,dir:0}
arm2_99999s: {x:15, y:4,dir:0}

arm3_0s: {x:0, y:0,dir:0}
arm3_1s: {x:-5, y:4,dir:0}
arm3_99999s: {x:-5, y:4,dir:0}

arm4_0s: {x:0, y:0,dir:0}
arm4_1s: {x:5, y:4,dir:0}
arm4_99999s: {x:5, y:4,dir:0}

arm6_0s: {x:0, y:0,dir:0}
arm6_1s: {x:0, y:15,dir:0}
arm6_99999s: {x:0, y:15,dir:0}
[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/巨大爆炸.ogg
createWhenOffscreen: true
#——————————祸根
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 40
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.4
scaleTo: 1
alpha: 0.7
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -22
[effect_星]
image:ROOT:/创世纪军事集团/单位特效/星星1.png
life: 2
fadeOut: true
spawnChance: 0.6
alpha: 1
attachedToUnit:true
#color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 0.3
scaleTo: 0.3
drawUnderUnits: false
atmospheric: false
yOffsetRelative: -15
[effect_导弹碎片]
#priority: low
image:祸根弹壳.png
spawnChance: 1
life: 130
fadeOut: true
createWhenOffscreen: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 0.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
ySpeedRelative: -0.6
yOffsetRelative: -15
hSpeed: 1
dirSpeedRandom: 10
[effect_导弹碎片1]
#priority: low
image:祸根弹壳1.png
spawnChance: 1
life: 130
fadeOut: true
createWhenOffscreen: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 0.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.85
ySpeedRelativeRandom: 0.85
ySpeedRelative:0.6
hSpeed: 1
dirSpeedRandom: 10
yOffsetRelative: 10
[effect_黑冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 4
alpha: 1
#——————————导弹
[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:ROOT:/通用特效/新导弹发射.wav
#——————————————————炸
[effect_爆炸hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.44
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/重型爆炸.wav
alwayStartDirAtZero: true
[effect_爆炸hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/12.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.21
alwayStartDirAtZero: true
[effect_闪光hx]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 8
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.85
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_pprojectileTrail]
stripIndex: effects
frameIndex: 0
life: 80
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.4
scaleTo: 2
alpha: 0.8
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.1
ySpeedAbsoluteRandom: 0.1
[movement]
movementType: AIR
reverseSpeedPercentage: 0
moveSpeed: 4.5
moveAccelerationSpeed: 2.5
moveDecelerationSpeed: 0
targetHeightDrift: 0.3
targetHeight: 140
maxTurnSpeed: 90
turnAcceleration: 0.1
moveSlidingMode: false

moveIgnoringBody: false
moveSlidingDir: 0
slowDeathFall: false


