


[core]
name: 电磁压制塔1
displayText: Башня электромагнитного подавления1
class: CustomUnitMetadata
displayDescription: 눈_눈
price: 0
maxHp: 15000
mass: 1
techLevel: 1
buildSpeed: 6s
radius: 13
softCollisionOnAll: 5
copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
hideScorchMark: true
energyMax: 60
energyRegen: -1
energyStartingPercentage: 1
dieOnZeroEnergy: true
#disableAllUnitCollisions: true
isBuilding: true
canNotBeDamaged:true
tags: 压制塔
showOnMinimap:false
isUnselectable: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
canNotBeGivenOrdersByPlayer: true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_shadow: AUTO
teamColorsOnTurret: true
icon_zoomed_out_neverShow:true
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 22
turretTurnSpeed: 3
maxAttackRange: 415

[movement]
movementType: HOVER
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0


