
[resource_2]
displayName: 2
displayNameShort: 2
displayColor: #FF9D00FF
priority: 1
hidden: true

[core]
name: 电磁压制塔
displayText: 电磁压制塔
class: CustomUnitMetadata
displayDescription: 눈_눈
price: 0
maxHp: 15000
mass: 1
techLevel: 1
buildSpeed: 6s
radius: 13
softCollisionOnAll: 5
copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
energyMax: 9000
energyRegen: -1
dieOnZeroEnergy: true
tags: 地面,压制塔,扫雷,伴生单位,无人单位,危险物品
#disableAllUnitCollisions: true
isBuilding: true
[hiddenAction_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
deleteSelf:true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_扫雷]
autoTrigger: if self.hasFlag(id=1)
deleteSelf: true
[decal_圈11]
image: 光圈1.png
layer:onTop
onlyWhileAlive:true
imageScale:1.2
isVisible:if self.resource.2>0.5
[action_余晖]
autoTrigger:if not self.tags(includes= '索敌单位') and self.resource.2>0.5
isVisible: false
temporarilyAddTags:索敌单位
[decal_主体s]
image: 主体.png
total_frames: 1
layer: onTop
isVisible:if self.resource.2<0.5
onlyWhileAlive:true
[decal_主体]
image: ROOT:/余辉军团/建筑特效/小重工仓.png
total_frames: 1
layer: onTop
isVisible:if self.resource.2>0.5
onlyWhileAlive:true
dirOffset:180
[action_b]
autoTrigger:true
displayType: action
price: 0
isVisible: false
spawnEffects:emp*4
[decal_圈]
image: 光圈2.png
layer:onTop
onlyWhileAlive:true
imageScale:1
[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_shadow: AUTO
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 22
turretTurnSpeed: 3
maxAttackRange: 415
[effect_emp]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: ROOT:/通用特效/电弧.png
total_frames: 8
animateFrameStart:1
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 0.6
drawUnderUnits: false
scaleFrom: 1
scaleTo:1
xOffsetRelativeRandom:385
yOffsetRelativeRandom:385
createWhenOffscreen: true
delayedStartTimerRandom:30
[movement]
movementType: HOVER
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0


