

[resource_1]
displayName: 1
displayNameShort: 1
displayColor: #FF9D00FF
priority: 1
hidden: true
[core]
name: 爆裂物
displayText: Взрывной заряд
price: -1
maxHp: 3
canOnlyBeAttackedByUnitsWithTags:消防
techLevel: 1
buildSpeed: 5s
radius: 7
displayRadius: 7
canNotBeDamaged: true
numBitsOnDeath: 0
fogOfWarSightRange: 5
isBio: false
softCollisionOnAll: 100
isBuilding: true
energyMax: 130
energyRegen: -0.7
dieOnZeroEnergy: true
canNotBeGivenOrdersByPlayer: true
disableAllUnitCollisions: true
isUnselectable: false
energyStartingPercentage: 1

copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
explodeOnDeath: false
hideScorchMark: true
armour: 0
tags:危险物品,地面
[hiddenAction_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
deleteSelf:true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_扫雷]
autoTrigger: if self.hasFlag(id=1)
deleteSelf: true
[hiddenAction_1]
autoTrigger: if self.resource.1<0.5 and self.energy<10
fireTurretXAtGround: 1
addResources: hp=-999999
[hiddenAction_2]
autoTrigger: if self.resource.1>0.5 and self.energy<10
fireTurretXAtGround: 2
addResources: hp=-999999


[hiddenAction_DPS1]
autoTrigger: if self.resource.1<0.5
spawnEffects: CUSTOM:蓝色波,CUSTOM:蓝闪光
[hiddenAction_PS1]
autoTrigger: if self.resource.1>0.5
spawnEffects: CUSTOM:粉色波,CUSTOM:粉闪光

[graphics]
total_frames: 1
image: 爆炸雷.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE

imageScale: 0.8
dustEffect: false


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 10

turretTurnSpeed: 6
maxAttackRange: 35
shootDelay: 8
aimOffsetSpread: 0.25


[turret_1]
x: 0
y: 0
invisible: true
projectile: 1
turnSpeed: 15
turnSpeedAcceleration: 1.0
shoot_sound: NONE
canShoot: true
[turret_2]
x:0
y: 0
copyFrom: 1
projectile: 2


[projectile_1]
@copyFromSection: template_能源
areaDamage: 5500
areaRadius: 90
life: 666
speed: 8888

targetSpeed: 8888
instant: true
deflectionPower: -1
areaRadiusFromEdge: true

explodeEffect: CUSTOM:等离子平铺爆炸实验,CUSTOM:等离子平铺爆炸闪光,CUSTOM:等离子平铺爆炸聚变,CUSTOM:等离子平铺爆炸冲击波,CUSTOM:等离子平铺爆炸冲击波1,CUSTOM:等离子平铺爆炸光球1,CUSTOM:等离子平铺爆炸光球
explodeEffectOnShield:CUSTOM:等离子平铺爆炸实验,CUSTOM:等离子平铺爆炸闪光,CUSTOM:等离子平铺爆炸聚变,CUSTOM:等离子平铺爆炸冲击波,CUSTOM:等离子平铺爆炸冲击波1,CUSTOM:等离子平铺爆炸光球1,CUSTOM:等离子平铺爆炸光球
[projectile_2]
areaDamage: 0
areaRadius: 0
life: 666
speed: 8888

targetSpeed: 8888
instant: true
deflectionPower: -1
areaRadiusFromEdge: true
spawnUnit: 小迷你黑洞
explodeEffect: CUSTOM:冲击波z,CUSTOM:闪光z,CUSTOM:实验z1,CUSTOM:碎星*12
explodeEffectOnShield: CUSTOM:冲击波z,CUSTOM:闪光z,CUSTOM:实验z1,CUSTOM:碎星*12
[effect_蓝色波]
stripIndex: shockwave
life: 33
scaleFrom: 0.5
scaleTo: 1.7
alpha: 0.8
color: #FF00B3FF
[effect_蓝闪光]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 1.8
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_粉色波]
stripIndex: shockwave
life: 33
scaleFrom: 0.5
scaleTo: 1.7
alpha: 0.8
color: #FFE56BFF
[effect_粉闪光]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFE56BFF
fadeInTime: 2
scaleFrom: 1.8
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[arm_1]
x: 0
y: 0
image_end: 黑洞雷.png
drawOverBody: true
hidden:if self.resource.1<0.5
moveSpeed:6
#——————————————黑洞爆炸
[effect_冲击波z]
priority: critical
image: ROOT:/余辉军团/单位特效/超级冲击波1.png
life: 45
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.6
alpha:1
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/余辉军团/单位特效/瓶.ogg
[effect_碎星]
spawnChance: 1
createWhenZoomedOut: false
priority: low
life: 60
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/粒子2.png
scaleFrom:0.22
scaleTo:0.22
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 9
ySpeedRelativeRandom: 9
[effect_实验z1]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0
scaleTo:4
alpha: 1
fadeInTime: 4
drawUnderUnits:true
createWhenZoomedOut: false
dirOffsetRandom:180
dirSpeedRandom: 1.5
[effect_闪光z]
priority: high
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 0.5

attachedToUnit: false
color: #FFFFFFFF
createWhenOffscreen: true
#fadeInTime:2
scaleFrom: 9

scaleTo: 0
drawUnderUnits: true
atmospheric: false
[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
moveSlidingMode : true
moveIgnoringBody: true


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


