


[core]
name: 太空浪人钻探机t3
displayText: Бурильная установка Скитальцев t3
displayDescription: 基本的矿业设施，\n-供给太空浪人军队需要。
class: CustomUnitMetadata
price: 4500
maxHp: 8000

generation_credits: 35
generation_delay: 40
techLevel: 1
buildSpeed: 8s
radius: 18

isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
placeOnlyOnResPool: true
numBitsOnDeath: 10
armour: 10
effectOnDeath: CUSTOM:冲击波, CUSTOM:爆炸,CUSTOM:闪光z
tags: 地面,灰影建筑,建筑,寄生免疫


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 太空浪人钻探机t1死亡.png
image_back: 背景.png
#image_shadow: AUTO

image_shadow: 影子.png
shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 30
maxAttackRange: 9999
shootDelay: 0


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_爆炸]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5

scaleTo: 1.5
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
color: #FFFF1200
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg


[effect_闪光z]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 7
scaleTo: 7

drawUnderUnits: true
atmospheric: false


[arm_2]
x: 11
y: 0
image_end: 货物.png
image_end_teamColors: true


[arm_3]
x: 10
y: 15
image_end: 玻璃.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_4]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(greaterThan=2880)


[animation_2]
onActions: idle
blendIn: 1s
blendOut: 2s
arm2_0s: {x:0, y:0}
arm2_2s: {x:0, y:37}

arm2_4s: {x:-22, y:37}
arm2_6s: {x:-22, y:-10}
arm2_8s: {x:0, y:-10}


[ai]
upgradedFrom: 太空浪人钻探机t1传送
ai_upgradePriority: 0.07


