[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[action_拆除哇袄]
addResources: 威胁点数=-600
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=600
[core]
selfRegenRate: 2
name: 亚空间运算引擎
displayText: подпространственный вычислительный движок
class: CustomUnitMetadata
price: 8000,蓝晶=2100
maxHp: 40000
maxShield: 45000
shieldRenderRadius: 1
shieldRegen: 1
footprint: -8,-2,8,7
constructionFootprint: -8,-2,8,7
techLevel: 1
numBitsOnDeath:25
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1
buildSpeed: 0s
radius: 98
fogOfWarSightRange: 35
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:通用实验*2,CUSTOM:通用闪光nk,CUSTOM:通用聚变nk,CUSTOM:通用云雾2nk*2,CUSTOM:通用云雾1nk*2,CUSTOM:通用云雾nk*2,CUSTOM:通用冲击波nk,CUSTOM:通用冲击波nk1,CUSTOM:通用冲击波nk2,CUSTOM:通用冲击波nk3,CUSTOM:通用聚变nk1,CUSTOM:通用光球1nk,CUSTOM:通用光球nk,CUSTOM:震动
unitsSpawnedOnDeath: 建筑损毁*2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
isBuilding: true
displayDescription: 【Уровень t4】【Сверхтяжёлый юнит】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)【Беспилотный юнит】\n-тактическое назначение: лаборатория предельных технологий, без вооружения.\n-амфибия, можно иметь только один.По сути, этот суперкомпьютер - воспроизведение технологий покойного Механического Бога;\n-на заре Империи Нова Механический Бог новаторски объединил подпространственные технологии и вычисления,\n-что позволило микрочастицам нарушить световой предел нашей вселенной и обойти теоретические ограничения вычислений.\n-Подпространственное вычислительное ядро не имеет себе равных по мощности - за микросекунды оно вычисляет то, на что обычным суперкомпьютерам требуются миллионы лет.\n-Это основа применения передовых технологий и производства продвинутых ядер ИИ Империи,\n-а также бесценное наследие, оставленное Механическим Богом своим подданным после его ухода в пустоту.
tags: 地面,建筑,无人单位,极端重型,亚空间运算引擎
energyNeedsToRechargeToFull: false
armour: 120
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='亚空间运算引擎')
deleteSelf: true
showMessageToPlayer: Эксплойт? Размечтался, в наказание лишний юнит сожрёт сервер눈_눈
addResources: 威胁点数=-600
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上

[action_重]
text: Сверхтяжёлый юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 10
iconImage: ROOT:/通用特效/重.png
isLockedMessage: Уникальное свойство огромных юнитов;\n-юниты с тегом «сверхтяжёлый» получают следующие свойства:\n-восстанавливают HP и имеют броню не менее 100,\n-не подвержены шоку, но получают повышенный урон от противобронетанковых юнитов.


[action_加装零点能数据仓]
text: Установить датахранилище нулевой энергии
buildSpeed: 350s
price: 12000,蓝晶=3000,energy=1
description: -Установить специализированную ИИ-капсулу, анализирующую формулы нулевой энергии и обработку синий кристаллИИ-капсула, \n-С её помощью, мы сможем производить мощнейший искусственный источник энергии — реактор нулевой точки.\n-После постройки данные сохраняются автоматически, даже если подпространственный вычислительный движокбудет уничтожен, \n-система всё равно считает наличие датахранилище нулевой энергии, Священный Инквизитор предварительная технология
isVisible: if not self.globalTeamTags(includes='零点能数据仓')
addGlobalTeamTags: 零点能数据仓
addResources: energy=1
showMessageToPlayer: Датахранилище нулевой энергии установлено
pos: 0.1
ai_isHighPriority: true
iconImage: 零点能.png
isLocked:  if not self.globalTeamTags(includes='泽塔诺亚3') or not self.globalTeamTags(includes='禁卫军2')
isLockedMessage: Требуется база чертежей Зетаноя 3 и\nрепликация вооружений гвардии 2






[action_零点能数据仓1]
displayType: infoOnlyNoBox
iconImage: 零点能.png
text:Датахранилище нулевой энергии установлено
isActive: false
pos: 2
isVisible: if self.globalTeamTags(includes='零点能数据仓')

[action_加装微观物质解析仓]
text: Установить анализатор микроматерии
buildSpeed: 100s
price: 6000,蓝晶=1500,energy=1
description: -Установить специализированную ИИ-капсулу для анализа микрочастиц и точной обработки ИИ-капсула, \n-С её помощью, мы сможем производить самое точное оборудование и самые прочные материалы Империи.\n-После постройки данные сохраняются автоматически, даже если подпространственный вычислительный движокбудет уничтожен, \n-система всё равно считает наличие анализатор микроматерии, разблокирует штурмовой десантный корабль класса «Лазурный Покров», \n-Хранитель Святилища предварительная технология
isVisible: if not self.globalTeamTags(includes='微观物质解析仓')
addGlobalTeamTags: 微观物质解析仓
addResources: energy=1
showMessageToPlayer: Анализатор микроматерии установлен
pos: 0.2
ai_isHighPriority: true
iconImage: 解析.png
isLocked:  if not self.globalTeamTags(includes='皇家舰队3') or not self.globalTeamTags(includes='禁卫军2')
isLockedMessage: Требуется доктрина имперского флота 3 и\nрепликация вооружений гвардии 2





[action_微观物质解析仓1]
displayType: infoOnlyNoBox
iconImage: 解析.png
text:Анализатор микроматерии установлен
isActive: false
pos: 2.1
isVisible: if self.globalTeamTags(includes='微观物质解析仓')


[action_加装重力控制仓]
text: Установить отсек гравитационного контроля
buildSpeed: 120s
price: 7500,蓝晶=1500,energy=1
description: -Установить ИИ-капсулу, отвечающую за производство сверхплотной материи и гравитацияуправленияИИ-капсула, \n-С её помощью, мы сможем свободно управлять гравитация для постройки различных мощных юнитов, \n-илиили создавать разрушительные Опустошитель.После постройки данные сохраняются автоматически, даже если подпространственный вычислительный движокбудет уничтожен, \n-система всё равно считает наличие отсек гравитационного контроля, Имея отсек гравитационного контроляможно десантировать здания высокого уровня, \n-Каратель Небес предварительная технология
isVisible: if not self.globalTeamTags(includes='重力控制仓')
addGlobalTeamTags: 重力控制仓
addResources: energy=1
showMessageToPlayer: Отсек гравитационного контроля установлен
pos: 0.3
ai_isHighPriority: true
iconImage: 重4.png
isLocked:  if not self.globalTeamTags(includes='乌托米尔3') or not self.globalTeamTags(includes='皇家舰队3')
isLockedMessage: Требуется атомная литография Утомир 3 и\nдоктрина имперского флота 3

[action_重力控制仓]
displayType: infoOnlyNoBox
iconImage: 重4.png
text:Отсек гравитационного контроля установлен
isActive: false
pos: 2.2
isVisible: if self.globalTeamTags(includes='重力控制仓')




[decal_支撑]
image: 水下.png
total_frames: 1
layer: shadow
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.isOverLiquid
#alpha:0.4

[decal_影子]
image: SHADOW:影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:8
xOffsetRelative:10
onlyWhileAlive:true
alpha:0.6

[decal_主体损坏]
image: 主体损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true

[decal_光线]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8


[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:0
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1


[decal_上层遮盖]
image: 上层.png
total_frames: 1
layer: onTop
isVisible:if self.globalTeamTags(includes='零点能数据仓')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true



[decal_上层损坏]
image: 上层损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36 and self.globalTeamTags(includes='零点能数据仓')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true


[decal_左侧遮盖]
image: 左侧.png
total_frames: 1
layer: onTop
isVisible:if self.globalTeamTags(includes='微观物质解析仓')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true


[decal_左侧损坏]
image: 左侧损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36 and self.globalTeamTags(includes='微观物质解析仓')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true

[decal_右侧遮盖]
image: 右侧.png
total_frames: 1
layer: onTop
isVisible:if self.globalTeamTags(includes='重力控制仓')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true


[decal_右侧损坏]
image: 右侧损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36 and self.globalTeamTags(includes='重力控制仓')
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true

[decal_上层护盾]
image: 上层盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and self.globalTeamTags(includes='零点能数据仓')
yOffsetRelative:0
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1

[decal_左护盾]
image: 左护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and self.globalTeamTags(includes='微观物质解析仓')
yOffsetRelative:0
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1

[decal_右护盾]
image: 右护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and self.globalTeamTags(includes='重力控制仓')
yOffsetRelative:0
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: NONE
image_back:地板.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:false
canAttackUnderwaterUnits: false
maxAttackRange:0
turretSize: 0
turretTurnSpeed: 0





[arm_1]
x: 0
y: 0
image_end: 右方块.png
image_end_teamColors: true
drawOverBody: true
hidden: if not self.globalTeamTags(includes='重力控制仓')



[arm_2]
x: 0
y: 0
image_end: LED1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36


[animation_1]
KeyframeTimeScale:0.6
onActions: idle
blendIn: 0.5s
blendOut: 0.5s
arm1_0s: {x:0,y:0}
arm1_0.5s: {x:0,y:2}
arm1_4.0s: {x:0,y:10}
arm1_4.5s: {x:0,y:12}
arm1_5.0s: {x:0,y:10}
arm1_8.5s: {x:0,y:2}
arm1_9.5s: {x:0,y:0}

arm2_0s: {x:0,y:0,alpha:0}
arm2_2.375s: {x:0,y:0,alpha:1}
arm2_4.75s: {x:0,y:0,alpha:0}
arm2_7.125s: {x:0,y:0,alpha:1}
arm2_9.5s: {x:0,y:0,alpha:0}
[effect_震动]
createWhenOffscreen:true
drawType: displacement
image:震动.png
life:40
fadeOut: false
fadeInTime:50
attachedToUnit: true
scaleFrom:20
scaleTo:20
alpha:0.035
drawUnderUnits:false
alwayStartDirAtZero: true
total_frames: 2
animateFrameStart: 0
animateFrameEnd:1
animateFrameSpeed: 0.3
animateFrameLooping:true
showInFog: true
priority: critical

[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0
[ai]
buildPriority: 10
maxEachBase: 1
maxGlobal: 2
noneInBaseExtraPriority:100
upgradedFrom: 建造亚空间运算引擎
