[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[action_拆除哇袄]
addResources: 威胁点数=-600
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=600
[core]
selfRegenRate: 2
name: 建造亚空间运算引擎
displayText: Строительство подпространственного движка
class: CustomUnitMetadata
price: 8000,蓝晶=2100
maxHp: 40000
footprint: -8,-2,8,7
constructionFootprint: -8,-2,8,7
techLevel: 1
showInEditor: false
fogOfWarSightRange: 35
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:通用实验*2,CUSTOM:通用闪光nk,CUSTOM:通用聚变nk,CUSTOM:通用云雾2nk*2,CUSTOM:通用云雾1nk*2,CUSTOM:通用云雾nk*2,CUSTOM:通用冲击波nk,CUSTOM:通用冲击波nk1,CUSTOM:通用冲击波nk2,CUSTOM:通用冲击波nk3,CUSTOM:通用聚变nk1,CUSTOM:通用光球1nk,CUSTOM:通用光球nk,CUSTOM:震动
unitsSpawnedOnDeath: 建筑损毁*2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
radius: 98
selfBuildRate: 99999
buildSpeed: 0s
softCollisionOnAll: 60
isBio: false
isBuilding: true
energyMax: 200
energyRegen: 0.056
energyStartingPercentage: 0
displayDescription: 【Уровень t4】【Сверхтяжёлый юнит】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)【Беспилотный юнит】\n-тактическое назначение: лаборатория предельных технологий, без вооружения.\n-амфибия, можно иметь только один.По сути, этот суперкомпьютер - воспроизведение технологий покойного Механического Бога;\n-на заре Империи Нова Механический Бог новаторски объединил подпространственные технологии и вычисления,\n-что позволило микрочастицам нарушить световой предел нашей вселенной и обойти теоретические ограничения вычислений.\n-Подпространственное вычислительное ядро не имеет себе равных по мощности - за микросекунды оно вычисляет то, на что обычным суперкомпьютерам требуются миллионы лет.\n-Это основа применения передовых технологий и производства продвинутых ядер ИИ Империи,\n-а также бесценное наследие, оставленное Механическим Богом своим подданным после его ухода в пустоту.
tags: 地面,建筑,无人单位,极端重型,亚空间运算引擎
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='亚空间运算引擎')
deleteSelf: true
showMessageToPlayer: Эксплойт? Размечтался, в наказание лишний юнит сожрёт сервер눈_눈
addResources: 威胁点数=-600
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上

[hiddenAction_升级]
convertTo: 亚空间运算引擎
autoTrigger:if self.energy==200
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
addResources: energy=1000

[hiddenAction_特效]
autoTrigger:true
isVisible: false
spawnEffects: CUSTOM:闪光*4,CUSTOM:光粒*2,CUSTOM:光粒1*2

[decal_支撑]
image: 水下.png
total_frames: 1
layer: shadow
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.isOverLiquid and self.energy>100
#alpha:0.4

[decal_地板]
image: 地板.png
total_frames: 1
layer: shadow
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.energy>100

[decal_影子]
image: SHADOW:影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:8
xOffsetRelative:10
onlyWhileAlive:true

alpha:min(0.6,((0.6/100)*(self.resource.energy)))


[decal_主体]
image: 主体.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy>100
onlyWhileAlive:true
layer: onTop
teamColors: true


[decal_初始化]
image: 建造.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy<100 and not self.isOverLiquid
onlyWhileAlive:true
layer: onTop
alpha:(self.resource.energy)/100


[decal_初始化x]
image: 建造1.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy<100 and self.isOverLiquid
onlyWhileAlive:true
layer: onTop
alpha:(self.resource.energy)/100


[decal_初始化1]
image: 建造.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy>99.5 and not self.isOverLiquid
onlyWhileAlive:true
layer: onTop
alpha:1-(((self.resource.energy)-100)/100)

[decal_初始化x1]
image: 建造1.png
total_frames: 1
xOffsetAbsolute:0
yOffsetAbsolute:0
isVisible:if self.energy>99.5 and self.isOverLiquid
onlyWhileAlive:true
layer: onTop
alpha:1-(((self.resource.energy)-100)/100)

[decal_预览]
image: 造.png
total_frames: 1
layer: onTop
isVisible: true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.9
onlyInPreview:true
[graphics]
total_frames: 1
image: NO.png
image_wreak:死亡.png
image_back: NO.png
#drawLayer: experimentals
#icon_build:造.png
[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 0







[effect_震动]
createWhenOffscreen:true
drawType: displacement
image:震动.png
life:40
fadeOut: false
fadeInTime:50
attachedToUnit: true
scaleFrom:20
scaleTo:20
alpha:0.035
drawUnderUnits:false
alwayStartDirAtZero: true
total_frames: 2
animateFrameStart: 0
animateFrameEnd:1
animateFrameSpeed: 0.3
animateFrameLooping:true
showInFog: true
priority: critical


[effect_闪光]
image: SHARED:light_50.png
life: 40
fadeOut: true
attachedToUnit: false
color: #FF5BFF23
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
xOffsetRelative:0
yOffsetRelative:20
xOffsetRelativeRandom:120
yOffsetRelativeRandom:120
alpha:0.8
delayedStartTimerRandom:50

[effect_光粒]
color: #FF5BFF23
priority: veryhigh
spawnChance: 1
image: ROOT:/余辉军团/建筑特效/粒.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.7
scaleTo: 0.7
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.6
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.7
xSpeedRelativeRandom: 0.7
atmospheric: true
xOffsetRelative:0
yOffsetRelative:20
xOffsetRelativeRandom:70
yOffsetRelativeRandom:120
alpha:0.4
delayedStartTimerRandom:50

[effect_光粒1]
color: #FF5BFF23
priority: high
spawnChance: 1
image: ROOT:/余辉军团/建筑特效/粒.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 0.4
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.6
dirOffsetRandom: 360
ySpeedRelativeRandom: 1.4
xSpeedRelativeRandom: 1.4
atmospheric: true
xOffsetRelative:0
yOffsetRelative:20
xOffsetRelativeRandom:70
yOffsetRelativeRandom:120
alpha:0.4
delayedStartTimerRandom:50
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0

[ai]
buildPriority: 10
maxEachBase: 1
maxGlobal: 2
noneInBaseExtraPriority:100


