
[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_2]
displayName: 2
displayNameShort: 2
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_3]
displayName: 3
displayNameShort: 3
displayColor: #FF9D00FF
priority: 1
hidden: true
[core]
name: 支援型载具站t1
displayText: поддержка типстанция машинt1
class: CustomUnitMetadata
price: 3600
maxHp: 3000
maxShield: 3000
fogOfWarSightRange: 30
shieldRenderRadius: 1
shieldRegen: 0.5
armour: 8
footprint: -4,-3,4,5
constructionFootprint: -4,-3,4,5
displayDescription:【Уровень t2】【Беспилотный юнит】【Здание】【Наземный юнит】\n-тактическое назначение: многофункциональный завод, \n-не может строиться на воде.без вооружения\n-Станция вспомогательной техники - это особое комплексное здание,, \n-основное применение - на полях боя низкой интенсивности, как опорный пункт фронта, \n-Не только производит базовые юниты на месте,, \n-но также имеет пусковую установку капсул и допускает расширение малого ангара, \n-Эти здания эффективно поддерживают передовые части,, являясь важной опорой имперских войск на фронте.
tags: 地面,无人单位,建筑,自动
energyMax: 4
energyRegen: 0.009
energyNeedsToRechargeToFull: true
energyStartingPercentage: 1
techLevel: 1
buildSpeed: 14s
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*10
unitsSpawnedOnDeath: 建筑损毁(offsetHeight=0,offsetDir=0,addResources=电磁:1)
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 78
isBio: false
isBuilding: true
nanoFactorySpeed:1
exit_x:0
exit_y: 60
exit_moveAwayAmount: 110
canBuild_31_name: setRally
canBuild_31_pos: 0.0001
[action_升级]
convertTo: 支援型载具站t2
text: Улучшить
price: 3500
buildSpeed: 18s
ai_isHighPriority: true
highPriorityQueue: true
displayType: upgrade
description: повышениеподдержка типстанция машинуровень, добавитьтвёрдыйего оборонаобъекти использоватьего может производствочастьуровеньуровеньT3 юнит, \n-Улучшитьпозади ещё будетувеличениедобавитьсамзащитабоймашинабиблиотека,  и дальнийЗапустить Минный модуль, \n-Щитовая батарея функцияможет .
pos:0.0002
refundAllQueuedItems:true
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3')
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня


[canBuild_T1]
name: 筑基虫,SDAF灼光坦克,SDAF光矛,SDAF流星攻城炮,SDAF捍卫者,SDAF巨魔
pos: 1
isVisible: true


[decal_影子]
image: SHADOW:主体.png
total_frames: 1
layer: shadow
yOffsetRelative:6
xOffsetRelative:6
onlyWhileAlive:true
isVisible:true
alpha:0.6

[decal_光]
image: ROOT:/余辉军团/建筑特效/小重工光.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true

#isVisible: if self.maxHp * 0.36< self.hp
[decal_遮盖]
image: 主体.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:true
teamColors: true
[decal_损坏]
image: 损坏.png
total_frames: 1
layer: onTop
isVisible: if self.hp < self.maxHp * 0.36
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true



[decal_转子]
image: ROOT:/余辉军团/建筑特效/小重工转子.png
total_frames: 3
frame: (self.customTimer * 15) % 3
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-0.5
yOffsetAbsolute:-31
isVisible:true
onlyWhileAlive:true
layer: onTop

[decal_光线]
image: LED.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp

alpha:0.8

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
#isVisible:if self.shield>self.maxShield*0.03
yOffsetRelative:0
xOffsetRelative:-0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 3.5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1



[graphics]
total_frames: 1
image: 主体.png
image_back: 小重工地板.png
image_wreak:ROOT:/余辉军团/建筑特效/小重工死亡.png
image_shadow: NONE
showShotDelayBar:false
[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0
maxAttackRange: 0
turretTurnSpeed: 50
turretMultiTargeting: true


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0



[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.25
scaleTo: 0.44
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 60
yOffsetRelativeRandom: 100
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/余辉军团/建筑特效/小群爆.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.38
alsoPlaySound: ROOT:/通用特效/建筑倒塌.wav
dirOffsetRandom: 180
xOffsetRelative: 0
yOffsetRelative: 0
xOffsetRelativeRandom:70
yOffsetRelativeRandom:120
delayedStartTimerRandom:30

[ai]
buildPriority: 0.08
ai_upgradePriority: 0.07
maxEachBase: 3
maxGlobal: 5
noneInBaseExtraPriority:0.15
upgradedFrom: 支援型载具站空投
