

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}
[core]
name:战争使徒
displayText: Апостол Войны
price: 5400
maxHp: 2000
maxShield: 9000
shieldRenderRadius: 52
shieldRegen: 0.15
displayDescription: 【Уровень t4】【Преодолевает утёсы】【Беспилотный юнит】【Наземный юнит】тактическое назначение: тяжёлый универсальный мех, не может транспортироваться.\n-вооружение:▲автоматический ракетомётX1 только по земле взрывной урон слабо эффективен против щитов, \n-▲ пусковая плазменных шиповX1 только по земле энергетический урон усиленный урон по щитам, \n-▲лазерная установка ближнего бояx1 только по воздуху энергетический урон, \n-▲блок плавающих пушекX2 по земле и воздуху энергетический урон\n-Апостол Войныпоздний период Войны Государств эпохи Древних Людей, для Империясухопутные войскаспециальныйдверьустановкарасчёт в  типштурммехов, \n-от компания Зетанояосновак семья Файад многовидподъёмслучайразработка, а приходит .\n-поэтому, этотмашина типединицаимеет густойтолстый тяжёлый огневая мощьустановкарасчёт.\n-Апостол Войныможет называтьвооружениек зубы, кромеодиндверьогневая мощькрайнедля огромный автоматический ракетомётчтобы снаружи , \n-ещё оснащёнимеет плавающая пушкаблок и пусковая плазменных шиповиспользует к компенсацияглавныйоружие огневая мощьмеждущель.\n-ммнет вопрос, Апостол Войныэто Империясухопутные войскав сильный механическийбойвоин, \n-они в один раз также один раз идтидвижениев для Его Величество Императороткрытьрасширение территорииземля.
effectOnDeath:CUSTOM:小型余晖死亡冲击波,CUSTOM:小型余晖死亡爆炸,CUSTOM:小型余晖死亡钢珠,CUSTOM:小型余晖死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
techLevel: 1
fogOfWarSightRange: ${int(attack.maxAttackRange/17.5)}
buildSpeed: 17s
radius: 52
displayRadius: 52
armour: 25
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
transportSlotsNeeded: 6000
tags: 地面,无人单位,战争使徒
maxTransportingUnits: 2
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 浮游炮
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]



[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯

[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 2
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 3s
requireConditional: if memory.灰机 < 2
addUnitsIntoTransport: 浮游炮
whenBuilding_cannotMove: false

[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1

[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)

[hiddenAction_创造]
autoTrigger: if attachment(slot= 'b1') == nullUnit
attachments_onlyOnSlots: b1
attachments_addNewUnits: 检测中介ty(addResources= ammo: 545 | setFlag= 0)
[attachment_b1]
x: 0
y: 0
onCreateSpawnUnitOf: 检测中介ty(addResources= ammo: 545 | setFlag= 0-1)
# 600是检测范围，0：对地，1：对空，2：反潜
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
[attachment_2]
x: 0
y: 0
onCreateSpawnUnitOf: 通用挂载附属1
lockRotation: true
prioritizeParentsMainTarget: true
alwaysAllowedToAttackParentsMainTarget: true
[attachment_drone1]
x: 29
y: -30
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false
addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
prioritizeParentsMainTarget: false
alwaysAllowedToAttackParentsMainTarget: false
lockRotation: true
idleDir: 145
height: 1
[attachment_drone2]
@copyFromSection: attachment_drone1
x: -29
y: -30
idleDir: -145
[action_a]
autoTrigger: if self.numberOfAttachedUnits(withTag= "ANM_cat", lessThan= 0.5)
isVisible: false
alsoQueueAction: b
stopLastAnimation: true
[action_b]
convertTo: 战争使徒1
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
convertTo_keepCurrentTags:true
convertTo_keepCurrentFields:maxHp,moveSpeed,maxTurnSpeed
temporarilyAddTags:迎敌

#--------—-----------——---------影子

[decal_影子1]
image: SHADOW:机体.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:-3
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_11
[decal_影子2]
image: SHADOW:主炮ax.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:7
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_5
[decal_影子3]
image: SHADOW:主炮av.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
basePositionFromLegEnd: arm_6
[decal_影子5]
image:射线.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:67
xOffsetRelative:-8
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_6
#--------—-----------——---------炮损坏
[decal_炮损坏]
layer: onTop
image: 主炮损坏1.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_5
isVisible: if self.hp < self.maxHp * 0.36
[decal_炮损坏1]
layer: onTop
image: 主炮损坏.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_6
isVisible: if self.hp < self.maxHp * 0.36
#--------—-----------——---------炮灯
[decal_炮灯]
image:炮灯.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_6
#--------—-----------——---------主体损坏
[decal_主体损坏a]
layer: onTop
image: 机体损坏.png
onlyWhileAlive: true
teamColors: true
basePositionFromLegEnd: arm_11
isVisible: if self.hp < self.maxHp * 0.36
alpha:0.8
#--------—-----------——---------机体灯
[decal_机体灯]
image:机体灯.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_11
#--------—-----------——---------遮盖
[decal_头]
image:头.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_12
[decal_肩]
image:肩.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_13
[decal_雷达]
image:雷达.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_14
#--------—-----------——---------头灯
[decal_头灯]
image:头灯.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
basePositionFromLegEnd: arm_12
[graphics]
image: NO.png
image_wreak: 死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 7
image_shield: NO.png
shadowOffsetY: 7
teamColorsOnTurret: true
lock_body_rotation_with_main_turret: true
lock_leg_rotation_with_main_turret: true
#imageScale: 0.85
showQueueBar: false

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 2
maxAttackRange: 500
shootDelay: 100
turretRotateWithBody: true
isFixedFiring: true

turretMultiTargeting: true



[turret_1]
x: 0
y: 0
canShoot: false
invisible: true
canAttackFlyingUnits: false
canOnlyAttackUnitsWithoutTags:高空

[arm_1]
x: 29
y: -30
image_end: 炮.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 145
hidden:if attachment(slot= 'drone1') == nullUnit
[arm_2]
x: -29
y: -30
image_end: 炮.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -145
hidden:if attachment(slot= 'drone2') == nullUnit
[arm_3]
x: -20
y: 29
image_end: 把手.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -150

[arm_4]
x: -5
y: 41
image_end: 主炮炮管.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -65
[arm_5]
x: -5
y: 41
image_end: 主炮ax.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -65
[arm_6]
x: -5
y: 41
image_end: 主炮av.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -65
[arm_7]
x: -35
y: 25
image_end: 左手.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 16
[arm_8]
x: -32
y: 14
image_end: 小臂.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -25
[arm_9]
x: 42
y: 11
image_end: 右手.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -25
[arm_10]
x: 37
y: 6
image_end: 小臂.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: 35
[arm_11]
x: 0
y: 3
image_end: 机体.png
image_end_teamColors: true
drawOverBody: true

drawDirOffset: 0
[arm_12]
x: 0
y: -2
image_end: 头.png
image_end_teamColors: true
drawOverBody: true

#drawDirOffset: 45


[arm_13]
x: -22
y: -42
image_end: 肩.png
image_end_teamColors: true
drawOverBody: true

[arm_14]
x: 22
y: -42
image_end: 雷达.png
image_end_teamColors: true
drawOverBody: true

[leg_1]
x: -19
y: 14
attach_x: -5
attach_y: 0
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚丫.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 19
y: 14
attach_x: 5
attach_y: 0
copyFrom: 1

drawDirOffset: 10

[animation_部署]
#onActions: attack
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}

arm3_0.3s: {x:20, y:30, dir:70}

arm1_0.6s: {x:-17, y:-9, dir:25}
arm2_0.6s: {x:-10, y:10, dir:25}
arm3_0.6s: {x:26, y:36, dir:150}
arm4_0.6s: {x:28, y:-4, dir:65}
arm5_0.6s: {x:28, y:-4, dir:65}
arm6_0.6s: {x:28, y:-4, dir:65}
arm7_0.6s: {x:16, y:12, dir:0}
arm8_0.6s: {x:10, y:8, dir:20}
arm9_0.6s: {x:6, y:-11, dir:0}
arm10_0.6s: {x:6, y:-11, dir:0}
arm11_0.6s: {x:0, y:0, dir:25}
arm12_0.6s: {x:0, y:0, dir:0}
arm13_0.6s: {x:-16, y:12, dir:0}
arm14_0.6s: {x:-22, y:-6, dir:0}

[animation_实验]

arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm7_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}

arm1_0.25s: {x:-1.5, y:-2.5, dir:3}
arm2_0.25s: {x:-1, y:0, dir:3}
arm3_0.25s: {x:0, y:0, dir:8}

arm4_0.25s: {x:0, y:1, dir:2}
arm5_0.25s: {x:0, y:1, dir:2}
arm6_0.25s: {x:0, y:1, dir:2}

arm7_0.25s: {x:1, y:1, dir:0}
arm8_0.25s: {x:1, y:1, dir:0}

arm9_0.25s: {x:0, y:-2, dir:0}
arm10_0.25s: {x:0, y:-2, dir:0}

arm11_0.25s: {x:0, y:0, dir:3}
arm12_0.25s: {x:0, y:0, dir:0}

arm13_0.25s: {x:-2, y:1, dir:0}
arm14_0.25s: {x:-2, y:-1, dir:0}

arm1_0.5s: {x:0, y:0, dir:0}
arm2_0.5s: {x:0, y:0, dir:0}
arm3_0.5s: {x:0, y:0, dir:0}
arm4_0.5s: {x:0, y:0, dir:0}
arm5_0.5s: {x:0, y:0, dir:0}
arm6_0.5s: {x:0, y:0, dir:0}
arm7_0.5s: {x:0, y:0, dir:0}
arm8_0.5s: {x:0, y:0, dir:0}
arm9_0.5s: {x:0, y:0, dir:0}
arm10_0.5s: {x:0, y:0, dir:0}
arm11_0.5s: {x:0, y:0, dir:0}
arm12_0.5s: {x:0, y:0, dir:0}
arm13_0.5s: {x:0, y:0, dir:0}
arm14_0.5s: {x:0, y:0, dir:0}

arm1_0.75s: {x:1.5, y:2.5, dir:-3}
arm2_0.75s: {x:1, y:0, dir:-3}

arm3_0.75s: {x:0, y:0, dir:-8}
arm4_0.75s: {x:0, y:-1, dir:-2}
arm5_0.75s: {x:0, y:-1, dir:-2}
arm6_0.75s: {x:0, y:-1, dir:-2}

arm7_0.75s: {x:-1, y:-1, dir:0}
arm8_0.75s: {x:-1, y:-1, dir:0}
arm9_0.75s: {x:0, y:2, dir:0}
arm10_0.75s: {x:0, y:2, dir:0}

arm11_0.75s: {x:0, y:0, dir:-3}
arm12_0.75s: {x:0, y:0, dir:0}

arm13_0.75s: {x:2, y:-1, dir:0}
arm14_0.75s: {x:2, y:1, dir:0}

arm1_1s: {x:0, y:0, dir:0}
arm2_1s: {x:0, y:0, dir:0}
arm3_1s: {x:0, y:0, dir:0}
arm4_1s: {x:0, y:0, dir:0}
arm5_1s: {x:0, y:0, dir:0}
arm6_1s: {x:0, y:0, dir:0}
arm7_1s: {x:0, y:0, dir:0}
arm8_1s: {x:0, y:0, dir:0}
arm9_1s: {x:0, y:0, dir:0}
arm10_1s: {x:0, y:0, dir:0}
arm11_1s: {x:0, y:0, dir:0}
arm12_1s: {x:0, y:0, dir:0}
arm13_1s: {x:0, y:0, dir:0}
arm14_1s: {x:0, y:0, dir:0}

[movement]
movementType: OVER_CLIFF
moveSpeed: 0.8
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.17
maxTurnSpeed: 1.5

turnAcceleration: 0.08
targetHeight: 1
moveSlidingMode : false
moveIgnoringBody: true
reverseSpeedPercentage: 0
slowDeathFall: true

[resource_电磁]
displayName: электромагнетизм
displayNameShort: электромагнетизм
displayColor: #FF9D00FF
priority: 1
hidden: true
