


[core]
name: 浮游炮
displayText: плавающая пушка
class: CustomUnitMetadata
displayDescription: -😡
price: 1
maxHp: 2400
shieldRegen: 0.1
techLevel: 1
buildSpeed: 0s
availableInDemo: true
showInEditor: false
fogOfWarSightRange: 22
radius: 10
displayRadius: 10
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 35
energyMax: 60
energyRegen: 0
energyNeedsToRechargeToFull: true
tags: 飞机,低空,浮游炮,寄生免疫,伴生单位,无人单位
canNotBeGivenOrdersByPlayer: true
energyStartingPercentage: 1
logIfCreditResourceUsed: true



[decal_喷火]
image: ROOT:/余辉军团/建筑特效/喷火.png
total_frames: 4
frame: (self.customTimer * 30) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:0
yOffsetRelative:-36
isVisible: if self.isMoving()
layer: onTop
onlyWhileAlive:true
imageScale:0.5

[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'


[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'


[hiddenAction_return]
autoTrigger: if not self.hasActiveWaypoint(type= 'loadInto') and not self.hasParent
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto


[hiddenAction_return1]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( self.energy < 0.9 or distanceBetweenSquared(self, customTarget1) > 810000 )
# distanceBetweenSquared 返回两个单位之间的平方距离。 比 distanceBetween 快一点，因为少了开方这一步。1000² 判断灰机离母体有多远，超过1000回家
# 因为是attackMove，所以没必要写 检测被攻击单位血量
clearActiveWaypoint: true
addWaypoint_target_fromReference: customTarget1

addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto


[hiddenAction_disconnect]
requireConditional: if self.hasParent and self.isEnergyFull and not self.hasActiveWaypoint(type= 'attackMove')

disconnectFromParent: true
addWaypoint_target_fromReference: attacking
addWaypoint_type: attackMove

addWaypoint_triggerActionIfMatched: return


[hiddenAction_energy]
autoTriggerOnEvent: enteredTransport
addResources:energy=61


[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
# 这条在鹰爪和雪崩里忘改成这样了，原本是打算航母凉后灰机用完能量才自杀，不过有bug忘了改回来
addResources: hp= -999999
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[graphics]
total_frames: 1
image: 炮.png
image_wreak: 炮死亡.png
image_turret: NONE
imageScale: 1
image_shadow: AUTO

[attack]
canAttack:true
canAttackFlyingUnits: if self.isInMap
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
turretSize: 20
maxAttackRange: 900
isFixedFiring: true


[turret_1]
x: 0
y: 10
canShoot: true
invisible:true
shoot_sound: ROOT:/余辉军团/单位特效/命中.wav
shoot_sound_vol: 0.2
shoot_flame: CUSTOM:发射闪光
shoot_light: #FF00B3FF
delay: 60
size:17
projectile: beam0
energyUsage:3
aimOffsetSpread:0
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
canOnlyAttackUnitsWithoutTags:高空
warmup:2
limitingRange: 345
[turret_233]
x: 0
y: 0
# limitingRange: 580
projectile: 233
warmup: 1s

delay: 0.9s
canAttackMaxAngle: 181
canAttackCondition: if self.energy(full= true) and self.hasParent()
canAttackFlyingUnits: true
canAttackLandUnits: true

canAttackUnderwaterUnits: false
invisible: true
onShoot_triggerActions: disconnect


[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true

[projectile_beam0]
@copyFromSection: template_能源
explodeEffect: CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:冲击波gd,CUSTOM:爆炸2gd
explodeEffectOnShield: CUSTOM:爆炸gd, CUSTOM:闪光gd,CUSTOM:冲击波gd,CUSTOM:爆炸2gd
directDamage: 450
life: 3
instant: true
moveWithParent: true
beamImage: ROOT:/通用特效/6.png
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
delayedStartTimer:0
[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/5.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/4.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/3.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/2.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/1.png
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE
spawnProjectilesOnEndOfLife: NONE




#———————————————轨道炮
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.4
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
[effect_爆炸2gd]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.9
color: #FF00B3FF

[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.43
scaleTo: 0.43
image: ROOT:/余辉军团/单位特效/爆.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
[effect_发射闪光]
priority:low
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: true
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 1.2
scaleTo: 0.1
drawUnderUnits: false
atmospheric: false
[effect_闪光gd]
priority:low
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 1
drawUnderUnits: true
atmospheric: false
[effect_冲击波gd]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.65
alpha: 0.8
drawUnderUnits: false
atmospheric: false




[movement]
movementType: AIR
moveSpeed: 4
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.06
targetHeight: 70
targetHeightDrift: 2
maxTurnSpeed: 3.5
turnAcceleration: 0.4
startingHeightOffset: 1000
moveSlidingMode : true
moveIgnoringBody: false
slowDeathFall: true


