



[core]
name: 阿特拉斯级运输船
displayDescription: 【阶级t4】【水陆两栖】【地面单位】【机械单位】【悬浮单位】【无武装】【工程单位】【极端重型单位】\n-战术定位:重型舰船建造者，可以建造超战舰，噬海女妖级战略核潜艇，\n-战列要塞，复仇女神级航空母舰。\n-创世纪为了满足战略需求，制造过的最为巨大的水陆两栖单位。\n-阿特拉斯级由科普斯军事公司在战前立项开发，并恰好在战后最缺乏运力的时候完成部署。\n-阿特拉斯能运输战略级数量的燃料，粮食，武器弹药远渡重洋，\n-又或者搭载创世纪超级战舰的巨型零件并完成初步组装，\n-毫不夸张的说，除了某些过于巨大的单位外，在创世纪军团中几乎没有阿特拉斯级装不下的东西。
price: 10000
maxHp: 20000
techLevel: 1
buildSpeed: 45s
radius: 100
displayRadius: 100
tags: 地面,极端重型,悬浮
isBio: false
selfRegenRate: 0.8
transportSlotsNeeded: 120
armour: 140
softCollisionOnAll: 25
copyFrom: ROOT:/通用特效/单位防护.ini
canRepairBuildings: true
canRepairUnits : true
nanoRange: 20
nanoRepairSpeed: 1
dieOnConstruct: true
unitsSpawnedOnDeath: 大型水上单位死亡*1
#————————————改造
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[decal_改造]
image:  ROOT:/创世纪军事集团/单位特效/左围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:-50
xOffsetRelative:-85
onlyWhileAlive:true

[decal_改造1]
image:  ROOT:/创世纪军事集团/单位特效/左围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:25
xOffsetRelative:-70
onlyWhileAlive:true

[decal_改造2]
image:  ROOT:/创世纪军事集团/单位特效/左围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:95
xOffsetRelative:-75
onlyWhileAlive:true

[decal_改造3]
image:  ROOT:/创世纪军事集团/单位特效/右围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:-50
xOffsetRelative:85
onlyWhileAlive:true

[decal_改造4]
image:  ROOT:/创世纪军事集团/单位特效/右围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:25
xOffsetRelative:70
onlyWhileAlive:true

[decal_改造5]
image:  ROOT:/创世纪军事集团/单位特效/右围挡.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:95
xOffsetRelative:75
onlyWhileAlive:true

[decal_支架]
image:  ROOT:/创世纪军事集团/单位特效/吊臂.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:95
xOffsetRelative:-46
onlyWhileAlive:true
dirOffset:65

[decal_支架1]
image:  ROOT:/创世纪军事集团/单位特效/吊臂.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:20
xOffsetRelative:-40
onlyWhileAlive:true
dirOffset:90

[decal_支架2]
image:  ROOT:/创世纪军事集团/单位特效/吊臂.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:-50
xOffsetRelative:50
onlyWhileAlive:true
dirOffset:-45

[decal_支架3]
image:  ROOT:/创世纪军事集团/单位特效/吊臂.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '模块化改造')
yOffsetRelative:30
xOffsetRelative:38
onlyWhileAlive:true
dirOffset:-90

[action_变形]
displayType: action
price: 2500
buildSpeed: 0s

playSoundAtUnit:  ROOT:/通用特效/部署.ogg
text: 改装为MK2
isLocked: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or self.isOverLiquid
isVisible:if not self.tags(includes= '模块化改造') and self.globalTeamTags(includes='模块化技术')
alsoQueueAction: 变形1
descriptionAddFromUnit:阿特拉斯级运输船MK2
descriptionAddUnitStats: 阿特拉斯级运输船MK2
temporarilyAddTags:模块化改造
iconImage: ROOT:/创世纪军事集团/单位特效/模块生产.png
setUnitStats:targetHeight=0
[action_变形1]
convertTo:阿特拉斯级运输船MK2
displayType: action
price: 0
buildSpeed: 25s
isVisible: false

highPriorityQueue: true
whenBuilding_cannotMove: true
convertTo_keepCurrentTags:true
temporarilyRemoveTags:模块化改造,↯
addResources:加血保险=-2
refundAllQueuedItems:true
setResourcesWithLogic: xk=0

[action_重]
text: 极端重型单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积夸张的单位独有的特性，\n-拥有极端重型单位标签的单位将拥有如下属性，\n-拥有自愈能力，且自身护甲不低于100点，\n-无法被休克，但是受到反重甲单位伤害增益。
[canBuild_1]
name: 建造战列要塞
pos: 1
forceNano: true
isLocked: if not self.globalTeamTags(includes='材料技术4')
isLockedMessage: 你需要先进材料技术
isVisible:if not self.tags(includes= '模块化改造')
[canBuild_2]
name: 建造超战舰
pos: 1.5
forceNano: true
isLocked: if not self.globalTeamTags(includes='轨道发射器3') or not self.globalTeamTags(includes='超导技术2')or not self.globalTeamTags(includes='材料技术3')
isLockedMessage: 你需要轨道发射器3，材料技术3和先进超导技术
isVisible:if not self.tags(includes= '模块化改造')
[canBuild_3]
name: 建造噬海女妖级战略核潜艇
pos: 2
forceNano: true
isLocked: if not self.globalTeamTags(includes='弹道导弹技术2') or not self.globalTeamTags(includes='基础科学进步1')or not self.globalTeamTags(includes='材料技术4')
isLockedMessage: 你需要便携式弹道导弹技术，先进材料技术和基础科学进步
isVisible:if not self.tags(includes= '模块化改造')
[canBuild_4]
name: 建造复仇女神级航空母舰
pos: 3
forceNano: true
isLocked: if not self.globalTeamTags(includes='纳米煅炉') or numberOfUnitsInTeam(greaterThan=0, withTag='复仇女神')
isLockedMessage: 你需要模块化纳米煅炉，或者已经拥有复仇女神级航空母舰。
isVisible:if not self.tags(includes= '模块化改造')
[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 7
shadowOffsetY: 7
teamColorsOnTurret: true
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 12

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 3

maxAttackRange: 10

[arm_1]
x: -64
y: -41.5
image_end:大风扇.png
image_end_teamColors: true
drawOverBody: true
spinRate:14
[arm_2]
x: -26
y: 116.5
image_end:大风扇.png
image_end_teamColors: true
drawOverBody: true
spinRate:14
[arm_3]
x: 64
y: -41.5
image_end:大风扇.png
image_end_teamColors: true
drawOverBody: true
spinRate:-14
[arm_4]
x: 26
y: 116.5
image_end:大风扇.png
image_end_teamColors: true
drawOverBody: true
spinRate:-14
[arm_5]
x: -50
y: -101
image_end:小风扇.png
image_end_teamColors: true
drawOverBody: true
spinRate:20
[arm_6]
x: 50
y: -101
image_end:小风扇.png
image_end_teamColors: true
drawOverBody: true
spinRate:-20
[arm_7]
x: 0
y: 0
image_end:遮盖.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_8]
x: 0
y: 0
image_end:灯光.png
#image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_9]
x: 0
y: 0
image_end:损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_10]
x: -11
y: -84.5
image_end:雷达.png
image_end_teamColors: true
drawOverBody: true
spinRate:5
[arm_11]
x: 0
y: 80
image_end:吊车.png
image_end_teamColors: true
drawOverBody: true
[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
life: 130
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 3
scaleTo:9
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -70
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
createWhenOverLiquid: true
createWhenOverLand: false
[effect_火]
life: 140
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1.2
scaleTo: 4.5
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1
yOffsetRelative	: -20
drawUnderUnits: true
createWhenOverLiquid: true
createWhenOverLand: false
[animation_1]
onActions: idle
arm11_0s: {x:0, y:0}
arm11_4s: {x:0, y:-20}
arm11_11s: {x:0, y:0}
[movement]
movementType: HOVER
moveSpeed: 0.72
moveAccelerationSpeed: 0.02
moveDecelerationSpeed: 0.03
maxTurnSpeed: 0.5
turnAcceleration: 0.02
targetHeight: 3
targetHeightDrift: 1
moveSlidingMode : false
moveIgnoringBody: true


