


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}


[core]
name: SDSF方舟级运输舰
displayText: SDSFнаправлениелодкауровеньтранспорткорабль
displayDescription: -направлениелодкауровеньтранспорткорабльэто ИмперияоченьВВСв год龄самыйбольшой  военный корабль, нетимеет среди , \n-направлениелодкауровеньтранспорткораблькогда-то делатьдля Древние Люди"阿尔башнявнутри мир"расчётразрез самыйконецпроизводствообъект, будетДревние Людиогоньвид带往космос.\n-следоватьгодэра толкатьперемещение, носительтоварколичествоогромный и оченьпрочный направлениелодкауровеньчертёжДревние Людиэраэравзаимный传.\n-потому чтодля честныйцена,  и технологияоченьоригиналначалопростойодиночный, нет теорияАравелидещё это Империя Новавсе Имея большой количество направлениелодка, \n-текущийнапример сейчасэтот份может 观 遗производствотогда隶属к Заревостратегическийтранспортвойска, они может одновременнотранспортобъектресурс и смерть.\n-по земле и воздуху, энергетический урон, против укрытий, может транспортвосемь格наземные юниты на пути, может производствобазовыйюнит.
class: CustomUnitMetadata
maxShield: 3000
shieldRegen: 0.4

price: 6000
maxHp: 2000
shieldDisplayOnlyDeflection: true
techLevel: 1
buildSpeed: 30s

availableInDemo: true
radius: 70
shieldRenderRadius: 42
displayRadius: 70
maxTransportingUnits: 8

copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
#transportSlotsNeeded: 20
effectOnDeathGroundCollision: CUSTOM:爆炸x*1
tags: 飞机,低空,无人单位

softCollisionOnAll: 20
armour: 10
fogOfWarSightRange: 20
nanoFactorySpeed: 1
transportUnitsKeepBuiltUnits: true
canBuild_1_name: SDAF预兆
canBuild_1_pos: 1
canBuild_2_name: SDAF冲击波
canBuild_2_pos: 2
canBuild_3_name: SDAF猎户座
canBuild_3_pos: 3
canBuild_4_name: HK死亡之雨
canBuild_4_pos: 4
canBuild_5_name: HK铁骑
canBuild_5_pos: 5
canBuild_6_name: HK清道夫
canBuild_6_pos: 6
[hiddenAction_地上]
autoTrigger: if not self.tags(includes= '地面') and not self.flying
isVisible: false
temporarilyAddTags:地面
temporarilyRemoveTags:飞机
[hiddenAction_天上]
autoTrigger: if self.tags(includes= '地面') and self.flying
isVisible: false
temporarilyAddTags:飞机
temporarilyRemoveTags:地面
[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
text: Позитронное ядро
displayType: infoOnlyNoBox

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=550, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=550, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false

[attachment_1]
x: 0
y: 0
canAttack:false
addTransportedUnits: true
hidden: true
setDrawLayerOnBottom:true
[attachment_2]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_3]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_4]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_5]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_6]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_7]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_8]
@copyFromSection: attachment_1
x: 0
y: 0

[graphics]
total_frames: 3
image: 身体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4
image_shield: 护盾.png
turretImageScale: 0.9

movementEffect: CUSTOM:火1,CUSTOM:火2,CUSTOM:火3
movementEffectRate: 1.5
animation_moving_start: 2
animation_moving_end: 2
animation_moving_speed: 8

animation_idle_start: 0
animation_idle_end: 1
animation_idle_speed: 3


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 340
shootDelay: 0


[turret_1]
x: 0
y: 12
image: 管.png
attachedTo: 2
slave: true

shoot_sound: ROOT:/余辉军团/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_flame: NONE
shoot_light: #FFccCCEE
projectile: 1

limitingAngle: 150
delay: 5
canAttackLandUnits: false
recoilOffset: -1
size: 4


[turret_2]
x: -30
y: -35
canShoot: false
image: 枪.png
idleDir: -45

#delay:180
limitingAngle: 150
canAttackLandUnits: false


[turret_3]
x: 0
y: 12
image: 管.png
attachedTo: 4
slave: true

shoot_sound: ROOT:/余辉军团/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_flame: NONE
shoot_light: #FFccCCEE
projectile: 1

limitingAngle: 150
delay: 5
canAttackLandUnits: false
recoilOffset: -1
size: 4


[turret_4]
x: 30
y: -35
canShoot: false
image: 枪.png
idleDir: 45

#delay:180
limitingAngle: 150
canAttackLandUnits: false


[turret_5]
x: 13
y: 42
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FF00B3FF

shoot_flame: CUSTOM:气浪*1
image: 炮.png
delay: 30
projectile: 2
size: 5

limitingAngle: 45
idleDir: 90


[turret_6]
x: -13
y: 42
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FF00B3FF

shoot_flame: CUSTOM:气浪*1
image: 炮.png
delay: 30
projectile: 2
size: 5

limitingAngle: 45
idleDir: -90


[projectile_1]
@copyFromSection: template_能源
directDamage: 25
life: 70
image: ROOT:/余辉军团/单位特效/双枪.png
drawSize: 0.5

speed: 9
targetSpeed: 9
explodeEffect: CUSTOM:火花
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
@copyFromSection: template_能源
directDamage: 70
life: 10
instantReuseLast: true
beamImage: SHARED:beam3.png

beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true

color: #FF00B3FF
lightColor: #FF004AFF
lightSize: 0.1
explodeEffect: CUSTOM:爆炸2,CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸2,CUSTOM:闪光
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_爆炸2]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1.3
scaleTo: 0.4
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2


[effect_火2]
life: 45
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 20
yOffsetRelative	: -74


[effect_火1]
life: 45
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 4

scaleTo: 1
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: -20
yOffsetRelative	: -74


[effect_火3]
life: 48
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 8

scaleTo: 3
image: ROOT:/通用特效/蓝火.png
alpha: 0.8
total_frames: 4
animateFrameStart: 0

animateFrameEnd: 3
animateFramePingPong: false
animateFrameSpeed: 0.3
xOffsetRelative	: 0
yOffsetRelative	: -122


[effect_气浪]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 30
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 0.8
alpha: 2
drawUnderUnits: false
atmospheric: false


[effect_爆炸x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/余辉军团/单位特效/爆炸25.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[arm_1]
x: -19
y: 42
image_end: 左.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_2]
x: 19
y: 42
image_end: 右.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[arm_3]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:19, y:0}
arm1_950s: {x:19, y:0}
arm2_1s: {x:-19, y:0}

arm2_950s: {x:-19, y:0}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}


[movement]
movementType: AIR
moveSpeed: 0.9
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.03
startingHeightOffset: 2000

fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0.4
landOnGround: onlyIdle
maxTurnSpeed: 1
turnAcceleration: 0.05

targetHeightDrift: 0.3
slowDeathFall: true
targetHeight: 70


[ai]
buildPriority: 0.9


