


[core]
name: 太空浪人多相聚变堆t1
displayText: Многофазный термоядерный реактор Скитальцев t1
class: CustomUnitMetadata
displayDescription: 相信没有人比太空浪人对核聚变反应更为了解，\n-多相聚变堆可以将聚变反应进行到最终阶段，\n-产生大量能量并通过无线充电原理给建筑供能。
price: 900
maxHp: 2000

footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1
techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 3s

isBio: false
#showInEditor:false
isBuilding: true
selfRegenRate: 0.12
radius: 20

effectOnDeath: CUSTOM:冲击波, CUSTOM:爆炸,CUSTOM:闪光
tags: 聚变堆,d,地面,灰影建筑,建筑
#armour:7
buildingToFootprintOffsetY: -5


[action_升级为被感染的聚变堆]
convertTo: 被感染的聚变堆
displayType: action
text: Улучшить до заражённого термоядерного реактора
price: hy=2700
buildSpeed: 18s

isVisible: if self.globalTeamTags(includes='灰影1')
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, и одновременно можно выбрать только одно улучшение
ai_isHighPriority: true
description: Покрыть многофазный термоядерный реактор вирусом «Серая Тень». В дополнение к питанию,\n-он будет давать всем своим юнитам и зданиям в радиусе питания +35% к урону\n-и восстанавливать 25 здоровья в секунду. Не складывается.


[action_升级为折越聚变堆]
convertTo: 折跃门聚变堆
displayType: action
text: Улучшить до реактора с порталом прыжка
price: 8100
buildSpeed: 25s

isVisible: if self.globalTeamTags(includes='灰影1')
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, и одновременно можно выбрать только одно улучшение
ai_isHighPriority: true
description: Позволит ближайшим заводам Скитальцев, производящим механические юниты, включить режим прыжка,\n-что позволит развёртывать порталы в любом месте с полем телепортации и быстро перебрасывать юнитов.\n-Это значительно увеличит производительность и сэкономит время в пути.
ai_isDisabled: true

[action_升级为堡垒聚变堆]
convertTo: 堡垒聚变堆
displayType: action
text: Улучшить до бастионного термоядерного реактора
price: 3900
buildSpeed: 35s

isVisible: if self.globalTeamTags(includes='灰影1')
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t3') or self.queueSize(greaterThan= 0.5)
isLockedMessage: Требуется Узел уровня 3, и одновременно можно выбрать только одно улучшение
ai_isHighPriority: true
description: Бастионный термоядерный реактор отлит из укреплённого суперсплава, обладает поразительной устойчивостью к ударам.\n-Также имеет встроенную систему варп-пушки, что делает его ещё сложнее уничтожить.\n-Атакует землю и воздух, энергетический урон.


[action_升级]
convertTo: 太空浪人多相聚变堆t2
displayType: upgrade
text: Улучшить
price: 600
pos: 0.05

buildSpeed: 22s
isLocked: if self.noUnitInTeam(withTag= '太空浪人枢纽t2')
isLockedMessage: Требуется Узел уровня 2
ai_isHighPriority: true
description: Усилить ключевые части термоядерного реактора пластинами суперсплава, что затрудняет его уничтожение.


[action_T1]
pos: 0
buildSpeed: 0s
addResources: setFlag=0,setFlag=1
isVisible: if not self.hasFlag(id=1) and not self.hasFlag(id=0)
text: Показать радиус питания


[action_T1_back]
pos: 0
buildSpeed: 0s
addResources: unsetFlag=0,unsetFlag=1
isVisible: if self.hasFlag(id=1)
text: Скрыть радиус питания


[graphics]
total_frames: 19
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
image_back: ROOT:/通用特效/NO.png

animation_idle_start: 0
animation_idle_end: 18
animation_idle_speed: 8
imageScale: 0.95
image_shadow: 影子.png


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 400

turretSize: 0
turretTurnSpeed: 50


[turret_光圈2]
x: 0
y: 0
canShoot: false
invisible: if self.isControlledByAI()or not self.hasFlag(id=1)
size: 1

image: ROOT:/太空浪人/建筑特效/光圈2.png


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.1

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_爆炸]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5

scaleTo: 1.5
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 7
scaleTo: 7

drawUnderUnits: true
atmospheric: false


[arm_1]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

lockMovement: true
hidden: if self.hp(greaterThan=720)


[arm_2]
x: 0
y: 0
image_end: 底座.png
image_end_teamColors: true
drawUnderAllUnits: true

drawOverBody: false
lockMovement: true
hidden: if not self.isOverLiquid


[ai]
upgradedFrom: 太空浪人多相聚变堆t1传送
ai_upgradePriority: 0.07


