


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources:威胁点数=120,ry= ${ryxq}
[action_拆除哇袄]
addResources: 威胁点数=-120
[core]
name: 余辉行星防御系统t1
displayDescription: 余辉先进的行星防御系统，负责链接整个轨道防空网，\n-当检测到来袭威胁时，可以直接从轨道设施暂时接收强大的能量，\n-并瞬间展开一面定向短时效克莱因瓶包裹目标而实现拦截，\n-同时又可向轨道设施传达坐标实现轨道打击。\n-只能拥有四座。战略武器防御，只能对地，能源伤害。
class: CustomUnitMetadata
price: 6000,ry= ${ryxq}
@global ryxq:20
reclaimPrice: ry= ${ryxq}
maxHp: 10000

footprint: -3,-2,3,2
constructionFootprint: -3,-2,3,2
armour: 40
techLevel: 1
buildSpeed: 45s

radius: 60
showInEditor: false
maxShield: 8000
shieldRegen: 0.09
displayRadius: 60

copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
shieldDisplayOnlyDeflection: true
shieldRenderRadius: 55
isBio: false

energyMax: 6
energyRegen: 0
energyNeedsToRechargeToFull: false
energyStartingPercentage: 0
tags: 卫星防御,地面,建筑

effectOnDeath: CUSTOM:烟雾2*4, CUSTOM:爆炸*1
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999



[action_0_补充能量]
price: 1500
text: 补充能量
buildSpeed: 12s
pos: 0.2
isActive: if self.energyIncludingQueued(lessThan=6)

addResources: energy=1


[graphics]
total_frames: 7
image: 身体.png
image_wreak: 死亡.png
image_back: ROOT:/通用特效/NO.png
image_shadow: AUTO

#scaleImagesTo: 20
#scaleTurretImagesTo: 9
image_shield: 护盾.png
#AUTO
shadowOffsetX: 3

shadowOffsetY: 3
animation_idle_start: 0
animation_idle_end: 6
animation_idle_speed: 8


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 1

turretTurnSpeed: 15
turretMultiTargeting: true
maxAttackRange: 1200
shootDelay: 23


[turret_3]
x: 0
y: 0
canShoot: true
invisible: true
size: 1.1

turnSpeed: 40
shoot_sound: ROOT:/通用特效/扫描.ogg
shoot_sound_vol: 1
projectile: 2
delay: 750

canOnlyAttackUnitsWithoutTags: 空降仓x
limitingRange: 800


[turret_1]
x: 0
y: 25
canShoot: true
shoot_sound: ROOT:/余辉军团/单位特效/瓶1.ogg
shoot_sound_vol: 0.5

shoot_flame: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:光柱
shoot_light: #FFEECCCC
projectile: 3
canAttackFlyingUnits: false
canAttackLandUnits: false

canAttackUnderwaterUnits: false
delay: 30
interceptProjectiles_withTags: 导弹2
interceptProjectiles_andUnderDistance: 1500

interceptProjectiles_andOverHeight: -100
energyUsage: 1
invisible: true

[turret_1x]
x: 0
y: 25
copyFrom: 1
interceptProjectiles_withTags: 天上战略
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战略防御天上



[turret_8]
x: 0
y: 25
canShoot: true
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.5

shoot_flame: CUSTOM:闪光z
shoot_light: #FFEECCCC
projectile: 5
canAttackFlyingUnits: false
canAttackLandUnits: false

canAttackUnderwaterUnits: false
delay: 10
interceptProjectiles_withTags: 战术武器
interceptProjectiles_andUnderDistance: 1500
interceptProjectiles_andOverHeight:-100
energyUsage: 0.15
invisible: true

[turret_8x]
x: 0
y: 25
copyFrom: 8
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 1500
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:1500
#战术防御天上





[turret_4]
x: 0
y: 25
canShoot: true
shoot_sound: ROOT:/余辉军团/单位特效/瓶1.ogg
shoot_sound_vol: 0.5

shoot_flame: CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波,CUSTOM:聚变,CUSTOM:冲击波1,CUSTOM:光柱
shoot_light: #FFEECCCC
projectile: 1
canAttackFlyingUnits: false
canAttackLandUnits: true

canAttackUnderwaterUnits: false
delay: 50
canOnlyAttackUnitsWithTags: 空降仓x
energyUsage: 0.5


[projectile_1]
directDamage: 100000
life: 666
speed: 999
targetSpeed: 999
trailEffect: false

image: NO.png
drawSize: 0
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:瓶*1,CUSTOM:瓶1*1,CUSTOM:波*1,CUSTOM:粒*3,CUSTOM:闪光d
mutator3_ifUnitWithTags: 空降仓x
mutator3_directDamageMultiplier: 800


[projectile_5]
directDamage: 0
life: 1000
speed: 33
image: ROOT:/余辉军团/单位特效/星星.png
drawSize: 0.55

lightSize: 1.5
lightColor: #FF00B3FF
explodeEffect: CUSTOM:爆炸zx
targetGround: false


[projectile_3]
areaDamage: 0
areaRadius: 0
life: 666
speed: 30
targetSpeed: 30

trailEffect: false
image: NO.png
drawSize: 0
largeHitEffect: true
deflectionPower: -1

explodeEffect: CUSTOM:瓶*1,CUSTOM:瓶1*1,CUSTOM:波*1,CUSTOM:粒*3,CUSTOM:闪光d

[projectile_2]
life: 600
directDamage: 0
speed: 40
targetSpeed: 40
drawSize: 0.1

frame: 1
targetGround: true
deflectionPower: -1
spawnUnit: 轨道轰炸*1
explodeEffect: NONE
[effect_烟雾2]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_瓶]
life: 300
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2

image: ROOT:/余辉军团/单位特效/超级盾.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false

animateFrameSpeed: 0.25
alsoPlaySound: ROOT:/余辉军团/单位特效/瓶.ogg
alwayStartDirAtZero: true
alpha: 1
drawUnderUnits: false


[effect_瓶1]
priority: critical
image: ROOT:/余辉军团/单位特效/瓶.png
life: 180
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1.3
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_爆炸zx]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波4.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 4
scaleTo: 7.5
alpha: 1.4
drawUnderUnits: true
atmospheric: false


[effect_粒]
life: 80
image: ROOT:/余辉军团/单位特效/光粒1.png
scaleFrom: 0.4
scaleTo: 2
alpha: 0.8

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
attachedToUnit: false


[effect_闪光d]
priority: critical
image: SHARED:light_50.png
life: 80
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 9
scaleTo: 9

drawUnderUnits: false
atmospheric: false


[effect_冲击波1]
life: 130
priority: critical
attachedToUnit: false
scaleFrom: 1.1
scaleTo: 2.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_冲击波]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 1.7
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_底色]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩.png
life: 140
fadeOut: true
attachedToUnit: false

scaleFrom: 0.45
scaleTo: 0.45
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 3
scaleTo: 3
alpha: 0.6
drawUnderUnits: false
atmospheric: false


[effect_闪光x]
priority: critical
image: SHARED:light_50.png
life: 240
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 8
scaleTo: 8

drawUnderUnits: true
atmospheric: false


[effect_闪光z]
priority: critical
image: SHARED:light_50.png
life: 30
fadeOut: true
alpha: 2

attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4

drawUnderUnits: true
atmospheric: false


[effect_光柱]
priority: critical
image: ROOT:/余辉军团/单位特效/激光.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.9
scaleTo: 0.9
alpha: 1.3
alwayStartDirAtZero: true
drawUnderUnits: false

atmospheric: false




[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.24
maxEachBase: 2
maxGlobal: 8
noneInBaseExtraPriority:0.7
upgradedFrom: 余辉行星防御系统t1空投


