

[core]
dont_load: true
@memory centerTarget0: unit
@memory 原地盘旋布尔: bool


[hiddenAction_原地盘旋A0]
autoTriggerOnEvent: newWaypointGivenByPlayer
setUnitMemory: centerTarget0 = activeWaypointTarget, 原地盘旋布尔 = false


[hiddenAction_原地盘旋B0]
requireConditional: if not memory.原地盘旋布尔 and not self.hasActiveWaypoint
autoTrigger: ${section.requireConditional}
setUnitMemory: centerTarget0 = select( memory.centerTarget0 != null, memory.centerTarget0, self.getAsMarker ), centerTarget0 = createMarker( min( max( ${ core.radius * 8 + 100}, memory.centerTarget0.x ), game.mapWidth - ${ core.radius * 8 + 100} ), min( max( ${ core.radius * 8 + 100}, memory.centerTarget0.y ), game.mapHeight - ${ core.radius * 8 + 100} ) )
# 圆心位置远离地图边缘
alsoTriggerAction: 原地盘旋C0
alsoTriggerActionRepeat: 6


[hiddenAction_原地盘旋C0]
requireConditional: if not memory.原地盘旋布尔
setUnitMemory: 原地盘旋布尔 = select( ( ( 360 + directionBetween( self, memory.centerTarget0.getOffsetRelative( x= 0, y= ${ int( core.radius * 0.2 ) * 30 + 100}, dirOffset= 60 * ( index + 1 ) + 37 ) ) - self.dir ) % 360 ) > ( ( 360 + directionBetween( self, memory.centerTarget0.getOffsetRelative( x= 0, y= ${ int( core.radius * 0.2 ) * 30 + 100}, dirOffset= 60 * ( index + 2 ) + 37 ) ) - self.dir ) % 360 ), true, false )
addWaypoint_type: move
addWaypoint_prepend: true
addWaypoint_target_fromReference: memory.centerTarget0.getOffsetRelative(x= 0, y= ${ int( core.radius * 0.2 ) * 30 + 100}, dirOffset= 60 * ( index + 1 ) + 37 )


[hiddenAction_原地盘旋B1]
requireConditional: if memory.原地盘旋布尔 and not self.hasActiveWaypoint
autoTrigger: ${section.requireConditional}
alsoTriggerAction: 原地盘旋C1
alsoTriggerActionRepeat: 18


[hiddenAction_原地盘旋C1]
addWaypoint_type: move
addWaypoint_target_fromReference: memory.centerTarget0.getOffsetRelative(x= 0, y= ${ int( core.radius * 0.2 ) * 30 + 100}, dirOffset= -60 * index + 37 )





# copyFrom: ROOT:/通用特效/原地盘旋.ini






