


[core]
name: 小型水上单位死亡
displayText: Гибель малого надводного юнита
class: CustomUnitMetadata
price: 0
techLevel: 1
buildSpeed: 1

radius: 2
displayRadius: 0
softCollisionOnAll: 0
hideScorchMark: true
explodeOnDeath: false

showInEditor: false
explodeOnDeathGroundCollosion: false
numBitsOnDeath: 0
canNotBeDirectlyAttacked: true
energyMax: 18

maxHp: 99999
armour: 99999
dieOnZeroEnergy: true
effectOnDeath:CUSTOM:巨大冲击波,CUSTOM:特殊, CUSTOM:特殊2,CUSTOM:巨大爆炸,CUSTOM:巨大钢珠,CUSTOM:巨大闪光,
[action_dl2]
autoTrigger: if self.globalTeamTags(includes='恐怖地雷3')
isVisible: false
spawnUnits: 恐怖地雷升级*3(offsetRandomX=50,offsetRandomY=50)

[action_t]
autoTrigger: true
isVisible: false
fireTurretXAtGround: 1
fireTurretXAtGround_count: 10
addEnergy: -18


[graphics]
total_frames: 1
image: NO.png
image_turret: NONE


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
aimOffsetSpread: 10

turretSize: 1
turretTurnSpeed: 400


[turret_1]
x: 0
y: 0
canShoot: false
projectile: 1


[projectile_1]
areaDamage: 0
areaRadius: 0
life: 200
drawSize: 1
largeHitEffect: true

image: 碎片.png
speed: 2.2
deflectionPower: -1
targetSpeed: 4
lightSize: 0.4

lightColor: #FFFFFF73
targetGround: true
initialUnguidedSpeedHeight: 4
trueGravity: 0.115
targetGroundSpread: 180
explodeEffect:CUSTOM:小爆炸,CUSTOM:烟雾1*2,CUSTOM:水波
trailEffect: CUSTOM:波雷爆炸


[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 2.2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3
scaleTo: 3
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 2.6
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[effect_巨大钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
alpha: 0.8
scaleFrom: 2
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3


[effect_波雷爆炸]
life: 30
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.3
image: 爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.6

[effect_小爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1.5
image: 爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 2
createWhenOverLiquid: false
createWhenOverLand: true
[effect_烟雾1]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.8
scaleTo: 1.85
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false

[effect_水波]
priority: low
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 0.28
alpha: 1
drawUnderUnits: true
atmospheric: true
createWhenOverLiquid: true
createWhenOverLand: false
[effect_特殊]
#displacement type ignored if postprocessing is not enabled
drawType: displacement
image: SHARED:ripple_normal_128.png
life: 115
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1
scaleTo: 3.5
alpha: 0.25
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 1
delayedStartTimer: 5
createWhenOverLiquid: true
createWhenOverLand: false
[effect_特殊1]
image: SHARED:ripple.png
life: 120
lifeRandom: 20
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1
scaleTo: 2.8
alpha: 0.6
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5
delayedStartTimer: 5
createWhenOverLiquid: true
createWhenOverLand: false
[effect_特殊2]
image: SHARED:ripple.png
life: 100
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 3
scaleTo: 1.5
alpha: 0.7
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5
delayedStartTimer: 5
createWhenOverLiquid: true
createWhenOverLand: false
[movement]
movementType: LAND


