


[core]
name: 清理标签
displayText: 清理标签
class: CustomUnitMetadata
displayDescription: 눈_눈
price: 0
maxHp: 15000
mass: 1
showInEditor: false
techLevel: 1
buildSpeed: 6s
radius: 13
softCollisionOnAll: 5
copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
hideScorchMark: true
dieOnZeroEnergy: true
#disableAllUnitCollisions: true
isBuilding: true
canNotBeDamaged:true
showOnMinimap:false
isUnselectable: true
disableAllUnitCollisions: true
canNotBeDirectlyAttacked: true
canNotBeGivenOrdersByPlayer: true
[action_t1]
autoTrigger: if self.timeAlive(laterThanSeconds=1)
isVisible: false
removeGlobalTeamTags:lg轨道炮,lg幻象,lg火箭,cx核弹,cx温压,cx歼灭,有和平了
deleteSelf: true
[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_shadow: AUTO
teamColorsOnTurret: true
icon_zoomed_out_neverShow:true
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 22
turretTurnSpeed: 3
maxAttackRange: 415

[movement]
movementType: HOVER
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0


