


[core]
name: 矿坑中介
strictLevel: 1
class: CustomUnitMetadata
techLevel: 1
showInEditor: false

mass: ${2^30}
radius: 0
price: 0
maxHp: 1
# tags: 
ignoreInUnitCapCalculation: true
isBuilding: true
footprint: -1,-1,1,1
constructionFootprint: -1, -1, 1, 1
buildingToFootprintOffsetX: 0
buildingToFootprintOffsetY: 0
softCollisionOnAll: 9999
isUnselectable: true
canNotBeDirectlyAttacked: true
isUnrepairableUnit: true


disableDeathOnZeroHp: true
showOnMinimap: false
onNewMapSpawn: emptyOrOccupiedResourcePools_asNeutral
stayNeutral: true


[hiddenAction_1]
autoTriggerOnEvent: destroyed
spawnUnits: ${core.name}(neutralTeam= true)


[graphics]
image: SHARED:blank.png
isVisible: false
disableLowHpFire: true
disableLowHpSmoke: true


[attack]
canAttack: false
maxAttackRange: 0


[movement]
movementType: HOVER
moveSpeed: 0
maxTurnSpeed: 999



