


[core]
name: 长弓护航艇
price: 1000
maxHp: 7500
displayDescription: 【阶级t4】【机械单位】【水上单位】【伴生单位】\n-战术定位:伴随式战舰，武器配置：\n-▲自动炮X1 只能对地 动能伤害\n-▲ 防空导弹垂发单元X1 对空对高空 爆炸伤害\n-长弓护航艇是一种伴随式小型舰艇，\n-他的主要责任是保护母体并消任何试图进犯的敌人。\n-由于依赖母体的指挥系统，离母体过远将面临破坏性停机。
armour: 15
techLevel: 1
buildSpeed: 8s
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 17
displayRadius: 17
tags: 地面,海上,反高空,伴生单位
effectOnDeath: CUSTOM:气浪2*3,CUSTOM:爆炸*1,CUSTOM:冲击波*1,CUSTOM:气浪*3,CUSTOM:水波*1
isBio: false
softCollisionOnAll: 2
canNotBeGivenOrdersByPlayer: true
energyMax: 30
energyRegen: 0
dieOnZeroEnergy: true
[action_电磁脉冲武器1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/电磁1.png
text: 电磁脉冲武器1
isActive: false
isVisible: if self.globalTeamTags(includes='电磁脉冲武器1')

[action_聚变弹头2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变2.png
text: 聚变弹头2
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头2')

[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_s1]
autoTrigger: if not self.isOverLiquid
isVisible: false
addResources: hp=-999999

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[hiddenAction_1]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=1000) and self.resource.xk < 1
addWaypoint_target_nearestUnit_tagged: 地面,低空,高空
addWaypoint_type: attack
addWaypoint_target_nearestUnit_team: enemy



[hiddenAction_21]
autoTrigger: if not self.hasUnitInTeam(withTag='战列要塞', withinRange=400) and self.resource.xk < 1
isVisible: false
clearAllWaypoints: true
addWaypoint_target_nearestUnit_tagged: 战列要塞
addWaypoint_target_nearestUnit_team: own

addWaypoint_maxTime: 1s
addWaypoint_type: move


[action_t1]
autoTrigger: if self.noUnitInTeam(withTag='战列要塞', withinRange=430)
isVisible: false
addResources: energy=-1
[action_tt]
autoTrigger: if self.hasUnitInTeam(withTag='战列要塞', withinRange=430)
isVisible: false
addResources: energy=5

[graphics]
total_frames: 1
image: 船体.png
image_wreak: 死亡.png
#scaleImagesTo: 20

teamColorsOnTurret: true
turretImageScale: 0.9
imageScale:0.9
image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2
splastEffect: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 4

turretSize: 16
maxAttackRange: 800

[turret_1]
x: 0
y: 12
#主炮
projectile: 1
limitingRange:600
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.5
shoot_flame: small
shoot_light: #FFEECCCC
canShoot: true
recoilOffset: -2
delay: 40
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='电磁脉冲武器1')
image: 管.png
attachedTo: 2
slave: true
size:8
invisible:if self.globalTeamTags(includes='电磁脉冲武器1')

[turret_2]
x: 0
y: 28
#炮塔
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='电磁脉冲武器1')
turnSpeed: 2.5
turnSpeedAcceleration: 0.12
image:炮.png
#limitingAngle: 135
limitingRange:600
invisible:if self.globalTeamTags(includes='电磁脉冲武器1')

[turret_3]
x: 0
y: -26
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*3, CUSTOM:冲击波1
shoot_light: #FFEECCCC
projectile: 2
size: 0
turnSpeed: 811
delay: 90
canOnlyAttackUnitsWithTags:高空
#limitingMinRange: 
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头2')
[turret_4]
x: 0
y: -26
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*3, CUSTOM:冲击波1
shoot_light: #FFEECCCC
projectile: 3
size: 0
turnSpeed: 811
delay: 90
canOnlyAttackUnitsWithoutTags:高空
altProjectile: 炮弹x
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头2')

[turret_5]
x: 0
y:28
copyFrom: 2
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='电磁脉冲武器1')
invisible:if not self.globalTeamTags(includes='电磁脉冲武器1')
image:休克炮.png
[turret_6]
x: 0
y: 6
#主炮
projectile: beam0
shoot_sound: ROOT:/通用特效/shock.ogg
shoot_sound_vol: 0.4
shoot_flame: CUSTOM:烟雾2*6
shoot_light: #FFEECCCC
canShoot: true
delay: 180
warmup:60
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='电磁脉冲武器1')
attachedTo: 5
canOnlyAttackUnitsWithoutTags:高空
slave: true
invisible:true
[projectile_1]
@copyFromSection: template_动能
directDamage: 180
life: 60
speed: 9
color: #FFFFFF73
drawSize: 1.85
largeHitEffect: true
lightSize: 1
lightColor: #FFFFFF73
[projectile_2]
life: 30
speed: 3
targetSpeed: 0
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:导弹碎片1


[projectile_锁定]
@copyFromSection: template_爆炸
directDamage: 785
life: 200
speed: 7
image: ROOT:/创世纪军事集团/单位特效/中导弹头.png
targetSpeed: 16
drawSize:0.8
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸x, CUSTOM:闪光,CUSTOM:冲击波x
explodeEffectOnShield: CUSTOM:钢珠,CUSTOM:爆炸x, CUSTOM:闪光,CUSTOM:冲击波x
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
trailEffectRate: 1.2
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_3]
life: 17
speed: 2.5
targetSpeed: 0
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 70
ballistic_delaymove_height: 55
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:导弹碎片1


[projectile_锁定1]
@copyFromSection: template_爆炸
directDamage: 785
life: 200
speed: 7
image: ROOT:/创世纪军事集团/单位特效/中导弹头.png
targetSpeed: 16
drawSize:0.8
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸x, CUSTOM:闪光,CUSTOM:冲击波x
explodeEffectOnShield: CUSTOM:钢珠,CUSTOM:爆炸x, CUSTOM:闪光,CUSTOM:冲击波x
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
trailEffectRate: 1.2
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_炮弹]
@copyFromSection:projectile_2
spawnProjectilesOnEndOfLife: 炮弹1
[projectile_炮弹1]
@copyFromSection: template_能源
life: 200
speed: 7
image: ROOT:/创世纪军事集团/单位特效/中导弹头.png
targetSpeed: 16
drawSize:0.8
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
trailEffectRate: 1.2
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
areaDamage: 1450
areaRadius: 60
areaRadiusFromEdge: true
[projectile_炮弹x]
@copyFromSection:projectile_2
spawnProjectilesOnEndOfLife: 炮弹x1
[projectile_炮弹x1]
@copyFromSection: template_能源
life: 200
speed: 7
image: ROOT:/创世纪军事集团/单位特效/中导弹头.png
targetSpeed: 16
drawSize:0.8
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
trailEffectRate: 1.2
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
areaDamage: 1450
areaRadiusFromEdge: true
areaRadius: 60
#————————————休克
[projectile_beam0]
explodeEffect: CUSTOM:电xk,CUSTOM:闪光xk
directDamage: 70
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 1.8
life: 3
instant: true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true
beamImage: ROOT:/通用特效/闪电1q.png
#beamImageOffsetRate: 2
armourIgnoreAmount: 99999
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
shieldDamageMultiplier:20
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电2q.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0
[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电3q.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电4q.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电5q.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电6q.png
spawnProjectilesOnEndOfLife: beam6(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam6]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电7q.png
spawnProjectilesOnEndOfLife: beam7(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam7]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电8q.png
spawnProjectilesOnEndOfLife: NONE
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0
[effect_电xk]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 1

drawUnderUnits: false
scaleFrom: 2
scaleTo: 2
[effect_闪光xk]
image: SHARED:light_50.png
life: 10
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
[effect_气浪]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 3
alpha: 1.3

drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedRelativeRandom: 0.2

ySpeedRelativeRandom: 0.2
xSpeedAbsoluteRandom: 0.4
ySpeedAbsoluteRandom: 0.4
createWhenOverLiquid: true
createWhenOverLand: false


[effect_气浪2]
stripIndex: effects
frameIndex: 0
life: 160
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 4
alpha: 1.3

drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedRelativeRandom: 0.2

ySpeedRelativeRandom: 0.2
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
createWhenOverLiquid: true
createWhenOverLand: false


[effect_冲击波]
stripIndex: shockwave
life: 70
scaleFrom: 0.3
scaleTo: 2.8
color: #FFF0AFA5

alpha: 1
createWhenOverLiquid: true
createWhenOverLand: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/单位特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/爆炸.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: true
createWhenOverLand: false




[effect_水花]
image: ROOT:/通用特效/水花.png
life: 160
fadeOut: true
attachedToUnit: false
color: #FFFFFF

fadeInTime: 4
scaleFrom: 0.05
scaleTo: 0.25
alpha: 0.6
drawUnderUnits: false

dirOffsetRandom: 0
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3

createWhenOverLiquid: true
createWhenOverLand: false


[effect_水波]
priority: critical
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.35
alpha: 1
drawUnderUnits: true
atmospheric: true

createWhenOverLiquid: true
createWhenOverLand: false

[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.3
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false
atmospheric: false
[effect_爆炸x]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.6
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/爆炸1.ogg
alpha: 1.2
[effect_冲击波x]
life: 110
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 1.4
scaleTo: 2.8
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_冲击波1]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1
#——————————聚变

[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.4
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1.1
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_实验jb]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:10
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.5
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
#——————————休克
[effect_烟雾2]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 60

fadeOut: true
attachedToUnit: true
#color:#FFE56BFF
#color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.4
scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
yOffsetRelative: 0.2

ySpeedRelative: 0.41
atmospheric: true

[arm_1]
x: 0
y: -26
image_end: 导弹曹.png
image_end_teamColors: true
drawUnderAllUnits: true


[arm_2]
x: 0
y: -26
image_end: 盖.png
image_end_teamColors: true
hidden:if self.isAttacking()
[movement]
movementType: WATER
moveSpeed: 1.2
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1
maxTurnSpeed: 3

turnAcceleration: 2
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


