
[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 25}

[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 25}


[core]
name: 余辉舰队航标t1
class: CustomUnitMetadata
price: 5500
maxHp: 5000
maxShield: 5000

shieldRegen: 0.05
isBuilding: true
shieldRenderRadius: 70
techLevel: 1
buildSpeed: 0.0005

isBio: false
footprint: -3,0,3,4
constructionFootprint: -3,0,3,4
showInEditor: false
copyFrom: ROOT:/通用特效/单位防护.ini
displayDescription: 余辉舰队航标负责引导在太空中的舰队和战机联队。\n-舰队航标将允许你随时召唤战机乃至战舰的增援。
numBitsOnDeath: 35
armour: 20
radius: 50
#displayRadius: 35
tags: 余辉机场,地面,建筑,无人单位

effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1
exit_x: 5
exit_y: 70
exit_moveAwayAmount: 180
canBuild_11_name: setRally

canBuild_11_pos: 0.1
canBuild_1_name: SDD狂风
canBuild_1_pos: 1
canBuild_2_name: SDD渡鸦
canBuild_2_pos: 2

canBuild_3_name: SDD猎杀者
canBuild_3_pos: 3

canBuild_4_name: SDSF方舟级运输舰
canBuild_4_pos: 4
#[canBuild_T31]
#name:SDD血星
#pos: 1

#isVisible: if self.globalTeamTags(includes='次时代')

[hiddenAction_ai自动造]
autoTrigger:if numberOfUnitsInTeam(lessThan=3, withTag='大农民') and self.isControlledByAI() and not self.tags(includes= '工程车保险')
alsoQueueAction:自动造
temporarilyAddTags:工程车保险
highPriorityQueue: true
[action_自动造]
displayType: action
price: 0
buildSpeed: 10s
isVisible: false
highPriorityQueue: true
temporarilyRemoveTags:工程车保险
spawnUnits:流光级工程穿梭机

[canBuild_T32]
name: SDD暗天使,SDD血星
pos: 5
isLocked:if not self.globalTeamTags(includes='皇家舰队1')
isLockedMessage: 你需要皇家舰队作战学说1



[canBuild_T33]
name: SDD地狱之龙
pos: 6
isVisible:true
isLocked:if not self.globalTeamTags(includes='乌托米尔1')
isLockedMessage: 你需要乌托米尔原子刻蚀技术1

[canBuild_T34]
name: SDSF凤凰级护卫舰
pos: 7
isVisible:true
isLocked:if not self.globalTeamTags(includes='泽塔诺亚2') or not self.globalTeamTags(includes='皇家舰队2')
isLockedMessage: 你需要泽塔诺亚蓝图数据库2和皇家舰队作战学说2

[canBuild_T35]
name: SDSF恐惧级驱逐舰
pos: 8
isVisible:true
isLocked:if not self.globalTeamTags(includes='乌托米尔2') or not self.globalTeamTags(includes='皇家舰队2')
isLockedMessage: 你需要乌托米尔原子刻蚀技术2和皇家舰队作战学说2

[canBuild_T36]
name: SDSF类星体级航空母舰
pos: 9
isVisible:true
isLocked:if not self.globalTeamTags(includes='禁卫军1')
isLockedMessage: 你需要禁卫军团军备复现1

[canBuild_T37]
name: SDSF灾厄级巡洋舰
pos: 10
isVisible:true
isLocked:if not self.globalTeamTags(includes='禁卫军1')
isLockedMessage: 你需要禁卫军团军备复现1

[canBuild_T38]
name: 流光级工程穿梭机
pos: 11
isVisible:true
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: 你需要四级AI核心作战中枢




[graphics]
total_frames: 7
image: 主体.png
image_back: ROOT:/通用特效/NO.png
image_wreak: 死亡.png
image_turret: NONE

#imageScale:0.75
animation_idle_start: 0
animation_idle_end: 6
animation_idle_speed: 11


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[effect_烟雾]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.5

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.2
ai_upgradePriority: 0.07
maxEachBase: 5
maxGlobal: 8
noneInBaseExtraPriority:0.8
upgradedFrom: 余辉舰队航标t1空投





