


[core]
name: 余辉海军工厂t1
displayText: Завод ВМФ Зареваt1
class: CustomUnitMetadata
price: 3500
maxHp: 3000
armour: 12
displayDescription: десантодин может самдвижениеразвернуть модельшткорабльдок, \n-этиоснащён и тяжёлый заводтот жеи т.п.масштаб строительствосистема корабльзаводможет быстрыйстроительствоИмперияЗаревомалый  типВМФюнит, \n-может Улучшить, \n-толькоможет в водана строительство.
maxShield: 3000
shieldRegen: 0.05
isBuilding: true
techLevel: 1
buildSpeed: 0.0005

shieldRenderRadius: 120
copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
footprint: -5,-2,5,7
constructionFootprint: -5,-2,5,7

showInEditor: false
numBitsOnDeath: 35
radius: 75
tags: 地面,海上,建筑,无人单位
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1

exit_y: 70
exit_moveAwayAmount: 180
canBuild_11_name: setRally
canBuild_11_pos: 0.1
canBuild_1_name: SDN电鳐

canBuild_1_pos: 1
canBuild_2_name: SDN窥视者
canBuild_2_pos: 2
canBuild_3_name: SDN涡流
canBuild_3_pos: 3

canBuild_4_name: 筑基虫
canBuild_4_pos: 0.2




[action_升级]
convertTo: 余辉海军工厂t2
displayType: action
text: Улучшить
price: 5000
buildSpeed: 18s

isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3')
isLockedMessage: вынужно3-й уровенькомандный центр
ai_isHighPriority: true
description: Улучшитьк t2, \n-все Улучшитьстроить корабльзавод кильи добавитьтвёрдыйоснование, \n-одновременноболее менятьстать ещё болееточный, огромный строительствосистема, \n-Этот системаможет производствоИмперия Новакогда-то проходитьпривлекатьчтобы для гордый теводана чудовище, \n-этотиспользовать ономожет быстрыйстроительствовыходит одинштприказврагидушалетатьнебоснаружи  ужасныйфлот.
pos: 0.05


[graphics]
total_frames: 1
image: 余辉海军工厂t1.png
image_back: 余辉海军工厂t1背景.png
image_wreak: 余辉海军工厂t1死亡.png
image_turret: NONE

#imageScale:0.75


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[effect_烟雾]
image: ROOT:/余辉军团/建筑特效/烟雾2.png
frameIndex: 0
life: 240
fadeOut: true
attachedToUnit: false

color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1

drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180

xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1.5

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true


[arm_2]
x: -40
y: 1
image_end: 部件.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_3]
x: -40
y: 48
image_end: 部件.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[arm_4]
x: -40
y: 95
image_end: 部件.png
image_end_teamColors: true
drawUnderAllUnits: false

drawOverBody: true


[animation_2]
onActions: idle
blendIn: 2s
blendOut: 1s
pingPong: true
arm2_1s: {x:80, y:0}

arm3_2s: {x:80, y:0}
arm4_1s: {x:80, y:0}


[movement]
movementType: WATER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.07
ai_upgradePriority: 0.07
maxEachBase: 10
maxGlobal: 50


