


[core]
name: 两栖突击舰
displayDescription: 【阶级t3】【机械单位】【地面单位】（在陆地上时）【水上单位】（在水域上时）【水陆两栖】【重型掩体】\n-战术定位:武装运兵船，载员数量：15，\n-无法被运输，内部载员无法向外开火，武器配置：\n-▲迫击炮X1 只能对地 爆炸伤害\n-▲火神炮X2 对地对空 动能伤害 反掩体\n-两栖突击舰是专门为夺岛登陆战设计的，\n-其内部空间十分宽敞可以容下一个步兵排或者四辆坦克，\n-与此同时其又配备了大量支援性武器为部队登陆清除障碍，\n-廉价而又可靠的两栖突击舰深受创世纪海军和陆军的信赖。\n-在艰难时期这种船舰甚至还能胜任制海任务。
price: 2500
maxHp: 3500

techLevel: 1
buildSpeed: 15s
maxTransportingUnits: 15
radius: 50
displayRadius: 50
isBio: false
softCollisionOnAll: 12
transportUnitsCanUnloadUnits: if not self.isOverLiquid
copyFrom: ROOT:/通用特效/单位防护.ini
unitsSpawnedOnDeath: 中型水上单位死亡*1
tags: 突击舰,地面,海上,重型掩体
transportUnitsUnloadDelayBetweenEachUnit: 10
armour: 10
energyMax: 10
energyStartingPercentage: 0
energyRegen: 0.006
fogOfWarSightRange: 19

[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
yOffsetRelative:0
xOffsetRelative:0
[decal_炮塔影子]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
[decal_炮塔影子1]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 3
alpha:0.65
[decal_炮塔影子2]
image: SHADOW:${turret_7.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 7
alpha:0.65
[decal_炮塔影子3]
image: SHADOW:${turret_8.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:-2
onlyWhileAlive:true
basePositionFromTurret: 8
alpha:0.65
[action_弹幕架1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕1.png
text: 弹幕架1
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架1')

[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。

[action_1_烟幕弹]
fireTurretXAtGround: 烟幕弹
text: 发射烟幕弹
displayType: action
buildSpeed: 1s
pos: 0.1

displayRemainingStockpile: true
highPriorityQueue: true
price: energy=10
canPlayerCancel: false
onlyOneUnitAtATime: true
description: 向目标区域投掷一枚烟幕弹，烟幕弹能严重干扰敌军的瞄准系统。\n-烟雾弹将降低附近160范围内的敌方地面单位的射程以及射速，\n-对具有长距离索敌能力以及拥有先进目标定位核心科技的单位无效。
iconImage: ROOT:/创世纪军事集团/单位特效/烟雾弹.png
isLocked: if self.resource.xk > 0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
whenBuilding_playAnimation: 1


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)





[attachment_1]
x: 0
y: 0
canAttack:false
addTransportedUnits: true
hidden: true
setDrawLayerOnBottom:true
[attachment_2]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_3]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_4]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_5]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_6]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_7]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_8]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_9]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_10]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_11]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_12]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_13]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_14]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_15]
@copyFromSection: attachment_1
x: 0
y: 0

[graphics]
total_frames: 1
image: 船壳1.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 2
shadowOffsetY: 2
teamColorsOnTurret: true
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 12

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretMultiTargeting: true

turretSize: 20
turretTurnSpeed: 4
maxAttackRange: 340


[turret_烟幕弹]
x: 0
y: -16
canShoot: false
idleDir: 0
invisible: true

size: 1.1
turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 3

delay: 0
canAttackCondition: if self.resource.xk < 1


[turret_1]
x: -17
y: -3
canShoot: false
image: ROOT:/创世纪军事集团/单位特效/炮.png
canAttackFlyingUnits: true
limitingRange: 280
delay: 2


[turret_2]
x: 0
y: 1
invisible: true
attachedTo: 1
slave: true

shoot_sound: ROOT:/创世纪军事集团/单位特效/机炮.ogg
shoot_sound_vol: 0.2
shoot_flame: CUSTOM:枪口火焰
shoot_light: #FFccCCEE
projectile: 2

canAttackCondition: if self.resource.xk < 1
limitingRange: 280
delay: 2


[turret_3]
x: 17
y: -3
copyFrom: 1


[turret_4]
x: 0
y: 1
attachedTo: 3
slave: true
copyFrom: 2

[turret_7]
x: 0
y: 8
attachedTo: 8
slave: true
image: ROOT:/创世纪军事集团/单位特效/炮管.png

shoot_sound: ROOT:/创世纪军事集团/单位特效/迫击炮音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FFFFEB88
recoilOffset: -2
recoilOutTime: 2

limitingMinRange: 150
recoilReturnTime: 30
size: 15
canAttackFlyingUnits: false
canAttackLandUnits: true

canAttackUnderwaterUnits: false
shoot_flame: CUSTOM:枪口火焰
projectile: 1
canAttackCondition: if self.resource.xk < 1

delay: 240
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='弹幕架1')

[turret_8]
x: 0
y: 20
canShoot: false
recoilOffset: -2
limitingMinRange: 150

image: ROOT:/创世纪军事集团/单位特效/炮塔2.png
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
canAttackCondition: if self.resource.xk < 1


#——————————————————科技
[projectile_炮弹]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 炮弹1*3(recursionLimit= 17)

[projectile_炮弹1]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
life: 6661
speed: 3

targetSpeed: 3
drawSize: 0.7
image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
explodeEffect:NONE
targetGround: true
spawnProjectilesOnExplode: 炮弹2(recursionLimit= 17)
trailEffect: true
initialUnguidedSpeedHeight:1.2
areaRadiusFromEdge: true
disableLeadTargeting: true
targetGroundSpread: 50
speedSpread:2
[projectile_炮弹2]
@copyFromSection: template_爆炸
areaDamage: 350
areaRadius: 60
life: 0
speed: 1
deflectionPower: -1
areaRadiusFromEdge: true
targetSpeed: 9999
frame:1
drawSize: 0
explodeEffect: CUSTOM:爆炸,CUSTOM:弹坑,CUSTOM:烟雾,CUSTOM:闪光*1,CUSTOM:烟雾3*3,CUSTOM:水波*1,CUSTOM:水花*1
lightSize: 0
targetGround:true
explodeOnEndOfLife: true
#————————————————————
[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
life: 6661
speed: 3

targetSpeed: 3
drawSize: 0.75
image: ROOT:/创世纪军事集团/单位特效/迫击炮弹.png
explodeEffect:NONE
targetGround: true
spawnProjectilesOnExplode: 1x
trailEffect: true
initialUnguidedSpeedHeight:1.2
areaRadiusFromEdge: true
disableLeadTargeting: true
[projectile_1x]
@copyFromSection: template_爆炸
areaDamage: 400
areaRadius: 60
life: 0
speed: 1
deflectionPower: -1
areaRadiusFromEdge: true
targetSpeed: 9999
frame:1
drawSize: 0
explodeEffect: CUSTOM:爆炸,CUSTOM:弹坑,CUSTOM:烟雾,CUSTOM:闪光*1,CUSTOM:烟雾3*3,CUSTOM:水波*1,CUSTOM:水花*1
lightSize: 0
targetGround:true
explodeOnEndOfLife: true

[projectile_2]
@copyFromSection: template_动能
directDamage: 10
life: 666
speed: 10
targetSpeed: 10

trailEffect: false
frame: 5
autoTargetingOnDeadTarget: false
deflectionPower: -1
explodeEffect: CUSTOM:火花
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_3]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.8

image: 导.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1


[projectile_锁定]
life: 600
directDamage: 0
speed: 4
targetSpeed: 8
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png

drawSize: 0.9
targetGround: true
spawnUnit: 烟幕弹*1
trailEffect: true
deflectionPower: -1
initialUnguidedSpeedHeight: 2.5
gravity: 0.4
explodeEffect:NONE
[effect_烟雾]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true

life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5

scaleFrom: 0.15
scaleTo: 0.3
alpha: 1.25
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_烟雾2]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 80
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 1
scaleTo: 1.8
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 3
scaleTo: 3


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟雾3]
priority: critical
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true

attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 3

alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true

hSpeed: 0.2
hOffsetRandom: 0.15
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/迫击炮爆炸.ogg
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15

xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false


[effect_水花]
image: ROOT:/通用特效/水花.png
life: 160
fadeOut: true
attachedToUnit: false
color: #FFFFFF

fadeInTime: 4
scaleFrom: 0.05
scaleTo: 0.4
alpha: 0.6
drawUnderUnits: false

dirOffsetRandom: 0
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3

createWhenOverLiquid: true
createWhenOverLand: false


[effect_水波]
priority: critical
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.45
alpha: 1
drawUnderUnits: true
atmospheric: true

createWhenOverLiquid: true
createWhenOverLand: false


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5

drawUnderUnits: false
atmospheric: false


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1
scaleTo: 1
createWhenOverLiquid: false
createWhenOverLand: true


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.6
image: ROOT:/创世纪军事集团/单位特效/火花.png
alpha: 1.2

total_frames: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFramePingPong: false
animateFrameSpeed: 0.3

[arm_1]
x: 0
y: 0
image_end: 船壳.png
image_end_teamColors: true


[arm_2]
x: 0
y: -16
image_end: 盖.png
image_end_teamColors: true
[animation_1]

arm2_0s: {x:0, y:0}
arm2_1s: {x:0, y:30}

[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
life: 90
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.4
scaleTo: 5
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -30
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
createWhenOverLiquid: true
createWhenOverLand: false
[effect_火]
life: 100
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1
scaleTo: 3.4
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1.5
yOffsetRelative	: 25
drawUnderUnits: true
createWhenOverLiquid: true
createWhenOverLand: false
[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.82
scaleTo: 0.82
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.82
scaleTo: 0.82
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10
[movement]
movementType: HOVER
moveSpeed: 1.1
moveAccelerationSpeed: 0.08
moveDecelerationSpeed: 0.3
maxTurnSpeed: 1.5

turnAcceleration: 0.6
targetHeight: 3
targetHeightDrift: 1


