


[core]
name: 休克打击坦克
displayText: Шок-танк
price: 3000,钍=45
maxHp: 8500
displayDescription: 【Уровень t4】【Механический юнит】【Наземный юнит】【Иммунитет к шоку】Тактическое назначение:瘫痪攻击 танк，\n-размер юнита:6，вооружение：▲EMP线圈X1 только по земле，нейтральный урон 附带休克эффект \n-穿透护盾и对无人юнит，биологический юнит伤害加成 пробивает укрытия \n-Шок-танк是Генезис科研部的一次大胆的尝试，鉴于традиционный的оружие均无法对余辉造成эффективный伤害，\n-а余辉的绝большинствоюнит都由精密устройство械构成，于是Генезис认为EMPоружиеабсолютныйможет对余辉造成毁灭性的удар。\n-войнасередина，随着универсальный性钍裂变堆和超导线圈的实现，第一批Шок-танк被производить出来и装配部队，\n-аШок-танктакже不负众望的取得了振奋人心的战果，независимо от多么мощный的машина械，только要被Шок-танк击中，\n-其все电子系统都会暂时或永久性瘫痪，и且使其реактор熄火动弹不得 。\n-这видможно怕的оружие的存在令余辉的地面мех部队再также不敢横行霸道。
fogOfWarSightRange: 25
techLevel: 1
buildSpeed: 18s
radius: 42
displayRadius: 42
isBio: false

softCollisionOnAll: 10
armour: 5
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,驻扎要塞
copyFrom: ROOT:/通用特效/单位防护.ini
transportSlotsNeeded:6
[decal_炮塔]
image: 炮塔.png
total_frames: 8
frame: (self.customTimer * 17) % 8
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 1
onlyWhileAlive:true
teamColors:true
[decal_炮塔1]
image: 炮塔损坏.png
basePositionFromTurret: 1
isVisible:if self.hp<self.maxHp * 0.36 
onlyWhileAlive:true
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 



#——————————————————科技
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: Мина «Кошмар»1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[action_先进目标定位核心1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位1.png
text: Улучшенный модуль наведения1
isActive: false
isVisible: if self.globalTeamTags(includes='目标定位1')
[hiddenAction_目标定位生效]
autoTrigger: if self.globalTeamTags(includes='目标定位1')
setUnitStats: maxAttackRange= ${attack.maxAttackRange*1.35},fogOfWarSightRange= ${core.fogOfWarSightRange*1.35}
temporarilyAddTags:免疫烟雾
[decal_炮塔影子]
image: 炮塔影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
[graphics]
total_frames: 3
image: 底盘.png
image_wreak: 死亡.png
teamColorsOnTurret: true
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
disablePassiveTargeting: false

turretMultiTargeting: true
turretSize: 22
turretTurnSpeed: 1.4
maxAttackRange: 550
#—————模块化————

#——————炮塔

[turret_1]
x: 0
y: -8
canShoot: false
image:炮塔1.png
canAttackFlyingUnits: false

[turret_2]
x: 0
y: 10
attachedTo: 1
slave: true
shoot_light: #FFEECCCC
shoot_sound: ROOT:/余辉军团/单位特效/瓶1.ogg
shoot_sound_vol: 0.7
warmup: 60
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
delay: 220
projectile: 1
size: 6
invisible: true
canAttackFlyingUnits: false

[turret_3]
x: 0
y: 10
attachedTo: 1
slave: true
shoot_light: #FFEECCCC
shoot_sound: ROOT:/余辉军团/单位特效/瓶1.ogg
shoot_sound_vol: 0
warmup: 60
delay: 220
projectile: 2
size: 6
invisible: true
canAttackFlyingUnits: false

[turret_4]
x: 0
y: 10
copyFrom: 3



[projectile_1]
areaDamage: 215
areaRadius: 140
life: 10
instant: true
laserEffect: true
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:闪电,CUSTOM:粒子*18,CUSTOM:电弧*8
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:闪电,CUSTOM:电弧*8
lightSize: 0.75
beamImage: 闪电.png
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: xk= 10
shieldDefectionMultiplier: 0.3
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator131_ifUnitWithTags: 无人单位
mutator131_directDamageMultiplier: 20
mutator131_areaDamageMultiplier: 20
mutator132_ifUnitWithTags: 步兵
mutator132_directDamageMultiplier: 10
mutator132_areaDamageMultiplier: 10
armourIgnoreAmount: 999999

[projectile_2]
life: 10
instant: true
directDamage: 0
lightingEffect: true
explodeEffect: NONE


[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.6
image:ROOT:/通用特效/电磁爆炸.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.5
scaleTo: 0.5

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7

ySpeedRelativeRandom: 3.7
#atmospheric: true


[effect_闪电]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 1

drawUnderUnits: false
scaleFrom: 4
scaleTo: 4


[effect_闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false

color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false

atmospheric: false
[effect_电弧]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: ROOT:/通用特效/电弧.png
total_frames: 8
animateFrameStart:1
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 0.85
drawUnderUnits: false
scaleFrom: 0.8
scaleTo:0.8
xOffsetRelativeRandom:60
yOffsetRelativeRandom:60
createWhenOffscreen: true
delayedStartTimerRandom:20

[movement]
movementType: LAND
moveSpeed: 0.75
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.1
maxTurnSpeed: 0.9

turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false


