


[core]
name: 中型陆军传送门
displayText: Средний наземный портал
class: CustomUnitMetadata
displayDescription: -Средний портал может телепортировать мех «Страж бездны», «Карателя», мех «Грифон»\n-и «Обсидиан». Каждый портал может телепортировать только одного юнита.\n-Любой телепортируемый юнит прибудет на поле боя в течение четырёх секунд.\n-Каждый портал поддерживается только 30 секунд, поспешите решить, кого телепортировать,\n-иначе портал закроется, не телепортировав никого. Порталы можно создавать только в поле телепортации.
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=30
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1


[action_取消]
text: Отменить постройку
addResources: hp=-999999,cs=30
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_冥卫机甲]
convertTo: 冥卫机甲
displayType: action
text: Телепортировать мех «Страж бездны»
description: -«Страж бездны» — это передовой,\n-уникальный и крайне смертоносный основной боевой мех.\n-Этот мощный мех является доказательством того, что\n-новые технологии Скитальцев не отстают от имперских.\n-На больших расстояниях, даже сталкиваясь с различными железными монстрами Имперского Зарева,\n-«Страж бездны» способен одержать верх.\n-Этот мех, олицетворяющий передовые технологии Скитальцев,\n-из-за крайней сложности изготовления\n-редко встречается в армии Скитальцев,\n-управлять им имеют право только лучшие из лучших пилотов.\n-Несмотря на высокую стоимость, «Страж бездны» по-прежнему мощно\n-сбивает спесь с дерзких наземных войск Зарева.\n-Атакует только землю, кинетический урон.
price: 5500,awz=100

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='法雅德2')
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_惩罚者]
convertTo: 惩罚者
displayType: action
text: Телепортировать «Каратель»
description: -Под угрозой орбитального оружия и космического флота Зарева создавать аэродромы на поверхности почти невозможно.\n-Чтобы обеспечить обслуживание истребителей, Скитальцы вынуждены были создать «Карателя».\n-«Каратель» переоборудован из тяжёлого военно-транспортного механизма Империи Нова, который ранее использовался для перевозки материалов для кораблей.\n-Скитальцы убрали грузовой отсек и установили двухпалубную лётную палубу и главное орудие.\n-Хотя изначально это был транспортный механизм, после полной переделки Скитальцами\n-«Каратель» переродился в жестокую боевую машину. Он несёт множество истребителей «Коготь орла»,\n-может с большого расстояния захватить господство в воздухе и полностью уничтожить врага. Даже в ближнем бою\n-«Каратель» благодаря мощному главному орудию и тяжёлой броне остаётся непобедимым.\n-Атакует землю и воздух. Главное орудие — кинетический урон, вторичные — энергетический. (Самолёты — энергетический.)
price: 8500,awz=180

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='科斯塔3')
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_狮鹫机甲]
convertTo: 狮鹫机甲
displayType: action
text: Телепортировать мех «Грифон»
description: -Печально известный мех «Грифон» был популярен в эпоху Воюющих государств Древних Людей — времени хаоса и порядка.\n-Будучи одним из самых продаваемых вооружений промышленной группы Коста, мех «Грифон» пользовался спросом у бесчисленных наёмников,\n-террористы с помощью «Грифонов» устраивали кровавые бойни. Множество боёв доказали мощь «Грифона».\n-К сожалению, ни Альфрид, ни Империя Нова никогда не закупали это дешёвое оружие. После основания Империи этот мех был забыт историей.\n-И только в конце Империи Нова отчаявшиеся Древние Люди при помощи остатков промышленной группы Коста\n-возобновили производство меха «Грифон» для борьбы с Заревом. Сегодня мощный мех «Грифон» по-прежнему активно действует в передовых частях против Зарева.\n-Атакует землю и воздух, энергетический урон.
price: 7400,awz=150

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='科斯塔2')
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_黑曜石]
convertTo: 黑曜石
displayType: action
text: Телепортировать «Обсидиан»
description: -Во времена Империи Нова «Обсидиан» был тяжёлым промышленным роботом на высокотехнологичных заводах,\n-их обычной задачей была перевозка тяжестей и другая тяжёлая работа.\n-В конце Империи Нова, когда Зарево захватило планету Викилант III,\n-в отчаянии люди выковали из заводских наноматериалов огромные мономолекулярные топоры для «Обсидианов».\n-Они переписали оригинальную систему меха «Обсидиан» военизированным управляющим ПО и переделали силовую установку,\n-превратив его в военизированный гражданский робот. Это часто было последним средством Древних Людей в борьбе с Заревом.\n-Они на «Обсидианах» устраивали засады в скрытых пещерах и руинах. Когда Зарево попадало в засаду,\n-«Обсидианы», тихо ждавшие в углу, разом нападали и мономолекулярными топорами рубили войска Зарева в металлолом.\n-По статистике, удар топора «Обсидиана» способен разбить большинство лёгких щитов\n-и разрубить суперсплавную броню Зарева пополам, как ножом по тыкве.\n-Атакует только землю. Нейтральный урон.
price: 6000

buildSpeed: 4s
isVisible: if self.globalTeamTags(includes='法雅德1')
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно

[action_漂泊者]
spawnUnits: 漂泊者(alwayStartDirAtZero= true)
displayType: action
text: Телепорт
addResources: hp=-999999
unitShownInUI: 漂泊者
textAddUnitName: 漂泊者
descriptionAddFromUnit: 漂泊者
price: 4000
descriptionAddUnitStats: 漂泊者
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно

[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.6


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.2
scaleTo: 0.45
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.55
scaleFrom: 0.55
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.5
scaleFrom: 0.5
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1

scaleTo: 0.75
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


