


[core]
name: 小型陆军传送门
displayText: Малый наземный портал
class: CustomUnitMetadata
displayDescription: -Малый портал может телепортировать танк «Егерь», канонерку «Небесный огонь», мех «Полярная звезда»\n-и мех «Краб-скрипач». Каждый портал может телепортировать только одного юнита.\n-Любой телепортируемый юнит прибудет на поле боя в течение четырёх секунд.\n-Каждый портал поддерживается только 30 секунд, поспешите решить, кого телепортировать,\n-иначе портал закроется, не телепортировав никого. Порталы можно создавать только в поле телепортации.
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=15
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 20


[action_取消]
text: Отменить постройку
addResources: hp=-999999,cs=15
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_猎兵坦克]
convertTo: 猎兵坦克
displayType: action
text: Телепортировать танк «Егерь»
description: -В период имперской смуты Нова свободные силы Либерата принципиально не использовали имперские технологии,\n-из-за чего долго не имели достойного наземного оружия. Чтобы противостоять многочисленным высокотехнологичным мехам роялистов,\n-тяжёлое шасси и 220-миллиметровая пушка нейтральных частиц составили устрашающий танк «Егерь».\n-Танк «Егерь» был создан для уничтожения тяжёлых наземных юнитов; даже это устаревшее оружие, разработанное во вторую великую эпоху мореплавания,\n-при увеличении мощности всё ещё может одним выстрелом пробить более половины имперских механических юнитов.\n-Появление танка «Егерь» не только сильно помогло наземным боям свободных сил, но и приблизило их идеал освобождения от имперских технологий.\n-Скитальцы сохранили эту простую и эффективную конструкцию и массово производят её, сделав основой своих сухопутных сил.\n-Атакует только землю, кинетический урон.
price: 2200

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_天火炮艇]
convertTo: 天火炮艇
displayType: action
text: Телепортировать канонерку «Небесный огонь»
description: -В конце эпохи Воюющих государств Древних Людей, для захвата территорий Республики Альфрид,\n-канонерка «Небесный огонь», способная действовать на суше и на море и адаптироваться к различным условиям, массово оснащалась Империей Нова.\n-Что особенно ценно, этот юнит сочетает свирепую огневую мощь и стремительную скорость,\n-даже в окружении он может нанести серьёзный урон врагу и быстро уйти. К сожалению,\n-канонерка «Небесный огонь» была снята с производства после войны и в большом количестве уничтожена. Скитальцы во время бегства нашли в базе данных скрытые чертежи «Небесного огня»,\n-и теперь Скитальцы массово производят «Небесный огонь», используя его манёвренность для партизанской войны и внезапных атак против Зарева.\n-Атакует землю и воздух, энергетический урон.
price: 2200

isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно
buildSpeed: 4s
ai_isHighPriority: true


[action_招潮蟹机甲]
convertTo: 招潮蟹机甲
displayType: action
text: Телепортировать мех «Краб-скрипач»
description: Мех «Краб-скрипач» создан для охоты на крупные юниты и крепости, по сей день остаётся основным мехом Скитальцев.\n-Полагаясь на мощную электромагнитную пушку, выпускающую тяжёлые конденсированные стальные иглы, он наносит смертельный удар различным тяжёлым юнитам.\n-Его мощная функция дальней бомбардировки и проходимость позволяют ему блистать в городских боях и тяжёлых штурмах укреплений.\n-Каждый раз, когда падают города Генезиса, Скитальцы забрасывают в город бесчисленных «Крабов-скрипачей»\n-для проведения «снайперской тактики» против оккупационных войск Зарева, нанося точечные удары на безопасном расстоянии.\n-Единственный недостаток — слабая защита «Краба-скрипача». Есть непроверенный рассказ:\n-однажды человек-старьёвщик, чтобы вывести любимую через стену, преграждавшую путь беженцам,\n-произведённым в прошлом веке гранатомётом M79 и тремя гранатами уничтожил «Краба-скрипача». Однако\n-«Краб-скрипач» всё же забрал у него любимую.\n-Атакует только землю, кинетический урон.
price: 4500

isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно
buildSpeed: 4s
ai_isHighPriority: true


[action_北极星机甲]
convertTo: 北极星机甲
displayType: action
text: Телепортировать мех «Полярная звезда»
description: -В середине второй великой эпохи мореплавания Древних Людей был разработан мех «Полярная звезда».\n-В то время частицевое оружие было весьма передовым и новаторским,\n-но, к сожалению, из-за отсталости технологии частицевое оружие было очень громоздким\n-и могло размещаться только на звёздных кораблях. «Полярная звезда» стал смелой попыткой миниатюризации частицевого оружия,\n-но эксперимент в итоге провалился, и материалы по «Полярной звезде» были скрыты в базе данных вне доступа.\n-Скитальцы в архивах обнаружили чертежи «Полярной звезды»; с современными технологиями его изготовление — пустяк.\n-Возрождённый мех «Полярная звезда» оправдал ожидания и стал самым широко используемым противовоздушным мехом Скитальцев.\n-Атакует только воздух, кинетический урон.
price: 4200,awz=50

isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно
buildSpeed: 4s
isVisible: if self.globalTeamTags(includes='科斯塔1')
ai_isHighPriority: true


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.4


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.1
scaleTo: 0.3
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.4
scaleFrom: 0.4
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.4
scaleFrom: 0.4
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1

scaleTo: 0.5
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


