


[core]
name: 小型陆军传送门
class: CustomUnitMetadata
displayDescription: -小型传送门可以传送猎兵坦克，天火炮艇，北极星机甲，\n-以及招潮蟹机甲，每个传送门仅能传送一个单位。\n-被传送的任何单位将在四秒之内到达战场。\n-每个传送门仅能维持30秒，请尽快决定要传送的单位，\n-否则传送门将在未传送任何单位的情况下关闭。且只能在传送场内产生传送门。
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=15
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 20


[action_取消]
text: 取消建造
addResources: hp=-999999,cs=15
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_猎兵坦克]
convertTo: 猎兵坦克
displayType: action
text: 传送猎兵坦克
description: -诺瓦帝国内乱时期，里贝拉图斯自由派因为执意不使用帝国科技，\n-导致一直没有能拿的上台面的地面作战武器，为对抗保皇派所持有的大量高科技机甲，\n-一张重型地盘和一门220毫米口径中性粒子炮，组成了令人生畏的猎兵坦克。\n-猎兵坦克的诞生皆在为了摧毁重型地面单位，即使是古人类二次大航海时期就诞生的落后武器，\n-只要调大功率进行堆叠，依旧可以一炮射穿一半以上的帝国机械单位。\n-猎兵坦克的出现不仅极大的帮助了自由派地面作战，也让他们脱离皇帝科技控制的理想更进一步。\n-太空浪人依旧保留了这种简单有效的设计，并大量生产成为了其陆军的主力。\n-只能对地，动能伤害。
price: 2200

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用


[action_天火炮艇]
convertTo: 天火炮艇
displayType: action
text: 传送天火炮艇
description: -古人类战国时期末期，为了占领亚尔佛里德共和国的领土，\n-能陆地海洋通用并且可以适应各种环境的天火炮艇被诺瓦帝国大量装备，\n-更难得可贵的是，这种单位兼备了凶残的火力和迅捷的速度，\n-哪怕是深陷重围也能在重创敌人后迅速脱离。只不过可惜的是，\n-天火炮艇在战后停产并被大量销毁，而太空浪人在逃亡时发现了雪藏于数据库中的天火蓝图，\n-现在天火被太空浪人广泛生产并利用其机动性，对余辉展开游击战和突袭作战。\n-对地对空，能源伤害。
price: 2200

isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用
buildSpeed: 4s
ai_isHighPriority: true


[action_招潮蟹机甲]
convertTo: 招潮蟹机甲
displayType: action
text: 传送招潮蟹机甲
description: 招潮蟹专为猎杀大型单位和堡垒而生，至今仍是太空浪人的主力机甲，\n-依靠强悍的线圈炮发射凝聚态重型钢针，能对各种重型单位造成致命打击。\n-其强力的远程轰炸功能和越野能力，使其在城市作战和重型攻坚战中大放异彩，\n-每当创世纪的城市沦陷，太空浪人就会将无数招潮蟹投放到城市中，\n-对占领城市的余辉军队进行“冷枪战术”，在安全距离外对余辉进行精确打击。\n-唯一美中不足的是招潮蟹防御能力堪忧。有一条未被证实的言论中提到：\n-曾经有一位人类拾荒者，为了将自己的爱人带出阻拦难民的封锁墙，\n-用上世纪生产的M79榴弹枪和三发榴弹就将招潮蟹炸毁了，只不过，\n-招潮蟹还是夺走了他的爱人。\n-只能对地，动能伤害。
price: 4500

isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用
buildSpeed: 4s
ai_isHighPriority: true


[action_北极星机甲]
convertTo: 北极星机甲
displayType: action
text: 传送北极星机甲
description: -在古人类第二次大航海时代中期，北极星就被古人类设计了出来，\n-在当时，粒子武器是一个十分先进且新颖的武器，\n-只不过可惜的是，由于技术过于落后，粒子武器的体积往往十分巨大，\n-导致粒子武器只能以星舰为载体，而北极星是对粒子武器小型化的一次大胆尝试，\n-但是实验最终还是以失败告终，而北极星资料也被雪藏于数据库中，不见天日。\n-太空浪人数据库资料里发现了北极星的图纸，以如今的技术将其制造出来简直易如反掌，\n-因此重获新生的北极星机甲果然不负众望，成为太空浪人部队中最广泛使用的防空机甲，\n-只能对空，动能伤害。
price: 4200,awz=50

isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: 失去了传送场，无法使用
buildSpeed: 4s
isVisible: if self.globalTeamTags(includes='科斯塔1')
ai_isHighPriority: true


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.4


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.1
scaleTo: 0.3
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.4
scaleFrom: 0.4
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.4
scaleFrom: 0.4
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1

scaleTo: 0.5
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


