[core]
name: 创世纪舰队港湾t1
displayText: Флотская гавань Генезисаt1
price: 3500
maxHp: 6500
footprint: -5,-5,5,9
constructionFootprint: -5,-5,5,9
displayDescription: 【Уровень t2】【Здание】【Надводный юнит】\n-Тактическое назначение: завод надводных кораблей, без вооружения.\n-можно строить только на воде。Модульный быстро развёртываемый военно-морской завод по стандартной системе постройки，\n-Встроена автоматизированная производственная линия，способная быстро собирать упакованные модули в боевые корабли，\n-Такая верфь — самое распространённое и необходимое сооружение в портах Генезиса。
unitsSpawnedOnDeath:建筑损毁*1
techLevel: 1
buildSpeed: 14s
#availableInDemo: true
nanoFactorySpeed:1
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 120
isBio: false
isBuilding: true
tags:地面,建筑,海上
extraBuildRangeWhenBuildingThis:150
effectOnDeath: CUSTOM:烟雾*6, CUSTOM:爆破*15
exit_x:0
exit_y: 95
exit_moveAwayAmount: 300
canBuild_31_name: setRally
canBuild_31_pos: 0.1
[action_煅炉增益]
autoTrigger:if self.globalTeamTags(includes='纳米煅炉') and not self.tags(includes= '煅炉保险')
isActive: false
isVisible: false
temporarilyAddTags:煅炉保险
setUnitStats: nanoFactorySpeed=1.3
[action_升级]
convertTo: 创世纪舰队港湾t2
displayType: action
text: 升класс
price: 5000
buildSpeed: 18s
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t3')
isLockedMessage: Требуется командный центр 3 уровня
ai_isHighPriority: true
description:повышаетФлотская гавань的уровень，加固其结构强度и使其можетпроизводство阶классT3的надводныйкорабльюнит。\n-升класс后将换装大体积龙 吊и获取主力舰строить模板，\n-这将позволяетверфьспособенстроитьГенезис海军中的大部分中坚力量。
pos: 0.05
[canBuild_T2]
name: 长须鲸工程船,蛙人潜水器,炮艇,追击舰
pos: 0.4

[graphics]
total_frames: 1
image: 底子.png
image_back: 底子.png
image_wreak:ROOT:/创世纪军事集团/建筑特效/死亡c.png
image_shadow: 影子.png
imageScale: 0.95

[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20
turretTurnSpeed: 30
maxAttackRange: 9999
shootDelay: 0



[arm_1]
x: 0
y: -130
image_end:阴影.png
image_end_teamColors: true
#drawOverBody: true
[arm_2]
x: -58
y: -29
image_end:ROOT:/创世纪军事集团/建筑特效/冲压机.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_3]
x: -58
y: -46
image_end:ROOT:/创世纪军事集团/建筑特效/冲压机.png
image_end_teamColors: true
hidden: if self.hp<self.maxHp * 0.36
drawOverBody: true
[arm_4]
x: -58
y: -63
image_end:ROOT:/创世纪军事集团/建筑特效/冲压机.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_5]
x: 0
y: 0
image_end:遮盖.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_6]
x: -67
y: 78
image_end:ROOT:/创世纪军事集团/建筑特效/起重机.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36

[arm_8]
x: 0
y: 0
image_end:ROOT:/创世纪军事集团/建筑特效/遮盖1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_9]
x: 3.5
y: -170
image_end:ROOT:/创世纪军事集团/建筑特效/水下.png
image_end_teamColors: true
#drawOverBody: true
[arm_10]
x: 0
y: 0
image_end:白光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36

[arm_11]
x: 0
y: 0
image_end:紫光.png
#image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_12]
x: 0
y: 0
image_end:损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[animation_2]
onActions: idle
arm2_0s: {x:0, y:0}
arm3_0s: {x:0, y:0}
arm4_0s: {x:0, y:0}
arm6_0s: {x:0, y:0}

arm2_2s: {x:0, y:0}
arm3_2s: {x:0, y:0}
arm4_2s: {x:-15, y:0}

arm2_4s: {x:0, y:0}
arm3_4s: {x:-15, y:0}
arm4_4s: {x:-15, y:0}

arm2_6s: {x:-15, y:0}
arm3_6s: {x:-15, y:0}
arm6_6s: {x:52, y:0}
arm4_6s: {x:-15, y:0}

arm2_8s: {x:-15, y:0}
arm3_8s: {x:-15, y:0}
arm4_8s: {x:0, y:0}

arm2_10s: {x:-15, y:0}
arm3_10s: {x:0, y:0}
arm4_10s: {x:0, y:0}

arm2_12s: {x:0, y:0}
arm3_12s: {x:0, y:0}
arm4_12s: {x:0, y:0}
arm6_12s: {x:0, y:0}
arm11_0s: {alpha:0}
arm11_3s: {alpha:1}
arm11_6s: {alpha:0}
arm11_9s: {alpha:1}
arm11_12s: {alpha:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:55
yOffsetRelativeRandom:120
delayedStartTimerRandom:30
[movement]
movementType: WATER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
buildPriority: 0.11
ai_upgradePriority: 0.07
maxEachBase: 15
maxGlobal: 50


