


[core]
name: 太空浪人无人机机库t1
class: CustomUnitMetadata
price: 6000
maxHp: 16000
selfRegenRate: 0.2

footprint: -4,-2,4,3
constructionFootprint: -4,-2,4,3
techLevel: 1
energyMax: 6
energyRegen: 0

energyNeedsToRechargeToFull: false
energyStartingPercentage: 0
buildSpeed: 10s
displayDescription: 停放大量攻击无人机以及拦截无人机的机库，\n-他们能在消灭敌人的同时，保护基地免遭远程武器的打击。\n-能释放战机攻击敌人，战略武器防御。只能拥有四座。
radius: 60

effectOnDeath: CUSTOM:冲击波, CUSTOM:爆炸,CUSTOM:闪光
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
tags: 地面,无人机库,航母lr,建筑

armour: 10
maxTransportingUnits: 4
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机lr

transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=4, withTag='无人机库')
deleteSelf: true
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈


[action_停电]
iconImage: ROOT:/太空浪人/单位特效/没电.png
text: 缺少供能
isActive: false
isVisible: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
displayType: infoOnly

isGuiBlinking: true


[action_0_补充能量]
price: 1500
text: 补充能量
buildSpeed: 12s
pos: 0.2
isActive: if self.energyIncludingQueued(lessThan=6)

highPriorityQueue: true
addResources: energy=1
isLocked: if self.noUnitInTeam(withTag= '聚变堆', withinRange= 400)
isLockedMessage: 没有供能



[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 4 and self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 4
addUnitsIntoTransport: 鹰爪


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1

[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)

[graphics]
total_frames: 6
image: 主体.png
image_back: 背景.png
image_wreak: 死亡.png
image_shadow: 影子.png

#imageScale:0.7


[attack]
canAttack: true
canAttackFlyingUnits: if self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
canAttackLandUnits:  if self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
canAttackUnderwaterUnits: false
maxAttackRange: 1200

turretMultiTargeting: true


[turret_1]
x: 0
y: 25
canShoot: true
shoot_flame: CUSTOM:烟雾3*5
projectile: 1

canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay: 30
interceptProjectiles_withTags: 导弹2
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
energyUsage: 1
canAttackCondition: if self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)

invisible: true
onShoot_playAnimation: 舱盖

[turret_1x]
x: 0
y: 25
copyFrom: 1
interceptProjectiles_withTags: 天上战略
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战略防御天上


[turret_2]
x: 0
y: 25
invisible: true
shoot_flame: CUSTOM:烟雾3*2
projectile: 2

canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay: 15
interceptProjectiles_withTags: 战术武器
interceptProjectiles_andUnderDistance: 1500
#interceptProjectiles_andOverHeight:-100
energyUsage: 0.15
canAttackCondition: if self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)

onShoot_playAnimation: 舱盖


[turret_2x]
x: 0
y: 25
copyFrom: 2
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 1500
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:1500
#战术防御天上




[turret_3]
x: 0
y: 25
invisible: true
shoot_flame: CUSTOM:烟雾3*3
projectile: 3

delay: 60
canOnlyAttackUnitsWithTags: 空降仓x
energyUsage: 0.5
canAttackCondition: if self.hasUnitInTeam(withTag= '聚变堆', withinRange= 400)
onShoot_playAnimation: 舱盖


[projectile_1]
areaDamage: 0
areaRadius: 0
life: 666
speed: 28
targetSpeed: 28
trailEffect: CUSTOM:尾巴
image: 飞机.png
drawSize: 1.2

largeHitEffect: true
trailEffectRate: 0.01
explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光,CUSTOM:冲击波
deflectionPower: -1


[projectile_2]
areaDamage: 0
areaRadius: 0
life: 666
speed: 33
targetSpeed: 33

ballistic_height: 130
ballistic_delaymove_height: 100
trailEffect: CUSTOM:尾巴
image: 飞机.png
drawSize: 1.2

largeHitEffect: true
trailEffectRate: 0.01
explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光,CUSTOM:冲击波
deflectionPower: -1


[projectile_3]
directDamage: 200000
life: 666
speed: 20
targetSpeed: 20
trailEffect: CUSTOM:尾巴

image: 飞机.png
drawSize: 1.2
largeHitEffect: true
trailEffectRate: 0.01
explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光,CUSTOM:冲击波

deflectionPower: -1
mutator3_ifUnitWithTags: 空降仓x
mutator3_directDamageMultiplier: 800

[attachment_drone1]
x: -25
y: 50
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
idleDir: 135

height: 1


[attachment_drone2]
x: 25
y: 50
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
idleDir: 135

height: 1


[attachment_drone3]
x: -25
y: 5
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
height: 1

idleDir: 135


[attachment_drone4]
x: 25
y: 5
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
height: 1

idleDir: 135


[arm_1]
x: 0
y: 0
image_end: 闪光.png
image_end_teamColors: true
drawOverBody: true

hidden: if self.hp(lessThan=5760)


[arm_2]
x: 0
y: 31
image_end: 上.png
image_end_teamColors: true
drawOverBody: false


[arm_3]
x: 0
y: 20
image_end: 下.png
image_end_teamColors: true
drawOverBody: false


[arm_4]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

hidden: if self.hp(greaterThan=5760)


[animation_1]
onActions: idle
blendIn: 1.4s
blendOut: 1.4s
arm1_0s: {alpha:0.0}
arm1_0.5s: {alpha:1}

arm1_0.9s: {alpha:0.1}
body_0s: {frame:0}
body_0.1s: {frame:1}
body_0.2s: {frame:2}
body_0.3s: {frame:3}

body_0.4s: {frame:4}
body_0.5s: {frame:5}


[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_爆炸]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3

scaleTo: 2.3
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg


[effect_爆炸1]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3

scaleTo: 2.3
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 9
scaleTo: 9

drawUnderUnits: true
atmospheric: false


[effect_烟雾3]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 3
scaleTo: 4.5
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
atmospheric: true


[effect_尾巴]
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.6
scaleTo: 0.3
alpha: 1

drawUnderUnits: true


[animation_舱盖]
blendIn: 1.0s
blendOut: 2.0s
arm2_1s: {x:0, y:20}
arm3_1s: {x:0, y:-20}


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


