


[core]
name: 晨曦之星轰炸机
displayText: Бомбардировщик «Утренняя звезда»
class: CustomUnitMetadata
showInEditor: false
displayDescription: -😭👊
price: 0
maxHp: 17800
techLevel: 1
buildSpeed: 0s
availableInDemo: true
fogOfWarSightRange: 28
armour: 58
radius: 33
displayRadius: 33
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
softCollisionOnAll: 90
energyMax: 60
energyRegen: 0
energyNeedsToRechargeToFull: true
tags: 飞机,高空,晨曦,寄生免疫,核弹,伴生单位
effectOnDeath:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
effectOnDeathGroundCollision:CUSTOM:巨大冲击波,CUSTOM:巨大爆炸,CUSTOM:巨大闪光
canNotBeGivenOrdersByPlayer: true
energyStartingPercentage: 1
logIfCreditResourceUsed: true
canOnlyBeAttackedByUnitsWithTags:反高空
[hiddenAction_有核弹]
autoTrigger: if self.globalTeamTags(includes='cx核弹') and self.hasParent 
temporarilyAddTags: 核弹
temporarilyRemoveTags:温压,歼灭
[hiddenAction_有歼灭]
autoTrigger: if self.globalTeamTags(includes='cx歼灭') and self.hasParent 
temporarilyAddTags: 歼灭
temporarilyRemoveTags:温压,核弹
[hiddenAction_有温压]
autoTrigger: if self.globalTeamTags(includes='cx温压') and self.hasParent 
temporarilyAddTags: 温压
temporarilyRemoveTags:歼灭,核弹
[hiddenAction_发送]
autoTriggerOnEvent: completeAndActive
sendMessageTo: customTarget1
sendMessageWithTags: 灰机a
sendMessageWithData: fish= 'z'
[hiddenAction_死亡发送]
autoTriggerOnEvent: destroyed
sendMessageTo: customTarget1
sendMessageWithTags: 灰机d
sendMessageWithData: fish= 'z'


[hiddenAction_return1]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( self.isEnergyRecharging or distanceBetweenSquared(self, customTarget1) > 3500 * 3500 )
# distanceBetweenSquared 返回两个单位之间的平方距离。 比 distanceBetween 快一点，因为少了开方这一步。1100² 判断灰机离母体有多远，超过1100回家
clearActiveWaypoint: true
addWaypoint_target_fromReference: customTarget1
addWaypoint_target_nearestUnit_team: own
addWaypoint_type: loadInto


[hiddenAction_disconnect]
autoTrigger: if not self.hasParent and not self.hasActiveWaypoint(type='loadInto') and ( not self.hasActiveWaypoint(type= 'attack') or activeWaypointTarget.height >10)
disconnectFromParent: true
clearActiveWaypoint: true
addWaypoint_type: attack
addWaypoint_prepend: true

addWaypoint_target_fromReference: customTarget1.attacking
addWaypoint_triggerActionIfMatched: 补丁
addWaypoint_triggerActionIfFailed: return1


[hiddenAction_补丁]
requireConditional: if not self.hasParent and not self.hasActiveWaypoint(type= 'attackMove')
addWaypoint_type: attackMove
addWaypoint_target_fromReference: thisActionTarget




[hiddenAction_energy]
autoTriggerOnEvent: enteredTransport
addResources:energy=61


[hiddenAction_t1]
autoTrigger: if customTarget1.hp <= 0
# 这条在鹰爪和雪崩里忘改成这样了，原本是打算航母凉后灰机用完能量才自杀，不过有bug忘了改回来
addResources: hp= -999999
[action_高空]
text: высотныйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的истребитель和боевой корабль。\n-在此高度下，только有地面和空中специальный的против высотныхюнит，а такжевысотныйюнит才может攻击до该юнит，\n-одновременно，大部分высотныйюнитможет互相攻击，иможет攻击обычныйвоздушный юнит，\n-только有специальный的высотныйюнит才можетпо земле攻击。

[action_akm]
autoTrigger: if self.hasParent and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
stopLastAnimation: true
[action_bkm]
autoTrigger: if not self.hasParent and self.hasFlag(id=1)
isVisible: false
addResources: unsetFlag=1
playAnimation: attack
[hiddenAction_zz1]
autoTrigger:if not self.isInMap() and not self.hasParent
addResources: hp= -999999
[graphics]
total_frames: 1
image: 飞机.png
image_wreak: 死亡.png
image_turret: NONE
imageScale: 0.9
image_shadow: NONE
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 1.5
maxAttackRange: 1000
attackMovement: bomber
[turret_1]
x: 0
y: 0
idleDir: 0
canShoot: true
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 1
canAttackFlyingUnits: false
projectile: 1
size: 1
delay:120
energyUsage:60
canAttackCondition:if self.tags(includes= '核弹')
limitingAngle: 15
[turret_2]
x: -15
y: -5
invisible: true
turnSpeed: 200
turnSpeedAcceleration: 11
projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/丢炸弹.ogg
shoot_sound_vol: 0.8
canShoot: true
delay: 2
canAttackFlyingUnits: false
energyUsage:5
limitingRange:750
canAttackCondition:if self.tags(includes= '歼灭')
[turret_3]
x: 15
y: -5
copyFrom: 2
[turret_4]
x: 0
y: 0
idleDir: 0
canShoot: true
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 1
canAttackFlyingUnits: false
projectile: 5
size: 1
delay:120
energyUsage:60
canAttackCondition:if self.tags(includes= '温压')
limitingAngle: 15
[projectile_1]
life: 55
speed: 0
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: 核导弹1.png
areaDamage: 0
areaRadius: 0
explodeEffect:CUSTOM:音效
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:2
explodeOnEndOfLife:true
drawUnderUnits:true
targetGround: true
disableLeadTargeting: true
targetGroundSpread: 60
[projectile_2]
directDamage: 0
deflectionPower: -1
life: 600
speed: 9
image: 核导弹.png
targetSpeed: 11
drawSize: 0.9
lightSize: 1.5
trailEffect: CUSTOM:烟
trailEffectRate: 0.7
lightColor: #FFFFFF73
targetGround: true
disableLeadTargeting: true
targetGroundSpread: 60
explodeEffect:NONE
spawnUnit:通用战略武器
tags:导弹2
[projectile_3]
@copyFromSection: template_爆炸
life: 55
speed: 0
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: 火箭1.png
areaDamage: 0
areaRadius: 0
explodeEffect:CUSTOM:音效1
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:4
explodeOnEndOfLife:true
drawUnderUnits:true
targetGround: true
disableLeadTargeting: true
targetGroundSpread: 90
[projectile_4]
areaDamage: 1750
explodeOnEndOfLife:true
areaRadius: 75
deflectionPower: -1
life: 600
speed: 2
image: 火箭.png
targetSpeed: 8
drawSize: 0.9
lightSize: 1.5
trailEffect: true
trailEffectRate: 0.7
lightColor: #FFFFFF73
targetGround: true
disableLeadTargeting: true
targetGroundSpread: 90
explodeEffect: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
explodeEffectOnShield: CUSTOM:冲击波hx1,CUSTOM:爆炸hx1, CUSTOM:爆炸hx,CUSTOM:闪光hx
areaRadiusFromEdge: true
speedSpread:1
[projectile_5]
@copyFromSection:projectile_1
spawnProjectilesOnEndOfLife:6
targetGroundSpread: 0
image: 燃烧1.png
[projectile_6]
directDamage: 0
deflectionPower: -1
life: 600
speed: 9
image: 燃烧.png
targetSpeed: 11
drawSize: 0.9
lightSize: 1.5
trailEffect: CUSTOM:烟
trailEffectRate: 0.7
lightColor: #FFFFFF73
targetGround: true
disableLeadTargeting: true
targetGroundSpread: 0
spawnUnit:通用战略武器(addResources=温压弹:1)
explodeEffect: CUSTOM:烟雾wy*15
explodeEffectOnShield: CUSTOM:烟雾wy*15
#————————尾焰
[effect_烟]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 2.5
alpha: 0.8
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: -8
ySpeedRelative: -2
yOffsetRelative	: -30
drawUnderUnits: true
[effect_火2]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 8
ySpeedRelative: -2
yOffsetRelative	: -30
drawUnderUnits: true
[arm_1]
x: 17
y: 4
image_end: 右.png
drawOverBody: true
image_end_teamColors: true
image_end_shadow: SHADOW:右.png
[arm_2]
x: -17
y: 4
image_end: 左.png
drawOverBody: true
image_end_teamColors: true
image_end_shadow: SHADOW:左.png
[arm_3]
x: 0
y: -22
image_end: 尾巴.png
drawOverBody: true
image_end_shadow: SHADOW:尾巴.png
image_end_teamColors: true
[arm_4]
x: 0
y: 25
image_end: 机头.png
drawOverBody: true
image_end_shadow: SHADOW:机头.png
image_end_teamColors: true
[arm_5]
x: 0
y: 0
image_end: 飞机.png
drawOverBody: true
image_end_teamColors: true
image_end_shadow: SHADOW:飞机.png
[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_0s: {x:0, y:0,dir:0}
arm1_1s: {x:20, y:-12,dir:0}
arm1_99999s: {x:20, y:-12,dir:0}

arm2_0s: {x:0, y:0,dir:0}
arm2_1s: {x:-20, y:-12,dir:0}
arm2_99999s: {x:-20, y:-12,dir:0}

arm3_0s: {x:0, y:0,dir:0}
arm3_1s: {x:0, y:-20,dir:0}
arm3_99999s: {x:0, y:-20,dir:0}

arm4_0s: {x:0, y:0,dir:0}
arm4_1s: {x:0, y:25,dir:0}
arm4_99999s: {x:0, y:25,dir:0}

[effect_巨大冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_巨大闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_巨大爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/巨大爆炸.ogg
createWhenOffscreen: true
[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:nuke_launch
[effect_音效1]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:ROOT:/创世纪军事集团/单位特效/导弹.ogg
#——————————————————炸
[effect_爆炸hx]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.35
image: ROOT:/创世纪军事集团/单位特效/boom.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.18
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/重型爆炸.wav
alwayStartDirAtZero: true
[effect_爆炸hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/12.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.21
alwayStartDirAtZero: true
[effect_闪光hx]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波hx1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
#——————————温压弹
[effect_烟雾wy]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 200
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 5
scaleTo: 7
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.31
xSpeedRelativeRandom: 0.31
xOffsetRelativeRandom:115
yOffsetRelativeRandom:115
delayedStartTimerRandom:15
atmospheric: true
[resource_温压弹]
displayName: ОДБ
displayNameShort: ОДБ
displayColor: #FF9D00FF
priority: 1
hidden: true
[movement]
movementType: AIR
reverseSpeedPercentage: 0
moveSpeed: 3
moveAccelerationSpeed: 2.5
moveDecelerationSpeed: 0
targetHeightDrift: 0.3
targetHeight: 140
maxTurnSpeed: 1.75
turnAcceleration: 0.07
moveSlidingMode: false

moveIgnoringBody: false
moveSlidingDir: 0
slowDeathFall: false


