


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 刚多林级巡洋舰
class: CustomUnitMetadata
price: 6000,awz= ${awzxq}
@global awzxq: 120
reclaimPrice: awz= ${awzxq}

maxHp: 8000
displayDescription: -科斯塔工业集团在古人类战国时期推出的一款不伦不类的产品，\n-刚多林级巡洋舰配有十分新颖的水路两栖技术，以及舰载机甲板，\n-其售卖的对像就是那些同时想追求扩充海洋和地面力量的国家，科斯塔本想这种设计可以大赚一笔，\n-在大规模生产后，却发现其市场非常惨淡，只有少数国家愿意少数购买，\n-大量积压的刚多林在诺瓦帝国统一古人类后被皇帝收缴，之后便被遗忘在仓库中。\n-之后在与余辉战斗的危及时刻，大量的刚多林被意外发现，\n-他们在被简单改造后就被投入了与余辉的战斗中，并在各种战役中爆发出了不小的威力，\n-这款生不逢时的巡洋舰至今已然成为太空浪人的主力海军之一。对地对空，主炮动能，副炮飞机能源且反掩体，水陆两栖
techLevel: 1
buildSpeed: 23s
availableInDemo: true

radius: 56
displayRadius: 56
isBio: false
softCollisionOnAll: 7
selfRegenRate: 0.2

armour: 20
fogOfWarSightRange: 34
copyFrom: ROOT:/通用特效/单位防护.ini
#tags:地面
tags: 航母lr,地面,海上

maxTransportingUnits: 1
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 战机lr
transportUnitsHealBy: 0.5

transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]
effectOnDeath: CUSTOM:爆炸5*1,CUSTOM:冲击波2,CUSTOM:水波1


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: 缺少暗物质
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[action_爆散2]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/爆散.png
text: 爆散弹头2
isActive: false
isVisible: if self.globalTeamTags(includes='爆散2')


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: 赛格门塔护甲1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_bx]
convertTo: 刚多林级巡洋舰1
whenBuilding_playAnimation: 部署
displayType: action
isVisible: false
buildSpeed: 1s

highPriorityQueue: true


[action_trigger_ax]
autoTrigger: if not self.overWater()
isVisible: false
alsoQueueAction: bx
highPriorityQueue: true



[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 1
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 1
addUnitsIntoTransport: 鹰爪


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2


[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource


[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1

[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯') or self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 身体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 4
shadowOffsetY: 4
splastEffect: true
teamColorsOnTurret: true
turretImageScale: 0.85


[attack]
canAttack: true
canAttackFlyingUnits: if self.resource.awz>-1
canAttackLandUnits: if self.resource.awz>-1
canAttackUnderwaterUnits: false
shootDelay: 75

maxAttackRange: 630
turretMultiTargeting: true


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-150
projectile: 13
delay: 120

size: 0
limitingRange: 550


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_1]
x: 0
y: 30
canShoot: true
recoilOffset: -4
projectile: 1

image: 主炮.png
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 1.1
shoot_light: #FFFF1200
shoot_flame: CUSTOM:气浪*5,CUSTOM:光粒*8

delay: 200
limitingAngle: 130
turnSpeed: 1.5
#limitingRange:300
canAttackFlyingUnits: false

canAttackCondition: if self.resource.xk < 1
size: 34
warmup: 60
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
altProjectile: 炮弹

altProjectileCondition: if self.globalTeamTags(includes='爆散2')


[turret_2]
x: 7
y: 8
projectile: 2
turnSpeed: 3
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FFFF1200
canShoot: true

recoilOffset: -3
size: 7
delay: 40
warmup: 0
canAttackCondition: if self.resource.xk < 1

image: 枪管.png
attachedTo: 4
slave: true
limitingRange: 360


[turret_3]
x: -7
y: 8
projectile: 2
turnSpeed: 3
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FFFF1200
canShoot: true

recoilOffset: -3
size: 7
delay: 40
warmup: 3
limitingRange: 360

canAttackCondition: if self.resource.xk < 1
image: 枪管.png
attachedTo: 4
slave: true


[turret_4]
x: 18
y: -5
canShoot: false
idleDir: 45
image: 副炮.png

turnSpeed: 3
turnSpeedAcceleration: 1.0
canAttackCondition: if self.resource.xk < 1
limitingRange: 360
limitingAngle: 130


[turret_5]
x: 7
y: 8
projectile: 2
turnSpeed: 3
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FFFF1200
canShoot: true

recoilOffset: -3
size: 7
delay: 40
warmup: 0
canAttackCondition: if self.resource.xk < 1

image: 枪管.png
attachedTo: 7
slave: true
limitingRange: 360


[turret_6]
x: -7
y: 8
projectile: 2
turnSpeed: 3
turnSpeedAcceleration: 1.0

#aimOffsetSpread:0.5
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FFFF1200
canShoot: true

recoilOffset: -3
size: 7
delay: 40
warmup: 3
limitingRange: 360

canAttackCondition: if self.resource.xk < 1
image: 枪管.png
attachedTo: 7
slave: true


[turret_7]
x: -18
y: -5
canShoot: false
idleDir: -45
limitingAngle: 130

image: 副炮.png
turnSpeed: 3
turnSpeedAcceleration: 1.0
canAttackCondition: if self.resource.xk < 1
limitingRange: 360


[projectile_1]
@copyFromSection: template_动能
areaDamage: 3000
areaRadius: 55
life: 200
areaRadiusFromEdge: true

speed: 9
image: ROOT:/太空浪人/单位特效/大炮弹.png
targetSpeed: 9
drawSize: 0.6
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:爆炸2*2,CUSTOM:聚变

explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:爆炸2*2,CUSTOM:聚变
lightSize: 0.75
trailEffectRate: 0.3
trailEffect: CUSTOM:尾巴
lightColor: #FFFF1200


[projectile_2]
@copyFromSection: template_能源
directDamage: 100
life: 10
instantReuseLast: true
beamImage: SHARED:beam3.png

beamImageStart: SHARED:beam1_start.png
sweepOffsetFromTargetRadius: 0.4
sweepSpeed: 10
instant: true
laserEffect: true

color: #FFFF1200
lightColor: #FFFF1200
lightSize: 0.1
explodeEffect: CUSTOM:爆炸3
explodeEffectOnShield: CUSTOM:爆炸3
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_炮弹]
@copyFromSection: template_爆炸
areaDamage: 3000
areaRadius: 55
life: 200
speed: 9

image: ROOT:/太空浪人/单位特效/大炮弹1.png
targetSpeed: 9
drawSize: 0.62
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸b, CUSTOM:闪光b,CUSTOM:溅射b,CUSTOM:粒子b*10,CUSTOM:聚变b

explodeEffectOnShield: CUSTOM:爆炸b, CUSTOM:闪光b,CUSTOM:溅射b,CUSTOM:粒子b*10,CUSTOM:聚变b
lightSize: 0.75
trailEffectRate: 0.5
trailEffect: CUSTOM:尾巴b
lightColor: #FF68FF2E

spawnProjectilesOnExplode: m2(yOffsetRelative= 20)


[projectile_m2]
@copyFromSection: template_爆炸
life: 1
deflectionPower: -1
explodeOnEndOfLife: true
speed: 0

turnSpeed: 0.0
areaDamage: 220
areaRadius: 40
areaRadiusFromEdge: true
targetGround: true

invisible: true
explodeEffect: CUSTOM:爆炸b1
spawnProjectilesOnCreate: m2(recursionLimit= 8, yOffsetRelative= 20)


[effect_爆炸3]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 2
image: ROOT:/太空浪人/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2
color: #FFFF1200


[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[effect_爆炸]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5

scaleTo: 1.5
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
color: #FFFF1200
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 1.2
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: true
atmospheric: false


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.6
scaleTo: 1.6
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_爆炸5]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.2

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/爆炸.ogg
alwayStartDirAtZero: true


[effect_爆炸2]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.6

drawUnderUnits: false
scaleFrom: 2
scaleTo: 4.5
color: #FFFF1200


[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 30
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7

drawUnderUnits: false


[effect_气浪]
#priority:critical
frameIndex: 0
stripIndex: effects
spawnChance: 0.7
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2

yOffsetRelative: 0.3
ySpeedRelative: 0.5
atmospheric: true


[effect_光粒]
spawnChance: 0.7
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.3
yOffsetRelative: 0.4
ySpeedAbsoluteRandom: 1
ySpeedRelative: 1
#xOffsetRelative:-2

atmospheric: true


[arm_3]
#左肩
x: -5
#x: -25
y: 48
image_end: 左.png

image_end_teamColors: true
drawOverBody: false
#moveSpeed: 6
#drawDirOffset: 90


[arm_4]
#左肩
x: 5
#x: 25
y: 48
image_end: 右.png

image_end_teamColors: true
drawOverBody: false
#moveSpeed: 6
#drawDirOffset: -90


[arm_5]
#左肩
x: -5
#x: -22
y: -50
image_end: 左.png

image_end_teamColors: true
drawOverBody: false
#moveSpeed: 6
#drawDirOffset: 90


[arm_6]
#左肩
x: 5
#x: 22
y: -50
image_end: 右.png

image_end_teamColors: true
drawOverBody: false
#moveSpeed: 6
#drawDirOffset: -90


[arm_7]
#左肩
x: 0
y: 85
image_end: 履带.png
image_end_teamColors: true

drawOverBody: false
#moveSpeed: 6
#drawDirOffset: 90


[arm_8]
#左肩
x: 0
y: 97
image_end: 前.png
image_end_teamColors: true

drawOverBody: false
#moveSpeed: 6
#drawDirOffset: -90


[attachment_drone1]
x: 0
y: -80
isUnselectable: true
isVisible: true
canBeAttackedAndDamaged: false

addTransportedUnits: true
setDrawLayerOnBottom: false
canAttack: true
lockRotation: true
idleDir: 180

height: 1


[animation_部署]
#onActions: attack
arm8_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}

arm6_0s: {x:0, y:0, dir:0}
arm8_1s: {x:0, y:-80, dir:0}
arm3_1s: {x:-20, y:0, dir:0}
arm4_1s: {x:20, y:0, dir:0}
arm5_1s: {x:-17, y:0, dir:0}

arm6_1s: {x:17, y:0, dir:0}
#______________________________


[effect_爆炸b]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.5

image: ROOT:/太空浪人/单位特效/核弹1.png
total_frames: 21
animateFrameStart: 0
animateFrameEnd: 21
animateFramePingPong: false

animateFrameSpeed: 0.27
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
#color: #FFFF1200


[effect_闪光b]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF68FF2E
fadeInTime: 2
scaleFrom: 5
scaleTo: 5

drawUnderUnits: false
atmospheric: false


[effect_粒子b]
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子.png
scaleFrom: 0.1
scaleTo: 0.3

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2

ySpeedRelativeRandom: 2.2
#atmospheric: true


[effect_冲击波b]
#priority:critical
image: ROOT:/太空浪人/单位特效/冲击波3.png
life: 45
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 0.77
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_聚变b]
priority: critical
image: ROOT:/太空浪人/单位特效/火光1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.8
scaleTo: 0.8
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
#color:#FFFF120


[effect_溅射b]
life: 100
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.55
scaleTo: 0.55
image: ROOT:/太空浪人/单位特效/爆散.png
total_frames: 9

animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.2
alpha: 1

atmospheric: false
#color:#FFFF1200


[effect_尾巴b]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束5.png
life: 30
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7

drawUnderUnits: false


[effect_爆炸b1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 2

image: ROOT:/太空浪人/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true
#color:#FFFF1200


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
movementType: HOVER
moveSpeed: 0.9
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.06
maxTurnSpeed: 2

turnAcceleration: 0.05
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


