


[core]
name: bfg千斤顶1
strictLevel: 1
price: 0
radius: 0
maxHp: 1

class: CustomUnitMetadata
showInEditor: false
canNotBeDirectlyAttacked: true
disableDeathOnZeroHp: true
isUnrepairableUnit: true

isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
[hiddenAction_开始]
autoTrigger:if not parent.tags(includes= '支架启动') and not self.tags(includes= '阻挡')
temporarilyAddTags:阻挡
stopLastAnimation: true
alsoQueueAction: b
playSoundAtUnit:ROOT:/通用特效/展开主炮.ogg
[action_b]
convertTo: bfg千斤顶
displayType: action
price: 0
buildSpeed: 4s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
[graphics]
image:NO.png
#isVisible: false
showQueueBar:false
showTransportBar:false
#imageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 600
[animation_1]
onActions: idle
arm16_0s: {alpha:0}
arm17_0s: {alpha:0}
arm18_0s: {alpha:0}

arm16_1.5s: {alpha:1}
arm17_1.5s: {alpha:0}
arm18_1.5s: {alpha:0}

arm16_3s: {alpha:0}
arm17_3s: {alpha:1}
arm18_3s: {alpha:0}

arm16_4.5s: {alpha:0}
arm17_4.5s: {alpha:0}
arm18_4.5s: {alpha:1}

arm16_6s: {alpha:0}
arm17_6s: {alpha:0}
arm18_6s: {alpha:0}
[arm_1]
x: 49
y: 180
image_end: 千斤顶2.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 0
drawOverBody: true
[arm_2]
x: -49
y: 180
image_end: 千斤顶2.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 0
drawOverBody: true
[arm_3]
x: 140
y: 59.5
image_end: 千斤顶1.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawOverBody: false
drawDirOffset: 45
[arm_4]
x: 110
y: 59.5
image_end: 千斤顶.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 90
drawOverBody: false
[arm_5]
x: -140
y: 59.5
image_end: 千斤顶1.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 45
drawOverBody: false
[arm_6]
x: -110
y: 59.5
image_end: 千斤顶.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: -90
drawOverBody: false
[arm_7]
x: 0
y: 0
image_end: 遮盖1.png
image_end_teamColors: true
drawDirOffset: 0
drawOverBody: false
[arm_8]
x: 80
y: -195
image_end: 千斤顶1.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 45
drawOverBody: false
[arm_9]
x: 80
y: -165
image_end: 千斤顶.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 180
drawOverBody: false
[arm_10]
x: 45
y: -220
image_end: 千斤顶1.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 45
drawOverBody: false
[arm_11]
x: 45
y: -190
image_end: 千斤顶.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 180
drawOverBody: false
[arm_12]
x: -80
y: -195
image_end: 千斤顶1.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 45
drawOverBody: false
[arm_13]
x: -80
y: -165
image_end: 千斤顶.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 180
drawOverBody: false
[arm_14]
x: -45
y: -220
image_end: 千斤顶1.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 45
drawOverBody: false
[arm_15]
x: -45
y: -190
image_end: 千斤顶.png
image_end_teamColors: true
#drawUnderAllUnits: true
drawDirOffset: 180
drawOverBody: false
[arm_16]
x: 0
y: 0
image_end: 指示灯.png
image_end_teamColors: true
drawOverBody: false
[arm_17]
x: 0
y: -17
image_end: 指示灯.png
image_end_teamColors: true
drawOverBody: false
[arm_18]
x: 0
y: -34
image_end: 指示灯.png
image_end_teamColors: true
drawOverBody: false


[animation_部署]
arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}
arm5_0s: {x:0, y:0, dir:0}
arm6_0s: {x:0, y:0, dir:0}
arm8_0s: {x:0, y:0, dir:0}
arm9_0s: {x:0, y:0, dir:0}
arm10_0s: {x:0, y:0, dir:0}
arm11_0s: {x:0, y:0, dir:0}
arm12_0s: {x:0, y:0, dir:0}
arm13_0s: {x:0, y:0, dir:0}
arm14_0s: {x:0, y:0, dir:0}
arm15_0s: {x:0, y:0, dir:0}

arm1_2s: {x:0, y:0, dir:0}
arm2_2s: {x:0, y:0, dir:0}
arm3_2s: {x:0, y:0, dir:-405}
arm4_2s: {x:0, y:0, dir:0}
arm5_2s: {x:0, y:0, dir:405}
arm6_2s: {x:0, y:0, dir:0}
arm8_2s: {x:0, y:0, dir:-405}
arm9_2s: {x:0, y:0, dir:0}
arm10_2s: {x:0, y:0, dir:-405}
arm11_2s: {x:0, y:0, dir:0}
arm12_2s: {x:0, y:0, dir:405}
arm13_2s: {x:0, y:0, dir:0}
arm14_2s: {x:0, y:0, dir:405}
arm15_2s: {x:0, y:0, dir:0}

arm1_4s: {x:0, y:-45, dir:0}
arm2_4s: {x:0, y:-45, dir:0}
arm3_4s: {x:-35, y:0, dir:-405}
arm4_4s: {x:-35, y:0, dir:0}
arm5_4s: {x:35, y:0, dir:405}
arm6_4s: {x:35, y:0, dir:0}
arm8_4s: {x:0, y:15, dir:-405}
arm9_4s: {x:0, y:15, dir:0}
arm10_4s: {x:0, y:35, dir:-405}
arm11_4s: {x:0, y:35, dir:0}
arm12_4s: {x:0, y:15, dir:405}
arm13_4s: {x:0, y:15, dir:0}
arm14_4s: {x:0, y:35, dir:405}
arm15_4s: {x:0, y:35, dir:0}

arm16_0s: {alpha:0}
arm17_0s: {alpha:0}
arm18_0s: {alpha:0}

arm16_0.5s: {alpha:1}
arm17_0.5s: {alpha:0}
arm18_0.5s: {alpha:0}

arm16_1s: {alpha:0}
arm17_1s: {alpha:1}
arm18_1s: {alpha:0}

arm16_1.5s: {alpha:0}
arm17_1.5s: {alpha:0}
arm18_1.5s: {alpha:1}

arm16_2s: {alpha:1}
arm17_2s: {alpha:0}
arm18_2s: {alpha:0}

arm16_2.5s: {alpha:0}
arm17_2.5s: {alpha:1}
arm18_2.5s: {alpha:0}

arm16_3s: {alpha:0}
arm17_3s: {alpha:0}
arm18_3s: {alpha:1}

arm16_3.5s: {alpha:1}
arm17_3.5s: {alpha:0}
arm18_3.5s: {alpha:0}

arm16_4s: {alpha:0}
arm17_4s: {alpha:1}
arm18_4s: {alpha:0}


[movement]
movementType: AIR
maxTurnSpeed: 9999
turnAcceleration: 9999

