


[core]
name: bfg导弹架
displayText: BFG-Ракетная установка
strictLevel: 1
price: 0
radius: 10
maxHp: 1
class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: bfg炮塔,家
canNotBeDirectlyAttacked: true
isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true

maxTransportingUnits: 1
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 追迹者
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and numberOfUnitsInTeam(lessThan=1, withTag='追迹者')
alsoQueueAction: SDD
[hiddenAction_SDD]
buildSpeed: 4s
addUnitsIntoTransport: 追迹者无人机

[attachment_5]
x: 0
y: -185
isUnselectable: true
isVisible: false
canBeAttackedAndDamaged: false
addTransportedUnits: true
setDrawLayerOnTop:true
canAttack: false
setDrawLayerOnBottom:false
lockRotation: true
idleDir: 180
height: 5
[hiddenAction_弹射]
autoTrigger:if parent.tags(includes= '发射侦查')
temporarilyAddTags:发射侦查
temporarilyRemoveTags:召回
[hiddenAction_召回]
autoTrigger:if parent.tags(includes= '召回')
temporarilyAddTags:召回
temporarilyRemoveTags:发射侦查
[graphics]
total_frames: 1
image: 导弹架.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange:5000
turretSize: 24
turretTurnSpeed: 2

[turret_1]
x: -100
y: 3.5
image:导弹.png
canShoot: true
projectile: 4
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.8
shoot_flame: CUSTOM:烟雾1*6
shoot_light: #FFEECCCC
limitingMinRange: 1500
size: 0
canAttackFlyingUnits: false
canAttackMaxAngle: 181
idleDir: -90
turnSpeed: 0
delay: 1200
warmup:0
recoilOffset: -40
recoilOutTime: 1
recoilReturnTime: 600
canAttackCondition: if parent.tags(includes= '用导弹')
[turret_2]
x: -100
y: 16.5
copyFrom: 1
delay:1100
warmup: 100
[turret_3]
x: -100
y: 29.5
copyFrom: 1
delay:1000
warmup: 200
[projectile_4]
areaDamage: 0
areaRadius: 0
spawnUnit: 旋风导弹(offsetHeight=0,offsetDir=0)
life: 40
speed: 3
#deflectionPower:-1
lightSize: 0
lightColor:  #FF00B3FF
drawSize: 1
targetSpeed: 0
turnSpeed: 0
trailEffect: true
image: 导弹.png
areaRadiusFromEdge: true
explodeEffect:NONE
explodeOnEndOfLife:true
[effect_烟雾1]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.9
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative:0
atmospheric: true
[arm_1]
x: 0
y: 0
image_end: 导弹架1.png
drawOverBody: true
[arm_2]
x: 0
y: -185
image_end: 麻了.png
drawDirOffset: 180
drawOverBody: true
hidden:if self.transportingCount<0.5
image_end_teamColors: true
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


