


[core]
name: bfg炮塔2
displayText: BFG-Башня2
strictLevel: 1
price: 0
radius: 10
maxHp: 1
class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: bfg炮塔
canNotBeDirectlyAttacked: true
isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
[action_hold]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
whenBuilding_cannotMove: false
allowMultipleInQueue:false
autoTrigger:if (parent.tags(includes= '核弹') or parent.tags(includes= '子母弹')) and self.queueSize <0.5
convertTo: bfg炮塔1
[hiddenAction_瞄准校正]
requireConditional: ${section.autoTrigger}
autoTrigger: if parent.hasActiveWaypoint(type= 'attack') and parent.activeWaypointTarget != self.attacking
clearAllWaypoints: true
addWaypoint_type: attack
addWaypoint_target_fromReference: parent.activeWaypointTarget
[hiddenAction_复位]
autoTrigger:if not parent.tags(includes= '开始变形') and not self.tags(includes= '阻挡')
setUnitStats:maxAttackRange=0.1
temporarilyAddTags:阻挡
[hiddenAction_复位1]
autoTrigger:if not parent.tags(includes= '炮管变形') and not self.tags(includes= '阻挡1')
temporarilyAddTags:阻挡1
alsoQueueAction:转换

[action_转换]
convertTo: bfg炮塔中介1
displayType: action
resetUnitStats:true
price: 0
buildSpeed: 3s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true

[decal_炮座影子]
image: 影子.png
total_frames: 1
layer: afterBody
#layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:-5
onlyWhileAlive:true
basePositionFromTurret: 1
[decal_炮座]
image: 炮座1.png
total_frames: 1
layer: afterBody
#layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 1
teamColors:true
[decal_炮仓影子]
image: 炮仓影子1.png
total_frames: 1
layer: afterBody
#layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:4
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_炮架影子]
image: 炮架影子1.png
total_frames: 1
layer: afterBody
#layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:10
onlyWhileAlive:true
basePositionFromTurret: 4
[decal_炮管影子]
image: 炮管影子1.png
total_frames: 1
layer: afterBody
#layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:10
onlyWhileAlive:true
basePositionFromTurret: 5
[decal_装填]
image: 弹仓动画.png
total_frames: 24
frame: select(self.tags(includes= '切枪'), (self.customTimer * 13) % 24, 0)
# 8为图片帧数，17改速度，1/17s下一帧
basePositionFromTurret: 8
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:-16
xOffsetRelative:-0.5
[hiddenAction_装填]
addResources: 弹药=1
[hiddenAction_装]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
whenBuilding_cannotMove:false
allowMultipleInQueue:false
autoTrigger: if self.resource.弹药>0.5 and not self.tags(includes= '切枪')
alsoQueueAction: ax
[action_ax]
displayType: action
price: 0
buildSpeed: 1s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
alsoQueueAction: bx
resetCustomTimer: true
temporarilyAddTags: 切枪
playSoundAtUnit:部署.ogg
[action_bx]
displayType: action
price: 0
buildSpeed: 1.8s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
addResources:弹药=-1
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
teamColorsOnTurret: true
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 99999
# 这个炮塔最好主体的最大范围多200
turretSize: 24
turretTurnSpeed: 2
turretMultiTargeting: true


[turret_1]
x:0
y: -80
canShoot: false
idleDir:0
image:NO.png
limitingAngle: 80
limitingMinRange: 2500
turnSpeed:0.4
turnSpeedAcceleration: 0.01
[turret_2]
x:0
y:0
canShoot: false
image:炮座灯.png
attachedTo: 1
slave: true

[turret_3]
x: 0
y: 1.5
projectile: 2
attachedTo: 1
slave: true
image: 炮仓x1.png
shoot_sound: NONE
shoot_sound_vol: 0
shoot_flame:NONE
canShoot: true
recoilOffset: -4
size:3
recoilOutTime: 5
recoilReturnTime:30
delay:540
canAttackFlyingUnits: false
limitingMinRange: 2500
canAttackCondition:if not parent.tags(includes= '核弹') or not parent.tags(includes= '子母弹')
[turret_4]
x: 0
y: 98
projectile: 2
attachedTo: 1
slave: true
image: 炮架x1.png
shoot_sound: NONE
shoot_sound_vol: 0
shoot_flame:NONE
canShoot: true
recoilOffset: -9
size:3
recoilOutTime: 10
recoilReturnTime: 50
delay:540
canAttackFlyingUnits: false
limitingMinRange: 2500
canAttackCondition:if not parent.tags(includes= '核弹') or not parent.tags(includes= '子母弹')
[turret_5]
x: 0
y: 73
projectile: 6
attachedTo: 1
slave: true
image: 炮管z.png
shoot_sound: ROOT:/创世纪军事集团/单位特效/巨炮发射.wav
shoot_sound_vol: 1.23
shoot_flame: CUSTOM:烟雾fs*18,CUSTOM:闪光fs,CUSTOM:冲击波fs,CUSTOM:冲击波fs1,CUSTOM:弹壳,CUSTOM:烟雾fs1*8,CUSTOM:闪光fs1
canShoot: true
recoilOffset: -15
size:135
recoilOutTime: 7
recoilReturnTime: 70
delay:540
canAttackFlyingUnits: false
limitingMinRange: 2500
onShoot_triggerActions:装填
canAttackCondition: if self.resource.弹药<0.5 and not parent.tags(includes= '子母弹') and not parent.tags(includes= '核弹')
altProjectile:4
altProjectileCondition: if parent.tags(includes= '电磁脉冲')

[turret_7]
x: 0
y: 98
projectile: 2
attachedTo: 1
slave: true
image: 炮架x.png
shoot_sound: NONE
shoot_sound_vol: 0
shoot_flame:NONE
canShoot: true
recoilOffset: -9
size:3
recoilOutTime: 10
recoilReturnTime: 50
delay:540
canAttackFlyingUnits: false
limitingMinRange: 2500
[turret_8]
x: 0
y: 1.5
projectile: 2
attachedTo: 1
slave: true
image: 炮仓x.png
shoot_sound: NONE
shoot_sound_vol: 0
shoot_flame:NONE
canShoot: true
recoilOffset: -4
size:3
recoilOutTime: 5
recoilReturnTime:30
delay:540
canAttackFlyingUnits: false
limitingMinRange: 2500
[resource_弹药]
displayName: 弹药
displayNameShort: 弹药
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_撞击]
displayName: 撞击
displayNameShort: 撞击
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_电磁脉冲]
displayName: ЭМИ
displayNameShort: ЭМИ
displayColor: #FF9D00FF
priority: 1
hidden: true
[projectile_2]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1
[projectile_4]
@copyFromSection: template_能源
areaDamage: 0
areaRadius: 0
targetSpeed: 18
life: 120
speed: 10
color: #FFFFFF73
largeHitEffect: true
lightSize: 3
lightColor: #FFFFFF73
image: ROOT:/创世纪军事集团/单位特效/光球.png
drawSize: 0.95
trailEffectRate: 0.4
initialUnguidedSpeedHeight: 7
trailEffect: CUSTOM:闪光wb,CUSTOM:projectileTrail
areaRadiusFromEdge: true
disableLeadTargeting: true
targetGround: true
spawnProjectilesOnEndOfLife:5
shouldRevealFog: true
alwaysVisibleInFog: true
nukeWeapon: true
[projectile_5]
@copyFromSection: template_能源
areaDamage: 0
areaRadius: 0
targetSpeed: 22
life: 18000
speed: 14
color: #FF00B3FF
largeHitEffect: true
lightSize: 3
lightColor:#FF00B3FF
image: 光球dc.png
drawSize: 0.95
trailEffectRate: 0.4
initialUnguidedSpeedHeight: 3.5
trailEffect: CUSTOM:闪光dc,CUSTOM:电磁,CUSTOM:projectileTrail
areaRadiusFromEdge: true
disableLeadTargeting: true
targetGround: true
explodeEffect:NONE
spawnUnit: 小核爆(addResources=电磁脉冲:1),电磁压制塔1
shouldRevealFog: true
alwaysVisibleInFog: true
nukeWeapon: true

[projectile_6]
@copyFromSection: template_能源
areaDamage: 0
areaRadius: 0
targetSpeed: 18
life: 120
speed: 10
color: #FFFFFF73
largeHitEffect: true
lightSize: 3
lightColor: #FFFFFF73
image: ROOT:/创世纪军事集团/单位特效/光球.png
drawSize: 0.95
trailEffectRate: 0.4
initialUnguidedSpeedHeight: 7
trailEffect: CUSTOM:闪光wb,CUSTOM:projectileTrail
areaRadiusFromEdge: true
disableLeadTargeting: false
targetGround: false
spawnProjectilesOnEndOfLife:7
shouldRevealFog: true
alwaysVisibleInFog: true
nukeWeapon: true
explodeEffect:CUSTOM:音效
explodeOnEndOfLife:true
[projectile_7]
@copyFromSection: template_动能,template_战略武器
directDamage: 45000
targetSpeed: 40
life: 18000
speed: 35
color: #FFFF1200
largeHitEffect: true
lightSize: 3
lightColor:  #FFFF1200
image: 光弹.png
drawSize: 0.8
trailEffectRate: 0.3
trailEffect: CUSTOM:闪光dn,CUSTOM:projectileTrailred,CUSTOM:光圈
areaRadiusFromEdge: true
disableLeadTargeting: false
targetGround: false
explodeEffect:NONE
spawnUnit: 小核爆(addResources=撞击:1)
shouldRevealFog: true
alwaysVisibleInFog: true
nukeWeapon: true
tags:导弹2
#——————————————主炮开炮特效
[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
[effect_烟雾fs]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 160
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 4.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.6
xSpeedRelativeRandom: 0.4
atmospheric: true
[effect_闪光fs]
image: SHARED:light_50.png
life: 45
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 13
scaleTo: 13
drawUnderUnits: false
atmospheric: false
[effect_闪光dn]
image: SHARED:light_50.png
life: 45
fadeOut: true
alpha: 0.8
attachedToUnit: false
color:  #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 3
drawUnderUnits: false
atmospheric: false
[effect_冲击波fs]
stripIndex: shockwave
life: 33
scaleFrom: 1
scaleTo: 6
alpha: 0.8
fadeOut: true
fadeInTime: 2

[effect_冲击波fs1]
life: 60
priority: critical
attachedToUnit: false
alpha: 0.8
fadeOut: true
fadeInTime: 2
scaleFrom: 0.8
scaleTo: 2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: false
[effect_弹壳]
image: 弹壳.png
spawnChance: 1
life: 300
fadeOut: true
attachedToUnit: false
#color: #FFFFFF
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1.3
createWhenZoomedOut: false
xSpeedRelative: 0.1
ySpeedRelative: -4
xSpeedRelativeRandom: -0.05
ySpeedRelativeRandom: -0.2
yOffsetRelative: -300
xOffsetRelative: 0
hSpeed: 2
dirSpeedRandom: 5
[effect_烟雾fs1]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 110
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 4.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.45
xSpeedRelativeRandom: 0.3
atmospheric: true
yOffsetRelative: -300
delayedStartTimer:10
[effect_闪光fs1]
image: SHARED:light_50.png
life: 65
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FFFFEB88
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
#————————————弹头尾巴
[effect_projectileTrailred]
stripIndex: effects
frameIndex: 0
life: 18
fadeOut: true
attachedToUnit: false
color:  #FFFF1200
fadeInTime: 5
scaleFrom: 1.5
scaleTo: 3
alpha: 0.5
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -22
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 18
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 1.5
scaleTo: 3
alpha: 0.8
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -22
[effect_星]
image:ROOT:/创世纪军事集团/单位特效/星星1.png
life: 5
fadeOut: true
spawnChance: 0.55
alpha: 1
attachedToUnit:true
#color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: false
atmospheric: false
yOffsetRelative: -27
xOffsetRelativeRandom:15
yOffsetRelativeRandom:15
[effect_尾巴]
priority: critical
image: ROOT:/通用特效/爆炸.png
life: 25
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 2
scaleFrom: 0.7
scaleTo: 2.2
alpha: 0.85
drawUnderUnits: false
atmospheric: false
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13
animateFrameSpeed: 0.2
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -27
[effect_星s]
image:ROOT:/创世纪军事集团/单位特效/星星1.png
life: 5
fadeOut: true
spawnChance: 0.55
alpha: 1
attachedToUnit:true
#color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 0.65
scaleTo: 0.65
drawUnderUnits: false
atmospheric: false
yOffsetRelative: -7
xOffsetRelativeRandom:13
yOffsetRelativeRandom:13
[effect_尾巴s]
priority: critical
image: ROOT:/通用特效/爆炸.png
life: 20
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 1.7
alpha: 0.85
drawUnderUnits: false
atmospheric: false
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13
animateFrameSpeed: 0.3
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -10
[effect_闪光wb]
image: SHARED:light_50.png
life: 32
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #FFFFEB88
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 2.5
drawUnderUnits: false
atmospheric: false
[effect_光圈]
priority: high
image: ROOT:/太空浪人/单位特效/冲击波.png
life: 30
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.02
scaleTo: 1
alpha: 0.8
drawUnderUnits: true
atmospheric: false
color:  #FFFF1200

#————————————闪电
[effect_电磁]
life: 120
dirOffset: 0
dirOffsetRandom: 180
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 0.45
drawUnderUnits: false
scaleFrom: 3
scaleTo: 3
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
[effect_闪光dc]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.7
scaleTo: 3.6
drawUnderUnits: false
atmospheric: false
[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 2.8
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


