


[core]
name: 炮艇
price: 1000
maxHp: 1100
displayDescription: 【阶级t2】【机械单位】【水上单位】\n-战术定位:高速侦查艇，武器配置：\n-▲机炮X1 对地对空 动能伤害 反掩体 对空军伤害加成\n-▲鱼雷X1 只能攻击水面单位和潜航单位 爆炸伤害\n-炮艇是一种小型侦查艇，仅配备了低强度装甲和少量武器，\n-他们主要用于在小型水域作战，也可以用于侦查和袭扰敌方海上设施。
techLevel: 1
buildSpeed: 8s
copyFrom: ROOT:/通用特效/单位防护.ini
radius: 31
armour: 2
displayRadius: 31
tags: 地面,海上
effectOnDeath: CUSTOM:气浪2*3,CUSTOM:爆炸*1,CUSTOM:冲击波*1,CUSTOM:气浪*3,CUSTOM:水波*1
isBio: false
softCollisionOnAll: 2
[decal_水下]
image: 水下.png
total_frames: 1
layer: beforeBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.8
alpha:0.6
[decal_炮塔影子]
image: SHADOW:${turret_1.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
imageScale: 0.8
[decal_炮塔影子1]
image: SHADOW:${turret_2.image}
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:3
xOffsetRelative:-3
onlyWhileAlive:true
basePositionFromTurret: 2
alpha:0.65
imageScale: 0.8
[decal_鱼雷]
image: 鱼雷.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:true
yOffsetRelative:0
xOffsetRelative:-0.4
onlyWhileAlive:true
basePositionFromTurret: 3
alpha:1
imageScale: 0.8
[decal_遮盖]
image: 主体.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
alpha:1
imageScale: 0.85
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
imageScale:0.85
[action_电磁炮1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/轨道1.png
text: 轨道发射器1
isActive: false
isVisible: if self.globalTeamTags(includes='轨道发射器1')

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 背景.png
image_wreak: 死亡.png
teamColorsOnTurret: true
turretImageScale: 0.85
imageScale:0.85
image_shadow: AUTO
shadowOffsetX: 2

shadowOffsetY: 2
splastEffect: true
movementEffect: CUSTOM:水波x,CUSTOM:火
movementEffectRate: 10

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
shootDelay: 4

turretSize: 16
maxAttackRange: 235



[turret_1]
x: 0
y: 14
attachedTo: 2
slave: true
shoot_flame: large
shoot_light: #FFFFEB88
shoot_sound: ROOT:/创世纪军事集团/建筑特效/机枪塔音效.ogg
shoot_sound_vol: 0.1
canAttackCondition: if self.resource.xk < 1
size: 8
image: 管.png
recoilOffset: -3
delay: 10
projectile: 1
canAttackUnderwaterUnits: false
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='轨道发射器1')
[turret_2]
x: 0
y: 19
canShoot: false
image:枪.png
canAttackCondition: if self.resource.xk < 1

[turret_3]
x: 0
y: -34
canShoot: true
idleDir:180
projectile: 2
shoot_sound: missile_fire
shoot_sound_vol: 0.2
shoot_flame: NONE
shoot_light: #FFEECCCC
canAttackFlyingUnits: false
canAttackMaxAngle: 181
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
turnSpeed: 0
image:NO.png
recoilOffset: -10
size:3
recoilOutTime: 4
recoilReturnTime: 60
delay:120
limitingMinRange:125
canOnlyAttackUnitsWithoutTags:悬浮
[projectile_1]
@copyFromSection: template_动能
directDamage: 10
life: 240
speed: 10
targetSpeed: 10

deflectionPower: -1
trailEffect: false
frame: 5
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator131_ifUnitWithTags: 飞机
mutator131_directDamageMultiplier: 2
mutator131_areaDamageMultiplier: 2
[projectile_炮弹]
@copyFromSection: template_动能
directDamage: 14
life: 60
speed: 15
image:ROOT:/创世纪军事集团/单位特效/子弹.png
drawSize: 0.4
explodeEffect: CUSTOM:大火花gd,CUSTOM:穿透gd
deflectionPower: -1
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
mutator131_ifUnitWithTags: 飞机
mutator131_directDamageMultiplier: 2
mutator131_areaDamageMultiplier: 2
armourIgnoreAmount: 10
shieldDamageMultiplier: 1.2
color: #FFFF1200
lightSize: 0.65
lightColor:#FFFF1200
[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
life: 30
speed: 3
deflectionPower: -1
areaRadiusFromEdge: true

image: 鱼雷.png
drawSize: 0.75
explodeEffect: CUSTOM:气浪*2,CUSTOM:水波
explodeEffectOnShield: CUSTOM:气浪*2,CUSTOM:水波
initialUnguidedSpeedHeight: 2
trueGravity: 0.2
lightSize: 0.75
trailEffectRate: 2
trailEffect:true
turnSpeed: 0
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage:300
areaRadius: 40
areaRadiusFromEdge: true
life: 460
speed: 0.5
targetSpeed: 5
image: 鱼雷1.png
drawSize: 0.6
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:烟雾3*2,CUSTOM:水波*1,CUSTOM:水花*1,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:烟雾3*2,CUSTOM:水波*1,CUSTOM:水花*1,CUSTOM:冲击波
lightColor: #FFEEEE00
lightSize: 0
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴
turnSpeed: 4
areaHitUnderwaterAlways:true

[effect_尾巴]
image: SHARED:light_50.png
life: 38
fadeOut: true
attachedToUnit: false
priority: high
color:#FF0092FF
fadeInTime: 2
scaleFrom: 0.28
scaleTo: 0.15
alpha: 0.8
drawUnderUnits: true
yOffsetRelative:-10
[effect_气浪]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 3
alpha: 1.3

drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedRelativeRandom: 0.2

ySpeedRelativeRandom: 0.2
xSpeedAbsoluteRandom: 0.4
ySpeedAbsoluteRandom: 0.4
createWhenOverLiquid: true
createWhenOverLand: false


[effect_气浪2]
stripIndex: effects
frameIndex: 0
life: 160
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 4
alpha: 1.3

drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedRelativeRandom: 0.2

ySpeedRelativeRandom: 0.2
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
createWhenOverLiquid: true
createWhenOverLand: false


[effect_冲击波]
stripIndex: shockwave
life: 70
scaleFrom: 0.3
scaleTo: 2.8
color: #FFF0AFA5
attachedToUnit: false
alpha: 1
createWhenOverLiquid: true
createWhenOverLand: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.4
image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/爆炸.ogg



[effect_烟雾3]
priority: critical
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true

attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 1
scaleTo: 2.5

alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true

hSpeed: 0.2
hOffsetRandom: 0.15
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15

xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false


[effect_水花]
image: ROOT:/通用特效/水花.png
life: 160
fadeOut: true
attachedToUnit: false
color: #FFFFFF

fadeInTime: 4
scaleFrom: 0.05
scaleTo: 0.25
alpha: 0.6
drawUnderUnits: false

dirOffsetRandom: 0
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.3
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3

createWhenOverLiquid: true
createWhenOverLand: false


[effect_水波]
priority: critical
image: ROOT:/通用特效/水波.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 0.35
alpha: 1
drawUnderUnits: true
atmospheric: true

createWhenOverLiquid: true
createWhenOverLand: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.6
image: ROOT:/创世纪军事集团/单位特效/火花.png
alpha: 1.2

total_frames: 3
animateFrameStart: 0
animateFrameEnd: 2
animateFramePingPong: false
animateFrameSpeed: 0.3
[effect_水波x]
image: ROOT:/通用特效/水波纹x.png
createWhenOverLand: false
life: 90
spawnChance: 1
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1
scaleTo: 3.2
alpha: 0.8
drawUnderUnits: true
yOffsetRelative: -20
ySpeedRelative: 0.3
dirOffsetRandom: 10
dirSpeedRandom: 0.1
[effect_火]
life: 70
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom:1
scaleTo: 1.8
image: SHARED:light_50.png
alpha: 0.9
color: #BBBBFFEE
xOffsetRelative	:0
ySpeedRelative: -1
yOffsetRelative	: 20
drawUnderUnits: true
#——————————————轨道
[effect_大火花gd]
life: 60
dirOffsetRandom: 180
spawnChance: 0.8
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.3
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12
animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 1.2
alsoPlaySound: ROOT:/通用特效/小碰撞.wav

[effect_穿透gd]
image: ROOT:/创世纪军事集团/单位特效/子弹.png
life: 30
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.12
scaleTo: 0.02
alpha: 1
drawUnderUnits: false
ySpeedRelative: 8.5
atmospheric: false
[movement]
movementType: WATER
moveSpeed: 1.2
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.1
maxTurnSpeed: 2

turnAcceleration: 0.1
#moveSlidingMode :false
moveIgnoringBody:true
#moveSlidingDir:  45


