


[core]
name: 侦察兵
displayText: Разведчик
class: CustomUnitMetadata
displayDescription:【Уровень t1】【Биологический юнит】【Наземный юнит】【Амфибия】  Тактическое назначение:поддержка пехота，\n-размер юнита:1，может维修другиеюнит。\n-вооружение：▲MP7冲锋枪X1 только по земле，нейтральный урон и пробивает укрытия \n-война 工兵являетсямногофункциятип兵вид，\n-ониоснащение двигательэкзоскелет，портативный治疗инструменти т.д.один系列новый鲜玩意，\n-喷气背包ещёможетпозволяетони悬浮в поверхность，в陆 и海洋间穿 ，\n-одновременнотакжеоснащён冲锋枪顺тогда给врагнаносит些麻烦。
price: 200
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/步兵掩体.md
isUnrepairableUnit:true
maxHp: 200
tags: 步兵,地面,驻扎要塞,1格
mass: 45
techLevel: 1
fogOfWarSightRange: 25
buildSpeed: 1.5s
softCollisionOnAll: 5
radius: 11
isBio: true
explodeOnDeath: false
effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
hideScorchMark: true
canRepairBuildings:true
canRepairUnits: true
canReclaimResources: false
autoRepair: true
nanoRepairSpeed: 0.3
nanoRange: 80
nanoBuildSpeed: 1

armour: 3

canBuild_6_name: 砖墙
canBuild_6_pos: 6
[graphics]
total_frames: 1
image: NO.png
image_wreak: 尸体.png
image_turret: NONE
image_shadow: ROOT:/创世纪军事集团/步兵特效/影子.png
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.7
turretImageScale: 0.7
repairEffect: CUSTOM:尾巴, CUSTOM:尾巴1
movementEffect: CUSTOM:projectileTrail
movementEffectRate: 1.8
teamColorsOnTurret: true
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
aimOffsetSpread: -0.01
maxAttackRange: 200
shootDelay: 24
turretRotateWithBody: true

[turret_1]
x: 6
y: 2
image: 左手.png
attachedTo: 3
projectile: 1
delay: 3
turnSpeed: 3.0
turnSpeedAcceleration: 0.5
shoot_sound: 手枪.ogg
shoot_sound_vol: 0.2
shoot_flame:CUSTOM:枪口火焰
shoot_light: #FFEECCCC
canShoot: true
size: 16
recoilOffset: -1
idleDir: 8
limitingAngle: 25
canAttackFlyingUnits: false
[turret_2]
x: -6
y: 2
idleDir: -8
attachedTo: 3
canShoot: false
image: 右手.png
[turret_3]
x: 0
y: 0
image: 躯干.png
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
canShoot: false
canAttackFlyingUnits: false
[turret_4]
x: 0
y: 0
image: 头盔.png
turnSpeed: 2.9
turnSpeedAcceleration: 0.3
canShoot: false
limitingAngle: 25
attachedTo: 3
slave:true
canAttackFlyingUnits: false
[turret_5]
x: -6
y: 0
idleDir: -8
attachedTo: 3
warmup: 0
size: 5
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true
image:修复.png
[projectile_1]
directDamage: 1
life: 666
speed: 8
deflectionPower: -1
frame: 5
drawSize: 0.6
explodeEffect: NONE
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.8
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.7
ySpeedRelativeRandom: 0.6

hSpeed: 1


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.5
scaleTo: 0.5
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1
ySpeedRelativeRandom: 1

hSpeed: 1
dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 600
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 3
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡.ogg,ROOT:/创世纪军事集团/步兵特效/死亡3.ogg,ROOT:/创世纪军事集团/步兵特效/死亡4.ogg,ROOT:/创世纪军事集团/步兵特效/死亡5.ogg


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
[effect_尾巴1]
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
priority: low
ySpeedRelativeRandom: 0.5
ySpeedRelative: 1
color: #AEA8FF50
fadeInTime: 2
scaleFrom: 0.25
scaleTo: 0.25
alpha: 1
drawUnderUnits: false
[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束5.png
life: 60
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.2
scaleTo: 0.2
alpha: 0.85
#ySpeedRelativeRandom: 0.5
drawUnderUnits: false
ySpeedRelative: 1
#yOffsetRelative: 10
[effect_projectileTrail]
createWhenZoomedOut: false
frameIndex: 0
stripIndex: effects
life: 28
fadeOut: true
attachedToUnit: false
#color: #FFFF1200
fadeInTime: 3
scaleFrom: 0.5
scaleTo: 0.1
alpha: 0.6
drawUnderUnits: true
ySpeedRelative: -0.4
atmospheric: true
createWhenOverLiquid:true
createWhenOverLand:false
[leg_1]
x: -2
y: 0
attach_x: -1
attach_y: -1
moveSpeed: 2.8
moveWarmUp: 0.5s
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25
targetHeightRelative: false
image_leg: 腿.png
dust_effect: false
holdDisMin: 1
holdDisMax: 6
hardLimit: 7
estimatingPositionMultiplier: 0.65
hidden: if self.hasParent() or self.isOverLiquid
[leg_2]
x: 2
y: 0
attach_x: 1
attach_y: -1
copyFrom: 1
hidden: if self.hasParent() or self.isOverLiquid
[movement]
movementType: HOVER
moveSpeed: 0.7
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
maxTurnSpeed: 1.5
reverseSpeedPercentage: 0
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: true


[ai]
disableUse: true


