
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=150

[core]
name: 流光级工程穿梭机
displayText: инженерный шаттл класса «Светлячок»
displayDescription: 【Уровень t4】【Механический юнит】【Воздушный юнит】【工程юнит】【Беспилотный юнит】\n-тактическое назначение:сначалав飞идтистроительствоюнит, вместимость десанта:16, не может транспортироваться, \n-внутричастьносительчленнет методнаружуоткрытьогонь, этотюнитединицаимеет захват прицеломвраги может сила.вооружение:\n-▲лазерная установка ближнего бояX1 энергетический урон только по воздуху \n-Утомирконтрольобщийиспользует  типвоздушныйнебоделать业платформа, может одновременностроитьустановка, десант и ремонти т.п.многовидмиссия, \n-это Империяфлотв каждыйвидармияделоидтидвижениев должен не может мало одинчлен, \n-одновременно, оноснащён 观测阵рядещё может в флотв наполнитьКогда перед 锋, для орбитальный флот огоньконтрольпредоставлятьвторой校в данный момент.\n-не трубкаэто  на высокий 耸входит 云 огромныйструктураещё это космосв свет璀璨 флот, \n-все малоне светв 背позади 默默посвящение тело影.
maxTransportingUnits: 16
transportUnitsUnloadDelayBetweenEachUnit:12
fogOfWarSightRange: 27
price: 5000,蓝晶=150
buildSpeed: 20s
maxHp: 4000
maxShield: 4000
shieldRenderRadius: 0
shieldRegen: 0.1
radius: 85
displayRadius: 85
isBio: false
tags: 飞机,低空,无人单位,流光,索敌单位,大农民
softCollisionOnAll: 20
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
effectOnDeath:CUSTOM:碎片,CUSTOM:碎片1,CUSTOM:大余晖单位死亡冲击波,CUSTOM:大余晖单位死亡爆炸,CUSTOM:大余晖单位死亡钢珠,CUSTOM:大余晖单位死亡闪光
effectOnDeathGroundCollision:CUSTOM:大余晖单位死亡爆炸,CUSTOM:大余晖单位死亡闪光
armour: 15
autoRepair: true
canRepairUnits: true
canRepairBuildings: true
nanoRepairSpeed: 4.5
nanoRange: 450
@memory 左转0: bool
@memory 右转0: bool
@memory oldDir0: float

updateUnitMemory: 左转0 = select( 180.2 < ( self.dir - memory.oldDir0 ) % 360 < 359.8, true, false ), 右转0 = select( 0.2 < ( self.dir - memory.oldDir0 ) % 360 < 179.8, true, false ), oldDir0 = self.dir - 360
updateUnitMemoryRate: 0

[action_已落地]
autoTriggerOnEvent:created
isVisible:false
addResources:setFlag=1,setFlag=2,setFlag=3,setFlag=4
[action_ax]
autoTrigger: if self.isMoving() and self.queueSize < 0.5 and not self.tags(includes= '飞行')
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
temporarilyAddTags: 切枪
alsoQueueAction: bx
resetCustomTimer: true
allowMultipleInQueue:true
highPriorityQueue:true

[hiddenAction_bx]
buildSpeed: 1.05s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove:false
temporarilyRemoveTags: 切枪
temporarilyAddTags:飞行
allowMultipleInQueue:false
resetCustomTimer: true

[action_ax1]
autoTrigger: if not self.isMoving() and self.queueSize < 0.5 and self.tags(includes= '飞行')
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
temporarilyAddTags: 切枪1

alsoQueueAction: bx1
resetCustomTimer: true
allowMultipleInQueue:true
highPriorityQueue:true

[hiddenAction_bx1]
buildSpeed: 1.05s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove:false
temporarilyRemoveTags: 切枪1,飞行
allowMultipleInQueue:false
resetCustomTimer: true


#——————————————————经济类建筑

[action_T1]
pos: 0.001
buildSpeed: 0s
addResources: setFlag=1
text: показатьэкономикатипздание
isVisible: if not self.hasFlag(id=1) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/经济.png
[action_T1_back]
pos: 0.002
buildSpeed: 0s
addResources: unsetFlag=1
isVisible: if self.hasFlag(id=1) and not self.isControlledByAI()
text: не показатьэкономикатипздание
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/经济.png

[canBuild_1]
name: 重力吸纳仓空投
pos: 1
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()

[canBuild_2]
name: 余辉蓝晶萃取房t1空投
pos: 2
forceNano: true
isVisible: if self.hasFlag(id=1) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3')
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня
#——————————————————生产类建筑

[action_T2]
pos: 0.003
buildSpeed: 0s
addResources: setFlag=2
text: показатьпроизводствотипздание
isVisible: if not self.hasFlag(id=2) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/生产.png
[action_T2_back]
pos: 0.004
buildSpeed: 0s
addResources: unsetFlag=2
isVisible: if self.hasFlag(id=2) and not self.isControlledByAI()
text: не показатьпроизводствотипздание
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/生产.png

[canBuild_21]
name: 轨道空降平台空投
pos: 8
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if numberOfUnitsInTeam(withTag='轻工',withinRange=700,greaterThan=0) and self.isControlledByAI()

[canBuild_22]
name: 支援型载具站空投
pos: 9
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t2')
isLockedMessage: Требуется боевой центр ядра ИИ 2-го уровня


[canBuild_23]
name: 余辉海军工厂t1空投
pos: 10
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t2')
isLockedMessage: Требуется боевой центр ядра ИИ 2-го уровня


[canBuild_24]
name: 机甲工厂空投
pos: 11
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3')
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня

[canBuild_25]
name: 余辉舰队航标t1空投
pos: 12
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3')
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня


[canBuild_26]
name: 建造璇星之梯
pos: 13
forceNano: true
isVisible: if self.hasFlag(id=2) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t4')
isLockedMessage: Требуется боевой центр ядра ИИ 4-го уровня
#——————————————————军事建筑

[action_T3]
pos: 0.005
buildSpeed: 0s
addResources: setFlag=3
text: показатьармиядело/научно-исследовательскийтипздание
isVisible: if not self.hasFlag(id=3) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/军事.png
[action_T3_back]
pos: 0.006
buildSpeed: 0s
addResources: unsetFlag=3
isVisible: if self.hasFlag(id=3) and not self.isControlledByAI()
text: не показатьармиядело/научно-исследовательскийтипздание
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/军事.png


[canBuild_31]
name: 余辉纳米维修站t1空投
pos: 31
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t2')
isLockedMessage: Требуется боевой центр ядра ИИ 2-го уровня

[canBuild_32]
name: 超级计算机核心空投
pos: 32
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3') or numberOfUnitsInTeam(withTag='计算机', greaterThan=0)
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня,  и можно иметь только один



[canBuild_33]
name: 余辉军械库空投
pos: 33
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3') or numberOfUnitsInTeam(withTag='军械库', greaterThan=0)
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня,  и можно иметь только один

[canBuild_34]
name: 余辉轨道通讯系统空投
pos: 34
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='行星突袭')
isLockedMessage: вынужнопланетарный штурмбоевойтеория



[canBuild_35]
name: 余辉战略资源调度站空投
pos: 35
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked:  if self.noUnitInTeam(withTag= '余辉指挥中心t3') or numberOfUnitsInTeam(withTag='调度站', greaterThan=0)
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня,  и можно иметь только один


[canBuild_36]
name: 余辉重力场要塞炮
pos: 36
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='禁卫军1') or numberOfUnitsInTeam(withTag='要塞炮', greaterThan=0, incompleteBuildings= true)
isLockedMessage: вынужноИмпериягвардияармиярезерввосстановитьтекущий1, иможно иметь только один

[canBuild_37]
name: 建造亚空间运算引擎
pos: 37
forceNano: true
isVisible: if self.hasFlag(id=3) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t4') or numberOfUnitsInTeam(withTag='亚空间运算引擎', greaterThan=0, incompleteBuildings= true,factoryQueue= true)
isLockedMessage: Требуется боевой центр ядра ИИ 4-го уровня,  и толькоможет Имея одиншт
#——————————————————防御建筑

[action_T4]
pos: 0.007
buildSpeed: 0s
addResources: setFlag=4
text: показатьоборонатипздание
isVisible: if not self.hasFlag(id=4) and not self.isControlledByAI()
iconExtraImage:SHARED:icon_on.png
iconImage: ROOT:/通用特效/防御.png
[action_T4_back]
pos: 0.008
buildSpeed: 0s
addResources: unsetFlag=4
isVisible: if self.hasFlag(id=4) and not self.isControlledByAI()
text: не показатьоборонатипздание
iconExtraImage:SHARED:icon_off.png
iconImage: ROOT:/通用特效/防御.png


[canBuild_42]
name: 空AG炮塔t2空投
pos: 42
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if self.noUnitInTeam(withTag= '余辉指挥中心t3')
isLockedMessage: Требуется боевой центр ядра ИИ 3-го уровня

[canBuild_43]
name: 余辉行星防御系统t1空投
pos: 43
forceNano: true
isVisible: if self.hasFlag(id=4) or self.isControlledByAI()
isLocked: if not self.globalTeamTags(includes='行星突袭')
isLockedMessage: вынужнопланетарный штурмбоевойтеория





[decal_左引擎关]
image: 左引擎关.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪1') and self.tags(includes= '飞行')
yOffsetRelative:0
xOffsetRelative:-38.5
onlyWhileAlive:true

[decal_右引擎关]
image: 右引擎关.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪1') and self.tags(includes= '飞行')
yOffsetRelative:0
xOffsetRelative:37.5
onlyWhileAlive:true

[decal_左引擎开]
image: 左引擎开.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '飞行')
yOffsetRelative:0
xOffsetRelative:-38.5
onlyWhileAlive:true

[decal_右引擎开]
image: 右引擎开.png
total_frames: 1
layer: onTop
isVisible:if not self.tags(includes= '切枪') and not self.tags(includes= '飞行')
yOffsetRelative:0
xOffsetRelative:37.5
onlyWhileAlive:true




[decal_12左关]
image: 12左关.png
total_frames: 12
frame: select(self.tags(includes= '切枪'), (self.customTimer * 11) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:0.5
xOffsetRelative:-39

[decal_12右关]
image: 12右关.png
total_frames: 12
frame: select(self.tags(includes= '切枪'), (self.customTimer * 11) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:0
xOffsetRelative:38

[decal_12左开]
image: 12左开.png
total_frames: 12
frame: select(self.tags(includes= '切枪1'), (self.customTimer * 11) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪1')
onlyWhileAlive:true
yOffsetRelative:0.5
xOffsetRelative:-39

[decal_12右开]
image: 12右开.png
total_frames: 12
frame: select(self.tags(includes= '切枪1'), (self.customTimer * 11) % 12, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪1')
onlyWhileAlive:true
yOffsetRelative:0
xOffsetRelative:38





[decal_右喷火]
image: ROOT:/余辉军团/建筑特效/喷火.png
total_frames: 4
frame: (self.customTimer * 30) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:25
yOffsetRelative:-147
isVisible: if self.isMoving()
layer: onTop
onlyWhileAlive:true
imageScale:0.85

[decal_左喷火]
image: ROOT:/余辉军团/建筑特效/喷火.png
total_frames: 4
frame: (self.customTimer * 30) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-26
yOffsetRelative:-147
isVisible: if self.isMoving()
layer: onTop
onlyWhileAlive:true
imageScale:0.85


[decal_左小喷火]
image: ROOT:/余辉军团/建筑特效/喷火.png
total_frames: 4
frame: (self.customTimer * 30) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-45
yOffsetRelative:-135
isVisible: if self.isMoving() and not memory.左转0
dirOffset:0
layer: onTop
onlyWhileAlive:true
imageScale:0.6

[decal_右小喷火]
image: ROOT:/余辉军团/建筑特效/喷火.png
total_frames: 4
frame: (self.customTimer * 30) % 4
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:45
yOffsetRelative:-135
isVisible: if self.isMoving() and not memory.右转0
dirOffset:0
layer: onTop
onlyWhileAlive:true
imageScale:0.6

[decal_主体]
image: 主体.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible:true
alpha:1

[decal_主体损坏]
image: 损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[decal_主体led]
image: LED.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
alpha:0.85


[decal_雷达影子]
image: SHADOW:雷达.png
total_frames: 1
layer: onTop
teamColors: false
isVisible:true
yOffsetRelative:2
xOffsetRelative:2
onlyWhileAlive:true
basePositionFromTurret: 2
alpha:0.65


[decal_雷达]
image: 雷达.png
total_frames: 1
layer: onTop
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
isVisible:true
alpha:1
basePositionFromTurret: 2

[decal_护盾]
image: 护盾.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:-0.5
xOffsetRelative:0.5
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1


[decal_光圈]
layer: shadow
image: 光圈2.png
onlyWhileAlive: true
teamColors: true
onlyWhenSelectedByAnyPlayer:true
hOffset:-70
alpha:0.5


[graphics]
total_frames: 1
image: 主体.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true
shadowOffsetX: 4
shadowOffsetY: 4
image_shadow: 影子.png
repairEffect: CUSTOM:尾巴, CUSTOM:光粒*2
repairEffectAtTarget:CUSTOM:闪光r, CUSTOM:火花*2
repairEffectRate:7
showQueueBar: false
showTransportBar: true
showEnergyBar: false
showShotDelayBar:false
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: true
turretSize: 19

turretTurnSpeed: 3
turretMultiTargeting: true
maxAttackRange: 445
shootDelay: 0



[turret_1]
x: 0
y: 110
idleDir: 180
warmup: 0
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true
image:手.png
size:45


[turret_2]
x: 0
y: -50
canShoot: false
image: NO.png
idleDir:180
turnSpeed: 3
turnSpeedAcceleration: 4
canAttackLandUnits: false
canOnlyAttackUnitsWithoutTags:高空
[turret_3]
x: 0
y: 5
shoot_sound: ROOT:/余辉军团/单位特效/激光炮.ogg
shoot_sound_vol: 0.4
shoot_light: #FF00B3FF
shoot_flame: NONE
invisible: true
delay: 50
projectile: beam01
size: 7
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup:10
canAttackLandUnits: false
attachedTo: 2
slave: true
canOnlyAttackUnitsWithoutTags:高空

[projectile_beam01]
@copyFromSection: template_能源
explodeEffect: CUSTOM:小等离子爆炸,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
explodeEffectOnShield: CUSTOM:小等离子爆炸,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
directDamage: 750
life: 3
instant: true
moveWithParent: true
beamImage: ROOT:/通用特效/6.png
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
delayedStartTimer:0
[projectile_beam0]
@copyFromSection: template_能源
explodeEffect: CUSTOM:小等离子爆炸,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
explodeEffectOnShield: CUSTOM:小等离子爆炸,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
directDamage: 400
life: 3
instant: true
moveWithParent: true
beamImage: ROOT:/通用特效/6.png
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
delayedStartTimer:0
[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/5.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/4.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/3.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/2.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/1.png
directDamage: 0
explodeEffect:NONE
explodeEffectOnShield:NONE
spawnProjectilesOnEndOfLife: NONE

[movement]
movementType: AIR
moveSpeed: 2.65
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.05
startingHeightOffset: 2000
targetHeightDrift: 1
fallingAccelerationDead: 0.01
reverseSpeedPercentage: 0
maxTurnSpeed: 0.8
turnAcceleration: 0.045
slowDeathFall: true
targetHeight: 70
#————————————————维修效果

[effect_尾巴]
image: SHARED:light_50.png
life: 65
fadeOut: true
attachedToUnit: false
priority: low
ySpeedRelative: 2
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.7
scaleTo: 0.7
alpha: 1
drawUnderUnits: false
[effect_闪光r]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 2
scaleTo: 2
drawUnderUnits:false
atmospheric: false
[effect_火花]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.35
physics: true
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.85
drawUnderUnits:false
xOffsetRelativeRandom:25
yOffsetRelativeRandom:25
[effect_光粒]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.2
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 1
ySpeedRelative: 3
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.85
drawUnderUnits:false
xOffsetRelativeRandom:10

#————————————————死亡

[effect_碎片]
priority: critical
image: 后碎片.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelative:0.5
ySpeedRelative:-1.5
ySpeedRelativeRandom: 0.5
yOffsetRelative: -65
xOffsetRelative: -30
hSpeed: 1.5
dirSpeed:0.1
dirSpeedRandom:0.05

[effect_碎片1]
priority: critical
image: 左碎片.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 1.5
createWhenZoomedOut: false
xSpeedRelative:-2
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.5
yOffsetRelative: -30
xOffsetRelative: -50
hSpeed: 1.5
dirSpeed:0.3
dirSpeedRandom:0.1
[ai]
useAsBuilder: true

[attachment_1]
x: 0
y: 0
canAttack:false
addTransportedUnits: true
hidden: true
isVisible:false
setDrawLayerOnBottom:true
[attachment_2]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_3]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_4]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_5]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_6]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_7]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_8]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_9]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_10]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_11]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_12]
@copyFromSection: attachment_1
x: 0
y: 0

[attachment_13]
x: 0
y: 0
canAttack:false
addTransportedUnits: true
hidden: true

[attachment_14]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_15]
@copyFromSection: attachment_1
x: 0
y: 0
[attachment_16]
@copyFromSection: attachment_1
x: 0
y: 0
