


[core]
name: 泰坦附属物1
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
energyMax: 4

energyRegen: 0.033
energyNeedsToRechargeToFull: true
tags:反高空
[hiddenAction_开始]
autoTrigger:if parent.tags(includes= '开始变形2') and not self.tags(includes= '阻')
temporarilyAddTags:阻
stopLastAnimation: true
alsoQueueAction: b

[action_b]
convertTo: 泰坦附属物
displayType: action
price: 0
buildSpeed: 4s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
temporarilyRemoveTags:阻

[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
#turretImageScale: 0.9

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 1800
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0
turretMultiTargeting: true
[turret_0]
x: -32.5
y: 215
canShoot: false
image: 炮座.png
limitingAngle: 35
limitingMinRange: 350
turnSpeed: 2
turnSpeedAcceleration: 0.2
canAttackFlyingUnits: true
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空
invisible: if self.tags(includes= '阻')
canAttackCondition:if not parent.tags(includes= '开始变形1')
[turret_1]
x: 0
y: 43
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/轨道炮音效.ogg
shoot_sound_vol: 0.35
shoot_flame: CUSTOM:烟雾*6,CUSTOM:粒子喷射*12,CUSTOM:发射闪光,CUSTOM:发射冲击波
shoot_light: #FFFFEB88
canShoot: true
recoilOffset: -17
recoilOutTime: 5
recoilReturnTime: 30
delay: 120
warmup:60
size:12
image: 内管.png
attachedTo: 0
slave: true
limitingMinRange: 350
canAttackFlyingUnits: true
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空
invisible: if self.tags(includes= '阻')
canAttackCondition:if not parent.tags(includes= '开始变形1')
[turret_2]
x: 0
y: 41.5
projectile: 2
shoot_sound:NONE
canShoot: true
recoilOffset: -6
recoilOutTime: 10
recoilReturnTime: 25
delay: 120
warmup:60
size:22
image: 炮管1.png
attachedTo: 0
slave: true
limitingMinRange: 350
canAttackFlyingUnits: true
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空
invisible: if self.tags(includes= '阻')
canAttackCondition:if not parent.tags(includes= '开始变形1')
[turret_3]
x: 0
y:0
canShoot: false
image: 炮座.png
attachedTo: 0
slave: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空
invisible: if self.tags(includes= '阻')
canAttackCondition:if not parent.tags(includes= '开始变形1')
[turret_4]
x: 0
y: 35
attachedTo: 0
projectile: 2
slave: true
delay: 35
shoot_flame: CUSTOM:电弧*2
canShoot: true
invisible: true
canAttackCondition:if not parent.tags(includes= '开始变形1')
#——————————
[turret_5]
x: 32.5
y:215
copyFrom: 0
[turret_6]
x: 0
y:43
copyFrom: 1
attachedTo: 5
slave: true
delay: 60
warmup:120
[turret_7]
x: 0
y:41.5
copyFrom: 2
image:炮管.png
attachedTo: 5
slave: true
delay: 60
warmup:120
[turret_8]
x: 0
y:0
copyFrom: 3
attachedTo: 5
slave: true
[turret_9]
x: 0
y:35
copyFrom: 4
attachedTo: 5
slave: true
[projectile_1]
@copyFromSection: template_动能
directDamage: 7500
life: 200
speed: 20
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
drawSize: 0.9
explodeEffect: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*25,CUSTOM:冲击波gd,CUSTOM:聚变gd,CUSTOM:实验,CUSTOM:穿透
explodeEffectOnShield: CUSTOM:爆炸gd, CUSTOM:爆炸1gd,CUSTOM:闪光gd,CUSTOM:碎星gd*25,CUSTOM:冲击波gd,CUSTOM:聚变gd,CUSTOM:实验,CUSTOM:穿透
lightSize: 1
trailEffectRate: 0.2
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴1,CUSTOM:尾巴2,CUSTOM:尾巴3
lightColor: #FFFF1200
armourIgnoreAmount: 9999
shieldDamageMultiplier: 1.5
[projectile_2]
directDamage: 0
life: -4
instant: true
drawSize: 0
frame: 33
color: #FF25E0AF
explodeEffect: none
#————————主炮发射特效
[effect_发射冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 3
alpha: 1

[effect_发射闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 5
scaleTo: 1
drawUnderUnits: true
atmospheric: false
[effect_粒子喷射]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false
#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1
xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2
atmospheric: true

[effect_电弧]
image: ROOT:/通用特效/红电弧.png
life: 70
priority: critical
attachedToUnit: true
scaleFrom: 0.25
scaleTo: 0.25
alpha: 0.8
total_frames: 8
animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
dirOffset:150
delayedStartTimerRandom:15
xOffsetRelativeRandom:10
yOffsetRelativeRandom:25
dirOffsetRandom: 360
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1
scaleTo: 2.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.65
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true
#——————————————尾巴
[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 20
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
drawUnderUnits: false
[effect_尾巴1]
image: ROOT:/太空浪人/单位特效/光束.png
spawnChance: 1
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.8
scaleTo: 0.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelative: -0.5
ySpeedRelativeRandom: 0.9
xSpeedRelativeRandom: 1
atmospheric: true
[effect_尾巴2]
priority: veryhigh
image: SHARED:light_50.png
life: 25
fadeOut: true
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1
drawUnderUnits: true
[effect_尾巴3]
priority: high
image: ROOT:/创世纪军事集团/单位特效/冲击波.png
life: 30
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.01
scaleTo: 0.5
alpha: 0.8
drawUnderUnits: true
atmospheric: false
#————————-——轨道
[effect_爆炸gd]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.4
scaleTo: 1.4
image: ROOT:/太空浪人/单位特效/爆炸1.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8
alsoPlaySound: ROOT:/通用特效/撞击.ogg
[effect_冲击波gd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_爆炸1gd]
image: ROOT:/创世纪军事集团/单位特效/轨道炮炸裂.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 5
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.55
alwayStartDirAtZero: true
[effect_聚变gd]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 40
fadeOut: true
attachedToUnit: false
scaleFrom: 2.8
scaleTo: 2.8
alpha: 0.6
drawUnderUnits: true
atmospheric: false
[effect_实验]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:30
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.2
scaleTo:2.5
alpha: 0.8
fadeInTime: 4
drawUnderUnits:false
[effect_碎星gd]
spawnChance: 1
createWhenZoomedOut: false
life: 45
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/粒子1.png
scaleFrom:0.25
scaleTo:0.25
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 6
ySpeedRelativeRandom: 6
[effect_穿透]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/电磁炮.png
life: 35
fadeOut: true
attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.8
scaleTo: 0.1
alpha: 1
drawUnderUnits: false
ySpeedRelative: 8
atmospheric: true
[effect_闪光gd]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 9
scaleTo: 1
drawUnderUnits: true
atmospheric: false
[arm_1]
x:-32.5
y: 180
image_end: 甲板.png
hidden:if not self.tags(includes= '阻')
[arm_2]
x:-32.5
y: 258
image_end: 内管.png
hidden:if not self.tags(includes= '阻')
[arm_3]
x:-19
y: 248
image_end: 右侧红外.png
hidden:if not self.tags(includes= '阻')
[arm_4]
x:-46
y: 248
image_end: 左侧无红外.png
hidden:if not self.tags(includes= '阻')
[arm_5]
x:-32.5
y: 215
image_end: 炮座.png
hidden:if not self.tags(includes= '阻')
[arm_6]
x:-15
y: 270
image_end: 红外.png
hidden:if not self.tags(includes= '阻')

#————————————
[arm_7]
x:32.5
y: 180
image_end: 甲板.png
hidden:if not self.tags(includes= '阻')
[arm_8]
x:32.5
y: 258
image_end: 内管.png
hidden:if not self.tags(includes= '阻')
[arm_9]
x:19
y: 248
image_end: 左侧红外.png
hidden:if not self.tags(includes= '阻')
[arm_10]
x:46
y: 248
image_end: 右侧无红外.png
hidden:if not self.tags(includes= '阻')
[arm_11]
x:32.5
y: 215
image_end: 炮座.png
hidden:if not self.tags(includes= '阻')
[arm_12]
x:15
y: 270
image_end: 红外.png
hidden:if not self.tags(includes= '阻')
[animation_部署]
#——————————红外
arm6_0s: {alpha:1}
arm6_0.5s: {alpha:0}
arm6_4s: {alpha:0}

arm12_0s: {alpha:1}
arm12_0.5s: {alpha:0}
arm12_4s: {alpha:0}
#——————————内管
arm2_0s: {x:0, y:0, dir:0}
arm2_2.5s: {x:0, y:-70, dir:0}
arm2_4s: {x:0, y:-70, dir:0}

arm8_0s: {x:0, y:0, dir:0}
arm8_2.5s: {x:0, y:-70, dir:0}
arm8_4s: {x:0, y:-70, dir:0}
#——————————非红外
arm4_0s: {x:0, y:0, dir:0}
arm4_2s: {x:0, y:0, dir:0}
arm4_2.5s: {x:-3, y:0, dir:0}
arm4_3s: {x:-3, y:-30, dir:0}
arm4_4s: {x:-3, y:-30, dir:0}

arm10_0s: {x:0, y:0, dir:0}
arm10_2s: {x:0, y:0, dir:0}
arm10_2.5s: {x:3, y:0, dir:0}
arm10_3s: {x:3, y:-30, dir:0}
arm10_4s: {x:3, y:-30, dir:0}
#——————————红外
arm3_0s: {x:0, y:0, dir:0}
arm3_2s: {x:0, y:0, dir:0}
arm3_2.5s: {x:3, y:0, dir:0}
arm3_3s: {x:3, y:-30, dir:0}
arm3_4s: {x:3, y:-30, dir:0}

arm9_0s: {x:0, y:0, dir:0}
arm9_2s: {x:0, y:0, dir:0}
arm9_2.5s: {x:-3, y:0, dir:0}
arm9_3s: {x:-3, y:-30, dir:0}
arm9_4s: {x:-3, y:-30, dir:0}

#——————————甲板
arm1_0s: {x:0, y:0, dir:0}
arm1_3s: {x:0, y:0, dir:0}
arm1_3.5s: {x:0, y:50, dir:0}
arm1_4s: {x:0, y:50, dir:0}

arm7_0s: {x:0, y:0, dir:0}
arm7_3s: {x:0, y:0, dir:0}
arm7_3.5s: {x:0, y:50, dir:0}
arm7_4s: {x:0, y:50, dir:0}


#——————————炮座
arm5_0s: {x:0, y:0, dir:0}
arm5_3s: {x:0, y:0, dir:0}
arm5_3.5s: {x:0, y:-40, dir:0}
arm5_4s: {x:0, y:-40, dir:0}

arm11_0s: {x:0, y:0, dir:0}
arm11_3s: {x:0, y:0, dir:0}
arm11_3.5s: {x:0, y:-40, dir:0}
arm11_4s: {x:0, y:-40, dir:0}





[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


