


[core]
name: 泰坦遮罩
displayText: Маска «Титан»
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true

tags:反高空
energyMax: 40
energyRegen: 0.13
energyNeedsToRechargeToFull: true

[decal_转子]
image: 动力炉子.png
total_frames: 3
frame: (self.customTimer * 18) % 3
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetRelative:-0.5
yOffsetRelative:-186
isVisible:true
onlyWhileAlive:true
[decal_左导弹井]
image: 左开启.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '开启')
yOffsetRelative:87
xOffsetRelative:-20
onlyWhileAlive:true
[decal_右导弹井]
image: 右开启.png
total_frames: 1
layer: onTop
isVisible:if self.tags(includes= '开启')

yOffsetRelative:87
xOffsetRelative:20
onlyWhileAlive:true
[decal_左开启]
image: 导弹动画1.png
total_frames: 7
frame: select(self.tags(includes= '切枪'), (self.customTimer * 14) % 7, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer:onTop
yOffsetRelative:87
xOffsetRelative:-20
[decal_左关闭]
image: 导弹动画关.png
total_frames: 7
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 14) % 7, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:87
xOffsetRelative:-19.5
[decal_右开启]
image: 导弹动画.png
total_frames: 7
frame: select(self.tags(includes= '切枪'), (self.customTimer * 14) % 7, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
layer:onTop
yOffsetRelative:87
xOffsetRelative:20
[decal_右关闭]
image: 导弹动画1关.png
total_frames: 7
frame: select(self.tags(includes= '切枪x'), (self.customTimer * 14) % 7, 0)
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:if self.tags(includes= '切枪x')
onlyWhileAlive:true
layer: onTop
yOffsetRelative:87
xOffsetRelative:19.5
[decal_灯]
image: 灯.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_灯1]
image: 灯1.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.65
#——————————导弹舱门
[hiddenAction_akm]
autoTrigger: if parent.tags(includes= '开始饱和打击') and not self.tags(includes= '关闭')
alsoQueueAction:zx
temporarilyAddTags: 切枪,关闭
resetCustomTimer: true
[action_zx]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪
temporarilyAddTags:开启
[hiddenAction_bkm]
autoTrigger: if not parent.tags(includes= '开始饱和打击') and self.tags(includes= '关闭')
alsoQueueAction:zxx
temporarilyAddTags: 切枪x
temporarilyRemoveTags: 开启
resetCustomTimer: true
[action_zxx]
displayType: action
price: 0
buildSpeed: 0.5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
temporarilyRemoveTags: 切枪x,关闭
#——————————————机库舱门
[hiddenAction_开始]
autoTrigger:if parent.tags(includes= '开舱门') and not self.tags(includes= '锥子')
temporarilyAddTags:锥子
stopLastAnimation: true
playAnimation: 开舱门

[hiddenAction_关闭]
autoTrigger:if parent.tags(includes= '关舱门') and self.tags(includes= '锥子')
temporarilyRemoveTags:锥子
stopLastAnimation: true

[graphics]
total_frames: 1
image: 新机库1.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
#turretImageScale: 0.8
teamColorsOnTurret: true
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 99999
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0
turretMultiTargeting: true
[turret_1]
x: 15
y: 160
invisible: if not parent.tags(includes= '死神')
canShoot: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.8
shoot_flame: CUSTOM:烟雾*8
shoot_light: #FFEECCCC
limitingMinRange: 200
image:死神.png
size: 80
canAttackMaxAngle: 181
idleDir: 0
turnSpeed: 0
delay: 150
warmup:150
canAttackCondition: if parent.tags(includes= '已经打开') and parent.tags(includes= '死神')
recoilOffset: -80
recoilOutTime: 0
recoilReturnTime: 80
resourceUsage:零件=10
[turret_2]
x: -15
y: 160
copyFrom: 1
warmup:210
delay:90
[turret_3]
x: 0
y: 145
canShoot: true
invisible: if not parent.tags(includes= '秃鹫')
projectile: 2
shoot_sound: ROOT:/通用特效/弹射.wav
shoot_sound_vol: 0.8
shoot_flame: CUSTOM:烟雾*8
shoot_light: #FFEECCCC
limitingMinRange: 200
image:弹射.png
size: 80
canAttackMaxAngle: 181
idleDir: 0
turnSpeed: 0
delay: 250
warmup:150 
canAttackCondition: if parent.tags(includes= '已经打开') and parent.tags(includes= '秃鹫')
recoilOffset: -80
recoilOutTime: 0
recoilReturnTime: 150
resourceUsage:零件=30
[turret_4]
x: 0
y: 145
copyFrom: 3
invisible: if not parent.tags(includes= '大力神')
image:发射.png
projectile: 3
canAttackCondition: if parent.tags(includes= '已经打开') and parent.tags(includes= '大力神')
[turret_5]
x: -20
y: 70
invisible: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾h1d*5,冲击波hd
shoot_light: #FFEECCCC
projectile: 4
size: 0
turnSpeed: 811
delay:800
limitingMinRange: 700
canOnlyAttackUnitsWithTags:被泰坦标记
canAttackCondition: if parent.tags(includes= '开始饱和打击') and self.tags(includes= '开启')
[turret_6]
x: -15
y: 81
copyFrom: 5
delay:750
warmup:50
[turret_7]
x: -20
y: 92
copyFrom: 5
delay:700
warmup:100
[turret_8]
x: -20
y: 103
copyFrom: 5
delay:650
warmup:150
[turret_9]
x: 20
y: 70
copyFrom: 5
delay:600
warmup:200
[turret_10]
x: 15
y: 81
copyFrom: 5
delay:550
warmup:250
[turret_11]
x: 20
y: 92
copyFrom: 5
delay:500
warmup:300
[turret_12]
x: 20
y: 103
copyFrom: 5
delay:450
warmup:350
[turret_21]
x: 0
y: 50
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 反导
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:180
interceptProjectiles_withTags:战术武器
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -10
invisible: true
shoot_flame: CUSTOM:烟雾at*6,CUSTOM:冲击波at,CUSTOM:闪光at
onShoot_playAnimation: 舱盖
canAttackCondition: if not parent.tags(includes= '已经打开')
resourceUsage:零件=15

[turret_21x]
x: 0
y: 50
copyFrom: 21
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战术防御天上






[turret_22]
x: 0
y: 50
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 反导
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:180
interceptProjectiles_withTags:导弹2
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -10
invisible: true
shoot_flame: CUSTOM:烟雾at*6,CUSTOM:冲击波at,CUSTOM:闪光at
onShoot_playAnimation: 舱盖
canAttackCondition: if not parent.tags(includes= '已经打开')
resourceUsage:零件=40


[turret_23]
x: 0
y: 50
copyFrom: 22
interceptProjectiles_withTags: 天上战略
interceptProjectiles_andUnderDistance: 2200
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2200
#战略防御天上


[projectile_1]
areaDamage: 0
areaRadius: 0
spawnUnit: 死神无人机(offsetHeight=140)
life: 80
speed: 7
deflectionPower:-1
drawSize: 1
targetSpeed: 1
turnSpeed: 0
trailEffect: true
image: 死神.png
areaRadiusFromEdge: true
explodeEffect:CUSTOM:无人寄碎片*2, CUSTOM:烟雾hd*7,CUSTOM:冲击波
explodeOnEndOfLife:true
initialUnguidedSpeedHeight:0
lightSize: 0
[projectile_2]
areaDamage: 0
areaRadius: 0
spawnUnit: 秃鹫无人机(offsetHeight=140)
life: 80
speed: 7
deflectionPower:-1
drawSize: 1
targetSpeed: 1
turnSpeed: 0
trailEffect: false
image: 弹射.png
areaRadiusFromEdge: true
explodeEffect:NONE
explodeOnEndOfLife:true
initialUnguidedSpeedHeight:0
lightSize: 0
shadowImage:弹射阴影.png
[projectile_3]
@copyFromSection:projectile_2
spawnUnit: 大力神无人机(offsetHeight=140)
image: 发射.png
shadowImage:发射阴影.png
[projectile_4]
life: 80
speed: 2
targetSpeed: -1
largeHitEffect: true
drawSize: 0.85
image: 战术导弹.png
directDamage: 0
ballistic: true
ballistic_height: 300
ballistic_delaymove_height: 260
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片hd,CUSTOM:冲击波hd,CUSTOM:烟雾h1d*4,CUSTOM:闪光hd,CUSTOM:音效hd
trailEffect: true
trailEffectRate: 1.2
deflectionPower: -1
drawUnderUnits:false
#autoTargetingOnDeadTarget: true
[projectile_锁定1]
areaDamage: 0
life: 30000
areaRadius: 100
alwaysVisibleInFog: true
nukeWeapon: true
speed: 0
image:导弹头x.png
targetSpeed: 12
drawSize:0.85
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: NONE
targetGroundSpread: 100
disableLeadTargeting: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate: 1.2
areaRadiusFromEdge: true
targetGround: true
ballistic: true
ballistic_height: 300
ballistic_delaymove_height: 260
drawUnderUnits:false
tags:导弹2
shouldRevealFog: true
deflectionPower: -1
#autoTargetingOnDeadTarget: true
spawnUnit:通用战略武器
[projectile_反导]
areaDamage: 0
areaRadius: 0
life: 120
speed: 18
targetSpeed: 22
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 1
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:钢珠fd,CUSTOM:爆炸fd, CUSTOM:闪光at
explodeEffectOnShield: CUSTOM:钢珠fd,CUSTOM:爆炸fd, CUSTOM:闪光at
trailEffectRate: 0.8
[arm_1]
x:-16
y: 153
image_end: 左舱盖.png
drawOverBody: true
[arm_2]
x:16
y: 153
image_end: 右舱盖.png
drawOverBody: true

[arm_3]
x: 0
y:0
image_end: 反导.png
image_end_teamColors: true
#drawOverBody: true
[arm_4]
x: 0
y:62
image_end: 上门.png
image_end_teamColors: true
drawOverBody: true
[arm_5]
x: 0
y:62
image_end: 下门.png
image_end_teamColors: true
drawOverBody: true
[arm_6]
x: 0
y: 0
image_end: 新泰坦遮盖1.png
drawOverBody: true
image_end_teamColors: true
[arm_7]
x:-20
y: 186
image_end: 左大门.png
drawOverBody: true
[arm_8]
x:20
y: 186
image_end: 右大门.png
drawOverBody: true
[arm_9]
x:0
y: -110
image_end: 雷达.png
drawOverBody: true
spinRate: 5
[animation_舱盖]
arm4_0.5s: {x:0, y:25}
arm5_0.5s: {x:0, y:-25}
[animation_开舱门]

arm7_0s: {x:0, y:0}
arm7_1.5s: {x:-30, y:0}
arm7_2s: {x:-30, y:-10}
arm7_3s: {x:-30, y:-10}
arm8_0s: {x:0, y:0}
arm8_1.5s: {x:30, y:0}
arm8_2s: {x:30, y:-10}
arm8_3s: {x:30, y:-10}

arm1_0s: {x:0, y:0}
arm1_1.5s: {x:0, y:0}
arm1_3s: {x:-28, y:0}
arm1_99999s: {x:-28, y:0}
arm2_0s: {x:0, y:0}
arm2_1.5s: {x:0, y:0}
arm2_3s: {x:28, y:0}
arm2_99999s: {x:28, y:0}


#——————————发射烟雾
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.9
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true
#——————————死神无人机
[effect_烟雾hd]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 80
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1
scaleTo: 2.8
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.14
xSpeedRelativeRandom: 0.68
atmospheric: true
[effect_无人寄碎片]
priority: critical
image: 壳.png
spawnChance: 1
life: 230
fadeOut: true
createWhenOffscreen: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.4
ySpeedRelativeRandom: 0.37
hSpeed: 3
dirSpeedRandom: 18
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.5
scaleTo: 4
alpha: 1
#——————————饱和打击
[effect_冲击波hd]
stripIndex: shockwave
life: 45
scaleFrom: 0.3
scaleTo: 2.8
alpha: 1
[effect_烟雾h1d]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.6
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_导弹碎片hd]
#priority: low
image: 导弹碎片.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.85
scaleTo: 0.85
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 50
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.8
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_音效hd]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:nuke_launch
[effect_闪光hd]
image: SHARED:light_50.png
life:30
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FFFF5B18
fadeInTime: 2
scaleFrom: 5.5
scaleTo: 1
drawUnderUnits: false
atmospheric: false
#——————————反导

[effect_闪光at]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false

[effect_烟雾at]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 2
scaleTo: 2.4
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波at]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 3
alpha: 1
#————————主武器命中


[effect_爆炸fd]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.3
scaleTo: 2.6

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/大爆炸.ogg
alwayStartDirAtZero: true


[effect_钢珠fd]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1.8
scaleTo: 2.3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


