


[core]
name: 泰坦炮组
displayText: Орудийная батарея «Титан»
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true

tags:反高空
[decal_枪管动画]
image: 枪管动画.png
total_frames: 2
frame: (self.customTimer * 14) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: onTop
isVisible: if numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=800, incompleteBuildings= true)
yOffsetRelative:15
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 12
imageScale:0.9
[decal_枪管动画1]
image: 枪管动画.png
total_frames: 2
frame: (self.customTimer * 14) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: onTop
isVisible: if numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=800, incompleteBuildings= true)
yOffsetRelative:15
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret: 13
imageScale:0.9

[decal_枪管动画2]
image: 枪管动画.png
total_frames: 2
frame: (self.customTimer * 14) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: onTop
isVisible: if numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=800, incompleteBuildings= true)
yOffsetRelative:15
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 15
imageScale:0.9
[decal_枪管动画3]
image: 枪管动画.png
total_frames: 2
frame: (self.customTimer * 14) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: onTop
isVisible: if numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=800, incompleteBuildings= true)
yOffsetRelative:15
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret: 16
imageScale:0.9
[decal_枪管动画4]
image: 枪管动画.png
total_frames: 2
frame: (self.customTimer * 14) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: onTop
isVisible: if numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=800, incompleteBuildings= true)
yOffsetRelative:15
xOffsetRelative:0
onlyWhileAlive:true
basePositionFromTurret: 18
imageScale:0.9
[decal_枪管动画5]
image: 枪管动画.png
total_frames: 2
frame: (self.customTimer * 14) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: onTop
isVisible: if numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=800, incompleteBuildings= true)
yOffsetRelative:15
xOffsetRelative:-0.5
onlyWhileAlive:true
basePositionFromTurret: 19
imageScale:0.9

[decal_炮塔影子]
image: 防空炮影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret: 5
[decal_炮管影子]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
[decal_炮管影子1]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 2
[decal_炮管影子2]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 3
[decal_炮管影子3]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 4

[decal_炮塔影子1]
image: 防空炮影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret: 10
[decal_炮管影子x]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 6
[decal_炮管影子y]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 7
[decal_炮管影子z]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 8
[decal_炮管影子c]
image: 大炮管影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 9
[decal_火神影子]
image: 火神影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:8
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret:11
imageScale:0.9
[decal_火神影子1]
image: 火神影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:8
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret:14
imageScale:0.9
[decal_火神影子2]
image: 火神影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:8
xOffsetRelative:1.5
onlyWhileAlive:true
basePositionFromTurret:17
imageScale:0.9
[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
turretImageScale: 0.9
teamColorsOnTurret: true
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
maxAttackRange: 1250
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0
turretMultiTargeting: true
[turret_1]
x: 10
y: 22
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/巨炮.ogg
shoot_sound_vol: 0.7
shoot_flame: large,CUSTOM:烟雾*4
canShoot: true
recoilOffset: -8
recoilOutTime: 4
recoilReturnTime: 35
delay: 200
image: 大炮管.png
attachedTo: 5
size:8
slave: true
limitingMinRange: 100
canOnlyAttackUnitsWithTags:高空
[turret_2]
x: 4
y: 22
copyFrom: 1
linkDelayWithTurret:1
delay:190
warmup:10
[turret_3]
x: -4
y: 22
copyFrom: 1
linkDelayWithTurret:2
delay:180
warmup:20
[turret_4]
x: -10
y: 22
copyFrom: 1
linkDelayWithTurret:3
delay:170
warmup:30
[turret_5]
x: 34
y: 39
canShoot: false
limitingAngle: 100
turnSpeed: 1.8
turnSpeedAcceleration: 0.1
image:防空炮.png
canOnlyAttackUnitsWithTags:高空
idleDir:30

[turret_6]
x: 10
y: 22
copyFrom: 1
delay:200
attachedTo: 10
slave: true
[turret_7]
x: 4
y: 22
copyFrom: 1
linkDelayWithTurret:6
delay:190
warmup:10
attachedTo: 10
slave: true
[turret_8]
x: -4
y: 22
copyFrom: 1
linkDelayWithTurret:7
delay:180
warmup:20
attachedTo: 10
slave: true
[turret_9]
x: -10
y: 22
copyFrom: 1
linkDelayWithTurret:8
delay:170
warmup:30
attachedTo: 10
slave: true
[turret_10]
x: -34
y: 39
copyFrom: 5
idleDir:-30
[turret_11]
x: 0
y: 0
canShoot: false
idleDir: 0
limitingRange: 800
image:火神.png
limitingAngle: 130
idleSweepAngle: 20
idleSweepDelay: 230
idleSweepSpeed: 1
[turret_12]
x: 8
y: 0
attachedTo: 11
slave: true
image:火神炮炮管.png
invisible:if numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=800, incompleteBuildings= true)
shoot_sound: ROOT:/创世纪军事集团/单位特效/机炮.ogg
shoot_sound_vol: 0.3
shoot_flame: small
shoot_light: #FFFFEB88
projectile: 2
limitingRange: 800
size:29
delay:5
[turret_13]
x: -8
y: 0
copyFrom: 12



[turret_14]
x: -35
y: -144.5
copyFrom: 11
idleDir:-90
limitingAngle: 100
[turret_15]
x: -8
y: 0
copyFrom: 12
attachedTo: 14
slave: true
[turret_16]
x: 8
y: 0
copyFrom: 12
attachedTo: 14
slave: true

[turret_17]
x: 35
y: -144.5
copyFrom: 11
idleDir:90
limitingAngle: 100
[turret_18]
x: -8
y: 0
copyFrom: 12
attachedTo: 17
slave: true
[turret_19]
x: 8
y: 0
copyFrom: 12
attachedTo: 17
slave: true

[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 800
areaRadius: 60
life: 250
color: #FFFFFF73
lightColor: #FFFFFF73
lightSize: 1
frame: 9
speed: 11
explodeEffect: CUSTOM:大爆炸,CUSTOM:钢珠,CUSTOM:冲击波,CUSTOM:闪光bg,CUSTOM:气浪
targetGround: true
disableLeadTargeting: true
areaRadiusFromEdge: true
trailEffectRate: 0.4
trailEffect: CUSTOM:尾巴,CUSTOM:尾巴x
drawSize: 0.8
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
targetGroundHeightOffset:140
targetGroundSpread: 70
[projectile_2]
@copyFromSection: template_动能
directDamage: 50
life: 120
speed: 15
color: #FFFFFF73
drawSize: 0.85
deflectionPower: -1
largeHitEffect: true
lightSize: 1
frame: 8
lightColor: #FFFFFF73
#——————————发射烟雾
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.9
scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1
atmospheric: true
#——————

[effect_尾巴]
image: SHARED:light_50.png
life: 15
fadeOut: true
attachedToUnit: false
priority: low
color: #FFFFFF73
fadeInTime: 2
scaleFrom: 0.4
scaleTo: 0.4
alpha: 1
drawUnderUnits: true
[effect_尾巴x]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/光束3.png
life: 17
fadeOut: true
attachedToUnit: false
yOffsetRelative	: -7
fadeInTime: 0.1
scaleFrom: 0.38
scaleTo: 0.38
alpha: 0.7
drawUnderUnits: false
#}————————主炮爆炸

[effect_大爆炸]
life: 100
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 1
image: ROOT:/创世纪军事集团/单位特效/大爆炸.png
total_frames: 40
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
animateFrameStart: 0
animateFrameEnd: 39
animateFramePingPong: false
animateFrameSpeed: 1.15
alpha: 2
[effect_冲击波]
life: 100
priority: veryhigh
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1.1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_闪光bg]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 2
scaleTo: 3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_气浪]
life: 55
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 3.8
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 0.8

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


