


[core]
name: 泰坦附属物
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
#tags:SMIB
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true
energyMax: 4

energyRegen: 0.033
energyNeedsToRechargeToFull: true
tags:反高空
[hiddenAction_开始]
autoTrigger:if parent.tags(includes= '开始变形3') and not self.tags(includes= '阻挡')
temporarilyAddTags:阻挡
stopLastAnimation: true
alsoQueueAction: b

[action_b]
convertTo: 泰坦附属物1
displayType: action
price: 0
buildSpeed: 4s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
whenBuilding_playAnimation: 部署
temporarilyRemoveTags:阻挡

[graphics]
total_frames: 1
image: NO.png
showQueueBar: false
showTransportBar: false
showEnergyBar: false
turretImageScale: 0.8
teamColorsOnTurret: true
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 2000
turretSize: 0
turretTurnSpeed: 2
shootDelay: 0.9
#aimOffsetSpread: 0
turretMultiTargeting: true
[turret_1]
x: -32.5
y: 215
canShoot: true
image: 空雷.png
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/深水炸弹.ogg
shoot_sound_vol: 1.4
shoot_flame: CUSTOM:烟雾*8,CUSTOM:发射冲击波
shoot_light: #FFEECCCC
size: 35
canAttackMaxAngle: 181
recoilOffset: -30
recoilOutTime: 0
recoilReturnTime: 180
turnSpeed: 0
delay: 240
invisible:if parent.tags(includes= '开始变形')
canAttackCondition:if not parent.tags(includes= '开始变形')
[turret_2]
x: 32.5
y:215
copyFrom: 1
warmup: 100
delay:140
[projectile_1]
areaDamage: 0
areaRadius: 0
spawnUnit: 特米纳斯浮空雷(offsetHeight=140,offsetDir=0)
life: 0
speed: 3
#deflectionPower:-1
lightSize: 0
lightColor:  #FF00B3FF
drawSize: 0
targetSpeed: 0
turnSpeed: 0
trailEffect: true
image: 空雷.png
areaRadiusFromEdge: true
explodeEffect:NONE
explodeOnEndOfLife:true
#————————主炮发射特效
[effect_发射冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 3.5
alpha: 1
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.6
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.65
xSpeedRelativeRandom: 0.5
xOffsetRelativeRandom: 0.2
ySpeedRelative: 1
atmospheric: true
[arm_1]
x:-32.5
y: 230
image_end: 甲板.png
#drawOverBody: true
#image_end_shadow: SHADOW:甲板.png
[arm_2]
x:-32.5
y: 188
image_end: 内管.png
drawOverBody: true
#hidden:if parent.tags(includes= '开始变形')
[arm_3]
x:-16
y: 218
image_end: 右侧红外.png
drawOverBody: true
#hidden:if not parent.tags(includes= '开始变形')
[arm_4]
x:-49
y: 218
image_end: 左侧无红外.png
drawOverBody: true
#hidden:if not parent.tags(includes= '开始变形')
[arm_5]
x:-32.5
y: 175
image_end: 炮座.png
drawOverBody: true
#hidden:if not parent.tags(includes= '开始变形')
[arm_6]
x:-15
y: 270
image_end: 红外.png
#drawOverBody: true
hidden:if not self.tags(includes= '阻挡')
#——————————
[arm_7]
x:32.5
y: 230
image_end: 甲板.png
#drawOverBody: true
[arm_8]
x:32.5
y: 188
image_end: 内管.png
[arm_9]
x:16
y: 218
image_end: 左侧红外.png
#drawOverBody: true
[arm_10]
x:49
y: 218
image_end: 右侧无红外.png
drawOverBody: true
[arm_11]
x:32.5
y: 175
image_end: 炮座.png
drawOverBody: true
#hidden:true
[arm_12]
x:15
y: 270
image_end: 红外.png
#drawOverBody: true
hidden:if not self.tags(includes= '阻挡')

[animation_部署]
#——————————甲板
arm1_0s: {x:0, y:0, dir:0}
arm1_1s: {x:0, y:-50, dir:0}
arm1_4s: {x:0, y:-50, dir:0}

arm7_0s: {x:0, y:0, dir:0}
arm7_1s: {x:0, y:-50, dir:0}
arm7_4s: {x:0, y:-50, dir:0}

#——————————炮座
arm5_0s: {x:0, y:0, dir:0}
arm5_1.5s: {x:0, y:0, dir:0}
arm5_2.5s: {x:0, y:40, dir:0}
arm5_4s: {x:0, y:40, dir:0}

arm11_0s: {x:0, y:0, dir:0}
arm11_1.5s: {x:0, y:0, dir:0}
arm11_2.5s: {x:0, y:40, dir:0}
arm11_4s: {x:0, y:40, dir:0}
#——————————红外
arm3_0s: {x:0, y:0, dir:0}
arm3_2s: {x:0, y:0, dir:0}
arm3_2.5s: {x:-3, y:0, dir:0}
arm3_3s: {x:-3, y:30, dir:0}
arm3_4s: {x:-3, y:30, dir:0}

arm9_0s: {x:0, y:0, dir:0}
arm9_2s: {x:0, y:0, dir:0}
arm9_2.5s: {x:3, y:0, dir:0}
arm9_3s: {x:3, y:30, dir:0}
arm9_4s: {x:3, y:30, dir:0}
#——————————非红外
arm4_0s: {x:0, y:0, dir:0}
arm4_2s: {x:0, y:0, dir:0}
arm4_2.5s: {x:3, y:0, dir:0}
arm4_3s: {x:3, y:30, dir:0}
arm4_4s: {x:3, y:30, dir:0}

arm10_0s: {x:0, y:0, dir:0}
arm10_2s: {x:0, y:0, dir:0}
arm10_2.5s: {x:-3, y:0, dir:0}
arm10_3s: {x:-3, y:30, dir:0}
arm10_4s: {x:-3, y:30, dir:0}
#——————————内管
arm2_0s: {x:0, y:0, dir:0}
arm2_2.5s: {x:0, y:0, dir:0}
arm2_3.5s: {x:0, y:70, dir:0}
arm2_4s: {x:0, y:70, dir:0}

arm8_0s: {x:0, y:0, dir:0}
arm8_2.5s: {x:0, y:0, dir:0}
arm8_3.5s: {x:0, y:70, dir:0}
arm8_4s: {x:0, y:70, dir:0}

#——————————红外
arm6_0s: {alpha:0}
arm6_3.6s: {alpha:0}
arm6_4s: {alpha:1}

arm12_0s: {alpha:0}
arm12_3.6s: {alpha:0}
arm12_4s: {alpha:1}

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 9999
turnAcceleration: 9999
targetHeight: 0
targetHeightDrift: 0

moveIgnoringBody: true


