


[core]
name: 玄鸟机库
displayText: Ангар «Чёрная Птица»
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
showInEditor: false
canNotBeDirectlyAttacked: true
disableDeathOnZeroHp: true
isUnrepairableUnit: true

isUnselectable: true
disableAllUnitCollisions: true
hideScorchMark: true
ignoreInUnitCapCalculation: true
maxTransportingUnits: 6

transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 玄鸟
transportUnitsHealBy: 6
transportUnitsRequireMovementType: air
tags:反高空,免疫烟雾
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
[hiddenAction_有炸弹]
autoTrigger: if parent.tags(includes= '用炸弹') and self.hasParent 
temporarilyAddTags: 用炸弹
temporarilyRemoveTags:用地雷,用导弹
[hiddenAction_有祸根]
autoTrigger: if parent.tags(includes= '用地雷') and self.hasParent 
temporarilyAddTags: 用地雷
temporarilyRemoveTags:用炸弹,用导弹
[hiddenAction_有导弹]
autoTrigger: if parent.tags(includes= '用导弹') and self.hasParent 
temporarilyAddTags: 用导弹
temporarilyRemoveTags:用地雷,用炸弹
[graphics]
image: NO.png
#isVisible: false
disableLowHpSmoke: true
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false
[attachment_drone1]
x: 100
y: -135
isVisible:true
addTransportedUnits: true
canAttack: false
setDrawLayerOnBottom:false
lockRotation:true
idleDir: 45
[attachment_drone2]
@copyFromSection: attachment_drone1
x: 90
y: -115
[attachment_drone3]
@copyFromSection: attachment_drone1
x: 80
y: -95

[attachment_drone4]
@copyFromSection: attachment_drone1
x: -100
y: -135
idleDir: -45
[attachment_drone5]
@copyFromSection: attachment_drone1
x: -90
y: -115
idleDir: -45
[attachment_drone6]
@copyFromSection: attachment_drone1
x: -80
y: -95
idleDir: -45
[hiddenAction_0]
autoTrigger: if not self.hasParent
deleteSelf: true


[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 6
alsoQueueAction: SDD


[hiddenAction_SDD]
buildSpeed: 4.5s
requireConditional: if memory.灰机 < 6
addUnitsIntoTransport: 玄鸟轰炸机


[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
setUnitMemory: 灰机 = memory.灰机 + 1


[hiddenAction_set1]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
setUnitMemory: 灰机 = memory.灰机 - 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 3500


[turret_233]
x: 0
y: 0
projectile: 233
delay: 0s
canAttackMaxAngle: 181
warmup:3s
invisible: true
canAttackFlyingUnits: if self.isInMap
canAttackLandUnits: if self.isInMap
canAttackUnderwaterUnits: false
unloadUpToXUnitsAndGiveAttackOrder: 1
[projectile_233]
life: 0
deflectionPower: -1
directDamage: 0
invisible: true
[arm_1]
x: 0
y: 0
image_end: 闪光灯.png
image_end_teamColors: true
drawOverBody: true
[animation_1]
onActions: idle
arm1_0s: {alpha:0}
arm1_1.5s: {alpha:0.8}
arm1_3s: {alpha:0}


[movement]
movementType: AIR
maxTurnSpeed: 9999
turnAcceleration: 9999

