


[core]
name: 无人机蜂箱
displayText: Улей дронов
displayDescription: 【Уровень t4】【мина】\n-Тактическое назначение: универсальная мина，\n-по земле и воздухупротиввысотный，взрывной урон。\n-顾имя思义Улей дронов — это видустановитьполный 杀式дрон 陷阱，\n-когдарядоместьвраг靠близковремя，隐藏вегов дронбудетбудет倾巢авыходить，\n-给врагодин огромный惊喜。
class: CustomUnitMetadata
price: 2100
maxHp: 5
buildSpeed: 18s
techLevel: 1
#availableInDemo: true
radius: 20
displayRadius: 20
energyMax: 1
energyRegen: 0
energyStartingPercentage:1
energyNeedsToRechargeToFull: true
dieOnZeroEnergy: true
numBitsOnDeath: 15
tags: 地雷,反高空
isBio: false
softCollisionOnAll: 100
fogOfWarSightRange: 5
selfBuildRate: 0.01
disableAllUnitCollisions: true
canNotBeDamaged:true
isBuilding: true
showOnMinimapToEnemies: false
canOnlyBeAttackedByUnitsWithTags:主动扫雷
[action_拆除]
displayType: action
iconImage: ROOT:/通用特效/关.png
text: 拆кроме
description: 拆кромемина
buildSpeed: 0s
highPriorityQueue: true
displayRemainingStockpile: false
deleteSelf: true


[hiddenAction_扫雷]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=50)  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)  or self.hasFlag(id=1)
deleteSelf: true
[action_显示]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=300) and not self.tags(includes= '显示')
isVisible:false
temporarilyAddTags:显示
[action_显示1]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',lessThan=1,withInRange=300) and self.tags(includes= '显示')
isVisible:false
temporarilyRemoveTags:显示
[decal_光圈a]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈b]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈c]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈1]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈2]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈3]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_地雷]
layer: afterBody
image: 蜂箱.png
onlyWhileAlive: true
imageScale:0.8
isVisible:true
onlyTeam:own
[decal_地雷1]
layer: afterBody
image: 蜂箱.png
onlyWhileAlive: true
imageScale:0.8
isVisible:if self.tags(includes= '显示')
onlyTeam:enemy


[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
imageScale: 0.8
dustEffect: false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: true
canOnlyAttackUnitsWithoutTags: 扫雷,悬浮
turretSize: 10
turretTurnSpeed: 6
maxAttackRange: 400
shootDelay: 1

#aimOffsetSpread: 0.25


[turret_1]
x: 0
y: 0
invisible: true
projectile: 1
turnSpeed: 15
turnSpeedAcceleration: 15
shoot_flame: CUSTOM:烟雾*8,CUSTOM:碎片*4
canShoot: true
delay:3000
canAttackFlyingUnits:false
energyUsage:1
[turret_2]
x: 0
y: 0
copyFrom: 1
canAttackFlyingUnits:true
canAttackLandUnits: false
canOnlyAttackUnitsWithoutTags:高空
projectile: 2
[turret_3]
x: 0
y: 0
copyFrom: 1
canAttackFlyingUnits:true
canAttackLandUnits: false
canOnlyAttackUnitsWithTags:高空
projectile: 3
[projectile_1]
directDamage: 0
life: 2
speed: 0.01
drawSize: 0
explodeOnEndOfLife: true
spawnUnit: 歌莉雅自爆机器人*7
deflectionPower: -1
explodeEffect: NONE
targetGround: true
targetGroundSpread: 60
[projectile_2]
directDamage: 0
life: 2
speed: 0.01
drawSize: 0
explodeOnEndOfLife: true
spawnUnit: 净化者无人机*5
deflectionPower: -1
explodeEffect: NONE
targetGround: true
targetGroundSpread: 60
[projectile_3]
directDamage: 0
life: 2
speed: 0.01
drawSize: 0
explodeOnEndOfLife: true
spawnUnit: 特米纳斯浮空雷*3
deflectionPower: -1
targetGround: true
targetGroundSpread: 35
explodeEffect: NONE
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 200
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 2
scaleTo: 4.5
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
xOffsetRelativeRandom:25
yOffsetRelativeRandom:25
delayedStartTimerRandom:10
atmospheric: true
[effect_碎片]
priority: critical
image: 碎片.png
spawnChance: 1
life: 360
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 2
ySpeedRelativeRandom: 2
xOffsetRelativeRandom:25
yOffsetRelativeRandom:25
yOffsetRelative: 0
xOffsetRelative: 0
hSpeed:1.5
dirSpeedRandom: 70
[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
targetHeight: -8
targetHeightDrift: 0
moveSlidingMode : true
moveIgnoringBody: true


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


