
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 毁灭之炎炮塔t3
displayText: Башня «Пламя разрушения»t3
displayDescription: 【Уровень t4】【Оборонительное здание】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение：входитьдистанцияпротивгруппабашня，вооружение：\n-▲ОДБпусковая установкаX2 только по земле нейтральный урон пробивает укрытия противбиологический юнит зданиеурон-бонус \n-можетнаносит燃烧эффект против сверхтяжёлых юнитслабый эффект есть概率генерировать燃烧район \n-запускатьновый Пусто气燃烧剂 среднийоборонапушка ，\n-способен沉тяжёлыйударразличныеюнит集группа冲锋，\n-вОбъёмно-детонирующая бомбавзрывобразовывать огромный气压差сбольшойповерхность积灼燃эффектповерхностьдо，\n-всёлёгкийбронетехникаибиологический юнитвсебудетмгновенно灰飞烟灭。
price: 8750,钍=15,bj= ${bjxq}
@global bjxq: 12
reclaimPrice: bj= ${bjxq}
maxHp: 48000
fogOfWarSightRange: 34
footprint: -2,-2,2,2
constructionFootprint: -2,-2,2,2

techLevel: 1

copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 20s
radius: 40
armour: 55

isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆破*4,largeExplosion
tags: 地面,建筑,防御建筑
energyMax: 20
energyStartingPercentage: 0
energyRegen: -0.01
energyNeedsToRechargeToFull:false
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_影子1]
image: ROOT:/创世纪军事集团/建筑特效/地板.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:2
xOffsetRelative:0
onlyWhileAlive:true
alpha:1
imageScale: 0.84
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/座2影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:9
xOffsetRelative:7
onlyWhileAlive:true
alpha:0.65
imageScale: 0.84
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/支持1.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-41
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.65
imageScale: 0.84
[decal_红热]
image:ROOT:/创世纪军事集团/建筑特效/红温.png
total_frames: 1
xOffsetRelative:-0.5
yOffsetRelative:38.5
isVisible:true
layer: onTop
alpha:(self.resource.energy)/20
onlyWhileAlive:true
basePositionFromTurret: 1
imageScale: 0.9
[decal_火焰]
image:ROOT:/创世纪军事集团/建筑特效/火焰.png
total_frames: 2
frame: (self.customTimer * 16) % 2
basePositionFromTurret: 1
isVisible:true
onlyWhileAlive:true
layer: onTop
yOffsetRelative:52.5
xOffsetRelative:0
imageScale: 0.9
[decal_转子]
image: 转子.png
total_frames: 2
frame: (self.customTimer * 30) % 2
isVisible:if self.isAttacking()
onlyWhileAlive:true
layer: onTop
yOffsetRelative:24.5
xOffsetRelative:-8.5
basePositionFromTurret: 1
imageScale: 0.9
[decal_转子1]
image: 转子.png
total_frames: 2
frame: (self.customTimer * 30) % 2
isVisible:if self.isAttacking()
onlyWhileAlive:true
layer: onTop
yOffsetRelative:24.5
xOffsetRelative:8.5
basePositionFromTurret: 1
imageScale: 0.9

[decal_装填]
image:ROOT:/创世纪军事集团/建筑特效/11.png
total_frames: 9
frame: select(self.tags(includes= '切枪'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_装填z]
image:ROOT:/创世纪军事集团/建筑特效/22.png
total_frames: 9
frame: select(self.tags(includes= '切枪1'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪1')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_装填z1]
image:ROOT:/创世纪军事集团/建筑特效/33.png
total_frames: 9
frame: select(self.tags(includes= '切枪2'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪2')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_装填z2]
image:ROOT:/创世纪军事集团/建筑特效/44.png
total_frames: 9
frame: select(self.tags(includes= '切枪3'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪3')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1

[decal_装填z3]
image:ROOT:/创世纪军事集团/建筑特效/55.png
total_frames: 9
frame: select(self.tags(includes= '切枪4'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪4')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1

#————————————————
[decal_x装填]
image:ROOT:/创世纪军事集团/建筑特效/11.png
total_frames: 9
frame: select(self.tags(includes= '切枪'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_x装填z]
image:ROOT:/创世纪军事集团/建筑特效/22.png
total_frames: 9
frame: select(self.tags(includes= '切枪1'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪1')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_x装填z1]
image:ROOT:/创世纪军事集团/建筑特效/33.png
total_frames: 9
frame: select(self.tags(includes= '切枪2'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪2')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_x装填z2]
image:ROOT:/创世纪军事集团/建筑特效/44.png
total_frames: 9
frame: select(self.tags(includes= '切枪3'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪3')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1

[decal_x装填z3]
image:ROOT:/创世纪军事集团/建筑特效/55.png
total_frames: 9
frame: select(self.tags(includes= '切枪4'), (self.customTimer * 14) % 9, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪4')
onlyWhileAlive:true
yOffsetRelative:13
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
#——————————指示灯
[decal_指示灯1]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>15
onlyWhileAlive:true
yOffsetRelative:5
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_指示灯2]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>10
onlyWhileAlive:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_指示灯3]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>5
onlyWhileAlive:true
yOffsetRelative:-3
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_指示灯4]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>0.1
onlyWhileAlive:true
yOffsetRelative:-6.5
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1

[decal_x指示灯1]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>15
onlyWhileAlive:true
yOffsetRelative:5
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_x指示灯2]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>10
onlyWhileAlive:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_x指示灯3]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>5
onlyWhileAlive:true
yOffsetRelative:-3
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1
[decal_x指示灯4]
image:ROOT:/创世纪军事集团/建筑特效/能量.png
total_frames: 1
layer:onTop
isVisible:if self.resource.弹药>0.1
onlyWhileAlive:true
yOffsetRelative:-6.5
xOffsetRelative:-0.5
imageScale: 0.9
basePositionFromTurret: 1

[decal_灯]
image:灯.png
total_frames: 1
layer:onTop
isVisible:true
onlyWhileAlive:true
yOffsetRelative:0
xOffsetRelative:0
imageScale: 0.9
basePositionFromTurret: 1
[decal_炮塔影子]
image: 烧影子.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.65
imageScale: 0.9
#——————————装弹逻辑
[hiddenAction_装]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
whenBuilding_cannotMove:false
allowMultipleInQueue:false
autoTrigger: if self.resource.弹药<0.1 and not self.tags(includes= '切枪') and not self.tags(includes= '结束')
temporarilyAddTags: 结束
alsoQueueAction: ax
[action_ax]
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
alsoQueueAction: bx
resetCustomTimer: true
temporarilyAddTags: 切枪
[action_bx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪
temporarilyAddTags: 切枪1
alsoQueueAction: cx
resetCustomTimer: true
[action_cx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
alsoQueueAction: dx
resetCustomTimer: true
temporarilyRemoveTags: 切枪1
temporarilyAddTags: 切枪2
[action_dx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
temporarilyRemoveTags: 切枪2
temporarilyAddTags: 切枪3
alsoQueueAction: ex
resetCustomTimer: true
[action_ex]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪3
temporarilyAddTags: 切枪4
alsoQueueAction: fx
[action_fx]
displayType: action
price: 0
buildSpeed: 0.6s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: false
resetCustomTimer: true
temporarilyRemoveTags: 切枪4,结束
addResources:弹药=20
[hiddenAction_装填]
addResources: energy=1.5

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯
[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
temporarilyRemoveTags: ↯
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[graphics]
total_frames: 1
image_back: ROOT:/通用特效/NO.png
image: ROOT:/创世纪军事集团/建筑特效/座2.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/中座死亡.png
image_turret: NONE
turretImageScale: 0.9
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.84
image_offsetY: -7
teamColorsOnTurret: true
[attack]
canAttack:true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 12
turretMultiTargeting:true
turretTurnSpeed: 6
maxAttackRange: 99999
shootDelay: 0
[turret_1]
x: 0
y: 31
canShoot: false
image: 烧.png
idleDir:90
turnSpeed: 1.5
turnSpeedAcceleration: 0.15
canAttackCondition: if self.resource.xk < 1
limitingRange:655
[turret_2]
x: 8
y: 28
#导弹右
projectile: 1
attachedTo: 1
slave: true
shoot_sound: ROOT:通用特效/火球发射.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾x*4,CUSTOM:火星*1,CUSTOM:闪光www
shoot_light: #FFEECCCC
canShoot: true
size:24
delay:140
canAttackCondition: if self.resource.xk < 1
invisible:true
resourceUsage:弹药=1
onShoot_triggerActions:装填
limitingRange:655
[turret_3]
x:-8
y:28
copyFrom: 2
delay:110
warmup:30
onShoot_triggerActions:装填
[turret_4]
x: -9
y: -35
canShoot: true
invisible: true
projectile: 2
shoot_sound: ROOT:/通用特效/烟幕弹音效.ogg
shoot_sound_vol: 0.1
shoot_flame: CUSTOM:烟雾z*1
size: 0
turnSpeed: 0
canAttackCondition: if self.resource.弹药 <0.1
canAttackMaxAngle: 181
delay:10
attachedTo: 1
slave: true
[turret_5]
x:9
y:-35
copyFrom: 4
[projectile_1]

areaDamage: 1350
areaRadius: 80
life: 600
speed: 12
drawSize: 0.57
largeHitEffect: true
lightSize: 3
lightColor: #FFFFFF73
image:ROOT:/创世纪军事集团/单位特效/光球.png
trailEffectRate: 0.7
trailEffect:CUSTOM:尾巴
areaRadiusFromEdge: true
disableLeadTargeting: true
targetGround: true
areaDamageNoFalloff: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.3
mutator2_ifUnitWithTags: 步兵
mutator2_areaDamageMultiplier: 2.5
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 0.6
mutator7_areaDamageMultiplier: 0.6
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=3
explodeEffect: CUSTOM:闪光wy2*2,CUSTOM:火光wy,CUSTOM:冲击波wy,CUSTOM:闪光wy1,CUSTOM:巨大冲击波wy,CUSTOM:闪光wy,CUSTOM:实验wy,CUSTOM:火星wy*2
initialUnguidedSpeedHeight: 2
targetGroundSpread: 50
spawnUnit: 铝热剂(spawnChance=0.1)
[projectile_2]
directDamage: 0
life: -4
instant: true
drawSize: 0
frame: 33
explodeEffect: none
#——————开炮
[effect_闪光www]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFFFF
scaleFrom: 4
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_烟雾z]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom:1.2
scaleTo: 1.8
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.15
xSpeedRelativeRandom: 0.4
ySpeedRelative: -1
atmospheric: true
[effect_烟雾x]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom:1.3
scaleTo: 2.4
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.6
atmospheric: true
[effect_火星]
priority:low
spawnChance: 1
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.4
scaleTo: 1.9
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelative: 1
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.2
atmospheric: true
[effect_尾巴]
priority: critical
image: ROOT:/通用特效/爆炸.png
life: 15
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 1.1
alpha: 0.75
drawUnderUnits: false
atmospheric: false
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13
animateFrameSpeed: 0.3
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
yOffsetRelative: -12
#————————温压弹
[effect_火光wy]
priority: critical
image: ROOT:/通用特效/火光.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 5
scaleTo: 5
alwayStartDirAtZero: true
color: #FFFF5B18
alpha: 0.9
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/通用特效/巨炮爆炸.wav
[effect_冲击波wy]
stripIndex: shockwave
life: 80
scaleFrom: 1
scaleTo: 6
alpha: 1
[effect_闪光wy]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFFFF
scaleFrom: 9
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true

[effect_闪光wy1]
image: SHARED:light_50.png
life: 100
fadeOut: true
alpha: 0.8
attachedToUnit: false
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 7
scaleTo: 7
drawUnderUnits: false
atmospheric: false
[effect_巨大冲击波wy]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.1
scaleTo: 2.4
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
color: #FFFF5B18
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_实验wy]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:25
fadeOut: true
attachedToUnit: true
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.8
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[effect_闪光wy2]
image: SHARED:light_50.png
life: 75
fadeOut: true
alpha: 2
attachedToUnit: false
color: #FFFFFF86
priority: critical
fadeInTime: 2
scaleFrom: 2.8
scaleTo: 2.8
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_火星wy]
priority:low
spawnChance: 1
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 100
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.8
scaleTo: 2.2
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:65
yOffsetRelativeRandom:65
[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:35
delayedStartTimerRandom:30
[resource_弹药]
displayName: Боеприпасы
displayNameShort: Боеприпасы
displayColor: #FF9D00FF
priority: 1
hidden: true
[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


