


[core]
name: 修复无人机
displayText: Ремонтный дрон
#displayText: 哨戒机枪
class: CustomUnitMetadata
displayDescription: 눈_눈
price: 0

maxHp: 1500
mass: -1
techLevel: 1
buildSpeed: 6s
transportSlotsNeeded: 999
radius: 13
fogOfWarSightRange: 13
softCollisionOnAll: 5
copyFrom: ROOT:/通用特效/单位防护.ini
isBio: false
energyMax: 3600
energyRegen: -1
dieOnZeroEnergy: true
tags: 地面,伴生单位
canRepairBuildings: true
autoRepair: true
canRepairUnits: true
nanoRepairSpeed: 2
nanoRange: 190
[hiddenAction_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
deleteSelf:true
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[hiddenAction_取消回收1]
requireConditional: ${section.autoTrigger}
autoTrigger: if self.hasActiveWaypoint(type= 'reclaim') and self.activeWaypointTarget.teamId != self.teamId
autoTriggerOnEvent: newWaypointGivenByPlayer
clearAllWaypoints: true
[graphics]
total_frames: 1
image: 底座.png
image_wreak: NONE
image_shadow: AUTO
teamColorsOnTurret: true
repairEffect: CUSTOM:尾巴, CUSTOM:尾巴1

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 22

turretTurnSpeed: 3
maxAttackRange: 190


[turret_0]
x: 0
y: 0
warmup: 0
size: 8
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true
image: 炮台.png
[effect_尾巴1]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low
ySpeedRelativeRandom: 0.5
ySpeedRelative: 1
color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true
[effect_尾巴]
priority: veryhigh
image: ROOT:/太空浪人/单位特效/光束3.png
life: 100
fadeOut: true
attachedToUnit: false

#color:
fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 0.5
alpha: 0.7
#ySpeedRelativeRandom: 0.5
drawUnderUnits: false
ySpeedRelative: 2
yOffsetRelative	: 10
[movement]
movementType: LAND
moveSpeed: 0
maxTurnSpeed: 0
turnAcceleration: 0
moveSlidingMode: false

moveIgnoringBody: true


