
[core]
name: 科普斯军事研究所
displayText: Военный институт Корпуса
class: CustomUnitMetadata
price: 8000,钍=380
maxHp: 75000
footprint: -7,-1,7,7
constructionFootprint: -7,-1,7,7
techLevel: 1
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1
buildSpeed: 80s
unitsSpawnedOnDeath:建筑损毁*2
radius: 93
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
displayDescription:【Уровень t4】【Здание】【Сверхтяжёлый юнит】【Наземный юнит】\n-Тактическое назначение：终极наукаразрабатыватьсооружение，без вооружения。\n-не может строиться на воде。-Военный институт Корпуса是довоенный各国尖端军事公司和Скитальцы科研персонал的集合体，\n-这些技术交易的самый终成果就是这座фронт综合сражение实验室--Военный институт Корпуса，\n-Корпус综合了浪人наука和Генезиссамый尖端的科学技术，\n-и藉由此производить出самый令人胆寒的用钢铁和наука铸造的庞然大物，\n-在遥далеко黑暗的恐怖未来，这个центр的наукатакже许象征着человечество的希望。
tags: 地面,科普斯,建筑,极端重型
energyNeedsToRechargeToFull: false
armour: 120
effectOnDeath: CUSTOM:烟雾*5, CUSTOM:爆破*12
fogOfWarSightRange: 30
selfRegenRate: 1
[action_重]
text: 极端重 юнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积夸张的юнит独有的характеристика，\n-иметь极端重 юнит标签的юнит将иметь如下属性，\n-иметь自愈способность，且自身护甲不低于100点，\n-无法被休克，но受до反重甲юнит伤害增益。
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='科普斯')
deleteSelf: true
showMessageToPlayer: 卡BUG？ты在想屁吃，做为惩罚多余юнитя服务устройство吞了눈_눈

[action_材料技术4]
text: Улучшенные материалы
buildSpeed: 280s
price: 8000,energy=1,钍=550
description: -Генезисвплоть до全человечество顶尖的材料科学，\n-在接受Скитальцынаука援助后，мыможетпроизводство有史с来самый强韧轻便的材料。\n-地狱之火ракета平 ，Завоеватель，Тяжёлый штурмовик класса «Похоронный звон»，Линкор-Крепость，Стратегическая ядерная подлодка класса «Поглощающая Сирена»，\n-Система ПРО «Гроза»，死亡之眼ракета的前置наука。\n-得益于передовойМатериаловедение，всемашина械сражениеюнитсамый大生命值+15%。
isVisible: if not self.globalTeamTags(includes='材料技术4')
addGlobalTeamTags: 材料技术4
addResources: energy=1
iconImage: 材料技术4.png
showMessageToPlayer: Улучшенные материалы已经разрабатывать完成
pos: 0.1
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术3')
isLockedMessage: Требуется материаловедение 3
[action_材料技术先进]
displayType: infoOnlyNoBox
iconImage: 材料技术4.png
text:已разрабатыватьУлучшенные материалы
isActive: false
pos: 2
isVisible: if self.globalTeamTags(includes='材料技术4')
[action_超导技术2]
text: Улучшенная сверхпроводимость
buildSpeed: 280s
price: 8000,energy=1,钍=450
description: -Скитальцы援助的技术将让мыможет熟练的производство出常温超导体，\n-这项关键的技术突破将使бесчисленные的军事оборудование构想становитьсяможноможет。\n-Чёрная Вдова，Воздушный канонёр класса «Серафим»，Суперкорабль，Жезл рассеивания тьмы的前置наука。\n-得益于передовойСверхпроводимость，все非英雄механический юнит移动скоростьувеличивает20%。\n-移动скорость加成的额外数值将不используется для计算衰解减速，Нанокатализатор加速等其он计算。\n-在被衰解时不обеспечивает增益。在与其он增益叠加时，将取самый大值。
isVisible: if not self.globalTeamTags(includes='超导技术2')
addGlobalTeamTags: 超导技术2
addResources: energy=1
iconImage: 超导技术3.png
showMessageToPlayer: Улучшенная сверхпроводимость已经разрабатывать完成
pos: 0.2
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='超导技术1')
isLockedMessage: Требуется сверхпроводимость 1
[action_超导技术先进]
displayType: infoOnlyNoBox
iconImage:超导技术3.png
text:已разрабатыватьУлучшенная сверхпроводимость
isActive: false
pos: 2.1
isVisible: if self.globalTeamTags(includes='超导技术2')
[action_先进目标定位核心1研发]
price: energy=1,3600,钍=275
text: Улучшенный модуль наведения1
displayType: upgrade
buildSpeed: 40s
isVisible: if not self.globalTeamTags(includes='目标定位1')
addGlobalTeamTags: 目标定位1
addResources: energy=1
description: -на основемаякразрабатывать出的第二代машина载主动можно探查式雷达系统，\n-来自Генезис科研部的наука结晶，该模块загружает后может取代машина体上原有的雷达，声纳，\n-одновременно越класс接入машина体火控系统，\n-позволяетзагружает了该模块的юнитможет极大повышаетполе боя感知способность。\n-эффективныйюнит:Танк «Челленджер»，РСЗО «Ливень»，Шок-танк，Паучонок，Истребитель «Чёрный страж»。\n-Крейсер класса «Трезубец»，Воздушный канонёр класса «Мерзость»，Линкор класса «Чёрная Жемчужина»。повышаетэффективныйюнит部分оружие35%的дальностьа также视野。
showMessageToPlayer: Улучшенный модуль наведения1已经разрабатывать完成
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位1.png
ai_isHighPriority: true
pos: 0.3

[action_先进目标定位核心2研发]
price: energy=1,5250,钍=400
text: Улучшенный модуль наведения2
displayType: upgrade
buildSpeed: 60s
isVisible: if self.globalTeamTags(includes='目标定位1') and not self.globalTeamTags(includes='目标定位2')
pos: 0.3
addGlobalTeamTags: 目标定位2
addResources: energy=1
description: -болеепередовой定位模块，только配 给немногие部队，\n-对比一代模块，он的体积более小，номожетобеспечиваетболее高的火控поддерживает，\n-毫不夸张的说，任何юнитзагружает该模块后都会产生质的变化，\n-毕竟在война中，先敌удар，先敌обнаруживатьнавсегда是王道。\n-эффективныйюнит:Завоеватель，Тяжёлый штурмовик класса «Похоронный звон»，Линейный крейсер класса «Морской волк»，Линкор-Крепость，Передовой MK2。\n-повышаетэффективныйюнит部分оружие35%的дальностьа также视野。
showMessageToPlayer: 目标定位系统2已经разрабатывать完成
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位2.png
ai_isHighPriority: true

[action_弹道导弹托1研发]
price: energy=1,5150,钍=355
text: Пусковая платформа
displayType: upgrade
buildSpeed: 100s
isVisible: if not self.globalTeamTags(includes='导弹托1')
addGlobalTeamTags: 导弹托1
addResources: energy=1
description: -通过逆向余辉垂 单元技术，разрабатывать的新一代Электромагнит弹射式ракетазапускать装置，\n-其通过Рельсотрон的原理将ракета抛射至высотный再开启ракета 动машина，\n-может极大程度上повышаетракетаоружие的дальностьи使其может命中высотныйюнит。\n-одновременно，这вид革命性的新 ракета技术такжеможет极大程度上уменьшаетдалеко程ракета所нуждается的燃料，\n-тем самым大大缩短ракета体积。из-зазапускать阶段无需为ракета点火，\n-这дажепозволяет一个垂 单元内может一次性存放数枚ракета，\n-极大повышает了огневая мощь与续航способность。эффективныйюнит:БМП «Хранитель»，Супертанк，Платформа ракет «Адский огонь»，Адский гончий，Стратегическая ядерная подлодка класса «Поглощающая Сирена»，\n-Эсминец класса «Молот-Рыба»，«Адская буря»。为эффективныйюнит的зенитная ракетаоружие添加对высотный的способность，或为эффективныйюнит的тактическое оружие的основа弹药обеспечивает二连射способность。\n-解锁Ракетная башняt3
showMessageToPlayer: Пусковая платформа已经разрабатывать完成
iconImage: ROOT:/创世纪军事集团/单位特效/导弹托.png
ai_isHighPriority: true
pos: 0.4
isLocked: if not self.globalTeamTags(includes='弹幕架3')
isLockedMessage: Требуется реактивная установка3

[action_地震弹头研发]
text: Сейсмическая боеголовка
buildSpeed: 100s
price: 7650,energy=1,钍=580
description: -通过对钍的深入研究，研究员们обнаруживать高浓度钍完全聚变所释放的может量довольно惊人，\n-поэтому，新一代的Термоядерная боеголовка代号“地震”被разрабатывать出来，\n-新弹头использовать枪式反应原理，充分的对数块高纯度钍进行加压，使其在半固态的状态下触 聚变再запускать，\n-这一反应может产生上万摄氏度的火球，мощность足с震天撼地。\n-эффективныйюнит:Супертанк，Супертанк MK2，Воздушный канонёр класса «Серафим»，Линкор-Крепость，解锁地狱之火ракета平 тактика核弹。\n-解锁Стратегический бомбардировщик класса «Заря»的стратегия核ракета。解锁Стратегическая ядерная подлодка класса «Поглощающая Сирена»的达摩克里斯之剑。\n-解锁Башня термоядерных торпедt3，\n-大幅повышаетэффективныйюнит的атакующая сила，одновременно将оружие伤害转变为中性，\n-одновременно对目标юнит附加燃烧эффект，усиленный урон по зданиям50%。
iconImage: ROOT:/创世纪军事集团/单位特效/地震弹头.png
addResources: energy=1
showMessageToPlayer: Сейсмическая боеголовка已经разрабатывать完成
addGlobalTeamTags: 地震弹头
isVisible: if not self.globalTeamTags(includes='地震弹头')
pos: 0.5
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='聚变弹头3')
isLockedMessage: Требуется термоядерная боеголовка3

[action_磁化钨棒研发]
text: 磁化钨棒
buildSpeed: 100s
price: 8000,energy=1,钍=485
description: -用钨与специальный材料混合а成的Рельсотрон炮弹，\n-这вид炮弹在轨道加速устройство的роль下может轻易洞穿самый厚重的броня，\n-再加上其специальный的磁化材料может扰乱余辉护盾装置的稳定性，\n-позволяет任何护盾装置在其面前都是一触即溃。\n-более令人眼前一亮的是，这вид炮弹дажеможет借助ракета为平 进行запускать。\n-эффективныйюнит:Завоеватель，Тяжёлый штурмовик класса «Похоронный звон»，Линейный крейсер класса «Морской волк»，Суперкорабль，解锁«Адская буря»的罐式Рельсотрон，\n-解锁Рельсотронt3,\n-将эффективныйюнит的伤害类 转变为动может点杀伤，无视основаброня，\n-усиленный урон по щитам80%，对极端重 юнит伤害加成50%，二者можно叠加。\n-有概率在射击后产生empэффект。
iconImage: ROOT:/创世纪军事集团/单位特效/轨道4.png
addResources: energy=1
showMessageToPlayer: 磁化钨棒已经разрабатывать完成
addGlobalTeamTags: 轨道4
isVisible: if not self.globalTeamTags(includes='轨道4')
pos: 0.6
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='轨道发射器3')
isLockedMessage: тынуждается轨道пусковая установка3
[action_模块化纳米煅炉研发]
text: модульный纳米煅炉
buildSpeed: 280s
price: 50000,energy=1,钍=1000
description: -一вид通过解析余辉纳米производитьоборудованиеа逆向а来的продвинутыйпроизводить技术，\n-其внутреннийзагружает的производитьмашина械точность达до纳米класс的одновременноещё保持了较为灵活的体积，\n-这вид技术способен在轻松производство多вид零вещь的одновременно保持极高的производствоточность和质量，\n-这позволяетбыстрый量产高质量юнитстановитьсяможноможет，такжепозволяетможет自я补充舰载машина的боевой корабль设想不再是空想。\n-解锁Немезида，Титан，одновременно使всеюнитпроизводствозданиепроизводствоэффективностьповышает30%，и额外获得200点补给，\n-Хранитель мира的前置наука。
iconImage: 模块化纳米煅炉.png
addResources: energy=1,bj=200
showMessageToPlayer: модульный纳米煅炉已经разрабатывать完成
addGlobalTeamTags: 纳米煅炉
isVisible: if not self.globalTeamTags(includes='纳米煅炉')
pos: 0.7
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术4') or not self.globalTeamTags(includes='超导技术2')
isLockedMessage: Требуется улучшенное материаловедение和Улучшенная сверхпроводимость。
[action_煅炉]
displayType: infoOnlyNoBox
iconImage:模块化纳米煅炉.png
text:已разрабатыватьмодульный纳米煅炉
isActive: false
pos: 2.5
isVisible: if self.globalTeamTags(includes='纳米煅炉')
[action_同步轨道加速器研发]
text: 同步轨道加速устройство
buildSpeed: 280s
price: 50000,energy=1,钍=1000
description: -在对超导材料а такжеСкитальцы质量加速устройство的充分研究后，производить的самый大масштаб的质量加速устройство，\n-同步轨道加速устройство相比于обычный的轨道加速устройство，не толькоможет将различные弹丸与实体加速до难с置信的скорость，\n-дажеможет将核聚变产生的等离子体около束и加速，\n-这видмощный质量加速устройствоможет广универсальный于轨道运输，重工业。或者используется дляпроизводитьсамый具毁灭性的终极оружие。\n-解锁BFG Ядерное Орудие，Сияние Чёрной Вдовы，одновременно使всеБуровая платформа每秒额外产出40资源。\n-и且使Лазерная буровая на тории每秒额外产出3钍，\n-Хранитель мира的前置наука。
iconImage: 同步轨道加速器.png
addResources: energy=1
showMessageToPlayer: 同步轨道加速устройство已经разрабатывать完成
addGlobalTeamTags: 同步轨道加速器
isVisible: if not self.globalTeamTags(includes='同步轨道加速器')
pos: 0.8
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术4') or not self.globalTeamTags(includes='超导技术2')
isLockedMessage: Требуется улучшенное материаловедение和Улучшенная сверхпроводимость。



[action_加速器]
displayType: infoOnlyNoBox
iconImage:同步轨道加速器.png
text:已разрабатывать同步轨道加速устройство
isActive: false
pos: 2.8
isVisible: if self.globalTeamTags(includes='同步轨道加速器')
[decal_核心]
image: 核心.png
total_frames: 9
frame: (self.customTimer * 20) % 9
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-0.5
yOffsetAbsolute:37.5
isVisible:if self.maxHp * 0.36 < self.hp
[decal_玻璃]
image: 玻璃.png
total_frames: 1
xOffsetAbsolute:-0.5
isVisible:if self.maxHp * 0.36 < self.hp
[graphics]
total_frames: 1
image: 雷达.png
image_wreak: 死亡.png
image_shadow: 影子.png
image_back:背景.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:false
canAttackUnderwaterUnits: false
maxAttackRange:0
turretSize: 0
turretTurnSpeed: 0
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0


[arm_1]
x: -118
y: 50
image_end: 箱子.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_2]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_3]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_4]
x: 0
y: 0
image_end: 灯光1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_5]
x: 0
y: 0
image_end: 灯光2.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_6]
x: 0
y: 0
image_end: 灯光3.png
image_end_teamColors: false
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_8]
x: -110
y: 150
image_end: 雷达.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -45
hidden: if self.hp<self.maxHp * 0.36 
[arm_9]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_10]
x: -110
y: 150
image_end: 雷达损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
drawDirOffset: -45

[animation_1]
onActions: idle
blendIn: 0.2s
blendOut: 0.2s
arm4_0s: {alpha:0.0}
arm4_1.3s: {alpha:1}
arm4_2.6s: {alpha:0.1}
arm5_0s: {alpha:0.0}
arm5_0.65s: {alpha:1}
arm5_1.3s: {alpha:0.1}
arm5_1.95s: {alpha:1}
arm5_2.6s: {alpha:0.1}
arm6_0s: {alpha:0.0}
arm6_0.65s: {alpha:1}
arm6_1.3s: {alpha:0.1}
arm6_1.95s: {alpha:1}
arm6_2.6s: {alpha:0.1}
arm1_0s: {x:0, y:0}
arm1_1.3s: {x:0, y:50}
arm1_1.7s: {x:0, y:50}
arm1_2.3s: {x:0, y:0}
arm1_2.6s: {x:0, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 360
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.4
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 50
yOffsetRelativeRandom: 70
xSpeedAbsoluteRandom: 0.35
ySpeedAbsoluteRandom: 0.35
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.8
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:100
yOffsetRelativeRandom:180
delayedStartTimerRandom:40

[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
maxEachBase: 1
maxGlobal: 1
noneGlobalExtraPriority:0.5