
[core]
name: 科普斯军事研究所
displayText: Военный институт Корпуса
class: CustomUnitMetadata
price: 8000,钍=380
maxHp: 75000
footprint: -7,-1,7,7
constructionFootprint: -7,-1,7,7
techLevel: 1
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1
buildSpeed: 80s
unitsSpawnedOnDeath:建筑损毁*2
radius: 93
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
displayDescription:【Уровень t4】【Здание】【Сверхтяжёлый юнит】【Наземный юнит】\n-Тактическое назначение：предельныйнаукаразрабатыватьсооружение，без вооружения。\n-не может строиться на воде。-Военный институт Корпусаявляетсядовоенныйкаждыйстранапередовойвоенный公司иСкитальцы科研персонал 集合体，\n-этот些технология交лёгкий в конечном счётерезультаттоявляетсяэтот фронт综合сражениереальный验室--Военный институт Корпуса，\n-Корпус综合 浪человекнаукаиГенезиссамыйпередовой 科学технология，\n-и藉тем самымпроизводитьвыходитьсамый令человек胆寒 использоватьстальжелезоинаука铸создавать колосс，\n-в遥далеко黑暗 ужасающийнеприходить，этот центр наукатакжеразрешать象征 человечество 希望。
tags: 地面,科普斯,建筑,极端重型
energyNeedsToRechargeToFull: false
armour: 120
effectOnDeath: CUSTOM:烟雾*5, CUSTOM:爆破*12
fogOfWarSightRange: 30
selfRegenRate: 1
[action_重]
text: крайне端тяжёлыйюнит
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积преувеличивать юнит独есть характеристика，\n-иметькрайне端тяжёлыйюнит标签 юнитбудетиметькакнизпринадлежатьтип，\n-иметь 愈способность，исобственный护甲ненизкийв100пункт，\n-не может шок，но受допротивтяжёлый甲юнит伤害бафф。
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='科普斯')
deleteSelf: true
showMessageToPlayer: 卡BUG？тыв想屁吃，делатьв качествештрафмногоостатокюнитя服务устройство吞 눈_눈

[action_材料技术4]
text: Улучшенные материалы
buildSpeed: 280s
price: 8000,energy=1,钍=550
description: -Генезисвплоть довсечеловечество顶尖 材料科学，\n-вприниматьСкитальцынаукапомощьпосле，мыможетпроизводствоза всю историюсильнейший韧лёгкий 材料。\n- 狱егоогоньракетаплатформа，Завоеватель，Тяжёлый штурмовик класса «Похоронный звон»，Линкор-Крепость，Стратегическая ядерная подлодка класса «Поглощающая Сирена»，\n-Система ПРО «Гроза»，死亡его眼ракета предварительная технология。\n- 益впередовойМатериаловедение，всемеханическийсражениеюнитмаксимальный生命值+15%。
isVisible: if not self.globalTeamTags(includes='材料技术4')
addGlobalTeamTags: 材料技术4
addResources: energy=1
iconImage: 材料技术4.png
showMessageToPlayer: Улучшенные материалыужеразрабатыватьзавершать
pos: 0.1
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术3')
isLockedMessage: Требуется материаловедение 3
[action_材料技术先进]
displayType: infoOnlyNoBox
iconImage: 材料技术4.png
text:ужеразрабатыватьУлучшенные материалы
isActive: false
pos: 2
isVisible: if self.globalTeamTags(includes='材料技术4')
[action_超导技术2]
text: Улучшенная сверхпроводимость
buildSpeed: 280s
price: 8000,energy=1,钍=450
description: -Скитальцыпомощь технологиябудетпозволяетмыможетумелый производствовыходитьсверхпроводник при комнатной температуре，\n-этот项关键 технология突破будетпозволятьбесчисленные военныйоборудование构想становитьсявозможно。\n-Чёрная Вдова，Воздушный канонёр класса «Серафим»，Суперкорабль，Жезл рассеивания тьмы предварительная технология。\n- 益впередовойСверхпроводимость，всенегероймеханический юнит移动скоростьувеличивает20%。\n-移动скорость加становиться 额внезначениебудетнеиспользуется для计算衰解замедление，Нанокатализатор加速и т.д.другие计算。\n-в 衰解времянеобеспечиваетбафф。всдругиебафф叠加время，будет取максимум。
isVisible: if not self.globalTeamTags(includes='超导技术2')
addGlobalTeamTags: 超导技术2
addResources: energy=1
iconImage: 超导技术3.png
showMessageToPlayer: Улучшенная сверхпроводимостьужеразрабатыватьзавершать
pos: 0.2
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='超导技术1')
isLockedMessage: Требуется сверхпроводимость 1
[action_超导技术先进]
displayType: infoOnlyNoBox
iconImage:超导技术3.png
text:ужеразрабатыватьУлучшенная сверхпроводимость
isActive: false
pos: 2.1
isVisible: if self.globalTeamTags(includes='超导技术2')
[action_先进目标定位核心1研发]
price: energy=1,3600,钍=275
text: Улучшенный модуль наведения1
displayType: upgrade
buildSpeed: 40s
isVisible: if not self.globalTeamTags(includes='目标定位1')
addGlobalTeamTags: 目标定位1
addResources: energy=1
description: -на основемаякразрабатыватьвыходить номервторое поколениемашинавезтиглавный动можно探查式雷达система，\n-приходить Генезис科研部 наукавенец，указанный模块загружаетпослеможет取поколениемашина体верхоригиналесть 雷达，声纳，\n-одновременно越класссоединять入машина体огоньуправлятьсистема，\n-позволяетзагружает указанный模块 юнитможеточень большойповышаетполе боячувствоватьзнатьспособность。\n-эффективный юнит:Танк «Челленджер»，РСЗО «Ливень»，Шок-танк，Паучонок，Истребитель «Чёрный страж»。\n-Крейсер класса «Трезубец»，Воздушный канонёр класса «Мерзость»，Линкор класса «Чёрная Жемчужина»。повышаетэффективный юнитчастьоружие35% дальностьа такжесчитать野。
showMessageToPlayer: Улучшенный модуль наведения1ужеразрабатыватьзавершать
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位1.png
ai_isHighPriority: true
pos: 0.3

[action_先进目标定位核心2研发]
price: energy=1,5250,钍=400
text: Улучшенный модуль наведения2
displayType: upgrade
buildSpeed: 60s
isVisible: if self.globalTeamTags(includes='目标定位1') and not self.globalTeamTags(includes='目标定位2')
pos: 0.3
addGlobalTeamTags: 目标定位2
addResources: energy=1
description: -болеепередовой定позиция模块，только配 给немногиевойска，\n-против比первое поколение模块，он 体积меньше，номожетобеспечиваетвыше огоньуправлятьподдерживает，\n-вовсе непреувеличивать говорить，любойюнитзагружаетуказанный模块послевсебудетпроизводит质 изменение，\n-毕竟вна войне，опередить врагаудар，опередить врагаобнаруживатьнавсегдаявляется王道。\n-эффективный юнит:Завоеватель，Тяжёлый штурмовик класса «Похоронный звон»，Линейный крейсер класса «Морской волк»，Линкор-Крепость，Передовой MK2。\n-повышаетэффективный юнитчастьоружие35% дальностьа такжесчитать野。
showMessageToPlayer: цель定позициясистема2ужеразрабатыватьзавершать
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位2.png
ai_isHighPriority: true

[action_弹道导弹托1研发]
price: energy=1,5150,钍=355
text: Пусковая платформа
displayType: upgrade
buildSpeed: 100s
isVisible: if not self.globalTeamTags(includes='导弹托1')
addGlobalTeamTags: 导弹托1
addResources: energy=1
description: -через逆кЗаревоВПУтехнология，разрабатывать новыйпервое поколениеЭлектромагнитснаряд射式ракетазапускатьустановить置，\n-егочерезРельсотрон оригинал理будетракета抛射至высотныйсновавключитьракета 动машина，\n-можеточень большойстепеньверхповышаетракетаоружие дальностьипозволятьегоможет命ввысотныйюнит。\n-одновременно，этот вид革命тип новый ракетатехнологиятакжеможеточень большойстепеньверхуменьшаетдальнийракета所нуждается 燃料，\n-тем самымбольшойбольшой缩短ракета体积。из-зазапускать阶периоднет需в качестверакетапунктогонь，\n-этотдажепозволяетодин ВПУвможетодин разтип存放число ракета，\n-очень большойповышает огневая мощьспродолжатьходспособность。эффективный юнит:БМП «Хранитель»，Супертанк，Платформа ракет «Адский огонь»，Адский гончий，Стратегическая ядерная подлодка класса «Поглощающая Сирена»，\n-Эсминец класса «Молот-Рыба»，«Адская буря»。в качествеэффективный юнит зенитная ракетаоружие添加противвысотный способность，或в качествеэффективный юнит тактическое оружие основаБоеприпасыобеспечивает二соединять射способность。\n-разблокироватьРакетная башняt3
showMessageToPlayer: Пусковая платформаужеразрабатыватьзавершать
iconImage: ROOT:/创世纪军事集团/单位特效/导弹托.png
ai_isHighPriority: true
pos: 0.4
isLocked: if not self.globalTeamTags(includes='弹幕架3')
isLockedMessage: Требуется реактивная установка3

[action_地震弹头研发]
text: Сейсмическая боеголовка
buildSpeed: 100s
price: 7650,energy=1,钍=580
description: -черезпротив钍 深入исследовать，исследовать员们обнаруживатьвысокий浓度钍полныйвсе聚变所释放 энергиядовольноудивительный，\n-поэтому，новыйпервое поколение Термоядерная боеголовкапоколение号“ 震” разрабатыватьвыходит，\n-новыйснаряд头использовать枪式реакцияоригинал理，充минута противчисло块высокий纯度钍выполнять加压，позволятьегов半固состояние состояниениз触 聚变сновазапускать，\n-этотодинреакцияможетпроизводитверхдесять тысяч摄氏度 огонь球，мощностьдостаточно для震небо撼 。\n-эффективный юнит:Супертанк，Супертанк MK2，Воздушный канонёр класса «Серафим»，Линкор-Крепость，разблокировать 狱егоогоньракетаплатформатактикаядерныйснаряд。\n-разблокироватьСтратегический бомбардировщик класса «Заря» стратегияядерныйракета。разблокироватьСтратегическая ядерная подлодка класса «Поглощающая Сирена» 达摩克里斯его剑。\n-разблокироватьБашня термоядерных торпедt3，\n-большой幅повышаетэффективный юнит атакующая сила，одновременнобудеторужие伤害превращениев качествевтип，\n-одновременнопротивцельюнит附加燃烧эффект，усиленный урон по зданиям50%。
iconImage: ROOT:/创世纪军事集团/单位特效/地震弹头.png
addResources: energy=1
showMessageToPlayer: Сейсмическая боеголовкаужеразрабатыватьзавершать
addGlobalTeamTags: 地震弹头
isVisible: if not self.globalTeamTags(includes='地震弹头')
pos: 0.5
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='聚变弹头3')
isLockedMessage: Требуется термоядерная боеголовка3

[action_磁化钨棒研发]
text: 磁化钨棒
buildSpeed: 100s
price: 8000,energy=1,钍=485
description: -использовать钨сспециальный材料混合астановиться Рельсотронснаряд，\n-этот видснарядворбитальный加速устройство рольнизможетлёгкийлёгкий洞穿самыйтолстыйтяжёлый броня，\n-снова加верхегоспециальный 磁化材料может扰乱Зарево护盾установить置 稳定тип，\n-позволяетлюбой护盾установить置вегоповерхностьдовсе — это 触то есть溃。\n-более令человек眼доодин亮 является，этот видснаряддажеможет借助ракетав качествеплатформавыполнятьзапускать。\n-эффективный юнит:Завоеватель，Тяжёлый штурмовик класса «Похоронный звон»，Линейный крейсер класса «Морской волк»，Суперкорабль，разблокировать«Адская буря» 罐式Рельсотрон，\n-разблокироватьРельсотронt3,\n-будетэффективный юнит 伤害类 превращениев качестве动можетпункт杀伤，игнорироватьосноваброня，\n-усиленный урон по щитам80%，против сверхтяжёлых юнитурон-бонус50%，二者можно叠加。\n-есть概率в射ударпослепроизводитempэффект。
iconImage: ROOT:/创世纪军事集团/单位特效/轨道4.png
addResources: energy=1
showMessageToPlayer: 磁化钨棒ужеразрабатыватьзавершать
addGlobalTeamTags: 轨道4
isVisible: if not self.globalTeamTags(includes='轨道4')
pos: 0.6
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='轨道发射器3')
isLockedMessage: тынуждаетсяорбитальныйпусковая установка3
[action_模块化纳米煅炉研发]
text: модульныйнано煅炉
buildSpeed: 280s
price: 50000,energy=1,钍=1000
description: -видчерез解析Заревонанопроизводитьоборудованиеа逆каприходить продвинутыйпроизводитьтехнология，\n-еговнутреннийзагружает производитьмеханическийточность达донанокласс одновременноещё保持 относительнов качествегибкий 体积，\n-этот видтехнологияспособенвлёгкий松производстворазныезапчасти одновременно保持очень высокий производствоточностьикачество，\n-этотпозволяетбыстрый量产высокийкачествоюнитстановитьсявозможно，такжепозволяетможет я补充舰везтимашина боевой корабль设想больше неявляетсяПусто想。\n-разблокироватьНемезида，Титан，одновременнопозволятьвсеюнитпроизводствозданиепроизводствоэффективностьповышает30%，и额внеполучить200пункт补给，\n-Хранитель мира предварительная технология。
iconImage: 模块化纳米煅炉.png
addResources: energy=1,bj=200
showMessageToPlayer: модульныйнано煅炉ужеразрабатыватьзавершать
addGlobalTeamTags: 纳米煅炉
isVisible: if not self.globalTeamTags(includes='纳米煅炉')
pos: 0.7
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术4') or not self.globalTeamTags(includes='超导技术2')
isLockedMessage: Требуется улучшенное материаловедениеиУлучшенная сверхпроводимость。
[action_煅炉]
displayType: infoOnlyNoBox
iconImage:模块化纳米煅炉.png
text:ужеразрабатыватьмодульныйнано煅炉
isActive: false
pos: 2.5
isVisible: if self.globalTeamTags(includes='纳米煅炉')
[action_同步轨道加速器研发]
text: 同步орбитальный加速устройство
buildSpeed: 280s
price: 50000,energy=1,钍=1000
description: -впротивсупер导材料а такжеСкитальцыкачество加速устройство 充минутаисследоватьпосле，производить максимальныймасштаб качество加速устройство，\n-同步орбитальный加速устройство相比вобычныйорбитальный加速устройство，не толькоможетбудетразличныеснарядсреальный体加速дотрудно置信 скорость，\n-дажеможетбудетядерный聚变производит и т.д.离сын体около束и加速，\n-этот видмощныйкачество加速устройствоможет广универсальныйворбитальныйтранспорт，тяжёлый工业。或者используется дляпроизводитьсамый具毁灭тип предельныйоружие。\n-разблокироватьBFG Ядерное Орудие，Сияние Чёрной Вдовы，одновременнопозволятьвсеБуровая платформаза секунду额вне产выходить40资源。\n-иипозволятьЛазерная буровая на торииза секунду额вне产выходить3钍，\n-Хранитель мира предварительная технология。
iconImage: 同步轨道加速器.png
addResources: energy=1
showMessageToPlayer: 同步орбитальный加速устройствоужеразрабатыватьзавершать
addGlobalTeamTags: 同步轨道加速器
isVisible: if not self.globalTeamTags(includes='同步轨道加速器')
pos: 0.8
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术4') or not self.globalTeamTags(includes='超导技术2')
isLockedMessage: Требуется улучшенное материаловедениеиУлучшенная сверхпроводимость。



[action_加速器]
displayType: infoOnlyNoBox
iconImage:同步轨道加速器.png
text:ужеразрабатывать同步орбитальный加速устройство
isActive: false
pos: 2.8
isVisible: if self.globalTeamTags(includes='同步轨道加速器')
[decal_核心]
image: 核心.png
total_frames: 9
frame: (self.customTimer * 20) % 9
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-0.5
yOffsetAbsolute:37.5
isVisible:if self.maxHp * 0.36 < self.hp
[decal_玻璃]
image: 玻璃.png
total_frames: 1
xOffsetAbsolute:-0.5
isVisible:if self.maxHp * 0.36 < self.hp
[graphics]
total_frames: 1
image: 雷达.png
image_wreak: 死亡.png
image_shadow: 影子.png
image_back:背景.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:false
canAttackUnderwaterUnits: false
maxAttackRange:0
turretSize: 0
turretTurnSpeed: 0
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0


[arm_1]
x: -118
y: 50
image_end: 箱子.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_2]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_3]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_4]
x: 0
y: 0
image_end: 灯光1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_5]
x: 0
y: 0
image_end: 灯光2.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_6]
x: 0
y: 0
image_end: 灯光3.png
image_end_teamColors: false
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_8]
x: -110
y: 150
image_end: 雷达.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -45
hidden: if self.hp<self.maxHp * 0.36 
[arm_9]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_10]
x: -110
y: 150
image_end: 雷达损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
drawDirOffset: -45

[animation_1]
onActions: idle
blendIn: 0.2s
blendOut: 0.2s
arm4_0s: {alpha:0.0}
arm4_1.3s: {alpha:1}
arm4_2.6s: {alpha:0.1}
arm5_0s: {alpha:0.0}
arm5_0.65s: {alpha:1}
arm5_1.3s: {alpha:0.1}
arm5_1.95s: {alpha:1}
arm5_2.6s: {alpha:0.1}
arm6_0s: {alpha:0.0}
arm6_0.65s: {alpha:1}
arm6_1.3s: {alpha:0.1}
arm6_1.95s: {alpha:1}
arm6_2.6s: {alpha:0.1}
arm1_0s: {x:0, y:0}
arm1_1.3s: {x:0, y:50}
arm1_1.7s: {x:0, y:50}
arm1_2.3s: {x:0, y:0}
arm1_2.6s: {x:0, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 360
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.4
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 50
yOffsetRelativeRandom: 70
xSpeedAbsoluteRandom: 0.35
ySpeedAbsoluteRandom: 0.35
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.8
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:100
yOffsetRelativeRandom:180
delayedStartTimerRandom:40

[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
maxEachBase: 1
maxGlobal: 1
noneGlobalExtraPriority:0.5