
[core]
name: 科普斯军事研究所
class: CustomUnitMetadata
price: 8000,钍=380
maxHp: 75000
footprint: -7,-1,7,7
constructionFootprint: -7,-1,7,7
techLevel: 1
energyMax: 1
energyRegen: 0
energyStartingPercentage: 1
buildSpeed: 80s
unitsSpawnedOnDeath:建筑损毁*2
radius: 93
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
isBuilding: true
displayDescription:【阶级t4】【建筑单位】【极端重型单位】【地面单位】\n-战术定位：终极科技研发设施，无武装。\n-无法在水上建造。-科普斯军事研究所是战前各国尖端军事公司和太空浪人科研人员的集合体，\n-这些技术交易的最终成果就是这座前线综合作战实验室--科普斯军事研究所，\n-科普斯综合了浪人科技和创世纪最尖端的科学技术，\n-并藉由此制造出最令人胆寒的用钢铁和科技铸造的庞然大物，\n-在遥远黑暗的恐怖未来，这个中心的科技也许象征着人类的希望。
tags: 地面,科普斯,建筑,极端重型
energyNeedsToRechargeToFull: false
armour: 120
effectOnDeath: CUSTOM:烟雾*5, CUSTOM:爆破*12
fogOfWarSightRange: 30
selfRegenRate: 1
[action_重]
text: 极端重型单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积夸张的单位独有的特性，\n-拥有极端重型单位标签的单位将拥有如下属性，\n-拥有自愈能力，且自身护甲不低于100点，\n-无法被休克，但是受到反重甲单位伤害增益。
[hiddenAction_refund]
autoTrigger: if numberOfUnitsInTeam(greaterThan=1, withTag='科普斯')
deleteSelf: true
showMessageToPlayer: 卡BUG？你在想屁吃，做为惩罚多余单位我服务器吞了눈_눈

[action_材料技术4]
text: 先进材料技术
buildSpeed: 280s
price: 8000,energy=1,钍=550
description: -创世纪乃至全人类顶尖的材料科学，\n-在接受太空浪人科技援助后，我们能生产有史以来最强韧轻便的材料。\n-地狱之火导弹平台，征服者，丧钟级重型攻击机，战列要塞，噬海女妖级战略核潜艇，\n-雷暴导弹防御系统，死亡之眼导弹的前置科技。\n-得益于先进的材料技术，所有机械作战单位最大生命值+15%。
isVisible: if not self.globalTeamTags(includes='材料技术4')
addGlobalTeamTags: 材料技术4
addResources: energy=1
iconImage: 材料技术4.png
showMessageToPlayer: 先进材料技术已经研发完成
pos: 0.1
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术3')
isLockedMessage: 你需要材料技术3
[action_材料技术先进]
displayType: infoOnlyNoBox
iconImage: 材料技术4.png
text:已研发先进材料技术
isActive: false
pos: 2
isVisible: if self.globalTeamTags(includes='材料技术4')
[action_超导技术2]
text: 先进超导技术
buildSpeed: 280s
price: 8000,energy=1,钍=450
description: -太空浪人援助的技术将让我们能熟练的生产出常温超导体，\n-这项关键的技术突破将使无数的军事设备构想成为可能。\n-黑寡妇，炽天使级空中炮艇，超战舰，破暗雷杖的前置科技。\n-得益于先进的超导技术，所有非英雄机械单位移动速度增加20%。\n-移动速度加成的额外数值将不用于计算衰解减速，纳米催化剂加速等其他计算。\n-在被衰解时不提供增益。在与其他增益叠加时，将取最大值。
isVisible: if not self.globalTeamTags(includes='超导技术2')
addGlobalTeamTags: 超导技术2
addResources: energy=1
iconImage: 超导技术3.png
showMessageToPlayer: 先进超导技术已经研发完成
pos: 0.2
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='超导技术1')
isLockedMessage: 你需要超导技术1
[action_超导技术先进]
displayType: infoOnlyNoBox
iconImage:超导技术3.png
text:已研发先进超导技术
isActive: false
pos: 2.1
isVisible: if self.globalTeamTags(includes='超导技术2')
[action_先进目标定位核心1研发]
price: energy=1,3600,钍=275
text: 先进目标定位核心1
displayType: upgrade
buildSpeed: 40s
isVisible: if not self.globalTeamTags(includes='目标定位1')
addGlobalTeamTags: 目标定位1
addResources: energy=1
description: -基于信标研发出的第二代机载主动可探查式雷达系统，\n-来自创世纪科研部的科技结晶，该模块装载后可以取代机体上原有的雷达，声纳，\n-同时越级接入机体火控系统，\n-使得装载了该模块的单位能极大提升战场感知能力。\n-有效单位:挑战者坦克，暴雨火箭炮，休克打击坦克，幼蛛，黑色守卫战斗机。\n-三叉戟级巡洋舰，憎恶级空中炮艇，黑珍珠级战列舰。提升有效单位部分武器35%的射程以及视野。
showMessageToPlayer: 先进目标定位核心1已经研发完成
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位1.png
ai_isHighPriority: true
pos: 0.3

[action_先进目标定位核心2研发]
price: energy=1,5250,钍=400
text: 先进目标定位核心2
displayType: upgrade
buildSpeed: 60s
isVisible: if self.globalTeamTags(includes='目标定位1') and not self.globalTeamTags(includes='目标定位2')
pos: 0.3
addGlobalTeamTags: 目标定位2
addResources: energy=1
description: -更先进的定位模块，只配发给少数部队，\n-对比一代模块，它的体积更小，但是能提供更高的火控支持，\n-毫不夸张的说，任何单位装载该模块后都会产生质的变化，\n-毕竟在战争中，先敌打击，先敌发现永远是王道。\n-有效单位:征服者，丧钟级重型攻击机，海狼级战列巡洋舰，战列要塞，尖兵MK2。\n-提升有效单位部分武器35%的射程以及视野。
showMessageToPlayer: 目标定位系统2已经研发完成
iconImage: ROOT:/创世纪军事集团/单位特效/目标定位2.png
ai_isHighPriority: true

[action_弹道导弹托1研发]
price: energy=1,5150,钍=355
text: 弹道导弹托
displayType: upgrade
buildSpeed: 100s
isVisible: if not self.globalTeamTags(includes='导弹托1')
addGlobalTeamTags: 导弹托1
addResources: energy=1
description: -通过逆向余辉垂发单元技术，研发的新一代电磁弹射式导弹发射装置，\n-其通过轨道炮的原理将导弹抛射至高空再开启导弹发动机，\n-能极大程度上提升导弹武器的射程并使其能命中高空单位。\n-同时，这种革命性的新型导弹技术也能极大程度上减少远程导弹所需要的燃料，\n-从而大大缩短导弹体积。由于发射阶段无需为导弹点火，\n-这甚至使得一个垂发单元内能一次性存放数枚导弹，\n-极大提升了火力与续航能力。有效单位:守护者IFV，超坦克，地狱火导弹平台，地狱猎犬，噬海女妖级战略核潜艇，\n-双髻鲨级驱逐舰，地狱风暴。为有效单位的防空导弹武器添加对高空的能力，或为有效单位的战术武器的基础弹药提供二连射能力。\n-解锁火箭弹幕炮塔t3
showMessageToPlayer: 弹道导弹托已经研发完成
iconImage: ROOT:/创世纪军事集团/单位特效/导弹托.png
ai_isHighPriority: true
pos: 0.4
isLocked: if not self.globalTeamTags(includes='弹幕架3')
isLockedMessage: 你需要弹幕架3

[action_地震弹头研发]
text: 地震弹头
buildSpeed: 100s
price: 7650,energy=1,钍=580
description: -通过对钍的深入研究，研究员们发现高浓度钍完全聚变所释放的能量相当惊人，\n-因此，新一代的聚变弹头代号“地震”被研发出来，\n-新弹头使用枪式反应原理，充分的对数块高纯度钍进行加压，使其在半固态的状态下触发聚变再发射，\n-这一反应能产生上万摄氏度的火球，威力足以震天撼地。\n-有效单位:超坦克，超坦克MK2，炽天使级空中炮艇，战列要塞，解锁地狱之火导弹平台战术核弹。\n-解锁黎明曙光级战略轰炸机的战略核导弹。解锁噬海女妖级战略核潜艇的达摩克里斯之剑。\n-解锁聚变鱼雷炮塔t3，\n-大幅提升有效单位的攻击力，同时将武器伤害转变为中性，\n-同时对目标单位附加燃烧效果，对建筑伤害加成50%。
iconImage: ROOT:/创世纪军事集团/单位特效/地震弹头.png
addResources: energy=1
showMessageToPlayer: 地震弹头已经研发完成
addGlobalTeamTags: 地震弹头
isVisible: if not self.globalTeamTags(includes='地震弹头')
pos: 0.5
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='聚变弹头3')
isLockedMessage: 你需要聚变弹头3

[action_磁化钨棒研发]
text: 磁化钨棒
buildSpeed: 100s
price: 8000,energy=1,钍=485
description: -用钨与特殊材料混合而成的轨道炮炮弹，\n-这种炮弹在轨道加速器的作用下能轻易洞穿最厚重的装甲，\n-再加上其特殊的磁化材料能扰乱余辉护盾装置的稳定性，\n-使得任何护盾装置在其面前都是一触即溃。\n-更令人眼前一亮的是，这种炮弹甚至能借助导弹为平台进行发射。\n-有效单位:征服者，丧钟级重型攻击机，海狼级战列巡洋舰，超战舰，解锁地狱风暴的罐式轨道炮，\n-解锁轨道炮t3,\n-将有效单位的伤害类型转变为动能点杀伤，无视基础装甲，\n-对护盾伤害加成80%，对极端重型单位伤害加成50%，二者可叠加。\n-有概率在射击后产生emp效果。
iconImage: ROOT:/创世纪军事集团/单位特效/轨道4.png
addResources: energy=1
showMessageToPlayer: 磁化钨棒已经研发完成
addGlobalTeamTags: 轨道4
isVisible: if not self.globalTeamTags(includes='轨道4')
pos: 0.6
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='轨道发射器3')
isLockedMessage: 你需要轨道发射器3
[action_模块化纳米煅炉研发]
text: 模块化纳米煅炉
buildSpeed: 280s
price: 50000,energy=1,钍=1000
description: -一种通过解析余辉纳米制造设备而逆向而来的先进制造技术，\n-其内部装载的制造机械精度达到纳米级的同时还保持了较为灵活的体积，\n-这种技术能够在轻松生产多种零件的同时保持极高的生产精度和质量，\n-这使得快速量产高质量单位成为可能，也使得能自我补充舰载机的战舰设想不再是空想。\n-解锁复仇女神，泰坦，同时使所有单位生产建筑生产效率提升30%，并额外获得200点补给，\n-和平守卫者的前置科技。
iconImage: 模块化纳米煅炉.png
addResources: energy=1,bj=200
showMessageToPlayer: 模块化纳米煅炉已经研发完成
addGlobalTeamTags: 纳米煅炉
isVisible: if not self.globalTeamTags(includes='纳米煅炉')
pos: 0.7
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术4') or not self.globalTeamTags(includes='超导技术2')
isLockedMessage: 你需要先进材料技术和先进超导技术。
[action_煅炉]
displayType: infoOnlyNoBox
iconImage:模块化纳米煅炉.png
text:已研发模块化纳米煅炉
isActive: false
pos: 2.5
isVisible: if self.globalTeamTags(includes='纳米煅炉')
[action_同步轨道加速器研发]
text: 同步轨道加速器
buildSpeed: 280s
price: 50000,energy=1,钍=1000
description: -在对超导材料以及太空浪人质量加速器的充分研究后，制造的最大规模的质量加速器，\n-同步轨道加速器相比于普通的轨道加速器，不仅能将各种弹丸与实体加速到难以置信的速度，\n-甚至能将核聚变产生的等离子体约束并加速，\n-这种强大的质量加速器能广泛用于轨道运输，重工业。或者用于制造最具毁灭性的终极武器。\n-解锁BFG核子巨炮，黑寡妇之耀，同时使所有的钻井平台每秒额外产出40资源。\n-并且使钍激光钻机每秒额外产出3钍，\n-和平守卫者的前置科技。
iconImage: 同步轨道加速器.png
addResources: energy=1
showMessageToPlayer: 同步轨道加速器已经研发完成
addGlobalTeamTags: 同步轨道加速器
isVisible: if not self.globalTeamTags(includes='同步轨道加速器')
pos: 0.8
ai_isHighPriority: true
isLocked: if not self.globalTeamTags(includes='材料技术4') or not self.globalTeamTags(includes='超导技术2')
isLockedMessage: 你需要先进材料技术和先进超导技术。



[action_加速器]
displayType: infoOnlyNoBox
iconImage:同步轨道加速器.png
text:已研发同步轨道加速器
isActive: false
pos: 2.8
isVisible: if self.globalTeamTags(includes='同步轨道加速器')
[decal_核心]
image: 核心.png
total_frames: 9
frame: (self.customTimer * 20) % 9
# 8为图片帧数，17改速度，1/17s下一帧
xOffsetAbsolute:-0.5
yOffsetAbsolute:37.5
isVisible:if self.maxHp * 0.36 < self.hp
[decal_玻璃]
image: 玻璃.png
total_frames: 1
xOffsetAbsolute:-0.5
isVisible:if self.maxHp * 0.36 < self.hp
[graphics]
total_frames: 1
image: 雷达.png
image_wreak: 死亡.png
image_shadow: 影子.png
image_back:背景.png


[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits:false
canAttackUnderwaterUnits: false
maxAttackRange:0
turretSize: 0
turretTurnSpeed: 0
[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0


[arm_1]
x: -118
y: 50
image_end: 箱子.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_2]
x: 0
y: 0
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_3]
x: 0
y: 0
image_end: 灯光.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_4]
x: 0
y: 0
image_end: 灯光1.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_5]
x: 0
y: 0
image_end: 灯光2.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_6]
x: 0
y: 0
image_end: 灯光3.png
image_end_teamColors: false
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36 
[arm_8]
x: -110
y: 150
image_end: 雷达.png
image_end_teamColors: true
drawOverBody: true
drawDirOffset: -45
hidden: if self.hp<self.maxHp * 0.36 
[arm_9]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_10]
x: -110
y: 150
image_end: 雷达损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
drawDirOffset: -45

[animation_1]
onActions: idle
blendIn: 0.2s
blendOut: 0.2s
arm4_0s: {alpha:0.0}
arm4_1.3s: {alpha:1}
arm4_2.6s: {alpha:0.1}
arm5_0s: {alpha:0.0}
arm5_0.65s: {alpha:1}
arm5_1.3s: {alpha:0.1}
arm5_1.95s: {alpha:1}
arm5_2.6s: {alpha:0.1}
arm6_0s: {alpha:0.0}
arm6_0.65s: {alpha:1}
arm6_1.3s: {alpha:0.1}
arm6_1.95s: {alpha:1}
arm6_2.6s: {alpha:0.1}
arm1_0s: {x:0, y:0}
arm1_1.3s: {x:0, y:50}
arm1_1.7s: {x:0, y:50}
arm1_2.3s: {x:0, y:0}
arm1_2.6s: {x:0, y:0}
[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 360
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.4
scaleTo: 0.9
alpha: 0.8
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 50
yOffsetRelativeRandom: 70
xSpeedAbsoluteRandom: 0.35
ySpeedAbsoluteRandom: 0.35
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2.8
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:100
yOffsetRelativeRandom:180
delayedStartTimerRandom:40

[ai]
buildPriority: 0.1
ai_upgradePriority: 0.1
maxEachBase: 1
maxGlobal: 1
noneGlobalExtraPriority:0.5