
[resource_电磁]
displayName: Электромагнит
displayNameShort: Электромагнит
displayColor: #FF9D00FF
priority: 1
hidden: true

[core]
name: 铝热剂
displayText: Термит
class: CustomUnitMetadata
price: 100
maxHp: 1200
armour: 9300000

techLevel: 1
buildSpeed: 0.01
#availableInDemo: true
isUnselectable: true

numBitsOnDeath: 0
showInEditor: false
radius: 0
#displayRadius: 20
isBio: false

isBuilding: true
tags:危险物品
softCollisionOnAll: 1000
canOnlyBeAttackedByUnitsWithTags:消防
[hiddenAction_扫雷]
autoTrigger: if self.hasFlag(id=1)
deleteSelf: true
[decal_弹坑]
image: ROOT:/通用特效/弹坑.png
total_frames: 1
layer: shadow
isVisible: if not self.isOverLiquid
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
imageScale:1.1
[hiddenAction_man1]
autoTrigger: if self.isOverLiquid and not self.isOverPassableTile(type='WATER')
isVisible: false
deleteSelf:true
[action_t1]
autoTrigger: if self.timeAlive(laterThanSeconds=18) and self.resource.电磁<1
isVisible: false
addResources: hp=-999999

[action_t2]
autoTrigger: if self.timeAlive(laterThanSeconds=10) and self.resource.电磁>1
isVisible: false
addResources: hp=-999999
[graphics]
total_frames: 1
image: NO.png
image_wreak: NO.png
image_turret: NO.png
image_shadow: NONE

shadowOffsetX: 1
shadowOffsetY: 1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 20

turretTurnSpeed: 40
maxAttackRange: 99999
shootDelay: 1


[turret_烟雾]
x: 0
y: 0
projectile: 13
shoot_flame: CUSTOM:烟雾,CUSTOM:闪光,CUSTOM:火星
delay: 15
size:0
invisible: true
canAttackCondition: if self.resource.电磁<1

[turret_火焰]
x: 0
y: 0
projectile: 13
shoot_flame: CUSTOM:聚变,CUSTOM:火焰
delay: 8
invisible: true
size: 0
canAttackCondition: if self.resource.电磁<1

[turret_1]
#area shock turret
x: 0
y: 0
invisible: true
canAttackFlyingUnits: true

canAttackLandUnits: true
canAttackUnderwaterUnits: false
projectile: 1
turnSpeed: 5.0
canAttackCondition: if self.resource.电磁<1
shoot_sound: NONE
shoot_sound_vol: 0.9
shoot_flame: NONE
canShoot: true
size: 0
delay: 3


[turret_烟雾1]
x: 0
y: 0
projectile: 13
shoot_flame: CUSTOM:烟雾1,CUSTOM:闪光1,CUSTOM:火星1
delay: 15
size:0
invisible: true
canAttackCondition: if self.resource.电磁>1

[turret_火焰1]
x: 0
y: 0
projectile: 13
shoot_flame: CUSTOM:聚变1,CUSTOM:火焰1
delay: 8
invisible: true
size: 0
canAttackCondition: if self.resource.电磁>1

[turret_12]
#area shock turret
x: 0
y: 0
invisible: true
canAttackFlyingUnits: true

canAttackLandUnits: true
canAttackUnderwaterUnits: false
projectile: 2
turnSpeed: 5.0
canAttackCondition: if self.resource.电磁>1
shoot_sound: NONE
shoot_sound_vol: 0.9
shoot_flame: NONE
canShoot: true
size: 0
delay: 3





[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1


[projectile_1]
areaDamage: 210
areaRadius: 60
speed: 11
life: 1
instant: false
largeHitEffect: false
explodeOnEndOfLife: true
deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.3
mutator2_ifUnitWithTags: 步兵
mutator2_directDamageMultiplier: 2
mutator2_areaDamageMultiplier: 2
mutator7_ifUnitWithTags: 极端重型
mutator7_directDamageMultiplier: 1.5
mutator7_areaDamageMultiplier: 1.5
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=1
shieldDamageMultiplier:0.2
armourIgnoreAmount: 20



[projectile_2]
areaDamage: 210
areaRadius: 60
speed: 11
life: 1
instant: false
largeHitEffect: false
explodeOnEndOfLife: true
deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1
buildingDamageMultiplier: 1.3
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: 燃烧=1
armourIgnoreAmount: 20





[effect_烟雾]
priority: low
image: SHARED:light_50.png
life: 135
fadeOut: true
color:  #FFFF5B18
attachedToUnit: true
scaleTo: 2.7
scaleFrom: 1.5
alpha: 0.8
hSpeed: 1.2
drawUnderUnits: false
atmospheric: true
spawnChance: 1
xSpeedRelative: 0.2
xSpeedRelativeRandom: 0.4
xSpeedAbsoluteRandom: 0.3
yOffsetRelative	: 14
alsoPlaySound: ROOT:/通用特效/燃烧.ogg


[effect_火焰]
priority: critical
image: 光束.png
life: 20
fadeOut: true
attachedToUnit: true
fadeInTime: 0.8
scaleTo: 5
scaleFrom: 3.5
alpha: 1
drawUnderUnits: false
atmospheric: false
spawnChance: 1
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1
attachedToUnit: false
color:  #FFFF5B18
fadeInTime: 1
scaleFrom: 4
scaleTo: 1
drawUnderUnits: true
atmospheric: false
[effect_聚变]
priority: high
image: ROOT:/通用特效/火光.png
life: 7
fadeOut: true
attachedToUnit: false
alpha: 0.8
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 2.7
scaleTo: 2.7
ySpeedAbsolute: -0.5
color: #FFFFF44C
alwayStartDirAtZero: true
createWhenOffscreen: true
xOffsetRelativeRandom:17
yOffsetRelativeRandom:7
spawnChance: 0.8
[effect_火星]
priority:low
image: ROOT:/创世纪军事集团/单位特效/火星.png
createWhenZoomedOut: false
life: 150
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.5
scaleTo: 2
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
spawnChance: 0.5
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:40
yOffsetRelativeRandom:40


#——————————


[effect_烟雾1]
priority: low
image: SHARED:light_50.png
life: 135
fadeOut: true
color: #FF00B3FF
attachedToUnit: true
scaleTo: 2.7
scaleFrom: 1.5
alpha: 0.8
hSpeed: 1.2
drawUnderUnits: false
atmospheric: true
spawnChance: 1
xSpeedRelative: 0.2
xSpeedRelativeRandom: 0.4
xSpeedAbsoluteRandom: 0.3
yOffsetRelative	: 14
alsoPlaySound: ROOT:/通用特效/燃烧.ogg


[effect_火焰1]
priority: critical
image: ROOT:/余辉军团/单位特效/蓄能.png
life: 20
fadeOut: true
attachedToUnit: true
fadeInTime: 0.8
scaleTo: 5
scaleFrom: 3.5
alpha: 1
drawUnderUnits: false
atmospheric: false
spawnChance: 1
xSpeedRelativeRandom: 0.2
ySpeedRelativeRandom: 0.2
[effect_闪光1]
priority: low
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FF00B3FF
fadeInTime: 1
scaleFrom: 4
scaleTo: 1
drawUnderUnits: true
atmospheric: false
[effect_聚变1]
priority: high
image: ROOT:/通用特效/火光y.png
life: 7
fadeOut: true
attachedToUnit: false
alpha: 0.8
drawUnderUnits: false
atmospheric: false
showInFog: true
scaleFrom: 2.7
scaleTo: 2.7
ySpeedAbsolute: -0.5
alwayStartDirAtZero: true
createWhenOffscreen: true
xOffsetRelativeRandom:17
yOffsetRelativeRandom:7
spawnChance: 0.8
[effect_火星1]
priority:low
image: ROOT:/余辉军团/单位特效/火星.png
createWhenZoomedOut: false
life: 150
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.5
scaleTo: 2
alpha: 1.2
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0
spawnChance: 0.5
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
atmospheric: true
xOffsetRelativeRandom:40
yOffsetRelativeRandom:40





[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.1
maxTurnSpeed: 0

turnAcceleration: 0.1
moveSlidingMode : false
moveIgnoringBody: false


