[core]
name: 鱼叉导弹
displayText: Гарпун-ракета
displayDescription: -别玩沙盒 。
class: CustomUnitMetadata
price: 0
maxHp: 1
techLevel: 1
canNotBeGivenOrdersByPlayer: true
softCollisionOnAll: 20
buildSpeed: 0.0007
radius: 16
canNotBeDamaged: true
fogOfWarSightRange: 8
numBitsOnDeath:0
explodeOnDeath: false
canNotBeDirectlyAttacked: true
showInEditor:false
showOnMinimapToEnemies: false
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 3000
energyRegen: -1
dieOnZeroEnergy: true
effectOnDeath:CUSTOM:主体碎片
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[resource_电磁]
displayName: Электромагнит
displayNameShort: Электромагнит
displayColor: #FF9D00FF
priority: 1
hidden: true
[action_ax]
autoTrigger: if self.timeAlive(laterThanSeconds=5)	and not self.tags(includes= '部署') and self.resource.电磁>0.5
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
temporarilyAddTags: 部署
spawnEffects:CUSTOM:导弹碎片*2
[action_bx]
autoTrigger: if self.timeAlive(laterThanSeconds=5)	and not self.tags(includes= '部署') and self.resource.电磁<0.5
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
temporarilyAddTags: 部署
spawnEffects:CUSTOM:导弹碎片x,CUSTOM:导弹碎片x1
[hiddenAction_答辩]
autoTrigger:if not self.isMoving()
addWaypoint_target_nearestUnit_tagged: 地面
addWaypoint_target_nearestUnit_team: enemy
addWaypoint_maxTime: 1s
addWaypoint_type: move
[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
splastEffect: true
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2
showEnergyBar: false
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: true
turretSize: 1
turretTurnSpeed: 25
maxAttackRange: 700
isMelee: true
meleeEngangementDistance: 99999

#isFixedFiring: true
[turret_1]
x: 0
y: 0
canShoot: false
limitingAngle: 25
[turret_2]
x: 0
y: 14
invisible: true
attachedTo: 1
slave: true
size:0
shoot_sound: ROOT:/余辉军团/单位特效/瓶1.ogg
shoot_sound_vol: 0.45
shoot_flame: CUSTOM:闪光1
shoot_light: #FF004AFF
projectile: beam0
canAttackCondition:if self.tags(includes= '部署') and self.resource.电磁>0.5
delay: 300
warmup: 30
limitingAngle: 25
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
[turret_3]
x: 0
y: 14
attachedTo: 1
slave: true
shoot_light: #FFEECCCC
shoot_sound_vol: 0
warmup: 30
delay: 300
projectile: 2
size: 0
canAttackCondition:if self.tags(includes= '部署') and self.resource.电磁>0.5
invisible: true
limitingAngle: 25
[turret_4]
x: 0
y: 10
copyFrom: 3
[turret_5]
x: 0
y: 14
invisible: true
attachedTo: 1
slave: true
size:0
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 0.6
shoot_flame: CUSTOM:烟雾f*5
projectile: 1
canAttackCondition:if self.tags(includes= '部署') and self.resource.电磁<0.5
delay: 300
warmup: 30
limitingAngle: 25
[projectile_1]
life: 1
speed: 0
targetSpeed: 0
largeHitEffect: false
drawSize: 0.1
frame: 1
trailEffect: false
directDamage: 0
spawnProjectilesOnEndOfLife: 锁定*5
[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 0
areaRadius: 0
targetSpeed: 9
life: 18000
speed: 3
color: #FFFFFF73
largeHitEffect: true
lightSize: 3
lightColor: #FFFFFF73
image: ROOT:/创世纪军事集团/单位特效/光球.png
drawSize: 0.6
trailEffectRate: 0.4
initialUnguidedSpeedHeight: 1.5
trailEffect: CUSTOM:尾巴s
areaRadiusFromEdge: true
disableLeadTargeting: true
targetGround: true
explodeEffect:NONE
spawnUnit: 铝热剂
speedSpread:2
targetGroundSpread: 180
[projectile_2]
life: 10
instant: true
directDamage: 0
lightingEffect: true
explodeEffect: NONE
[projectile_beam0]
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:闪电,CUSTOM:粒子*18,CUSTOM:电弧*8
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:闪电,CUSTOM:电弧*8
areaDamage: 800
areaRadius: 75
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 10
life: 3
instant: true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true
beamImage: ROOT:/通用特效/闪电1q.png
#beamImageOffsetRate: 2
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
shieldDamageMultiplier:40
armourIgnoreAmount: 99999
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电2q.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0
[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电3q.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电4q.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电5q.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电6q.png
spawnProjectilesOnEndOfLife: beam6(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam6]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电7q.png
spawnProjectilesOnEndOfLife: beam7(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam7]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电8q.png
spawnProjectilesOnEndOfLife: NONE
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0







[arm_1]
x: 0
y: 0
image_end: 电磁弹1.png
image_end_teamColors: false
drawOverBody: true
image_end_shadow: SHADOW:电磁弹1.png
hidden:if self.resource.电磁<0.5
[arm_2]
x: -3
y: 16
image_end: 电磁弹碎片.png
image_end_teamColors: false
drawOverBody: true
image_end_shadow: SHADOW:电磁弹碎片.png
hidden:if self.tags(includes= '部署') or self.resource.电磁<0.5
[arm_3]
x: 3
y: 16
image_end: 电磁弹碎片1.png
image_end_teamColors: false
drawOverBody: true
image_end_shadow: SHADOW:电磁弹碎片1.png
hidden:if self.tags(includes= '部署') or self.resource.电磁<0.5
[arm_4]
x: 0
y: 0
image_end: 子母弹1.png
image_end_teamColors: false
drawOverBody: true
image_end_shadow: SHADOW:子母弹1.png
hidden:if self.resource.电磁>0.5
[arm_5]
x: 0
y: 14
image_end: 子母弹碎片.png
image_end_teamColors: false
drawOverBody: true
image_end_shadow: SHADOW:子母弹碎片.png
hidden:if self.tags(includes= '部署') or self.resource.电磁>0.5
[arm_6]
x: 0
y: 20
image_end: 子母弹碎片1.png
image_end_teamColors: false
drawOverBody: true
image_end_shadow: SHADOW:子母弹碎片1.png
hidden:if self.tags(includes= '部署') or self.resource.电磁>0.5

[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 0
ySpeedRelative: -2
yOffsetRelative	: -18
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 0
#ySpeedRelative: -0.2
yOffsetRelative	: -21
#drawUnderUnits: true

[effect_导弹碎片]
#priority: low
image: 电磁弹碎片1.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50
yOffsetRelative	: 16
ySpeedRelative:1
[effect_导弹碎片x]
#priority: low
image: 子母弹碎片.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50
yOffsetRelative	: 14
ySpeedRelative:1
[effect_导弹碎片x1]
#priority: low
image: 子母弹碎片1.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50
yOffsetRelative	: 20
ySpeedRelative:1
[effect_主体碎片]
#priority: low
image: 碎片.png
spawnChance: 1
life: 120
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 5
ySpeedRelative:2
[effect_爆炸]
life: 70
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.6
image:ROOT:/通用特效/电磁爆炸.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.8

#color:#FFFF1200


[effect_粒子]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.5
scaleTo: 0.5

alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7

ySpeedRelativeRandom: 3.7
#atmospheric: true


[effect_闪电]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false

attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2

animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 1

drawUnderUnits: false
scaleFrom: 4
scaleTo: 4


[effect_闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false

color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 6
scaleTo: 1
drawUnderUnits: false

atmospheric: false
[effect_电弧]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: ROOT:/通用特效/电弧.png
total_frames: 8
animateFrameStart:1
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 0.85
drawUnderUnits: false
scaleFrom: 0.8
scaleTo:0.8
xOffsetRelativeRandom:60
yOffsetRelativeRandom:60
createWhenOffscreen: true
delayedStartTimerRandom:20
[effect_闪光1]
image: SHARED:light_50.png
life: 60
fadeOut: true
alpha: 1
attachedToUnit: true
color:  #FF004AFF
fadeInTime: 2
scaleFrom: 1
scaleTo: 1
drawUnderUnits: false
atmospheric: false
[effect_烟雾f]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 90
fadeOut: true
attachedToUnit: true
fadeInTime: 10
scaleFrom: 0.5

scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.3
xSpeedRelativeRandom: 0.4
yOffsetRelative: 1
ySpeedRelative: 0.3
atmospheric: true
[effect_尾巴s]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low
color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1
drawUnderUnits: true
[movement]
movementType: AIR
moveSpeed: 2.5
moveAccelerationSpeed: 100
moveDecelerationSpeed: 0
maxTurnSpeed: 1.4
turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false

