


[core]
name: 方舟武士
displayText: 方舟武士
displayDescription: -方舟武士与余辉的HK徘徊者渊源于诺瓦帝国的同一款机甲，\n-太空浪人按照遗留的蓝图并结合自己的设计打造出了方舟武士，\n-虽然没有原装HK徘徊者功能强大，\n-，但方舟武士专精于近战与突击，\n-只需眨眼的功夫方舟武士就能突然出现在敌人的面前，\n-然后使用高周波巨刃将他们大卸八块。\n-只能对地，无战损，近身攻击。中性伤害，反掩体
class: CustomUnitMetadata
techLevel: 1

buildSpeed: 20s
radius: 24
selfRegenRate: 0.2
price: 3300
maxHp: 3000

armour: 6
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 10
energyRegen: 0.0024
tags: 地面,射程x

unitsSpawnedOnDeath: 损毁*1
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[action_1_强袭]
fireTurretXAtGround: 强袭
text: 强袭
displayType: action
buildSpeed: 0s
pos: 0.1

displayRemainingStockpile: true
highPriorityQueue: true
price: energy=7
canPlayerCancel: false
onlyOneUnitAtATime: false

description: 将能量汇聚于动力系统，\n-以难以置信的速度冲向敌人。
isLocked:if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

[action_t1]
autoTrigger: if self.isOverLiquid
isVisible: false
addResources: hp=-999999


[graphics]
image: 方舟武士主体.png
image_wreak: 方舟武士死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 12
isFixedFiring: true
maxAttackRange: 55
shootDelay: 30
meleeEngangementDistance: 345

isMelee: true
aimOffsetSpread: -0.01


[turret_强袭]
x: 0
y: 0
canShoot: false
idleDir: 0
invisible: true

size: 1.1
turnSpeed: 40
shoot_sound: NONE
shoot_sound_vol: 0.6
projectile: 22

limitingRange: 300


[turret_1]
x: 0
y: 0
image: 方舟武士主体.png
turnSpeed: 28
turnSpeedAcceleration: 0.3

canShoot: false


[turret_3]
x: 0
y: 0
invisible: true
delay: 90
projectile: 2

turnSpeed: 100
turnSpeedAcceleration: 0.07
shoot_sound: ROOT:/通用特效/光剑.ogg
onShoot_playAnimation: attack
shoot_flame: CUSTOM:刀光

canShoot: true
size: 1
attachedTo: 1
idleDir: 0
slave: true

canAttackCondition: if self.resource.xk < 1


[arm_1]
x: 19
y: 10
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: -20
moveSpeed: 6


[arm_2]
x: 18
y: 21
image_end: 刀.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 240
moveSpeed: 6


[arm_3]
x: 11
y: 0
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 40
moveSpeed: 6


[arm_4]
x: -25
y: -13
image_end: 刀鞘.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 60


[arm_5]
x: -10
y: 7
image_end: 胳膊.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 200


[projectile_2]
life: 5000
areaDamage: 400
areaRadius: 30
instant: true
speed: 10

targetSpeed: 10
explodeEffect: CUSTOM:sparks*10 ,CUSTOM:闪光
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_22]
life: 600
directDamage: 0
speed: 7
targetSpeed: 7
image: 方舟武士2.png

drawSize: 1
targetGroundSpread: 8
targetGround: true
deflectionPower: -1
trailEffect: CUSTOM:尾巴

explodeEffect: CUSTOM:闪光,CUSTOM:冲击波
teleportSource: true


[animation_attack]
#onActions: attack
blendIn: 0.2s
blendOut: 0.2s
arm2_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm5_0s: {x:0, y:0, dir:0}
arm1_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm2_0.1s: {x:10, y:6, dir:0}
arm4_0.2s: {x:-7, y:-7, dir:-7}

arm5_0.2s: {x:-7, y:-7, dir:0}
arm1_0.1s: {x:8, y:6, dir:0}
arm3_0.1s: {x:8, y:4, dir:0}
arm2_0.15s: {x:11, y:8, dir:0}
arm1_0.15s: {x:9, y:8, dir:0}

arm2_0.16s: {x:11, y:8, dir:90}
arm1_0.16s: {x:9, y:8, dir:35}
arm2_0.17s: {x:11, y:7, dir:100}
arm1_0.17s: {x:7, y:5, dir:50}
arm2_0.4s: {x:11, y:8, dir:0}

arm1_0.4s: {x:9, y:8, dir:-5}


[leg_1]
x: -9
y: -1.5
attach_x: -8
attach_y: -1
moveSpeed: 4

rotateSpeed: 10
heightSpeed: 3
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false
holdDisMin: 28

holdDisMax: 42
hardLimit: 60


[leg_2]
x: 8
y: -1.5
attach_x: 8
attach_y: -1
copyFrom: 1

drawDirOffset: 10


[effect_刀光]
life: 20
spawnChance: 1
priority: critical
attachedToUnit: false
scaleFrom: 0.5

scaleTo: 0.5
image: 刀光.png
color: #FFFF1200


[effect_sparks]
attachedToUnit: false
life: 60
scaleFrom: 0.3
scaleTo: 0.3
physics: true

xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: ROOT:/太空浪人/单位特效/光束.png
alpha: 0.7


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2


[effect_尾巴]
priority: critical
image: 方舟武士2.png
life: 30
fadeOut: true
attachedToUnit: false

color: #63e6e8
fadeInTime: 0.1
scaleFrom: 1
scaleTo: 0.7
alpha: 1

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1

scaleTo: 0.5
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[movement]
movementType: LAND
moveSpeed: 1.7
moveAccelerationSpeed: 2
moveDecelerationSpeed: 2
maxTurnSpeed: 4

turnAcceleration: 0.5
moveSlidingMode: false
moveIgnoringBody: true


