


[core]
name: 中型空军传送门
displayText: Средний воздушный портал
class: CustomUnitMetadata
displayDescription: -Средний портал может телепортировать штурмовик «Злой дух», фрегат класса «Световой нимб», корабль класса «Арбитр»,\n-тяжёлый эсминец класса «Вспышка», крейсер класса «Анкараган». Каждый портал может телепортировать только одного юнита.\n-Любой телепортируемый юнит прибудет на поле боя в течение четырёх секунд.\n-Каждый портал поддерживается только 30 секунд, поспешите решить, кого телепортировать,\n-иначе портал закроется, не телепортировав никого. Порталы можно создавать только в поле телепортации.
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=30
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: -2,-1,2,2
constructionFootprint: -2,-1,2,2


[action_取消]
text: Отменить постройку
addResources: hp=-999999,cs=15
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_恶灵攻击机]
convertTo: 恶灵攻击机
displayType: action
text: Телепортировать штурмовик «Злой дух»
description: -В ранний период Империи Нова «Злой дух» был тяжёлым штурмовиком, специально созданным императором для Королевской гвардии.\n-Его размеры почти достигают предела, который может вынести лётная палуба корабля.\n-Размер «Злого духа» приближается к стандартному фрегату, и поэтому он обладает непревзойдённой грузоподъёмностью и тяжёлой огневой мощью.\n-По сравнению с уязвимыми палубными десантными капсулами, штурмовик «Злой дух» способен пройти даже сквозь самые плотные сети ПВО для доставки юнитов,\n-одновременно эффективно очищая зону высадки и обеспечивая мощную огневую поддержку десанту.\n-Единственный чертёж штурмовика «Злой дух» был обнаружен Скитальцами в обломках космической станции Таутени-4. Хотя у Зарева их тоже много,\n-«Злые духи» Зарева из-за отсутствия чертежей не могут обслуживаться и давно вышли из строя.\n-После уникальной модификации Скитальцами штурмовик «Злой дух» по сей день служит основным штурмовым транспортным самолётом.\n-Атакует землю и воздух, пулемёты — кинетический урон, остальное — энергетический.
price: 5600,awz=90

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='法雅德2')


[action_光轮级护卫舰]
convertTo: 光轮级护卫舰
displayType: action
text: Телепортировать фрегат класса «Световой нимб»
description: -В отличие от универсального имперского фрегата класса «Феникс», фрегат класса «Световой нимб» поставлялся только Королевской гвардии,\n-его передовая боевая эффективность поражает воображение — даже в боях, где разница в классах не имеет значения,\n-фрегат «Световой нимб» не уступает противнику. Такой мощный корабль давно был желанной добычей для семьи Фаяд.\n-Однако строгий, даже жёсткий запрет Империи Нова на оружие вынуждал семью Фаяд тайно копировать его в подполье.\n-После раскола Империи чертежи «Светового нимба» были утрачены вместе с Таутени,\n-а единственные оставшиеся «Световые нимбы» в руках Зарева были полностью уничтожены в боях. Если сегодня вы хотите вновь увидеть былую мощь «Светового нимба»,\n-многочисленные журналы уничтожения врагов в копиях «Светового нимба» Скитальцев расскажут вам о его прошлой храбрости.\n-Атакует землю и воздух, энергетический урон. Внимание: без технологий этот юнит даст вам -6 к доходу.
price: 6000

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='帝国科技解析2')


[action_仲裁者级航空母舰]
convertTo: 仲裁者级航空母舰
displayType: action
text: Телепортировать корабль класса «Арбитр»
description: -Класс «Арбитр» — основная часть флота Скитальцев. Использование «Арбитра» вызвано не превосходством, а вынужденной необходимостью.\n-После раскола Империи император не оставил людям ни военной промышленности, ни оружия,\n-поэтому, столкнувшись с могущественным королевским флотом Зарева, Скитальцы были вынуждены переоборудовать свои гражданские корабли для военных нужд.\n-Сняв грузовые отсеки с имперского разведывательного корабля класса «Судьба» и установив частицевые пушки и лётную палубу,\n-его можно было кое-как использовать как малый авианосец, хотя это оружие нельзя назвать особо мощным.\n-Даже его эффективность сомнительна, но при массовом применении он способен проявить на поле боя немалую силу.\n-Атакует землю и воздух, энергетический урон.\n-Внимание: без технологий этот юнит даст вам -9 к доходу.
price: 7000,awz=75

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='帝国科技解析2')


[action_耀斑级重型驱逐舰]
convertTo: 耀斑级重型驱逐舰
displayType: action
text: Телепортировать тяжёлый эсминец класса «Вспышка»
description: -Прототипом тяжёлого эсминца класса «Вспышка» послужил суперкорабль Республики Альфрид — дредноут класса «Бояс».\n-Хотя в своё время дредноут класса «Бояс» не имел равных, его крайне низкий выпуск и колоссальные потребности в обслуживании\n-вынудили учёных Альфрида разработать другой корабль на роль основного боевого корабля.\n-На базе класса «Бояс» был создан класс «Вспышка», или, точнее, «Вспышка» — это уменьшенная версия «Бояса».\n-«Вспышка» унаследовала большинство достоинств «Бояса», обладая при этом высочайшей надёжностью, что принесло ей известность.\n-Затем своей мощью она победила ряд конкурентов и прочно заняла трон основного боевого корабля Республики.\n-После раскола Империи остатки рода Бояс пытались возродить свой давно заброшенный трон — класс «Бояс» — для борьбы с Заревом.\n-Но в тяжёлых условиях того времени «Вспышка» вновь увидела свет,\n-и до сих пор класс «Вспышка» остаётся одним из немногих кораблей Скитальцев со способностью дальнего снайперского огня.\n-В обычном режиме атакует только воздух, энергетический урон. В режиме главного калибра — кинетический урон, атакует землю и воздух. Этот юнит даст вам -18 к доходу.
price: 12000,awz=250

buildSpeed: 4s
#isVisible: if self.globalTeamTags(includes='法雅德1')
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='帝国科技解析2')


[action_安卡拉刚级巡洋舰]
convertTo: 安卡拉刚级巡洋舰
displayType: action
text: Телепортировать крейсер класса «Анкараган»
description: -Крейсер класса «Анкараган» — образцовый звёздный корабль Древних Людей, который прошёл почти всю историю их космических сражений.\n-Анкараган начал службу ещё в середине второй великой эпохи мореплавания Древних Людей в составе флота Республики Буэнфендель, и до сих пор используется крупнейшими фракциями.\n-В ту эпоху, когда щиты и частицевое оружие ещё не были изобретены, Анкараган был символом абсолютной силы в космосе,\n-а также горделивым воздушным троном гегемонии Буэнфендель. Хотя сегодня Анкараган уже сильно устарел,\n-благодаря простой и грубой технологии, для отражения вторжения Зарева, Скитальцы переоснастили Анкараган частицевым оружием,\n-заменили реактор на более совершенный и перестроили всю электросеть корабля. Под руководством Скитальцев Анкараган переродился,\n-и сегодня крейсер класса «Анкараган» по-прежнему служит во флоте Скитальцев, продолжая славу и мощь былого Буэнфенделя.\n-Атакует землю и воздух, многоствольные пушки наносят кинетический урон, остальное — энергетический. Внимание: без технологий этот юнит даст вам -21 к доходу.
price: 16000,awz=300

buildSpeed: 4s
ai_isHighPriority: true
isVisible: if self.globalTeamTags(includes='帝国科技解析2')


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

#drawLayer:top
animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.8


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.2
scaleTo: 0.6
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.8
scaleFrom: 0.8
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.7
scaleFrom: 0.7
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.2

scaleTo: 0.9
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


