


[core]
name: 小型空军传送门
displayText: Малый воздушный портал
class: CustomUnitMetadata
displayDescription: -小型传送门可以传送胡蜂无人机，光翼战斗机，蝮蛇战斗机，萤火轰炸机\n-以及路西法，每个传送门仅能传送一个单位。\n-被传送的任何单位将在四秒之内到达战场。\n-每个传送门仅能维持30秒，请尽快决定要传送的单位，\n-否则传送门将在未传送任何单位的情况下关闭。且只能在传送场内产生传送门。
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=15
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1


[action_取消]
text: Отменить постройку
addResources: hp=-999999,cs=15
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_光翼战斗机]
convertTo: 光翼战斗机
displayType: action
text: Телепортировать истребитель «Световое крыло»
description: -光翼曾是亚尔佛里德标准战斗机，参与过所有亚尔佛里德的战争，\n-光翼战机凭借其先进的武器和新颖的可变翼，在诺瓦帝国之前是最先进的战机。\n-不过，因为和诺瓦帝国战斗的失利导致光翼战机被大量摧毁，帝国建国后，\n-光翼更是被全新的猎杀者战机击败，最终惨遭遗弃。\n-在之后与余辉艰苦卓绝的战斗中，伯亚斯家族为太空浪人再次复刻了这款战机。\n-至今仍是太空浪人空军中主力战机，值得一提的是，创世纪血翼战机是在他的基础上改造的。\n-对地对空。对空模式动能，对地模式能源
price: 2000

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_胡蜂无人机]
convertTo: 胡蜂无人机
displayType: action
text: Телепортировать дрон «Шершень»
description: -胡蜂无人机经常被太空浪人内部人员戏称为“长了翅膀的鱼雷”，\n-相比于普通的鱼雷来说，胡蜂无人机航程更远，威力更强，\n-其内置高度浓缩的等离子体，能在最高强度的装甲上钻出一个大洞，\n-运用偷袭战术时胡蜂无人机总是能予以敌人重创。\n-对地对空，自杀式袭击，能源伤害。
price: 800

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_萤火轰炸机]
convertTo: 萤火轰炸机
displayType: action
text: Телепортировать бомбардировщик «Светлячок»
description: -萤火轰炸机是太空浪人在极为艰苦的条件下诞生的，\n-其技术简单到创世纪都可以嘲笑，其更是采用原始的手段进行攻击。\n-在太空浪人撤离希诺星系的最后时刻，舰队已经几乎损失殆尽，\n-面对浩浩荡荡的帝国皇家舰队，萤火轰炸机成为了为数不多的反舰武器之一，\n-他们会对目标投掷下密密麻麻的无导等离子炸弹，而炸弹唯一的动力却只有惯性，\n-因为这种方法实在是效率过于底下，现如今萤火轰炸机通常执行对地轰炸任务，\n-并取得了丰硕的战果。\n-只能对地，反潜，能源伤害。
price: 1750

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_蝮蛇战斗机]
convertTo: 蝮蛇战斗机
displayType: action
text: Телепортировать истребитель «Гадюка»
description: -蝮蛇战斗机是法雅德家族专为与帝国余辉争夺制空权所研发的战斗机，\n-为了能应对余辉庞大且先进的战机连队，蝮蛇战机的一切都是按最高标准来设计的，\n-以便有效击落余辉的战机乃至战舰。\n-在一对一的较量中，没有任何一架余辉的战斗机是蝮蛇的对手，\n-哪怕是面对护卫舰都能有一战之力。但是当时太空浪人持有的工业体系早已支离破碎，\n-不巧的是，蝮蛇对制造工艺要求非常挑剔，最终只能少量制造部署于空间站等关键设施内。\n-蝮蛇战机至今仍是太空浪人最具威力的战斗机，同样也没有任何余辉战机是他的对手。\n-只能对空，主炮能源，机炮动能
price: 4500,awz=45

buildSpeed: 4s
isVisible: if self.globalTeamTags(includes='法雅德1')
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_路西法]
displayType: action
text: Телепортировать «Люцифер»
description: -古人类战国时期，路西法是科斯塔工业集团推出的一款多用途攻击机，\n-其设计是基于那些没有额外经费支出给海军发展的落后国家。\n-路西法在作为一款强力的攻击机的同时，还配有新颖的变形系统，\n-使其可以变形潜入水下作战，在一定程度上可以当做海军使用，\n-在当时，路西法是星系间最抢手的军火之一，几乎所有反对亚尔佛里德的国家都拥有路西法。\n-直至今日，路西法依旧在太空浪人的军队中服役，并为打击余辉做出了卓越贡献。\n-只能对地，空中能源伤害，水下模式动能伤害
price: 2900
buildSpeed: 4s

setBodyRotation: 0
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно
convertTo: 路西法


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.6


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.2
scaleTo: 0.45
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.55
scaleFrom: 0.55
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.5
scaleFrom: 0.5
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1

scaleTo: 0.75
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


