


[core]
name: 小型空军传送门
displayText: Малый воздушный портал
class: CustomUnitMetadata
displayDescription: -Малый портал может телепортировать дрон «Шершень», истребитель «Световое крыло», истребитель «Гадюка», бомбардировщик «Светлячок»\n-и «Люцифер». Каждый портал может телепортировать только одного юнита.\n-Любой телепортируемый юнит прибудет на поле боя в течение четырёх секунд.\n-Каждый портал поддерживается только 30 секунд, поспешите решить, кого телепортировать,\n-иначе портал закроется, не телепортировав никого. Порталы можно создавать только в поле телепортации.
radius: 17
showActionsWithMixedSelectionIfOtherUnitsHaveTag: csm

price: cs=15
maxHp: 1500
techLevel: 1
buildSpeed: 0.1s
isBio: false

isBuilding: true
numBitsOnDeath: 0
selfBuildRate: 100
hideScorchMark: true
fogOfWarSightRange: 0

tags: 地面,csm,建筑
footprint: -1,-1,1,1
constructionFootprint: -1,-1,1,1


[action_取消]
text: Отменить постройку
addResources: hp=-999999,cs=15
buildSpeed: 0s
ai_isDisabled: true
ai_isHighPriority: false


[placementRule_传送基站]
searchTags: 核
searchTeam: own
searchDistance: 300
# 这个改检测范围
excludeIncompleteBuildings: true

excludeNonBuildings: false
checkEachTile: false
minCount: 1
cannotPlaceMessage: 只能放置在传送点附近


[hiddenAction_1]
autoTrigger: true
fireTurretXAtGround: 1


[action_zh1]
autoTrigger: if self.timeAlive(laterThanSeconds=30)
isVisible: false
addResources: hp=-999999


[action_光翼战斗机]
convertTo: 光翼战斗机
displayType: action
text: Телепортировать истребитель «Световое крыло»
description: -«Световое крыло» был стандартным истребителем Альфрида и участвовал во всех войнах Альфрида.\n-Благодаря передовому оружию и новаторскому изменяемому крылу, до Империи Нова он был самым передовым истребителем.\n-Однако из-за поражения в боях с Империей Нова «Световое крыло» был массово уничтожен. После основания Империи\n-«Световое крыло» был побеждён новым истребителем «Охотник» и в итоге был забыт.\n-В последующих тяжёлых боях с Заревом семья Бояс воссоздала этот истребитель для Скитальцев.\n-По сей день он остаётся основным истребителем авиации Скитальцев, и стоит отметить, что истребитель «Кровавое крыло» Генезиса создан на его основе.\n-Атакует землю и воздух. В режиме ПВО — кинетический урон, в режиме атаки земли — энергетический.
price: 2000

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_胡蜂无人机]
convertTo: 胡蜂无人机
displayType: action
text: Телепортировать дрон «Шершень»
description: -Дрон «Шершень» среди Скитальцев в шутку называют «торпедой с крыльями».\n-По сравнению с обычной торпедой, дрон «Шершень» имеет большую дальность и мощь,\n-его встроенная высококонцентрированная плазма способна пробить дыру даже в самой прочной броне.\n-При тактике внезапного нападения дрон «Шершень» всегда наносит врагу серьёзный урон.\n-Атакует землю и воздух, самоубийственная атака, энергетический урон.
price: 800

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_萤火轰炸机]
convertTo: 萤火轰炸机
displayType: action
text: Телепортировать бомбардировщик «Светлячок»
description: -Бомбардировщик «Светлячок» был создан Скитальцами в крайне тяжёлых условиях.\n-Его технология настолько проста, что над ней мог бы посмеяться даже Генезис, и атакует он самыми примитивными методами.\n-В последний момент эвакуации Скитальцев из галактики Сино флот был почти полностью потерян.\n-Перед лицом грозного королевского флота Империи бомбардировщик «Светлячок» стал одним из немногих противокорабельных вооружений.\n-Они сбрасывают на цели плотный поток неуправляемых плазменных бомб, единственная сила которых — инерция.\n-Из-за крайне низкой эффективности этого метода сегодня «Светлячки» обычно выполняют задачи бомбардировки наземных целей\n-и достигают значительных результатов.\n-Атакует только землю и подводные цели, энергетический урон.
price: 1750

buildSpeed: 4s
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_蝮蛇战斗机]
convertTo: 蝮蛇战斗机
displayType: action
text: Телепортировать истребитель «Гадюка»
description: -Истребитель «Гадюка» был разработан семьёй Фаяд специально для борьбы с Заревом за господство в воздухе.\n-Чтобы противостоять огромным и передовым эскадрильям Зарева, всё в «Гадюке» было сделано по высшим стандартам,\n-чтобы эффективно сбивать истребители и даже корабли Зарева.\n-В поединке один на один ни один истребитель Зарева не может тягаться с «Гадюкой»,\n-даже против фрегата он способен сразиться. Но в то время промышленная база Скитальцев уже была раздроблена,\n-к тому же «Гадюка» очень требователен к производственным процессам, поэтому в итоге их выпускают в небольших количествах и размещают на ключевых объектах вроде космических станций.\n-Истребитель «Гадюка» по сей день остаётся самым мощным истребителем Скитальцев, и ни один истребитель Зарева не может ему противостоять.\n-Атакует только воздух, главное орудие — энергетический урон, авиапушка — кинетический.
price: 4500,awz=45

buildSpeed: 4s
isVisible: if self.globalTeamTags(includes='法雅德1')
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно


[action_路西法]
displayType: action
text: Телепортировать «Люцифер»
description: -В эпоху Воюющих государств Древних Людей «Люцифер» был многоцелевым штурмовиком, выпускавшимся промышленной группой Коста.\n-Его конструкция была разработана для отсталых стран без дополнительного бюджета на развитие флота.\n-«Люцифер» — это мощный штурмовик, оснащённый новаторской системой трансформации,\n-которая позволяет ему погружаться под воду для боя, до некоторой степени заменяя флот.\n-В то время «Люцифер» был одним из самых популярных вооружений в галактике; почти все страны, противостоявшие Альфриду, имели «Люциферов».\n-По сей день «Люцифер» служит в армии Скитальцев и внёс выдающийся вклад в борьбу с Заревом.\n-Атакует только землю, в воздухе — энергетический урон, в подводном режиме — кинетический урон.
price: 2900
buildSpeed: 4s

setBodyRotation: 0
ai_isHighPriority: true
isLocked: if not numberOfUnitsInTeam(withTag='核', greaterThan=0,withinRange=300)
isLockedMessage: Поле телепортации потеряно, использование невозможно
convertTo: 路西法


[graphics]
total_frames: 4
image: ROOT:/太空浪人/传送门/传送门2.png
image_back: ROOT:/太空浪人/传送门/收缩.png
image_wreak: NONE
image_turret: NONE

animation_idle_start: 0
animation_idle_end: 3
animation_idle_speed: 8
imageScale: 0.6


[turret_1]
x: 1.5
y: 2
canShoot: false
shoot_flame: CUSTOM:光柱,CUSTOM:光柱2,CUSTOM:光粒*3,CUSTOM:冲击波
projectile: 13


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0
frame: 1

explodeEffect: NONE


[effect_光粒]
priority: high
image: ROOT:/太空浪人/传送门/光粒.png
life: 260
fadeOut: true
attachedToUnit: false

color: #FFFFFF
fadeInTime: 4
scaleFrom: 0.2
scaleTo: 0.45
alpha: 0.4

drawUnderUnits: false
dirOffsetRandom: 0
xSpeedRelativeRandom: 0.5
ySpeedRelativeRandom: 0.6
xSpeedAbsoluteRandom: 0.3

ySpeedAbsoluteRandom: 0.3


[effect_光柱]
priority: critical
image: ROOT:/太空浪人/传送门/光柱.png
life: 60
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.55
scaleFrom: 0.55
alpha: 0.7
hSpeed: 1.5

drawUnderUnits: false
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.5


[effect_光柱2]
priority: high
image: ROOT:/太空浪人/传送门/光柱2.png
life: 40
fadeOut: true
attachedToUnit: false

fadeInTime: 0.8
scaleTo: 0.5
scaleFrom: 0.5
alpha: 0.7
hSpeed: 0.5

drawUnderUnits: true
atmospheric: false
spawnChance: 5
ySpeedAbsoluteRandom: 0.3


[effect_冲击波]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.1

scaleTo: 0.75
alpha: 0.6
drawUnderUnits: false
atmospheric: true


[attack]
canAttack: false
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 0

turretTurnSpeed: 50


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


[ai]
useAsAttacker: true
buildPriority: 0.35
maxEachBase: 2
maxGlobal: 5


