


[core]
name: 噩梦展开
displayText: «Кошмар» развёртывание
showInEditor: false
price: 3500
maxHp: 6000
displayDescription: 【Уровень t3】【Защита от тактического оружия】【Механический юнит】【Наземный юнит】Тактическое назначение:重 зенитная ракета，\n-размер юнита:6，вооружение：▲зенитная ракетапусковая трубаX4 только по воздуху взрывной урон \n-▲增程зенитная ракетапусковая трубаX4 только по высотным взрывной урон\n-面对余辉的空天боевой корабль，традиционный的зенитная ракетахотяможетэффективный击中，\n-нотрадиционныйракета的мощность在余辉的庞然大物面前宛如瘙痒，\n-于是，Военная Группа Генезисс爱国者зенитная ракета为原 进行改造，\n-为зенитная ракетаоснащение了足с炸毁боевой корабль的全氮阴离子盐弹头。\n-«Кошмар»зенитная ракета的появляется打破了余辉боевой корабль不败的神话。
transportSlotsNeeded:699
techLevel: 1
buildSpeed: 16s
radius: 48
displayRadius: 48
isBio: false
softCollisionOnAll:15
unitsSpawnedOnDeath: 损毁2*1
tags: 地面,反高空
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 27
energyMax: 4
energyRegen: 0.005
energyNeedsToRechargeToFull: true


[hiddenAction_打断]
autoTrigger:if self.hasParent
disconnectFromParent: true




#科技——————————


[action_聚变弹头2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变2.png
text: Термоядерная боеголовка2
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头2')


[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: Мина «Кошмар»1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3') 

[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: Мина «Кошмар»3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3') 




#休克————————————


[hiddenAction_↯a]
autoTrigger: if self.resource.xk>0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
isActive: false
highPriorityQueue: true

temporarilyRemoveTags: ↯
[action_b]
displayType: action
isLocked: if self.queueSize > 0.5 or self.resource.xk > 0 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)

price: 0
buildSpeed: 0s
isVisible: true
whenBuilding_cannotMove: true
text: 收起ракета 
alsoQueueAction: bx
description: 收起固定装置和垂直状态的ракета ，\n-使«Кошмар»зенитная ракетавходит移动模式。\n-收起主炮后将无法по воздуху对высотный进行攻击，\n-恢复移动способность，\n-а также对常规воздушный юнит的способность，\n-失去дальность增益，失去тактическое оружиеоборонаспособность。
iconImage: ROOT:/通用特效/收起主炮.png
resetCustomTimer: true
temporarilyAddTags: 切枪
playSoundAtUnit:ROOT:/通用特效/展开主炮.ogg
allowMultipleInQueue:false
playAnimation: 动画
[action_bx]
convertTo: 噩梦
displayType: action
price: 0
buildSpeed: 0.8s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove: true
allowMultipleInQueue:false
temporarilyRemoveTags: 切枪,反高空
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
[decal_履带]
image: 轮胎1.png
total_frames: 1
layer: afterBody
isVisible:true
onlyWhileAlive:true
xOffsetRelative:-0.5
[decal_履带1]
image: 轮胎.png
total_frames: 2
frame: (self.customTimer * 22) % 2
# 8为图片帧数，17改速度，1/17s下一帧
layer: afterBody
isVisible:false
onlyWhileAlive:true
xOffsetRelative:-0.5
[decal_炮塔1]
image: 贞1.png
total_frames: 8
frame: select(self.tags(includes= '切枪'), (self.customTimer * 8) % 8, 0)
# 8为图片帧数，17改速度，1/17s下一帧
layer:onTop
isVisible:if self.tags(includes= '切枪')
onlyWhileAlive:true
yOffsetRelative:-40
[graphics]
total_frames: 1
image: 车身.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 3
shadowOffsetY: 3
dustEffect: true
teamColorsOnTurret: true
showEnergyBar: false


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 8

turretTurnSpeed: 3
maxAttackRange: 700
shootDelay: 240
turretMultiTargeting: true





[turret_1]
x: -13
y: -56
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*5, CUSTOM:冲击波
shoot_light: #FFEECCCC
projectile: 1
size: 0
turnSpeed: 811
delay: 260
canOnlyAttackUnitsWithTags:高空
limitingMinRange: 300
energyUsage:1
canAttackCondition:if self.resource.xk<1 and not self.tags(includes= '切枪')
altProjectile: 2
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头2')

[turret_2]
x: -6
y: -64
copyFrom: 1
warmup: 60
#canAttackCondition:if self.Energy>2 and self.Energy<3.1
[turret_3]
x: 6
y: -64
#导弹左
copyFrom: 1
warmup: 120
#canAttackCondition:if self.Energy>1 and self.Energy<2.1

[turret_4]
x: 13
y: -56
#导弹左
copyFrom: 1
warmup: 180
#canAttackCondition:if self.Energy<1.1

[turret_5]
x: 0
y: -60
canShoot: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.55
shoot_light: #FFEECCCC
projectile: 3
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
delay:420
interceptProjectiles_withTags:战术武器
interceptProjectiles_andUnderDistance: 2000
interceptProjectiles_andOverHeight: -10
energyUsage: 2
size:0
invisible: true
shoot_flame: CUSTOM:烟雾*8, CUSTOM:冲击波
[turret_5x]
x: 0
y: -60
copyFrom: 5
interceptProjectiles_withTags: 天上战术
interceptProjectiles_andUnderDistance: 2000
interceptProjectiles_andOverHeight: -100
interceptProjectiles_andTargetingGroundUnderDistance:2000
#战术防御天上



[projectile_1]
life: 45
speed: 3
targetSpeed: 0
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:导弹碎片1


[projectile_锁定1]
@copyFromSection: template_爆炸
#主炮子弹
directDamage: 1400
life: 250
speed: 6
targetSpeed: 12
image: ROOT:/创世纪军事集团/单位特效/新大导弹1.png
drawSize: 0.87
trailEffect: true
deflectionPower: -1
trailEffectRate: 0.8
lightSize: 0.75
lightColor: #FFFFFF73
autoTargetingOnDeadTarget: true
explodeEffect:CUSTOM:爆炸,CUSTOM:冲击波z, CUSTOM:闪光, CUSTOM:钢珠
explodeEffectOnShield:CUSTOM:爆炸,CUSTOM:冲击波z, CUSTOM:闪光, CUSTOM:钢珠
[projectile_2]
life: 45
speed: 3
targetSpeed: 0
largeHitEffect: true
drawSize: 0.8
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
spawnProjectilesOnEndOfLife: 锁定2
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:导弹碎片1
[projectile_锁定2]
@copyFromSection: template_能源
#主炮子弹
areaDamage: 1950
areaRadius: 65
life: 250
speed: 6
targetSpeed: 12
image: ROOT:/创世纪军事集团/单位特效/新大导弹1.png
drawSize: 0.87
trailEffect: true
deflectionPower: -1
trailEffectRate: 0.8
lightSize: 0.75
lightColor: #FFFFFF73
autoTargetingOnDeadTarget: true
explodeEffect: CUSTOM:聚变,CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波x
explodeEffectOnShield: CUSTOM:聚变,CUSTOM:底色,CUSTOM:闪光x,CUSTOM:冲击波x
areaRadiusFromEdge: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_3]
areaDamage: 0
areaRadius: 0
life: 120
speed: 40
trailEffect:true
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
drawSize: 1
largeHitEffect: true
deflectionPower: -1
trailEffectRate: 0
explodeEffect: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:钢珠,CUSTOM:爆炸, CUSTOM:闪光
[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/大导弹碎片1.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/大导弹碎片.png
spawnChance: 1
life: 52
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false
xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10

[effect_闪光]
image: SHARED:light_50.png
life: 25
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false

atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.7
scaleTo: 1.7

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false

scaleFrom: 2
scaleTo: 2.7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0

animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_冲击波z]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 2
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.3
scaleTo: 1.4
alpha: 1
[effect_冲击波y]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波.png
life: 30
fadeOut: true
attachedToUnit: false

fadeInTime: 0.1
scaleFrom: 0.3
scaleTo: 0.7
alpha: 1.5
drawUnderUnits: true


[effect_光子]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.75
scaleTo: 0.75
alpha: 1.4

drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 2
ySpeedRelativeRandom: 2

[effect_底色]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.47
scaleTo: 0.47
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_闪光x]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false
atmospheric: false


[effect_冲击波x]
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 25
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_聚变]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 25
fadeOut: true
attachedToUnit: false

scaleFrom: 1.2
scaleTo: 1.2
alpha: 0.4
drawUnderUnits: false
atmospheric: false
#主武器——————————



[arm_1]
x: 8.5
y: -81
image_end: 支架.png
image_end_teamColors: true
drawUnderAllUnits: true
#drawDirOffset: 180
[arm_2]
x: -8.5
y: -81
image_end: 支架.png
image_end_teamColors: true
drawUnderAllUnits: true
#drawDirOffset: 180
[arm_3]
x: -31
y: -33
image_end: 支架.png
image_end_teamColors: true
drawUnderAllUnits: true
drawDirOffset: 90
[arm_4]
x: 31
y: -33
image_end: 支架.png
image_end_teamColors: true
drawUnderAllUnits: true
drawDirOffset: -90
[arm_5]
x: 0
y: -62
image_end: 导弹1.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.tags(includes= '切枪')
[arm_6]
x: -13
y: -56
image_end: 导弹头.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.Energy<3.1 or self.tags(includes= '切枪')
[arm_7]
x: -6
y: -64
image_end: 导弹头.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.Energy<2.1 or self.tags(includes= '切枪')
[arm_8]
x: 6
y: -64
image_end: 导弹头.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.Energy<1.7 or self.tags(includes= '切枪')
[arm_9]
x: 13
y: -56
image_end: 导弹头.png
image_end_teamColors: true
drawOverBody: true
hidden:if self.Energy<1.2 or self.tags(includes= '切枪')
[animation_动画]

arm1_0s: {x:0, y:0, dir:0}
arm2_0s: {x:0, y:0, dir:0}
arm3_0s: {x:0, y:0, dir:0}
arm4_0s: {x:0, y:0, dir:0}

arm1_0.8s: {x:0, y:17, dir:0}
arm2_0.8s: {x:0, y:17, dir:0}
arm3_0.8s: {x:17, y:0, dir:0}
arm4_0.8s: {x:-17, y:0, dir:0}
[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.03
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0
moveSlidingMode : false
moveIgnoringBody: false


