


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}
[action_拆除哇袄]
addResources: 威胁点数=-${core.price / 50}

[core]
name: AG等离子喷火塔t2
class: CustomUnitMetadata
price: 3300
maxHp: 2500
maxShield: 2500

shieldRegen: 0.07
#footprint used for collisions with units (left, up, right, down)
footprint: 0,0,1,1
#used for placement, and placement of other buildings
constructionFootprint: 0,0,1,1

copyFrom: ROOT:/通用特效/单位防护.ini
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 13
techLevel: 1
buildSpeed: 0.0008

armour: 12
#availableInDemo: true
tags: 地面,建筑,无人单位
radius: 25
#displayRadius: 25

buildingSelectionOffset: -8
isBuilding: true
isBio: false
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image_back: ROOT:/通用特效/NO.png
image: ROOT:/余辉军团/建筑特效/二级座.png
image_wreak: ROOT:/余辉军团/建筑特效/座死亡.png
image_turret: 塔.png

image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColorsOnTurret: true
scaleTurretImagesTo: 26

imageScale: 0.9


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 1

turretSize: 18
turretTurnSpeed: 3
maxAttackRange: 340


[turret_1]
x: 0
y: 23
canShoot: false
idleSweepAngle: 100
idleSweepDelay: 210

idleSweepSpeed: 0.2


[turret_3]
x: 6.5
y: 4
projectile: 1
shoot_sound: ROOT:/通用特效/火焰.ogg
shoot_sound_vol: 0.2

shoot_flame: CUSTOM:smoke
canShoot: true
invisible: true
attachedTo: 1
slave: true

canAttackCondition: if self.resource.xk < 1


[turret_2]
x: -6.5
y: 4
projectile: 1
shoot_sound: ROOT:/通用特效/火焰.ogg
shoot_sound_vol: 0.1

shoot_flame: CUSTOM:smoke
canShoot: true
invisible: true
attachedTo: 1
slave: true

canAttackCondition: if self.resource.xk < 1


[projectile_1]
life: 5000
speed: 6.5
areaDamage: 25
areaRadius: 70
targetSpeed: 7

image: 爆炸2.png
drawSize: 0.6
flameWeapon: true
areaRadiusFromEdge: true
targetGroundSpread: 25

targetGround: true
lightSize: 1
lightColor: #FF2A71DE
deflectionPower: -1
explodeEffect: CUSTOM:爆炸
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_smoke]
#priority:high
frameIndex: 0
stripIndex: smoke_black
spawnChance: 0.3
createWhenZoomedOut: false

life: 90
fadeOut: true
attachedToUnit: false
#color: #fdc14d
color: #FFFFFF

fadeInTime: 2
scaleFrom: 0.3
scaleTo: 1
alpha: 5
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.2
dirOffsetRandom: 180
xSpeedRelativeRandom: 0.4
ySpeedRelativeRandom: 0.4

atmospheric: true


[effect_爆炸]
priority: critical
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
life: 70
fadeOut: true
attachedToUnit: false

color: #FFFFFF
scaleFrom: 0.7
scaleTo: 0.85
alpha: 1
drawUnderUnits: false

ySpeedRelative: 2
atmospheric: true
total_frames: 14
animateFrameStart: 4
animateFrameEnd: 13

animateFrameSpeed: 0.2


[ai]
buildPriority: 0.22
noneInBaseExtraPriority: 0.17
maxEachBase: 3


[movement]
movementType: BUILDING
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1


