


[core]
name: HK徘徊者
displayText: HK Странник
displayDescription: -в Война Государств эпохи Древних Людей (период), потери морской пехоты всегда оставались высокими, \n-Империя Новасрочно требовался мех, защищающий пехоту и эффективно противостоящий бронетехнике, \n-Так появился этот мех с плазменной противотанковой батареей и другим оружием, \n-, Как универсал поля боя , Странникможет легко справляться с большинством ситуаций, \n-При необходимости этот мех может отбросить ракетную пусковую установку и провести героическую атаку, \n-Никакой подозреваемый не уйдёт от преследования этого эффективного и манёвренного охотника.\n-только по земле.клинок нейтральный и против укрытий, пулемёт энергетический, остальные энергетические.
class: CustomUnitMetadata
techLevel: 1
buildSpeed: 13s

maxShield: 800
shieldRegen: 0.05
radius: 18
displayRadius: 18
price: 1500
fogOfWarSightRange: ${int(attack.maxAttackRange/16)}
maxHp: 700
energyMax: 8
energyRegen: 0.05
energyNeedsToRechargeToFull: true
unitsSpawnedOnDeath: 损毁*1
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 地面,无人单位
armour: 3

[action_万岁冲锋]
convertTo: HK徘徊者冲锋模式
displayType: action
price: 0
text: Героическая атака
autoTrigger: if self.hp < self.maxHp * 0.36

buildSpeed: 1s
description: Отбросить ракетный модуль и пулемёт, разогнать и поджечь плазменный клинок, \n-и направить всю энергию на двигатель,, щит и клинок.\n-Процесс необратим,, автоматически активируется при HP < 36%.
addResourcesWithLogic: shield= max( ${core.maxShield * 0.36} - self.shield, 0 )
highPriorityQueue: true
whenBuilding_cannotMove: false

whenBuilding_playAnimation: 部署
spawnEffects: CUSTOM:弹壳*1
isLocked: if self.resource.xk > 0


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
image: HK徘徊者主体.png
image_wreak: HK徘徊者死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 12
isFixedFiring: true
maxAttackRange: 255
shootDelay: 30


[turret_2]
x: 14
y: -2
invisible: true
attachedTo: 1
idleDir: 0

slave: true
warmup: 0
projectile: 1
delay: 10
turnSpeed: 122

turnSpeedAcceleration: 5
shoot_sound: ROOT:/余辉军团/单位特效/突击炮音效.ogg
shoot_sound_vol: 0.2
shoot_light: #FF004AFF
canShoot: true

size: 14
recoilOffset: -1
canAttackCondition: if self.resource.xk < 1
energyUsage: 2


[turret_4]
x: 5
y: 6
invisible: true
attachedTo: 1
idleDir: 0

slave: true
warmup: 0
projectile: 3
delay: 5
turnSpeed: 122

turnSpeedAcceleration: 5
shoot_sound: ROOT:/余辉军团/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_light: #FF004AFF
canShoot: true

size: 14
canAttackCondition: if self.resource.xk < 1


[turret_1]
x: 0
y: 0
image: HK徘徊者主体.png
turnSpeed: 28
turnSpeedAcceleration: 0.3

canShoot: false


[turret_3]
x: 0
y: 0
invisible: true
delay: 110
projectile: 2

turnSpeed: 100
turnSpeedAcceleration: 0.07
shoot_sound: ROOT:/通用特效/光剑.ogg
onShoot_playAnimation: attack
shoot_flame: CUSTOM:刀光

canShoot: true
size: 1
attachedTo: 1
idleDir: 0
slave: true

limitingRange: 110
canAttackCondition: if self.resource.xk < 1


[arm_1]
x: -8
y: -18.5
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: false


[arm_5]
x: -13
y: -13
image_end: 左小.png
image_end_teamColors: true
drawOverBody: false


[arm_6]
x: 13
y: -13
image_end: 右小.png
image_end_teamColors: true
drawOverBody: false


[arm_2]
#刀
x: -23
y: -10
image_end: HK徘徊者刀.png
image_end_teamColors: true

drawOverBody: false
drawDirOffset: 20
moveSpeed: 6


[arm_3]
x: 8
y: -18.5
image_end: 右翼.png
image_end_teamColors: true
drawOverBody: false


[arm_4]
#左胳膊下
x: -13
y: 0
image_end: HK徘徊者胳膊.png
image_end_teamColors: true

drawOverBody: false
drawDirOffset: 45


[projectile_1]
@copyFromSection: template_能源
directDamage: 100
life: 270
image: ROOT:/余辉军团/单位特效/蓄能.png
drawSize: 0.9

speed: 5
targetSpeed: 8
explodeEffect: CUSTOM:波雷爆炸,CUSTOM:闪光
lightSize: 0.6
lightColor: #FF00B3FF

trailEffect: CUSTOM:尾巴


[projectile_2]
life: 2000
areaDamage: 200
areaRadius: 30
instant: true
speed: 10

targetSpeed: 10
explodeEffect: CUSTOM:sparks*10
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1



[projectile_3]
@copyFromSection: template_能源
directDamage: 4
life: 70
image: ROOT:/余辉军团/单位特效/光束2.png
drawSize: 0.4

speed: 6
targetSpeed: 6
explodeEffect: CUSTOM:火花


[effect_波雷爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 2
image: ROOT:/余辉军团/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg

alpha: 2


[animation_attack]
#onActions: attack
blendIn: 0.5s
blendOut: 0.5s
KeyframeTimeScale: 0.15
arm2_0s: {x:0, y:0, dir:0}

arm4_0s: {x:0, y:0, dir:0}
arm2_0.5s: {x:0, y:40, dir:0}
arm4_0.5s: {x:0, y:0, dir:300}
arm2_1s: {x:26, y:40, dir:150}
arm4_1s: {x:0, y:0, dir:300}

arm2_1.5s: {x:16,y:52, dir:-120}
arm4_1.5s: {x:0, y:0, dir:300}


[animation_部署]
blendIn: 0.5s
blendOut: 0.5s
arm1_0s: {x:0, y:0, dir:25}
arm5_0s: {x:0, y:0, dir:38}
arm6_0s: {x:0, y:0, dir:-25}

arm3_0s: {x:0, y:0, dir:-38}


[leg_1]
x: -9
y: -1.5
attach_x: -8
attach_y: -1
moveSpeed: 2.7

rotateSpeed: 7
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_leg: 腿.png

image_foot: 脚.png
drawDirOffset: -10
hidden: if self.hasParent()
#draw_foot_on_top: true
#dust_effect: false

holdDisMin: 28
holdDisMax: 42
hardLimit: 60


[leg_2]
x: 8
y: -1.5
attach_x: 8
attach_y: -1
copyFrom: 1

drawDirOffset: 10
hidden: if self.hasParent()


[effect_刀光]
life: 20
spawnChance: 1
priority: critical
attachedToUnit: false
scaleFrom: 0.5

scaleTo: 0.5
image: 刀光.png


[effect_sparks]
attachedToUnit: false
life: 60
scaleFrom: 0.3
scaleTo: 0.3
physics: true

xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.7


[effect_尾巴]
priority: veryhigh
image: ROOT:/余辉军团/单位特效/光束2.png
life: 20
fadeOut: true
attachedToUnit: false

color: #63e6e8
fadeInTime: 0.1
scaleFrom: 0.35
scaleTo: 0.35
alpha: 0.7

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 1.5
scaleTo: 1.5
drawUnderUnits: false

atmospheric: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2


[effect_弹壳]
priority: critical
image: 炮.png
spawnChance: 1
life: 240
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 1
scaleTo: 1
alpha: 2

fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
xSpeedRelative: 1.2
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -2

xOffsetRelative: 14
hSpeed: 2
dirSpeedRandom: 50


[movement]
movementType: LAND
moveSpeed: 1
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1
maxTurnSpeed: 2

turnAcceleration: 0.5
moveSlidingMode: false
moveIgnoringBody: true


