


[core]
name: HK徘徊者冲锋模式
displayText: HK Странник (атака)
displayDescription: -в Война Государств эпохи Древних Людей (период), потери морской пехоты всегда оставались высокими, \n-Империя Новасрочно требовался мех, защищающий пехоту и эффективно противостоящий бронетехнике, \n-Так появился этот мех с плазменной противотанковой батареей и другим оружием, \n-, Как универсал поля боя , Странникможет легко справляться с большинством ситуаций, \n-При необходимости этот мех может отбросить ракетную пусковую установку и провести героическую атаку, \n-Никакой подозреваемый не уйдёт от преследования этого эффективного и манёвренного охотника.\n-только по земле.
class: CustomUnitMetadata
techLevel: 1
buildSpeed: 13s
maxShield: 800
shieldRegen: 0.05
radius: 18
displayRadius: 18
fogOfWarSightRange: 15
price: 1500
maxHp: 700
armour: 5
unitsSpawnedOnDeath: 损毁*1
tags: 地面,射程x,无人单位

copyFrom: ROOT:/通用特效/单位防护.ini


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
image: HK徘徊者冲锋.png
image_wreak: HK徘徊者死亡.png
image_turret: NO.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
teamColorsOnTurret: true
movementEffect: CUSTOM:projectileTrail1,CUSTOM:projectileTrail2
movementEffectRate: 8


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 12
isFixedFiring: true
maxAttackRange: 55
shootDelay: 30
meleeEngangementDistance: 450

isMelee: true


[turret_1]
x: 0
y: 0
image: HK徘徊者冲锋.png
turnSpeed: 28
turnSpeedAcceleration: 0.3

canShoot: false


[turret_3]
x: 0
y: 0
invisible: true
delay: 90
projectile: 2

turnSpeed: 100
turnSpeedAcceleration: 0.07
shoot_sound: ROOT:/通用特效/光剑.ogg
onShoot_playAnimation: attack
shoot_flame: CUSTOM:刀光

canShoot: true
size: 1
attachedTo: 1
idleDir: 0
slave: true

canAttackCondition: if self.resource.xk < 1


[arm_1]
x: -8
y: -18.5
image_end: 左翼.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 25


[arm_5]
x: -13
y: -13
image_end: 左小.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: 38


[arm_6]
x: 13
y: -13
image_end: 右小.png
image_end_teamColors: true
drawOverBody: false

drawDirOffset: -38


[arm_2]
#刀
x: -23
y: -10
image_end: HK徘徊者刀2.png
image_end_teamColors: true

drawOverBody: false
drawDirOffset: 20
moveSpeed: 6


[arm_3]
x: 8
y: -18.5
image_end: 右翼.png
image_end_teamColors: true
drawDirOffset: -25

drawOverBody: false


[arm_4]
#左胳膊下
x: -13
y: 0
image_end: HK徘徊者胳膊.png
image_end_teamColors: true

drawOverBody: false
drawDirOffset: 45


[projectile_2]
life: 2000
areaDamage: 250
areaRadius: 30
instant: true
speed: 10

targetSpeed: 10
explodeEffect: CUSTOM:sparks*10 ,CUSTOM:闪光
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1


[animation_attack]
#onActions: attack
blendIn: 0.5s
blendOut: 0.5s
KeyframeTimeScale: 0.15
arm2_0s: {x:0, y:0, dir:0}

arm4_0s: {x:0, y:0, dir:0}
arm2_0.5s: {x:0, y:40, dir:0}
arm4_0.5s: {x:0, y:0, dir:300}
arm2_1s: {x:26, y:40, dir:150}
arm4_1s: {x:0, y:0, dir:300}

arm2_1.5s: {x:16,y:52, dir:-120}
arm4_1.5s: {x:0, y:0, dir:300}


[leg_1]
x: -9
y: -1.5
attach_x: -8
attach_y: -1
moveSpeed: 4

rotateSpeed: 10
heightSpeed: 3
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
hidden: if self.hasParent()

image_leg: 腿.png
image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false

holdDisMin: 28
holdDisMax: 42
hardLimit: 60


[leg_2]
x: 8
y: -1.5
attach_x: 8
attach_y: -1
copyFrom: 1

drawDirOffset: 10
hidden: if self.hasParent()


[effect_刀光]
life: 20
spawnChance: 1
priority: critical
attachedToUnit: false
scaleFrom: 0.5

scaleTo: 0.5
image: 刀光.png


[effect_sparks]
attachedToUnit: false
life: 60
scaleFrom: 0.3
scaleTo: 0.3
physics: true

xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 0.7


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 0.3
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2


[effect_projectileTrail1]
image: ROOT:/余辉军团/单位特效/蓄能.png
life: 30
fadeOut: true
attachedToUnit: false
color: #63e6e8

fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 1
alpha: 1.5
drawUnderUnits: true

xOffsetRelative	: 9
yOffsetRelative	: -5
atmospheric: true


[effect_projectileTrail2]
image: ROOT:/余辉军团/单位特效/蓄能.png
life: 30
fadeOut: true
attachedToUnit: false
color: #63e6e8

fadeInTime: 0.1
scaleFrom: 0.5
scaleTo: 1
alpha: 1.5
drawUnderUnits: true

xOffsetRelative	: -9
yOffsetRelative	: -5
atmospheric: true


[movement]
movementType: LAND
moveSpeed: 2
moveAccelerationSpeed: 2
moveDecelerationSpeed: 2
maxTurnSpeed: 4

turnAcceleration: 0.5
moveSlidingMode: false
moveIgnoringBody: true


