


[core]
name:猎空无人机
displayText: 猎空无人机
displayDescription: -?
class: CustomUnitMetadata
price: 0
maxHp: 2300
techLevel: 1
canNotBeGivenOrdersByPlayer: true
softCollisionOnAll: 200
radius: 12
explodeOnDeath: false
fogOfWarSightRange: 20
isBio: false
numBitsOnDeath:0
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
energyMax: 2000
energyRegen: -1
dieOnZeroEnergy: true
canOnlyBeAttackedByUnitsWithTags:反高空
tags: 飞机,寄生免疫,伴生单位,无人单位,反高空,高空
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_zz1]
autoTrigger:if not self.isInMap
addResources: hp= -999999

[action_ax]
autoTrigger: if self.timeAlive(laterThanSeconds=1)	and not self.tags(includes= '部署')
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
temporarilyAddTags: 部署
playAnimation: attack

[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE

shadowOffsetX: 1
shadowOffsetY: 1
splastEffect: false
movementEffect: CUSTOM:火
movementEffectRate: 0.5

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 1
turretMultiTargeting:false
turretTurnSpeed: 250
maxAttackRange: 150
isMelee: true
meleeEngangementDistance: 99999
dieOnAttack: true
[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir: 0
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: true
shoot_sound: NONE
shoot_sound_vol: 0.3
projectile: 1
size: 1.1
turnSpeed: 999
canOnlyAttackUnitsWithTags:高空
canOnlyAttackUnitsWithoutTags:伴生单位
[turret_2]
x: 0
y: 0
copyFrom: 1
projectile: 2
canOnlyAttackUnitsWithTags:低空
canOnlyAttackUnitsWithoutTags:伴生单位
[projectile_1]
@copyFromSection: template_能源
life: 250
speed: 6
targetSpeed: 10
areaDamage: 4600
areaRadius: 85
drawSize: 1
explodeEffect: CUSTOM:等离子平铺爆炸实验,CUSTOM:等离子平铺爆炸闪光,CUSTOM:等离子平铺爆炸聚变,CUSTOM:等离子平铺爆炸冲击波,CUSTOM:等离子平铺爆炸冲击波1,CUSTOM:等离子平铺爆炸光球1,CUSTOM:等离子平铺爆炸光球
explodeEffectOnShield:CUSTOM:等离子平铺爆炸实验,CUSTOM:等离子平铺爆炸闪光,CUSTOM:等离子平铺爆炸聚变,CUSTOM:等离子平铺爆炸冲击波,CUSTOM:等离子平铺爆炸冲击波1,CUSTOM:等离子平铺爆炸光球1,CUSTOM:等离子平铺爆炸光球
deflectionPower: -1
areaRadiusFromEdge: true
image: 主体.png
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
autoTargetingOnDeadTarget: true
autoTargetingOnDeadTargetRange:150
[projectile_2]
@copyFromSection:projectile_1
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[arm_1]
x: -5
y: 0
image_end: 左.png
drawOverBody: true
image_end_shadow: SHADOW:左.png
drawDirOffset: 50
[arm_2]
x: 5
y: 0
image_end: 右.png
drawOverBody: true
image_end_shadow: SHADOW:右.png
drawDirOffset: -50
[arm_3]
x: 0
y: 0
image_end: 机体.png
drawOverBody: true
image_end_shadow: SHADOW:机体.png


[animation_attack]

arm1_0s: {x:0, y:0,dir:0}
arm1_0.4s: {x:-3, y:0,dir:-50}
arm1_9500s:{x:-3, y:0,dir:-50}
arm2_0s: {x:0, y:0,dir:0}
arm2_0.4s: {x:3, y:0,dir:50}
arm2_9500s:{x:3, y:0,dir:50}
[effect_火]
life: 17
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FF00B3FF
xOffsetRelative	: 0
ySpeedRelative: -1
yOffsetRelative	: -14
drawUnderUnits: true

[movement]
movementType: AIR
moveSpeed: 5.3
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.004
joinsGroupFormations: false
maxTurnSpeed: 4.5
turnAcceleration: 1
moveSlidingMode : false
moveIgnoringBody: false
targetHeight: 140
slowDeathFall: false


