


[core]
name: 魔像
displayText: Голем
displayDescription: -Протёкший из-за разрушения Заревом ториевый реактор, земля, заражённая вирусом «Серая Тень» Скитальцев,\n-и невезучий зомби-гигант породили этого чудовищного монстра — Голема.\n-Из-за радиоактивного заражения и нестабильности вируса «Серая Тень» биологическая структура Голема крайне искажена,\n-его масса возросла в десять раз по сравнению с исходной, а множество редкоземельных веществ в коже и теле образовали непробиваемую стену.\n-По результатам испытаний Генезиса, Голем легко выдерживает прямое попадание из 125-мм и даже 280-мм пушки.\n-«Эта тварь слишком жёсткая», — так Генезис написал в отчёте об эксперименте для Скитальцев.\n-Поэтому Голем стал образцом и был запущен Скитальцами в массовое производство.\n-Атакует только землю. Нейтральный урон, пробивает укрытия, биологический юнит.
class: CustomUnitMetadata
price: hy=1500
maxHp: 15000

mass: 8000
techLevel: 1
buildSpeed: 18s
radius: 44
isBio: true
isUnrepairableUnit:true
transportSlotsNeeded: 3
armour: 25
copyFrom: ROOT:/通用特效/单位防护.ini
shieldRegen: 0.05
tags: 步兵,地面,寄生免疫

effectOnDeath: CUSTOM:飘血*9,CUSTOM:飘血2*8,CUSTOM:飘血3
explodeOnDeath: false
hideScorchMark: true


[action_灰影寄生虫科技提示1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/灰影寄生虫.png
text: Паразит «Серая Тень» 1
isActive: false
isVisible: if self.globalTeamTags(includes='寄生虫1')


[hiddenAction_DPS]
alsoQueueAction: DPS1


[hiddenAction_DPS1]
buildSpeed: 0.5s
fireTurretXAtGround: 伤害
whenBuilding_cannotMove: true
fireTurretXAtGround_withOffset: 0, 65
#size: 1

#attachedTo:1
#slave:true


[graphics]
total_frames: 1
image: NO.png
image_wreak: 死亡.png
#image_turret: null.png
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
#imageScale: 1
teamColorsOnTurret: true
#drawLayer:ground2


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 35

turretTurnSpeed: 1
maxAttackRange: 55
isFixedFiring: true
isMelee: true


[turret_1]
invisible: true
x: 0
y: 0
size: 14
idleDir: 0

turnSpeed: 9.0
turnSpeedAcceleration: 0.08
canShoot: false
#shouldResetTurret: false


[turret_2]
x: 0
y: 0
invisible: true
delay: 80
projectile: 2

turnSpeed: 100
turnSpeedAcceleration: 70
onShoot_playAnimation: attack
canShoot: true
size: 1

onShoot_triggerActions: DPS
attachedTo: 1
slave: true


[turret_伤害]
invisible: true
x: 0
attachedTo: 1
slave: true
y: 0

size: 0
turnSpeed: 4
turnSpeedAcceleration: 4
canShoot: false
projectile: 1

altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='寄生虫1')


[turret_0]
x: 0
y: -5
turnSpeed: 0
turnSpeedAcceleration: 1
canShoot: false

attachedTo: 1
invisible: true
slave: true


[arm_1]
x: 0
y: 0
image_end: 主体.png
image_end_teamColors: true
drawOverBody: true

image_end_shadow: SHADOW:主体.png


[leg_1]
x: -18
y: 20
attach_x: -10
attach_y: 4
moveSpeed: 2.7

rotateSpeed: 5
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
image_foot_shadow: SHADOW:左手.png

image_leg: 左.png
image_foot: 左手.png
drawDirOffset: -10
#draw_foot_on_top: true
#dust_effect: false

holdDisMin: 15
holdDisMax: 35
hardLimit: 27
dust_effect: true


[leg_2]
x: 18
y: 20
attach_x: 10
attach_y: 4
copyFrom: 1

drawDirOffset: 10
image_leg: 右.png
image_foot: 右手.png
image_foot_shadow: SHADOW:右手.png


[leg_3]
x: -22
y: -25
attach_x: -10
attach_y: -7
moveSpeed: 2.7

rotateSpeed: 5
heightSpeed: 1
estimatingPositionMultiplier: 1.2
favourOppositeSideNeighbours: true
dust_effect: true

image_foot_shadow: SHADOW:脚.png
image_leg: 腿.png
image_foot: 脚.png
drawDirOffset: -10
#draw_foot_on_top: true

#dust_effect: false
holdDisMin: 15
holdDisMax: 35
hardLimit: 40


[leg_4]
x: 22
y: -25
attach_x: 10
attach_y: -7
copyFrom: 3

drawDirOffset: 10


[projectile_2]
directDamage: 0
life: 2
instant: true
explodeEffect: NONE


[projectile_1]
life: 5000
areaDamage: 800
areaRadius: 95
instant: true
speed: 10

targetSpeed: 10
explodeEffect: CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:冲击波1,CUSTOM:烟雾,CUSTOM:钢珠
areaRadiusFromEdge: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_炮弹]
life: 5000
areaDamage: 900
areaRadius: 95
instant: true
speed: 10
tags: 灰影寄生虫
targetSpeed: 10
explodeEffect: CUSTOM:冲击波,CUSTOM:弹坑,CUSTOM:冲击波1,CUSTOM:烟雾,CUSTOM:钢珠
areaRadiusFromEdge: true
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: JSC=0.001
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[effect_飘血]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/小肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 1.3
scaleTo: 1.3
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.2
ySpeedRelativeRandom: 1.2

hSpeed: 1


[effect_飘血2]
life: 300
priority: low
image: ROOT:/创世纪军事集团/步兵特效/中肉块.png
spawnChance: 1
attachedToUnit: false

color: #FFFFFF
scaleFrom: 1
scaleTo: 1
drawUnderUnits: true
liveAfterAttachedDies: true

physics: true
physicsGravity: 1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.8
ySpeedRelativeRandom: 1.8

hSpeed: 1
dirSpeedRandom: 50


[effect_飘血3]
priority: high
image: ROOT:/创世纪军事集团/步兵特效/飘血.png
spawnChance: 1
life: 600
fadeOut: true

attachedToUnit: false
scaleFrom: 3
scaleTo: 6
alpha: 1.2
fadeInTime: 3

drawUnderUnits: false
liveAfterAttachedDies: false
total_frames: 11
animateFrameStart: 0
animateFrameEnd: 10

animateFramePingPong: false
animateFrameSpeed: 0.34
createWhenZoomedOut: false
alsoPlaySound: ROOT:/创世纪军事集团/步兵特效/死亡2.ogg


[effect_冲击波]
stripIndex: shockwave
life: 40
scaleFrom: 0.3
scaleTo: 3
#color: #FFF0AFA5

alpha: 1


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1
scaleTo: 1
createWhenOverLiquid: false
createWhenOverLand: true


[effect_烟雾]
priority: veryhigh
image: ROOT:/通用特效/烟雾.png
frameIndex: 0
createWhenOverLiquid: false
createWhenOverLand: true

life: 240
fadeOut: true
attachedToUnit: false
#color: #6D5448
fadeInTime: 5

scaleFrom: 0.2
scaleTo: 0.27
alpha: 1.25
drawUnderUnits: false
hSpeed: 0.2

hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24

xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_冲击波1]
life: 130
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 1.4

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_钢珠]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 2
alsoPlaySound: 地震.ogg
scaleTo: 3
image: ROOT:/创世纪军事集团/单位特效/钢珠.png

total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3

alpha: 1.2


[animation_attack]
#onActions: attack
leg1_0s: {x:0, y:0, dir:0}
leg2_0s: {x:0, y:0, dir:0}
arm1_0s: {x:0, y:0, dir:0}
leg1_0.5s: {x:0, y:0,height:7 }

leg2_0.5s: {x:0, y:0,height:7}
arm1_0.5s: {x:0, y:0,height:4}


[movement]
movementType: OVER_CLIFF
moveSpeed: 0.95
moveAccelerationSpeed: 1
moveDecelerationSpeed: 1
maxTurnSpeed: 1.6

turnAcceleration: 0.1
targetHeight: 3
moveSlidingMode: false
moveIgnoringBody: true


