


[core]
name: 巨兽坦克
displayDescription: -【阶级t3】【机械单位】【地面单位】【重型掩体】战术定位:重型突击炮，\n-单位体积:6 武器配置：▲400毫米主炮X1 只能对地。动能伤害 \n-在艰苦的战争条件下，创世纪被迫生产技术简单粗暴的作战单位。\n-于是，原型为二战时坦克歼击车的巨兽坦克便因此应运而生。\n-巨兽坦克装备了400毫米战列舰主炮，和极为厚重的传统装甲。\n-其厚重的传统装甲和反应装甲相堆叠，连反坦克导弹都难以击穿。\n-巨兽坦克可以轻易粉碎任何敢于挡路的傻瓜。
transportSlotsNeeded:6
price: 5500
maxHp: 13000
techLevel: 1
buildSpeed: 21s
radius: 45
isBio: false
tags: 地面,重型掩体,驻扎要塞

armour: 50
unitsSpawnedOnDeath: 损毁3*1
softCollisionOnAll: 20
copyFrom: ROOT:/通用特效/单位防护.ini
fogOfWarSightRange: 21


[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免部分速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。

#————————科技


[action_聚变弹头2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变2.png
text: 聚变弹头2
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头2')




#————————休克


[hiddenAction_↯a]
autoTrigger: if self.resource.xk>0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
isActive: false
highPriorityQueue: true

temporarilyRemoveTags: ↯


[hiddenAction_掩体1取消]
autoTrigger:if self.hasParent and self.tags(includes= '重型掩体')
isVisible:false
temporarilyRemoveTags:重型掩体
[hiddenAction_掩体1生成]
autoTrigger:if not self.hasParent and not self.tags(includes= '重型掩体')
isVisible:false
temporarilyAddTags:重型掩体



[graphics]
total_frames: 3
image: 巨兽坦克.png
image_wreak: 巨兽坦克死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 3
shadowOffsetY: 3
animation_moving_start: 0
animation_moving_end: 2
animation_moving_speed: 2.85

movementEffect: CUSTOM:烟1,CUSTOM:烟2
movementEffectRate: 20
showQueueBar: false
showTransportBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 28

turretTurnSpeed: 4
isFixedFiring: true
maxAttackRange: 385
shootDelay: 280
aimOffsetSpread: -0.01



#———————炮塔


[turret_1]
#主炮
x: 0
y: 40
projectile: 1
shoot_sound: ROOT:/创世纪军事集团/单位特效/突击炮音效.ogg

shoot_sound_vol: 0.6
shoot_flame: CUSTOM:烟雾*5,CUSTOM:枪口火焰
shoot_light: #FFEEEEEE
canShoot: true
image: 炮管.png

recoilOffset: -10
recoilOutTime: 12
recoilReturnTime: 30
attachedTo: 2
slave: true
canAttackFlyingUnits: false
canAttackCondition: if self.resource.xk<1
altProjectile: 2
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头2')


[turret_2]
#绑定
x: 0
y: 15
canShoot: false
invisible: true
canAttackFlyingUnits: false

[projectile_1]
@copyFromSection: template_动能
#普通炮弹
areaDamage: 2200
areaRadius: 50
life: 5000

speed: 7.5
color: #FFFFFF73
lightSize: 1.5
frame: 9
lightColor: #FFFFFF73

drawSize: 0.7
targetSpeed: 8
areaRadiusFromEdge: true
explodeEffect: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑
explodeEffectOnShield: CUSTOM:爆炸,CUSTOM:钢珠,CUSTOM:闪光,CUSTOM:冲击波,CUSTOM:弹坑


[projectile_2]
@copyFromSection: template_能源
areaDamage: 3600
areaRadius: 75
life: 5000
speed: 7.5

lightSize: 1.5
lightColor: #FFFFFF73
drawSize: 0.9
targetSpeed: 8
deflectionPower: -1

image: ROOT:/创世纪军事集团/单位特效/核弹.png
explodeEffect: CUSTOM:底色,CUSTOM:聚变,CUSTOM:闪光1,CUSTOM:冲击波1
explodeEffectOnShield: CUSTOM:底色,CUSTOM:聚变,CUSTOM:闪光1,CUSTOM:冲击波1
buildingDamageMultiplier: 1.2
areaRadiusFromEdge: true

#主炮开火特效————————


[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.9

scaleTo: 2.4
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.5
xSpeedRelativeRandom: 0.5
yOffsetRelative: 0.7
ySpeedRelative: 1

atmospheric: true


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 5
scaleTo: 5

#主炮爆炸特效———————————


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 3

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false

atmospheric: false


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false

scaleFrom: 1.7
scaleTo: 2.2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0

animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1
image: ROOT:/通用特效/冲击波.png

total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18

alwayStartDirAtZero: true
drawUnderUnits: true


[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true

scaleFrom: 1.2
scaleTo: 1.2
createWhenOverLiquid: false
createWhenOverLand: true
#科技主炮爆炸特效——————


[effect_底色]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 0.52
scaleTo: 0.52
alpha: 1.3
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_聚变]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 42
fadeOut: true
attachedToUnit: false

scaleFrom: 1.2
scaleTo: 1.2
alpha: 0.5
drawUnderUnits: false
atmospheric: false


[effect_闪光1]
image: SHARED:light_50.png
life: 40
fadeOut: true
alpha: 2
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false

atmospheric: false


[effect_冲击波1]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.05
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
atmospheric: false

#履带特效—————————


[effect_烟1]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative	: 24
yOffsetRelative	: -50


[effect_烟2]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative	: -24
yOffsetRelative	: -50


[arm_1]
x: 0
y: 15
image_end: 遮盖.png
image_end_teamColors: true
drawOverBody: true

hidden: if self.hp<self.maxHp * 0.36


[arm_2]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

hidden: if self.maxHp * 0.36 < self.hp


[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0.9

turnAcceleration: 0.05
moveSlidingMode : false
moveIgnoringBody: false


