


[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=154


[core]
name: SDN亡魂
displayText: SDNПризрак
class: CustomUnitMetadata
price: 5000,蓝晶=320
maxHp: 4000
maxShield: 4000

shieldRenderRadius: 43
shieldRegen: 0.07
shieldDisplayOnlyDeflection: true
displayDescription: -Аравелидпоздний период, войнауже основаштзавязатьпучок, Империя Новаобладать надеждойклятвагалактика большой частьвестиземля, \n-но это Аравелид плаватьбитьотрядпо-прежнемув нестиупорносопротивление, , а Призрактогдаэто они самыйединицаэравнешний оружиесреди .\n-Призракштэто Аравелид модель глубокиймореразведкакорабль, шттелопереноситьимеет сначалавразведкаустановкарезерв и малый  типнанозавод, \n-этотразведкакорабльразумместоКогда так плаватьбитьотрядпереоборудованныйстать военный корабль, и даватьбойпозади  чистыйразумработаделатьполосаприходит не малый  проблема.\n-послеэтотвоенный корабль чертёжИмперия Новаубратьзахватить, но однако толькоделатьдля ресурсматериалзащитахранение, нетимеет большой количествопроизводство.\n-прямойк Зарево и созиданиеэпохаэраоткрытьбой, Заревовынужденныйрезатьнужнотип не превышатьуровень, а мощный ВМФ, \n-к это , Призракв проходитьопытнесколько эпохаэра тонутьспатьпозади снова разпробуждение.\n-то естьиспользоватьв Заревоглазвнутри этотне это модель собрать оружие, но  и созиданиеэпохаэраВМФв данный моментсравнительноколичествотакже это очень богатыйимеет остаток.\n-по земле и воздуху, может производствосамоубийство типнет человекмашина, пулемётможет источникпротив укрытий, нет человекмашинаможет источникпротив укрытий, его остатоквзрыв.\n-Тип проекта:Аравелид черепицаЛанисследованиеучреждениеданные
techLevel: 1

buildSpeed: 22s
availableInDemo: true
radius: 70
fogOfWarSightRange: 25
displayRadius: 70

isBio: false
softCollisionOnAll: 7
armour: 10
tags: 地面,海上,无人单位
effectOnDeath: CUSTOM:爆炸5*1,CUSTOM:冲击波2,CUSTOM:水波1

copyFrom: ROOT:/通用特效/单位防护.ini
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[action_反物质1]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/反1.png
text: Антиматериальное оружие 1
isActive: false
isVisible: if self.globalTeamTags(includes='反物质1')


[action_重子兵器2]
displayType: infoOnlyNoBox
iconImage: ROOT:/余辉军团/单位特效/重2.png
text: барионное оружие 2
isActive: false
isVisible: if self.globalTeamTags(includes='重子2')


[action_1_曲线跳跃]
fireTurretXAtGround: 曲线
text: Кривой прыжок
isVisible: if self.globalTeamTags(includes='曲线核1')
iconImage: ROOT:/余辉军团/单位特效/曲线核1.png
displayType: action

buildSpeed: 0s
pos: 0.1
#displayRemainingStockpile: true
highPriorityQueue: true
canPlayerCancel: false

onlyOneUnitAtATime: false
description: Активирует кривое ядро, совершая короткий мгновенный прыжок,\n-юнит мгновенно перемещается в указанную точку.
addActionCooldownTime: 15s
isLocked: if self.resource.xk > 0
[turret_曲线]
x: 0
y: 0
canShoot: false
idleDir: 0
invisible: true

size: 1.1
turnSpeed: 40
shoot_sound: NONE
shoot_sound_vol: 0.6
projectile: 炮弹3

limitingRange: 300

[action_2_护盾]
autoTrigger: if self.globalTeamTags(includes='护盾充能')
buildSpeed: 0s
addResources: shield=10
displayType: infoOnlyNoBox
text: Позитронное ядро

price: 0
isVisible: if self.globalTeamTags(includes='护盾充能')
isActive: false
iconImage: ROOT:/余辉军团/单位特效/护盾充能.png


[action_s1]
autoTrigger: if not self.isOverwater()
isVisible: false
addResources: hp=-999999


[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=570, incompleteBuildings= true) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=570, incompleteBuildings= true)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36



[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 身体.png
image_wreak: 死亡.png
image_turret: 主炮.png
#scaleTurretImagesTo: 14

image_shield: 护盾.png
#imageScale:0.8
image_shadow: AUTO
shadowOffsetX: 4
shadowOffsetY: 4

splastEffect: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shootDelay: 125

maxAttackRange: 530
turretMultiTargeting: true
turretSize: 10
turretTurnSpeed: 2


[turret_1]
x: 0
y: 65
shoot_flame: NONE
shoot_light: #FF00B3FF
shoot_sound: ROOT:/余辉军团/单位特效/大炮音效.ogg

shoot_sound_vol: 0.3
image: 主炮.png
canAttackCondition: if self.resource.xk < 1
canShoot: false

limitingRange: 450
recoilOffset: -1
limitingAngle: 130
canAttackFlyingUnits: false


[turret_2]
x: 0
y: 0
attachedTo: 1
slave: true
invisible: true
canAttackFlyingUnits: false
projectile: 1
size: 10
canAttackCondition: if self.resource.xk < 1
limitingRange: 450
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='反物质1')

[turret_3]
x: 0
y: 0
copyFrom: 2

[turret_4]
x: 0
y: 0
copyFrom: 2

[turret_5]
x: 0
y: 0
copyFrom: 2

[turret_6]
x: 0
y: 0
copyFrom: 2

[turret_7]
x: 0
y: 0
copyFrom: 2

[turret_8]
invisible: true
x: 20
y: 0
idleDir: 0
projectile: 5

size: 1
turnSpeed: 10
delay: 700
canAttackFlyingUnits: false
canAttackNotTouchingWaterUnits: false


[turret_9]
x: -20
y: 0
copyFrom: 8

[turret_10]
x: 0
y: -9
invisible: true
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*2
shoot_light: #FFEECCCC
projectile: 2
size: 0
turnSpeed: 811
warmup: 40
turnSpeedAcceleration: 10
delay: 200
canAttackFlyingUnits: false
limitingMinRange: 170
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹2
altProjectileCondition: if self.globalTeamTags(includes='重子2')

[turret_11]
x: 0
y: 12
image: 管.png
attachedTo: 12
slave: true
shoot_sound: ROOT:/余辉军团/单位特效/激光枪音效.ogg
shoot_sound_vol: 0.3
shoot_flame: NONE
shoot_light: #FFccCCEE
projectile: 4
limitingAngle: 130
delay: 5
recoilOffset: -1
size: 4
limitingRange: 330
canAttackCondition: if self.resource.xk < 1


[turret_12]
x: -31
y: -41
canShoot: false
image: 枪.png
idleDir: -45
delay: 180
limitingAngle: 130
limitingRange: 330
canAttackCondition: if self.resource.xk < 1

[turret_13]
x: 0
y: 12
copyFrom: 11
attachedTo: 14
slave: true

[turret_14]
x: 31
y: -41
idleDir: 45
copyFrom: 12


[projectile_5]
directDamage: 0
life: 2
speed: 0.01
drawSize: 0
color: #1E1E96

explodeOnEndOfLife: true
spawnUnit: SDN幽魂*1
deflectionPower: -1
explodeEffect: NONE


[projectile_4]
@copyFromSection: template_能源
directDamage: 50
life: 70
image: ROOT:/余辉军团/单位特效/双枪.png
drawSize: 0.5

speed: 9
targetSpeed: 9
explodeEffect: CUSTOM:火花
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 155
areaRadius: 35
life: 60
lightSize: 1

largeHitEffect: true
speed: 7
targetGroundSpread: 20
image: ROOT:/余辉军团/单位特效/炮弹.png
drawSize: 0.55

targetGround: true
explodeEffect: CUSTOM:大爆炸,CUSTOM:闪光*1
areaRadiusFromEdge: true


[projectile_2]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85

image: ROOT:/余辉军团/单位特效/鱼雷.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定*6
lightSize: 1
lightColor: #FF00B3FF


[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 225
areaRadius: 50
life: 200
speed: 7

image: ROOT:/余辉军团/单位特效/星星.png
targetSpeed: 14
drawSize: 0.45
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光

targetGroundSpread: 65
targetGround: true
areaRadiusFromEdge: true
lightSize: 0.75
lightColor: #FF00B3FF
[projectile_炮弹1]
@copyFromSection: template_能源
areaDamage: 175
areaRadius: 50
targetGroundSpread: 35
targetGround: true

life: 300
lightSize: 1
largeHitEffect: true
speed: 8
areaRadiusFromEdge: true
trailEffect: CUSTOM:尾巴
drawSize: 0.8
explodeEffectOnShield: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:底色
explodeEffect: CUSTOM:爆炸b,CUSTOM:闪光b,CUSTOM:底色
image: ROOT:/余辉军团/单位特效/中子弹1.png
trailEffectRate: 0.66


[projectile_炮弹2]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85

image: ROOT:/余辉军团/单位特效/鱼雷.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定1*2
lightSize: 1
lightColor: #FF00B3FF


[projectile_锁定1]
@copyFromSection: template_爆炸
areaDamage: 750
areaRadius: 65
life: 200
speed: 7

areaHitAirAndLandAtSameTime: true
image: ROOT:/余辉军团/单位特效/星星2.png
targetSpeed: 14
drawSize: 0.55
explodeEffectOnShield: CUSTOM:底色a,CUSTOM:闪光d,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:聚变

explodeEffect: CUSTOM:底色a,CUSTOM:闪光d,CUSTOM:冲击波a,CUSTOM:粒子a*3,CUSTOM:聚变
targetGroundSpread: 65
targetGround: true
areaRadiusFromEdge: true
lightSize: 0.75

lightColor: #FF00B3FF


[projectile_炮弹3]
life: 600
directDamage: 0
speed: 70
targetSpeed: 70
drawSize: 0

frame: 1
targetGroundSpread: 8
targetGround: true
deflectionPower: -1
explodeEffect: CUSTOM:闪光c,CUSTOM:冲击波c

teleportSource: true


[effect_大爆炸]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸]
image: ROOT:/余辉军团/单位特效/爆炸25.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.7

scaleTo: 1.4
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_烟雾]
#priority:high
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 60
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.25
scaleTo: 1.25
alpha: 0.65
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.2
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.5
atmospheric: true


[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.6

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true


[effect_爆炸5]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.2

image: ROOT:/余辉军团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/爆炸.ogg
alwayStartDirAtZero: true


[effect_火花]
life: 12
dirOffsetRandom: 180
priority: high
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 1.3
scaleTo: 0.4
image: ROOT:/余辉军团/单位特效/蓄能.png
alpha: 1.2
#————————————————


[effect_闪光b]
priority: critical
image: SHARED:light_50.png
life: 150
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFE56BFF
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5

drawUnderUnits: false
atmospheric: false


[effect_爆炸b]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 1
scaleTo: 1.35
image: ROOT:/余辉军团/单位特效/自制2.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.25
alpha: 1.2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg


[effect_尾巴]
#priority:veryhigh
image: ROOT:/余辉军团/单位特效/粗子弹2.png
life: 30
fadeOut: true
attachedToUnit: false

#color: #63e6e8
fadeInTime: 0.1
scaleFrom: 0.1
scaleTo: 0.1
alpha: 0.5

drawUnderUnits: false
yOffsetRelative	: -5
atmospheric: true


[effect_底色]
priority: critical
image: ROOT:/余辉军团/单位特效/收缩1.png
life: 35
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 0.2
alpha: 1
drawUnderUnits: false
atmospheric: false


[effect_底色a]
priority: critical
image: ROOT:/余辉军团/单位特效/黑洞1.png
life: 120
fadeOut: true
attachedToUnit: false

scaleFrom: 0.33
scaleTo: 0.33
alpha: 1.3
drawUnderUnits: false
atmospheric: false


[effect_闪光d]
image: SHARED:light_50.png
life: 120
fadeOut: true
alpha: 2
attachedToUnit: false

color: #FF00B3FF
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: true

atmospheric: false


[effect_粒子a]
life: 45
image: ROOT:/余辉军团/单位特效/光粒.png
scaleFrom: 0.1
scaleTo: 3
alpha: 1

dirOffsetRandom: 100
dirSpeed: -2
dirSpeedRandom: 1.5
drawUnderUnits: true


[effect_冲击波a]
priority: critical
image: ROOT:/余辉军团/单位特效/冲击波3.png
life: 100
fadeOut: true
attachedToUnit: false

scaleFrom: 0.1
scaleTo: 3
alpha: 0.8
drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/余辉军团/单位特效/光束.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1
scaleTo: 1
alpha: 0.6
drawUnderUnits: false
atmospheric: false

alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg


[effect_冲击波c]
image: ROOT:/太空浪人/传送门/冲击波.png
life: 100
fadeOut: true
attachedToUnit: false
scaleFrom: 0.3

scaleTo: 0.8
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[effect_闪光c]
image: SHARED:light_50.png
life: 50
fadeOut: true
alpha: 1
attachedToUnit: false

color: #FF39FFFF
fadeInTime: 2
scaleFrom: 6
scaleTo: 6
drawUnderUnits: false

atmospheric: false




[arm_3]
x: 0
y: -9
image_end: 井.png
image_end_teamColors: true
drawUnderAllUnits: true


[arm_1]
x: 0
y: -5
image_end: 盖1.png
image_end_teamColors: true


[arm_2]
x: 0
y: -13
image_end: 盖2.png
image_end_teamColors: true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:25}
arm1_950s: {x:0, y:25}
arm2_1s: {x:0, y:-25}

arm2_950s: {x:0, y:-25}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm1_1s: {x:0, y:0}
arm2_1s: {x:0, y:0}


[movement]
movementType: WATER
moveSpeed: 1.2
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.06
maxTurnSpeed: 1.2

turnAcceleration: 2
#moveSlidingMode :false
#moveIgnoringBody:false
#moveSlidingDir:  45


