


[core]
name: 长吻鳄级攻击潜艇
displayText: Атакующая подлодка класса «Длинноносый Кайман»
price: 3500
maxHp: 3000
displayDescription: 【Уровень t3】【Механический юнит】【Подводный юнит】\n-Тактическое назначение:тактическое оружиеатакаподводная лодка，вооружение：\n-▲противокорабельная торпедаX2 только по надводным и подводным юнитам взрывной урон \n-▲тактикаракетаВПУX1 только по земле взрывной урон тактическое оружие\n-Атакующая подлодка класса «Длинноносый Кайман»является海域 隐форма猎杀者，\n-онможетвпочтинеиздаватьлюбой声响 в случаезапускатьснаряд道ракетаиторпеда，\n-тем самымлёгкийалёгкий举 будет海поверхностькорабль埋葬в深海егов。
techLevel: 1
buildSpeed: 15s
radius: 68
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
tags: 潜艇,长吻鳄,海上,寄生免疫
showOnMinimapToEnemies: false
unitsSpawnedOnDeath: 中型水上单位死亡*1
[action_无损]
text: усиливаетструктура
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/无损.png
isLockedMessage: указанныйюнитне будетпотому что生命уменьшаета变в качествевойна损состояние
[action_弹幕架2]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕2.png
text: Реактивная установка2
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架2')
[action_导弹]
displayType: infoOnlyNoBox
iconImage:logo.png
text: уже включенотактикаракетапусковая установка
isActive: false
isVisible:if self.globalTeamTags(includes='弹道导弹技术1')

[action_导弹1]
displayType: infoOnlyNoBox
iconImage:logo.png
text: не включенотактикаракетапусковая установка
isActive: false
isVisible:if not self.globalTeamTags(includes='弹道导弹技术1')
[action_0_上浮]
price: 0
text: всплытие
buildSpeed: 2.5s
convertTo: 长吻鳄级攻击潜艇上浮
displayType: action

description: всплытиепослеподводная лодкабудетполучитьвыше скорость ходаиболеедалеко дальностьсчитать野
highPriorityQueue: true
convertTo_keepCurrentFields:maxHp,moveSpeed
convertTo_keepCurrentTags:true
temporarilyRemoveTags:潜艇,↯
iconImage: ROOT:/通用特效/上浮.png
isLocked:if self.queueSize > 0.5  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isLockedMessage: другиедействиявыполнятьв，пожалуйста, подождите
spawnEffects: CUSTOM:水波xx, CUSTOM:水波xx1*3, CUSTOM:水波xx2,CUSTOM:水雾xx*13
setResourcesWithLogic: xk=0

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
total_frames: 1
image: 潜艇.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 2
shadowOffsetY: 2
imageScale:0.85

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: true

turretSize: 20
turretTurnSpeed: 1.5
maxAttackRange: 800
shootDelay: 180
turretMultiTargeting: true

[turret_1]
x:0
y: -27
invisible: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false

shoot_sound: ROOT:/创世纪军事集团/单位特效/大导弹.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:水雾y*3,CUSTOM:冲击波t
shoot_light: #FFEECCCC
projectile: 1
size: 0
turnSpeed: 811
delay:12s
limitingMinRange: 365
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹道导弹技术1') 

[turret_2]
x: -8
y: 73
canShoot: true
invisible: true
projectile: 2
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFEECCCC
canAttackFlyingUnits: false
size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='弹幕架2')
canAttackMaxAngle: 181
limitingRange: 365
delay:180
canOnlyAttackUnitsWithoutTags:悬浮
[turret_3]
x: 8
y: 73
copyFrom: 2
delay:120
warmup:60


[turret_炮台1]
x: -8
y: 73
canShoot: true
invisible: true
projectile: 炮弹2

shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.5
shoot_flame: NONE
shoot_light: #FFEECCCC
canAttackFlyingUnits: false

size: 15
canAttackMaxAngle: 181
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
limitingRange: 365
turnSpeed: 0
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹幕架2')
canOnlyAttackUnitsWithoutTags:悬浮
[turret_炮塔2]
x: 8
y: 73
copyFrom: 炮台1
warmup: 7
delay:173
[turret_炮塔3]
x: -8
y: 73
copyFrom: 炮台1
warmup: 14
delay:166
[turret_炮塔4]
x: 8
y: 73
copyFrom: 炮台1
warmup: 21
delay:159
[projectile_炮弹2]
@copyFromSection: template_爆炸
areaDamage: 400
areaRadius: 40
areaRadiusFromEdge: true
life: 800
speed: 2
targetSpeed: 4
image: 鱼雷1.png
drawSize: 0.7
trailEffect: true
largeHitEffect: true
explodeEffect: CUSTOM:冲击波2,CUSTOM:闪光,CUSTOM:水波1
explodeEffectOnShield: CUSTOM:冲击波2,CUSTOM:闪光,CUSTOM:水波1
turnSpeed: 3
lightColor: #FFEEEE00
lightSize: 0

[projectile_1]
life: 80
speed: 2
targetSpeed: -1
largeHitEffect: true
drawSize: 0.9
image: 战术导弹.png
directDamage: 0
ballistic: true
ballistic_height: 260
ballistic_delaymove_height: 210
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片,CUSTOM:冲击波t,CUSTOM:闪光mx,CUSTOM:音效
trailEffect: true
trailEffectRate: 1.2
deflectionPower: -1
[projectile_锁定1]
@copyFromSection: template_爆炸
areaDamage: 4500
life: 1000
areaRadius: 100
alwaysVisibleInFog: true
nukeWeapon: true
speed: 0
image:导弹头.png
targetSpeed: 9
drawSize:0.9
lightSize: 0.9
lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸m,CUSTOM:气浪m,CUSTOM:冲击波m,CUSTOM:闪光m*2,CUSTOM:弹坑m
targetGroundSpread: 60
disableLeadTargeting: true
trailEffect: CUSTOM:projectileTrail
trailEffectRate: 1.2
areaRadiusFromEdge: true
targetGround: true
ballistic: true
ballistic_height: 260
deflectionPower: -1
ballistic_delaymove_height: 210
tags:战术武器
shouldRevealFog: true


[projectile_2]
@copyFromSection: template_爆炸
areaDamage: 500
areaRadius: 40
areaRadiusFromEdge: true
life: 800
speed: 2
targetSpeed: 4
image: 鱼雷1.png
drawSize: 0.8
largeHitEffect: true
deflectionPower: -1
explodeEffect: CUSTOM:冲击波2,CUSTOM:闪光,CUSTOM:水波1,CUSTOM:水雾y*3
explodeEffectOnShield: CUSTOM:冲击波2,CUSTOM:闪光,CUSTOM:水波1,CUSTOM:水雾y*3
turnSpeed: 2
lightColor: #FFEEEE00
lightSize: 0
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴


[effect_烟雾4]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10

scaleFrom: 1
scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
atmospheric: true


[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
createWhenOverLiquid: true
createWhenOverLand: false
drawUnderUnits: true


[effect_水波1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 3
scaleTo: 4.5

image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg

[effect_闪光]
priority: low
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4.2
scaleTo: 0
drawUnderUnits: false
atmospheric: false


[effect_尾巴]
image: SHARED:light_50.png
life: 38
fadeOut: true
attachedToUnit: false
priority: high
color:#FF0092FF
fadeInTime: 2
scaleFrom: 0.28
scaleTo: 0.15
alpha: 0.8
drawUnderUnits: true
yOffsetRelative:-10

[effect_水雾y]
stripIndex: effects
frameIndex: 0
life: 150
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 2.5
scaleTo: 4
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.25
ySpeedRelativeRandom: 0.25
xSpeedAbsoluteRandom: 0.25
ySpeedAbsoluteRandom: 0.25
createWhenOverLiquid: true
createWhenOverLand: false
xOffsetRelativeRandom:5
yOffsetRelativeRandom:5

#——................._————————战术导弹
[effect_冲击波t]
stripIndex: shockwave
life: 33
scaleFrom: 0.6
scaleTo: 3.5
alpha: 0.9
fadeOut: true
attachedToUnit: false
fadeInTime: 2
[effect_导弹碎片]
#priority: low
image: 导弹碎片.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 0.9
scaleTo: 0.9
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 50
[effect_音效]
image:NO.png
life: 0
alpha: 0
attachedToUnit: false
scaleFrom: 0
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
alsoPlaySound:nuke_launch
[effect_闪光mx]
image: SHARED:light_50.png
life:30
fadeOut: true
alpha: 1
attachedToUnit: false
color:#FFFF5B18
fadeInTime: 2
scaleFrom: 5.5
scaleTo: 5.5
drawUnderUnits: false
atmospheric: false
#战术飞弹————————
[effect_弹坑m]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true

[effect_气浪m]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 3
scaleTo: 7.6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true

[effect_闪光m]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo: 5
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true

[effect_冲击波m]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 3.5
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true
[effect_爆炸m]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2.5
scaleTo: 4.8
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true
[effect_projectileTrail]
stripIndex: effects
frameIndex: 0
life: 120
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 5
scaleFrom: 0.5
scaleTo: 3.5
alpha: 0.8
drawUnderUnits: false
#ySpeedRelative:-1
atmospheric: true
dirOffsetRandom: 180
shadow: true
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
#战术飞弹————————
[effect_水波xx]
drawType: displacement
image: SHARED:ripple_normal_128.png
life: 90
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1.6
scaleTo: 5
alpha: 0.1
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 1
delayedStartTimer: 5
[effect_水波xx1]
image: SHARED:ripple.png
life: 90
lifeRandom: 20
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1.5
scaleTo: 5
alpha: 0.7
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5
delayedStartTimer: 5
[effect_水波xx2]
image: SHARED:ripple.png
life: 60
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 2
scaleTo: 5
alpha: 0.7
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5
delayedStartTimer: 5
[effect_水雾xx]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 3.5
scaleTo: 5
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false
xOffsetRelativeRandom:60
yOffsetRelativeRandom:120
delayedStartTimerRandom:30
[arm_1]
x: 0
y: -21.5
image_end: 盖子.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.isAttacking()
[movement]
movementType: WATER
moveSpeed: 0.85
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.07
#moveSlidingMode :false

#moveIgnoringBody:false
#moveSlidingDir:  45
targetHeight: -8
targetHeightDrift: 0.3
maxTurnSpeed: 1.2

turnAcceleration: 0.1


