


[core]
name: 践踏
strictLevel: 1
price: 0
radius: 10
maxHp: 1

class: CustomUnitMetadata
techLevel: 1
showInEditor: false
tags: 눈_눈
canNotBeDirectlyAttacked: true

isUnrepairableUnit: true
disableAllUnitCollisions: true
ignoreInUnitCapCalculation: true
disableDeathOnZeroHp: true


[graphics]
total_frames: 8
image: NO.png
showQueueBar: false
showTransportBar: false
# lock_body_rotation_with_main_turret: true

# lock_leg_rotation_with_main_turret: true
animation_attack_start: 0
animation_attack_end: 7
animation_attack_speed: 3.5
animation_idle_start: 0

animation_idle_end: 7
animation_idle_speed: 3.5
showEnergyBar: false


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 9999

# 这个炮塔最好主体的最大范围多200
disablePassiveTargeting: true
isFixedFiring: true
turretSize: 24
turretTurnSpeed: 200

shootDelay: 0.9
aimOffsetSpread: 0


[turret_2]
x: 0
y: 0
delay: 1
projectile: 1
turnSpeedAcceleration: 5000

size: 6
invisible: true


[projectile_1]
areaDamage: 80
areaRadius: 135
armourIgnoreAmount: 40
speed: 0.1
life: 0
image: NO.png
instant: false
largeHitEffect: false
explodeOnEndOfLife: true
deflectionPower: -1
explodeEffect: NONE
explodeEffectOnShield: NONE
areaDamageNoFalloff: true
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[movement]
movementType: AIR
moveSpeed: 0
maxTurnSpeed: 180
targetHeight: 0
targetHeightDrift: 0

turnAcceleration: 233
moveIgnoringBody: true


