
[hiddenAction_寄生b]
addResources: bj= ${bjxq}

[core]
name: 黑寡妇
displayDescription: 【阶级t4】【机械单位】【地面单位】【极端重型单位】【长距离索敌】【可翻越悬崖】\n-【无人机指挥单位】战术定位:重型功能型攻击机甲，无法被运输，免疫休克，\n-武器配置：▲重型粉碎机X1 只能对地 中性伤害 反掩体 造成休克效果 \n-▲温迪戈无人机发射舱X4 对地对空 爆炸伤害 \n-▲长距离索敌导弹X4 只能攻击地面被锁定的敌方单位 爆炸伤害 \n-▲防空导弹垂发X10 对地对空 爆炸伤害 对非极端重型单位伤害加成。\n-以创世纪落后且老旧的科学技术为基础创造的奇迹。\n-黑寡妇是一座无懈可击的钢铁堡垒，巨大的身躯不仅搭载了各种战术设备，\n-还内置了一个功能全面的无人机工厂和数目庞大的无人机连队。\n-不过他最令人印象深刻的是前端那庞大的液压粉碎机，\n-黑寡妇真正的威力在于能以极高的航速向敌人的阵线发起猛冲，\n-其庞大的身躯和液压粉碎机可以将余辉的花哨玩具粉碎成扭曲的金属零件，\n-命令黑寡妇去追赶余辉的地面部队，看着他们在惊恐之中被压成废铁，\n-是时候让他们见识一下什么才是真正的钢铁巨兽了。
class: CustomUnitMetadata
price: 25000,钍=500,bj= ${bjxq}
@global bjxq:27
reclaimPrice: bj= ${bjxq}
maxHp: 63500
selfRegenRate: 1
armour: 195
techLevel: 1
buildSpeed: 90s
radius: 85
displayRadius: 85
fogOfWarSightRange: 43

isBio: false
softCollisionOnAll: 80
transportSlotsNeeded: 200
energyNeedsToRechargeToFull: true
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/扎针1.md

energyMax: 20
energyRegen: 0.008
unitsSpawnedOnDeath: 损毁3*1
tags: 地面,极端重型,暴君,射程x,免疫烟雾
[action_聚变弹头3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变3.png
text: 聚变弹头3
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头3')
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[action_清空能量]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
isVisible: false
addResources: energy=-9999
[action_坦克]
text: 建造幼蛛
displayType: action
buildSpeed: 0s
pos: 0.8
displayRemainingStockpile: false
highPriorityQueue: true
price:1500
canPlayerCancel: false
onlyOneUnitAtATime: false
whenBuilding_cannotMove: true
allowMultipleInQueue:false
descriptionAddFromUnit: 幼蛛
descriptionAddUnitStats: 幼蛛
isVisible: true
temporarilyAddTags: 布雷
alwaysSinglePress:false
playAnimation: 布雷
alsoQueueAction: 坦克1
iconImage: ROOT:/通用特效/机甲.png
playSoundAtUnit:ROOT:/通用特效/展开主炮.ogg
isLocked: if self.queueSize > 0.5 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)
[action_坦克1]
displayType: action
price: 0
buildSpeed: 5s
isVisible: false
highPriorityQueue: true
whenBuilding_cannotMove:true
temporarilyRemoveTags: 布雷
allowMultipleInQueue:false
spawnUnits:幼蛛(spawnSource= self.getOffsetRelative(x= 0, y= 100,dirOffset=180))



[decal_炮塔]
image: 滚筒.png
total_frames: 4
frame: (self.customTimer * 28) % 4
# 8为图片帧数，17改速度，1/17s下一帧
isVisible:true
onlyWhileAlive:true
layer: afterBody
yOffsetRelative:126
xOffsetRelative:0

[action_重]
text: 极端重型单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox

buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重.png
isLockedMessage: 体积夸张的单位独有的特性，\n-拥有极端重型单位标签的单位将拥有如下属性，\n-拥有自愈能力，且自身护甲不低于100点，\n-无法被休克，但是受到反重甲单位伤害增益。
[action_长距离]
text: 长距离索敌
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/长距离.png
description: 该单位有能力射击极远距离上的被锁定单位。\n-黑寡妇在攻击 地面单位 中的 被锁定 敌方单位时，\n-可以使用两侧射程为2000的巡航导弹挂架进行打击。

[action_1_烟幕弹]
fireTurretXAtGround: 烟幕弹
text: 发射烟幕弹
displayType: action
buildSpeed: 1s
pos: 0.1

displayRemainingStockpile: true
highPriorityQueue: true
price: energy=2
canPlayerCancel: false
onlyOneUnitAtATime: true

description: 向目标区域投掷一枚烟幕弹，烟幕弹能严重干扰敌军的瞄准系统。\n-烟雾弹将降低附近160范围内的敌方地面单位的射程以及射速，\n-对具有长距离索敌能力以及拥有先进目标定位核心科技的单位无效。
iconImage: ROOT:/创世纪军事集团/单位特效/烟雾弹.png
whenBuilding_triggerAction: 烟雾弹动画
isLocked: if self.queueSize > 0.5 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)


[hiddenAction_烟雾弹动画]
playAnimation: 1
#debugMessage: 烟雾弹


[action_1_布雷火箭]
fireTurretXAtGround: 布雷火箭
text: 发射布雷火箭
displayType: action
buildSpeed: 1s
pos: 0.1

displayRemainingStockpile: true
highPriorityQueue: true
price: energy=3
canPlayerCancel: false
onlyOneUnitAtATime: true

description: 布雷火箭能释放大量的恐怖地雷，\n-能够有效封锁地区不过射程很近。反掩体
whenBuilding_triggerAction: 布雷弹动画
iconImage: 布雷弹.png
isLocked: if self.queueSize > 0.5 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)


[hiddenAction_布雷弹动画]
playAnimation: 2
#debugMessage: 烟雾弹



[action_1_温压弹]
fireTurretXAtGround:温压弹
text: 发射空气燃料炸弹
displayType: action
buildSpeed: 1s
pos: 0.1

displayRemainingStockpile: true
highPriorityQueue: true
price: energy=8
canPlayerCancel: false
onlyOneUnitAtATime: true
iconImage: ROOT:/创世纪军事集团/单位特效/温压弹.png
description: 发射一枚空气燃料炸弹攻击敌方地面单位，\n-对范围150内的敌方地面单位造成5000点无衰减aoe爆炸伤害。\n-对建筑，生物单位伤害加成，对极端重型单位效果差，\n-对无护盾单位施加燃烧效果，反掩体。\n-这种武器将被判定为战术武器。
isVisible: true
whenBuilding_triggerAction: 烟雾弹动画
isLocked: if self.queueSize > 0.5 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or not self.globalTeamTags(includes='温压弹1')
isLockedMessage: 你需要空气燃料炸弹1才能发射，或其他动作进行中，请等待，或单位被干扰
[action_1_emp]
fireTurretXAtGround:emp
text: 发射电磁脉冲炸弹
displayType: action
buildSpeed: 1s
pos: 0.1
displayRemainingStockpile: true
highPriorityQueue: true
price: energy=6
canPlayerCancel: false
onlyOneUnitAtATime: true
iconImage: ROOT:/创世纪军事集团/单位特效/电磁1.png
description: 发射一枚电磁脉冲炸弹攻击敌方地面单位，\n-对范围300内的敌方地面单位造成1000点中性无衰减aoe伤害。\n-同时将对范围内所有单位施加休克效果，\n-极端重型单位为3.5秒，普通单位为7秒。\n-同时范围内的敌方所有常规护盾都将被摧毁。\n-反掩体，且这种武器将被判定为战术武器。
isVisible:true
whenBuilding_triggerAction: 布雷弹动画
isLocked: if self.queueSize > 0.5 or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415) or not self.globalTeamTags(includes='电磁脉冲武器1')
isLockedMessage: 你需要电磁脉冲武器1才能发射，或其他动作进行中，请等待，或单位被干扰
[attachment_1]
x: 0
y: 0
onCreateSpawnUnitOf: 践踏
lockRotation: false
prioritizeParentsMainTarget: true

resetRotationWhenNotAttacking: true
alwaysAllowedToAttackParentsMainTarget: true


[attachment_2]
x: 0
y: 0
onCreateSpawnUnitOf: 导弹炮台
lockRotation: false
prioritizeParentsMainTarget: true

resetRotationWhenNotAttacking: true
alwaysAllowedToAttackParentsMainTarget: true




[graphics]
total_frames: 1
image: 盖.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO

shadowOffsetX: 7
shadowOffsetY: 7

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 1
maxAttackRange: 53
shootDelay: 1
#turretRotateWithBody: true
isFixedFiring: true

isMelee: true
#turretMultiTargeting: true


[turret_1]
x: 0
y: 0
canShoot: false
#image:主体.png


[turret_2]
x: 0
y: 0
invisible: true
delay: 1
projectile: 1

turnSpeed: 100
turnSpeedAcceleration: 0.07
shoot_sound: ROOT:/创世纪军事集团/单位特效/电锯.ogg
shoot_flame: CUSTOM:火花*2,CUSTOM:火花1,CUSTOM:闪光
canShoot: true

size: 128
attachedTo: 1
slave: true


[turret_烟幕弹]
x: -33.5
y: -50
canShoot: false
invisible: true
size: 1.1

turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 2
delay: 0

shoot_flame: CUSTOM:烟雾*7
shoot_light: #FFEECCCC
limitingRange: 500
attachedTo: 1
slave: true
[turret_温压弹]
x: -33.5
y: -50
#导弹中
copyFrom: 烟幕弹
warmup: 20
projectile: 温压弹
limitingRange: 900
[turret_emp]
x: -33.5
y: -50
#导弹中
copyFrom: 烟幕弹
warmup: 20
projectile: emp
limitingRange: 900
[turret_布雷火箭]
x: 33.5
y: -50
canShoot: false
invisible: true
size: 1.1

turnSpeed: 40
shoot_sound: ROOT:/创世纪军事集团/单位特效/烟雾弹射击.ogg
shoot_sound_vol: 0.6
projectile: 3
delay: 0

shoot_flame: CUSTOM:烟雾*7
shoot_light: #FFEECCCC
limitingRange: 300
attachedTo: 1
slave: true


[projectile_1]
life: 5000
areaDamageNoFalloff: true
areaDamage: 130
areaRadius: 70
instant: true

speed: 10
targetSpeed: 10
explodeEffect: NONE
areaRadiusFromEdge: true
mutator1_ifUnitWithoutTags: jabzhdja

mutator1_addResourcesDirectHit: xk= 1
armourIgnoreAmount: 1000
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_2]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.9

image: 导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1


[projectile_锁定]
life: 600
directDamage: 0
speed: 4
targetSpeed: 8
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png

drawSize: 0.9
targetGround: true
spawnUnit: 烟幕弹*1
trailEffect: true
deflectionPower: -1


[projectile_3]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.9

image: 导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 80

ballistic_delaymove_height: 300
spawnProjectilesOnEndOfLife: 锁定1*12
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1

[projectile_温压弹]
life: 600
speed: 4
targetSpeed: 10
largeHitEffect: true
drawSize: 0.9

image: 温压弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
explodeOnEndOfLife: true
explodeEffect: CUSTOM:烟雾wy*19
spawnUnit:通用战略武器(addResources=温压弹:1)
tags:战术武器
trailEffectRate: 0.6
[projectile_emp]
life: 600
speed: 4
targetSpeed: 10
largeHitEffect: true
drawSize: 0.9
image:电磁弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
explodeOnEndOfLife: true
explodeEffect: NONE
spawnUnit:通用战略武器(addResources=电磁:1)
tags:战术武器
trailEffectRate: 0.6
[projectile_锁定1]
life: 600
directDamage: 0
speed: 4
targetSpeed: 8
image: ROOT:/创世纪军事集团/单位特效/烟幕弹.png

drawSize: 0.9
spawnUnit: 恐怖地雷升级
explodeEffect: CUSTOM:烟雾*2
trailEffect: true
deflectionPower: -1

targetGroundSpread: 145
targetGround: true


[effect_火花]
attachedToUnit: false
life: 60
scaleFrom: 0.35
scaleTo: 0.35
physics: true

xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2
image: 光束.png
alpha: 0.85
xOffsetRelativeRandom:40
yOffsetRelativeRandom:10

[effect_火花1]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.2
scaleTo: 0.4
image: ROOT:/创世纪军事集团/单位特效/大火花.png
total_frames: 12

animateFrameStart: 0
animateFrameEnd: 11
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.85
xOffsetRelativeRandom:15
yOffsetRelativeRandom:5
physics: true
xSpeedRelativeRandom: 3
ySpeedRelativeRandom: 3
hSpeed: 2


[effect_闪光]
#priority:critical
image: SHARED:light_50.png
life: 10
fadeOut: true
alpha: 1

attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 4

drawUnderUnits: true
atmospheric: false


[leg_1]
x: -70
y: 90
attach_x: -27
attach_y: 45
moveSpeed: 2.6

rotateSpeed: 8
heightSpeed: 0.6
moveWarmUp: 4
resetAngle: 20
holdDisMin: 12

holdDisMax: 25
image_leg: 新腿.png
image_foot: 新脚.png
endDirOffset: -40
hardLimit: 35

favourOppositeSideNeighbours: true


[leg_2]
x: 70
y: 90
attach_x: 27
attach_y: 45
copyFrom: 1

endDirOffset: 40


[leg_3]
x: -80
y: -62
attach_x: -35
attach_y: -18
copyFrom: 1

endDirOffset: -130


[leg_4]
x: 80
y: -62
attach_x: 35
attach_y: -18
copyFrom: 1

endDirOffset: 130


[leg_5]
x: -94
y: 15
attach_x: -45
attach_y: 15
copyFrom: 1

endDirOffset: -90


[leg_6]
x: 94
y: 15
attach_x: 45
attach_y: 15
copyFrom: 1

endDirOffset: 90
[arm_1]
x: 0
y: 0
image_end:机架.png
drawDirOffset: 180
image_end_teamColors: true
[arm_2]
x: 0
y: 0
image_end:机架x.png
hidden:if not self.tags(includes= '布雷')
image_end_teamColors: true
drawDirOffset: 180

[arm_3]
x: 0
y: 0
image_end: 机体.png
image_end_teamColors: true
drawOverBody: false

[arm_4]
x: 33.5
y: -55
image_end: 盖子.png
image_end_teamColors: true
drawOverBody: false


[arm_5]
x: 33.5
y: -45
image_end: 盖子1.png
image_end_teamColors: true
drawOverBody: false


[arm_6]
x: -33.5
y: -55
image_end: 盖子2.png
image_end_teamColors: true
drawOverBody: false


[arm_7]
x: -33.5
y: -45
image_end: 盖子3.png
image_end_teamColors: true
drawOverBody: false





[arm_8]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true

hidden: if self.maxHp * 0.36 < self.hp







[effect_烟雾]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 120

fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 10
scaleFrom: 1

scaleTo: 3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01

dirOffsetRandom: 180
ySpeedRelativeRandom: 0.1
xSpeedRelativeRandom: 0.6
atmospheric: true


[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.88
scaleTo: 0.88
alpha: 2
fadeInTime: 5

drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10
[effect_烟雾wy]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 200
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 5
scaleTo: 7
alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.31
xSpeedRelativeRandom: 0.31
xOffsetRelativeRandom:115
yOffsetRelativeRandom:115
delayedStartTimerRandom:15
atmospheric: true

[animation_1]
# blendIn: 1s
# blendOut: 1s
arm6_0s: {x:0, y:0}
arm7_0s: {x:0, y:0}
arm6_0.6s: {x:0, y:0}
arm7_0.6s: {x:0, y:0}
arm6_1s: {x:0, y:-15}
arm7_1s: {x:0, y:15}
arm6_1.3s: {x:0, y:-15}
arm7_1.3s: {x:0, y:15}
arm6_1.31s: {x:0, y:0}
arm7_1.31s: {x:0, y:0}


[animation_2]
# blendIn: 1s
# blendOut: 1s
arm4_0s: {x:0, y:0}
arm5_0s: {x:0, y:0}
arm4_0.6s: {x:0, y:0}
arm5_0.6s: {x:0, y:0}
arm4_1s: {x:0, y:-15}
arm5_1s: {x:0, y:15}
arm4_1.3s: {x:0, y:-15}
arm5_1.3s: {x:0, y:15}

arm4_1.31s: {x:0, y:0}
arm5_1.31s: {x:0, y:0}
[animation_布雷]
arm1_0s: {x:0, y:0}
arm1_5s: {x:0, y:-100}
arm2_0s: {x:0, y:0}
arm2_5s: {x:0, y:-100}
[resource_温压弹]
displayName: 温压弹
displayNameShort: 温压弹
displayColor: #FF9D00FF
priority: 1
hidden: true
[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true

[movement]
movementType: OVER_CLIFF
moveSpeed: 1
moveAccelerationSpeed: 0.5
moveDecelerationSpeed: 0.5
maxTurnSpeed: 0.8

turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false


