


[core]
name: 小型防御塔底座t4
displayText: Малая база оборонительной башниt4
displayDescription: 【Уровень t4】【Оборонительное здание】【Здание】【Наземный юнит】【Надводный юнит】(при развёртывании на воде)\n-Тактическое назначение: малая универсальная база оборонительной башни。без вооружения, когда оборонительная башня не развёрнута。\n-Малая база оборонительной башни развёртывает компактные оборонительные системы Генезиса，\n-Это вооружение, хоть и малое по размерам,，но недооценивать его силу нельзя。
price: 4000
maxHp: 20000
footprint: 0,0,1,1
constructionFootprint: 0,0,1,1
buildingToFootprintOffsetX: 20
buildingToFootprintOffsetY: 20
techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 20s
radius: 16
buildingSelectionOffset: -8
armour:35
isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*2, CUSTOM:爆炸*1,largeExplosion*1
tags: 地面,建筑,防御建筑
[action_机枪塔]
convertTo: 机枪塔t4
displayType: action
text: развёртыватьПулемётная башняt4
price: 150
buildSpeed: 10s
isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется командный центр 4 уровня
unitShownInUI: 机枪塔t4
descriptionAddFromUnit: 机枪塔t4
descriptionAddUnitStats: 机枪塔t4
[action_迫击炮]
convertTo: 迫击炮t4
displayType: action
text: развёртыватьминомётt4
price: 4000
buildSpeed: 10s
isLocked: if not self.globalTeamTags(includes='弹幕架1') or self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: Требуется реактивная установка1ичетыреклассКомандный центр
unitShownInUI: 迫击炮t4
descriptionAddFromUnit: 迫击炮t4
descriptionAddUnitStats: 迫击炮t4
[action_镭射炮塔]
convertTo: 镭射炮塔t4
displayType: action
text: развёртыватьЛазерная башняt4
price: 4250,钍=178
buildSpeed: 10s
isLocked: if not self.globalTeamTags(includes='超导技术1')
isLockedMessage: Требуется сверхпроводимость 1
unitShownInUI: 镭射炮塔t4
descriptionAddFromUnit: 镭射炮塔t4
descriptionAddUnitStats: 镭射炮塔t4

[action_高射炮]
convertTo: 高射炮t4
displayType: action
text: развёртыватьЗенитное орудиеt4
price: 2200,钍=113
buildSpeed: 10s
isLocked: if not self.globalTeamTags(includes='轨道发射器3')
isLockedMessage: тынуждаетсяорбитальныйпусковая установка3
unitShownInUI: 高射炮t4
descriptionAddFromUnit: 高射炮t4
descriptionAddUnitStats: 高射炮t4

[action_休克打击炮塔]
convertTo: 休克打击炮塔t4
displayType: action
text: развёртыватьШоковая башняt4
price: 1100,钍=163
buildSpeed: 10s
isLocked: if not self.globalTeamTags(includes='电磁脉冲武器1')
isLockedMessage: Требуется ЭМИ-оружие
unitShownInUI: 休克打击炮塔t4
descriptionAddFromUnit: 休克打击炮塔t4
descriptionAddUnitStats: 休克打击炮塔t4
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[decal_影子]
image: ROOT:/创世纪军事集团/建筑特效/t4影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:0
xOffsetRelative:3
onlyWhileAlive:true
alpha:0.65
[decal_灯光]
image: ROOT:/创世纪军事集团/建筑特效/led.png
total_frames: 1
layer: afterBody
teamColors: true
isVisible:true
yOffsetRelative:-3
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.85
[decal_支柱]
image: ROOT:/创世纪军事集团/建筑特效/大支撑.png
total_frames: 1
isVisible:if self.isOverLiquid
layer: beforeBody
yOffsetRelative:-30
xOffsetRelative:0
onlyWhileAlive:true
imageScale:0.9
alpha:0.9
[graphics]
total_frames: 1
image: ROOT:/创世纪军事集团/建筑特效/防御塔t4底座.png
image_wreak: ROOT:/创世纪军事集团/建筑特效/防御塔t1死亡.png
image_turret: NONE
image_offsetY: 1

image_back: ROOT:/通用特效/NO.png
#AUTO
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.9

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 12

turretTurnSpeed: 6
maxAttackRange: 0
shootDelay: 0


[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true

attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37

alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true

dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.8

image: ROOT:/创世纪军事集团/建筑特效/爆炸.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 14
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
alwayStartDirAtZero: true
createWhenOverLiquid: false
createWhenOverLand: true


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0
maxTurnSpeed: 0

turnAcceleration: 0


[ai]
buildPriority: 0.1
ai_upgradePriority: 0.9
maxEachBase: 10
maxGlobal: 100


