


[core]
name:温迪戈无人机
displayText: Дрон «Вендиго»
displayDescription: -?
class: CustomUnitMetadata
price: 0
maxHp: 700
techLevel: 1
canNotBeGivenOrdersByPlayer: true
softCollisionOnAll: 200
radius: 12
explodeOnDeath: false
fogOfWarSightRange: 10
showOnMinimapToEnemies: true
isBio: false
numBitsOnDeath:0
copyFrom: ROOT:/通用特效/单位防护.ini
energyMax: 7000
energyRegen: -1
dieOnZeroEnergy: true
tags: 飞机,寄生免疫,伴生单位,无人单位
[hiddenAction_中立自杀]
autoTrigger: if self.teamId == -2
isVisible:false
isActive:false
deleteSelf:true
[hiddenAction_zz1]
autoTrigger:if not self.isInMap
addResources: hp= -999999

[action_ax]
autoTrigger: if self.timeAlive(laterThanSeconds=1)	and not self.tags(includes= '部署')
displayType: action
price: 0
buildSpeed: 0s
isVisible: false
temporarilyAddTags: 部署
playAnimation: attack

[graphics]
total_frames: 1
image: NO.png
image_wreak: NONE
image_turret: NONE

shadowOffsetX: 1
shadowOffsetY: 1
splastEffect: false
movementEffect: CUSTOM:火
movementEffectRate: 0.5

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: true
turretSize: 1
turretTurnSpeed: 250
maxAttackRange: 150
isMelee: true
meleeEngangementDistance: 99999
[turret_1]
#bomber
invisible: true
x: 0
y: 0
idleDir: 0
shoot_flame: CUSTOM:导弹碎片,CUSTOM:导弹碎片1
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: true
projectile: 1
size: 0
turnSpeed: 2
aimOffsetSpread: 0
[projectile_1]
@copyFromSection: template_爆炸
life: 250
speed: 5
targetSpeed: 10
areaDamage: 3500
areaRadius: 70
drawSize: 1
image:机体.png
explodeEffect: CUSTOM:大爆炸,CUSTOM:钢珠,CUSTOM:冲击波,CUSTOM:闪光,CUSTOM:气浪
explodeEffectOnShield:CUSTOM:大爆炸,CUSTOM:钢珠,CUSTOM:冲击波,CUSTOM:闪光,CUSTOM:气浪
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
deflectionPower: -1
areaRadiusFromEdge: true
trailEffectRate: 0.4
trailEffect: CUSTOM:火


[arm_1]
x: -2
y: 0
image_end: 左翼.png
drawOverBody: true
image_end_shadow: SHADOW:左翼.png

[arm_2]
x: 2
y: 0
image_end: 右翼.png
drawOverBody: true
image_end_shadow: SHADOW:右翼.png

[arm_3]
x: 0
y: 0
image_end: 机体.png
drawOverBody: true
image_end_shadow: SHADOW:机体.png


[animation_attack]
blendIn: 1s
blendOut: 2s
arm1_0s: {x:0, y:0,dir:0}
arm1_1s: {x:4, y:2,dir:-70}
arm1_9500s:{x:4, y:2,dir:-70}
arm2_0s: {x:0, y:2,dir:0}
arm2_1s: {x:-4, y:2,dir:70}
arm2_9500s:{x:-4, y:0,dir:70}
[effect_火]
life: 17
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.25
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #BBBBFFEE
xOffsetRelative	: 0
ySpeedRelative: -1
yOffsetRelative	: -14
drawUnderUnits: true
[effect_导弹碎片]
#priority: low
image: 左翼.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelative:-1
xSpeedRelativeRandom: -1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 15
xOffsetRelative	: -4
yOffsetRelative: 2
[effect_导弹碎片1]
#priority: low
image: 右翼.png
spawnChance: 1
life: 70
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 2
fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
xSpeedRelative:1
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 1.5
dirSpeedRandom: 15
xOffsetRelative	: 4
yOffsetRelative: 2
#——————————
[effect_大爆炸]
life: 100
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.2
image: ROOT:/创世纪军事集团/单位特效/大爆炸.png
total_frames: 40
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
animateFrameStart: 0
animateFrameEnd: 39
animateFramePingPong: false
animateFrameSpeed: 1.15
alpha: 2
[effect_冲击波]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.6
scaleTo: 1.1
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 2.4
scaleTo: 3.2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_气浪]
life: 55
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 1.8
scaleTo: 4.2
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 0.8
createWhenOverLiquid: false
createWhenOverLand: true
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1.4
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5
scaleTo:1
drawUnderUnits: false
atmospheric: false
[movement]
movementType: AIR
moveSpeed: 3.2
moveAccelerationSpeed: 100
moveDecelerationSpeed: 0.008
targetHeight: 70
targetHeightDrift: 2
maxTurnSpeed: 1.8
turnAcceleration: 0.06
#startingHeightOffset: 1000
moveSlidingMode : false
moveIgnoringBody: false
slowDeathFall: false


