


[core]
name: 多功能前哨站t2
displayDescription: 【阶级t3】【防御类建筑】【建筑单位】【地面单位】【水上单位】（当部署在水上时）\n-战术定位：维修设施/反水面舰艇炮塔 武器配置：\n-▲鱼雷发射管X2 只有建立在水上时才可用 只能攻击水面单位和潜航单位 爆炸伤害 \n-▲维护者无人机X1 能修复受损的机械单位 无武装\n-创世纪使用标准建造模板在战线各处广泛建造的多功能前哨站，\n-这种哨站结构简单，但内部却大有洞天，\n-这种哨站装备有修复无人机起降平台，水上版甚至还附加了大威力鱼雷发射器，\n-多功能前哨站可以作为一处坚实可靠的部队维护设施使用。站可以作为一处坚实可靠的部队维护设施使用。
price: 6000
maxHp: 13000
fogOfWarSightRange: 42
footprint: -4,-1,4,4
constructionFootprint: -4,-1,4,4
techLevel: 1
copyFrom: ROOT:/通用特效/单位防护.ini
buildSpeed: 20s
radius: 50
armour: 15
unitsSpawnedOnDeath:建筑损毁*1
isBuilding: true
isBio: false
numBitsOnDeath: 9
effectOnDeath: CUSTOM:烟雾*4, CUSTOM:爆破*6,largeExplosion
tags: 地面,建筑,修复塔
maxTransportingUnits: 1
transportUnitsCanUnloadUnits: false
transportUnitsAddUnloadOption: false
transportUnitsRequireTag: 维修飞机
transportUnitsHealBy: 0.5
transportUnitsRequireMovementType: air
transportUnitsKeepBuiltUnits: true
@memory 灰机: number
@memory 灰机list: unit[]
[hiddenAction_海上]
autoTrigger: if not self.tags(includes= '海上') and self.isOverLiquid
isVisible: false
temporarilyAddTags:海上

[hiddenAction_地上]
autoTrigger: if self.tags(includes= '海上') and not self.isOverLiquid
isVisible: false
temporarilyRemoveTags:海上
[action_升级]
convertTo: 多功能前哨站t3
displayType: action
text: 升级
buildSpeed: 15s
price: 2000

isLocked: if self.noUnitInTeam(withTag= '创世纪指挥中心t4')
isLockedMessage: 你需要四级指挥中心
description: 最大化多功能前哨站等级，加固其结构强度，增加其武器射程和威力，\n-增加额外一架维修无人机并添加雷达能力。\n-升级后将扩展多功能前哨站的飞行甲板，使其能额外停放一架维修无人机，\n-极大提升维修效率。
[hiddenAction_drone]
autoTrigger: if self.queueSize < 0.5 and memory.灰机 < 1
alsoQueueAction: SDD
[hiddenAction_SDD]
buildSpeed: 4s
requireConditional: if memory.灰机 < 1
addUnitsIntoTransport: 维护者无人机
[hiddenAction_set0]
autoTriggerOnEvent: newMessage(withTag= '灰机a')
alsoTriggerAction: set1, count0
alsoTriggerActionRepeat: memory.灰机list.size + 2
[hiddenAction_set1]
requireConditional: if memory.灰机list[0] != null and memory.灰机list[thisActionIndex].hp <= 0 or thisActionIndex == 0
setUnitMemory: 灰机list[0] = null, 灰机list[thisActionIndex] = eventSource

[hiddenAction_unset0]
autoTriggerOnEvent: newMessage(withTag= '灰机d')
alsoTriggerAction: count0
alsoTriggerActionRepeat: memory.灰机list.size + 1

[hiddenAction_count0]
requireConditional: if memory.灰机list[thisActionIndex].hp > 0 or thisActionIndex == 0
setUnitMemory: 灰机 = select(thisActionIndex == 0, 0, memory.灰机 + 1)


[decal_地板]
image: ROOT:/创世纪军事集团/建筑特效/地板x.png
total_frames: 1
layer: shadow
yOffsetRelative:-22
xOffsetRelative:0
onlyWhileAlive:true
isVisible:if not self.isOverLiquid
alpha:1
[decal_支撑]
image: ROOT:/创世纪军事集团/建筑特效/支x.png
total_frames: 1
layer: shadow
yOffsetRelative:-75
xOffsetRelative:0.5
onlyWhileAlive:true
isVisible:if self.isOverLiquid
alpha:0.4
[decal_shadow]
image: SHADOW:柱子.png
layer: shadow
xOffsetAbsolute: -4
yOffsetAbsolute: -65
alpha: 0.5
onlyWhileAlive: true
isVisible: true
[decal_钢门]
image: ROOT:/创世纪军事集团/建筑特效/钢门.png
total_frames: 1
layer: beforeBody
yOffsetRelative:-61
xOffsetRelative:0.5
onlyWhileAlive:true
isVisible:if not self.isOverLiquid
[decal_鱼雷]
image: ROOT:/创世纪军事集团/建筑特效/鱼雷.png
total_frames: 1
layer: beforeBody
yOffsetRelative:-66
xOffsetRelative:0.5
onlyWhileAlive:true
isVisible:if self.isOverLiquid
[decal_损坏]
image: 损坏.png
total_frames: 1
layer: afterBody
yOffsetRelative:65.5
xOffsetRelative:-11
onlyWhileAlive:true
isVisible:if self.hp<self.maxHp * 0.36
teamColors: true
[decal_灯光]
image: 灯光.png
total_frames: 1
layer: onTop
yOffsetRelative:65.5
xOffsetRelative:-11
onlyWhileAlive:true
isVisible:if self.maxHp * 0.36 < self.hp
alpha:0.8

[graphics]
total_frames: 1
image_back: ROOT:/通用特效/NO.png
image: 柱子.png
image_turret: NONE
image_offsetY: -65
image_offsetX: -10
image_wreak: ROOT:/创世纪军事集团/建筑特效/柱子死亡.png
image_shadow: NONE
shadowOffsetX: 1
shadowOffsetY: 1
showShotDelayBar:false
#drawLayer: ground
[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: true
turretSize: 12
canAttackNotTouchingWaterUnits: false
turretTurnSpeed: 6
maxAttackRange: 700
shootDelay: 0
[turret_1]
x: -4
y: -65
canShoot: true
invisible: true
projectile: 1
shoot_sound: ROOT:/通用特效/鱼雷音效.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:冲击波y,CUSTOM:水雾x*3
shoot_light: #FFEECCCC
canAttackFlyingUnits: false
size: 15
turnSpeed: 0
canAttackLandUnits: true
canAttackUnderwaterUnits: true
canAttackNotTouchingWaterUnits: false
canAttackCondition: if self.resource.xk < 1 and self.isOverLiquid
canAttackMaxAngle: 181
delay:480
limitingMinRange: 200
idleDir: 90
canOnlyAttackUnitsWithoutTags:悬浮
[turret_2]
x: 6
y: -65
copyFrom: 1
warmup: 30
delay:450


[projectile_1]
@copyFromSection: template_爆炸
areaDamage: 1000
areaRadius: 65
areaHitUnderwaterAlways:true
areaRadiusFromEdge: true
life: 1000
speed: 2
targetSpeed: 4
image: 鱼雷1.png
largeHitEffect: true
deflectionPower: -1
drawSize: 0.9
explodeEffect: CUSTOM:冲击波y,CUSTOM:闪光y,CUSTOM:水波y,CUSTOM:水雾y*4,CUSTOM:水波1
explodeEffectOnShield: CUSTOM:冲击波y,CUSTOM:闪光y,CUSTOM:水波y,CUSTOM:水雾y*4,CUSTOM:水波1
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴
turnSpeed: 2


[movement]
movementType: HOVER
moveSpeed: 0
moveAccelerationSpeed: 0.01
moveDecelerationSpeed: 0.01
maxTurnSpeed: 0

turnAcceleration: 0.1

[effect_烟雾]
image: ROOT:/创世纪军事集团/建筑特效/烟雾2.png
frameIndex: 0
createWhenOverLiquid: false
life: 240
fadeOut: true
attachedToUnit: false
color: #6D5448
fadeInTime: 5
scaleFrom: 0.15
scaleTo: 0.37
alpha: 1
drawUnderUnits: false
hSpeed: 0.2
hOffsetRandom: 0.15
atmospheric: true
dirOffsetRandom: 180
xOffsetRelativeRandom: 24
yOffsetRelativeRandom: 24
xSpeedAbsoluteRandom: 0.2
ySpeedAbsoluteRandom: 0.2
[effect_爆破]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.5
image: ROOT:/创世纪军事集团/单位特效/寄.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.32
alsoPlaySound: ROOT:/太空浪人/建筑特效/倒塌特效/倒塌.ogg
dirOffsetRandom: 180
xOffsetRelative	: 0
yOffsetRelative	: 0
xOffsetRelativeRandom:35
yOffsetRelativeRandom:55
delayedStartTimerRandom:30
#——————开火
[effect_冲击波]
stripIndex: shockwave
life: 33
scaleFrom: 0.6
scaleTo: 3.5
alpha: 0.9
fadeOut: true
attachedToUnit: false
fadeInTime: 2
[effect_闪光y]
image: SHARED:light_50.png
life: 15
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 5.5
scaleTo: 5.5
drawUnderUnits: false
atmospheric: false
[effect_冲击波y]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 1.2
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
createWhenOverLiquid: true
createWhenOverLand: false
drawUnderUnits: true
[effect_水波y]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 4
scaleTo: 6
image: ROOT:/通用特效/水波1.png
total_frames: 14
animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/巨炮爆炸.wav
[effect_水雾y]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 3.5
scaleTo: 5
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.27
ySpeedRelativeRandom: 0.27
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
createWhenOverLiquid: true
createWhenOverLand: false
xOffsetRelativeRandom:10
yOffsetRelativeRandom:10
[effect_水雾x]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 2
scaleTo: 3.5
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.27
ySpeedRelativeRandom: 0.27
xSpeedAbsoluteRandom: 0.3
ySpeedAbsoluteRandom: 0.3
createWhenOverLiquid: true
createWhenOverLand: false
[effect_尾巴]
image: SHARED:light_50.png
life: 38
fadeOut: true
attachedToUnit: false
priority: high
color:#FF0092FF
fadeInTime: 2
scaleFrom: 0.35
scaleTo: 0.2
alpha: 0.8
drawUnderUnits: true
yOffsetRelative:-10
[effect_水雾]
stripIndex: effects
frameIndex: 0
life: 175
fadeOut: true
attachedToUnit: false
color: #FFFFFF
fadeInTime: 4
scaleFrom: 3.5
scaleTo: 5
alpha: 1.33
drawUnderUnits: false
atmospheric: true
dirOffsetRandom: 180
shadow: true
hSpeed: 0.2
hOffsetRandom: 0.15
xSpeedRelativeRandom: 0.15
ySpeedRelativeRandom: 0.15
xSpeedAbsoluteRandom: 0.15
ySpeedAbsoluteRandom: 0.15
createWhenOverLiquid: true
createWhenOverLand: false
xOffsetRelativeRandom:100
yOffsetRelativeRandom:180
delayedStartTimerRandom:40
[effect_水波1]
image: SHARED:ripple.png
life: 90
lifeRandom: 20
fadeOut: true
fadeInTime: 3
attachedToUnit: false
color: #FFFFFF
scaleFrom: 1.5
scaleTo: 5
alpha: 0.7
drawUnderUnits:false
dirOffsetRandom: 180
dirSpeed: 0.5
dirSpeedRandom:0.5
delayedStartTimer: 5

[arm_3]
x: -48
y: 88
image_end: 钩子.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.hp<self.maxHp * 0.36
[arm_4]
x: -48
y: 88
image_end: 钩子损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp
[arm_5]
x: -9.5
y: 64.5
image_end: 遮蔽.png
image_end_teamColors: true
drawOverBody: true
[animation_2]
onActions: idle
arm3_0s: {x:0, y:0, dir:0}
arm3_1.5s: {x:-30, y:0, dir:0}
arm3_2s: {x:-30, y:0, dir:0}
arm3_3.5s: {x:0, y:0, dir:0}
arm3_5s: {x:0, y:0, dir:0}
[attachment_drone1]
x: 0
y:150
isVisible:true
addTransportedUnits: true
canAttack: false
setDrawLayerOnBottom:false
lockRotation:true
idleDir: 135
[ai]
buildPriority: 0.05
ai_upgradePriority: 0.05
maxEachBase: 3
maxGlobal: 10


