


[core]
name: 守护者IFV
displayDescription: :【阶级t4】【机械单位】【地面单位】【重型掩体】战术定位:布雷型步兵堡垒，载员数量：12\n-只能装载生物单位 自身无法被运输 死亡后内部成员将存活。\n-武器配置：▲40毫米自动炮X1 对地对空 动能伤害 \n-▲防空导弹垂发单元x2 只能对空 爆炸伤害\n-守护者IFV是创世纪空间最大，装甲最厚，功能最全面的步兵战车，\n-其内置的巨大空间甚至可以塞下一整个机甲小队，或者是一个私人包厢用于护送VIP。\n-哪怕是直面重型部队，其配备的40毫米自动炮和防空飞弹，\n-也能在交战中丝毫不落下风，即便最终实力不敌，\n-守护者也能在撤退中部署大量地雷埋伏敌人并彻底封锁整个区域。
class: CustomUnitMetadata
price: 5000
maxHp: 17500
fogOfWarSightRange: 19
techLevel: 1
buildSpeed: 17s
radius: 33
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini
nanoFactorySpeed: 1.3
tags: 地面,重型掩体,本来就有啊,jabzhdja
armour: 22
maxTransportingUnits: 12
transportUnitsRequireTag: 步兵,卧倒,机甲
transportUnitsKillOnDeath: false

transportUnitsKeepBuiltUnits: true
unitsSpawnedOnDeath: 损毁2*1
canRepairBuildings: true
autoRepair: true
canRepairUnits: true

nanoRepairSpeed: 0.5
nanoRange: 345
canBuild_1_name: 休克打击步兵
canBuild_1_pos: 1
canBuild_2_name: 机甲战士

canBuild_2_pos: 2
canBuild_3_name: 角斗士
canBuild_3_pos: 3
canBuild_4_name: 操纵者
canBuild_4_pos: 4

canBuild_5_name: 蜂刺导弹小组
canBuild_5_pos: 5

[canBuild_1]
name:彻甲榴弹
pos: 0.1
forceNano: true
[canBuild_2]
name: 无人机蜂箱
pos: 0.2
forceNano: true
[hiddenAction_1q]
price: 0
buildSpeed: 0s
isVisible: false
autoTrigger:if  self.numberOfAttachedUnits(withTag= '1格')*1 + self.numberOfAttachedUnits(withTag= '蜂刺')*2 + self.numberOfAttachedUnits(withTag= '反坦克炮') * 2+self.numberOfAttachedUnits(withTag= '机甲战士') * 2+self.numberOfAttachedUnits(withTag= '角斗士') * 3+self.numberOfAttachedUnits(withTag= '操纵者') * 2+self.numberOfAttachedUnits(withTag= '狩猎者') * 4> 12
forceUnloadTransportNow:true
forceUnloadTransportNow_onlyOnSlot:1
highPriorityQueue: true
#refundAllQueuedItems:true
displayType: action
[action_结构]
text: 强化结构
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/强化结构.png
isLockedMessage: 该单位的结构构造经过特殊的强化和加固，\n-能免疫一切负面效果。
[action_重型掩体]
text: 重型掩体
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/重型掩体.png
description: 一处重型掩体，能为附近140范围内的生物单位提供重型掩护。\n-重型掩护能为生物单位减免75%的伤害，\n-但是，掩体无法减免部分速射，激光，火焰，电击，中性，自爆，近战，衰解等其他无视掩体的武器。

[action_akm]
autoTrigger: if numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=420) and not self.hasFlag(id=1)
isVisible: false
addResources: setFlag=1
playAnimation: attack


[action_bkm]
autoTrigger: if self.hasFlag(id=1) and not numberOfUnitsInEnemyTeam(greaterThan=0, withinRange=420)
playAnimation: attack1
stopLastAnimation: true
addResources: unsetFlag=1
isVisible: false


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)

[action_弹道导弹托]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/导弹托.png
text: 弹道导弹托
isActive: false
isVisible: if self.globalTeamTags(includes='导弹托1')
[hiddenAction_添加]
autoTrigger: if self.globalTeamTags(includes='导弹托1') and not self.tags(includes= '反高空')
temporarilyAddTags: 反高空
[action_弹幕架3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/弹幕3.png
text: 弹幕架3
isActive: false
isVisible: if self.globalTeamTags(includes='弹幕架3')
[action_恐怖地雷1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖1.png
text: 恐怖地雷1
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷1') and not self.globalTeamTags(includes='恐怖地雷3')
isAlsoViewableByAllies: true
[action_恐怖地雷3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/恐怖3.png
text: 恐怖地雷3
isActive: false
isVisible: if self.globalTeamTags(includes='恐怖地雷3')
[action_电磁脉冲武器1]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/电磁1.png
text: 电磁脉冲武器1
isActive: false
isVisible: if self.globalTeamTags(includes='电磁脉冲武器1')
[decal_损坏]
layer: afterBody
image: 损坏.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.hp<self.maxHp * 0.36 
[decal_遮盖]
layer: afterBody
image: 遮盖.png
onlyWhileAlive: true
teamColors: true
isVisible:if self.maxHp * 0.36< self.hp
[graphics]
total_frames: 2
image: 主体.png
image_wreak: 死亡.png
image_shadow: AUTO
shadowOffsetX: 2

shadowOffsetY: 2
animation_moving_start: 0
animation_moving_end: 1
animation_moving_speed: 3
dustEffect: true

#turretImageScale:0.8
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 13

turretTurnSpeed: 4
maxAttackRange: 450
turretMultiTargeting: true






[turret_3]
x: 0
y: -40
idleDir: 180
warmup: 0
size: 8
limitingRange: 320
canShoot: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
isMainNanoTurret: true

image: 塔.png


[turret_4]
x: 0
y: 15
#主炮
projectile: 1
turnSpeed: 2.5
limitingRange: 320
turnSpeedAcceleration: 0.04
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:烟雾2,CUSTOM:枪口火焰,CUSTOM:弹壳
shoot_light: #FFEECCCC

canShoot: true
recoilOffset: -3.5
recoilOutTime: 4
recoilReturnTime: 20
delay: 20

canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1 and not self.globalTeamTags(includes='电磁脉冲武器1')
image: 炮管.png
attachedTo: 6
canOnlyAttackUnitsWithoutTags:高空
slave: true
invisible:if self.globalTeamTags(includes='电磁脉冲武器1')
[turret_5]
x: 0
y: 15
#主炮
projectile: beam0
turnSpeed: 2.5
limitingRange: 320
turnSpeedAcceleration: 0.04
shoot_sound: ROOT:/通用特效/shock.ogg
shoot_sound_vol: 0.4
shoot_flame: CUSTOM:烟雾2*6
shoot_light: #FFEECCCC
canShoot: true
delay: 180
warmup:60
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='电磁脉冲武器1')
image: 炮管1.png
attachedTo: 6
canOnlyAttackUnitsWithoutTags:高空
slave: true
invisible:if not self.globalTeamTags(includes='电磁脉冲武器1')

[turret_6]
x: 0
y: -15
#炮塔
canShoot: false
canAttackFlyingUnits: true
canOnlyAttackUnitsWithoutTags:高空
canAttackLandUnits: true
canAttackCondition: if self.resource.xk < 1
image: 炮塔.png
limitingRange: 320


[turret_7]
x: -13
y: -35
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*5
shoot_light: #FFEECCCC
canOnlyAttackUnitsWithoutTags:高空
canAttackCondition: if self.resource.xk < 1
projectile: 2
size: 0
turnSpeed: 811
delay: 80
[turret_8]
x: 13
y: -35
copyFrom: 7
warmup: 10
delay: 70
[turret_9]
x: -13
y: -35
copyFrom: 7
warmup: 20
delay: 60
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹幕架3')
[turret_10]
x: 13
y: -35
copyFrom: 7
warmup: 30
delay: 50
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹幕架3')

[turret_11]
x: -13
y: -35
invisible: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹.ogg
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:烟雾*5
shoot_light: #FFEECCCC
canOnlyAttackUnitsWithTags:高空
canAttackCondition: if self.resource.xk < 1
projectile: 3
size: 0
turnSpeed: 811
delay: 80
[turret_12]
x: 13
y: -35
copyFrom: 11
warmup: 10
delay: 70
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹幕架3')
[turret_13]
x: -13
y: -35
copyFrom: 11
warmup: 20
delay: 60
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹幕架3')
[turret_14]
x: 13
y: -35
copyFrom: 11
warmup: 30
delay: 50
canAttackCondition: if self.resource.xk < 1 and self.globalTeamTags(includes='弹幕架3')

[projectile_1]
@copyFromSection: template_动能
#主炮子弹
directDamage: 90
life: 60
speed: 7.5

color: #FFFFFF73
drawSize: 0.86
largeHitEffect: true
lightSize: 1
frame: 8

lightColor: #FFFFFF73
explodeEffect: CUSTOM:爆炸,CUSTOM:闪光


[projectile_2]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85

image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 70

ballistic_delaymove_height: 80
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1


[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 400
areaRadius: 70
life: 200
speed: 5

image: ROOT:/创世纪军事集团/单位特效/导弹头.png
targetSpeed: 9
drawSize: 0.85
explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸1, CUSTOM:闪光,CUSTOM:冲击波

areaRadiusFromEdge: true
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_3]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.85
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 140
ballistic_delaymove_height: 100
spawnProjectilesOnEndOfLife: 锁定1
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2, CUSTOM:导弹碎片1
[projectile_锁定1]
@copyFromSection: template_爆炸
areaDamage: 400
areaRadius: 70
life: 200
speed: 5
image: ROOT:/创世纪军事集团/单位特效/导弹头.png
targetSpeed: 9
drawSize: 0.85
explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸1, CUSTOM:闪光,CUSTOM:冲击波
areaRadiusFromEdge: true
trailEffect: true
lightSize: 0.9
lightColor: #FFFFFF73
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

#————————————休克
[projectile_beam0]
explodeEffect: CUSTOM:电xk,CUSTOM:闪光xk
directDamage: 70
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 1
life: 3
instant: true
instantReuseLast: true
instantReuseLast_alsoChangeTurretAim: true
moveWithParent: true
beamImage: ROOT:/通用特效/闪电1q.png
#beamImageOffsetRate: 2
spawnProjectilesOnEndOfLife: beam1(recursionLimit= 17)
armourIgnoreAmount: 99999
shieldDamageMultiplier:20
mutator30_ifUnitWithTags: 轻型掩护
mutator30_directDamageMultiplier: 1
mutator30_areaDamageMultiplier: 1
mutator31_ifUnitWithTags: 重型掩护
mutator31_directDamageMultiplier: 1
mutator31_areaDamageMultiplier: 1

[projectile_beam1]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电2q.png
spawnProjectilesOnEndOfLife: beam2(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0
[projectile_beam2]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电3q.png
spawnProjectilesOnEndOfLife: beam3(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam3]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电4q.png
spawnProjectilesOnEndOfLife: beam4(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam4]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电5q.png
spawnProjectilesOnEndOfLife: beam5(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam5]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电6q.png
spawnProjectilesOnEndOfLife: beam6(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0


[projectile_beam6]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电7q.png
spawnProjectilesOnEndOfLife: beam7(recursionLimit= 17)
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[projectile_beam7]
@copyFromSection: projectile_beam0
beamImage: ROOT:/通用特效/闪电8q.png
spawnProjectilesOnEndOfLife: NONE
directDamage: 0
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: xk= 0

[attachment_1]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_2]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false
keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_3]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_4]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false

[attachment_5]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_6]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_7]
x: 0
y:0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_8]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_9]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_10]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_11]
x: 0
y:0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[attachment_12]
x: 0
y: 0
isVisible: false
height: -1
canBeAttackedAndDamaged: false

keepAliveWhenParentDies: true
addTransportedUnits: 1
rotateWithParent: true
lockRotation: false
resetRotationWhenNotAttacking: true

canAttack: true
setDrawLayerOnBottom: true
alwaysAllowedToAttackParentsMainTarget: false


[effect_枪口火焰]
life: 8
attachedToUnit: true
image: ROOT:/创世纪军事集团/步兵特效/枪口火焰.png
total_frames: 3
animateFrameStart: 0

priority: critical
animateFrameEnd: 2
animateFrameSpeed: 0.5
fadeOut: false
scaleFrom: 2

scaleTo: 2


[effect_烟雾2]
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 60

fadeOut: true
attachedToUnit: true
#color:#FFE56BFF
#color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.4
scaleTo: 1.3
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.2
xSpeedRelativeRandom: 0.2
yOffsetRelative: 0.2

ySpeedRelative: 0.41
atmospheric: true


[effect_弹壳]
#priority: low
image: ROOT:/通用特效/弹壳.png
#spawnChance: 0.8
life: 130
fadeOut: true

attachedToUnit: false
color: #FFFFFF
scaleFrom: 0.5
scaleTo: 0.5
alpha: 2

fadeInTime: 5
drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2

createWhenZoomedOut: false
xSpeedRelative: 1.2
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.8
yOffsetRelative: -35

xOffsetRelative: 5
hSpeed: 2
dirSpeedRandom: 50


[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false

color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 2.5
scaleTo: 2.5
drawUnderUnits: false

atmospheric: false


[effect_爆炸]
life: 60
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 1
image: ROOT:/通用特效/爆炸特效1.png
total_frames: 7

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.26
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg

alpha: 1.2


[effect_烟雾]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 100
fadeOut: true
attachedToUnit: true
color: #FFFFFF
fadeInTime: 10

scaleFrom: 0.3
scaleTo: 1.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false

hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.27
xSpeedRelativeRandom: 0.27
atmospheric: true


[effect_冲击波]
life: 110
priority: critical
fadeInTime: 2
fadeOut: true
attachedToUnit: false

scaleFrom: 1.4
scaleTo: 2.8
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2

createWhenOverLiquid: false
createWhenOverLand: true


[effect_爆炸1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 2
scaleTo: 2.3

image: ROOT:/创世纪军事集团/单位特效/小爆炸动态.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg
alwayStartDirAtZero: true


[effect_导弹碎片]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片1.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50


[effect_导弹碎片1]
#priority: low
image: ROOT:/创世纪军事集团/单位特效/导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true

attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2.5
createWhenZoomedOut: false

xSpeedRelativeRandom: 0.1
ySpeedRelativeRandom: 0.3
hSpeed: 2.5
dirSpeedRandom: 10
[effect_电xk]
life: 120
dirOffset: 0
dirOffsetRandom: 360
fadeInTime: 0
fadeOut: false
attachedToUnit: false
image: SHARED:lightning_shock.png
total_frames: 14
animateFrameStart: 2
animateFrameStartRandomAdd: 2
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.5
animateFrameSpeedRandom: 0.1
alpha: 1

drawUnderUnits: false
scaleFrom: 2
scaleTo: 2
[effect_闪光xk]
image: SHARED:light_50.png
life: 10
fadeOut: true
alpha: 1
attachedToUnit: false
color: #FFFFFFFF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false

[arm_1]
x: 0
y: 0
image_end: 导弹.png
image_end_teamColors: true
drawUnderAllUnits: true


[arm_2]
x: 12
y: -34.7
image_end: 盖子.png
image_end_teamColors: true
#drawUnderAllUnits:t


[arm_3]
x: -12
y: -34.7
image_end: 盖子.png
image_end_teamColors: true
#drawUnderAllUnits:true


[animation_attack]
blendIn: 1s
blendOut: 2s
arm2_1s: {x:0, y:21}
arm2_490s: {x:0, y:21}
arm3_1s: {x:0, y:21}

arm3_490s: {x:0, y:21}


[animation_attack1]
blendIn: 1s
blendOut: 2s
arm2_1s: {x:0, y:0}
arm3_1s: {x:0, y:0}


[movement]
movementType: LAND
moveSpeed: 1.15
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.17
reverseSpeedPercentage: 0.6

maxTurnSpeed: 1.8
turnAcceleration: 0.08
moveSlidingMode: false
moveIgnoringBody: false


[ai]
useAsBuilder: true


