


[hiddenAction_寄生b]
addResources: awz= ${awzxq}


[core]
name: 北极星机甲
displayText: Мех «Полярная звезда»
copyFrom: ROOT:/通用特效/单位防护.ini
price: 4200,awz= ${awzxq}
@global awzxq: 50
reclaimPrice: awz= ${awzxq}

maxHp: 4200
displayDescription: -在古人类第二次大航海时代中期，北极星就被古人类设计了出来，\n-在当时，粒子武器是一个十分先进且新颖的武器，\n-只不过可惜的是，由于技术过于落后，粒子武器的体积往往十分巨大，\n-导致粒子武器只能以星舰为载体，而北极星是对粒子武器小型化的一次大胆尝试，\n-但是实验最终还是以失败告终，而北极星资料也被雪藏于数据库中，不见天日。\n-太空浪人数据库资料里发现了北极星的图纸，以如今的技术将其制造出来简直易如反掌，\n-因此重获新生的北极星机甲果然不负众望，成为太空浪人部队中最广泛使用的防空机甲，\n-对空，对高空，动能伤害。
techLevel: 1
buildSpeed: 15s
#availableInDemo: true
fogOfWarSightRange: 29
radius: 28
armour: 8
displayRadius: 28
unitsSpawnedOnDeath: 损毁*1
tags: 地面,反高空

selfRegenRate: 0.2
@memory 计时1: float

[hiddenAction_强制脱离]
autoTrigger: if self.hasParent(withTag= '阿玛洛克')
disconnectFromParent: true
[hiddenAction_手动档]
autoTriggerOnEvent: newWaypointGivenByPlayer
setUnitMemory: 计时1 = self.timeAlive + 15
# 检索延迟15s


[hiddenAction_检索]
autoTrigger: if self.timeAlive > memory.计时1 and not self.isAttacking and not self.hasActiveWaypoint(type= 'move') and not self.hasActiveWaypoint(type= 'attackmove') and not self.hasActiveWaypoint(type='patrol') and not self.hasActiveWaypoint(type='guard')
clearAllWaypoints: true
takeResources_searchOnly: true
takeResources_includeUnitsWithinRange: ${attack.maxAttackRange}
# 检索范围

takeResources_excludeUnitsWithoutTags: 飞机,高空
takeResources_includeUnitsWithinRange_team: enemy
takeResources_includeUnitsInTransport: false
takeResources_includeParent: false
takeResources_triggerActionForEach: 自动索敌

setUnitMemory: 计时1 = self.timeAlive + 1.5
# 检索延迟1.5s


[hiddenAction_自动索敌]
requireConditional: if not thisActionTarget.hasParent and not thisActionTarget.tags(includes= '不检测') and (thisActionTarget.tags(includes= '高空') or distanceBetweenSquared(self, thisActionTarget) < 470 * 470)
# 800为常规射程
addWaypoint_type: attack
addWaypoint_target_fromReference: thisActionTarget


[action_停暗物质]
iconImage: ROOT:/太空浪人/单位特效/没暗物质.png
text: Недостаточно тёмной материи
isActive: false
isVisible: if self.resource.awz<0
displayType: infoOnly

isGuiBlinking: true


[action_赛格门塔护甲1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人纳米蜂巢/赛格门塔护甲.png
text: Броня «Сегмента» 1
isActive: false
isVisible: if self.globalTeamTags(includes='赛格门塔1')


[action_衰解科技TS1]
displayType: infoOnlyNoBox
iconImage: ROOT:/太空浪人/太空浪人建筑/t3建筑/太空浪人智脑节点/衰解.png
text: Фазовая распадная пушка 2
isActive: false
isVisible: if self.globalTeamTags(includes='衰解2')



[action_t1]
autoTrigger: if self.isOverLiquid and not self.hasParent()
isVisible: false
addResources: hp=-999999


[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯') or self.resource.awz<0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)


[graphics]
image: ROOT:/通用特效/NO.png
image_wreak: 死亡.png
image_turret: 主体.png
image_shadow: AUTO
shadowOffsetX: 1

shadowOffsetY: 1
showEnergyBar: false
lock_body_rotation_with_main_turret: true
lock_shadow_rotation_with_main_turret: true
teamColorsOnTurret: true


[attack]
canAttack: true
canAttackFlyingUnits: if self.resource.awz>-1
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 14

turretTurnSpeed: 1
maxAttackRange: 630
shootDelay: 6
turretRotateWithBody: true


[turret_hj1]
x: 0
y: 0
#shoot_sound_vol:0.5
shoot_sound: NONE
shoot_flame: CUSTOM:光环h,CUSTOM:粒子h*12,CUSTOM:冲击波h

invisible: true
canAttackCondition: if self.globalTeamTags(includes='赛格门塔1')
resourceUsage: hp=-100
projectile: 13
delay: 120

size: 0
limitingRange: 470


[projectile_13]
life: 0
speed: 0
directDamage: 0
drawSize: 0


[turret_2]
x: 19
y: 22
image: 枪管.png
attachedTo: 1
slave: true
limitingRange: 470
projectile: 1
shoot_sound: ROOT:/太空浪人/单位特效/副炮.ogg
shoot_sound_vol: 1
shoot_flame: CUSTOM:弹壳右
shoot_light: #FFFF1200

canShoot: true
size: 10
recoilOffset: -4
delay: 30
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='衰解2')
canOnlyAttackUnitsWithoutTags:高空

[turret_3]
x: 23
y: 22
image: 枪管.png
attachedTo: 1
slave: true
limitingRange: 470
projectile: 1
shoot_sound: ROOT:/太空浪人/单位特效/副炮.ogg
shoot_sound_vol: 1
shoot_flame: CUSTOM:弹壳右
shoot_light: #FFFF1200
canOnlyAttackUnitsWithoutTags:高空
canShoot: true
size: 10
recoilOffset: -4
delay: 30
warmup: 5
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='衰解2')


[turret_4]
x: 21
y: 22
image: 枪管.png
attachedTo: 1
slave: true
limitingRange: 470
projectile: 1
shoot_sound: ROOT:/太空浪人/单位特效/副炮.ogg
shoot_sound_vol: 1
shoot_flame: CUSTOM:弹壳右
shoot_light: #FFFF1200
canOnlyAttackUnitsWithoutTags:高空
canShoot: true
size: 10
recoilOffset: -4
delay: 30
warmup: 10
canAttackCondition: if self.resource.xk < 1
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='衰解2')


[turret_5]
x: -19
y: 40
attachedTo: 1
slave: true
invisible: true
projectile: 2
shoot_sound: ROOT:/余辉军团/单位特效/等离子音效.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子1*6
shoot_light: #FFFF1200

warmup: 60
#warmupStartEffect:CUSTOM:气浪,CUSTOM:粒子*2
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
canShoot: true
size: 22


canAttackLandUnits: false

delay: 120
#limitingRange:250
canAttackCondition: if self.resource.xk < 1
limitingMinRange: 260
altProjectile: 炮弹1
limitingRange: 470
altProjectileCondition: if self.globalTeamTags(includes='衰解2')
canOnlyAttackUnitsWithoutTags:高空
[turret_6]
x: -19
y: 40
attachedTo: 1
slave: true
invisible: true
projectile: 2
shoot_sound: ROOT:/余辉军团/单位特效/等离子音效.ogg
shoot_sound_vol: 0.7
shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子1*6
shoot_light: #FFFF1200

warmup: 60
#warmupStartEffect:CUSTOM:气浪,CUSTOM:粒子*2
chargeEffectImage: ROOT:/太空浪人/单位特效/光束.png
canShoot: true
size: 22
canAttackLandUnits: false
delay: 120
canAttackCondition: if self.resource.xk < 1
limitingMinRange: 260
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='衰解2')
canOnlyAttackUnitsWithTags:高空
[turret_1]
x: 0
y: 0
image: 主体.png
turnSpeed: 2.2
turnSpeedAcceleration: 0.4

canShoot: false
canAttackCondition: if self.resource.xk < 1
[turret_7]
x: -19
y: 40
image: 炮管.png
attachedTo: 1
slave: true
canShoot: false
canAttackCondition: if self.resource.xk < 1

[projectile_1]
@copyFromSection: template_动能
areaDamage: 100
areaRadius: 40
life: 200
speed: 10

image: ROOT:/太空浪人/单位特效/光束.png
targetSpeed: 10
drawSize: 1
explodeEffect: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:碎裂
explodeEffectOnShield: CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:碎裂

#targetGround:true
areaRadiusFromEdge: true
lightSize: 0.75
trailEffectRate: 0.9
trailEffect: CUSTOM:尾巴

lightColor: #FFFF1200
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_炮弹]
@copyFromSection: template_能源
areaDamage: 90
areaRadius: 60
life: 200
speed: 10

image: ROOT:/太空浪人/单位特效/光束7.png
targetSpeed: 10
drawSize: 1
explodeEffect: CUSTOM:爆炸s, CUSTOM:闪光s,CUSTOM:碎裂s
explodeEffectOnShield: CUSTOM:爆炸s, CUSTOM:闪光s,CUSTOM:碎裂s

mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesAreaHit: sz=4
#targetGround:true
areaDamageNoFalloff: true
areaRadiusFromEdge: true

lightSize: 0.75
trailEffectRate: 0.9
trailEffect: CUSTOM:尾巴s
lightColor: #FF2C56FF
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0

[projectile_2]
@copyFromSection: template_动能
directDamage: 1800
life: 20
instant: true
laserEffect: true

explodeEffect: CUSTOM:爆炸1, CUSTOM:闪光1,CUSTOM:聚变,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:爆炸1, CUSTOM:闪光1,CUSTOM:聚变,CUSTOM:冲击波
lightSize: 0.75
beamImage: 激光.png
#color:#FFFF1200


[projectile_炮弹1]
@copyFromSection: template_能源
directDamage: 2500
life: 20
instant: true
laserEffect: true

explodeEffect: CUSTOM:爆炸1s, CUSTOM:闪光1s,CUSTOM:聚变s,CUSTOM:冲击波s,CUSTOM:粒子s*10
explodeEffectOnShield: CUSTOM:爆炸1s, CUSTOM:闪光1s,CUSTOM:聚变s,CUSTOM:冲击波s,CUSTOM:粒子s*10
mutator1_ifUnitWithoutTags: jabzhdja
mutator1_addResourcesDirectHit: sz=60
lightSize: 0.75

beamImage: ROOT:/太空浪人/单位特效/光束6.png
#color:#FFFF1200


[effect_爆炸]
life: 30
dirOffsetRandom: 180
priority: critical
fadeInTime: 1
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 1.5
image: ROOT:/太空浪人/单位特效/波雷爆炸.png
total_frames: 14

animateFrameStart: 0
animateFrameEnd: 13
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 2

alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
color: #FFFF1200


[effect_闪光]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 1.5
scaleTo: 1.5

drawUnderUnits: false
atmospheric: false


[effect_碎裂]
life: 40
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.4
image: ROOT:/太空浪人/单位特效/碎裂.png
total_frames: 8

animateFrameStart: 0
animateFrameEnd: 7
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 0.8


[effect_尾巴]
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFF1200
fadeInTime: 2
scaleFrom: 0.37
scaleTo: 0.37
alpha: 1

drawUnderUnits: true


[effect_弹壳右]
priority: high
image: 弹壳.png
spawnChance: 1
life: 360
fadeOut: true

attachedToUnit: false
scaleFrom: 0.6
scaleTo: 0.6
alpha: 2
fadeInTime: 5

drawUnderUnits: false
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false

xSpeedRelative: 1.2
xSpeedRelativeRandom: 0.3
ySpeedRelativeRandom: 0.25
yOffsetRelative: -40
xOffsetRelative: 3

hSpeed: 3
#dirSpeedRandom
dirOffsetRandom: 180


[effect_烟雾1]
priority: critical
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false

life: 70
fadeOut: true
attachedToUnit: false
#color:#FFE56BFF
#color: #FFFFFF

fadeInTime: 10
scaleFrom: 0.7
scaleTo: 2
alpha: 0.9
drawUnderUnits: false

liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6

yOffsetRelative: 0.8
ySpeedRelative: 1.5
atmospheric: true


[effect_粒子1]
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false

#color: #FFFFFF
fadeInTime: 10
image: ROOT:/太空浪人/单位特效/光束.png
scaleFrom: 0.4
scaleTo: 0.8

alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1

xSpeedRelativeRandom: 0.6
yOffsetRelative: 0.8
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
#xOffsetRelative:-2

atmospheric: true


[effect_爆炸1]
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.2

scaleTo: 1.2
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false

animateFrameSpeed: 0.35
alwayStartDirAtZero: true
#alsoPlaySound:ROOT:/通用特效/迫击炮爆炸.ogg
color: #FFFF1200


[effect_闪光1]
priority: critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FFFF1200
fadeInTime: 2
scaleFrom: 3
scaleTo: 3

drawUnderUnits: false
atmospheric: false


[effect_聚变]
priority: critical
image: ROOT:/太空浪人/单位特效/光束1.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.2
scaleTo: 1.2
alpha: 0.6
drawUnderUnits: true
atmospheric: false


[effect_冲击波]
priority: critical
image: ROOT:/太空浪人/单位特效/冲击波2.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 0.2
scaleTo: 1
alpha: 0.8
drawUnderUnits: false
atmospheric: true


[leg_1]
x: -17
y: 7
attach_x: -7
attach_y: 4
moveSpeed: 2.8

moveWarmUp: 0.1s
hidden: if self.hasParent()
rotateSpeed: 7
heightSpeed: 0.65
resetAngle: 25

image_leg: 腿.png
image_foot: 脚1.png
#draw_foot_on_top: true
dust_effect: false
holdDisMin: 5

holdDisMax: 20
estimatingPositionMultiplier: 0.8


[leg_2]
x: 17
y: 7
attach_x: 7
attach_y: 4
copyFrom: 1

hidden: if self.hasParent()
#—————————————————————


[effect_爆炸s]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1
scaleTo: 1.4

image: ROOT:/太空浪人/单位特效/小爆炸动态1.png
total_frames: 16
animateFrameStart: 0
animateFrameEnd: 16
animateFramePingPong: false

animateFrameSpeed: 0.27
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸1.ogg
alwayStartDirAtZero: true


[effect_闪光s]
#priority:critical
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF2C56FF
fadeInTime: 2
scaleFrom: 1.5
scaleTo: 1.5

drawUnderUnits: false
atmospheric: false


[effect_碎裂s]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.5
image: ROOT:/太空浪人/单位特效/衰解1.png
total_frames: 6

animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.25
#alsoPlaySound:ROOT:/余辉军团/单位特效/激光命中.ogg

alpha: 1.2
atmospheric: false


[effect_爆炸1s]
life: 100
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true

attachedToUnit: false
scaleFrom: 0.7
scaleTo: 0.7
image: ROOT:/太空浪人/单位特效/衰解.png
total_frames: 9

animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.35
alpha: 1

#color:#FFFF1200
alsoPlaySound: ROOT:/太空浪人/单位特效/激光炮音效.ogg


[effect_闪光1s]
#priority:critical
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 1

attachedToUnit: false
color: #FF2C56FF
fadeInTime: 2
scaleFrom: 4
scaleTo: 4

drawUnderUnits: false
atmospheric: false


[effect_粒子s]
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false

color: #FF2C56FF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.7
scaleTo: 0.7

alpha: 1
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 360
xSpeedRelativeRandom: 3.7

ySpeedRelativeRandom: 3.7
#atmospheric: true


[effect_聚变s]
priority: critical
image: ROOT:/太空浪人/单位特效/衰解闪光.png
life: 60
fadeOut: true
attachedToUnit: false

scaleFrom: 1.3
scaleTo: 1.3
alpha: 0.6
#drawUnderUnits:f
atmospheric: false

#drawUnderUnits:true


[effect_冲击波s]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FF2C56FF


[effect_尾巴s]
image: SHARED:light_50.png
life: 18
fadeOut: true
attachedToUnit: false
priority: low

color: #FF2C56FF
fadeInTime: 2
scaleFrom: 0.37
scaleTo: 0.37
alpha: 1

drawUnderUnits: true


[effect_光环h]
priority: critical
image: ROOT:/太空浪人/单位特效/吸血环.png
life: 40
fadeOut: true
attachedToUnit: false

scaleFrom: 0.75
scaleTo: 0.75
alpha: 0.9
drawUnderUnits: false
atmospheric: false

alwayStartDirAtZero: true
color: #FFFF1200


[effect_粒子h]
life: 60
image: ROOT:/太空浪人/单位特效/吸血.png
scaleFrom: 1.5
scaleTo: 0.1
alpha: 1

dirOffsetRandom: 360
dirSpeed: -2
dirSpeedRandom: 1.5


[effect_冲击波h]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.3
scaleTo: 0.85

image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false

animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
color: #FFFF1200


[movement]
moveSpeed: 1.1
moveAccelerationSpeed: 0.07
moveDecelerationSpeed: 0.07
moveSlidingMode : false
moveIgnoringBody: false

movementType: LAND
maxTurnSpeed: 1.8
turnAcceleration: 0.35
reverseSpeedPercentage: 0.1


