


[core]
name: 彻甲榴弹
displayText: 彻甲榴弹
displayDescription:【阶级t4】【地雷】\n-战术定位：复装式地雷，\n-爆炸伤害，被触发后冷却一段时间可以再次使用。只能对地。对建筑效率低。\n- 彻甲榴弹是针对余辉重型单位研发的新一代地雷，\n-采用了新颖的攻顶式设计以及自动装填能力。\n-其恐怖的威力连重型坦克都能轻易掀翻，\n-彻甲榴弹是创世纪联盟中最强大的地雷。
class: CustomUnitMetadata
price:1200
maxHp: 5

techLevel: 1
#availableInDemo: true
radius: 20
displayRadius: 20
buildSpeed: 18s
tags: 地雷
isBio: false
softCollisionOnAll: 100
energyMax: 4
energyRegen: 0.005
energyNeedsToRechargeToFull: true
dieOnZeroEnergy: false
fogOfWarSightRange: 5
selfBuildRate: 0.01
disableAllUnitCollisions: true
showOnMinimapToEnemies: false
canNotBeDamaged:true
isBuilding: true
canOnlyBeAttackedByUnitsWithTags:主动扫雷
[action_拆除]
displayType: action
iconImage: ROOT:/通用特效/关.png
text: 拆除
description: 拆除地雷
buildSpeed: 0s
highPriorityQueue: true
displayRemainingStockpile: false
deleteSelf: true


[hiddenAction_扫雷]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=50)  or numberOfUnitsInEnemyTeam(withTag='压制塔',greaterThan=0, withinRange=415)  or self.hasFlag(id=1)
deleteSelf: true
[action_显示]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',greaterThan= 0,withInRange=300) and not self.tags(includes= '显示')
isVisible:false
temporarilyAddTags:显示
[action_显示1]
autoTrigger: if numberOfUnitsInEnemyTeam(withTag='扫雷',lessThan=1,withInRange=300) and self.tags(includes= '显示')
isVisible:false
temporarilyRemoveTags:显示
[decal_光圈a]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈b]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈c]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:true
hOffset:8
onlyTeam:own
[decal_光圈]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈1]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈2]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_光圈3]
layer: afterBody
image: ROOT:/通用特效/警告光圈.png
onlyWhileAlive: true
imageScale:0.2
isVisible:if self.tags(includes= '显示')
hOffset:8
onlyTeam:enemy
[decal_地雷]
layer: afterBody
image: 地雷主体.png
onlyWhileAlive: true
imageScale:0.8
isVisible:true
onlyTeam:own
[decal_地雷1]
layer: afterBody
image: 地雷主体.png
onlyWhileAlive: true
imageScale:0.8
isVisible:if self.tags(includes= '显示')
onlyTeam:enemy

[graphics]
total_frames: 1
image: ROOT:/通用特效/NO.png
image_wreak: NONE
image_turret: NONE
image_shadow: NONE
dustEffect: false


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
dieOnAttack: false

canOnlyAttackUnitsWithoutTags: 扫雷,悬浮,建筑
turretSize: 10
turretTurnSpeed: 6
maxAttackRange: 355
shootDelay: 1

#aimOffsetSpread: 0.25


[turret_1]
x: 0
y: 0
invisible: true
projectile: 1
turnSpeed: 15
energyUsage:4
turnSpeedAcceleration: 15
canShoot: true
warmup: 300
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹x.ogg
shoot_sound_vol: 0.3
canOnlyAttackUnitsWithoutTags:扫雷,悬浮

[projectile_1]
life: 30
speed: 4
targetSpeed: 1
largeHitEffect: true
drawSize: 0.7
image: ROOT:/创世纪军事集团/单位特效/中导弹.png
trailEffect: true
directDamage: 0
ballistic: true
ballistic_height: 125
ballistic_delaymove_height: 85
spawnProjectilesOnEndOfLife: 锁定
explodeOnEndOfLife: true
explodeEffect: CUSTOM:导弹碎片*2

[projectile_锁定]
@copyFromSection: template_爆炸
areaDamage: 5000
areaRadius: 70
life: 200
speed: 7
targetSpeed: 12
frame: 9
drawSize: 0.8
explodeEffect: CUSTOM:爆炸,CUSTOM:气浪,CUSTOM:冲击波2,CUSTOM:闪光*2,CUSTOM:弹坑
explodeEffectOnShield:  CUSTOM:爆炸,CUSTOM:气浪,CUSTOM:冲击波2,CUSTOM:闪光*2,CUSTOM:弹坑
targetGround: true
areaRadiusFromEdge: true
lightSize: 1.5
lightColor: #FFFFFF73
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴
disableLeadTargeting: true
buildingDamageMultiplier: 0.1
[effect_尾巴]
image: SHARED:light_50.png
life: 30
fadeOut: true
attachedToUnit: false
priority: low

color: #FFFF5B18
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.5
alpha: 1

drawUnderUnits: true
[effect_导弹碎片]
#priority: low
image: 导弹碎片.png
spawnChance: 1
life: 130
fadeOut: true
attachedToUnit: false
scaleFrom: 0.8
scaleTo: 0.8
alpha: 2
fadeInTime: 5
drawUnderUnits: true
liveAfterAttachedDies: false
physics: true
physicsGravity: 2
createWhenZoomedOut: false
xSpeedRelativeRandom: 1.5
ySpeedRelativeRandom: 0.4
hSpeed: 2
dirSpeedRandom: 50
[effect_弹坑]
image: ROOT:/通用特效/弹坑.png
spawnChance: 0.7
life: 360
attachedToUnit: false
drawUnderUnits: true
scaleFrom: 2.5
scaleTo: 2.5
createWhenOverLiquid: false
createWhenOverLand: true
createWhenOffscreen: true

[effect_气浪]
life: 90
fadeInTime: 2
fadeOut: true
attachedToUnit: false
scaleFrom: 1.8
scaleTo: 6
image: ROOT:/太空浪人/单位特效/气浪.png
drawUnderUnits: true
alpha: 1.2
createWhenOffscreen: true

[effect_闪光]
image: SHARED:light_50.png
life: 160
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 4
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true

[effect_冲击波2]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.15
scaleTo: 3
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.18
alwayStartDirAtZero: true
drawUnderUnits: true
createWhenOffscreen: true

[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.8
scaleTo: 4
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/大爆炸1.ogg
createWhenOffscreen: true



[movement]
movementType: LAND
moveSpeed: 0.0
moveAccelerationSpeed: 0
moveDecelerationSpeed: 0.12
maxTurnSpeed: 0

turnAcceleration: 0.75
targetHeight: -8
targetHeightDrift: 0
moveSlidingMode : true
moveIgnoringBody: true


[ai]
buildPriority: 0.12
noneInBaseExtraPriority: 0.12
noneGlobalExtraPriority: 0.1
maxEachBase: 10


