


[core]
name: 猛禽战斗机
displayDescription: 【阶级t4】【机械单位】【空中单位】【高空单位】【长距离索敌】【雷达隐形】\n-战术定位:空优战斗机，武器配置：▲空对空导弹X2 对空对高空 爆炸伤害 \n-▲长距离索敌空对空导弹X2 只能攻击被锁定的高空单位 爆炸伤害\n-猛禽战机在战前便是人类最先进制空战机的代言人，\n-可以有效减少反射面的外形与隐形涂层使她一度成为黑暗中的隐形杀手，\n-战争开始后幸存下来的F22被统一改造成黑色猛禽战机，\n-这种只少量配发给精锐部队的战斗机具有无与伦比的机动性和火力，\n-比起创世纪其他空优战机，猛禽飞得更高更快，载荷量更大，尤其是对余晖战舰更为致命，\n-其挂载的新型空对空导弹可以有效毁伤帝国余辉的部分战舰。
showOnMinimapToEnemies: false
price: 4800
maxHp: 6000
armour: 16
techLevel: 1
buildSpeed: 17s
availableInDemo: true
radius: 43
displayRadius: 43
isBio: false
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/扎针1.md
softCollisionOnAll: 10
fogOfWarSightRange: 35
tags: 飞机,高空,反高空
transportSlotsNeeded: 1
effectOnDeathGroundCollision: CUSTOM:爆炸*1
canOnlyBeAttackedByUnitsWithTags:反高空
[action_聚变弹头3]
displayType: infoOnlyNoBox
iconImage: ROOT:/创世纪军事集团/单位特效/聚变3.png
text: 聚变弹头3
isActive: false
isVisible: if self.globalTeamTags(includes='聚变弹头3')
[action_高空]
text: 高空单位
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/高空.png
description: 处于极高高度的战机。\n-在此高度下，只有地面和空中特殊的反高空单位，以及高空单位才能攻击到该单位，\n-同时，大部分高空单位可以互相攻击，并可以攻击普通空中单位，\n-只有特殊的高空单位才能对地攻击。
[action_长距离]
text: 长距离索敌
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.1
iconImage: ROOT:/通用特效/长距离.png
description: 该单位有能力射击极远距离上的被锁定单位。\n-允许猛禽战机在攻击 高空单位 中的 被锁定 敌方单位时，\n-将射程提升至1275。

[graphics]
total_frames: 1
image:机体.png
image_wreak: 死亡.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
imageScale: 0.85
movementEffectRate: 0.4
movementEffect: CUSTOM:火1,CUSTOM:火2, CUSTOM:火3,CUSTOM:火4
[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 20
aimOffsetSpread: -0.01
turretTurnSpeed: 10000
maxAttackRange: 1275
[turret_1]
invisible: true
x: 39
y: -8
idleDir: 0
projectile: 1
size: 1.1
turnSpeed: 0
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹发射音效.ogg
shoot_sound_vol: 0.5
delay: 180
canAttackMaxAngle: 181
canOnlyAttackUnitsWithTags:被锁定
limitingMinRange: 750
canOnlyAttackUnitsWithoutTags:低空
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
[turret_2]
x: -39
y: -8
copyFrom: 1
warmup:60
[turret_3]
invisible: true
x: -39
y: -8
idleDir: 0
projectile: 2
size: 1.1
turnSpeed: 0
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹发射音效.ogg
shoot_sound_vol: 0.5
delay: 180
canAttackMaxAngle: 181
canOnlyAttackUnitsWithoutTags:高空
limitingRange:750
altProjectile: 炮弹1
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
[turret_4]
x: 39
y: -8
copyFrom: 3
warmup:60
[turret_5]
invisible: true
x: -39
y: -8
idleDir: 0
projectile: 1
size: 1.1
turnSpeed: 0
shoot_sound: ROOT:/创世纪军事集团/单位特效/导弹发射音效.ogg
shoot_sound_vol: 0.5
delay: 180
canAttackMaxAngle: 181
canAttackCondition: if self.tags(includes= '高空')
canOnlyAttackUnitsWithTags:高空
limitingRange:750
altProjectile: 炮弹
altProjectileCondition: if self.globalTeamTags(includes='聚变弹头3')
[turret_6]
x: 39
y: -8
copyFrom: 5
warmup:60
delay:120
[projectile_1]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.9
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
areaDamage: 900
areaRadius: 45
explodeEffect: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
deflectionPower: -1
autoTargetingOnDeadTarget: true
turnSpeed: 3.5
trailEffectRate: 0.8
areaRadiusFromEdge: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_炮弹]
@copyFromSection: template_能源
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.9
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
areaDamage: 1250
areaRadius: 70
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
deflectionPower: -1
autoTargetingOnDeadTarget: true
turnSpeed: 3.5
trailEffectRate: 0.8
areaRadiusFromEdge: true
mutator8_ifUnitWithoutTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
[projectile_2]
@copyFromSection: template_爆炸
life: 40
speed: 0
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
areaDamage: 900
areaRadius: 45
explodeEffect: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
spawnProjectilesOnEndOfLife:4
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
drawUnderUnits:true
[projectile_炮弹1]
@copyFromSection: template_能源
life: 40
speed: 0
targetSpeed: 0
largeHitEffect: true
drawSize: 0.9
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
areaDamage: 1250
areaRadius: 70
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
spawnProjectilesOnEndOfLife:炮弹2
deflectionPower: -1
turnSpeed: 0
areaRadiusFromEdge: true
trueGravity: 0.1
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
drawUnderUnits:true
[projectile_4]
@copyFromSection: template_爆炸
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.9
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
areaDamage: 900
areaRadius: 45
explodeEffect: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
explodeEffectOnShield: CUSTOM:冲击波,CUSTOM:爆炸, CUSTOM:闪光,CUSTOM:钢珠
deflectionPower: -1
autoTargetingOnDeadTarget: true
turnSpeed: 3.5
areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
trailEffectRate: 0.8
[projectile_炮弹2]
@copyFromSection: template_能源
life: 300
speed: 6
targetSpeed: 9
largeHitEffect: true
drawSize: 0.9
image: ROOT:/创世纪军事集团/单位特效/大导弹.png
trailEffect: true
areaDamage: 1250
areaRadius: 70
explodeEffect: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
explodeEffectOnShield: CUSTOM:底色jb,CUSTOM:聚变jb,CUSTOM:闪光jb,CUSTOM:冲击波jb,CUSTOM:实验jb,CUSTOM:冲击波
deflectionPower: -1
autoTargetingOnDeadTarget: true
turnSpeed: 3.5
areaRadiusFromEdge: true
mutator8_ifUnitWithTags:高空
mutator8_directDamageMultiplier: 0
mutator8_areaDamageMultiplier: 0
trailEffectRate: 0.8
[effect_闪光]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 1
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 3.5
scaleTo: 3.5
drawUnderUnits: false
atmospheric: false


[effect_爆炸]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 1.3
scaleTo: 2.2
image: ROOT:/创世纪军事集团/单位特效/爆炸251.png
total_frames: 26
animateFrameStart: 0
animateFrameEnd: 25
animateFramePingPong: false
animateFrameSpeed: 0.35
alwayStartDirAtZero: true
alsoPlaySound: ROOT:/通用特效/迫击炮爆炸.ogg


[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.5
scaleTo: 2
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2


[effect_冲击波]
life: 100
priority:veryhigh
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.8
image: ROOT:/通用特效/冲击波.png
total_frames: 10
animateFrameStart: 0
animateFrameEnd: 9
animateFramePingPong: false
animateFrameSpeed: 0.22
alwayStartDirAtZero: true
alpha: 0.8
[effect_火1]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: -5
ySpeedRelative: -2
yOffsetRelative	: -47
drawUnderUnits: true
[effect_火2]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: -5
#ySpeedRelative: -0.2
yOffsetRelative	: -52
#drawUnderUnits: true
[effect_火3]
life: 15
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.1
image: SHARED:light_50.png
alpha: 0.5
color: #FFFFA920
xOffsetRelative	: 5
ySpeedRelative: -2
yOffsetRelative	: -47
drawUnderUnits: true
[effect_火4]
life: 10
fadeInTime: 1
fadeOut: true
attachedToUnit: false
scaleFrom: 0.13
scaleTo: 0.02
image: SHARED:light_50.png
alpha: 1
color: #FFFFFFFF
xOffsetRelative	: 5
yOffsetRelative	: -52
#drawUnderUnits: true
#——————————聚变

[effect_底色jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/收缩2.png
life: 80
fadeOut: true
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.4
alpha: 1.3
drawUnderUnits: false
atmospheric: false
alsoPlaySound: ROOT:/太空浪人/单位特效/爆炸.ogg
[effect_聚变jb]
priority: veryhigh
image: ROOT:/创世纪军事集团/单位特效/聚变.png
life: 35
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 1
alpha: 0.5
drawUnderUnits: false
atmospheric: false
[effect_闪光jb]
image: SHARED:light_50.png
life: 20
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 6
scaleTo: 0
drawUnderUnits: false
atmospheric: false
[effect_冲击波jb]
priority: critical
image: ROOT:/创世纪军事集团/单位特效/冲击波2.png
life: 30
fadeOut: true
attachedToUnit: false
scaleFrom: 0.05
scaleTo: 1.1
alpha: 0.8
drawUnderUnits: false
atmospheric: false
[effect_实验jb]
image:SHARED:ripple_normal_128.png
drawType: displacement
color:#FF00B3FF
life:10
fadeOut: true
attachedToUnit: false
createWhenOffscreen: true
scaleFrom:0.1
scaleTo:1.5
alpha: 1
fadeInTime: 4
drawUnderUnits:false
createWhenZoomedOut: false
[arm_1]
x: 0
y: 0
image_end: 损坏.png
image_end_teamColors: true
drawOverBody: true
hidden: if self.maxHp * 0.36 < self.hp

[arm_2]
x: 0
y: -46
image_end: 尾巴.png
image_end_teamColors: true
drawOverBody: true
hidden: if not self.isMoving()
[arm_3]
x: 0
y: 22
image_end: 风扇.png
image_end_teamColors: true
drawOverBody: true
spinRate: 18
[arm_4]
x: 0
y: 8
image_end: 盖子.png
image_end_teamColors: true
drawOverBody: true

[animation_move]
onActions: move
blendIn: 0.5s
blendOut: 0.5s
arm4_0s: {x:0, y:0}
arm4_1s: {x:0, y:10}
arm4_999s: {x:0, y:0}
[movement]
movementType: AIR
moveSpeed: 3.9
moveAccelerationSpeed: 0.1
moveDecelerationSpeed: 0.04
joinsGroupFormations: false

maxTurnSpeed: 3
turnAcceleration: 0.08
moveSlidingMode : false
moveIgnoringBody: false
slowDeathFall: true

targetHeight: 140


[ai]
buildPriority: 0.085


