
[resource_1]
displayName: 1
displayNameShort: 1
displayColor: #FF9D00FF
priority: 1
hidden: true

[resource_电磁]
displayName: 电磁
displayNameShort: 电磁
displayColor: #FF9D00FF
priority: 1
hidden: true
[hiddenAction_寄生b]
autoTriggerOnEvent: destroyed
addResources: 威胁点数=${core.price / 50}
[core]
name: 圣裁战锤
class: CustomUnitMetadata
price: 5000
maxHp: 8000
maxShield: 8000
shieldRenderRadius: 1
shieldRegen: 0.07
displayDescription: 【阶级t4】【无人单位】【机械单位】【地面单位】【长距离索敌】\n-战术定位:泛用型重坦克，单位体积：7，武器配置：\n-▲转轮等离子炮 X1 对地对空 能源伤害 ▲等离子炮 X2 只能对地 能源伤害\n-▲蝗虫SRM X2 只能对空 爆炸伤害\n-▲长距离索敌SRM X2 对地对空对高空 只能攻击被锁定的敌人 爆炸伤害\n-诺瓦帝国军的空降序列中缺乏一辆全地形重型坦克，\n-在这样的现实问题下，泽塔诺亚公司开发出了圣裁战锤，\n-圣裁战锤自设计之初，目的就是克服最糟糕的地形以及抵挡最多的伤害，\n-厚重的装甲和护盾又能使在重火力的攻击下屹立不倒，\n-在拥有这些可贵品质的同时，圣裁战锤还拥有丰富且致命的武装。\n-无论面对多么恶劣的环境，无论面对多么凶猛的炮火，\n-圣裁战锤总是能成为空降部队最坚实的排头兵，为后续部队提供最高效的掩护。
effectOnDeath:CUSTOM:小型余晖死亡冲击波,CUSTOM:小型余晖死亡爆炸,CUSTOM:小型余晖死亡钢珠,CUSTOM:小型余晖死亡闪光
unitsSpawnedOnDeath: 损毁2(offsetHeight=0,offsetDir=0,addResources=电磁:1)
fogOfWarSightRange: 40
techLevel: 1
buildSpeed: 17s
radius: 65
displayRadius: 65
isBio: false
transportSlotsNeeded:7
softCollisionOnAll: 10
armour: 55

tags: 地面,无人单位,反高空,免疫烟雾
copyFrom: ROOT:/通用特效/单位防护.ini,ROOT:/通用特效/爆炸素材库.md
energyMax: 8
energyRegen: 0.025
energyNeedsToRechargeToFull: true

[action_长距离]
text: 长距离索敌
isVisible: true
isLocked: true
price: 0
displayType: infoOnlyNoBox
buildSpeed: 0s
pos: 0.15
iconImage: ROOT:/通用特效/长距离.png
description: 该单位有能力射击极远距离上的被锁定单位。\n-允许圣裁战锤在攻击 地面，空中，高空单位 中的 被锁定 敌方单位时，\n-使用1100射程的长距离索敌SRM攻击敌人

[hiddenAction_↯a]
autoTrigger: if self.resource.xk > 0 and not self.tags(includes= '↯')
alsoQueueAction: ↯b
isActive: false
temporarilyAddTags: ↯


[hiddenAction_↯b]
buildSpeed: 3.5s
whenBuilding_cannotMove: true
isActive: false
highPriorityQueue: true
temporarilyRemoveTags: ↯

setResourcesWithLogic: xk= select(self.resource.xk > 7, 1, 0)
[decal_影子]
image: SHADOW:影子.png
total_frames: 1
layer: shadow
isVisible:true
yOffsetRelative:5
xOffsetRelative:5
onlyWhileAlive:true
alpha:0.5
[decal_小炮影子]
image:SHADOW:小炮.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 1
alpha:0.5
[decal_小炮影子1]
image:SHADOW:小炮.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:2
xOffsetRelative:3
onlyWhileAlive:true
basePositionFromTurret: 3
alpha:0.5
[decal_炮影子]
image:SHADOW:炮塔.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:4
xOffsetRelative:4
onlyWhileAlive:true
basePositionFromTurret: 5
alpha:0.65
[decal_炮影子1]
image:SHADOW:加特林1.png
total_frames: 1
layer: afterBody
isVisible:true
yOffsetRelative:4
xOffsetRelative:4
onlyWhileAlive:true
basePositionFromTurret: 6
alpha:0.65
#————————————履带动画
[decal_履带]
image: 履带.png
total_frames: 4
frame: (self.customTimer * 22) % 4
# 8为图片帧数，17改速度，1/17s下一帧
layer: beforeBody
isVisible:if self.isMoving
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
[decal_履带1]
image: 静止.png
total_frames: 1
layer: beforeBody
isVisible:if not self.isMoving
onlyWhileAlive:true
#————————————炮管动画
[decal_损坏]
image: 底盘损坏.png
total_frames: 1
layer: afterBody
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
alpha:1
[decal_机体灯]
image:灯.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.8
[decal_炮塔动画]
image: 加特林.png
total_frames: 6
frame: (self.customTimer * 30) % 6
basePositionFromTurret: 6
isVisible:if self.isAttacking() and numberOfUnitsInEnemyTeam(greaterThan=0,withInRange=550, incompleteBuildings= true)
onlyWhileAlive:true
layer: onTop
yOffsetRelative:0
xOffsetRelative:-0.5
[decal_红热]
image:红温.png
total_frames: 1
xOffsetRelative:-0.5
yOffsetRelative:0
isVisible:true
layer: onTop
alpha:(self.resource.1)/50
onlyWhileAlive:true
basePositionFromTurret: 6
[decal_红热1]
image:红温.png
total_frames: 1
xOffsetRelative:-0.5
yOffsetRelative:0
isVisible:true
layer: onTop
alpha:(self.resource.1)/50
onlyWhileAlive:true
basePositionFromTurret: 6
[decal_红热2]
image:红温.png
total_frames: 1
xOffsetRelative:-0.5
yOffsetRelative:0
isVisible:true
layer: onTop
alpha:(self.resource.1)/50
onlyWhileAlive:true
basePositionFromTurret: 6
[decal_脑袋]
image: 炮塔.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
basePositionFromTurret: 5
[decal_炮塔损坏]
image: 炮塔损坏.png
total_frames: 1
layer: onTop
yOffsetRelative:0.5
xOffsetRelative:-0.5
onlyWhileAlive:true
teamColors: true
isVisible: if self.hp < self.maxHp * 0.36
basePositionFromTurret: 5
alpha:1
[decal_射线]
image:射线.png
total_frames: 1
layer: onTop
isVisible:true
yOffsetRelative:77
xOffsetRelative:13.2
onlyWhileAlive:true
basePositionFromTurret: 5
[decal_机体灯1]
image:灯1.png
total_frames: 1
layer: onTop
isVisible:if self.maxHp * 0.36 < self.hp
yOffsetRelative:0
xOffsetRelative:0
onlyWhileAlive:true
alpha:0.8
basePositionFromTurret: 5

[decal_护盾]
image: ROOT:/余辉军团/单位特效/通用护盾.png
total_frames: 1
layer: onTop
isVisible:if self.shield>self.maxShield*0.03 and not self.tags(includes= '克莱因')
yOffsetRelative:10
xOffsetRelative:0
alpha: max( 0, sin( self.shield * 90 / self.maxShield ) - ( 5 *  self.hasTakenDamage ))
onlyWhileAlive:true
imageScale: 1.1

[hiddenAction_丢弃]
autoTrigger:if self.resource.1>60
setResourcesWithLogic:1=60
[hiddenAction_DPS]
addResources: 1=1
[hiddenAction_DPS1]
autoTrigger: if not self.isAttacking() and numberOfUnitsInEnemyTeam(lessThan=1,withInRange=550, incompleteBuildings= true)
isVisible: false
addResources: 1=-3
[graphics]
total_frames: 1
image: 底盘.png
image_wreak: 死亡.png
image_turret: NONE
teamColorsOnTurret: true

image_shadow: NONE
movementEffect: CUSTOM:烟1,CUSTOM:烟2
movementEffectRate: 20
showQueueBar: false
showEnergyBar: false
showShotDelayBar:false

[attack]
canAttack: true
canAttackFlyingUnits:true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
disablePassiveTargeting: false

turretMultiTargeting: true
turretSize: 22
turretTurnSpeed: 1.4
maxAttackRange: 1100
[turret_1]
x: -58
y: -6
canShoot: false
image: 小炮.png
idleDir:-40
canAttackCondition: if self.resource.xk < 1
turnSpeed: 3
turnSpeedAcceleration: 4
canAttackFlyingUnits:false
canOnlyAttackUnitsWithoutTags:高空
limitingAngle: 70
limitingRange: 510
[turret_2]
x: 0
y: 5
shoot_sound: ROOT:/余辉军团/单位特效/等离子.wav
shoot_sound_vol: 0.5
shoot_light: #FF00B3FF
shoot_flame: CUSTOM:烟雾*3
invisible: true
delay: 100
projectile: 1
size: 17
chargeEffectImage: ROOT:/余辉军团/单位特效/蓄能.png
warmup:20
canAttackCondition: if self.resource.xk < 1
attachedTo: 1
slave: true
canAttackFlyingUnits:false
canOnlyAttackUnitsWithoutTags:高空
limitingRange: 510
[turret_3]
x: 58
y: -6
copyFrom: 1
idleDir:40
[turret_4]
x: 0
y: 5
copyFrom: 2
attachedTo: 3
slave: true
linkDelayWithTurret:2

[turret_5]
x: 0
y: -8
#炮塔
turnSpeed: 1.3
turnSpeedAcceleration: 0.75
canShoot: false
canAttackFlyingUnits: true
canAttackLandUnits: true
idleSweepAngle: 10
idleSweepDelay: 400
idleSweepSpeed: 0.1
canAttackCondition: if self.resource.xk < 1
image:炮塔.png
limitingRange: 510
[turret_6]
x: 0
y: 66
#主炮
projectile: 2
shoot_sound: ROOT:/太空浪人/单位特效/音效.ogg
shoot_sound_vol: 0.4
shoot_flame: CUSTOM:烟雾1*3,CUSTOM:粒子*2
shoot_light: #FF00B3FF
canShoot: true
delay: 18
canAttackCondition: if self.resource.xk < 1
attachedTo: 5
slave: true
size: 50
canOnlyAttackUnitsWithoutTags:高空
image:加特林1.png
onShoot_triggerActions: DPS
limitingRange: 510
[turret_7]
x: -19
y: -35
attachedTo: 5
slave: true
projectile: 3
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FFEECCCC
canShoot: true
size: 0
shoot_flame: CUSTOM:烟雾
energyUsage: 0.4
invisible: true
delay:8
canAttackLandUnits: false
canAttackCondition: if self.resource.xk < 1 and self.energy>4
canOnlyAttackUnitsWithoutTags:高空
limitingRange: 510
[turret_8]
x: -10
y: -35
copyFrom: 7
delay:5
linkDelayWithTurret:7
warmup:3

[turret_9]
x: 19
y: -35
copyFrom: 7
canAttackCondition: if self.resource.xk < 1 and self.energy<4.5
[turret_10]
x: 10
y: -35
copyFrom: 7
delay:5
linkDelayWithTurret:9
warmup:3
canAttackCondition: if self.resource.xk < 1 and self.energy<4.5

[turret_11]
x: -19
y: -35
attachedTo: 5

projectile: 4
shoot_sound: ROOT:/创世纪军事集团/单位特效/小轨道炮.ogg
shoot_sound_vol: 0.3
shoot_light: #FFEECCCC
canShoot: true
size: 0
shoot_flame: CUSTOM:烟雾
energyUsage: 0.4
invisible: true
delay:8
canAttackCondition: if self.resource.xk < 1 and self.energy>4
canOnlyAttackUnitsWithTags:被锁定
canAttackMaxAngle: 181
canAttackFlyingUnits:true
canAttackLandUnits: true
idleDir:0
turnSpeed: 0
[turret_12]
x: -10
y: -35
copyFrom: 11
delay:5
linkDelayWithTurret:11
warmup:3
[turret_13]
x: 19
y: -35
copyFrom: 11
canAttackCondition: if self.resource.xk < 1 and self.energy<4.5
[turret_14]
x: 10
y: -35
copyFrom: 11
delay:5
linkDelayWithTurret:9
warmup:3
canAttackCondition: if self.resource.xk < 1 and self.energy<4.5

[projectile_1]
@copyFromSection: template_能源
#主炮子弹
directDamage: 400
life: 60
speed: 14
lightSize: 1.5
image:ROOT:/余辉军团/单位特效/炮弹x.png
lightColor: #FF00B3FF
drawSize: 0.55
explodeEffectOnShield:CUSTOM:小等离子冲击波,CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
explodeEffect: CUSTOM:小等离子冲击波,CUSTOM:小等离子爆炸1,CUSTOM:小等离子爆炸1,CUSTOM:小等离子闪光
trailEffectRate: 0.8
trailEffect: CUSTOM:尾巴

[projectile_2]
@copyFromSection: template_能源
#普通炮弹
directDamage: 350
life: 5000
speed: 10
lightSize: 1.5
image:ROOT:/余辉军团/单位特效/小闪光.png
lightColor: #FF00B3FF
drawSize: 0.9
targetSpeed: 15
explodeEffect: CUSTOM:冲击波zp, CUSTOM:爆炸zp,CUSTOM:爆炸zp1,CUSTOM:闪光zp
explodeEffectOnShield: CUSTOM:冲击波zp, CUSTOM:爆炸zp,CUSTOM:爆炸zp1,CUSTOM:闪光zp
trailEffectRate: 0.4
trailEffect: CUSTOM:尾巴1


[projectile_3]
@copyFromSection: template_爆炸
life: 420
speed: 3
targetSpeed: 9
drawSize: 1
lightSize: 1
lightColor: #FF00B3FF
trailEffect: false
directDamage: 220
speedSpread:1
image: ROOT:/余辉军团/单位特效/导弹头.png
explodeEffect: CUSTOM:小爆炸,CUSTOM:钢珠,CUSTOM:小等离子闪光
explodeEffectOnShield:CUSTOM:小爆炸,CUSTOM:钢珠,CUSTOM:小等离子闪光
autoTargetingOnDeadTarget: true
autoTargetingOnDeadTargetRange:100

[projectile_4]
@copyFromSection: template_爆炸
life: 40
speed: 3
targetSpeed: 9
drawSize: 1
lightSize: 1
lightColor: #FF00B3FF
trailEffect: false
directDamage: 330
speedSpread:1
image: ROOT:/余辉军团/单位特效/导弹头.png
explodeEffect: CUSTOM:小爆炸,CUSTOM:钢珠,CUSTOM:小等离子闪光
explodeEffectOnShield:CUSTOM:小爆炸,CUSTOM:钢珠,CUSTOM:小等离子闪光
autoTargetingOnDeadTarget: true
autoTargetingOnDeadTargetRange:100
turnSpeed: 0
spawnProjectilesOnEndOfLife: 5
armourIgnoreAmount: 15
[projectile_5]
@copyFromSection:projectile_4
life: 1200
turnSpeed: 4.5
wobbleAmplitude: 4
wobbleFrequency: 100
speed: 11
spawnProjectilesOnEndOfLife: NONE
#————————————小炮
[effect_尾巴]
priority: low
image: ROOT:/余辉军团/单位特效/光束3.png
life: 17
fadeOut: true
attachedToUnit: false
fadeInTime: 0.1
scaleFrom: 0.4
scaleTo: 0.4
alpha: 0.7
drawUnderUnits: false
yOffsetRelative: 5
[effect_烟雾]
priority: veryhigh
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 0.5
scaleTo: 1.7
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.4
xSpeedRelativeRandom: 0.3
ySpeedRelative: 0.8
atmospheric: true
#————————————履带印
[effect_烟1]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative: 24
yOffsetRelative: -58


[effect_烟2]
life: 100
priority: high
fadeInTime: 1
fadeOut: true
attachedToUnit: false

scaleFrom: 0.3
scaleTo: 0.3
image: ROOT:/通用特效/履带.png
alpha: 0.65
drawUnderUnits: true

xOffsetRelative: -24
yOffsetRelative: -58
#————————————主炮开火
[effect_尾巴1]
image: SHARED:light_50.png
life: 25
fadeOut: true
attachedToUnit: false
priority: verylow
color: #FF00B3FF
fadeInTime: 2
scaleFrom: 0.5
scaleTo: 0.2
alpha: 0.8
drawUnderUnits: false
[effect_烟雾1]
priority: low
frameIndex: 0
stripIndex: effects
spawnChance: 1
createWhenZoomedOut: false
life: 70
fadeOut: true
attachedToUnit: false
fadeInTime: 10
scaleFrom: 1.5
scaleTo: 2.5
alpha: 0.9
drawUnderUnits: false
liveAfterAttachedDies: false
hSpeed: 0.01
dirOffsetRandom: 180
ySpeedRelativeRandom: 0.8
xSpeedRelativeRandom: 0.6
ySpeedRelative: 0.8
atmospheric: true


[effect_粒子]
priority: low
spawnChance: 1
createWhenZoomedOut: false
life: 50
fadeOut: true
attachedToUnit: false
#color: #FFFFFF
fadeInTime: 10
image: ROOT:/余辉军团/单位特效/蓄能.png
scaleFrom: 0.6
scaleTo: 0.7
alpha: 0.8
drawUnderUnits: false
liveAfterAttachedDies: false
dirOffsetRandom: 10
ySpeedRelativeRandom: 1
xSpeedRelativeRandom: 1.1
ySpeedAbsoluteRandom: 2
ySpeedRelative: 2
atmospheric: true
#————————主炮爆炸

[effect_爆炸zp]
life: 70
dirOffsetRandom: 180
priority: veryhigh

fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 0.55
scaleTo: 0.55
image: ROOT:/余辉军团/单位特效/爆.png
total_frames: 6
animateFrameStart: 0
animateFrameEnd: 5
animateFramePingPong: false
animateFrameSpeed: 0.4
alpha: 0.9

[effect_爆炸zp1]
life: 100
priority: critical
attachedToUnit: false
scaleFrom: 0.4
scaleTo: 0.65
image: ROOT:/余辉军团/单位特效/炸裂.png
total_frames: 9
animateFrameStart: 0
animateFrameEnd: 8
animateFramePingPong: false
animateFrameSpeed: 0.28
alpha:0.8
alsoPlaySound: ROOT:/余辉军团/单位特效/波雷爆炸.ogg
[effect_闪光zp]
image: SHARED:light_50.png
life: 35
fadeOut: true
alpha: 2
attachedToUnit: false
color: #BBBBFFEE
fadeInTime: 2
scaleFrom: 4
scaleTo: 0
drawUnderUnits: false
atmospheric: false
createWhenOffscreen: true
[effect_冲击波zp]
stripIndex: shockwave
life: 20
scaleFrom: 0.4
scaleTo: 1.6
alpha: 0.9
color: #FF00B3FF
#————————————导弹爆炸
[effect_钢珠]
life: 60
dirOffsetRandom: 180
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1.2
scaleTo: 1.7
image: ROOT:/创世纪军事集团/单位特效/钢珠.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.3
alpha: 1.2
[effect_小爆炸]
life: 90
dirOffsetRandom: 180
priority: critical
fadeInTime: 3
fadeOut: true
attachedToUnit: false
scaleFrom: 1
scaleTo: 2.5
image: ROOT:/余辉军团/单位特效/爆炸特效.png
total_frames: 7
animateFrameStart: 0
animateFrameEnd: 6
animateFramePingPong: false
animateFrameSpeed: 0.4
alsoPlaySound: ROOT:/创世纪军事集团/单位特效/迫击炮爆炸.ogg
alpha: 1.2
[movement]
movementType: LAND
moveSpeed: 0.85
moveAccelerationSpeed: 0.05
moveDecelerationSpeed: 0.1
maxTurnSpeed: 0.8

turnAcceleration: 0.1
moveSlidingMode : false
moveIgnoringBody: false


